### ISSUE TITLE
Show connected containers in network view

### ISSUE THREAD

**Issue by stuartthomson** [microsoft/vscode-docker#1002]
I would like to be able to see which containers are connected to a docker network. This would allow me to quickly see that for example my docker-compose file created the network I imagined it would and correctly attached the containers. It also would allow me to quickly know which containers I should be able to see when inside an interactive prompt of a container. Preferably I would also be able to use this view to interact with the containers including disconnecting them from the network. 

I often find myself having to do a `docker network inspect NETWORK_NAME` to find this information, and would prefer to always have it visible.

**Comment by 1138-4EB** [comment]
@stuartthomson meanwhile, you might find https://github.com/portainer/portainer/ useful.

**Comment by EricJizbaMSFT** [comment]
@stuartthomson the settings stuff is merged in master. You're welcome to take a stab at adding containers, but take a look at the "Group By" setting for both the containers view and networks view first (There should be a gear icon for each view). I'm curious if we could group containers by network in the _containers_ view which sounds simpler than adding containers to the networks view.

As an aside, feel free to take a look at the settings for the network view and add any more you think are useful or let me know if you think we should change the defaults

**Comment by stuartthomson** [comment]
@EricJizbaMSFT I'll take a look  at this, thanks for the heads up!

**Comment by bwateratmsft** [comment]
Related to #2592

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
