### ISSUE TITLE
Missing/incorrectly labeled images

### ISSUE THREAD

**Issue by 1138-4EB** [microsoft/vscode-docker#1003]
I found that some images are either missing or incorrectly labeled:

- Images labeled as `name/<none>` are shown as `<none>/<none>`. I have three images with this kind of labels: `alpine:<none>`, `golang:<none>`, `portainer/portainer:<none>`. In the VSC extension, all of them are grouped under `<none>`. In order to tell them apart, I need to 'Inspect' them.

- There is a single image which is unlabeled (it is shown as `REPOSITORY <none>, TAG <none>` by `docker images`). Yet, this is not shown by the VSC extension at all.

Therefore, I think there might be some bug when handling `<none>`, either in the REPOSITORY (not shown) or in the TAG (wrongly applied to the REPOSITORY field too).

**Comment by EricJizbaMSFT** [comment]
> Images labeled as name/\<none\> are shown as \<none\>/\<none\>

This is a known issue. See https://github.com/microsoft/vscode-docker/issues/209. But that issue is pretty old and I don't know all the backstory. @1138-4EB how can I get an image like `name/<none>` so that I can test this?

> There is a single image which is unlabeled (it is shown as REPOSITORY <none>, TAG <none> by docker images). Yet, this is not shown by the VSC extension at all.

This was an intentional choice to filter out all dangling images, but we could add a setting if you want to see those. See https://github.com/microsoft/vscode-docker/issues/169

**Comment by 1138-4EB** [comment]
> This is a known issue. See #209. But that issue is pretty old and I don't know all the backstory. @1138-4EB how can I get an image like `name/<none>` so that I can test this?

I think I've been able to consistently reproduce this in the past. However, I would say that previous versions did not show `<none>`, it was just empty. I'll check my notes.

> This was an intentional choice to filter out all dangling images, but we could add a setting if you want to see those. See #169

With the new 2.0 layout, I think it might be sensible to add an (optional) 'Prune' o 'Dangling' header. It could contain a tree with up to three parents: images, volumes, networks. The 'Prune' command would be moved there. I believe this would be a good balance between clean interface for new users and detailed quick-access for advanced users.

Should I comment about it in #169?

**Comment by 1138-4EB** [comment]
> > This is a known issue. See #209. But that issue is pretty old and I don't know all the backstory. @1138-4EB how can I get an image like `name/<none>` so that I can test this?
> 
> I think I've been able to consistently reproduce this in the past. However, I would say that previous versions did not show `<none>`, it was just empty. I'll check my notes.

Some info about the context:

```
└─<missing> Virtual Size: 5.5 MB
  └─<missing> Virtual Size: 5.5 MB
    ├─<missing> Virtual Size: 6.1 MB
    │ └─<missing> Virtual Size: 6.1 MB
    │   └─<missing> Virtual Size: 6.1 MB
    │     └─<missing> Virtual Size: 347.2 MB
    │       └─<missing> Virtual Size: 347.2 MB
    │         └─<missing> Virtual Size: 347.2 MB
    │           └─<missing> Virtual Size: 347.2 MB
    │             └─d4953956cf1e Virtual Size: 347.2 MB
    │               └─ea5f4858fd6d Virtual Size: 721.8 MB Tags: dbhi/site:latest
```

`d4953956cf1e` is shown as `golang:<none>` by `docker ps` and as `<none>:<none>` by the VSC extension. Image `dbhi/site:latest` only exists locally. It is not pushed to any repository. I am not the owner of the name in hub.docker.com, indeed. I had to rename the `dbhi*` image, push it, remove it, then remove `golang:<none>` and last pull the renamed `dbhi*` images again.

I dont know why that happened. Anyway, I think that it is possible to generate a similar context when images are pulled by digest:

``` bash
docker pull alpine@sha256:b3dbf31b77fd99d9c08f780ce6f5282aba076d70a513a8be859d8d3a4d0c92b8
```

Ref [moby/moby#23895](https://github.com/moby/moby/issues/23895#issuecomment-268205765)

**Comment by EricJizbaMSFT** [comment]
I can repro now, thanks.

@1138-4EB you should be able to see Volumes and Networks if you're on the latest from master. See these instructions: https://aka.ms/azCodeInsiders

If you still don't see updates, try uninstalling the old "alpha" vsix. We don't add build number to the vsix version, so sometimes it doesn't pick up changes unless you unintall the other vsix since they're technically the same version

**Comment by 1138-4EB** [comment]
Thanks! I was just coming to comment that https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6932 works. I had to restart VSC. But it works fairly well.

Congratulations. You are improving the extension really fast.
