### ISSUE TITLE
html/javascript code will not run. .NET (preview) exception before

### ISSUE THREAD

**Issue by neel216** [microsoft/vscode-docker#1006]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:263:45299
```

</details>

**Comment by philliphoff** [comment]
@neel216  You can add the appProject or appFolder properties to your debug configuration like shown below. Note that you need only specify appProject or appFolder, not both.

```
{
    "configurations": [
        {
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "appProject": "${workspaceFolder}/project/project.csproj",
            "appFolder": "${workspaceFolder}/project"
            "dockerBuild": {
                // Image customizations
            },
            "dockerRun": {
                // Container customizations
            }
        }
    ]
}
```

If neither of those work, let me know and, please, provide any additional details about your project that you can (e.g. the hierarchy of (project) files within the workspace).

**Comment by StephenWeatherford** [comment]
@philliphoff We've been seeing a lot of these.  Do we need to add a link for help to the message?

**Comment by nanangassa** [comment]
yes, please.
I am looking forward to it

**Comment by philliphoff** [comment]
@StephenWeatherford That's a good idea; I've added a task #1113 for that.
