### ISSUE TITLE
[Discussion] "docker.showExplorer" setting in Explorer 2.0

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-docker#1014]
I removed this setting when I did [Docker Explorer 2.0](https://github.com/microsoft/vscode-docker/pull/966):
```
"docker.showExplorer": {
          "type": "boolean",
          "default": true,
          "description": "Show or hide the Explorer"
        },
```

but I wanted to file an issue to discuss if/how we should support that before releasing. I see some value in having a VS Code setting to control this, but it's already possible to hide views if you right click on them.

But that begs the question - do we have one setting for all views _and_ a setting per view? For example:
```
docker.showExplorer
docker.images.showExplorer
docker.containers.showExplorer
```

Or should we flip the wording:
```
docker.hideExplorer
docker.images.hideExplorer
docker.containers.hideExplorer
```

**Comment by fiveisprime** [comment]
My initial thought is that the setting is unnecessary given how the new explorer windows work. It feels natural to modify the UI using the context menus that are already available.

What is the experience for customers how have the extension installed with the explorer hidden using the setting who take the this update?

**Comment by chrisdias** [comment]
I think the `docker.showExplorer` setting is a hangover from way before extensions could create viewlets, and right click hide/show. So removing it is fine. 

My $0.02 on the other settings, I would wait for feedback that people want to control the explorer visibility through settings rather than right click.

**Comment by StephenWeatherford** [comment]
Agreed.
