### ISSUE TITLE
Allow custom file names

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode-docker#102]
[Right now, `COMPOSE_FILE_GLOB_PATTERN` and `DOCKERFILE_GLOB_PATTERN` are hardcoded patterns](https://github.com/Microsoft/vscode-docker/blob/91a56df16058eaa134855eb2438be4216fa2b74d/dockerExtension.ts#L29-L30).

We'd need a way to configure those, either by user or by project.

Thanks!

**Comment by chrisdias** [comment]
would a free form text entry be sufficient?  

or, the ability to right click on any file to build (today the context menu only shows for files that match these patterns):

![image](https://user-images.githubusercontent.com/1487073/28483685-5eab5936-6e23-11e7-809b-5cb55363f4da.png)

**Comment by Yajo** [comment]
Just now I tried on [this project](https://github.com/Tecnativa/docker-duplicity) and right-clicking on any of the dockerfiles there shows that menu item, although running *Docker: Build* from the command palette only shows the main `Dockerfile`. I think the `DOCKERFILE_GLOB_PATTERN` should be more like `*.Dockerfile,Dockerfile.*` (not sure if that's the syntax, but you get it), or simply let vscode detect those, since it does it pretty well.

I also tried on [this another project](https://github.com/Tecnativa/docker-odoo-base/tree/scaffolding) where we have 5 valid docker-compose files (although `common.yaml` shouldn't be used by itself) and none matches this module's regexps. You can't use any docker-compose features from this module (unless you symlink any of those with the right names). Also I don't think those file names should be treated by default as docker-compose files, because they are very project-specific, but it would be perfect to be able to have a setting that lets the project define its environments, like being able to add to `./.vscode/config.json`:

```json
{
    "docker.compose.fileGlobs": ["*.yaml"]
}
```

**Comment by chrisdias** [comment]
👍 on the idea of settings to override the glob patterns.

**Comment by robertpeteuil** [comment]
I agree with the requests to allow changing the globs.

Can `docker-compose` be added as an available language?  At least this would allow manually selecting it when working with a "unique-named" docker-compose file.

**Comment by rodrigodiez** [comment]
Would also love to see this implemented. I have some Golang repositories with multiple binaries and I'd like to have a Dockerfile for each of them. Unfortunately at the moment I have to manage the build manually because these Docker files are not recognized

**Comment by StephenWeatherford** [comment]
@rodrigodiez Please not that you can in fact do this already for Dockerfiles (but not compose files) - see https://github.com/Microsoft/vscode-docker/pull/248#issuecomment-391539247:

{
    "files.associations": {
        "Dockerfile*": "dockerfile"
    }
}

**Comment by crstamps2** [comment]
@StephenWeatherford while the association is a great start for syntax highlighting and such, the commands provided to vscode do not work. An error is given that it cannot find any Dockerfile in the work space.

**Comment by StephenWeatherford** [comment]
@crstamps2 Thanks, will see if there's anything we can do.

**Comment by bwateratmsft** [comment]
To recap since this has been around a while--the `files.associations` setting helps by adding syntax highlighting, but the extension commands (e.g. "Compose Up", "Build Docker Image", etc.) do not recognize all docker-compose YML files and Dockerfiles. It would require code changes for these commands to work; in particular settings for controlling the glob patterns would work.
