### ISSUE TITLE
Highlights USER ${SOME_ARG} as an error

### ISSUE THREAD

**Issue by nicorevin** [Microsoft/vscode-docker#103]
```dockerfile
ARG OK=ok

USER ${OK}
```

will be highlighted as an error.

**Comment by rcjsuen** [comment]
This shouldn't be a problem in the next release because the (original) linter has been removed.

Also see [projectatomic/dockerfile_lint#69](https://github.com/projectatomic/dockerfile_lint/issues/69) which seems to be a duplicate of this issue.

**Comment by rcjsuen** [comment]
Hi @nicorevin, you shouldn't see this error anymore with the new 0.0.17 release.
