### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ChoiJY** [microsoft/vscode-docker#1036]
Repro steps:

Action: docker.activate
Error type: Error
Error Message: command 'vscode-docker.images.selectGroupBy' already exists

Version: 0.6.3
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

**Comment by Hipska** [comment]
Duplicates #1008.

**Comment by fiveisprime** [comment]
Sorry for the issue! I updated the publisher ID and it caused some conflicts for existing users. 😢 

Uninstalling then reinstalling the extension will fix it, but you may also see some recommendations when working with docker files that point to the old extension. Please don't install the recommended extension as that will cause the same issue again - it should be removed from the marketplace by now, but I'm seeing people run into that still.

See #1008 for more information.
