### ISSUE TITLE
vcode-docker

### ISSUE THREAD

**Issue by rdgacarvalho** [microsoft/vscode-docker#1040]
Repro steps:

1.
2.

Action: docker.activate
Error type: Error
Error Message: command 'vscode-docker.images.selectGroupBy' already exists

Version: 0.6.3
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
d.registerCommand extensionHostProcess.js:491:447
Object.registerCommand extensionHostProcess.js:709:422
Object.module.exports.t.registerCommand extension.bundle.js:211:110531
ue extension.bundle.js:157:609314
Object.<anonymous> extension.bundle.js:157:611927
Object.<anonymous> extension.bundle.js:1:394616
module.exports.n extension.bundle.js:1:392954
module.exports.n extension.bundle.js:1:392731
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394533
Object.module.exports.t.activateInternal extension.bundle.js:157:610822
```

</details>

**Comment by Hipska** [comment]
Duplicates #1008.

**Comment by fiveisprime** [comment]
Sorry for the issue! I updated the publisher ID and it caused some conflicts for existing users. 😢 

Uninstalling then reinstalling the extension will fix it, but you may also see some recommendations when working with docker files that point to the old extension. Please don't install the recommended extension as that will cause the same issue again - it should be removed from the marketplace by now, but I'm seeing people run into that still.

See #1008 for more information.
