### ISSUE TITLE
Creation of docker compose triggers install of docker extension

### ISSUE THREAD

**Issue by lferro9000** [microsoft/vscode-docker#1041]
Repro steps:

1. Create a file called "docker-compose.yml"

Expected behavior is that the file is recognized as a docker related file.

Actual result is triggering the installation of docker extension (even if it was already present), and resulting in this error.

Action: docker.activate
Error type: Error
Error Message: command 'vscode-docker.images.selectGroupBy' already exists

Version: 0.6.3
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
d.registerCommand extensionHostProcess.js:497:447
Object.registerCommand extensionHostProcess.js:716:422
Object.module.exports.t.registerCommand extension.bundle.js:211:110531
ue extension.bundle.js:157:609314
Object.<anonymous> extension.bundle.js:157:611927
Object.<anonymous> extension.bundle.js:1:394616
module.exports.n extension.bundle.js:1:392954
module.exports.n extension.bundle.js:1:392731
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394533
Object.module.exports.t.activateInternal extension.bundle.js:157:610822
```

</details>

**Comment by fiveisprime** [comment]
Sorry for the issue! I updated the publisher ID and it caused some unexpected conflicts. 😢 

We've updated the recommendation in VS Code core and I'll work to get that patch out ASAP so the recommendations are correct/don't show up when you already have the extension installed.

See #1008 for more information.
