### ISSUE TITLE
Could not find the preLaunchTask 'npm: compile'

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-docker#106]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393

3a33301d6bd6b638960392d67cd8c16bdbbb5b00 made changes to the `.vscode/launch.json` file and now I get a 'Could not find the preLaunchTask 'npm: compile'' error at the top of VS Code when I try to run the 'Launch Extension' launch configuration.

**Comment by chrisdias** [comment]
I'm going to revert the `tasks.json` and `preLaunchConfig` changes from that commit as it has other consequences as well.
