### ISSUE TITLE
"The Docker extension is recommended" even though it's already installed

### ISSUE THREAD

**Issue by pzelnip** [microsoft/vscode-docker#1075]
Issue Type: <b>Bug</b>

Even though I have the Docker extension already installed, whenever I open a Dockerfile in VS Code I get the "The 'Docker' extension is recommended for this file type." dialog showing up.

I've tried uninstalling & reinstalling the Docker extension, and same thing keeps happening.

Extension version: 0.6.4
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nturinski** [comment]
Hi @pzelnip,

Thanks for reporting this.  There have been some issues with the Docker extension because we changed the publisher name.  This bug should be fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/) and should be released in the next stable version of VS Code. Sorry for the notification, I know it's super annoying.

**Comment by pzelnip** [comment]
No longer seems to be an issue after the 1.36.0 update for VS Code.  Closing, thanks!
