### ISSUE TITLE
Docker extension cannot be used after running the Virtual Box

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#1077]
**OS**: Mac
**Extension Version:** [20190620.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7019)

**Steps to reproduce:**
1. Install Virtualbox https://www.virtualbox.org/ and run it.
2. Create a docker-machine using virtualbox with this command:
`docker-machine create --driver=virtualbox dev`
3. Output your machine's settings with this command
`docker-machine env dev`
4. Modify your VS Code settings based on those variables. It'll look something like this:
"docker.host": "tcp://192.168.99.100:2376",
"docker.certPath": "/Users/erijiz/.docker/machine/machines/dev",
"docker.tlsVerify": "1",
"docker.machineName": "dev"
5. Docker extension is auto removed, then try to install the Docker extension again.
6. Check whether the Docker extension like normal or not.

**Expect Experience:**

The Docker extension works as expected.

**Actual Experience:**

Cannot use the Docker extension.
![image](https://user-images.githubusercontent.com/34729022/59919201-66404900-9459-11e9-9b06-3439d53f4a2e.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh if you expand the "Failed to connect" node - what error does it display?

Also if you run these commands, does it work:
(This command makes it so that the opened terminal uses the "dev" machine)
```
eval "$(docker-machine env dev)"
```

(This command just tries to list images)
```
docker image ls
```

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT , the error message shows as below screenshot after expanding the 'Fail to connect' node.
![image](https://user-images.githubusercontent.com/34729022/60423485-e4061080-9c20-11e9-8dfd-261610e49cb4.png)

The docker still doesn't work after running the below two commands.
```
eval "$(docker-machine env dev1)"
docker image ls
```
![image](https://user-images.githubusercontent.com/34729022/60423533-026c0c00-9c21-11e9-894f-fd603f1b62b3.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh what version of VS Code are you on? They improved some certificate stuff in version 1.33.0. Try updating if you're on a lower version and let us know if this fixes it.

If not - can you show a screenshot of the result of `docker-machine env dev1`? And a screenshot of your VS Code settings that match?

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT , We used VS Code version is 1.36.0. you can see the details info from the below screenshot.

![image](https://user-images.githubusercontent.com/34729022/60478184-4d832f00-9cb4-11e9-9d0f-742576972b3d.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh the VS Code version and settings look good in that screenshot, but the error says host is not running, which means you probably just need to start the virtual machine somehow. Can you start it and post another screenshot? `docker-machine env dev1` should succeed

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT ,you can get the detail settings from the below screenshot.
![image](https://user-images.githubusercontent.com/34729022/60576312-c0250500-9daf-11e9-8338-923738f82199.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh right, but do you still get the same error message in VS Code as well? I was hoping for a screenshot of both the docker machine command _and_ VS Code error message after you started the virtual machine

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT ,Yes, we still get the same error in VS Code. Please see the below screenshot.
![image](https://user-images.githubusercontent.com/34729022/60710282-e9c36500-9f44-11e9-90ef-6d9beeeaa90a.png)

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh have you by chance modified the `docker.importCertificates` setting? If so - maybe try removing that setting?

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT ,Yes. I have modified the setting `docker.importCertificates` =`true` by chance.

But the reported error still occurs after removing that setting.

**Comment by EricJizbaMSFT** [comment]
@v-xuanzh can you try running the following command:
```
docker-machine regenerate-certs dev1
```

And copy the output here if it fails or otherwise let me know if that fixes it

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT 

I have tried running the command `docker-machine regenerate-certs dev1`, the output shows as below
![certs](https://user-images.githubusercontent.com/34729022/61525847-ce2f8280-aa4b-11e9-91d3-f3bb0ec625ac.png)

And the the reported error still shows.
