### ISSUE TITLE
debug issue 

### ISSUE THREAD

**Issue by cqwydz** [microsoft/vscode-docker#1086]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: 1
Error Message: Command failed: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\ZY\.vsdbg\GetVsDbg.ps1" -Version vs2017u5 -RuntimeID linux-x64 -InstallPath "C:\Users\ZY\.vsdbg\linux-x64\vs2017u5"
New-Object : ʹ�á�1�����������á�.ctor��ʱ�����쳣:�������ѳ�ʱ����
����λ�� C:\Users\ZY\.vsdbg\GetVsDbg.ps1:76 �ַ�: 19
+ ... ipArchive = New-Object System.IO.Compression.ZipArchive -ArgumentList ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object]��MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 

Version: 0.6.4
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

**Comment by nturinski** [comment]
Hi @cqwydz,

Thanks for reporting this issue.  Could you provide repro steps, please?
