### ISSUE TITLE
Support ${env:-} in the dockerRun/volumes/localPath 

### ISSUE THREAD

**Issue by psaxton** [microsoft/vscode-docker#1094]
**Issue**: Currently, the only variable allowed for substitution in the dockerRun/Volumes/localPath value is ${workspaceFolder}. When trying to use another value such as ${env:HOME}, an error occurs on build:

`Command failed: docker run -dt -P --name "MyProject"  -v "${env:HOME}/.aws/:/root/.aws:ro"`

`/bin/sh: 1: Bad substitution`

**Example**:
```json
   "dockerRun": {
      "volumes": [
         {
            "localPath": "${env:HOME}",
            "containerPath": "/root/.aws",
            "permissions": "ro"
         }
      ]
   }
```

**Use case**: When developing applications accessing AWS services, configuration and, more importantly *authentication credentials*, are stored in ~/.aws. Docker requires absolute paths for volume values. The home directory is user dependent.

**Plugin version**: Problem encountered with version 0.6.4

**Comment by psaxton** [comment]
This issue is related to but not solved by #785.

**Comment by philliphoff** [comment]
@psaxton This is a good idea, but likely requires custom logic to parse and resolve environment variables. (I don't believe VS Code provides an API for such resolution, which is why I've only supported such substitutions on an as-needed basis.)

**Comment by bwateratmsft** [comment]
Fixed in https://github.com/microsoft/vscode-docker/pull/1245 since we don't inspect the volumes, just pass along to ShellExecution.
