### ISSUE TITLE
docker 

### ISSUE THREAD

**Issue by liuhuanhui** [microsoft/vscode-docker#1102]
Repro steps:

1.
2.

Action: vscode-docker.container.show-logs
Error type: Error
Error Message: There are no Docker containers that apply to this command.

Version: 0.6.4
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
l extension.bundle.js:1:423932
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@liuhuanhui  please add repro steps to this issue

As an aside, https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders
