### ISSUE TITLE
docker.truncateLongRegistryPaths doesn't truncate container image names

### ISSUE THREAD

**Issue by hutchisr** [microsoft/vscode-docker#1103]
The `docker.truncateLongRegistryPaths` tooltip claims to truncate registry names for both images and containers: `Truncate long Image and Container registry paths in the Explorer`, however it only truncates registry paths in the images section of the explorer, not containers, which still display the full registry path.

**Comment by EricJizbaMSFT** [comment]
@hutchisr this was recently fixed in https://github.com/microsoft/vscode-docker/pull/989. You're welcome to try the latest from master with these instructions: https://aka.ms/azCodeInsiders otherwise we hope to release pretty soon
