### ISSUE TITLE
[Suggestion] Display 'Removing…' instead of 'Deleting...' during removing one container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-docker#1107]
**Extension Build:** [20190703.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7464)
**OS:** All

**Steps to reproduce:**
1.  Right click one container -> Select 'Remove...'.
2. Observe the container.

**Actual Experience:**
Display 'Deleting...' during removing one container.
![image](https://user-images.githubusercontent.com/41351993/60660541-92f95500-9e8a-11e9-8776-3e3fd4a45bb3.png)

**Suggestion:**
 Display 'Removing...' during removing one container.

**More Info:**
Pop up a notification during removing one container.
![image](https://user-images.githubusercontent.com/41351993/60660763-04390800-9e8b-11e9-9d78-3830a03bcfcb.png)

**Comment by bwateratmsft** [comment]
This would require changing in `vscode-azureextensionui`, which would affect all the other Azure extensions (Cosmos, Functions, etc.). Since the change would be very broad it's probably best to leave things as they are.
