### ISSUE TITLE
Can't access to container from VSCODE

### ISSUE THREAD

**Issue by dpinalopez** [microsoft/vscode-docker#1108]
Hello friends, I've just installed your extension on vscode but when it tries to connect with the succesfully just created container it hits me the next error:

Unable to connect to Docker. Please make sure you have installed Docker and that it is running. Also make sure you've followed the Linux post-install instructions "Manage Docker as a non-root user". Details: connect ENOENT /var/run/docker.sock

My user belongs to docker group.
The container is sucessfully created. 
Docker.sock exists on that directory.

Any Help?

David

**Comment by EricJizbaMSFT** [comment]
@dpinalopez are you able to see successful output if you run` docker image ls` from the command line? And can you give more detailed information about your OS, docker version, and how you installed docker?

**Comment by adkhn777** [comment]
I am also facing the same issue, although i am able to run `docker image ls` and other docker commands under same user without sudo
