### ISSUE TITLE
The container auto removes when debugging the .NET Core Console application

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1110]
**OS**: Windows
**Build Version:** [20190703.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7464)

**Repro Steps:**
1. Create a new .NET Core ASP.NET application by "dotnet new web --name test".
2. Open it in VS Code Insiders --> Click "Yes" when prompted to add required assets.
![image](https://user-images.githubusercontent.com/34729092/60711915-77548400-9f48-11e9-9aae-e0b9da7ee33d.png)
3. Run "Add Docker files to workspace" -->Select ASP.NET Core --> Select Linux --> Port 80.
4. Add .NET Core debug launch task by adding "Docker: Launch .NET Core (Preview)".
5. Edit the .NET Core debugging configuration as below:
![image](https://user-images.githubusercontent.com/34729092/60713009-c8fe0e00-9f4a-11e9-93d6-11ef7dd4fe82.png)
6. Edit the Dockerfile as below:
![image](https://user-images.githubusercontent.com/34729092/60713021-d0bdb280-9f4a-11e9-9956-040dc8b097e2.png)
7. Create a new directory called "Dockerfile.env" with below content:
![image](https://user-images.githubusercontent.com/34729092/60712338-5e000780-9f49-11e9-9cb1-fd8898baf3a7.png)
8. Debug and check the Output window.

**Expect:**
The container keeps running.

**Actual:**
The container auto removes. 
![image](https://user-images.githubusercontent.com/34729092/60713088-f5198f00-9f4a-11e9-95d3-071c3f88a0a3.png)

**Comment by philliphoff** [comment]
@v-dantch The extension intentionally kills the running container when the debugging session ends (either due to the user's action to stop the debugger or if the application itself ends, such as if there was an error).  Are you able to debug the application at all?  Is the application immediately exiting upon starting (check the debugging output)?

**Comment by v-dantch** [comment]
Hi Phillip, sorry for my late reply. 
Finally we found the root cause is that the version of dotnet in the Dockerfile is inconsistent with the locally installed. Thus there pops up bellow error:
![image](https://user-images.githubusercontent.com/34729092/61356238-80c6e000-a8a8-11e9-9be8-66e31a593a4d.png)

After keeping the same version, there is no any exceptions.

We will pay more attention to error message and meanwhile we will note this in our test case.

**Comment by philliphoff** [comment]
@v-dantch Glad you found the root cause; should this issue now be closed?

**Comment by v-dantch** [comment]
Hi @philliphoff  thanks for your help and it gives me inspiration.  And I will close this issue.
