### ISSUE TITLE
Formatting removes escape character at EOL

### ISSUE THREAD

**Issue by SuperSandro2000** [microsoft/vscode-docker#1112]
Formatting this Dockerfile snippet
````
RUN apt-get update -qy && \
  apt-get install -qy --no-install-recommends libmysqlclient-dev
````
results in 
````
RUN apt-get update -qy &&
  apt-get install -qy --no-install-recommends libmysqlclient-dev
````
which is invalid and can't be build.

**Comment by rcjsuen** [comment]
@SuperSandro2000 Thank you for your bug report.

Unfortunately, I am unable to reproduce this error. Can you please provide a) exact steps, b) your complete Dockerfile, or c) some animated gif or video that shows the problem?

Thank you for your assistance.

**Comment by SuperSandro2000** [comment]
Wrong extensions. The bug comes from https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format
