### ISSUE TITLE
Improve help for .NET Core debugging configuration

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1113]
A lot of customers seem to have issues with configuring--or rather, the tool inferring the configuration of--their project for debugging. Perhaps the error messaging can be improved to lead the customer to an appropriate solution.

**Comment by bwateratmsft** [comment]
I've added a ton of info on this (and Node debugging) into the rel/0.9.0 branch of the wiki.

**Comment by karolz-ms** [comment]
@bwateratmsft Roger, thanks. Will add that to my prototype/fork

**Comment by dbreshears** [comment]
Docs are in progress for being updated based on the wiki content.
