### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by jesielsilva** [microsoft/vscode-docker#1114]
Repro steps:

1.
2.

Action: vscode-docker.image.tag
Error type: Error
Error Message: There are no docker images. Try Docker Build first.

Version: 0.6.4
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.quickPickImage extension.bundle.js:1:421717
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jesielsilva please add repro steps to this issue
