### ISSUE TITLE
The Azure Registries node auto collapses after selecting "Copy Image Digest"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1120]
**OS:** Win10
**Build Version:** [20190709.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7546)
**VS Code Insider Version:** 1.37.0-insider (user setup)

**Repro Steps:**
1.Drill down from "REGISTRIES" -> "Azure" -> applied subscription -> one specified azure registry -> one image.
2. Right click the image and select "Copy Image Digest" item.
3. Check the result.

**Expect:**
Succeed to copy the image digest and the Azure Registries node won't auto collapse .

**Actual:**
Succeed to copy the image digest and the Azure Registries node auto collapses .
![image](https://user-images.githubusercontent.com/34729092/60957170-c4649b80-a336-11e9-829a-67c00ad848f0.png)

**More Info:**
The Azure Registries node also auto collapses after deleting one azure registry.
![image](https://user-images.githubusercontent.com/34729092/60957307-042b8300-a337-11e9-9d07-e48b8dcfdf22.png)

**Comment by EricJizbaMSFT** [comment]
https://github.com/microsoft/vscode/issues/77129

**Comment by EricJizbaMSFT** [comment]
This was fixed in latest insiders of VS Code
