### ISSUE TITLE
"Refresh" of applied subscription context menu collapses the Azure Registries n

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1121]
**OS:** Win10
**Build Version:** [20190709.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7546)
**VS Code Insider Version:** 1.37.0-insider (user setup)

**Repro Steps:**
1. Drill down from the applied subscription --> one azure registry --> repository -> image.
2. Right click the applied subscription --> Select "Refresh".
3. Check the result.

**Expect:**
The applied subscription collapses.

**Actual:**
The Azure Registries node auto collapses.
![image](https://user-images.githubusercontent.com/34729092/60957805-dabf2700-a337-11e9-82b3-3f3ae81ac11e.png)

**More Info;**
The Azure Registries node also collapses when refreshing one azure registry.
The Docker Hub Registries node also collapses when refreshing one registry.

**Comment by EricJizbaMSFT** [comment]
https://github.com/microsoft/vscode/issues/77129

**Comment by EricJizbaMSFT** [comment]
This was fixed in latest insiders of VS Code
