### ISSUE TITLE
Allow right click on "Incorrect Registry Credentials" to re-enter credentials

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-docker#1122]
When you enter an invalid password for your dockerhub, there is no option to retry. You can disconnect and try again if you right click the DockerHub item, but it felt like we should be able to do something (right click, single click, click a button) in the message 

I recommend it allows right click on "Incorrect Registry Credentials" to re-enter credentials

![image](https://user-images.githubusercontent.com/1202528/60970379-d3742b00-a2ef-11e9-9d97-cf90d9f15b38.png)

**Comment by bwateratmsft** [comment]
Hey @johnpapa, this is now available in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).

**Comment by johnpapa** [comment]
Thank you
