### ISSUE TITLE
Allow to remove all images in a group via right-click in tree

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-docker#1123]
Currently, this is only possible when using the command palette. Would be nice if I could right-click a group and do "Remove...".

**Comment by PrashanthCorp** [comment]
Yeah, it looks like the code doesn't consider the multi-select case: 

https://github.com/microsoft/vscode-docker/blob/master/src/commands/images/removeImage.ts#L11

**Comment by bwateratmsft** [comment]
We added multi-select support in 1.0.0. It's not exactly the same as this request, but I feel like it's close enough, so I'll close it. If you disagree please let us know. Thanks!
