### ISSUE TITLE
Support to execute "Copy Image Digest" for the ACR Task by command

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1125]
**OS:** Win10
**Build Version:** [20190710.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7574)

**Repro Steps:**
1. F1 --> Type and select "Docker Registries: Copy Image Digest".
2. Complete the selection according to prompting.
3. Check whether the "Copy Image Digest" for the existing ACR Task can be executed or not.

**Expect:**
Succeed to execute "Copy Image Digest" for the ACR Task by command.

**Actual:**
The ACR Task cannot list when selecting repository.
![image](https://user-images.githubusercontent.com/34729092/61047938-2a265580-a413-11e9-99d4-d8cbf1d0fe4a.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20200818.1, this issue still reproduces for now. I will continue to track this issue.

**Comment by bwateratmsft** [comment]
Closing this for now; the interest doesn't seem to be there.
