### ISSUE TITLE
Deploy image to App Service context menu is missing.

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#1128]
I see the global command, but the context menu isn't showing up on tags in registries.

**Comment by EricJizbaMSFT** [comment]
So it shows, but only if you have Azure connected as a registry provider.

![Screen Shot 2019-07-17 at 9 23 59 AM](https://user-images.githubusercontent.com/11282622/61392880-b81b9980-a874-11e9-9bef-427396a15b1a.png)

We can fix that since ACR isn't needed for App Service.

**Comment by bwateratmsft** [comment]
This is no longer an issue.
