### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by jnather** [microsoft/vscode-docker#1129]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint mc (085d864a35f9b78a18a466d39b8bf4364c6885eb4f05ce9b7dc8de7a93e4f79b): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:25565:tcp:172.17.0.2:25565: input/output error 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by StephenWeatherford** [comment]
@jnather Does this happen consistently?  Does it repro outside of vscode?  It's unlikely it's related to the extension.

I would start by making sure the port is available, perhaps restart docker.  Then search online for the error message, especially the last part of it - not sure what the "mkdir" command is trying to do, e.g. try a search like https://www.bing.com/search?q=docker+error+starting+userland+proxy%3A+mkdir+%2Fport%2Ftcp%3A0.0.0.0%3A25565%3Atcp%3A172.17.0.2%3A25565%3A+input%2Foutput+error&form=EDGTCT&qs=PF&cvid=14ee8cb022814fc2afbd8dea4c52d8e3&refig=9c04b78983dc417d9ce0e6c019cc718e&cc=US&setlang=en-US&elv=AQj93OAhDTi*HzTv1paQdnhNDHquXhd47ZC0HHwJ8%21RO0z%21n57XjnACu6L2vE4HBVpRy0vwb67wmyl6YAgzPUnMqlKTH%219mLnsuMxmOPURYS&plvar=0
