### ISSUE TITLE
Graceful Error when no Docker

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docker#113]
Windows
Testing: https://github.com/Microsoft/vscode/issues/33053

1. Install extension
2. Reload
3. Try any of the explorer actions e.g. expand Images

Docker extension should (upon activation) check that Docker is installed to avoid errors.

Where errors do occur we should catch and provide a help message.

Current behavior:
![image](https://user-images.githubusercontent.com/1051190/29840912-6fde9674-8cb8-11e7-86ec-77a349e8a1e9.png)

**Comment by chrisdias** [comment]
Nice find. 

Now I catch the error and say "Unable to connect to Docker, is the service running?".
