### ISSUE TITLE
sffdfd

### ISSUE THREAD

**Issue by tienanhcntt2** [microsoft/vscode-docker#1130]
Repro steps:

1.
2.

Action: vscode-docker.images.run
Error type: 404
Error Message: (HTTP code 404) no such image - no such image: sha256:00beff41929ec04e50aa84c6976ef0cea7a14233a706bd4f1aa71ba02d35f613: No such image: sha256:00beff41929ec04e50aa84c6976ef0cea7a14233a706bd4f1aa71ba02d35f613 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by StephenWeatherford** [comment]
@tienanhcntt2 Is this happening consistently?  If so, please provide repro steps.  Otherwise I would take the error message at its word - the image you're trying to start no longer exists (did you delete it somehow? perhaps through pruning or deleting it via another tag?)
