### ISSUE TITLE
Docker Containers commands in Remote Development

### ISSUE THREAD

**Issue by unfalln** [microsoft/vscode-docker#1131]
When using Remote Development extensions, the commands for Docker Containers (e.g. "View Logs", "Attach Shell") are being executed in the terminal shell. This means that, if I am remote-developing inside a docker container, the commands fail because the docker client is on the host, not inside the container.

**Comment by EricJizbaMSFT** [comment]
@unfalln I'm not entirely following your scenario, but please see https://github.com/microsoft/vscode-docker/issues/954. You can force the Docker extension to run in the remote with this setting:
```
"remote.extensionKind": {
    "ms-azuretools.vscode-docker": "workspace"
}
```

If that doesn't help, please add more detailed repro steps to this issue

**Comment by unfalln** [comment]
To clarify, this is a request for some of the functionality described in #954 , primarily:

> An API to create a terminal on the local machine (instead of in the container) to run commands like "Build Image"

I am looking for this moreso for the "View Logs" command to run on the local machine rather than in the container.

I will leave this closed as it is already outlined elsewhere.
