### ISSUE TITLE
Docker Error when stop container

### ISSUE THREAD

**Issue by mlazuardy-dyned** [microsoft/vscode-docker#1132]
Repro steps:

1.
2.

Action: vscode-docker.containers.stop
Error type: 304
Error Message: (HTTP code 304) container already stopped -  

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by StephenWeatherford** [comment]
@mlazuardy-dyned Is this happening repeatedly?  If so, please provide repro steps.  If not, it sounds like the container had simply already been stopped.  Thx.
