### ISSUE TITLE
unable to launch docker container images in VS code

### ISSUE THREAD

**Issue by NirajCricket** [microsoft/vscode-docker#1133]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint elegant_bartik (cbf52abab7639c6604c8e9e3e96d3d7995c194d4961d1f07d4198a94ae220c5f): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by StephenWeatherford** [comment]
Have you tried running the same command outside of vscode?  It's unlikely it has anything to do with the extension.  

I would check first that no other containers are bound to port 80, and then that you do have permissions to be binding to it.
