### ISSUE TITLE
Error type: Error

### ISSUE THREAD

**Issue by sinesiobittencourt** [microsoft/vscode-docker#1134]
Repro steps:

1.
2.

Action: vscode-docker.containers.stop
Error type: Error
Error Message: No matching resources found.

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
ContainersTreeItem.<anonymous> extension.bundle.js:31:103770
o extension.bundle.js:31:98683
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sinesiobittencourt can you add repro steps for this issue? It's likely there weren't any containers when you tried to run this command.
