### ISSUE TITLE
 如何处理

### ISSUE THREAD

**Issue by zhangshuaiming** [microsoft/vscode-docker#1136]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 404
Error Message: (HTTP code 404) no such container - No such container: 6aac8939f79cd7c20c9a88d89becf0b01948f39bc756181e77c4280b1cbf6f58 

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@zhangshuaiming please add repro steps to your issue
