### ISSUE TITLE
Docker build / vs \

### ISSUE THREAD

**Issue by tvalbusa** [microsoft/vscode-docker#1139]
Open wsl on windows 10
Start code :  /mnt/c/User/xxxx/code .
Docker build (right click on Dockerfile)

Error :
docker build --rm -f "app-kb-front\nodejs.Dockerfile" -t google-ccai-kb-front:0.1.1 app-kb-front

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /mnt/c/Users/tvalbusa/Gdrive_job/dev/prj-innovation2/app-kb-front\nodejs.Dockerfile: no such file or directory

Corrrection : 

Command should be : 

\ should be replace by / between "app-kb-front" and "nodejs.Dockerfile"

docker build --rm -f "app-kb-front /nodejs.Dockerfile" -t google-ccai-kb-front:0.1.1 app-kb-frontWe have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/960
