### ISSUE TITLE
Issue #471 is not fixed in 0.7.0

### ISSUE THREAD

**Issue by JFLeblay** [microsoft/vscode-docker#1142]
Your new release 0.7.0 has a bug that was fixed in previous release (see issue #471). The API URL to check API version needs a trailing slash.
The bug is in src/tree/registries/dockerV2/GenericDockerV2RegistryTreeItem.ts:
`await registryRequest(this, 'GET', 'v2');` should be actually `await registryRequest(this, 'GET', 'v2/');`

**Comment by EricJizbaMSFT** [comment]
@JFLeblay thanks for reporting! If you want to get the latest fix, you can use a master build with these instructions: https://aka.ms/azcodeinsiders
