### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by JuneJobs** [microsoft/vscode-docker#1146]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@JuneJobs please try updating your VS Code version to at least v1.26.0
