### ISSUE TITLE
issue with docker login and vscode

### ISSUE THREAD

**Issue by rxmii4269** [microsoft/vscode-docker#1147]
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: string
Error Message: WARNING! Your password will be stored unencrypted in /home/romaine/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@rxmii4269 this error is coming from Docker. Please see the link mentioned above for more info:

https://docs.docker.com/engine/reference/commandline/login/#credentials-store
