### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JaphethacCalzada** [microsoft/vscode-docker#1148]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint laradock_mysql_1 (c184b81fc3078827b533a72067efafd2df34e7f71c2cb87f33d86730b9d4d70f): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use 

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.0
Language: es

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
IncomingMessage.EventEmitter.emit domain.js:442:20
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@JaphethacCalzada please add repro steps to this issue
