### ISSUE TITLE
not working it can't connect

### ISSUE THREAD

**Issue by truth8280** [microsoft/vscode-docker#1149]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@truth8280 is docker installed and running? Either way, please add repro steps
