### ISSUE TITLE
Explorer visibility

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-docker#115]
Windows
Testing https://github.com/Microsoft/vscode/issues/33053

1. Hide explorer with right click context
2. How do I get it back? (I should know I know :smile:)
3. This setting does not help `"docker.showExplorer": true`

**Comment by chrisdias** [comment]
right click on the EXPLORER title and you can hide/show any sash:

![image](https://user-images.githubusercontent.com/1487073/29844381-f0f77676-8cc3-11e7-94d6-78831459d5b0.png)

That said, it is still a valid issue that the configuration property doesn't do anything.  It was added before the user could hide/show sashes so I'll remove it.
