### ISSUE TITLE
Connected register

### ISSUE THREAD

**Issue by magnomatos822** [microsoft/vscode-docker#1151]
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@magnomatos822 please add repro steps
