### ISSUE TITLE
Unable to debug on linux

### ISSUE THREAD

**Issue by itlackey** [microsoft/vscode-docker#1153]
Repro steps:

1. Create new aspnet core app. dotnet new mvc 
2. Use extension to add docker files. Docker: Add Files to workspace
3. Add launch config to launch.json (Debug -> Add Configuration -> Docker Launch Core)
4. Click Start Debugging

Action: debugCoreClr
Error type: SyntaxError
Error Message: Unexpected end of JSON input

Version: 0.7.0
OS: linux mint 19
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDaemonIsLinuxPrerequisite.checkPrerequisite extension.bundle.js:157:519978
```

</details>

If appears to be failing here:
/src/debugging/coreclr/prereqManager.ts Line : 29
```
const daemonOs = JSON.parse(daemonOsJson.trim());
```

If I run `docker version --format {{json .Server.Os}}` it returns "linux" which appears to be what is expected by the extension.

Any help is much appreciated!

**Comment by philliphoff** [comment]
@itlackey What version of Docker are you using?

**Comment by itlackey** [comment]
@philliphoff I apologize, I was out of town and offline for a while. I am using: 
Docker version 18.06.1-ce, build e68fc7a

**Comment by philliphoff** [comment]
@itlackey Ah, ok.  We saw the same issue on 18.06 and appears to be specific to that version of Docker; later versions do not exhibit this behavior.  If you can, try updating your Docker installation and let us know if you're still having trouble.

**Comment by bwateratmsft** [comment]
That's good news! Thanks for the update!
