### ISSUE TITLE
Image failed to remove error

### ISSUE THREAD

**Issue by slavslav** [microsoft/vscode-docker#1154]
Repro steps:

1. Do "docker run --rm -it nvcr.io/nvidia-hpcvis/paraview:egl-5.6.0rc3" in Windows 10 vscode & have a same commanded terminal running.
2. Try to delete image 

Action: vscode-docker.containers.remove
Error type: 409
Error Message: (HTTP code 409) unexpected - removal of container 7cd1e98d6d59dc5547539999e06f65149572b028bd2b830cb2dbaed1fcce0922 is already in progress 

Version: 0.7.0
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.37.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@slavslav is the error inaccurate? What are you expecting here? Seems like you just have to wait for the current removal to finish

**Comment by slavslav** [comment]
ok i see. i think i have it fixed. i did to the computer cmos to egl ... i messed with that here over the vstudio-docker app. thanks.
