### ISSUE TITLE
Remove Generic Docker Registry failed

### ISSUE THREAD

**Issue by degus2019** [microsoft/vscode-docker#1155]
Repro steps:

1. Add an empty URL for "Generic Docker Registry"
2. Try to Remove them

Action: vscode-docker.registries.disconnectRegistry
Error type: ERR_INVALID_URL
Error Message: Invalid URL: 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
onParseError url.js:237:17
parse url.js:246:3
new URL url.js:321:5
GenericDockerV2RegistryTreeItem.get host [as host] extension.bundle.js:31:159472
GenericDockerV2RegistryTreeItem.get label [as label] extension.bundle.js:157:487343
GenericDockerV2RegistryTreeItem.get effectiveLabel [as effectiveLabel] extension.bundle.js:1:464668
ConnectedRegistriesTreeItem.compareChildrenImpl extension.bundle.js:31:100285
module.exports.loadMoreChildrenInternal.n._cachedChildren._cachedChildren.concat.sort extension.bundle.js:31:102539
ConnectedRegistriesTreeItem.<anonymous> extension.bundle.js:31:102522
o extension.bundle.js:31:98683
```

</details>

**Comment by EricJizbaMSFT** [comment]
@degus2019 can you give me an example "incorrect URL" that I can try?

**Comment by degus2019** [comment]
As example our internal registry: 
https://nexus3.xx.xxxxx.de:18445
alternative:
https://10.11.11.2:18445

After i added the IP URL, there is no additional entry in "Connected Registries" Tab. 
When I try to add one of the two urls, I am told that the urls already exist

it is not possible to disconnect any registry entry .. 
i tried to remove the credentials in windows store... without result
where are the connect data stored?

**Comment by EricJizbaMSFT** [comment]
@degus2019 Very helpful - thanks!

Unfortunately, I couldn't find an easy workaround with the existing extension. However, I've created a build which should allow you to disconnect the registry with the empty url. If you're interested, install [this build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8120) using these instructions: https://aka.ms/azCodeInsiders

**Comment by EricJizbaMSFT** [comment]
FYI @quangkieu see above comment for a workaround

**Comment by degus2019** [comment]
i used the build, but there is no option for disconnect,
you only can reset all connections, because you cant see the entrys..
i added min. 3 entrys 

![2019-07-25 21_48_00-Window](https://user-images.githubusercontent.com/47261225/61904048-4f908480-af26-11e9-995b-b983c04bd1fe.png)

**Comment by EricJizbaMSFT** [comment]
@degus2019 sorry - you have to do "Disconnect" from the command palette (View -> Command Palette) and type in "Disconnect" to filter

![Screen Shot 2019-07-25 at 1 33 58 PM](https://user-images.githubusercontent.com/11282622/61906768-ef2b2400-aee0-11e9-98bb-413d0675fe65.png)

**Comment by degus2019** [comment]
Ah ok :-) 

works fine. 
thx

**Comment by quangkieu** [comment]
confirm fix. Thank you Eric
