### ISSUE TITLE
Unexpected exit when debug by using compound to launch multiple docker configurations

### ISSUE THREAD

**Issue by DatXN** [microsoft/vscode-docker#1157]
Hi, 
I have 2 docker launch configuration for 2 .net core console project, and use compound to launch 2 configuration at the same time.

**Problem: When one console is continue on one console (then it should exist) -> the other console will exist unexpectedly even though the debug still on.**

Attachment is the sample solution to reproduce the issue.

[DxApollo.zip](https://github.com/microsoft/vscode-docker/files/3432474/DxApollo.zip)

Here is my launch.json file:

> {
>    // Use IntelliSense to find out which attributes exist for C# debugging
>    // Use hover for the description of the existing attributes
>    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
>    "version": "0.2.0",
>    "configurations": [
>         {
>             "name": "(Docker) Consumer",
>             "type": "docker-coreclr",
>             "request": "launch",
>             "preLaunchTask": "build",
>             "appProject": "${workspaceFolder}/DxApollo.Consumer/src/DxApollo.Consumer/DxApollo.Consumer.csproj",
>             "dockerBuild": {
>                 "context": "${workspaceFolder}",
>                 "dockerfile": "${workspaceFolder}/DxApollo.Consumer/devops/docker/Dockerfile",
>                 "tag": "dev",
>                 "target": "publish"
>             },
>             "dockerRun": {
>                 "containerName": "dxapollo.consumer",
>             }
>         },
>         {
>             "name": "(Docker) Publisher",
>             "type": "docker-coreclr",
>             "request": "launch",
>             "preLaunchTask": "build",
>             "appProject": "${workspaceFolder}/DxApollo.Publisher/src/DxApollo.Publisher/DxApollo.Publisher.csproj",
>             "dockerBuild": {
>                 "context": "${workspaceFolder}",
>                 "dockerfile": "${workspaceFolder}/DxApollo.Publisher/devops/docker/Dockerfile",
>                 "tag": "dev",
>                 "target": "publish"
>             },
>             "dockerRun": {
>                 "containerName": "dxapollo.publisher",
>             }
>         }
>         ],
>     "compounds": [
>         {
>             "name": "(Docker) Comsumer & Publisher",
>             "configurations": ["(Docker) Consumer", "(Docker) Publisher"]
>         }
>         
>     ]
> }

**Comment by bwateratmsft** [comment]
Potentially resolved by #1245

**Comment by DatXN** [comment]
Still bug with my provided code: The pipe program 'docker' exited unexpectedly with code 137.

**Comment by bwateratmsft** [comment]
The code in #1245 hasn't been released yet :)
It'll probably be a few weeks at least until that's available.

**Comment by philliphoff** [comment]
The problem with the previous version of the extension was that it would try to remove *all* outstanding debug containers when a debug session ends, even though there may be a container still being debugged in another session.

I successfully tested your sample with `0.9.0` after switching to the new "task-based" Docker build/run/debug model.  In this new release, container tear-down is better associated with a specific session.

I added the following tasks to `tasks.json`:

```json
        {
            "type": "docker-build",
            "label": "consumer: docker-build: debug",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "consumer:dev",
                "target": "base",
                "dockerfile": "${workspaceFolder}/DxApollo.Consumer/devops/docker/Dockerfile",
                "context": "${workspaceFolder}"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Consumer/src/DxApollo.Consumer/DxApollo.Consumer.csproj"
            }
        },
        {
            "type": "docker-run",
            "label": "consumer: docker-run: debug",
            "dependsOn": [
                "consumer: docker-build: debug"
            ],
            "dockerRun": {
                "containerName": "dxapollo-consumer"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Consumer/src/DxApollo.Consumer/DxApollo.Consumer.csproj",
                "enableDebugging": true
            }
        },
        {
            "type": "docker-build",
            "label": "publisher: docker-build: debug",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "publisher:dev",
                "target": "base",
                "dockerfile": "${workspaceFolder}/DxApollo.Publisher/devops/docker/Dockerfile",
                "context": "${workspaceFolder}"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Publisher/src/DxApollo.Publisher/DxApollo.Publisher.csproj"
            }
        },
        {
            "type": "docker-run",
            "label": "publisher: docker-run: debug",
            "dependsOn": [
                "publisher: docker-build: debug"
            ],
            "dockerRun": {
                "containerName": "dxapollo-publisher"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Publisher/src/DxApollo.Publisher/DxApollo.Publisher.csproj",
                "enableDebugging": true
            }
        }
```

I added the following configurations to `launch.json` (with corresponding new compound configuration):

```json
        {
            "name": "(new) Publisher",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "publisher: docker-run: debug",
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Publisher/src/DxApollo.Publisher/DxApollo.Publisher.csproj"
            }
        },
        {
            "name": "(new) Consumer",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "consumer: docker-run: debug",
            "netCore": {
                "appProject": "${workspaceFolder}/DxApollo.Consumer/src/DxApollo.Consumer/DxApollo.Consumer.csproj"
            }
        }
```
