### ISSUE TITLE
Docker Explorer: selection always resets

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docker#116]
testing https://github.com/Microsoft/vscode/issues/33053:

- select a container

Observe: after a brief moment the container is deselected for no reason:

![2017-08-30_15-34-14](https://user-images.githubusercontent.com/1898161/29875115-2ee4cc6a-8d99-11e7-995b-280577b59fb9.gif)

**Comment by chrisdias** [comment]
I'm removing the current automatic refresh...
