### ISSUE TITLE
Cannot restart nginx container

### ISSUE THREAD

**Issue by ABouzidi90** [microsoft/vscode-docker#1161]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 400
Error Message: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Users/PC/iotech/ioc/nginx/conf.d/default.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/27ea0400692c60ad0357e844467effbd23099f26443adce349a3ebedee7fc93f/merged\\\" at \\\"/var/lib/docker/overlay2/27ea0400692c60ad0357e844467effbd23099f26443adce349a3ebedee7fc93f/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: fr

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ABouzidi90 please add repro steps to this issue
