### ISSUE TITLE
Docker Extension polling causes docker engine fd leak

### ISSUE THREAD

**Issue by sureshsankaran** [microsoft/vscode-docker#1168]
Test setup:
Docker extension version - Alpha version built from source code as it is on July 27, 2019.
Docker engine on remote machine - 18.03 version

With default refresh interval of 1sec, extension is polling remote docker engine for status on different docker components like containers/images/registry etc., With this i do see that docker engine on remote machine keep opening fd and eventually reaches maximum soft limit of open files.  This is very serious issue because the docker engine becomes pretty much unusable within few mins.

When i disable extension, i don't see the fd leak issue on remote docker engine.

**Comment by EricJizbaMSFT** [comment]
@sureshsankaran I just want to confirm - have you tried the `docker.explorerRefreshInterval` setting and does that solve the issue on your machine?

**Comment by EricJizbaMSFT** [comment]
Are you advocating for a higher default polling interval? If so, what value would work well on your machine? Or are you saying you would prefer _no_ polling by default?

Also, the extension should stop polling if you switch away from the Docker view in VS Code. Let us know if you're not seeing this behavior.

**Comment by sureshsankaran** [comment]
>  I just want to confirm - have you tried the docker.explorerRefreshInterval setting and does that solve the issue on your machine?

> Are you advocating for a higher default polling interval? If so, what value would work well on your machine? Or are you saying you would prefer no polling by default?

This will not help as we are anyways leaking fd in docker engine. So in few secs or few days, we will hit this soft max files open limit on remote docker engine (and making it unusable). I would like understand what is causing this docker leak ? Is it open connection ?

**Comment by EricJizbaMSFT** [comment]
> This will not help as we are anyways leaking fd in docker engine.

Can you confirm how you know there's a fd leak? It feels possible that we're just polling too often for you and it "reaches maximum soft limit of open files" without any leak at all - which would be solved by polling much less often.

**Comment by sureshsankaran** [comment]
I could see from dir.. /proc/$docker_engine_pid/fd

fds kept on increasing with extension polling.  Again it is not about how often you are polling. 

Solution:
With every poll you should not be triggering new fd creation of docker engine.

**Comment by philliphoff** [comment]
@sureshsankaran I've tried to reproduce this with the latest `vscode-docker` (0.9.0) and the latest Docker engine (19.03.5) on a remote machine, but do not see an increasing number of file descriptors for the `dockerd` process as the Docker treeviews poll/refresh.

Do you continue to see this issue (on the latest version of Docker)?  If so, can you provide a little more detail on how you've setup your remote connection to help ensure I'm attempting to reproduce it in the same manner.
