### ISSUE TITLE
DOCKER_TLS_VERIFY automatically enabled even without any config

### ISSUE THREAD

**Issue by sureshsankaran** [microsoft/vscode-docker#1169]
Test setup:
Docker extension version - Alpha version built from source code as it is on July 27, 2019.
Docker engine on remote machine - 18.03 version

I was trying to connect to remote docker engine by setting config parameters corresponding to 
 DOCKER_HOST and DOCKER_CERT_PATH. Didn't set any value for "DOCKER_TLS_VERIFY"  associated setting. Now the extension throws the error saying invalid server certificate, mismatched common name in the cert. I understand that the IP address used to connect to the docker engine is different from the one present in ssl cert common name. But this is the expected behavior with DOCKER_TLS_VERIFY=1. But why i am getting this error without even setting VERIFY=1.

Expected behavior:
Extension should successfully connect to the remote docker engine without having to verify the server ssl cert.

**Comment by EricJizbaMSFT** [comment]
We leverage `docker-modem` under the covers which has [this logic](https://github.com/apocas/docker-modem/blob/0d07517d3f684d7d151ec06e090041a936b4ff67/lib/modem.js#L43):
```
if (process.env.DOCKER_TLS_VERIFY === '1' || opts.port === '2376') {
  opts.protocol = 'https';
} else {
  opts.protocol = 'http';
}
```

Are you using port `2376`? Based on [these docs](https://docs.docker.com/engine/reference/commandline/dockerd/):
> It is conventional to use port 2375 for un-encrypted, and port 2376 for encrypted communication with the daemon.

**Comment by sureshsankaran** [comment]
Yes i am using port 2376 with https tls. Issue here is to support the client mode where we don't verify server certificate. 

Like third bullet point of client modes in this snapshot. Pretty much check for 

<img width="918" alt="Screen Shot 2019-07-26 at 8 25 18 PM" src="https://user-images.githubusercontent.com/7672865/62241406-f4c7b480-b38d-11e9-8c0d-395cf7820744.png">

**Comment by bwateratmsft** [comment]
As this is a limitation of docker-modem, I have copied this issue there: https://github.com/apocas/docker-modem/issues/110
