### ISSUE TITLE
Error is comming while launching docker

### ISSUE THREAD

**Issue by vishal9458425389** [microsoft/vscode-docker#1170]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: 1
Error Message: Command failed: dotnet msbuild "C:\Users\VISHAL~1.SIN\AppData\Local\Temp\temp_1564460477402_22012_1.tmp" "/t:GetTargetPath" "/p:ProjectFilename=c:\Users\Vishal.Singh\AzureFunctionsPOCs\AzureFunctionsPOCs.csproj" "/p:TargetOutputFilename=C:\Users\VISHAL~1.SIN\AppData\Local\Temp\temp_1564460477402_22012_2.tmp"

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:299:12
ChildProcess.emit events.js:182:13
maybeClose child_process.js:962:16
Process.ChildProcess._handle.onexit child_process.js:251:5
```

</details>

**Comment by bwateratmsft** [comment]
@philliphoff Looks like a failure in the GetTargetPath magic. @vishal9458425389 , are you able to share your AzureFunctionsPOCs.csproj file?

**Comment by vishal9458425389** [comment]
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.3"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by vishal9458425389** [comment]
![image](https://user-images.githubusercontent.com/37198555/62337472-6587e180-b4f2-11e9-9a81-2dfc04f7521e.png)

**Comment by bwateratmsft** [comment]
@vishal9458425389 can you try this?

1. Copy and paste this MSBuild target into a file:
```
<Project>
    <Target Name="GetTargetPath">
        <MSBuild
            Projects="$(ProjectFilename)"
            Targets="GetTargetPath">
        <Output
            TaskParameter="TargetOutputs"
            ItemName="TargetOutput" />
        </MSBuild>
        <Message
            Importance="High"
            Text="@(TargetOutput)" />
    </Target>
</Project>
```

2. Call it with the following arguments (filling in the path to that target file you just created):
`dotnet msbuild C:\PATH\TO\ABOVE\TARGET\file.tmp /t:GetTargetPath /p:ProjectFilename=c:\Users\Vishal.Singh\AzureFunctionsPOCs\AzureFunctionsPOCs.csproj`

Can you share the output from that? Thanks!
