### ISSUE TITLE
xe

### ISSUE THREAD

**Issue by lackeda** [microsoft/vscode-docker#1171]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:361:320208
```

</details>

**Comment by philliphoff** [comment]
@lackeda You can add the `appProject` or `appFolder` properties to your debug configuration like shown below. Note that you need only specify `appProject` or `appFolder`, not both.

```
{
    "configurations": [
        {
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "appProject": "${workspaceFolder}/project/project.csproj",
            "appFolder": "${workspaceFolder}/project"
            "dockerBuild": {
                // Image customizations
            },
            "dockerRun": {
                // Container customizations
            }
        }
    ]
}
```

If neither of those work, let me know and, please, provide any additional details about your project that you can (e.g. the hierarchy of (project) files within the workspace).

**Comment by lackeda** [comment]
tks

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
