### ISSUE TITLE
Docker sent me this error message.  When I tried running a container from VScode.  

### ISSUE THREAD

**Issue by rickbeacham** [microsoft/vscode-docker#1172]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint docker-magento-php7_web_1 (2e9a96313de357c2148518ee20f2b4fe3e75aaf6cb465d000bfb72ef62275b3d): Bind for 0.0.0.0:443 failed: port is already allocated 

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@rickbeacham please add repro steps
