### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by raphaelgiovanini** [microsoft/vscode-docker#1175]
Repro steps:

1.
2.

Action: vscode-docker.networks.remove
Error type: 403
Error Message: (HTTP code 403) unexpected - none is a pre-defined network and cannot be removed 

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: pt-br

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@raphaelgiovanini please add repro steps and expected behavior. Seems like docker won't you let you remove the 'none' network
