### ISSUE TITLE
VSCode:No matching resources found

### ISSUE THREAD

**Issue by ravikumar-singi** [microsoft/vscode-docker#1178]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: Error
Error Message: No matching resources found.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
ContainersTreeItem.<anonymous> extension.bundle.js:31:103770
o extension.bundle.js:31:98683
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ravikumar-singi please add repro steps to this issue. Seems like you may not have any stopped containers
