### ISSUE TITLE
TOTP (2fa) failure

### ISSUE THREAD

**Issue by danwdart** [microsoft/vscode-docker#1182]
Repro steps:
1. Have Docker with 2fa
2. Login

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@danwdart that seems like a somewhat common linux error related to `gnome-keyring`. Check out https://github.com/MicrosoftDocs/live-share/issues/224, which has suggested steps to fix
