### ISSUE TITLE
Support multi-select in 'containers' list

### ISSUE THREAD

**Issue by 1138-4EB** [microsoft/vscode-docker#1184]
When multiple stopped containers need to be removed, it would be useful to be able to select all of them with Ctrl or Shift and/or through checkboxes, and then right-click once only.

My use case is removal, but I believe the same feature can be useful for stopping, restarting, viewing the logs, attaching, etc.

**Comment by EricJizbaMSFT** [comment]
@1138-4EB this is already possible if you run "Docker Containers: Remove" from the command palette (View -> Command Palette)

It's not yet supported directly in the tree, but that's tracked here: https://github.com/microsoft/vscode-docker/issues/331
