### ISSUE TITLE
Error Message: connect EACCES /var/run/docker.sock

### ISSUE THREAD

**Issue by coderyangyangyang** [microsoft/vscode-docker#1185]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@coderyangyangyang is Docker installed and running? Please add repro steps

**Comment by coderyangyangyang** [comment]
There ia no error when I just reboot

> @coderyangyangyang is Docker installed and running? Please add repro steps
