### ISSUE TITLE
Execute in bash error (name of container undefined)

### ISSUE THREAD

**Issue by nlaplante** [microsoft/vscode-docker#1190]
When choosing "Execute in bash" from container context menu, the resulting command printed in the terminal puts *undefined* instead of container name.

Example:

Right click on "TEST" container, click on "Execute in bash".

Resulting command in terminal is: `docker exec -it undefined bash`

VS Code 1.36.1, Windows 10

**Comment by EricJizbaMSFT** [comment]
@nlaplante can you show a screenshot of the context menu? I don't think we provide an "Execute in Bash" command. Perhaps another extension is providing that?

This is what I see:
![Screen Shot 2019-08-07 at 8 29 54 AM](https://user-images.githubusercontent.com/11282622/62635975-9058a800-b8ed-11e9-8b5f-e0950ce9e773.png)

**Comment by WizBangCrash** [comment]
@EricJizbaMSFT  I get the same error. I have a lot more commands available in the context menu. Where are they all coming from :-)
![Screenshot 2019-08-10 at 18 50 18](https://user-images.githubusercontent.com/3075593/62825207-ea809400-bb9f-11e9-8414-bb1a016a813d.jpg)

**Comment by nlaplante** [comment]
![image](https://user-images.githubusercontent.com/141054/62841882-25a3c580-bc7b-11e9-8e0c-06de4887f6d8.png)

**Comment by bwateratmsft** [comment]
It looks like you are using the [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) extension. The repo for that extension is here: https://github.com/formulahendry/vscode-docker-explorer
