### ISSUE TITLE
Help me Container error???

### ISSUE THREAD

**Issue by nsw78** [microsoft/vscode-docker#1191]
Repro steps:

1.
2.

Action: vscode-docker.containers.restart
Error type: 500
Error Message: (HTTP code 500) server error - Cannot restart container 42d8c5b1ec190d6b244a07381607ef376ac81d6f147b5e98461d888901c41c91: Cannot kill container 42d8c5b1ec190d6b244a07381607ef376ac81d6f147b5e98461d888901c41c91: unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused "permission denied"
: unknown 

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@nsw78 please add repro steps
