### ISSUE TITLE
Allow attachShellCommand to support login shells

### ISSUE THREAD

**Issue by Ace-Cassidy** [microsoft/vscode-docker#1197]
I want to be able to attach to my docker container as: 
 docker exec -it HASH /bin/bash --login
but giving setting: "docker.attachShellCommand.linuxContainer": "/bin/bash --login"
does not seem to pick up the --login flag

Please support flags or add a setting for attachShellCommand.linuxContainer.flags

**Comment by bwateratmsft** [comment]
Related to #363

**Comment by bwateratmsft** [comment]
This will be fixed by #1596 so I will dupe this to that.
