### ISSUE TITLE
Honor the Docker context when running in WSL 2

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#1199]
I believe this is related to how dockerode works; however, I'm pretty sure the host/socket can be overridden when instantiating a new Docker instance so it may not actually be a bug with dockerode.

On Windows 10 (18950) running WSL 2 with the Docker Desktop WSL 2 Technical Preview. The TP separates the Windows and WSL contexts to prevent destructive operations and Dockerode only accesses the Windows context. For example, on Windows, with WSL 2 enabled I see this (notice that wsl is active)

![image](https://user-images.githubusercontent.com/1186948/62584478-9442e680-b869-11e9-94d2-814c5d97dd57.png)

Running `$ docker ps` and `$ docker images` shows the containers and images running in WSL no matter when shell I access Docker from. With the extension in UI mode, I get the containers running within the default Windows context.

This may appear to be working as expected since UI shows Windows and Workspace shows WSL, but it's a **damn** confusing experience for existing extension users who enable WSL 2 and install the technical preview expecting to see containers running in WSL (the same as they see from PowerShell). If the context were honored the same way, the workspace/ui separation wouldn't be an issue for Windows WSL 2 users.

**Comment by ksawerykarwacki** [comment]
Further more to run docker-compose from windows you have to set DOCKER_HOST to the endpoint within wsl2 which brakes everything as extension says that DOCKER_HOST is not valid.

**Comment by Will-Blackburn** [comment]
I've been fighting with this for the last few days, Bash and Windows working with WSL2 but the UI for VSCode is running on Windows for Docker and I've not found a way to make it work with WSL

**Comment by bwateratmsft** [comment]
Upstream dockerode issue: https://github.com/apocas/dockerode/issues/526

**Comment by mcauto** [comment]
I use Docker explorer in WSL2

but, Do not use with vscode-docker. Affect each other. 

![image](https://user-images.githubusercontent.com/15080806/66170455-3e2ecb80-e67f-11e9-98e9-02581fd2efdd.png)
