### ISSUE TITLE
Docker Lint: Support ARG before FROM

### ISSUE THREAD

**Issue by avluis** [Microsoft/vscode-docker#120]
Support for using `ARG` before a `FROM` command was added in 17.05  | [issue](https://github.com/moby/moby/issues/18119) | [pr](https://github.com/moby/moby/pull/31352) | [doc](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) |

Would love for lint to stop screaming at me for making use of this 💔

![capture-combined](https://user-images.githubusercontent.com/875593/29952006-1f9f2220-8e8c-11e7-9de0-176418cef38f.png)
---
*Sample Dockerfile*
```Dockerfile
ARG CODE_VERSION=5.6-apache
FROM php:$CODE_VERSION

LABEL name="PHP-CI Bundle" \
version=$CONT_IMG_VER \
maintainer="Luis E Alvarado <no-reply@avnet.ws>" \
description="PHP environment for CI"

ARG CODE_VERSION
ARG CONT_IMG_VER
ENV CONT_IMG_VER=${CONT_IMG_VER:-v0.1}

CMD php -v
```

Can be built with the following commands:
 * `docker build -f php-ci\Dockerfile -t php-ci:5.6-apache php-ci`

```PS
PS C:\git\docker-images> docker run --rm -it -p 80:80 php-ci:5.6-apache
PHP 5.6.31 (cli) (built: Aug  3 2017 23:01:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

* `docker build --build-arg CODE_VERSION=7.0-fpm -f php-ci\Dockerfile -t php-ci:7.0-fpm php-ci`

```PS
PS C:\git\docker-images> docker run --rm -it -p 80:80 php-ci:7.0-fpm
PHP 7.0.23 (cli) (built: Aug 31 2017 19:01:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

 * `docker build --build-arg CODE_VERSION=7.1-apache -f php-ci\Dockerfile -t php-ci:7.1-apache php-ci`

```PS
PS C:\git\docker-images> docker run --rm -it -p 80:80 php-ci:7.1-apache
PHP 7.1.8 (cli) (built: Aug  4 2017 18:55:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by rcjsuen** [comment]
Thank you for the bug report, @avluis! I have opened [projectatomic/dockerfile_lint#85](https://github.com/projectatomic/dockerfile_lint/issues/85) to track the error that you are seeing against the dockerfile_lint project.

You shouldn't see this error anymore in the next release of the vscode-docker extension though.

**Comment by rcjsuen** [comment]
Hi @avluis, this shouldn't be flagged as an error anymore with the new 0.0.17 release.

**Comment by avluis** [comment]
@rcjsuen Thank you for the prompt fix! Had a VS Code update and refreshed to grab this update as well.
All looks well from my end 😻
