### ISSUE TITLE
Error container

### ISSUE THREAD

**Issue by gbolivar** [microsoft/vscode-docker#1200]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 404
Error Message: (HTTP code 404) no such container - network c013ac6a262682fe56e7f9469ee894771020b8a1ca8493a80a9cce27779aebb9 not found 

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by StephenWeatherford** [comment]
@gbolivar Please provide repro steps.  Also, does it reproduce outside of vscode?  Thx.
