### ISSUE TITLE
Working with multiple docker file and docker compose

### ISSUE THREAD

**Issue by mahapatraprabhanjan** [microsoft/vscode-docker#1202]
How to specify multiple dockerfile in docker build and docker run as well as appProject in Docker: Launch .Net Core (Preview). My current configuration looks as follows. But I would like to use docker compose there by utilising docker-compose.override.yml and multicontainer apis.

> {

    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "appProject": "${workspaceFolder}/src/Services/Test/Test.Api/Test.Api.csproj",
            "dockerBuild": {
                "dockerfile": "${workspaceFolder}/src/Services/Test/Test.Api/Dockerfile"
            },
            "dockerRun": {
                "ports": [
                    {
                        "hostPort": "5101",
                        "containerPort": "80"
                    }
                ]
            }
        }
    ]
}

>

**Comment by bwateratmsft** [comment]
This is essentially .NET debug w/ Docker-compose, so I'm going to dupe it over to #840
