### ISSUE TITLE
dockerimage

### ISSUE THREAD

**Issue by sujian1988** [microsoft/vscode-docker#1205]
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sujian1988 please add repro steps
