### ISSUE TITLE
VSCode: "No matching resources found." when using with Azure Container Registry extension

### ISSUE THREAD

**Issue by nikkitan** [microsoft/vscode-docker#1207]
Repro steps:

1. Open Command Palette.
2. Search for Azure Container Registry's commands.
3. Click on Azure Container Registry: Open in Portal.
4. (Same error can also be repro-ed by clicking on Azure Container Registry: Create Registry)
5. The error will pop up at the lower right corner. It also has the message of Source: Docker(Extension).

Action: vscode-docker.registries.azure.openInPortal
Error type: Error
Error Message: No matching resources found.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:31:103770
o extension.bundle.js:31:98683
```

</details>

**Comment by EricJizbaMSFT** [comment]
@nikkitan did you connect Azure? Go to the registries view and you should see a connect button. We already changed it so that "Connect" would show up if you run an Azure command from the command palette in https://github.com/microsoft/vscode-docker/pull/1163, but that hasn't shipped yet.

**Comment by nikkitan** [comment]
@EricJizbaMSFT Yes I was connected to Azure. I firstly got this error after I used the extension of Azure Account to sign in to Azure in VSCode on an Ubuntu VM. Then I repro-ed the error on my Windows machine and I reported this issue from it.

**Comment by nikkitan** [comment]
@EricJizbaMSFT  Did you mean I need to connect to Azure Container Registry? I didn't do that step. Can you specify more where the registries view is in VSCode? Thanks!

**Comment by EricJizbaMSFT** [comment]
Click the Docker button on the left and you should see "Registries"
![Screen Shot 2019-08-12 at 11 07 40 AM](https://user-images.githubusercontent.com/11282622/62887107-7524d880-bcf1-11e9-9717-157cf0af3d58.png)

Also you should be able to see "Connect Registry..." in the command palette:
![Screen Shot 2019-08-12 at 11 08 32 AM](https://user-images.githubusercontent.com/11282622/62887148-8e2d8980-bcf1-11e9-943e-6d31245199e1.png)

And just select Azure:
![Screen Shot 2019-08-12 at 11 08 38 AM](https://user-images.githubusercontent.com/11282622/62887155-9259a700-bcf1-11e9-9e69-a881d8d27e2f.png)

**Comment by nikkitan** [comment]
> Click the Docker button on the left and you should see "Registries"
> 
> Also you should be able to see "Connect Registry..." in the command palette:
> 
> And just select Azure:

@EricJizbaMSFT Thanks! This solved my issue.

**Comment by bwateratmsft** [comment]
Looks like the same root cause as #1702.
