### ISSUE TITLE
Add option to remove volume _and_ container that's using it

### ISSUE THREAD

**Issue by hexxone** [microsoft/vscode-docker#1209]
Repro steps:

1. Using Vscode & Docker on Windows
2. Start a docker-compose stack with shared local volume
3. rename the volume in your docker-compose.yml
4. "docker-compose up -d" => the new named volume is created and showing up
5. trying to delete the old volume wont work even after restarting vscode & docker completely

Action: vscode-docker.volumes.remove
Error type: 409
Error Message: (HTTP code 409) conflict - remove stack1_data: volume is in use - [718bb945308234da47e349XXXXXXXXXXXXXXX21ae78b944e3eeb4edcc4c72b3a] 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by PrashanthCorp** [comment]
Did you try stopping the container before deleting it?

**Comment by Hexxonite** [comment]
Yes, the containers were all stopped. Even restarted Docker to make sure.

**Comment by EricJizbaMSFT** [comment]
@Hexxonite based on [this thread](https://stackoverflow.com/questions/34658836/docker-is-in-volume-in-use-but-there-arent-any-docker-containers) seems like stopping a container isn't enough. You have to remove them as well. You can do that in one of several ways as mentioned in that thread:
1. Manually remove the container if you know which one it is
1. Prune containers to remove all stopped containers
1. docker compose down

In any case, we could probably figure out which container is using the volume and give users an option to remove that first. Modified title to reflect that
