### ISSUE TITLE
why this network?

### ISSUE THREAD

**Issue by andrei-i-florentin** [microsoft/vscode-docker#1210]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ETIMEDOUT
Error Message: connect ETIMEDOUT 192.168.99.100:2376

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by PrashanthCorp** [comment]
Does this repro consistently?
