### ISSUE TITLE
Fail to start with F5

### ISSUE THREAD

**Issue by FBoucher** [microsoft/vscode-docker#1212]
Hello,
This was working a few days ago. Since then I update VSCode and .NET Core. I try with the previous .NET version (preview7) and I still have the error so I think it's more on the VSCOde (or the extension) side.

Repro steps:

1. Create a Docker Container with a .Net Core (preview 7 or 8) SDK `docker run -it --name blazor-dev -v d:/Dev/local/blazortest:/app mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview8-disco bash`
2. Install the latest Blazor WebAssembly template with the command `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7`
3. Create a new app in the ./app folder `dotnet new  blazorwasm -n blazortest -o app`
4. Open VSCode and attach it to the running container using the Docker extension.
5. Open a Folder. Select the `..` to go at the root and select the `app/` folder.
6. Press F5
7. When prompt select the *Docker Launch .NET Core container (preview)

Note: this is right after the creation of the project, no code change. If I run or package it works perfectly... but the debug doesn't.

Action: debugCoreClr
Error type: Error
Error Message: The application folder '\app' does not exist. Ensure that the 'appFolder' or 'appProject' property is set correctly in the Docker debug configuration.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppFolder extension.bundle.js:361:319606
```

</details>

**Comment by bwateratmsft** [comment]
Can you share your project, the folder structure in particular?

Also, I'm not sure I understand why you're creating a container in step 1. The Docker extension will create the container for you when you F5. At best, this container would simply be thrown away; at worst it could cause name conflicts.

**Comment by FBoucher** [comment]
I create a container so I can create an application without installing the preview SDK on my machine.
I want to "Remote develop", maybe I do something wrong here... 

The structure is the default application of .Net Core 

![2019-08-15_10-02-53](https://user-images.githubusercontent.com/2404846/63099995-2327c100-bf44-11e9-9ef2-6bcf654dea63.png)

**Comment by bwateratmsft** [comment]
The Docker extension does debugging by building on the host, mapping the output into the container, and starting it there. It is possible to make this scenario (building in the container) work, but it's tricky.

1. First, start your container, mapping in the folder for source, and ensuring it's read-write:
`docker run -dt --name DotnetSdk -v C:\Users\brandonw\source\repos\ContainerMap:/app:rw mcr.microsoft.com/dotnet/core-nightly/sdk:3.0 tail -f /dev/null`
(The `tail -f /dev/null` entry point keeps the container alive indefinitely)
2. Create the app within the container:
`docker exec -it -w /app DotnetSdk dotnet new mvc` (or similar)
3. In VSCode, open up the mapped-in folder, i.e. in my example C:\Users\brandonw\source\repos\ContainerMap.
4. When the C# extension asks to add VSCode stuff, let it do so--it'll create the launch.json and tasks.json (this step may not be necessary, but should be harmless I think?)
![image](https://user-images.githubusercontent.com/36966225/63101875-fa092f80-bf47-11e9-81ae-a9cd6848b73b.png)
5. Add Dockerfiles to your workspace. I updated the images in the Dockerfile to be the `core-nightly` images, matching the SDK image I'd chosen above.
6. Add to tasks.json:
```
        {
            "label": "container-build",
            "type": "shell",
            "command": "docker",
            "args": [
                "exec",
                "-it",
                "-w",
                "/app",
                "DotnetSdk",
                "dotnet",
                "build"
            ]
        }
```
7. Add to launch.json:
```
        {
            "name": "Docker: Launch .NET Core (Preview)",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "container-build",
            "dockerBuild": {},
            "dockerRun": {}
        },
```
8. F5 and enjoy!

It is worth noting--for debug builds, Blazor essentially assumes you are building and running in exactly the same place. It uses a manifest XML that tells it where to find static assets (i.e. any Blazor components you consume from a Razor class library, or NuGet packages); this manifest contains paths matching whatever is the case where it is built. If you build in a Linux container and run in a separate Linux container, it may work by coincidence, if the paths to the NuGet cache and the solution are the same.

You could also configure a task to automatically launch that DotnetSdk container if needed, but I'll leave that as an exercise to the reader. :)

**Comment by FBoucher** [comment]
Thanks.
I forgot to mention I as attaching the C# extension also.
It was working last week... but that I'll adapt.
:)
