### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by diarraba60** [microsoft/vscode-docker#1214]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by EricJizbaMSFT** [comment]
@diarraba60 make sure Docker is installed and running. If it is and you still see this issue, please add repro steps
