### ISSUE TITLE
Run/Run Interactive: do not specify -rm

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docker#1217]
I am using the Docker extension to create a container from an image and I picked the "Run Interactive" command. To my surprise all my data was lost when the container stopped. This seems to be due to the -rm option that is passed.

I suggest to not add this.

@chrmarti cc

**Comment by xgdgsc** [comment]
I lost my 2 hours of config because of this!

**Comment by bwateratmsft** [comment]
This will be fixed by #1596 so I will dupe this one to that.

**Comment by chrmarti** [comment]
@bwateratmsft The change to fix #1596 seems to keep `--rm` in (https://github.com/microsoft/vscode-docker/pull/1649/files).

**Comment by bwateratmsft** [comment]
@chrmarti Yes; by design. But it's trivial to customize now.
