### ISSUE TITLE
Group "Attach" actions closer together

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docker#1218]
In this case:

![image](https://user-images.githubusercontent.com/900690/63329609-8c3b7a00-c332-11e9-8025-06994c2f05af.png)

I suggest to have the "Attach" actions grouped together.

**Comment by bpasero** [comment]
Suggestion:
Attach Shell
Attach VSC
---------
Inspect
View Logs
---------
Stop
Restart
----------
Remove

**Comment by bwateratmsft** [comment]
@bpasero The "Attach Visual Studio Code" command is part of a different extension, https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers. Can you file this to their repository here? https://github.com/microsoft/vscode-remote-release

**Comment by bpasero** [comment]
I filed https://github.com/microsoft/vscode-remote-release/issues/1215 but it will not mean anything unless you put that action into a group that the other can pick it up.
