### ISSUE TITLE
Problem with start contener after create from image

### ISSUE THREAD

**Issue by qshmobile** [microsoft/vscode-docker#1222]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint gitlab (11303a16273c9d995e84f3fc2ff393a837ffe09c0125f2416a47b3525fc15e96): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use 

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
IncomingMessage.EventEmitter.emit domain.js:442:20
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @qshmobile,

Thanks for reporting this issue. Could you provide repro steps?

**Comment by sgreenmsft** [comment]
My read of that error is that localhost port 80 is in use and so Docker cannot allocate the port.  Steps to reproduce would look like:
1) Run a container: docker run -dt -p 8822:8822 --entrypoint tail mcr.microsoft.com/dotnet/core/sdk:2.2 -f /dev/null
2) In VS Code, stop the container that was just started
3) Run another container: docker run -dt -p 8822:8822 --entrypoint tail mcr.microsoft.com/dotnet/core/sdk:2.2 -f /dev/null
4) In VS Code, attempt to start the first (stopped) container.

**Comment by bwateratmsft** [comment]
@sgreenmsft I'm not really sure this is actionable. There's infinitely many things that could be holding port 80.

**Comment by sgreenmsft** [comment]
Similar to VS, a better error message would be an improvement here.

**Comment by bwateratmsft** [comment]
This issue has been closed automagically because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
