### ISSUE TITLE
Error: connect ENOENT //./pipe/docker_engine Unable to connect windows 10 home

### ISSUE THREAD

**Issue by DmacTorstar** [microsoft/vscode-docker#1226]
Seems like same issue as : 
https://github.com/microsoft/vscode-docker/issues/576
https://github.com/microsoft/vscode-docker/issues/164

Steps to reproduce:
1. Launch docker quickstart terminal
2. login to azure registry
3. build image - success

Results:
- Azure registry shows up in sidebar
- No containers, images, volumes show up.

I am able to run the docker hello-world example with no problems.
When I use kitematic, it says docker not running, run with Virtualbox, (I dont have hyperv with home edition of windows) and it seems the hello world example.

**Comment by bwateratmsft** [comment]
@DmacTorstar Does this issue consistently reproduce? Does restarting the Docker service have any effect?
