### ISSUE TITLE
adding docker private registry

### ISSUE THREAD

**Issue by geekzoo** [microsoft/vscode-docker#1229]
Repro steps:

Kubuntu <<
lsb_release -a provides
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

1. add a private docker registry url
2. provide username
3. provide password

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

**Comment by bwateratmsft** [comment]
@geekzoo This issue looks like it may be with the Docker CLI itself. Can you open an issue at their [GitHub repo](https://github.com/docker/cli)?

There are many issues that resemble this one, not all of them with Docker:
https://github.com/moby/buildkit/issues/1078
https://github.com/Foundry376/Mailspring/issues/681
