### ISSUE TITLE
No docker configuration in debug add configuration/intellisense

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#123]
why doesn't the docker attach option show up here?

![image](https://user-images.githubusercontent.com/1487073/30524747-0a43f692-9bae-11e7-98c6-abbc8ae41d6c.png)

**Comment by lostintangent** [comment]
Is this a dupe of #49? I had thought we just needed to declare a "debug snippet"'for the extension.

**Comment by chrisdias** [comment]
yep. its sunday morning, didn't feel like searching :)

**Comment by lostintangent** [comment]
Understood :)
