### ISSUE TITLE
Add pickDockerContainer command

### ISSUE THREAD

**Issue by scabana** [microsoft/vscode-docker#1235]
Would be equivalent to command:pickDockerContainer from omnisharp. This would enable to have a single launch task that looks like this: 
```json
{
  "name": ".NET Core Docker Attach",
  "type": "coreclr",
  "request": "attach",
  "processId": "${command:pickRemoteProcess}",
  "pipeTransport": {
    "pipeProgram": "docker",
    "pipeArgs": [ "exec", "-i", "${command:pickDockerContainer}" ],
    "debuggerPath": "/vsdbg/vsdbg",
    "pipeCwd": "${workspaceRoot}",
    "quoteArgs": false
  }
}
```
instead of having 1 launch task per container.

**Comment by scabana** [comment]
Would you take a contribution on this?

**Comment by EricJizbaMSFT** [comment]
@scabana can you describe the scenario when you would use this launch.json? I'd like to hear more about the problem you're trying to solve before we go straight to the fix. Specifically @bwateratmsft is working on some .NET Core debugging features and I wonder if his work could simplify your debugging experience so that you don't have to pick the process/container each time

**Comment by scabana** [comment]
@EricJizbaMSFT For a microservice architecture, where a lot of microservices are generated from a template. Most of the time, the remote attach is to debug docker-compose ran automated tests. In that case, we can have from 2-5 containers up for a single run into which we could want attach. If a command would exist, this would mean we could have a config without specific container names hard coded into launch.json. It also helps out when running a single image in the same microservice. The goal here is to run the same docker-compose as the pipeline would run reducing the "works on my machine, but not on the pipeline" scenario.

**Comment by bwateratmsft** [comment]
At the moment I don't have any plans for .NET Core _attach_ (just launch) so I think this work is different from what I'm working on.

**Comment by bwateratmsft** [comment]
Yes, I agree.
