### ISSUE TITLE
Can we just skip it?

### ISSUE THREAD

**Issue by veonua** [microsoft/vscode-docker#1236]
Repro steps:

try to pull image from azure repository

Action: vscode-docker.registries.pullImage
Error type: string
Error Message: WARNING! Your password will be stored unencrypted in /home/veon/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

**Comment by bwateratmsft** [comment]
@veonua I'm not sure exactly what this is asking for, have you tried following the steps within the [link](https://docs.docker.com/engine/reference/commandline/login/#credentials-store)?

**Comment by veonua** [comment]
what if i don’t want to encrypt my password, can we just ignore the warning

**Comment by bwateratmsft** [comment]
Obviously I cannot recommend keeping your password in cleartext anywhere as it is a severe security risk. Unfortunately there isn't a way to work around this other than to configure a credential helper. The Docker CLI emits both warnings and errors to stderr, and the code as-written will raise an exception if there is any output to stderr.

**Comment by veonua** [comment]
So plug-in doesn't work without credential helper. Which is optional for docker itself

Andrew

**Comment by bwateratmsft** [comment]
Changing to dupe of #1296
