### ISSUE TITLE
Could not  pull responsitry

### ISSUE THREAD

**Issue by xusai2014** [microsoft/vscode-docker#1237]
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username xusai2014 --password-stdin
Error saving credentials: error storing credentials - err: no credentials server URL, out: `no credentials server URL`

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:182:13
maybeClose child_process.js:961:16
Process.ChildProcess._handle.onexit child_process.js:248:5
```

</details>

**Comment by bwateratmsft** [comment]
@xusai2014 This issue looks like it may be with the Docker CLI itself. Can you open an issue at their [GitHub repo](https://github.com/docker/cli)?
