### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by CorrieScheepers2** [microsoft/vscode-docker#1239]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint latex_dev_texhost_1 (f29165ac097f4c71075f8eb2d580f0175ccc97c141341d72701a3adc0b83f140): Error starting userland proxy: listen tcp 0.0.0.0:4000: bind: An attempt was made to access a socket in a way forbidden by its access permissions. 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404extension.bundle.js:157:579404
extension.bundle.js:157:579367extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@CorrieScheepers2 Can you add repro steps? Does restarting Docker have any effect?
