### ISSUE TITLE
Allow to disable custom explorer view on startup

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode-docker#124]
Every time a new project is opened, Docker will create a custom explorer view. Although VSCode allow users to hide custom explorer views out of the box, doing this hiding stuffs on multiple projects is quite tedious. By allowing Docker users to disable custom explorer view at all help reduce these kind of task a lot.

I don't see if VSCode already provide an option to disable any custom explorer view by default. So that's why I open this issue.

**Comment by chrisdias** [comment]
Agreed, it can be annoying.  I'll add a configuration option to not show the explorer contribution, should be able to get this published today. 

Also, i'll file an issue on VS Code to not persist explorer state on workspaces, but globally.

**Comment by spywhere** [comment]
@chrisdias That's already done [here](https://github.com/Microsoft/vscode/issues/34557) :)

**Comment by chrisdias** [comment]
@spywhere ah, good, i'll close my issue. thanks :)
