### ISSUE TITLE
Error when delete network

### ISSUE THREAD

**Issue by lucasscarduelli** [microsoft/vscode-docker#1248]
Repro steps:

1.
2.

Action: vscode-docker.networks.remove
Error type: 403
Error Message: (HTTP code 403) unexpected - bridge is a pre-defined network and cannot be removed 

Version: 0.7.0
OS: linux
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:579404
extension.bundle.js:157:579367
module.exports.m.buildPayload extension.bundle.js:157:579377
IncomingMessage.<anonymous> extension.bundle.js:157:578877
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
I'm not sure what the problem is here? `bridge` is a pre-defined network and cannot be removed; this is Docker's decision, not ours.
