### ISSUE TITLE
performance issues vusual studio code

### ISSUE THREAD

**Issue by DJGHOSTMACHINE** [microsoft/vscode-docker#1249]
Repro steps:

1.
2.

Action: vscode-docker.volumes.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by bwateratmsft** [comment]
@DJGHOSTMACHINE Is Docker installed and running?
