### ISSUE TITLE
suggestion: change prune icon to something more prune-ish

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#125]
and perhaps prompt before running prune

**Comment by jpstrikesback** [comment]
First, thanks for your hard work on this plugin!!

Third, please bring the prompt back, typically destructive ops are confirmed  :/ cautionary tale follows:

The icon was great, although I thought it was to close the side pane. Alas, I was wrong, I'll be restoring from a backup tmrw...

**Comment by driskell** [comment]
I am running 0.0.24 and it seems to not prompt me at all. Clicking it results in no prompt. Looking at the commit it seems it should be in 0.0.24 - is it not working?

I clicked refresh and accidentally clicked the button (which I didn't know what it was at the time). Pruning sounded innocent until I realised it wiped my entire Docker setup...

**Comment by chrisdias** [comment]
set the `docker.promptOnSystemPrune` setting to `true` (it is `false` by default) to be prompted.

**Comment by driskell** [comment]
Thanks - probably no need to set the prompt as I now know what happens. For other new users I raised a pull request to change the default so they can learn to be super careful around the button, and learn it from the prompt rather than the action 👍  :)
