### ISSUE TITLE
docker-vscode issue

### ISSUE THREAD

**Issue by saidevops55** [microsoft/vscode-docker#1251]
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login  --username chandusai95 --password-stdin
unable to resolve docker endpoint: open C:\Users\ADMIN\.docker\machine\machines\default\ca.pem: The system cannot find the file specified.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:299:12
ChildProcess.emit events.js:182:13
maybeClose child_process.js:962:16
Process.ChildProcess._handle.onexit child_process.js:251:5
```

</details>

**Comment by bwateratmsft** [comment]
@saidevops55 Can you add repro steps?
