### ISSUE TITLE
visual studio code

### ISSUE THREAD

**Issue by swiddmim** [microsoft/vscode-docker#1252]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.7.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:361:320208
```

</details>

**Comment by bwateratmsft** [comment]
@swiddmim Can you add repro steps? In cases where the csproj/fsproj is not easily located, you need to set either appFolder or appProject in the launch.json config for Docker .NET Core debugging.

**Comment by swiddmim** [comment]
Sorry but this is my first time of using it so I don’t know how to do it. Can you please have more details instructions please.

Tuyen Le
2293388307


________________________________

**Comment by bwateratmsft** [comment]
@swiddmim No problem! Can your share your launch config from .vscode/launch.json? Essentially, what is needed is to add the .NET Core project file (csproj, fsproj, etc.) to the project you wish to debug, like this:

![image](https://user-images.githubusercontent.com/36966225/64490082-91039780-d227-11e9-9b22-631446bfdb02.png)

**Comment by swiddmim** [comment]
I added it but still doesn't work.
________________________________

**Comment by bwateratmsft** [comment]
Can you share your workspace?

**Comment by swiddmim** [comment]
[cid:772a2636-ae26-4690-994b-1c483ab4358d]
________________________________

**Comment by bwateratmsft** [comment]
Can you try again? It seems nothing came through.
