### ISSUE TITLE
The container auto removed for .NET Core Console applications on Mac and Win10

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1263]
**OS:** Win10 & Mac
**Build Version**: [20190909.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9611)

**Repro Steps:**
1. Create a new .NET Core Console application by command "dotnet new console --name test".
2. Open the new created application in VS Code.
3. Wait for and respond "yes" when prompted to add required assets to build and debug like below.
![image](https://user-images.githubusercontent.com/34729092/64690073-25892680-d4c2-11e9-8e46-19d65de64121.png)
4. F1 --> Type and select "Docker: Add Docker files to workspace" --> ".NET Core Console" --> Linux -->Add "Docker : Launch .NET Core ASP.NET (Preview)" configuration.
5. Debug.
![image](https://user-images.githubusercontent.com/34729092/64690240-7bf66500-d4c2-11e9-8b40-1308ee1c2f7b.png)
6. Check the Output window.

**Expect:**
The container doesn't auto remove.

**Actual:**
The container auto removed .
![image](https://user-images.githubusercontent.com/34729092/64690303-a0ead800-d4c2-11e9-81d8-b3cbd7403918.png)

**More Info:**
This issue doesn't reproduce on Linux.

**Comment by bwateratmsft** [comment]
This behavior is intentional; if it's not removing on Linux we have a bug there. With the work Phil and I are doing in #1245, there will be an option in the launch configuration, default on, to remove the container after debugging.
