### ISSUE TITLE
The browser window displaying "Hello World!" doesn't open after debugging a .NET Core ASP.NET application

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1264]
**OS:** Linux
**Build Version**: [20190909.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9611)

**Repro Steps:**
1. Create a new .NET Core ASP.NET application by "dotnet new web --name test".
2. Open this application in VS Code.
3. Wait for and respond "yes" when prompted to add required assets to build and debug like below.
![image](https://user-images.githubusercontent.com/34729092/64690676-8bc27900-d4c3-11e9-859f-b41728c7374c.png)
4. F1 --> Type and select "Docker: Add Docker Files to Workspace..." --> ASP .NET Core --> Linux --> Enter one port --> Add "Docker : Launch .NET Core (Preview)" configuration.
5. Debug.
![image](https://user-images.githubusercontent.com/34729092/64690826-e8259880-d4c3-11e9-9618-2f676172c0c7.png)

**Expect:**
Succeed to debug and a browser window opens and display "Hello World!".

**Actual:**
Succeed to debug but no matched browser window opens. And there is no new website displaying "Hello World!"  when opening the Firefox Browser manually.

**Comment by bwateratmsft** [comment]
Potentially a regression from SSL changes; I'll take a look.
