### ISSUE TITLE
error to create Dockerfile by VS Code

### ISSUE THREAD

**Issue by dsouzasccp** [microsoft/vscode-docker#1269]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: EPERM
Error Message: EPERM: operation not permitted, open 'c:\docker-compose.yml'

Version: 0.8.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.openSync fs.js:436:3
Object.module.ELECTRON_ASAR.js:160:31
Object.writeFileSync fs.js:1168:35
extension.bundle.js:1:287978extension.bundle.js:1:287978
```

</details>

**Comment by bwateratmsft** [comment]
@dsouzasccp Can you add repro steps? Usually the root C:\ folder is ACL'd to admins only; if you ran VSCode unelevated you most likely cannot add Dockerfiles there. Try moving your source to a different place or giving your user account permissions at that folder.
