### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Doldragon001** [microsoft/vscode-docker#1273]
Repro steps:

1.
2.

Action: vscode-docker.containers.attachShell
Error type: Error
Error Message: No matching resources found.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
ContainersTreeItem.<anonymous> extension.bundle.js:31:86243
o extension.bundle.js:31:80784
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by bwateratmsft** [comment]
@Doldragon001 Can you add repro steps?
