### ISSUE TITLE
intelli-sense not working (conflict?)

### ISSUE THREAD

**Issue by proclaim** [Microsoft/vscode-docker#128]
if I type as usual, intelli-sense won't show up, but if I have a colon, it'll recognize it

![sep-21-2017 15-30-38](https://user-images.githubusercontent.com/2252778/30684111-8cce0986-9ee2-11e7-88ac-348184cb342a.gif)

not sure if it's just me or conflict with other package

**Comment by dodalovic** [comment]
For me intellisense only works in `Dockerfile`, in `docker-compose.yml` doesn't work at all.

MacOS Sierra, latest stable vscode

**Comment by franky47** [comment]
I have the same issue, same setup as @dodalovic.

**Comment by aparajita** [comment]
Same here.

**Comment by mbotmcc** [comment]
same issue here

**Comment by mpavkovic** [comment]
Same thing for me on Linux, IntelliSense doesn't work in `docker-compose.yml`

**Comment by BruceWangTRT** [comment]
On Mac OS, IntelliSense does not work on docker-compose.yml

**Comment by StephenWeatherford** [comment]
So apparently in Dockerfile Intellisense shows up automatically, whereas with docker-compose.yml you have to press CTRL+SPACE to get suggestions.

In other file types (e.g. .ts), I'm seeing autocomplete coming up mostly by itself.

Current work-around: Use CTRL+SPACE

**Comment by StephenWeatherford** [comment]
Tracked by #243.

**Comment by StephenWeatherford** [comment]
And thanks Remy @rcjsuen for the hint.
