### ISSUE TITLE
CONTAINERS: Failed to connect.

### ISSUE THREAD

**Issue by shi2yu3** [microsoft/vscode-docker#1280]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:23750

Version: 0.8.1
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.39.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1054:14
```

</details>

**Comment by bwateratmsft** [comment]
@shi2yu3 Can you add repro steps? What is your Docker configuration?

**Comment by shi2yu3** [comment]
Seems it is due to the Windows upgrade which caused WSL being uninstalled. It works again after re-installing WSL.

Thanks,
Yu

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Brandon Waterloo [MSFT] <notifications@github.com>
发送时间: Tuesday, September 17, 2019 10:50:05 AM
收件人: microsoft/vscode-docker <vscode-docker@noreply.github.com>
抄送: shi2yu3 <shi2yu3@live.com>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/vscode-docker] CONTAINERS: Failed to connect. (#1280)


@shi2yu3<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshi2yu3&data=02%7C01%7C%7Cb0e034b6685549370d0d08d73b9779a0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637043394071963657&sdata=Je2EN8PSuXPHHO8iy0rexXa%2BgyJe%2FLW64gIs7m0anzw%3D&reserved=0> Can you add repro steps? What is your Docker configuration?

―

**Comment by bwateratmsft** [comment]
Ah, glad it's working now!
