### ISSUE TITLE
Quota exceeded for resource type webhooks

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-docker#1281]
Repro steps:

1. Right click on a image in an Azure Container Registry
2. Deploy Image to Azure App Service
3. Repeat until you get the following error (I see it when trying to create the 3rd webhook on basic sku)

The error makes sense, but it's still annoying because it happens _after_ all of the long running operations to create an app service plan/web app. Perhaps we can detect this ahead of time and warn users _before_ all of that? Also - should we allow them to deploy without setting up a webhook?

Action: vscode-docker.registries.deployImageToAzure
Error type: QuotaExceeded
Error Message: Quota exceeded for resource type webhooks for the registry SKU Basic. Learn more about different SKU quotas and upgrade process: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus

Version: 0.8.1
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.39.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:332:208419
s extension.bundle.js:218:8615
s extension.bundle.js:157:287391
extension.bundle.js:157:288631
o extension.bundle.js:218:7060
extension.bundle.js:157:286312
$._callback extension.bundle.js:31:90211
$.callback extension.bundle.js:187:5469
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:187:18282
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:187:17124
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment]
Looks like in basic SKU the quota for webhooks is 2, so it really wouldn't take long to hit that.

**Comment by Abdelkrim** [comment]
@EricJizbaMSFT  delete the unnecessary webhooks 

1. Click on https://portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.ContainerRegistry%2Fregistries
2. Select the registry
3. Click on `webhooks`
4. Select the `webhook` you want to delete
5. Hit `Delete`
