### ISSUE TITLE
Promote Nightly version of the Docker extension

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1284]
(Title)

**Comment by EricJizbaMSFT** [comment]
We already have a nightly build definition:
https://dev.azure.com/ms-azuretools/AzCode/_build?definitionId=16

And here are our current instructions for people to try out insider versions of the extension (points to latest master build, not nightly build):
https://aka.ms/azCodeInsiders

Not opposed to improvements - just telling you what we have already

**Comment by bwateratmsft** [comment]
We mean to release it on the extension marketplace so it has more visibility.

**Comment by bwateratmsft** [comment]
Depends on https://github.com/microsoft/vscode-azuretools/pull/599

**Comment by bwateratmsft** [comment]
@roblourens, I saw that you implemented the nightly setup for the Remote - SSH extension, which I've been using as inspiration for this. What would you say the positives and negatives of a nightly extension release have been? Any considerations we should make before we go ahead and do it ourselves?

**Comment by roblourens** [comment]
The positives are that I can easily push a possible fix for an issue and have someone try it out, without doing a full release to 100% of users. And when people use it, I get early feedback about new issues. Of course, you have to work harder to keep master stable because it will be constantly released to people.

**Comment by bwateratmsft** [comment]
@roblourens Any strategies that have been particularly helpful for maintaining high master branch quality, aside from the obvious "test _before_ merge"?

**Comment by roblourens** [comment]
CI running the build and tests is key. I am the only person committing to the remote-ssh repo so it's easy for me to handl eit, but if there were more people, I would set up something like a bot to ping people when the build breaks, which have in the vscode repo.

**Comment by bwateratmsft** [comment]
Resolving now, "fixed" with #1408
