### ISSUE TITLE
Pop up an error when debugging a ASP.NET MVC web app

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1286]
**OS:** Win10
**Build Version:** [20190918.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10136)
**.NET Core Version**: 2.2.401
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new ASP.NET MVC web app by "dotnet new mvc --no-https --name test1".
2. Open this project in VS Code.
3. Select "Yes" when asked whether add the required assets to build and debug or not.
![image](https://user-images.githubusercontent.com/34729092/65238900-5a275e80-db10-11e9-9214-2b56146723d2.png)
4. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core -->Linux -->Port : 80,443.
5. Navigate to "File Explorer" -->"Test1" project --> "Controllers" folder -->Open "HomeController.cs" -->Set a breakpoint in the Index() method.
6. Go to the Debug tab --> Select the Docker launch profile --> Debug.
![image](https://user-images.githubusercontent.com/34729092/65239238-1b45d880-db11-11e9-9842-13fc7453475d.png)

**Expect:**
Succeed to debug and the breakpoint can be hit.

**Actual:**
Pop up below error.
![image](https://user-images.githubusercontent.com/34729092/65239259-27ca3100-db11-11e9-99d6-72c2c5bf00f5.png)
![image](https://user-images.githubusercontent.com/34729092/65239392-77106180-db11-11e9-8004-489f2fc6f899.png)

**Comment by bwateratmsft** [comment]
Looks like the vsdbg script isn't getting bundled correctly; I'll take a look.

**Comment by v-dantch** [comment]
Got it. Thanks for your quick response.
