### ISSUE TITLE
New Feature: Add badge/Annotation to sidebar for number of running containers

### ISSUE THREAD

**Issue by marvingreenberg** [microsoft/vscode-docker#1287]
Minor.  But it would be useful to see at a glance when containers are running (just as when the editor or SCM icons show unsaved or uncommitted changes.  Philosophically it is a little analogous (OK its a stretch), since if I started containers from inside VScode I may want to close them before closing VScode.

**Comment by bwateratmsft** [comment]
I like that idea. Something like this?
![image](https://user-images.githubusercontent.com/36966225/65246483-b791c000-dabc-11e9-9962-adecd7b403d3.png)

It wouldn't be terribly simple to display containers started specifically from VSCode (we would have to label them all to know that they were created by VSCode), but showing all running containers should be simpler.

**Comment by marvingreenberg** [comment]
No, the whole business about the philosophical justification for the badge was stupid, just show the running number.

**Comment by bwateratmsft** [comment]
It looks like this would depend on https://github.com/microsoft/vscode/issues/54938.

**Comment by bwateratmsft** [comment]
It's been a long time since there have been any updates to https://github.com/microsoft/vscode/issues/62783 so it seems unlikely it will happen. I am still following that issue, but for the meantime, I will close this one to keep the Future milestone a little clearer.

**Comment by bwateratmsft** [comment]
As of VSCode 1.74.0 there is a built-in feature to hide badges, so we wouldn't need a setting anymore. https://code.visualstudio.com/updates/v1_74#_hide-badges-per-view-container

**Comment by almaceleste** [comment]
So... when will I be able to see the number of running containers in my activity bar?
Are there any obstacles?
