### ISSUE TITLE
Docker extension feedback, as per chat with Chris and Kenneth

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-docker#129]
Q and A from @chrisdias and @auchenberg 
 
Q.	you do -d and –build in launching docker compose.  should we always do a build and run detached?
A.	I always build detached because it is annoying to have the terminal reserved and have to create a new one. However, this means logs aren’t “just there” and we have to kill it later. I still think this is the best way, personally. But I’m not an advanced Docker user. So who is the audience? 

Q.	why did you set up npm scripts to run docker compose? why not just use the extension commands?  
A	Its shorter. I had a hard time remembering the exact commands.

Q	its good to see a .vscode folder in the /develop branch, will you merge that back into master?
A	I think I will. Brian Clark asked me about this too. “What id they are not using vscode?” Well, then it wont harm them  But it’s super helpful. One kicker here … the master branch is for the official 6 part docs which cover the MEAN app. The develop branch is what we are using to show security, deployment and docker. So we may have to keep it separate … or make a new repo later.

Q	can we get an extensions.json into your .vscode folder to recommend the docker extension (and perhaps the Azure ones, which will release tomorrow)?
A	I have no idea what an extension.json is … it sounds interesting … what is it? What is released now?
 
Q	the volume is for mapping the local file system to the container. This can be useful in scenarios where you want to make edits locally and have them reflected in your container. for example, you can run nodemon in the container and map in the local file system. you then edit files locally and use the container to serve up the app.  This is probably why when you looked into the container you saw a different file system – you were looking at the local file system.  It’s a little against the notion that an image is “production”. I’m thinking we remove this from the docker extension template, thoughts? 
A	I could not get this to work at all. It didn’t just map … it made the container not work. So unless we can find a way to make this more obvious, I say remove it

Q	in the docker extension I can  try to figure out the node version and create a dockerfile that has the right one (e.g. 6 or 8).
A	This may be helpful, but for –inspect … that works with node 6 and 8. So I’d just jeep --inspect

Q	in the compose file I can then try to see if its 6 or 8 and use -debug or -inspect accordingly.
A	See above

Q	No quotes on ports
A	Ok. The docs show quotes (what Kenneth pointed me at). You may want to adjust that

Q	you didn’t do the ip address below in the compose file, is there a reason you didn’t? I think I still need to add this to the template I create.
A	It worked without it.
 
Q What else do we need to do to the docker extension.  
A We can ...
  - Auto refresh the docker containers and images. They get old quick. via a setting
  - Change the icon for pruning. It runs immediately, so if we accidentally hit it, it feels destructive.
  - Consider updating the npm scripts for the docker compose and docker compose debug files. Notice the debug command is a bit lengthy to remember (see below)

    ```bash
    "docker": "docker-compose up -d --build",
    "docker-debug": "docker-compose -f docker-compose.debug.yml up -d --build",
    "docker-down": "docker-compose down",
    ```

**Comment by chrisdias** [comment]
the list...

- [x] compose with -d --build @chrisdias
- [x] auto refresh @chrisdias
- [x] prune icon, prompt @chrisdias
- [ ] update npm scripts to add docker XXXXX commands @chrisdias
- [ ] look for node version when build dockerfile and docker-compose files @chrisdias
- [ ] remove volume mapping from compose debug file (too confusing) @chrisdias
- [ ] add .vscode/extensions.json to sample repo @johnpapa

**Comment by auchenberg** [comment]
@johnpapa If you are using Node 6 with Inspector protocol, be aware that there's a bunch of issues, as the protocol shipped as experimental. It's my recommendation to either use the older V8 protocol or upgrade your Node version.

**Comment by johnpapa** [comment]
just revisiting this ...  are we ready to close?

**Comment by StephenWeatherford** [comment]
Closing, let me know if you'd like me to reopen.
