### ISSUE TITLE
Unable to pull image from registry

### ISSUE THREAD

**Issue by nakamin** [microsoft/vscode-docker#1296]
Repro steps:
Try to pull an image from docker registry from the command pallete or docker extension tab

```
Action: vscode-docker.registries.pullImage
Error type: string
Error Message: WARNING! Your password will be stored unencrypted in /home/anton/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

The full output
```
docker login  --username nakamin --password-stdin
Login Succeeded
WARNING! Your password will be stored unencrypted in /home/anton/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Error: WARNING! Your password will be stored unencrypted in /home/anton/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by bwateratmsft** [comment]
@nakamin I would highly recommend following the instructions to configure a credential store. That said we should consider making this a warning popup that does not block functionality; see also #1236.

**Comment by nakamin** [comment]
@bwateratmsft so I did all the setup with pass on Arch Linux, and `docker login` works without producing any warnings. VSCode does not show any registries, and when I try to add one it still prompts me for a password. Once I provide it I get this error
```
Action: vscode-docker.registries.connectRegistry

Error type: Error

Error Message: The name org.freedesktop.secrets was not provided by any .service files
```
![image](https://user-images.githubusercontent.com/17557668/65521507-59e3e600-deb7-11e9-89f1-6c2b65fb477d.png)

**Comment by bwateratmsft** [comment]
It seems that this error shows up in a lot of different applications:
https://github.com/vladimiry/ElectronMail/issues/34
https://bbs.archlinux.org/viewtopic.php?id=239198
https://github.com/flathub/io.lbry.lbry-app/issues/10
https://github.com/Foundry376/Mailspring/issues/681

It seems like for most of them it was resolved with `sudo apt install gnome-keyring`?

**Comment by nakamin** [comment]
I would prefer not to install another keyring manager since I already have one, I'm using KDE. I looked around the code and it seems like vscode-docker uses node-keytar to get the password, is that right? I might poke around to see what's going on then.

**Comment by veonua** [comment]
>  I would highly recommend following the instructions to configure a credential store

My passwords are not that valuable to keep them in credential storage. So it would be nice not to force this
