### ISSUE TITLE
Vertical selection and editing causes linter errors

### ISSUE THREAD

**Issue by leventyalcin** [microsoft/vscode-docker#1297]
Hi, 

I have made vertical line selection for repeating `ARG` statements and deleted the keywords in order to copy and paste them in a docker image and test something quickly instead building the whole image. 

After copying the vars I've done redo with `CMD+Z` to the original state but that confused the linter. 

What I'm seeing is irrelevant errors such as 
```
failed to process ""v1.13.1"ARG": unexpected end of statement while looking for matching double-quotedockerfile-utils(36)
```
but the line actually looks like this
```
ARG KUBECTL_VERSION="v1.13.1"
```

or seeing this error 
```
Unknown instruction: N_VERSION="V1.ARGARG17.3"dockerfile-utils(38)
```
for this line
```
ARG YARN_VERSION="v1.17.3"
```

If I delete all the `ARG` keyword and type it one by one, the linter error disappears (or reloading the file helps).

![output](https://user-images.githubusercontent.com/1218537/65421967-0ad97a80-ddfd-11e9-803b-6e474011aa64.gif)

```
$ code --version 
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95

$ uname -o -i -m
x86_64 MacBookPro15,1 Darwin
```

**Comment by bwateratmsft** [comment]
@rcjsuen This one is part of the language server, right? (Forgive my limited understanding, I think it's syntax colorization comes from VSCode in the `tmLanguage` file, and linting / intellisense comes from your language server?)

**Comment by rcjsuen** [comment]
@bwateratmsft Yes, this is coming from the language server. Thanks for the ping.

I think more investigation is required as I was able to reproduce the problem and then when I tried it again I couldn't reproduce the problem. :(

**Comment by bwateratmsft** [comment]
I reopened this one over in https://github.com/rcjsuen/dockerfile-language-service/issues/51.
