### ISSUE TITLE
unable to remove docker container

### ISSUE THREAD

**Issue by suhasmshetty** [microsoft/vscode-docker#1298]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: 409
Error Message: (HTTP code 409) unexpected - a prune operation is already running 

Version: 0.8.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@suhasmshetty can you add repro steps? Did you click Prune more than once in quick succession?
