### ISSUE TITLE
 failed to create endpoint condescending_mclean on network

### ISSUE THREAD

**Issue by demasj** [microsoft/vscode-docker#1299]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - failed to create endpoint condescending_mclean on network nat: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20) 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by demasj** [comment]
For some reason I'm not able to reproduce the problem anymore but for the whole picture.

I was trying to run docker SQL2017 linux-latest with the default port 1433 mapped to 1433
apparently this caused a problem with my local SQL server installation that also used the default port 1433
After changing the container port parameter  -p 1433:1433 to -p 14333:1433 It starts working

**Comment by bwateratmsft** [comment]
Ah, that is behaving as intended; the same port on the host can't be mapped to both the local SQL instance and the container. Unfortunately the error message is not very clear, but we've previously engaged with Docker Inc. to improve their error messages.
