### ISSUE TITLE
Better prerequisite checks/errors

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1300]
Add prerequisite checks during tasks / debug.

Some possible ideas (not an exhaustive list):

- [x] .NET Core: build tasks are present
- [ ] All: container OS matches what is set in daemon (Windows only)
- [ ] All: Minimum Docker version installed
- [ ] All: Docker running
- [ ] Linux: user added to Docker users group
- [x] Python: extension installed
- [ ] .NET Core: project is structured in an understandable way (e.g. csproj exists, etc.)
- [ ] Node: project is structured in an understandable way (e.g. package.json exists, etc.)

~~.NET Core: drive sharing enabled~~ WSL2 makes this mostly unnecessary

**Comment by bwateratmsft** [comment]
Blocked by https://github.com/microsoft/vscode/issues/80375

**Comment by bwateratmsft** [comment]
Delaying this one to 0.10.0

**Comment by philliphoff** [comment]
Let's use 0.10.0 to better understand what failures are occurring, in order to better understand what, specific, checks are needed.

**Comment by ravipal** [comment]
The current behavior is 1.0, is F5 pop-ups this error
![image](https://user-images.githubusercontent.com/1775825/77207578-fd086780-6ab6-11ea-8389-55687fdaf06f.png)

**Comment by bwateratmsft** [comment]
@ravipal could you add more context to that screenshot?

**Comment by ravipal** [comment]
When user runs 'Add Docker Files to Workspace' without adding the Net Core build and launch tasks. Then F5, user will run into an error (the above screen shot)

**Comment by ravipal** [comment]
Now the command 'Docker: Add Docker Files to Workspace' will check if the build task is present and fail if it is not present.

**Comment by bwateratmsft** [comment]
I don't think this is resolved yet as we want to cover a lot more than just .NET Core build tasks.

**Comment by ravipal** [comment]
Please add more information on what other issues that needs to be addressed.

**Comment by bwateratmsft** [comment]
I've added some ideas to the original opening comment.

**Comment by bwateratmsft** [comment]
I'm going to close this, it doesn't seem to be necessary--not really any volume of user reports that indicate confusion.
