### ISSUE TITLE
nginx, elasticsearch and articulate-rasa

### ISSUE THREAD

**Issue by Cesarcuna** [microsoft/vscode-docker#1301]
Repro steps:

Action: vscode-docker.containers.start
Error type: 400
Error Message: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/c/GitClone/articulate-0.29.0/articulate-0.29.0/local-storage/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/c7250f6dcdfa20ff5dfcf6f7a291e5c3b9b0d9d84cd70fcd1de5f90a8c8d42db/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/c7250f6dcdfa20ff5dfcf6f7a291e5c3b9b0d9d84cd70fcd1de5f90a8c8d42db/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
```

</details>

**Comment by bwateratmsft** [comment]
Can you share repro steps?
