### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RobsonAndrei** [microsoft/vscode-docker#1309]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint db_bancoDeDados (0d28a52286a8d0277723001a45a9abad14a193f196118234948c6d1ead9b5a57): Bind for 0.0.0.0:5436 failed: port is already allocated 

Version: 0.8.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@RobsonAndrei Can you add repro steps? It looks like the port is already allocated; you'll need to assign a different port or shut down the container using it.
