### ISSUE TITLE
Cannot connect to Azure container registry from Docker extension

### ISSUE THREAD

**Issue by paulyuk** [microsoft/vscode-docker#1310]
I have the lastest Docker 0.8.1 and several Azure extensions: Azure App Insights, Azure CLI Tools, and Azure Dev Spaces as of 9/26/2019.  There seems to be an error or conflict connecting to Azure with the Docker extension.  

Repro steps:

1. Docker Registries: Connect Registry.. from command pallette
2. Choose Azure

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: Only one provider with id "azure" is allowed at a time.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.connectRegistry extension.bundle.js:332:362455
```

</details>

**Comment by bwateratmsft** [comment]
@paulyuk When I look at the Registries list, Azure is already connected automatically (I did not add it manually):
![image](https://user-images.githubusercontent.com/36966225/65771502-51351f00-e106-11e9-99a4-02d66ff738fc.png)
What do you see?

**Comment by philliphoff** [comment]
I see the same error when I attempt to connect to Azure registries when I've already previously connected.  Perhaps we just need to massage the error message?  Maybe note that we've already connected to a given provider in the quick pick as well?  (I'm not sure we want to remove connected providers from the quick pick, as that may be a discoverability issue.)

**Comment by bwateratmsft** [comment]
Yes, same here. The Azure registry depends on the Azure Account extension; to verify I disabled that extension. The Azure node still showed up, simply with text saying "Install Azure Account extension". Clicking that led to the extension page, I re-enabled it, didn't need a full VSCode reload. Once I hit refresh on the Registries view it came right back.

I'm wondering if the Azure node did not show up for @paulyuk for some reason? If that's the case we definitely need to look into it.

**Comment by bwateratmsft** [comment]
@paulyuk can you share what you saw in the registries tab?

**Comment by paulyuk** [comment]
I do have two registries in the Explorer registry tab.  I suppose I did not need to use Connect palette command at all.  However, given I have two valid ones I'd expect a Success message (and maybe the registries to pop up) vs. an error.  In Docker, it's typical to login, build, push.  So i tried similar flow and was surprised by the login / connect step failing.

**Comment by BigMorty** [comment]
We should change this to just an Info message stating a connection of this type already exists. I also like the idea of switching the to the Explorer and selecting the connection, whether we just added it or in this case that it was already there.  Thoughts?
