### ISSUE TITLE
Invoke Docker run task when running Docker images from explorer

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1311]
When running [interactively] a Docker build image via the context menu for a tag in the Docker Explorer, the extension should look for an associated Docker run task and, if found, use that rather than building a static command line.  This would allow users to easily customize container instances (e.g. add networks/aliases) without having to involve scripts, Docker Compose, etc.

If more than one task is associated with the Docker image, then a quick-pick dialog would be shown for the user to choose which of the tasks to execute.  If no tasks are associated with the Docker image, the extension would build a static command line (as it does now).

**Comment by bwateratmsft** [comment]
@philliphoff There's a little bit of conflating build/run here. What mechanism would we use to determine that an image is associated to some run task?

**Comment by philliphoff** [comment]
@bwateratmsft I'd suggest matching on the `dockerRun.image` task property.  This came up when I was testing debugging for an application which depended on a MongoDB instance running; I needed to repeatedly spin up the MongoDB container with a specific set of network parameters via the command line.  It would be nice to be able to simply make that a task, which might also be useful in being a dependency of the application's Docker run task itself.

**Comment by bwateratmsft** [comment]
Yeah, I agree that would be good. One challenge is related to applications where they're doing debugging; we don't necessarily put the image name into the `docker-run` task but it is implied by the `docker-build` task, or by the application itself. In such a case how would we best tell if it's an image that we should use a task for?

**Comment by philliphoff** [comment]
If there is no `image` property, then I think we would compare the user-selected tag in the Explorer view with the inferred image name for task (based on the project).  If those match, then we'll use that task.

One hitch to that approach would be that the debug run task likely has a dependent build task; when running an image from the Explorer view, I don't think we'd want the image to be re-built (since the user has already told us they want to run *that* image.) That may be a bit of an edge case; I'm not sure how likely the user is to run the application image from the Explorer view vs. some other (related) image (like a DB, queue, or other service the application depends on).

**Comment by bwateratmsft** [comment]
We'd have to do a slight refactoring to make it so each language helper has a "get the image name for this workspace folder" method; not a hard thing to do.

That's a good point about task dependency. I don't think we can resolve away the `dependsOn`, so avoiding the build task when the user hasn't manually erased it is probably not possible.

**Comment by dbreshears** [comment]
Closing this as we don't have plans and don't believe it is possible.
