### ISSUE TITLE
(HTTP code 500) server error - driver failed programming external connectivity on endpoint 

### ISSUE THREAD

**Issue by ChakritRakuang** [microsoft/vscode-docker#1312]
(HTTP code 500) server error - driver failed programming external connectivity on endpoint codewind-performance (cd9a108024c561e9ed9098a628dc8851afce7cdcf218ef21fca3f5fc928293fa): Error starting userland proxy: listen tcp 127.0.0.1:9095: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by bwateratmsft** [comment]
@ChakritRakuang Can you add repro steps?
