### ISSUE TITLE
[Request] Pull image from images list

### ISSUE THREAD

**Issue by nihaals** [microsoft/vscode-docker#1313]
It would be great to be able to pull a newer version of an image from the list of images, either the latest tag if you select the image, or the specific tag if you select a specific tag in the image's list

**Comment by bwateratmsft** [comment]
Similar to what I was trying to address with #1213

**Comment by eine** [comment]
@bwateratmsft, it seems that #1213 was closed without merging. Is there any chance of having it reopened? I believe that's exatcly what @OrangutanGaming and me are missing...

**Comment by bwateratmsft** [comment]
@eine Sorry I didn't see this until now, I was on parental leave at the time. Yes, we're still planning to do this but don't have a milestone at this time.

**Comment by bwateratmsft** [comment]
This feature is now available in version 1.2.0 of the [Docker extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
