### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by vidiep** [microsoft/vscode-docker#1318]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: 125
Error Message: Command failed: docker run -dt --name "WebGateway-dev" --network "bridge" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=http://+:80;https://+:443" --label "com.microsoft.created-by=visual-studio-code" -v "e:\Exercise2\SOAR/Sources/ApiGateways/WebGateway:/app:rw" -v "C:\Users\VI.DIEP\.vsdbg:/remote_debugger:ro" -v "C:\Users\VI.DIEP\.nuget\packages:/root/.nuget/packages:ro" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro" -v "C:\Users\VI.DIEP\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\VI.DIEP\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -p "7000:80" --entrypoint "tail" "26d535b3adda" -f /dev/null
docker: Error response from daemon: driver failed programming external connectivity on endpoint WebGateway-dev (f26b2b7aa8c3b1543055448888b81eb4b6d4be7cb22ccec65547e509313d2357): Bind for 0.0.0.0:7000 failed: port is already allocated.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:299:12
ChildProcess.emit events.js:182:13
```

</details>

**Comment by bwateratmsft** [comment]
@vidiep Can you add repro steps? It looks like port 7000 is already bound to another container or even another app.

**Comment by vidiep** [comment]
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "compounds": [
        {
            "name": "Docker: Launch all",
            "configurations": [ "Docker: Launch WebGateway", "Docker: Launch OrderingApi" ]
        },
        {
            "name": "Docker: Attach all",
            "configurations": [ "Docker: Launch WebGateway", "Docker: Attach to OrderingApi"]
        }
   ],
   "configurations": [
       {
           "name": "PowerShell Launch ",
           "type": "PowerShell",
           "request": "launch",
           "script": "${workspaceFolder}/scripts/project-tasks.ps1",
           "args": ["-Compose"],
           "cwd": "${workspaceFolder}"
       },
        {
            "name": "Docker: Launch OrderingApi",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "dockerBuild": {},
            "dockerRun": {
                "ports": [ { "hostPort": "7001", "containerPort": "80" } ],
                "env": {
                    "ASPNETCORE_ENVIRONMENT": "Development",
                    "ASBConnectionString": "Endpoint=...",
                    "ASBTopicName": "soar-topic",
                    "SubscriptionClientName": "Ordering"
                }
            },
            "appFolder": "${workspaceFolder}/Sources/Services/Ordering/OrderingApi"
        },
        {
            "name": "Docker: Launch WebGateway",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "dockerBuild": {},
            "dockerRun": {
                "network": "bridge",                
                "ports": [ { "hostPort": "7000", "containerPort": "80" } ],
                "env": { 
                    "ASPNETCORE_ENVIRONMENT": "Development"
                }
            },
            "appFolder": "${workspaceFolder}/Sources/ApiGateways/WebGateway"
        },
        {
            "name": "Docker: Attach to WebGateway",
            "type": "coreclr",
            "request": "attach",
            "sourceFileMap": {
                "/src": "${workspaceFolder}"
            },
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}/Sources/ApiGateways/WebGateway",
                "pipeArgs": [ "exec", "-i", "soar_webgateway_1" ],
                "debuggerPath": "/app/vsdbg/vsdbg",
                "pipeProgram": "docker",
                "quoteArgs": false
            }
        },
        {
            "name": "Docker: Attach to OrderingApi",
            "type": "coreclr",
            "request": "attach",
            "sourceFileMap": {
                "/src": "${workspaceFolder}"
            },
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}/Sources/Services/Ordering/OrderingApi",
                "pipeArgs": [ "exec", "-i", "soar_orderingapi_1" ],
                "debuggerPath": "/app/vsdbg/vsdbg",
                "pipeProgram": "docker",
                "quoteArgs": false
            }
        },
        {
            "name": ".NET Core Launch (WebGateWay)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/WebGateway/bin/Debug/netcoreapp2.2/WebGateway.dll",
            "args": [],
            "cwd": "${workspaceFolder}/WebGateway",
            "stopAtEntry": false,
            // Enable launching a web browser when ASP.NET Core starts. For more information: https://aka.ms/VSCode-CS-LaunchJson-WebBrowser
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"                
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_URLS": "http://localhost:7000"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Launch (CatalogApi)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/CatalogApi/bin/Debug/netcoreapp2.2/CatalogApi.dll",
            "args": [],
            "cwd": "${workspaceFolder}/CatalogApi",
            "stopAtEntry": false,
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_URLS": "http://localhost:7001"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        }
    ]
}
config files debugger vscode

**Comment by bwateratmsft** [comment]
Does this issue occur every time or did it only happen once?
@philliphoff Do you happen to know if the existing debug code will shut down multiple containers, when using compound debug configurations?

**Comment by philliphoff** [comment]
@bwateratmsft The extension keeps a list of the containers it has started, and then tries to shut them down after the debugging session ends. In any case, it will attempt to shutdown containers with the same name prior to starting a new one.

@vidiep It would be great if you could describe what you were doing when you ran into the problem.

**Comment by vidiep** [comment]
Thank all

**Comment by bwateratmsft** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
