### ISSUE TITLE
Mount Directory in Docker Container

### ISSUE THREAD

**Issue by shreyu86** [Microsoft/vscode-docker#132]
I love the Docker Extension and was wondering what is the best way to mount the current directory into the Docker Container that is running interactively. This would be ideal for containers which are spawned interactively. Happy to submit a PR if this is a use case for other users too. 
For example this would another option like Run Interactive with current directory  which would mount `pwd` into the container into a location like `/code` and set that as the workdir using the option `-w` in Docker run.

**Comment by chrisdias** [comment]
Hi!

I find the easiest way to do this is to set up volume mounting in the `docker-compose.yml` file. For example, this will mount the current folder `.` into `/usr/src/app` in the container:

``` yml
    volumes:
      - .:/usr/src/app
```

Then run `docker compose up` from the command palette.

Doing it this way means we don't have to have a bunch of different variations of `docker run`. Instead, update the compose file with various configurations (e.g. setting environment variables).

Let me know what you think.

**Comment by shreyu86** [comment]
Thanks @chrisdias this is a great work around, really appreciate the quick reply!

**Comment by chrisdias** [comment]
Let me know how that works for you and please keep the ideas coming in!
