### ISSUE TITLE
Rename "Run" / "Run Interactive" to "Create Container"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-docker#1320]
As a user, getting from an image to container is not intuitive. I would have expected a context menu on an image to "Create Container":

![image](https://user-images.githubusercontent.com/900690/66195731-82c66100-e697-11e9-989a-33e96851da7d.png)

//cc @chrmarti

**Comment by ThorstenHans** [comment]
I think `run` is correct in the context of `docker` because it is actually invoking the `docker run` command

**Comment by bwateratmsft** [comment]
I think I'm with @ThorstenHans on this one. Containers are a bit like processes; it is true that you "create" processes but normally we say we "run" processes/applications/etc. @BigMorty What do you think?

**Comment by BigMorty** [comment]
I tend to agree, Run seems to be the correct verb here. What do folks think about "Run Container" and "Run Container Interactive" ???

**Comment by ThorstenHans** [comment]
That would end up in appending either *container* or *image* to every entry

**Comment by BigMorty** [comment]
Yes, good point!
