### ISSUE TITLE
Allow non-platform-specific build/run tasks

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1321]
Allow the creation of Docker build/run tasks not tied to a given platform (e.g. Node or .NET Core) in order to allow tasks to be used for arbitrary configurations of images/containers.

For example, I may want to (repeatedly) create a MongoDB container with a specific set of environment variables, attached to a specific network, etc..  While this can be done via a shell script or Docker Compose YAML, it may not be as convenient as being able to execute a Docker run task in VS Code, or integrate as well into a sequence of tasks used for various purposes.

**Comment by bwateratmsft** [comment]
[Good idea!](https://github.com/microsoft/vscode-docker/pull/1245#discussion_r321762021)

**Comment by philliphoff** [comment]
(@bwateratmsft I'm pretty sure you suggested this at some point, but it's already proven to be a sorely missing feature in my debugging testing.)

**Comment by bwateratmsft** [comment]
Yeah. Shouldn't be a difficult thing to implement either; just return undefined platform helper instead of erroring. Same validation rules would apply.
