### ISSUE TITLE
Error rates: Some commands (like prune) don't give any indication that they are running and can take some time

### ISSUE THREAD

**Issue by oswagner** [microsoft/vscode-docker#1323]
Repro steps:
1. Just open the extension 
2. Try to prune images

Action: vscode-docker.images.prune
Error type: 409
Error Message: (HTTP code 409) unexpected - a prune operation is already running 

Version: 0.8.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@oswagner I'm not able to reproduce this; are you certain there isn't a prune operation running already?

**Comment by oswagner** [comment]
@bwateratmsft already had another prune operation running, but I didn't receive any feedback, and then received this error.

**Comment by bwateratmsft** [comment]
Gotcha. I'll change the title to more accurately reflect the issue.

**Comment by bwateratmsft** [comment]
I think the best solution is to use vscode.window.withProgress for prune operations.
