### ISSUE TITLE
Refactor static Dockerode property to be provider-based

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1325]
The static Dockerode property `ext.dockerode` is problematic as it must be created in a synchronous way on extension initialization, as well as refreshed whenever a Docker-related configuration setting is changed.  We should refactor this property to be "provider-based" where creation is deferred until actually used.  This would simplify refreshing the instance when configuration values change, as the cached instance can simply be thrown away and only re-instantiated upon the next request.

**Comment by bwateratmsft** [comment]
Can we make it a simple `Lazy<T>`?

**Comment by bwateratmsft** [comment]
Probably the new Docker SDK will take care of the needs here.

**Comment by karolz-ms** [comment]
Don't we do this effectively today? All the calls to Dockerode go through`callDockerodeXxx` wrappers...

**Comment by bwateratmsft** [comment]
This is complete with #2119 and #2134.
