### ISSUE TITLE
Use WORKDIR in Dockerfile to infer debugger remote source root

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1328]
Some debuggers (e.g. for Node.js) have a "remote source root" configuration property that helps it map code executing remotely (e.g. in a Docker container) back to the source code on the developer's local machine.  By default, the Node.js Docker debugger will use the same static value used during Docker file scaffolding (so both the Dockerfile and the debugger configuration will align).

However, an existing Dockerfile may use any arbitrary `WORKDIR` and may not align with that default location used in the scaffolded debugger configuration, and this currently requires explicit setting by the user.

If the debugger configuration resolution logic could, instead, identify the associated Dockerfile (by walking the build/run/debug task dependency chain), it could use the WORKDIR associated with the build stage as the default remote source root, and be more likely to be correct.

**Comment by bwateratmsft** [comment]
Closing this for now; the interest doesn't seem to be there.
