### ISSUE TITLE
failed while trying to add my docker hub registry credentials

### ISSUE THREAD

**Issue by hsarena** [microsoft/vscode-docker#1329]
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

**Comment by bwateratmsft** [comment]
Duplicate of #722.
