### ISSUE TITLE
Support `--chown` option for COPY instruction

### ISSUE THREAD

**Issue by Spy-Seth** [Microsoft/vscode-docker#133]
Recently docker add the support of the `--chown` option on `ADD` and `COPY` command: 

```
COPY --chown=bar:bar /foo /home/bar
``` 

Could you upgrade this plugin to support it? 😃 

For now the plugin show it as an error:
![screenshot 2017-10-02 10 23 16](https://user-images.githubusercontent.com/95120/31069227-c7f27098-a75b-11e7-96ca-1ea3e728287c.png)

See the PR https://github.com/moby/moby/pull/34263

**Comment by rcjsuen** [comment]
Hi @Spy-Seth, thank you for the bug report. I see that Docker CE 17.09 has been officially released. I will implement this as soon as possible.

Please refer to rcjsuen/dockerfile-language-server-nodejs#166. Thanks!
