### ISSUE TITLE
Use ENTRYPOINT in Dockerfile to infer (Node.js) debugger arguments

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1330]
Some Node.js application frameworks use custom CLIs to manage starting/stopping/debugging/packaging of the applications. As such, they may not specify a main script or a recognizable "node script.js" NPM script needed during debugging to infer the command line used to enable the debugger.  In those cases, the user must be explicit about the Docker run command in the task configuration and include the debugging-related arguments.

While these frameworks may use a CLI for development tasks, the CLI is often not necessary once the application is Dockerized (e.g. because the CLI generates a package that is otherwise a generic Node.js application with no dependencies on that CLI, which is then just executed directly by the Docker container).  In those cases, the debugger may be able to infer the command line by using the Dockerfile's ENTRYPOINT and not require the suer to be explicit.

**Comment by bwateratmsft** [comment]
Closing this for now; the interest doesn't seem to be there.
