### ISSUE TITLE
FROM image suggestions from store

### ISSUE THREAD

**Issue by daimor** [microsoft/vscode-docker#1337]
Very often use images like `store/intersystems/iris-community` in `FROM` and it does not have latest version, I should remember the version number. 
Would it be possible if this extension could suggest a version image in such cases?

**Comment by rcjsuen** [comment]
@daimor Are you talking about the case where you're typing in your `Dockerfile` in the editor? If yes, does the editor give you suggestions if you don't use `store/` and refer to things like `node:...`?

**Comment by daimor** [comment]
Right, and yes, it does work for common docker images

**Comment by daimor** [comment]
btw, I found only one way how to gather information about tags in `store/ `
https://registry-1.docker.io/v2/store/intersystems/iris-community/tags/list
but it requires access token

**Comment by daimor** [comment]
And how to get a list of products in Store
```
curl -X GET  'https://hub.docker.com/api/content/v1/products/search?q=intersystems' | jq
```
But did not find how to get this `store/intersystems/iris-community`, for instance

**Comment by rcjsuen** [comment]
@daimor If this feature is important to you, please open an issue in the [rcjsuen/dockerfile-language-service repository](https://github.com/rcjsuen/dockerfile-language-service). Thank you.

**Comment by daimor** [comment]
@rcjsuen I fixed it for me by editing dockerfile-ast
added this code after [line](https://github.com/rcjsuen/dockerfile-ast/blob/759f7a6a872997c5fb47e5e63877925b01cc823e/src/instructions/from.ts#L174) 
```
      if (content.startsWith("store/")) {
        return null;
      }
```
so, the parser does not recognize `store` as a registry and keeps the image name as 'store/intersystems/iris-community'
Maybe I should fill the issue there?

**Comment by rcjsuen** [comment]
@daimor That's some next level archaeology you did there. Please open an issue in [rcjsuen/dockerfile-ast repository](https://github.com/rcjsuen/dockerfile-ast) for starters and we can continue the conversation there. Thank you.

**Comment by bwateratmsft** [comment]
Marking this one as closed, tracking https://github.com/rcjsuen/dockerfile-ast/issues/59.
