### ISSUE TITLE
DOCKERFILE_GLOB_PATTERN is too permissive

### ISSUE THREAD

**Issue by freeformz** [Microsoft/vscode-docker#134]
We have a `dockerfile.go` file in at least one repo and it's being detected as belonging to this plugin instead of the Go plugin.

This is likely because the [current DOCKERFILE_GLOB_PATTERN](https://github.com/Microsoft/vscode-docker/blob/master/dockerExtension.ts#L32) is too permissive.

**Comment by freeformz** [comment]
`dockerfile_test.go` is also detected as a Dockerfile, instead of a `.go` file.

**Comment by chrisdias** [comment]
this is also painful when developing the docker extension :)

**Comment by dlech** [comment]
@lostintangent, what is the motivation for 950d9f0ca120a77de4e275848b95bfbcbe200b81?

It seems that the standard format is either `Dockerfile` or `*.dockerfile`. 

I'm going to suggest using only the most common filenames in the extension and users can use the language-specific settings in VSCode if they need to match other files.
