### ISSUE TITLE
I am not able authrozie the org in VSCode. unable to get local issuer certificate

### ISSUE THREAD

**Issue by Sp00127c** [microsoft/vscode-docker#1345]
Hello,

when I am trying to authorize the org in VSCode, it is redirecting to login page. when I enter credentials, it is showing unable to get local issuer certificate.

can anyone please help me resolve this issue.

thanks in advance

**Comment by bwateratmsft** [comment]
@Sp00127c Can you add repro steps and maybe screenshots of the error?
