### ISSUE TITLE
TesteAngular

### ISSUE THREAD

**Issue by wwwsilvathiago** [microsoft/vscode-docker#1348]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:332:328523
```

</details>

**Comment by bwateratmsft** [comment]
@wwwsilvathiago Is there a csproj/fsproj project file present in the workspace? Can you share the structure of your solution and also the Docker debug task from `.vscode\launch.json`?
