### ISSUE TITLE
Add -u setting when attach shell and vscode

### ISSUE THREAD

**Issue by MikeZhu92** [microsoft/vscode-docker#1349]
I'm trying to use the 'attach shell' and `attach vscode` the plugin execute cmd is like this:
`docker exec -it container_id /bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"`

I want to add `-u` before the container id but I can only config the settings after container_id in the docker plugin setting `Attach command to use for Linux containers`.

#807 is related to this, but the user seems changed everything to root as a walk around solution.

Any help or suggestion would be great!

**Comment by bwateratmsft** [comment]
Related also to #1197 , #363

**Comment by jolimas** [comment]
This could be easily done adding a config option to settings (named "attachShellOptions"?). 

Like the "attachShellCommand" but for  exec options (docker container exec **[OPTIONS]** CONTAINER COMMAND [ARG...]).

**Comment by MikeZhu92** [comment]
This feature now supported in remote development plugin. 
@jolimas here is the reference: https://github.com/microsoft/vscode-remote-release/issues/1155

@bwateratmsft feel free to close this issue if you think this might be duplicated feature in other plugin.

**Comment by jolimas** [comment]
Thanks @MikeZhu92 . I'll give it a try.

**Comment by bwateratmsft** [comment]
This functionality is added in the Docker extension via #1596, so I'll dupe this item to that one.
