### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by anegrelli** [microsoft/vscode-docker#1354]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete 314918ddaedf (cannot be forced) - image is being used by running container 87e8242dddb0 

Version: 0.8.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps? Are you trying to delete an image that is still in use?
