### ISSUE TITLE
Infer browser location based on exposed Docker ports

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1355]
The new task-model of debugging relies on the `dockerServerReadyAction` to determine whether/when/where to launch the browser.  This relies on certain recognized statements being written to the debug console; in the case of Node.js, several of the popular logging libraries do not actually write to the console by default (e.g. they write to `stdout` instead, even when using a "console" logger).  This requires users to explicitly update their application to ensure that the statements can be seen by the debugger.

This task is to investigate whether we can, at least in some circumstances, infer whether/when/where to launch the browser based on other factors, such as the ports exposed by the running container.

> Note that this may be hampered by the fact that the debug configuration which defines whether/where to launch the browser is resolved before the container run task executes.  Not only that, but *when* the browser launches is another consideration that may be difficult to infer without actually seeing application output.

**Comment by bwateratmsft** [comment]
FWIW, the "official" approach that VSCode took was this `serverReadyAction`; I'd like to have plugged into that rather than copy it entirely, but requiring app output to indicate readiness seems to be the norm.

**Comment by philliphoff** [comment]
May now be a duplicate of #1545.

**Comment by bwateratmsft** [comment]
I'm not sure I feel like this should be considered P1 when the built-in server ready action goes to no such lengths...
