### ISSUE TITLE
when i start the container got this

### ISSUE THREAD

**Issue by goe13** [microsoft/vscode-docker#1356]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint fazhihao (7aba3d3f8dcbb8cce4fbc7d0bd1e837f2f8aeb5f82266cb979e2da4683560519): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps? What happens if you try again?

**Comment by goe13** [comment]
Repro steps:
1.When I runing command follow then got the error.
command:
`docker run -dit --name fazhihao -v "E:\dockers\fazhihao\data\www\front:/home/www/front" -v "E:\dockers\fazhihao\data\www\LegalDailyCMS:/home/www/LegalDailyCMS" -p 8083:80 benchu1k/t1:1.0`
error:
`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint fazhihao (b4b97b68f67508c56b31257db1c3ba3a3b6c99e5738da2fc18d40bb5f430e7a4): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500.`
2.When I right click the container to start use this extensions ,then I got this error.
