### ISSUE TITLE
Error Message: (HTTP code 500) server error - error while creating mount source path '/host_mnt/c/Software/code/dycom/web-app': mkdir /host_mnt/c: file exists 

### ISSUE THREAD

**Issue by ntakadzeni-tharage** [microsoft/vscode-docker#1361]
Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - error while creating mount source path '/host_mnt/c/Software/code/dycom/web-app': mkdir /host_mnt/c: file exists 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@ntakadzeni-tharage This is a relatively common issue where volume mapping on Docker decides it doesn't want to work anymore...typically, restarting Docker Desktop has worked for me. Can you try that?
