### ISSUE TITLE
error :connect ENOENT//./pipe/docker_engine

### ISSUE THREAD

**Issue by TDPrabhu** [microsoft/vscode-docker#1363]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by bwateratmsft** [comment]
@TDPrabhu Can you add repro steps? Is Docker actually running?
