### ISSUE TITLE
cannot debug node apps (anymore)

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docker#1365]
create a new node/express app:

``` console
npx express-generator myExpressApp
cd myExpressApp
code . -r
```

open the command palette, choose `Add Dockerfiles to workspace...`, follow prompts for Node, port 3000.

Result:  `Dockerfile`, `docker-compose.yml`, and `docker-compose.debug.yml` are all created, but there is no `launch.json`...

in debug viewlet, add new debug configuration, choose `Docker: Nodejs`

Result:

``` json
    "configurations": [
        {
            "name": "Docker: Attach to Node",
            "type": "node",
            "request": "attach",
            "remoteRoot": "/usr/src/app"
        }
    ]
```

right click on the `docker-compose.debug.yml` file and choose `Docker Compose Up`

Set a breakpoint

Press `F5` to debug the app, try to hit the breakpoint, it never attaches

Not sure what changed, but the extension used to generate a `launch.json` along with the other artifacts and IIRC it specified the port.

**Comment by chrisdias** [comment]
looks like i have another extension installed that is conflict with this scenario... need to figure out which one.

**Comment by bwateratmsft** [comment]
@chrisdias let us know if you figure it out, in case others run into the problem. @philliphoff it may be something we can solve as well.
