### ISSUE TITLE
Error Message: (HTTP code 500) server error - Cannot restart container 

### ISSUE THREAD

**Issue by anadapa** [microsoft/vscode-docker#1366]
Repro steps:

1.
2.

Action: vscode-docker.containers.restart
Error type: 500
Error Message: (HTTP code 500) server error - Cannot restart container d6e79c45f7ea1411bed07ff26b5e8b5bf9da99075617f65ab3efffa7c73971bb: error while creating mount source path '/host_mnt/e/Sistemas/betuel/estamos-contigo/estamos-contigo-app': mkdir /host_mnt/e: file exists 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@anadapa This is a relatively common error with Docker. Try restarting Docker Desktop.
