### ISSUE TITLE
Problem with docker on VSCODE

### ISSUE THREAD

**Issue by atmmoreira** [microsoft/vscode-docker#1373]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps? Is Docker running? Have you configured it for non-sudo users?
