### ISSUE TITLE
When running app

### ISSUE THREAD

**Issue by amitsingh11** [microsoft/vscode-docker#1375]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:332:328523
```

</details>

**Comment by amitsingh11** [comment]
please help for the same

**Comment by bwateratmsft** [comment]
@amitsingh11 Where is the csproj in your workspace located?

**Comment by amitsingh11** [comment]
I have downloaded app from github and put that folder in d drive.
My os is in c drive.
If any query please let me know.

**Comment by bwateratmsft** [comment]
@amitsingh11 What app from GitHub? In order to do .NET Core debugging, the extension needs to be able to find the csproj in your workspace. If it's not in the root of the workspace, you need to set the `appProject` or `appFolder` property in the launch.json profile.

**Comment by amitsingh11** [comment]
Thanks for the quick response.
I am very happy from your side.
I have tried to set appFolder in launch.js . Also use the 2-3 reference
site. Not able to resolve the issue.
Please can you help me by referring the site or any other way.

Thanks a lot for your help.

Please help.

**Comment by bwateratmsft** [comment]
Does your workspace contain a `.csproj` file?

**Comment by amitsingh11** [comment]
No , my projects does not contain the same.

**Comment by bwateratmsft** [comment]
You can't debug any arbitrary project with the .NET Core Docker debug provider. Do you have some other kind of .NET Core project (e.g. `.vbproj`, `.fsproj`)?

**Comment by amitsingh11** [comment]
This project is for block chain.
.Net core is used for accessing block chain API.
Hyper ledger is used for creating the block chain.

What is the solution ?
I need to create new project for debugger ?
Please suggest.

**Comment by bwateratmsft** [comment]
I would suggest starting here: https://github.com/microsoft/vscode-docker/wiki/Debug-.NET-Core-(Preview)

You can only debug .NET Core web and console apps with this debug provider; if you don't have a .NET Core project (`.csproj`, `.fsproj`, `.vbproj`) then you don't have a .NET Core app, regardless of what APIs are being used.

**Comment by amitsingh11** [comment]
Thanks for your great help.
I will start as per your suggestions.

May you suggest sample code for blockchain which is using .Net core for
development.
So that I can create blockchain application on Microsoft Azure.

Once again thank you for your support.

**Comment by bwateratmsft** [comment]
I'm not aware of any, perhaps others are? I've labeled this "Question".

**Comment by karolz-ms** [comment]
@amitsingh11 you said you have downloaded a sample from GitHub. Can you clarify what sample are you using (give us the link/URL)?

**Comment by amitsingh11** [comment]
Sure I will share the link with you by tomorrow.
This is for IBM blockchain on hyper ledger.

**Comment by amitsingh11** [comment]
Hi Microsoft/Vscode-Docker,
Below is the link from where I have copied the application.
HTTPS://github.com/IBM/build-blockchain-insurance-app

**Comment by bwateratmsft** [comment]
I looked; that is not a .NET Core app at all. The `web` folder contains a Node.js app, the rest is just Dockerfiles.

**Comment by amitsingh11** [comment]
Yes , when I am trying execute vs code then it shows alert for appFolder.

I think we can use vs code IDE for that type of application.
Please suggest can we use vs code for that ?

Or I can use other IDE like sublime etc.

**Comment by bwateratmsft** [comment]
VSCode can debug Node.js applications, but you can't use the _.NET Core_ debugger for that, which is what you've been trying to do. You need to use a Node.js debug provider, most likely with a Node Attach configuration after starting the app with `Docker Compose: Up`. More about Node.js debugging here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging
