### ISSUE TITLE
[Suggestion]Add a button to navigate to the Azure Portal to enable the ACR 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1379]
**OS**: All
**Build Version:** [20191025.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11605)
**Regression**: Not a Regression

**Repro Steps:**
1. Create a new Azure Registry --> Run "Docker Registries : Log In to Docker CLI" --> Push an image to this new Azure Registry.
2. Drill down from the Azure --> Applied subscription --> New Azure Registry --> Right click the new pushed image --> Select "Deploy Image to Azure App Service...".
3. Pop up an error.

**Actual:**
There is only one button "Report an issue".
![image](https://user-images.githubusercontent.com/34729092/67762338-2b41c800-fa80-11e9-9e07-556a822bb75e.png)

**Suggestion:**
Add a button to navigate to the Azure Portal to enable the ACR, it would be better for users to enable the ACR.

**Comment by bwateratmsft** [comment]
We're planning to remove this admin requirement with #1685, so will close this one.
