### ISSUE TITLE
Opened terminal from built in command remains empty (bug)

### ISSUE THREAD

**Issue by CodeMyCoffee** [Microsoft/vscode-docker#138]
Whenever a command is executed, either from the GUI by right clicking the container or by using the command palette, a terminal should be opened and show the executed command and it's results/logs.
This behaviour works just fine IF I don't have any other previous terminal opened. Every time I run a  new command with an already opened terminal, the command would execute and run, but I can't see any output on the newly opened terminal. That's a bit of an issue when I use the Up command, and then I want to see the specific log for a container, I can't do it by using the built in commands. 

Did anyone ran into this issue before?

This is happening to me on Win10, having by default both powershell or cmd, even git bash, all of them work on the first terminal, but subsecuent terminals are just blank

**Comment by chrisdias** [comment]
If you resize the terminal the content should show up.  this is a bug in the integrated terminal, see https://github.com/Microsoft/vscode/issues/35728.

sorry about this.
