### ISSUE TITLE
Cannot remove registry docker

### ISSUE THREAD

**Issue by ryanbekhen** [microsoft/vscode-docker#1382]
Repro steps:

1.
2.

Action: vscode-docker.registries.deleteImage
Error type: UNSUPPORTED
Error Message: The operation is unsupported.

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:157:803988
$.callback extension.bundle.js:157:802837
$.e.callback.t.callback [as _callback] extension.bundle.js:157:801891
$.t._callback.t.callback.t.callback extension.bundle.js:187:5469
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:187:18282
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:187:17124
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@ryanbekhen What type of registry were you using? Private registry, Docker Hub, ACR, etc.?

**Comment by ryanbekhen** [comment]
Private registry

**Comment by bwateratmsft** [comment]
@ryanbekhen I found this issue that looks similar:
https://github.com/docker/distribution/issues/1573

According to that you need to set an environment variable for your registry, `REGISTRY_STORAGE_DELETE_ENABLED=true`. Can you try that and see if it works?

**Comment by sogalgeeko** [comment]
@bwateratmsft Just to mention that I encountered the very same issue and that adding this environment variable solved the issue.
Thank you.
