### ISSUE TITLE
Use vscode.window.withProgress for prune operations

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1384]
Prune operations can take some time; a relatively common error from telemetry is users starting another prune operation before the prior one has completed. There isn't really any indication that one is running, so we should use `vscode.window.withProgress` to show that it's happening in the background.

**Comment by dbreshears** [comment]
Should we also enable/disable via context

**Comment by bwateratmsft** [comment]
Dupe of #1323
