### ISSUE TITLE
Can't remove docker container

### ISSUE THREAD

**Issue by May-0599** [microsoft/vscode-docker#1385]
Repro steps:

1.
2.

Action: vscode-docker.containers.remove
Error type: 409
Error Message: (HTTP code 409) unexpected - removal of container d3d445766b093d6208985d33ed4acf3a41fd0e5ad9e6b5a48280987cd77c417e is already in progress 

Version: 0.8.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps?
