### ISSUE TITLE
Cannot start container: bind: address already in use

### ISSUE THREAD

**Issue by conglam96** [microsoft/vscode-docker#1389]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint lam_gay_apache_1 (416e70f5eed1eff186ad0a490c8d24738f24a0143393625ca08f92f6338b3a36): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use 

Version: 0.8.1
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034
extension.bundle.js:157:702997
m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps?
