### ISSUE TITLE
ms-vscode.azure-account has been unpublished from the VS Code Marketplace

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-docker#139]
The [Azure Tools for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azuretoolsforvscode) extension with the `ms-vscode.azure-account` identified has been unpublished.

> _Note:_ During preview phase, this extension has been moved to https://marketplace.visualstudio.com/items?itemName=bradygaster.azuretoolsforvscode

This makes it impossible to develop vscode-docker because the extension will not start due to the missing dependency.

https://github.com/Microsoft/vscode-docker/blob/4c14927ac9253fb4935a41539087dfe25f241047/package.json#L426

https://github.com/Microsoft/vscode-docker/blob/4a0934caf5328b7d510260a06d9f3aaa209eb5d7/explorer/deploy/azureAccountWrapper.ts#L21

https://github.com/Microsoft/vscode-docker/blob/4a0934caf5328b7d510260a06d9f3aaa209eb5d7/explorer/models/registryRootNode.ts#L18

https://github.com/Microsoft/vscode-docker/blob/4a0934caf5328b7d510260a06d9f3aaa209eb5d7/explorer/models/azureRegistryNodes.ts#L11

**Comment by chrisdias** [comment]
@rcjsuen  sorry, I'm a bit confused.  

All you need to do is install the [Azure Account extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) and then you can build/run the Docker extension.  

Am I missing something?  If not, then I don't think we need the PR.

**Comment by rcjsuen** [comment]
@chrisdias Sorry, you're right. I got led astray because the Azure Tools was the first hit that came up and I somehow totally misread everything.

I'm trying to install `ms-vscode.azure-account` now but I'm getting an `end of central directory record signature not found` error.

**Comment by chrisdias** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account

are you getting the 'end of central directory...' error from the marketplace or in the vscode-docker extension?

**Comment by rcjsuen** [comment]
@chrisdias I'm getting it when from VS Code itself when I try to install the `ms-vscode.azure-account` extension.

![image](https://user-images.githubusercontent.com/15629116/31579300-8e95d5ac-b16e-11e7-9224-22d66f0f2f56.png)

I tried [this workaround](https://github.com/Microsoft/vscode/issues/2384#issuecomment-323440725) but it didn't work. Will continue googling around...

**Comment by chrisdias** [comment]
bummer, sorry about that, i wish i had more info on how to fix that one.  

in the meantime, you could simply clone the azure account repo, vsce package it, and side load it.  

``` console
clone https://github.com/microsoft/vscode-azure-account
cd vscode-azure-account && npm install
vsce package
code-insiders --install-extension azure-account-0.1.3.vsix
```

**Comment by chrisdias** [comment]
closing this particular issue...
