### ISSUE TITLE
Remote - Containers suggests invalid container tag

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-docker#1390]
- Open the vscode-remote-try-rust repo
- Run "Docker Images: Build Image..."
- Accept the suggested tag of `.devcontainer`
- Get an error about an invalid tag

I think they can't start with `.`

**Comment by rcjsuen** [comment]
> I think they can't start with .

That is correct per the [documentation](https://github.com/docker/cli/blob/ae1618713f83e7da07317d579d0675f578de22fa/docs/reference/commandline/tag.md).

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by bwateratmsft** [comment]
I think this may already be fixed in #1245 but I will verify. (The code in #1245 has not yet released so it is expected to still have the bug in the public release)

**Comment by bwateratmsft** [comment]
Yes, validated that this is fixed. It will suggest `vscoderemotetryrust:latest` by default.
