### ISSUE TITLE
Issui when i try deletin my image by vsconde

### ISSUE THREAD

**Issue by ClaudioLazaro** [microsoft/vscode-docker#1391]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete 965ea09ff2eb (cannot be forced) - image has dependent child images 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@ClaudioLazaro Can you add repro steps? It appears there are images built based on the one you are trying to delete; in this case deletion is not allowed.
