### ISSUE TITLE
Add default VS labels to all task-built Docker images

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1392]
Currently, the "old" .NET Core debugging logic as well as the new NET Core Docker build task will add the `com.microsoft.created-by` label, if no other labels are specified.  We should also add this label (by default) to all images created via tasks (.NET Core, Node.js, and otherwise).

**Comment by philliphoff** [comment]
We should also consider:

 - Always adding this label, even when other labels are specified, but then adding a task option to explicitly disable the default labels.  (This would be similar to VS.)
 - Also adding this label to containers started by VS (using tasks). Containers will inherit the labels of their images, but users could theoretically run an arbitrary image using a task, which might not have that label.

**Comment by bwateratmsft** [comment]
The usage in VS got too complicated, IMO. Is it not sufficient to use the default labels for images only unless one is specified? (i.e. what we're doing for .NET Core)

What do we want to achieve with these labels?

**Comment by philliphoff** [comment]
Enabling us to add labels *in addition* to those added by users just gives us the flexibility to use labels as metadata stores later (e.g. knowing which containers are safe(r) to remove on debug end or close due as we've marked them as having been created by us and/or a specific debug session).

**Comment by bwateratmsft** [comment]
That makes sense. We should see if we can come up with a simpler way to specify things than what we did in VS. I'm not super keen on having a `labels` property *and* a `noDefaultLabels` boolean property.

**Comment by bwateratmsft** [comment]
We can also deal with `ports` `publishAllPorts` in a similar manner.

**Comment by bwateratmsft** [comment]
We can also deal with `ports` `publishAllPorts` in a similar manner.
