### ISSUE TITLE
erro no start

### ISSUE THREAD

**Issue by hevertonpablo** [microsoft/vscode-docker#1393]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 400
Error Message: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Docker/laradock/php-fpm/php7.3.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/4e08d3717ce00b9a28617c7429180f219afcca82666a2f8c1ff7bda2514c5abd/merged\\\" at \\\"/var/lib/docker/overlay2/4e08d3717ce00b9a28617c7429180f219afcca82666a2f8c1ff7bda2514c5abd/merged/usr/local/etc/php/php.ini\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098extension.bundle.js:157:703098
extension.bundle.js:157:703061extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by bwateratmsft** [comment]
@hevertonpablo Can you add repro steps?
