### ISSUE TITLE
High Contrast Rendering Issue with Configure Explorer

### ISSUE THREAD

**Issue by robfallows** [microsoft/vscode-docker#1397]
## Platform

![image](https://user-images.githubusercontent.com/6086035/68293406-c7be2880-0085-11ea-8b8d-c5b6b777277e.png)

## Issue

When using the High Contrast Theme:

Selecting `Images` -> `Configure Explorer...` renders:

![image](https://user-images.githubusercontent.com/6086035/68293627-4024e980-0086-11ea-8ad2-33c5cdd2f4e6.png)

**Comment by bwateratmsft** [comment]
AFAIK we aren't doing any special UI so this may be a VSCode issue. I'll investigate.

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT So this menu is just a vanilla `vscode.window.showQuickPick` done through the Azure Extension framework. I'm pretty sure that makes this a VSCode issue, would you agree?

I'll try reproing the issue with a dummy extension.

**Comment by bwateratmsft** [comment]
I'm able to reproduce in a stub extension with the following code, so I'll move this to VSCode.

```
    const items: vscode.QuickPickItem[] = [
        {
            label: "My label 1",
            description: "The description 1",
            detail: "The detail 1",
        },
        {
            label: "My label 2",
            description: "The description 2",
            detail: "The detail 2",
        },
        {
            label: "My label 3",
            description: "The description 3",
            detail: "The detail 3",
        }
    ];

    await vscode.window.showQuickPick(items);
```

**Comment by bwateratmsft** [comment]
Closing as external, external item is https://github.com/microsoft/vscode/issues/84062.
