### ISSUE TITLE
Error rates: Better error messages for image deletion failure

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1398]
One of the most common two errors we see from telemetry relate to failed image deletion, for the following two reasons:
- image has dependent child images
- image is being used by running container xxx

We should catch these two, provide a clearer error message, and suppress the Report Issue button.

See #1391, #1354, #1362, #1357, #1208, #1126, and probably even more.

**Comment by bwateratmsft** [comment]
Similar idea of reducing error rate w/ #1323, #1383.

**Comment by v-dantch** [comment]
Verified on the candidate [20200122.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13983&view=results), display below notification when deleting an image which cannot be deleted.
![image](https://user-images.githubusercontent.com/34729092/72882992-7fd2a780-3d3e-11ea-8196-282b7332e847.png)
