### ISSUE TITLE
Use optional chaining where applicable

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1399]
[TypeScript 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) adds optional chaining (the glorious `?.` operator). We should review our usage of things like `foo && foo.bar && foo.bar.baz` and replace with `?.` as appropriate.

**Comment by bwateratmsft** [comment]
Please also note that `foo && foo.bar && foo.bar.baz` isn't exactly the same as `foo?.bar?.baz`. The former will stop on any falsy value (and return it), whereas the latter will only stop on `null`/`undefined` (and return it). In most cases this is not an issue because this should _only_ be used on `object?.object?.something` or similar--and the only falsy value for an object is `null`/`undefined` (except for `document.all` but we aren't getting into that).

**Comment by philliphoff** [comment]
We will use optional chaining going forward and only refactor where/when it makes sense.
