### ISSUE TITLE
can not stop the container

### ISSUE THREAD

**Issue by littlepai** [microsoft/vscode-docker#1404]
Repro steps:

1.
2.

Action: vscode-docker.containers.stop
Error type: 500
Error Message: (HTTP code 500) server error - cannot stop container: 77e643ef3418ed6fd4353e12a8a2a3a6a89314c7de46702bdf4e9e21dfb25add: Cannot kill container 77e643ef3418ed6fd4353e12a8a2a3a6a89314c7de46702bdf4e9e21dfb25add: unknown error after kill: runc did not terminate sucessfully: container_linux.go:389: signaling init process caused "permission denied"
: unknown 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

i just run docker-compose up -d
and then change the volume owner

**Comment by bwateratmsft** [comment]
@littlepai Can you add repro steps?
