### ISSUE TITLE
Ensure local images are up to date

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1409]

**Comment by bwateratmsft** [comment]
We have the `dockerBuild.pull` flag today, if true it is equivalent to using `--pull`. Currently it is treated as false if unspecified, but we can change that.

**Comment by philliphoff** [comment]
We should continue to treat unspecified as `false`, but we should instead scaffold `pull` to `true` in new tasks.

**Comment by eine** [comment]
> We should continue to treat unspecified as `false`, but we should instead scaffold `pull` to `true` in new tasks.

Since the default behaviour in docker is `false`, I think it should be better kept like that.

**Comment by philliphoff** [comment]
> Since the default behaviour in docker is false, I think it should be better kept like that.

Thanks for the feedback.  We've had discussions related to this behavior in Visual Studio, too, but users there seem to prefer the images kept up to date despite the Docker CLI's defaults, hence our wanting to copy that behavior in VS Code as well.  Scaffolding `pull` to `true` for new tasks is a bit of a compromise over simply changing the interpretation of omitting the value on a task; it also allows for changing our minds if VS Code users end up preferring the opposite behavior.
