### ISSUE TITLE
Unknown or unsupported transport “disabled” for address “disabled:”

### ISSUE THREAD

**Issue by RichardNilsson** [microsoft/vscode-docker#1411]
Repro steps:

1. Press "Connect registry..."
2. Choose "Docker Hub"
3. Insert Docker Hub username
4. Insert Docker Hub password
5. Press "enter"

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: Unknown or unsupported transport “disabled” for address “disabled:”

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

**Comment by bwateratmsft** [comment]
@RichardNilsson It looks like this is an issue with node-keytar, and fixed by installing gnome-keyring. Can you try installing gnome-keyring and see if that fixes the problem?

More information here: https://github.com/atom/node-keytar/issues/132

**Comment by alexeadem** [comment]
installing keytar/gnome-keyring doesn't fix the problem. Entry can't be removed. It should be a right click option to remove the entry
