### ISSUE TITLE
config

### ISSUE THREAD

**Issue by XSD-zhcn** [microsoft/vscode-docker#1415]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: The application folder 'c:\Users\Administrator\AppData\Local\Temp\Temp1_12121212.zip\gofaker-master' does not exist. Ensure that the 'appFolder' or 'appProject' property is set correctly in the Docker debug configuration.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppFolder extension.bundle.js:332:328464
```

</details>

**Comment by bwateratmsft** [comment]
@XSD-zhcn can you add repro steps?
