### ISSUE TITLE
Fail to execute the 'compose up' action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1416]
**OS:** All
**Build Version:** [20191108.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12238)
**Regression:** Previous Build [20191106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12147)

**Repro Steps:**
1. Create a certs folder with command "mkdir %USERPROFILE%\certs".
2. Download [mkcert ](https://github.com/FiloSottile/mkcert/releases) and rename it to mkcert.exe.
3. Install the mkcert.exe with below command:
- set CAROOT=%USERPROFILE%\certs\CARoot
- cd %USERPROFILE%\certs
- mkcert -install
4. Create a self-signed certification for SSL using the new CA certificate: mkcert 127.0.0.1.
5. Open the certs folder in VS Code and create a Dockerfile to this folder with below content.
- FROM registry
- #Create a password file with username=testuser, password=testpassword
- RUN mkdir /auth
- RUN htpasswd -Bbn testuser testpassword > /auth/htpasswd
6. Right click Dockerfile to build image using this tag: authregistry.
7. Save a docker-compose.yml to certs folder.
8. Right click on docker-compose.yml -> Compose Up.

**Expect:**
Execute 'compose up' action successfully without any error.

**Actual:**
Fail to execute the 'compose up' action.
![image](https://user-images.githubusercontent.com/45614674/68670708-7e3f7300-0588-11ea-8cd6-4a45e6716ca1.png)

**Comment by bwateratmsft** [comment]
I was not able to reproduce the issue. @v-ruizh, can you try removing the "authregistry" and "registry" base images, and try again and see if the issue still occurs?

Thanks!

**Comment by v-ruizh** [comment]
@bwateratmsft The issue also reproduces after removing all images. It also can be reproduced on Mac and Linux platform.

**Comment by bwateratmsft** [comment]
@v-ruizh Strange, I was testing on Mac and had no issues...

**Comment by bwateratmsft** [comment]
@v-ruizh I can repro if the `authregistry` image does not exist. Building that image (from right-click Dockerfile -> Build Image) and tagging it `authregistry` are part of the steps. Can you verify that you built the image and it is tagged `authregistry`?

Nevertheless, that compose file wasn't very well-crafted, so I've altered it and changed the test case steps. Now, you'll just need to save the Dockerfile and docker-compose.yml from the OneNote, then do Docker Compose Up on the docker-compose.yml file. It will build the Docker image automatically.
