### ISSUE TITLE
new docker file add problem in vs code . net core 3

### ISSUE THREAD

**Issue by arstev** [microsoft/vscode-docker#1420]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: No .csproj or .fsproj file could be found. You need a C# or F# project file in the workspace to generate Docker files for the selected platform.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:285638extension.bundle.js:1:285638
processTicksAndRejections task_queues.js:89:5
async C extension.bundle.js:1:285465
async t.configure extension.bundle.js:1:288220
```

</details>

**Comment by bwateratmsft** [comment]
@arstev Can you add repro steps? Is there a csproj / fsproj in your workspace?

**Comment by arstev** [comment]
I do not think so.
I was trying to use dotnet command tool.
Do you have a good resource on how to build microservice .netcore & docker?
Thank you
Arsen

________________________________

**Comment by bwateratmsft** [comment]
@haniamr Do you have a good sample project you can recommend as a starting point?

**Comment by bwateratmsft** [comment]
In the meantime I'll close this one as by-design.
