### ISSUE TITLE
.NET Core debugging fails with untrusted certificate

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1424]
When debugging a .NET Core web application on Windows using SSL where the SSL certificate is not yet trusted, VS Code will fail with the error `Error: Process exited with code 7`.

This is due to the `spawnAsync()` not throwing an `Error` object with the `code` property set (as is done by `child_process.exec()`, so the resulting `parseError()` cannot extract the error code, and the certificate trust logic cannot separate this "known" error from any other.

**Comment by bwateratmsft** [comment]
Good catch!
