### ISSUE TITLE
Add a "Copy full tag" command, helpful for things like Dive, etc.

### ISSUE THREAD

**Issue by sandipchitale** [microsoft/vscode-docker#1426]
Checkout [this](https://marketplace.visualstudio.com/items?itemName=sandipchitale.docker-dive) VSCode extension that integrates with [dive](https://github.com/wagoodman/dive) command. The `dive` command enables the exploration of layers in a Docker file. This extension also adds the Dive command with the image tag node in **Docker View:Images Viewlet** tree context menu.

**Comment by bwateratmsft** [comment]
Did you mean to link another VSCode extension?

**Comment by sandipchitale** [comment]
Oops forgot: https://marketplace.visualstudio.com/items?itemName=sandipchitale.docker-dive

**Comment by bwateratmsft** [comment]
Is this just promoting your extension? GitHub issues are not the right place for that.

**Comment by sandipchitale** [comment]
Wanted to make user of your extension aware of additional extension on top.

**Comment by bwateratmsft** [comment]
We appreciate the additional features but I'm not sure issues are the right place for this. @BigMorty do you think we can add a page on the Wiki with links to some other extensions users might be interested in, like this one and probably also Remote - Containers?

**Comment by bwateratmsft** [comment]
@dbreshears suggested, if you would like, you can also submit a PR into this repo to add this feature. It's up to you.

**Comment by sandipchitale** [comment]
Ok. I will look into it.

**Comment by sandipchitale** [comment]
OK. I will look into it.

**Comment by sandipchitale** [comment]
FIiled pull request: https://github.com/microsoft/vscode-docker/pull/1428

**Comment by dbreshears** [comment]
@sandipchitale Thank you for submitting a PR for the team to consider.  There are two aspects of this PR that we discussed. The first being the "Copy Full Tag" which seems to be a good addition to the Docker extension itself.  For the second aspect, where functionality is dependent on other downloads/utilities that we have no control over, we believe a better extensibility model is to encourage these extensions to build their functionality on top of the Docker extension, in a manner you have done.  We are also in discussion of including a section on the wiki to provide links to such extensions.      

Would you be willing to create a new PR with just the “Copy Full Tag” functionality?

**Comment by sandipchitale** [comment]
Sure. I can do that.

And I find Copy Full Tag command really useful because that is the format once needs in other docker CLI commands.

And I guess I will keep my extension going then.

**Comment by sandipchitale** [comment]
Filed a new PR with Copy Full Tag command only. See: https://github.com/microsoft/vscode-docker/pull/1431

**Comment by bwateratmsft** [comment]
I changed the title based on our current plan.

**Comment by philliphoff** [comment]
Resolved by #1431.
