### ISSUE TITLE
Review execution of container commands via palette

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1430]
Many (all?) of the container-related contextual commands are also available via the command palette.  In that scenario, the command will typically display a quick-pick prompt so the user can select a specific container.  However, several of these commands are valid only when a container is in a given state, which means they may fail if the wrong container is selected.

We should review each command to (1) determine whether it makes sense to be available via the command palette and (2) whether the quick-pick prompt should be filtered to show only containers relevant to the command.

**Comment by v-dantch** [comment]
#1576 This issue also reproduces.
