### ISSUE TITLE
Container and Image Icons corrupted

### ISSUE THREAD

**Issue by MikeWilliams-UK** [microsoft/vscode-docker#1432]
When I start VS Code and start our application via docker-compose up -d the icons for the containers and images are smudges as shown below.

![image](https://user-images.githubusercontent.com/13162784/68931425-69c9c900-0788-11ea-8107-cbce703ab0a8.png)

Can anyone advise on how to fix this please?

**Comment by MikeWilliams-UK** [comment]
My installed plug ins are shown below
![image](https://user-images.githubusercontent.com/13162784/68931657-e8bf0180-0788-11ea-8c58-d8e9c2d321bb.png)

**Comment by bwateratmsft** [comment]
Those icons are from the [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) extension (not this one). Their repository is here: https://github.com/formulahendry/vscode-docker-explorer, you will need to open this issue there.

TBH I'm not sure I understand why you have both of them installed as their functionality is most overlapped.

**Comment by MikeWilliams-UK** [comment]
Maybe that's the issue (having them both installed)

**Comment by bwateratmsft** [comment]
That could be. I looked through their contributions in package.json and it seems they are _mostly_ not using the same IDs, but the views do use the same IDs and therefore could be "stepping on each others feet" so to speak.
