### ISSUE TITLE
error

### ISSUE THREAD

**Issue by truonghdpk** [microsoft/vscode-docker#1433]
Repro steps:

1.
2.

Action: vscode-docker.volumes.remove
Error type: 409
Error Message: (HTTP code 409) conflict - remove mymagento2faild_dbdata: volume is in use - [744544e92b3749abaaa0f93f97f6eb636fcc80b064848652ad6863f2505a32e4] 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment]
@truonghdpk can you add repro steps?
