### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by pmcastell** [microsoft/vscode-docker#1438]
Repro steps:

Action: vscode-docker.images.remove
Error type: ECONNRESET
Error Message: socket hang up

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
connResetException errors.js:559:14
Socket.socketOnEnd _http_client.js:436:23
Socket.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@pmcastell Is this issue repeatable?  If so, could you add repro steps?

**Comment by pmcastell** [comment]
I am afraid I have not be able to repeat it, philliphoff. I let you know as soon as it happens to me again. Thanks

**Comment by bwateratmsft** [comment]
I will close this issue since we haven't heard back in a while, but please let us know if the problem reoccurs! Thanks!
