### ISSUE TITLE
Docker Connect Registry

### ISSUE THREAD

**Issue by mikaelosterberg** [microsoft/vscode-docker#1442]
Repro steps:
Add local gitlab container registry using user token. 
container registry uses self signed cert.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.8.2
OS: linux (Kbuntu)
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

**Comment by bwateratmsft** [comment]
Dupe of #722
