### ISSUE TITLE
Failure to pull image

### ISSUE THREAD

**Issue by aidandj** [microsoft/vscode-docker#1443]
Repro steps:

1. Connect to private repo (I can see all images on the registry
2. Try to pull an image.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login http://<ip:port> --username admin --password-stdin
time="2019-11-21T12:59:19-08:00" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://<ip:port>/v2/: http: server gave HTTP response to HTTPS client"
Get https://<ip:port>/v2/: http: server gave HTTP response to HTTPS client

Version: 0.8.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by philliphoff** [comment]
@aidandj What kind of registry were you using?  Does that registry support HTTPS?

**Comment by aidandj** [comment]
No idea. It was set up by a co-worker. I will confirm, thanks.

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
