### ISSUE TITLE
error while creating a new network from vs code (HTTP code 404) driver not found

### ISSUE THREAD

**Issue by madkaikar-ashish** [microsoft/vscode-docker#1444]
Repro steps:

1. Select Docker from the left most vertical tabs 
2. In Networks section click on Create 
3. Or in command palette Docker Networks:Configure Explorer

Action: vscode-docker.networks.create
Error type: 404
Error Message: (HTTP code 404) driver not found - could not find plugin bridge in v1 plugin registry: plugin not found 

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098extension.bundle.js:157:703098
extension.bundle.js:157:703061extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@madkaikar-ashish Are you using Windows containers?  Also, did you try to create a `bridge` network?

I can reproduce the issue on Windows, using Windows containers, when creating a `bridge` network.  Apparently there are differing sets of Docker network types depending on whether using Linux containers vs. Windows containers.  We'll likely need to dynamically populate the network type quick-pick prompt based on target platform.
