### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anilk372** [microsoft/vscode-docker#1446]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1054:14
```

</details>

**Comment by philliphoff** [comment]
@anilk372 Is this error repeatable?  If so, could you provide repro steps?
