### ISSUE TITLE
delete image in linux

### ISSUE THREAD

**Issue by xDemon200** [microsoft/vscode-docker#1447]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete ea85a3a4491c (cannot be forced) - image has dependent child images 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@xDemon200 Was this error repeatable?  If so, could you provide repro steps?  From the error, it looks like the image being deleted had derived images; is that the case (in which case we would expect not being able to delete it)?

**Comment by xDemon200** [comment]
Hello, i was able to solve the issue. it was caused by the container created because it stayed running as i tried to delete it. solution: stop the container and delete the image.

`docker stop <id>`
`docker rmi <id_image>`
