### ISSUE TITLE
Cannot install or upgrade to 0.0.19

### ISSUE THREAD

**Issue by goofansu** [Microsoft/vscode-docker#145]
vscode version: 1.17.1

Cannot install or upgrade either from vscode _Extensions_ tab or [marketplace website]( https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker).

Error: `end of central directory record signature not found`

**Comment by chrisdias** [comment]
sorry about this!  see: https://github.com/Microsoft/vscode/issues/34730 for potential workarounds

@joaomoreno this is the 2nd time this week I've heard about this for the docker extension...

**Comment by goofansu** [comment]
@chrisdias Thanks. Install the vsix successfully.
