### ISSUE TITLE
 vscode-docker.containers.start error 500

### ISSUE THREAD

**Issue by sy2un** [microsoft/vscode-docker#1450]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint londx_postgres_1 (b984407764a792023057a7d7da34d04b423cf8bbc1116ef027a97df33cb5ac0c): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use 

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098
extension.bundle.js:157:703061
module.exports.m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by philliphoff** [comment]
@sy2un Is this error repeatable?  If so, can you provide repro steps?
