### ISSUE TITLE
debugCoreClr

### ISSUE THREAD

**Issue by projaet** [microsoft/vscode-docker#1451]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:332:326003
extension.bundle.js:332:325823
Object.<anonymous> extension.bundle.js:1:479255
extension.bundle.js:1:477347
n extension.bundle.js:1:477124
Object.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:479174
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:332:325754
extensionHostProcess.js:729:964
```

</details>

**Comment by projaet** [comment]
Why it doesn't work?Can anyone help me?

**Comment by karolz-ms** [comment]
@projaet can you add repro steps (what led to the error above)?

**Comment by projaet** [comment]
@karolz-ms Well,firrst,I'm sorry for reply so late,then,here is my repro steps if them can help you,
![72Z3 A1KDGL4C}M%NH7BB}8](https://user-images.githubusercontent.com/55475905/69880241-71e74400-1304-11ea-8508-efc87001aaeb.png)and,I choose the Docker:Launch.NET Core(preview)
![image](https://user-images.githubusercontent.com/55475905/69880542-22edde80-1305-11ea-9577-05032324ba5a.png)
,and the error came,like this
![9E2J$ Y)}QAJJXZ6L8%1 Y3](https://user-images.githubusercontent.com/55475905/69880623-61839900-1305-11ea-9831-621c36a40a18.png)

**Comment by karolz-ms** [comment]
@projaet thanks and sorry for late reply

Looks like you have a C++ program here. Not sure if this is what you are trying to do, but the Docker extension does not support debugging C++ programs running as a container. By using `Docker: Launch .NET Core` command you are trying to debug your program using .NET debugger (for C# programs), which is not going to work.

You can use the Docker extension to build an image of your program and run it (create a container instance of that image), just not debug. Note that a "Hello World!" program like this will immediately exit, leaving the container in a "stopped" state, but you can still look at the container logs using Docker view in VS Code.

Hope this helps!

**Comment by projaet** [comment]
@karolz-ms Thanks for your help!It's my mistakes that occurs your time,and your reply do really help me!
