### ISSUE TITLE
Erro na criação de container

### ISSUE THREAD

**Issue by mauromaurer** [microsoft/vscode-docker#1452]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - error while creating mount source path '/host_mnt/c/php717www/Docker/DockerAnywhere16/contabil': mkdir /host_mnt/c: file exists 

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703098extension.bundle.js:157:703098
extension.bundle.js:157:703061extension.bundle.js:157:703061
m.buildPayload extension.bundle.js:157:703071
IncomingMessage.<anonymous> extension.bundle.js:157:702571
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by karolz-ms** [comment]
@mauromaurer could you add repro steps?
