### ISSUE TITLE
Add "start all containers" option

### ISSUE THREAD

**Issue by messi-yang** [microsoft/vscode-docker#1453]
Add "start all containers" option

**Comment by philliphoff** [comment]
@messi-yang Could you provide a little more context to this request?  You'd like an option (e.g. in the containers tree view) to start all existing containers, or only those in a particular state (e.g. paused), etc.?

**Comment by messi-yang** [comment]
@philliphoff Sure, I want an option to start all existing containers in containers list view. Same as the command: docker start $(docker ps -a -q). If some containers are already started, we just skip them.
![image](https://user-images.githubusercontent.com/17985592/70030814-f37cf180-15e4-11ea-8f1d-4b8e0c2b32e9.png)

**Comment by philliphoff** [comment]
While a "start all" command may not be the best overall option, [`1.38`](https://code.visualstudio.com/updates/v1_38#_multiselect-in-custom-tree-view) of VS Code added support for multi-select within tree views which may provide reasonably equivalent behavior.

**Comment by messi-yang** [comment]
@philliphoff Could you provide the right action for multi-select within tree views, or the keyboard shortcuts? My environment is Mac OS 10.15.1. Thanks.

**Comment by philliphoff** [comment]
@messi-yang Sorry, that was just intended to be a note for future implementors.  VS Code (relatively) recently provided support for tree views to allow multi-selection, but individual tree views still have to opt-in to that support and update their command handlers to accommodate the change--that means code changes before users can actually use multi-select.  That enhancement is being looked at for the future, but I can't say for sure when it might end up in the product.

**Comment by messi-yang** [comment]
@philliphoff Got it, very thanks for providing this information to me.

**Comment by allanwright** [comment]
I have created PR #1620 to address this feature request.

**Comment by bwateratmsft** [comment]
This would also be covered by the fix for #331.

**Comment by bwateratmsft** [comment]
Multi-select is now available for many commands in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
