### ISSUE TITLE
409 like it doesnt exist

### ISSUE THREAD

**Issue by will7455** [microsoft/vscode-docker#1454]
Repro steps:

1.
2.

Action: vscode-docker.images.push
Error type: Error
Error Message: Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/.vscode')

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
S.writeFile workbench.desktop.main.js:1558:224
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by philliphoff** [comment]
@will7455 Is this error repeatable?  If so, could you provide repro steps?
