### ISSUE TITLE
Remote Containers using SSH doesn't work in Windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-docker#1458]
Related to microsoft/vscode-remote-release#1935

- I confirmed that I can successfully connect to the remote machine using SSH via command line
- There is no error in the entire UI, just loading progress bars when opening the Docker viewlet
- When running `Attach to Running Container`, nothing happens
- When I open devtools, this is what I see:

![image](https://user-images.githubusercontent.com/22350/70048648-14d0e400-15cb-11ea-946e-3ef839e581b1.png)

**Comment by philliphoff** [comment]
@joaomoreno Can you provide repro steps and what version of VS Code and vscode-docker you're using?

**Comment by joaomoreno** [comment]
This was the latest VS Code Insider and latest vscode-docker from 6 days ago. I don't have access to the machine right now. I tested it on a fresh VM: install VS Code, Docker extension, Docker for Windows, Git for Windows, create SSH key, make sure you can `ssh` from Command Prompt solely using the key. Once all of that is done, simply configure the remote docker setting to the `ssh://` format.

**Comment by diablodale** [comment]
I have same error messages in my VSCode Log(Window). They appear forever, the UI does not update, and there is no give-up and report error dialog.

```
[2019-12-22 14:14:19.184] [renderer12] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-22 14:14:21.154] [renderer12] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
```

Issue Type: <b>Bug</b>

SSH docker.host, e.g. `"docker.host": "ssh://username@mylanserver"
Click on docker icon on VSCode left navbar
Results in no UI updates for the docker extension. Forever errors in log.

May be related to https://github.com/microsoft/vscode-remote-release/issues/937

## Setup

* local Windows 10 1909  build 18363.535
* remote Ubuntu 18.04.3 LTS
* VS Code for Windows 1.41.1 (system setup)
* Docker extension 0.9.0
* Remote Development 0.19.0
* Remote SSH 0.48.0
* Remote WSL 0.41.6
* Remote Containers 0.94.0
* Have working SSH ~/.ssh/config and key setup for seamless ssh usage in WSL.
* Have working shim bat file that if VSCode needs to run `ssh` from windows, that it is routed to WSL. This includes the setting `"remote.SSH.path": "C:\\mybatfile.bat"`
* Have working remote explorer that successfully shows containers on this remote SSH target
* Have working Remote-SSH solution to this remote docker host
* In main settings for VSCode, set `"docker.host": "ssh://username@mylanserver"`

## Repro

1. Open VSCode
2. Click docker icon in left nav bar

## Result

Docker extension UI (containers, images, registries, etc.) are forever blank. Top blue progress bar/slice forever goes left and right. Log (Window) has forever errors...

```
[2019-12-22 14:14:19.184] [renderer12] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-22 14:14:21.154] [renderer12] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-22 14:14:21.207] [renderer12] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-22 14:14:21.245] [renderer12] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-22 14:14:23.191] [renderer12] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2019-12-22 14:14:25.163] [renderer12] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-22 14:14:25.203] [renderer12] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

## Expected

The Docker extension to show me the images, running containers, etc. on my remote docker host.

## Notes

1. From WSL I can run `ssh username@mylanserver` and it seamlessly connects and I get a prompt
2. On that prompt I can run `docker container ls` and see all the containers
3. On that prompt I can run `docker run hello-world` and I get the successful expected output

The error message above are suspicious. They say `pipe`. Doesn't that imply Windows connectivity? It shouldn't be using Windows connectivity. It should be using WSL, unix, ssh connectivity.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 5.0.0-37-generic
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: home-nas|
|OS|Linux x64 5.0.0-37-generic|
|CPUs|Intel(R) Pentium(R) CPU G3258 @ 3.20GHz (2 x 1974)|
|Memory (System)|7.66GB (2.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|
</details>

**Comment by zifik** [comment]
I am experiencing the exact same thing as @diablodale.

I was able to eliminate the "openssh-ssh-agent" error messages by starting the "ssh-agent" service in Windows 10: I found this helpful: https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro

I am perplexed by this as I am able to run `docker -H ssh://user@ip ps` from Powershell and WSL just fine.

**Comment by zifik** [comment]
Additionally, I see theses messages if I open the vscode developer tools from Help:
`mainThreadExtensionService.ts:66 Error: All configured authentication methods failed`

**Comment by zifik** [comment]
Ok, so I figured it out for my purposes -- finally.

My situation was practically identical to what @diablodale describes. 

**SOLUTION**

Even though you have your keys setup and you can do example commands like `docker -H ssh://user@ip ps`, you can still run into auth issues because this extension is specifically making using of the "ssh-agent" under the hood.

_**IMPORTANT**: Don't get these steps confused with similar things that can be done in WSL. Things done in WSL do not affect the outcome. This extension does not use WSL under the hood even if you have your terminal configured to use WSL. You must have it setup through the means the Windows OS uses._
1. Follow directions [here](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent) to enable the Windows SSH-Agent.  This addresses the errors with the ` \\.\pipe\openssh-ssh-agent` in the message.
2. Ensure that you have your SSH keys inside of `<windows user folder>/.ssh/`. 
3. Run `ssh-add` from powershell. This was the last part that I was missing and why I would get `All configured authentication methods failed`

In the end, would be nice if these errors were caught and the users were notified of the GUI of what actions might be needed.

**Comment by bwateratmsft** [comment]
I agree with @zifik. There's nothing we can do about the fact that our dependencies (`dockerode`, `ssh2` NPM packages) require an auth agent, but we can look at warning the user if they have an SSH DOCKER_HOST but no agent set up. A Learn More link to the [Wiki page on SSH setup](https://github.com/microsoft/vscode-docker/wiki/SSH) would probably also help.

**Comment by bwateratmsft** [comment]
We have improved the warnings for this in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
