### ISSUE TITLE
[Suggestion] Auto refresh after installing Azure Account Extension

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1461]
**OS**: Mac
**Build Version:** [20191203.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12805)
**Regression:** Not a Regression

**Repro Steps:**
1. Uninstall all dependencies of Azure Account Extension --> Uninstall Azure Account Extension.
2. Use "Connect Registry" button to connect Azure --> Prompt to install Azure Account Extension.
![image](https://user-images.githubusercontent.com/34729092/70120053-98abce80-16a6-11ea-9296-3f1661a1d8a8.png)
3, Install Azure Account Extension.

**Actual**:
Need to refresh manually after installing Azure Account Extension.

**Suggestion:**
Auto refresh after installing Azure Account Extension.

**Comment by philliphoff** [comment]
That seems like a reasonable thing to do.
