### ISSUE TITLE
Attach Shell should label the Terminal window with Container name not image name

### ISSUE THREAD

**Issue by rstaylor** [microsoft/vscode-docker#1463]
When you attach a shell via this docker extension the name given the terminal shell is the Image name.  If you have several copies of the same image used in running containers it makes it difficult to tell which shell you are looking at.  Please change or provide the option to change this to the container name.  

This can be seen when you attach a shell then look in the dropdown list for available terminal windows.

![image](https://user-images.githubusercontent.com/3357911/70158781-d5b39900-1685-11ea-802a-fdeab3045eb9.png)

In this image you can see the name given the terminal session is "Shell:nsmttest:2008".  The 'nsmttest:2008' is the image name.  As I can have more than one container run from this image it makes it hard to tell the difference when you have mutiple shells open at the same time.

**Comment by philliphoff** [comment]
That sounds like a reasonable thing to do.  It looks like it just requires a small tweak to [attachShellContainer.ts](https://github.com/microsoft/vscode-docker/blob/8f74a63c9eec84248a9ddae463ac4dd7c055ba04/src/commands/containers/attachShellContainer.ts#L29).
