### ISSUE TITLE
.service file not found

### ISSUE THREAD

**Issue by jordan-public** [microsoft/vscode-docker#1466]
Repro steps:

1.Sign up to Docker Hub
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

**Comment by jordan-public** [comment]
This is on Pixelbook i7/16G/512G

**Comment by philliphoff** [comment]
@jordan-public Can you provide more context about your setup (e.g. Linux distro, etc.)?  I don't see the issue on my Ubuntu test VM, for example.  Based on the error message, it may just be an issue with the keyring setup/dependencies.  You might look at this [issue](https://github.com/MicrosoftDocs/live-share/issues/224) to see if its resolution helps you.

**Comment by jordan-public** [comment]
It's the latest Google Pixelbook linux beta distro (inside ChromeOS)- see the uname output below. 
To reproduce:
1. Install Visual Studio Code
2. Add Docker plugin
3. Sign up to the Docker registry (docker.com) -->> fails with the above complain

$ uname -a
Linux penguin 4.19.69-06666-g6c4f8cbba24e #1 SMP PREEMPT Fri Sep 6 22:15:24 PDT 2019 x86_64 GNU/Linux

Please let me know if you need more info.

**Comment by philliphoff** [comment]
Unfortunately, I don't have access to a Pixelbook and am not familiar with how it leverages VMs to run that Linux distro.  From what I gather, Debian is the closest match to that distro, but I don't see the same issue on a fresh install (nor on Ubuntu or Mint).  Was the [link](https://github.com/MicrosoftDocs/live-share/issues/224) above any help?  Given that the "Linux (beta)" distro is supposed to be stripped down from a standard distro, perhaps its just missing some security/password management packages that's assumed by VS Code.

**Comment by nickdex** [comment]
Having same issue on Manjaro with KDE. I was able to login via CLI without any issues.

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.15-1-MANJARO
