### ISSUE TITLE
Telemetry for .NET Core Docker scaffolding log "compose" orchestration  

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1469]
It appears that telemetry for Docker scaffolding command is incorrectly setting the `orchestration` property for non-Node.js platforms to `docker-compose`.  (As, currently, only Node.js makes a distinction between the two orchestration flavors, that value should probably be left blank.)

**Comment by bwateratmsft** [comment]
That was intentional on my part. Those other orchestrations (aside from .NET) _are_ compose. :)

**Comment by ravipal** [comment]
It is no longer an issue, fixed by @philliphoff .
