### ISSUE TITLE
Make Registries extensible (support custom registries)

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docker#147]
The Registries node should be extensible in that someone can write an extension that provides support for Azure, AWS, or whatever they like.  This includes the browsing of the registries plus any deployment if they so desire.

Azure support then moves to a "Docker Azure" extension and the user of the Docker extension can install/enable it separately.

**Comment by YvanGuidoin** [comment]
I uninstalled the extension as soon as I have seen the forced push to the Azure crap, I know it's a Microsoft software, but please keep it clean, add Azure support in another package, not as a dependency you can't get rid of.

**Comment by chrisdias** [comment]
@YvanGuidoin I should have an update out today, see https://github.com/Microsoft/vscode-docker/pull/149

**Comment by YvanGuidoin** [comment]
@chrisdias Thanks a lot

**Comment by chrisdias** [comment]
@YvanGuidoin i've updated the extension to not have a hard dependency on the Azure Account extension. I'll work on making it pluggable over the next few weeks.

**Comment by phil-harmoniq** [comment]
@chrisdias Any updates on this? It would be pretty neat to have support for custom registries. :)

**Comment by chrisdias** [comment]
@phil-harmoniq i made some good progress before the holidays in the [chrisdias/extensions](https://github.com/Microsoft/vscode-docker/tree/chrisdias/extensions) branch. The [Azure extension](https://github.com/Microsoft/vscode-docker-azure-ext) then extends the Docker extension.  Still lots of work to do, but it is a start.

**Comment by fiveisprime** [comment]
I'd also like to work with a custom registry. What's the status on this?

**Comment by timjesp** [comment]
@chrisdias any updates on this 😄  ?

**Comment by squillace** [comment]
@chrisdias Hi Chris, I'm running into customers and users all over the world who would like to see their own registries in this extension. Let's chat about how to help get that done. @SteveLasker @itowlson, @akaroml.

**Comment by chrisdias** [comment]
Support for extensions to the extension is this branch:  https://github.com/Microsoft/vscode-docker/tree/chrisdias/extensions. This would let people write extensions to the Docker extension that would then provide support for additional registries. 

But it is a tricky setup after the branch is merged in. For example, you have to symlink extensions together to develop/debug them locally. 

@fiveisprime and @StephenWeatherford are going to start helping out with the extension, so we should prioritize this on the backlog as there have been quite a few requests.

**Comment by squillace** [comment]
That's cool but in the case I'm describing, they just want to be able to use a docker login to add an entry. They aren't looking for more than that at this point.

However, you will have a more holistic picture of requests than I will...

**Comment by zhangtbj** [comment]
Thanks a lot for your introduction today @squillace ! :)

We just used the common command to login our registry: docker login -u <username> -p <password> <registry_url>

So I think this is a standard usage, right now I cannot config the docker registry setting in CODE, only support me to use default dockerhub.

It is better for all of the people to use their custom docker registry.

Thanks a lot! :)

**Comment by SteveLasker** [comment]
We’ve just started integrating ACR and ACR build into the extension. Perhaps we can help with the generic and unique registry light up scenarios. 
@zhangtbgj, would showing all registries you have configured through docker login, in the docker config file be relevant?

**Comment by StephenWeatherford** [comment]
#18

**Comment by PrashanthCorp** [comment]
We already handle private registries and expanding support for other functionality. We shall revisit these in a bit.

**Comment by bwateratmsft** [comment]
I think we can close this now since this is largely done, especially with #1753.
