### ISSUE TITLE
Docker: Add Docker Files to Workspace

### ISSUE THREAD

**Issue by lpf0712** [microsoft/vscode-docker#1470]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:423244
extension.bundle.js:1:305167extension.bundle.js:1:305167
Object.t.captureCancelStep extension.bundle.js:157:373232
S extension.bundle.js:1:299147
t.configure extension.bundle.js:1:305148
extension.bundle.js:324:343471extension.bundle.js:324:343471
```

</details>

**Comment by philliphoff** [comment]
@lpf0712 In order to scaffold Docker-related files for a project, that project's folder must be opened in VS Code.  Did the error occur in some other scenario?  If so, could you provide repro steps?
