### ISSUE TITLE
not able to connect to local docker

### ISSUE THREAD

**Issue by bowdenk7** [microsoft/vscode-docker#1471]
![image](https://user-images.githubusercontent.com/820883/70364704-85ce0100-1842-11ea-8509-4ba408ed1fa8.png)

Tried restarting docker. 

Not sure what `docker-machine` is but @fiveisprime ran 
```
> docker-machine ls
```
and it returned nothing so maybe that helps.

Let me know if there is any other information I can pull.

**Comment by philliphoff** [comment]
@bowdenk7 So `docker version` returns data for both client and server?  Which version of Docker are you using (and on which platform)?

**Comment by bowdenk7** [comment]
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

MacOS

**Comment by philliphoff** [comment]
Is your Docker engine running on your local Mac or are you connecting to a remote Docker host?

**Comment by bowdenk7** [comment]
I have docker running locally. It's possible I tested using a remote docker host at some point, but i do currently have Docker installed and running locally.

**Comment by philliphoff** [comment]
Do you have any `DOCKER_HOST`, `DOCKER_CERT_PATH` environment variables set or are there any specific values set for the `Docker: Host` or `Docker: Cert Path` VS Code settings?
