### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Kumar-Ashish-Jha** [microsoft/vscode-docker#1473]
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: Unknown or unsupported transport “disabled” for address “disabled:”

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

**Comment by philliphoff** [comment]
@ashijha Can you provide some context for the error?  What kind of registry were you attempting to connect to?  When in the connection process did you see that error?  Is the error repeatable?  What distribution of Linux are you using?

That error has been seen before (see [#945](https://github.com/microsoft/vscode-docker/issues/945)) and may be related to setup of the Linux key ring.  Let us know if the remedies in that issue do not resolve the issue.
