### ISSUE TITLE
Default registry value is not used during docker push

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1478]
The registries lists shows an option to set a default registry as shown below. I set "MainACR" as default.
![image](https://user-images.githubusercontent.com/1775825/70483512-83b3ae80-1a9d-11ea-99bd-ee37bbbdccef.png)

Then during "Docker Images: Push" again I got the below prompt to save mainacr as default registry.

![image](https://user-images.githubusercontent.com/1775825/70483572-c83f4a00-1a9d-11ea-9238-8aca7c24cc3a.png)

**Comment by philliphoff** [comment]
The problem is that the extension does not check whether a default already exists before prompting to save a tagged image prefix as the default.
