### ISSUE TITLE
redis-test

### ISSUE THREAD

**Issue by yundd** [microsoft/vscode-docker#1479]
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: To build Docker files you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:423244
t.buildImage extension.bundle.js:324:86939
extension.bundle.js:324:343471extension.bundle.js:324:343471
```

</details>

**Comment by philliphoff** [comment]
@yundd Is this issue repeatable?  If so, could you provide repro steps?

**Comment by yundd** [comment]
不行啊

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
