### ISSUE TITLE
Please remove dependency on "Azure Account"

### ISSUE THREAD

**Issue by bmhatfield** [Microsoft/vscode-docker#148]
Somewhat relates to https://github.com/Microsoft/vscode-docker/issues/147

Hi There,

The Docker VSCode extension recently added an "Azure Account" dependency, which was automatically added to the VSCode extensions list on my machine. I don't use Azure, and as such would like to uninstall the unused dependency. I strongly prefer to keep things tidy and not pull in extensions that I won't use.

Please consider another avenue to providing this functionality to the folks who would like it.

Thank you!
Brain

**Comment by chrisdias** [comment]
working on it right now... https://github.com/Microsoft/vscode-docker/pull/149

**Comment by chrisdias** [comment]
fixed and published, thanks for the feedback.

**Comment by bmhatfield** [comment]
Thank you, works as expected!
