### ISSUE TITLE
can't delete registry entry with name not resolving

### ISSUE THREAD

**Issue by alexeadem** [microsoft/vscode-docker#1480]
Repro steps:

1. add registry endpoint as http://localhostl.com ( <+ See  typo in the spelling) - Can't be resolved
2. Right click to disconnect in docker explorer and fails

Action: vscode-docker.registries.disconnectRegistry
Error type: Error
Error Message: Unknown or unsupported transport “disabled” for address “disabled:”

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

It should be just an easy way to delete the entry... Any registry entry

**Comment by philliphoff** [comment]
@alexdima The error may be related to installation of `keytar` (see #945).

That said, such an error shouldn't prevent the entry from being removed.
