### ISSUE TITLE
sempre esse mesmo erro

### ISSUE THREAD

**Issue by hevertonpablo** [microsoft/vscode-docker#1481]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint laradock_apache2_1 (99a1312bd4a0ef829d675d2a5be322c9f5e56a7d0d48f984096e772c0ce01746): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500 

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546extension.bundle.js:324:440546
extension.bundle.js:324:440508extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@hevertonpablo Is this error repeatable?  Can you start the image using the command line (and thereby testing whether Docker itself is in a good state)?  If so, can you provide any repro steps?
