### ISSUE TITLE
[Suggestion] Support Azure File name

### ISSUE THREAD

**Issue by sembaye** [microsoft/vscode-docker#1483]
As a Azure Developer i want to use the Features of the Plugin (Possible when choosing a filename which ends whith .Dockerfile). It would be nice if the Plugin supports another filename constellation which is used in Azure ecosystems. (See pic)

![image](https://user-images.githubusercontent.com/13312166/70636302-952fbe80-1c35-11ea-9413-678b60fdcee0.png)

**Comment by bwateratmsft** [comment]
Hey @sembaye,

It is possible to make this work with simple user or workspace settings. We've discussed different patterns for Dockerfiles to improve the recognition. One suggestion that has come up many times is `Dockerfile.*`, but we feel that pattern is too broad. We have seen examples of non-Dockerfile source files, like `Dockerfile.cs` or `Dockerfile.js`, etc.

There's a few different things you can do.

The first option is to change the language mode to `Dockerfile`, with `Change language mode` in the command palette. Unfortunately this is only temporary.

For a more permanent fix, you can add additional file associations, either as workspace settings (so, other people using the repo will get them), or user settings (so, you will get them across any repos you open).
1. From the command palette, run `Preferences: Open Workspace Settings` or `Preferences: Open User Settings` (whichever you want the settings attached to).
1. In the search box, enter `files.associations`, and then click `Edit in settings.json`. 
![image](https://user-images.githubusercontent.com/36966225/74261059-97aba480-4cc8-11ea-805b-75f5f58646ea.png)
1. In the settings.json, paste the following and save:
```
{
    "files.associations": {
        "Dockerfile.*": "dockerfile"
    }
}
```

This will allow you to associate any file patterns you want with the `dockerfile` language.
