### ISSUE TITLE
On remove container 

### ISSUE THREAD

**Issue by alysonfs** [microsoft/vscode-docker#1485]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete e116d2efa2ab (cannot be forced) - image has dependent child images 

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@alysonfs Is this issue repeatable?  If so, can you provide repro steps?  From the error, it appears it was an attempt to remove an image that served as a base image for other images, so removal failing would be expected.  That said, do you have an opinion on a better way to handle that situation (e.g. better messaging, an option to force removal, an option to remove all related images, disable remove command in such situations, etc.)?
