### ISSUE TITLE
Error in docker extention

### ISSUE THREAD

**Issue by NeerajDana** [microsoft/vscode-docker#1491]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1054:14
```

</details>

**Comment by philliphoff** [comment]
@NeerajDana Is this error repeatable? If so, can you provide repro steps? From the error message, I'd guess it's permissions problem connecting to Docker; can you perform Docker operations from a command line?
