### ISSUE TITLE
WORKDIR paths should be absolute

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-docker#1492]
1. F1 > `Docker: Add Docker Files to Workspace`
2. `ASP․NET Core`

The generated `Dockerfile` has an error on `WORKDIR "/src/."`. See below:

![image](https://user-images.githubusercontent.com/88981/70853276-b4a14280-1ee6-11ea-8bd1-65b59eae0201.png)

I have to remove double quote manually to remove the warning.

![image](https://user-images.githubusercontent.com/88981/70853281-c71b7c00-1ee6-11ea-9562-42f610ad9083.png)

Is this kind of bug in vscode-docker?

**Comment by rcjsuen** [comment]
@doggy8088 This is an issue with the linter where it isn't taking the quotation marks into account correctly. I have opened rcjsuen/dockerfile-utils#67 to track this.

Thank you for your bug report and have a great day!

**Comment by doggy8088** [comment]
@rcjsuen Thanks!

**Comment by bwateratmsft** [comment]
@rcjsuen Would we need a new version of `dockerfile-utils` published to consume the fix in https://github.com/rcjsuen/dockerfile-utils/commit/11ef5d225d05bc79cb6435a78c89123e8efc03e1?

**Comment by rcjsuen** [comment]
@bwateratmsft You'll need a new version of the language server to get the fix. When are you planning to cut a new release?

**Comment by bwateratmsft** [comment]
The powers that be tell me sometime in the next couple weeks. @BigMorty to keep me honest.

**Comment by BigMorty** [comment]
We are actually planning a small release fairly soon, how soon could we integrate a new version of the language server with this fix? Otherwise the next release will be a number weeks out; we don't have a specific date at this time.

**Comment by rcjsuen** [comment]
@BigMorty The size of the pull request is often rather miniscule (as the change is really a simple change to the `package.json` file). Let me tie up some loose ends and then I'll push out a new release for you.

**Comment by rcjsuen** [comment]
@bwateratmsft @BigMorty Opened #1619 to upgrade the language server.

**Comment by bwateratmsft** [comment]
Should be fixed now by https://github.com/microsoft/vscode-docker/pull/1619.

**Comment by bwateratmsft** [comment]
Verified this is fixed.

**Comment by BigMorty** [comment]
@bwateratmsft, I assume we will integrate the new language server in our next major release?

**Comment by bwateratmsft** [comment]
@BigMorty Yep!

**Comment by bwateratmsft** [comment]
The fix for this is now available in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
