### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by Nguyenxuanvietanh** [microsoft/vscode-docker#1495]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint docker_web_1 (095529be1ddc7facb110b878df748e080e0a352b5a0106ef8d61266e48d5ea53): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500 

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546extension.bundle.js:324:440546
extension.bundle.js:324:440508extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@Nguyenxuanvietanh Is this error repeatable?  If so, can you provide repro steps?  Are you able to connect to and use Docker (e.g. start a container) on the command line?
