### ISSUE TITLE
Windows first run experience for WSL2

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#1498]
[This is a future item and depends on WSL 2 shipping in Mn.]

For customers who run the Docker extension for the first time, prompt them to the best possible path. This would be the option to run through WSL 2 setup and point them to the Docker Desktop for WSL 2.

**Comment by bwateratmsft** [comment]
WSL2 will probably become the "only" option eventually. In the edge channel installer it prompts you about WSL2, and seems to pretty strongly suggest using it. If you do, then the Moby VM isn't even present, it only uses WSL2. Karol has stated that the documentation and/or UI discourages going back to the Moby VM.

**Comment by dbreshears** [comment]
Mike will confirm with Docker, Inc.  that they will be prompting users to use WSL2 when available

**Comment by nebuk89** [comment]
Hey (from PM for DockerDesktop :) )
We will be prompting users to move to WSL 2 as part of their upgrade and will move this over to our default for new users as well! 

Thanks and let me know if you have questions!

**Comment by BigMorty** [comment]
Thanks Ben for confirming!

**Comment by bwateratmsft** [comment]
Here's what I see upon upgrading:
![image](https://user-images.githubusercontent.com/36966225/82940677-2e902a00-9f63-11ea-8c24-0bc7af1c639d.png)
:smile:
