### ISSUE TITLE
Support custom named Dockerfiles

### ISSUE THREAD

**Issue by Vloz** [Microsoft/vscode-docker#15]
The extension seems to works only with "Dockerfile" named files, and in some situation you have to set custom name (multiple dockerfiles in a single directory for docker composer for instance).

The probleme is i didnt see any name convention in such situations, some people are using **Dockfile_foo**, [compose's doc is using **Dockerfile-foo**](https://docs.docker.com/compose/compose-file/), and some people names it **foo.docker** ...

**Comment by PeterJausovec** [comment]
There's an issue in VS Code repo that's tracking this (https://github.com/Microsoft/vscode/issues/1851). In the meantime you could select the language mode manually in VS (however, you'll have to change it each it you open a file).
