### ISSUE TITLE
Annoying tooltip box

### ISSUE THREAD

**Issue by chranmat** [microsoft/vscode-docker#150]
Hi,

I recently started to use vscode-docker extension and I immediately discovered that the tooltip box displayed when writing code, have a quite annoying behavior.

STR:
1. Open vscode and install vscode-docker extension.
2. Start writing a new Dockerfile or open an existing Dockerfile
3. Start writing a RUN command

Expected behavior:
Tooltip box displayed at first, but disappear when continue writing, such as above lines can be used as reference when writing a new line.

Actual behavior:
Tooltip box stays on screen during the completion of the line and blocks the view for the above lines.

Screenshot attached:

<img width="578" alt="vscode-tooltip" src="https://user-images.githubusercontent.com/18611032/31713284-1a4db0d8-b3fe-11e7-85d4-0eb52e91daf8.png">

Best regards,
Christian

**Comment by rcjsuen** [comment]
The tooltip that you are seeing is a result of the `textDocument/signatureHelp` request provided by the language server. It is akin to the suggestion of parameter hints for a function or a method as you can see in the following JavaScript example.

![signature](https://user-images.githubusercontent.com/15629116/31722112-3cc39d6e-b456-11e7-867c-08010b24a184.gif)

Perhaps this feature isn't actually all that useful?

![signature2](https://user-images.githubusercontent.com/15629116/31722386-e70548a4-b456-11e7-851a-c892b27d1a56.gif)

**Comment by chranmat** [comment]
The feature it self is quite useful, its just the behavior of it how I can see it I find strange. Its not like the "videos" shown in your answer. Is this a local problem somehow?

**Comment by rcjsuen** [comment]
@chranmat I think it's dependent on where the text cursor is relative to the bounds of the editor.

For example, if you're at the top of the editor then the popup window should be drawn below the current text cursor (assuming of course that it is within the bounds of the monitor itself). Depending on how the tooltip window calculates its bounds, it may draw itself above the text cursor if necessary.

**Comment by mihai-dinu** [comment]
I have the same annoyance with the tooltip, especially noticeable for the RUN command where I have to write stuff in most of the times for a Dockerfile. If you have a RUN command split on multiple lines then the tooltip follows you to the end of the earth or until you click outside of the RUN commands.

I would love it to just disappear if you press ESC or something, but I don't know how possible that is.

**Comment by peterblazejewicz** [comment]
> I would love it to just disappear if you press ESC

I'm not sure if this is still a case, but it just exactly this (VSCode: Version 1.19.0 (1.19.0)

**Comment by chrisdias** [comment]
you can always turn this off (on a per language basis) in your settings file:

```json
    "[dockerfile]": {
        "editor.parameterHints": false,
        "editor.quickSuggestions": {
            "other": false,
            "comments": false,
            "strings": false
        }
    },
```

See [customizing IntelliSense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) for more information

**Comment by ibbles** [comment]
If I disable the tooptip using chrisdias' changes to the settings file, is there some keyboard shortcut I can press to bring up the tooltip when I need it?

**Comment by mihai-dinu** [comment]
@ibbles You might be able to use suggestions (ctrl + space on Mac) to at least see what options you have

**Comment by rcjsuen** [comment]
@ibbles As far as I know, you can use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd> (on Windows anyway) to get the dialog to pop up. Check your keybindings for `editor.action.triggerParameterHints` to see what your keyboard shortcut is.

**Comment by ibbles** [comment]
Both approaches work. Ctrl+Space twice on a partial command, such as `RU`, gives a short description on possible completions to the partial command, and  Ctrl+Shift+Space on a completed command, including the trailing space, gives a longer description.

**Comment by andrask** [comment]
@rcjsuen Thank you for the options write up. 

I vote for `1`.

To be honest, this type of info is useful practically only when someone is getting started with docker but it is easy to look it up in the Docs. Additionally, the Docs are already available if someone hovers the mouse over the keyword.

**Comment by StephenWeatherford** [comment]
@rcjsuen Just wondering if there are any updates on this.  Note: we plan to ship in about two weeks.

**Comment by StephenWeatherford** [comment]
Okay, looks like this one is our code, too...

**Comment by rcdailey** [comment]
> 
> 
> you can always turn this off (on a per language basis) in your settings file:
> 
> ```json
>     "[dockerfile]": {
>         "editor.parameterHints": false,
>         "editor.quickSuggestions": {
>             "other": false,
>             "comments": false,
>             "strings": false
>         }
>     },
> ```
> 
> See [customizing IntelliSense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) for more information

On the latest version of vs code, `editor.parameterHints` is now `editor.parameterHints.enabled`.

**Comment by zachvalenta** [comment]
> > you can always turn this off (on a per language basis) in your settings file:
> > ```json
> >     "[dockerfile]": {
> >         "editor.parameterHints": false,
> >         "editor.quickSuggestions": {
> >             "other": false,
> >             "comments": false,
> >             "strings": false
> >         }
> >     },
> > ```
> > 
> > 
> > See [customizing IntelliSense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense) for more information
> 
> On the latest version of vs code, `editor.parameterHints` is now `editor.parameterHints.enabled`.

the issue has stagnated but the workaround continues to be updated :)

**Comment by philliphoff** [comment]
@BigMorty This appears to be a function of the Dockerfile language service and not the extension itself.  For a change, we'd need to work with @rcjsuen to decide on the most appropriate action, with recognition that this would likely also impact other editors using the language service.

@rcjsuen Have you gotten any further feedback, within VS Code or the other editors, about this issue?  From my perspective, options (3) or (5) (the subset being the longer, more free-form flavor of the `RUN`, `CMD`, and `ENTRYPOINT` commands) seem like a good starting point.  I don't think we want to completely disable it, as that would tend to be inconsistent with the defaults for DockerCompose YAML.

**Comment by rcjsuen** [comment]
@philliphoff Outside of the feedback from this issue, I have not heard any feedback (positive or negative) regarding `textDocument/signatureHelp` from any other LSP client that is using my language server.

**Comment by BigMorty** [comment]
Agree we should not completely disable it. For those that want to disable it there are instructions on how to do so above.
