### ISSUE TITLE
1111

### ISSUE THREAD

**Issue by gongwei-23314** [microsoft/vscode-docker#1501]
Repro steps:

1.
2.

Action: docker-launch
Error type: Error
Error Message: To debug with Docker you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:65436extension.bundle.js:324:65436
Object.<anonymous> extension.bundle.js:1:434228
extension.bundle.js:1:432316extension.bundle.js:1:432316
n extension.bundle.js:1:432090
Object.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:434146
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:324:65364
extensionHostProcess.js:712:440extensionHostProcess.js:712:440
```

</details>

**Comment by philliphoff** [comment]
@gongwei-23314 Can you provide a bit more context related to this error?  Did you, in fact, have a folder or workspace open?  If so, was the `docker-launch` task was defined within the workspace file (as opposed to the `tasks.json`), in which case this might be a known VS Code issue?
