### ISSUE TITLE
debug asp.net core mvc 3.1 with vs code Error: Process exited with code 1

### ISSUE THREAD

**Issue by tech-cn** [microsoft/vscode-docker#1503]
Acquiring the latest .NET Core debugger...
Unable to acquire the .NET Core debugger.
Error: Process exited with code 1
Repro steps:

1.
2.

Action: docker-launch
Error type: 1
Error Message: Process exited with code 1

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:530610
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by tech-cn** [comment]
debug asp.net core mvc 3.1 with vs code

**Comment by philliphoff** [comment]
@tech-cn Is this issue reproducible?  If so, can you provide repro steps and/or additional context related to your project?
