### ISSUE TITLE
There is no output log for "Deploy" part after executing "Deploy Image to Azure App Service" action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1506]
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)

**Steps to reproduce:**

1. Go to REGISTRIES explorer and connect to the registry which has image pushed to it.
2. Right click the image and execute "Deploy Image to Azure App Service" action.
3. Check the output log.

**Expect:**
There is output log for "Deploy" part.

**Actual:**
There is no output log for "Deploy" part, only have logs for creating web app.
![image](https://user-images.githubusercontent.com/45614674/71408562-a3d89580-2679-11ea-8ca2-107c57f9416d.png)

**Comment by philliphoff** [comment]
@v-ruizh Is there specific output you were expecting to see?  Is this a regression from earlier versions, or more of a general request to see more output than currently shown?

**Comment by v-ruizh** [comment]
This is not a regression issue. Because this action named "**Deploy** Image to Azure App Service", but the output log and notification only say "Successfully created web app...". It would be better to add the output for "Deploy" part, such as "Successfully deploy image...".

**Comment by philliphoff** [comment]
@v-ruizh Ok, I see, it's more about consistency in the terminology between the command, output text, and notification text.  I'll let @BigMorty weigh in on what changes might be appropriate.
