### ISSUE TITLE
[Suggestion] Add an "Open" button to open the Azure website

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1507]
**OS**: All
**Build Version**: [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression**: Not a Regression

**Steps to reproduce:**

1. Go to REGISTRIES explorer and connect to the registry which has image pushed to it.
2. Right click the image and execute "Deploy Image to Azure App Service" action.
3. Check the notification.

**Actual:**
There is no "Open" button to open the website.
![image](https://user-images.githubusercontent.com/45614674/71408795-5f012e80-267a-11ea-8031-1e1ce8964979.png)

**Suggestion:**
Add an "Open" button, it will be convenient to access the website.

**Comment by philliphoff** [comment]
@v-ruizh Seems like a reasonable thing to do. Thanks for the suggestion!

**Comment by allanwright** [comment]
Pull request #1580 has been created to address this.

**Comment by v-ruizh** [comment]
Add the "Open" button on the new build [20200206.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14471&view=artifacts&type=publishedArtifacts), close it.
