### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by sarjonator** [microsoft/vscode-docker#1508]
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The user name or passphrase you entered is not correct.

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

**Comment by ravipal** [comment]
@sarjonator, the error message says "The user name or passphrase you entered is not correct.". Are you giving the right credentials and still the login fails?

**Comment by sarjonator** [comment]
Docker is want to update that end of issue.

**Comment by ravipal** [comment]
Based on your comment, I believe this is not an issue. Please reopen if you believe this is an issue with the vscode-docker extension.
