### ISSUE TITLE
browse to azure container registry

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-docker#151]
love that we can now browse to docker hub to see an image. can we add a right click to browse to the portal to the ACR to see our images there too?

![image](https://user-images.githubusercontent.com/1202528/31794603-daf3cf50-b4f0-11e7-9311-256288725e47.png)

cc @chrisdias

**Comment by chrisdias** [comment]
@johnpapa ya, it feels like something is missing here. but, at the same time, there really isn't much in portal below the "repositories" blade. What is the manifest used for?

**Comment by johnpapa** [comment]
The 2 things I look at in the portal for the ACR are the images with it tag, and the webhook. The webhook is nice to see because it shows a timestamp when it receives a new image/tag and a green/red light when it gets pushed.
