### ISSUE TITLE
There is no inputting validation for the "port input box"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1510]
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression:** Not a Regression

**Steps to reproduce:**

1. Open a folder/workspace in VS Code.
2. F1->Docker: Add Docker Files to Workspace...->Node.js->Yes/No.
3. Input the port with "3;;'['']?\><" in the "port input box".

**Expect:**
There is an error like below.
![image](https://user-images.githubusercontent.com/45614674/71440494-3a6b8c00-2738-11ea-9af0-38c80f89127d.png)

**Actual:**
There is no inputting validation for the "port input box".
![image](https://user-images.githubusercontent.com/45614674/71440524-566f2d80-2738-11ea-9e6f-e9ced0ecea5c.png)

**Comment by allanwright** [comment]
I've created #1518 to fix this issue.
