### ISSUE TITLE
Hard to read the output logs after executing "Run as task in Azure" action for "taskmulti.yaml"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1511]
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression:** Not a Regression

**Steps to reproduce:**

1. Download the [acr-build-helloworld-node](https://github.com/Azure-Samples/acr-build-helloworld-node) project.
2. Open this project in VS Code.
3. Right click the "taskmulti.yaml" file and execute "Run as task in Azure".
4. Check the output logs.

**Expect:**
Easy to read the output logs.

**Actual:**
Hard to read the output logs after executing "Run as task in Azure" action.
![image](https://user-images.githubusercontent.com/45614674/71441089-f62dbb00-273a-11ea-9445-8c1ac09d7373.png)

**Comment by philliphoff** [comment]
The output window (channel) isn't a proper terminal, so terminal command escape codes (e.g. colorizing) from Docker build output are not natively supported.  We could decide to strip those out (as we do for the Containers Tools Window logs tab in VS).
