### ISSUE TITLE
Docker not running - client is older 1.22 - how do I install 1.24?

### ISSUE THREAD

**Issue by rajabhathor** [microsoft/vscode-docker#1514]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - hcsshim::CreateComputeSystem d12c7d89873e30716d05ba3c06298a98cb4e21fb4373ac59c867ed08beba3333: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"d12c7d89873e30716d05ba3c06298a98cb4e21fb4373ac59c867ed08beba3333","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\d12c7d89873e30716d05ba3c06298a98cb4e21fb4373ac59c867ed08beba3333","Layers":[{"ID":"63c32ea1-871c-513c-8559-8e43c042fa35","Path":"C:\\ProgramData\\Docker\\windowsfilter\\885285cca6717207fd892f9da3b190ceb5eb7c5d8a10c33eb7bec6c2ac4f01b6"},{"ID":"11670f69-9b4c-5640-a746-5b74b0285214","Path":"C:\\ProgramData\\Docker\\windowsfilter\\46c084673f790919a319bea0759081bee0828a0b972eedb3505b26e2fd534467"},{"ID":"6aaf8adb-25c2-5cd1-9b61-15b799065b42","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fae5d0779cf23304d260b75076f8b8746da95441b166a47dd1bf42c4fcc66741"}],"HostName":"d12c7d89873e","HvPartition":true,"EndpointList":["FB4358E1-669F-4400-87B8-86C3308A0BDA"],"HvRuntime":{"ImagePath":"C:\\...

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

**Comment by ravipal** [comment]
Looks like virtualization is not enabled on BIOS. Please check https://stackoverflow.com/questions/57431890/error-response-from-daemon-hcsshimcreatecomputesystem-the-virtual-machine-co
