### ISSUE TITLE
vscode-docker

### ISSUE THREAD

**Issue by mu-offline** [microsoft/vscode-docker#1521]
Repro steps:

1.
2.

Action: vscode-docker.networks.prune
Error type: Error
Error Message: Failed to connect. Is Docker installed and running? Error: connect ENOENT //./pipe/docker_engine

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.wrapDockerodeENOENT extension.bundle.js:1:389351
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by philliphoff** [comment]
@mu-offline Is this issue repeatable?  If so, can you provide repro steps?  Can you verify that Docker is up and running on the machine (e.g. `docker version` returns results for the Docker server host)?
