### ISSUE TITLE
Container names to attach are incorrect; names combined from adjacent containers

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-docker#1523]
This docker extension _and_ the Remote-Container extension both show and try to use incorrect container names. Naturally, everything fails. They fails to attach, display wrong attribute values, etc.

I have a screenshot of the actual running containers with incorrect names that I can share directly with Microsoft. Any verified Microsoft employee can give me the process to securely and privately send that screenshot. Meanwhile...

### Local Client

* Windows 10 x64
* VSCode
  Version: 1.41.1 (system setup)
  Commit: 26076a4de974ead31f97692a0d32f90d735645c0
  Date: 2019-12-18T14:58:56.166Z
  Electron: 6.1.5
  Chrome: 76.0.3809.146
  Node.js: 12.4.0
  V8: 7.6.303.31-electron.0
  OS: Windows_NT x64 10.0.18363
* VSCode Extension -> Docker
* VSCode Extension -> Remote Development
* WSL Ubuntu 18.04.3 LTS
* SSH tunnel to remote server using https://code.visualstudio.com/docs/remote/troubleshooting#_using-an-ssh-tunnel-to-connect-to-a-remote-docker-host

### Remote Server

* Ubuntu 18.04.3 LTS x86_64
* Docker Server 19.03.5
* 8 running containers. Ensure that several of those containers have images with namespaces, names, and tags.

## Repro

1. Setup client and server as above.
2. Start the client ssh tunnel to the remote server as in the instructions above
3. Change the VSCode setting `"docker.host"` to match that ssh tunnel
4. Click on the docker whale icon in the left nav

### Result 1

In the container window are 8 containers. They have names which are incorrect. Some recombine names of containers to be namespaces of other containers.

### Continued Repro

1. Click on the green box in the bottom left of VSCode
2. Choose Remote-Container: attach to running container

### Result 2

The list of containers is incorrect. It also has incorrect names in bold. Namespaces and names are recombined.

### Continued Repro

1. Choose one of the containers with a namespace/name:tag
2. Right click and choose Attach Visual Studio Code

### Result 3

A new window opens. A modal error dialog box appears `Cannot attach to the container with name/id *redacted*/*redacted*, it no longer exists.

In the background, the terminal window has...
```
[1 ms] Start: Resolving remote
[11 ms] Setting up container *redacted*/*redacted*
```

Please note, all of those redacted container names are wrong. In this case, it took the name of the container listed directly above this container as the namespace and then appended the correct container name on that.

## Notes

Below I've recreate a subset of the errant containers with sanitized names.

| Full Image Tag |
| ----------------|
| mybiz-docker/myservice-crypto:latest |
| mybiz-docker/myservice-web:latest |

#### Expected Names

| Container Name |
|--------------------|
| myservice-crypto |
| myservice-web |

#### Actual Errant Names

In nothing have I indicated a container names should have a prefix then slash. These errant names do not appear in the command line tools. They only appear in the VSCode UI and its functionality that fails.

| Container Name |
|--------------------|
| myservice-crypto |
| myservice-crypto/myservice-web |

**Comment by philliphoff** [comment]
@diablodale Does this seem to occur only when using a remote Docker host and/or when images used by those containers have full namespaces/repositories/tags?  How were the containers (with errant names in the explorer) started (e.g. via the command line or via VS Code, given explicit names or implicitly named by Docker, etc.)?

If you're comfortable with sending screenshots via email, feel free to send them to `phillip.hoff@microsoft.com`.

**Comment by diablodale** [comment]
I believe I've isolated the cause of the errant behavior and the specific fix that is needed.

#### Isolation

Docker extension's containers pane, is configured with `Label=FullTag`, `Description=ContainerName,Status`. Screenshots reflect that. I can identify a few more things now:

* The FullTag is correct in the container list.
* The ContainerName is mangled.
* Therefore functionality that relies on container name fails.
* Right-click Attach Visual Studio Code uses Container Name and fails.
* Right-click Attach Shell uses the _Container ID_. 🤪 It fails in the SSHtunnel, but works in the remote extensions scenario (see below).

The screenshots I provide by email show mangled container names, some with with slashes in them. Docker container names **can not** have slashes in them.  Here are the core Docker code name rules...

https://github.com/moby/moby/blob/master/daemon/names/names.go

In my email to you, I have included some additional information:

* Output of `docker container ls` named `docker-container-ls.txt`
* Output of `curl --unix-socket /var/run/docker.sock http:/v1.24/containers/json` named `api-containers.json`

In the former `container ls`, the names are correct.  
In the latter `api json`, I found matching mangled names.

#### Cause

I believe the errant behavior surfaces when Docker containers are using the Docker v1 `link` feature. https://docs.docker.com/network/links/#connect-with-the-linking-system
Many service providers (e.g. AWS ECS) only support the v1 linking for intra-container connectivity. When this v1 linking is used, the Docker API `http:/v1.24/containers/json` returns the following; where `linksourcename1` and `linksourcename2` are the names of the containers that linked to this container named `mycontainername`

```json
{
    "Id": "1234567890123456789012345678901234567890123456789012345678901234",
    "Names": [
        "/linksourcename1/mycontainername",
        "/mycontainername",
        "/linksourcename2/mycontainername"
    ],
    "Image": "myimagename:latest",
```

I suspect the VSCode Docker extension is blindly taking the container name as Names[0]. This is not safe. As you can see in the JSON I sent by email (and in the redacted example above), the content of the Names array and its order is not guaranteed to only contain a single name or that name to be the first in the array. Instead, it can contain multiple names in various orders. However, from my scenarios of testing, there is always one (and only one) entry in the Names array that is the canonical name...and that name has no `/` in it other than the beginning slash.

#### Fix

Use the same logic as the core Docker CLI itself. In that code is written, "Additional names for the container (related to the legacy `--link` feature) are omitted".

https://github.com/docker/cli/blob/f7f4a19328f139347a33aa5e728a06927a0036b7/cli/command/formatter/container.go#L124

I believe the VSCode Docker extension needs to find the single canonical container name
from the Names array using a similar method. That should fix the container names in the
UI and other VSCode functionality that also relies on such.

Separate yet related, it may be beneficial for right-click-Attach-Shell and right-click-Attach-VSCode to both use the same method...to use the container ID.

# Answers to questions from your post above

I have sent the original screenshot to your email shortly after this post. It will be
named`github-vscodedocker-1523-sshtunnel.png`. You will also receive some more screenshot that I reference below.

## Occur only when using a remote Docker host?

My answer is two-fold because of scenarios.

#### Local VSCode + Local Docker server

_My answer is I don't know._ I have no computer that is setup for both local VSCode UI and local Docker server. In the past, I had run Docker for Windows but its limitations with permissions, volumes, kernel features, etc. made it untenable. Therefore, all my work is with a Windows 10 computer for VSCode/VSStudio and most everything else in WSL (python, php, lint, etc.) and a remote Ubuntu host for Docker.

In the past, I briefly tried remote and SSH connectivity to Docker but ran into tech roadblocks or my lack of knowledge. Recently, improvements have been made to VSCode's SSH/Docker story so I tried again. However, this appears to still be limited and that issue is being explored separately in https://github.com/microsoft/vscode-remote-release/issues/2079. It was only on my retry of SSH/Docker, the above separate bug, and then falling back to an SSH tunnel...did I discover these mangled names.

#### Local VSCode + remote Docker server

_My answer is no and yes._ My original issue above describes how it doesn't work as expected in that specific remote connectivity method. However, there are other methods for remote connectivity.

Local Windows machine with VSCode. Extensions for Docker and Remote-Containers force installed to the workspace with settings...

```json
"remote.extensionKind": {
    "ms-azuretools.vscode-docker": "workspace",
    "ms-vscode-remote.remote-containers": "workspace",
},
"docker.host": "",
```

With that setup, then _Click on the docker whale icon in the left nav_, I see in the "Containers" windows a list of containers. This list of containers **has the same errant names** as the scenario using the SSH tunnel. At the same time, it is slightly more successful with functionality. _Right-click on a container, choose attach, and I successfully get a shell prompt inside the selected container._ However, right-clicking and choosing Attach Visual Studio code fails with the elsewhere discussed issue `Error: connect ENOENT //./pipe/docker_engine`. I will send a screenshot of this list of containers named `github-vscodedocker-1523-workspace-extensions.png`. Please note that in this configuration, it is not possible for me to click on the lower-left green icon and choose attach. Only the 'Remote-SSH' actions are available. :-(

## Occur only when images used by those containers have full namespaces/repositories/tags?

No. The errant behavior is not triggered by the images names. Instead, triggered by container
names. This can be seen by the different between containers with names having no
slashes...versus...containers having names with slashes. (Please note, slashes in container names are
not allowed as discussed at the top of this post).

Slashes in names result in model error dialog and no errors printed in log. In this scenario, the container was never reached.

```
[0 ms] Start: Resolving remote
[11 ms] Setting up container mycontainer1/mycontainer2
```

No slashes in name results in further progress, then a model error dialog AND errors printed in log. In this scenario the container was reached, but some later error occurred.

```
[0 ms] Start: Resolving remote
[10 ms] Setting up container mycontainer3
[62 ms] Start: Check Docker is running
[113 ms] Start: Inspecting container
[190 ms] Start: Run in container: uname -m
[195 ms] Start: Run in container: cat /etc/passwd
[199 ms] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
        at doWrite (_stream_writable.js:413:19)
        at writeOrBuffer (_stream_writable.js:401:5)
        at Socket.Writable.write (_stream_writable.js:301:11)
        at c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:95871
        at c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96235
        at async Object.exec (c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96256)
        at async c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134613
        at async Object.t.getContainerProperties (c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134571)
        at async Object.t.resolve (c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:384869)
        at async c:\Users\dale\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:1028173
```

## How were the containers (with errant names in the explorer) started (e.g. via the command line or via VS Code, given explicit names or implicitly named by Docker, etc.)?

I use `docker-compose`. My docker-compose defines several services, each having `build`, `container_name`, `image`, `network_mode`, `links`, etc. In the data I sent to you by email, you are seeing the containers from two separate docker-compose projects running on the same remote Docker host.

**Comment by philliphoff** [comment]
@diablodale This is fantastic analysis and feedback, thanks so much!  While I've only been able to reproduce your issue once through some combination of container ups/downs that no longer replicates, I *can* readily generate multi-named containers that would theoretically cause that problem if the order of the names differed.  So I'm fairly confident we can fix that.

Looking through the source, the Docker extension is generally doing the right thing with regard to using the container ID rather than the container name (e.g. the "Attach Shell" command), so it's mostly a visual artifact.  On the other hand, the Remote Containers extension (which layers the  "Attach Visual Studio Code" command atop our tree view) appears to be using the first container name in the array more readily throughout their codebase.  I'll file an issue in that repo and link it to this one.

**Comment by dbreshears** [comment]
Fixed on the Docker extension side but remaining work for this is in the VS code open issue above.

**Comment by diablodale** [comment]
Matthew, please delete via PRV0020176
