### ISSUE TITLE
Feature to find dependent child images

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/vscode-docker#1529]
While I understand the error, it'd be great if there was a feature that helped me determine what child images were causing this error:

![image](https://user-images.githubusercontent.com/21112697/71937117-3ee46b80-3160-11ea-898c-f823cd6a080f.png)

**Comment by philliphoff** [comment]
That's a good idea.  I could see scanning for and adding a list to the error message itself, though that could get unwieldy.  Perhaps an option to group images by base image?

**Comment by bwateratmsft** [comment]
@MRayermannMSFT @philliphoff I've been working on something I think you're gonna like. Here's a couple screenshots that I think convey the concept:

![image](https://user-images.githubusercontent.com/36966225/77098501-dd0a7280-69e8-11ea-91ad-c8110eb4e56c.png)

![image](https://user-images.githubusercontent.com/36966225/77098392-ab91a700-69e8-11ea-9164-cbb610ef8c6a.png)
