### ISSUE TITLE
Options to filter images/containers

### ISSUE THREAD

**Issue by whitecolor** [microsoft/vscode-docker#153]
It would be useful for a particular project to see only certain images/containers (referring to the project), so options with filtering pattern for names would be nice.

The same refers to registries and images there.

**Comment by chrisdias** [comment]
Help me understand... we could do something like have a configuration that lets you specify a regex for images to be shown in the explorer and the command palette.  would this work for you?

**Comment by whitecolor** [comment]
Yes I'm talking about this. Filter for images/containers/registries.

**Comment by lanzkron** [comment]
I second this, adding a filter (or search) for containers when many containers/images are present will be a big plus
![image](https://user-images.githubusercontent.com/11015162/41899708-d4e12ffe-7935-11e8-939c-a5113a0722f0.png)

**Comment by whitecolor** [comment]
Any progress on that feature?

**Comment by StephenWeatherford** [comment]
@whitecolor Would #430 solve the problem for you?  Or do you need that plus filtering?  Thx.

**Comment by BigMorty** [comment]
VSCode now supports highlighting and filtering of tree views. Just click in the treeview you want to filter and start typing; here is an example of what I see when I type 'docker' in the Images treeview.
![image](https://user-images.githubusercontent.com/947510/65357221-4977f680-dbab-11e9-9625-f76ae6207bc9.png)

If I hover over the word 'docker' in the top right corner and then click on the highlight/filter toggle I can switch to filter mode to only show the nodes that match my search.
![image](https://user-images.githubusercontent.com/947510/65357349-aecbe780-dbab-11e9-8e5f-ca38855b689a.png)

I think this should give you the flexibility you need to search/filter Images, Containers, and any other treeview!
