### ISSUE TITLE
Support debugging of multi-targeted .NET Core projects 

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1532]
Currently the debugging process uses the `<TargetFramework>` property in the project file to infer which base image to use when scaffolding a Docker file.  However, projects that target multiple frameworks use the `<TargetFrameworks>` property instead.  We should support both properties:

 - If `<TargetFramework>` exists, use that value.
 - Otherwise, if `<TargetFrameworks>` exists and specifies a single .NET Core version, use that value.  
 - Otherwise, if more than one .NET Core version is specified, prompt the user to choose which of those to scaffold.
 - Otherwise, if no .NET Core versions are specified, return an error similar to "this project doesn't target .NET Core".

> Note that [.NET Core ignores `<TargetFrameworks>` if `<TargetFramework>` is specified](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj).

**Comment by karolz-ms** [comment]
👍

**Comment by bwateratmsft** [comment]
Is there a CLI way to determine frameworks? That would be ideal, more so than inspecting project files.

**Comment by bwateratmsft** [comment]
I believe this is fixed by #1866
