### ISSUE TITLE
docker ssh : docker_host does not support ipv6 ssh addresses 

### ISSUE THREAD

**Issue by afausttanasescu** [microsoft/vscode-docker#1533]
Docker host environment variable should support ipv6 as well.

    VSCode Version: insiders build 1.42.0-insider
    Local OS Version: win10
    Remote OS Version: win10
    Remote Extension/Connection Type: ssh+docker

Steps to Reproduce:

    Configure environment variable to ssh://ec2-user@fda1:aadd:ef9b:7777::5.5.5.5:22
    In the docker extension, under networks : Docker env variable should be something like ....

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by afausttanasescu** [comment]
I should add that docker -H doesn't seem to accept the ipv6 address either. In the extension code, I only see a regex for something that starts with ssh://, so it should work.

**Comment by hholst80** [comment]
I confirm that this does not work. I can only see this after 3 minutes of connecting.

![image](https://user-images.githubusercontent.com/6200749/74086451-2b8c2f00-4a83-11ea-9f72-6cbc14a6dda7.png)

**Comment by hholst80** [comment]
Reproduce this by setting `DOCKER_HOST=ssh://user@remote`. 

This works from CLI:

![image](https://user-images.githubusercontent.com/6200749/74086477-71e18e00-4a83-11ea-8975-9344c2b33a92.png)

**Comment by hholst80** [comment]
> 
> 
> I should add that docker -H doesn't seem to accept the ipv6 address either. In the extension code, I only see a regex for something that starts with ssh://, so it should work.

DOCKER_HOST=ssh://... uses docker.sock so that is not related to this issue.

**Comment by bwateratmsft** [comment]
This could be an issue with the way `dockerode` consumes the DOCKER_HOST variable. Need to investigate.

**Comment by bwateratmsft** [comment]
@karolz-ms do you think this might work with the `docker context` changes?

**Comment by karolz-ms** [comment]
@bwateratmsft I think there is a good chance that https://github.com/microsoft/vscode-docker/pull/1790 will fix this. Will try to verify next week.

**Comment by karolz-ms** [comment]
Sorry for long delay, it was only last week that I was finally able to figure out how to create and SSH over IPv6 into an Azure VM, so I could test the scenario. Unfortunately it does not work, at leas on a Mac. Investigating...

**Comment by karolz-ms** [comment]
OK, it actually works, one just needs to specify the username part of the SSH URL, even if the default works just fine with Docker CLI. So 

```shell
docker context create mycontextname --docker "host=ssh://username@machine-name"
```

IPv6 address and/or machine name that represents the AAAA DNS record should work as `machine-name` part. The machine name has to be DNS-resolvable name (the Docker extension, or more precisely, the underlying docker-modem/ssh2 library combo, [does not look into `~/.ssh/config` for host aliases yet](https://github.com/apocas/docker-modem/issues/113).

**Comment by karolz-ms** [comment]
(VSCode Docker extension version 1.1.0 or later)

**Comment by hholst80** [comment]
> OK, it actually works, one just needs to specify the username part of the SSH URL, even if the default works just fine with Docker CLI. So
> 
> ```shell
> docker context create mycontextname --docker "host=ssh://username@machine-name"
> ```
> 
> IPv6 address and/or machine name that represents the AAAA DNS record should work as `machine-name` part. The machine name has to be DNS-resolvable name (the Docker extension, or more precisely, the underlying docker-modem/ssh2 library combo, [does not look into `~/.ssh/config` for host aliases yet](https://github.com/apocas/docker-modem/issues/113).

It's actually much more than aliases. There can be various proxy commands etc, that are setup in a ssh connection. Do not use `~/.ssh/config` unless you support it natively.
