### ISSUE TITLE
Link to Azure App Service website is minimized and unclickable

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1537]
The notification produced from successfully deploying an Azure Container Registry image to Azure App Service is not clickable. Links in the VSCode terminal are clickable so this behavior is not desirable. 

I have two suggestions to improve the experience of going from deploying a new web app to seeing it in action: 
1. Expanding the notification the make the link fully viewable
2. Creating the ability to click the link and open App in default browser

Steps to reproduce:

1. In Docker Extension, under the "Registries" pane, right click an image
2. Select "Deploy to Azure App Service"
3. Walk through steps and successfully deploy the New Web App
4. Afterwards, in the bottom right corner of VS Code, you will see notification resembling 5
5. ![image](https://user-images.githubusercontent.com/20650058/72031731-2187ce00-3242-11ea-8fc4-84b95aeee7de.png)
6. You must then click the arrow to expand the link to see the notification resembling 7
7. ![image](https://user-images.githubusercontent.com/20650058/72031746-29477280-3242-11ea-85b1-dc038e18bd31.png)
8. In either view of the "Successfully created" message, the link to the App Service Instance is not clickable

**Comment by allanwright** [comment]
The second suggestion 'Creating the ability to click the link and open App in default browser' has been implemented in #1580.

**Comment by bwateratmsft** [comment]
I think that when buttons are present it will automatically be expanded as well, so it might cover part 1 too.

**Comment by bwateratmsft** [comment]
Yes, indeed it does:
![image](https://user-images.githubusercontent.com/36966225/76533755-ef1b6c80-644e-11ea-9c15-05cd05f09b07.png)

I'll close this issue as fixed.
