### ISSUE TITLE
Prompting user to set Default Registry

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1540]
After **initially** installing the Docker extension, building an image, and selecting the push command, docker push gives no prompt to set a default registry or to push to a specific registry (#1539). Instead, the user is forced to properly tag the image  (someusername.azurecr.io/someexpressapp:latest) or else  the container is pushed to docker.io by default. As a user aiming to push the image to Azure Container Registry, it was frustrating being met with this error multiple times. 

![image](https://user-images.githubusercontent.com/20650058/72059091-2bcbbb80-3286-11ea-9638-514ff32c1398.png)

If default registry has not been set, there should be prompting to either select a default or select a specific registry each time they push. The latter feature is discussed in #1539.

**Comment by karolz-ms** [comment]
@ucheNkadiCode like I mentioned in https://github.com/microsoft/vscode-docker/issues/1539, a tag is always required to push to any repository other than those hosted on docker.io. The concept of 'default registry' is something that does not currently exist in Docker in the sense that you are describing here.

My understanding is you are looking for a way  to make working with registries easier. Let's brainstorm.
