### ISSUE TITLE
[Python] Make docker compose optional when adding Docker files to the workspace

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1548]
Similar to Node.js and .Net Core, we should prompt to optionally include "docker compose" files when adding Docker files to the workspace, which would provide a single container experience along with the existing docker compose support when scaffolding Docker support in Python

**Comment by haniamr** [comment]
@dbreshears Is this only about making "Docker compose files" optional? If so, we can close it since it was addressed in 1.0.
