### ISSUE TITLE
myfirsttest

### ISSUE THREAD

**Issue by lqixy** [microsoft/vscode-docker#1549]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:423244
extension.bundle.js:1:305167extension.bundle.js:1:305167
Object.t.captureCancelStep extension.bundle.js:157:373232
S extension.bundle.js:1:299147
t.configure extension.bundle.js:1:305148
extension.bundle.js:324:343471extension.bundle.js:324:343471
```

</details>

**Comment by philliphoff** [comment]
@lqixy Did you have an individual folder open when attempting to add the Docker files, or did you have a workspace open?  Could you add repro steps?
