### ISSUE TITLE
Docker Hub Login error

### ISSUE THREAD

**Issue by phibonacci85** [microsoft/vscode-docker#1550]
Repro steps:

1. Login to Docker Hub Registry

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

**Comment by philliphoff** [comment]
Are you using KDE and its `kwallet` for credentials management?  If so, you'll still need to install `gnome-keyring` as `kwallet` does not support the common API for Linux's `libsecret` library, used as the foundation for credentials management in VS Code (and our extension) on that platform.
