### ISSUE TITLE
Unable to pull repo at from Docker hub

### ISSUE THREAD

**Issue by MustafaJamal** [microsoft/vscode-docker#1551]
Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username edevtech --password-stdin
Error response from daemon: Get https://registry-1.docker.io/v2/: unknown method

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:200:13
ChildProcess.EventEmitter.emit domain.js:471:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by philliphoff** [comment]
@MustafaJamal Is this a private registry hosted on DockerHub? Are you able to login to and pull the repository on the command line?  From the error, it looks like the registry and/or credentials may not have been set correctly. Can you provide (general) repro steps?

**Comment by MustafaJamal** [comment]
Hi @philliphoff thanks for your response. Yes it's private registry hosted on DockerHub. No I cannot login using command line. see below:

```
C:\WINDOWS\system32>docker login
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get https://registry-1.docker.io/v2/: unknown method
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (edevtech): edevtech
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: unknown method
```

Please let me know if further information is required. Thanks

**Comment by philliphoff** [comment]
@MustafaJamal Given that you get the same error on the command line as in VS Code, it's unlikely to be an issue specific to the VS Code Docker extension, and a more fundamental issue authenticating against that private registry.  (I'll tentatively mark this issue as "external" for now.)

Are you behind a proxy, by chance (which is where some of these types of errors appear to lead)?  No other suggestions come to mind at the moment.  You may have better luck looking at Docker [registry] support forums.
