### ISSUE TITLE
Remote SSH Containers not found

### ISSUE THREAD

**Issue by brombomb** [microsoft/vscode-docker#1552]
I am using VSCode to connect to a Linux VM, that is managed by my IT department.  This means that my user is an account managed by AD.  However, all my other docker panes work, and my docker commands can be run sudoless.

![image](https://user-images.githubusercontent.com/1136944/72165525-e510bb00-3384-11ea-93ea-38b3c13a98f8.png)
Highlighted in yellow is the empty containers pane, my `/etc/group` with docker and myself and a sample of sudoless `docker ps`. 

Expected behavior:
A list of all the containers shown by docker ps in the containers pane, which is what I see running the same project locally.

**Comment by philliphoff** [comment]
@brombomb Can you provide a little more information on how you've configured the Remote SSH connection in VS Code?  For example, are you running the `vscode-docker` extension in "workspace" or "UI" mode?  Are you running Docker locally and, if so, at that time were there running containers?  (I'm trying to discern whether the extension was reflecting the remote machine incorrectly or, perhaps, the local one instead.)

**Comment by brombomb** [comment]
@philliphoff I pulled the same code base in my local instance and opened up my remote instance next to it and what do you know it's showing local docker containers.

I tried to install Docker remotely but it's not available to, either in the UI or using the command palette.

![image](https://user-images.githubusercontent.com/1136944/72263940-dece4900-35e7-11ea-86d5-4e93394e8f3b.png)

I've enabled the remote connections for docker but it still doesn't seem to be picking it up

**Comment by philliphoff** [comment]
@brombomb Can you show the Extensions tab [with the extensions categorized by local/remote](https://code.visualstudio.com/docs/remote/ssh#_managing-extensions)?  Does the Docker extension not show up in either list (either as installed or as available to be installed)?  As far as I know, there shouldn't be any [reason why it can't be installed remotely](https://code.visualstudio.com/docs/remote/ssh#_docker-extension-limitations).

**Comment by brombomb** [comment]
![image](https://user-images.githubusercontent.com/1136944/72290321-e8bd6f80-361a-11ea-9a64-1e7dcfb30805.png)

Nothing is loaded in Remote.  A few of the extensions below have a green "Install in SSH:dev" button.

**Comment by philliphoff** [comment]
@brombomb Do you happen to have any `"remote.extensionKind"` settings set (that could prevent extensions from running remotely)?  v0.9.0 of the Docker extension should default to running remotely unless specifically configured to run locally.  If not, you could try [forcing the docker extension to be installed remotely on any SSH connection](https://code.visualstudio.com/docs/remote/ssh#_always-installed-extensions).
