### ISSUE TITLE
error remove image docker vscode

### ISSUE THREAD

**Issue by lucasnpinheiro** [microsoft/vscode-docker#1553]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 404
Error Message: (HTTP code 404) no such image - No such image: sha256:2b07004d22be1f5a724f7cc347e5706cb1f9888e16961ac5d18c83f3ef485523 

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@lucasnpinheiro Is this error repeatable?  If so, can you provide repro steps?  Perhaps an earlier action was taken to remove the image and was still in progress when another action was taken, which then couldn't find the image (as the previous action had just removed it).
