### ISSUE TITLE
remove failed

### ISSUE THREAD

**Issue by nf-chace** [microsoft/vscode-docker#1555]
Repro steps:

1.
2.

Action: vscode-docker.images.remove
Error type: 409
Error Message: (HTTP code 409) conflict - conflict: unable to delete 549b9b86cb8d (cannot be forced) - image has dependent child images 

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546
extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
This is a case where the image cannot be removed as there are other images (perhaps used by running containers) that depend on this one.  That said, it's a problem that occurs regularly enough that we have an issue for dealing with that scenario more gracefully, #1529.
