### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by daklinux** [microsoft/vscode-docker#1559]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.1
Language: fr

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:423182
extension.bundle.js:1:305105
Object.t.captureCancelStep extension.bundle.js:157:373232
S extension.bundle.js:1:299085
t.configure extension.bundle.js:1:305086
extension.bundle.js:324:343471
```

</details>

**Comment by philliphoff** [comment]
@daklinux Did you have a folder open when invoking the command?  Or did you have a workspace open?  (There were a couple known issues with the latter case, that should be fixed in the next release.) . Can you provide repro steps?
