### ISSUE TITLE
Call Stack

### ISSUE THREAD

**Issue by jggj-c** [microsoft/vscode-docker#1560]
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.buildImage
Error type: Error
Error Message: No matching resources found.

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:1:699812
o extension.bundle.js:1:694323
propagateAslWrapper async-listener/index.js:502:23
async-listener/glue.js:188:31
async-listener/index.js:539:70
async-listener/glue.js:188:31
```

</details>

**Comment by philliphoff** [comment]
@jggj-c Is this error repeatable?  If so, can you provide repro steps?
