### ISSUE TITLE
Cannot properly copy text from Successfully Created Web App notification

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1566]
After Deploying a container to Azure App Service, other than the popup being minimized and unclickable (#1537), the user can highlight, but not actually copy selected text within the notification. This behavior creates another small obstacle to viewing my web app in action.

When I highlight my webapp link, right click, select Copy Text ->

Expected output: https://uchendjangodemo.azurewebsites.net

Given output: Successfully created web app "uchenDjangoDemo": https://uchendjangodemo.azurewebsites.net

Steps to reproduce:
1. In Docker Extension, under the "Registries" pane, right click an image
2. Select "Deploy to Azure App Service"
3. Walk through steps and successfully deploy the New Web App
4. Maximize Notification to view the full url
5. Highlight website link
6. Right click and select "Copy text"
![image](https://user-images.githubusercontent.com/20650058/72653893-fbe57d80-3941-11ea-82b1-e60e1cd708d5.png)
7. Paste link in browser

**Comment by philliphoff** [comment]
This isn't specific to the Docker extension; the "Copy text" command on *any* notification in VS Code will copy the entire text (rather than just the selected portion).

**Comment by ucheNkadiCode** [comment]
Okay thank you, I'll drop the issue in VS Code
