### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Mihael112** [microsoft/vscode-docker#1567]
Repro steps:

1.
2.

Action: vscode-docker.images.inspect
Error type: Error
Error Message: Failed to show text document azureextensionuiReadonly:/8a8d032af0663d5b8917449c0c2fa9681b15f682339225c838ad0cf659686fd0/latest.json, should show in editor #vs.editor.ICodeEditor:3,$model13

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extensionHostProcess.js:641:878extensionHostProcess.js:641:878
```

</details>

**Comment by philliphoff** [comment]
@Mihael112 Is this issue repeatable?  If so, can you provide repro steps?
