### ISSUE TITLE
Unable to acquire the .NET Core debugger  on mac

### ISSUE THREAD

**Issue by louieyu** [microsoft/vscode-docker#1568]
Repro steps:

1.
2.

Action: docker-launch
Error type: 1
Error Message: Process exited with code 1

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:530610
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by philliphoff** [comment]
@louieyu Is this issue repeatable?  If so, can you provide repro steps?
