### ISSUE TITLE
Failed building a docker container with a dockerfile

### ISSUE THREAD

**Issue by AravindJaimon** [microsoft/vscode-docker#1573]
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: 5
Error Message: Task to execute is undefined

Version: 0.9.0
OS: linux
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

**Comment by philliphoff** [comment]
@AravindJaimon Is this issue repeatable?  If so, can you add repro steps?  Did you have a normal folder open in VS Code, or did you have an actual workspace open?

**Comment by AravindJaimon** [comment]
Yeah it was a workspace
