### ISSUE TITLE
Display 404 in browser after following the baseImage link from Dockerfile

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1574]
**OS**: All
**Build Version**: [20200122.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13983&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Open a new empty file called "Dockerfile "--> Press "Ctrl + Space" --> See the FROM snippet.
2. Press "Ctrl + Click" to follow the link of "baseImage".
![image](https://user-images.githubusercontent.com/34729092/72871212-3164df00-3d25-11ea-94d4-a72967417383.png)

**Expect:**
Display a matching webpage.

**Actual:**
Display 404 in browser.
![image](https://user-images.githubusercontent.com/34729092/72871257-48a3cc80-3d25-11ea-812b-b6aee87e494f.png)

**Comment by philliphoff** [comment]
@v-dantch Can you show a screenshot of the IntelliSense dialog with the link to the documentation?  On my machine, the "Online documentation" link goes to [`https://docs.docker.com/engine/reference/builder/#from`](https://docs.docker.com/engine/reference/builder/#from)
