### ISSUE TITLE
.Net Core ENTRYPOINT is not using AssemblyName for .dll reference

### ISSUE THREAD

**Issue by jmreiche** [microsoft/vscode-docker#1583]
When using the otherwise brilliant "Add Docker Files To Workspace.." feature it seems like the code to generate the ENTRYPOINT at the end of the Dockerfile uses the name of the Project instead of the AssemblyName from inside the .csproj file. 

This means that if you have another AssemblyName specified inside the .csproj then the reference for ENTRYPOINT will point to an incorrect .dll name.

This will give a cryptic error message when trying to run the Docker image:

It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

In my case the line generated was:

ENTRYPOINT ["dotnet", "Physio.Server.WebApi.dll"]

But should have been:

ENTRYPOINT ["dotnet", "Habitlab.Physio.Server.WebApi.dll"]

As that is what I have specified in AssemblyName and RooNameSpace for that matter.

**Comment by philliphoff** [comment]
@jmreiche You're right, the scaffolding logic makes the assumption that the assembly name matches the project file name when generating the Dockerfile.  Interestingly, we don't make that assumption when debugging that same project (where we extract the evaluated `TargetOutputFilename` from the project file).  (Note that the scaffolding logic was written *long* before the debugging logic and likely just didn't take that scenario into account.) Given that, it should be straightforward to fix.

**Comment by jmreiche** [comment]
Super. Thanks a lot for the rapid feedback! I could not imagine it being a difficult fix either. Just annoying for the few people who encounter it, as the error received from Docker is cryptic.
