### ISSUE TITLE
Feature request: Allow change of docker-machine from the sidebar

### ISSUE THREAD

**Issue by rogermartensson** [microsoft/vscode-docker#1584]
You can add a docker-machine using the settings or through environment variables.

But it would be neat to have a way to display all my docker-machines that are visible through "docker-machine ls".
This could be visible in the sidebar and then be able to change docker-machine by clicking. It then populates the settings by using "docker-machine env <chosen machine>".

**Comment by philliphoff** [comment]
@rogermartensson How many Docker machines are you typically managing and switching between?  Are these machines local to your client computer or are they separate VMs?

**Comment by rogermartensson** [comment]
I do have machine local on the client and some on our server evironment. 

It could be just one or it could be "many". I don't see the number as being that important. What I see is that it would help setting up the settings easier from inside vscode. 

Currently it's either getting the variables from docker-machine and run vscode from the shell or copying it to the settings which could be a bit cumbersome for some.

**Comment by rogermartensson** [comment]
It seems that docker-machine is on it's way out and being deprecated. So maybe it's no idea to implement my request.

**Comment by bwateratmsft** [comment]
I think the spiritual replacement for `docker-machine` is `docker context`, which we in part respect today. I'm not sure if it automatically changes when `docker context` is changed, but it might be valuable to allow changing that from somewhere in the extension UI.
