### ISSUE TITLE
driver failed programming external connectivity on endpoint SonarQube

### ISSUE THREAD

**Issue by tarcisiobruni** [microsoft/vscode-docker#1588]
Repro steps:

1.
2.

Action: vscode-docker.containers.start
Error type: 500
Error Message: (HTTP code 500) server error - driver failed programming external connectivity on endpoint SonarQube (0a8ed915417c7ca16ae9d9cf616bd1b534f3638dedb200f67d8e3360193457a3): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500 

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:440546extension.bundle.js:324:440546
extension.bundle.js:324:440508extension.bundle.js:324:440508
g.buildPayload extension.bundle.js:324:440518
IncomingMessage.<anonymous> extension.bundle.js:324:439984
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by dbreshears** [comment]
@tarcisiobruni .  can you start the container from the command line with docker run?
