### ISSUE TITLE
ID conflicts between Docker related extensions

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1589]
There is another [Docker-related extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) that shares several IDs with our extension. This can result in VS Code populating the wrong views with the wrong content, as well as overlapping contextual commands.

We should investigate changing our IDs to have extension-specific prefixes to avoid that conflict (and hopefully future ones).  The difficulty will be determining whether it has back-compat issues for extensions that are deliberately layered atop our own.

**Comment by dbreshears** [comment]
Duplicate of #1432
