### ISSUE TITLE
 Require secondary authentication on MFA enabled account

### ISSUE THREAD

**Issue by FHDumont** [microsoft/vscode-docker#1591]
I have MFA enabled to login in Docker but the extension ask only for username and password, it doesn't ask for the MFA code and I've received the message: Require secondary authentication on MFA enabled account.

Does this occur consistently? Yes
Repro steps:
1. Registries > Connect Registry...
2. Docker Hub > fill docker id > fill password

Action: vscode-docker.registries.dockerHub.openInBrowser
Error type: 401
Error Message: Require secondary authentication on MFA enabled account

Version: 0.10.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.41.1

Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:317:58453
B.callback extension.bundle.js:317:57296
B.e.callback.t.callback [as _callback] extension.bundle.js:317:56344
B.t._callback.t.callback.t.callback extension.bundle.js:194:5618
B.emit events.js:200:13
B.<anonymous> extension.bundle.js:194:18478
B.emit events.js:200:13
IncomingMessage.<anonymous> extension.bundle.js:194:17310
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by philliphoff** [comment]
@FHDumont Have you tried creating and entering a [Docker personal access token](https://docs.docker.com/docker-hub/access-tokens/) in lieu of the password?

**Comment by philliphoff** [comment]
@FHDumont It appears that using a personal access token is not quite enough; the Docker Hub web API doesn't appear to [support PAT for all of the methods](https://github.com/docker/hub-feedback/issues/1947) we use within the extension.  For example, we can list the namespaces and repositories associated with a user account, but not list the tags of those repositories.  That limitation may just be a part of 2FA still being in beta.

**Comment by philliphoff** [comment]
@FHDumont This is resolved now on the Docker Hub API side, so using a personal access token as your password when connecting to Docker Hub in the extension should now work.  Let us know if it does not.
