### ISSUE TITLE
Telemetry: Process exited with code XX

### ISSUE THREAD

**Issue by haniamr** [microsoft/vscode-docker#1592]
Look into improving the error message in the debugging telemetry events (docker-run-execute, docker-launch and docker-build-execute) by adding the stdout from the running process if possible?

Currently, it shows as: "Process exited with code 7".

**Comment by haniamr** [comment]
@bwateratmsft would that be resolved by this PR https://github.com/microsoft/vscode-docker/pull/1745?

**Comment by bwateratmsft** [comment]
I think it would for cases *other* than tasks. Let's chat today about how best to handle this...
