### ISSUE TITLE
Add Functionality to the image Push command

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1595]
**Problem**: I believe that the push command could do a better job of handling untagged images. Currently, when a user tries to push an untagged image with no Default Registry set, the image is pushed to docker.io/library which is likely to be denied. Even if a default registry is set, the user is prompted to tag their image before pushing it and then must click Tag. Image shown below

![image](https://user-images.githubusercontent.com/20650058/73489390-5a0d5a00-435f-11ea-81fe-8da89f2e5b14.png)

**My proposal**: If an image isn't already tagged with a strict registry path, I believe clicking the push command should trigger the command pallete in which the user can select a container registry from any of the registries they are connected to and have the option of creating an ACR (if they are connected to Azure) if they don't have one already. This will help the user tag their image properly before pushing it to their registry of choice.

**Comment by bwateratmsft** [comment]
We should also handle login when possible/practical.
