### ISSUE TITLE
dbus error

### ISSUE THREAD

**Issue by togoodtobetrue** [microsoft/vscode-docker#1597]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: org.freedesktop.DBus.Error.ServiceUnknown

Version: 0.10.0
OS: linux
OS Release: 5.3.0-28-generic
Product: Visual Studio Code - OSS
Product Version: 1.41.1
Language: en

**Comment by philliphoff** [comment]
@togoodtobetrue Is this problem repeatable? If so, can you provide repro steps?  Can you successfully login to this registry using the `docker login ...` command line?

**Comment by togoodtobetrue** [comment]
Sorry I'm new to git I'm still learning how to use this sorry for the late reply I will report it if it happens again.

**Comment by bwateratmsft** [comment]
@togoodtobetrue sounds good, I'll close this issue for now but please let us know if the problem occurs again!
