### ISSUE TITLE
Support for commenting shortcut

### ISSUE THREAD

**Issue by Vloz** [Microsoft/vscode-docker#16]
Need the `Ctrl+shift+A` support to multiline-comment _Dockerfile_ and _docker-compose.yml_ files (using the **#** character).

**Comment by rcjsuen** [comment]
@Vloz Using the 'Toggle Line Comment' command with the (default?) `Ctrl+/` keybinding seems to work in both Dockerfiles and docker-compose.yml files.

**Comment by chrisdias** [comment]
@rcjsuen is correct... this should work with Toggle Line Comment.  If not, please do open a new issue with repro steps. Thanks!!
