### ISSUE TITLE
Fails to connect if `docker.host` uses ssh with a custom port

### ISSUE THREAD

**Issue by rodogir** [microsoft/vscode-docker#1604]
The extension fails to connect to my remote host which listens on the `4202` port for ssh connections.

It is not a problem of the host machine as I am able to successfully connect to it using the cli:

```powershell
$env:DOCKER_HOST = "ssh://rodogir@my-domain.dev:4202"
docker info
# prints information of the host machine
```

This problem can probably be reproduced using the following steps:

1. set up an ssh server that binds to port `4202` on the docker host machine
2. on a different machine in vscode, configure `docker.host` to `ssh://user@your-domain.dev:4202`
3. restart/reload vs code
4. open the docker extension. It should fail to produce any output. I just see the loading animation at the top.

From what I understand, this could be a problem with `dockerode` not supporting custom ports for ssh. 

What would I need to do, to debug the problem?

**Comment by philliphoff** [comment]
@rodogir Are you able to connect (in VS Code) to a remote host listening on the standard SSH port (`22`)?  (That would help identify whether it's just a general SSH configuration issue or just related to the ports.) Have you followed the [SSH configuration guide in the extension wiki](https://github.com/microsoft/vscode-docker/wiki/SSH#directly-via-ssh)?

The `dockerode` library itself relies on a `ssh` library that does have some limitations compared to, for example, just setting `DOCKER_HOST` environment variable or the `-H` argument on the `docker` command line.  I can't tell, however, whether a fixed SSH port number is one of those limitations.

**Comment by rodogir** [comment]
@philliphoff Thanks for the quick reply. I will give it a try later today and let you know it it works with the default SSH port.

**Comment by rodogir** [comment]
@philliphoff Following the wiki did the trick! Thank you, I wasn't aware of it as I followed the documentation for VS Code [Developing inside a container on a remote Docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).
