### ISSUE TITLE
Usage with Visual Studio Online

### ISSUE THREAD

**Issue by abymsft** [microsoft/vscode-docker#1606]
I'm trying to build and run a container, based on an alpine image, prinitng helloworld, using this plugin on Visual Studio Online. 

Has anyone used built images and used this plugin with Visual Studio Online ?

I keep getting popup with a link to install dockers whenever I try a docker command from the cmd palette? I understand the current plugin expects docker for windows/mac to be installed. But isn't there a way to make this work with VS online ?

Any guidance would help. Thanks.

**Comment by philliphoff** [comment]
@abymsft The Docker extension isn't fully supported by the Visual Studio Online VM environment, namely, as Docker isn't installed by default and (from my quick testing) cannot be run within the VM that underpins the environment.  I suppose, if you had a Docker daemon running elsewhere that was accessible to the Internet, you might try to configure the extension to use that instead.

What it means to run the extension within Visual Studio Online is an interesting question; it's one we know we'll need to answer at some point but we have no immediate plans to do so (that I'm aware of).

**Comment by bwateratmsft** [comment]
I'm going to close this; it seems like Codespaces is the logical replacement and it does include Docker. Most features work. See #2180.
