### ISSUE TITLE
Use proper templating engine for scaffolded files

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1617]
The text definition/manipulation we use to scaffold files (e.g. Docker files) is...not pretty.  It'd be nice to move to a proper templating engine to get the inline strings into separate files and stop cluttering up the actual scaffolding logic.

I don't have a huge preference on any particular template engine; we're using [Handlebars](https://handlebarsjs.com/) in another extension and it seems to work reasonably well.

@bwateratmsft edit: From @conradwt in #2026:
> **Goal**
I would like to be able to add additional languages as well as customize existing languages for my development workflows without having to submit a PR to update the extension.
> **Currently**
The supported languages are fixed and new customizations need to be redeployed within a future version of this extension.
> **Possible Solution**
Extend the extension to allow users to add their own templates to a designated directory that would get picked up and displayed within VS Code when one uses Docker Add command.

**Comment by bwateratmsft** [comment]
I'd almost consider this feature work, not just engineering...

**Comment by philliphoff** [comment]
@bwateratmsft Almost added the feature label but, technically, it wouldn't have any visibility to users, which is the sort of thing I tend to put in the "engineering" bucket.

**Comment by bwateratmsft** [comment]
Can't it have visibility though? I can see users wanting ways to offer their own templates, through settings or otherwise.

**Comment by philliphoff** [comment]
Well, yes, adding user-customization the Docker-related files would be a new feature.  Having "real" templates on disk rather than embedded inline is likely to make that easier, but that I wouldn't consider that the initial goal.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension 1.6.0.
