### ISSUE TITLE
add access to gitlab.com registry

### ISSUE THREAD

**Issue by scgm11** [microsoft/vscode-docker#162]
registry.gitlab.com

**Comment by phil-harmoniq** [comment]
I would also like to access my GitLab Docker registry from VS Code.

**Comment by pmjohann** [comment]
It would be great to include **self-hosted** instances of GitLab also.

**Comment by rfults** [comment]
+1 for adding self-hosted GitLab registries as well as Red Hat and RH Satellite registries.

**Comment by beleidy** [comment]
+1 this would be super useful!

**Comment by raimaj** [comment]
+1 for adding self-hosted GitLab registries!

**Comment by Zetanova** [comment]
+1

**Comment by Bananas-Are-Yellow** [comment]
+1

**Comment by walkafwalka** [comment]
I believe this is a matter of developing an oauth authentication method, not necessarily add support for the GitLab registry in particular. Though there is not an issue open, they are aware they do not support oauth authentication.

**Comment by carsoni** [comment]
+1 for self-hosted registries

**Comment by EricJizbaMSFT** [comment]
Hi all - we're tracking generic support for registries that require OAuth in https://github.com/microsoft/vscode-docker/issues/162

Added your votes to that issue and closing this as a duplicate
