### ISSUE TITLE
teste docker

### ISSUE THREAD

**Issue by wesleyrossetti** [microsoft/vscode-docker#1628]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.10.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:427875
c extension.bundle.js:317:80786
extension.bundle.js:31:190971extension.bundle.js:31:190971
Object.t.scaffold extension.bundle.js:317:81418
t.configure extension.bundle.js:1:246732
extension.bundle.js:317:348968extension.bundle.js:317:348968
```

</details>

**Comment by bwateratmsft** [comment]
Same as #1559. @wesleyrossetti , can you open a folder or workspace before trying to generate Docker files?
