### ISSUE TITLE
TesteDocker

### ISSUE THREAD

**Issue by antoniopereirasilva** [microsoft/vscode-docker#1629]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.10.0
OS: linux
OS Release: 5.3.0-28-generic
Product: Visual Studio Code - Insiders
Product Version: 1.43.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:427813
c extension.bundle.js:317:80786
extension.bundle.js:31:190971
Object.t.scaffold extension.bundle.js:317:81418
t.configure extension.bundle.js:1:246670
extension.bundle.js:317:348968
```

</details>

**Comment by bwateratmsft** [comment]
Same as #1559. @antoniopereirasilva , can you open a workspace folder in VSCode before running the `Configure Workspace...` command?
