### ISSUE TITLE
Unable to debug ASP.NET Core app from within WSL 2

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1636]
To repro one needs a Windows 10 machine with WSL 2 and Docker with WSL 2 engine (Edge) installed and enabled. Use Ubuntu 18.04 LTS as the WSL 2 distro. I am using Insider Preview of Windows 10 build 19564.1005, VS Code 1.42.1, and Docker Desktop 2.2.1.0 (42746) edge channel.

Repro steps:
1. Use Remote-WSL extension to open a session into WSL 2 environment
2. Follow ASP.NET quickstart https://code.visualstudio.com/docs/containers/quickstart-aspnet-core and try debugging

Expected: debugging should work
Actual: seemingly infinite loop of the same dialog popping up that asks "How do you want to open this?" and offers a choice of browsers. Clicking "Always use this app" checkbox does not seem to help. See screenshot below:

![image](https://user-images.githubusercontent.com/15271049/74858368-0eb0f080-52fa-11ea-88b4-c2ba2fee0b57.png)

Removing `dockerServerReadyAction` does not seem to help

**Comment by bwateratmsft** [comment]
Strange...this might be a VSCode issue or maybe even a Windows issue; we use the official `vscode.env.openExternal` API to actually launch the browser.

**Comment by bwateratmsft** [comment]
What happens if you choose a default browser from outside of the context of VSCode?

**Comment by karolz-ms** [comment]
The default browser is set to Microsoft Edge in OS settings, if this is what you are asking about

**Comment by bwateratmsft** [comment]
What happens if you open a "Learn More" link (or something like that) from within VSCode?

**Comment by karolz-ms** [comment]
Good question, Brandon. Seems like a Win10 Preview issue. I can repro the same behavior by opening File Explorer and typing `https://www.microsoft.com` into the quick access bar 😞
