### ISSUE TITLE
Use wizard-like flow for Dockerfile scaffolding

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#1642]
In a discussion about the Python scaffolding flow, an idea was brought up related to making the series of user prompts bi-directional, in case the user needed to correct a prompt or make a different choice.  Currently the scaffolding flow is a series of independent prompts; the user can't go "back" without cancelling the entire commands.

VS Code does have a more complex form of the input/quick-pick APIs that allow for things such as back buttons, etc., which would allow us to move to a more user-friendly wizard-like flow.  In fact, the `vscode-azureextensionui` library we use actually has a wrapper around that API that we could use as well.

**Comment by bwateratmsft** [comment]
Related to #1617.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension 1.6.0.
