### ISSUE TITLE
Missing name of repository in GitLab Docker Registry

### ISSUE THREAD

**Issue by danielgospodinow** [microsoft/vscode-docker#1643]
I'm using the GitLab registry and I noticed that the name of the current repository from a given registry is missing.

And this behavior can be observed only for GitLab, DockerHub works like a charm.

I'll provide some images so that it's more clear.

Observation:
![Image of observed defect](https://i.imgur.com/rF0RkNS.png)

Current state in GitLab:
![Current state in GitLab](https://i.imgur.com/Y82uIcR.png)

The same thing, but in DockerHub:
![Current state in GitLab](https://i.imgur.com/jtgrMbq.png)

**Comment by bwateratmsft** [comment]
Definitely looks like a bug, we'll look into it. Thanks for reporting it @danielgospodinow!

**Comment by bwateratmsft** [comment]
@BigMorty I think we should take this for 0.11.0 as it essentially makes GitLab unusable in our Registries view.

**Comment by bwateratmsft** [comment]
So Docker Hub does not allow pushes to the namespace itself. i.e. I can push `bwateratmsft/webworkspace:latest` but not `bwateratmsft:latest`.

**Comment by danielgospodinow** [comment]
It's good that you managed to reproduce the issue and I'm happy that you even figured out what's going on exactly! :smile: Good luck, guys!

**Comment by bwateratmsft** [comment]
Thank you! We were trying to decide exactly what text should go in that spot. Technically, it's another repository altogether. Some of our ideas include:

1. Give the full name, e.g. in my example it would be `bwateratmsft/vscode-extension-testing`. This would be the exact same text as the parent node.
2. Show <root>
3. Show <default>

Do you have any preference or is there different text that makes sense to show there?

**Comment by danielgospodinow** [comment]
I think option 1 seems quite reasonable. In fact, that's the behavior that I expect as a user. :smile:

I got familiar with the source code and I'll also do my best to help resolving this issue. I would love to contribute to this project. :smile:

**Comment by bwateratmsft** [comment]
I looked further into the code, and it seems like this is a quirk of GitLab itself. Their API returns a `name` value that is blank. Still, I think the fix is essentially the same--when constructing the repository node, we can just give a default name like the project name if there's nothing from the request.

**Comment by danielgospodinow** [comment]
Yes, I absolutely agree! :smile: This fix should do the trick.
I managed to apply the fix locally.
Can I try and make a pull request for this, even though it's just a single line of code? :smile:

**Comment by bwateratmsft** [comment]
Yes, please do! We welcome user contributions. :smile:

**Comment by danielgospodinow** [comment]
I've made a pull request. :smile: I'll try to continue contributing as much as I can! :v: And thank you for the wonderful discussion, It was a wonderful opportunity for me!
