### ISSUE TITLE
Intellisense should stop "helping" inside comments

### ISSUE THREAD

**Issue by ssteinerx** [Microsoft/vscode-docker#165]
This only seems to happen with the Docker support.

Inside a comment in a Dockerfile, it's almost impossible to just type 'cause "helpful" suggestions pop up constantly.

`#` at the beginning of a line starts a comment and everything else after that should be left alone for regular typing.

**Comment by rcjsuen** [comment]
Hi @ssteinerx, thank you for the bug report.

Could you attach a screenshot that shows what you are seeing? I want to ensure that the behavior I am seeing matches what you are encountering.

**Comment by ssteinerx** [comment]
Pretty simple...
`#` to start a comment
`<space>` brings up a list of Docker commands and makes typing virtually impossible

![vscode-helpful-docker](https://user-images.githubusercontent.com/43063/32671360-1b905314-c615-11e7-8d40-8a8a4b85e120.gif)

**Comment by ssteinerx** [comment]
@rcjsuen Thanks!  How would one get that updated into their VSCode installation?  At the moment, mine says there are no updates available.  Does it require also pushing an update to this extension?  Thanks again!

**Comment by rcjsuen** [comment]
@ssteinerx The bug is in one of the dependencies of the the vscode-docker extension. It would require both an update to the dependency and an update to the extension (to increment the version of the dependency).

**Comment by rcjsuen** [comment]
I think we can close this since #173 has been merged?

**Comment by ssteinerx** [comment]
@rcjsuen Is this supposed to be in most recent code insiders release?

**Comment by rcjsuen** [comment]
@ssteinerx The fix should be in the 0.0.23 release of this extension that was published on January 6th.
