### ISSUE TITLE
Create wiki or doc info about command customization

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1653]
Related to #1596. We need documentation about what is possible and how to do it.

**Comment by karolz-ms** [comment]
I suggest we add this to our [Reference topic in the docs](https://code.visualstudio.com/docs/containers/reference)

**Comment by bwateratmsft** [comment]
Works for me :smile:
I changed the title slightly to reflect that.

**Comment by bwateratmsft** [comment]
The docs have been merged.

**Comment by bwateratmsft** [comment]
https://code.visualstudio.com/docs/containers/reference#_command-customization
