### ISSUE TITLE
Error running docker build in VS Code

### ISSUE THREAD

**Issue by nosregor** [microsoft/vscode-docker#1657]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: 5
Error Message: Task to execute is undefined

Version: 0.10.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

**Comment by bwateratmsft** [comment]
Looks like a dupe of #1647
