### ISSUE TITLE
Pop up an error "s.filter is not a function" when running "Docker Images: Remove..."

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1660]
**OS:** Windows
**Build Version**: [20200225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15184&view=artifacts&type=publishedArtifacts)
**Regression:** Previous Release (0.10.0)

**Repro Steps:**
1. F1 --> Type and select "Docker Images: Remove...".
2. Check the result.

**Expect:**
Succeed to remove the images by this command.

**Actual:**
Pop up an error "s.filter is not a function".
![image](https://user-images.githubusercontent.com/34729092/75333249-a488d600-583a-11ea-921e-aec1aa8077f7.png)

**Comment by bwateratmsft** [comment]
Probably a bug from the multi-select work, I'll take a look.
