### ISSUE TITLE
Display a stopped container after composing up a .NET Core Console app

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1661]
**OS:** Windows, Mac
**Build Version**: [20200225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15184&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression (0.10.0)

**Repro Steps:**
1. Create a .NET Core Console app by "dotnet new console --name testconsole".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
![image](https://user-images.githubusercontent.com/34729092/75342895-26cdc600-584c-11ea-8f5e-3d8d63df776a.png)
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> .NET Core Console --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".

**Expect:**
Display a running container after composing up.

**Actual:**
Display a running container during the process, but it becomes stopped when finishing composing up.
![image](https://user-images.githubusercontent.com/34729092/75343474-6ba62c80-584d-11ea-8e1a-9ca741b57e56.png)

**More Info:**
Fail to start the stopped container from the context menu.

**Comment by bwateratmsft** [comment]
My first guess at a glance is that the entrypoint failed because the binaries weren't built. If you don't build manually before step 4, this would occur.

**Comment by ravipal** [comment]
Since the compose up does the full build of dockerfile, the app should be built. The issue here is the default Program.cs generated by 'dotnet new console'  simply prints the "Hello World!" and exits. So the container is stopped. Please update the Program.cs to have a continuous loop so the program doesn't exit.

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
