### ISSUE TITLE
Fail to debug with "Docker: .NET Core Attach (Preview)" configuration for ASP .NET Core web apps in Windows Containers mode

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1662]
**OS:** Windows
**Build Version**: [20200225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15184&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression

**Repro Steps:**
1. Switch to Windows Containers mode.
2. Create a ASP .NET Core web app by "dotnet new mvc".
3. Open this project in VS Code --> Prompt to add the required assets --> Yes.
4. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP .NET Core --> Windows--> Include optional Docker Compose files --> Enter ports: the default 80,443.
5. Right click the docker-compose.yml --> Select "Compose Up".
6. Open launch.json file --> Add "Docker: .NET Core Attach (Preview)" configuration.
7. Debug with "Docker: .NET Core Attach (Preview)" configuration.

**Expect:**
Succeed to debug.

**Actual:**
Fail to debug with error "Process exited with code 126".
![image](https://user-images.githubusercontent.com/34729092/75346055-b8d8cd00-5852-11ea-896e-22daf5df2f7f.png)

**Comment by ravipal** [comment]
Attach to windows container is not supported. But we should improve the experience by validating the target container OS and provide appropriate error message to user.

**Comment by bwateratmsft** [comment]
Is it not possible, period, or could users set up the debugger themselves and make it work?

**Comment by ravipal** [comment]
We don't support windows out of the box. But user can still debug with the below steps.
1. Run 'Add Docker Files to Workspace' to create the docker-compose.debug.yml
2. Add the "Docker .NET Core Attach (Preview)" to launch.json
3. Download (https://aka.ms/getvsdbgps1) and install the vsdbg on the host machine at ~/.vsdbg
4 Update the launch config "Docker .NET Core Attach (Preview)" by adding debuggerPath as shown below.
        "netCore": {
            "debuggerPath": "C:\\remote_debugger\\win7-x64\\latest\\vsdbg"
        }
5. Now "Docker .NET Core Attach (Preview)" will attach the windows container.

**Comment by dbreshears** [comment]
Let's emit a better error message and the above steps should be added to the troubleshooting page.  Confirm and/or add telemetry for Windows attach vs. Linux

**Comment by ravipal** [comment]
Since now we copy the debugger from host machine to container. We could support the debugger for windows.
