### ISSUE TITLE
Allow user to select all containers by writing '*' asterisk in the command palette

### ISSUE THREAD

**Issue by ovirta** [microsoft/vscode-docker#1663]
Small feature request to docker command palette. Please allow user to select all containers just by typing '*' in the command palette and press enter. Usually I am only using keyboard to execute tasks and it is not a big effort to click the select all check box but I always think this could be improved (a little).

![image](https://user-images.githubusercontent.com/4389140/75346012-73de8600-58a6-11ea-8ffd-425e05050040.png)

Just minor ux improvement to a great tool set.

**Comment by bwateratmsft** [comment]
I think this would probably need to be changed in VSCode itself since we use their APIs for these picks. I'll investigate and move this item if needed.

**Comment by bwateratmsft** [comment]
I wasn't able to find anything in the API that would enable us to do this. The closest things were flags to allow matching on description / detail, but that would not apply here. I'll create an issue in the VSCode repo to suggest this.

**Comment by bwateratmsft** [comment]
@ovirta before I file that, I did find something that would help. Upon opening the quick-pick, if you do `Shift` + `Tab`, it moves focus back to the "select all" checkbox adjacent the search box. Then, hitting `Space` checks that "select all" checkbox, thus checking all items in view--no mouse needed. Does that work for you? Or would you still like to see the `*` search text work?

**Comment by ovirta** [comment]
Should have thought that myself. That’ll work nicely. Thanks a lot for swift reply. Closing.
