### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration after customize it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1664]
**OS:** Windows, Mac
**Build Version:** [20200225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15184&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression (0.10.0)

**Repro Steps:**
1. Create a .NET Core Console app by "dotnet new mvc --name mvctest".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core  --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.
7. Stop debugging and add below to the launch config
_"containerName": "mvctest"
"netCore": {
	"debuggerPath": "/remote_debugger"
	  }_
8. Run the "Docker .NET Core Attach (Preview)" config again.

**Expect:**
Run the configuration successfully without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/75346186-01908600-5853-11ea-8ea4-7b7d304e1a96.png)

**Comment by ravipal** [comment]
The customization is using the wrong container name. the container name created by the compose up should be something like testmvc_testmvc_1. User 'docker ps' to get the container name.
