### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration on Mac

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1665]
**OS:** Mac
**Build Version:** [20200225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15184&view=artifacts&type=publishedArtifacts)
**.NET Core SDK:** 2.1.607
**Regression:** Not a Regression (0.10.0)

**Repro Steps:**
1. Create a .NET Core Console app by "dotnet new mvc --name mvctest".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.

**Expect:**
Run the configuration successfully without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/75346967-9fd11b80-5854-11ea-83b6-c5e8413da166.png)

**More Info:**
This issue does not reproduce on Windows with .NET Core 3.1 SDK installed.

**Comment by philliphoff** [comment]
@v-ruizh I'm not able to reproduce this on Mac using .NET Core 2.1 (2.1.16 in the container) nor with the latest .NET Core 3.1.  Does this reproduce every time for you?

**Comment by v-ruizh** [comment]
This issue does not reproduce on the new build 20200227.1 with Linux image Ubuntu/Debian. But it also reproduces with Linux image 2.1-alpine. The error is "Process exited with code 127".

**Comment by ravipal** [comment]
I tried both 3.1-alpine and 2.1-alpine from windows host machine and it works for me.
@v-ruizh can you please share the logs from output window? The latest build should log the output of the debugger installation on container. Also did you create the mvc project targeting 2.1 framework using  `-f netcoreapp2.1` ?

**Comment by philliphoff** [comment]
I'm seeing the "127" error on Mac.  I'm continuing to look into it.

**Comment by philliphoff** [comment]
I think it's a Mac vs Windows shell quoting issue.  This doesn't work (what we try to run):

```bash
> docker exec -it 1b87e1d384ebef79f2937b1b17521e81419ad32b975f4ca0a7c259e3b05f8db4 /bin/sh -c "ID=default; if [ -e /etc/os-release ]; then . /etc/os-release; fi; echo $ID; if [ $ID == alpine ]; then apk --no-cache add curl && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger ; else apt-get update && apt-get install unzip && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger; fi"

sh: alpine: unknown operand
/bin/sh: apt-get: not found
```

Using single quotes works:

```bash
> docker exec -it 1b87e1d384ebef79f2937b1b17521e81419ad32b975f4ca0a7c259e3b05f8db4 /bin/sh -c 'ID=default; if [ -e /etc/os-release ]; then . /etc/os-release; fi; echo $ID; if [ $ID == alpine ]; then apk --no-cache add curl && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger ; else apt-get update && apt-get install unzip && curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /remote_debugger; fi'
alpine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
OK: 15 MiB in 29 packages
Info: Last installed version of vsdbg is '16.3.10904.1'
Info: VsDbg is up-to-date
Info: Using vsdbg version '16.3.10904.1'
Using arguments
    Version                    : 'latest'
    Location                   : '/remote_debugger'
    SkipDownloads              : 'true'
    LaunchVsDbgAfter           : 'false'
    RemoveExistingOnUpgrade    : 'false'
Info: Skipping downloads  
```
