### ISSUE TITLE
Support for Moby 

### ISSUE THREAD

**Issue by ebmarquez** [microsoft/vscode-docker#1667]
Issue Type: <b>Bug</b>

When Moby's docker service is installed an running as demaon on Windows the extension does not reconize the service.

Extension version: 0.10.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (47.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
What error message(s) do you see?

**Comment by ebmarquez** [comment]
I think I figured out what’s going on.  Moby requires elevated privileges to interact with ☹.  In a normal user session this is what you see, but with Admin you see below.
[cid:image001.png@01D5EC95.4AE0B3E0]


VsCode running as Administrator.
[cid:image003.png@01D5EC95.4AE0B3E0]

**Comment by bwateratmsft** [comment]
When Docker is set up on Windows, it creates a "docker-users" group and adds the current user by default; but if you're signed in as any other user you would need to elevate. Can you try adding your current user to that group and see if elevation is no longer required?

**Comment by ebmarquez** [comment]
I can already see my domain account in that user group already.  Just to make sure, I attempted to add it again and I was denied.
[cid:image003.png@01D5EC99.93A23410]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwateratmsft** [comment]
The screenshots aren't coming through via email, when possible can you post them directly on GitHub?

**Comment by ebmarquez** [comment]
![image](https://user-images.githubusercontent.com/15785107/75388911-923e8480-589a-11ea-9fb6-faf7d72b4ecb.png)

**Comment by bwateratmsft** [comment]
Thanks @ebmarquez, I'll close this one as external for now. Please let us know if you find any more issues when running with Moby!
