### ISSUE TITLE
False positive error message `Invalid containerPort: ...`

### ISSUE THREAD

**Issue by 31z4** [Microsoft/vscode-docker#167]
Having the following Dockerfile
```dockerfile
FROM openjdk:8-jre-alpine
ENV ZOO_PORT=2181
EXPOSE $ZOO_PORT
```
I get an error message `Invalid containerPort: $ZOO_PORT` which is incorrect, since environment variables [are supported](https://docs.docker.com/engine/reference/builder/#environment-replacement) by the following list of instructions in the `Dockerfile`:
* `ADD`
* `COPY`
* `ENV`
* `EXPOSE`
* `FROM`
* `LABEL`
* `STOPSIGNAL`
* `USER`
* `VOLUME`
* `WORKDIR`
as well as:
* `ONBUILD` (when combined with one of the supported instructions above)

**Comment by rcjsuen** [comment]
Thank you very much for your bug report, @31z4. I have opened rcjsuen/dockerfile-language-server-nodejs#192 to track this problem in the language server.

**Comment by rcjsuen** [comment]
This can be closed since #173 has been merged.

**Comment by chemidy** [comment]
With the last version 0.0.23, it's not resolved.

**[dockerfile-lsp] Invalid containerPort:**

```dockerfile
FROM scratch
ARG GRPC_PORT
EXPOSE $ZOO_PORT
```

**Comment by rcjsuen** [comment]
Hi @chemidy, if you use the Dockerfile that was [originally posted](https://github.com/Microsoft/vscode-docker/issues/167#issue-273119689), you shouldn't get any errors.

In the Dockerfile you have provided, you defined an argument named `GRPC_PORT` but your `EXPOSE` instruction is using `$ZOO_PORT`. Did you make a copy/paste error? Is this the Dockerfile you intended to  write in your comment?
```Dockerfile
FROM scratch
ARG GRPC_PORT
EXPOSE $GRPC_PORT
```

**Comment by rcjsuen** [comment]
In any case, I have opened rcjsuen/dockerfile-language-server-nodejs#199 for the problem that you have found regarding build arguments with no default values.

Thank you for the bug report!

**Comment by chemidy** [comment]
Hi @rcjsuen , yes it was a copy/paste error. Thks for the bug report

**Comment by rcjsuen** [comment]
@chemidy Please update to 0.0.24 for a fix to the problem you reported. Thanks again for the bug report!
