### ISSUE TITLE
Fail to run the attach launch configuration since the debuggerPath is provided

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1672]
**OS:** Windows
**Build Version:** [20200227.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15381&view=results)

**Repro Steps:**
1. Create an ASP.NET Core web app --> Open this project in VS Code --> Add the required assets.
2. Add docker files to workspace with  --> ASP.NET Core--> Linux --> Include optional Docker Compose files --> Compose up the docker-compose.yml.
3. Add "Docker .NET Core Attach (Preview)" configuration into launch.json.
4. Run the above configuration with the new running container-->Install vsdbg on the container --> Stop the debug.
5. Add the debuggerPath in launch.json like:
"netCore": {
            "debuggerPath": "/remote_debugger"
}
6. Run the attach launch config again.

**Expect:**
Succeed to debug and it won't ask user permission to install the debugger.

**Actual:**
Pop up an error "Permission deny".
![image](https://user-images.githubusercontent.com/34729092/75417598-4b767c00-58e6-11ea-8134-ed52482cc4f6.png)

**Comment by ravipal** [comment]
My bad, the test case description was wrong. The path should point to the script file. Please use "debuggerPath": "/remote_debugger/vsdbg"

**Comment by v-dantch** [comment]
Thanks for your share. Verified again with "remote_debugger/vsdbg" for ASP.NET Core and .NET Core Console web apps and they both work well.
