### ISSUE TITLE
Pop up an error when installing Docker Extension v1.0.0 with VS Code v1.40.2

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1678]
**OS**: Windows
**Build Version**: [20200227.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15381&view=results)

**Repro Steps:**
1. Install VS Code with 1.40.2 according to the version in extension/package.json file.
![image](https://user-images.githubusercontent.com/34729092/75522306-8cda5a80-59be-11ea-82fb-c1b8a40bf1fd.png)
2. Install the Docker Extension v1.0.0.

**Expect:**
Succeed to install the Docker Extension and there is no any error.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/75522399-bf845300-59be-11ea-9375-49904ca70226.png)

**Comment by bwateratmsft** [comment]
Thanks @v-dantch, we'll need to update the package.json to enforce 1.41 or up.
