### ISSUE TITLE
There is no docker-compose.debug.yml file in python project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1679]
**OS:** Windows, Mac, Linux
**Build Version:** [20200227.10](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15438&view=results)

**Repro Steps:**
1. Open a python project(General/Django/Flask) in VS Code.
2. F1->Docker: Add Docker Files to Workspace->include docker compose files.
3. Check if there is docker-compose.debug.yml file. 

**Expect:**
There is a docker-compose.debug.yml file in python project.

**Actual:**
There is no docker-compose.debug.yml file in python project.

**Comment by bwateratmsft** [comment]
@haniamr This is intentional right?

**Comment by bwateratmsft** [comment]
According to Lubo / @BigMorty this is indeed by design.
