### ISSUE TITLE
Unable to delete image from remote registry (private registry)

### ISSUE THREAD

**Issue by mvirnoche** [microsoft/vscode-docker#1680]
Does this occur consistently? 
Repro steps:

1. Open Docker side bar icon
2. Navigate to registries --> connected registries
3. Locate image --> right click --> delete

Action: vscode-docker.registries.deleteImage
Error type: UNSUPPORTED
Error Message: The operation is unsupported.

Version: 0.10.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:317:58453
B.callback extension.bundle.js:317:57296
B.e.callback.t.callback [as _callback] extension.bundle.js:317:56344
B.t._callback.t.callback.t.callback [as callback] extension.bundle.js:194:5618
B.emit events.js:200:13
B.<anonymous> extension.bundle.js:194:18478
B.emit events.js:200:13
IncomingMessage.<anonymous> extension.bundle.js:194:17310
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by bwateratmsft** [comment]
@mvirnoche Are you sure your registry allows deleting images?
