### ISSUE TITLE
Deploy from ACR to App Service should use MSI with ACRPull role

### ISSUE THREAD

**Issue by berndverst** [microsoft/vscode-docker#1685]
Many users attempt to enable the *admin mode* on ACR. This is bad for security. At the same time, newly created ACR instances don't provide App Service with the necessary access for deployment, even via the VS Docker extension. Many users wrongly believe enabled admin mode is the only way out.

This is a feature request specific to the deployment from ACR to App Service / Web App which will allow making the deployment seamless.
1. Retrieve Web App Managed Identity or Create (Assign) a new one of it does not exist
1. Assign ACR Pull role to the system managed identity for the ACR in question.

References:
- [App Service Managed Service Identity](https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-app-service)
- [How to use Managed Service Identities with ACR](https://docs.microsoft.com/azure/container-registry/container-registry-authentication-managed-identity#example-2-access-with-a-system-assigned-identity)

**Comment by bwateratmsft** [comment]
@berndverst I am not able to figure out how to get the app service to actually log in using the MSI.

I added you as an owner on the resource group ("bwater"). Here's what I did:

1. Created ACR and put some images on it.
1. Created web app, pointed at that registry. I cannot even create the web app without enabling admin mode, so I enabled it temporarily:
![image](https://user-images.githubusercontent.com/36966225/82934721-f1736a00-9f59-11ea-8e15-b2348dccdabe.png)
1. Web app gets created. Turn admin mode back off on the ACR.
1. In the Config tab, it has `DOCKER_SERVER_REGISTRY_URL`, `DOCKER_SERVER_REGISTRY_USERNAME`, `DOCKER_SERVER_REGISTRY_PASSWORD`, and others. I removed username and password.
1. Turn on system-assigned identity on the web app.
1. Assign AcrPull role to said identity.
1. Open web app in browser, get error.
1. Diagnostic logs say auth failure to registry.

It seems to me that Web App services aren't actually capable of authenticating to ACR with MSI.

**Comment by berndverst** [comment]
@bwateratmsft  I agree with you. From the docs it sounds like it should be possible, but it isn't actually. Digging around internally it seems that the App Service Team does not actually support system assigned identity for accessing ACR.

I don't recall whether the App Service MSI page mentions this limitation, but if not that might be worthwhile calling out.

**Comment by bwateratmsft** [comment]
I'll file a doc bug about that, and link this to that one.

**Comment by bwateratmsft** [comment]
Opened https://github.com/MicrosoftDocs/azure-docs/issues/55802.

**Comment by bwateratmsft** [comment]
We should reactivate this and do the necessary work if support is added in the future.

**Comment by BigMorty** [comment]
The AppSvc team has added the ability to use managed service identities to pull from ACR.

**Comment by bwateratmsft** [comment]
@BigMorty where did you hear that MSI is enabled for App Service accessing ACR? I still get this in the Portal:

![image](https://user-images.githubusercontent.com/36966225/111533255-f4378980-873c-11eb-97aa-010c4ed94cd1.png)
