### ISSUE TITLE
docker-build custom task: The terminal process failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by shaktisinghr** [microsoft/vscode-docker#1686]
Steps to reproduce:
Open folder (containing Dockerfile) from VS Code. This is a custom image, doesn't use .NET or Node.js.
Click Terminal -> Configure Default Build Task and create tasks.json from template
Setup custom docker-build task -
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build image",
            "type": "docker-build",
            "dockerBuild": {
                "context": "${workspacefolder}",
                "dockerfile": "Dockerfile",
                "tag": "my-tag"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`
Click Run Build Task -> The terminal process failed to launch (exit code: 1). Adding `"platform": "node",` line also results in same error.

Running `docker build -f Dockerfile -t my-tag C:\workspace\folder\here` from terminal successfully builds the image.

vscode-docker version 0.10.0

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by bwateratmsft** [comment]
Thanks for the detailed info @shaktisinghr! I'll try out the scenario and see if I can repro. It is supposed to work for non-.NET/Node as long as tag, context, and dockerfile are present (which I see they are).

**Comment by bwateratmsft** [comment]
I am able to reproduce. There's two issues happening here.

1. The value for context is `${workspacefolder}`. VSCode is case-sensitive about these variables; it needs to be `${workspaceFolder}`. I looked briefly and did not find any issues about this in [their repo](https://github.com/microsoft/vscode); feel free to file one if you think it should be changed.
1. The value for dockerfile is `Dockerfile`. Unfortunately our code only properly understands it if it is `${workspaceFolder}/Dockerfile`. In my view this is a bug, if the Dockerfile is a relative path it should be obvious that it is relative to the workspace folder. Moreover, `docker build -f relativePath/Dockerfile` works fine as long as it is executed from the workspace folder (which in this case, it would be).

As a workaround, you can change your task to be this:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build image",
            "type": "docker-build",
            "dockerBuild": {
                "context": "${workspaceFolder}",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "tag": "my-tag"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by bwateratmsft** [comment]
A third issue is that the error message in validation is not surfaced to the user. We should fix that as well.

**Comment by shaktisinghr** [comment]
Thanks @bwateratmsft for the quick response. Unfortunately the workaround task definition also didn't work for me (same error).

**Comment by bwateratmsft** [comment]
Hm, strange. Can you share the output of a directory listing from the workspace folder? There might be another case-sensitivity issue happening...

**Comment by shaktisinghr** [comment]
Here's the directory listing of the folder -
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/2/2020  10:59 AM                .vscode
-a----         3/2/2020   2:32 PM           2180 Dockerfile
```

**Comment by bwateratmsft** [comment]
Well, that definitely looks correct. Once I get PR #1688 checked in, I can produce a nightly build. This version would provide a lot more information on what is going wrong. Would you be able to install a nightly build and try it out?

**Comment by bwateratmsft** [comment]
#1688 is submitted. Can you try following the instructions for #1408 to install the nightly build, and try?

**Comment by shaktisinghr** [comment]
Thanks @bwateratmsft, on the nightly build the Docker image builds successfully with the workaround (using ${workspaceFolder}/Dockerfile). However, using just "dockerfile": "Dockerfile" results in the same error as earlier - The terminal process failed to launch (exit code: 1).

**Comment by bwateratmsft** [comment]
Ugh, I'm sorry @shaktisinghr, the nightly build happened too early yesterday and missed my changes. I should have manually triggered a build. Can you try once more with the latest nightly?

**Comment by shaktisinghr** [comment]
Thanks @bwateratmsft , the latest nightly works without any workaround.
`"dockerBuild": {
                "context": "${workspaceFolder}",
                "dockerfile": "Dockerfile",
            },`

**Comment by bwateratmsft** [comment]
Awesome! Glad to hear it.

**Comment by bwateratmsft** [comment]
A fix for this bug has been released.
