### ISSUE TITLE
Feature - Toggle <none> images or Don't show them at all

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-docker#169]
Add a toggle so we can decide to show/hide the "none" images. Pruning isn't always desired, as it removes the intermediate layers that help speed up re-builds of the image.

![image](https://user-images.githubusercontent.com/1202528/32764398-395a2120-c8d3-11e7-999b-555dc6829a2a.png)

Preferred option is to filter out all dangling images. Without more context, there is less value in having them listed.

cc @chrisdias

**Comment by johnpapa** [comment]
`docker images --filter dangling=false`

**Comment by johnpapa** [comment]
I submitted a PR that will filter out the dangling images. It seems this was partially code previously.

If we do this ... a follow up could be to remove the system prune command. The use case here I'm thinking of is that the user will want to see the tagged images and want the re-builds to be fast as possible. So pruning may hurt that chance of faster rebuilds. Thus we may want to keep them there.

However, if we show all of the `<none>` tagged images (intermediates), then the treeview gets crowded fast, making it difficult to find the image we want. 

One option is to add a toggle. The other is to just not show the danglers. If we go this route, then we may as well remove the pruning, since the user cant see them.

I suspect the intent originally was to make the treeview easier to use. I think this PR makes that happen. Then later we can decide to remove the pruning option.

**Comment by fiveisprime** [comment]
I vote to hide the intermediates. People are confused about why they show up when I demo this internally.

**Comment by johnpapa** [comment]
I agree ... my PR does this (hides them).

**Comment by fiveisprime** [comment]
Haha yeah, I'm saying not to bother with the toggle. Keep your PR the way it is and we can react to any feedback about it going away imo

**Comment by johnpapa** [comment]
cool ... thanks.

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode-docker/pull/175
