### ISSUE TITLE
dockerServerReadyAction should have default pattern attribute

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1692]
As the user is using IntelliSense in the launch.json, when the user is inputting "pattern", there is no starting point given for the user. 

Developers will often have their own custom settings for their server ready messages so I am proposing that Intellisense defaults to a more clear regex pattern such as "Starting development server at (https?://\\S+|[0-9]+)"

Attaching @haniamr

**Comment by haniamr** [comment]
@ucheNkadiCode do you suggest a specific default value? The one you mentioned here is Django's, do we want to use that or have a more generic one such as just `(https?://\\S+|[0-9]+)`?

**Comment by ucheNkadiCode** [comment]
> @ucheNkadiCode do you suggest a specific default value? The one you mentioned here is Django's, do we want to use that or have a more generic one such as just `(https?://\\S+|[0-9]+)`?

So I think we could basically use the example described in Debug Python 
```json
"dockerServerReadyAction": 
{
  "action": "openExternally",
  "pattern": "Starting development server at (https?://\\S+|[0-9]+)",
  "uriFormat": "%s://localhost:%s/about.html"
}
```
And as your saying, only Django does the "Starting development server at...". So, myy opinion is to go with JUST `(https?://\\S+|[0-9]+)` because I think it'll be rare a person logs a url to the browser otherwise
