### ISSUE TITLE
docker: Error response from daemon: mkdir C:\Program Files\dotnet\sdk\NuGetFallbackFolder: Access is denied.

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1693]
Extension assumes that "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" exists and asks to volume mount.   I am uncertain when this folder is actually created but I don't have it.  I have dotnet sdk 3.1 + dotnet sdk 5.0 Preview 1 installed and ".Net Core Launch (web)" works

> docker run -dt -P --name "mymvc-dev" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" --label "com.microsoft.created-by=visual-studio-code" -v "c:\Users\devinb\mymvc:/app:rw" -v "c:\Users\devinb\mymvc:/src:rw" -v "C:\Users\devinb\.vsdbg:/remote_debugger:ro" -v "C:\Users\devinb\.nuget\packages:/root/.nuget/packages:ro" **-v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder**:/root/.nuget/fallbackpackages:ro" -v "C:\Users\devinb\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\devinb\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" "mymvc:dev" <

**docker: Error response from daemon: mkdir C:\Program Files\dotnet\sdk\NuGetFallbackFolder: Access is denied.**

**Comment by bwateratmsft** [comment]
Should be easy to validate that the folder exists before doing a volume mount. I think probably the right place for it is our `addVolumeWithoutConflicts` (spelling?) method.
