### ISSUE TITLE
Fail to debug Python project on Mac

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1694]
**OS:** Mac
**Build Version:** [1.0.0](\\haniamr-dev\VSCode\vscode-docker-1.0.0.vsix)

**Repro Steps:**
1. Open a python project(General/Django/Flask) in VS Code.
2. F1->Docker: Add Docker Files to Workspace->Python->include docker compose files.
3. F5.

**Expect:**
Debug Python project successfully without any error.

**Actual:**
Fail to debug Python project. (Share the path can't fix this issue)
![image](https://user-images.githubusercontent.com/45614674/75771993-122a8a00-5d86-11ea-8254-55ef35dfcd25.png)

**Comment by bwateratmsft** [comment]
@haniamr this might just be a test case/doc issue. For .NET Core we have a similar thing where some extra folders must be explicitly shared.

**Comment by bwateratmsft** [comment]
Fixed by #1703
