### ISSUE TITLE
The docker-compose.debug.yml template for a default ASP.NET Core web app does not work

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1695]
The docker-compose.debug.yml files created do not deal with user secret mapping, but do still set ASPNETCORE_URLS including an HTTPS endpoint. Because of this, compose-up will start the container but it will immediately exit.

The exception in the Docker log shows that it could not find the developer certificate:
`System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.`

**Comment by ravipal** [comment]
Yes, the container fails to start when it has https endpoint is provided.
The simpler fix is to not add https endpoint and default scaffold to include the following
- ASPNETCORE_URLS=http://+:80

**Comment by bwateratmsft** [comment]
Fixed by #1705
