### ISSUE TITLE
Support docker-compose V2 syntax?

### ISSUE THREAD

**Issue by tkvangorder** [Microsoft/vscode-docker#17]
Are there any plans to support the V2 syntax for docker compose? 

https://docs.docker.com/compose/compose-file/#versioning

**Comment by SteveLasker** [comment]
Hi Tyler,
Yes, this is something we've been looking at with our other docker tools and need to round back here. 
Is there specific features your looking to scaffold out?

**Comment by tkvangorder** [comment]
Just looking for intellisense for a V2 file. Thanks!

**Comment by SteveLasker** [comment]
Ahh, ok. So your looking for an updated language service. Not just updated scaffolding from yo docker.

**Comment by miguelchico** [comment]
Any update about V2 support?

**Comment by SteveLasker** [comment]
Unfortunately, the language service isn't something we've had a chance to prioritize. We've been working on our Windows container support, perf and consolidating the experience between vs code and vs. 
as an open source project, we would be very interested if someone wanted to propose some updates, have a quick review and take a pull request.

**Comment by lostintangent** [comment]
@tkvangorder This has been resolved via #34. If you want, you can pull the latest bits from this repo, and build/install the extension locally. Otherwise, it will get picked up in the next marketplace release. Thanks so much for the feedback!
