### ISSUE TITLE
VSCode Docker Run and Debug shows exit status of 1

### ISSUE THREAD

**Issue by dvoit** [microsoft/vscode-docker#1709]
Does this occur consistently?  Yes
Repro steps:

1. Select the "RUN AND DEBUG" Configuration option from the select list.
2. Click the Run icon just to the left of the "RUN AND DEBUG" select list.

This encompasses step 5 (Start debugging) listed underneath the "Debug in container" section
https://code.visualstudio.com/docs/containers/quickstart-aspnet-core

After clicking the run icon, I'm prompted with a "Process exited with code 1 ... Source: Docker (Extension)" dialog.

Action: docker-launch
Error type: 1
Error Message: Process exited with code 1

Version: 0.10.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:541435
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
Thanks @dvoit. Is there any output in the Tasks window for .NET build / Docker build / Docker launch? Is there anything in the Output tab > Docker?
