### ISSUE TITLE
Fail to execute "Compose up" action for docker-compose.debug.yml 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1711]
**OS:** Mac/Linux
**Build Version:** [20200304.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15718&view=results)

**Repro Steps:**
1. Open a .NET Core MVC/Console project in VS Code.
2. F1->Docker: Add Docker Files to Workspace->.NET Core->include docker compose files.
3. Right click docker-compose.debug.yml and execute "Compose up" action.

**Expect:**
Execute "Compose up" action successfully.

**Actual:**
Fail to execute "Compose up" action.
![image](https://user-images.githubusercontent.com/45614674/75885960-686cfb00-5e62-11ea-9baa-df08cfd27e25.png)

**More Info:**
This issue does not reproduce on Windows.

**Comment by bwateratmsft** [comment]
Scaffolding creates a backslash but should create a forward slash.
