### ISSUE TITLE
Provide a way to persist user option to install debugger on container

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1717]
During attach to .Net Core container, we ask user permission to install the debugger on the container. As long as the container has the debugger installed we don't ask again. So this should address most of the cases.
But if user attaches to another container (say compose down and compose up), it wouldn't have debugger and we prompt user for permission. 
We should provide a way to persist user option (like don't ask again) at workspace level or globally.

**Comment by bwateratmsft** [comment]
Perhaps the best option is to just map `~/.vsdbg`, which is what docker-compose.debug.yml is doing. We should also add code to install the debuggers in case they never execute the single-Dockerfile debugging (and thus don't have that folder populated).

For users who want to avoid the prompts every time, they should compose-up with the debug.yml.

**Comment by bwateratmsft** [comment]
This is mitigated in part by the fix we need for #1794

**Comment by ravipal** [comment]
we still need to copy files to container and we still require user consent to do so.

**Comment by bwateratmsft** [comment]
Also, this probably becomes obsolete with #840

**Comment by bwateratmsft** [comment]
With #2338 I think this becomes unnecessary. We now unconditionally install vsdbg before running .NET containers, so the default docker-compose.debug.yml will work for free. It's still possible to get the prompt if you try to debug the not-debug configuration, but I don't think that is a serious issue.
