### ISSUE TITLE
Add ability to deploy an image in ACR (or other registry?) to Azure Container Instances (ACI)

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#1718]
Similar to how I can click on an image in ACR and deploy it to Azure App Service, I would like to be able to deploy it to ACI as well.

**Comment by dbreshears** [comment]
Lets also do this for Docker Hub since Azure services can pull from Docker Hub since it is public.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension 1.6.0.
