### ISSUE TITLE
Open in Browser fails with new ASP.NET Core project when using Docker-Compose Up

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1720]
Looks like it is attempting to navigate to https://localhost:<port> based on 443 ports in the Docker compose files and failing due to asp.net core not working with https in the container yet.     A workaround for now is to remove -443 from the ports section of the compose files

1) dotnet new mvc
2) Docker: Add Docker Files to Workspace...  (choose yes to add compose files)
3) right click the docker-compose.yml or docker-compose-debug.yml and select "Compose Up"
4) right click the container in the explorer and choose "Open in Browser"

**Comment by bwateratmsft** [comment]
Fixed by #1721, but it also needs to be cherry-picked to master.
