### ISSUE TITLE
ASP .NET Core docker compose is not setting up https endpoint

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1724]
The default scaffolding of docker compose for ASP .Net Core isn't setting up https endpoint.

**Comment by bwateratmsft** [comment]
We should make sure we use as much of the same code path as possible between single and compose, since this is implemented already for single.

**Comment by ravipal** [comment]
We decided to add a comment with link to a document explaining how to setup a https developer certificate
