### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration with alpine image on Linux

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1739]
**OS:** Linux (Ubuntu 18.04)
**Build Version:** [20200306.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15959&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Open a .NET Core Console project in VS Code --> Prompt to add the required assets --> Yes
2. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> .NET Core Console --> Linux --> Include optional Docker Compose files.
3. Edit the Dockerfile with **alpine** image.
4. Right click the docker-compose.debug.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container.

**Expect:**
Run the configuration successfully without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/76211085-67f8a980-6240-11ea-8e31-4a40fc7ad89b.png)

**More Info:**
1. This issue does not reproduce on Windows and Mac.
2. This issue does not reproduce for Ubuntu and Debian images.
3. This issue also reproduces for .NET Core MVC project.

**Comment by bwateratmsft** [comment]
I was not able to reproduce when I tried this out on Ubuntu 19.04. I tried two scenarios:

1. _Before_ ever running single-Dockerfile F5 and getting the debugger installed locally
1. Delete the debugger installed from container (to avoid another bug), then run single-Dockerfile F5 to get a debugger installed locally, and then compose up + attach.

@v-ruizh Can you try again and see if this still occurs?

**Comment by ravipal** [comment]
@bwateratmsft, The problem seems to be with Alpine image, If you have the Linux machine can you try with alpine image?

**Comment by bwateratmsft** [comment]
@ravipal It was with an Alpine image, didn't have any problem.

**Comment by ravipal** [comment]
Got it. When you said, Ubuntu I misunderstood that you were using Ubuntu image.

**Comment by v-ruizh** [comment]
@bwateratmsft I created a new Ubuntu 18.04 VM and verify this issue, it **does not reproduce** on the new machine. Maybe this is an environment issue, close it.

**Comment by ravipal** [comment]
@v-ruizh, Next time when you hit similar bug, please capture the content of window output, which will have information about the vsdbg installation on the container.
