### ISSUE TITLE
The "unexpected operator" log occurs during installing the latest .NET Core debugger

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1741]
**OS:** All
**Build Version:** [20200306.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15959&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Open a .NET Core MVC project in VS Code --> Prompt to add the required assets --> Yes
2. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
3. Right click the docker-compose.yml --> Select "Compose Up".
4. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
5. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.
6. Check the Docker output log.

**Expect:**
There is no "unexpected operator" log during installing the latest .NET Core debugger.

**Actual:**
The "unexpected operator" log occurs during installing the latest .NET Core debugger.
![image](https://user-images.githubusercontent.com/45614674/76212249-02f28300-6243-11ea-9041-eceffb3cca15.png)

**More Info:**
1. This issue reproduces for Ubuntu and Debian images but not for Alpine image.
2. This issue also reproduces for .NET Core Console project.

**Comment by bwateratmsft** [comment]
This might be emitted by the vsdbg script itself.

**Comment by bwateratmsft** [comment]
I looked and it's not from vsdbg, but rather because we have `if [ $ID == alpine ]` in there. Evidently sh doesn't like `==`, and would prefer `=`.

**Comment by bwateratmsft** [comment]
Ironically, sh on Alpine is just fine with `==` so the script overall still works on Alpine. So, we do not need to fix this for 1.0.0. I tested with `=` and it seems fine so I'll make that change.
