### ISSUE TITLE
Cannot debug aspnet core projects

### ISSUE THREAD

**Issue by richarddavenport** [microsoft/vscode-docker#1744]
Repro steps:

1. Create a new web api project (cli): `dotnet new webapi`
2. Make sure OmniSharp server is running and run (command palette): `.NET: Generate Assets for Build and Debug`
3. Run (command palette): `Docker: Add Docker Files to Workspace`
4. Select `ASP.NET Core`
5. Select `Linux`
6. Keep default ports: `80, 443`
7. Start debugging with the newly created `Docker .NET Core Launch` launch task.

This is happening suddenly on all my docker asp.net core projects.

Action: docker-launch
Error type: 9
Error Message: Process exited with code 9

Version: 0.9.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:530610
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@richarddavenport Does it show anything in the terminal window?

**Comment by richarddavenport** [comment]
I realize it says `Version 0.9.0`, but I had tried to downgrade to see if it fixed the issue, it did not. I'm actually running 0.10.0.

No, I don't see anything in the terminal window.

Here is what I see in the Output panel:
<img width="671" alt="Screen Shot 2020-03-09 at 11 31 39 AM" src="https://user-images.githubusercontent.com/3596012/76235805-a159f680-61f9-11ea-8309-0c580d368257.png">

**Comment by richarddavenport** [comment]
Sorry, I was able to get it to come up.
```
> Executing task: docker-run: debug <

> docker run -dt --name "mbpapidocuments-dev" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" --label "com.microsoft.created-by=visual-studio-code" -v "/Users/richardd/Projects/MBP/MBP.API.Documents/src:/app:rw" -v "/Users/richardd/Projects/MBP/MBP.API.Documents:/src:rw" -v "/Users/richardd/.vsdbg:/remote_debugger:ro" -v "/Users/richardd/.nuget/packages:/root/.nuget/packages:ro" -v "/usr/local/share/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro" -v "/Users/richardd/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro" -v "/Users/richardd/.aspnet/https:/root/.aspnet/https:ro" -p "12802:80/tcp" -p "12803:443/tcp" "mbp.api.documents:dev" <

56408a69906cde05b280ab6d8b4a1cd1df0819c29e4d68330a1a7b4f064a74a4
Attempting to containerize Blazor static web assets manifest...
Failed to update Blazor static web assets manifest. Static web assets may not work.
The error was: TypeError: l.StaticWebAssets.ContentRoot is not iterable

Terminal will be reused by tasks, press any key to close it.
```

**Comment by bwateratmsft** [comment]
We're aware of that warning (#1715) but it doesn't actually prevent debugging. Is there anything in the debug console?

**Comment by richarddavenport** [comment]
Okay, so I figured it out, but only because I tried without docker... which is not what I normally do. I tried debugging as a regular .net app. It said my dev-cert was in a weird state.

I had to run:
`dotnet dev-certs https --clean`

After that succeeded I ran
`dotnet dev-certs https`

I had to enter my password several times and it worked.
I then tried debugging in docker again and it prompted with this:
<img width="451" alt="Screen Shot 2020-03-09 at 11 46 13 AM" src="https://user-images.githubusercontent.com/3596012/76237277-044c8d00-61fc-11ea-8a32-7275d789ca1f.png">

After I ran `dotnet dev-certs https --trust` It all started working again.

So it seems this is somehow a dev-cert issue?

**Comment by bwateratmsft** [comment]
I guess it could be. I'll investigate to see. That exit code 9 might have come from `dotnet dev-certs`.

**Comment by richarddavenport** [comment]
To be clear, I did not see anything in the Debug Console.
Thanks!

**Comment by richarddavenport** [comment]
One thing I remember now... I had to change my domain password on my mac... That is most likely the beginning of my issues.

**Comment by bwateratmsft** [comment]
Looks like that's what was happening. There's a new-ish failure mode in the `dev-certs` tool: https://github.com/dotnet/aspnetcore/blob/master/src/Tools/dotnet-dev-certs/src/Program.cs#L165

Unfortunately our code is not emitting the above error message anywhere, so that's definitely something we should improve.

**Comment by bwateratmsft** [comment]
It's possible that #1689 fixes this too...
