### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by carlosjacinto** [microsoft/vscode-docker#1747]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.reconnectRegistry
Error type: Error
Error Message: Couldn't create item: The secret was transferred or encrypted in an invalid way.

Version: 1.0.0
OS: linux
OS Release: 5.3.0-40-generic
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

**Comment by bwateratmsft** [comment]
Hey @carlosjacinto, does this issue happen consistently? What happens if you disconnect the registry, then try connecting again?

**Comment by bwateratmsft** [comment]
Seems like there's [a lot of reports](https://www.google.com/search?q=%22The+secret+was+transferred+or+encrypted+in+an+invalid+way.%22) of this error showing up throughout the years. Something broken down in gnome-keyring. It sounds erratic.
