### ISSUE TITLE
Selecting multiple compose files with context menu "Compose Up" should execute them in a single command

### ISSUE THREAD

**Issue by slavdok** [microsoft/vscode-docker#1749]
Maybe related to #569, but different.

It's now fixed that doing `Command Palette > Docker: Compose Up` will detect if there is an docker-compose.override.yml file, and will include that by running `docker-compose up` without specifying a file.

However when I select `docker-compose.yml` from `Explorer View > Right click > Compose up`, it still runs `docker-compose -f "$file" up`. This is probably by design.

But what if I have `docker-compose.yml`, `docker-compose.override.yml` and `docker-qa.yml` files. I would like to select 2 in the Explorer view (it supports that now), the default and the qa one, then `Right click > Compose up`, and would like to see `docker-compose -f "docker-compose.yml" -f "docker-qa.yml" up` command executed.

Instead right now it launches each individually. 
If this infringes on anyone's workflow, maybe make it a configurable option, like `-d` and `--build`

**Comment by bwateratmsft** [comment]
@slavdok I had thought of this also when working on the compose command customization, so you certainly aren't alone, but I didn't want to change the behavior present.

One challenge is knowing the order to put them in--I don't think VSCode gives us any hint as to what order they were selected in, and alphabetical wouldn't always be right.

**Comment by slavdok** [comment]
> One challenge is knowing the order to put them in

Solution one: just like #569 fix, is to assume correct filenames, so `docker-compose.yml` first, the rest second (in alphabetical order). If `docker-compose.yml` is not present, revert to current behaviour.

Solution two: use the same functionality as selecting files for compare, where you mark one file first, then individually mark the second file for compare (I am sure at that point, VSCode knows which was first)

Thanks for looking into this

**Comment by bwateratmsft** [comment]
In the meantime, if you're hitting this issue pretty consistently for a single project or if you have a consistent pattern of files, you could customize the Compose command using this new mechanism for 1.0.0: https://code.visualstudio.com/docs/containers/reference#_command-customization

For example, you could create two compose-up commands:
```json
    "docker.commands.composeUp": [
        {
            "label": "Compose up with QA",
            "template": "docker-compose ${configurationFile} -f docker-qa.yml up ${detached} ${build}"
        },
        {
            "label": "Compose up without QA",
            "template": "docker-compose ${configurationFile} up ${detached} ${build}"
        }
    ]
```
When you right-click the main `docker-compose.yml` file in this instance and do compose up, it will prompt you to choose between the above two templates, remembering your previous choice. You could make this a workspace setting if this is applicable to a particular project only.

**Comment by ravipal** [comment]
This is documented here - https://code.visualstudio.com/docs/containers/docker-compose#_docker-compose-with-multiple-compose-files
