### ISSUE TITLE
Error Message: Task to execute is undefined

### ISSUE THREAD

**Issue by fhumayun** [microsoft/vscode-docker#1754]
Does this occur consistently? Yes
Repro steps:

1.  Used this as my dockerfile

FROM node:10.13-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
RUN apt-get install sudo
RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER docker

# this is where I was running into problems with the other approaches
RUN sudo apt-get update 
COPY . .
EXPOSE 3000
CMD npm startRUN apt-get update 

2.  Attempt to build image

Action: vscode-docker.images.build
Error type: 5
Error Message: Task to execute is undefined

Version: 1.0.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

**Comment by bwateratmsft** [comment]
Hey @fhumayun, this is a known issue we have fixed for the upcoming v1.1 release. You can fix it by removing the Docker tasks from the workspace file and moving them into the workspace _folder_ `tasks.json` file. More info available here: #1462
