### ISSUE TITLE
F5 continues without waiting for user to trust the ASP dev certificate

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1755]
F5 (Docker .Net Core Launch) on ASP .NET Core web application shows the below prompt
![image](https://user-images.githubusercontent.com/1775825/76669379-93350e80-6548-11ea-9efb-257121564d32.png)
But doesn't wait for user input and continue the debugging and opens the webpage that shows "This site is not secure"

**Comment by bwateratmsft** [comment]
This design was intentional. Trusting the certificate is not a mandatory step, and in fact aside from Windows it's not even possible.

**Comment by bwateratmsft** [comment]
The discussions we had at the time was that a modal popup was way too annoying, and a non-modal popup could be missed (which would cause us to wait forever). Since trusting isn't mandatory we opted to not wait.
