### ISSUE TITLE
The specified task cannot be tracked

### ISSUE THREAD

**Issue by haniamr** [microsoft/vscode-docker#1756]
### Environment
VS Code version: 1.43.0
Docker extension: 1.0.0

### Repro steps:
1. Create a dotnet core project then Add Docker Files to workspace
2. F5 and it works fine
3. In tasks.json, change the "dockerBuild -> target" to an invalid value, something like "base1"
4. F5 and docker-build fails, which is expected
5. Correct the issue in step 3 and F5 again, docker-build succeeds but then I get this:
![image](https://user-images.githubusercontent.com/5480153/76670314-16586380-654d-11ea-8ff2-0187474ca98f.png)
![image](https://user-images.githubusercontent.com/5480153/76670451-c928c180-654d-11ea-9341-d8cf5d0971d5.png)

It doesn't work until I restart VS Code. Not sure what's happening here but it seems that the docker-run task crashes before it gets to execute anything.

**Comment by daniellessio** [comment]
I'm getting similar behavior running on Ubuntu 18.04, except I don't need to purposely brake the task. Restarting VS Code makes it work.

My environment:
OS: Ubuntu 18.04.4 LTS
VS Code: 1.43.0 / 78a4c91400152c0f27ba4d363eb56d2835f9903a / x64
Docker extension: 1.0.0

**Comment by alexr00** [comment]
I'm trying to repro using the steps above, but when I F5 the first time I just get an error notification:
"Process exited with code 1" Any other steps that should be done after adding the docker files?

**Comment by alexr00** [comment]
There is this bug: https://github.com/microsoft/vscode/issues/92792
It seems that the task system is now taking longer to run tasks the second time. About how long does the prelaunch task take to run the first time? If it's close to 10 seconds, you might be seeing the same thing.
However, if your task takes close to 10 seconds then you might hit the "can't be tracked" timeout even without that bug since it shows after 10 seconds.

**Comment by bwateratmsft** [comment]
`docker-build` can definitely take longer than 10 seconds, especially if it needs to download images.

@alexr00 I don't think we'd seen this error prior to now, even with the amount of time the tasks can take. Did something change in 1.43?

**Comment by alexr00** [comment]
It looks like this is a duplicate of microsoft/vscode#92792 I think there's a missing task event.

**Comment by bwateratmsft** [comment]
Missing on our side or in VSCode itself?

**Comment by alexr00** [comment]
Missing in VS Code itself. Since I can't get the repro steps above to work, I can't be 100% sure but it certainly looks the same.

**Comment by haniamr** [comment]
Thanks @alexr00 and @bwateratmsft, I'm not sure why you were getting this error however as you mentioned the issue seems very similar to what you're referring to.

**Comment by alexr00** [comment]
You should be able to test if the issue is fixed in the latest insiders now.

**Comment by bwateratmsft** [comment]
Per Alex's [comment](https://github.com/microsoft/vscode/issues/92792#issuecomment-600514123) this will be in the 1.43.1 stable release, so I will remove the 1.0.1 milestone and delete/close it, since this will not require a change from our end.

>Yes, it is in the latest insiders now. It is also planned to be included in the 1.43.1 sable release.

**Comment by bwateratmsft** [comment]
@haniamr Version 1.43.1 is released now, we should try it out and make sure this is fixed.

**Comment by haniamr** [comment]
I tried on both 1.43.1 and the latest insiders, but still can repro the issue.

@alexr00 for the repro steps to work, can you please run this from an administrator cmd: `mkdir "C:\Program Files\dotnet\sdk\NuGetFallbackFolder"` and try it again? It should work this way.

**Comment by alexr00** [comment]
I can repro the issue now. Looking into what might be going on...

**Comment by alexr00** [comment]
I found the problem and merged a fix into VS Code. If we have another recovery release it will likely go into stable with that.

**Comment by haniamr** [comment]
Thanks a lot @alexr00, totally appreciate the quick fix!

**Comment by haniamr** [comment]
Verified the issue on the latest Insiders build and it is fixed, but will keep this for tracking purposes till the fix is available in the stable builds.

**Comment by alexr00** [comment]
The fix is planned to be in 1.43.2, so I expect that to be this week.

**Comment by haniamr** [comment]
Thanks @alexr00, I verified the issue in 1.43.2 and it is resolved.
