### ISSUE TITLE
docker extension missing

### ISSUE THREAD

**Issue by dimensionaltechs** [microsoft/vscode-docker#1757]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 1.0.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerHubAccountTreeItem.<anonymous> extension.bundle.js:1:722205
o extension.bundle.js:1:716083
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@dimensionaltechs what registries do you have connected in the Explorer tab?
