### ISSUE TITLE
Wrong date/duration description in Volume and Network tree item

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1758]
some of the volume and description related tests started failing.
When the date is 45 days ago from now (2020-03-16), then the date is 2020-01-31. This translates into '2 months ago' based on the implementation (moment(time).fromNow()). But the tests were expecting 1 month ago.
Either the test should be updated to use the same implementation in verification code or use some other implementation that shows '1 month ago' instead of '2 months ago'

Sample test failure: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16278&view=results

**Comment by bwateratmsft** [comment]
Seems like a good candidate for getting removed. This test is really testing what the output is from `moment.fromNow()`--why would we need a test case for that? That's somebody else's code :smile:

**Comment by ravipal** [comment]
The test covers more than just `moment(time).fromNow()` like how the description is formatted, group by date, etc. I temporarily updated the test to make it pass.
As I mentioned in the issue, either the test should be updated to use `moment()` in expected result or update the product code to come up with the right description.

**Comment by bwateratmsft** [comment]
Where does that age come from in the product code? Is it from Docker itself?

**Comment by ravipal** [comment]
On a second thought, this is a product issue. The description should NOT say '2 months ago' when it is 45 days ago.

It is in our code. The input from docker is a date and we come up with the description based on the date.

**Comment by bwateratmsft** [comment]
Where is that code?

**Comment by ravipal** [comment]
https://github.com/microsoft/vscode-docker/blob/05d585ed9c98533d506ed70f0236968faf278129/src/tree/settings/CommonProperties.ts#L33

**Comment by bwateratmsft** [comment]
I see, so the test case is really comparing the output of `moment` to a fixed string. But, that means it's a test of somebody else's code--not something we should have.

**Comment by ravipal** [comment]
Here is what the test is validating
1. Provide a date which is 45 days ago to simulate docker inspect is obtaining this date string from docker. (example: 2020-01-31 assuming today is 03/16).
2. Validate the description of tree item shows 'id - 1 month ago'.

But due to implementation error, the code returns 'id - 2 months ago'.

**Comment by bwateratmsft** [comment]
Maybe that can only happen on March 15/16, due to February being shorter?

**Comment by ravipal** [comment]
I am not sure if it is specific to that specific day or not. Require more testing. Doesn't matter whether it is coming from other package we depend on or not, it is still a bug.

**Comment by bwateratmsft** [comment]
I disagree. Saying it's 2 months ago is not an unreasonable description for something created in January.

**Comment by dbreshears** [comment]
According to the docs on fromNow,  45 to 319 days  is "2 months ago .. 10 months ago"
