### ISSUE TITLE
Don't use the golang:onbuild image as it's deprecated

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode-docker#176]
See https://hub.docker.com/_/golang/ which mentions https://github.com/docker-library/official-images/issues/2076 .

**Comment by chrisdias** [comment]
What would a good `go` default `Dockerfile` look like?

**Comment by brettcannon** [comment]
I have no idea as I'm not a active Go developer anymore. 😄 I just happened to be looking at the current `Dockerfile` templates and noticed that the DockerHub image stated that all the `onbuild` images were deprecated. So I guess maybe what the `onbuild` image does except with those steps in the template itself? Or maybe ask one of the Go-focused CDAs what they think?

**Comment by chrisdias** [comment]
this fixed with https://github.com/Microsoft/vscode-docker/pull/194 and is in 0.0.23.
