### ISSUE TITLE
Debugging docker-compose projects with predictable port?

### ISSUE THREAD

**Issue by filipweidemann** [microsoft/vscode-docker#1765]
A few issues since jumping on the VSCode Debugging train since the 1.0 release:

- Is it possible to use the debugger for very large `docker-compose` projects?
Currently I am having issues spinning up more than one container using a Dockerfile, it seems as the docker-compose.yml is completely ignored.
 
- Why is the port mapping random? Do we currently have the possibility to run an app inside the container listening on, lets say, port `8000` and connect to it using port `8000` on our host? All I can currently run is using random ports, increasing them by 1 each time I restart the debugger.
This surely isn't right, correct?

I am sorry for opening an issue for this, but I can't find anything inside the docs for this specific use case, just vague examples for very very tiny use cases and nothing regarding compose at all!
Thanks for your time guys :)

**Comment by filipweidemann** [comment]
Okay so I figured out how to customize the host port, look something like this:

`
"dockerRun": {
        "ports": [
          {
            "containerPort": 8000,
            "hostPort": 8000
          }
        ],
}
`

However, I am still not sure how to use the `docker-compose.yml`

**Comment by bwateratmsft** [comment]
I'm glad you asked! We're still working on a more integrated debugging experience for docker-compose, but it is possible to debug today for most frameworks. The `docker-run` task does indeed ignore compose files; in the future we want to have `docker-compose-up` tasks that will use the compose files.

You'll want to move your port mappings into your `docker-compose.yml` files. The port mappings in `tasks.json` will only apply for that particular project/Dockerfile and only when launched using the `docker-run` task, i.e. `docker-compose up` will not use them.

The debugging flow will consist of two main steps--

1. Run `docker-compose up`. There are quite a few ways you can do this:
    1. (Manual) In the terminal
    1. (Manual) Right-click your `docker-compose.yml` and choosing "Compose Up"
    1. (Manual) Run "Docker: Compose Up" in the command palette
    1. (Automatic--will happen when you <kbd>F5</kbd>) Create a shell task in `tasks.json`, and set it as the `preLaunchTask` of your debug configuration in `launch.json` (more on that below). The task will look something like this:
```json
        {
            "label": "Compose Up",
            "type": "shell",
            "problemMatcher": [],
            "command": "docker-compose up -d"
        }
```
2. Attach to your application using an attach configuration in `launch.json`. This will depend on the language/framework you are using. Are you using Node, .NET Core, Python, others, a mix?
    1. It is possible to attach to multiple containers with one <kbd>F5</kbd>, using a [compound debugging configuration](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations).
    1. (Optional if using 1.iv. above) In your launch configuration, set the `preLaunchTask` to your compose up task, e.g. "Compose Up".
    1. (Optional) Set the `postDebugTask` to a "Compose Down" task, like the "Compose Up" one above.

**Comment by filipweidemann** [comment]
First of all, thank you for the detailed answer. This made things pretty clear already!
I am currently running a mix of different Django/Flask Projects, so Python all the way here.

Will definitely look forward to the `docker-compose-up` task, but doing it manually for now is absolutely okay as well! Thank you for explaining the flow, it is quite clear what to do now. Thanks!

**Comment by bwateratmsft** [comment]
@haniamr can you add some information on Python attach to a composed-up container to my post?

**Comment by haniamr** [comment]
Sure thing. Here are the steps to debug your app running with Gunicorn (could apply to any web server as well) while using docker-compose: https://code.visualstudio.com/docs/containers/debug-python#_how-to-debug-your-app-with-gunicorn

@filipweidemann please feel free to get back to us if you have any questions and we'll be happy to help!

**Comment by filipweidemann** [comment]
Thank you very much @haniamr @bwateratmsft.

**Comment by bwateratmsft** [comment]
I'll close this issue for now, please let us know if anything else comes up. Thanks!
