### ISSUE TITLE
[Python] Handle failures of dependent tasks when waiting for debugger

### ISSUE THREAD

**Issue by haniamr** [microsoft/vscode-docker#1768]
### Repro steps:
- Add docker files to a Python project
- Introduce a syntax error in the Dockerfile
- F5

### Results
docker-build fails as expected however the debugger is still trying to attach.

In this line https://github.com/microsoft/vscode-docker/blob/e76d2dc1b560f1cc394b85d6a18e3d15ea0024b3/src/tasks/python/PythonExtensionHelper.ts#L38, we wait for the preLaunchTask indefinitely. However, in this scenario, the preLaunchTask doesn't even start since a dependent task fails.

The challenge is that VSCode doesn't inform us about a result of a task when it finishes (i.e. failed or succeeded), so there isn't a definitive way to know that a dependent task passed/failed given there might be N number of tasks that are introduced by the user and there's no way for us to infer the result.

I opened this issue in the VSCode repo https://github.com/microsoft/vscode/issues/92978 about the possibility of passing in the result of an executed task.

**Comment by bwateratmsft** [comment]
@haniamr Our code does the Docker build and Docker run, at a minimum, so we can create events for that. I'm not sure if there's anything we can do about other dependent tasks, but those two would cover a majority of cases.
