### ISSUE TITLE
when trying to push to azure registry, I have to manually run az acr login from the command line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-docker#177]
_From @MaurGi on November 17, 2017 23:53_

CLI tools - Release 0.3.0

My VS Code version:
![image](https://user-images.githubusercontent.com/13138584/32973928-6932a672-cbaf-11e7-811d-1ac7f09f9f57.png)

_Copied from original issue: Microsoft/vscode-azurecli#26_

**Comment by chrmarti** [comment]
What would the expected behavior be? (I think the registry has a separate username and password.)

**Comment by chrmarti** [comment]
_From @MaurGi on November 20, 2017 16:30_

Sorry this bug is poorly written, I was in a rush - my expectation is to prompt for username and password, like it does for DockerHub - if you select DockerHub under registries, you are prompted for a username: 
![image](https://user-images.githubusercontent.com/13138584/33029204-d8e8e9c6-cdcc-11e7-80a3-a07724d2ac6e.png)
The same is not true if you select Azure as registry -

thx

**Comment by chrmarti** [comment]
Got it, are you using the Docker extension? This might be a request going to that extension.

**Comment by chrmarti** [comment]
_From @MaurGi on November 20, 2017 18:46_

I am - 
I have Docker extension version 0.0.22 - thx.

**Comment by chrisdias** [comment]
The extension simply shells out to `docker push` which is why you need a separate login. ideally we can do a `push` through the API so that we don't have to shell to the `docker` cli.  that would be the "fix" here.

**Comment by MaurGi** [comment]
Thanks for the reply!
All I am saying is that when you use Docker registry you are prompted with username and password, while when you use Azure registry you are not, you have to know that you need to manually do an `az acr login`  to be able to use it -

**Comment by PrashanthCorp** [comment]
Let's investigate this to check if it's a dupe.
