### ISSUE TITLE
Pop up an error when running "Docker Registries: Log In to Docker CLI"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1776]
**OS**: Windows
**Build Version:**  [20200319.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16479&view=results)
Regression: Previous Release

Does this occur consistently?  Yes
**Repro steps:**

1. F1 --> Type and select "Docker Registries: Log In to Docker CLI".
2. Select one Azure Registry.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Command failed: docker login undefined --username 00000000-0000-0000-0000-000000000000 --password-stdin
Error response from daemon: Get https://undefined/v2/: dial tcp: lookup undefined on 192.168.65.1:53: no such host
![image](https://user-images.githubusercontent.com/34729092/77145534-12917900-6a46-11ea-9c5c-f23030c6f7ef.png)

Version: 1.0.1-alpha
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code - Insiders
Product Version: 1.44.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**More Info:**
This issue doesn't reproduce on the previous release.
![image](https://user-images.githubusercontent.com/34729092/77145476-e675f800-6a45-11ea-897d-0939f1312b36.png)

**Comment by bwateratmsft** [comment]
Looks like `creds.registryPath` was undefined, might be a regression from the recent refactoring. I'll take a look.
