### ISSUE TITLE
Display an error "The resource namespace 'Microsoft.ContaimerRegistry' is invalid " when signing in with Azure Germany account

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1777]
**OS**: Windows
**Build Version:** [20200319.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16479&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Sign in with Azure Germany account.
2. Drill down from Registry -> Azure -> One applied subscription.

**Expect:**
Succeed to list the created Azure registries.

**Actual:**
Display an error "The resource namespace 'Microsoft.ContaimerRegistry' is invalid " . Not sure it is supported for Azure Germany accounts.
![image](https://user-images.githubusercontent.com/34729092/77146625-72c7ff80-6ac6-11ea-90fd-24ca44f1f2e9.png)

**More Info:**
1. Not rerroduce for Azure accounts.
2. Not reproduce for Azure China accounts.

**Comment by bwateratmsft** [comment]
Looks like it is not supported in the German sovereign region(s):

![image](https://user-images.githubusercontent.com/36966225/77170602-a2104980-6a91-11ea-9193-2d80a5f3ffaf.png)
