### ISSUE TITLE
after installing Docker extension successfully, and running "Docker Images: Build Image... ", giving error that "Task Not Found"

### ISSUE THREAD

**Issue by ahmedbham** [microsoft/vscode-docker#1781]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: Task not found

Version: 1.0.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:3664:990
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
This looks similar to #1647. @ahmedbham are you using workspaces or workspace folders?
