### ISSUE TITLE
Add command palette for Docker Context 

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1784]
Add support via command palette for Docker Context 

For the following commands:

Use
Inspect
Remove

**Comment by bwateratmsft** [comment]
If we're gonna do Remove, we should do Create/Update as well (or neither) IMO.

**Comment by karolz-ms** [comment]
@bwateratmsft creating/updating may involve a bunch of data related to authN. I'd say let's not go there in the first iteration and have the user rely on Docker CLI
 
@haniamr I have a change in the works that is very related to this Talk to me before you start working on it. It might be most efficient for me to do both.

**Comment by haniamr** [comment]
Based on our offline discussion, I'll assign this one to Karol.

**Comment by bwateratmsft** [comment]
Fixed in #1814
