### ISSUE TITLE
Can't reach the express web page after executing "Compose Up" action for docker-compose.yml

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1792]
**OS:** Windows
**Build Version:**[20200324.4](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16633&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Create an Express App and open it in VS Code
2. F1->Docker: Add Docker files to Workspace->Node.js->include Docker compose file->port:3001
3. Verify that your docker-compose.yml is like this
 ![image](https://user-images.githubusercontent.com/62053665/77629939-42c8a280-6f85-11ea-81f2-880e1e515e9f.png)
4. Right click docker-compose.yml file -->compose up
5. Browse to http://localhost:3001 in a web browser

**Expect:**
You should see this express web page:
![image](https://user-images.githubusercontent.com/62053665/77630700-722bdf00-6f86-11ea-8110-b0482c88688d.png)

**Actual:**
Can't reach this page:
![image](https://user-images.githubusercontent.com/62053665/77630633-59232e00-6f86-11ea-93dd-87e9137758ea.png)

**Comment by ravipal** [comment]
@v-amyang, The generated docker-compose.yml will have that port mapping as below.
ports:
  - 3001

When the container is started using compose up, it will assign a random host port which can be obtained using `docker ps` or `docker inspect <id>`

Please re-open if this is not the case.

**Comment by bwateratmsft** [comment]
@ravipal The docker-compose.yml maps 3001 to 3001:
> - 3001:3001

**Comment by ravipal** [comment]
well, I don't see this port mapping behavior. The new scaffold behavior just creates -3001 without explicit host port.
Were you able to repro?

**Comment by ravipal** [comment]
Had a chat with @v-amyang  and got the issue. The node js express app is defined to use port 3000. But during scaffolding 3001 was used. Hence the app didn't work (both single and compose). After updating the app (myExpressApp1\bin\www) to use 3001. it works.

**Comment by bwateratmsft** [comment]
@ravipal Is there an issue in our scaffolding logic?

**Comment by ravipal** [comment]
No. We take port input from user and we that port.
