### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration for .NET Core 5.0 project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1794]
**OS:** Windows
**Build Version:** [20200326.8](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16781&view=artifacts&type=publishedArtifacts)
**.NET Core SDK:** 5.0.100-preview.1.20155.7

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.

**Expect:**
Run the configuration successfully without any error.

**Actual:**
An error occurs "The pipe program 'docker' exited unexpectedly with code 126".
![image](https://user-images.githubusercontent.com/45614674/77751379-8a702c80-7060-11ea-80d0-7e8003cef7cf.png)

Docker output:
  _Installing the latest .NET Core debugger..._
  > /bin/sh: 1: curl: not found
  > 
  > debian
  > 
  _Debugger installed_

Debug Console:
_Starting: "docker" exec -i console_console_1 /remote_debugger/vsdbg --interpreter=vscode
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/remote_debugger/vsdbg\": stat /remote_debugger/vsdbg: no such file or directory": unknown_

**More Info:**
The debugger installed successfully with alpine image but the debug will be auto-stopped.

**Comment by bwateratmsft** [comment]
Looks like `curl` was removed from the base image. I'll look into this.

**Comment by bwateratmsft** [comment]
The removal was intentional: https://github.com/dotnet/dotnet-docker/issues/1645#issuecomment-581593827

**Comment by bwateratmsft** [comment]
We should be able to use `docker cp` to copy the debugger into the container from the host, and always install on the host.
