### ISSUE TITLE
Update SSH tunneling docs to use Docker context

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1797]
After 1.1.0 with [Docker context support](https://github.com/microsoft/vscode-docker/pull/1790) ships, we should update [SSH tunneling documentation](https://code.visualstudio.com/docs/containers/ssh) and advise users to use Docker context instead of setting `DOCKER_HOST` environment variable explicitly.

With Docker context the user can switch between various Docker engines quickly and apply all configuration settings consistently.

**Comment by bwateratmsft** [comment]
Please note in the docs that an SSH agent is still needed to do SSH tunneling successfully
