### ISSUE TITLE
Jira

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/vscode-docker#1798]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: No .csproj or .fsproj file could be found. You need a C# or F# project file in the workspace to generate Docker files for the selected platform.

Version: 1.0.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
L extension.bundle.js:317:53714
async t.scaffoldNetCore extension.bundle.js:317:54282
async Object.t.scaffold extension.bundle.js:317:83764
async t.configure extension.bundle.js:1:301571
```

</details>

**Comment by bwateratmsft** [comment]
@Dmarch28 Are there any .NET project files in your workspace?

**Comment by Dmarch28** [comment]
Yes a lot, making sales on most I just started to use github and I past up on one post.
sorry about that!!!

**Comment by Dmarch28** [comment]
Right now I'm updating visual studio 2019

**Comment by bwateratmsft** [comment]
I'm not sure I'm following. This extension isn't for Visual Studio, but rather Visual Studio Code.
