### ISSUE TITLE
Support to custom registries

### ISSUE THREAD

**Issue by fsmaia** [microsoft/vscode-docker#18]
Would be nice to have support to different registries (image repositories), like a server list or something related.

**Comment by johnpapa** [comment]
Agreed. I heard this feedback at some recent events in Athens and Oslo. Specifically, some folks wanted to use the docker extension to see repositories in AWS and other registries.

cc @chrisdias and @fiveisprime  as an FYI to our previous discussion

**Comment by StephenWeatherford** [comment]
Tracked in https://github.com/microsoft/vscode-docker/issues/869
