### ISSUE TITLE
Feature request: display only container names in tree view

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/vscode-docker#180]
See screenshot:
![screen shot 2017-11-24 at 21 25 29](https://user-images.githubusercontent.com/8881674/33223307-74558f6a-d15e-11e7-93e7-3177d8426edf.png)

We're using AWS ECS registry so the full image path ```<registry>/<image>:<tag>``` is very long. It's hard to see actual image name without expanding tree view to the right or until hovering the list item.

Ideally there should be an option to either hide registry path or use container name (the one in the ```( )``` ) as tree item label.

Thanks!

**Comment by chrisdias** [comment]
what if we provide an option to truncate the registry path at some number of characters? would that work, or do you want to show the container name?

**Comment by asvetliakov** [comment]
>what if we provide an option to truncate the registry path at some number of characters?

Since the container name is being displayed in the ```()``` brackets after registry too, this would work.

I think it's best to truncate registry in the middle then, i.e. ```account-id.ecr...com/image (name)```. In this case the image name will be clearly visible even when no container name was provided.

**Comment by chrisdias** [comment]
two new config options:

`docker.truncateLongRegistryPaths` defaults to `false`
`docker.truncateMaxLength` defaults to 10, including the `...`

![image](https://user-images.githubusercontent.com/1487073/33526099-b1401cea-d83b-11e7-8406-359a4f818876.png)
