### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 1147046772** [microsoft/vscode-docker#1801]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: To build Docker files you must first open a folder or workspace in VS Code.

Version: 1.0.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.43.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.t.quickPickWorkspaceFolder extension.bundle.js:1:431375
t.buildImage extension.bundle.js:317:94635
extension.bundle.js:317:356931
```

</details>

**Comment by bwateratmsft** [comment]
@1147046772 Can you try opening a folder and doing Docker Build?
