### ISSUE TITLE
Docker extension can't find Docker files ... but they are present.

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-docker#181]
![image](https://user-images.githubusercontent.com/1202528/33225950-91a7950e-d14f-11e7-9c0d-8130ae5f2467.png)

![image](https://user-images.githubusercontent.com/1202528/33225941-5c91788a-d14f-11e7-9b15-b2d441021fbb.png)

**Comment by chrisdias** [comment]
looks like an insiders issue... investigating.

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode/issues/39158

**Comment by chrisdias** [comment]
This is fixed in insiders.

**Comment by johnpapa** [comment]
thanks!
