### ISSUE TITLE
The debugging is auto-stopped when running 'Docker .Net Core Attach (Preview)' configuration with alpine image

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1812]
**OS:** Windows
**Build Version:** [20200401.21](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17137&view=results)
**.NET Core SDK:** 5.0.100-preview.1.20155.7

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Change the image to 5.0-alpine in Dockerfile and right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.

**Expect:**
Run the configuration successfully and it keeps debugging.

**Actual:**
The debugging is auto-stopped.

Docker output:
_Copying the .NET Core debugger to the container...
Debugger copied_

Debug Console:
_Starting: "docker" exec -i mvc_mvc_1 /remote_debugger/vsdbg --interpreter=vscode
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications._

**More Info:**
This issue also reproduces for Console app.

**Comment by bwateratmsft** [comment]
I can reproduce. I'll take a look.

**Comment by bwateratmsft** [comment]
This does _not_ occur on .NET Core 3.1 Alpine containers, so I suspect it has something to do either with the .NET 5 image or the debugger (or both).

**Comment by ravipal** [comment]
F5 (single) isn't starting the application. But in compose, at least the application starts and working but the attach fails. The container log shows the following. I think there is something wrong with the debugger.

C:\vscode\web5.0>docker logs -f 99e3f4145864c0dfcc7cfce10adcedf9d5231d54fb0d19c713cb7b51980948ee
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {0867aee7-c060-4f01-b756-7e2c2071f97f} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by bwateratmsft** [comment]
According to the vsdbg folks, there was a change made in .NET 5.0-preview1 that broke debugging; it is fixed in .NET 5.0-preview2 (available today). I verified that debugging works in both Alpine and not-Alpine .NET 5.0 preview 2 images.

Breaking change: https://github.com/dotnet/runtime/pull/32331
Fixing change: https://github.com/dotnet/runtime/pull/32579
