### ISSUE TITLE
Docker Containers : Restart, doesn't work select key

### ISSUE THREAD

**Issue by risto24** [microsoft/vscode-docker#1813]
I want to select containers using the space key.
But this way, a blank will be entered.

![image](https://user-images.githubusercontent.com/46432541/78312464-d81ff400-758e-11ea-8d76-238f0a3f2dd2.png)

Is there a workaround?

**Comment by bwateratmsft** [comment]
You can move focus to the checkboxes by hitting <kbd>Tab</kbd> twice, and then use <kbd>Space</kbd> to select them. You can also use <kbd>Shift</kbd>+<kbd>Tab</kbd> to move backward to the "Select All" checkbox.

Additionally, at least in VSCode 1.43, I can use arrow keys to move up and down and still use <kbd>Space</kbd> to select items.

**Comment by risto24** [comment]
I see now.
It's working as expected.
Thanks.
