### ISSUE TITLE
The Docker view in the VS Code jumps between local/remote shortly after changing context

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1815]
**OS:** Windows
**Build Version:** [20200401.21](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17137&view=results)

**Repro Steps:**
1. Create an Ubuntu 18.04 LTS machine with SSH access--as a remote machine.
2. Install Docker in this Linux machine.
3. In local machine, install Remote-SSH extension in VS Code local instance.
4. Connect to the remote Ubuntu machine via SSH in VS Code.
5. Switch to the VS Code local instance use 'docker context' command to create a context for connecting to the remote machine:
docker context create --docker "host=ssh://username@machineIP" contextname
6. Switch Docker context to the remote machine and verify that it works from command line:
docker context use contextname
docker ps
docker images
7. Check the Docker view in the VS Code local instance.

**Expect:**
Docker view in the VS Code local instance shows Docker assets on the remote machine.

**Actual:**
Docker view in the VS Code local instance can't show the Docker assets on the remote machine.
![image](https://user-images.githubusercontent.com/45614674/78348597-e2fd7780-75d4-11ea-9d2c-a74fcedc18f8.png)

The context output shows as below:
PS C:\Users\AzureTest> docker context inspect
[
    {
        "Name": "test",
        "Metadata": {},
        "Endpoints": {
            "docker": {
                "Host": "ssh://serene@172.18.3.7",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "C:\\Users\\AzureTest\\.docker\\contexts\\meta\\9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
            "TLSPath": "C:\\Users\\AzureTest\\.docker\\contexts\\tls\\9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
        }
    }
]

**Comment by bwateratmsft** [comment]
@v-ruizh `docker context` does not move back and forth between remote and local VSCode sessions. It is strictly on the local machine, so you cannot do `docker context create` on the local session and then `docker context use` on the remote to use it.

Additionally, we have a 20 second refresh policy; the Docker Explorer window only tries to refresh every 20 seconds, so after doing `docker context use` on the local machine it may still take 20 seconds to start showing the containers/images/etc. from the other context.

**Comment by karolz-ms** [comment]
I will take a look.

**Comment by karolz-ms** [comment]
OK two issues discovered, but none with the product

1. `ssh-agent` was not set up on the client machine. See https://code.visualstudio.com/docs/containers/ssh paragraph 2 for details
2. There is [an issue with ssh-agent that comes with Windows](https://github.com/PowerShell/Win32-OpenSSH/issues/1263) that prevents it from working properly with newer SSH daemons (the one used by @v-ruizh was Ubuntu 19.04). The workaround is to use ECDSA key, not RSA key, for the connection:

```shell
ssh-keygen -t ecdsa -b 521
ssh-add id_ecdsa
```
After adding the corresponding public key (`id_ecdsa.pub`) to `$/.ssh/authorized_keys` on the target machine ([see tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1804)) the VS Code Docker extension correctly reacts to Docker context changes.

**Comment by v-ruizh** [comment]
@karolz-ms Thanks for your guidance. The Docker view in local VS Code instance correctly reacts to Docker context changes. 

But there is an issue after switch back to local context. The docker view in local VS Code instance will move back and forth between remote and local VS Code Docker assets once or twice after use default context, then it will show local Docker assets successfully. Could you help to take a look?

**Docker extension build**: [20200413.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17741&view=results)
**Steps:**
1. Use 'docker context' command to create a context 'test' for connecting to the remote machine.
2. From VS Code local instance terminal, "docker context use test" to switch Docker context to the remote machine. Check the Docker view, it will show remote Docker assets.
3. Switch back to local Docker context with "docker context use default" and check the changes of Docker view.
The docker view in local VS Code instance will move back and forth between remote and local VS Code Docker assets once or twice, then show the local Docker assets successfully.

**Comment by bwateratmsft** [comment]
Hm, that is strange. I expect that when using the terminal to switch it will take a bit of time for the UI to reflect that, but once it switches it should stay switched.

@karolz-ms, if I had to make a guess, I'd say that the 2s refresh rate is too fast, and calls to `dockerode` are stacking up on `await`s, and then finishing out of order. You can expect that localhost calls would return much faster than remote which probably increases this effect.

For example:
1. Call to refresh (remote) starts
1. Context switches to local
1. Call to refresh (local) starts
1. Call to refresh (local) finishes (call from step 3), local resources are displayed
1. Call to refresh (remote) finishes (call from step 1), remote resources are displayed
1. Another call to refresh (local) starts and finishes, local resources are displayed

**Comment by karolz-ms** [comment]
Agreed. There are ways to fix this but I am not sure if it is worth given low severity of the issue.

Good catch though, @v-ruizh , thanks for reporting this!

**Comment by bwateratmsft** [comment]
The clearest way I can think of to fix it is to wrap the Dockerode calls in a `Promise` with a cancellation token, and have said cancellation cause an immediate reject of the `Promise`.

**Comment by karolz-ms** [comment]
That is a good idea, esp. since all the calls to Dockerode go through `callDockerodeXxx` utility methods so the retry logic could be centralized there.

**Comment by bwateratmsft** [comment]
Reopening for 1.2 as discussed in standup.
