### ISSUE TITLE
[Python] Download debugpy and scaffold docker-compose.debug.yaml

### ISSUE THREAD

**Issue by haniamr** [microsoft/vscode-docker#1817]
The scenario is as follows:
- Download `debugpy` from [pypi](https://files.pythonhosted.org/packages/b7/aa/7280d6595710bdc81757025e8515c344d4ca0457d78c92d8d27ecf3a4c44/debugpy-1.0.0b5-py2.py3-none-any.whl) using `pip` and save it under the user profile (plus checking daily if there's a new version or not, same as what we do for netcore)
- Add docker-compose.debug.yaml if the user selected compose, with a volume mapping to the debugger: "`~/debugpy`" (this should work on both Windows and Linux hosts)

**Comment by bwateratmsft** [comment]
Can we also use `debugpy` for single-Dockerfile debugging?
