### ISSUE TITLE
"Did you mean to run dotnet SDK commands?" after adding Docker files

### ISSUE THREAD

**Issue by dracan** [microsoft/vscode-docker#182]
Steps to reproduce ...

* Create a new asp.net project with `dotnet new mvc`
* Open folder in vscode
* Choose `Docker: Add docker files to workspace` from command palette
* Switch to the command line, and run `docker-compose up --build`

Note the following output ...

```
Building dockertest
Step 1/7 : FROM microsoft/aspnetcore:1
 ---> e1f267239f25
Step 2/7 : LABEL Name=dockertest Version=0.0.1
 ---> Using cache
 ---> 6a74f7db70ad
Step 3/7 : ARG source=.
 ---> Using cache
 ---> d41094353ac3
Step 4/7 : WORKDIR /app
 ---> Using cache
 ---> fc0c9d779b0b
Step 5/7 : EXPOSE 3000
 ---> Using cache
 ---> 754baadde60a
Step 6/7 : COPY $source .
 ---> Using cache
 ---> f9bd4a355039
Step 7/7 : ENTRYPOINT dotnet dockertest.dll
 ---> Using cache
 ---> cc61a2187244
Successfully built cc61a2187244
Successfully tagged dockertest:latest
Starting dockertest_dockertest_1 ...
Starting dockertest_dockertest_1 ... done
Attaching to dockertest_dockertest_1
dockertest_1  | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
dockertest_1  |   http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
dockertest_dockertest_1 exited with code 145
```

This is on Docker for Windows. I'm currently on the _Edge_ version (17.11.0-ce-win40 (14328)), but it happened before updating from the stable version too. I also tried it on my work pc which is on the stable version, and got the same issue.

**Comment by dracan** [comment]
Forgot to mention that this is using Linux containers, not Windows containers.

**Comment by dracan** [comment]
So a few things I've noticed. And I don't know if this is just me completely misunderstanding how we should be using this ...

* The `dockertest.dll` was actually `DockerTest.exe`. So it looks like the `Dockerfile` creation isn't picking up the case correctly.
* It defaults to version 1 of the base image. Surely this should now be defaulting to the latest?
* The `$SOURCE` variable was being set to `.`. Shouldn't this be the `publish` folder?

If I change all the above, it then works.

**Comment by dracan** [comment]
Just to clarify - the `Did you mean to run dotnet SDK commands? Please install dotnet SDK from` in my first post was because it couldn't find the `dockertest.exe` - both because of the case sensitivity issue I mentioned in my last comment, and also the incorrect path I mentioned in my last comment.

**Comment by surabhshah** [comment]
Hi @dracan ,

I was facing the same issue as you did and came across a similar issue [here](https://github.com/aspnet/aspnet-docker/issues/322).

In case, you are still stuck with this, would suggest you to go through it, as I was able to resolve the issue by referring to the same.

Regards,
Surabh

**Comment by dracan** [comment]
Hi @surabhshah,

Thanks, but as I mentioned in [this comment above](https://github.com/Microsoft/vscode-docker/issues/182#issuecomment-346990702), it works if I correct the issues I listed. I shouldn't have had to make those changes though - so there's a bug in the vscode docker tooling in that it doesn't use the correct case for the project DLL filename when creating the Dockerfile.

**Comment by bwateratmsft** [comment]
I don't think this issue still exists, so I'm going to resolve it:
![image](https://user-images.githubusercontent.com/36966225/64984145-2a6a2380-d890-11e9-8d30-0110c35b25bc.png)
