### ISSUE TITLE
docker.images.build error - Task to execute is undefined

### ISSUE THREAD

**Issue by jialu98** [microsoft/vscode-docker#1821]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: 5
Error Message: Task to execute is undefined

Version: 1.0.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

**Comment by bwateratmsft** [comment]
Dupe of #1462
