### ISSUE TITLE
Docker Build Image Issue no such file

### ISSUE THREAD

**Issue by Lechus** [microsoft/vscode-docker#1824]
Why VS Code cannot build docker image using solution with ASP.NET Core and Dockerfile created in VS2019?

Dockerfile is inside  project - that works out of the box in VS2019.

In VS Code getting error:
docker build --rm -f "ConsumerAPI\Dockerfile" -t client:dev "ConsumerAPI"
Sending build context to Docker daemon     78MB
Step 1/17 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
 ---> c819eb4381e7
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> 81ee0e578cf6
Step 3/17 : EXPOSE 80
 ---> Using cache
 ---> 8bfc87b301f4
Step 4/17 : EXPOSE 443
 ---> Using cache
 ---> 5f08531c75ed
Step 5/17 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
 ---> fc3ec13a2fac
Step 6/17 : WORKDIR /src
 ---> Using cache
 ---> de5b6bcfe75d
Step 7/17 : COPY ["ConsumerAPI/ConsumerAPI.csproj", "ConsumerAPI/"]
**COPY failed: stat /var/lib/docker/tmp/docker-builder157431713/ConsumerAPI/ConsumerAPI.csproj: no 
such file or directory**

If I move Dockerfile up in directory hierarchy it works.

VS2019, VS Code , docker extension - up2date.

VS2019 command:
`docker build -f "E:\Projects\Consumer\ConsumerAPI\Dockerfile" --force-rm -t consumerapi  "E:\Projects\ReferencedProject"`

VS Code:
`docker build --rm -f "ConsumerAPI\Dockerfile" -t client:dev "ConsumerAPI"`

**Comment by bwateratmsft** [comment]
Can you share your directory structure for `E:\Projects`?

**Comment by Lechus** [comment]
VS2019 - create webapi project. sln file, and project folder with project and Dockerfile (Happy default VS2019).
`..
Consumer
- consumer.csproj
- controlers, startup, program, files etc.
-Dockerfile
.dockerignore
solution.sln`

VS Code - open  folder with sln file.

**Comment by bwateratmsft** [comment]
Thanks, I'll try this out and see if I can figure out what's going on.

**Comment by bwateratmsft** [comment]
I see what's happening. The extension's default behavior is to use the Dockerfile's containing folder as the build context--in this case, `Consumer\ConsumerAPI`. However, Visual Studio 2019 scaffolds Dockerfiles with the _solution_ folder as the build context--in this case, `Consumer`.

There's two ways to solve this!

1. Set the Docker extension setting `docker.imageBuildContextPath` to `.`. You can do this as a user setting, or if you want it specific to this workspace, create a folder `.vscode` in the solution folder, then `settings.json` inside that, and paste this:
```json
{
    "docker.imageBuildContextPath": "."
}
```
2. Use the new [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) features. This can also be a user or workspace setting, and there's a lot you can do with it--more info in those docs. As an example:
```json
{
    "docker.commands.build": "docker build --pull --rm -f \"${dockerfile}\" -t ${tag} ."
}
```

Let me know if either of those workarounds work. I'm going to keep this issue open as we want the experience of jumping between VS and VSCode to be as painless as possible.
