### ISSUE TITLE
Move 'Install Docker...' link from the Docker view to notification

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1826]
Current implementation shows a Install Docker link in Docker View like below. These links will be shown whenever the docker command throws error. It could be either docker is installed but not started or docker is not installed.
![image](https://user-images.githubusercontent.com/1775825/78704649-066c3f00-78c1-11ea-958e-e57a94daa9e8.png)

Identify whether the docker installed or not and show Install Docker link as notification.

**Comment by bwateratmsft** [comment]
IMO we should leave this link here, in addition to the notification.

**Comment by ravipal** [comment]
The main concern is to not show the 'Install Docker...' message in 4 places in Docker View and notification is the right way to show it (per UX review). But once user dismisses the notification they wouldn't see it again until they open a new workspace or explicitly start the command. Lets see what others think.

**Comment by bwateratmsft** [comment]
@BigMorty What do you think? It seems harmless to leave it in the explorer view (even though it's four times), but still add the notification. As Ravi mentioned, if you dismiss the notification then the link in the tree view is the only remaining way until relaunch.

**Comment by bwateratmsft** [comment]
Something I'd like to add--we don't currently have a way to tell the difference between "Docker is not installed" vs. "Docker is installed but not running". I would bet that the majority of the time, it would be the latter case. It would annoy users to show a toast to them suggesting an action that isn't necessary.

**Comment by ravipal** [comment]
If we are going with toast message we must be sure that the docker is not installed. I have some information to identify it and need to test it out.

**Comment by bwateratmsft** [comment]
Just don't involve the CLI, it's horribly slow.

**Comment by BigMorty** [comment]
Agree we need to do this only when we can have more confidence on knowing if Docker Desktop is not installed vs not running.
