### ISSUE TITLE
It keeps installing the Docker Desktop more than 20 mins on Mac

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#1828]
**OS:** Mac
**Build:** [20200407.17](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17457&view=artifacts&type=publishedArtifacts)

**Repro Step:**
1. Make sure the Docker Desktop is uninstalled on Mac.
2. Open the Docker view in VS Code --> Select "Install Docker...".

**Expect:**
Install Docker Desktop successfully.

**Actual:**
Show notification "Opening the Docker Desktop installer..." more than 20 mins and can't continue the installation.
![image](https://user-images.githubusercontent.com/57662131/78773090-46b4e580-79c5-11ea-96e7-cce7d2e2e59c.png)
Output log:
Executing command chmod +x '/var/folders/nx/mz07zpcx35d0ytsmjfxfdkvr0000gn/T/docker_1586337975872_8984_1.dmg' && open '/var/folders/nx/mz07zpcx35d0ytsmjfxfdkvr0000gn/T/docker_1586337975872_8984_1.dmg'

**More Info:**
1. This issue reproduces by selecting command from command palette.
2. This issue does not reproduce on Windows and Linux.

**Comment by bwateratmsft** [comment]
Install is not working because it has to be done interactively.
