### ISSUE TITLE
unable to run docker command in vs code

### ISSUE THREAD

**Issue by shafiyal** [microsoft/vscode-docker#1829]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Command failed: docker login https://iotedgeregistryshafiya.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin
'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.0.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@shafiyal Do you have Docker Desktop installed?
