### ISSUE TITLE
Python Container exits without logs in certain cases

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1831]
When a user does the repro steps below, by default, the container starts and exits immediately without writing any meaningful error logs in the Debug Console.

**Repro Steps**:

- During Add Docker Files to Workspace command, choose Python: Django or Python: Flask and select Port 1000.
- After the lines

```docker
WORKDIR /app
ADD . /app
```
Add in 

```docker
RUN useradd appuser && chown -R appuser /app
USER appuser
```
- Hit F5 to run the container
- Container will start and stop

**Current solution to diagnose this issue**:
Although it's possible to find out what's really happening in the container, it is a pain and the user cannot be expected to know/do these steps mentioned below. 

- Open and modify your launch.json file
- Add "removeContainerAfterDebug": false, above "python" line
- Run your container again
- After it fails, navigate to docker explorer and click view logs 
![image](https://user-images.githubusercontent.com/20650058/78824044-91693a00-7992-11ea-8a9f-f092699f6658.png)

In a Django app, you will see the error:

> Error: You don't have permission to access that port.

In a Flask app, you may see the error:

>self.socket.bind(self.server_address)  
>PermissionError: [Errno 13] Permission denied

This likely means you are exposing a system-port (ports 0 - 1023) while attempting to run as a non-root user. This incompatible configuration is demonstrated in the image above, but there must be an easier way to find this issue.

**Comment by bwateratmsft** [comment]
IMO this is a self-inflicted issue. Our scaffolding will do non-root if all ports are >1023, and root otherwise, so what we scaffold works.

However, there are an infinite number of ways users can alter the Dockerfile to end up with something that doesn't work. We can't possibly be responsible for that.

**Comment by haniamr** [comment]
I think the problem here is that when the exception is thrown (due to the permission issue), it doesn't get written in the debug console. You can still debug and set breakpoints fine, so I don't think it is a startup issue since ptvsd doesn't execute the app process until something attaches to it.

**Comment by bwateratmsft** [comment]
In that case would this be a ptvsd issue? If anything, exceptions outta make it to the debug console.

**Comment by haniamr** [comment]
Might be, I opened an issue over there: https://github.com/microsoft/ptvsd/issues/2117

**Comment by bwateratmsft** [comment]
From that issue, it sounds like data is being written to stderr but Django is terminating itself before stderr is flushed.
