### ISSUE TITLE
Node.js: Investigate using "node-user" by default

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1834]
Investigate using "node-user" in the container by default. Of course, Node ecosystem is huge so this won't work all the time, but probably will most of the time.

Related to #1766.

**Comment by ucheNkadiCode** [comment]
This is necessary for writing our troubleshooting document for VS Code Docker extension

**Comment by bwateratmsft** [comment]
I'd like to hear what @philliphoff thinks. It's almost a certainty that _some_ apps/packages are not going to work as non-root. However, that raises two questions--how common of a problem do we think it will be? Also...do we care? Obviously requiring root permissions is _usually_ a bad idea and I wouldn't feel so badly about being incompatible with some of them.

**Comment by bwateratmsft** [comment]
A fix for this has been released in Docker extension version 1.16.0.
