### ISSUE TITLE
.NET: Investigate creating and using a non-root user by default

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1835]
Investigate creating and using a non-root user in the container by default.

Related to #1766.

**Comment by bwateratmsft** [comment]
Related to #2228 as well.

**Comment by bwateratmsft** [comment]
Moving to 1.9.0 since our .NET plans for that milestone should make this realistic.

**Comment by ucheNkadiCode** [comment]
Just a note: As we move forward with these changes to .NET support (disabling ssl by default) we'll need to add documentation of how a user can add this feature to their Single .NET Core project

**Comment by bwateratmsft** [comment]
Splitting docs out into #2805
