### ISSUE TITLE
suggest application platform when generating dockerfile

### ISSUE THREAD

**Issue by geerligs** [microsoft/vscode-docker#1837]
It would be nice when generating a dockerfile the language of the current workspace (application platform) is detected automatically. This might eliminate the need to select the application platform

**Comment by bwateratmsft** [comment]
@geerligs Do you think the extension should "suggest" it (like, highlight it by default in the quick pick), or should it skip the quick pick completely?

**Comment by geerligs** [comment]
Thanks for your question. I would opt for "suggest" as "highlight it by default in the quick pick".

**Comment by bwateratmsft** [comment]
Related to #3346. I think it's probably best to leave this to Copilot as it's sort of an AI task, determining what platform is being used.
