### ISSUE TITLE
New panel for Docker context

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1844]
Panel that shows Docker contexts and is a sibling of containers, networks etc.
This panel should be at the bottom and collapsed by default
Current context in use is clearly marked (bolded)
Displays context description on hover.
Hookup the use, delete, and inspect context commands to context menu items named the same.

Later this year this panel will also show all shared contexts a user has in DockerHub, assuming they are signed into DockerHub.

**Comment by bwateratmsft** [comment]
One thing about the hover text--it may have accessibility impact, we would want to validate that.

**Comment by karolz-ms** [comment]
Good point. 

The hover thing is a nice-to-have; if we find spending a lot of time on this, we can just drop it.

**Comment by bwateratmsft** [comment]
This is interesting: https://code.visualstudio.com/api/references/vscode-api#TreeItem

They have a `description` property which is rendered less prominently--probably similar to quick pick items' description/detail--that might be a good place for it. Or, it might be a good place for the "currently selected" label.

**Comment by BigMorty** [comment]
After out design session today, here is what the current thinking is:
- Panel will be named "CONTEXTS"
- Panel will be above the Help and Feedback panel
- Panel will collapsed by default (if VS Code offers this)
- Panel will have Gear, Refresh, and Help icons
- Help icon should take user to new help doc that discusses Contexts
- All local contexts will be displayed in flat list (no parent item)
- Items will show Name & Description by default - Docker endpoint will be the other available field
- Items will not have a icon unless it is the active icon and then the plug icon will be displayed
- Gear icon will show Label, Description, Reset settings
- Context menu items will be Inspect & Use in first section and Remove in the second section

**Comment by karolz-ms** [comment]
Thanks @BigMorty! Two questions:

> Help icon should take user to new help doc that discusses Contexts

Do we really need to have a new documentation topic for contexts? Can we just link to [Docker context doc](https://docs.docker.com/engine/context/working-with-contexts/) instead? We really just expose basic operations around contexts, so having a VSCode docs for them seems like a waste of electrons.

> Gear icon will show Label, Description, Reset settings

I assume this is to the user can list context by Description instead of by Name? (in Docker lingo the context has "Name", not "Label"). Do we really need this Gear icon and associated functionality? Can we just populate the item `description` with context Description, like @bwateratmsft [suggested above](https://github.com/microsoft/vscode-docker/issues/1844#issuecomment-611745695)?

**Comment by bwateratmsft** [comment]
I agree with @karolz-ms, I feel like nobody would actually use the gear to change the label / description. I can't honestly see why anybody would want something other than context name as label, context description as description.

**Comment by ravipal** [comment]
Agree on doc - we can reuse  [Docker context doc](https://docs.docker.com/engine/context/working-with-contexts/).

Agree that most of the users will use the default. Having a settings will help user if they want to see 'docker endpoint' in the tree view. Besides this functionality is provided in base class doesn't require much effort to add it.

**Comment by BigMorty** [comment]
I can go either way on the gear/settings. Regarding the help link, I feel like it should go to a Docker Explorer specific page that discusses Contexts. But you are right we probably don't need an entire page for Contexts. Let me think on this a bit and get back to you. you can have it do the standard behavior like the other panels do for now.

**Comment by bwateratmsft** [comment]
If our UI is complicated enough that it _needs_ a doc page, I think we've made a mistake. The UI should be self-explanatory enough that the Docker page is sufficient.
