### ISSUE TITLE
Integrate new container tutorial

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1845]
Have a pseudo-node in the container tree if no containers are present. The pseudo-node, when clicked, launches a web page with VS Code-specific container tutorial.

**Comment by bwateratmsft** [comment]
Should we also keep the current entry? 
![image](https://user-images.githubusercontent.com/36966225/78939502-462e5480-7a82-11ea-8859-200f9ffe74ae.png)

**Comment by karolz-ms** [comment]
I think so, yes. Just change what it says and does.

**Comment by bwateratmsft** [comment]
We can also have both nodes show. Maybe mockup some screenshots to compare?

**Comment by BigMorty** [comment]
I was thinking of showing just the new message and not the existing one, but if folks think it is important to call out that no containers were found we could keep. but I think it would look better with just the new message.

The new message should read "Get started with Docker containers". Let's use the whale icon we use when connected to DockerHub. The link to use is https://aka.ms/getstartedwithdocker.

**Comment by bwateratmsft** [comment]
I think it's really important to keep the existing node.
