### ISSUE TITLE
Grouping containers by Compose invocation

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1846]
Add new grouping option that groups together containers launched by the same `docker-compose up` invocation. This grouping option should be called "Compose". These containers can be identified by a common label called `com.docker.compose.project`

Also add a new group called "Label" that provides the ability to group containers by any label. When selected the user will be prompted in the command palette to enter the name of the label they want to group by.

In both cases the containers should be parented under each distinct label value (i.e. ComposeGroup1, ComposeGroup2, etc.). Containers that don't have the label be parented under an top node named  "Other".

**Comment by bwateratmsft** [comment]
I like this idea. In the group node, we might also be able to provide a 'Compose Down' command, as long as we can find the relevant compose file(s).

**Comment by ravipal** [comment]
We decided to postpone the generic group by any label.

**Comment by ThaDaVos** [comment]
Any progress on the Docker Compose grouping?
Having a group by docker-compose can make things so much easier!

Currently as workaround I'm grouping by network but I would love better Docker-Compose integration

**Comment by bwateratmsft** [comment]
@ThaDaVos This is now released in 1.2.0!
