### ISSUE TITLE
Issues generated when running my Docker Image on VS Code

### ISSUE THREAD

**Issue by philtopher** [microsoft/vscode-docker#1848]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: 1
Error Message: Process exited with code 1

Version: 1.0.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:549589
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:203:13
Pipe.<anonymous> net.js:588:12
```

</details>

**Comment by bwateratmsft** [comment]
@philtopher What platform are you debugging with? .NET Core, Node, Python?

**Comment by philtopher** [comment]
.Net Core using VS Code. I've got extensions enabled. My Docker image was built successfuly but i had to send this issue generated by VS Code.

**Comment by bwateratmsft** [comment]
Thanks @philtopher. We did make changes in the upcoming 1.1 release to provide much more useful error messages than "Process exited with code 1", so that will help.

In the meantime, there's three likely candidates for what process is failing:
1. `dotnet`, and we failed to get the output path of the DLL
2. `dotnet`, and we failed to set up SSL certificates
3. `powershell` (`sh` on Unix), failing to download the VSCode debuggers

Can you confirm if this is successful? Open Command Palette, choose `Run Task`, and choose `docker-run: debug` from the task list

**Comment by philtopher** [comment]
I got only these: 
1. docker: Error response from daemon: invalid volume specification:
2. The terminal process terminated with exit code: 125

I'm using Windows containers.

**Comment by bwateratmsft** [comment]
Aha! You've hit #1735 (already fixed for upcoming 1.1).

You should be able to resolve at least the `invalid volume specification` error, by adding `"os": "Windows"` to your `docker-run: debug` task in `tasks.json`, like this:
```json
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build: debug"
            ],
            "dockerRun": {
                "os": "Windows"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/NetWindows.csproj",
                "enableDebugging": true
            }
        },
```

Let me know if that fixes the invalid volume error, and also see if it fixes the failed F5.

**Comment by philtopher** [comment]
I had the same error message. I then used Ctrl + F5 and i got this on the Debugger Console. 

Starting: "docker" exec -i <my container name>-dev /remote_debugger/vsdbg --interpreter=vscode
Error from pipe program 'docker': Error: No such container: <my docker container> -dev

One thing to note is that i'm using an old Azure Account in my VS Code, i'm not using my active account on VS Code.

**Comment by philtopher** [comment]
This is my launch.json

{
    "configurations": [
        
        {
            "name": "Docker .NET Core Launch",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "netCore": {
                "appProject": "${workspaceFolder}/(my container name).csproj"
            },
            "dockerServerReadyAction": {
                "uriFormat": "%s://localhost:%s/WeatherForecast"
            }
        }
    ]
    
}

**Comment by bwateratmsft** [comment]
Can you share tasks.json?

**Comment by loligans** [comment]
I got this error as well. The problem was due to my `appProject` set to an invalid file/directory. The fix was to use a valid `csproj` file location.

Incorrect App Project location:
```json
"netCore": {
    "appProject": "${workspaceFolder}/Secretum.Identity.Api.csproj"
}
```
Correct App Project location:
```json
"netCore": {
    "appProject": "${workspaceFolder}/Secretum.Identity.Api/Secretum.Identity.Api.csproj"
}
```

**Comment by philtopher** [comment]
> Can you share tasks.json?

I've got my tasks.json

{
    "tasks": [
        {
            "type": "docker-build",
            "label": "docker-build: debug",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "directory name:dev",
                "target": "base",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            },
            "netCore": {
                "appProject": "${workspaceFolder}/directory name.csproj"
            }
        },
        {
            "type": "docker-build",
            "label": "docker-build: release",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "directory name:latest",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            },
            "netCore": {
                "appProject": "${workspaceFolder}/directory name.csproj"
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build: debug"
            ],
            "dockerRun": {},
            "netCore": {
                "appProject": "${workspaceFolder}/directory name.csproj",
                "enableDebugging": true
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: release",
            "dependsOn": [
                "docker-build: release"
            ],
            "dockerRun": {
                "os": "Windows"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/directory name.csproj"
            }
        }
    ]
}

**Comment by bwateratmsft** [comment]
@philtopher can you change the `dockerRun` section of the `docker-run: debug` task to include `"os": "Windows"`? I see you already did it for the `docker-run: release` task.

**Comment by philtopher** [comment]
Ok, thanks.

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
