### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bafang1981** [microsoft/vscode-docker#1853]
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 1.0.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:317:397767
extension.bundle.js:317:397674extension.bundle.js:317:397674
Object.<anonymous> extension.bundle.js:1:442792
extension.bundle.js:1:440768extension.bundle.js:1:440768
n extension.bundle.js:1:440542
Object.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:442710
DockerNetCoreDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:317:397605
extensionHostProcess.js:805:493extensionHostProcess.js:805:493
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps? Do you have a workspace folder open?
