### ISSUE TITLE
Python Dockerfile scaffold should use 3.8-slim-buster image

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1877]
This puts the developer on a specific Debian base and results in a very significant app image size reduction (950 MB --> 210 MB).

**Comment by bwateratmsft** [comment]
Brett suggested `-slim`, not `-slim-buster`.

- Advantage of `-slim`: Upgrading to the next Debian is automatic
- Disadvantage of `-slim`: Upgrading to the next Debian is automatic

**Comment by haniamr** [comment]
> Brett suggested `-slim`, not `-slim-buster`.
> 
> * Advantage of `-slim`: Upgrading to the next Debian is automatic
> * Disadvantage of `-slim`: Upgrading to the next Debian is automatic

He wasn't so fixed on that, he just mentioned that it's what he usually goes to. Since the vote was stronger on `slim-buster`, I'll go with that.
