### ISSUE TITLE
Debugging manage.py not working

### ISSUE THREAD

**Issue by acebot712** [microsoft/vscode-docker#1880]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: string
Error Message: Failed to attach the debugger within the alotted timeout.

Version: 1.0.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.1
Language: en

**Comment by bwateratmsft** [comment]
Sounds like this is probably the same as #1860. @acebot712 Can you take a look at @haniamr's [comment](https://github.com/microsoft/vscode-docker/issues/1860#issuecomment-613613397) on that issue and provide the same info?

Thanks!
