### ISSUE TITLE
Pasting formatted (or previously-formatted) text produces invalid Dockerfile

### ISSUE THREAD

**Issue by ComputerCarl** [microsoft/vscode-docker#1884]
When I copy text from vscode, it shows up as formatted, color-coded, and code-style text in OneNote 2016 -- very pretty.

However, if I take this text and paste it into a `Dockerfile` file,  it produces  unusable code. The vscode Docker extension `build` command fails as well as CLI `docker build`.

Disabling the extension allows me to paste the formatted text without issue. (Edit: The code is still not valid after disabling the extension; only the warnings are gone.)

This is OneNote, first line in `normal`-styling (unformatted?), second was pasted from vscode.
![image](https://user-images.githubusercontent.com/29293242/79674615-6b0b9000-8217-11ea-8473-d17629095ef2.png)

When pasting formatted text, it is invalid. However, I have also tried copying the formatted text into notepad, copying from there, and have still pasted invalid code.
![image](https://user-images.githubusercontent.com/29293242/79675862-1fa5b180-8218-11ea-9cf1-77f83e5a69a7.png)

**Comment by rcjsuen** [comment]
@ComputerCarl Hi, thank you for reporting this.

1. If you copy/paste the file into Notepad and use `docker build` from the command line, does it build?
1. If you paste the content into a Dockerfile in VS Code **with the extension disabled**, does it build?
1. If you paste the content onto this [online Dockerfile editor](https://rcjsuen.github.io/dockerfile-language-service/), do you see any parsing errors?

Thank you for your information.

**Comment by ComputerCarl** [comment]
@rcjsuen The pasted code fails on all accounts (notepad, disabled extension, and online editor). I posted here, because when I disabled the extension, it *appeared* to get better (but still fails).

I even use a program on my Windows 10 PC called "PureText" which is also unable to remove whatever OneNote is doing to this text.

The only way I seem to be able to remove whatever is causing the failed `Dockerfile` is an online text-stripping service (in this case a service called textcleanr). Even copying the formatted text, and re-pasting into OneNote as plain text will fail. I can paste OneNote text snippets into other files, like JS/CSS which will work fine. Very odd.

I am closing the issue here, because I suppose this is a vscode thing. I still welcome any suggestions, but I imagine this is just a strange edge-case.

**Comment by rcjsuen** [comment]
> Edit: add screenshot
> ![image](https://user-images.githubusercontent.com/29293242/79677178-0a815080-8221-11ea-80a3-e5242ad8dabe.png)
> 
> Edit-2: pastebin also strips text. I found the issue using a hex editor. Apparently what is happening is the OneNote is using non-breaking spaces (C2 A0) and vscode is not converting them to regular spaces.

@ComputerCarl Your assessment makes sense based on your provided screenshot. The parser seems to think `FROM node:10.13-alpine` is a single word with no spaces.

**Comment by bwateratmsft** [comment]
I wonder if VSCode provides any options for languages that could control this formatted-pasting? Obviously formatted pasting shouldn't be happening in Dockerfiles...

**Comment by ComputerCarl** [comment]
@bwateratmsft - I found a vscode [extension](https://marketplace.visualstudio.com/items?itemName=ShaneRay.InvisibleCharacterVisualizer) that shows "invisible" characters, but none that would do automatic conversion as of yet.

I don't know why anyone would possibly *want* to use non-breaking spaces, but it certainly does create a difficult-to-diagnose issue. The rather strange part is the code I'm using is pasted from vscode to OneNote (then automatically prettified), copied from OneNote, and then pasted back into vscode. I'm wondering now is some of the JS/CSS/etc I'm pasting from my notes has a bunch of non-breaking spaces in it and what issues this might cause later. 

It seems from the other GitHub issues this may be common in some other Microsoft applications like Excel -- maybe when also using formatting.

**Comment by bwateratmsft** [comment]
@ComputerCarl I've seen similar issues but usually from the special double quotes; often I paste things in Notepad, re-copy, and then paste in VSCode (or vice versa).

**Comment by karolz-ms** [comment]
Non-breaking space should be treated as a whitespace character, just like the regular space. It is not really "formatting". IMO what is described are bugs in Docker CLI *and* in Docker language service.

**Comment by rcjsuen** [comment]
> Non-breaking space should be treated as a whitespace character, just like the regular space. It is not really "formatting". IMO what is described are bugs in Docker CLI _and_ in Docker language service.

If someone does open a bug against the docker CLI about this, please share the link here. Thanks!
