### ISSUE TITLE
Docker intellisense is not working in vscode remote machines 

### ISSUE THREAD

**Issue by ricardosantos9521** [microsoft/vscode-docker#1885]
When the docker extension is installed only in the host machine (e.g. windows) docker intellisense for Dockerfile's only works on the host and don't work in remote machines (e.g. WSL/ssh). If i install the docker extension with the vsix in the remote machine (e.g WSL) it starts working.

If i change extensionKind to workspace it works too.
```json
"remote.extensionKind": {
    "ms-azuretools.vscode-docker": [
        "workspace"
    ]
}
```

**Comment by karolz-ms** [comment]
Sorry, @ricardosantos9521 This is a bug in VS Code that has been lingering for a while 😞 https://github.com/microsoft/vscode/issues/83675

We have documented the workaround [on the Troubleshooting page](https://github.com/microsoft/vscode-docker/wiki/Troubleshooting#the-extension-does-not-find-docker-on-a-remote-machine-failed-to-connect-is-docker-installed-and-running-error)
