### ISSUE TITLE
Show "Getting started" page after installation of extension

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#1895]
This getting started page will help users understand what features/functionality the extension has and should offer next steps and/or shortcuts to features. This should work similar to what the Python extension has done.

**Comment by bwateratmsft** [comment]
This might depend on https://github.com/microsoft/vscode/issues/83451.

**Comment by dbreshears** [comment]
Python team is creating a getting started page experiment, will wait to see the outcome

**Comment by bwateratmsft** [comment]
This change has now been released in 1.8.0.
