### ISSUE TITLE
question : generalized version of providing this for yaml files

### ISSUE THREAD

**Issue by dfinke** [Microsoft/vscode-docker#19]
Hello,

I have a yaml file and would love to provide an editing experience for it in vs code.

I just wanted to check before re-purposing this. Is there a generalized version of this? Where I can supply the "grammar", hints etc an it just plugs in?

Thank you,
Doug

**Comment by PeterJausovec** [comment]
Hi, 

Check the topic here: https://code.visualstudio.com/docs/customization/colorizer on how to do this.

Thanks,
Peter

**Comment by SteveLasker** [comment]
Hi Doug
Are you looking to contribute to the docker language service, or where to get sample code for what we used for your own editing experience?
