### ISSUE TITLE
Docker view shows the local Docker assets after setting the docker machine variables

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1900]
**OS:** Mac
**Extension Version:** [20200421.29](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18158&view=results)
**Regression:** Previous release (1.1.0)

**Steps to reproduce:**
1. Install Virtualbox https://www.virtualbox.org/ and run it.
2. Create a docker-machine using virtualbox with this command:
   docker-machine create --driver=virtualbox name
3. Output your machine's settings with this command
   docker-machine env dev
4. Modify your VS Code settings based on those variables. It'll look something like this:
   "docker.tlsVerify": "1",
   "docker.host": "tcp://192.168.99.102:2376",
   "docker.certPath": "/Users/bys/.docker/machine/machines/name",
   "docker.machineName": "name",
5. Check the Docker assets in Docker view.

**Expect Experience:**
Docker view shows the Docker assets of the docker machine "name".
![Screen Shot 2020-04-22 at 5 29 43 PM](https://user-images.githubusercontent.com/45614674/79968187-5a327700-84c2-11ea-8c3c-6b289a0f0bb5.png)

**Actual Experience:**
Docker view shows the local Docker assets.
![Screen Shot 2020-04-22 at 5 26 22 PM](https://user-images.githubusercontent.com/45614674/79968097-425af300-84c2-11ea-9687-ef3e22d72870.png)

**More info:**
This issue does not reproduce on the previous release build 1.1.0.

**Comment by bwateratmsft** [comment]
Reopening, this is still not working right.
