### ISSUE TITLE
Recommend Docker extension for Python, Node.js, and .NET Core workspaces

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#1903]

**Comment by rspiewak47** [comment]
How about PHP? I'm trying to connect the Xdebug debugger to a PHP container (or the associated Apache container) but getting errors. I'm following the excellent guidance in this article:
 https://www.cloudreach.com/en/resources/blog/containerize-this-how-to-use-php-apache-mysql-within-docker-containers/
with the same approach to separating the PHP code from the Apache server.

**Comment by bwateratmsft** [comment]
@rspiewak47 At the moment we don't have any support specific to PHP (e.g., no scaffolding, no debugging, etc.) but that is being tracked: #752 

Of course, you can still use the [`docker-build`](https://code.visualstudio.com/docs/containers/reference#_docker-build-task) and [`docker-run`](https://code.visualstudio.com/docs/containers/reference#_docker-run-task) tasks and [commands](https://code.visualstudio.com/docs/containers/reference#_command-customization), along with Dockerfile syntax highlighting / linting, as all of those features are language-agnostic.

**Comment by chrisdias** [comment]
fixed. will show up in Insiders tomorrow.

**Comment by EricJizbaMSFT** [comment]
Hey guys I noticed this on Insiders today whenever I open a "package.json" file and I have no idea why I'm being prompted to install Docker? I honestly thought it was a funny mistake on somebody's part 😝, not an intentional change

**Comment by EricJizbaMSFT** [comment]
Feels like maybe you're trying to say "Hey you can convert your Node.js project to use Docker, at which point the Docker extension will be helpful", but I feel like the extension recommendations are usually "Hey you're already using Docker, here's an extension that will be helpful now" (as it should be IMO)

**Comment by chrisdias** [comment]
hmmm not my intention here. should be a "passive" recommendation.  Sorry, I will fix asap.

**Comment by EricJizbaMSFT** [comment]
Ah - yeah a passive recommendation seems reasonable

**Comment by chrisdias** [comment]
if it is both passive and important, it will prompt no matter what.  need to find a separate way to do this.  reverting, will be in Insiders tomorrow.  I dont know yet how to fix for real.

**Comment by chrisdias** [comment]
whoops hit close by mistake.

**Comment by chrisdias** [comment]
fixed properly this time, should be in insiders tomorrow.

**Comment by bwateratmsft** [comment]
@chrisdias What behavior should we expect?

**Comment by chrisdias** [comment]
whenever the user opens a .net like file (.cs, .csproj, etc.), a python file, or Node like file (.js, .ts, package.json) then the Docker extension will be added to the recommended list.  

The user can see these in the "RECOMMENDED" section in the extension viewlet:

![image](https://user-images.githubusercontent.com/1487073/87717581-79f5d600-c765-11ea-9e8d-a77cf0262983.png)

And when the user selects "Show Recommended Extensions" from the Extension Viewlet `...` menu (or types in the query `@recommended` manually):

![image](https://user-images.githubusercontent.com/1487073/87717666-9db91c00-c765-11ea-9a5e-43200b1afe45.png)

**Comment by bwateratmsft** [comment]
This has been implemented.
