### ISSUE TITLE
Starting debugger without project in the editor

### ISSUE THREAD

**Issue by helperweb** [microsoft/vscode-docker#1905]
Does this occur consistently? 
Repro steps:

1. start a empty workspace on vs code
2. press "F5"
3. select "Docker: Debug in Container"

Action: docker-launch
Error type: Error
Error Message: To debug with Docker you must first open a folder or workspace in VS Code.

Version: 1.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:226:318192extension.bundle.js:226:318192
Object.<anonymous> extension.bundle.js:1:494457
extension.bundle.js:1:492288extension.bundle.js:1:492288
s extension.bundle.js:1:491974
Object.callWithTelemetryAndErrorHandling extension.bundle.js:1:494365
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:226:318045
extensionHostProcess.js:805:493extensionHostProcess.js:805:493
```

</details>

**Comment by bwateratmsft** [comment]
@helperweb Do you actually have a workspace open?

**Comment by helperweb** [comment]
Hello @bwateratmsft ,

Yes, I have!

![_1](https://user-images.githubusercontent.com/64093399/80118678-1fcae780-855f-11ea-815a-bdcfc8de34b2.PNG)
![_2](https://user-images.githubusercontent.com/64093399/80118681-20637e00-855f-11ea-8ecb-73297e62d0fe.PNG)

**Comment by bwateratmsft** [comment]
@helperweb You'll need to open a workspace folder (that "Add Folder") button.

**Comment by helperweb** [comment]
@bwateratmsft Hum, ok!

Thank for your help. The problem is solved

Best regards!

![_3](https://user-images.githubusercontent.com/64093399/80121652-f90eb000-8562-11ea-9034-f085ec0dc5f3.PNG)

**Comment by bwateratmsft** [comment]
Glad to help!
