### ISSUE TITLE
Support generating dockerfile for Java App

### ISSUE THREAD

**Issue by kyliel** [Microsoft/vscode-docker#191]
1. Generate a dockerfile for Java App. Now Go, .NET, Nodejs are supported.
2. Optimize dockerfile for typical Java App (e.g. Tomcat and/or Spring is used).

**Comment by kyliel** [comment]
@andxu from Java tooling team will work on it.

**Comment by StephenWeatherford** [comment]
@kyliel This was implemented a while ago.  Please give it a spin.  Thanks.

**Comment by kyliel** [comment]
Yes, confirmed. This was implemented. I love this feature. Thank  you.
