### ISSUE TITLE
Logging in into docker hub

### ISSUE THREAD

**Issue by divyaksh-shukla** [microsoft/vscode-docker#1911]
Does this occur consistently? Yes
Repro steps:
Create a new account in docker hub and try to connect it using the tool

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.1.0
OS: linux (Manjaro)
OS Release: 4.19.116-1-MANJARO
Product: Code - OSS
Product Version: 1.44.1
Language: en

**Comment by bwateratmsft** [comment]
Duplicate of #722

**Comment by divyaksh-shukla** [comment]
Hey sorry for a creating a duplicate issue. I thought I was working on kde and did not use gnome-keyring so I thought this would be a separate issue.

Thanks
