### ISSUE TITLE
Feature: docker run with options

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode-docker#1912]
Extend docker run menu item with run options:
**--name !!!** to label running image
--- network
-- background
...
etc.
Actual:
there are only 2 options: run and run interactively. Terminal command completion helps a little. 
Expected:
all docker run options can be defined
Link to Docker run reference is desired
 (https://docs.docker.com/engine/reference/commandline/run/) although it is a long reading

**Comment by bwateratmsft** [comment]
This is possible today. For intermediate use cases, [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) is sufficient; for more advanced cases the [`docker-run`](https://code.visualstudio.com/docs/containers/reference#_docker-run-task) task or a generic shell task should be used.
