### ISSUE TITLE
Docker installer fails to download

### ISSUE THREAD

**Issue by yunanmr** [microsoft/vscode-docker#1913]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: Client network socket disconnected before secure TLS connection was established

Version: 1.1.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
connResetException errors.js:559:14
TLSSocket.onConnectEnd _tls_wrap.js:1357:19
Object.onceWrapper events.js:291:20
TLSSocket.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by bwateratmsft** [comment]
@ravipal Can you take a look at this one? I suspect that something prevented the installer download.
