### ISSUE TITLE
docker install failed

### ISSUE THREAD

**Issue by HisakaKoji** [microsoft/vscode-docker#1917]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: ECONNRESET
Error Message: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3080

Version: 1.1.0
OS: win32
OS Release: 6.3.9600
Product: Visual Studio Code
Product Version: 1.44.2
Language: ja

<details>
<summary>Call Stack</summary>

```
ClientRequest.onError extension.bundle.js:225:112594
Object.onceWrapper events.js:291:20
ClientRequest.emit events.js:208:15
Socket.socketErrorListener _http_client.js:399:9
Socket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by bwateratmsft** [comment]
This looks very similar to #1913. I'll mark this as a dupe since in general both are network connectivity problems.
