### ISSUE TITLE
Pressing "ESC" next to "Connect Registry..." step can't cancel all operation

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1918]
**OS:** Windows
**Build Version:** [20200427.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18373&view=results)

**Repro Steps:**
1. F1->Docker Images: Push->Select one image->Connect Registry...
2. It prompt you to select the provider for the registry.
![image](https://user-images.githubusercontent.com/45614674/80468979-82aeeb00-8972-11ea-9bfb-4d3614c7d7fd.png)
3. Press "ESC".

**Expect:**
Pressing "ESC" will cancel all operation.

**Actual:**
Pressing "ESC" can't cancel all operation but back to the previous step.
![image](https://user-images.githubusercontent.com/45614674/80468437-c1907100-8971-11ea-8758-aa188d0a8782.png)

**Comment by bwateratmsft** [comment]
I'm not able to reproduce this on Windows with VSCode 1.44.2. @v-ruizh what VSCode version did you test with?

**Comment by v-ruizh** [comment]
@bwateratmsft I used VS Code Insider 1.45.0.
![image](https://user-images.githubusercontent.com/45614674/80554508-0367f880-8a00-11ea-987b-d0ba7bcc21f7.png)

**Comment by bwateratmsft** [comment]
Ah, I got it to reproduce. This behavior is intentional, the tree item picker is a "wizard", so <kbd>Esc</kbd> does a "Back" operation instead of a "Cancel". We want to actually introduce that in more places.
