### ISSUE TITLE
Support for Dockerfile.some-env

### ISSUE THREAD

**Issue by maxime1992** [microsoft/vscode-docker#192]
Since Docker 1.8 we can do something like that in order to have multiple Dockerfile in the same folder:

```
docker build -f Dockerfile.db .
docker build -f Dockerfile.web .
```

See https://stackoverflow.com/a/32108873/2398593

With VSC, we loose intellisense within a file `Dockerfile.something` file.

**Comment by kamcma** [comment]
If you add the following to your VSCode settings, you should get it back:
```json
"files.associations": {
    "[Dd]ockerfile*": "dockerfile",
    "docker-compose*": "yaml"
}
```
For the Dockerfile entry, I'm getting IntelliSense and file icons, but the docker-compose entry isn't giving me file icons for some reason.

**Comment by abbas001** [comment]
Thanks its working.

**Comment by bwateratmsft** [comment]
I think this scenario is entirely covered by #102, so I'll resolve this as duplicate.
