### ISSUE TITLE
Error type: ENOENT

### ISSUE THREAD

**Issue by paulsd2020** [microsoft/vscode-docker#1920]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.networks.create
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 1.1.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1056:14
```

</details>

**Comment by bwateratmsft** [comment]
@paulsd2020 Is Docker running?
