### ISSUE TITLE
An error occurs when executing Docker related actions

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1925]
**OS:** Windows
**Build Version:** [20200428.22](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18467&view=results)

**Simple Repro Steps:**
From Docker images view, right click one image and execute "Run" action.
![image](https://user-images.githubusercontent.com/45614674/80583916-7e063780-8a43-11ea-93c9-657506f56464.png)

**Repro Steps:**
1. Create a folder.
2. Open this folder in VS Code Insiders.
3. F1->Docker: Add Docker Files to workspace...->Node.js->Yes to create compose files->Accept default port 3000.

**Expect:**
Add Docker files successfully without any error.

**Actual:**
Add Docker files with an error.
![image](https://user-images.githubusercontent.com/45614674/80581582-efdc8200-8a3f-11ea-9e34-a329c9ab8bcc.png)
Error Text:
_Command 'Docker: Add Docker Files to Workspace...' resulted in an error (Cannot read property 'length' of undefined)_

**Comment by bwateratmsft** [comment]
I can reproduce but I can't get it to give me the error stack...

**Comment by bwateratmsft** [comment]
Got it. This is a regression from `vscode-extension-telemetry`: https://github.com/microsoft/vscode-extension-telemetry/issues/44

**Comment by ravipal** [comment]
I will revert the telemetry change until vscode-extension-telemetry is fixed.

**Comment by bwateratmsft** [comment]
I'll mark this as fixed via #1930. In #1934 we will move back to a higher version.
