### ISSUE TITLE
Docker installer fails to run

### ISSUE THREAD

**Issue by U31664** [microsoft/vscode-docker#1926]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: 1
Error Message: Process '"C:\Users\u31664\AppData\Local\Temp\docker_1588165...' exited with code 1
Error: The system cannot execute the specified program.

Version: 1.1.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:477087
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
Similar to #1913. @ravipal we should capture errors for this as well (installation failure).
