### ISSUE TITLE
[feature request] Consider checking best practices

### ISSUE THREAD

**Issue by bnkamalesh** [microsoft/vscode-docker#1928]
Docker file recommends certain best practices as mentioned here https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

There's a different extension which does this (https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint). We should probably consider adding to this extension as well.

**Comment by bwateratmsft** [comment]
@rcjsuen I think this would involve the language server.

**Comment by rcjsuen** [comment]
> @rcjsuen I think this would involve the language server.

@bwateratmsft Correct.

> @rcjsuen I didn't test very thoroughly but it seems like the language server and the [hadolint](https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint) extension get along. It seems like the right solution is for users to install it if they want this feature, rather than for us to try to duplicate it.

I think that makes sense. If anyone is interested in suggesting specific additions, an issue can be opened in the [rcjsuen/dockerfile-utils repository](https://github.com/rcjsuen/dockerfile-utils).
