### ISSUE TITLE
 DOCKER_CONTENT_TRUST_SERVER

### ISSUE THREAD

**Issue by NA3** [microsoft/vscode-docker#1929]
when i push an image with le left click menu
this open a new terminal and dont ask for the passphrase to sign with notary
if i add :

- export DOCKER_CONTENT_TRUST_SERVER=https://*******
- export DOCKER_CONTENT_TRUST=1

on my .zshrc it will work 
can we give this variable on the module option?
Regard

**Comment by bwateratmsft** [comment]
You can add this to your `settings.json`:

```json
    "terminal.integrated.env.linux": {
        "DOCKER_CONTENT_TRUST_SERVER": "https://...",
        "DOCKER_CONTENT_TRUST": "1"
    },
```

The options for other OS's are `'terminal.integrated.env.windows'` and `'terminal.integrated.env.osx'`.

Is that sufficient?

**Comment by NA3** [comment]
thanks.
Regards.
