### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by faisal6621** [microsoft/vscode-docker#1937]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.1.0`
- OS Version: `Linux x64 5.3.0-51-generic`
- VSCode version: `1.44.2`

[ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-docker/files/4567557/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@faisal6621 does this happen frequently or was this an isolated instance? We made some substantial performance improvements in 1.1.0 (#1804). Our data shows that code loading time dropped by about 30%, and activation time by about 90%, for an overall improvement of about 60%--so we know it's working.

Unfortunately, webpack renders the CPU profile pretty unhelpful 😞

**Comment by faisal6621** [comment]
Hi @bwateratmsft,

This is the first time I had this issue. I am not sure what else information I can provide you at this time.

**Comment by bwateratmsft** [comment]
@faisal6621 It may have just been a fluke, in that case. I'll close this one for now, but please let us know if it keeps occurring!
