### ISSUE TITLE
Add support for GitHub pacakges registry

### ISSUE THREAD

**Issue by assapir** [microsoft/vscode-docker#1938]
I couldn't found an API docs for that. The thing I did found is that for getting a docker manifest it should be in the form of:
`https://docker.pkg.github.com/v2/{owber}/{repo}/{container}/manifests/{tag}`, and it's always require authentication (basic) with GitHub username and token

**Comment by bwateratmsft** [comment]
GitHub is tracked on #869.

**Comment by assapir** [comment]
thanks. I am trying to implement this.

**Comment by BigMorty** [comment]
@assapir - Before you start on this effort I want to let you know we are in the midst of changing how registries will get added to the Docker extension going forward. Our design is not complete but we expect it to be soon. We don't plan to approve PR's for the current method of adding registries so please wait and use the new method once it is ready. Thanks!

**Comment by assapir** [comment]
Hey, thanks for the heads-up. Any ETA?

**Comment by assapir** [comment]
Also, I found out that it can be used with basic auth and also support the `tags` endpoints

**Comment by bwateratmsft** [comment]
The critical thing is that it does not support the `_catalog` endpoint (which they're aware of--we've filed a request to do so).

`_catalog` is for listing repositories. Obviously, GitHub cannot list _all_ repositories; it's a monolithic registry and there would be thousands of results. However, the [API spec](https://docs.docker.com/registry/spec/api/#listing-repositories) addresses this:
> Some registries may opt to provide a full catalog output [or] **limit it based on the user’s access level...**

The right way for GitHub to implement `_catalog` would be to show a subset of interesting repositories--probably only those they have push access to. Docker Hub is in the same boat--no `_catalog` endpoint, but identity could be used as a hint to what should be shown. Each of those registries needs to decide for themselves what is the right list to show, but IMO it would be possible for them to make the change.

**Comment by assapir** [comment]
Yeah, I took a look on the docker hub connector, and I am trying to implement something similar, at least get every images for a specific repo, which is what I am trying to do

**Comment by BigMorty** [comment]
No ETA for implementation, need to finalize design which I hope to do in the next week or two.

**Comment by assapir** [comment]
Thanks!
