### ISSUE TITLE
Pop up an error "e.substr is not a function" when executing "Open in Browser" for a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1943]
**OS:** All
**Build Version:** [20200505.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18767&view=results)

**Repro Steps:**

1. From the command-line, type: docker pull registry
2. Image--> Right click "registry"--> Run
3. Container--> Right click "registry: latest"--> Open in browser

**Expect:**
Succeed to execute "Open in Browser" for this running container.

**Actual:**
Pop up an error message: Error running command vscode-docker.container.browse: e.substr is not a function.
![image](https://user-images.githubusercontent.com/62053665/81167388-b79cec80-8fc7-11ea-9f64-ec0c3192a071.png)

**Comment by bwateratmsft** [comment]
I am able to reproduce, though the browser still opens.

**Comment by bwateratmsft** [comment]
Unfortunately this error does not occur during debugging, even with telemetry enabled, unlike last time...

**Comment by bwateratmsft** [comment]
Found the root cause, it happens due to https://github.com/microsoft/vscode-extension-telemetry/issues/45. I'm going to change our code to give a string instead of an array.
