### ISSUE TITLE
compose up command customization with no match produces wrong command

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1954]
By default the compose up command runs the command
`docker-compose -f "docker-compose.yml" up -d --build`

But when a command customization is provided with no match, it suppose to use the default command same as above. But it runs the below command (note the location of up) which is not valid.
`docker-compose up -f "docker-compose.yml" -d --build`

**Comment by bwateratmsft** [comment]
We talked in water cooler, if we take another fix (e.g. for #1958) we'll include this one as well (so as to avoid needing to branch), otherwise it will wait until 1.3.0.

**Comment by bwateratmsft** [comment]
The fix for this is now released in 1.3.0.
