### ISSUE TITLE
installing docker extension to ssh remote not possible

### ISSUE THREAD

**Issue by nickbroon** [microsoft/vscode-docker#1955]
This comment: https://github.com/microsoft/vscode-docker/issues/646#issuecomment-542889588 suggests that it should be possible to install the extension to a remote ssh host.

I do not see this options. (see attached screenshot).

![Screenshot 2020-05-08 at 00 11 33](https://user-images.githubusercontent.com/1462531/81353432-f5ca0700-90c0-11ea-9054-713319991bf2.png)

Is there some additional configuration that's needed first?

**Comment by karolz-ms** [comment]
No, it is a bug in VSCode, but [there is a workaround](https://github.com/microsoft/vscode-docker/wiki/Troubleshooting#the-extension-does-not-find-docker-on-a-remote-machine-failed-to-connect-is-docker-installed-and-running-error) and the fix has just been submitted, so it should appear in the next VSCode release. Sorry!

**Comment by nickbroon** [comment]
Fab, thanks!
Your workaround: https://github.com/microsoft/vscode-docker/issues/1582#issuecomment-578882428 fixed the issues for me.
