### ISSUE TITLE
Error occurs when building image in container registry from VS code

### ISSUE THREAD

**Issue by aliciayuting** [microsoft/vscode-docker#1957]
I was trying to use VS code to build image in container registry, but see this image in the output. It would be great if someone could provide some insights!
Thanks in advance.

The issue text was copied to the clipboard.  Please paste it into this window.Setting up temp file with 'sourceArchivexxxx.tar.gz'
   Sending source code to temp file
   Getting build source upload URL
   Getting blob info from upload URL
   Creating blob service
   Creating block blob
Uploaded source code to /......../sourceArchivexxxx.tar.gz
Set up run request
Error: Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name '.devcontainer:{{.Run.ID}}' is invalid. 
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
Please refer to docs for more information on using image name and tag:  https://aka.ms//az-acr-build

**Comment by bwateratmsft** [comment]
@aliciayuting The aka.ms link you shared doesn't seem to be valid, can you show what steps you were following?
