### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": unknown.

### ISSUE THREAD

**Issue by chaoskidneo77** [microsoft/vscode-docker#1963]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-attach
Error type: NoResouceFoundError
Error Message: No running containers are available to attach.

Version: 1.1.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
ContainersTreeItem.<anonymous> extension.bundle.js:1:769337
fulfilled extension.bundle.js:1:763138
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
Can you try restarting Docker Desktop?

**Comment by PavelSosin-320** [comment]
Could you execute docker ps --all  before  and after the restart, i.e. "Docker is running" appears on the Docker setting screen? Do you see some exited containers?

**Comment by chaoskidneo77** [comment]
Restart dockers error gone
