### ISSUE TITLE
When doing Context > Use in explorer view, takes 20s for "Connected" icon to move

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1965]
1. Create a Docker context
1. In Explorer view, right click it, "Use"

Expected:
"Connected" icon should move quickly

Actual:
"Connected" icon takes 20s to move over, long after the containers/images/etc. views are already refreshed with the new context

![image](https://user-images.githubusercontent.com/36966225/81585974-e4178680-9382-11ea-904f-150e451cdf3a.png)

**Comment by bwateratmsft** [comment]
We should make our context->use command immediately change the icon.

**Comment by ravipal** [comment]
After context switch, we do refresh the context tree, so user don't have to wait for the refresh interval. I can't repro this issue using my contexts. @bwateratmsft can you repro this consistently? Does this happen only when you switch to a specific context. Also how long does the command 'docker context ls' takes when you run from CLI

**Comment by karolz-ms** [comment]
I have seen this. I suspect the call to refresh context tree is queued behind calls to refresh other panes. This is esp. possible if default 2-sec refresh period was retained when switching to remote context.

Instead of expediting the panel refresh we should just change the view model immediately to indicate the new active context.

**Comment by ravipal** [comment]
Added some traces to debug the issue and it seems like sometimes the command `docker context use` is not instantaneous. In my machine most of the time it completes within a second and sometime it takes 8 seconds.
I don't think updating the view model would solve the delay, if the context switch command is taking long time. It could improve a bit and don't have to wait for the actual refresh.

**Comment by bwateratmsft** [comment]
Why would updating the view model not work?

**Comment by karolz-ms** [comment]
The context switch may indeed take a long time to complete. Consider having a progress indicator while `docker context use` command is running. Once it is complete, we should update the view model to indicate the new context in use.

**Comment by bwateratmsft** [comment]
I know for at least _some_ parts of the whole operation we have a progress indicator above the Contexts panel, but it seemed to be a little flickery. That said, above the contexts panel isn't very visible, so I'd like to have a progress notification for as long as it takes to get the context switched. When the switching operation finishes, we can update the view model to show the new "Current" node, and the containers/images/etc. views will automatically refresh within 2 seconds.

**Comment by ravipal** [comment]
I sent a private bit for you to try. The new behavior is
1. When context switch is in progress, no new auto refresh will be triggered.
2. A progress icon will be shown on the context that is being switched to and the description will say 'Using...'

**Comment by bwateratmsft** [comment]
@ravipal @BigMorty In order to get this into 1.2.1 we will need to dual-checkin. I'll create a `rel/1.2.1` branch.

**Comment by BigMorty** [comment]
We should definitely get this into 1.2.1.

**Comment by bwateratmsft** [comment]
Fix released in 1.2.1.
