### ISSUE TITLE
Collapse some Explorer tree views by default

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1966]
**OS:** Windows
**Build Version:** 20200511.5

**Repro Steps:**
Navigate to Docker view->click on context or "HELP AND FEEDBACK" items

**Actual:**
The Containers view toolbar is hidden. Click on the blank container view, the containers show but not show the Container view toolbar. Also can't show the "HELP AND FEEDBACK" view.
![image](https://user-images.githubusercontent.com/45614674/81634691-0a502b80-9442-11ea-92de-eafaf6a7e6a9.png)
 
**Suggestion:**
We can check containers or help view by collapse several views. It's convenient to check all items if add a Scrollbar for the Docker view.

**Comment by bwateratmsft** [comment]
Ultimately we'd like to collapse Help & Feedback by default, along with probably Contexts, Networks, and Volumes. Unfortunately that feature is not available externally at this time.

@philliphoff @ravipal Did we file/find an issue on VSCode to expose that functionality?

**Comment by dbreshears** [comment]
We should collapse the panes but need to wait for support in VSCode

**Comment by philliphoff** [comment]
VS Code 1.48 now adds an initial `visibility` property in `package.json` for tree views, allowing them to be expanded, collapsed, or hidden by default for any given workspace.  (Any changes the user then makes to the state of the tree view is persisted for that workspace.)    This should unblock this scenario.

**Comment by BigMorty** [comment]
Please collapse Networks, Volumes, and Contexts by default

**Comment by bwateratmsft** [comment]
@philliphoff Do you know how sticky that initial visibility is? Does it only persist until the user expands / collapses it once or will those views be collapsed every time they reinit?

**Comment by philliphoff** [comment]
@bwateratmsft The defaults are supposed to be applied per-workspace.  Once the user's made a change, that change is persisted and used from that point on (across sessions of that workspace).
