### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by supernovaslc** [microsoft/vscode-docker#1967]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '/home/quang/Projects/WebAPI/ReactAPI2/package.json'

Version: 1.1.0
OS: linux
OS Release: 5.3.0-51-generic
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

**Comment by bwateratmsft** [comment]
@supernovaslc Does the file it's mentioning exist?
