### ISSUE TITLE
Cannot use personal access token to connect to GitLab

### ISSUE THREAD

**Issue by tecandrew** [microsoft/vscode-docker#1968]
Issue Type: <b>Bug</b>

1. Create personal access tokon on GitLab (with API access)
2. Add Gitlab registry provider
3. Use Gitlab username (not email) when prompted
4. Login with token

Extension version: 1.1.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.4.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2764)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (0.30GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by niikoo** [comment]
Same problem here. It returns 401

**Comment by M-Whitaker** [comment]
Same issue too. Is there a work around known for this?

**Comment by UNRULYEON** [comment]
Logging in returns 400 for me.

Extension version: 1.8.1
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

**Comment by mvaschetto** [comment]
I get error code 400 too, using gitlab username or email with gitlab access token 

Extension version: v1.9.0
VS Code version: Code 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64
OS version: Debian buster kernel 4.19.0-12-amd64

**Comment by bwateratmsft** [comment]
Marking this for re-triage, and making this a bug instead of enhancement. OAuth is no longer realistically an option since it now requires a client app ID and secret, so personal or project access tokens are basically the only option. Using GitLab is blocked until we implement this.

**Comment by bwateratmsft** [comment]
This fix is now released in Docker extension version 1.10.0.
