### ISSUE TITLE
Disable tips during write Dockerfile

### ISSUE THREAD

**Issue by stefanocog** [Microsoft/vscode-docker#197]
It's possibile to disable tips during typing code into Dockerfile? ...they are very annoying

**Comment by rcjsuen** [comment]
@stefanocog I think you are encountering #150?

**Comment by stefanocog** [comment]
yes...so it can't disable...

**Comment by rcjsuen** [comment]
@stefanocog Try disabling it via the suggestion Chris posted [here](https://github.com/Microsoft/vscode-docker/issues/150#issuecomment-356749649).
