### ISSUE TITLE
Add GitLab Groups to list of supported registry providers

### ISSUE THREAD

**Issue by tecandrew** [microsoft/vscode-docker#1970]
Issue Type: <b>Feature Request</b>

When attempting  to log into Gitlab I am prompted to enter my username and password (token) with no choice to connect to a specific group/registry within GitLab.

Would be great if I were given a choice to connect when GitLab group to connect to (to see only those specific docker containers).

Extension version: 1.1.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.4.0-29-generic snap

---
This possibly could be tied to #1968. From my experience, GitLab structures "users" and "groups" a bit oddly when it comes to logins and authorizations. 

[Gitlab Workflow](https://marketplace.visualstudio.com/items?itemName=fatihacet.gitlab-workflow) extension mandates the explicit URL of the domain to connect to (`https://gitlab.com/<username>` to use **user** registries/repos/pipelines) when attempting to log in. If `https://gitlab.com/` is used when logging in nothing connects (I'm assuming a 401 error).

**Comment by bwateratmsft** [comment]
Moving to #869
