### ISSUE TITLE
issue noticed in creating dockerfile

### ISSUE THREAD

**Issue by splunkdevabhi** [microsoft/vscode-docker#1981]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open '/Users/abhishekshukla/Desktop/SplunkUG/package.json'

Version: 1.2.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

**Comment by bwateratmsft** [comment]
@splunkdevabhi does the referenced file exist?
