### ISSUE TITLE
Error logging in to Docker Hub

### ISSUE THREAD

**Issue by will-chow** [microsoft/vscode-docker#1985]
Does this occur consistently?  Yes
Repro steps:

1.  Docker > REGISTRIES > Connect Registry...
2. Select provider for your registry = Docker Hub
3. Enter your Docker ID
4. Enter your password
   

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The user name or passphrase you entered is not correct.

Version: 1.2.0
OS: darwin
OS Release: 17.7.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by bwateratmsft** [comment]
Are you sure you have the correct username and password?

**Comment by will-chow** [comment]
Issue was the Keychain Access app on MacOS - i had to lock and unlock the login function.  I was able to login to the Docker Hub registry after.  Appreciate your help.  Thanks.
