### ISSUE TITLE
Change the context menu from "Push" to "Push..." for Docker images

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1987]
**OS:** All
**Build Version:** [20200516.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19576&view=results)

**Repro Steps:**
Right click one image in Docker Images view and check the context menu push.

**Expect:**
The context menu shows "Push...".

**Actual:**
The context menu shows "Push".
![image](https://user-images.githubusercontent.com/45614674/82188173-0cbdf400-9920-11ea-8b10-c3575ea4b1ca.png)

**Comment by bwateratmsft** [comment]
Yes, we should change this. The convention in the past has been to use "..." when there will be prompts beyond just the context menu click (e.g. like "Tag..." which prompts for tag)
