### ISSUE TITLE
not fund file or directory

### ISSUE THREAD

**Issue by BrutyLi** [microsoft/vscode-docker#1988]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.buildImage
Error type: ESOCKETTIMEDOUT
Error Message: ESOCKETTIMEDOUT

Version: 1.2.0
OS: linux
OS Release: 5.6.0-kali1-amd64
Product: Visual Studio Code
Product Version: 1.45.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:201:12902
Object.onceWrapper events.js:291:20
ClientRequest.emit events.js:203:13
TLSSocket.emitRequestTimeout _http_client.js:680:40
Object.onceWrapper events.js:291:20
TLSSocket.emit events.js:203:13
TLSSocket.Socket._onTimeout net.js:434:8
listOnTimeout timers.js:531:17
processTimers timers.js:475:7
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps?
