### ISSUE TITLE
How can I pass --build-arg when running "build image" command

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-docker#199]
I have a Dockerfile with ARG variables. And I would like to use the "build image" command in the extension to build image. But it seems there is no way to pass the args. The docker command line support this through "--build-arg".

**Comment by chrisdias** [comment]
Would a `docker compose build` command be sufficient?  you could simply define all of the build args in the docker-compose.yml (see [docker-compose args docs](https://docs.docker.com/compose/compose-file/#args))

**Comment by adashen** [comment]
Yes docker compose build could solve the problem. However it needs another file created and edited. And in my scenario, I just want to build a image, so the support on build docker file is a lightweight way

**Comment by chrisdias** [comment]
If we were to add this to `docker build`, how would you suggest the experience works? Does `docker build` always prompt for arguments? That seem like an extra step for folks that do not pass arguments to build. How many arguments do you want to pass? Would you want one big text input or multiple prompts? etc.

You can run a command in VS Code to generate a `docker-compose` file for you, then you can probably edit it and forget it.  Press `F1` and then choose `Docker: Add docker files to workspace`. This will generate a `docker-compose.yml` file, a `docker-compose.debug.yml` (for debugging), a `Dockerfile`, and a `.dockerignore` file.

**Comment by chrisdias** [comment]
Closing this due to lack of a response (sorry).  If using `docker-compose` isn't sufficient, please let me know and I'll reopen it.
