### ISSUE TITLE
The deleted docker-compose.yml flashes quickly when generating a new docker compose file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1994]
**OS:** Windows
**Build Version:** [20200518.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19626&view=results)

**Repro Steps:**
1. Open an empty folder in VS Code.
2. F1->Docker: Add Docker Files to Workspace...->Node.js->Yes to include Docker compose files->3000.
3. Check the content for the original docker-compose.yml file.
4. Delete all Docker related files from this folder.
5. Immediately, F1->Docker: Add Docker Compose Files to Workspace...

**Expect:**
A sample docker-compose.yml file will be generated.

**Actual:**
The deleted docker.compose.yml flashes quickly then generate a sample docker-compose.yml file.

**Comment by bwateratmsft** [comment]
Most likely this is a VSCode bug relating to the in-memory caching of file contents. In any case the severity is low.

**Comment by dbreshears** [comment]
This is an external VSCode issue but P3 so closing
