### ISSUE TITLE
No notification pops up if use the context by context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1995]
**OS:** Windows
**Build Version:** [20200518.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19626&view=results)

**Repro Steps:**
Docker context view->Right click one context and select 'Use'

**Expect:**
The new context have the plug icon and there is a notification like below.
![image](https://user-images.githubusercontent.com/45614674/82308676-b40c5b00-99f4-11ea-86c4-dc215a6c4c00.png)

**Actual:**
The new context have the plug icon but there is no notification.

**More Info:**
The notification pops up if use the context by F1->Docker Contexts: Use.

**Comment by bwateratmsft** [comment]
@ravipal This is intentional right?

**Comment by ravipal** [comment]
Yes, this is the new behavior when the context panel it used, which shows the plug icon to indicate the switch. But the notification will still show up when invoking the command using command palette
