### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1996]
**OS:** Windows
**Build Version:** [20200518.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19626&view=results)
**.NET Core SDK:** **3.1.202**

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.

**Expect:**
Run the configuration successfully without any error.

**Actual:**
An error occurs "The pipe program 'docker' exited unexpectedly with code 126".
![image](https://user-images.githubusercontent.com/45614674/82310991-b15f3500-99f7-11ea-8df2-2ff219ccc93f.png)

Debug Console:
Starting: "docker" exec -i mvc_mvc_1 \remote_debugger\vsdbg --interpreter=vscode
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"\\\\remote_debugger\\\\vsdbg\": executable file not found in $PATH": unknown

Docker output:
Acquiring the latest .NET Core debugger...
> Executing: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\AzureTest\.vsdbg\GetVsDbg.ps1" -Version latest -RuntimeID linux-x64 -InstallPath "C:\Users\AzureTest\.vsdbg\linux-x64\latest" <
Info: Using vsdbg version '16.6.20415.1'
Info: Using Runtime ID 'linux-x64'
Info: Successfully installed vsdbg at 'C:\Users\AzureTest\.vsdbg\linux-x64\latest'
Debugger acquired.
Acquiring the latest .NET Core debugger...
> Executing: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\AzureTest\.vsdbg\GetVsDbg.ps1" -Version latest -RuntimeID linux-musl-x64 -InstallPath "C:\Users\AzureTest\.vsdbg\linux-musl-x64\latest" <
Info: Using vsdbg version '16.6.20415.1'
Info: Using Runtime ID 'linux-musl-x64'
Info: Successfully installed vsdbg at 'C:\Users\AzureTest\.vsdbg\linux-musl-x64\latest'
Debugger acquired.
Copying the .NET Core debugger to the container...
Debugger copied

**Comment by bwateratmsft** [comment]
This doesn't occur in 1.2.1, so it may be a regression from #1948. @ravipal it looks like slashes are getting normalized incorrectly for Linux containers; the path is right but the slashes are backwards:
`\remote_debugger\vsdbg`.

Can you take a look?
