### ISSUE TITLE
run docker-compose up without --build (and maybe without -d)

### ISSUE THREAD

**Issue by JoeSchr** [Microsoft/vscode-docker#200]
Hi,
I would like to have the possibility to run `docker-compose up` without `--build` and without `-d`.

Reasons:
----------

`--build `: takes a long time on my laptop and I don't see the need to build everytime. also since it runs in cmd shell it sometimes breaks with an IO error (same command in powershell is fine)

`-d`: I usually run a unittest right after bringing my dev enviroment up, so I really would like to see this part of the log

Thx!

**Comment by vascofg** [comment]
+1 this should be configurable

**Comment by JoeSchr** [comment]
I think that is a good idea

**Comment by JoeSchr** [comment]
awesome, thx!

**Comment by chrisdias** [comment]
@JoeSchr i've published a new build of the extension 0.0.24 with a fix. There are 2 new settings `docker.dockerComposeBuild` and `docker.dockerComposeDetached` that you can set to `false` to shut off (they default to `true`).
