### ISSUE TITLE
[Suggestion] Add a button to navigate to the troubleshooting page in the notification 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2001]
**OS:** Windows
**Build Version:** [20200519.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19712&view=results)

**Repro Steps:**
1. Switch to Windows Containers mode in Docker Desktop.
2. Create a ASP .NET Core web app by "dotnet new mvc --no-https".
3. Open this project in VS Code --> Prompt to add the required assets --> Yes.
4. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP .NET Core --> Windows--> Include optional Docker Compose files --> Enter ports: the default 80.
5. Right click the docker-compose.yml --> Select "Compose Up".
6. Open launch.json file --> Add "Docker: .NET Core Attach (Preview)" configuration.
7. Debug with "Docker: .NET Core Attach (Preview)" configuration.

**Actual:**
A notification says that "Attaching a debugger to a Hyper-V container is not supported.", there is no button to navigate to the troubleshooting page which has the workaround for this error.
![image](https://user-images.githubusercontent.com/45614674/82411576-9dbdd800-9aa4-11ea-8879-4248190d90f5.png)

**Suggestion:**
Add a button in the notification to navigate to the troubleshooting page which has the workaround for this error.

**Comment by dbreshears** [comment]
Will wait for additional feedback before considering this.
