### ISSUE TITLE
Extension does not work with remote host anymore

### ISSUE THREAD

**Issue by instalab** [microsoft/vscode-docker#2003]
I've noticed today that the extension does not want to connect to a docker host running on my second computer. I know the issue is not with the host where docker is installed because a different docker extension "ms-vscode-remote.remote-containers" works fine and recognizes the containers, I can even attach to them without issues, standard CLI tool works fine too either using the environment variable or CLI option. I tried running vscode with either environment variable set or "docker.host" setting in vs code and neither worked.
_Some screens:_
![Screenshot_2020-05-20_10-23-35](https://user-images.githubusercontent.com/23265116/82429578-0f395e80-9a84-11ea-90b3-05fb91546bd7.png)
![Screenshot_2020-05-20_10-23-46](https://user-images.githubusercontent.com/23265116/82429587-12344f00-9a84-11ea-87f4-a3c85052ebe6.png)

**Environment:**
OS: Arch Linux x86_64
Kernel Release: 5.6.13-arch1-1
Docker version 19.03.9-ce, build 9d988398e7
VSCode (Tested on both stable and insiders):
 - 1.46.0-insider
 - 1.45.1

$ code --list-extensions
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack

**Comment by bwateratmsft** [comment]
How are you connecting to the other computer (what do you have for `docker.host`)? SSH, HTTP, etc.?

**Comment by instalab** [comment]
The other composer's docker is listening on a standard TCP port.
I can connect to it from CLI like this: `docker -H 192.168.1.175:2375 ps`
Or like this `DOCKER_HOST=192.168.1.175:2375 docker ps`
This is what I put in `docker.host`: `"docker.host": "192.168.1.175:2375"`

**Comment by bwateratmsft** [comment]
Can you try using `tcp://192.168.1.175:2375` for `docker.host`?

**Comment by instalab** [comment]
@bwateratmsft Thanks, adding 'tcp://' to the address solved the issue.

It's odd that other tools work fine without 'tcp://', only vscode docker has this issue.

**Comment by bwateratmsft** [comment]
There is some difference; the Remote - Containers extension uses the CLI exclusively but the Docker extension uses both CLI and Dockerode. Dockerode handles the explorer and most of the commands. I thought it was supposed to raise an error if it was given something that didn't look like "protocol://something"; I'll take a look next week at why it wasn't doing that...
