### ISSUE TITLE
Remove '...' for the "Docker Registries Help" and "Docker Contexts Help" commands

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2005]
**OS:** All
**Build Version:** [20200520.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19784&view=results)

**Repro Steps:**
F1->Input Help->Check the Help commands for Docker Registries and Docker Contexts.

**Expect:**
There is no '...' for these two commands.

**Actual:**
There is '...' for these two commands.
![image](https://user-images.githubusercontent.com/45614674/82540481-b7811d00-9b81-11ea-8ac9-4ec5faa48947.png)

**Comment by bwateratmsft** [comment]
@BigMorty Up to you ultimately; I kinda think they should stay since they both end up opening a web page in the browser.

**Comment by BigMorty** [comment]
I don't think the ... should be there if just opening a web page. Other Help commands in VS Code don't have the ...
