### ISSUE TITLE
Display "Application Error" in browser after deploying image to Azure App Service

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2006]
**OS:** Windows
**Build Version:** [20200520.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19784&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. From the command line, run: "docker run -d --rm --name noAuthRegistry -p 5100:5000 registry"
2. Verify the curl http://localhost:5100/v2/_catalog is working, you can see: "Content: {"repositories":[]}"
3. Click on "Connect Registry" -> Generic Docker Registry-->URL: http://localhost:5100 --> Username: press ENTER
4. Right click "myExpressApp" image--> Push--> Select "Connect Registry"-->Select http://localhost:5100
5. Right-click on the image in this registry view -> Deploy Image to Azure App Service--> Follow steps to create a web app
6. Open the link

**Expect:**
Succeed to open in the browser, such as:
![image](https://user-images.githubusercontent.com/62053665/82544567-e1d5d900-9b87-11ea-9d66-863839695559.png)

**Actual:**
Display "Application Error".
![image](https://user-images.githubusercontent.com/62053665/82544665-0cc02d00-9b88-11ea-8f34-478ccd87d0d5.png)

**Comment by bwateratmsft** [comment]
I took a look at this. `localhost` or any internal IP address would never be able to work for deploying to Azure. The website is configured and given the registry URL, username, and password. With a URL of `localhost`, Azure certainly cannot pull an image (that registry isn't in Azure).

We should probably add validation to block `localhost` for sure, and if possible also internal IP addresses. I'm surprised Azure doesn't already block this.

**Comment by PavelSosin-320** [comment]
Something strange is going with the local registry - it changes its mind every day. It returned empty response yesterday, then it worked this morning After that I got a failed Windows update, then Windows Desktop update and now it works. But it is empty.

**Comment by PavelSosin-320** [comment]
Don't hurry to block the localhost, please. This is a useful configuration: local cluster with ingress in which localhost is only the cluster name and local registry is the service. It's enough that **application and local registry are in the same network** It works for me.

**Comment by bwateratmsft** [comment]
@PavelSosin-320 I don't mean blocking `localhost` registry, I mean blocking from deploying to Azure from a `localhost` registry (which cannot work).

**Comment by PavelSosin-320** [comment]
OK it should be impossible!

**Comment by dbreshears** [comment]
Not blocking anything for now
