### ISSUE TITLE
Running > Docker: Compose Up on a workspace always uses the same folder as root

### ISSUE THREAD

**Issue by vascofg** [Microsoft/vscode-docker#201]
I have a workspace with two folders and running Compose Up prompts me to choose one of them, but ends up always launching the compose on the first folder.
Is this a bug or support for this isn't really finalized?

![prompt](https://user-images.githubusercontent.com/634441/34890635-a2aad0a4-f7ca-11e7-9056-148939d6d971.png)

**Comment by chrisdias** [comment]
fix is in chrisdias/201, have to test on Mac/Linux tomorrow.

**Comment by chrisdias** [comment]
@vascofg i've published a new build of the extension 0.0.24 with this fix. thanks!
