### ISSUE TITLE
docker container not starting

### ISSUE THREAD

**Issue by linklayeredu** [microsoft/vscode-docker#2010]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.buildImage
Error type: Error
Error Message: To quick build Docker files you must first open a folder or workspace in VS Code.

Version: 1.2.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.quickPickWorkspaceFolder extension.bundle.js:1:428598
scheduleRunRequest extension.bundle.js:310:763619
Object.scheduleRunRequest extension.bundle.js:1:714130
processTicksAndRejections task_queues.js:85:5
buildImageInAzure extension.bundle.js:310:817304
```

</details>

**Comment by bwateratmsft** [comment]
@linklayeredu Do you have a workspace open?
