### ISSUE TITLE
Docker extension doesn't show the icon in the sidebar

### ISSUE THREAD

**Issue by emendoza-dev** [microsoft/vscode-docker#2011]
Issue Type: <b>Bug</b>

Just install the docker extension and after that the siderbar doesn't shows the icon to access to that extension.

Extension version: 1.2.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
@emendoza-dev Can you share a screenshot? Does it persist after restarting VSCode?

**Comment by emendoza-dev** [comment]
![image](https://user-images.githubusercontent.com/58489186/83263388-24994180-a184-11ea-993d-08652d7bbed7.png)

**Comment by emendoza-dev** [comment]
The access is in the sidebar but it doesn't show the icon. 
![image](https://user-images.githubusercontent.com/58489186/83263506-53afb300-a184-11ea-97a0-8056bd46bba6.png)

**Comment by emendoza-dev** [comment]
> @emendoza-dev Can you share a screenshot? Does it persist after restarting VSCode?

Yes, It persists after restarting VSCode.

**Comment by emendoza-dev** [comment]
I did it, I uninstalled the docker extension and I installed it again, but it doesn't show the icon.

![2020-05-29_14-15-47](https://user-images.githubusercontent.com/58489186/83296947-43fd9200-a1b7-11ea-8b44-17a0e35003f2.gif)

**Comment by bwateratmsft** [comment]
Strange. This must be a VSCode bug. I'll open one there...

**Comment by bwateratmsft** [comment]
Opened https://github.com/microsoft/vscode/issues/98833. I'll close this one as external to that.
