### ISSUE TITLE
dockerRun.ports task setting ineffective when debugging a Node.js app

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2012]
I have a simple Node.js app that listens on port 5000. Haven't changed the Dockerfile from what VS Code Docker extension scaffolds. Here are my Docker run tasks:

```json
{
  "type": "docker-run",
  "label": "docker-run: release",
  "dependsOn": [
    "docker-build"
  ],
  "platform": "node",
  "dockerRun": {
    "ports": [
      { "hostPort": 5000, "containerPort": 5000 }
    ]
  }
},
{
  "type": "docker-run",
  "label": "docker-run: debug",
  "dependsOn": [
    "docker-build"
  ],
  "dockerRun": {
    "env": {
      "DEBUG": "*",
      "NODE_ENV": "development"
    },
    "ports": [
      { "hostPort": 5000, "containerPort": 5000 }
    ]
  },
  "node": {
    "enableDebugging": true
  }
}
```

When I start `docker-run: release` task, the container is listening on host port 5000, as expected
When I start `docker-run: debug` task, the container is listening on random host port.

**Comment by karolz-ms** [comment]
This was reproduced on Windows 10 2004, WSL2 Docker Desktop 2.3.0.0, Docker extension version 1.2.0, VS Code version 1.45.1

**Comment by bwateratmsft** [comment]
@karolz-ms I cannot reproduce:

![image](https://user-images.githubusercontent.com/36966225/82907960-4c469a80-9f35-11ea-96c2-5d85a518ba5d.png)
![image](https://user-images.githubusercontent.com/36966225/82907990-56689900-9f35-11ea-8142-0c6c2c2f4d8d.png)
![image](https://user-images.githubusercontent.com/36966225/82908028-654f4b80-9f35-11ea-9600-9f86b9b72328.png)

**Comment by karolz-ms** [comment]
Tried restarting VS Code, I can still reproduce every time. Will try to do some debugging later today.

**Comment by bwateratmsft** [comment]
Just to be sure I'll change to port 5000.

**Comment by karolz-ms** [comment]
This is caused by https://github.com/microsoft/vscode/issues/98617
