### ISSUE TITLE
There is an extra space between "-d" and "-p"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2014]
**OS:** Linux
**Build Version:** 20200520.2

**Repro Steps:**

1. From command line, type: "docker pull registry".
2. Navigate to image, right click registry --> Run.
3. Check the result.

**Expect:**
Execute "docker run  --rm -d -p 5000:5000/tcp registry:latest".

**Actual:**
There is an extra space between "-d" and "-p".
![image](https://user-images.githubusercontent.com/62053665/82873009-73699000-9f66-11ea-85d2-4b38ad0200bf.png)

**Comment by bwateratmsft** [comment]
This is intentional. It doesn't cause any issues but makes command lines much easier to build correctly.
