### ISSUE TITLE
Docker view shows "Failed to connect. Is Docker running?" even though Docker Desktop is running

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2015]
**OS:** Mac 10.13.6/10.14.6
**Build Version:** 20200520.2

**Repro Steps:**

1. Make sure Docker Desktop is installed.
2. Start the Docker Desktop.
3. Check the Docker view in VS Code.

**Expect:**
The Docker view will show the following, such as:
![image](https://user-images.githubusercontent.com/62053665/82896436-868d5780-9f88-11ea-942a-9dea1f0d4054.png)

**Actual:**
Docker view shows "Failed to connect. Is Docker running?", such as:
![image](https://user-images.githubusercontent.com/62053665/82896593-c94f2f80-9f88-11ea-9efa-08a42c95cbcb.png)

**More info:**
This issue doesn't reproduce on Mac 10.15.2.

**Comment by bwateratmsft** [comment]
@v-mengwe How long did this persist? We don't refresh as often if we detect that Docker isn't running.

**Comment by v-mengwe** [comment]
We solve this issue by clean `docker.host` setting, so close it.
