### ISSUE TITLE
VS code issue

### ISSUE THREAD

**Issue by karavadip** [microsoft/vscode-docker#2018]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.0

Version: 0.5.0
OS: darwin

**Comment by bwateratmsft** [comment]
@karavadip VSCode 1.25 is very, very old. You need to update.
