### ISSUE TITLE
Adding Commented Link to docker run/build tasks

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2019]
Per customer feedback, it could be helpful to put a comment in a scaffolded Docker run or docker build task that says "For more information, go to aka.ms/docker-customize". This is congruent with our current Python Dockerfile that links users to various locations of documentation.

I could imagine this addition in all languages, but I am totally fine with adding this to just Python for now.

**Comment by bwateratmsft** [comment]
@ucheNkadiCode This isn't possible without dramatically changing our task scaffolding system in ways I'm not really willing to do.

**Comment by ucheNkadiCode** [comment]
So even if we put a comment inside of or above the dockerBuild tasks, we can expect that JSON cannot handle this?

**Comment by bwateratmsft** [comment]
JSON doesn't actually have comments, but VSCode handles them reasonably well anyway. You could add your own comments to the tasks.json. However, it's not possible to write JSON out (with the JSON serializer) that contains comments (you can't put comments on properties of an object). So, we'd have to write raw text (which happened to be JSON+comments), which would make it extremely difficult to preserve existing tasks/launch configs, and would make it impossible to validate at build time that the text we're writing out is even valid.

**Comment by bwateratmsft** [comment]
@ucheNkadiCode I spent some time investigating, I found two alternative options:

## Kinda weird option 1
An actual "comment" field on the task/launch, though that would look a little strange (ignore the yellow squiggles, they wouldn't be there):
![image](https://user-images.githubusercontent.com/36966225/83064906-92ccef80-a030-11ea-9b82-c8ff0f8e7f46.png)

(That looks out of place to me, though.)

## Super cool option 2
We can put clickable links into the intellisense description!
![image](https://user-images.githubusercontent.com/36966225/83065224-21417100-a031-11ea-96ab-50d98c63eadd.png)

**Comment by ucheNkadiCode** [comment]
By your titles, I wonder which one is your favorite 🤔😆. Great Job Brandon! I truly feel as through adding a link would further increase observability. 

Would it be possible to add https://code.visualstudio.com/docs/containers/reference#_docker-build-task for the dockerBuild task (or I can create an aka.ms link). Where do you think might be a good attribute to add a hover for a https://code.visualstudio.com/docs/containers/reference#_docker-run-task  <--- link? (I can also create an aka.ms link)

**Comment by bwateratmsft** [comment]
Can you make an aka.ms link for both of them? The "docker-build-task" one can go on `dockerBuild`, and "docker-run-task" one on `dockerRun`. Seems like the most suitable place for them.

**Comment by ucheNkadiCode** [comment]
I agree, each link is now under:
1. https://aka.ms/vscode-docker-build-task
1. https://aka.ms/vscode-docker-run-task

Thanks for figuring this out!
