### ISSUE TITLE
Add setting for "docker-compose --compatibility"

### ISSUE THREAD

**Issue by sburlappp** [microsoft/vscode-docker#2021]
Docker removed the ability to easily define memory and CPU limits on services in v3 Compose files, unless you're also using Swarm. However, they did eventually add the "--compatibility" flag as a work-around:

https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-mode

This can currently be enabled in VScode by adding these lines to settings.json:

```
{
    "docker.commands.composeUp": "docker-compose --compatibility ${configurationFile} up ${detached} ${build}",
    "docker.commands.composeDown": "docker-compose --compatibility ${configurationFile} down"
}
```

Please consider adding an option "docker.dockerComposeCompatibility" which would work like docker.dockerComposeBuild and docker.dockerComposeDetached to add the "--compatibility" option when desired. (Also, please consider having it default to "true".)

**Comment by bwateratmsft** [comment]
Is command customization not sufficient?

**Comment by karolz-ms** [comment]
I think Docker is working on new iteration of Compose spec that will bring CPU and memory limits back...

**Comment by sburlappp** [comment]
The ```--compatibility``` flag was added as a compromise for users who wanted to use the v3 file format for local development. Officially, Docker recommends using v2 for local and v3 for Swarm:

https://github.com/docker/compose/issues/4513
https://github.com/docker/compose/pull/5684

It appears that the ```--compatibility``` flag is as close as they intend to get to restoring the old functionality. I do plan to leave my own settings.json customized, but expect that many others have run into this issue too. Adding a VScode setting with an explanation in the docs would probably help avoid confusion.

(Or, if this is rejected, leaving this note here may help others anyway.)

**Comment by bwateratmsft** [comment]
Is a setting specific to compatibility any easier to discover than the generic command customization settings, though?

@karolz-ms do you know where the info about those compose items possibly returning is?

**Comment by karolz-ms** [comment]
@bwateratmsft the cpu limits etc reintroduction is tracked by [this issue](https://github.com/compose-spec/compose-spec/issues/12)

Given this is point-in-time limitation and that a good workaround exists (command customization is a good fit for those who want `--compatibility` flag) I suggest we don't do anything on VS Code Docker ext side

**Comment by bwateratmsft** [comment]
Good to know. It seems like there is actual traction on the issue; i.e. there are PRs being created and merged. So, I agree that this seems like a point-in-time problem.

**Comment by bwateratmsft** [comment]
@sburlappp based on the availability of command customization and the temporary nature of the issue, we have decided not to add this setting. Nevertheless, we do want to thank you for your suggestion, we really appreciate it!
