### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fybwid** [microsoft/vscode-docker#2023]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.2.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/yosef_bw/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

:package: [ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-docker/files/4693025/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@fybwid is this issue consistent at all?

**Comment by fybwid** [comment]
@bwateratmsft it's happened with https://github.com/Dart-Code/Dart-Code/issues/2429#issuecomment-635069554 and after update with https://github.com/Dart-Code/Dart-Code/releases/tag/v3.11.0-beta.4 everything works fine.

**Comment by bwateratmsft** [comment]
Ok, glad it's working. I'll close this for now but let us know if issues come back!
