### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ayaya0074** [microsoft/vscode-docker#2027]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\豪\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@Ayaya0074 Does this issue occur regularly?
