### ISSUE TITLE
popups are always displayed when writing multiline RUN command

### ISSUE THREAD

**Issue by hidekuro** [Microsoft/vscode-docker#203]
When writing a long RUN command, always popups are displayed and it is an eyesore.

![2018-01-18_18h19_12](https://user-images.githubusercontent.com/3986668/35090439-03be9306-fc7d-11e7-8ddd-18e0ef6dd7b1.png)

**Comment by rcjsuen** [comment]
@hidekuro Please see #150.

**Comment by hidekuro** [comment]
I tried [customize suggestion preferences](https://github.com/Microsoft/vscode-docker/issues/150#issuecomment-356749649).
It works fine for me.

```json
    "[dockerfile]": {
        "editor.parameterHints": false,
        "editor.quickSuggestions": {
            "other": false,
            "comments": false,
            "strings": false
        }
    },
```
thanks to @rcjsuen , @chrisdias
