### ISSUE TITLE
compose up not working from ctrl+shift+P

### ISSUE THREAD

**Issue by rabinovic** [microsoft/vscode-docker#2030]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up
Error type: TypeError
Error Message: Cannot read property 'filter' of null

Version: 1.2.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
selectCommandTemplate extension.bundle.js:1:648022
Object.selectComposeCommand extension.bundle.js:1:649694
compose extension.bundle.js:310:783137
processTicksAndRejections task_queues.js:85:5
async composeUp extension.bundle.js:310:783355
```

</details>

**Comment by bwateratmsft** [comment]
@rabinovic Do you have any settings for `docker.commands.composeUp`?
