### ISSUE TITLE
error

### ISSUE THREAD

**Issue by paulsd2020** [microsoft/vscode-docker#2031]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login  --username waxmiguel --password-stdin
'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.2.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
ChildProcess.EventEmitter.emit domain.js:476:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
Process.onexit async-listener/glue.js:188:31
```

</details>

**Comment by bwateratmsft** [comment]
@paulsd2020 Do you have Docker installed?
