### ISSUE TITLE
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon.

### ISSUE THREAD

**Issue by kushalchordiya216** [microsoft/vscode-docker#2032]
Ubuntu 18.04.3 OS
Steps to reproduce the issue
Install docker version 19.03
make a dockerfile and run docker build service_name .

I have already run the commands for using docker as a non-root user, in fact this very same command runs fine with no issues in an external terminal, but doesn't run inside vsc terminal unless I explicitly run the 
`sudo usermode -aG docker $USER command` 
for each new session of the integrates console.

This has also blocked the docker extension for some reason, as i constantly get 
"failed to connect. Is docker running?" 
for all options on the docker extension

**Comment by karolz-ms** [comment]
@kushalchordiya216 can you restart VS Code process and check if that solves the issue?

**Comment by PavelSosin-320** [comment]
If you use Docker Desktop 2.3 ... with WSL try to go back to the Settings -> WSL Integration and add your distro again. After Docker restart the issue disappears. Something was broken in WSL integration but now it works for me.

**Comment by kushalchordiya216** [comment]
Hi, I kind of have a solution and kind of know why this was failing, though I'm not entirely sure. So, the strange thing is, everything works perfectly when i start vscode from the command line, by typing in code, but not when i start it by clicking on the icon or by searching for it from in the search bar. Now, i have a guess as to why this is happening, but as i said, I'm not sure. I'm using ubuntu 18 with gnome DE, and normally when you launch any application, it is by default launched in s sandboxed environment with lesser permissions, for security reasons. This is kind of why you can't launch vscode as a root user and if you somehow do, you keep getting a warning telling you this is a bad idea. 

This would explain why I was able to use docker commands from the integrated terminal after I used the sudo usermod command again for each terminal session. As of now, everything works fine, as long as I launch code directly from the terminal, with no sandbox. I tried messing with my code.desktop file a bit to allow the same things to happen for a normal launch but to no avail. Just in case anyone else with a Linux/GNOME/Ubuntu OS is facing the same problems, just remember this as a possible fix

**Comment by bwateratmsft** [comment]
That's good information, thanks @kushalchordiya216. It sounds like this is more or less intentional design with the sandboxing functionality.

**Comment by kushalchordiya216** [comment]
A quick update. 
In the user settings for code, add the following line 
  "terminal.integrated.shellArgs.linux": ["-l"]
this makes sure that code sources .bash_profile every time it is launched through any means. Why exactly this solves the problem is beyond me, but I have observed that now, the extension works perfectly, even when launching it via the dock. 

for reference, this is what's in my bash_profile 
`
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export PATH=$PATH:/usr/local/go/bin
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
`
I know it makes no sense for this to change anything, but just sharing a possible fix for anyone else who may be facing a similar issue

**Comment by bwateratmsft** [comment]
I'll close this issue for now since it seems like a sandboxing limitation.
