### ISSUE TITLE
Error in Deploying in azure app service

### ISSUE THREAD

**Issue by HendwanAbozide** [microsoft/vscode-docker#2041]
Does this occur consistently? Yes
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 1.2.1
OS: linux
OS Release: 5.4.0-33-generic
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
getNewSiteConfig extension.bundle.js:310:502904
processTicksAndRejections task_queues.js:85:5
async deployImageToAzure extension.bundle.js:310:502367
async deployImageToAzure extension.bundle.js:1:714685
```

</details>

**Comment by bwateratmsft** [comment]
@HendwanAbozide You need to enable admin mode on the ACR you are using as a source. This is what App Service uses to pull images to deploy them. Unfortunately there are no other possible authentication options. See here for more info: https://github.com/microsoft/vscode-docker/issues/1685#issuecomment-634873423
