### ISSUE TITLE
Using "@" symbol in username for docker context host will break connection because the symbol encoded to "%40"

### ISSUE THREAD

**Issue by netaskd** [microsoft/vscode-docker#2044]
I have a username like `username@internal.domain` and remote host like `linux.host` and I try to use it in connection string in docker context settings like
```
...
        "Endpoints": {
            "docker": {
                "Host": "ssh://username@internal.domain@linux.host",
                "SkipTLSVerify": false
            }
        },
...
```
In this case, connection to `linux.host` with username `username@internal.domain` will never successful because username converts to `username%40internal.domain` and I see in /var/log/secure logs a string like:
`sshd[116842]: input_userauth_request: invalid user username%40internal.domain [preauth]`
So, it would be great to escape `@` symbol in username for ssh connection string inside of the "VSCode-Docker" extension.

**Comment by netaskd** [comment]
A workspace fields for docker extension
Containers
Images
Networks
Volumes
will try to connect in  a loop, but never reach because 
`sshd[116842]: input_userauth_request: invalid user username%40internal.domain [preauth]`

**Comment by bwateratmsft** [comment]
This is an issue in the [`ssh2`](https://www.npmjs.com/package/ssh2) Node package. In [`docker-modem`](https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L37), Node's [`URL`](https://nodejs.org/api/url.html) library parses out the username as `username%40internal.domain`, but `ssh2` does not handle it correctly.
