### ISSUE TITLE
Add image size on description

### ISSUE THREAD

**Issue by danjudex** [microsoft/vscode-docker#2047]
Issue Type: <b>Feature Request</b>

In the settings of the list of images there is not enough opportunity to display image size. The description configuration does not have this option.

![image](https://user-images.githubusercontent.com/6211155/83961853-cf121280-a8b0-11ea-8c18-a2a8496332cc.png)

Extension version: 1.2.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-101-generic

**Comment by bwateratmsft** [comment]
Should be pretty straightforward to add this.

**Comment by bwateratmsft** [comment]
This has been fixed in Docker extension version 1.5.0.
