### ISSUE TITLE
Better management of Volumes

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2054]
[This came from PaulY]
First, the challenge:
I have a lot of volumes.  I think most are orphaned junk I should clean up but using our commands or inspect I see no useful information.  What I really want to know is which container is using a volume, if any.  

The Docker command that solves this is as follows where volume could be the name or the mountpoint inspect tells you:
$ docker ps -a --filter volume=c4be1fa31accf8c43de23adacc2542c7af14ee8e60048cd9fe0b3900eda00261
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                 PORTS                    NAMES
12d0ecc421bb        mariadb             "docker-entrypoint.s…"   6 weeks ago         Up 5 hours (healthy)   0.0.0.0:3306->3306/tcp   mariadb

Ah ha, it's mariadb container that is using it -- and I should not delete it.

In the docker explorer, it would be really cool if containers just let you find mounted volumes. And also if volumes could show their dependent containers.

Here is a somewhat related issue from the past - https://github.com/microsoft/vscode-docker/issues/1209

**Comment by bwateratmsft** [comment]
Should look to see if there are commands we could use to highlight/select tree nodes.

**Comment by bwateratmsft** [comment]
I don't think this is actionable.

1. The relationship of container to volume is many-to-many. Consequently, grouping cannot be used, or a node could appear multiple times in a tree view which is problematic for many reasons.
1. Volume inspect info does not give any information about usage, even though the [spec](https://docs.docker.com/engine/api/v1.40/#operation/VolumeInspect) suggests it should.
1. There is already a Prune command for removing all unused volumes.
1. The Remote - Containers extension offers the ability to "look into" a volume (Inspect volume in Visual Studio Code).
1. The best we could possibly do is shoehorn the containers using a volume into the volume's inspect data, but the user experience is mediocre and I'm not sure it justifies the amount of work it would take.

**Comment by bwateratmsft** [comment]
Duping this to #2538.
