### ISSUE TITLE
Request textDocument/semanticTokens failed

### ISSUE THREAD

**Issue by csakaszamok** [microsoft/vscode-docker#2055]
during writing a Dockerfile i get error messages:  

[Error - 10:47:31 AM] Request textDocument/semanticTokens failed.
  Message: Request textDocument/semanticTokens failed with message: Maximum call stack size exceeded
  Code: -32603

**Comment by rcjsuen** [comment]
@csakaszamok Thank you for your bug report. I presume this bug is not reproducible?

Can you share your Dockerfile? Do you remember what you were changing at the time?

**Comment by csakaszamok** [comment]
yes, you can reproduce it with a litte sample Dockerfile:
FROM ubuntu
ENV \
# common variables:
  ENV1=something \
  ENV2=999 

if you remove or move the comment, everything is ok
so it is good:
FROM ubuntu
ENV \
  ENV1=something \
# common variables:
  ENV2=999 


thank you

**Comment by rcjsuen** [comment]
@csakaszamok Thank you for sharing your Dockerfile. I have opened https://github.com/rcjsuen/dockerfile-language-service/issues/69 to track this.

**Comment by csakaszamok** [comment]
Thx

**Comment by JoseFMP** [comment]
Still happening over here.

**Comment by rcjsuen** [comment]
> Still happening over here.

Hi, @JoseFMP. You are correct. The bug fix is not in a release yet so you will continue to encounter this issue until then. Thank you for your understanding.

**Comment by rcjsuen** [comment]
@JoseFMP Would you mind sharing your Dockerfile here so we can ensure that your bug is covered?

**Comment by rcjsuen** [comment]
Thank you @csakaszamok and @JoseFMP for your bug report. I have opened #2146 to address this.

**Comment by bwateratmsft** [comment]
We have released Docker 1.4.0 which contains a fix for this.

**Comment by khs1994** [comment]
```docker
FROM alpine

ENV PHP_EXTRA_CONFIGURE_ARGS \
        kkk \
        # comment
        # comment
        # comment
        # comment
        kkk2
```

with one more comment line,show this error message

**Comment by rcjsuen** [comment]
@khs1994 Thank you for your bug report. I have reproduced the problem and have opened https://github.com/rcjsuen/dockerfile-language-service/issues/74 to track this.
