### ISSUE TITLE
Adding Node.js files to workspace breaks when package.json in subfolder

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2057]
I was following the [Deploy images to ACI Tutorial](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-tutorial-prepare-app) and noticed that containerizing the app as-is was failing. I suspect it is because the package.json is found in a folder named `app`. Even though the docker-build and docker-run tasks don't reference this file, I am still blocked from hitting F5

Repro Steps:
From Terminal
1. `git clone https://github.com/Azure-Samples/aci-helloworld.git` into a folder of choice
1. `code .` to open editor
Within VS Code
1. Delete or Rename current Dockerfile to Dockerfile_original
1. `Ctrl + Shift + P` Add Dockerfile to workspace and select Node.js
1. I am met with this error: 
![image](https://user-images.githubusercontent.com/20650058/84332604-31357680-ab42-11ea-8c87-24847bc5a192.png)
1. After moving the package.json to the root folder, the container now builds, but during run there is the error:
![image](https://user-images.githubusercontent.com/20650058/84333018-5aa2d200-ab43-11ea-8bf5-70b9161b6c20.png)
1. This can be fixed by changing the `main` property in `package.json` to "./app/index.js" but I'm unsure if this problem would have persisted in a fresh node project scenario

**Comment by karolz-ms** [comment]
@ucheNkadiCode showed me that even if Dockerfile is edited with correct path to package.json, the image build still fails with the error mentioned in step 5. This seems wrong.

**Comment by bwateratmsft** [comment]
I spoke to @philliphoff, and we think the best approach is to do more-or-less the same as is done for .NET: 
- The Docker build context is always the workspace folder (by default)
- The Dockerfile is placed next to the package.json and copies in everything
- The entrypoints/etc. in the Dockerfile are subpath'd

**Comment by bwateratmsft** [comment]
This is now fixed in Docker extension version 1.7.0.
