### ISSUE TITLE
Add a docker-compose Language ID so it can be assigned via file.associations (or manually)

### ISSUE THREAD

**Issue by robertpeteuil** [microsoft/vscode-docker#206]
Please add `docker-compose` to the installed languages and give it a unique language ID (like `dockercompose`.

This would enable assigning it via user-settings, workspace-settings and manually via the Select Language Mode dropdown.

I should be able to define a file to the docker-compose DSL with something like this:

```
"files.associations": {
    "core-service.yml": "dockercompose"
}
```
An example of a YAML based DSL extension that does this is [language-Ansible](https://github.com/haad/vs-language-ansible).  It registers the `ansible` language which enables configuring and selecting the language as described above.  

I've read about changing the ENV var COMPOSE_FILE_GLOB_PATTERN, but this isn't a solution for many reasons:
- It changes it globally (for all open projects) on that computer
- It must be changed on every computer (via some method outside of vscode's config system)
- It doesn't allow for configuration in user-settings - setting user-specific names and allows the setting to be synced between machines
- It doesn't allow configuration in workspace-settings - for project specific filenames (which is likely the most useful)

**Comment by robertpeteuil** [comment]
Thanks @seffyroff - I'm surprised there hasn't been more noise about this. 

The current implementation is great, but limited by strange implementation choices:
- Define an entire language syntax & autocomplete engine, then skipped the most important step - registering it as a language.  
- Hard-coding it to specific filenames (well excepting system-wide environment vars, which is another odd choice.) 

Perhaps this implementation is caused by other features in the extension that requiring knowing the filenames in advance (for action like compose up)
- if so, why can't the language be released as a separate extension?

**Comment by hahntech** [comment]
Yes, please add this!  We use compose files names for components of our solution everywhere.  I cannot believe this isn’t built it.

**Comment by Frodox** [comment]
Heavy +1.
We regularly use `docker-compose-dev.yml`, `docker-compose-prod.yml`, `docker-compose-monitoring.yml`, `docker-compose-wthatever.yml`, and it would be great to highlight all them too!

**Comment by bradwilson** [comment]
Do we need a PR to get this to happen?

**Comment by sarink** [comment]
Temporarily, you can at least tell vscode that it's yml with the following
```
"files.associations": {
  "docker-compose*.yml": "yaml"
}
```

**Comment by bradwilson** [comment]
It's already recognized as YAML. This is about getting Intellisense for the Docker Compose features, not syntax highlighting.

**Comment by akankov** [comment]
Just add these to your config
`
"docker-compose.files": [
        "docker-compose.yml",
        "docker-compose-dev.yml"
    ]
`

**Comment by bradwilson** [comment]
@akankov That does not appear to be a valid setting in 0.4.0:

![image](https://user-images.githubusercontent.com/16944/50580581-0b605a00-0e05-11e9-9c01-cd3a11e05bf5.png)

**Comment by xenoterracide** [comment]
still open :'(

**Comment by Frickeldave** [comment]
Yes. please implement. For some reason in our project the compose-files are named "Composefile". With file associations i can associate them with YAML, but not with docker-compose. This results in "No Intellisense" and "No options in right-click context menu".

**Comment by bwateratmsft** [comment]
Duping to #2539
