### ISSUE TITLE
Add checkbox for registry in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2060]
**OS:** All
**Build Version:** 20200608.1

**Repro Steps:**
F1 -> Azure Container Registry: Delete Registry... -> Select the subscription -> Check the registry list.

**Expect:**
There is a checkbox for every registry and a select all checkbox, like the below screen.
![image](https://user-images.githubusercontent.com/45614674/84375451-2a763480-ac12-11ea-8a23-9c94e96a7042.png)

**Actual:**
There is no checkbox for every registry, can't delete several registries at the same time.
![image](https://user-images.githubusercontent.com/45614674/84375742-99ec2400-ac12-11ea-84a0-23f1678fcd69.png)

**More Info:**
This issue also reproduces for "Delete Repository..." command.

**Comment by bwateratmsft** [comment]
I'll dupe this one over to #1631 since that covers the same scenarios.
