### ISSUE TITLE
Getting this issue while creating azure container registry through VS code

### ISSUE THREAD

**Issue by shakuntalakhatri** [microsoft/vscode-docker#2065]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: Error
Error Message: Entry not found in cache.

Version: 1.2.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54224extension.js:229:54224
extension.js:229:52217extension.js:229:52217
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@shakuntalakhatri can you add repro steps?

**Comment by bwateratmsft** [comment]
Ah, it looks like it is this upstream issue: https://github.com/microsoft/vscode-azure-account/issues/53

Can you try reopening the window or signing out and back in to Azure?
