### ISSUE TITLE
[Suggestion] Add a notification "No running containers are available to attach" if the container is not running before debugging

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2066]
**OS:** All
**Build Version:** 20200611.3

**Repro Steps:**
1. Open a Django/Flask project in VS Code and add Docker support including docker-compose files.
2. Add a new "Python Remote Attach" configuration.
3. Change the configuration to "Python Remote Attach".
4. Right click docker-compose.debug.yml file and select "Compose Up" action.
5. F5 immediately.

**Actual:**
Auto stop the debugging if the container is not running before debugging.

**Suggestion:**
Add a notification "No running containers are available to attach" if the container is not running before debugging. Like below screen in .NET Core project.
![image](https://user-images.githubusercontent.com/45614674/84494033-5c070280-acdb-11ea-86f1-f6bfab61a01c.png)

**Comment by bwateratmsft** [comment]
@haniamr the Python Remote Attach config comes from the Python extension, not the Docker extension, correct?

**Comment by haniamr** [comment]
@bwateratmsft yes, that's correct. We don't have control to do that, unless we start to scaffold our own version of the attach configuration.

**Comment by bwateratmsft** [comment]
I'd rather avoid that, so I'll resolve this as external.
