### ISSUE TITLE
Cannot attach linux container in Windows OS

### ISSUE THREAD

**Issue by mwithi** [microsoft/vscode-docker#2069]
Issue Type: <b>Bug</b>

Cannot attach the container on windows OS (seems calling shell from the host):

$ docker exec -it a905890074b9015c2e17de9b56144cdafbd858da7a26c2e69d0627c30e3b959a /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/sh\": stat C:/Program Files/Git/usr/bin/sh: no such file or directory": unknown

Extension version: 1.2.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
Hey @mwithi, this is a known issue with Git Bash (#462). Git Bash is doing something it should not be doing (namely, changing the slashes), causing the command to fail.

In the short term, you can fix this by changing the setting `docker.attachShellCommand.linuxContainer` from the default of `/bin/sh` to `//bin/sh`. We are planning to deprecate that setting and redo shell attach at some point in the future, which will fix this issue for good.
