### ISSUE TITLE
Cannot read property 'filter' of null during BuildImage

### ISSUE THREAD

**Issue by samirpatry** [microsoft/vscode-docker#2072]
Cannot read property 'filter' of null during BuildImage

![image](https://user-images.githubusercontent.com/46788546/84900851-4a9d6c00-b0c8-11ea-897b-6ea9fa78a193.png)

**Comment by bwateratmsft** [comment]
This looks similar to #2030. @samirpatry, do you have any custom values for any of the `docker.commands.*` settings?

**Comment by samirpatry** [comment]
> This looks similar to #2030. @samirpatry, do you have any custom values for any of the `docker.commands.*` settings?

NO. Anywhere i can check this. 

Note: Very new to VSCode.

**Comment by bwateratmsft** [comment]
No problem! Let's check your settings.

1. Open the command palette (<kbd>F1</kbd> by default)
1. Type in "open settings", look for the command "Preferences: Open Settings (JSON)"
1. This will open a small or even empty JSON file containing all of your user-customized settings. In here, look for anything called `"docker.commands.*"`.

**Comment by samirpatry** [comment]
Yes its there.
"docker.commands.build": null,
Whats should i set here ?

{
    "[go]":  {
        "editor.formatOnSave": false
    },
    "go.formatTool": "goimports",
    "vs-kubernetes": {
        "vs-kubernetes.kubectl-path.windows": "C:\\Users\\samir.patry\\.vs-kubernetes\\tools\\kubectl\\kubectl.exe",
        "vs-kubernetes.minikube-path.windows": "C:\\Users\\samir.patry\\.vs-kubernetes\\tools\\minikube\\windows-amd64\\minikube.exe",
        "vs-kubernetes.helm-path.windows": "C:\\Users\\samir.patry\\.vs-kubernetes\\tools\\helm\\windows-amd64\\helm.exe",
        "vs-kubernetes.draft-path.windows": "C:\\Users\\samir.patry\\.vs-kubernetes\\tools\\draft\\windows-amd64\\draft.exe",
        "vs-kubernetes.knownKubeconfigs": [
            "c:\\Users\\samir.patry\\Desktop\\temp\\config"
        ],
        "vs-kubernetes.kubeconfig": "c:\\Users\\samir.patry\\Desktop\\temp\\config"
    },
    "[dockerfile]": {
    
    
    },
    "docker.commands.build": null,
    "vsdocker.imageUser": "rajviva",
    "docker.volumes.sortBy": "Label"
}

**Comment by bwateratmsft** [comment]
You should remove it entirely, the default setting will work for you for now.

**Comment by samirpatry** [comment]
Yes working fine now.

**Comment by bwateratmsft** [comment]
Glad it's working now! Please let us know if any other issues come up!

**Comment by samirpatry** [comment]
Thanks @bwateratmsft . We can close this.

**Comment by bwateratmsft** [comment]
We have released Docker 1.4.0 which contains a fix for this.
