### ISSUE TITLE
Running Python project with Ctrl+F5 still hits breakpoint

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2075]
**OS:** All
**Build Version:** 1.3.1-alpha

**Repro Steps:**
1. Open a python project(General/Django/Flask) in VS Code.
2. Add Docker support for it.
3. Set a breakpoint and Ctrl+F5 to run this project.

**Expect:**
Run the project successfully without breakpoint hit.

**Actual:**
It will still hits the breakpoint.

**Comment by bwateratmsft** [comment]
No a very serious issue IMO.

**Comment by ucheNkadiCode** [comment]
> Not a very serious issue IMO.

I'll investigate this likely next week, but I plan to try and run each of the projects with CTRL + F5 on the regular python Launch configs for the respective languages and see if it skips over a breakpoint. 

If I am able to repro this issue, what are the next steps?

**Comment by bwateratmsft** [comment]
> If I am able to repro this issue, what are the next steps?

We need to decide if it's actually important enough to matter. :smile:

**Comment by int19h** [comment]
For Python, running with debugging can have a substantial perf penalty in some cases - it's not a cooperative runtime like .NET or Node.js, so tracing is not zero-cost even sans breakpoints. 

It's probably an easy fix - check whether "noDebug" property in the debug config that you get from VSCode is propagated to debugpy adapter.

**Comment by bwateratmsft** [comment]
@int19h Ah, I didn't realize that was how it worked (VSCode passes a property in that we need to pass along). If so, it is probably the same underlying issue as #2024 and fixed by #2093. I'll try it out.

**Comment by bwateratmsft** [comment]
Yup, indeed that was the case so I'll mark this fixed by #2093.
