### ISSUE TITLE
Python docker debug launch - Cannot read property 'python' of undefined

### ISSUE THREAD

**Issue by revmischa** [microsoft/vscode-docker#2077]
Does this occur consistently? Yes
Repro steps:
Create launch config: https://code.visualstudio.com/docs/containers/debug-common#_python

```
"configurations": [
    {
      "name": "Docker: Python - Django",
      "type": "docker",
      "request": "launch",
      "preLaunchTask": "docker-run: debug",
      "python": {
        "pathMappings": [
          {
            "localRoot": "${workspaceFolder}/foo",
            "remoteRoot": "/srv/foo"
          }
        ],
        "projectType": "django",
        "django": true
      }
    },...
```

Action: docker-launch
Error type: TypeError
Error Message: Cannot read property 'python' of undefined

Version: 1.3.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
PythonDebugHelper.resolveDebugConfiguration extension.bundle.js:423:352918
DockerDebugConfigurationProvider.resolveDebugConfigurationInternal extension.bundle.js:492:322397
processTicksAndRejections task_queues.js:85:5
extension.bundle.js:492:322145extension.bundle.js:492:322145
```

</details>

**Comment by bwateratmsft** [comment]
@uchenkadicode is this the debugpy issue you mentioned?

**Comment by bwateratmsft** [comment]
@revmischa Did you add this launch config directly to launch.json or did you use one of the commands `Add Dockerfiles to workspace` or `Initialize for debugging` to add it?

**Comment by revmischa** [comment]
@bwateratmsft I just copied it from https://code.visualstudio.com/docs/containers/debug-common#_python

**Comment by bwateratmsft** [comment]
Ok. If you already have a dockerfile can you try doing `Docker: Initialize for debugging`, or if not `Docker: Add Dockerfiles to workspace`? This will add all the necessary launch and tasks. However, debugging will still be blocked due to #2080 which we are working on fixing ASAP.

@ucheNkadiCode, we need to update the docs to make it clearer that copying the launch config isn't sufficient.

@haniamr, we should try to detect this failure condition and give a better error message.

**Comment by revmischa** [comment]
That does solve the error at least, but I want to use docker-compose

**Comment by bwateratmsft** [comment]
We don't currently have integrated docker-compose debugging, but @haniamr might be able to help you set up an attach configuration that will work.
