### ISSUE TITLE
No matching resources found when deleting ACR

### ISSUE THREAD

**Issue by joambi** [microsoft/vscode-docker#2086]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.deleteRegistry
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 1.3.1
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:3:739112
fulfilled extension.bundle.js:3:732913
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@joambi Do any Azure registries appear in the registries list?
