### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by amrutadighe** [microsoft/vscode-docker#2088]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.3.1`
- OS Version: `Windows_NT x64 6.0.6000`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\SIS\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@amrutadighe Does this happen consistently?
