### ISSUE TITLE
Dangling docker images - not matching same command in docker cli

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-docker#209]
Thanks for merging and publishing the dangling option from my PR. I just tried the extension and it appeared to work, but on closer examination, it appears to be doing something different in VS Code than it is doing when I run the command in terminal. Is there some other logic that I missed in the vscode extension APIs?
 
Notice the left below is VS Code … and these don’t match what is to the right. I’m stumped.

![image](https://user-images.githubusercontent.com/1202528/35768673-ce04ea96-08cd-11e8-8cac-55034fc123ec.png)

From @chrisdias :
>  if i read this right the difference can be seen in the 2nd item in the list.  the extension says `<none>:<none>` and the cli says `johnpapa/angular-ngrx:<none>`

> the problem is that the library i use to get the image information doesn't easily give me the image name in that case.  given that, i just say `<none>:<none>`.  I looked into this once in the past but couldn't figure out how the docker CLI does it.  They may be looking at image IDs and somehow mapping them back to the base image. 

I created this issue so we can poke into this when we both have more time.

**Comment by 1138-4EB** [comment]
@johnpapa, @chrisdias, does any of you have access to the original comment by @chrisdias that @johnpapa quoted above? It seems that image names were not `quoted`, so they were interpreted as HTML tags and removed.

**Comment by EricJizbaMSFT** [comment]
@1138-4EB updated the comment with quotes
