### ISSUE TITLE
Use exec form of the CMD Dockerfile command in files we scaffold

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2090]
This is Docker best practice https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#cmd that ensures signals are properly delivered to the main container process and eliminates shell dependency

https://github.com/microsoft/vscode-docker/pull/2089 highlighted a problem in the Node.js Dockerfiles; there might be other places that need changing

**Comment by bwateratmsft** [comment]
Looking at the code, we already do this form for Python, CPP, and Ruby. I think only Node and Other need to be changed.

**Comment by bwateratmsft** [comment]
This has been fixed in Docker extension version 1.5.0.
