### ISSUE TITLE
Update "Deploy to Azure" article docs to include information on Docker ACI support

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2094]
The current article: https://code.visualstudio.com/docs/containers/app-service

We should add content on creating Docker ACI contexts and using Docker Hub/ACR to instantiate containers and Compose services on ACI (Azure Container Instances)

**Comment by bwateratmsft** [comment]
Moving this out of 1.7.0 to draw attention to it in triage.

**Comment by karolz-ms** [comment]
This has been done by @ghogen https://code.visualstudio.com/docs/containers/app-service#_deploy-to-aci
