### ISSUE TITLE
Debugging docker-compose projects

### ISSUE THREAD

**Issue by Deitsch** [microsoft/vscode-docker#2096]
Are there any news regarding this issue: https://github.com/microsoft/vscode-docker/issues/1765? Is possible to spin up a compose file by now?

**Comment by bwateratmsft** [comment]
Unfortunately, fully-integrated compose debugging is still not available. You can use the information in #1765 to set it up manually. I'd be happy to help get the configurations lined up so that F5 will do everything that is needed; can you tell me more about your project?

Related to #840, #1294

**Comment by Deitsch** [comment]
All good, i got it working by spinning up the compose-file in a pre task (and stopping it post). I simply attach the container run by vsc to the compose-file network. Works like a charm!

**Comment by bwateratmsft** [comment]
Awesome, I'm glad you got it working!
