### ISSUE TITLE
The error is inconsistent when single remove default context and remove it with other contexts together

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2098]
**OS:** Win 10
**Build Version:** 20200623.1

**Repro Steps:**
1. Make sure there are several contexts in Docker context view and use default context.
2. F1 --> Docker Contexts: Remove... --> Select all context to remove.
3. Check the error message.

**Expect:**
An error indicating that the in use context will not be removed.
![image](https://user-images.githubusercontent.com/45614674/85495284-c9d0f980-b60c-11ea-971b-d8d174245ddf.png)

**Actual:**
The error is "Process 'docker context rm default' exited with code 1".
![image](https://user-images.githubusercontent.com/45614674/85495333-e4a36e00-b60c-11ea-818e-fa4097baf405.png)

**More Info:**
1. An error indicating that the in use context will not be removed if there is only one default context.
2. The error is "Process 'docker context rm default' exited with code 1" when using other context and remove the default context.

**Comment by bwateratmsft** [comment]
I think we should disable multi-select on the Contexts view; there isn't really a good use case for mass deleting them.

**Comment by bwateratmsft** [comment]
@v-ruizh We made changes so that you cannot remove the currently-selected context nor the default context. The "Remove" option is hidden from the right-click menu and any current/default contexts will not show in the command palette if you do remove from there.

Thanks!
