### ISSUE TITLE
VSCode error while connecting to docker cli

### ISSUE THREAD

**Issue by dilshod2017** [microsoft/vscode-docker#2101]
Could not connect to docker cli

Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 1.3.1
OS: linux
OS Release: 5.4.0-37-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerHubAccountTreeItem.<anonymous> extension.bundle.js:3:739112
fulfilled extension.bundle.js:3:732913
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@dilshod2017 Do you have any registries connected in the explorer?

**Comment by dilshod2017** [comment]
@bwateratmsft No, I freshly installed ubuntu, vscode, and extension only.

**Comment by bwateratmsft** [comment]
The `Docker Registries: Log In to Docker CLI` command only works if you have registries attached in the explorer view. If you want to manually log in by providing a server / username / password, you will need to use the terminal directly.
