### ISSUE TITLE
x

### ISSUE THREAD

**Issue by romlarios** [microsoft/vscode-docker#2104]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.4.0
OS: win32

**Comment by bwateratmsft** [comment]
@romlarios This is a very old version of the Docker extension, you need to update.
