### ISSUE TITLE
when i runing my image, Cannot read property 'filter' of null.

### ISSUE THREAD

**Issue by helinux** [microsoft/vscode-docker#2108]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.run
Error type: TypeError
Error Message: Cannot read property 'filter' of null

Version: 1.3.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.46.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
selectCommandTemplate extension.bundle.js:3:599908
Object.selectRunCommand extension.bundle.js:3:601113
runImageCore extension.bundle.js:576:811304
processTicksAndRejections task_queues.js:85:5
async runImage extension.bundle.js:576:811526
```

</details>

**Comment by bwateratmsft** [comment]
@helinux This looks to be the same as #2072. I suspect you have a VSCode setting for `docker.commands.run` set to `null`; you need to remove this entry.
