### ISSUE TITLE
Not able to deploy image to Azure App Service

### ISSUE THREAD

**Issue by kelvin1794** [microsoft/vscode-docker#2109]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 1.3.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
getNewSiteConfig extension.bundle.js:576:502932
processTicksAndRejections task_queues.js:85:5
async deployImageToAzure extension.bundle.js:576:502395
async deployImageToAzure extension.bundle.js:3:667747
```

</details>

**Comment by bwateratmsft** [comment]
This is the same root issue as #1685. Azure App Service does not support using ACRs without admin enabled. This limitation is outside of our control. You can read about enabling admin on an ACR here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account

**Comment by kelvin1794** [comment]
Thanks @bwateratmsft
