### ISSUE TITLE
Task hangs forever when executing "Build Image..." from Dockerfile

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2110]
**OS:** Win 10
**Build Version:** 20200625.4

**Repro Steps:**
1. Open a .NET Core MVC or console app.
2. Add Docker support.
3. Right click Dockerfile --> Build Image... --> Check the result.

**Expect:**
Succeed to build image.

**Actual:**
The state keeps "Executing task: Workspace: docker-build: release".
![image](https://user-images.githubusercontent.com/45614674/85988078-1eb3ac00-ba21-11ea-90aa-bd4af6a96259.png)

**Comment by bwateratmsft** [comment]
I wasn't able to reproduce in a quick test. @v-ruizh Does this happen consistently? If you restart Docker Desktop does it continue to happen?

**Comment by v-ruizh** [comment]
@bwateratmsft Yes, this issue reproduces consistently. I have verified this issue on several machines using master build 20200629.7, all of them can reproduce this issue. The .NET Core Version is 5.0.100-preview.6.20318.15. Please feel free to contact me if you still can't reproduce it. I can share my machine to you.

**Comment by bwateratmsft** [comment]
Thanks, I am able to reproduce easily in the Insiders build. I'll investigate. Surprisingly, it does not reproduce on F5, which is also doing a `docker build` call.

**Comment by bwateratmsft** [comment]
Looks to be this issue: https://github.com/microsoft/vscode/issues/101412

**Comment by bwateratmsft** [comment]
Verified this is fixed now in the latest versions of VSCode Insiders.
