### ISSUE TITLE
Intellisense still requires CTRL + SPACE

### ISSUE THREAD

**Issue by phil-harmoniq** [microsoft/vscode-docker#2112]
I found [this previous issue](https://github.com/microsoft/vscode-docker/issues/243) and it seemed like a PR was made to fix this, but I still have to manually hit CTRL + SPACE to get hints in docker-compose files.

Extension version: 1.3.1
VS Code version: 1.46.1

**Comment by bwateratmsft** [comment]
@phil-harmoniq What's the name of your compose file?

**Comment by phil-harmoniq** [comment]
I just realized that it was because I was using the remote feature and needed to also install the extension on the server. It seems to be working as expected now.

**Comment by bwateratmsft** [comment]
Ah, glad it's working now. Let us know if you experience any other issues!
