### ISSUE TITLE
Error - command 'vscode-docker.configure' not found 

### ISSUE THREAD

**Issue by jvalrog** [microsoft/vscode-docker#2113]
I know this is an old issue but I'm facing it right now.

Ubuntu: 20.04
Docker: 19.03.8
VSCode: 1.46.1
Docker extension: 1.0.0

I've tried everything but the extension doesn't work, any command outputs: `command 'vscode-docker.configure' not found `.

Please help.

**Comment by bwateratmsft** [comment]
That's an older version of the Docker extension, can you try upgrading to the latest (1.3.1) and see if the issue persists?

**Comment by jvalrog** [comment]
Hello, I forgot I was running Codium instead of Code. Installed Code and now I see the right extension version.

Thanks you!

**Comment by bwateratmsft** [comment]
Ok, let us know if you encounter any other issues!
