### ISSUE TITLE
Support creating a new SSH or HTTP(S) context from the Contexts panel

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2115]
Similar to the + sign in the Networks panel we should support creating a SSH context. Once we support ACI and SSH context creation the + sign icon should prompt user for type of context. For SSH we should prompt for endpoint.

**Comment by karolz-ms** [comment]
@BigMorty what about

- `tls`, `tlscacert`, `tlscert`, `tlskey`, and `tlsverify` options
- Certificate path (`DOCKER_CERT_PATH` equivalent)

See https://docs.docker.com/engine/context/working-with-contexts/#the-anatomy-of-a-context and https://docs.docker.com/engine/reference/commandline/cli/ for reference

**Comment by BigMorty** [comment]
We should talk with Docker folks and see what is most common. When I created a context to use against the Azure VM you shared with me there were not many params I had to specify. I am not suggesting we support every possible combination.

**Comment by karolz-ms** [comment]
Also, if one is not very familiar with how SSH works and how to set up SSH agent for key management, the SSH context created by VS Code will not work.

**Comment by BigMorty** [comment]
Good point. Let's think about this and discuss more. This is lower priority than the create ACI context anyways.

**Comment by bwateratmsft** [comment]
We're talking about 0.2% of the population using SSH, I don't see how that justifies much effort...

**Comment by dbreshears** [comment]
Closing stale issue as Not planned
