### ISSUE TITLE
Please help entry not found in cache

### ISSUE THREAD

**Issue by dmarinere** [microsoft/vscode-docker#2122]
Does this occur consistently? 
Repro steps:

1. Which one is entry not found in cache again 
2.

Action: vscode-docker.registries.azure.buildImage
Error type: Error
Error Message: Entry not found in cache.

Version: 1.3.1
OS: linux
OS Release: 5.4.0-39-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902
extension.js:229:54224
extension.js:229:52217
extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@dmarinere Can you add repro steps?

**Comment by dmarinere** [comment]
I tried to build a docker image from a code in my system directly to Azure registry and that was the error, I had to first build it in my system.
The way i do this now is through Docker and Github has I wasnt able to do it and I don't want to download and be uploading to online as this drains my data

**Comment by bwateratmsft** [comment]
Looks like it is this upstream issue: https://github.com/microsoft/vscode-azure-account/issues/53

According to https://github.com/microsoft/vscode-azurefunctions/issues/2068, you can reload VSCode or sign out and back into Azure to fix it.

**Comment by dmarinere** [comment]
Hello, Please respond  and if you are not sure about my issue to refer me to someone else, you do not understand my problem and you are telling me something that is not related at all
I was able to create docker images only if I had pushed them to my docker which is costing me data, but to push my repo directly and create this image on the cloud is what has been generating this error

To explain clearly, 
I can create a docker image on my system push it to Azure container registry then azure container instance
But I am not able to directly build an image to Azure container registry from my System, is this something normal or what 

It is annoying to find someone who doesn't understand a problem come and say something as annoying and unhelpful as you did, my account has no issue and also my Azure docker is working perfectly
