### ISSUE TITLE
AspNetCore3.1 Docker deugger not working

### ISSUE THREAD

**Issue by hassanrazakhalid** [microsoft/vscode-docker#2127]
Does this occur consistently? 
Repro steps:

1.Used command Docker: Initialize for Docker debugging 
2.Clicked on Play button
3.Then i see the following error

Action: docker-launch
Error type: 1
Error Message: Process '/Users/hassanrazakhalid/.vsdbg/getvsdbg.sh -v late...' exited with code 1
Error: dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
/Users/hassanrazakhalid/.vsdbg/getvsdbg.sh: line 357: 42362 Abort trap: 6           wget -q "$url" -O "$vsdbgCompressedFile"

Version: 1.3.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:3:286702
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
Looks like an issue in debugger download.

**Comment by bwateratmsft** [comment]
@hassanrazakhalid Have you made any changes that might affect `wget`? It seems `getvsdbg.sh` is not getting what it needs.

**Comment by hassanrazakhalid** [comment]
Nope but i solved it the issue by downgrading  to libss l.1.0.0.dylib for now. Somehow it was not picking up the latest version already installed on my machine.

**Comment by bwateratmsft** [comment]
Ok, glad it's working now.
