### ISSUE TITLE
Substitution with environment variables

### ISSUE THREAD

**Issue by cecilphillip** [microsoft/vscode-docker#2132]
#1094 is closed, so I'm opening a new one here.
Variable substitution using `${env:var}` doesn't seem to be working for me when I try to set it in the `localPath` property under `volumes`. I'm using version 1.3.1 on MacOS.
Predefined variables like `${workspaceFolder}` work though.

Running the following task outputs the expected path.
```json
 {
      "label": "echo",
      "type": "shell",
      "command": "echo ${env:HOME}"
 }
```
When I run the container using the extension, the docker run command contains ` -v "${env:HOME}/.aspnet/https:/https:ro"` versus ` -v "/home/myuser/.aspnet/https:/https:ro"`

my configured task looks like this..
```json
{
      "type": "docker-run",
       "label": "docker-run: website debug",
       "dependsOn": [
             "docker-build: website debug"
         ],
         "dockerRun":  {
             "volumes": [
              {
                  "localPath": "${env:USER}/.aspnet/https",
                  "containerPath": "/https",
                  "permissions": "ro"
              }
             ]
            },
            "netCore": {
                "appProject": "${workspaceFolder}/src/ContosoCrafts.WebSite/ContosoCrafts.WebSite.csproj",
                "enableDebugging": true
            }
},
```

**Comment by bwateratmsft** [comment]
This one is the same as #1961, ultimately same as #1413. @cecilphillip, we need changes from the VSCode team to unblock this scenario, do you mind commenting on https://github.com/microsoft/vscode/issues/81007 to encourage them to make said changes? :smile:
