### ISSUE TITLE
v1.3.1 - No images or containers panels

### ISSUE THREAD

**Issue by shoaib-xo** [microsoft/vscode-docker#2133]
Same as https://github.com/microsoft/vscode-docker/issues/1609 and the fix isn't applicable. There are no leftover settings and the context menu doesn't even have the Images/Containers. Features Contributions tab lists images & containers.

- Uninstalled Docker Explorer & Docker
- Installed Docker, still no images or containers panels
- All kind of restarts.

![image](https://user-images.githubusercontent.com/37289032/86792365-d9782580-c083-11ea-98a0-10076c8eeb42.png)

VSCode
======
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-33-generic snap

**Comment by bwateratmsft** [comment]
@shoaib-xo Can you check the Files tab? The view moving code permanently places them in the Files tab if Docker Explorer activates first.

**Comment by shoaib-xo** [comment]
My bad, the "reset location," from files tab placed them in the correct spot.
