### ISSUE TITLE
Unable to Pull fro VsCode

### ISSUE THREAD

**Issue by sagarg1988** [microsoft/vscode-docker#2136]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username sagarg1988 --password-stdin
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.2.1
OS: linux
OS Release: 5.3.0-51-generic
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:203:13
Pipe.<anonymous> net.js:588:12
```

</details>

**Comment by bwateratmsft** [comment]
@sagarg1988 Have you added your user to the `docker` group? https://docs.docker.com/engine/install/linux-postinstall/
