### ISSUE TITLE
docker hub connection failed

### ISSUE THREAD

**Issue by shwang1a** [microsoft/vscode-docker#2137]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: 位址「disabled:」有不明或不支援的傳輸「disabled」

Version: 1.3.1
OS: linux
OS Release: 3.10.0-1127.13.1.el7.x86_64
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

**Comment by bwateratmsft** [comment]
@shwang1a can you add repro steps and translate the error message?
