### ISSUE TITLE
There is an error "Cannot read property 'containerId' of undefined" when executing command "Docker Container: Stop"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2138]
**OS:** Mac
**Build Version:** 20200708.11

**Repro steps:**

1. F1 --> Docker Container: Stop --> Select a running container.
2. Check the result.

**Expect:**
Stop the running container successfully without any error.

**Actual:**
There is an error "Cannot read property 'containerId' of undefined".
![Screen Shot 2020-07-09 at 10 57 34 AM](https://user-images.githubusercontent.com/62053665/87001982-4e19a400-c1eb-11ea-91e7-7848018684d9.png)

**More info:**
This issue does not reproduce when right clicking this running container and selecting 'stop".

Action: vscode-docker.containers.stop
Error type: TypeError
Error Message: Cannot read property 'containerId' of undefined

Version: 1.3.2-alpha
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code - Insiders
Product Version: 1.47.0-insider
Language: en

**Comment by bwateratmsft** [comment]
I can repro. Looks like this would also affect Start and Restart the same way.
