### ISSUE TITLE
Connect Docker registry prompt won't go or cannot make it go away

### ISSUE THREAD

**Issue by grajsb** [microsoft/vscode-docker#2139]
![Annotation 2020-07-09 171646](https://user-images.githubusercontent.com/13052578/87036163-01909180-c208-11ea-87cc-db016a52597f.png)
Issue Type: <b>Bug</b>

Clicked on connect to registry to add details but chose not to. However was unable to make the Connect Docker Registry prompt go away.

Extension version: 1.3.1
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
Hitting <kbd>Esc</kbd> works for me, can you try that? Clicking elsewhere intentionally does not close this since it is considered a "wizard".
