### ISSUE TITLE
Cannot read property 'python' of undefined

### ISSUE THREAD

**Issue by django-diletante** [microsoft/vscode-docker#2141]
Does this occur consistently? Yes 
Repro steps:

1. Following this tutorial, for a general python script
2. launching the "Build, run, and debug the container"

Action: docker-launch
Error type: TypeError
Error Message: Cannot read property 'python' of undefined

Version: 1.3.1
OS: linux
OS Release: 4.15.0-109-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

```
PythonDebugHelper.resolveDebugConfiguration extension.bundle.js:423:354415
processTicksAndRejections task_queues.js:85:5
async DockerDebugConfigurationProvider.resolveDebugConfigurationInternal extension.bundle.js:492:321098
extension.bundle.js:492:320854extension.bundle.js:492:320854
```

</details>

**Comment by bwateratmsft** [comment]
@django-diletante Did you add the tasks as well by doing "Docker: Add Docker files to workspace" or did you just copy the launch config from the tutorial?

**Comment by django-diletante** [comment]
Hi. bwateratmsft thanks for your fast answer. 
I did Docker: Add Docker files to workspace.

**Comment by django-diletante** [comment]
Hi Brandon, thanks for your fast answer.
I did "Docker: Add Docker files to workspace"

**Comment by bwateratmsft** [comment]
Ok, in that case it's likely the same as #2085, so I'll close this one as duplicate.
