### ISSUE TITLE
Attach to shell error

### ISSUE THREAD

**Issue by devjavivazz** [microsoft/vscode-docker#2142]
Does this occur consistently? Yes
Repro steps:
1. Right click over container 
2. Click on Attach to shell

Action: vscode-docker.containers.attachShell
Error type: TypeError
Error Message: Cannot read property 'filter' of null

Version: 1.3.1
OS: win32/64
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

</details>

**Comment by bwateratmsft** [comment]
Duplicate of #2072. @devjavivazz, please open your settings.json and remove the entry for "docker.commands.attach".
