### ISSUE TITLE
unable to connect hub.docker.com registry

### ISSUE THREAD

**Issue by minesh1291** [microsoft/vscode-docker#2144]
Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached

Version: 1.3.1
OS: linux
OS Release: 5.3.0-1030-gcp
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

**Comment by bwateratmsft** [comment]
This is an external error in gnome-keyring. I did a short search but only found one good answer, basically to install `gnupg2` and `pass`. https://stackoverflow.com/questions/50151833/cannot-login-to-docker-account
