### ISSUE TITLE
Feature Requested: Search/ Filter for container and images name

### ISSUE THREAD

**Issue by chandanjainn** [microsoft/vscode-docker#2147]
My workspace happens to contain 100+ images and containers so it would be great to have a filter to search by name

**Comment by bwateratmsft** [comment]
Good news, this is possible already! VSCode has built-in searching and filtering in all tree view. To search, click anywhere in the box and start typing.

Searching:
![image](https://user-images.githubusercontent.com/36966225/87307398-8967eb80-c4e7-11ea-90b6-5434fd9bfb6a.png)

To filter, hover over that search text in the top right, and enable filtering:
![image](https://user-images.githubusercontent.com/36966225/87307455-a13f6f80-c4e7-11ea-8571-5166b6876679.png)
