### ISSUE TITLE
error during connect:

### ISSUE THREAD

**Issue by DaniloOP1381521** [microsoft/vscode-docker#2149]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login  --username danilo1988 --password-stdin
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/auth: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Version: 1.3.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@DaniloOP1381521 is Docker Desktop running?

**Comment by DaniloOP1381521** [comment]
> @DaniloOP1381521 is Docker Desktop running?

not the error occurs in the terminal. more correction has already been resolved. thank you!

**Comment by bwateratmsft** [comment]
Ok, let us know if you see other issues!
