### ISSUE TITLE
Contexts UI not working

### ISSUE THREAD

**Issue by dmaglio** [microsoft/vscode-docker#2155]
![image](https://user-images.githubusercontent.com/446573/87401290-3b6fe800-c5ba-11ea-880b-885d2ffac5e4.png)
the option ``--format`` is missing in ``docker context ls``, also ``docker: 'context' is not a docker command.``

**Comment by bwateratmsft** [comment]
@dmaglio what version of Docker do you have? Can you run `docker info`?

**Comment by dmaglio** [comment]
@bwateratmsft Docker Legacy for Windows
``
λ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 19.03.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.154-boot2docker
Operating System: Boot2Docker 19.03.5 (TCL 10.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.5MiB
Name: default
ID: TFCA:2FKR:NXEG:FTEN:RLA6:FKXS:AT3R:WBM6:VTUV:OPGU:MLOE:JH5L
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: 192.168.99.100,localhost
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
``

**Comment by bwateratmsft** [comment]
Do you mean Docker Toolbox?

**Comment by dmaglio** [comment]
yes. not Hyper-V version, Virtualbox

**Comment by bwateratmsft** [comment]
Gotcha. Is anything other than context-related features not working, or are there any toasts with "Report Issue" showing up without running any commands? Or is the only error the one in the screenshot in the Contexts view?

If Docker Toolbox doesn't support `docker context` there's really nothing we can do, but as long as other features are working I'd consider it a success.
