### ISSUE TITLE
The outdated image state is not changed after reopening VS Code and waiting for 1 min

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2162]
**OS:** All
**Build Version:** 20200714.2

**Repro steps:**
1. Open Docker view, if the image "alpine:latest" is present, remove it: docker rmi alpine:latest.
2. Pull any image, and tag it as "alpine:latest": docker pull hello-world:latest && docker tag hello-world:latest alpine:latest.
3. Remove the "hello-world:latest" image: docker rmi hello-world:latest.
4. Restart VS Code, then check the state of the image "alpine:latest" after 1 min.

**Expect:**
The "alpine:latest" image should appear with the warning icon and text reading "Out of date".
![image](https://user-images.githubusercontent.com/45614674/87516488-0d6ccf80-c6b0-11ea-9627-4d13ab5b6f67.png)

**Actual:**
The "alpine:latest" image is not "Out of date", it will be "Out of date" after refreshing the image view manually.
![image](https://user-images.githubusercontent.com/45614674/87516695-62104a80-c6b0-11ea-8c38-2d9acf4deb96.png)

**Comment by bwateratmsft** [comment]
@v-ruizh Does this issue happen consistently? I tried several times but could not get it to reproduce; there is code to automatically refresh the images list after the image check finishes.

**Comment by v-ruizh** [comment]
@bwateratmsft Yes, this issue happens consistently. I have sent a video to you by Teams.

**Comment by bwateratmsft** [comment]
@v-ruizh Thanks! I saw on the video that there was only one image, so I tried removing all my images except the "fake" `alpine:latest`, but it still did not reproduce the issue. I think it must be some sort of timing issue, I will investigate.

**Comment by bwateratmsft** [comment]
I've tried a bunch of different things and I cannot reproduce the issue. The feature is now disabled by default though so I don't think it's critical.
