### ISSUE TITLE
Don't display "Getting digest..." status when executing "Copy Image Digest" on a task run

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2163]
**OS:** All
**Build version:** 20200714.2
**.NET Core SDK:** 2.1

**Repro Steps:**

1. Command palette -> Docker Images: Run Azure CLI.
2. Run these commands in the new terminal to set environment variables:
 ```
 ACR_NAME=registry-name
 GIT_USER=github-username
 GIT_PAT=personal-access-token
 az login
 az account set -s your-subscription-name
 az acr task create --registry $ACR_NAME --name taskhelloworld --image helloworld:{{.Run.ID}} --context https://github.com/$GIT_USER/acr-build-helloworld-node.git --branch master --file Dockerfile --git-access-token $GIT_PAT
 ```
3. Expand the build task named 'taskhelloworld' from the REGISTRIES window.
4. Execute "Run Task".
5. Click "Copy Image Digest" on a task run.

**Expect:**
Display "Getting digest..." status, such as:
![image](https://user-images.githubusercontent.com/62053665/87519515-4c048900-c6b4-11ea-96b9-044d2e3b5f15.png)

**Actual:**
Don't display "Getting digest..." status.
![image](https://user-images.githubusercontent.com/62053665/87520359-6ee36d00-c6b5-11ea-8d09-237c75edd386.png)

**Comment by bwateratmsft** [comment]
For ACR task runs, we already have the output image and digest, and don't need to make a web request. So, we simply put the digest in the clipboard without the "Getting digest..." text. I'll close this as by-design.
