### ISSUE TITLE
Bug: Using port 2376 + No SSL/TLS => Extension cannot establish connection (TLS Failure)

### ISSUE THREAD

**Issue by ntziolis** [microsoft/vscode-docker#2164]
While it is pretty standard to use SSL/TLS when port 2376 is specified the extension should not assume this as a given.

When using docker from the command line incl from within vscode) there were no issues when using the same host + port configuration.

When exposing the remote docker host + vscode settings to use port 2375 the extension can connect just fine. No other configuration was changed.

**Comment by bwateratmsft** [comment]
@ntziolis This is a function of `docker-modem` which is used by `Dockerode` in our extension: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L44

Can you file this issue there? Thanks!

**Comment by ntziolis** [comment]
Done, thanks for identifying where this should land instead. Much appreciated.
