### ISSUE TITLE
[Python] Prompt to replace requirements.txt

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2179]
In using an older Django project, I realized that the requirements.txt file was stale with just 

```docker
django
gunicorn
```
As an end user, I wouldn't know what to add as the "lastest" version of Django/Gunicorn so it could help out in the case they are already using **Add Dockerfiles to Workspace** they at least have the option to overwrite their requirement.txt.

**Comment by bwateratmsft** [comment]
Another scaffolding item to solve along with the scaffolding refactoring...
