### ISSUE TITLE
Linter error "There can only be one CMD instruction in a Dockerfile." does not always apply

### ISSUE THREAD

**Issue by Korijn** [Microsoft/vscode-docker#218]
In multi-stage builds, it can be reasonable to have a different CMD instruction for different build targets (e.g. dev vs. release). The linter error "There can only be one CMD instruction in a Dockerfile." is then quite bothersome. Is there an option to disable this linter error?

**Comment by rcjsuen** [comment]
Hi, @Korijn. Thank you for your bug report.

Please see rcjsuen/dockerfile-utils#22.

**Comment by Korijn** [comment]
Nice. Thanks!
