### ISSUE TITLE
Create and use better sample projects in our tutorials

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2184]
We should create a simple sample app, one that uses an environment variable that gets written to the log and/or screen in our tutorials.

**Comment by karolz-ms** [comment]
Is this issue just about Python?

**Comment by BigMorty** [comment]
Python for sure, I want to check on .NET and Node.js as well.

**Comment by BigMorty** [comment]
All three language tutorials have the user add an env variable now.
