### ISSUE TITLE
The dialog "Do you want to copy the debugger to the container" still pops up for the second debugging

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2186]
**OS:** Win 10/Mac
**Build Version:** 20200722.19

**Repro Steps:**
1. Create a .NET Core mvc app by "dotnet new mvc --name mvctest".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to copy debugging to the container.
7. Disconnect this attach, then F5 and connect to the same container.

**Expect:**
There shouldn't be any prompt to copy debugger.

**Actual:**
The dialog "Do you want to copy the debugger to the container" still pops up.
![image](https://user-images.githubusercontent.com/45614674/88266417-c57a2800-cd01-11ea-9a35-5926608f0e85.png)

**More Info:**
This issue does not reproduce on the latest released Docker extension build.

**Comment by karolz-ms** [comment]
I am actually not able to complete step 6 successfully ☹️ I am getting the following error instead (starting the debugger inside the container fails):

```shell
Starting: "docker" exec -i mvctest_mvctest_1 /remote_debugger/vsdbg --interpreter=vscode
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "no such file or directory": unknown
```

Note I am running Docker Edge 2.3.3.2 build 46784

**Comment by karolz-ms** [comment]
Seems like the vsdbg scripts are incorrectly encoded (CR-LF vs LF)...

**Comment by karolz-ms** [comment]
OK the problem above turned out a line ending mismatch that git did not detect. Needed to delete the file and do `git checkout --force` on the path to have it updated. 🙄 Back to the bug...

**Comment by karolz-ms** [comment]
Fixed by https://github.com/microsoft/vscode-docker/commit/0645b1c403609ae250a103d8e90fa5b40293b258

Thanks for reporting @v-ruizh !
