### ISSUE TITLE
Executing interactive commands as tasks prevents recreating new identical ones

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2188]
The logic to change CLI commands into tasks has caused one issue--if a task of the exact same command line is running already (one of the interactive ones, basically), another of the same cannot be executed.

For example, choose an Alpine image, and do "Run Interactive", which will open a task that will stay running. Do the same thing again, and instead of running a second container interactively, the task system says the task is already running. Arguably, this behavior is correct for attach shell (if you have a shell attached to a particular container already, it will simply direct you back to that shell, rather than making a new one), but I think it's sub-ideal for run interactive in particular.

**Comment by bwateratmsft** [comment]
I found an easy way to do this, and we can choose on a per-command basis what the behavior should be.

"Run Interactive", "Attach Shell", and "View Logs" are the potentially interactive commands. @BigMorty - which commands do you think should always open a new task, and which should re-use an already-running task? Personally I think "Run Interactive" should always run a new container, "View Logs" should open an existing one, and I could go either way on "Attach Shell". Do you think there's a use case for attaching multiple shells to the same container?

**Comment by karolz-ms** [comment]
I definitively think there are cases when attaching more than one shell will be useful

**Comment by BigMorty** [comment]
I agree with what you guys decided above.
