### ISSUE TITLE
Fail to show the Docker assets with error "This view is not supported in the current Docker context"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2190]
**OS:** Win 10/Mac
**Build Version:** 20200723.12
**Regression:** Previous Build 

**Repro Steps:**
1. Install the Docker extension.
2. Navigate to "Docker View" and check the Docker assets.

**Expect:**
All Docker assets show well.

**Actual:**
Fail to show the Docker assets with an error "This view is not supported in the current Docker context".
![image](https://user-images.githubusercontent.com/45614674/88356748-71238680-cd9b-11ea-8d80-a5994e3e94a0.png)

**More Info:**
1. This issue reproduces if there is only one default Docker context.
2. This issue does not reproduce if there are several Docker contexts.
3. This issue does not reproduce on the previous build 20200723.3.

**Comment by bwateratmsft** [comment]
It appears it is trying to use the new Docker SDK provider in an old context. I'll investigate.

**Comment by bwateratmsft** [comment]
I am able to reproduce.
