### ISSUE TITLE
ed1

### ISSUE THREAD

**Issue by Viniciuspnascimento** [microsoft/vscode-docker#2196]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username pinheirovinni --password-stdin
'docker' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

Version: 1.4.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
ChildProcess.EventEmitter.emit domain.js:476:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@Viniciuspnascimento It looks like Docker is not installed, can you verify that you have it installed?
