### ISSUE TITLE
Configuration property descriptions are garbled

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2199]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
Docker extension 1.41.1

![image](https://user-images.githubusercontent.com/15271049/88601677-181b5300-d026-11ea-97b1-534173908950.png)

Note descriptions for configuration properties show localization keys instead of expected information

**Comment by bwateratmsft** [comment]
@karolz-ms This would need to go either to marketplace or to VSCode core. This same issue exists for the extension title and description, and is why we reverted the description to the non-localizable string.

**Comment by bwateratmsft** [comment]
For an example, I looked at the Python extension. Their settings have hardcoded English strings in package.json, but their command names are localized. Here's what their settings show in the marketplace:
![image](https://user-images.githubusercontent.com/36966225/88670310-e8fef300-d0b2-11ea-9e39-525b37912357.png)

But their commands (mostly) have the same garbling as our settings:
![image](https://user-images.githubusercontent.com/36966225/88670373-f916d280-d0b2-11ea-9b87-938b52a66f3d.png)

I found a VSCode issue tracking this, I'll close this one as external: https://github.com/microsoft/vscode/issues/54111
