### ISSUE TITLE
Add url behaviour at docker-compose image string as Dockerfile

### ISSUE THREAD

**Issue by hildogjr** [microsoft/vscode-docker#2200]
The `Dockerfile` file allow to direct access the image page on https://hub.docker.com/ when \<Ctrl\>+\<Right click\> at the image name string in the `FROM dockerhub_imagename` line.

The same could be done in the at `docker-compose.yml` file in

```
service:
   service_name:
       image: dockerhub_imagename
```

**Comment by bwateratmsft** [comment]
Duping to #2539
