### ISSUE TITLE
Cannot generate Docker Compose files

### ISSUE THREAD

**Issue by Bruce20091128** [microsoft/vscode-docker#2201]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configureCompose
Error type: Error
Error Message: To generate docker-compose files you must first open a folder or workspace in VS Code.

Version: 1.4.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.3
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.quickPickWorkspaceFolder extension.bundle.js:3:451926
promptForFolder extension.bundle.js:494:55346
extension.bundle.js:3:1011229extension.bundle.js:3:1011229
configureCompose extension.bundle.js:494:55753
extension.bundle.js:578:827559extension.bundle.js:578:827559
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@Bruce20091128 do you have a workspace folder open?
