### ISSUE TITLE
Remote Host SSL Error on Windows 7

### ISSUE THREAD

**Issue by calee88** [microsoft/vscode-docker#2206]
Hello. I'm trying to connect to a remote docker within vscode. I'm using Windows 7. For Windows 7, there is no ssh-agent service. Instead, I found https://github.com/RaeesBhatti/ssh-agent-helper. So, now I can do docker -H ssh://{id}@{host}:{port} {command} from a newly opened cmd. But, when I set docker.host in the vscode setting, it doesn't work. It says Error: read ECONNRESET or Error: write EPROTO 74754392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242. And it also complains that I didn't configured ssh-agent.

ssh -V: OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

For more information, when I used the remote-ssh extension, the Docker extension shows the correct information. However, I can't attach to a running container with remote-ssh as far as I know from reading and my experience.

What might be the reason of the above SSL error? How can I attach to a remote Docker container?

**Comment by bwateratmsft** [comment]
Pageant should work as an SSH agent; you will need to set the environment variable `SSH_AUTH_SOCK = pageant`, more on that [here](https://code.visualstudio.com/docs/containers/ssh). Can you try out that guide and let us know if things work with Pageant?

Also, the Remote - Containers extension may have a command to attach without using the Docker extension's explorer view--I believe their extension only uses the Docker CLI, no Dockerode (this, agent auth may not be necessary). I'm away from my computer and not able to check at the immediate moment.

**Comment by karolz-ms** [comment]
> For more information, when I used the remote-ssh extension, the Docker extension shows the correct information. However, I can't attach to a running container with remote-ssh as far as I know from reading and my experience.

@calee88 can you elaborate? What is the problem/error that you are experiencing? By "attach", do you mean run another process like a shell within a container (the 'Attach Shell' command in VS Code)?

BTW even if there is some issue with VS Code Attach Shell command, you should still be able to add a shell to the container using `docker exec` command from built-in Terminal

**Comment by calee88** [comment]
> Pageant should work as an SSH agent; you will need to set the environment variable `SSH_AUTH_SOCK = pageant`, more on that [here](https://code.visualstudio.com/docs/containers/ssh). Can you try out that guide and let us know if things work with Pageant?

Nope. I set the environment variable, opened pageant, added my private key, and relaunched a vscode. Same errors. I also tried to launch vscode using pageant: pageant {key} -c code. But it also doesn't work.

> Also, the Remote - Containers extension may have a command to attach without using the Docker extension's explorer view--I believe their extension only uses the Docker CLI, no Dockerode (this, agent auth may not be necessary). I'm away from my computer and not able to check at the immediate moment.

This works. Docker view still doesn't work, but I can attach to remotely running containers. Awesome! This is enough for me now. Thank you very much for your help.

**Comment by calee88** [comment]
> > For more information, when I used the remote-ssh extension, the Docker extension shows the correct information. However, I can't attach to a running container with remote-ssh as far as I know from reading and my experience.
> 
> @calee88 can you elaborate? What is the problem/error that you are experiencing? By "attach", do you mean run another process like a shell within a container (the 'Attach Shell' command in VS Code)?
> 
> BTW even if there is some issue with VS Code Attach Shell command, you should still be able to add a shell to the container using `docker exec` command from built-in Terminal

Thank you for asking. Actually, attach shell does work. However, Attach Visual Studio Code doesn't work. "It says Docker returned an error. Make sure the Docker daemon is running."
