### ISSUE TITLE
There is a transient error in Docker view before switching to the local Docker assets

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2207]
**OS:** Windows 10
**Build Version:** 20200728.8

**Repro Steps:**
1. In VS Code local instance, use 'docker context' command to create a context for connecting to the remote machine:
    docker context create --docker "host=ssh://username@machineIP" contextname
2. Switch Docker context to the remote machine using command "docker context use contextname".
3. Switch Docker context to default using command "docker context use default".
4. Check the result in Docker view.

**Expect:**
Docker view switch to show the local Docker assets without any error.

**Actual:**
There is a transient error in Docker view before switching to the local Docker assets.
![image](https://user-images.githubusercontent.com/45614674/88766479-addfeb00-d1aa-11ea-81fa-a9632bd2b0a5.png)

**More Info:**
This issue does not reproduce if use the context by command palette or context menu.

**Comment by bwateratmsft** [comment]
This is probably a consequence of #2205

**Comment by bwateratmsft** [comment]
We can detect when a tree error is a `UserCancelledError`, maybe we can just rethrow that in the node refresh code path?
