### ISSUE TITLE
Debug points are not being hit for .NET Core app

### ISSUE THREAD

**Issue by t-dedah** [microsoft/vscode-docker#2208]
I followed the below-mentioned doc for adding debug support to .NET core app with docker. Docker container and the app is working fine but the debugging with the breakpoint is not working as per the requirements. No breakpoints are being hit.

https://code.visualstudio.com/docs/containers/debug-netcore

I have added task.json and launch.json as per the requirement.

**Comment by t-dedah** [comment]
@bwateratmsft can you please suggest something to remedy this issue?

**Comment by karolz-ms** [comment]
@t-dedah I cannot reproduce the issue using .NET Core console app. 

Can you please describe step-by-step (starting from empty folder) what have you done to create the app, build the image, run the container, and where in the code do you expect the breakpoint to be hit. Thanks!
