### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by osamashadwo** [microsoft/vscode-docker#2217]
- Issue Type: `Bug`
- Extension Name: `vscode-docker`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by karolz-ms** [comment]
@osamashadwo I noticed that you have opened two other issues, not providing any new data, but just copying conversation fragments from older, resolved issues. Please don't. It is not helpful.

If you encounter a problem with the Docker extension, please describe step-by-step what you have done, what you expected the extension to do, and what actually happened, and we will try our best to help you. We can't do much without that information.
