### ISSUE TITLE
[Suggestion] Add a clear error during debugging a project which targeted is different from Docker server host configured

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2219]
**OS:** Windows 10
**Build Version:** 20200731.1

**Repro Steps:**
1. Switch the Docker Desktop to **windows** containers.
2. Open a .NET Core web app in VS Code and add **Linux** Docker support.
3. Switch configuration to "Docker .NET Core Launch" and debug this project.

**Actual:**
An unclear error "Error response from daemon: invalid volume specification..." occurs.
![image](https://user-images.githubusercontent.com/45614674/89165580-54612d00-d5ab-11ea-9d41-20c883e4e5cf.png)

**Suggestion:**
Add a clear error during debugging a project which targeted is different from Docker server host configured, such as "Your Docker server host is configured for 'Windows', however your project targets 'Linux'".

**Comment by karolz-ms** [comment]
@dbreshears @BigMorty what say you?

**Comment by BigMorty** [comment]
We had an item for detecting the OS setting of Docker, I was a fan of doing that and telling the user things are not configured correctly, or even offering to switch it for them like we do in VS. I don't remember the reason we did not do this.

**Comment by dbreshears** [comment]
Probably was related to perf, do we know the impact of checking this with each debug?

**Comment by bwateratmsft** [comment]
@dbreshears It's a CLI call so anywhere from fraction of a second to a few seconds. Since essentially nobody actually uses Windows containers I don't see this as worthwhile.

**Comment by bwateratmsft** [comment]
We discussed in email that we'd send a [suggestion](https://github.com/docker/cli/issues/2691) to Docker and close this as won't-fix.
