### ISSUE TITLE
vscode-docker

### ISSUE THREAD

**Issue by cristianeasreis** [microsoft/vscode-docker#2221]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker.activate
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\Cris_Ricke\.docker\machine\machines\default\ca.pem'

Version: 1.4.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: pt-br

<details>
<summary>Call Stack</summary>

```
Object.openSync fs.js:447:3
Object.func asar.js:140:31
Object.func [as openSync] asar.js:140:31
Object.readFileSync fs.js:349:35
Object.fs.readFileSync asar.js:542:40
Object.fs.readFileSync asar.js:542:40
n.exports extension.bundle.js:578:1065494
extension.bundle.js:578:883745extension.bundle.js:578:883745
new Modem extension.bundle.js:578:884106
new Docker extension.bundle.js:578:865215
Object.refreshDockerode extension.bundle.js:578:864799
new DockerodeApiClient extension.bundle.js:578:858675
DockerContextManager.refresh extension.bundle.js:578:856032
processTicksAndRejections task_queues.js:85:5
extension.bundle.js:33:376731extension.bundle.js:33:376731
```

</details>

**Comment by karolz-ms** [comment]
Thanks for submitting the report, Christiane. I am pretty sure this is the same issue as https://github.com/microsoft/vscode-docker/issues/2204 We will have a fix in the next release of the extension (~ 2 weeks).
