### ISSUE TITLE
error debugging ASP.NET Core application

### ISSUE THREAD

**Issue by Siargei** [microsoft/vscode-docker#2222]
1. I created a Docker debugging configuration using command Docker: initialize for Docker debugging
2. tasks.json got updated with following configurations
` {
            "type": "docker-build",
            "label": "docker-build: debug",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "sample-project:dev",
                "target": "base",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            },
            "netCore": {
                "appProject": "${workspaceFolder}/sample-project.csproj"
            }
        },
        {
            "type": "docker-build",
            "label": "docker-build: release",
            "dependsOn": [
                "build"
            ],
            "dockerBuild": {
                "tag": "sample-project:latest",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            },
            "netCore": {
                "appProject": "${workspaceFolder}/sample-project.csproj"
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build: debug"
            ],
            "dockerRun": {},
            "netCore": {
                "appProject": "${workspaceFolder}/sample-project.csproj",
                "enableDebugging": true
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: release",
            "dependsOn": [
                "docker-build: release"
            ],
            "dockerRun": {},
            "netCore": {
                "appProject": "${workspaceFolder}/sample-project.csproj"
            }
        }`
3. launch.json got updated with following configurations
`        {
            "name": "Docker .NET Core Launch",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "netCore": {
                "appProject": "${workspaceFolder}/sample-project.csproj"
            }
        }`
4. I get the following error when try to execute newly create launch configuration

Action: docker-launch
Error type: Error
Error Message: The platform 'undefined' is not currently supported for Docker debugging.

Version: 1.4.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.getHelper extension.bundle.js:494:29840
DockerDebugConfigurationProvider.resolveDebugConfigurationInternal extension.bundle.js:494:27748
processTicksAndRejections task_queues.js:85:5
extension.bundle.js:494:27447extension.bundle.js:494:27447
```

</details>

**Comment by karolz-ms** [comment]
@Siargei could you also share the sample project that triggers the issue?
