### ISSUE TITLE
[Python] Docker-compose.debug.yml open in broswer failure

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2223]
When trying to right-click **Open in Browser** after running Compose Up on the scaffolded `docker-compose.debug.yml` file from my [Django Sample Tutorial](https://github.com/microsoft/python-sample-vscode-django-tutorial/blob/tutorial/README.md). The container successfully runs, but when I launch the browser, I receive:

![image](https://user-images.githubusercontent.com/20650058/89681140-2d577380-d8a9-11ea-9e34-c2e0d70feaf3.png)

When I right click on the running container and select **View Logs**, in the terminal I see:

```bash
docker logs -f c870ba3497191debd65205c7bc0a66452819b2ff9dafcd7a9ad7aebbde344f6d
WARNING: The directory '/home/appuser/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting debugpy
  Downloading debugpy-1.0.0b12-cp38-cp38-manylinux2010_x86_64.whl (5.6 MB)
Installing collected packages: debugpy
Successfully installed debugpy-1.0.0b12
```

Repro steps:
- Git clone the [Django Sample Tutorial](https://github.com/microsoft/python-sample-vscode-django-tutorial/blob/tutorial/README.md)
- Add docker files to workspace (say yes to compose)
- right click compose up on the `docker-compose.debug.yml` file
- On the running container from the Explorer view, right click "Open in browser"

**Comment by dbreshears** [comment]
@ucheNkadiCode . In the docker-compose-debug.yml command we pass "--wait-for-client" on the debugger so I don't believe the server is up and running yet.   If you start debugging with "Python: Attach", I find that the page is browsable from the container entry point.

**Comment by karolz-ms** [comment]
Agreed it is by design. Thanks @dbreshears for figuring out the cause of the observed behavior, much appreciated!
