### ISSUE TITLE
Error Message: Process 'docker context inspect default' exited with code 127 Error: /bin/sh: docker: command not found

### ISSUE THREAD

**Issue by lkj1114889770** [microsoft/vscode-docker#2229]
Action: vscode-docker.contexts.inspect
Error type: 127
Error Message: Process 'docker context inspect default' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.4.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.47.3
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:3:329310
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:203:13
Pipe.<anonymous> net.js:588:12
```

</details>

**Comment by karolz-ms** [comment]
@lkj1114889770  Is Docker installed in the environment that VS Code is using?

If yes, are you able to do `docker context inspect default` from terminal window running inside VS Code?

**Comment by lkj1114889770** [comment]
How to check the environment of Docker and VS Code?

**Comment by lkj1114889770** [comment]
And with `docker context inspect default `from terminal window running inside VS Code,  the terminal output
```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Comment by karolz-ms** [comment]
OK, thanks @lkj1114889770 , that looks as expected. 

Can you reproduce the problem consistently? What do you do for the error to show up?

**Comment by lkj1114889770** [comment]
In fact, i just want to attach container in VScode, but i got the error `Docker returned an error. Make sure the Docker daemon is running.` And also when i try to open flolder in container or attach to running contianer, the same erro occurs. And i try to use or inspect vscode-docker.contexts, the error message is `Error: Process 'docker context inspect default' exited with code 127 Error: /bin/sh: docker: command not found`.

But the container has been already started and, i can attach to the shell of the container by the terminal of VScode.

**Comment by karolz-ms** [comment]
And you are using Docker Desktop for Mac, correct?

**Comment by lkj1114889770** [comment]
@karolz-ms yes!

**Comment by karolz-ms** [comment]
What version of Docker Desktop?

Does logging out of the machine and back in make the issue go away?

Do you have any settings/default overrides for VS Code Docker extension?

**Comment by lkj1114889770** [comment]
Docker version 19.03.12, build 48a66213fe
logging out of the machine and back in doesn't work.
` which -a docker
/usr/local/bin/docker`

**Comment by karolz-ms** [comment]
I am sorry, I tried a few things, but I cannot reproduce the issue. From telemetry I can see this error shows up, but very rarely (about 10 times worldwide in the last 2 weeks). 

My suggestion would be to take a look at the environment of the VS Code program (`ps eww <vscode PID>`) and try to figure out why VS Code cannot find the Docker program (not on PATH?).

Please let us know if you find the cause for this error--thanks!
