### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RajputJay41** [microsoft/vscode-docker#2230]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.3.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\jayrajput\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by karolz-ms** [comment]
This is is an older version of the extension. Please re-open if the issue also occurs with version 1.4.1 or newer--thanks!
