### ISSUE TITLE
Fail to execute command "Compose Restart" after executing command "Compose Up"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2231]
**OS:** Win10/Mac
**Build Version:** 20200807.6

**Repro Steps:**

1. Create an Express App project and open it in VS Code.
2. Command Palette -> Add Docker files to workspace -> Node.js -> Enter port.
3. Right click docker-compose.yml/docker-compose.debug.yml -> Select "Compose Up".
4. A new running container appears in the Containers tree view.
5. Right click docker-compose.yml/docker-compose.debug.yml -> Select "Compose Restart".
6. Check the result.

**Expect:**
Execute command "Compose Restart" successfully without any error.

**Actual:**
Execute command "Compose Restart" failed with an error.
![image](https://user-images.githubusercontent.com/62053665/89871206-9ad90c00-dbe9-11ea-8f1c-0fc447580a57.png)

**More Info:**
This issue also reproduces for a .NET Core MVC project.

**Comment by karolz-ms** [comment]
I can reproduce. Investigating...

**Comment by karolz-ms** [comment]
What we are *trying* to do in our code is to do `compose down`, wait for that to finish, then do `compose up`. However, as we now run commands as tasks, what we are doing to wait for the task execution to finish, actually does not work. There is simply no easy way to wait for a task to finish.  https://github.com/microsoft/vscode/issues/98483 Investigating alternatives...

**Comment by karolz-ms** [comment]
Fix available. This is good bug; affects more than just this scenario and could result in unpredictable errors/race conditions. Good job, @v-mengwe !
