### ISSUE TITLE
Error response from daemon: Get https://registry.gitlab.com/v2/: denied: access forbidden

### ISSUE THREAD

**Issue by ratriv** [microsoft/vscode-docker#2236]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login registry.gitlab.com --username ratriv --password-stdin
Error response from daemon: Get https://registry.gitlab.com/v2/: denied: access forbidden

Version: 1.4.1
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by karolz-ms** [comment]
@ratriv are you able to log in to your registry and pull the image using `docker` program from the command line?

**Comment by ratriv** [comment]
> @ratriv are you able to log in to your registry and pull the image using `docker` program from the command line?

No, I am not even if using proxy and ENV settings.

I am using Docker behind Corporate NAT where I am using Proxy to connect registries but It's giving error when I use a proxy and working fine on the open internet (Using VM with personal HOTSPOT to bypass Corp Internet).
Not sure why Docker is not working with proxy.

**Comment by bwateratmsft** [comment]
@karolz-ms @ratriv I think this would be a Docker CLI bug. Gitlab is (mostly) not a V2-compliant registry, they have their own spec entirely. The Docker CLI is querying the `/v2/` endpoint but I would not expect this to succeed.

**Comment by bwateratmsft** [comment]
@BigMorty You have a GitLab test account right? Can you try pulling an image from it?

**Comment by BigMorty** [comment]
docker pull registry.gitlab.com/bigmorty/samples/webapplication11:dev worked fine for me.

**Comment by bwateratmsft** [comment]
@BigMorty How about `docker login registry.gitlab.com --username bigmorty --password-stdin`?

**Comment by BigMorty** [comment]
That did not work for me. After typing my password and pressing Enter, nothing happened, things just sat there.

**Comment by bwateratmsft** [comment]
The only thing I can think of is the proxy blocking login or potentially something transient. If the proxy is blocking the CLI from doing login to Gitlab there's nothing that can be done in the Docker extension. I'll close this as external.

**Comment by BigMorty** [comment]
Why does it work when using our extension UI?

**Comment by bwateratmsft** [comment]
The user mentioned they are behind a proxy which is probably what prevented this from working.
