### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DoctorWho8** [microsoft/vscode-docker#2237]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\hanso\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by karolz-ms** [comment]
@DoctorWho8 does it happen consistently? Can you attach the profile?
