### ISSUE TITLE
The webpage keeps loading for Django project when debugging it with "Python Remote Attach" configuration

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2239]
**OS:** Win10
**Build Version:** 20200812.1

**Repro Steps:**

1. Open a Python Django project and add Docker support for it in VS Code.
2. Right click the docker-compose.debug.yml -> Select "Compose Up".
3. Add a new "Python Remote Attach" configuration in launch.json. 
4. F5.
5. Navigate to the docker explorer, right-click the container and select "Open in Browser".

**Expect:**
Open a webpage successfully.

**Actual:**
The webpage keeps loading.

**More Info:**

1. This issue doesn't reproduce on Mac/Linux.
2. The webpage opens successfully at the second time.

**Comment by karolz-ms** [comment]
There **might** be some timing issue here, but it will be very hard to track down. I though I had a repro when I first try the scenario, but I was not able to repro after that, on many subsequent tries.

Note that `docker-compose.debug.yml` uses `--wait-for-client` flag when starting the service process under the debugger . This means no requests will be served until VS Code debug client is attached (step number 4, `F5`). But the attach is asynchronous, so if the attach does not complete before the browser hits the service endpoint (step 5), the browser might look as if the service was not responding. 

This could also be related to https://github.com/microsoft/vscode-docker/issues/2191

Without a more solid repro there is not much we can do at the moment.
