### ISSUE TITLE
command 'dockerExplorer.refreshExplorer' not found

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-docker#224]
_From @mseld on February 25, 2018 21:18_

### Issue Type
Bug

### Description

docker ext 
after system log-in open vs code click on refresh button in docker explorer 
system throws error - command 'dockerExplorer.refreshExplorer' not found

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (2.39GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
beautify|Hoo|1.3.0
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|3.2.3
vscode-docker|Pet|0.0.24
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
gitlens|eam|8.0.2
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
rest-client|hum|0.17.0
docthis|joe|0.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
gitignore|mic|1.0.1
vscode-exec-node|mir|0.5.0
python|ms-|2018.1.0
js-atom-grammar|ms-|0.1.14
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.1.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.20.0
expresssnippet|vla|0.2.3
JavaScriptSnippets|xab|1.5.0

(5 theme extensions excluded)

</details>
Reproduces only with extensions

_Copied from original issue: Microsoft/vscode#44367_

**Comment by bradygmsft** [comment]
I'm seeing the same thing. I see this when I try any of the Docker commands from the command palette, or when I try to refresh the explorer panel. It's as if the commands are turned off or de-registered. cc @fiveisprime FYI

**Comment by chrisdias** [comment]
Since this was reported against insiders and `0.0.24` of the Docker extension, I suspect it was a result of the ASAR changes. I published a new version of the Docker extension yesterday (`0.0.25`) that fixes this, so as please try with the latest insiders and docker extension.  If it still fails, please open an issue in the [vscode-docker](https://github.com/microsoft/vscode-docker/issues) repository.

**Comment by bradygmsft** [comment]
@chrisdias i'm still seeing this after the .25 update, so i'll file a bug.

**Comment by mudrii** [comment]
I can confirm same issue on Windows 10 on 0.0.25 installed

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by chrisdias** [comment]
@mudrii i suspect you have a corrupted install of the extension. this could have happened if you restarted while an update was being downloaded. That issue has been resolved, but in the meantime you can force a clean re-install by pressing `F1`, search for `Developer: Reinstall Extension...`:

![image](https://user-images.githubusercontent.com/1487073/37790513-0651721e-2dc4-11e8-9ea4-3f8baaa0cd07.png)

and then pick the `Docker` extension:

![image](https://user-images.githubusercontent.com/1487073/37790554-20d1eb00-2dc4-11e8-9d5c-dfd1ceaeec69.png)

Let me know if this doesn't resolve the issue.
