### ISSUE TITLE
docker vs

### ISSUE THREAD

**Issue by mksean13** [microsoft/vscode-docker#2242]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: ERR_INVALID_URL
Error Message: Invalid URL: 192.168.20.3

Version: 1.5.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
onParseError url.js:243:9
new URL url.js:319:5
extension.bundle.js:578:848090extension.bundle.js:578:848090
Object.<anonymous> extension.bundle.js:3:478367
extension.bundle.js:3:477558extension.bundle.js:3:477558
o extension.bundle.js:3:477244
Object.callWithTelemetryAndErrorHandling extension.bundle.js:3:478275
DockerContextManager.loadContexts extension.bundle.js:578:847430
AsyncLazy.valueFactory extension.bundle.js:578:845795
AsyncLazy.getValue extension.bundle.js:3:317996
DockerContextManager.getContexts extension.bundle.js:578:846996
DockerContextManager.getCurrentContext extension.bundle.js:578:847051
DockerContextManager.refresh extension.bundle.js:578:846409
extension.bundle.js:33:374506extension.bundle.js:33:374506
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by karolz-ms** [comment]
@mksean13 please take a look at the docs describing the remote Docker daemon configuration: https://code.visualstudio.com/docs/containers/ssh#_tips 

Hope this helps. Feel free to re-open the issue if you still have questions.
