### ISSUE TITLE
Unable to use Right Click Compose Up/Down commands

### ISSUE THREAD

**Issue by umbraesoulsbane** [microsoft/vscode-docker#2244]
Since the latest update to VSCODE I am unable to use the right click command to bring up and down containers. I get the following error which looks like the command is being sent or parsed wrong.

```
> Executing task: docker-compose -f "docker-compose.yml" down <

Parameter format not correct - -Command
```

I see there were changes to allow customizations to be done to the command, but is this expected to break the default behaviours?

**VSCODE**
Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Docker Extension Version v1.5.0

Thank you.

**Comment by umbraesoulsbane** [comment]
I should not that although the code block above is for compose down. Compose up gives the exact same error.

**Comment by karolz-ms** [comment]
@umbraesoulsbane  This is definitively not expected. Do you have a Compose file and/or project that shows the problem that you could share?

**Comment by umbraesoulsbane** [comment]
This is the project I was using which is fairly basic. Obviously I can just copy and paste the command from the error that failed and it works, so its something with how the right click menu is processing it.

https://github.com/umbraesoulsbane/dnsTools/blob/master/docker-compose.yml

This was working prior to the last monthly VSCODE update, so not sure if this was the extension or something in the VSCODE base. Figured it was best to start here.

**Comment by umbraesoulsbane** [comment]
Just to confirm I tried multiple projects with the same result, so I don't think is the compose files themselves. I have all of this projects on my Github account should you want to review. However, as I said things work fine when I manually run the command. Its just the right click which as a dyslexic I prefer to use than typing. :)

**Comment by karolz-ms** [comment]
I cannot reproduce with the same OS/VSCode/Docker extension combination and I do not see anything like this in our telemetry... 🤔 

What is the Docker Desktop version and `docker-compose` version that you are using? 
Do you have any command customization (user-level or workspace-level) turned on?

**Comment by umbraesoulsbane** [comment]
![image](https://user-images.githubusercontent.com/2028719/90812196-bf249f00-e2f3-11ea-9ac1-5bec12d4ccbb.png)

Hopefully that has enough version information.

I have not done any command customizations which I didn't even know was possible until today.

Is there any particular setting or config I need to look for specifically? I will try and review any custom settings to see if anything is out of place. 

In the end, Docker is working and so are my projects its just the right click menu which is pretty weird.

**Comment by karolz-ms** [comment]
The command we are trying to execute seems correct. I think the error is coming from the shell. What kind of shell are you using? Seems PowerShell? Is there something special about PowerShell configuration on your machine?

**Comment by umbraesoulsbane** [comment]
Yes it is powershell and I have done nothing to configure it special. On this machine specifically I have never used Powershell for anything other than the terminal in VSCODE. And this was literally working fine until I installed the VSCODE patch last week. Today was just the first time I have tried to start a docker container since the patch was installed.

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Thanks for the help. I was hoping this was something that was reproducable. I have another machine with VSCODE on it, but I cannot test it until tomorrow. Not to mention it updates based on an enterprise policy so I am not sure I have or can install the same VSCODE version. It will most likely be a few months behind.

**Comment by karolz-ms** [comment]
Suggestion: you can try VS Code Insiders build. It is side-by-side installable, so it won't mess up your stable build.

Also, both stable and insiders can be installed in "portable" way (download zip, unzip it into some folder, run the exe). So on your corp machine you might still be able to use latest version without running an installer.

**Comment by umbraesoulsbane** [comment]
Ok, sorry for the delay. So I do have the same version on my office PC. There was even an update so now both systems are on 1.48.1. The office PC appears to work fine, but I am still getting the error on my personal.

Other than Windows version everything is the same including Extensions and everything. I intentionally keep both these system in sync as much as my organization will allow me, so no idea why this is broken on my personal one. 

Is there anything I should look at? Any specific configurations or settings? Any information on how this process works so I can look at anything related?

Would any Docker configurations cause this? Docker is managed by my corp so there may be some differences there.

Any help would be great. I did nothing to set this up other than install the extension and have not changed anything between this working or not. So far the only differences between systems I can think of is the OS version and that I have Chrome Edge instead of Edge.

**Comment by karolz-ms** [comment]
@umbraesoulsbane thank you for the information, that helps

Like I said earlier, my suspicion is that `Parameter format not correct - -Command` error message comes from PowerShell. So I would zero in on differences between how PowerShell is configured on your personal machine vs other machine(s). Another possible difference is something related to system locale, how strings are quoted etc.. but that is a long shot.

For what it is worth, I am running exactly the same version of Windows, VS Code, Docker extension, PowerShell, yet I am not experiencing the issue... 🤔

**Comment by umbraesoulsbane** [comment]
Well I would agree with you, but I can post the exact command thats reported to run and it works fine. So its got to be something with how this is being passed into PowerShell from the extension. Is there a way I can get exactly what is passing? Right now I just see: 

> Executing task: docker-compose -f "docker-compose.yml" down <

So I assume that is just a comment rather than the actual command as its being sent to powershell.

**Comment by umbraesoulsbane** [comment]
Ok, I ended up doing a generic search for Parameter format not correct in powershell. This led me to enabling UTF-8 in Powershell, which I attempted to do a while back. I was able to get this to work in Powershell, but not in the Terminal in VSCODE. However, I appearently left the settings in my personal machine. Although this didn't fix my UTF-8 issue it also didn't break anything until the last VSCODE update.

I removed the following in my settings:

`	"terminal.integrated.shellArgs.windows": [
		"-NoExit",
		"/c",
		"chcp.com 65001"
	],
	"terminal.integrated.env.windows": {
		"LC_ALL": "C.UTF-8"
	},`

I still need to test with Docker up and running, but it did seem to run the right click commands without the Parameter error, so pretty sure that resolved it.

Hopefully this helps anyone that has the same issue.

**Comment by umbraesoulsbane** [comment]
Worth noting as this was something I got off the VSCODE github originally which was supposed to enable UTF-8, so I might not be the only one affected if others followed those instructions.

**Comment by karolz-ms** [comment]
@umbraesoulsbane I am glad that you figured it out! Thanks for the update

**Comment by CoonHouse** [comment]
I have/had the same issue. I am using [Cmder](https://cmder.net/) as my terminal in VScode. Since the last update the contextmenu option 'Compose Up' and 'Compose Down' no longer work.
When switching back to the default terminal in VScode, the contectmenu options work as expected.

Regards,
Wilco

**Comment by umbraesoulsbane** [comment]
@CoonHouse Are you getting the same error or something different. I have used Cmder which is a great tool but I had compatibility issues that made me drop it once I moved from Win 7 to Win 10. I think there was updates in VSCode that changed how the command is issues. As such where I had to remove custom options, you might need to add some. I would work with Cmder support as they can probably assist more than anyone here.

**Comment by umbraesoulsbane** [comment]
Also you might want to make sure you can still manually compose up and down in Cmder using the raw commands. If that doesn't work it may be a Docker issue as well. However, I assume you probably tested this.

**Comment by CoonHouse** [comment]
@umbraesoulsbane  I did get the same error. Typing the command `docker-compose -f "docker-compose.yml" up -d` did work as supposed. And before the update of VScode (or the docker plugin?) it did work with Cmder. When I switched to the internal terminal it did work. 
I just installed the latest Cmder version to check if this helps, and it did. The "compose up/down" now work (again) with Cmder. I did not try if reenabling the older version of Cmder would have fixed the problem.

**Comment by umbraesoulsbane** [comment]
I believe VSCODE changed how commands were sent to the terminal. My issues was related to customizing the character code for the console. I would imagine the older version of Cmder probably customized the shell in some fashion, and the newest version took the VSCODE/Powershell updates in mind and fixed it.

Glad you got it working.

**Comment by CoonHouse** [comment]
@umbraesoulsbane  Yes, I like Cmder over Powershell. 

Thanks
