### ISSUE TITLE
Survey prompt can show up simultaneously in multiple sessions

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2245]
If multiple VS Code sessions are started at the same time (e.g. after machine restart), and the user is selected for a survey, the current implementation will pop up a survey prompt pretty much in all sessions at the same time. That can be annoying.

We could solve this by adding a random delay to the survey prompt, so that one session with shortest delay shows the prompt, and other sessions are delayed enough to "notice" the user was already prompted.

**Comment by bwateratmsft** [comment]
Good catch @karolz-ms. Maybe we could mix the current hardcoded delay and add a slush of +/- a few seconds?

**Comment by karolz-ms** [comment]
@bwateratmsft yes, that is exactly what I had in mind
