### ISSUE TITLE
p*roblem

### ISSUE THREAD

**Issue by SpyManxD** [microsoft/vscode-docker#2249]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: TypeError
Error Message: Cannot read property '0' of undefined

Version: 1.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:494:26973extension.bundle.js:494:26973
Object.<anonymous> extension.bundle.js:3:478367
extension.bundle.js:3:477558extension.bundle.js:3:477558
o extension.bundle.js:3:477244
Object.callWithTelemetryAndErrorHandling extension.bundle.js:3:478275
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:494:26772
extensionHostProcess.js:894:493extensionHostProcess.js:894:493
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@SpyManxD Can you add repro steps?
