### ISSUE TITLE
Tree nodes in incorrect order after running prune

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-docker#225]
I have no idea how this happened. I'm on Windows, VS Code@1.20.1 (stable)

Built some images, ran some images, pushed some images, then pruned. Upon
running the prune the explorer refreshed and left me with these shenanigans.

![wat](https://user-images.githubusercontent.com/1186948/36754438-d0a06584-1bbd-11e8-887b-b7f1d7becea5.gif)

I've tried to create it with no luck and it seems like it may be a VS Code rendering
issue rather than the extension.

**Comment by StephenWeatherford** [comment]
This would be a vscode issue if it still repros.
