### ISSUE TITLE
I don't knwo what happened

### ISSUE THREAD

**Issue by kazman71** [microsoft/vscode-docker#2253]
Issue Type: <b>Bug</b>

I was running a container and viewing the logs.

Extension version: 1.5.0
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
@kazman71 There isn't any error here in what you've pasted. Can you add repro steps and describe what went wrong?
