### ISSUE TITLE
Containers panel shows connection error when ACI context is selected and Docker Desktop is shutdown

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2257]
Create an ACI context
Switch to this ACI context to be the active one in use
Shutdown Docker Desktop
Containers panel in Docker explorer show the following connection error:
![image](https://user-images.githubusercontent.com/947510/90943573-3aa74e80-e3cf-11ea-8a6f-9bdd452d509c.png)

Expected containers from the ACI context to be displayed.
Docker CLI can still list containers in the ACI context and even 'docker run' to ACI

**Comment by bwateratmsft** [comment]
Blocked on https://github.com/docker/node-sdk/issues/31.

**Comment by bwateratmsft** [comment]
Moving this out to 1.9.0 for now.

**Comment by dbreshears** [comment]
A bit of an edge case.  Seems like a lot of work to address this.
