### ISSUE TITLE
No Docker extension commands work

### ISSUE THREAD

**Issue by bradygmsft** [Microsoft/vscode-docker#226]
I'm using 0.0.25, and I've removed all my extensions down to three: 

1. Docker
1. C/C++
1. Arduino

None of the commands will work from either the command palette or from the explorer window. When I click the refresh button in the Docker explorer window I see this error:

```
command 'vscode-docker.explorer.refresh' not found
```

When I run the **Docker: Add files to workspace** command I see this error: 

```
command 'vscode-docker.configure' not found
```

**Comment by bradygmsft** [comment]
cc @chrisdias FYI

**Comment by chrisdias** [comment]
The extension isn't loading which is why you get the "command not found" errors.  Can you do a few things for me to help narrow it down:

- disable/remove the C++ and Arduino extensions and see if it repros still.  
- Open the chrome dev tools and see if there are any errors in the console (F1 > Toggle Developer Tools)
- Try the extension in STable, does it load there?

**Comment by bradygmsft** [comment]
Thanks for the tip on the debugger, Chris. I am using Stable, and when I opened the dev tools I think I immediately see the issue. Looks like there's a dependency on `vscode-extension-telemetry` in the Docker extension that's not getting pulled in? 

![cuprit](https://user-images.githubusercontent.com/35678886/36858236-723bc998-1d2f-11e8-88a0-a77a46ab1974.png)

**Comment by chrisdias** [comment]
Getting closer... :)

Can you try the extension in Insiders and see if it loads there?

Windows/Mac/Linux?

I have a suspicion that the extension didn't install/update correctly and is now in a bad state.  Uninstall and reinstall may not actually help :(.

So, try uninstalling the extension, restarting VS Code completely, and then installing it again from the marketplace.  IMPORTANT: Let me know if you see anything weird here, like the "Reload" button not being shown after uninstall or install.

From there, we may have to delete the `.vscode/extensions` folder.

Thanks.

**Comment by bradygmsft** [comment]
Mac. And **not** on Insiders but will try that next. 

1. I uninstalled the extension, **fully** closed down VS Code, then opened it back up. 
1. I go to the Extensions explorer, then search for Docker and install it again. 
1. I take note that both the *Reload* and *Uninstall* buttons light up once the extension has been re-installed. 
1. I close VS Code fully again. 
1. I re-open VS Code. 
1. I see the Docker Explorer open up, and this time, I can click the Refresh button without any errors, and the other Docker commands re-appear. 

Seems like it was as you proposed - to make **sure** it's fixed I need to uninstall and then **close** VS Code.

**Comment by leepowellcouk** [comment]
Same issue. Can confirm uninstall, hard restart of VS Code and a reinstall seems to work.

**Comment by AlexandreOuellet** [comment]
The same thing is happening again for me, and uninstalling/closing/reinstalling/closing/restarting doesn't work.

running vscode 1.25.0 and the docker extension 0.0.27.  Docker is version 18.03.1-cd, build 9ee9f40, and I am able to pull and run various docker images
