### ISSUE TITLE
Documentation for dockerRun does not list the `remove` property

### ISSUE THREAD

**Issue by s-truax** [microsoft/vscode-docker#2268]
The documentation page for writing custom tasks using the Docker extension does not list `remove` as a property of the `dockerRun` object. [Link](https://code.visualstudio.com/docs/containers/reference#_run-task-reference).

However, this is an attribute of the `RunDockerOptions` interface defined in `src/tasks/DockerRunTaskDefinitionBase.ts` as can be seen on [this](https://github.com/microsoft/vscode-docker/blob/878624f1334da5626cb07115f11a9254cd6cd2b9/src/tasks/DockerRunTaskDefinitionBase.ts#L42) line.

**Comment by bwateratmsft** [comment]
Good catch!

**Comment by bwateratmsft** [comment]
We should also update the docs for #2294 at the same time as this.

**Comment by bwateratmsft** [comment]
Fixed this in https://github.com/microsoft/vscode-docs/pull/3902.
