### ISSUE TITLE
extremely slow pc

### ISSUE THREAD

**Issue by saurabhgayali** [microsoft/vscode-docker#2276]
Issue Type: <b>Bug</b>

it is very slow after installation even when not in use

Extension version: 1.5.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
If you disable the Docker extension is it still slow?

**Comment by saurabhgayali** [comment]
disabled docker and restarted. it was still the same. 
uninstall hyper-v from windows features option and restarted but still it was slow.
then i followed step 7 from this link: https://www.sysnettechsolutions.com/en/uninstall-hyperv-windows-10/
an uninstalled hypervisor platform which is an extra feature in windows 10. and only then my full speed is regained.
Read somewhere that hyper-v should be installed prior to installation of docker extension as docker installs hyper-v with extra features as well as different config then default. Could confirm though. I anyways shifted to virtualbox for testing.

Speed fixed now.

**Comment by bwateratmsft** [comment]
It sounds like the slowdown was from Docker or Hyper-V, not from the Docker extension.

**Comment by saurabhgayali** [comment]
It is definite that I installed docker and Hyper-C on my system from VSCods exntension only. So I believe something can really be changed in the settings of the code so as to enforce proper installation of Docker. Have used Docker earlier on lab pc without VScode. That docker and hyper-v was totally fine.

**Comment by bwateratmsft** [comment]
The Docker extension isn't responsible for installing Docker or configuring Hyper-V. That is all done by Docker Desktop.
