### ISSUE TITLE
Creat

### ISSUE THREAD

**Issue by ElizabetePluGgui** [microsoft/vscode-docker#2277]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 1.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:3:950246
fulfilled extension.bundle.js:3:944203
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by bwateratmsft** [comment]
@ElizabetePluGgui can you add repro steps?

**Comment by ElizabetePluGgui** [comment]
I won't add , thank you

Em sex, 4 de set de 2020 10:53, Brandon Waterloo [MSFT] <
notifications@github.com> escreveu:

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
