### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Krrishdhaneja** [microsoft/vscode-docker#2278]
- Issue Type: `Bug`
- Extension Name: `vscode-docker`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bwateratmsft** [comment]
@Krrishdhaneja there's no bug here, can you paste the needed info?
