### ISSUE TITLE
Rebuilding a docker image doesn't show the updated time

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-docker#228]
When re-building an existing image, the time when the image was created is not updated in the extension. See below.

![untitled](https://user-images.githubusercontent.com/1202528/36995979-9f37cba2-2083-11e8-8be4-2d6d4b508a64.gif)

**Comment by chrisdias** [comment]
is it really rebuilding? last message says its up to date...

**Comment by johnpapa** [comment]
When i ran it, it had the changes in it (during my keynote last week)

**Comment by chrisdias** [comment]
What I try this it is updated unless I'm just rebuilding the image that has not changed. The last message from docker is `vikings_vikings_1 is up-to-date`.  If the image ins't being rebuilt then the date/time wont be updated.  what does it look like from `docker images`?

**Comment by StephenWeatherford** [comment]
This is exactly how Docker does it, although I agree it can be confusing.  Suggestions?  Do we need multiple ways to sort or group?

**Comment by StephenWeatherford** [comment]
There's a LastTagTime in the metadata...

**Comment by PrashanthCorp** [comment]
Related to #603?

**Comment by StephenWeatherford** [comment]
Superseded by #603
