### ISSUE TITLE
There is an extra warning icon before "Install Azure Account Extension..."

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2280]
**OS:** Win10
**Build Version:** 20200903.1

**Repro Steps:**
1. Uninstall the "Azure Account" extension if you have it installed.
2. Use the "Connect Registry" button to connect Azure.
3. Expand the Azure node and check the result.

**Expect:**
There is no warning icon before "Install Azure Account Extension...".
![image](https://user-images.githubusercontent.com/45614674/92372758-f8e90880-f12f-11ea-992d-b60f04fdaa16.png)

**Actual:**
There is an extra warning icon before "Install Azure Account Extension...".
![image](https://user-images.githubusercontent.com/45614674/92372691-e66ecf00-f12f-11ea-9402-431bc62493a9.png)

**More Info:**
This issue does not reproduce on the previous released Docker extension build.

**Comment by bwateratmsft** [comment]
Looks like this is an intentional change upstream in `vscode-azureextensionui`: https://github.com/microsoft/vscode-azuretools/pull/776/files#diff-82ccf94a062bb23a20d833bf57893dd5R85
