### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shishiracharya01** [microsoft/vscode-docker#2281]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\User\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@shishiracharya01 does this issue occur consistently?
