### ISSUE TITLE
SSH connection with Docker daemon does not work

### ISSUE THREAD

**Issue by Forinil** [microsoft/vscode-docker#2283]
I tried connecting to Docker daemon running on a remote host, by setting `docker.host` setting to `ssh://docker`, while running VS Code on my Windows 10 laptop.

Hostname `docker` is not resolved by DNS, but rather set in `C:\Windows\System32\drivers\etc\hosts`.
I also have `%USERPROFILE%\.ssh\config` with connection options for `docker` specified:

```
Host docker
  HostName host's ip address
  User username
  Port 2522
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile path\to\host\specific\key\file
  IdentitiesOnly yes
  LogLevel FATAL
```

I can confirm that `docker -H ssh://docker ps` works fine.

**Comment by bwateratmsft** [comment]
@Forinil Did you set up an [SSH agent](https://code.visualstudio.com/docs/containers/ssh#_set-up-ssh-tunneling)?

**Comment by karolz-ms** [comment]
> 
> Hostname `docker` is not resolved by DNS, but rather set in `C:\Windows\System32\drivers\etc\hosts`.
> I also have `%USERPROFILE%\.ssh\config` with connection options for `docker` specified:
> 
This won't work, sorry, it is a known limitation. For more info see https://code.visualstudio.com/docs/containers/ssh

**Comment by Forinil** [comment]
@bwateratmsft  No I used `%USERPROFILE%\.ssh\config` to provide a path to the private key.
@karolz-ms Thanks for the information.

**Comment by bwateratmsft** [comment]
> @bwateratmsft No I used `%USERPROFILE%\.ssh\config` to provide a path to the private key.

Gotcha. Unfortunately, the `ssh2` Node.js package used by `Dockerode` doesn't know how to use the SSH config file. It requires an SSH agent to be configured with the key and running. There's more information about how to do that in the doc that @karolz-ms and I linked; fortunately it's pretty easy to do on Windows.

I think that as long as an SSH agent is set up, it *should* work to use this approach; I don't think there would be any problem with the hostname being "docker" as long as it is in the hosts file like you mentioned.
