### ISSUE TITLE
Unable to connect to Docker on Windows 7 with correctly configured DOCKER_HOST env

### ISSUE THREAD

**Issue by thadguidry** [Microsoft/vscode-docker#229]
Correctly configured and working Docker on Windows 7 as shown in next 3 screen capture snippets...

![capture4](https://user-images.githubusercontent.com/986438/37055951-a12fadec-2148-11e8-8ab1-baaf256766c2.PNG)

![capture](https://user-images.githubusercontent.com/986438/37055796-48887570-2148-11e8-9568-d9c468131c29.PNG)
![capture2](https://user-images.githubusercontent.com/986438/37055981-af4d3f02-2148-11e8-9405-aef75d6cec1a.PNG)

Yet, when I start VSC as Administrator , it still cannot connect...

![capture3](https://user-images.githubusercontent.com/986438/37055992-b3ccccfa-2148-11e8-9936-f6df601cdfd3.PNG)

**Comment by chrisdias** [comment]
@thadguidry is this when you are expanding the tree in the explorer, or when you run a command from the command palette?

**Comment by chrisdias** [comment]
Unfortunately I don't have a win7 machine readily available (not sure where I can even get one). 

You could clone this repo, open it in VS Code and run it.  You would want to search for `Daemon` and then put a breakpoint on each one of these, and when hit inspect the `error` object.

**Comment by thadguidry** [comment]
@chrisdias yeah, when I expand the Docker explorer tree.. and click images.

Awesome, ok...I'll breakpoint it and see what I find...perhaps contribute :)

**Comment by chrisdias** [comment]
This will be very helpful, thanks.  Here's the two lines to put breakpoints on:

https://github.com/Microsoft/vscode-docker/blob/82e3038e73efe666c7ae8d0e221e2e9c6715efa0/explorer/models/rootNode.ts#L147

https://github.com/Microsoft/vscode-docker/blob/82e3038e73efe666c7ae8d0e221e2e9c6715efa0/explorer/models/rootNode.ts#L246

Then inspect `error` and let me know what you find.

Thanks!!

**Comment by thadguidry** [comment]
@chrisdias Sure thing.  Will let you know tomorrow when I get back to @Ericsson office. (5th largest software company, right behind @Microsoft) :)

**Comment by thadguidry** [comment]
I cloned this repo, opened in VSC, and clicked green Launch Extension.
New VSC opened, I then clicked on Docker panel and this error came up.

C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=26582 --debugId=4fd2e665-dae6-4f1b-8f33-8a0f264bb4bd --extensionDevelopmentPath=C:\Users\eguitha\vscode-docker 
Activating extension `PeterJausovec.vscode-docker` failed: Cannot find module 'C:\Users\eguitha\vscode-docker\out\dockerExtension'.
Activating extension `PeterJausovec.vscode-docker` failed:  Cannot find module 'C:\Users\eguitha\vscode-docker\out\dockerExtension'
Here is the error stack:  Error: Cannot find module 'C:\Users\eguitha\vscode-docker\out\dockerExtension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.G.Q.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Function.a [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:31:863)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:687:367
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:687:479)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:686:357)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:684:415)

**Comment by chrisdias** [comment]
Looks like you you need to run `npm install` in the folder before you can run it.

``` console
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker
npm install
code .
```

Then press `F5` to run.

**Comment by thadguidry** [comment]
It retrieved and parsed the DOCKER_HOST variable it seems just fine. "192.168.99.100" and "2376" Nice.
Wondering where down the rabbit hole do I look now ? :)  hints ?
![capture](https://user-images.githubusercontent.com/986438/37115178-0f5737c8-2210-11e8-89bb-0d5a0514ff2e.PNG)

**Comment by chrisdias** [comment]
did you put breakpoints on the lines mentioned above? if so, just hit `F5` until you reach the breakpoint and then inspect the `error` from the catch block.

**Comment by thadguidry** [comment]
Clicking on Explorer -> Docker -> Images

getimages() 

Error: write EPROTO 101057795:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:1493:SSL alert number 42

**Comment by chrisdias** [comment]
hmmm... seems like an SSL problem :).  check this article, see if it helps: https://docs.docker.com/toolbox/faqs/troubleshoot/#example-errors

**Comment by thadguidry** [comment]
@chrisdias ah yeah...it seems that the daemon itself is not reachable even to Windows, yet the machine starts and I can use it, but its not exposed...

```
$ docker-machine ls
NAME      ACTIVE      DRIVER      STATE      URL      SWARM      DOCKER      ERRORS
default               virtualbox  Timeout
````
where it should be looking something like this
```
$ docker-machine ls
NAME             ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
default          *        virtualbox     Running   tcp://192.168.99.101:2376           v1.10.1
```

I'll debug this on my end and get the machine properly exposed
Thanks for the pointers !

**Comment by sudippurkayastha** [comment]
@thadguidry, i'm facing the same issue. But the deamon seems to be running. Please guide
![image](https://user-images.githubusercontent.com/32146991/40565637-2de6cbcc-6022-11e8-9e4c-a6e44e81f6dd.png)
