### ISSUE TITLE
An error occurs when stopping a container next to "attach shell" action

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2291]
**OS:** Linux
**Build:** 20200909.2

**Repro Steps:**
1. Right click the "registry" image --> Run.
2.  Right click the "registry" container --> Attach Shell.
3. A new Terminal should open, then type "ls" and press ENTER.
4. Right click the "registry" container --> Stop.

**Expect:**
The container should stop and also should get automatically removed.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/92692819-54590780-f377-11ea-97b4-2e5f4d4d5f43.png)

**Comment by bwateratmsft** [comment]
This looks similar to #2284.

**Comment by bwateratmsft** [comment]
@v-xinda I wasn't able to reproduce. Can you try again? If it happens again can you click the "Report issue" button, and copy and paste the information that fills in to this issue?

**Comment by v-xinda** [comment]
Verified this issue on the build 20200909.2(vscode-docker-nightly-2), it doesn't reproduce. So close it .
