### ISSUE TITLE
Can't attach VS Code to container inside of remote machine (but attaching shell works)

### ISSUE THREAD

**Issue by awesomebytes** [microsoft/vscode-docker#2298]
Hello, I'm trying to attach VS Code to a docker container running in a remote machine.

* Issue Type: Bug
* Extension Name: vscode-docker
* Extension Version: 1.5.0
* OS Version: Ubuntu 18.04
* VSCode version: 1.48.2

My workflow looks like:

1. Open a VS Code instance on a local project.
2. From there, use `VS Code Remote` to get a VS Code instance in a remote machine.
3. In this remote VS Code instance, I can see the Docker containers available in that machine. If I right click and choose `Attach Shell` I correctly get a shell in that remote machine docker container. However, if I right click and choose `Attach Visual Studio Code` I get the list of Docker containers in my local machine on the top-center commandline-like bar instead of the remote one (that I just right-clicked).

I've reported this worded differently as they also have a functionality to attach to docker containers in the VS Code Remote plugin repo: https://github.com/microsoft/vscode-remote-release/issues/2514

Where I've also added this video/gif showing this workflow:

![vscode_remote_cascade_docker_plugin](https://user-images.githubusercontent.com/1721716/92834274-2b8b4d80-f41d-11ea-97ff-49541abfe65d.gif)

Given attaching a shell works, I find unintuitive that attaching VS Code doesn't.

**Comment by bwateratmsft** [comment]
@awesomebytes The "Attach Shell" command is ours but the "Attach VS Code" one actually belongs to the Remote - Containers extension, they use some of VS Code's capabilities to make it show up in our menu. Nevertheless, they'll have to take a look in https://github.com/microsoft/vscode-remote-release/issues/2514. Sorry!
