### ISSUE TITLE
Missing active bar icon

### ISSUE THREAD

**Issue by Xesenix** [microsoft/vscode-docker#2299]
Issue Type: <b>Bug</b>

I don't really know how to reproduce this reinstalling vscode or extension doesn't help me according to screens from plugin page there should be icon for docker related accordion tabs:
![obraz](https://user-images.githubusercontent.com/2124257/92845893-bf422700-f3e7-11ea-9d2e-aee43c208b61.png)

But I have those instead cluttering my explorer tab:
![obraz](https://user-images.githubusercontent.com/2124257/92845977-d7b24180-f3e7-11ea-9aba-bb4354b05a06.png)

Also, I am missing ability to turn on Docker active tab:
![obraz](https://user-images.githubusercontent.com/2124257/92846122-03cdc280-f3e8-11ea-803f-61d7f8d86fd1.png)

Is there any revelant setting that I should checkout to enable that icon?

Extension version: 1.5.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (10.39GB free)|
|Process Argv|--crash-reporter-id 270eb560-78a9-4d30-b013-4fc3fdf355fb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
Strange. Does checking any of those in the explorer tab (Containers, Images, Registries, ..., Contexts) cause anything to show up? Does restarting VSCode have any effect?

@sbatten do you have any ideas?

**Comment by sbatten** [comment]
Yes, the views seem to have been moved to the explorer view container. They are hidden (hence the checkboxes missing) so your recommendation should bring them back. To get the docker icon back: `F1` > `Reset View Locations`

**Comment by Xesenix** [comment]
@bwateratmsft checking them shows them on explorer tab but they clutter space there. Even reinstalling wither plugin or whole vscode doesn't restore that docker icon. I searched for some settings for it but I didn't found anything.

**Comment by sbatten** [comment]
@Xesenix To get the docker icon back: `F1 > Reset View Locations`

**Comment by Xesenix** [comment]
@sbatten Thx that worked I guess we can close/archive this bug.
