### ISSUE TITLE
Error：EACCES

### ISSUE THREAD

**Issue by 0xPagliacci** [microsoft/vscode-docker#2300]
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: EACCES
Error Message: connect EACCES /var/run/docker.sock

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] net.js:1113:14
```

</details>

**Comment by bwateratmsft** [comment]
@0xPagliacci can you add repro steps?
