### ISSUE TITLE
докер

### ISSUE THREAD

**Issue by irinazheltisheva** [microsoft/vscode-docker#2303]
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 1.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.0
Language: ru

<details>
<summary>Call Stack</summary>

```
DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:578:838397
extension.bundle.js:578:838304extension.bundle.js:578:838304
Object.<anonymous> extension.bundle.js:3:478367
extension.bundle.js:3:477558extension.bundle.js:3:477558
o extension.bundle.js:3:477244
Object.callWithTelemetryAndErrorHandling extension.bundle.js:3:478275
DockerNetCoreDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:578:838235
extensionHostProcess.js:934:493extensionHostProcess.js:934:493
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment]
Duplicate of #1451. You need to open a workspace folder to do any debugging. Additionally, the `docker-coreclr` debug type is deprecated and will be removed soon.
