### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yuzaihui** [microsoft/vscode-docker#2305]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:361:320208
```

</details>

**Comment by bwateratmsft** [comment]
@yuzaihui The `docker-coreclr` debug configuration is deprecated and will be removed soon. You should run `Docker: Add Docker files to workspace` and re-create with the new `docker` tasks and launch config.

**Comment by yuzaihui** [comment]
thankyou

于再辉
