### ISSUE TITLE
[Suggestion] Change the oldest VS Code version that the Docker extension supported

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2309]
**OS:** Windows 10
**Build Version:** 20200909.2

**Repro Steps:**
1. Figure out the oldest VS Code version that the extension supports, the version is "1.44.0".
![image](https://user-images.githubusercontent.com/45614674/93077053-e2f0c000-f6ba-11ea-8825-b2a52afabd33.png)
2. Install VS Code 1.44.2.
3. Install Docker extension in VS Code then pull image/push image.

**Actual:**
An error "Cannot read property 'uri' of undefined" occurs. Known bug [2177](https://github.com/microsoft/vscode-docker/issues/2177).
![image](https://user-images.githubusercontent.com/45614674/93077352-437ffd00-f6bb-11ea-9040-c7e7f48447b9.png)

**Suggestion:**
Change the oldest VS Code version that the Docker extension supported.

**Comment by bwateratmsft** [comment]
It is updated to 1.49.0 in #2250. I didn't expect this error though, I'll investigate it.

**Comment by bwateratmsft** [comment]
It looks like the issue was introduced potentially in 1.45.0, and fixed in 1.48.0. We could update the minimum VSCode version to 1.48.0 for 1.6.0. By now nearly everyone will have 1.48 or 1.49.

@BigMorty @dbreshears what do you think? Should we update the min version? I think this bug only occurs when no workspace folder is opened which is less common.

**Comment by BigMorty** [comment]
I dont think we need to update the min version.

**Comment by bwateratmsft** [comment]
As @BigMorty we'll leave it as-is for 1.6.0. About 92% are at 1.48.0+ and therefore don't have the bug. The remaining 8% may have it, but if we added a min version in 1.6.0, it wouldn't fix them--just prevent them from updating to 1.6.0.

In #2250 we updated to 1.49.0 for other reasons so I'll close this as fixed for 1.7.0.
