### ISSUE TITLE
Open a wrong webpage when debugging the ASP.NET Core project created by "dotnet new mvc"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2311]
**OS:** Linux
**Build:** 20200911.36

**Repro Steps:**
1. Create an ASP.NET Core web app by "dotnet new mvc" and open it in VS Code --> Select "Yes".
2. F1 --> Click "Docker: Add Docker Files to Workspace" --> Choose "ASP.NET Core" as appropriate --> Choose Linux --> Default port --> Yes.
3. Set a breakpoint in HomeController.cs.
4. Go to the Debug tab in VSCode, and select "Docker .NET Core Launch" --> Debug it.
5. Check the result.

**Expect:**
Open a webpage and hit the breakpoint.

**Actual:**
Open a "Warning: potential Security Risk Ahead" webpage and don't hit breakpoint.
![image](https://user-images.githubusercontent.com/57662131/93077187-0d427d80-f6bb-11ea-95ca-7ef94bf449d1.png)

**Comment by bwateratmsft** [comment]
This is expected on Linux and Mac*. The browser is unhappy that the certificate presented by the ASP.NET web service is self-signed and not trusted, so it shows this warning--if you click "Advanced..." there will be an option to proceed anyway, then the website should load and the breakpoint will be hit.

*On Windows we prompt to trust the certificate automatically; there will be a popup asking to trust the certificate. When it is trusted this warning page will not appear. However on Linux there is no central trust store--it varies by OS and the browser installed--and on Mac, we can't trust it automatically, it has to be done manually by running `sudo dotnet dev-certs https --trust` in a terminal window. Once trusted on Mac this warning page should no longer appear.
