### ISSUE TITLE
There is no option to choose a Dockerfile to build when the Node.js project contains multiple Dockerfiles

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2312]
**OS:** All
**Build Version:** 20200909.2

**Repro Steps:**

1. Open a Node.js Project with multiple Dockerfiles.
2. F1 -> "Docker Images: Build Image...".
3. Check the result.

**Expect:**
There is an option to choose a Dockerfile to build.
![Screen Shot 2020-09-14 at 7 53 40 PM](https://user-images.githubusercontent.com/62053665/93083572-60b9c900-f6c5-11ea-8af1-5a031cb38e12.png)

**Actual:**
There is no option to choose a Dockerfile to build.

**More Info:**
This issue doesn't reproduces for Python/.NET Core project.

**Comment by bwateratmsft** [comment]
This may be because of the `docker-build` task that gets created. I'll check it out.

**Comment by bwateratmsft** [comment]
I checked the code and even though an official build task is present it should still prompt. However, I am not able to reproduce this issue. @v-mengwe can you share the project you encountered this issue with?

**Comment by v-mengwe** [comment]
Thanks for your sharing! Verified on the latest build 20200914.7, this issue doesn't reproduce, so close it.
