### ISSUE TITLE
Unable to build Dockerfile to Azure if filename isn't "Dockerfile"

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2317]
Some developers choose to have a file named "Dockerfile" and another file named "Dockerfile.prod" in the same directory for different reasons. This difference in file name is still seen as the type Dockerfile. However, even if both files are valid, we lose the ability to Right click "Build to Azure" unless we rename a "Dockerfile.dev" to "Dockerfile".

Repro:
Right click on a valid Dockerfile, Build to Azure.
Rename Dockerfile to "Dockerfile.prod"

**Comment by bwateratmsft** [comment]
I can repro. The fix is easy. The code for showing in the _editor_ context menu (i.e. right-click inside the text editor) has the correct `when` clause:
```json
                {
                    "when": "editorLangId == dockerfile && isAzureAccountInstalled",
                    "command": "vscode-docker.registries.azure.buildImage",
                    "group": "docker"
                },
```

But in the _explorer_ context menu (right-click the file in the explorer view) does not:
```json
                {
                    "when": "resourceFilename =~ /(^|\\.)dockerfile$/i && isAzureAccountInstalled",
                    "command": "vscode-docker.registries.azure.buildImage",
                    "group": "docker"
                },
```
