### ISSUE TITLE
container Instance view on VS Code

### ISSUE THREAD

**Issue by helpservd** [microsoft/vscode-docker#2318]
My client is  following https://cloudblogs.microsoft.com/opensource/2020/07/22/vs-code-docker-extension-azure-containers-instances/ but on his Vs Code, he cant view his container instances.
The Turning point  on this doc:
" Before you can use an Azure Container Instances (ACI) context, you first must create one. The Docker CLI has new docker login azure and docker context create aci commands you can use to log into Azure and create an ACI context, but the VS Code Docker tools make that easier as well. Click the plus sign (+) in the header area of the Contexts panel and you will see an interactive UI experience that lets you select the Azure subscription you want to use and an existing Azure resource group, or create a new one."
This Plus sign isnt displaying on his side.

He is using version 1.4 of Visual Studio Code Docker extension.

**Comment by karolz-ms** [comment]
Version 1.4 does not have the functionality to create ACI Docker contexts; it is implemented in the extension version 1.5 and newer.

**Comment by bwateratmsft** [comment]
@karolz-ms it was in 1.4, however they need to install the latest Edge build of Docker. It will be available in stable very soon (today?).

Nevertheless I highly recommend they upgrade to 1.5.0. There is no reason not to :smile:
