### ISSUE TITLE
Cannot use "attach shell" by right click on the runnning container

### ISSUE THREAD

**Issue by angangi** [microsoft/vscode-docker#2319]
the error info is `The terminal process failed to launch: Path to shell executable "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist.`

**Comment by bwateratmsft** [comment]
If you don't have PowerShell installed you'll need to configure cmd as your default shell. There's more info on that [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-shell-for-tasks-and-debug).

**Comment by angangi** [comment]
I changed the config 
`"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`
and the feedback is 
`> Executing task: docker exec -it e88defdb9dc9780ea7b0d6e3c7dd4a5efc8176e5a34b452e869a0a93082bf6fc bash <

The terminal process failed to launch: Path to shell executable "C:\Windows\System32\cmd.exe" does not exist.

Terminal will be reused by tasks, press any key to close it.
`
And for further infomation, I use the remote-wsl plugin and installed the docker in wsl2. So when I'm under remote-wsl environment to manage the docker by your plugin-in vscode-docker, may your plug-in script still use windows terminal path under remote-wsl environment ? (And vscode try to find it under wsl2 env) I guess that's the problem

**Comment by bwateratmsft** [comment]
Ahh, it sounds like you might have the extension operating in UI mode but it works much better in workspace mode when doing remoting. If you go to the Extensions tab, do you see an option to install the Docker extension in the remote workspace?

**Comment by angangi** [comment]
Amazing! I solved it by changing to workspace mode. Thank you so much! 
P.S. I ONLY install the docker extension under vscode's WSL:ubuntu environment, not on windows environment. And I actually didn't see the prompt...
