### ISSUE TITLE
Add CI build support

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-docker#232]
#219 was merged even though it had a compiler error. It was quickly fixed with ec5e219e1c311be0bdfd1cfbda1f72b360d72348 but it would have been nice if the pull request kicked off a CI build to catch this.

Perhaps Travis CI could be used for this?

**Comment by chrisdias** [comment]
This was my fault, to some extent. 

I read the PR but didn't pull it down and compile/run it.  Its sometimes easier to do the merge, then pull, then fix it up.

But, generally not a good practice.

**Comment by rcjsuen** [comment]
I think everyone's unintentionally submitted a broken pull request before. We can reduce the frequency of this by having a CI build though. I can submit a simple `.travis.yml` file if necessary.

However, I understand that nothing happens for free and maintaining Travis CI takes time so if this seems like too much work then please feel free to close this issue.

**Comment by rcjsuen** [comment]
Looks like #283 will implement this.

**Comment by StephenWeatherford** [comment]
Thanks for pointing that out.
