### ISSUE TITLE
Remote docker host config and using in VSCode

### ISSUE THREAD

**Issue by vurachaitanya** [microsoft/vscode-docker#2320]
Trying to use : https://code.visualstudio.com/docs/containers/ssh

Repro steps:

1.
2.

Action: vscode-docker.contexts.use
Error type: 1
Error Message: Process 'docker context use default' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.5.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:3:173256
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@vurachaitanya Do you have Docker Desktop installed?

**Comment by vurachaitanya** [comment]
No i have Linux VM which has docker installed on it and shared via SSH

**Comment by bwateratmsft** [comment]
Ok, you need to have Docker installed locally even to use it remotely. However, you can use the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension to set up remoting to that Linux VM; from there you can install the Docker extension in the remote session and it should work nicely. This way you don't have to install Docker Desktop on your host machine.
