### ISSUE TITLE
Group containers by Compose invocation "project" by default

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2324]
Docker Desktop is doing that already. Given how widely used Compose is it probably make sense to have Compose be the default grouping for containers pane

**Comment by bwateratmsft** [comment]
We'd definitely want to have them expanded by default (would require a small framework change in vscode-azureextensionui). Probably want to change the text for non-compose containers to something other than "Other Containers".

**Comment by dbreshears** [comment]
possibilities : standalone,  non-compose, other

**Comment by bwateratmsft** [comment]
This is now fixed in Docker extension version 1.7.0.
