### ISSUE TITLE
Add "Docker Compose: Logs" command

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2325]
Add a command to quickly do `docker-compose logs -ft`. This interleaves logs from all containers that are part of the same Compose invocation, decorating each log entry with service name and timestamp. It is a good way to see interactions between services.

**Comment by bwateratmsft** [comment]
Dupe of #2506 I suppose.

**Comment by bwateratmsft** [comment]
Also, this is really weird; this bug hid itself from triage somehow. It wasn't showing up in any of our triage queries even though it had no milestone.
