### ISSUE TITLE
Improvements to compose file scaffolding

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2326]
We discussed what we want for a user experience for Compose scaffolding.

- [ ] Ability to add services to already-scaffolded compose files for all platforms (one service at a time)
    - [ ] ~~Choose which compose file(s) to add the service to--allowing support for having many different compose files that launch different groups of services~~
- [ ] Multiple-platform support, e.g. a compose file that references both .NET and Node projects
- [ ] Samples for external services (e.g. database) that aren't being built (maybe best done in language server, #2539)

**Comment by bwateratmsft** [comment]
Moving to future per our discussion. We'll await user feedback.

**Comment by ucheNkadiCode** [comment]
Adding specific note: Inserting snippet to add a "well known" service/image within a compose file. (Redis, postgres)

**Comment by bwateratmsft** [comment]
Probably the best way to do that would be with the language server. I'll put a checkmark for it.

**Comment by bwateratmsft** [comment]
Basically covered by #2539 so I'm going to close this one.
