### ISSUE TITLE
Error: connect EACCES /var/run/docker.sock

### ISSUE THREAD

**Issue by xahon** [microsoft/vscode-docker#2329]
Not a duplicate of #1193
I have the same issue after making all the instructions and rebooting
**luozhouyang** had the same behaviour as i have but stupid bot locked the issue, that is why i want to open a new one

**Comment by bwateratmsft** [comment]
@xahon Did you add your user to the `docker` group?

**Comment by xahon** [comment]
Sorry, i forgot to make docker service to start automatically
