### ISSUE TITLE
Allow the use of variables in the specification of $docker.host

### ISSUE THREAD

**Issue by Ryan-Chaves-CambridgeConsultants** [microsoft/vscode-docker#2330]
I'd like to be able to specify `$docker.host` as something like below in my workspace `settings.json`:

    {
        "docker.host": "ssh://${localEnv:USERNAME}@myserver",
    }

This would allow the configuration to be valid for anyone on the team. Right now we can't version control `settings.json` because the username part of `$docker.host` has to be changed for each team member.

**Comment by bwateratmsft** [comment]
@karolz-ms would an SSH agent prevent the need to specify a username at all?

**Comment by Ryan-Chaves-CambridgeConsultants** [comment]
I tried that. At my company, what ends up happening is that the username supplied to `myserver` is _`domain\username`_ which doesn't match the `username` login for `myserver`. Attempting to use the [provided instructions](https://code.visualstudio.com/docs/remote/troubleshooting#_quick-start-using-ssh-keys) to setup SSH Agent this way ends up failing because, as stated above, _`domain\username`_ is not the actual username on `myserver`.

    PS C:\Users\username> $pubKey=(Get-Content "$PUBKEYPATH" | Out-String); ssh "$USER_AT_HOST" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '${pubKey}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
    domain\username@myserver's password:

**Comment by karolz-ms** [comment]
@Ryan-Chaves-CambridgeConsultants so `USERNAME` is somethin that is set per-developer? Is it the same for all projects/Docker servers used by developers?

@bwateratmsft wasn't there a VS Code issue about allowing the use of env. variables in extension config?

**Comment by bwateratmsft** [comment]
> @bwateratmsft wasn't there a VS Code issue about allowing the use of env. variables in extension config?
That's for tasks and launch config. There has never been any sort of support for environment variables in settings. I'm not aware of other extensions doing similar things either.

@Ryan-Chaves-CambridgeConsultants Can you use docker contexts instead of using `docker.host`?

**Comment by Ryan-Chaves-CambridgeConsultants** [comment]
@karolz-ms Yes our standard machine configuration always has `USERNAME` defined in the environment.

@bwateratmsft I haven't used docker contexts before, so I needed to read up on that. A quick test shows this to be relatively straightforward and allows the context to be configuration-managed by name and captured in the `initializeCommand` parameter of `devcontainer.json` for remote container development.

A benefit of using `docker.host` is that it works without Docker Desktop running on my local machine. It would seem I'd have to have it running locally in order for VS Code to use docker contexts successfully. Also, I have a suspicion that `docker.host` means all docker CLI execution takes place on the remote machine, whereas with docker contexts some amount of docker-related work may still be done by my local machine (which could be significantly under-powered compared to the remote machine). If the context is being properly set via `initializeCommand` then perhaps this effect is minimized?

**Comment by Ryan-Chaves-CambridgeConsultants** [comment]
Although I've just realized and noticed that this setup permanently changes the docker context until `docker context` is execute again (e.g. `docker context use default`). So if I wanted to work with local and remote containers simultaneously, docker contexts may not be the best solution, unless there is a way to limit the change in context for the VS Code remote container session. So far, `initializeCommand` appears to be the only workable place to specify this; if specified in `runArgs`, `--context=_mycontext_` is specified in the wrong place on the commandline (i.e. after the `run` command) and docker exits with an errorcode.

**Comment by bwateratmsft** [comment]
In theory Docker contexts and `DOCKER_HOST` (or `docker.host`) should work essentially the same. As you point out, there is an advantage to `DOCKER_HOST` in that Dockerode--what we use for the explorer view and many commands--does not require the Docker CLI to be present.

Depending on your use case it may be easier to use [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) with the Docker extension in workspace mode.

Can you share more about how you use different Docker hosts?

**Comment by Ryan-Chaves-CambridgeConsultants** [comment]
I can describe two different use cases which I am not currently running simultaneously, but could if I had to do work on these two different projects at the same time.

1. Project A - Container for running unit tests locally (pre-commit) or within our remote CI infrastructure (post-commit).
1. Project B - Container for developing a Tensorflow-based application on remote hardware with GPUs, where live development & debug on the remote host is required.

There are multiple developers for both projects; this is not really a constraint for how containers / Docker hosts are used for Project A, but for Project B each developer has their own login to the remote machine and it would be great if the remote container development configuration can be version controlled within the project's Git repo (hence my desire to use `${localEnv:USERNAME}` initially).

**Comment by bwateratmsft** [comment]
This sounds like it could be a good use case for #2264. This would use Docker contexts, but would not set them globally; rather it would use the `DOCKER_CONTEXT` environment variable like `DOCKER_HOST` is used today. With this, you could set up Docker contexts on each user's machine, and have a settings in each workspace to instruct VSCode to use the appropriate context.

**Comment by karolz-ms** [comment]
To add to what Brandon said, one could open two VS Code windows, one using `docker.context` setting pointing to the remote machine, another using the local Docker engine. This way one would have full VS Code Docker experience for both.

**Comment by dbreshears** [comment]
Going to dupe this against #2264 and close this one
