### ISSUE TITLE
Proposal: show files of running containers

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#2333]
## Proposal

The Containers tool window (CTW) in Visual Studio allows users to browse the file system of running containers, and users seem to really like this feature. Should we do the same for Visual Studio Code, something along the lines of the mockup below?

<img width="409" alt="Screenshot 2020-09-18 at 10 53 07" src="https://user-images.githubusercontent.com/6402946/93629865-d65fb680-f99d-11ea-8172-67feee44a319.png">

As a related item, it was suggested that, when opening a container file, if that container file actually maps to a local file that's been volume-mounted into the container, that the local file be opened instead.  (This is something that CTW does *not* currently do, but the idea seems good in both places.)

**Comment by bwateratmsft** [comment]
I think that this functionality overlaps too much with Remote - Containers to justify, TBH.

**Comment by philliphoff** [comment]
While I agree that you *can* use Remote - Containers for similar purposes, it's much more invasive when connecting (e.g. installing the VS Code server, container-side extensions, etc.) as it tries to make that container a "dev" container.  If you just want to poke around the file system and look at a couple of files, it seems very heavy handed.

**Comment by karolz-ms** [comment]
I agree with @philliphoff Being able to see where the files are and what they contain is what most users need. Injecting VS Code backend into the container for that purpose is more than necessary, and also not intuitive/discoverable.

**Comment by bwateratmsft** [comment]
That's fair although I wouldn't say I'm quite convinced. If we do add this, we should use the API instead of the CLI. The slow performance of the CLI would make this feature pretty frustrating.

**Comment by PavelSosin-320** [comment]
This is a great idea with one big BUT: existing Docker volume drivers don't support data access concurrency. See discussion: [Concurrency managed by volumes](https://stackoverflow.com/questions/48782326/how-is-concurrency-managed-in-volumes-when-they-are-shared-by-multiple-container). The pre-requisite is PR: develop Docker volume driver supporting data access concurrency without involving Inter-container IPC based synchronization. Maybe, it is possible when the container is stopped when somebody looks into its volumes  and all mounts are read-only except one.

**Comment by PavelSosin-320** [comment]
This post contains explanations for sharing data between containers in the Docker [sharing data between containers](https://www.mirantis.com/blog/multi-container-pods-and-container-communication-in-kubernetes/#:~:text=Why%20does%20Kubernetes%20allow%20more,can%20also%20use%20shared%20volumes.): how and why. Regarding the architecture proposal, you can ask Erich Gamma.

**Comment by PavelSosin-320** [comment]
Why it is so hard to implement? 
Say we have Container1, a writer which populates in the volume mounted by this Container. For example, run 1st container with -it option and mount Volume1 as shared.
cd to the volume mount point inside 1st container and run git clone ..... &.
Run Container2, reader in the way similar way, cd to the mount point of the Volume1 in the 2nd container and do ls. The result will be ???? depends. The default overlay2 Docker storage driver doesn't ensure any concurrency. Do ls a few seconds later to refresh and now you will see Volume1 populated. If you do it in the same FS you can process FileSystem notification or use flock for synchronization but in your scenario, you have to send notification from Container1 to Container2 to say that Volume1 has been populated and can be read.

**Comment by karolz-ms** [comment]
Note: in addition to what @bwateratmsft said about performance, what Visual Studio currently does (execute 'ls' command inside the container and parse output) will not work for containers built from scratch (because they don't have any shell binaries). See [this discussion on StackOverflow](https://stackoverflow.com/questions/54720824/how-to-docker-exec-a-container-built-from-scratch) for some ideas.

**Comment by philliphoff** [comment]
@karolz-ms That's a known limitations and I've seen such containers here and there when using CTW, but I'm not sure there's a "no touch" option.  We could copy in a shell, execute it, and then remove the shell; but there will be the potential for leaving bits behind.  That might be *ok* for such containers, but I think we'd want to warn users that we're making modifications to the running container in such cases.

**Comment by karolz-ms** [comment]
@philliphoff if only volumes could be mounted dynamically... ☺️

**Comment by bwateratmsft** [comment]
The API has a way to get file contents (and presumably write them but haven't validated that): https://docs.docker.com/engine/api/v1.40/#operation/ContainerArchive

It *almost* worked for listing directory contents but the output of `HEAD /containers/{id}/archive` is more or less useless:
```json
{
    "name": "/",
    "size": 4096,
    "mode": 2147484141,
    "mtime": "2020-09-29T15:27:33.82Z",
    "linkTarget": ""
}
```

Nevertheless, the `GET` / `PUT` could be helpful if we want to read / write files. Also, we should probably see if this whole thing can be implemented as a [FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider).

**Comment by philliphoff** [comment]
I assume that that API is the basis of the `docker copy` CLI command.  Unfortunately, that command isn't supported on Docker hosts configured to run Windows containers.  In that case, VS uses an ugly hack to stream the file out of the container via `docker exec`.

**Comment by bwateratmsft** [comment]
I don't know for sure about `docker cp`, but it is the basis of `docker export`.

**Comment by philliphoff** [comment]
I agree that a `FileSystemProvider` would be a nice way to expose container files, both for consumption by our extension as well as others that find a use.

**Comment by bwateratmsft** [comment]
This feature has now been released in 1.8.0.

**Comment by benpinchas** [comment]
Hey : ) 
There's a way I can disable this feature in release 1.8.0?

**Comment by PavelSosin-320** [comment]
@bwateratmsft Clarification: The files of containers and how fast the list of container files are questions without a single answer because according to OCI container format (Docker, runc , Podman, Kubernetes, Openshift,...) every container has more than 1 filesystem: 1. RootFS served by overlay2 driver and created in the memory when the image is loaded, container created, and shared among all running containers by image layers basis. It designed to be very slim and static to ensure big Cloud clusters be scalable. More than one team is working to improve these figures but nobody cares about Root FS too much and overlay2 is maximum has been achieved. 2. Mounted and bound and volumes served by storage drivers of Docker, Podman, and underlying Cloud infrastructure. Scores of developers are employed to improve storage driver and storage services performance to make big data applications and video streaming possible and expected performance is much above 1 terabyte per second for certain drivers and infrastructure.
So, ls / and ls mount-point are absolutely different questions.
ls / is image layers structure plus changed files, i.e. Docker diff plus ls of all mount points.

**Comment by karolz-ms** [comment]
@benpinchas why would you like to disable the feature? It does not incur any cost if you do not expand the Files node...

**Comment by benpinchas** [comment]
@karolz-ms 

First I find this toggle mechanism annoying and less clean. (attaching before and after)

Second, let's say you have many microservices, and you want to deal with a specific one.

Before that feature, you would just click on one of them to gain focus, start typing part of the microservice name and vs-code would mark any matched microservices (elements) for you.

Now, with this feature, click on one of the elements to gain focus would toggle it and result in an unwanted reveal of its files :(
A real pain in the neck.

Edit:
I found that you don't have to click on of the elements for "filter-by-type", you could also click the scroll-bar / the dead area beneath the list. 

Before
![image](https://user-images.githubusercontent.com/51172312/100543351-46b96c80-3258-11eb-80c8-066222156fa9.png)


After
![image](https://user-images.githubusercontent.com/51172312/100543327-18d42800-3258-11eb-9fbe-2f2726d9bc20.png)

Still one of the most helpful and powerful extension by far!

**Comment by karolz-ms** [comment]
@benpinchas glad you found a workaround

Just FYI the extension now groups container nodes by Compose "project" by default (that is why there is a "docker" top-level node in the new tree layout), but that can be turned off via settings if you don't like that
