### ISSUE TITLE
Aplication date field one medium

### ISSUE THREAD

**Issue by samuel-velazquez** [microsoft/vscode-docker#2336]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.contexts.use
Error type: 1
Error Message: Process 'docker context use default' exited with code 1
Error: "docker" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Version: 1.6.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:33:76269
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@samuel-velazquez Is Docker installed?

**Comment by samuel-velazquez** [comment]
law this common test appset -- jet member update out-time

**Comment by bwateratmsft** [comment]
This account looks to be a bot.
