### ISSUE TITLE
no se puede realizar la conexion

### ISSUE THREAD

**Issue by abelantonios8520** [microsoft/vscode-docker#2337]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username abelantoniosalcedo --password-stdin
"docker" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Version: 1.6.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:304:12
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@abelantonios8520 is Docker installed?
