### ISSUE TITLE
command 'docker-compose.container.attach' not found on attach attempt

### ISSUE THREAD

**Issue by aoighost** [Microsoft/vscode-docker#234]
On the typescript tutorial, I get "command 'docker-compose.container.attach' not found"
 as I try to attach to docker on Windows 10.

**Comment by chrisdias** [comment]
@aoighost sorry about this. it sounds like the `docker` extension isn't loading properly. 

could you please tell me what you see in the developer tools console?

press `F1`
search for `Developer: Toggle Developer Tools` to bring up the chrome tools
click on the `Console` tab and let me know if there are any errors

After which, you will probably want to reinstall the extension:

press `F1`
search for `Developer: Reinstall extension...`
Then pick the docker extension and do a hard reload of VS Code

**Comment by chrisdias** [comment]
Closing due to no response. Please let me know if you still have an issue.
