### ISSUE TITLE
Link to install Docker in the explorer window

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2343]
1. Create a Docker context (or do anything that will result in using the CLI during context init)
1. Uninstall Docker
1. Launch VSCode and open a Dockerfile

Expect: No error
Actual:
![image](https://user-images.githubusercontent.com/36966225/93937847-60898100-fcf6-11ea-83c9-749917efea4f.png)
![image](https://user-images.githubusercontent.com/36966225/93937869-6aab7f80-fcf6-11ea-882f-697f9e05018a.png)

**Comment by bwateratmsft** [comment]
Additionally--we could put an "Install Docker..." node here:
![image](https://user-images.githubusercontent.com/36966225/93938854-e954ec80-fcf7-11ea-937a-f8b46f3a0f48.png)

**Comment by bwateratmsft** [comment]
Since the primary error toast only occurs when you've already created Docker contexts--therefore had it installed at some point--I don't think this is as urgent. Maybe doesn't need a solution at all. I think that there may still be value to the install node. In any case since the problem isn't critical I'm taking it out of the 1.7.0 milestone for re-triage.

**Comment by dbreshears** [comment]
@BigMorty ,   Brandon and I discussed and think that maybe a "Install Docker..." link in help and feedback panel shown conditionally when Docker is not installed may help as the toast can go away and then you click the bell to bring up the notification again which isn't discoverable.

**Comment by BigMorty** [comment]
I feel like it would get more noticed if we put it in the Containers panel not the Help & Feedback panel.
