### ISSUE TITLE
Add keybinding support for "workbench.view.extension.docker"

### ISSUE THREAD

**Issue by r44083** [microsoft/vscode-docker#2345]
Issue Type: <b>Feature Request</b>

Curently there is no posibility to map keybinding to Docker extension view.
It would be great if you added such feature to map "workbench.view.extension.docker" to some keybinding.

in keybindings.json:
*(for example)*
```json
...
{"key": "ctrl+shift+k", "command": "workbench.view.extension.docker"}
...
```

Extension version: 1.6.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 4.19.30-scom

**Comment by bwateratmsft** [comment]
This can be done with user settings for keyboard shortcuts (<kbd>Ctrl</kbd> + <kbd>K</kbd> + <kbd>S</kbd>) for `workbench.view.extension.dockerView`. For example, here I set it to <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>H</kbd>:
![image](https://user-images.githubusercontent.com/36966225/94145840-211b7b80-fe41-11ea-8ac6-d29c843c82a6.png)

However, I don't think it would be appropriate to set a default shortcut. There is simply too much potential for conflicting shortcuts.
