### ISSUE TITLE
The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

### ISSUE THREAD

**Issue by hatsem78** [microsoft/vscode-docker#2347]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.createRegistry
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.6.0
OS: linux
OS Release: 5.4.0-48-generic
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:33:66487
extension.bundle.js:33:1636251
processTicksAndRejections task_queues.js:94:5
AzureRegistryCreateStep.execute extension.bundle.js:1276:35083
```

</details>

**Comment by bwateratmsft** [comment]
The link in the error message contains some information on how to set up your Azure subscription for using Azure Container Registries.
