### ISSUE TITLE
docker context is not recognized on windows 10

### ISSUE THREAD

**Issue by jifox** [microsoft/vscode-docker#2349]
# Problem Description

Docker extension section **CONTEXTS** is not displaying all existing contexts.

Only context `default` is displayed the `swarm1`, `swarm2`, `swarm3` contexts are missing.

I suspect it has something to do with the new `vctl` because the default context has a `KUBERNETES ENDPOINT`

> Containers and Kubernetes
> For developers, we’ve added support for Containers and Kubernetes with a new CLI tool: vctl!
[see vmware](https://blogs.vmware.com/workstation/2020/08/announcing-workstation-16-and-fusion-12.html)

# Environment

- Windows 10 

     Version 1909 (Build 18363.1082)

- Vscode 

     Version: 1.49.2 (system setup)
     Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
     Datum: 2020-09-24T16:29:41.983Z
     Electron: 9.2.1
     Chrome: 83.0.4103.122
     Node.js: 12.14.1
     V8: 8.3.110.13-electron.0
     Betriebssystem: Windows_NT x64 10.0.18363

- Docker extension

     ms-azuretools.vscode-docker
     v1.6.0

- VMware® Workstation 16 Pro

     16.0.0 build-16894299

## Reproduce error

- install VMware
- install docker-cli  "choco install docker-cli"
- Create docker contexts `docker context create swarm1 ...`
- open VScode - Docker Extension page

The docker ports are forwarded via a ssh port forwarding to the swarm nodes port 2376 and everything is working fine on commandline.

## Docker Output

```powershell
PS C:\devops\pydev> docker --version
Docker version 19.03.12, build 0ed913b8


PS C:\devops\pydev> docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                  KUBERNETES ENDPOINT                     ORCHESTRATOR
default             Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine   https://192.168.10.111:6443 (default)   swarm
swarm1 *            swarm1-dch                                tcp://localhost:1271                                                     swarm
swarm2              swarm2-dch                                tcp://localhost:1272                                                     swarm
swarm3              swarm3-dch                                tcp://localhost:1273                                                     swarm


PS C:\devops\pydev> docker context use swarm1
swarm1
Current context is now "swarm1"


PS C:\devops\pydev> docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
o2r7rtk53o47zgfm5ku795puj *   swarm1              Ready               Active              Leader              19.03.12      
oarpj27dv4zsnh4mxmc4v35gt     swarm2              Ready               Active              Reachable           19.03.11      
884jyld4j214l18czh37uwyxd     swarm3              Ready               Active              Reachable           19.03.11 


S C:\devops\pydev> dir C:\Users\username\.docker\contexts\meta


    Verzeichnis: C:\Users\username\.docker\contexts\meta


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25.09.2020     17:39                54104ce9d4d8df74e006e12269fa64e9178ebb3e4b00177f6f3f3af210050690
d-----       25.09.2020     17:40                b6206ed227b0bfde999f7c40ab193aa8e8373f6d309fa84b7be4f3de7e63ad75
d-----       25.09.2020     17:32                f740aea1606420d66e577c6b5c5e98691b88c1bf0126a1942f73cfcf6ce37aa3
```

KR
Josef

**Comment by bwateratmsft** [comment]
@jifox Do you have any VSCode settings in place for `docker.host` or `docker.dockerodeOptions`, or any environment variables for `DOCKER_HOST`?

**Comment by jifox** [comment]
@bwateratmsft Thanks for pointing to right direction. I've cleard the DOCKER_HOST setting and now all contexts are shown.

**Comment by bwateratmsft** [comment]
Glad to help! The reason we did this is that if `DOCKER_HOST` is set, the Docker CLI ignores contexts; we wanted to mirror that behavior. We also don't look for anything more than the default context if that variable is present.
