### ISSUE TITLE
remote container error - Terminal failed to launch

### ISSUE THREAD

**Issue by KennyChen0909** [microsoft/vscode-docker#2350]
I have a customer trying to launch remote containers through VSCode to a linux docker system and receive a Terminal failed to launch error despite being able to connect to the docker server and view containers. 

![image](https://user-images.githubusercontent.com/40878442/94389345-3dd9eb00-0182-11eb-87b1-49161394057d.png)

From the screenshot, it seems that VSCode is trying to use a local powershell terminal when it should use a remote bash terminal.

From this document: https://code.visualstudio.com/docs/remote/ssh#_opening-a-terminal-on-a-remote-host
_Opening a terminal on the remote host from VS Code is simple. Once connected, any terminal window you open in VS Code (Terminal > New Terminal) will automatically run on the remote host rather than locally._ 

Can we know is there any settings needs to be noticed to make it open bash on remote?

**Comment by bwateratmsft** [comment]
@KennyChen0909 Try installing the Docker extension in workspace mode instead of UI mode (in your scenario, it will read "Install in SSH..." instead of "Install in WSL...":

![image](https://user-images.githubusercontent.com/36966225/94450691-8fcb4280-017b-11eb-814e-2177e5040f61.png)

@karolz-ms For one thing we should be warning when this is attempted--I thought we already were but maybe that code is misbehaving. However, I'm starting to doubt the value of supporting UI mode at all. It seems like 95%+ of the time users want it to be in workspace mode, but even though workspace mode is preferred (and, package.json explicitly defines it as preferred), it is _not_ the default _until_ the extension is installed in the remote workspace. What do you think?

**Comment by karolz-ms** [comment]
@bwateratmsft agreed. I am re-reading the [extensionKind docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds) and I am having hard time coming up with a situation where Docker extension would want to run as an UI extension.

**Comment by bwateratmsft** [comment]
The only scenario I can think of is running a container locally and attaching to it. You'd want the Docker extension to stay pointing at the host (i.e., in UI mode, here), but VSCode within the container.

**Comment by karolz-ms** [comment]
Good point. Still making the extension workspace-only is probably a good tradeoff. If one needs to work with Docker inside the container, they can install Docker CLI into it and map the Docker socket to the host; this is [already documented](https://code.visualstudio.com/docs/remote/containers-advanced#_using-docker-or-kubernetes-from-a-container)

**Comment by bwateratmsft** [comment]
Oh, bonus bug. Even in workspace mode this does not work.

**Comment by bwateratmsft** [comment]
@alexr00 The task execution is executing in the right place (on the remote Linux server) but trying to use the wrong shell (powershell). Our code for this is [here](https://github.com/microsoft/vscode-docker/blob/master/src/utils/executeAsTask.ts#L11-L54). Any ideas what's going wrong? Is there an option we're forgetting to pass?

**Comment by KennyChen0909** [comment]
@bwateratmsft Do we have a workaround for my customer for this issue?

**Comment by alexr00** [comment]
@bwateratmsft I will need to debug and see. There's nothing obvious I can think of.

**Comment by alexr00** [comment]
Looks like we were falling back to the local details when there wasn't a folder open. It makes more sense to fallback to the first remote's details instead. Change has been pushed to VS Code. Please test it in insiders once it is available!

**Comment by bwateratmsft** [comment]
Thank you for the fast fix as always @alexr00! I'll try it out in Insiders ASAP.

@KennyChen0909 As a workaround, if you open any folder in the remote window (even an empty one) with File -> Open Folder, it should cause the commands to start working.

**Comment by bwateratmsft** [comment]
@alexr00 everything seems to be working perfectly now, thank you!

@KennyChen0909 I'm going to close this as fixed since there's no additional work to be done in the Docker extension; I assume the fix should be available in VSCode 1.50.0; it is in Insiders now.

**Comment by bwateratmsft** [comment]
This is now fixed in VSCode 1.50.
