### ISSUE TITLE
Display a stopped container after composing up a .NET Core Console app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2351]
**OS:** Windows 10
**Build Version:** 20200924.1
**.NET Core:** 5.0.100-rc1.1.20452.10

**Repro Steps:**
1. Create a .NET Core Console app by "dotnet new console".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> .NET Core Console --> Linux --> Include optional Docker Compose files.
4. Update the Program.cs to have a continuous loop so the program doesn't exit.
5. Change the image to alpine.
![image](https://user-images.githubusercontent.com/45614674/94408725-c4ed8a00-01a7-11eb-8df6-f80d541b3361.png)
6. Right click the docker-compose.yml --> Select "Compose Up" --> Check the container in Docker container view.

**Expect:**
Display a running container after composing up.

**Actual:**
Display a stopped container when finishing composing up.
![image](https://user-images.githubusercontent.com/45614674/94408817-e8183980-01a7-11eb-9aa4-2ecea0082378.png)

**More Info:**
1. Fail to start the stopped container from the context menu.
2. This issue does not reproduce for Debian and Ubuntu images.
3. This issue does not reproduce for .NET Core MVC project.

**Comment by bwateratmsft** [comment]
I was not able to reproduce. @v-ruizh Can you right click the container and do "View Logs" and share the output?

**Comment by v-ruizh** [comment]
> Executing task: docker logs -f 391357e0d0ba309a94c64b448e6ab9cdb4c04411e10962f33d7356cd0710dbb3 <

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0-rc.1.20451.14' was not found.
  - The following frameworks were found:
      5.0.0-preview.8.20407.11 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0-rc.1.20451.14&arch=x64&rid=alpine.3.12-x64

Terminal will be reused by tasks, press any key to close it.

**Comment by bwateratmsft** [comment]
My best guess is that the Alpine image there is a little old on the machine where the issue reproduces. If you find the `mcr.microsoft.com/dotnet/runtime:5.0-alpine", and do right click -> Run Interactive, you can get a shell. I tested in the latest alpine image, and here's what I see--
```
/ # dotnet --list-runtimes
Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

If it says that 5.0.0-preview.8 is the latest, try right click -> Pull on the image and see if that fixes the issue.
