### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by aliqamer** [microsoft/vscode-docker#2357]
- Issue Type: `Bug`
- Extension Name: `vscode-docker`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 18341,
		"activateCallTime": 10,
		"activateResolvedTime": 516,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-azuretools.vscode-docker",
				"_lower": "ms-azuretools.vscode-docker"
			},
			"activationEvent": "onLanguage:yaml"
		}
	},
	"runtimeErrors": []
}
```

**Comment by bwateratmsft** [comment]
@aliqamer Can you elaborate on what the issue is?

**Comment by aliqamer** [comment]
I was working on my flutter project during which I found the docker extension failed to load and it gave me a message to "report" the issue. It copied above json in the clipboard. if it doesn't make sense plz close it.

**Comment by bwateratmsft** [comment]
Gotcha. I see that is a very long code loading time (18341 ms), typically it's 500ms or less depending on OS. Does this happen regularly or is this the only time you've seen it?

**Comment by aliqamer** [comment]
It happened just once so far, haven't been able to reproduce.

**Comment by bwateratmsft** [comment]
Ok. Keep an eye on it; if you see it happen again we can investigate. We've done a lot of optimizations lately for code loading so hopefully it won't be an issue but sometimes weird stuff happens.
