### ISSUE TITLE
Context panel shows "Switching..." UI forever

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2358]
VS Code 1.49.2 on Mac Catalina 10.15.6
Docker Extension 1.6.0

Repro steps
1. Create an ACI context
2. Right-click on the ACI context in the Context pane and choose "Use".

Expected: ACI context becomes the context-in-use and the UI updates accordingly

Actual: the UI remains in "Switching..." state forever

![image](https://user-images.githubusercontent.com/15271049/94621652-91713500-0265-11eb-921a-61cf0ef909f3.png)

This does not reproduce every time, but I have been seeing it at least once a day recently. As far as I can tell the ACI context is active, it is just that the UI somehow does not notice that the switch is complete.

**Comment by karolz-ms** [comment]
Some more observations:
- Refreshing the Contexts panel will "fix" it
- In the "Switching.." state the Container panel remains empty. So it is not just the Contexts panel that is not working--entire Docker view is in an intermediate, non-usable state

**Comment by bwateratmsft** [comment]
I'm guessing something isn't calling back under some circumstances, e.g. after the `docker context use` we aren't getting the callback that it finished.
