### ISSUE TITLE
Linting errors are not cleared for deleted files

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode-docker#237]
Steps to reproduce:

1. Open a new VS Code instance with this extension installed in an empty folder
2. Create a file called `Dockerfile`, but don't add any contents. You (correctly) get a linting error stating `No source image provided with FROM`
3. Delete the `Dockerfile`

Expected behavior:

The linting error disappears from the Problems pane.

Actual behavior:

The linting error is still displayed.

Footnote:

According to the [documentation for the language server protocol](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics), it's up to the extension to clear out messages by pushing an empty array.

**Comment by rcjsuen** [comment]
@tlycken Thank you very much for your bug report. I have reproduced the problem.

I will have to figure out how to detect this deletion event in the language server.

**Comment by rcjsuen** [comment]
@tlycken I have opened rcjsuen/dockerfile-language-server-nodejs#214 to capture this problem. I have also written up two proposed solutions there.

**Comment by rcjsuen** [comment]
@tlycken Thanks again for the bug report. This has been fixed in the 0.0.27 release.
