### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AXZV** [microsoft/vscode-docker#2373]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Saturn\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@AXZV does this happen regularly?
