### ISSUE TITLE
Trying to connect to docker container

### ISSUE THREAD

**Issue by xjoshbrownx** [microsoft/vscode-docker#2374]
Issue Type: <b>Bug</b>

Trying to open docker at remote distro using prompts. Logs say .vscode-server/bin/xxxxxxxx/node not found.

 
![image](https://user-images.githubusercontent.com/11632883/95280058-1d64fd00-0822-11eb-8513-cfd9e8646184.png)

Extension version: 1.6.0
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.01GB free)|
|Process Argv|--crash-reporter-id 556037a4-6803-44ff-82ed-5091d20fa748|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|Memory (System)|12.33GB (9.55GB free)|
|VM|0%|
</details>

**Comment by PavelSosin-320** [comment]
Your assumption that docker-desktop is a 'general-usage" WSL distro: wsl -d docker-desktop. But it is not. This is Docker Desktop dedicated distro. It is better to use another distro, Ubuntu for example, and configure its WSL integration in the Docker Desktop setting.
You will not be able to maintain Docker-desktop distro rootfs when it will be filled 100% by the Docker's artifacts.
In both cases, your target distro and docker-desktop will share the same singleton WSL VM with its IP, ports, etc.

**Comment by karolz-ms** [comment]
@PavelSosin-320 is right (thanks a bunch!)

@xjoshbrownx please use a general-purpose distro as the basis for a containerized development environment. For an overview of options check out https://code.visualstudio.com/docs/containers/choosing-dev-environment
