### ISSUE TITLE
Builds for service css pass

### ISSUE THREAD

**Issue by samuel-velazquez** [microsoft/vscode-docker#2375]
Issue Type: <b>Bug</b>

andwer request so back trial´s are model someone like string if regular expess only called in target blank ios platform (have) todo in setting or plug aset info talks yours tasks access time.

Extension version: 1.6.0
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2117U @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.73GB free)|
|Process Argv|--crash-reporter-id 1c0edcc5-a745-43d2-919e-3d08e3f58ec8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
This user is a bot continually posting spam all over the place. I reported them, no result yet.
