### ISSUE TITLE
Error 500 while trying to tag image using ipaddress:port/imagename format

### ISSUE THREAD

**Issue by PlkMarudny** [microsoft/vscode-docker#2376]
While trying to use tag for a local registry 10.0.x.x:5000/image, the extension reports the tag format is wrong.

Windows 10 Pro 1903

**Comment by karolz-ms** [comment]
@PlkMarudny can you please provide detailed repro steps?

In the example above there is no tag in the image name has no tag. See https://docs.docker.com/engine/reference/commandline/tag/ for examples

**Comment by bwateratmsft** [comment]
This is by-design. This image name format isn't valid as @karolz-ms points out. The CLI lets you get away with it because it implicitly adds `:latest`, but the API requires you to be explicit. If I do `10.0.x.x:5000/image:latest` it works.
