### ISSUE TITLE
The terminal process failed to launch: Path to shell executable "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist.

### ISSUE THREAD

**Issue by sjuratov** [microsoft/vscode-docker#2378]
I am running VS Code on my local Windows VM.

I have installed VS Code Remote Development extension so that I can SSH to remote Ubuntu VM. After successful SSH to this remote VM, I was able to create new Docker image using docker cmdline.

Now I want to push this image to ACR, so I have installed VS Code Docker extension (I can see after install that it is SSH installed, not local). I can login to Azure, find my ACR, see images I have published.

However, when I try either push an image (from Ubuntu VM) to ACR, or pull an image from ACR to Ubuntu VM, I get following error:

---------------------------------

> Executing task: docker pull 5c5dd98e724841e884500abc807070b9.azurecr.io/azureml/azureml_788671660c5ec027a2dbf2ff5cda3e5c:latest <

The terminal process failed to launch: Path to shell executable "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist.

Terminal will be reused by tasks, press any key to close it.

---------------------------------

Why is Docker extension trying to use PowerShell? Obviously this path doesn't exist on remote Ubuntu VM. What am I missing?

**Comment by bwateratmsft** [comment]
Looks the same as #2350 which is a VS Code bug. Can you try opening a workspace folder on the remote side? Or use the latest VS Code Insiders build?

**Comment by sjuratov** [comment]
Opening a workspace folder on the remote side solved the problem. Thanks!
