### ISSUE TITLE
Add lint rule forbidding single quotes in Dockerfile

### ISSUE THREAD

**Issue by AnalyzePlatypus** [Microsoft/vscode-docker#238]
According to the [Dockerfile documentation](https://docs.docker.com/engine/reference/builder/#run), `CMD`'s array syntax must use double quotes:

> Note: The _exec_ form is parsed as a JSON array, which means that you must use double-quotes (“) around words not single-quotes (‘).
```
# Valid
CMD ["/bin/bash", "echo", "this should work"]

# Invalid
CMD ['/bin/bash', 'echo', 'mysteriously fails']
```
This build will fail with the unintelligible error `/bin/sh: 1: /bin/echo,: not found`
I just spent a few hours scratching my head, until I found [this StackOverflow answer](https://stackoverflow.com/a/30651455/6068782).

Can we include a lint rule that explicitly complains if the wrong form of quotes in used?
([Discussion over on the Moby project](https://github.com/moby/moby/issues/5701).)

**Comment by rcjsuen** [comment]
Hi, @AnalyzePlatypus. Thank you for using vscode-docker and thank you for opening this bug report!

I have opened rcjsuen/dockerfile-utils#28 to track this in the validator. We can leave this issue until a) it is fixed and b) the vscode-docker extension has adopted the fix.

**Comment by AnalyzePlatypus** [comment]
This correct place for this change is in the `dockerfile-language-service`  repo.
I've opened this issue there ([#32]('https://github.com/rcjsuen/dockerfile-language-service/issues/32')).

This should be closed.

**Comment by AnalyzePlatypus** [comment]
@rcjsuen, thanks for your fast response!

**Comment by rcjsuen** [comment]
@AnalyzePlatypus Thanks again for the bug report. This new linting rule has been added in the 0.0.27 release.
