### ISSUE TITLE
[Codespaces] The new created context does not exist in context view until refresh

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2382]
**OS:** Windows 10
**Build Version:** 20201009.1

**Repro Steps:**
1. Create a Linux Codespace and connect it.
2. Install Docker extension in this Codespace.
3. Create a new context using command and check it in context view.

**Expect:**
The new created context shows in context view.
![image](https://user-images.githubusercontent.com/45614674/95652010-9e710c80-0b20-11eb-8518-918f009785ff.png)

**Actual:**
The new created context does not exist in context view until refresh.

**Comment by bwateratmsft** [comment]
@karolz-ms I assume because `~/.docker/config.json` can't be watched from within a codespace. IMO not a big deal, I don't think contexts would be used much if at all within codespaces.

**Comment by karolz-ms** [comment]
@bwateratmsft the ACI/ECS contexts might get some use, although there is an extra step of installing the new CLI into the codespace to take advantage of the Docker cloud integration. The scenario fits into the overall "stuff works great in the cloud" theme and I know that @BigMorty is eager to show Codespaces + ACI to the world.

That is why I think we will need to find a way to fix this, and related bug (2383).

**Comment by bwateratmsft** [comment]
We discussed this and decided to won't-fix this one, and fix #2383. There's not a great way to deal with this without introducing some sort of periodic refresh, which I'm not a fan of. Additionally, going and refreshing the contexts view is likely a natural user action, so it might not be a big deal for them.

**Comment by BigMorty** [comment]
If I have just clicked the + sign to create a context, I would expect that to show up!

**Comment by karolz-ms** [comment]
> If I have just clicked the + sign to create a context, I would expect that to show up!

Yes, this is issue https://github.com/microsoft/vscode-docker/issues/2383 and that one **will** be fixed

**Comment by BigMorty** [comment]
Gotcha, thanks!
