### ISSUE TITLE
[Codespaces] The context keeps "Switching" state after using a different one

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2383]
**OS:** Windows 10
**Build Version:** 20201009.1

**Repro Steps:**
1. Create a Linux Codespace and connect it.
2. Install Docker extension in this Codespace.
3. Create a new context.
4. Use this new context and check the result.

**Expect:**
Switch to the new context successfully.

**Actual:**
The context keeps "Switching" state after using a different one.
![image](https://user-images.githubusercontent.com/45614674/95652166-c4e37780-0b21-11eb-876a-7f12a2db6f91.png)

**Comment by bwateratmsft** [comment]
Probably the same root cause as #2382, we issue the `docker context use` command and then wait until the context change event is picked up, but that event _can't_ be picked up from codespaces because we can't listen for changes to `~/.docker/config.json`.

**Comment by bwateratmsft** [comment]
Similar issue to #2358, maybe both can be fixed the same way and #2382 have an independent fix.

(#2358 might already be fixed)
