### ISSUE TITLE
docker desktop not able to be uninstalled.

### ISSUE THREAD

**Issue by Justpro77** [microsoft/vscode-docker#2385]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.contexts.inspect
Error type: 1
Error Message: Process 'docker context inspect default' exited with code 1
Error: exec: "com.docker.cli": executable file not found in %PATH%

Version: 1.6.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:33:76269
ChildProcess.emit events.js:223:5
ChildProcess.EventEmitter.emit domain.js:475:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by PavelSosin-320** [comment]
In my  Docker Desktop CE 2.4.1 Docker version 19.03.13 installed on updated Windows build Such a problem doesn't exist anymore. It looks like Mirantis (the new Docker owner) already solved it with other issues. Try to upgrade without uninstalling.

**Comment by bwateratmsft** [comment]
@justpro77 can you add more details?

**Comment by Justpro77** [comment]
I already solved , thank you guys.
