### ISSUE TITLE
vs code debug project

### ISSUE THREAD

**Issue by mertker** [microsoft/vscode-docker#2390]
Does this occur consistently? 
Repro steps:

1.
2.

Action: debugCoreClr
Error type: SyntaxError
Error Message: Unexpected token e in JSON at position 0

Version: 1.6.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDaemonIsLinuxPrerequisite.checkPrerequisite extension.bundle.js:897:296308
processTicksAndRejections task_queues.js:94:5
extension.bundle.js:897:299741extension.bundle.js:897:299741
async AggregatePrerequisite.checkPrerequisite extension.bundle.js:897:299691
async DockerNetCoreDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:1276:115809
extension.bundle.js:1276:115063extension.bundle.js:1276:115063
```

</details>

launch.json

{
  "version": "0.2.0",
  "compounds": [
    {
      "name": "Launch All API (Docker)",
      "configurations": ["Identity.API Launch (Docker)"]
    }
  ],
  "configurations": [
    {
      "name": "Identity.API Launch",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build identity api",
      "program": "${workspaceFolder}/Services/Identity/Identity.API/bin/Debug/netcoreapp3.1/Identity.API.dll",
      "args": [],
      "cwd": "${workspaceFolder}/Services/Identity/Identity.API",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    {
      "name": "Identity.API Launch (Docker)",
      "type": "docker-coreclr",
      "request": "launch",
      "preLaunchTask": "build identity api",
      "configureAspNetCoreSsl": false,
      "appProject": "${workspaceFolder}/Services/Identity/Identity.API/Identity.API.csproj",
      "dockerBuild": {
        "dockerfile": "${workspaceFolder}/Services/Identity/Identity.API/Dockerfile",
        "context": "${workspaceFolder}/Services/Identity/Identity.API",
        "target": "base"
      },
      "dockerRun": {}
    }
  ]
}

tasks.json

{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build identity api",
      "command": "dotnet",
      "type": "process",
      "args": [
        "build",
        "${workspaceFolder}/Services/Identity/Identity.API/Identity.API.csproj",
        "/property:GenerateFullPaths=true",
        "/consoleloggerparameters:NoSummary"
      ],
      "problemMatcher": "$msCompile"
    },
  ]
}

**Comment by mertker** [comment]
docker file

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Services/Identity/Identity.API/Identity.API.csproj", "Services/Identity/Identity.API/"]
RUN dotnet restore "Services/Identity/Identity.API/Identity.API.csproj"
COPY . .
WORKDIR "/src/Services/Identity/Identity.API"
RUN dotnet build "Identity.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Identity.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.API.dll"]

**Comment by bwateratmsft** [comment]
@mertker The `docker-coreclr` debug configuration has been deprecated for some time now and will be removed entirely in the upcoming 1.7.0 release. Please switch over to a [`docker` debug configuration](https://code.visualstudio.com/docs/containers/debug-common). You can run `Docker: Initialize for debugging` to create the debug config and tasks.
