### ISSUE TITLE
[Codespaces] Fail to create a new ACI context in codespace environment

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2391]
**OS:** Windows 10
**Build Version:** 20201012.4

**Repro Steps:**
1. Connect to a codespace and install [new CLI](https://github.com/docker/compose-cli/blob/main/INSTALL.md#ubuntu-linux-installation) into this codespace.
2. Right click on one image in the registries view -> Deploy Image to Azure Container Instances... -> Create a new ACI context following the wizard.
3. Check the result.

**Expect:**
Succeed to create a new ACI context.

**Actual:**
Fail to create a new ACI context. (There is no sign in wizard during creating ACI context)
![image](https://user-images.githubusercontent.com/45614674/95836014-86dc9280-0d71-11eb-92e0-8ce18a135b92.png)

**More Info:**
This issue does not reproduce without codespace.

**Comment by bwateratmsft** [comment]
@karolz-ms this is definitely going to be an issue. Any ideas how to solve it?

**Comment by karolz-ms** [comment]
Running through the scenario today I see two issues:

1. When one initiates step 2 without being logged to Azure via Docker CLI (`docker login azure`), the extension displays "Creating ACI context 'blah'" toast and **just never progresses from there**.
 
    After logging in to Azure (using device login flow, which Docker CLI correctly executes) the rest of the process of creating a context and completing the deployment to ACI works 

2. (after successful deployment) The Containers pane is not able to show the running ACI container. Instead, the pane shows **`Error: 14 UNAVAILABLE:  No connection established`** error message. Docker CLI (`docker ps`, `docker logs` etc) work fine.

I won't be able to work on this this week (sorry), so re-assigning to @bwateratmsft

**Comment by bwateratmsft** [comment]
There must be something wrong with the login flow, in that case. The code already attempts to log in if it gets a specific error (5) back from the first attempt: https://github.com/microsoft/vscode-docker/blob/master/src/tree/contexts/aci/AciContextCreateStep.ts#L24-L37

I'm guessing that `docker login azure` we're trying is hanging or something like that.

**Comment by bwateratmsft** [comment]
Oh, I see. It's trying to do device auth but can't because it's doing this in the background. We should move the `docker login azure` to the terminal.

**Comment by bwateratmsft** [comment]
@gtardif, regarding the `Error: 14 UNAVAILABLE: No connection established`: the `docker serve` daemon is not running in a codespace. Is there any way to make it start?

**Comment by bwateratmsft** [comment]
Potentially fixed by #3263.

**Comment by bwateratmsft** [comment]
Closing since we're doing ACA instead with #3535.
