### ISSUE TITLE
Failed to attach vscode

### ISSUE THREAD

**Issue by chong1144** [microsoft/vscode-docker#2396]
## Behaviour
Failed to attach vscode to an already running containers
![image](https://user-images.githubusercontent.com/35533252/95967532-efde0c00-0e3e-11eb-9810-45e8e9775381.png)

![image](https://user-images.githubusercontent.com/35533252/95967750-2e73c680-0e3f-11eb-9089-169a9c081959.png)

However, attach shell works fine, which means `docker exec` is okay.

![image](https://user-images.githubusercontent.com/35533252/95967922-6bd85400-0e3f-11eb-81fe-ba7adcbf25fc.png)

## Other information
This is on remote server which is installed docker extension

- docker extension: 1.6.0
- remote containers: 0.145.0
- vscode: 1.50.0

**Comment by chong1144** [comment]
It really confused me a lot. Also, it did work.
Hope someone can help. Thanks!

**Comment by bwateratmsft** [comment]
@chong1144 The "Attach Visual Studio Code" feature is actually part of the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. Can you open an issue in their repo here: https://github.com/microsoft/vscode-remote-release
