### ISSUE TITLE
How do I associate Dockerfile_xxx ?

### ISSUE THREAD

**Issue by vikas027** [Microsoft/vscode-docker#240]
Hey,

At the moment my VS Code automatically recognizes `Dockerfile`, I need to do the same with `Dockerfile_<something>` as I have multiple Dockerfiles in my repository.

I understand that this could be done by `files.associations` in User settings something like below
```
"Jenkinsfile*": "groovy"
```
I am not sure how do I do the same with this plugin. I have already tried below options in vain
```
"Dockerfile_*": "docker"
"Dockerfile_*": "Docker"
```
Any ideas how to achieve this? Thanks!

Cheers,
Vikas

**Comment by chrisdias** [comment]
the type is `dockerfile`, not `docker`.  try this in your `settings.json`:

``` json
    "files.associations": {
        "dockerfile_*": "dockerfile"
    }
```
