### ISSUE TITLE
Getting error Invalid URL user@ip in Visual Studio Code Remote Containers after Reopen Locally

### ISSUE THREAD

**Issue by kzawad1** [microsoft/vscode-docker#2400]
Does this occur consistently? YES
Repro steps:

1. In Visual Studio Code Remote Containers and connected to container.
2. Choose Reopen Locally.
3. Wait until Visual Studio Code reopens locally.

Action: docker-context.initialize
Error type: ERR_INVALID_URL
Error Message: Invalid URL: user@x.x.x.x

Version: 1.6.0
OS: linux
OS Release: 5.4.0-51-generic
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
onParseError url.js:243:9
new URL url.js:319:5
extension.bundle.js:1276:124859
Object.<anonymous> extension.bundle.js:33:983874
extension.bundle.js:33:983065
o extension.bundle.js:33:982751
Object.callWithTelemetryAndErrorHandling extension.bundle.js:33:983782
DockerContextManager.loadContexts extension.bundle.js:1276:124199
AsyncLazy.valueFactory extension.bundle.js:1276:122564
AsyncLazy.getValue extension.bundle.js:33:223891
DockerContextManager.getContexts extension.bundle.js:1276:123765
DockerContextManager.getCurrentContext extension.bundle.js:1276:123820
DockerContextManager.refresh extension.bundle.js:1276:123178
extension.bundle.js:84:584201
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment]
@kzawad1 what do you have for `docker.host` / `DOCKER_HOST`?

**Comment by kzawad1** [comment]
I am not setting the DOCKER_HOST manually.  However, the ~/.config/Code/User/settings.json file is set to:
```{
    "workbench.iconTheme": "vscode-icons",
    "docker.host": "user@x.x.x.x"
}```

Is doesn't make sense that it gives that error when it can clearly connect to the remote host.

**Comment by bwateratmsft** [comment]
Are you using SSH to connect? If so try changing that `docker.host` value to `ssh://user@x.x.x.x`.

**Comment by kzawad1** [comment]
Modifying that value worked:
```
{
    "workbench.iconTheme": "vscode-icons",
    "docker.host": "ssh://user@x.x.x.x"
}
```

No more error.
