### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by whuera** [microsoft/vscode-docker#2401]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Command failed: docker login  --username whuera --password-stdin
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.6.0
OS: linux
OS Release: 5.4.0-48-generic
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:304:12
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:223:5
Pipe.<anonymous> net.js:664:12
```

</details>

**Comment by bwateratmsft** [comment]
@whuera have you followed the [steps](https://docs.docker.com/engine/install/linux-postinstall/) to enable using Docker as a non-root user on Linux?
