### ISSUE TITLE
No error occurs if fail to create a new ACR during executing push action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2402]
**OS:** Windows 10
**Build Version:** 20201014.2

**Repro Steps:**
1. Right click one image and select "Push..." -> Select "+ Create new registry..." to create a new ACR with "Australia Central" location.
2. Check the result.

**Expect:**
An error occurs during ACR creation.
![image](https://user-images.githubusercontent.com/45614674/96104945-08682800-0f0c-11eb-9ab8-8f91445769ca.png)

**Actual:**
No error occurs, the output shows "Creating registry..." but the tag image text box pops up.
![image](https://user-images.githubusercontent.com/45614674/96103071-d229a900-0f09-11eb-9f1d-e91ad5ab79cc.png)

**More Info:**
Fail to create a new registry with "Australia Central" separately, this location is not supported.

**Comment by bwateratmsft** [comment]
I can reproduce, I'll take a look. Doesn't seem urgent for 1.7.0 though.

**Comment by bwateratmsft** [comment]
The code at "fault" here is [this](https://github.com/microsoft/vscode-docker/blob/master/src/commands/images/pushImage.ts#L33-L40). I'm struggling to remember why I implemented it this way but I think it was so that a user could push images without having a matching registry connected.

**Comment by bwateratmsft** [comment]
IIRC we wanted to catch and ignore the `NoResouceFoundError` [sic]. This error isn't exposed by `vscode-azureextensionui`'s API so we would need to expose it there if we want to specifically catch and ignore that error but not others.
