### ISSUE TITLE
[Suggestion] Remove the unsupported location from the location list when creating a new ACR

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2403]
**OS:** Windows 10
**Build Version:** 20201014.2

**Repro Steps:**
Create a new ACR with "Australia Central" location.

**Actual:**
Fail to create the ACR with an error.
![image](https://user-images.githubusercontent.com/45614674/96105537-ba075900-0f0c-11eb-9e50-d2a3034b893c.png)

**Suggestion:**
Remove the unsupported location from the location list.
![image](https://user-images.githubusercontent.com/45614674/96105908-27b38500-0f0d-11eb-9e26-cc7b3b855903.png)

**Comment by bwateratmsft** [comment]
We would need a good way to know and maintain a list of what regions are supported.

**Comment by bwateratmsft** [comment]
Looks like there is no way to list locations for container registries, unlike app service which has `WebsiteManagementClient.listGeoRegions()`. I don't really want to try to maintain a list of supported regions as it would be too easy to let it get out of date. I think the best approach therefore is to leave things as they are; users might hit errors but at least we wouldn't be accidentally blocking them from using a valid region.
