### ISSUE TITLE
The running container is not automatically displayed in the "Container" list after executing "Run" command with the other software is opening

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2404]
**OS:** Mac
**Build Version:** 20201014.2

**Repro steps:**

1. Open VS Code -> Navigation to Docker Image node -> Expand the Image node -> Open other software (e.g. Terminal).
2. Right click an image ->  Select "Run".
3. Check the result.

**Expect:**
The running container is automatically displayed in the "Container" list.

**Actual:**
The running container is not automatically displayed in the "Container" list. ( Please get a video from [docker.zip](https://github.com/microsoft/vscode-docker/files/5383920/docker.zip))

**More Info:**
This issue doesn't reproduce on Windows/Linux.

**Comment by PavelSosin-320** [comment]
Docker runs containers asynchronously and emits Docker events about container status changes.  What is the running container exactly, Docker ps list, keepalive response is OK. Docker container ls with a certain filter like status=running. docker wait doesn't show the container exit code?
Even orchestration engines give different answers to the Docker service ps and ls questions. 
Container exists after it is created and "Created" event is emitted.
If the 3rd party tool doesn't observe Docker container events it can't know the exact status. It can only do polling of the container's status, i.e. shows a picture with delay.

**Comment by bwateratmsft** [comment]
I think this is a consequence of VSCode's implementation on Mac, along with our logic to stop refreshing if VSCode does not have focus. I'll double check but if so there isn't anything we could do to fix it.

**Comment by bwateratmsft** [comment]
Yep, I verified--this is because the window is not considered focused in this scenario. We can't fix this without going back to refreshing when the window is out of focus, which we don't want to do for perf reasons.
