### ISSUE TITLE
Process get and member descripts node url

### ISSUE THREAD

**Issue by samuel-velazquez** [microsoft/vscode-docker#2407]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username sesoshumanos --password-stdin
"docker" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Version: 1.6.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:304:12
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
Go away bot
