### ISSUE TITLE
The port of docker-compose.yml file is blank when adding compose files to workspace with port 443 for a ASP.NET Core mvc project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2408]
**OS:** All
**Build Version:** 20201014.2

**Repro steps:**

1. Create a .NET Core Console app by "dotnet new console".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace..." --> ASP.NET Core --> Linux
 --> Include optional Docker Compose files --> Ports: 80,443.
4. Check the docker-compose.yml file.
5. F1 --> Type and select "Docker: Add Docker Compose Files to Workspace..." -> ASP.NET Core  --> Linux --> Port: 443 --> Overwrite All.
6. Check the docker-compose.yml file.

**Expect:**
The port of docker-compose.yml file is 443.

**Actual:**
The port of docker-compose.yml file is blank.
![image](https://user-images.githubusercontent.com/62053665/96234734-678d7180-0fcc-11eb-9979-e5e6a4d36823.png)

**More Info:**

1. This issue also reproduces for the docker-compose.debug.yml file.
2. This issue doesn't reproduce when entering other ports.

**Comment by bwateratmsft** [comment]
This is sort of by design; we intentionally remove 443 in the compose file for .NET because setting up HTTPS is far too complicated with compose. However, ideally that `ports:` should not show up.

**Comment by bwateratmsft** [comment]
@karolz-ms I'm curious what you think would be the best way to handle this...should we just put 80 back in?

**Comment by karolz-ms** [comment]
I think we should
1. Stop scaffolding HTTPS ports at all (we have ample customer evidence to support this change)
1. Use whatever ports the user specified and not assume that 443 == HTTPS

**Comment by bwateratmsft** [comment]
> 1. Stop scaffolding HTTPS ports at all (we have ample customer evidence to support this change)

Won't hear any argument from me. :smile:

**Comment by bwateratmsft** [comment]
Collapsing this issue into #1835. The solution for this and that are really the same.
