### ISSUE TITLE
There is no validation when inputting a duplicate ACI name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2409]
**OS:** All
**Build Version:** 20201014.2

**Repro Steps:**
1. Create a new ACI context.
2. Click "Create ACI context" button and input the above ACI name.

**Expect:**
There is a validation to say the context already exists.

**Actual:**
There is no validation when inputting a duplicate ACI name.
![image](https://user-images.githubusercontent.com/45614674/96238553-34011600-0fd1-11eb-8269-fbb358427aec.png)

**More Info:**
There is an error during creation.
![image](https://user-images.githubusercontent.com/45614674/96238598-3f544180-0fd1-11eb-9f02-bb75b475d9e7.png)

**Comment by bwateratmsft** [comment]
Should be a relatively easy enhancement.
