### ISSUE TITLE
Docker build "platform" support

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-docker#241]
Docker 18.02 as I understand it adds ability in Windows for Docker to build a Linux-based image while under Windows container mode. However, in order to do that, you have to provide the `--platform linux` on the build command.

Can this functionality be added to the command palette prompts when we are building an image?

Right now I'm getting:

```PS C:\git\sqllinux-with-agent> docker build --rm -f dockerfile -t sqllinux-with-agent:latest .
Sending build context to Docker daemon   59.9kB
Step 1/9 : FROM microsoft/mssql-server-linux:latest
latest: Pulling from microsoft/mssql-server-linux
cannot download image with operating system "linux" when requesting "windows"```

So potentially after it prompts for "tag image as..", have it prompt whether we want to use another platform.

**Comment by wsmelton** [comment]
Just adding an example of the platform parameter

![image](https://user-images.githubusercontent.com/11204251/38150797-5b4d6e4a-3426-11e8-86ff-cf29957d7e65.png)

**Comment by chrisdias** [comment]
the docs show `--platform` as experimental for `build` and `pull`.  

![image](https://user-images.githubusercontent.com/1487073/38156812-e0874806-3435-11e8-991e-a7359951cfa9.png)

**Comment by chrisdias** [comment]
Is `--platform` something you always set, such that it should be a setting instead of another command?

**Comment by wsmelton** [comment]
If you have Docker for Windows in Windows Mode you have to supply that parameter to pull or build an image/container that is not Windows OS. So any Linux based image/container requires that parameter to be passed in. 

If you are building a Windows-based container I believe providing that parameter causes the command to fail, so it would not be efficient to have it as a setting that I know.

**Comment by StephenWeatherford** [comment]
@wsmelton We feel this is a special case that probably doesn't make sense to support directly. I would like to see us be more customizable in the commands that are used, that's something we might look at in the coming releases.  Thanks for bringing it up, though.
