### ISSUE TITLE
There is no validation when inputting an invalid Docker ID during connecting to Docker Hub registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2410]
**OS:** All
**Build Version:** 20201014.2

**Repro Steps:**
F1 -> Docker Registries: Connect Registry... -> Select Docker Hub -> Enter an invalid Docker ID.

**Expect:**
There is a validation, like sign in from website.
![image](https://user-images.githubusercontent.com/45614674/96239186-fa7cda80-0fd1-11eb-9559-262631600a32.png)

**Actual:**
There is no validation.
![image](https://user-images.githubusercontent.com/45614674/96239025-be497a00-0fd1-11eb-8cd7-08cb42528186.png)

**Comment by bwateratmsft** [comment]
This is by design for now; that same username prompt is shared by all registries so there wouldn't necessarily be consistent naming rules.
