### ISSUE TITLE
An error occurs when debugging Django/Flask project with host network

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2411]
**OS:** Windows 10
**Build Version:** 20201014.2

**Repro Steps:**
1. Open a Python Django project in VS Code.
2. Add Dockerfile and docker compose files to it.
3. Execute "Compose Up" for docker-compose.yml file.
4. In the task "docker-run: debug", add the host network in the dockerRun property:
"dockerRun": {
"network": "host"
}
5. F5.

**Expect:**
No error occurs during debugging.

**Actual:**
An error "Error: That port is already in use" occurs.
![image](https://user-images.githubusercontent.com/45614674/96249002-163aad80-0fdf-11eb-88fa-d138c557030c.png)

**More Info:**
1. This issue does not reproduce if skip step 3.
2. This issue does not reproduce if use "bridge" network.
3. The error shows as below when debugging Flask project.
![image](https://user-images.githubusercontent.com/45614674/96249202-6b76bf00-0fdf-11eb-8674-56ac5f91c34e.png)

**Comment by bwateratmsft** [comment]
This is a limitation of the way Python debugging works. Only the bridge network can be used.
