### ISSUE TITLE
Fail to execute the "Docker Images: Run Azure CLI" command on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2412]
**OS:** Mac
**Build Version:** 20201014.2

**Repro steps:**

1. Run command : `docker login` -> Enter GitHub username and password.
2. F1 -> Type and select: "Docker Images: Run Azure CLI".
3. Check the result.

**Expect:**
Succeed to execute the "Docker Images: Run Azure CLI" command.

**Actual:**
Fail to execute the "Docker Images: Run Azure CLI" command.
![Screen Shot 2020-10-16 at 7 04 02 PM](https://user-images.githubusercontent.com/62053665/96252965-5dc43800-0fe5-11eb-8dd8-9a4112bd2410.png)

**Comment by bwateratmsft** [comment]
Strange. There's probably an MCR image we should switch to, though.
