### ISSUE TITLE
Attaching shell does not focus terminal

### ISSUE THREAD

**Issue by dschuessler** [microsoft/vscode-docker#2413]
Steps to reproduce on macOS:

1. Start up some Docker container that runs indefinitely.
2. Shift+Cmd+P (or whatever opens the command picker on other systems besides macOS)
3. Select "Docker Containers: Attach Shell"
4. Select the container

Expected behavior: A terminal is opened and I can type in it right away.
Actual behavior: A terminal is opened but it is out of focus. I have to click on the terminal to be able to type in it.

Other commands that open a terminal (like "Debug: Create Javascript Debug Terminal") focus it per default.

**Comment by bwateratmsft** [comment]
I'm not able to reproduce the issue, what has focus in the bottom pane when it happens for you?

**Comment by jeroendk** [comment]
Got the same issue. When the focus is on the code editor before opening, the code editor keeps the focus. When I have another terminal focused, the focus completely disappears.

**Comment by bwateratmsft** [comment]
Ok, with my cursor in the text editor window, focus stayed there. I'll take a look.

**Comment by bwateratmsft** [comment]
I found the root cause and the fix should be quite simple.

**Comment by bwateratmsft** [comment]
This fix has now been released in 1.8.0.
