### ISSUE TITLE
(Optionally) ask for project name at Docker compose start

### ISSUE THREAD

**Issue by rugk** [microsoft/vscode-docker#2418]
**Use case:** If you use Docker compose, you may have multiple project names for one `docker-compose.yml` in order to start/stop different "instances".
I want to quickly switch between them/execute them, preferably with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>.

**Solution:** Docker has the [`COMPOSE_PROJECT_NAME`](https://docs.docker.com/compose/reference/envvars/#compose_project_name) variable or `-p` parameter for this.

**Suggestion:** It would be great if you could ask for the project name (at least optionally) when you try to run one of the Docker compose commands.

**Comment by bwateratmsft** [comment]
You may find this useful for your use case: https://code.visualstudio.com/docs/containers/reference#_command-customization

You could customize several different Compose Up commands and choose which one you want to run.

**Comment by rugk** [comment]
Indeed, thanks, this is a nice solution too, for now.
However, it seems to be missing `docker.commands.composeRestart`, i.e. the quite handy "Docker compose restart" command.
It asks for these then, but that is not really convenient.

**Comment by karolz-ms** [comment]
Docker will be adding project name as a Compose spec property: https://github.com/compose-spec/compose-spec/issues/106 

I believe this will cover your needs @rugk, but if not, or if you have other suggestions, please share!

**Comment by rugk** [comment]
Thanks, yeah. That does it exactly! :smiley:
