### ISSUE TITLE
Docker causing high cpu usage 

### ISSUE THREAD

**Issue by RJ-0605** [microsoft/vscode-docker#2419]

**Comment by bwateratmsft** [comment]
@RJ-0605 does this happen consistently?

**Comment by RJ-0605** [comment]
yeah it does it makes work quite sloe to complete and i  i use this on an ubuntu linux os version 

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by bwateratmsft** [comment]
Are things still slow if you disable the Docker extension?
