### ISSUE TITLE
An error occurs when adding docker files to workspace

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2424]
**OS:** Windows 10
**Build Version:** 20201020.8
**VS Code Insider build:**
![image](https://user-images.githubusercontent.com/45614674/96702898-ce43ce00-13c4-11eb-8efa-c9a7b6a31cae.png)

**Repro Steps:**
1. Create a .NET Core Console app by "dotnet new console".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace..." --> ASP.NET Core.

**Expect:**
Navigate to select OS part.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/96702953-dd2a8080-13c4-11eb-9535-6079eefffd35.png)

**More Info:**
This issue does not reproduce in VS Code build 1.50.1.

**Comment by bwateratmsft** [comment]
I can reproduce.

**Comment by bwateratmsft** [comment]
I verified this is now fixed in the latest Insiders build, thanks again @alexr00!
