### ISSUE TITLE
cannot build docker image in vs code

### ISSUE THREAD

**Issue by mtahle** [microsoft/vscode-docker#2425]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: To build Docker files you must first open a folder or workspace in VS Code.

Version: 1.7.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.quickPickWorkspaceFolder extension.bundle.js:52:44124
buildImage extension.bundle.js:594:237053
extension.bundle.js:594:267249
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment]
@mtahle you will need to open a workspace folder or workspace to build Docker images.
