### ISSUE TITLE
Build image from Dockerfile fails in version 1.5-1.7.

### ISSUE THREAD

**Issue by wanfengkai** [microsoft/vscode-docker#2427]
Sorry for raise this issue again but the same issue arise in newest version again.
**Mirroring issue:**
[https://github.com/microsoft/vscode-docker/issues/2366](https://github.com/microsoft/vscode-docker/issues/2366)

**Problem description:**
This bug emerges continuously from version 1.5.0 to 1.7.0.

Right click & build image in VScode only works with version 1.4.0 and older ones.

The bug could be miss configuration of docker cli in PATH or some miss-alignment with new docker version?

![image](https://user-images.githubusercontent.com/16138109/96840923-64223c00-144b-11eb-9ed5-1b0e6850afb8.png)

**Environments:**
Mac OS latest, VScode latest, Docker Desktop latest, I'm building with a Dockerfile. 

**Work around if anyone comes across similar situation**

Downgrade this vscode-docker to 1.4.0.

**PS**
In my terminal I don't see such error but only in VScode.

**Comment by bwateratmsft** [comment]
This is the same issue as #2366, it is due to a bug in Docker Desktop. I've opened https://github.com/docker/compose-cli/issues/754 against them for it.
