### ISSUE TITLE
pull image with no tag fails

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#2434]
Issue Type: <b>Bug</b>

1. docker pull mcr.microsoft.com/dotnet/runtime@sha256:e091076ba28b0d10400a5c97f4d5287041092210d930896032014b6544a8f93e
2. This image will show as mcr.microsoft.com/dotnet/runtime:<none> in the images list
3. Right click and pull this image. It will fail
> Executing task: docker pull mcr.microsoft.com/azure-functions/dotnet:<none> <

The syntax of the command is incorrect.
The terminal process "C:\windows\System32\cmd.exe /d /c docker pull mcr.microsoft.com/azure-functions/dotnet:<none>" terminated with exit code: 1.

Extension version: 1.5.0
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19042

**Comment by bwateratmsft** [comment]
Hm, IIRC images without tags aren't even supposed to show up in the explorer.
