### ISSUE TITLE
Pj column

### ISSUE THREAD

**Issue by indira11-in** [microsoft/vscode-docker#2435]
Issue Type: <b>Bug</b>

columns php

Extension version: 1.7.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.75GB (0.29GB free)|
|Process Argv|--crash-reporter-id 159ff9e1-393b-43ff-a756-2bcc57f3f4da|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
@indira11-in can you add repro steps and explain what went wrong?
