### ISSUE TITLE
zte

### ISSUE THREAD

**Issue by chrisn805** [microsoft/vscode-docker#2436]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: EPERM
Error Message: EPERM: operation not permitted, open 'c:\Windows\System32\Recovery\requirements.txt'

Version: 1.7.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.51.0-insider
Language: en

**Comment by bwateratmsft** [comment]
@zte can you add repro steps?
