### ISSUE TITLE
Cannot use commands with tmux

### ISSUE THREAD

**Issue by magikid** [Microsoft/vscode-docker#244]
I am running OSX 10.12.6, VS Code 1.21.1, Docker extension 0.0.26.

Here is my current VS Code config:
```
{
    "terminal.integrated.shell.osx": "/Users/magikid/bin/code-shell",
    "terminal.integrated.shellArgs.osx": [],
}
```

And here is the code-shell command:
```
#!/bin/sh
SESSION="vscode`pwd | md5`"
tmux attach-session -d -t $SESSION || tmux new-session -s $SESSION
```

I like to use tmux so I have setup VS Code to use it in my integrated shell.  When I try to use the docker extension to start my containers, I see the commands echo'd to a terminal screen but nothing appears to ever run.

Is there a way to resolve this short of disabling tmux?

**Comment by chrisdias** [comment]
@Tyriar i can reproduce this problem, any ideas?  all we do in the extension is create a terminal and send the docker commands as text.

**Comment by Tyriar** [comment]
Not sure if there's a way to fix this other than adding a timeout before the `sendText` call, which could be flaky. I think the problem is that `sh` is consuming the sent text before tmux has a chance to launch.

**Comment by chrisdias** [comment]
maybe I could add an option `docker.tmuxDelay`.
