### ISSUE TITLE
Build image forces "--pull", makes local development inconvenient

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode-docker#2443]
When invoking the "Docker Images: Build Image..." command, the command-line executed always includes the `--pull` option, e.g. `docker build --pull --rm -f "Dockerfile" -t mything:tag .`

This invariably yields `pull access denied for mybase, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`, given a `Dockerfile` starting with 
```
FROM mybase:tag

ENV ...
```

This makes it inconvenient to develop a _stack_ of images locally, e.g. `debian:buster -> mybase:tag -> mything:tag` inside the 

I appreciate why `--pull` is present, but I'd also really appreciate a means to not have `--pull` present.

**Comment by bwateratmsft** [comment]
Good news! You can customize the `docker build` (and several other commands) at either the user or workspace level. More info on that here: https://code.visualstudio.com/docs/containers/reference#_command-customization

**Comment by shoffmeister** [comment]
Bad news! I do read documentation - I don't want to *define* the complete behaviour of the docker build command myself, I just want it to (optionally) not --pull, in a UX/UI friendly way ;) I do not want to spend effort, in other words.

If I wanted to fully define the behaviour of the command, I could just uninstall the extension and use the command-line. The whole point of such an extension is to make UI life friendlier and easier.

If I am not part of your target group, fair enough.
