### ISSUE TITLE
container launching got stuck at "installing extensions"

### ISSUE THREAD

**Issue by SuYouge** [microsoft/vscode-docker#2446]
Hi! Great extension! And I have a little problem while using it.
When I am using this extension for launching a container, sometime it will stuck at "installing extensions".
It will stuck at this state as follow for a long time and no response.
![Screenshot from 2020-10-28 23-28-24](https://user-images.githubusercontent.com/29477239/97459030-45a1d080-1976-11eb-924b-c341afcff8ec.png)
Sometime it works fine and fast, sometime does not.
I have commented all the extensions in devcontainer.json file but it still happens sometime.
I dont know whether it a network issue or something else. And I want to know how can I make it stable?
Thanks!

This is my devcontainer.json.
```
{
    "name": "gazebo_ros_docker",
    "dockerFile": "Dockerfile",
    "extensions": [
		// "ms-iot.vscode-ros",
		// "ms-vscode.cpptools",
		// "mhutchie.git-graph"
    ],
    "runArgs": [
		"-it",
		"--rm",
		"--privileged",
		"-e ROS_HOSTNAME=localhost",
		"-e ROS_MASTER_URI=http://localhost:11311",
		"--name=ros_container",
	    ],
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash"
    },
	// "postCreateCommand": "bash /catkin_ws/src/panda_simulation/scripts/docker-setup.sh",
	"workspaceMount": "source=${localWorkspaceFolder},target=/catkin_ws,type=bind",
	// "workspaceMount": "source=${localWorkspaceFolder},target=/catkin_ws,type=bind,consistency=delegated",
	"workspaceFolder": "/catkin_ws",
	"mounts": [
		"source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind",
	],
	"containerEnv": {
		"DISPLAY": "${localEnv:DISPLAY}",
	},
	"containerUser": "docker_ros"
}
```

**Comment by SuYouge** [comment]
This issue is not for this repo.

**Comment by bwateratmsft** [comment]
It looks like this is for Remote - Containers, their repo is here: https://github.com/microsoft/vscode-remote-release

**Comment by SuYouge** [comment]
> It looks like this is for Remote - Containers, their repo is here: https://github.com/microsoft/vscode-remote-release

Yes, I misunderstood this repo, thank you!
