### ISSUE TITLE
Fail to install Docker Desktop

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2448]
**OS:** Windows 10
**Build Version:** 20201028.7

**Repro Steps:**
1. Make sure there is no Docker Desktop installed on the machine.
2. Install Docker extension and navigate to Docker view in VS Code.
3. Click "Install" from the below notification. 
![image](https://user-images.githubusercontent.com/45614674/97516519-377f9e80-19ce-11eb-8a69-53814e25ad87.png)
4. Check the result.

**Expect:**
Download Docker Desktop successfully and pop up installation page.

**Actual:**
Fail to install Docker Desktop.
![image](https://user-images.githubusercontent.com/45614674/97516653-90e7cd80-19ce-11eb-90a9-769e4b817476.png)

**Comment by bwateratmsft** [comment]
Can you try running that file directly and see if an error occurs?

**Comment by v-ruizh** [comment]
There is no file "C:\Users\AZURET~1\AppData\Local\Temp\XXX.tmp". The file is not recognized as an internal or external command, operable program or batch file. 
![image](https://user-images.githubusercontent.com/45614674/97654098-2f426480-1a9d-11eb-80d0-be7e96412ba7.png)

**Comment by bwateratmsft** [comment]
Can you download the Docker Desktop installer from [this link](https://aka.ms/download-docker-windows-vscode) and try running it manually?

**Comment by v-ruizh** [comment]
@bwateratmsft Succeed to download the Docker Desktop from [this link](https://aka.ms/download-docker-windows-vscode) and it can be installed manually.

The .tmp file will be auto removed after popping up the error "Docker Desktop installation failed". 
If I tried to run the .tmp file directly by "Command Prompt" before the installation error, the Docker Desktop can be installed successfully.
![image](https://user-images.githubusercontent.com/45614674/97838479-3b3b5a00-1d1b-11eb-9d79-3361dca52b65.png)

**Comment by bwateratmsft** [comment]
Ok, thanks! Does the same error still happen when you try to install using the "Install Docker" command?

**Comment by v-ruizh** [comment]
The same error still happens if try to install it using the "Install Docker" command.

**Comment by bwateratmsft** [comment]
I'm able to reproduce, I'll take a look.

**Comment by bwateratmsft** [comment]
Found the issue, the fix is easy so I'll take it in 1.8.0.

**Comment by bwateratmsft** [comment]
This fix has now been released in 1.8.0.

**Comment by v-ruizh** [comment]
This issue can be reproduced on Docker extension 20210714.2, reopen it.

**Comment by karolz-ms** [comment]
Fixed. The Docker Desktop link that we were using has expired.
