### ISSUE TITLE
A confusing error occurs when executing "Compose Up" action again with the old network removing

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2449]
**OS:** Windows 10
**Build Version:** 20201028.7

**Repro Steps:**
1. Create a .NET Core MVC project and add Docker files which include Docker compose files.
2. Execute "Compose Up" action for docker-compose.yml file, there is a container and a network generated.
3. Navigate to container view and stop the generated container.
4. Remove the generated network from "Networks view".
![image](https://user-images.githubusercontent.com/45614674/97539424-e935c400-19fc-11eb-858b-8aa046e07677.png)
5. Execute "Compose Up" action for docker-compose.yml file again and check the result.

**Actual:**
A new network is created but there is a confusing error "the network XXX(the removed one) not found".
![image](https://user-images.githubusercontent.com/45614674/97539330-bbe91600-19fc-11eb-8dc4-93c5107bd1f2.png)

**More Info:**
No new network is created and no error occurs if skip step 4.

**Comment by bwateratmsft** [comment]
This error comes from the CLI, I think we should preserve it as-is.
