### ISSUE TITLE
[Suggestion] Keep the error messages consistently when starting and restarting the container with the network removing

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2450]
**OS:** Windows 10
**Build Version:** 20201028.7

**Repro Steps:**
1. Create a .NET Core MVC project and add Docker files which include Docker compose files.
2. Execute "Compose Up" action for docker-compose.yml file, there is a container and a network generated.
3. Navigate to container view and stop the generated container.
4. Remove the generated network from "Networks view".
5. Start and restart the above container and check the error messages.

**Actual:**
The error messages are inconsistent.
![image](https://user-images.githubusercontent.com/45614674/97540845-2c913200-19ff-11eb-8aca-7837175e7890.png)

**Suggestion:**
Keep the error messages consistently.

**Comment by bwateratmsft** [comment]
These errors come from the Docker daemon, I think we should preserve them as-is.
