### ISSUE TITLE
Support for self-managed gitlab instance

### ISSUE THREAD

**Issue by ax1036** [microsoft/vscode-docker#2457]
It should be nice to support self managed gitlab, make this hard coded link configurable

https://github.com/microsoft/vscode-docker/blob/aad5061343a7d1b6c7088c7710493071bab56fca/src/tree/registries/gitLab/GitLabAccountTreeItem.ts#L23

**Comment by bwateratmsft** [comment]
Same as #1832. Since we're tracking all the registry asks in #869 I'll resolve this as dupe.
