### ISSUE TITLE
vscode-docker.registries.pullImage

### ISSUE THREAD

**Issue by FLM210** [microsoft/vscode-docker#2458]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "hahtangtang" --password-s...' exited with code 1
Error: 'docker' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Version: 1.7.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.50.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:91411
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@FLM210 Can you share repro steps?
