### ISSUE TITLE
Enable editing of files in a running container

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#2465]
An earlier [feature](#2333) added viewing (read-only) of files in a running container. This issue builds on top of that functionality to enable editing (and saving) of those files back to the container.

**Comment by dbreshears** [comment]
make sure we can track the usage

**Comment by aviadcye** [comment]
Any news on this?

**Comment by philliphoff** [comment]
@aviadcye It's being worked on.  :-) See #2671.

**Comment by aviadcye** [comment]
cool, thanks :)

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
