### ISSUE TITLE
vaExtension causes high cpu load

### ISSUE THREAD

**Issue by samuel-280589** [microsoft/vscode-docker#2471]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.7.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.51.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\samuel\AppData\Local\Temp\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@samuel-280589 does this happen consistently?
