### ISSUE TITLE
In files explorer, folders aren't shown first

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2473]
![image](https://user-images.githubusercontent.com/36966225/98591637-82d36000-229e-11eb-8ae4-aea7869cb4d0.png)

~~Also--I believe we can change the icons further. IMO the file one should be more like a file, and the folders IIRC we can do closed and open folders.~~
UPDATE: The icons we used match what VSCode uses so I'm content.

**Comment by philliphoff** [comment]
Yes, it looks like a recent VS Code update has changed their folder icon to be...not show an icon at all.  We were already switching between the standard "open" and "closed" folder icon based on the node expansion state.

**Comment by philliphoff** [comment]
Regarding sorting, I, personally, like the "everything sorted together" look (and using the icons to differentiate between items) rather than "folders sorted, then files sorted" look but, you're right, the latter is more consistent with VS Code's file explorer.  That should be easily done.

**Comment by bwateratmsft** [comment]
Yeah, I think the ideal would be to follow VSCode's file explorer, which uses the arrows for folders and that file icon for (some) of the files--so, exactly what you have. For sorting they put folders first.
