### ISSUE TITLE
An error occurs in expanded folder node when targeting Docker Desktop to windows container

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2479]
**OS:** Windows 10
**Build Version:** 20201109.2
**.NET Core:** 5.0.100

**Repro Steps:**
1. Switch Docker Desktop to windows container.
2. Create a .NET Core MVC project and add docker files including docker-compose files to it.
3. Right click the docker-compose.yml file and select "Compose Up".
4. Navigate to Docker Containers view -> Expand the MVC container node -> Expand the "Files" node -> Expand the folder node.

**Expect:**
There is no error in the expanded folder node.

**Actual:**
An error occurs in expanded folder node.
![image](https://user-images.githubusercontent.com/45614674/98790712-1348a680-243f-11eb-9f3c-f448610d23ce.png)

**More Info:**
1. This issue does not reproduce in Linux container.
2. Fail to open the "License.txt" file from "Files" node.
![image](https://user-images.githubusercontent.com/45614674/98790546-d977a000-243e-11eb-9ba1-d3958a4979a5.png)

**Comment by bwateratmsft** [comment]
@philliphoff I'm guessing the .NET runtime image doesn't have `wmic` (I'd be kinda surprised if it did). When you were testing, were you using the SDK image or something else?
