### ISSUE TITLE
The file isn't opened in a running container after double click it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2480]
**OS:** Windows 10
**Build Version:** 20201109.2

**Repro Steps:**
Navigate to Docker Containers view -> Expand the running container node -> Expand the "Files" node -> Double click one file.

**Expect:**
The file is opened successfully.

**Actual:**
The file isn't opened after double click it.

**Comment by bwateratmsft** [comment]
Should be an easy addition.

**Comment by philliphoff** [comment]
This was intentional. AFAIK, VS Code doesn't have a notion of command-on-double-click, only command-on-selection, and I didn't want to attempt to open a (potentially large or non-text) file simply because it had been selected for some reason. It just seemed like there needed to be more of a explicit gesture to open a file. While the VS Code workspace explorer *does* work that way, those files are (more) local and seems less potentially expensive to retrieve on a whim.  Given that, I could probably be convinced to follow along.

**Comment by bwateratmsft** [comment]
That makes sense. Would it be possible to check the file size before trying to open it, if we did do a single-click-to-open?

**Comment by philliphoff** [comment]
I think I'd prefer to do "all or nothing", as the user won't likely be able to discern why we would automatically open some files but not others, which could be confusing.  I could maybe see a setting like "auto-open of these extensions and/or files under this size" that defaults to some reasonable set (e.g. `.log`, `.conf`, `.sh`, `.txt`, etc.).  Maybe wait for user feedback on their preference?  (I'll admit to being biased in that I'm not a huge fan of VS Code's auto-open to begin with.)

**Comment by bwateratmsft** [comment]
> Maybe wait for user feedback on their preference?

That sounds reasonable to me. Should we close this issue for now and await that feedback?

**Comment by philliphoff** [comment]
That sounds good to me, but I'll give @BigMorty a chance to chime in first.  Also, @v-ruizh, let us know what you think, as a user, too.

**Comment by BigMorty** [comment]
I am fine with waiting for user feedback on this.

**Comment by v-ruizh** [comment]
@philliphoff As a user, I think it would be better if I can open the file by single click it. 

BTW, We can open the file by single click it in other VS Code extensions, such as Azure Functions/Azure Storage extensions. And the file can be opened when double click it in VS. So I logged this issue.

It's OK if you plan to wait for the user feedback on this. We can open the file by the "Open" action.

**Comment by dbreshears** [comment]
Won't fix this for now as single click for super large files could be really annoying.   Will leave it as right click for now
