### ISSUE TITLE
[Suggestion] It would be better if remove "-" from the error message

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2481]
**OS:** Mac
**Build Version:** 20201109.2

**Repro Steps:**

1. Right click a running container -> Select "Stop/Start". 
2. Right click the running container -> Select "Stop/Start" again during the container is stopping.
3. Check the error message.

**Actual:**
The error message is end of "-", looks like the error message is incomplete.
![image](https://user-images.githubusercontent.com/62053665/98798009-56f3de00-2448-11eb-86e7-e876c6dd9056.png)
![image](https://user-images.githubusercontent.com/62053665/98798336-bc47cf00-2448-11eb-86b7-84dd0a24b049.png)

**Suggestion:**
It would be better if remove "-" from the error message.

**Comment by bwateratmsft** [comment]
This particular error message comes from the Docker daemon so we can't control it unfortunately.
