### ISSUE TITLE
Docker fails to launch on VS code

### ISSUE THREAD

**Issue by ikemerrix** [microsoft/vscode-docker#2485]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: Error
Error Message: Dependency ms-toolsai.jupyter failed to activate

Version: 1.7.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
h._handleActivateRequest extensionHostProcess.js:665:10
h._activateExtensions extensionHostProcess.js:666:71
extensionHostProcess.js:666:374extensionHostProcess.js:666:374
propagateAslWrapper async-listener/index.js:504:23
glue.js:188:31async-listener/glue.js:188:31
index.js:541:70async-listener/index.js:541:70
glue.js:188:31async-listener/glue.js:188:31
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment]
@ikemerrix can you add repro steps?
