### ISSUE TITLE
[Suggestion] Add a "Install" button to install the Azure Account extension directly

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2486]
**OS:** Windows 10
**Build Version:** 20201111.4

**Repro Steps:**
1. Make sure there is no Azure Account extension installed.
2. Right click one image from Docker Hub registry -> Select "Deploy Image to Azure Container Instances..." -> + Create new ACI context... -> Check the notification.

**Actual:**
There is no "Install" button to install the Azure Account extension directly.

**Suggestion:**
Add a "Install" button to install the Azure Account extension directly.
![image](https://user-images.githubusercontent.com/45614674/98903482-a989d480-24f2-11eb-865e-bc81a31fc5fc.png)

**Comment by bwateratmsft** [comment]
Unfortunately it isn't possible to directly install it; there is no command to install an extension's latest version.
