### ISSUE TITLE
There is no "Deploy Image to Azure App Service" action in context menu if Azure Account extension isn't installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2487]
**OS:** Windows 10
**Build Version:** 20201111.4

**Repro Steps:**
1. Make sure there is no Azure Account extension installed.
2. Right click one image from Docker Hub registry and check the context menu.

**Expect:**
There is a "Deploy Image to Azure App Service" action in context menu.
![image](https://user-images.githubusercontent.com/45614674/98904900-709f2f00-24f5-11eb-9fa5-810077d3f39f.png)

**Actual:**
There is no "Deploy Image to Azure App Service" action in context menu.
![image](https://user-images.githubusercontent.com/45614674/98904768-35046500-24f5-11eb-9e00-67a87cf89a07.png)

**Comment by bwateratmsft** [comment]
This is by design. Deploying to App Service requires the Azure Account extension, so it does not show when it isn't installed. However, deploying to ACI does not require the Azure Account extension, so I wanted it to show in that case.

**Comment by v-ruizh** [comment]
@bwateratmsft Creating a new ACI requires the Azure Account extension. Deploying to ACI requires the Azure Account extension if no ACI exists. Deploying to ACI does not require the Azure Account extension if there is an existing ACI.

It would be better to show the "Deploy Image to Azure App Service" action in context menu if there is no Azure Account extension installed. Then remind the user to install the Azure Account extension if they want to "Deploy Image to Azure App Service", like the below screen. 
![image](https://user-images.githubusercontent.com/45614674/99020965-97fc0780-259a-11eb-9737-2d5c060d165a.png)

What do you think about this?

**Comment by bwateratmsft** [comment]
Of course! Now I feel silly. It is still possible to create an ACI context strictly from command line, then the Azure Account extension isn't needed.

@BigMorty what do you think for this? If the Azure account extension is not installed, should we still show the Deploy to ACI button, since ACI contexts can be created from command line without needing the Azure Account extension?

**Comment by BigMorty** [comment]
I think we should be consistent and only show Azure features if the Azure Account extension is installed.
