### ISSUE TITLE
There is no Files node for the running container in ACI

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2488]
**OS:** Windows 10
**Build Version:** 20201111.4

**Repro Steps:**
1. Execute "Deploy Image to Azure Container Instances..." action from Docker Hub registry or ACR.
2. Expand the running container and check it in Docker containers view.

**Expect:**
Display a Files node for the running container that represents the root of that container's file system.
![image](https://user-images.githubusercontent.com/45614674/98913410-4c961a80-2502-11eb-9b7e-df7ba1bbd1d3.png)

**Actual:**
There is no Files node for the running container in ACI.
![image](https://user-images.githubusercontent.com/45614674/98913513-6afc1600-2502-11eb-8802-061a8fcb8ebd.png)

**More Info:**
This issue does not reproduce in default context.

**Comment by bwateratmsft** [comment]
This is by-design, limitations in ACI make it impossible to have a file explorer.
