### ISSUE TITLE
The terminal process failed to launch: Could not find the terminal with id 2 on the extension host.

### ISSUE THREAD

**Issue by marviobezerra** [microsoft/vscode-docker#2498]
Issue Type: <b>Bug</b>

### Environment:
MAC OS Big Sur 11.0.1
.Net 5.0.100
VS Code 1.51.1 & Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
VS Code Docker extension v1.8.0
Docker 2.5.0.1

### Steps to reproduce

1. Create a new API using .Net 5 (v 5.0.100)
`dotnet new webapi -o sample`

2. Open the new project on VS Code and add the recommended `launch.json` and `tasks.json` (it prompts up in a popup window a question add these files, answer yes)

> Note that the build and run are working fine at this point.

3. Add a new Dockerfile by using `Command + Shift + P` (select the default options)

4. Select the launch configuration `Docker .NET Core Launch` and press `F5`.

> Console output shows the error **`The terminal process failed to launch: Could not find the terminal with id 2 on the extension host.`**

### Full console output

```
> Executing task: dotnet build {ommited}/Sample.csproj <

Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Sample -> {ommited}/Sample/bin/Debug/net5.0/Sample.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.03

Terminal will be reused by tasks, press any key to close it.

> Executing task: docker-build: debug <

The terminal process failed to launch: Could not find the terminal with id 2 on the extension host.

Terminal will be reused by tasks, press any key to close it.
```

Extension version: 1.8.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id 7c485502-5ac2-4ba8-8173-af1c2ab7fb3f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
@alexr00 this looks like a terminal system issue, any ideas?

**Comment by philliphoff** [comment]
I wasn't able to repro the issue (but ran into another) when using Docker 2.4.2.0 (edge). After updating to Docker 2.5.1.0 (edge), I do now see the same terminal issue.  Stepping through the code, task execution seems to halt (but no exception thrown) after VS Code calls our `CustomExecution` constructor callback, after it returns a `Pseudoterminal` instance, but before VS Code calls `Pseudoterminal.open()`.  I don't see this issue in another extension that also uses `CustomExecution` (via a slightly different implementation), and stepping through one of those and `vscode-docker`, I don't see any reason why the former should work but not the latter.

**Comment by bwateratmsft** [comment]
That's really strange. The Docker version shouldn't have any bearing on this since we're executing the Docker command via `spawn`--one would think it should be entirely invisible to VSCode.

**Comment by alexr00** [comment]
@meganrogge do you by chance have a mac with Big Sure and Docker 2.5.1.0 ? If so, we should arrange time to debug.

**Comment by meganrogge** [comment]
Hey @alexr00 i do not have a Mac unfortunately. I do have Mac as my personal computer, but can’t install XCode because do not have the space and that’s required to build VSCode as far as I know.

**Comment by bwateratmsft** [comment]
@philliphoff and I both have Macbooks (mine is upgrading to Big Sur as I write this); if you can give us some info on how to do it we can probably debug things.

**Comment by vitmsrk** [comment]
Having same issue after upgrading to Big Sur

**Comment by maxverro** [comment]
Same issue here with macOS Big Sur and Docker 2.5.0.1, is there a workaround atm?

**Comment by philliphoff** [comment]
This may have the same underlying cause as [vscode#105446](https://github.com/microsoft/vscode/issues/105446).  Applying the workaround discussed in the issue (removing the code signature for the renderer app) resolved the issue for me.

> NOTE: I don't claim to know all of the security implications of said workaround, so use at your own risk, your mileage may vary, etc.

**Comment by philliphoff** [comment]
Note that the workaround may need to be applied after any update of VS Code.

**Comment by ralfscheffler** [comment]
Hi, i have the same error with tmswebcore installed. It disappears every time i rename the the folder I'm working on. That means: the folder for example is named /webcore-neu. I working with this the whole day, close everything and the next day, when I opened this folder and try to compile the code this error:
The terminal process failed to launch: Could not find the terminal with id 2 on the extension host.
appears. 
i rename the folder to (say): /webcore-2020 and everything works - till the next day.

**Comment by dbreshears** [comment]
Closing as there should be no work in the Docker extension for this
