### ISSUE TITLE
Update background of marketplace banner to match Docker logo

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#2499]
With the switch to the new "blue whale" icon for the extension, we should update the background color of the banner shown in the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker), as the current blue-on-blue looks muddled.

<img width="1225" alt="Screenshot 2020-11-17 at 09 47 15" src="https://user-images.githubusercontent.com/6402946/99427404-3b5e5c80-28ba-11eb-89f0-259120867a95.png">

**Comment by bwateratmsft** [comment]
Huh, I would not have even guessed it was possible to control this, but now I noticed that `galleryBanner` setting in package.json for the first time.

**Comment by philliphoff** [comment]
Yup!  I'd go with a gray, but we wouldn't want it to clash with the gray and black already used in the header.  Maybe a quick question for our UX expert?

**Comment by bwateratmsft** [comment]
Good idea. I'm inclined toward `#1e1e1e`, which is the default editor background in the default dark theme--and also, what you see when you go to the Extensions tab.
