### ISSUE TITLE
suggestion: add "docker compose restart" command

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#250]
I find as I'm working on a `Dockerfile` I tend to run the commands `docker-compose up` and `docker-compose down` quite a bit in sequence.  I run the container, see that something is wrong, make edits to the `Dockerfile` and then run down and up.  

Maybe a `docker compose: restart` command would be useful.

**Comment by PrashanthCorp** [comment]
Is this a dupe of #73?
