### ISSUE TITLE
How do I configure the run task to remain attached?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode-docker#2504]
I have a run task configured as follows

```
		{
			"type": "docker-run",
			"label": "docker-run: release",
			"dependsOn": [
				"docker-build"
			],
			"platform": "node",
			"dockerRun": {
				"customOptions": "-v ~/workspaces/vscodenodetest6:/usr/src/app -v /usr/src/app/node_modules",
				"command": "./node_modules/.bin/nodemon server.js",
				"remove": true
			}
		},
```

This is essentially the default generated run task, I've just added a couple of volumes and overridden the container command to execute nodemon.

I want to be able to run this task and have the terminal remain attached to the container so that I can monitor the nodemon output. However if I run this task the `docker run` command that is executed is always in detached mode.

I've looked through the documentation [here](https://code.visualstudio.com/docs/containers/reference#_docker-build-task) and I don't see the solution.

Towards the bottom it describes how `docker.commands.run` and `docker.commands.runInteractive` can be customised, but it would seem logical from the fact that there is already an interactive variant of the command that I just need to configure my task to use that instead, but I don't see any way to do this.

There is also mention of a match setting that is compared to either the Dockerfile name or the workspace folder name, but I don't see any obvious way in which that solves my problem.

**Comment by bwateratmsft** [comment]
So the `docker-run` task is meant primarily for debugging, and as you point out always runs detached. The `docker.commands.run` / `docker.commands.runInteractive` are not tasks, but customizable command lines instead. For this purpose your best bet is to make a custom `docker.commands.runInteractive` command. There's a great deal of info on command customization in the doc here: https://code.visualstudio.com/docs/containers/reference#_command-customization

For example, given the above task, you might use this for a command:
```json
    "docker.commands.runInteractive": [
        {
            "label": "My custom interactive command",
            "template": "docker run --rm -it -v ~/workspaces/vscodenodetest6:/usr/src/app -v /usr/src/app/node_modules ${tag} ./node_modules/.bin/nodemon server.js"
        }
    ]
```
Does that work for your scenario?

**Comment by Neutrino-Sunset** [comment]
Possibly that would work. I certainly understand the documenation a lot better now after your explanation. I hadn't really understood that it was the commands available in the Command Palette that the customization docs were referring to and thought it was some aspect of the launch.json and task.json configuration.

If I use a custom command though, how would that build the image when required in the way that the run task depends on the build task?

I have to confess actually that I've worked my way further through the VsCode container documentation and found it much easier to configure this using the docker-compose support. Using that I already have `docker-compose -f docker-compose.debug.yml up` working so that it runs nodemon, and I have a launch profile which can attach a debugger to that running container too. But thanks for the help.

**Comment by bwateratmsft** [comment]
If you still want to use tasks to handle build, you can do a custom run task using just a shell task, rather than the `docker-run` task. This way, the `docker-build` task still happens first:

```json
		{
			"type": "shell",
			"label": "My docker run task",
			"command": "docker run --rm -it -v ~/workspaces/vscodenodetest6:/usr/src/app -v /usr/src/app/node_modules <imageName> ./node_modules/.bin/nodemon server.js",
			"dependsOn": [
				"docker-build"
			],
			"problemMatcher": []
		}
```

You'll need to fill in `<imageName>` with whatever image is created by your `docker-build` task.
