### ISSUE TITLE
ContainerId is shown in description instead of imageId

### ISSUE THREAD

**Issue by wendellmva** [microsoft/vscode-docker#2507]
In the container.description settings when the imageid is checked, the containerid is shown in the container node description instead of the imageid.

**Comment by bwateratmsft** [comment]
I can repro. I think the issue is [here](https://github.com/microsoft/vscode-docker/blob/master/src/tree/images/ImageProperties.ts#L64), for containers the `Id` field is the container ID but for images that field is the image ID.

**Comment by bwateratmsft** [comment]
This is now fixed in Docker extension version 1.9.0.
