### ISSUE TITLE
Feature Request: Add Debugging Support for PowerShell

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/vscode-docker#2508]
Right now, the Docker extension appears to support debugging of C# / .NET Core, Python, and Node.js applications. This is according to the Visual Studio Code documentation, linked below.

I would like the ability to perform interactive debugging of a PowerShell application, inside a Docker container, as well.

https://code.visualstudio.com/docs/containers/debug-common
https://code.visualstudio.com/docs/containers/debug-netcore

**Comment by bwateratmsft** [comment]
It looks like the [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) supports debugging so this is probably possible.

**Comment by bwateratmsft** [comment]
Duping to #3346 (umbrella issue)
