### ISSUE TITLE
unable to pull docker image

### ISSUE THREAD

**Issue by rishikaushal2009** [microsoft/vscode-docker#2515]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "rishikaushal" --password-...' exited with code 1
Error: Error saving credentials: rename C:\Users\qwin\.docker\config.json385557979 C:\Users\qwin\.docker\config.json: The process cannot access the file because it is being used by another process.

Version: 1.8.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:98044
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@rishikaushal2009 are you able to log in or pull images from the command line directly?

**Comment by rishikaushal2009** [comment]
@bwateratmsft  i did a workaround by creating image locally using docker desktop instead of pulling from dockerhub as in docker hub it was in pvt registry that required secret to pull

**Comment by bwateratmsft** [comment]
Ok, glad you were able to work around it. Thanks!
