### ISSUE TITLE
how do i connect vscode docker explorer to windows (host) docker toolbox boot2docker (guest)?

### ISSUE THREAD

**Issue by laurencefass** [Microsoft/vscode-docker#252]
I want to connect vscode to manage an arbitrary docker registry with exposed API. I'm running vscode on a windows 10 host with docker windows toolbox. the docker registry is running in a boot2docker virtual machine.

c:\host>docker-machine env default

```
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\laurence\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env default') DO @%i
```

I've exposed docker API using this method and I have updated the host DOCKER_HOST env var accordingly.

https://stackoverflow.com/questions/27949254/docker-remote-api-not-accessible/49939177#49939177.

> edit /var/lib/boot2docker/profile.

```
DOCKER_TLS=no
DOCKER_HOST=0.0.0.0:2375 
```

then these return valid data...
```

curl http://localhost:2375/containers/json
curl http://localhost:2375/images/json
```

vscode docker explorer sidebar observations:

-     main docker accordion is empty.
-     docker Images accordion is empty.
-     running Compose Down/Compose up on a compose file is not working (no errors, no actions)
-     running Build Image on a docker file is not working (no errors, no actions). 

thanks

**Comment by laurencefass** [comment]
perhaps a more general support question: how does docker extension connect to docker hub with vscode running on windows? surely this is not the solution... https://www.axians-infoma.de/navblog/use-vs-code-docker-extension-remote-docker-host/

**Comment by chrisdias** [comment]
The Docker extension simply uses the public DockerHub.com APIs.  There is no way to point it to another registry.

**Comment by laurencefass** [comment]
thanks.

for clarity can you also comment on these (undocumented?) features:

can VSCode _only_ manage images on DockerHub?
can I use VSCode to point to mulitple registries (as implied in the UI)?
how do i manage my local repository with VSCode?

**Comment by chrisdias** [comment]
Actually, it looks like you are just trying to connect to another docker machine, not a registry.

Can you open the dev tools and see if there are any errors in the console? Press `F1` and search for `Developer: Toggle Developer Tools`, and then look in the console.

**Comment by laurencefass** [comment]
...ip address needed a :port for some reason. anyway. works! im just getting started with tools. thanks for your time.

**Comment by squillace** [comment]
@chrisdias Here's my problem. I have minikube -- this issue mentions another local cluster variation. I want to be able to `eval $(minikube docker-env)` and then refresh and have the _local_ env vars for the engine be picked up so that the images I list are the ones from the minikube engine and not the local engine. 

This is a standard way of pointing at different docker engines in the shell. Note, this is not specific to any specific local cluster tool, but the way that the extension doesn't pick up the local env vars for docker. 

Hope that makes sense.

**Comment by akaroml** [comment]
I'm also doing so when working with minikube. minikube does not use the local docker registry by default. So you see a view presented by Docker but inside Kubernetes extension, another one is used. This is very confusing.
It would be nice if one of the extensions can provide a way of switching local registry instances and some hint to the user of what registry is actually being used.

**Comment by squillace** [comment]
Hi @akaroml; I filed https://github.com/Azure/vscode-kubernetes-tools/issues/192 against the Kube extension to support this for F5 in the Draft debugger adapter, but the _both_ that extension and this one should do the right and normal thing for docker envs.

**Comment by StephenWeatherford** [comment]
Does the new private registry functionality unblock you for this?  Thx.
