### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Tapankumarpanda-kcc** [microsoft/vscode-docker#2522]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\u1\AppData\Local\Temp\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@Tapankumarpanda-kcc does this happen consistently?
