### ISSUE TITLE
Debug docker

### ISSUE THREAD

**Issue by JheyssonD** [microsoft/vscode-docker#2523]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND vsdebugger.blob.core.windows.net

Version: 1.8.1
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RequestError extension.bundle.js:786:154906
Request.callback extension.bundle.js:786:153547
Request.RP$callback [as _callback] extension.bundle.js:786:152993
o._callback.o.callback.o.callback extension.bundle.js:846:4497
Request.emit events.js:223:5
Request.onRequestError extension.bundle.js:846:13795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by bwateratmsft** [comment]
@JheyssonD it looks like the DNS lookup for `vsdebugger.blob.core.windows.net`. Do you have a custom DNS provider or something like that?
