### ISSUE TITLE
docker-compose seems to ignore context

### ISSUE THREAD

**Issue by ZeeMoros** [microsoft/vscode-docker#2525]
I have two docker.sock contexts, the default one and one from a docker dind.

![image](https://user-images.githubusercontent.com/42606668/100332586-dbf6ff80-2fd1-11eb-8244-345f8f8c930c.png "contexts")

My docker dind is empty as seen bellow.

![image](https://user-images.githubusercontent.com/42606668/100332654-f03afc80-2fd1-11eb-9109-ec767c9e15f0.png "zee context")

I want to add a container to it by running a docker-compose up but I get the following result : 

```bash
/zee-data # docker-compose up -d nginx
Creating nginx ... error

ERROR: for nginx  Cannot create container for service nginx: Conflict. The container name "/nginx" is already in use by container "54c9f6b5059b94c6dfe623f184a4a42dd095795858cfa072e1d51f8fd0caff88". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for nginx  Cannot create container for service nginx: Conflict. The container name "/nginx" is already in use by container "54c9f6b5059b94c6dfe623f184a4a42dd095795858cfa072e1d51f8fd0caff88". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

I have found out that if I precise the host to compose it works : 

```bash
/zee-data # docker-compose -H unix:///var/run/zee/docker.sock up -d nginx
Creating nginx ... done
```

I should also precise that docker-compose sees that no containers exists in the context :

```bash
/zee-data # docker-compose ps -a
Name   Command   State   Ports
------------------------------
```

Am I missing something to use docker-compose up in another context ?

**Comment by bwateratmsft** [comment]
I'd expect this to work but it also doesn't look like this is an issue related to the Docker extension. Can you share the output of `docker context ls`?

**Comment by ZeeMoros** [comment]
Here you go :
![image](https://user-images.githubusercontent.com/42606668/100630208-89e41000-332a-11eb-95a5-1ba9a3c1ca94.png)

I must admit that I haven't used docker context much up till now... So I'm not able to help much in identifying the source of the problem.

**Comment by ZeeMoros** [comment]
I also found out that setting the DOCKER_HOST environment variable just before docker-compose works : 
```bash
# DOCKER_HOST=unix:///var/run/zeemoros/docker.sock /zee-data # docker-compose up -d nginx
Creating nginx ... done
```

But the following doesn't work and I personnaly find that odd :
```bash
# DOCKER_HOST=unix:///var/run/zeemoros/docker.sock; /zee-data # docker-compose up -d nginx
[ ... ]
# echo $DOCKER_HOST
unix:///var/run/zeemoros/docker.sock
```

It seems that the DOCKER_HOST is straight ignored by docker compose in the latter.

**Comment by PavelSosin-320** [comment]
1. Docker insists that it works [Docker-compose use of Docker context](https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/).  Check your docker-compose version, please.
2. It is odd to mix Docker context and DOCKER_HOST because DOCKER_HOST is declared obsolete.
3. This is purely Docker issue.

**Comment by ZeeMoros** [comment]
These are the version I have :
```bash
/zeemoros-data # docker-compose -v
docker-compose version 1.25.4, build unknown
/zeemoros-data # docker -v
Docker version 19.03.12, build 48a66213fe1747e8873f849862ff3fb981899fc6
```

Do you expect an incompatibility ?

**Comment by PavelSosin-320** [comment]
Yes, I see: you need [Docker compose 1.26 pre-release. ](https://github.com/docker/compose/releases/tag/1.26.0-rc2). You have only 1 version to go.

**Comment by ZeeMoros** [comment]
Alright then I'll be patient and wait thanks a bunch ^^

For anyone that would like an alternative I personally use linux symlinks to do it right now, i just override the /var/run/docker.sock with the sock of the context I want to use.
