### ISSUE TITLE
Action: vscode-docker.registries.azure.runFileAsTask

### ISSUE THREAD

**Issue by kaycoinsUSA** [microsoft/vscode-docker#2526]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.runFileAsTask
Error type: Error
Error Message: To run a task from a .yaml file you must have yaml file in your VS Code workspace.

Version: 1.8.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.quickPickYamlFileItem extension.bundle.js:46:509845
processTicksAndRejections task_queues.js:94:5
Object.scheduleRunRequest extension.bundle.js:659:261109
runFileAsAzureTask extension.bundle.js:1040:128459
```

</details>

**Comment by bwateratmsft** [comment]
@kaycoinsUSA do you have a YAML file in your workspace?

**Comment by kaycoinsUSA** [comment]
> Does this occur consistently?
> Repro steps:
> 
> 
> Action: vscode-docker.registries.azure.runFileAsTask
> Error type: Error
> Error Message: To run a task from a .yaml file you must have yaml file in your VS Code workspace.
> 
> Version: 1.8.1
> OS: win32
> OS Release: 10.0.19041
> Product: Visual Studio Code
> Product Version: 1.51.1
> Language: en
> 
> Call Stack
> ```
> Object.quickPickYamlFileItem extension.bundle.js:46:509845
> processTicksAndRejections task_queues.js:94:5
> Object.scheduleRunRequest extension.bundle.js:659:261109
> runFileAsAzureTask extension.bundle.js:1040:128459
> ```
I addressed this issue thank you.
