### ISSUE TITLE
Cannot connect to Github Container Registry ghcr.io

### ISSUE THREAD

**Issue by windsource** [microsoft/vscode-docker#2528]
I want to use the docker extension to browse the images stored in the [Github Container Registry (GHCR)](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages) but I cannot get it working:

![image](https://user-images.githubusercontent.com/13716595/100588826-9a789400-32f2-11eb-8d2b-624630b18dcc.png)

* Type: Generic Docker Registry
* URL: https://ghcr.io
* Username: windsource
* Password: `<Github token>`

**Comment by bwateratmsft** [comment]
This is covered on #869
