### ISSUE TITLE
push docker image error

### ISSUE THREAD

**Issue by waynesun01** [microsoft/vscode-docker#2530]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Command failed: docker login https://harbor.s9537.cn:4433 --username admin --password-stdin
Error response from daemon: Get https://harbor.s9537.cn:4433/v2/: x509: certificate signed by unknown authority

Version: 1.6.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@waynesun01 can you add repro steps?
