### ISSUE TITLE
Stopped containers are still shown as running

### ISSUE THREAD

**Issue by justalemon** [Microsoft/vscode-docker#254]
After few failures of stopping containers that are shown as running:

![imagen](https://user-images.githubusercontent.com/11861253/39091242-9d4b3d52-45c6-11e8-8d1c-b856631a22e7.png)

I always get:

![imagen](https://user-images.githubusercontent.com/11861253/39091250-b0066dcc-45c6-11e8-94bf-bcc2f4b279a5.png)

Even if I refresh the Docker panel, they are still showing as running.

**vscode-docker version**: 3.094.832
**VS Code version**: 1.22.2
**Docker Version**: 18.04.0-ce

**Comment by chrisdias** [comment]
It usually takes some time (10s of seconds) for a container to stop.  You should see something in the status bar while this is happening.

![image](https://user-images.githubusercontent.com/1487073/39097138-2a35f39c-460d-11e8-90ff-1e78f8beab77.png)

Is this with any container?  What OS are you on?  Is the image somewhere public that I can try it (e.g. in dockerhub)?

**Comment by justalemon** [comment]
This problem happens when an "intermediary container" is not removed. Because of this, they still show as existing and running.

I tried to build [this](https://github.com/justalemon/DockerImages/blob/master/plex/Dockerfile) Dockerfile and stopped the build with CTRL+C. This makes "intermediary containers" show as running in the Left panel.

```
Microsoft Windows [Versión 10.0.16299.371]
(c) 2017 Microsoft Corporation. Todos los derechos reservados.

D:\Proyectos\DockerImages>docker build --rm -f plex\Dockerfile -t justalemon/plex:latest plex
Sending build context to Docker daemon   5.12kB
Step 1/5 : FROM microsoft/windowsservercore:1709
 ---> f4d21eb79928
Step 2/5 : SHELL ["powershell", "-Command"]
 ---> Using cache
 ---> 64c82f340e79
Step 3/5 : RUN Get-ChildItem 'C:\\Windows\\servicing\\Packages\\*Media*.mum' | ForEach-Object { (Get-Content $_) -replace 'required','no' | Set-Content $_};     Install-WindowsFeature Server-Media-Foundation;
 ---> Using cache
 ---> 094052cc7a1f
Step 4/5 : RUN $version = '1.12.3.4973-215c28d86';     $url = ('https://downloads.plex.tv/plex-media-server/{0}/Plex-Media-Server-{1}.exe' -f
$version, $version);     (New-Object System.Net.WebClient).DownloadFile($url, 'plex.exe');     Start-Process plex.exe /quiet -Wait;     Remove-Item plex.exe;     Start-Process 'C:\\Program Files (x86)\\Plex\\Plex Media Server\\Plex Media Server.exe';
 ---> Running in 5ddb68674799
# CTRL+C here, exit with no output
```

![imagen](https://user-images.githubusercontent.com/11861253/39106413-e7da7f1a-4691-11e8-97b0-af53d694158c.png)

**Comment by StephenWeatherford** [comment]
@justalemon Does docker CLI also show them as running?  Thanks.

**Comment by justalemon** [comment]
The Docker CLI shows them as stopped or even removed

**Comment by StephenWeatherford** [comment]
What's the STATUS of these containers?  Is it "Created"? From either the explorer:

![image](https://user-images.githubusercontent.com/6913354/42719938-46f300c2-86d3-11e8-87e0-0521692e6828.png)

or docker ps --all

![image](https://user-images.githubusercontent.com/6913354/42719941-53b37e36-86d3-11e8-938b-0d7dc92c7bb6.png)

**Comment by justalemon** [comment]
Looks like it was a Docker problem, upgrading from 18.04.0-ce to 18.06.0-ce fixed it.
