### ISSUE TITLE
Can't connect to docker using https

### ISSUE THREAD

**Issue by screamsyk** [microsoft/vscode-docker#2540]
when i set `"docker.host"="https://192.168.1.12:2375"`，the connect will fail and tip that `Failed to connect:Client send an HTTP request to an HTTPS server`

**Comment by bwateratmsft** [comment]
This issue is due to `docker-modem`'s implementation for determining protocol: https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L44-L54

You can either set the environment variable `DOCKER_TLS_VERIFY` to `1`, or use port 2376 instead of 2375. Are either of those options?

**Comment by screamsyk** [comment]
@bwateratmsft Thank you very much for your answer, and that fixed my problem by setting the environment variable `DOCKER_TLS_VERIFY` to 1
