### ISSUE TITLE
Improve Invalid URL error

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2541]
When a user gets an Invalid URL error, I believe we could help them fix this issue faster. 

In terms of the error message itself we are given, I think it could be clearer to tell the user the source of the error. 
Either:
1. They have an invalid setting for docker.host attribute in their settings.json
2. They do not have a docker.host attribute (which would override) and instead have an invalid variable for DOCKER_HOST env var

It would help if we changed the popup notification when an invalid URL error occurs from "Report Issue" to "Open Settings".
Then we could open the VS Code Docker settings directly to the docker.host attribute that needs to be modifed. 

In the VS Code Docker Settings, we should provide some examples of the protocols that must be prepended to a url to properly communicate with the docker daemon or your private server. The message could say something like "Depending on the protocol your server is using, you should use a url such as "ssh://192.168.1.1" or "tcp://192.168.1.1". 

This would provide clearer messaging.

**Comment by bwateratmsft** [comment]
Adding some self-notes here--

We can use use command `workbench.action.openGlobalSettings` with argument:
```js
{
    revealSetting: {
        key: 'docker.host',
        edit: true // I think
    }
}
```
