### ISSUE TITLE
Use document well-type of window to view container logs

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2546]

**Comment by bwateratmsft** [comment]
The problem with this approach is that it would not allow following the log of a running container.

**Comment by PavelSosin-320** [comment]
Docker container log is not a document. It is a stream of records with timestamps.
Docker log has no file type or content type like regular Windows files.
The format and destination of the stream are defined by logdriver and its parameters.
Log can be filtered by timestamps.
When docker client accesses container log on the remote engine via TLS encoded connection log is encoded as any data.
Even there is no universal default: default is provider dependant: either syslog or text-json.
The best rendering of the docker log at the client-side is a stream of messages.

**Comment by bwateratmsft** [comment]
Talked to Mike, since putting it into the document well would sacrifice the ability to follow, we'll keep things as-is.
