### ISSUE TITLE
can't open log file

### ISSUE THREAD

**Issue by AbdallahSalameh83** [microsoft/vscode-docker#2549]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.containers.openFile
Error type: Error
Error Message: cannot open docker://869dbae493ad6a5a4a19df5dff787154bef2a5871cdfeea44e262dd2a072987e/var/log/lastlog?fileType%3Dfile%26containerOS%3Dlinux%26path%3D%252Fvar%252Flog%252Flastlog. Detail: File seems to be binary and cannot be opened as text

Version: 1.8.1
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6687:388
```

</details>

**Comment by karolz-ms** [comment]
@AbdallahSalameh83 is the log a binary file?

@philliphoff is there a particular reason why we use `vscode.workspace.openTextDocument(0` API in `openContainerFile` action, assuming a text document, as opposed to just `vscode.open()`, that presumably can also handle binary files?

**Comment by philliphoff** [comment]
@karolz-ms Mostly just following similar logic to VS, where the download option was targeting non-text files.  I wasn't sure to what degree VS Code handled random binary files.  It's worth doing some investigation to see whether we can/should relax that logic (even if/when we add support for downloading arbitrary files).

**Comment by PavelSosin-320** [comment]
@AbdallahSalameh83 which log do you want to see: daemon log or container log?
Docker Container log content and format depends on Log driver and can have json, text, binary formats in the case when it is piped to the system event logger or a systemd journal or Logregator. Only **Docker logs command** can be used to view Container logs. 
This is a separate big topic in the Docker documentation [Docker logging](https://docs.docker.com/config/containers/logging/configure/). This is an obvious security requirement to keep Docker's logs in a not human-readable format.
Please, provide your logging configuration.

**Comment by karolz-ms** [comment]
@AbdallahSalameh83 with https://github.com/microsoft/vscode-docker/pull/2551 you will be able to "download" binary files from a container and open them locally. We also have https://github.com/microsoft/vscode-docker/issues/2550 to investigate the ability to open binary files directly.

Given that I am going to close this issue. Thank you for helping us make Docker extension better.
