### ISSUE TITLE
Allow opening non-text container files

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#2550]
Currently the extension assumes running container files being opened in the editor are text files (specifically calling VS Code's `workspace.openTextDocument()`.  We should investigate whether VS Code does a reasonable job of determining the type of file being opened in order to support more non-text files.

This may help resolve issues such as #2549.

**Comment by dbreshears** [comment]
@philliphoff , if we have download this can be a lower priority and pushing to future

**Comment by bwateratmsft** [comment]
Closing as not planned
