### ISSUE TITLE
Docker extension interferes with npm scripts detection

### ISSUE THREAD

**Issue by Peluko** [microsoft/vscode-docker#2552]
With the following configuration:

- Windows 10 Pro19042.630
- VSCode 1.51.1
- Docker extension 1.8.1
- Docker Desktop 2.4.0.0 (48506)
- Docker is running on a remote linux machine, I use it on windows with a SSH docker context
- The SSH connection is configured to use a private key loaded into ```ssh-agent```.

This setup usually works fine.

But when I'm not using docker, the private key isn't loaded into ```ssh-agent```, so Docker can't connect to the remote context. Everything else works fine, except for one thing. When I open a local project on VSCode, the npm scripts auto detection doesn't work. It keeps detecting scripts forever. The blue progress indicator on the keeps running and never stops:

![image](https://user-images.githubusercontent.com/412867/101619411-87ad4000-3a13-11eb-91b1-547f00e61b83.png)

If I load the same project with the private key loaded into ```ssh-agent```, so docker can connect to the context, the npm scripts detection works perfectly for the local project. Also it works fine if I disable the Docker extension.

**Comment by bwateratmsft** [comment]
@Peluko is the SSH agent not running, or just doesn't have they key added? I haven't been able to reproduce the issue, at least not in VSCode 1.52.0.

Can you run the command "Developer: Show Running Extensions", look for "NPM support for VS Code", and see if it is showing any errors?
![image](https://user-images.githubusercontent.com/36966225/102242107-b326a380-3ec7-11eb-8ca0-b0b528fa4042.png)

**Comment by bwateratmsft** [comment]
@Peluko is this still occurring?

**Comment by Peluko** [comment]
Sorry, I've been somewhat disconnected last weeks. Now it doesn't occur, it's working ok. Something on the last updates corrected it.
Closing. Regards.

**Comment by bwateratmsft** [comment]
Glad to hear it's working now!
