### ISSUE TITLE
[Suggestion] Add a "Successfully downloaded files" notification after finishing downloading container files

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2557]
**OS:** Windows 10
**Build Version:** 20201210.1

**Repro Steps:**
1. Download container files from Container Files node.
2. Check whether there is a "Successfully downloaded files" state in the notification or not.

**Actual:**
There is no notification after downloading completed, only a "downloading files" notification during downloading.

**Suggestion:**
Add a "Successfully downloaded files" notification after finishing downloading container files.

**Comment by philliphoff** [comment]
@v-ruizh @BigMorty The removal of the progress notification is intended to be the indicator of completion (or cancelling of a) file download.  If there were an error, the user should get an additional error notification.  I'm hesitant to add a notification for success given users' general disdain for notifications in VS Code.  (I think this suggestion is similar to issue #1509, where we decided to *not* show a completion notification.)

**Comment by karolz-ms** [comment]
The team discussed this--the conclusion is to wait for user feedback and also prioritize the suggestion based on how popular the "Download Files" command is.

**Comment by bwateratmsft** [comment]
We will stick with the progress toast for now.
