### ISSUE TITLE
need an icon for viewlet

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#256]
related to: https://github.com/Microsoft/vscode/issues/48637

can you help me get a docker icon that will work in the activity bar (per the above issue)?

The official icons and guidelines for docker are here: https://www.docker.com/brand-guidelines

**Comment by misolori** [comment]
[Here is the properly sized icon](https://github.com/Microsoft/vscode-docker/files/1957175/docker-logo.zip). I also tested this via the custom view contribution to ensure it will work:

![image](https://user-images.githubusercontent.com/35271042/39390899-63597238-4a50-11e8-9730-e3dd5639b24d.png)

**Comment by chrisdias** [comment]
@TheDutchCoder this looks like a different issue where in your case you are not seeing an icon.  Can you open a new issue for that, and check the dev tools console for errors?  To do this, go to the help menu, choose `Toggle Developer Tools` and then click on the `Console` tab.  Thx.

**Comment by TheDutchCoder** [comment]
Ah, a simple restart seemed to have fixed it (there were no errors in the console). Not sure why the restart helped, I haven't updated the plugin in a while. Thanks though!
