### ISSUE TITLE
Cannot attach VS Code to remote container

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-docker#2562]
Issue Type: <b>Bug</b>

Expected result: Able to `Attach Visual Studio Code` to container on remote host via SSH.

Actual result: Can only `Attach Visual Studio Code` to containers running on my LOCAL machine, even while connected to the remote host via SSH and able to `Attach Shell` to remote containers.

Steps to reproduce:

- `CMD-SHIFT-P` > `Remove-SSH: Connect to host...`
- `ubuntu@mydomain.com` (an Ubuntu LTS EC2 with Docker Engine installed)
- `CMD-SHIFT-X` > search for and install `Docker` extension on the remote host
- Navigate to Docker sidebar
- Right click container and `Attach Shell` -- successful
- Right click container and `Attach Visual Studio Code` -- brings up a list of containers on my LOCAL machine

Extension version: 1.8.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0
Remote OS version: Linux x64 4.4.0-1110-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 30710210-57bb-4fa9-8da6-c4ab3930cb9c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mydomain.com|
|OS|Linux x64 4.4.0-1110-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz (16 x 2999)|
|Memory (System)|30.64GB (4.10GB free)|
|VM|0%|
</details>

**Comment by karolz-ms** [comment]
@mrmachine thank you for reporting this issue. 

The `Attach Visual Studio Code` command is actually provided by the Remote-SSH extension and there are some known problems with it and remote containers. The latest I could find on the topic [is this](https://github.com/microsoft/vscode-remote-release/issues/4072)

**Comment by PavelSosin-320** [comment]
Docker server is built to access its REST API service point via TLS directly from the remote client or via Proxy. The local access requires a user that belongs to the Docker group to allow docker.sock access, unlike remote access that requires only TLS. How SSH session can work as Proxy port 22 --> docker.sock?
