### ISSUE TITLE
Command Docker: Add Docker Compose Files to Workspace does not prompt for Dockerfile

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2566]
When using the Python Tutorial Sample, I ran the **Docker: Add Docker Compose Files to Workspace** command. This successfully added the `docker-compose.yml` file and the `docker-compose.debug.yml` file. However, I ran this command without actually making a valid Dockerfile anywhere in my workspace. My **Compose Up** command then failed due to no Dockerfile found

In this case, should be prompt the user in some way? Such as "You do not have a valid dockerfile in your root directory, would you like to create one?" and this would then run **Docker: Add Dockerfiles to Workspace** under the covers. The user may have a Dockerfile in a different folder, but I'm wondering if a root directory Dockerfile is a common case.

**Comment by PavelSosin-320** [comment]
May contradict the logic of the new experimental **docker CLI 19.03 feature** docker app. User will be denied from the usage of the "official" Docker application initialization method. The warning is mandatory.

**Comment by bwateratmsft** [comment]
I think we should just throw an error if the Dockerfile isn't in a place where the resulting scaffolded compose files will work. We can use the new special error handling that @ejizba added for this to show a button to add Docker files, and we can automatically assume compose.
