### ISSUE TITLE
The state of the outdated base image "alpine:latest" is not "Out of date" 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2568]
**OS:** All
**Build Version:** 20201210.10

**Repro steps:**
1. Make sure enable setting "Docker > Images: Check for outdated images".
2. Open Docker view, if the image "alpine:latest" is present, remove it: docker rmi alpine:latest.
3. Pull any image, and tag it as "alpine:latest": docker pull hello-world:latest && docker tag hello-world:latest alpine:latest.
4. Remove the "hello-world:latest" image: docker rmi hello-world:latest.
5. Restart VS Code, then check the state of the outdated base image "alpine:latest" after 1 min.

**Expect:**
The state of the outdated base image "alpine:latest" is "Out of date".
![image](https://user-images.githubusercontent.com/45614674/102078035-37841280-3e45-11eb-9474-e9f49d8f5bbd.png)

**Actual:**
The state of the outdated base image "alpine:latest" is not "Out of date".
![image](https://user-images.githubusercontent.com/45614674/102077927-0572b080-3e45-11eb-8b19-16b86a44ce68.png)

**More Info:**
Refresh can't fix this issue.

**Comment by bwateratmsft** [comment]
Probably also related to the caching logic; we only check once-per-day by default. I need to update the test case to include info about how to clear the cache.

**Comment by bwateratmsft** [comment]
I'll dupe this to #2496; ultimately both are about the caching logic. I need to take some time to update the test case.
