### ISSUE TITLE
[CodeSpace] The notification "Do you want to copy the debugger to the container" pops up after executing "Compose Up" for docker-compose.debug.yml file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2570]
**OS:** Win 10
**Build Version:** 20201214.5
**.NET Core:** 5.0.100

**Repro Steps:**

1. Create a .NET Core mvc app by "dotnet new mvc".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the **docker-compose.debug.yml** --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4.
7. Check whether pop up a notification "Do you want to copy the debugger to the container".

**Expect:**
There shouldn't be any prompt to copy debugger.

**Actual:**
The notification "Do you want to copy the debugger to the container" still pops up.
![image](https://user-images.githubusercontent.com/62053665/102215619-ed6a6200-3f14-11eb-9e48-8b55d622b860.png)

**More Info:**
This issue only reproduces for GitHub Codespaces.

**Comment by bwateratmsft** [comment]
This is expected due to the volume mapping limitations of Codespaces. Even though we download the debugger, volume mapping it is not possible in Codespaces at this time. As a result, when trying to attach we detect that the debugger is not present in the expected location, and offer to copy it.
