### ISSUE TITLE
Cannot Pull image from DockerHub via Vscode

### ISSUE THREAD

**Issue by freshDevops1** [microsoft/vscode-docker#2573]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "example_Username" --password-st...' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by karolz-ms** [comment]
@freshDevops1 do you have Docker Desktop for Windows installed?

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
