### ISSUE TITLE
Mac OS Big Sur zsh:1: command not found: docker

### ISSUE THREAD

**Issue by gagocaan** [microsoft/vscode-docker#2574]
When try to run a image from task bar the console output says

``` bash
zsh:1: command not found: docker
```

i can run the images from terminal without problems

**Comment by karolz-ms** [comment]
I am sorry: https://github.com/microsoft/vscode-docker/issues/2509#issuecomment-740781160

Duplicate of https://github.com/microsoft/vscode-docker/issues/2254
