### ISSUE TITLE
There is no docker assets in Docker view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2575]
**OS:** Windows 10
**Build Version:** 20201217.1

**Repro Steps:**
1. Install the latest docker extension build from main branch.
2. Check the Docker view.

**Expect:**
The Docker view shows well.
![image](https://user-images.githubusercontent.com/45614674/102864695-8c401280-446f-11eb-82ea-a9e7c8a6fbfa.png)

**Actual:**
There is no docker assets in Docker view.
![image](https://user-images.githubusercontent.com/45614674/102863784-0a9bb500-446e-11eb-9b07-30bd250e0a81.png)

**More Info:**
1. There is no image in Docker view after pulling one image using command.
2. An error occurs when adding Docker Files to workspace.
![image](https://user-images.githubusercontent.com/45614674/102864526-3c614b80-446f-11eb-9eec-fbaeb7c2821c.png)

**Comment by karolz-ms** [comment]
I can reproduce. Investigating...
