### ISSUE TITLE
https://github.com/docker/for-win/issues/1825#issuecomment-450501157

### ISSUE THREAD

**Issue by rishikaushal2009** [microsoft/vscode-docker#2576]
Issue Type: <b>Bug</b>

https://github.com/docker/for-win/issues/1825#issuecomment-450501157

Extension version: 1.9.0
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.67GB free)|
|Process Argv|--crash-reporter-id 82082a77-3e05-4cb8-9734-d3da98de8aba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt875:30239451

```

</details>

**Comment by karolz-ms** [comment]
@rishikaushal2009 not sure what problem you are referring to--the comment you referenced is very old and probably irrelevant to current versions of Docker Desktop for Windows or the VS Code Docker extension.

If you are still experiencing difficulties, please open a new issue and tell us exactly (step by step) what you have done with the extension, what you expected to happen, and what happened instead. Thanks!
