### ISSUE TITLE
Need workaround(s) for docker exe missing from path issue (MacOS)

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2578]
Many customers are suffering from the bug in MacOS that makes the docker executable folder disappear from path, for example: https://github.com/microsoft/vscode-docker/issues/2254 https://github.com/microsoft/vscode-docker/issues/2574 https://github.com/microsoft/vscode-docker/issues/2577

Docker seems to have hard time finding the root cause https://github.com/docker/compose-cli/issues/754

Consider
- following @ke6jjj suggestion and add a setting that contains full path to docker executable (the extension user would set it as a workaround)
- when "docker not found" error happens, probe the default Docker Desktop for Mac installation path and use the executable there if it exists
- (other ideas welcome)

**Comment by karolz-ms** [comment]
Another idea: use terminal to figure out where the docker executable is (VS Code terminal seems to be unaffected by the incomplete path issue most of the time)

**Comment by bwateratmsft** [comment]
Another possibility: look in `PATH` for `/usr/bin/local` (which I'd expect to ALWAYS be there). If it's not there, append it.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
