### ISSUE TITLE
There are no running containers to attach to.

### ISSUE THREAD

**Issue by jakeum** [microsoft/vscode-docker#2579]
ubuntu 18.04
computer A (vscode)
server B(docker)

Let say I used vscode ssh connectioin to serverB(docker) 
`computerA ---------> ssh------------> serverB(docker) 
`then I try to connect with vscode's(try to connect attach a Running Container) 

`computerA ---------> ssh------------> serverB(docker)-----> connect attach a running container
`
but I got the error 
`There are no running containers to attach to.
`

**Comment by PavelSosin-320** [comment]
Docker is server by itself, for good and bad. It is always possible to attach to the container using Docker remote API in a very secure manner. In the proposed Babylon tower 3 flows are redundant: ssh client on the client-side, ssh server on the server-side, docker CLI at the server-side. Unlike direct API connection that allows monitoring Docker engine status using _PING and Docker container using health-check it will be very hard to synchronize lifecycle of the remote SSH server, remote Docker engine, and remote docker container with the VSCode running on the client-sideThe frequency of "Can't connect" and "Can't find" will be very high.

**Comment by karolz-ms** [comment]
@jakeum are you trying `Attach Shell...` command, or `Attach Visual Studio Code...` command?

If this is the latter, please refer to [this issue](https://github.com/microsoft/vscode-docker/issues/2562)

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
