### ISSUE TITLE
namespace?

### ISSUE THREAD

**Issue by radicaldeepscale** [microsoft/vscode-docker#2581]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.push
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.9.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:101054
extension.bundle.js:52:345032extension.bundle.js:52:345032
processTicksAndRejections task_queues.js:94:5
async AzureRegistryCreateStep.execute extension.bundle.js:924:144570
```

</details>

**Comment by karolz-ms** [comment]
@radicaldeepscale please do as the error message says, that is, see  https://aka.ms/rps-not-found for how to register your subscription to enable Azure Container Registry use.
