### ISSUE TITLE
The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

### ISSUE THREAD

**Issue by mainul-alam** [microsoft/vscode-docker#2582]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.9.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:101054
extension.bundle.js:52:345032extension.bundle.js:52:345032
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by karolz-ms** [comment]
@mainul-alam please do as the error message says, see https://aka.ms/rps-not-found for how to register your subscription to enable deployment to Azure App Service
