### ISSUE TITLE
tpf-tool

### ISSUE THREAD

**Issue by joambi** [microsoft/vscode-docker#2586]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: To build Docker files you must first open a folder or workspace in VS Code.

Version: 1.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.quickPickWorkspaceFolder extension.bundle.js:52:400678
buildImage extension.bundle.js:924:135844
extension.bundle.js:924:166248
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by karolz-ms** [comment]
This is currently by design, but we will make the experience better via https://github.com/microsoft/vscode-docker/issues/2512
