### ISSUE TITLE
VSCode Docker Issue

### ISSUE THREAD

**Issue by ShoaibSajid** [microsoft/vscode-docker#2587]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "shoaibs" --password-stdin' exited with code 1
Error: error during connect: Post http://127.0.0.1:2375/v1.24/auth: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

Version: 1.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by karolz-ms** [comment]
@ShoaibSajid this is unlikely to be an issue with the extension--looks like you were trying to connect to a Docker registry running locally on your development machine, but it does not seem like the registry daemon was actually running.

If you think this is an issue with the Docker VS, please re-open the issue and describe, step-by-step, what you were trying to do, what you expected to happen, and what happened instead, presumably leading to the error you are seeing. Thanks!
