### ISSUE TITLE
Regroup container by partial name

### ISSUE THREAD

**Issue by iMinosGFX** [microsoft/vscode-docker#2588]
Hello, 
Working in microservices in my company, I am starting to have a lot of containers per project, the list becomes unreadable. 
I was wondering if it was possible to group the containers by part of the name?
For example, all the microservices (i.e. containers) of "project 1" are going to start with "pj1-...", so I would like to be able to make a group with all the containers starting with "pj1-".
Is this possible? 

Thank you !

![Screenshot_2](https://user-images.githubusercontent.com/35743637/103519324-a1587080-4e75-11eb-8aaa-baa4cd63e261.png)

**Comment by bwateratmsft** [comment]
Unfortunately this isn't possible today. Are these all part of a single compose project?

**Comment by iMinosGFX** [comment]
Not especially, the docker composes is only in demo & prod, we don't need it in dev :/

**Comment by philliphoff** [comment]
@iMinosGFX Would a feature like the following be useful to you: the ability to group containers by an arbitrary Docker container label?

Suppose you were to add a Docker label "container-group" set to "<group1>", "<group2>", ..., "<groupN>" to each set of related containers.  For example, "container-group"="pj1" to each container belonging to project 1.  Then suppose the Containers view had the ability to set grouping by "label", after which the user is prompted to enter/select a label (e.g. "container-group").  The view would then show a group of containers for every unique value for that label.  E.g.:

 - pj1
   - pj1-containerA
   - pj1-containerB
 - pj2
   - pj2-containerA
   - pj2-containerB

Do you think such a feature would provide sufficient (and flexible) ordering of your containers?

**Comment by bwateratmsft** [comment]
I'll dupe this to #2617
