### ISSUE TITLE
Semantic highlighting is not showing for my Dockerfile

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2596]
I have 1.9.0 of the Docker extension installed and 1.52.1 of VS Code.

![image](https://user-images.githubusercontent.com/947510/103701026-2e74f580-4f5a-11eb-845a-d2ca5f2fe2fa.png)

**Comment by bwateratmsft** [comment]
@rcjsuen I noticed today that semantic highlighting doesn't show when I'm debugging the Docker extension, but still does show normally otherwise. I don't see any helpful logs in the Output window. Is there somewhere we can look for more info?

**Comment by rcjsuen** [comment]
@bwateratmsft Unfortunately, I don't have any ideas if there is no obvious output being logged anywhere.

1. You could try toggling your settings to see if it helps at all. Do the other language features work normally?
```
"[dockerfile]": {
    "editor.semanticHighlighting.enabled": true
}
```

2. Alternatively, I guess you could use the middleware provided by `vscode-languageclient` and try to monitor the traffic that's being sent to and from the language server.

What I can say is that 0.1.1 of the language server is volatile (see https://github.com/rcjsuen/dockerfile-language-server-nodejs/issues/247). I would suggest making a new release of the Docker extension (which comes with 0.2.0, per #2585) at your earliest convenience.

**Comment by bwateratmsft** [comment]
I built a VSIX from today's main branch, and installed it--in this one, semantic highlighting has stopped working for me (outside of debugging the Docker extension):
![image](https://user-images.githubusercontent.com/36966225/103783058-3be7b980-5006-11eb-96cc-c047aa3ea3e2.png)

This is with `editor.semanticHighlighting.enabled` == `true`. Other things seem to be working--intellisense, completions, etc.

> Alternatively, I guess you could use the middleware provided by `vscode-languageclient` and try to monitor the traffic that's being sent to and from the language server.

I found the options but I'm not really sure how to use them. I put in a `provideDocumentSemanticTokens` but it isn't being called.

**Comment by rcjsuen** [comment]
> > Alternatively, I guess you could use the middleware provided by `vscode-languageclient` and try to monitor the traffic that's being sent to and from the language server.
> 
> I found the options but I'm not really sure how to use them. I put in a `provideDocumentSemanticTokens` but it isn't being called.

@bwateratmsft Thanks for checking! Your comment here raises obvious flags so I dug into the `vscode-languageclient` code and I think I know what's going on.

Can you share the VSIX file here and I'll try installing it? I'm on macOS 10.15.7 running VS Code 1.52.1.

**Comment by bwateratmsft** [comment]
This link should work: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/29501/artifacts?artifactName=vsix&api-version=6.0&%24format=zip

I'm on Win10 20H2, VSCode 1.52.1.

**Comment by rcjsuen** [comment]
@bwateratmsft Thanks for sharing the VSIX build. Some experimentation leads me to believe that https://github.com/rcjsuen/dockerfile-language-server-nodejs/issues/248 is the root cause.

VS Code's language server support was recently tightened to honour the specification more closely in https://github.com/microsoft/vscode-languageserver-node/issues/706 (rightly so). Unfortunately, this backfired on me as I didn't have everything just right on my end.

I've published version 0.2.1 of the language server which includes the fix. Perhaps you can give it a whirl...though I'm not sure how you would do that since semantic highlighting works in your debugging instance but not your host instance...? 🤔

**Comment by bwateratmsft** [comment]
Thanks @rcjsuen! I tested out a build both in debugging and as a packaged VSIX and everything seems to be working. I created #2604 to update it (and fix unrelated #2603).

Thanks again for the fast response as always! We really appreciate all your hard work.

**Comment by karolz-ms** [comment]
+1 on what @bwateratmsft said, many thanks @rcjsuen 🤗

**Comment by BigMorty** [comment]
Thanks @rcjsuen for being a great partner!

**Comment by rcjsuen** [comment]
@bwateratmsft @karolz-ms @BigMorty Happy to help. We're all working towards the common goal of trying to help make developers' lives easier when working with Docker. Just doing my part where I can. :)

Thanks for the bug reports and enhancement requests!
