### ISSUE TITLE
[Suggestion] Add another "Open Workspace" button in the notification if add Docker files without workspace

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2599]
**OS:** Windows 10
**Build Version:** 20210106.8

**Repro Steps:**
1. Make sure there is no folder or workspace opening in VS Code.
2. F1 -> Docker: Add Docker Compose Files to Workspace... -> Check the notification.

**Actual:**
There is only one "Open Folder" button in the notification.
![image](https://user-images.githubusercontent.com/45614674/103855855-80e71b00-50ee-11eb-9e6d-edf569032bf6.png)

**Suggestion:**
Add another "Open Workspace" button in the notification.

**More Info:**
This issue also reproduces when executing "Add Docker Files to Workspace..." command without workspace.

**Comment by bwateratmsft** [comment]
We intentionally decided to exclude the "Open Workspace" button. Users can still open a workspace, of course, but most of our features work better with just folders rather than workspaces (especially debugging, see #2327 for example).
