### ISSUE TITLE
Provide auto-completion of tags for Docker repositories

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-docker#26]
It would be awesome to have auto-completion for the list of available tags within a specified repository. For example, if I have `FROM node:` in my `Dockerfile` and type `CTRL+Space` after the colon, it would be really useful to see the [list of tags](https://hub.docker.com/r/library/node/tags/) for that exact repository (e.g. `6-slim`), without needing to go to its DockerHub page to determine them. Apologies if this behavior already exists and I missed it somehow.

**Comment by rcjsuen** [comment]
@lostintangent Could you update to 7a223846d7b6957fd7f47458d8a513baab6336d1 and then `npm install` to see if image tags are being suggested for you properly with the new dependency on the v0.0.7 release of the language server? Thanks!

**Comment by rcjsuen** [comment]
This feature should be working in the 0.0.17 release.

**Comment by peterblazejewicz** [comment]
This one could be closed:
https://github.com/Microsoft/vscode-docker#intellisense-completions-for-images

**Comment by StephenWeatherford** [comment]
Closing fixed per @rcjsuen's comment above.

**Comment by rcjsuen** [comment]
@StephenWeatherford I think you forgot to click the button.

**Comment by StephenWeatherford** [comment]
:-)
