### ISSUE TITLE
[Unstable] An error "Request timed out" occurs in the notification when pruning Docker volumes

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2600]
**OS:** Windows 10
**Build Version:** 20210106.8
**Note:** **We are not sure the stable reproduce steps for this issue, only track it with this issue**.

**Repro Steps:**
1. Make sure there are a lots of Docker volumes.
2. Prune volumes.

**Expect:**
There is no error when pruning Docker volumes.

**Actual:**
An error "Request timed out" occurs in the notification.
![image](https://user-images.githubusercontent.com/45614674/103859235-ad9e3100-50f4-11eb-9da7-bc4c14d61757.png)

**More Info:**
1. There is no volume in the "Volumes view" after refreshing it.
2. Sometimes, this issue also reproduces when pruning Docker images.

**Comment by bwateratmsft** [comment]
This issue would exist somewhere in the Dockerode / docker-modem / Docker engine API stack. I think it's fine to show this error message in this scenario.
