### ISSUE TITLE
[Suggestion] It will be better if change the volume**s**(s) to volume(s) in the notification message when pruning Docker volumes

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2603]
**OS:** Windows 10
**Build Version:** 20210106.8

**Repro Steps:**
1. Click the prune button to prune volumes.
2. Check the notification message after pruning volumes.

**Actual:**
The notification shows "Removed XX volume**s**(s) and reclaimed XX MB of space".
![image](https://user-images.githubusercontent.com/45614674/103878289-2f03bc80-5111-11eb-8c07-00bfd7616cc6.png)

**Suggestion:**
It will be better if change the volume**s**(s) to volume(s) in the notification message.

**More Info:**
1. This issue also reproduces when pruning Docker images.
![image](https://user-images.githubusercontent.com/45614674/103878066-df24f580-5110-11eb-9244-947ffe772139.png)
2. This issue does not reproduce when pruning Docker containers.
![image](https://user-images.githubusercontent.com/45614674/103878101-eea43e80-5110-11eb-97fc-848712483770.png)

**Comment by bwateratmsft** [comment]
Quick spelling fix.
