### ISSUE TITLE
Error pulling repository

### ISSUE THREAD

**Issue by mateustaufer** [microsoft/vscode-docker#2609]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "mateustaufer" --password-...' exited with code 1
Error: 

Version: 1.9.0
OS: linux
OS Release: 5.8.0-36-generic
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@mateustaufer there isn't an error message in here. Can you add the error and repro steps?
