### ISSUE TITLE
VSCode with Docker Preview MacOs (M1)

### ISSUE THREAD

**Issue by csanders1999** [microsoft/vscode-docker#2610]
Looking for a workaround in order to run Docker (Preview) in VSCode for development on my new MacBook Pro via the Docker Extension.

Is there a way to do so? I have downloaded Docker Preview, but still getting "Docker Desktop is not installed. Would you like to install it?" from the extension.

Thanks.

**Comment by bwateratmsft** [comment]
We're still working on getting a hold of an M1, so we'd love to work with you on this in the meantime! What do you see if you run `docker -v` in the integrated terminal in VSCode?

**Comment by csanders1999** [comment]
zsh: command not found: docker

**Comment by csanders1999** [comment]
For reference, the only Docker I have installed is Docker Preview now. Let me know if I should be re-download the regular version as well

**Comment by bwateratmsft** [comment]
@philliphoff I'm not too familiar with the M1's or the Docker Preview for them, do you know more about what @csanders1999 should expect to see here?

**Comment by philliphoff** [comment]
I've been lobbying for an M1 but haven't gotten my hands on one yet, so I can only speculate.  My first thought would be that it's simply a path issue--that is, that the shells spawned by the extension within the context of the VS Code process to run Docker commands don't have `docker` in the `PATH`.  I've seen such issues happen before on my (non-M1) Mac.

@csanders1999 I assume you're able to run `docker` commands in the Mac terminal?  Which shell are you using in the Mac terminal, and are you using that same shell when using integrated VS Code terminals?

**Comment by csanders1999** [comment]
I am using zsh in VS Code and I got `docker -v `to produce `Docker version 20.10.1, build 831ebeae96`. I can also right click on the Dockerfile and `Build Image`. However, I am unsure how to reopen my project in a container. On my previous Mac, it was in the bottom lefthand corner

<img width="1053" alt="Screen Shot 2021-01-08 at 3 46 34 PM" src="https://user-images.githubusercontent.com/32108822/104062555-b102ec80-51c8-11eb-8aa2-7b77826ac45a.png">

However, I am not sure how to do such now. Any help is much appreciated! Thanks @philliphoff

**Comment by bwateratmsft** [comment]
Images are showing which is encouraging, that means at least the explorer+Dockerode is working.

**Comment by csanders1999** [comment]
Hi all! I wanted to let you know that I got it to work by downloading VSCode Insiders

**Comment by csanders1999** [comment]
For others, using that with Docker Preview was the solution for me! Thank you guys for the help.
