### ISSUE TITLE
Issue in launching app service from vs code. Issue is seen even after enabling admin

### ISSUE THREAD

**Issue by alpha-nome** [microsoft/vscode-docker#2614]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 1.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
getNewSiteConfig extension.bundle.js:924:171843
processTicksAndRejections task_queues.js:94:5
async deployImageToAzure extension.bundle.js:924:171306
```

</details>

**Comment by bwateratmsft** [comment]
Did the error message change after enabling admin mode? Does it still persist after restarting VSCode?

**Comment by alpha-nome** [comment]
It worked after restart. But can you try to change the error code if posssible. Thanks. Not quite sure whats going wrong.

**Comment by bwateratmsft** [comment]
If it worked after restarting, most likely it's a timing or caching issue. FWIW, we're working on eliminating the need to enable admin mode, #1685.
