### ISSUE TITLE
FastAPI Docker Debugger 

### ISSUE THREAD

**Issue by Kludex** [microsoft/vscode-docker#2615]
## Description 

As a VSCode user I want to be able to debug my [FastAPI](https://fastapi.tiangolo.com/) application living inside a Docker container. :tada: 

## More information

The web framework is growing, and I think the community will benefit from this feature. :sunglasses:

Besides, a PR was accepted on the [Python VSCode extension](https://github.com/microsoft/vscode-python) with the same purpose, but without Docker: https://github.com/microsoft/vscode-python/issues/14247 

The idea is to have the option `Python: FastAPI` on the `Docker: Initialize for Docker debugging`:
![image](https://user-images.githubusercontent.com/7353520/104109644-610f4d00-52d0-11eb-9135-0a13b88d885b.png)

## Notes
- I'll be working on this. I'll link the PR when I've finished. :factory_worker:
- Please let me know if this feature will not be accepted, so I stop working on it :sunflower:

**Comment by bwateratmsft** [comment]
Thanks for the suggestion! As long as the Python extension supports FastAPI remote debugging (which it probably does), then this should be possible. We'll take a look.

**Comment by Kludex** [comment]
Fwiw, it should be similar to what's on the Flask one.

Basically this: https://github.com/Kludex/fastapi-docker-debug/

**Comment by karolz-ms** [comment]
@Kludex yes, please submit a PR, and thank you for helping us make the extension better!!

**Comment by Kludex** [comment]
@karolz-ms Thank you for accepting the idea! I'll be pushing a PR in the next days.

**Comment by bwateratmsft** [comment]
Hey @Kludex, any updates on this?

**Comment by Kludex** [comment]
@bwateratmsft I've started. But I lost track of it.

I'll be working (and hopefully) finishing it this weekend. :)

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.11.0.
