### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by gusdoe** [microsoft/vscode-docker#2616]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.9.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
ChildProcess.EventEmitter.emit domain.js:475:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@gusdoe when does this error occur? Do you have Docker installed?
