### ISSUE TITLE
--chmod support for COPY and ADD

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docker#2624]
In docker engine 20.10 support for the `--chmod` flag has been added. Trying to use it in a Dockerfile gives:
```
Unknown flag: chmoddockerfile-utils(40)
```

It would be nice to add support for it.

**Comment by bwateratmsft** [comment]
@thernstig I haven't been able to find any documentation about this flag, even in the [release notes](https://docs.docker.com/engine/release-notes/). Do you have any docs about it? Thanks!

**Comment by thernstig** [comment]
See here https://github.com/moby/buildkit/pull/1492#issuecomment-758105476

They just forgot to add it to the relesae notes.

**Comment by bwateratmsft** [comment]
Thanks!

Where are you seeing the above error? I did not get any intellisense for `--chmod`, but there was no error either.

**Comment by rcjsuen** [comment]
> @rcjsuen it seems this was a rather stealthy addition from Docker; can you add support for it in the language server?

Yeah. There are a few different pieces to supporting a new flag but I'll start by making sure it is ignored by the linting process.

**Comment by rcjsuen** [comment]
@bwateratmsft I've published version 0.3.0 of the language server to stop flagging the `--chmod` flag as an error for both `ADD` and `COPY` instructions.

**Comment by bwateratmsft** [comment]
Awesome! Thanks @rcjsuen!

**Comment by rcjsuen** [comment]
@bwateratmsft Thanks for getting the fix merged in and thank you @thernstig for letting me know about this issue!

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
