### ISSUE TITLE
IntelliSense helps with ordering for Dockerfile authoring

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2627]
While authoring my Dockerfile, sometimes I do not know which section would be most efficient to come first. Should EXPOSE go at the top or bottom? Is there a better place to put my COPY or ADD command? Would there be a way to provide helpful suggestions so that if I was writing a Dockerfile from scratch, the user would definitely get a "FROM imagename:2.4" on the first trigger of IntelliSense?

Scenario Ideas:
- When I hit CTRL + Spacebar, could there be an order that is given to the user more in line with their Docker authoring rather than alphabetical? 
- When I put a command that is more likely to change or will take a long time (bad ordering) - give a yellow squiggly to tell the user it may be more performant to move their line to a specific place

**Comment by bwateratmsft** [comment]
@ucheNkadiCode I don't really think this is plausible, for several reasons--
1. Most Dockerfiles are authored by either copying from examples or scaffolding. Writing them from scratch is rare and when it is done, it's typically done by people with enough expertise to know what to put.
1. The order of things is going to vary dramatically by platform/language
1. The order of things is going to vary dramatically based on individual needs and implementations
1. Knowing the true meaning of commands--e.g., "is this line a nuget restore?", is an insurmountably complex problem

We could spend _years_ working on this and end up with something only marginally useful for some and actively unhelpful for others.

**Comment by bwateratmsft** [comment]
@ucheNkadiCode It's not a bad idea but it'd probably take a pretty advanced AI. Also it'd probably put us out of a job. :smile:
