### ISSUE TITLE
[Suggestion] Change the minimum VS Code version that the Docker extension supports

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2628]
**OS:** Windows 10
**Build Version:** 20210111.1

**Repro Steps:**
1. Figure out the minimum VS Code version that the Docker extension supports, the version is "1.49.0".
![image](https://user-images.githubusercontent.com/45614674/104550040-f57e0480-566e-11eb-9f44-fdff1de51425.png)
2. Install VS Code 1.49.3.
4. Install Docker extension in VS Code and navigate to Docker view.

**Actual:**
An error "The language client requires VS Code version ^1.52.0 but received version 1.49.3" occurs.
![image](https://user-images.githubusercontent.com/45614674/104550000-e1d29e00-566e-11eb-930e-0fd33b2a0e1a.png)

**Suggestion:**
Change the minimum VS Code version that the Docker extension supports.

**Comment by bwateratmsft** [comment]
We should do this for 1.9.1.
