### ISSUE TITLE
The name of the container "myexpressapp:latest" will be changed after executing "Run Interactive" for other images

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2632]
**OS:** All
**Build Version:** 20210114.1

**Repro Steps:**

1. Create an Express App project and open it in VS Code.
2. Command Palette -> Add Docker files to workspace -> Node.js -> Enter port.
3. Right click Dockerfile -> Build image.
4. Navigate to "Images" view -> Right click this image -> Select "Run" -> There is a running container named "myexpressapp:latest".
5. Open the Dockerfile -> Add the following two "ENV" lines -> Build image again
     ```
    ENV PORT 3001
    ENV DEBUG myexpressapp:*
    ```
6. Navigate to "Images" view -> Right click the “hello-world” image -> Select "Run Interactive".
7. Check whether The name of the container "myexpressapp:latest" remains unchanged.

**Expect:**
The name of the container "myexpressapp:latest" remains unchanged.

**Actual:**
The name of the container "myexpressapp:latest" will be changed.
![container](https://user-images.githubusercontent.com/62053665/104698331-2e3fdb80-574c-11eb-8e10-5bc95783f2ae.gif)

**Comment by bwateratmsft** [comment]
I'll have to investigate to be sure but I think what is happening is that, upon rebuilding a new image, the `myexpressapp:latest` tag is taken away from the previous image--which the container is still running. _Technically_ this behavior would be correct since the container is running an outdated image, and it also no longer has any association to `myexpressapp:latest`.

**Comment by bwateratmsft** [comment]
Yes, this is the behavior I thought would happen. After rebuilding, the old image remains, but its tag becomes `<none>:<none>`. We don't show such images in the images explorer, but instead of showing `<none>:<none>` as the image name in the containers explorer, we show the SHA digest.
