### ISSUE TITLE
[Doc Request] Debug containerized C++ apps

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2636]
A user is requesting that we write documentation for how to debug containerized C++ applications? This is an interesting topic since I wonder if there are many users out there Running containers with C++. 

Reference bug: https://github.com/microsoft/vscode-docs/issues/4238

**Comment by bwateratmsft** [comment]
C++ is extremely popular in VSCode (second most installed extension after Python), so it stands to reason there's a fair bit of them doing containerized work.

**Comment by gregvanl** [comment]
@ucheNkadiCode Here is another user hitting friction trying to debug C++ in a container. https://github.com/microsoft/vscode-dev-containers/issues/827

**Comment by ucheNkadiCode** [comment]
Feedback from @gregvanl 
I'm doing some issue grooming in the vscode-docs repo and wondered if you're still planning to do a topic on debugging C++ in a container similar to the tutorials for Node.js, Python, and ASP.NET? https://github.com/microsoft/vscode-docker/issues/2636.
[Doc Request] Debug containerized C++ apps · Issue #2636 · microsoft/vscode-docker
A user is requesting that we write documentation for how to debug containerized C++ applications? This is an interesting topic since I wonder if there are many users out there Running containers wi...

[1:35 PM] Greg Van Liew
This Doc Request issue is linked to from https://github.com/microsoft/vscode-docs/issues/4238.
Debug containerized C++ apps · Issue #4238 · microsoft/vscode-docs
As the documentation says https://code.visualstudio.com/docs/containers/debug-common only Node.js, Python and .Net apps are supported. What I would like to be able is to debug C++ executables using...

[1:36 PM] Greg Van Liew
We see surprisingly high page views for the VS Code C++ tutorials so I think there is a lot of interest in C++ development. 

I want to resubmit this to triage.

**Comment by ucheNkadiCode** [comment]
Closing this issue as we do not have plans to provide scaffolding/debugging support for C++ executables.

**Comment by bwateratmsft** [comment]
We already have some scaffolding support though it is very old and probably not that good. The big challenge is that C++ projects tend to almost always have a unique build / structure that would make creating a common Dockerfile impossible.
