### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by giorgiootto** [microsoft/vscode-docker#2638]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/15fce6e9-3a4c-47ab-89be-1e219e3b91c1/resourceGroups/giorgiootto-echo-app/providers/Microsoft.Web/serverfarms/giorgiootto-echo-app?api-version=2019-08-01 failed, reason: connect ETIMEDOUT 191.233.205.17:443

Version: 1.9.0
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by bwateratmsft** [comment]
@giorgiootto is this consistent? Can you add repro steps?

**Comment by giorgiootto** [comment]
Hi,

I Tried to publish in container as service.

**Comment by bwateratmsft** [comment]
Does this happen every time?
