### ISSUE TITLE
Visual Studio Docker build Problem

### ISSUE THREAD

**Issue by erselbey** [microsoft/vscode-docker#2639]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: Error
Error Message: To build Docker files you must first open a folder or workspace in VS Code.

Version: 1.9.0
OS: darwin
OS Release: 20.2.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.quickPickWorkspaceFolder extension.bundle.js:52:400678
buildImage extension.bundle.js:924:135844
extension.bundle.js:924:166248
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by karolz-ms** [comment]
@erselbey do you have a folder or workspace open? Can you explain how you got this error message (repro steps)?

@bwateratmsft I think we should consider disabling the capability to do one-click issue submission for this error message

**Comment by bwateratmsft** [comment]
We did! #2593
