### ISSUE TITLE
docker new .netcore issues

### ISSUE THREAD

**Issue by RonakThakkar** [Microsoft/vscode-docker#264]
There are several issues.

1. docker new .netcore uses old asp.net core image FROM microsoft/aspnetcore:1. It should use new image as FROM microsoft/aspnetcore:2.0

2. dockerfile should be created using multi stage as shown in below link
https://docs.docker.com/engine/examples/dotnetcore/#create-a-dockerfile-for-an-aspnet-core-application

3. dockerfile should have different content and base image for .NET Core Console and .NET Core ASP.NET Web API. Right not it creates same for both types of projects.

**Comment by chrisdias** [comment]
I've got a request out to the .NET folks for updated dockerfile artifacts...
