### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by donielix** [microsoft/vscode-docker#2640]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.9.0`
- OS Version: `Linux x64 5.8.0-7630-generic`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@donielix does this happen consistently?
