### ISSUE TITLE
Debugging python in a docker in WSL works not.

### ISSUE THREAD

**Issue by kristjanvalur** [microsoft/vscode-docker#2642]
Issue Type: <b>Bug</b>

To reproduce:

- In wsl, create a new project with hello.py in it.  Add a print("hello") to it.
- open "code ." and use docker to create Dockerfiles.  Specify Python-general and to run hello.py
- set a breakpoint at your print statement
- Launch debugger.  A container is launched, but the launching process never completes and the breakpoint is never hit.
- Stop debugging.  Reopen the folder on Windows
- Launch debugger.  After a while, debug launching succeeds and breakpoint is hit.

Extension version: 1.9.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (10.92GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/kristjan/git/manipulator --remote=wsl+Ubuntu-18.04 --crash-reporter-id c94004f9-c509-4021-b2a6-63ae621267ef|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4199)|
|Memory (System)|25.03GB (16.94GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
vstry244:30244299
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600cf:30241728

```

</details>

**Comment by bwateratmsft** [comment]
This sounds the same as #2641, I wonder if Python debugging is regressed again.

**Comment by kristjanvalur** [comment]
The output in the console is the same.  Opening a cli in the container shows me no processes running.
I can put any arguments to the "python" section in tasks.json, e.g. specify a non-existing .py file, and there is no error because apparently it never even comes to that.

The important part is that it fails when working with a remote WSL connection, but succeeds when doing it locally.

**Comment by bwateratmsft** [comment]
Ok, it looks like this is indeed the same as #2641 so I'll close this one as duplicate.
