### ISSUE TITLE
Pasting password

### ISSUE THREAD

**Issue by haf** [microsoft/vscode-docker#2643]
When adding a registry, having a 30+ char password, you can't paste your password in the popdown at the top of the VSCode window.

You must be able to.

**Comment by bwateratmsft** [comment]
I was able to paste without any trouble. What version of VSCode do you have, and what OS?

**Comment by haf** [comment]
VSCode: 1.52.1
macOS: 10.15.7

**Comment by PavelSosin-320** [comment]
Pasting passwords must be prohibited due to security reasons. It is learned in the Secure programming courses. Interception of GUI control is much easier than keyboard input. The password visual control must prevent boilerplate display and copy its value. Hackers know it.

**Comment by haf** [comment]
I’m sorry but that’s bullshit. Having long unique passwords for every site is better than having a single short typeable password that you reuse everywhere.

Also I don’t see why what you’re saying makes sense at face value. Suppose the GUI was compromised and it showed the same dialog: I’d be toast no matter how I inserted the password.

**Comment by bwateratmsft** [comment]
I wasn't able to repro on my Mac. I looked into the settings we're using for the InputBox but nothing obvious stood out. I _did_ find this, however: https://github.com/microsoft/vscode/issues/114325

You're definitely not the only user encountering paste issues. I'm going to comment on that issue, but I'll close this one as there's no settings in our code that would cause this--seems to just be a VSCode bug.

**Comment by PavelSosin-320** [comment]
@haf This is SSH security issue only. Having 30 characters length password for every server / user without a password recovery mechanism is too inconvenient. It's better to change it weekly. Windows itself allows 7 characters passwords.
Pastable password control will fail any security auditing. 
If you are talking about Web sites and you use Chrome it doesn't allow you to have one short weak password for all sites. Today the session security is not password-based. If you see the locked lock in the left upper corner and no security warning the site uses TLS > 1.2 After a certain period of time the token will expire regardless of password length.

**Comment by haf** [comment]
@PavelSosin-320  I have 897 unique passwords across servers, web sites, etc. Good luck convincing me to 1) remember them all, 2) rotate them all every 7 days. If your password storage is secure, it's more secure to have a really long password than to have a short one, even if you don't rotate it.

In my work, I do security audits and build cloud platforms, amongst other things, so I'm fairly sure that removing the paste functionality doesn't make you more secure. Since this is OT for the thread (and I'm not even vaguely sure you're not trolling me!), this is my last reply now! Over and out.

**Comment by bwateratmsft** [comment]
I'd agree with @haf. Microsoft also has dropped guidance to rotate passwords regularly; any human-generated passwords regularly rotated tend to be worse, not better.
