### ISSUE TITLE
Docker returned an error. Make sure the Docker daemon is running.

### ISSUE THREAD

**Issue by chen-bowen** [microsoft/vscode-docker#2645]
I didn't do anything, but just trying to connect to remote docker gives a popup message "Docker returned an error. Make sure the Docker daemon is running." When I click on show logs it shows "spawn docker ENOENT". The docker image I used is the default docker101tutorial

**Comment by bwateratmsft** [comment]
@chen-bowen when you say "trying to connect" do you mean using the Remote - Containers extension?
