### ISSUE TITLE
Right Click Option to "Select a subset of Compose services"

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2646]
In order to select a subset of services by right-clicking a Compose file and selecting "Compose Up", a user has to go into their settings.json file and write:

docker.commands.composeUp: "docker-compose ${configurationFile} up ${detached} ${build} ${serviceList}"

Now that we can select services dynamically before Composing up, I'd like an option that makes this dynamic selection more accessible to use

![image](https://user-images.githubusercontent.com/20650058/105126237-273e0380-5a93-11eb-9fa0-645356352f28.png)

It could follow default functionality of this feature such as "none selected" is the same as all selected etc . 

**Question**: Does this composeUp setting in settings.json persist for all other projects the user may open up in VS Code? I feel like this may be problematic if they are a user that has a simpler Project that uses compose and also a more complex project that actually needs the subset

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
