### ISSUE TITLE
Increase awareness for new features

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2647]
To increase awareness, I suggest we:

- Add Wordings that mention our new Compose Subset of services feature. We can put it in a higher section that is separated from the current messaging. Within that blurb, we should link them to documentation on how to enable it/use it with tasks and whatever else 
- Bump up the amount of users that see our getting started page upon installation/update

Editing to encompass files, subset, and tooltips

**Comment by ucheNkadiCode** [comment]
Suggested wording 

# What's New

## Run your choice of services in Compose
Users are now able to 

To enable this feature:
1. Navigate to File > Preferences > Settings (Ctrl + ,) 
2. Search for 'Compose Up' to find the **Docker > Commands: Compose Up ** setting
3. Select Edit in settings.json
4. docker.commands.composeUp: docker-compose ${configurationFile} up ${detached} ${build} ${serviceList}

(still editing)

**Comment by bwateratmsft** [comment]
@ucheNkadiCode @BigMorty I've been thinking... (dangerous, I know!)

We may want to just wait on this until we have an outcome from this compose up subset experiment. Otherwise we either need long and complicated text to explain how to use the feature--which probably won't fit on the page anyway--or a link to the docs to similarly long and complicated text. On the other hand, if we find this compose up subset experiment successful and decide to keep the command, we can much more easily just point to that context menu option.

**Comment by bwateratmsft** [comment]
Moving to 1.11 per our chat.

**Comment by bwateratmsft** [comment]
@ucheNkadiCode what's the plan here? The comment you have above is *waaaay* too long to put on our start page, we need like ~1 sentence per item.

**Comment by ucheNkadiCode** [comment]
@bwateratmsft 

Would it be easier if I just show a picture for each item rather than explaining how the user can use the feature? 

# What's New

## Select which services to run in your Compose file
When you right-click on a Compose file, choose **Compose Up - Select Services** to select which services you want to run!

[TODO for Brandon] - Can we get a picture of this feature? 

## View files in your container
While your container is running, you can now view any folders and open or download files right from VS Code!

![image](https://user-images.githubusercontent.com/20650058/109889754-d34e3f00-7c3a-11eb-80b8-a7413ab7c0ce.png)

## Hover over items for more information
Introducing, Docker Tooltips! When you hover your mouse over a container, image, network, volume, or context, we give you a quick glance at the important details of each item! 

![image](https://user-images.githubusercontent.com/20650058/109933020-d0297200-7c7f-11eb-8315-472c7967c66f.png)

**Comment by bwateratmsft** [comment]
We don't have space on the start page for images without scrapping everything there now. The most we have is room for about three lines of text.

**Comment by bwateratmsft** [comment]
Won't be time to do this in 1.11.0.

**Comment by bwateratmsft** [comment]
Spitball text:

Try the new "Docker: Compose Up - Select Services" command! You can use it to start a subset of all the services in your compose document.

The Docker Explorer view now has advanced tooltips containing a lot of useful info.

Expand a container node and you can view the file system.

**Comment by bwateratmsft** [comment]
We'll run this as an experiment so we can see if it's actually effective. We're going to ramp up exposure quickly.

**Comment by ucheNkadiCode** [comment]
Final Draft :D @bwateratmsft, ready to go

# What's New

- The Docker Explorer View now has advanced tooltips!  Hover your mouse over an item to see useful info.
- You can now now open and download the files in a running container! Expand a container node to get started.
- Right-click on a Compose file to try our new `Docker: Compose Up - Select Services` command!
