### ISSUE TITLE
Add Video Links to Help and Feedback Section

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2648]
I think it would be helpful if we added a video link to the Help and Feedback section within the Docker View. Maybe the section could be called: 

- Docker Extension Videos
- Walkthrough Videos
- Getting Started Videos
- Tutorial Videos
- Tips & Tricks - Videos

I recommend @BigMorty's Youtube playlist 😀

**Comment by BigMorty** [comment]
Text for the new entry in the Help section should be "Docker Extension Videos".
The link for the new entry should be "https://aka.ms/helppanel_videos".
The icon for the new entry should be the "play-circle" icon.
Please make this new entry the second entry, just below "Docker Extension Documentation".

**Comment by bwateratmsft** [comment]
Thanks @BigMorty!

**Comment by bwateratmsft** [comment]
@BigMorty @ucheNkadiCode here's how it looks:
![image](https://user-images.githubusercontent.com/36966225/105367333-55742e00-5bce-11eb-878a-71be2798a72c.png)

I'm wondering--the rest of the items are verbs/actions, like "get started" "open" "review", etc. Should we change the first one to "read extension documentation", and this one to "watch tutorial videos" or something like that?

**Comment by BigMorty** [comment]
I like having a verb/action, so yes lets do as you suggest.

**Comment by bwateratmsft** [comment]
How's this @BigMorty @ucheNkadiCode ?

![image](https://user-images.githubusercontent.com/36966225/105402595-97fd3100-5bf5-11eb-9c8e-079eeb528e71.png)

**Comment by BigMorty** [comment]
looks great, thanks!
