### ISSUE TITLE
report issue

### ISSUE THREAD

**Issue by reydamunta** [microsoft/vscode-docker#2653]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.contexts.inspect
Error type: 1
Error Message: Process 'docker context inspect default' exited with code 1
Error: 'docker' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

Version: 1.9.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:114908
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@reydamunta is Docker installed?
