### ISSUE TITLE
Include OCI client ID header in manifest checks for out-of-date-ness

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2659]

**Comment by MichaelSimons** [comment]
Here is the ACR issue which describes the OCI client ID header in more detail - https://github.com/Azure/acr/blob/main/docs/http-headers.md

**Comment by bwateratmsft** [comment]
@MichaelSimons Thanks! Do you have a suggestion for what our ID should be? Perhaps `azure/vscode/docker`, or `on-prem/vscode/docker`?

**Comment by MichaelSimons** [comment]
Those seem reasonable to me.  @Steve.Lasker@MSFT, do you have any input?
