### ISSUE TITLE
/home/ponce/environment/dc_rls

### ISSUE THREAD

**Issue by poncew7** [microsoft/vscode-docker#2662]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.buildImage
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.9.1
OS: linux
OS Release: 4.15.0-134-generic
Product: Visual Studio Code
Product Version: 1.52.1
Language: ja

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:52:358891
fulfilled extension.bundle.js:52:352830
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by bwateratmsft** [comment]
Hey @poncew7, unfortunately this is a longstanding upstream issue that has never been fixed. The easiest workaround is to just restart VSCode.

Upstream issue: https://github.com/microsoft/vscode-azure-account/issues/53
Upstream further from that: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/197
