### ISSUE TITLE
Python Code Spaces Scenario has some bad UX

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2664]
When following the https://github.com/microsoft/vssaas-planning/issues/1740 - Scenario a few bugs are occurring when trying to create a GitHub Codespaces for https://github.com/ucheNkadiCode/codespaces-docker-python. 

Some of these issues may span our entire experience.

- When Adding Dockerfiles to Workspace, manage.py is not found. I would like app.py and manage.py to be defaulted to the top if it was found.
- When a file that does not exist is entered, aka manage.py in this case, the command fails with no error messaging. I think it would be fine if the scaffolding still worked even if the user would ultimately get a "file not found error". The reason being that they could easily add that file later
- After entering any random file that our extension does find and changing it back to manage.py, composing up on compose-debug and attaching to that running container fails.

**Comment by bwateratmsft** [comment]
> * When Adding Dockerfiles to Workspace, manage.py is not found. I would like app.py and manage.py to be defaulted to the top if it was found.

Couple things happening here...
1. There were so many `.venv` files that the pattern search capped out, resulting in `manage.py` not showing up. I'm making a fix that will ignore `.venv` files.
1. Making another fix that will push `manage.py` and `app.py` to the top of the list.

> When a file that does not exist is entered, aka manage.py in this case, the command fails with no error messaging. I think it would be fine if the scaffolding still worked even if the user would ultimately get a "file not found error". The reason being that they could easily add that file later

The input box is actually a search box, not an input box--so entering an arbitrary value is not actually entering that value, rather, it is cancelling.

> After entering any random file that our extension does find and changing it back to manage.py, composing up on compose-debug and attaching to that running container fails.

The filename is written into both `tasks.json` _and_ `docker-compose.debug.yml`. It's easy to miss in the latter. Once I changed that place as well, it worked.
