### ISSUE TITLE
about code completion

### ISSUE THREAD

**Issue by alexzshl** [microsoft/vscode-docker#2666]
sorry ,but I think the code completion is not very specification. There isn't `$0` privided, which resulted that we have to press another `tab` to exit the snippet. 

such as:
![image](https://user-images.githubusercontent.com/39125296/105578675-dc86f900-5dbc-11eb-860d-9e4ca2bfde8e.png)
~~I think change $1 to $0 will be better.~~
Anther question, I found it in file `server.js` from extension folder, but I can't find the corresponding source file in this repo. Anyone knowns, tells me, thanks

**Comment by rcjsuen** [comment]
> sorry ,but I think the code completion is not very specification. There isn't `$0` privided, which resulted that we have to press another `tab` to exit the snippet.
> 
> such as:
> ![image](https://user-images.githubusercontent.com/39125296/105578675-dc86f900-5dbc-11eb-860d-9e4ca2bfde8e.png)
> I think change $1 to $0 will be better.

@alexzshl I'm not sure I understand the issue here. If you type `FR` then autocomplete to `FROM baseImage`, you can type `alpine` and once you hit the <kbd>A</kbd> key you are no longer in code completion mode.

> A snippet can define tab stops and placeholders with `$1`, `$2` and `${3:foo}`. `$0` defines the final tab stop, it defaults to the end of the snippet. Placeholders with equal identifiers are linked, that is typing in one will update others too.

Also, based on the [specification](https://github.com/microsoft/language-server-protocol/blob/481a6f8d2eb6fa54d4de3c98eb6b6d6590785a1d/_specifications/specification-3-16.md), `$0` is optional.

> Anther question, I found it in file `server.js` from extension folder, but I can't find the corresponding source file in this repo. Anyone knowns, tells me, thanks

The Docker extension team does not maintain the language server in this repository. I maintain it at the [rcjsuen/dockerfile-language-server-nodejs repository](https://github.com/rcjsuen/dockerfile-language-server-nodejs).

**Comment by alexzshl** [comment]
@rcjsuen 
I know how to exit code snippets, but mine is that using $0 will allow users to exit code snippets faster. In my experience, $0 does make a difference

The language server:
![docker_1](https://user-images.githubusercontent.com/39125296/105580285-71dabb00-5dc6-11eb-9db5-651867b6c5b8.gif)
progress:
1. type `fr`
2. press `tab`
3. press `tab`
4. type `add`


Then there is a custom code snippet used to demonstrate $0:
![docker_2](https://user-images.githubusercontent.com/39125296/105580374-f3cae400-5dc6-11eb-90ff-3bddbb7ff9ea.gif)
progress:
1. type `fr`
2. press `tab`
3. type `add`
Because there is only one placeholder here, when I press `tab` to accept sugguestion, I have automatically exited the code snippet
```json
  "from": {
		  "prefix": "bfrom",
		  "body": [
			  "FROM ${1:baseImage}",
			  "$0"
		  ]
	  }
```

**Comment by rcjsuen** [comment]
@alexzshl Why do you use the <kbd>Tab</kbd> key to exit out of the snippet? If you're at the end of the line in a Dockerfile wouldn't you just use hit the <kbd>Enter</kbd> key to go to the next line? That would exit you out of code completion mode completely.

**Comment by alexzshl** [comment]
@rcjsuen  Your answer made me realize that there must be some differences in our vscode. I cannot automatically exit the code snippet by hitting the `Enter` key (I disabled all other extensions).

As you can see from the first gif above, I typed "add" after hit `Enter`, but it is obvious that I am still in the code snippet at this time(pay attention to the gray coloring on the word `add`). I just think the active code snippet state interferes with our code too much.

To disable the vscode setting item `Snippets Prevent Quick Suggestions`, then I can get code suggestions at any time. This setting solves most people's problems, although I don't like it.

In general, I think this is a functional trade-off. My question is not helpful, so I should close it.
