### ISSUE TITLE
HOW TO Suppress Problem?

### ISSUE THREAD

**Issue by conkpb-cg** [microsoft/vscode-docker#2670]
We would like to suppress the following linter problem:

![image](https://user-images.githubusercontent.com/60627763/105757972-57aef300-5f14-11eb-876f-1e1608ffa066.png)

`WORKDIR paths should be absolute`

Is there way to suppress like for other linters?

**Comment by bwateratmsft** [comment]
You can do this with a setting:
![image](https://user-images.githubusercontent.com/36966225/105758333-21c23c80-5f1d-11eb-81de-f53d450348da.png)

**Comment by conkpb-cg** [comment]
Thanks!
