### ISSUE TITLE
files opend with read-only,and i cant change every file

### ISSUE THREAD

**Issue by Kingflyinger** [microsoft/vscode-docker#2674]
i am a new learner, i know the question may be silly, but i just cant find a way to avoid it.
i just want to know how to edit file

![image](https://user-images.githubusercontent.com/41682019/105875974-6d6a0880-6039-11eb-96cd-0535fa1bad89.png)

**Comment by bwateratmsft** [comment]
Editing files is not currently possible but it is being worked on: #2465
