### ISSUE TITLE
Support editing files of running Windows containers

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#2675]
The Docker host for Hyper-V based containers (i.e. Windows containers) does not support the get/put archive APIs used to support file viewing/editing of files. While we have found a workaround for viewing files in a Windows containers, I've yet to find one for editing those files.  Hence, we currently only support editing of Linux containers (which make up the vast majority of running containers).

If there's enough customer interest, we should both push Docker for that API support and/or resume investigating potential workarounds.

This is an extension of #2465.

**Comment by dbreshears** [comment]
This is not planned
