### ISSUE TITLE
Make tooltips user-customizable

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2677]
With #2592 / #2652 we added some nice Handlebars-templated tooltips to the explorer views. We should look at making them user-customizable.

**Comment by houldsg** [comment]
I would really like to be able to customize the delay before the tooltip shows. I find it pops up too soon and stops me being able to click on the container I actually want.

**Comment by bwateratmsft** [comment]
@alexr00 is there any way to set the hover delay?

We could also add a setting to disable the tooltips altogether.

**Comment by bwateratmsft** [comment]
It looks like this was requested some time ago, but was [won't-fixed](https://github.com/electron/electron/issues/12861) in Electron and [closed external](https://github.com/microsoft/vscode/issues/49047) in VSCode. I'm not sure if it's even possible to implement some configuration in VSCode or not--I think @alexr00 would know the answer to that.

**Comment by alexr00** [comment]
If you're using just string tooltips, then all the won't-fix and close-as-external stand.

However, if you're using markdown `MarkdownString`, then this is a feature request that we could accommodate through a setting. For tooltips with a `MarkdownString` we use our own custom hovers and we can control the delay. Currently it is hardcoded to be similar to the system default hovers (about 1500 ms on mac, about 500 ms on Windows and linux).

Opened https://github.com/microsoft/vscode/issues/117894 to discuss.

**Comment by bwateratmsft** [comment]
Yep, we're using `MarkdownString`. Cool!
