### ISSUE TITLE
The tooltip shows "loading..." when hovering the mouse over "Image group"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2679]
**OS:** Win 10
**Build Version:** 20210127.15

**Repro Steps:**
1. Navigate to Docker view.
2. Hover the mouse over "Image group", check the tooltip.

**Expect:**
The tooltip shows well, such as when hovering the mouse over the image.
![image](https://user-images.githubusercontent.com/45614674/106097485-5b3fb580-6172-11eb-9796-946fe9b38604.png)

**Actual:**
The tooltip shows "loading...".
![image](https://user-images.githubusercontent.com/45614674/106097262-fab07880-6171-11eb-96ed-9cc8805aa53c.png)

**More Info:**
1. This issue does not reproduce when hovering the mouse over the image/container.
2. This issue also reproduces when hovering the mouse over "Container group/Azure/Docker Hub...".

**Comment by bwateratmsft** [comment]
I'm trying on Windows as well and it's not showing any tooltip at all for the group nodes, which is what I'd expect. @v-ruizh does this happen consistently?

**Comment by bwateratmsft** [comment]
Ok, I *can* repro this issue on Insiders. I'll take a look.

**Comment by bwateratmsft** [comment]
Working on an upstream fix in [vscode-azureextensionui](https://github.com/microsoft/vscode-azuretools/pull/841), but also opening https://github.com/microsoft/vscode/issues/115337. Either of those two will fix our issue.
