### ISSUE TITLE
Debug configuration for docker containers

### ISSUE THREAD

**Issue by ekimia** [Microsoft/vscode-docker#268]
I've seen some sporadic things online and have been clamoring for full docker debugging support in visual studio code, similar to this in JetBrains land: https://www.jetbrains.com/help/pycharm/using-docker-compose-as-a-remote-interpreter.html#docker-compose-remote

What's the status? How could I help?

**Comment by chrisdias** [comment]
@ekimia yes you can debug apps running in docker containers.  the extension provides a debug configuration that you can access when editing `launch.json`:

![image](https://user-images.githubusercontent.com/1487073/40405879-36f66832-5e13-11e8-8892-ce883bd1ff28.png)

And, here is a detailed document on how to set up debugging of containers: https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript
