### ISSUE TITLE
Extension won't connect to docker daemon running in Minikube

### ISSUE THREAD

**Issue by guneemwelloeux** [microsoft/vscode-docker#2681]
# Description
The extension won't show me the running containers when I'm selecting the docker context that points to the daemon inside my minikube cluster.
It show the error `Error: write EPROTO ... SSLV3_ALERT_BAD_CERTIFICATE ...` (could not copy the actual error line from VSCode)

# Reproduction steps:
MacOS Catalina, minikube v1.9.2, kubernetes v1.14.10, docker daemon in kubernetes: 19.03.8
1. Start and run a minikube cluster.
2. Point the default context to minikube with `eval $(minikube docker-env)`
3. Create a new context with `docker context create minikube --from=default`
4. Unset docker env vars with `eval  $(minikube docker-env --unset)`
5. Switch to docker context minikube with `docker context use minikube`

At this point, in the terminal, `docker ps` will give me the list of running pods in my minikube's docker daemon, indicating that the context is apparently fine.

Head over to VSCode, verify that `minikube` is selected in the Contexts pane of VSCode. Refreshing the Images or Containers panes in VSCode will show the issue.

**Comment by bwateratmsft** [comment]
@guneemwelloeux can you add more information about your setup?

**Comment by guneemwelloeux** [comment]
Sorry about the lack of info before, a misclick resulted in an empty issue. I hope what I have added to the description will be enough, and if not, feel free to ask for more!

**Comment by bwateratmsft** [comment]
Thanks! We'll take a look.

**Comment by bwateratmsft** [comment]
At a glance I think this is probably due to #2058 but I'd like to investigate to be sure.

**Comment by bwateratmsft** [comment]
Yep, it looks to me to indeed be #2058. In our code for determining Docker context, we don't consider certificates. In [this comment](https://github.com/microsoft/vscode-docker/issues/2058#issuecomment-642640363) I mention some possible workarounds--they are unfortunately cumbersome, but do seem to work. I tried out using just `eval $(minikube docker-env)` and was able to see containers in the explorer. It stinks not being able to use contexts...but that's what #2058 is about, ultimately.
