### ISSUE TITLE
Dockerfile linting error in FROM

### ISSUE THREAD

**Issue by rodynnz** [Microsoft/vscode-docker#269]
If your `FROM` contains a port in the registry host section, the linting throws an error in the tag section.

**Example to reproduce:**

`FROM example.registry.com:12345/base/image:1.0.0`

**Error shown:**

`[dockerfile-utils] Invalid reference format`

**Versions affected:**

- Visual Studio Code 1.23.1 (April 2018)
- Docker 0.0.27

**Comment by rcjsuen** [comment]
Hi, @rodynnz. Thank you for your bug report. I identified this error a few days ago and have already opened rcjsuen/dockerfile-utils#39.

Regarding private registries, is the lack of a port number also valid? Will the Docker Engine query a default port with the registry API?

```Dockerfile
# is this Dockerfile valid?
FROM example.registry.com/base/image:1.0.0
```

**Comment by rodynnz** [comment]
Yeah sure, port is optional and follow the rules for HTTP/S connections (ports 80 or 443 are default ones)

**Comment by rcjsuen** [comment]
@rodynnz Cool, thanks for the info! I'll look into correcting my parser... :)

**Comment by StephenWeatherford** [comment]
@rodynnz This has been fixed and will be available in the next release.

**Comment by StephenWeatherford** [comment]
@rodynnz Just wanted to let you know that we have published a new version of the Docker extension that should contain this fix.  Happy coding!
