### ISSUE TITLE
An error occurs if creating an ACI context with "+ Create new resource group" selected while logged out

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2692]
**OS:** Win 10
**Build Version:** 20210201.3

**Repro Steps:**
1. F1 -> Azure: Sign Out.
2. F1 -> Docker Contexts: Create Azure Container Instances Context... -> Enter a context name -> Select "Sign in to Azure..." to finish sign in -> Select "+ Create new resource group".

**Expect:**
Navigate to "Enter the name of the new resource group" item.

**Actual:**
An error "Cannot read property 'resourceManagerEndpointUrl' of undefined" occurs.
![image](https://user-images.githubusercontent.com/45614674/106567509-e94dde80-656c-11eb-8790-8c0836f57829.png)

**More Info:**
1. This issue does not reproduce if selecting an existing resource group.
2. This issue does not reproduce if sign in to Azure before creating ACI context.

**Comment by bwateratmsft** [comment]
<details>
<summary>Call Stack</summary>

```
Object.createAzureClient extension.bundle.js:65:701907
Object.<anonymous> extension.bundle.js:16:311313
fulfilled extension.bundle.js:16:310686
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by bwateratmsft** [comment]
@ejizba Have you seen similar errors in any of the other Azure extensions?

**Comment by ejizba** [comment]
Last time I saw that error was https://github.com/microsoft/vscode-azure-account/issues/215

**Comment by bwateratmsft** [comment]
That one is still open so I'll resolve this as external.
