### ISSUE TITLE
Backslash causes build failure using VSCode on Windows, Docker on WSL

### ISSUE THREAD

**Issue by zzumbo** [microsoft/vscode-docker#2695]
Issue Type: <b>Bug</b>

When using the Docker plugin's "Build Image..." feature in the context menu the build fails because it runs WSL from a Windows CMD terminal using backslashes to separate folder names instead of forward slashes. 

Example:
I have a repo cloned in Windows with multiple folders each containing Dockerfiles (C:\Users\myuser\repo, with projects p1, p2, p3, etc.). I have a Dockerfile from p1 open in VSCode and want to build. I right click, click build image and it runs the following command:
C:\Windows\System32\wsl.exe -e docker build -f "p1\Dockerfile" p1

This fails seemingly because of the backslash:
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount424337585/p1\Dockerfile: no such file or directory

If I rerun the whole command in CMD replacing the backslash with a forwardslah, it works fine. Also, if I open a WSL2 terminal and run docker build -f "p1/Dockerfile" p1 (from within the repo folder) it also works. It seems the plugin should use file separators based on the target docker installation (in this case, Unix file separator '/'). 

Extension version: 1.9.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.85GB free)|
|Process Argv|C:\\Users\\zzumbo\\svn\\CHI-Docker-Images --crash-reporter-id 9b6e6509-b99e-4496-8f76-d7158aec7ab2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2807)|
|Memory (System)|6.09GB (0.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspyt653:30244269
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
vstry914:30250197
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt875:30251590

```

</details>

**Comment by bwateratmsft** [comment]
It depends on the shell running the command, not necessarily on the OS. Since you have WSL configured as the shell this occurs. I'd recommend leaving the default PowerShell as the shell.

**Comment by zzumbo** [comment]
Right, that makes sense to me. Switching the shell to Powershell or CMD does work in this case, but that doesn't really seem to fix the issue, it's just a workaround, plus then I'd have to use Powershell/CMD as default which isn't what I'd want in this case. I was saying if WSL is configured as shell then when CMD executes wsl.exe -e it should provide arguments in terms that WSL can understand. Is that not a bug?

**Comment by bwateratmsft** [comment]
Right, we'd have to determine the shell from VSCode and figure out what path separator should be used. Unfortunately there are a huge number of options...cmd, powershell, WSL, git bash, real bash, sh, zsh, I'm sure many others...

Another alternative would be to take advantage of [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) and use remoting to host your code within WSL; from there the build should work normally as if it was being done in bash on Linux.

**Comment by bwateratmsft** [comment]
I'm going to close this issue for now; there haven't been other instances and doing the CLI detection would be extremely challenging + intelligence.
