### ISSUE TITLE
Error Add Docker Compose Files to Workspace

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode-docker#2696]
Does this occur consistently? Yes
Repro steps:

1. Shift-Command P
2. Type Compose and choose Add Docker Compose Files ...
3. Choose Workspace Folder
4. Select Application Platform: .Net ASP.Net Core 
5. Select Operating System: Linux
6. Choose default ports (80, 443)
7. Observe popup alert: An error has occured. Check output window for more details.
8. Observe text in output window
Action: vscode-docker.configureCompose
Error type: 1
Error Message: Process 'dotnet build /r:false /t:GetProjectProperties /p:C...' exited with code 1
Error: 

Note: This does not occur when choosing another Application Platform such as Node. 

dotnet --version
2.2.401

Version: 1.9.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:114908
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by karolz-ms** [comment]
@dfdumaresq do you see any continuation of the error message after "`'dotnet build /r:false /t:GetProjectProperties /p:C...' exited with code 1` "? 

Can you build the project from command line (`dotnet build`)?

**Comment by dfdumaresq** [comment]
@karolz-ms Yes, I can build the project from the command line. 

Here is the complete output:
```The Docker extension will try to connect to 'unix:///var/run/docker.sock', via context 'default'.
Error: Process 'dotnet build /r:false /t:GetProjectProperties /p:C...' exited with code 1
Error: ```

**Comment by dfdumaresq** [comment]
@karolz-ms I tried it again this morning and it's working now. I'm not sure what changed.

**Comment by bwateratmsft** [comment]
Strange. Glad it's working now though--let us know if you encounter further issues!

**Comment by dfdumaresq** [comment]
Will do. Thanks!
