### ISSUE TITLE
'docker' is not recognized as an internal or external command from VS CODE

### ISSUE THREAD

**Issue by lakshmisivareddy** [Microsoft/vscode-docker#270]
Hi  i am getting the below error when i am trying to load the module to docker with the below command 

docker build  --rm -f "d:\WorkSpace\FilterModule\Dockerfile.amd64" -t xxx.azurecr.io/filtermodule:0.0.1-amd64 "d:\WorkSpace\FilterModule" && docker push xxx.azurecr.io/filtermodule:0.0.1-amd64
'docker' is not recognized as an internal or external command,
operable program or batch file

**Comment by chrisdias** [comment]
@lakshmisivareddy  sorry about this.  usually this means the extension didn't load properly, and usually that is a result of a "corrupt" installation/update.  The best course of action is to uninstall and reinstall.

Can you open the dev tools in VS Code and see if there are any errors in the console? Press `F1`, search for `Developer: Toggle Developer Tools`, and then look in the console. Report that information back here.

Then, most likely you will need to do a hard reinstall of the extension. Press `F1` then search for `Developer: Reinstall Extension`, then pick the `Docker` extension, reload.

Here are a couple of related issues:  #262 and #257.

**Comment by lakshmisivareddy** [comment]
Hi @chrisdias thanks for the support

**Comment by AzureLu** [comment]
Hi @chrisdias I got the same issue and even the reinstall not work. My OS is windows, dose this matter?

**Comment by chrisdias** [comment]
@AzureLu sorry about this. No, it should not matter that you are on Windows.  

Can you see if anything is in the console (see above [comment](https://github.com/Microsoft/vscode-docker/issues/270#issuecomment-391228466)).

And, to confirm, you did a "hard" uninstall/reinstall of the extension?   Press `F1` then search for `Developer: Reinstall Extension`, then pick the Docker extension, reload.

Let me know what you find.

**Comment by StephenWeatherford** [comment]
Closing due to lack of response. Please feel free to reopen with new information, thanks.
