### ISSUE TITLE
Extension: Docker links not click- or copyable

### ISSUE THREAD

**Issue by ai-bits** [microsoft/vscode-docker#2703]
Latest VS Code and Docker extension as of today on up-to-date Ubuntu 18.04
In the description the "Working with container" et al links neither ^click- nor copyable.

Thanks
G.

**Comment by bwateratmsft** [comment]
@ai-bits does this occur for any other extensions? I was not able to reproduce the issue.

**Comment by ai-bits** [comment]
A double sorry from my side. 1) for overlooking your reply and taking so long and 2) that I can´t repro it neither on Ubuntu 18.04 nor 20.04 nor on Mac nor on two Windows 10 machines.
May have been on an Ubuntu on an USB stick I stopped using, but I guess you can disregard this exception.

Hope my diversity lab makes you smile! Cudos for Code!
Cheers
G.

**Comment by bwateratmsft** [comment]
No problem!
