### ISSUE TITLE
Error when scaffolding

### ISSUE THREAD

**Issue by Rezegmushtaha** [microsoft/vscode-docker#2704]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: Unable to write into the launch configuration file. Please open it to correct errors/warnings in it and try again.

Version: 1.9.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
k.reject workbench.desktop.main.js:5856:265
file:/workbench.desktop.main.js:5860:267
async k.doWriteConfiguration workbench.desktop.main.js:5853:403
```

</details>

**Comment by bwateratmsft** [comment]
@Rezegmushtaha can you add repro steps?
