### ISSUE TITLE
The running container is not removed from the "CONTAINERS" node after restarting debugging

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2706]
**OS:** All
**Build Version:** 20210204.1

**Repro Steps:**

1. Create an Express App project and open it in VS Code -> Command Palette -> Add Docker files to workspace -> Node.js -> Enter port.
2. Debug -> Stop debugging -> The running container is removed from the "CONTAINERS" node.
3. Debug -> Restart debugging -> Stop debugging.
4. Check whether the running container is removed.

**Expect:**
The running container is removed from the "CONTAINERS" node.

**Actual:**
The running container is not removed from the "CONTAINERS" node.

**More Info:**
This issue also reproduces for .NET Core/Python project.

**Comment by bwateratmsft** [comment]
Probably related to #2676 or maybe a dupe, so I'll mark this for 1.11.0.

**Comment by bwateratmsft** [comment]
Turns out this is external same as #2676. It might be the same bug or closely related. Resolving this as external, to https://github.com/microsoft/vscode/issues/117984.
