### ISSUE TITLE
The running container time doesn't refresh automatically when executing "Compose Task" again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2712]
**OS:** All
**Build Version:** 20210204.1

**Repro Steps:**

1. Create a Project -> Add Docker files and including Compose files.
2. Add a compose up task and down task into the .vscode/tasks.json file as below.(update the "services" and "scale" parameters)

>         {
>             "type": "docker-compose",
>             "label": "My Docker Compose Up task",
>             "dockerCompose": {
>                 "up": {
>                     "detached": true,
>                     "build": true,
>                     "scale": {
>                         "backend": 1
>                     },
>                     "services": [
>                         "backend"
>                     ]
>                 },
>                 "files": [
>                     "${workspaceFolder}/docker-compose.yml",
>                     "${workspaceFolder}/docker-compose.debug.yml"
>                 ]
>             }
>         },
>         {
>             "type": "docker-compose",
>             "label": "My Docker Compose Down task",
>             "dockerCompose": {
>                 "down": {
>                     "removeVolumes": false,
>                     "removeImages": "local"
>                 },
>                 "files": [
>                     "${workspaceFolder}/docker-compose.yml",
>                     "${workspaceFolder}/docker-compose.debug.yml"
>                 ]
>             }
>         }

3. F1 -> Choose "Tasks: Run Task" -> Choose "My Docker Compose Up task" -> Display a running container.
4. Repeat steps: F1 -> Choose "Tasks: Run Task" -> Choose "My Docker Compose Up task".
5. Check whether the running container time refreshes automatically.

**Expect:**
The running container time refreshes automatically.

**Actual:**
The running container time doesn't refresh automatically.
![image](https://user-images.githubusercontent.com/62053665/107457949-0ea2a400-6b8e-11eb-9f17-5695d0bd04c1.png)

**Comment by bwateratmsft** [comment]
Looks like this is actually a pretty old issue; I rolled back to 1.4.0 and it was present there too. The timestamp doesn't get corrected until manually clicking "Refresh".

**Comment by v-mengwe** [comment]
Verified on the latest build 20210714.2, this issue reproduces, so reopen it.

**Comment by dbreshears** [comment]
This should be resolved when we resolve #2983
