### ISSUE TITLE
Request: Display a "Use" button when hovering context

### ISSUE THREAD

**Issue by csmarttemplates** [microsoft/vscode-docker#2719]
Requiring a right click is clunky way to access the use action (and inspect for that matter).
It would be nicer if when you hover a context a "Use" button would be displayed the same way as the Pencil icon is shown to the right of the text label when you hover a breakpoint in the debug view.

<img width="418" alt="Screen Shot 2021-02-10 at 12 40 20 PM" src="https://user-images.githubusercontent.com/51419311/107569432-26355900-6b9d-11eb-8288-e2d03f0bfffb.png">

Would be nicer if there was an icon like the pencil below. It would save a click!

<img width="451" alt="Screen Shot 2021-02-10 at 12 39 38 PM" src="https://user-images.githubusercontent.com/51419311/107569353-0c941180-6b9d-11eb-8628-f30bf838a4c2.png">

**Comment by bwateratmsft** [comment]
I think this would be possible using a view item icon, which is what is present there in the breakpoints list.

@csmarttemplates we would need to use an icon from VSCode's [Codicons list](https://microsoft.github.io/vscode-codicons/dist/codicon.html). From there I was thinking maybe "play", "debug-start", or "check", but I'm definitely open to other ideas. Can you check out that icon list and see if any seem like a good fit to you?

**Comment by csmarttemplates** [comment]
I think I like "check" the most. "play" and "debug-start" are good but might be a little confusing since it implies something is being started rather than selected.

**Comment by ucheNkadiCode** [comment]
Ideas of implementation:
The socket Icon will continue to show that a context is currently in use
On Hover: Display an icon (likely the check icon from vscodicons) the user can click to use that context. The user can still right click to either select inspect or use.
If that context is already being used, the check icon will not be displayed.

**Comment by bwateratmsft** [comment]
This change is now released with Docker extension version 1.12.0.
