### ISSUE TITLE
Unable to sign into GitLab's Container Registry with personal access token

### ISSUE THREAD

**Issue by timothyfroehlich** [microsoft/vscode-docker#2723]
I am attempting to sign into my project's Container Registry in Gitlab, but all attempts result in `Failed with code "401"`. 

My account uses MFA and I have been able to successfully log in with `docker login` using a personal access token with the correct permissions. However, attempting to use the token as the "password" in Visual Studio Code's Docker Extension's Registries tab just results in the 401. 

According to the documentation (https://docs.gitlab.com/ee/api/oauth2.html#resource-owner-password-credentials-flow) users with two-factor authentication must use the a different authorization method with the personal access token as described here (https://docs.gitlab.com/ee/api/oauth2.html#access-gitlab-api-with-access-token). 

I believe a second code path here (https://github.com/microsoft/vscode-docker/blob/master/src/tree/registries/gitLab/GitLabAccountTreeItem.ts) would need to be added to directly use the token vs trying to POST the password to /oath/token.

**Comment by karolz-ms** [comment]
I believe we have a fix already and will be releasing it pretty soon: https://github.com/microsoft/vscode-docker/pull/2689

**Comment by bwateratmsft** [comment]
@karolz-ms is right on! @timothyfroehlich we are probably going to release that today.
