### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by snm501** [microsoft/vscode-docker#2726]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SHUBHA~1\AppData\Local\Temp\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@snm501 does this happen consistently?
