### ISSUE TITLE
Gockerfailed to Load

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/vscode-docker#2728]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: EPIPE
Error Message: write EPIPE

Version: 1.10.0
OS: linux
OS Release: 5.4.72-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
afterWriteDispatched stream_base_commons.js:154:25
writeGeneric stream_base_commons.js:145:3
Socket._writeGeneric net.js:786:11
Socket._write net.js:798:8
doWrite _stream_writable.js:403:12
writeOrBuffer _stream_writable.js:387:5
Socket.Writable.write _stream_writable.js:318:11
extension.bundle.js:16:96494
spawnAsync extension.bundle.js:16:95444
Object.execAsync extension.bundle.js:16:97856
extension.bundle.js:672:83061
D._withProgress remoteExtensionHostProcess.js:86:28630
D.withProgress remoteExtensionHostProcess.js:86:28384
Object.withProgress remoteExtensionHostProcess.js:94:29629
Object.logInToDockerCli extension.bundle.js:672:82821
async pullImages extension.bundle.js:1053:102536
async pullImageFromRepository extension.bundle.js:1053:103024
```

</details>

**Comment by karolz-ms** [comment]
@Dmarch28 can you describe what you did before the error occurred (repro steps)? Can you reproduce consistently?

**Comment by Dmarch28** [comment]
Placed Docker within container of Visual Studio Code

**Comment by karolz-ms** [comment]
@Dmarch28 not sure I understand. Do you mean you tried to [attach Visual Studio Code to a running container](https://code.visualstudio.com/docs/remote/attach-container)?
