### ISSUE TITLE
Interaction with Windows Container in Docker preventing certificate import

### ISSUE THREAD

**Issue by pabloro76** [microsoft/vscode-docker#2734]
Trying to install a certificate in a Windows container via PowerShell and receiving the following errors:

repro:
From VS code, connect to container --> docker exec -it containrName "powershell"
use commands interactively import pfx certificate with pwd from VS code UI 
$pfx.import($certPath,$pfxPass,"Exportable,PersistKeySet") 
$store = New-Item -Path cert:\LocalMachine\CustomStore
$store.open("MaxAllowed") 
$store.add($pfx) 
$store.close()

Exception calling "Import" with "3" argument(s): "The specified network password is not correct.
same code above executed within a file inside container fails with similar error

**Comment by bwateratmsft** [comment]
This doesn't sound like a bug with the extension though? I'm not sure what's expected here.

**Comment by pabloro76** [comment]
Has the extension been tested while trying to install a .pfx certificate on a windows container? 
I'm questioning the way a SecureString is parsed as error indicates the password is not correct, while it is

**Comment by bwateratmsft** [comment]
I don't think I see how the extension is involved when running PowerShell commands in a terminal attached to a Windows container.

**Comment by pabloro76** [comment]
The commands are being executed from VSCode using the extension to interact with the container

**Comment by bwateratmsft** [comment]
Once you've attached a terminal the extension is no longer involved, it's just like you were running it directly from command line.
