### ISSUE TITLE
Attach Visual Studio Code to Windows container errors

### ISSUE THREAD

**Issue by 41GitHub** [microsoft/vscode-docker#2736]
Is it possible to Attach to a Windows container?

### Issue
Right click on a Windows Container -> Attach Visual Studio Code
failure in Windows system call: The user name or password is incorrect.

**Comment by bwateratmsft** [comment]
The "Attach Visual Studio Code" functionality is actually provided by the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. You can create an issue in their repo here: https://github.com/microsoft/vscode-remote-release
