### ISSUE TITLE
Unable to pull an image, even though I've connected OK

### ISSUE THREAD

**Issue by simonl65** [microsoft/vscode-docker#2737]
Does this occur consistently? Yes

Repro steps:
1. Right mouse click on an image under REGISTRIES 
2. Click on Pull Image

Actual result:
Permission denied error (even though I've connected to Docker Hub OK - as evidenced by the fact that I've picked from a list of my images)

Expected result:
Image is pulled

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "---65" --password-stdi...' exited with code 1
Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.10.0
OS: linux
OS Release: 5.8.0-44-generic
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:96377
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by simonl65** [comment]
This would appear to be due to VSCode running as a "normal" user. If I run VSC as a root user the problem goes away - albeit with warnings from VSC complaining about being run as root!

I'd rather not have to run as root, so can this be fixed?

**Comment by simonl65** [comment]
Oh, maybe related to #112 from 2017?

**Comment by PavelSosin-320** [comment]
@simonl65 VSCode has nothing to do with the fact that the Docker user has to be either root either belong to the group Docker or your Docker must be the very recent Docker CE version 20.10.  Otherwise, the permissions of rootless users are not enough to access  docker.sock. You can pick one of the solutions.

**Comment by simonl65** [comment]
Done. Thanks.
