### ISSUE TITLE
Update wording of Python Scaffolding

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2747]
``` dockerfile
# Creates a non-root user and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN useradd appuser && chown -R appuser /app
USER appuser
```
Through the changes made from [Issue 2724](https://github.com/microsoft/vscode-docker/issues/2724), I want to make appuser lines more clear in the Dockerfile. The Document title has also changed so the link must change to reflect.

**Comment by ucheNkadiCode** [comment]
Based on our meeting, there are minor changes that need to be made to incorporate @TheYarin feedback

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN useradd -u 5678 appuser && chown -R appuser /app
USER appuser

**Comment by bwateratmsft** [comment]
I'll use #2724 to track this change in the scaffolding
