### ISSUE TITLE
Implement Authentication Provider API for Docker Hub registry auth

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2753]
The [Authentication Provider API](https://code.visualstudio.com/api/references/vscode-api#authentication) has been finalized, so we should look into using it for registry auth.

Also, we should register an authentication provider for Docker Hub, if possible, which would allow other extensions to take advantage of it (with user's permission, of course).

**Comment by bwateratmsft** [comment]
Related to / dependent on #2033

**Comment by bwateratmsft** [comment]
Related to #2975; probably #2975 needs to be done as part of this.

**Comment by bwateratmsft** [comment]
Unfortunately, it looks like (at least right now), this is impractical for us. Was reading up on [here](https://docs.docker.com/docker-hub/2fa/#enable-two-factor-authentication), where toward the end of the doc it states:

> **Note:** Now that you have two-factor authentication enabled on your account, you must create at least one personal access token. Otherwise, you will be unable to log in to your account from the Docker CLI. See [Managing access tokens](https://docs.docker.com/docker-hub/access-tokens) for more information.

Consequently, in order to function as a more general auth provider, we'd have to share to the caller either the personal access token (bad) or the password (worse). Even if the user consents to an extension accessing that I don't think I'd be willing to go that route.

We could do auth specifically for Docker Hub, via the `/v2/users/login` endpoint, but that would not support MFA or the CLI, so I think is of only marginal use.

**Comment by bwateratmsft** [comment]
Need to work out what scopes we should define. Password auth gives a scope of "" (empty string) and appears to have full permissions. Using a PAT can yield one of the following four scopes: `repo:admin`, `repo:write`, `repo:read`, `repo:public_read`, in descending order of access. More here: https://docs.docker.com/docker-hub/api/latest/#tag/access-tokens

Also, it seems like the scope accepted by the auth provider needs to contain a hint as to what username to log in with, unless we want to support only single-user (which is less than what the registries feature supports, which allows multiple Docker Hub sign-ins).

**Comment by dbreshears** [comment]
Closed as not planned
