### ISSUE TITLE
Use project name in Compose commands in the Container panel

### ISSUE THREAD

**Issue by petergloor** [microsoft/vscode-docker#2755]
Issue Type: <b>Feature Request</b>

Whenever I start a project using _Docker: compose up_  from the command palette (ctrl+shift+P) it starts a project using the name of the directory that contains the docker-compose.yml file. The name of this project appears in the **Containers** panel. A right mouse click provides the commands **Compose Logs**, **Compose Restart** and **Compose Down**. So far this works fine.

However, in case I start `docker compose -p <project name> up` using an alternative project name from a Terminal window, the project name will be the one provided with the -p parameter and not the projects directory name. 

In this case the **Compose commands** in the **Containers** panel will fail, because the parameter -p with the right project name is missing in the docker-compose command executed under the hood.

Note: of course it's always possible to execute the commands from a terminal window, but especially when using remote contexts it would be nice if the commands would be available.

Extension version: 1.10.0
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic
Remote OS version: Linux x64 5.4.0-66-generic

**Comment by petergloor** [comment]
Using Inspect on the containers, the project name can be found in the Config/Labels section:

    {
    "Config": {
        "Labels": {
            "com.docker.compose.project": "<project-name>",
        }
    }

**Comment by bwateratmsft** [comment]
Related to (but not the same as) #2633

**Comment by bwateratmsft** [comment]
Should be straightforward to fix, as @petergloor points out the project name is available from the label `com.docker.compose.project` and can be applied unconditionally (i.e. using `-p <the name>` works even in the "normal" case where the project is started without `-p <name>`).

**Comment by BigMorty** [comment]
Love it, thanks @petergloor!!!

**Comment by bwateratmsft** [comment]
This fix is now released with Docker extension version 1.12.0.
