### ISSUE TITLE
🐛 Regression? Linter warning: WORKDIR paths should be absolute

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/vscode-docker#2756]
In VSCode, I'm receiving a linter warning in my project's `Dockerfile`:

```
WORKDIR paths should be absolute
```

Looks like this was previously an issue here: https://github.com/microsoft/vscode-docker/issues/1492

* VSCode 1.54.1
* Microsoft Docker Extension 1.10.0
* Windows 10 Dev Preview build 21327

![image](https://user-images.githubusercontent.com/466713/110211351-71b4ed00-7e53-11eb-8aaf-91f3b9f7da22.png)

**Comment by rcjsuen** [comment]
@pcgeek86 Thanks for the bug report.

Looks like this is because the `WORKDIR` instruction is written in the JSON format. `/app/` or `"/app/"` should work for you as a temporary workaround.

**Comment by rcjsuen** [comment]
@pcgeek86 Note that `WORKDIR` instructions don't accept JSON as a valid format. Did you copy/paste this from somewhere?

**Comment by pcgeek86** [comment]
I created this myself. I didn't realize that wasn't valid syntax for this particular instruction. Makes sense though, considering that `WORKDIR` should be a singleton string, and wouldn't make sense as an array value. I've just always done it that way before. Cheers!
