### ISSUE TITLE
"Failed to connect. Is Docker installed?" when running a Dev Container

### ISSUE THREAD

**Issue by nathanjwtx** [microsoft/vscode-docker#2759]
I have been testing out the MS `Node.js & TypeScript` container for a project. When I am in the container I get an extension recommendation to install this Docker extension. However, after installing, and with the Dev Container running, I get `Failed to connect. Is Docker installed?` This **only** happens when running the Dev Container. The extension detects my Docker containers and images, and will run commands in the integrated terminal, when not running a Dev Container.

I can run Docker commands from both WSL2 instances. Ubuntu was a fresh install today to try and rectify this issue.

I have tried this on both versions of VS Code. I also have the extension installed globally; not sure if this causes conflicts?

Windows 10: 10.0.19042 Build 19042
Docker Desktop 3.2.1
Running WSL2 with Debian and Ubuntu
Extension version: 1.10.0

Let me know if I need to provide additional info.

**Comment by karolz-ms** [comment]
Does `docker` command work from WSL2 command window? Did you enable Docker for your WSL2 distribution? (go to Docker Desktop settings UI | Resources | WSL Integration and make sure your distribution is "enabled")

**Comment by nathanjwtx** [comment]
HI. Yes, I can run `docker` from both Ubuntu and Debian terminals. 
![image](https://user-images.githubusercontent.com/1558027/110390188-38cf7080-802b-11eb-97ba-0e108930f3b1.png)

![image](https://user-images.githubusercontent.com/1558027/110390254-50a6f480-802b-11eb-8f56-4406d6f4cda7.png)

**Comment by karolz-ms** [comment]
OK, sorry, I did not fully realize it is about a dev container, my bad. Are you mounting the Docker socket into the devcontainer like [described here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#enabling-root-user-access-to-docker-in-the-container)?

**Comment by nathanjwtx** [comment]
I wasn't, but now I'm getting:
`Error: connect EACCES /var/run/docker.sock`

**Comment by nathanjwtx** [comment]
I can run `docker` from the built-in terminal inside the dev-container now though

**Comment by karolz-ms** [comment]
You probably want to [follow the remaining instructions](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#enabling-non-root-access-to-docker-in-the-container) from the repo I referenced earlier.

**Comment by nathanjwtx** [comment]
thank you for your help with this!

**Comment by bwateratmsft** [comment]
It sounds like everything is working now? I'll close this but please let us know if you encounter any more issues!
