### ISSUE TITLE
An error occurs when building the image for the simple-go-web-app-master project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2764]
**OS:** All
**Build Version:** 20210309.2

**Repro Steps:**

1. Open the simple-go-web-app-master project in VS Code.
2. F1 --> Click "Docker: Add Docker Files to Workspace..." --> Select "Go" as application platform --> Keep default 3000 as the port.
3. Right click on Dockerfile file --> Select "Build Image...".
4. Check whether build the image successfully or not.

**Expect:**
Build the image successfully without any error.

**Actual:**
An error occurs when building the image.
![image](https://user-images.githubusercontent.com/57662131/110604406-048eb800-81c3-11eb-93c7-3c2406af6dd4.png)

**Comment by karolz-ms** [comment]
We should make the app use modules if it does not. Pretty much the whole Go world switched to modules by now. LMK if you need help with this.

**Comment by bwateratmsft** [comment]
I know absolutely nothing about Go so I'd be happy to accept help. :smile:

**Comment by karolz-ms** [comment]
We need to update the testcase to use a more modern app. The sample app the testcase currently uses has not been updated for 3 years.

**Comment by karolz-ms** [comment]
Testcase updated
