### ISSUE TITLE
h1

### ISSUE THREAD

**Issue by VMikhailW** [microsoft/vscode-docker#2768]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "vegass" --password-stdin' exited with code 1
Error: error during connect: This error may indicate that the docker daemon is not running.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/auth: open //./pipe/docker_engine: The system cannot find the file specified.

Version: 1.10.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:96377
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
@VMikhailW are you sure Docker Desktop is running?
