### ISSUE TITLE
The error message is not clear after executing compose actions with lower docker-compose version installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2769]
**OS:** Ubuntu 18.04
**Build Version:** 20210310.1

**Repro Steps:**
1. Make sure there is no docker-compose installed on the machine.
2. Install docker-compose using this command "sudo apt install docker-compose" and check its version.
![image](https://user-images.githubusercontent.com/45614674/110765217-edb59780-828e-11eb-9544-3ac9dcb94e6b.png)
3. Right click docker-compose.yml and execute "Compose Up" action.
4. Navigate to Docker view -> Right click the container group and select "Compose Logs/Compose Restart/ Compose Down".
5. It will pop up an error.
6. Check whether the error message is clear or not.

**Expect:**
The error message is clear, such as "Docker-compose version is lower than expected, please update the docker-compose version".

**Actual:**
The error message is not clear.
![image](https://user-images.githubusercontent.com/45614674/110765745-746a7480-828f-11eb-9079-23c364b12e95.png)

**More Info:**
The error will disappear after installing the docker-compose 1.28.5 refer to https://docs.docker.com/compose/install/.

**Comment by bwateratmsft** [comment]
I see the issue; there are labels we expect missing due to the old Compose version.

**Comment by bwateratmsft** [comment]
Not likely to impact many users.
