### ISSUE TITLE
[Suggestion] Add commands "Compose Logs" in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2770]
**OS:** Ubuntu 18.04
**Build Version:** 20210310.1

**Repro Steps:**
1. Right click docker-compose.yml file and execute "Compose Up" action.
2. Navigate to Docker view -> Right click the container group and check its menu.
![image](https://user-images.githubusercontent.com/45614674/110766951-b0520980-8290-11eb-9ea6-5cedfad0e444.png)
3. F1 to check whether these commands are in command palette or not.

**Actual:**
These commands don't exist in command palette.

**Suggestion:**
Add commands "Compose Logs/Compose Restart/ Compose Down" in command palette.

**Comment by bwateratmsft** [comment]
Restart and Down are available in the palette, albeit with slightly different names ("Docker: Compose Restart" and "Docker: Compose Down"). Logs is not, we should consider adding that.

**Comment by v-ruizh** [comment]
@bwateratmsft The commands "Docker: Compose Restart" and "Docker: Compose Down" in the command palette you mentioned above is for docker-compose.yml or docker-compose.debug.yml, but the one I mentioned is for Container group. 

When I try to executing "Docker: Compose Restart" and "Docker: Compose Down" commands, it require one project folder opening which contains docker-compose.yml file, we can select the docker-compose.yml file to continue this action.

But I can right click container group and executing "Compose Restart/ Compose Down" without any folder opening. 

I guess they may be difference. Could you help to confirm this?

**Comment by bwateratmsft** [comment]
Ah yes, you are totally right. Fixing the title.

**Comment by bwateratmsft** [comment]
Unfortunately there is no good way to handle the user experience of showing the "Down" and "Restart" commands in the palette, since there are already such commands but targeted to files instead of compose projects. Users would see two of the same command and we couldn't really explain how they were different.

Logs is a new command, so it is possible to work it this way. Updated the title.

**Comment by bwateratmsft** [comment]
This fix is now released with Docker extension version 1.12.0.
