### ISSUE TITLE
[Codespaces] The repository isn't removed after deleting the image

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2772]
**OS:** **Remote Codespaces**
**Build Version:** 20210311.1

**Repro Steps:**

1. Create a Azure registry -> Push an image to the Azure registry.
2. Expand the Azure registry -> Right click the image -> Select "Delete Image...".
3. Refresh the Azure registry -> Check whether the repository is removed.

**Expect:**
The repository is removed after deleting the image.

**Actual:**
The repository isn't removed after deleting the image.
![reg](https://user-images.githubusercontent.com/62053665/110915733-fc658280-8352-11eb-96ca-5178bdbd6fd6.gif)

**Comment by bwateratmsft** [comment]
I was partly able to repro--after the first delete, the node doesn't disappear (by design). However, after I refreshed, it does disappear.

@v-mengwe does this happen consistently, where refreshing doesn't cause it to disappear?

**Comment by v-mengwe** [comment]
Thanks for your sharing, this issue doesn't reproduce for now, so close it.
