### ISSUE TITLE
An error "The resource namespace 'Microsoft.ContainerRegistry' is invalid" exists in the Azure Germany subscription node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2776]
**OS:** Win 10
**Build Version:** 20210312.1
**Docker Desktop:** 3.2.1 (61626)

**Repro Steps:**
1. Sign in with Azure Germany account.
2. Navigate to "Registries view" and expand the Azure Germany Subscription node.
3. Check if there is an error in the Azure Germany Subscription node.

**Expect:**
There is no error in the Azure Germany Subscription node.

**Actual:**
An error "The resource namespace 'Microsoft.ContainerRegistry' is invalid" exists in the Azure Germany Subscription node.
![image](https://user-images.githubusercontent.com/45614674/111124471-8445c980-85ab-11eb-9883-769bf4699c03.png)

**More Info:**
This issue does not reproduce in Azure China Subscription node.

**Comment by bwateratmsft** [comment]
Looks like ACR is not supported in Germany:

![image](https://user-images.githubusercontent.com/36966225/111173685-3c0fb280-857d-11eb-89a6-bf42bb88d5b7.png)

**Comment by karolz-ms** [comment]
Correct, is is (not so) well-known Azure Germany limitation
