### ISSUE TITLE
Error Loading image list from Nexus docker registry

### ISSUE THREAD

**Issue by seldad8** [microsoft/vscode-docker#2778]
It was able to pull a partial list, but generated this error when I selected "Load More..." at the bottom of the list.

Does this occur consistently? Yes or No
Repro steps:
1.  In Docker extension, Connect to Generic Docker Registry
2. Load the list of available images (Only gets a partial list since it's very long)
3. Select "Load More..." at the bottom and this error is generated.

Action: vscode-docker.registries.loadMore
Error type: 404
Error Message: \n\n \n \n \n \n \n \n Nexus Repository Manager\n \n \n OSS 3.29.2-02\n \n \n [\"https://<my internal nexus server>\"]\n\n\n\n \n \n Error 404\n Not Found\n \n \n \n Not Found\n \n \n\n

Version: 1.10.0
OS: linux
OS Release: 3.10.0-1160.15.2.el7.x86_64
Product: Visual Studio Code
Product Version: 1.54.2
Language: en

<details>
<summary>Call Stack</summary>

```
new StatusCodeError extension.bundle.js:799:187948
Request.callback extension.bundle.js:799:186744
Request.RP$callback [as _callback] extension.bundle.js:799:185792
Request.o._callback.o.callback.o.callback extension.bundle.js:859:4496
Request.emit events.js:315:20
Request.<anonymous> extension.bundle.js:859:17623
Request.emit events.js:315:20
IncomingMessage.<anonymous> extension.bundle.js:859:16410
Object.onceWrapper events.js:421:28
IncomingMessage.emit events.js:327:22
endReadableNT _stream_readable.js:1220:12
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by bwateratmsft** [comment]
Might be an issue with pagination, we should take a look.

**Comment by bwateratmsft** [comment]
This is probably due to Nexus itself. I am not hitting any issues with other generic V2 registries, including Azure and the generic registry:2 image.
