### ISSUE TITLE
Docker failed to start

### ISSUE THREAD

**Issue by azmisecure** [microsoft/vscode-docker#2779]
I see error Docker failed to stop. 

Following is the message I get:

![image](https://user-images.githubusercontent.com/62207733/111202399-d574ae00-85e9-11eb-9b92-8a086861d3b5.png)

Please help me.

**Comment by bwateratmsft** [comment]
This would be an error in Docker Desktop, not in the VSCode extension. You can file issues in their repo here: https://github.com/docker/for-win
