### ISSUE TITLE
Docker page showed up randomly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-docker#2780]
![image](https://user-images.githubusercontent.com/323878/111229423-1bf2ea00-85a3-11eb-9490-2d761e88dd6c.png)

This just popped up randomly, I am not using the Docker extension right now and have not used it for a while

**Comment by bwateratmsft** [comment]
@roblourens We just updated the extension, so on activation it would have shown this. Any ideas what could have caused it to activate?

- Opening any YAML file
- Opening any Dockerfile
- Running any Docker commands (sounds unlikely)
- Opening the Docker explorer (sounds unlikely)

**Comment by roblourens** [comment]
Either an unrelated F5 or Run Task :(

**Comment by bwateratmsft** [comment]
I'll have to look back and see if we actually need `onDebugInitialConfigurations`, or if we can simply rely on `onDebugResolve:docker`. As far as tasks go, it would be nice if there was an analogue to `onDebugResolve`, like `onTaskResolve:docker-build` etc.
