### ISSUE TITLE
The error is not marked with a red background box when inputting an invalid ACR name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2781]
**VS Code Version:** **VS Code Insider 1.55.0-insider** (**Not reproduce** in **VS Code 1.54.2**)
**OS Version:** Wind 10
**Docker Extension Build:** 20210312.1

**Steps to Reproduce:**
1. Try to create a new Azure Container Registry with an invalid name.
2. Check the error.

**Expect:**
The error is marked with a red background box.
![image](https://user-images.githubusercontent.com/45614674/111250477-595d8300-8648-11eb-8b20-e2c3e2161735.png)

**Actual:**
The error is not marked with a red background box.
![image](https://user-images.githubusercontent.com/45614674/111250465-56629280-8648-11eb-9d47-04fccbd45a04.png)

**More Info:**
1. This issue does not reproduce in VS Code: 1.54.2.
2. https://github.com/microsoft/vscode/issues/118945.

**Comment by bwateratmsft** [comment]
I think this is actually external (VSCode). The validation is getting called, and the message appears, but the red border/background specifically is gone.

**Comment by bwateratmsft** [comment]
The VSCode issue was reopened, so closing this one.
