### ISSUE TITLE
desktop-disabling-repo-indicators

### ISSUE THREAD

**Issue by Sebastianokunkelo** [microsoft/vscode-docker#2783]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: ERR_INVALID_ARG_TYPE
Error Message: The "path" argument must be of type string. Received undefined

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
validateString validators.js:120:11
Object.basename path.js:671:5
PythonTaskHelper.provideDockerRunTasks extension.bundle.js:305:26172
extension.bundle.js:859:113177extension.bundle.js:859:113177
DockerDebugScaffoldingProvider.initializeForDebugging extension.bundle.js:859:113275
async DockerDebugScaffoldingProvider.initializePythonForDebugging extension.bundle.js:859:113012
async ScaffoldDebuggingStep.execute extension.bundle.js:65:263803
```

</details>

**Comment by bwateratmsft** [comment]
@Sebastianokunkelo can you add repro steps?
