### ISSUE TITLE
Restart container returns 500 error

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode-docker#279]
Using the restart container menu option returns the follow error, but I can issue `docker container start <mycontainer>` and it works fine.

(HTTP code 500) server error - Cannot restart container 0c81831da355d4e5319c9f73954b72aceba53127191f2b2d14c3c28398b7e9ec: container 0c81831da355d4e5319c9f73954b72aceba53127191f2b2d14c3c28398b7e9ec encountered an error during CreateContainer: failure in a Windows system call: The process cannot access the file because it is being used by another process. (0x20) extra info: {"SystemType":"Container","Name":"0c81831da355d4e5319c9f73954b72aceba53127191f2b2d14c3c28398b7e9ec","Owner":"docker","LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\0c81831da355d4e5319c9f73954b72aceba53127191f2b2d14c3c28398b7e9ec","Layers":[{"ID":"dfb0f8a5-8c6f-5766-8a2a-6dbf31407928","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c280f68d535881881344ffc8799f12a18515d4706d3e98fb49953947fce8596e"},{"ID":"edcaa0ca-22e0-584d-9601-fda922b49893","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d8a390361d1df7a4c029b6dfd634255dc9a3a4c9534163a5647efdc50afc3308"},{"ID":"fc03e24b-c991-535a-a50b-38f11099b8a1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2697015d2d30371a1b872fd4903b52df05b0ceb9fb7c26a884322f5dd0570289"},{"ID":"ab4a4f6a-2732-58aa-978e-195d2323e002","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5aece88dd76c919fbf6f7603e0d0e201bca27ef2ad4932f05dbf5e125d804322"},{"ID":"98c7e041-bf23-5169-986d-9de5aa4f8481","Path":"C:\\ProgramData\\Docker\\windowsfilter\\00388202f2237a8c21c65afb8217fa54f8ae739c1a0c06a9d38983c61dd68d17"},{"ID":"0511c952-3b2a-5db3-aebe-44ba4341d05c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6093f3bfb6085d32faedff1a0e707c4d9454a97a144224349ed92141932fb61e"},{"ID":"13ec7b8a-ebb3-57db-9675-ca6a4aa54dfa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\84c84d5a9eff6dbf66d9b2f7e78de5ff5f2036ff3e3f7e1a7e6c87ea04f6f2c2"},{"ID":"7376ff6f-5b8f-5d67-890f-ecf60982c649","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cb03af674b8df9390ef37c1f86450031a006d09a35a381eefbf527b64cdc5bd4"},{"ID":"6d98b925-5342-507e-b329-7ef9e2293584","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b4180d1cf8ef325807b5297e3c5c3eea4d89eb1c0ce4a020659d4e075b57942a"},{"ID":"7c37c681-9004-58ab-a922-07bbd380f1f3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9eab6901546e5205e638edf4eaf80177455f9ac6cd74753021f639bc0ffdcd9c"},{"ID":"6ffe3be7-1037-59e8-8c41-ddfb027909e4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1afcf66cb92e492fefc6a860a513a42e706c3dca8c2a7f1ae42bc0805a9a413c"},{"ID":"57c5d895-4fab-5f47-bf28-7e29a859cb6f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f43cb89a8660d6e603aaa68e294feeaef4609f107f0ec04930bd3359742c95ab"},{"ID":"d040554b-dd69-5218-a10d-d6a34f913b6e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\465df2db2540b3bea582e39e6b1afee28ef866c4be634ed01ed8ccc9991a57c0"},{"ID":"9600a2bd-1d60-5824-a4ae-b884563538aa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\76ba5f88c9a04c6ec223b034afd737d92001aec520e83faa164cac5fcbe612d5"},{"ID":"be37d759-9384-51e8-8d5f-ee5058d06afd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\14e71db57cdc8c2575a4050f95bc43a4183467ca05ab9312247e094858f098fc"}],"HostName":"0c81831da355","MappedDirectories":[{"HostPath":"c:\\sqlfiles\\sql12","ContainerPath":"c:\\sqlfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["9673bdf1-55c4-40b3-9bd2-f9e4db69ef5d"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\76ba5f88c9a04c6ec223b034afd737d92001aec520e83faa164cac5fcbe612d5\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}

**Comment by StephenWeatherford** [comment]
@wsmelton Does this repro consistently, or was it one time?  Thx.

**Comment by wsmelton** [comment]
Repeatable. Even after updates to VS Code and new containers being created still receive the same thing.

**Comment by StephenWeatherford** [comment]
Does this happen:
1) only for Windows containers?
2) only for containers which have stopped?

I see this behavior even with the command line
   docker restart <containerid>

… but only for Windows containers that are not running.  Also, what docker version?  Thx.

**Comment by StephenWeatherford** [comment]
https://github.com/docker/for-win/issues/2216

**Comment by wsmelton** [comment]
1. I only use Windows container so can't answer if the issue is with Linux or not.
2. No, I can restart a currently running container without any errors.

I get an error when trying to run docker restart on a stopped container, but not on one that is already running.

```
> docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssword12345" -p 1416:1433 -v C:\sqlfiles\sql16:C:\sqlfiles --name sql16 -d dbafromthecold/sqlserver2016dev:sp1
29536bdb41f3686bd13c399f3f67475361d06f90668989af634471b7a79d7886
07-17 08:17:24 C:\ [master ≡ +1 ~1 -0 !] 119ms
> docker restart sql16
Error response from daemon: Cannot restart container sql16: container 29536bdb41f3686bd13c399f3f67475361d06f90668989af634471b7a79d7886 encountered an error during CreateContainer: failure in a Windows system call: The process cannot access the file because it is being used by another process. (0x20) extra info: {"SystemType":"Container","Name":"29536bdb41f3686bd13c399f3f67475361d06f90668989af634471b7a79d7886","Owner":"docker","LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\29536bdb41f3686bd13c399f3f67475361d06f90668989af634471b7a79d7886","Layers":[{"ID":"1d9e8792-22d2-589c-a82f-d57bea9a3a6e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b74ff854e2ad8068655d8c3ef3287d8467d9cad867a5be21269a23dff5f7b35d"},{"ID":"e2d15b3b-3a9b-5837-a962-b33e128e822c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c6124d94daa506276fef9503ed5540f775228ae354ac747e9d825a7494c6a62e"},{"ID":"5e125797-a4b6-5d74-8673-454d2a2c374e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cd390fc5455efd94dd257ab7039fc24dc33e88ba7ffe8873b66fb76f9d8d78e1"},{"ID":"817c2830-e748-56f0-9459-54f82fd22cc3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\515b1305197a59a6ba05fe69e43f1d75adb8a3ccb69e7f20956c3807eb16cb1e"},{"ID":"9af09df0-4317-51c0-9be7-e05c0e3862e2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3b218ae463927b7d758f239cdcf9455c4f2979aeb142c2cb0676996dd34b3a19"},{"ID":"7a7afbef-e5f1-59e8-b2c2-734afe182686","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d5fa2ef320b076c339b2cfed288db4bd68753f3ede6c2c0e895dd26f4b71c6d6"},{"ID":"2829b8e2-945d-5a68-8ce4-53b047e1e632","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fc76e11a94063027a8a881988ed93981104d2091fe22e876bb92b33e201d1dd3"},{"ID":"337f4aca-d6c5-5f69-abb9-11307375bf26","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ba6087924b88fe24eaaa18ef8460f79ca7a6d80de6f4055e0ab18228293bfd07"},{"ID":"f4beb2e4-c9b1-548a-82b8-4fbb594b1b07","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ce2fdc41743fc46e55757050f05e470e51cca7d4350faa3195c9e953808c909b"},{"ID":"fbd9757a-c010-57e4-a351-94311cbf19fb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\464db99a89d5bfb1033476f0eed9497d2cfa7ef45870b3065a5cb1143be7031e"},{"ID":"7deca6aa-27eb-5508-80a8-bb9f414c0451","Path":"C:\\ProgramData\\Docker\\windowsfilter\\de97cefc89c44f867a070847fd532402b29b2fb8a075fb30487fca19445504a0"},{"ID":"fff6599a-9e8d-5c91-a01a-b6e5bd69ec56","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c292247858c6051159c6786757a187284b9542ec76f21d255a0d58654f562b26"},{"ID":"0654c2f0-e765-56c5-a73f-59d4cdec8a5f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a2917ffa2374b44749c70ba2f252026c8dd68560b24bf65d771a79f2563d9dab"},{"ID":"befd4313-8fa4-53bc-ba22-fd06bcbe13a4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\daf8fcaa39344f8806a6918bb048626c4fbd65a45fe06c15876320fdab89acca"},{"ID":"cd4f7ae2-82d3-5786-956a-ca8e26e325d8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cb24296e7541d751d32e516823f7e2db09e6bc7ba9ae826ee864065791864498"},{"ID":"27abb501-8e09-5452-99df-cea567a6d838","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3746392c172fead44b0deb6332aee3ae10d97ec3552cb97e3bb5850446ea1834"},{"ID":"28d8da87-fc41-574f-95fe-c6e68aa7756d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\790f4e1bf5ee0fab8f42b4439d277cc16fda0543df02ecdfa476d93ae5cdd72e"},{"ID":"232905f5-f6cf-58fc-8d61-fde1525abe3a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\62ab29b7cff8ed3d8b517aba97dfabd6579e41c856bed96a5a84acb9a85e8259"},{"ID":"be37d759-9384-51e8-8d5f-ee5058d06afd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\14e71db57cdc8c2575a4050f95bc43a4183467ca05ab9312247e094858f098fc"}],"HostName":"29536bdb41f3","MappedDirectories":[{"HostPath":"c:\\sqlfiles\\sql16","ContainerPath":"c:\\sqlfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["ba0e5b3b-0e42-43bb-9e6c-1ba42937fb75"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\62ab29b7cff8ed3d8b517aba97dfabd6579e41c856bed96a5a84acb9a85e8259\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
07-17 08:18:03 C:\ [master ≡ +1 ~1 -0 !] 147ms
> docker start sql16
sql16
07-17 08:19:47 C:\ [master ≡ +1 ~1 -0 !] 176ms
> docker restart sql16
sql16
07-17 08:20:49 C:\ [master ≡ +1 ~1 -0 !] 172ms
>
```

I'm on the edge release but have seen the same effects on the stable version as well:
![image](https://user-images.githubusercontent.com/11204251/42819964-97e2e438-899a-11e8-8d2c-d5f1686004be.png)

**Comment by StephenWeatherford** [comment]
Okay, thanks.  This is definitely a bug in docker.  I filed it as shown above, we'll see what they say.

**Comment by StephenWeatherford** [comment]
Still repros in 18.06.0-ce-win70 (19075)

**Comment by StephenWeatherford** [comment]
We should consider adding a "Start container"...
