### ISSUE TITLE
Cannot connect to docker from vscode

### ISSUE THREAD

**Issue by dean-azure** [microsoft/vscode-docker#2793]
Does this occur consistently? Yes
Repro steps:

1.Right click on repo
2.Pull Reposiitory

or

1   docker login --username "deanerling" --password [Redacted]

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "deanerling" --password-st...' exited with code 1
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.11.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
Are you able to pull images from the command line?

**Comment by dean-azure** [comment]
I'm able to connect, but even the most simplistic examples are failing:

from:

***@***.***/beginners-guide-to-use-docker-build-run-push-and-pull-4a132c094d75

c:\Code\tournament>docker build -t docker-whale .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM docker/whalesay:latest
latest: Pulling from docker/whalesay
Image docker.io/docker/whalesay:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
e190868d63f8: Extracting [==================================================>]  65.77MB/65.77MB                         909cd34c6fd7: Download complete                                                                                         0b9bfabab7c1: Download complete                                                                                         a3ed95caeb02: Download complete                                                                                         00bf65475aba: Download complete                                                                                         c57b6bcc83e3: Download complete                                                                                         8978f6879e2f: Download complete                                                                                         8eed3712d2cf: Download complete                                                                                         failed to register layer: re-exec error: exit status 1: output: Failed to safefile.OpenRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\6c62d6ae92b02d44329feb963c07b0014b33674846749f8689e39d1b3a6a3bea\usr\lib\perl\5.18.2\sys: Cannot create a file when that file already exists. (0x1f) usr\lib\perl\5.18.2\sys\


Cannot create a file when that file already exists. (0x1f)

The file doesn't exist.   This should not be this hard.



________________________________

**Comment by bwateratmsft** [comment]
Sounds like Docker is not in a good state. Try restarting Docker and/or your whole computer, and if that doesn't work, try reinstalling Docker altogether.

**Comment by dean-azure** [comment]
Uninstalling/reinstalling did resolve the issue.

Hours of grief the night before could have been saved had I tried this a day earlier.   😉

Thanks for your help.   The issue is resolved.

________________________________

**Comment by bwateratmsft** [comment]
Glad it's working now! Let us know if you encounter any further issues.
