### ISSUE TITLE
1

### ISSUE THREAD

**Issue by sollo11** [microsoft/vscode-docker#2797]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.runTask
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.11.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:22:662889
fulfilled extension.bundle.js:22:656828
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by bwateratmsft** [comment]
Same as #2662. Try restarting VSCode, there is a longstanding external issue causing this.
