### ISSUE TITLE
Facing issue during Docker file creation when specifying port number

### ISSUE THREAD

**Issue by Shah-Hassan-Khan** [microsoft/vscode-docker#2798]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configureCompose
Error type: 134
Error Message: Process 'dotnet build /r:false /t:GetProjectProperties /p:C...' exited with code 134
Error: 

Version: 1.11.0
OS: linux
OS Release: 5.8.0-45-generic
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
@Shah-Hassan-Khan can you try running the following in a terminal window and see what the output is?
```bash
dotnet build /r:false /t:GetProjectProperties /p:CustomAfterMicrosoftCommonTargets="~/.vscode/extensions/ms-azuretools.vscode-docker-1.11.0/resources/netCore/GetProjectProperties.targets" /p:CustomAfterMicrosoftCommonCrossTargetingTargets="~/.vscode/extensions/ms-azuretools.vscode-docker-1.11.0/resources/netCore/GetProjectProperties.targets" /p:InfoOutputPath="~/getprojectpropertiesoutput.txt" "<your .csproj file>"
```

If that fails please share the error message, otherwise please share the output it puts into `~/getprojectpropertiesoutput.txt`.

**Comment by Shah-Hassan-Khan** [comment]
Thanks for your response. I faced below issue

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: <NetCoreApi.csproj file>

**Comment by bwateratmsft** [comment]
Are you using the `<>` in the command line? They aren't needed, just there for explanatory purposes.
