### ISSUE TITLE
Docker extension does not show containers, images, etc. after changing context to remote machine

### ISSUE THREAD

**Issue by wvolkov** [microsoft/vscode-docker#2800]
**Visual Code:** Version 1.54.2
**Host OS:** Windows 10 2004
**WSL:** v2 Ubuntu 20.04
**Docker extension:** v1.11.0 (installed at WSL) 
**Docker:** for Windows version v1.19.7 installed with WSL2 compability.

**Issue :**

Docker extension doesn't show containers, images, networks, etc. while context is changed to a remote machine via ssh, nevertheless, commands like `docker ps` and `docker images ls` are working correctly on bash and returning results from a remote docker engine:

![image](https://user-images.githubusercontent.com/49549154/111880651-d036ab00-89bd-11eb-8adb-512c2751d867.png)

**Steps to reproduce:**
1. Install docker on windows, install docker extension for vs code
2. Activate ssh-agent on WSL Ubuntu with command `` eval `ssh-agent` ``
3. Add private key via command `ssh-add ~/path/to/private/key`
4. Create context: `docker context create new_context --docker "ssh://user@host:port"`
5. Change context via command palette `CTRL+SHIFT+P` -> `Docker Contexts: Refresh` -> `Docker Contexts: Use` -> `new_context`

**Expected behaviour:**
Extension lists remote containers, images, networks, volumes

**Actual behavior:**
Failed to connect. Is Docker running?

Again, I would like to highlight, that commands from WSL bash at Ubuntu with switched context are executed with success:
![image](https://user-images.githubusercontent.com/49549154/111880961-60292480-89bf-11eb-9f6e-0ff3e4626ee0.png)

Remote machine to which context is switched to is under Synology DSM os with installed docker of version 18.09 and Docker extension as well.

**Comment by bwateratmsft** [comment]
Does the issue persist after restarting VSCode or clicking "Refresh" on any of the panes?

**Comment by wvolkov** [comment]
Yes, problem persist. I have tried both refresh and `CTRL+SHIFT+P -> Developer: Reload Window`. Clicking refresh button doesn't help either.

**Comment by bwateratmsft** [comment]
Ok, I was able to reproduce something similar. Do you see this warning toast?
![image](https://user-images.githubusercontent.com/36966225/112022920-1cdacd00-8b09-11eb-907f-a36efc466fa8.png)

**Comment by bwateratmsft** [comment]
Update: I think I eventually figured out what was wrong, it seems like my ssh-agent was in a bad state or something. I killed the process, and had to manually delete `~/home/bwater/mysock`, but once I did that and restarted the agent and VSCode, all was well and I'm able to see resources again.

**Comment by wvolkov** [comment]
Yes, I can see a warning toast about SSH DOCKER_HOST.
As for error at developer tools I see a bit different:
![image](https://user-images.githubusercontent.com/49549154/112110552-1e1d0000-8bc4-11eb-9eea-8e5145ab4b6b.png)

`docker context ls`:
![image](https://user-images.githubusercontent.com/49549154/112110596-30973980-8bc4-11eb-8e42-562d84f0d53d.png)

`ssh-add -l` :
![image](https://user-images.githubusercontent.com/49549154/112110661-486ebd80-8bc4-11eb-8aa7-4b5a0f0166cc.png)

but it is worth to mention that in order to launch ssh-agent I need to perfrom `` eval `ssh-agent` `` once WSL is launched, otherwise it raises a different error:

`Could not open a connection to your authentication agent.`

**Comment by wvolkov** [comment]
as for `echo $SSH_AUTH_SOCK` in my case it is:

`/tmp/ssh-rifo6mS4mV9E/agent.316`

Should I configure in some other way? I tried to perform your suggested workaround changing sock to one at ~/mysock but that didn't help

**Comment by bwateratmsft** [comment]
Regarding that error "Cannot read property 'some' of undefined", I had that too, I fixed it with #2802.

If you're doing `eval \`ssh-agent ...\`` from a terminal in the WSL VSCode window, that explains the problem. With that approach, the environment variable `SSH_AUTH_SOCK` is not set for the VSCode process, only the terminal window.

It's not imperative to set it to a fixed value like `~/mysock`, but doing so lets the .bashrc script test to see if an agent is already running before creating a new one. What distro are you using where it won't assign a fixed socket? I've got Ubuntu.

**Comment by wvolkov** [comment]
I am using default Ubuntu distro:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

I have altered my `.bashrc` script with your suggested workaround and it worked as a charm. Now I can see every docker container and image from a remote context. Thank you!

To sum up, the problem was at sock of ssh-agent daemon? I didn't get  the real reason of that issue.

**Comment by bwateratmsft** [comment]
Glad it's working now!

The issue was that when you do `eval $(ssh-agent ...)` from within a terminal in the VSCode WSL window, then `SSH_AUTH_SOCK` gets set for that terminal window, but not for the VSCode process itself or the extension host processes. So the Docker extension was not able to see that value; as far as it knew the `SSH_AUTH_SOCK` variable was empty.

**Comment by Aisuko** [comment]
Same issue on my macOS Big Sur 11.2.3 

```
➜  vscode-dev-containers git:(feat/scheme) code --version                                                
1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64
```

<img width="1674" alt="Screen Shot 2021-03-29 at 7 51 15 PM" src="https://user-images.githubusercontent.com/8053949/112832759-5c388900-90c8-11eb-8c12-d13ee46a8a0b.png">

**Comment by Aisuko** [comment]
@bwateratmsft Hello sir, sorry to bother you, please help me out

**Comment by bwateratmsft** [comment]
@Aisuko please check out our docs on how to set up SSH tunneling: https://code.visualstudio.com/docs/containers/ssh

**Comment by Aisuko** [comment]
Thanks.
