### ISSUE TITLE
Extension host terminated Unexpectedly

### ISSUE THREAD

**Issue by nlarusstone** [microsoft/vscode-docker#2806]
Issue Type: <b>Bug</b>

I was getting the same error as https://github.com/microsoft/vscode/issues/114714, so I ran `Extension Bisect` and got the following:

`Extension Bisect is done and has identified ms-azuretools.vscode-docker as the extension causing the problem.`

Extension version: 1.11.0
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 9018034f-fec5-45d9-89cb-67558edd20d1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes516:30244333
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by bwateratmsft** [comment]
@nlarusstone Any information on what the crash is?

**Comment by nlarusstone** [comment]
Sorry, I think it might actually be a `Code` issue, not an extension issue. Re-ran bisect and it gave me:

```
Extension Bisect is done but no extension has been identified. This might be a problem with Code.
```

**Comment by bwateratmsft** [comment]
Gotcha. If you do see more crashes please let us know! We want to make sure things work well on M1.
