### ISSUE TITLE
ECONNREFUSED when opening start page

### ISSUE THREAD

**Issue by Seth1u** [microsoft/vscode-docker#2807]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:7080

Version: 1.11.0
OS: linux
OS Release: 5.4.72-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1141:16
```

</details>

**Comment by bwateratmsft** [comment]
This seems similar to https://github.com/microsoft/vscode/issues/95678, where a Webview fails to open due to ECONNREFUSED. @Seth1u does this happen consistently?
