### ISSUE TITLE
Failed to connect. Is Docker installed?

### ISSUE THREAD

**Issue by liu550** [microsoft/vscode-docker#2810]
Issue Type: <b>Bug</b>
I installed the Docker extension on VS Code and was trying to containerize a C++ application, which is a simple main function printing "hello world." 

While I was able to run the "Add Docker files to Workspace" and "Build Image" commands, when I clicked the Docker tab at the bottom of the left column of the editor, the "Images" section said "Failed to connect. Is Docker installed?" So did the "Containers," "Networks," and the "Volumes" sections. The "Registries" section said "Connect Registry..."

I tried re-installing the extension, but it did not solve the issue. I am wondering what goes wrong and how I can solve it.

Thanks for your help!

**Environment:**
CPU: M1
intelliSenseMode: macos-clang-arm
Extension version: 1.11.0
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:00:52.911Z)
OS version: Darwin arm64 20.2.0

**Dockerfile**
```
FROM ubuntu:latest

RUN apt-get -y update && apt-get install -y

RUN apt-get -y install clang

COPY . /Desktop/c++

WORKDIR /Desktop/c++

RUN clang++ -o hello_world hello_world.cpp

CMD ["./hello_world"]
```

**Comment by bwateratmsft** [comment]
You have the extension installed but do you have Docker itself installed? They have a preview build for M1: https://docs.docker.com/docker-for-mac/apple-m1/
