### ISSUE TITLE
why ".coverage" file is not opening from docker environment

### ISSUE THREAD

**Issue by GSAIVENKAT** [microsoft/vscode-docker#2811]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.containers.openFile
Error type: Error
Error Message: cannot open docker://34499277f1dc438d1b3685a6c8c5fe1a312e7c97e48c90589cbbd6c513c4f28c/usr/src/app/processing-block-template/.coverage?fileType%3Dfile%26containerOS%3Dlinux%26path%3D%252Fusr%252Fsrc%252Fapp%252Fprocessing-block-template%252F.coverage. Detail: File seems to be binary and cannot be opened as text

Version: 1.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:2212:111667
```

</details>

**Comment by bwateratmsft** [comment]
What is the file type? I assume it isn't actually a binary file?
