### ISSUE TITLE
Docker extension will try to connect to 'unix:///var/run/docker.sock', via context 'default'.

### ISSUE THREAD

**Issue by migtam628** [microsoft/vscode-docker#2814]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "---rod" --password-std...' exited with code 1
Error: Error response from daemon: dial unix docker.raw.sock: connect: connection refused

Version: 1.11.0
OS: darwin
OS Release: 20.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.55.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:483:12
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
Is Docker running?
