### ISSUE TITLE
Help me Please do not run dockerfile

### ISSUE THREAD

**Issue by cherryishappy** [microsoft/vscode-docker#2815]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Request failed with status code 407

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
createError extension.bundle.js:65:195713
settle extension.bundle.js:185:26041
IncomingMessage.handleStreamEnd extension.bundle.js:829:29524
IncomingMessage.emit events.js:327:22
endReadableNT _stream_readable.js:1220:12
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by bwateratmsft** [comment]
@cherryishappy does this happen consistently?
