### ISSUE TITLE
VSCode Docker Error

### ISSUE THREAD

**Issue by Takeru9016** [microsoft/vscode-docker#2816]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND default.exp-tas.com

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:66:26
```

</details>

**Comment by bwateratmsft** [comment]
Looks like a network issue when trying to query flighting info.
