### ISSUE TITLE
ModuleNotFoundError: No module named 'pynput'

### ISSUE THREAD

**Issue by ismado** [microsoft/vscode-docker#2819]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:53078

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1141:16
```

</details>

**Comment by bwateratmsft** [comment]
Same as #2807. Does this happen consistently?
