### ISSUE TITLE
Fail to build the alpine image for a .NET Core project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2821]
**OS:** Win 10
**Build Version:** 20210329.3
**.NET Core SDK:** 5.0.201

**Repro Steps:**
1. Open a .NET Core MVC project in VS Code Insiders.
2. Add Docker support for this project.
3. Change the image to "5.0-alpine" in Dockerfile.
4. Right click the Dockerfile -> Select "Build Image...".
5. Check whether the alpine image is built successfully or not.

**Expect:**
The alpine image is built successfully.

**Actual:**
Fail to build the alpine image.
![image](https://user-images.githubusercontent.com/45614674/112965767-25bc4600-917c-11eb-965e-fd668eda37ab.png)

**More Info:**
1. This issue does not reproduce for Ubuntu and Debian images.
2. This issue also reproduces for .NET Core Console app.

**Comment by bwateratmsft** [comment]
Ugh. Looks like Alpine uses "adduser" instead of "useradd", because the world wasn't overcomplicated enough already.
