### ISSUE TITLE
Unable to pull docker image from docker hub in vscode.

### ISSUE THREAD

**Issue by mtbirla** [microsoft/vscode-docker#2822]
Does this occur consistently?  Yes
Repro steps:

1. Logged in to docker hub using my personal credentials.
2. Accessed my image and tried pulling but error occurred.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username username --password-stdin' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.9.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@mtbirla do you have Docker installed?
