### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by paulosix** [microsoft/vscode-docker#2824]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:160068
extension.bundle.js:1053:1322466extension.bundle.js:1053:1322466
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by karolz-ms** [comment]
@paulosix please follow instructions on the page referenced in the error message and feel free to re-open the issue if you still run into problems deploying an image to Azure after that. Hope this helps!
