### ISSUE TITLE
Fail to execute the "Compose Up" action for a .NET Core MVC project on Windows container

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2825]
**OS:** Win 10
**Build Version:** 20210329.3
**.NET Core SDK:** 5.0.201

**Repro Steps:**
1. Switch Docker Desktop to windows containers.
2. Open a .NET Core MVC project in VS Code Insiders.
3. Add Docker files with "Windows OS" and including Docker compose files for this project.
4. Right click the docker-compose.yml file -> Select "Compose Up".
5. Check whether the "Compose Up" action is executed successfully or not.

**Expect:**
The "Compose Up" action is executed successfully.

**Actual:**
Fail to execute the "Compose Up" action.
![image](https://user-images.githubusercontent.com/45614674/113107468-8f008f80-9236-11eb-8bcd-e3a640875d21.png)

**More Info:**
1. This issue does not reproduce on Linux container.
2. This issue does not reproduce for a .NET Core Console app.

**Comment by bwateratmsft** [comment]
Looks like this is a regression due to #2314. I mentioned in the original comment that since other platforms don't open ports < 1024 they didn't need it as much; that is now true for .NET as well, so I'll simply revert #2314.
