### ISSUE TITLE
Misssing Containers in Ubuntu

### ISSUE THREAD

**Issue by shlomoweb1** [microsoft/vscode-docker#2827]
Issue Type: <b>Bug</b>

The Containers menu is missing on Ubuntu 18.04.4 LTS

Extension version: 1.6.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz (4 x 2237)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.50GB (0.34GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by bwateratmsft** [comment]
@shlomoweb1 Maybe the same as #1609? If so, try the following:

1. Uninstall the third-party Docker Explorer extension, if it is present
1. Run the command "View: Reset View Locations"
