### ISSUE TITLE
Docker extension does not show the containers after updaing vscode to v1.55: vscode error connect econnrefused 127.0.0.1:80

### ISSUE THREAD

**Issue by davari** [microsoft/vscode-docker#2831]
Issue Type: <b>Bug</b>

VS Code Version: 1.55
OS Version: Windows 10 Pro, Version 20H2

After updating vscode to version 1.55 (March 2021), the Docker extension does not show the remote containers anymore and instead shows this error:
vscode error connect econnrefused 127.0.0.1:80
It is worth noting that the containers were shown before the update in vscode 1.54.3.

Failed temporary solution: By disabling the update.mod and downgrading vscode to version 1.54.3, the containers appear again in the remote-docker extension. However, the "Attach Visual Studio Code" option gets disappeared (apparently caused by disabling the auto-update).

**Comment by majksner** [comment]
Have exactly the same issue. I've reported it here, maybe a wrong place. microsoft/vscode-remote-release#4800

It will work if you enable "Remote Explorer" in the sidebar instead of using Docker. That worked at least for me.

**Comment by davari** [comment]
> Have exactly the same issue. I've reported it here, maybe a wrong place. [microsoft/vscode-remote-release#4800](https://github.com/microsoft/vscode-remote-release/issues/4800)
> 
> It will work if you enable "Remote Explorer" in the sidebar instead of using Docker. That worked at least for me.

Thank you Nikola for the solution. It worked for me!
As the bug with the docker extension still remains, I do not close the issue for the time being.

**Comment by bwateratmsft** [comment]
@davari @majksner can you share a screenshot of what you're seeing?

**Comment by majksner** [comment]
<img width="349" alt="Screenshot 2021-04-01 at 15 15 52" src="https://user-images.githubusercontent.com/512355/113299435-29c3a180-92fd-11eb-8e09-1ad88017f123.png">
<img width="377" alt="Screenshot 2021-04-01 at 15 16 47" src="https://user-images.githubusercontent.com/512355/113299727-77d8a500-92fd-11eb-9d3b-cd63e6e27d77.png">

**Comment by bwateratmsft** [comment]
Do you have an SSH Docker host?

**Comment by majksner** [comment]
I do, I use Docker context with SSH connection.

**Comment by bwateratmsft** [comment]
Ok. Did you follow the SSH agent setup [here](https://code.visualstudio.com/docs/containers/ssh)?

**Comment by majksner** [comment]
I did. A bit more info than in this issue. 

I'm pasting my original issue here: (microsoft/vscode-remote-release#4800)

After update to Code 1.55 "Remote - Containers" extension is stopped working correctly. I can't connect to remote Docker via context any more. By reverting to Code 1.54.3 I can see containers showing up but I don't have option "Attach Visual Studio Code", but if I downgrade "Remote - Containers" extension to 0.163.1 (Code 1.54.3) I can see "Attach Visual Studio Code" again when I do right-click on the running container. Reverting extension in Code 1.55 didn't help.

Extension version: 0.166.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:07:58.402Z)
OS version: Darwin arm64 20.3.0

**Comment by davari** [comment]
@bwateratmsft my answers to your questions so far are exactly similar to @majksner's

**Comment by bwateratmsft** [comment]
Ok, I think I've reproduced something similar. I haven't figured out _why_ yet, but for some reason Dockerode is making requests to localhost instead of to the SSH server. I see "404" because there's a web server running on port 80 locally; @davari it makes sense that you see ECONNREFUSED if nothing is running locally on 80.

**Comment by bwateratmsft** [comment]
@davari @majksner if you set the "http.proxySupport" setting to "off", does the issue go away (might need to restart VSCode after)?

![image](https://user-images.githubusercontent.com/36966225/113309433-23b9ca80-92d5-11eb-8cf0-063d9dd41688.png)

I think this might be [this issue](https://github.com/microsoft/vscode/issues/65118) come back to life.

**Comment by bwateratmsft** [comment]
cc @chrmarti since this might be due to the update to `vscode-proxy-agent` 0.9.0.

**Comment by davari** [comment]
@bwateratmsft Setting the http.proxySupport setting to off solved the problem for me. Thank you! But why should the Docker extension make request to the localhost instead of the defined SSH server?!

**Comment by bwateratmsft** [comment]
That's just it, it _shouldn't_ make it to localhost. Seems like `vscode-proxy-agent` is hijacking the agent used by `docker-modem` and redirecting requests when it should not be.

**Comment by bwateratmsft** [comment]
I opened https://github.com/microsoft/vscode/issues/120354 against VSCode.

**Comment by markedwards** [comment]
Same issue here on OS X version -- I can confirm that `"http.proxySupport": "off"` is a fix for me as well.

**Comment by sartyukhov** [comment]
> @davari @majksner if you set the `http.proxySupport` setting to `off`, does the issue go away (might need to restart VSCode after)?

thanks for that temporary solution
I have exactly the same problem as topic starter since this update, but I am using linux env DOCKER_HOST=ssh://... for access to my remote docker

**Comment by fhaefemeier** [comment]
> Same issue here on OS X version -- I can confirm that `"http.proxySupport": "off"` is a fix for me as well.

Same issue here (OS X 10.13.6 and Fedora 32, vscode 1.55) using configured docker context with ssh url, but the workaround does not help in my case. I get 'Error: request timed out'. 
Side note: the request to the remote server via shell CLI call is working perfect.

**Comment by bwateratmsft** [comment]
@fhaefemeier do you have an SSH agent set up?

**Comment by max06** [comment]
And another one bit the dust. 
Working in Containers on a remote machine through ssh, using a docker context. `docker ps` is working perfectly fine in any shell. 
`"http.proxySupport": "off"` instantly fixed it.

**Comment by fhaefemeier** [comment]
> @fhaefemeier do you have an SSH agent set up?

On OS X yes, it is running, but my ssh keys are missing. After adding it the extension is now working. Thanks for the hint.

**Comment by bwateratmsft** [comment]
@davari @majksner @markedwards @sartyukhov @max06 @fhaefemeier (Wow that's a lot of tags!)

VSCode 1.55.1 is released now and should fix this issue without needing `"http.proxySupport": "off"`. I was able to connect successfully in a quick canary test. Can anyone else confirm?

**Comment by davari** [comment]
@bwateratmsft I can confirm that updating to VSCode 1.55.1 solved the issue. Thank you and the team!
