### ISSUE TITLE
Error response from daemon: certificate is valid for bf-dev-artifactory.sai.mycompany, not auth.docker.io

### ISSUE THREAD

**Issue by SaiSasankKhajjayam** [microsoft/vscode-docker#2834]
our docker service is running in a centos machine where internet is blocked.

We are getting the following error when we try to pull docker images from a private Jfrog docker registry and following entries are added in /etc/hosts file to block all docker public access.

content of /etc/hosts file is
10.XXX.XXX.XX platform-docker-dev.bf-dev-artifactory.mycompany.com
0.0.0.0 index.docker.io auth.docker.io  dseasb33srnrn.cloudfront.net production.cloudflare.docker.com

Error is :
Error response from daemon: Head https://registry-1.docker.io/v2/library/hello-world/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io: x509: certificate is valid for bf-dev-artifactory.prod.hclpnp.com, not auth.docker.io

if we remove this "0.0.0.0 index.docker.io auth.docker.io  dseasb33srnrn.cloudfront.net production.cloudflare.docker.com" in hosts file  then docker images are pulling from docker.io even though internet is blocked.

Can any one help me to resolve the issue ?

**Comment by bwateratmsft** [comment]
It looks like this error is coming from the Docker command line--do image pulls work from command line directly?

**Comment by SaiSasankKhajjayam** [comment]
@bwateratmsft   Images are not pulling from command line. Getting the same error.

**Comment by bwateratmsft** [comment]
If it's also coming from the command line then this isn't an error with the extension.
