### ISSUE TITLE
Disable/give option to disable decorators/syntax highlighting for Dockerfile

### ISSUE THREAD

**Issue by GBrachetta** [microsoft/vscode-docker#2837]
Is it possible to disable the decorators/syntax/color highlighting for Dockerfile?

I would like to either tweak them or use another option since your configuration isn't easy on my eyes.

I would really appreciate to have a choice to not use them or disable them.

**Comment by bwateratmsft** [comment]
There are a lot of settings you can configure for languages, all of which you can configure in settings.json (`Preferences: Open Settings (JSON)` in command palette).

If you want to disable syntax highlighting entirely, you can have the file be treated as plain text:
```json
    "files.associations": {
        "Dockerfile": "plaintext"
    },
```

If you want to disable semantic highlighting and just use the basic highlighting:
```json
    "[dockerfile]": {
        "editor.semanticHighlighting.enabled": false
    }
```

In general, there are dozens of settings under `editor.*` that you can specify for Dockerfiles, so I'm confident you can do what you need.
