### ISSUE TITLE
Files from readme (gif, png) not loading in VSCODE's extensions tab

### ISSUE THREAD

**Issue by rara4** [microsoft/vscode-docker#2838]
For some reason none of the files are showing up in Vscode's extensions.
I thought of using the files' relative paths instead, or even adding ?raw=true at the end of the urls, but I'm not sure either one is going to work. I also tried refreshing Vscode, so I don't think the issue is on my end.
I included a screenshot, hopefully this helps.

![dockerscreenshot](https://user-images.githubusercontent.com/77614258/113500954-4ab90c00-9522-11eb-80eb-e12d84d34918.png)

**Comment by bwateratmsft** [comment]
Looks like a bug with the VS Code marketplace. It is looking at the master branch for images but that branch no longer exists; we need to get it to look at main somehow.

**Comment by bwateratmsft** [comment]
I made a temporary workaround that should cause those files to reappear, I'm working on a permanent fix.

**Comment by rara4** [comment]
> Looks like a bug with the VS Code marketplace. It is looking at the master branch for images but that branch no longer exists; we need to get it to look at main somehow.

Interesting, nice catch ! Feel free to close this issue, it's working now thanks to your responsiveness.

**Comment by bwateratmsft** [comment]
> Interesting, nice catch ! Feel free to close this issue, it's working now thanks to your responsiveness.

There's still a change we need to make on our side (#2840) so that we don't have to apply the workaround, so I'll close this with #2840. :smile:

**Comment by bwateratmsft** [comment]
This fix is now released with Docker extension version 1.12.0.
