### ISSUE TITLE
UDP exposed ports not launching correctly

### ISSUE THREAD

**Issue by GTB3NW** [Microsoft/vscode-docker#284]
For example in my config if I have:

```
        "ExposedPorts": {
            "20000/udp": {}
        },
```
The launched container is given the following flags:

`$ docker run --rm -d -p 20000:20000 <redacted image>`

It should be:

`$ docker run --rm -d -p 20000:20000/udp <redacted image>`

I think it's just a bug with vscode parsing the config and not knowing to correctly add /udp when it's a udp service.

If I'm doing something wrong myself please do let me know.

**Comment by PrashanthCorp** [comment]
It doesn't seem to be an issue with vscode. 
[This line](https://github.com/Microsoft/vscode-docker/blob/084db32e0e047b29fdd019a26b5575c78f0e591d/commands/start-container.ts#L32) in the docker run file makes the in-variance assumption that the host and listener ports are always the same. 

I have a fix for this. I haven't exhaustively tested this. I just want to understand all the other use cases of the -p flag: 
1. The default format (no overrides from config file) tends to be `300/tcp`. Does this assumption hold well? 
2. It looks like the host port like `3000/tcp` would be invalid. Is truncating this in all cases a reasonable course of action? 
Will have a PR out soon. 
It'd be great if you could review it and lmk if it fixes the edge cases you have in mind.

**Comment by GTB3NW** [comment]
Hey @PrashanthCorp apologies for my delay in getting back to you, I've not been logged in on github for a little while.

Thank you for submitted the PR, great work!

1. With no manual changes to the config file that should be the default format. I've tried to find reference material as to what docker expects to see but I can't find it I'm afraid. I presume if you manually edit that to omit it, docker will not accept the file. Docker build does however automatically add /tcp if no protocol is specified, that behavior is what leads me to believe omission is not allowed in that generated output.

2. Not 100% with what you mean there sorry. Could you explain?

**Comment by PrashanthCorp** [comment]
Regarding 2, I mean something like this: 
`docker run --rm -d -p 20000/udp:20000/udp <container id>`
 which leads to an error  : 
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Invalid hostPort: 20000/udp.
