### ISSUE TITLE
wordpress.image

### ISSUE THREAD

**Issue by DavidSpurlock** [microsoft/vscode-docker#2845]
Does this occur consistently? 
Repro steps:

docker run --wordpress --network 19.168.208.131/24 -d wordpress
docker run --192.168.208.131/24  -p 8080:80 -d wordpress
docker run --wordpress -e WORDPRESS_DB_HOST=10.1.2.3:3306 \
    -e WORDPRESS_DB_USER=mysqluser -e WORDPRESS_DB_PASSWORD=mysqlpass -d wordpress
docker run --wordpress -e WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mysql-root docker.yml -d wordpress:image
docker stack deploy -c stack.yml wordpress

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "davspur" --password-stdin' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:483:12
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
@DavidSpurlock Do you have Docker installed?

**Comment by DavidSpurlock** [comment]
Yes, I have it installed on Visual Code as an extension. I am trying to use Docker to dispense it on a Virtual machine, Ubuntu Server, with apache installed to have a working WordPress. I'm having an issue with the Database.

**Comment by DavidSpurlock** [comment]
I honestly didn't realize I was making an issue ticket.
