### ISSUE TITLE
No dialog pops up after clicking "Open Folder" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2846]
**OS:** Mac
**Build Version:** 20210405.1

**Repro Steps:**

1. Install the docker extension -> F1 -> Type and select "Add Docker Files to Workspace... -> Click "Open Folder" when asking to open a folder or workspace.
2. Check whether open a dialog to select a folder or workspace.

**Expect:**
Pop up a dialog to select a folder or workspace.
![Screen Shot 2021-04-06 at 4 08 51 PM](https://user-images.githubusercontent.com/62053665/113679648-93272400-96f2-11eb-9f0b-84c14f5c9f7a.png)

**Actual:**
No dialog pops up.

**More Info:**
This issue doesn't reproduce on Windows/Linux.

**Comment by bwateratmsft** [comment]
Looks like an external bug, I'll file it.

**Comment by bwateratmsft** [comment]
Closing as external, https://github.com/microsoft/vscode/issues/120752.

**Comment by bwateratmsft** [comment]
Reopening, as in VSCode this is by-design. I don't think it makes the bar for 1.12.0 though as it's been present for multiple releases now.
