### ISSUE TITLE
The push refers to repository [docker.io/realwujing/ubuntu]

### ISSUE THREAD

**Issue by RealWuJing** [microsoft/vscode-docker#2850]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login --username "real---" --password-st...' exited with code 1
Error: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/auth: open //./pipe/docker_engine: The system cannot find the file specified.

Version: 1.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.55.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:483:12
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:443:11
Socket.emit events.js:315:20
Socket.EventEmitter.emit domain.js:483:12
Pipe.<anonymous> net.js:674:12
```

</details>

**Comment by bwateratmsft** [comment]
@RealWuJing is Docker running?

**Comment by RealWuJing** [comment]
yeah,docker is running

**Comment by bwateratmsft** [comment]
Does the same command work from the command line?

`docker login --username "yourUsername" --password-stdin`
