### ISSUE TITLE
[Suggestion] It would be better to add the ellipsis end of "Download"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2851]
**OS:** All
Build Version: 20210406.3

**Repro Steps:**

1. Open the Docker Containers view in VS Code -> Expand the "Files" node for a running container -> Hover over a file -> Hover over the download icon.
2. Check the tooltip.

**Actual:**
There is no ellipsis end of "Download".
![image](https://user-images.githubusercontent.com/62053665/113836075-2594f980-97bf-11eb-824d-84c140ded30b.png)

**Suggestion:**
It would be better to add an ellipsis in the end of "Download".

**Comment by bwateratmsft** [comment]
I agree, since there's a prompt to choose a location to save the file to, I think an ellipsis would be best.
