### ISSUE TITLE
idk what i do xd

### ISSUE THREAD

**Issue by CbParra117** [microsoft/vscode-docker#2855]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 1
Error Message: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 1
Error: Couldn't find env file: c:\xampp\htdocs\Dcode\dynasty_code\.env.dev

Version: 1.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:16:91853
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by karolz-ms** [comment]
Carlos, can you add repro steps? Does the same `docker-compose` command work from command line?
