### ISSUE TITLE
[GitHub Codespaces] The web page displays incorrectly when executing "Open in Browser" action for a Django container

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2860]
**OS:** Remote Codespaces
**Build Version:** 20210406.3

**Repro Steps:**
1. Open a Python Django project and add Docker support for it in VS Code.
2. Right click the docker-compose.yml -> Select "Compose Up" -> Pop up a dialog to open the browser.
![image](https://user-images.githubusercontent.com/57662131/114148268-25763480-994c-11eb-94ed-ce11e9e5002a.png)
3. Navigate to "CONTAINERS" view -> Right click the running container -> Click "Open in Browser".
4. Check whether the web page displays successfully or not.

**Expect:**
The web page should display successfully.

**Actual:**
The web page displays incorrectly.
![image](https://user-images.githubusercontent.com/57662131/114147772-9ff28480-994b-11eb-9fda-60fed9e4e708.png)

**More Info:**
1. This issue also reproduces for the Python Flask project.
2. This issue doesn't reproduce on the non-codespaces and local-codespaces.
2. The web page displays successfully when clicking the "Open in Browser" in the dialog.

**Comment by bwateratmsft** [comment]
I wasn't able to reproduce with either local VSCode or browser Codespaces, but this looks like a service hiccup to me.
