### ISSUE TITLE
[GitHub Codespaces] The web page keeps loading when debugging a MVC project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2861]
**OS:** Local Codespaces
**Build Version:** 20210406.3

**Repro Steps:**
1. Open a .NET Core MVC project and add Docker support in VS Code.
2. Debug this project with configuration "Docker .NET Core Launch".
3. Check whether the web page can be opened successfully or not.

**Expect:**
The web page can be opened successfully.

**Actual:**
The web page keeps loading.

**More Info:**
1. There is no web page opening in Remote Codespaces environment.
2. This issue does not reproduce in non-Codespaces environment.

**Comment by bwateratmsft** [comment]
I encountered this as well with Django, but I think it's just Codespaces being really, really slow.

**Comment by bwateratmsft** [comment]
@karolz-ms @philliphoff can one of you try using Codespaces today? Things seem to be *incredibly* slow, especially opening things in browser.

**Comment by bwateratmsft** [comment]
I spoke to @Chuxel who has also seen this issue; apparently opening it a third time magically makes it work (and I verified that weirdness). I opened https://github.com/microsoft/vssaas-planning/issues/3556 for this.
