### ISSUE TITLE
unable to type my code due to object event 

### ISSUE THREAD

**Issue by SNmcdarby1** [microsoft/vscode-docker#2862]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: [object Event]

Version: 1.11.0
OS: linux
OS Release: 5.4.0-1024-gcp
Product: Gitpod Code
Product Version: 1.54.2
Language: en-US

<details>
<summary>Call Stack</summary>

```
Object.ensureError loader.js:249:22
ModuleManager._createLoadError loader.js:1440:33
ModuleManager._onLoadError loader.js:1451:30
loadNextPath loader.js:1597:27
Object.errorback loader.js:1617:25
OnlyOnceScriptLoader.triggerErrorback loader.js:623:36
https:/loader.js:610:151
HTMLScriptElement.errorEventListener loader.js:646:17
```

</details>

**Comment by bwateratmsft** [comment]
Does this happen consistently?

**Comment by SNmcdarby1** [comment]
Not really .This only happened when the new interface was released on
gitpod.

Did some changes with the user settings and this is how I got to this point.

**Comment by bwateratmsft** [comment]
Thanks. Can you add repro steps? Does this same issue reproduce in VS Code?
