### ISSUE TITLE
Docker extension not recognising c# extension version when generating .NET docker files

### ISSUE THREAD

**Issue by dpwdec** [microsoft/vscode-docker#2867]
When I used the `Add Docker Files to Workspace...` utility I get an error message that says:

> Cannot generate Dockerfiles for a .NET project unless version 1.23.9 or higher of the C# extension is installed.

I assume this is referring to the Microsoft C# extension for vscode. I have restarted my computer and vscode. I believe both the Docker and C# extensions are installed and updated to their most recent version however I still get this error.

Please let me know if you need me to provide you with further information.

**Comment by bwateratmsft** [comment]
Can you check the extensions tab and see what version of the C# extension you have?

**Comment by pecigonzalo** [comment]
Im facing the same issue, version is 1.23.11

**Comment by bwateratmsft** [comment]
Strange. Does the issue persist if you restart VSCode @pecigonzalo?

**Comment by pecigonzalo** [comment]
Yes it does. I'm indeed using a remote session to WSL2, I suspect that might be the culprit, maybe some bug in checking the remote/local version?

I manually edited the file as a test, inverted the > check and it "works" now.

**Comment by dpwdec** [comment]
When I list my extensions with versions using `dotnet --list-extensions --show-versions` I get `ms-dotnettools.csharp@1.23.11` for the c# tools.

I am not using a remote desktop and have reproduced this on two separate machines.

**Comment by bwateratmsft** [comment]
> I manually edited the file as a test, inverted the > check and it "works" now.

As in, [this check](https://github.com/microsoft/vscode-docker/blob/main/src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts#L140)? I'd be very interested in what VSCode is giving for `cSharpExtension.packageJSON.version` there.

**Comment by bwateratmsft** [comment]
🤦‍♂️ I realized what's wrong. That `<` is exactly the problem, it doesn't actually mean what you'd expect. SemVer should be using `.lt()`, instead. I'm guessing it's doing string comparison; considering strings, '1.23.9' is equal to '1.23.9'--so it passed our initial testing--but '1.23.11' is less than '1.23.9' (alphabetically, i.e. how strings get compared).

**Comment by pecigonzalo** [comment]
> > I manually edited the file as a test, inverted the > check and it "works" now.
> 
> @pecigonzalo As in, [this check](https://github.com/microsoft/vscode-docker/blob/main/src/scaffolding/wizard/netCore/NetCoreGatherInformationStep.ts#L140)? I'd be very interested in what VSCode is giving for `cSharpExtension.packageJSON.version` there.

Yep, exactly that one. It was in the minified JS so I just inverted the symbol, although I could have replaced with just `false`.

**Comment by pecigonzalo** [comment]
Yeah, that sounds about right. 🎉 Nice find.

**Comment by bwateratmsft** [comment]
@pecigonzalo @dpwdec As a workaround, you can install C# extension 1.23.9 specifically, add the Dockerfiles, and then update back to 1.23.11+.

1. ![image](https://user-images.githubusercontent.com/36966225/114452172-2c987f00-9ba6-11eb-9468-92324292d0c2.png)
1. Add Dockerfiles
1. ![image](https://user-images.githubusercontent.com/36966225/114452353-59e52d00-9ba6-11eb-94e1-2be99ef55709.png)

I'm going to get a fix out ASAP.

**Comment by bwateratmsft** [comment]
Ok, I just released an update to the Docker extension a few seconds ago. This issue is now fixed in 1.12.1. Sorry for the headache @dpwdec, @pecigonzalo, and thanks for helping me figure it out!

**Comment by pecigonzalo** [comment]
No worries! Thank you for fixing it so fast. I'll install it first thing
tomorrow.

**Comment by dpwdec** [comment]
@bwateratmsft Yeah, it's working for me now as well. Thank you so much for fixing it so promptly.
