### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by hfenelsoftllc** [microsoft/vscode-docker#2868]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN default.exp-tas.com

Version: 1.11.0
OS: linux
OS Release: 5.4.72-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.55.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:66:26
```

</details>

**Comment by bwateratmsft** [comment]
Similar to a few other issues, but this will be fixed in 1.12.0 with #2812.

**Comment by bwateratmsft** [comment]
This fix is now released with Docker extension version 1.12.0.
