### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VladPutinEu** [microsoft/vscode-docker#2873]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.12.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.1`

[ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-docker/files/6299741/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@VladPutinEu Unfortunately these CPU profiles that VSCode generates are pretty much useless. Does this issue occur consistently?

**Comment by VladPutinEu** [comment]
> @VladPutinEu Unfortunately these CPU profiles that VSCode generates are pretty much useless. Does this issue occur consistently?

No. It was just a one-time thing.

**Comment by bwateratmsft** [comment]
Neat, VSCode added a viewer for CPU profiles, and a bonus extension that provides a flame chart. It looks like in this profile, essentially all of the time was consumed loading/compiling the code, not actually running the code. That would make this an external issue. I do sometimes see weird loader issues like this, where the loader woke up on the wrong side of the bed and can't get things done...
