### ISSUE TITLE
Support for Digital Ocean registry

### ISSUE THREAD

**Issue by bbrefeld** [microsoft/vscode-docker#2879]
Recently I started using VSCode and noticed I was unable to connect to the Digital Ocean registry through the extension.

After some communication with support I got the following message from Digital Ocean:

> "After digging further into this, the issue is that Visual Studio is trying to authenticate using the endpoint v2/registry/auth whereas we use /v2/registry/docker-credentials for authentication hence the 404 error"

Would it be possible to add support for this registry?

**Comment by bwateratmsft** [comment]
We've been tracking registries in #869. I added Digital Ocean to the list.
