### ISSUE TITLE
Syntax Highlighting for FROM field is invalid for <host:port/path:version>

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-docker#288]
![image](https://user-images.githubusercontent.com/3254987/42112230-03e4b862-7b9c-11e8-9ec2-3165a39bd8e0.png)

**Comment by rcjsuen** [comment]
Hi, @unional. Thank you very much for your bug report.

I believe your issue is the same as #269 and #280. Do you agree?

**Comment by unional** [comment]
Oh yes, you are correct. I searched for "highlighting from" and couldn't find those two issues. I should have searched for linting.

Dup of #269 and #280.

**Comment by StephenWeatherford** [comment]
@unional Just wanted to let you know that we have published a new version of the Docker extension that should contain this fix.  Happy coding!

**Comment by unional** [comment]
Excellent! Thx
