### ISSUE TITLE
dockerConnect

### ISSUE THREAD

**Issue by AmadouDiallo4** [microsoft/vscode-docker#2889]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 1.12.1
OS: linux
OS Release: 5.10.27-v7l+
Product: Visual Studio Code
Product Version: 1.55.1
Language: en

**Comment by karolz-ms** [comment]
Hmm, it looks similar to https://github.com/microsoft/vscode-docker/issues/722 but that should have been fixed... @AmadouDiallo4 what container registry are you using? Can you add repro steps?
