### ISSUE TITLE
Add quick actions to explorer nodes 

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode-docker#2891]
Colocar nos ícones das viewlet DOCKER > CONTAINERS e DOCKER > IMAGES, buttons como em Source Control.
Place on the DOCKER viewlet icons > CONTAINERS and DOCKER > IMAGES, buttons as in Source Control.

O que precisa ser possível:
What needs to be possible:

1. 
- [ ] Criar e deletar contêineres de imagens baixadas ou não.
- [ ] Create and delete containers from downloaded images or not.

2.
- [ ] Criar e/ou baixar e deletar imagens de contêineres.
- [ ] Create and/or download and delete container images.

3.
- [ ] Entrar na linha de comado de cada contêiner ou fazer run em uma imagem e entrar na linha de comando em seguida.
- [ ] Enter the comad line of each container or run into an image and enter the command line next.

4.
- [ ] Publicar meus contêineres e imagens diretamente para os REGISTRIES.
- [ ] Publish my containers and images directly to REGISTRIES.

6.
- [ ] Deletar meus contêineres e imagens dos REGISTRIES com confirmação.
- [ ] Delete my containers and images from REGISTRIES with confirmation.

5.
- [ ] Exportar e importar contêineres e imagens para arquivos compactados de forma direta e em um clique.
- [ ] Export and import containers and images to compressed files directly and in one click.

![simplescreenrecorder-2021-04-19_17.16.14](https://i.imgur.com/HBkzSzK.gif)

**Comment by dbreshears** [comment]
We should investigate what makes sense based on most commonly used actions

**Comment by AlexandroGonSan** [comment]
[pt-br][Original]

Podemos trabalhar com a equipe do mscode para verificar como permitir selecionar os itens e assim colocávamos as opções no dropdown.

[en][Bing Translate]

We can work with the mscode team to see how to select items and then put the options in the dropdown.

**Comment by bwateratmsft** [comment]
We will need to evaluate which, if any of the actions we want on the nodes. We have a lot of actions--far more than source control--and we can't crowd the nodes so much that the labels get washed out.

**Comment by dbreshears** [comment]
Given the space constraints in the UI it makes it a bit busy and crowded.   Thank for the feedback but we decided not to add this feature.  We will monitor for additional user feedback however.
