### ISSUE TITLE
Docker Visual Code Issue

### ISSUE THREAD

**Issue by aeplager** [microsoft/vscode-docker#2892]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login --username "quicksoftwaresolutions" -...' exited with code 1
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.12.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:483:12
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by karolz-ms** [comment]
@aeplager does this happen consistently? Can you log in to your registry using `docker` from command line?

**Comment by yaroslavsadin** [comment]
I do experience similar issue when updated to the latest release, in my case I can't connect to Nexus repository with "Error: invalid json repsonse body at ..."

**Comment by aeplager** [comment]
For me it ended up with the naming of the docker.   I had some invalid characters in the name.    What I did was make sure that I only had alphabetic characters in it.   I believe I had a \ in it but it was some time ago.   I apologize for the lack of specificity.

**Comment by karolz-ms** [comment]
Glad you were able to resolve the issue @aeplager ☺️ 

@yaroslavsadin feel free to open a new issue for the problem you are seeing, but please include repro steps--thank you.
