### ISSUE TITLE
Add "Compose Stop" option on grouped-by-compose nodes

### ISSUE THREAD

**Issue by Dozorengel** [microsoft/vscode-docker#2895]
We already have a list of options like "Compose Logs", "Compose Restart", "Compose Down" for a group of containers in Docker sidebar. However, I've been missing "Compose Stop" option for a long time. If I just compose down my contaners, they'll dissappear from the sidebar and I won't be able to start/restart them from there.

There is only a "Stop" option for an individual container, so now I have to select all my containers with "Shift" pressed on within the group and stop them every time that way. But it's not as convenient as we had an option to stop them all in one click. I know that there is a command to stop a group of containers, but I'm used to manage my containers from the sidebar. Therefore, it shouldn't be a hard task to add this option in the list.

**Comment by karolz-ms** [comment]
@Dozorengel thank you for the suggestion, makes sense.

For our education, could you describe why you find the option to "stop" a group of containers useful? E.g. what kind of app/image are you using and why stopping is better for these than restarting from scratch? Thank you!

**Comment by Dozorengel** [comment]
@karolz-ms Thanks for the quick response.

I have to work on the multiple projects at the same time. They are all dockerized and mainly there are two reasons to do that.

First, all the launched containers share my system resources (cpu, ram). Moreover, I launch them under WSL, and it greatly increase the consuming. It's totally fine if you work on a single project with 16 gb ram equipped. But for two projects and more, either WSL will stop responding and you have to manually shutdown it and then restart, or WSL will devour all your system resources that makes the PC be extremely laggy.

I'm really tired out of that and purchased 64 gb ram. For example, now my usual working environment with a browser, IDE and 3 running container clusters is consuming up to 26-27 gb. But it's not an option for all developers, some of them have laptops that support 16 gb ram max. For this case you need to stop one cluster and start another one. 

Second, running containers share ports. For example, I can't launch two mysql instances in different projects at the same time as they expose the same 3306 port. The configuration is under git in the project, I'm not allowed to change ports there. As a workaround I change them only locally and have to make sure I won't push the config to the repository. But it's not always a best solution, sometimes it's easier to just stop the containers.

**Comment by karolz-ms** [comment]
@Dozorengel thank you. Just to make sure I understand what you said: you want to "stop" a Compose project (group of containers) so that they do not consume host resources (RAM, ports), but you want to keep them available under Docker so you can quickly spin them back up--that is why you do not want to "Compose Down" them? Is that correct?

**Comment by Dozorengel** [comment]
@karolz-ms absolutely, yes.

**Comment by bva-mike** [comment]
hello, 

it would be great to add stop to this context menu also please, thank you !

![image](https://user-images.githubusercontent.com/51820538/125612367-c0be20cd-c725-47b4-af05-281f0df0b629.png)

**Comment by bwateratmsft** [comment]
This has been released in Docker extension version 1.16.0.
