### ISSUE TITLE
Crashed while I was experimenting with docker-compose config options.

### ISSUE THREAD

**Issue by DeathBot9** [microsoft/vscode-docker#2896]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 1
Error Message: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 1
Error: The Compose file './docker-compose.yml' is invalid because:
services.km.deploy.resources.limits contains an invalid type, it should be an object

Version: 1.12.1
OS: darwin
OS Release: 20.3.0
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by karolz-ms** [comment]
@DeathBot9 looks like a legitimate error given the information provided... Are you sure the Compose file is well-formed? Does `docker-compose up` from the command line work with the same file?
