### ISSUE TITLE
"Webview is disposed" error opening start page

### ISSUE THREAD

**Issue by mohdsaquib-cloud** [microsoft/vscode-docker#2898]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.help.openStartPage
Error type: Error
Error Message: Webview is disposed

Version: 1.12.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
v.assertNotDisposed extensionHostProcess.js:87:53676
v.set html [as html] extensionHostProcess.js:87:53045
StartPage.createOrShow extension.bundle.js:2:4383398
async openStartPage extension.bundle.js:2:4385088
```

</details>

**Comment by philliphoff** [comment]
@mohdsaquib-cloud Can you provide a little more detail around how this error showed up?  Is it a persistent problem, or just happened once? Thanks!

**Comment by karolz-ms** [comment]
Duplicate of https://github.com/microsoft/vscode-docker/issues/2820
