### ISSUE TITLE
docker pull 

### ISSUE THREAD

**Issue by poohfrog45** [microsoft/vscode-docker#2899]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: TypeError
Error Message: Only HTTP(S) protocols are supported

Version: 1.12.1
OS: linux
OS Release: 4.4.0-19041-Microsoft
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
getNodeRequestOptions extension.bundle.js:2:3346448
extension.bundle.js:2:3347182
Module.fetch extension.bundle.js:2:3346141
Object.httpRequest extension.bundle.js:2:4650611
async Object.registryRequest extension.bundle.js:2:4665886
async GenericDockerV2RegistryTreeItem.loadMoreChildrenImpl extension.bundle.js:2:4623605
```

</details>

**Comment by karolz-ms** [comment]
@poohfrog45 can you add repro steps?

**Comment by poohfrog45** [comment]
No I can’t I’m stuck and I need help

**Comment by karolz-ms** [comment]
Sorry to hear that @poohfrog45 

Make sure you followed the [Docker installation instructions](https://docs.docker.com/engine/install/) for your OS, including [post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/). Then I suggest you go through the [Docker tutorial](https://docs.docker.com/get-started/). Hope it helps!
