### ISSUE TITLE
Can't pull image

### ISSUE THREAD

**Issue by ISPLab** [microsoft/vscode-docker#2900]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "andreusimus" --password-s...' exited with code 1
Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.12.1
OS: linux
OS Release: 5.4.0-1034-raspi
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:443:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:674:12
```

</details>

**Comment by karolz-ms** [comment]
@ISPLab are you able pull the image using docker CLI (from command line)? Did you go through the [Docker post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/)?

**Comment by ISPLab** [comment]
Hi Karol!
This issue was created automatically. I found solution for my task (possible I checked your links after too) and don’t need help.
I thought it may be interesting for developers because  it was proposed by the docker.
Close issue if it is not actually.
Thanks!

**Comment by karolz-ms** [comment]
Thanks for clarification and for helping us make the extension better, @ISPLab 👍
