### ISSUE TITLE
Connecting to Azure Registries opens localhost URL instead of microsoft.com for authorisation

### ISSUE THREAD

**Issue by dombarnes** [microsoft/vscode-docker#2901]
Issue: When attempting to connect to the Azure registry, a browser window is opened with a localhost URL instead of an internet based URL to allow authentication via a Microsoft account
e.g http://localhost:<random-port-number>/signin?nonce=<random-string>

Note: Unable to replicate currently. Process eventually suggests logging in with a device code. I have tried disconnecting Azure but upon attempting to Connect, it seems to have preserved my previous details so can't re-do to capture screenshots)

VS Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Extension Version - v1.12.1

**Comment by karolz-ms** [comment]
@dombarnes thank you for reporting this issue. I guess we will keep an eye on it, hopefully it was just a one-time Heisenbug
