### ISSUE TITLE
Header Issue

### ISSUE THREAD

**Issue by aeplager** [microsoft/vscode-docker#2902]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login --username "quicksoftwaresolutions" -...' exited with code 1
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.12.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:483:12
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by karolz-ms** [comment]
@aeplager can you add repro steps?

I just tried my Docker registry and it seems to work fine with the same combination of VS Code and Docker ext
