### ISSUE TITLE
connecting to docker i need help 

### ISSUE THREAD

**Issue by poohfrog45** [microsoft/vscode-docker#2903]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 127
Error Message: Process 'docker login --username "mailikh151o" --password-s...' exited with code 127
Error: /bin/sh: 1: docker: not found

Version: 1.12.1
OS: linux
OS Release: 4.4.0-19041-Microsoft
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:443:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:674:12
```

</details>

**Comment by karolz-ms** [comment]
@poohfrog45 are you able to use `docker` from command line? (e.g. try `docker ps`). Are you able pull an image from command line? Did you go through the [Docker post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/)?
