### ISSUE TITLE
>Docker: Initialize for Docker debugging

### ISSUE THREAD

**Issue by chris-ryu** [microsoft/vscode-docker#2904]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.debugging.initializeForDebugging
Error type: Error
Error Message: Unable to write into the launch configuration file. Please open it to correct errors/warnings in it and try again.

Version: 1.12.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
C.reject workbench.desktop.main.js:2060:16779
file:/workbench.desktop.main.js:2060:20853
async C.doWriteConfiguration workbench.desktop.main.js:2060:13958
```

</details>

**Comment by karolz-ms** [comment]
@chris-ryu the "launch configuration file" mentioned in the error message is the file named `launch.json` in the `.vscode` folder at the workspace root. Please open it, correct any errors, and run "Add Docker files..." command again.

If you are still facing a problem, feel free to re-open this issue, but please add repro steps, i.e. describe exactly what you did, what you expected to happen, and what happened instead. Hope this helps!
