### ISSUE TITLE
error on visual studio code

### ISSUE THREAD

**Issue by brunohelius** [microsoft/vscode-docker#2906]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.push
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.12.1
OS: darwin
OS Release: 20.5.0
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1211545
extension.bundle.js:2:1199379
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by karolz-ms** [comment]
Hi @brunohelius Please follow the instructions mentioned in the error message (https://aka.ms/rps-not-found ) If that does not help, please open a new issue and add repro steps (what you have done, what you expected to happen, and what happened instead). Thanks!
