### ISSUE TITLE
Error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by alevvalles** [microsoft/vscode-docker#2908]
I've connected Docker extension with my private registry (Harbor), but tags appear as "Invalid" and opening it, it shows the mentioned Error: Cannot read property '0' of undefined.

![Screenshot from 2021-04-28 09-26-16](https://user-images.githubusercontent.com/25229146/116403336-d3feee00-a803-11eb-886c-7d7c66d2dbba.png)

**Comment by karolz-ms** [comment]
@alevvalles what version of Harbor are you using? They had/have some issues with registry v2 protocol support e.g. https://github.com/goharbor/harbor/issues/13653
