### ISSUE TITLE
Error after changing docker's data-root

### ISSUE THREAD

**Issue by chamboin** [microsoft/vscode-docker#2909]
The extension throw `Error: connect EACCES /var/run/docker.sock` after I change the docker's `data-root`

I changed docker's storage root by edit `/etc/docker/daemon.json` to another directory on host machine, then the extension seems couldn't connect, help plz

**Comment by karolz-ms** [comment]
@chamboin thanks. Some questions:
- what OS, what Docker engine version
- does `docker` CLI work from within VS Code terminal? Does restarting VS Code help?
- how exactly did you restart the Docker daemon after changing `data-root`?

**Comment by chamboin** [comment]
Thanks, solved this problem with completely restart : )
