### ISSUE TITLE
Docker push failed

### ISSUE THREAD

**Issue by StianJakobsen** [microsoft/vscode-docker#2910]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login "https://azurefunctionreg.azurecr.io"...' exited with code 1
Error: Error response from daemon: Get https://azurefunctionreg.azurecr.io/v2/: Get https://azurefunctionreg.azurecr.io/oauth2/token?account=00000000-0000-0000-0000-000000000000&client_id=docker&offline_token=true&service=azurefunctionreg.azurecr.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

Version: 1.12.1
OS: darwin
OS Release: 20.2.0
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:443:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:674:12
```

</details>

**Comment by karolz-ms** [comment]
@StianJakobsen are you able to log in and push images to your registry from command line? 

Check the name of the registry--sometimes this error shows when one mis-spells the name when adding the registry to VS Code.
