### ISSUE TITLE
Cannot pull new public image directly

### ISSUE THREAD

**Issue by imonace** [microsoft/vscode-docker#2912]
Using the extension's built in command ">Docker Images: Pull", it will prompt a "Select image group" and list the existing image groups, then prompt to select the tags of the image.

Both two selector prompt don't allow enter a non-existing image.

Also tried "Docker Registries: Pull image" and "Pull repository", don't allow new public image either.

Is there any ways to directly pull a new public image from the registry?

VSCode 1.55.2 with docker extension 1.12.1
on macOS 11.3 with Docker Desktop 3.3.1

**Comment by karolz-ms** [comment]
Does `Docker Registries: Refresh` help?

**Comment by imonace** [comment]
> Does `Docker Registries: Refresh` help?

Tried but still not work 😂.

My goal is to pull some public images that neither exists in local storage, nor belongs to the current user, pretty much like executing `docker pull ubuntu:latest`.

`docker pull ubuntu:latest` could work in command-line, but I wonder if there any ways to execute it directly from VSCode, or perhaps i've still missed something. 

Btw, thanks for the effort on this amazing extension.

**Comment by karolz-ms** [comment]
OK, got it! Indeed `Docker Images: Pull` does not allow pulling arbitrary image. 🤔 

Thanks for the suggestion!

**Comment by dbreshears** [comment]
Closing stale issue, we don't have plans to add this to the UI
