### ISSUE TITLE
constant 100% CPU docker process

### ISSUE THREAD

**Issue by okarika** [microsoft/vscode-docker#2918]
docker process is constantly using 100% cpu regardless if I do something in code or it's totally idle

**Comment by karolz-ms** [comment]
@okarika what is your OS & Docker version? Does restarting the machine help? (Docker can get into bad state)

If machine restart (or upgrade to latest Docker version) do not help, can you tell what are the parameters to the docker command/process that is consuming 100% CPU?

**Comment by okarika** [comment]
restart didn't help

OS Ubuntu 21.04
docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu2

the process is the dockerd itself:
/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock 

seems this command is constantly running:
/bin/sh -c docker images --filter "dangling=false" --format "{{.ID}} {{.Repository}} {{.Tag}}"
its parent is:
/usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
hope this helps

**Comment by karolz-ms** [comment]
@okarika thank you, this helps a lot.

What version of the Docker extension are you using? Are you using any other, Docker-related extensions? The command that you mentioned, that is 

`docker images --filter "dangling=false" --format "{{.ID}} {{.Repository}} {{.Tag}}"`

 is not used/issued by our extension. 

If you restart the machine and issue the same command from command line, does it also cause `dockerd` to consume a lot of CPU?

**Comment by okarika** [comment]
Thanks Karol,

your answer helped a lot!

Seems to be clear that the source of the problem is an other extension: docker-explorer.

Sorry for bothering you

Thanks again

Tibor Kovács

**Comment by karolz-ms** [comment]
No worries, you are very welcome.
