### ISSUE TITLE
vscode debugging docker /lib64/ld-linux-x86-64.so.2 issue macos m1

### ISSUE THREAD

**Issue by Jonatthu** [microsoft/vscode-docker#2919]
System:
MacOs m1 11.3
.net 5.0
docker 3.3.2
vscode insiders

I am able to debug using the normal debugger for dll.
I am able to build a docker image and run it and hit my swagger in the 5000 port

But when I am trying to debug the image with docker, this does not work, and throws the next message:
```
Starting: "docker" exec -i backend-dev /remote_debugger/vsdbg --interpreter=vscode
Error from pipe program 'docker': /lib64/ld-linux-x86-64.so.2: No such file or directory
The pipe program 'docker' exited unexpectedly with code 255.
```

Debugging with the same configurations works on windows for docker.

I am thinking I might missing an argument or something to make it work on m1.

**Comment by jp4u** [comment]
I am also experiencing the same issue. It works on my Windows PC but not on my Mac M1

**Comment by Jonatthu** [comment]
@karolz-ms any hints or tips?

**Comment by karolz-ms** [comment]
@philliphoff do you know what is the state of .NET debugger support for M1 Macs?

**Comment by Jonatthu** [comment]
@karolz-ms the debugger works on the M1 for targeting dlls, but it seems more like a vscode + docker + debugger thing.
Just to clarify docker is building and running the image just fine.

**Comment by karolz-ms** [comment]
@Jonatthu understood, thanks. We are probably injecting wrong debugger bits into the container (wrong architecture). 

@philliphoff is our expert on all things Mac so I'd like to pick up his brain first, that's all.

**Comment by Jonatthu** [comment]
@karolz-ms Thanks!
@philliphoff if you need any sample of my files or task.json or launch.json I am open to share.
But as a background on this, I am using the generated files from vscode to make it work.
Windows works just fine, and mac intel as well, the only problem is mac M1.

The lib is not finding is /lib64/ld-linux-x86-64.so.2

Maybe is trying to look from the intel architecture and we just need to make it understand it must go through rosetta or something like that. I am not an expert but I hope I can help to find out this.

**Comment by philliphoff** [comment]
At the moment, we don't have a `arm64` flavor of `vsdbg` to insert into `arm64` containers.  (The tools currently blindly install the `amd64` debugger into the containers, which generate the errors being seen.)  As soon as we do, we'll be able to update our tools to choose the debugger that matches the architecture of container being run.

**Comment by Jonatthu** [comment]
@philliphoff Where is this issue being tracked?

**Comment by philliphoff** [comment]
#2884.

**Comment by philliphoff** [comment]
Closing this in favor of #2884.
