### ISSUE TITLE
$$

### ISSUE THREAD

**Issue by sollo11** [microsoft/vscode-docker#2926]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.runTask
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.12.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.56.0
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:2:5108241
fulfilled extension.bundle.js:2:5102121
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
Same as https://github.com/microsoft/vscode-docker/issues/2662 Workaround is to restart VSCode. Sorry!
