### ISSUE TITLE
"Unknown flag: --subscription-id" when deploying to Azure Container Instances

### ISSUE THREAD

**Issue by rw3iss** [microsoft/vscode-docker#2927]
Does this occur consistently? Yes

Repro steps:
1. In VSCode Docker extension, build and tag an image, push it, then under registries choose 'Deploy Image to Azure Container Service'.
2. In the dialog to create or choose a registry name, enter anything.

Version: 1.12.1
OS: Windows through WSL 2
OS Release: 5.4.72-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.56.0
Docker Desktop v3.3.3, Docker Engine v20.10.6
Language: en

Errors:
```
Creating ACI context "brt-context"...
Error: Process 'docker context create aci brt-context --subscripti...' exited with code 125
Error: unknown flag: --subscription-id
See 'docker context create --help'.
```

Any idea why the parameter mishap?

**Comment by karolz-ms** [comment]
@rw3iss which version of Docker are you using?

**Comment by rw3iss** [comment]
@karolz-ms Docker Desktop v3.3.3, Docker Engine v20.10.6

**Comment by karolz-ms** [comment]
In the context of Remote-WSL session the extension is having trouble logging in to the registry:

```shell
Error: Process 'docker login "https://someregistry.azurecr.io" --userna...' exited with code 1
Error: Error saving credentials: error storing credentials - err: exit status 1, out: ``

Error: Unable to determine ports to expose. The error is: Process 'docker --context default pull someregistry.azurecr.io/h...' exited with code 1
Error: Error response from daemon: Head https://someregistry.azurecr.io/v2/webappsample/manifests/0.4: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

**Comment by karolz-ms** [comment]
@rw3iss the error you have seen makes me think the extension was invoking an older docker executable in the context of WSL2 session, one that did not come with Docker Desktop v3.3.3 and did not have ACI support. On my machine, using "integrated" docker executable (injected into WSL2 environment by Docker Desktop) the `docker context create aci` command recognizes `--subscription-id` parameter even if an ACI context is in use and if the command is issued from Docker environment.

Could you try `which docker` and `docker --version` in the WSL2 environment and let us know what is the output? The binary on my machine is `/usr/bin/docker` which is a link to `/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker`
