### ISSUE TITLE
Update the Azure Icon in our Extension

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2928]
As Azure release a new icon, we should update our existing icon. 

https://azure.microsoft.com/en-us/blog/a-fluent-new-look-for-the-azure-icon/

**Comment by philliphoff** [comment]
@ucheNkadiCode Which icon are you referring to?  We have one ACR icon (used for each connected ACR), but it's not clear if/how it changes.  The Azure account node (under which the individual subscriptions sit), is based on a base node from [vscode-azureextensionui](https://github.com/microsoft/vscode-azuretools/tree/main/ui), so the icon will need to change there.

**Comment by philliphoff** [comment]
I filed [vscode-azuretools#921](https://github.com/microsoft/vscode-azuretools/issues/921) to see if they'll change the common icon.
