### ISSUE TITLE
@

### ISSUE THREAD

**Issue by leeeunok** [microsoft/vscode-docker#2938]
Issue Type: <b>Feature Request</b>

#

Extension version: 1.12.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by karolz-ms** [comment]
I assume this was opened by mistake.. feel free to re-open as necessary, but please provide more information about what the request is
