### ISSUE TITLE
There is a stopped container after executing "Compose Up" for an express app project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2940]
**OS:** Mac/Linux
**Build Version:** 20210513.4

**Repro Steps:**

1. Create an Express App project and open it in VS Code -> Command Palette -> Add Docker files to workspace 
-> Node.js -> Choose a package.json file in the `node_modules` directory -> Enter port -> Yes.
2. Right click the docker-compose.yml file -> Select "Compose Up".
3. Check whether there is a running container.

**Expect:**
There is a running container.

**Actual:**
There is a stopped container.
![Screen Shot 2021-05-14 at 5 45 34 PM](https://user-images.githubusercontent.com/62053665/118253454-86a99e80-b4dc-11eb-841b-afe8ae01cf95.png)

**More Info:**
This issue also reproduces for docker-compose.debug.yml file

**Comment by karolz-ms** [comment]
@v-mengwe can you share the app? What are the logs from the stopped container, any clues why it stopped?

**Comment by v-mengwe** [comment]
Create an Express App project with following commands:
```
npm install -g express-generator
express myExpressApp
cd myExpressApp
npm install
SET DEBUG=myexpressapp:*
npm start
```
Logs after executing "Compose Up" for the docker-compose.yml file:

> Executing task: docker-compose -f "docker-compose.yml" up -d --build <
> 
> Creating network "myexpressapp_default" with the default driver
> Building onfinished
> Sending build context to Docker daemon  14.85kB
> Step 1/8 : FROM node:12.18-alpine
> 12.18-alpine: Pulling from library/node
> cbdbe7a5bc2a: Pull complete 
> 6282c10629b6: Pull complete 
> 24f383844fee: Pull complete 
> 22e94daf4797: Pull complete 
> Digest: sha256:abe347411c713e4a66846f351d426d65e2c93d084d59bc04b25954f1cde11df0
> Status: Downloaded newer image for node:12.18-alpine
>  ---> e13d60032d4d
> Step 2/8 : ENV NODE_ENV=production
>  ---> Running in dfd97166cc03
> Removing intermediate container dfd97166cc03
>  ---> 0ab268515f5f
> Step 3/8 : WORKDIR /usr/src/app
>  ---> Running in 37491c198454
> Removing intermediate container 37491c198454
>  ---> d8134b2d7ae0
> Step 4/8 : COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
>  ---> 6f0de369fda6
> Step 5/8 : RUN npm install --production --silent && mv node_modules ../
>  ---> Running in 4033823f4687
> added 1 package from 2 contributors and audited 50 packages in 1.032s
> found 17 vulnerabilities (4 low, 1 moderate, 9 high, 3 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details
> Removing intermediate container 4033823f4687
>  ---> f3cbea6f993e
> Step 6/8 : COPY . .
>  ---> 825a659e3c92
> Step 7/8 : EXPOSE 3000
>  ---> Running in 212cff39c2c0
> Removing intermediate container 212cff39c2c0
>  ---> ba973a8c27bf
> Step 8/8 : CMD ["npm", "start"]
>  ---> Running in 1c116dc36374
> Removing intermediate container 1c116dc36374
>  ---> 8fffe00a6ab8
> Successfully built 8fffe00a6ab8
> Successfully tagged onfinished:latest
> Creating myexpressapp_onfinished_1 ... done
> 
> Terminal will be reused by tasks, press any key to close it.

There is log after executing "Compose Logs" to the stopped container:
>  Executing task: docker-compose -f 'docker-compose.yml' -p 'myexpressapp' logs -f --tail 1000 <
> 
> Attaching to myexpressapp_onfinished_1
> onfinished_1  | npm ERR! missing script: start
> onfinished_1  | 
> onfinished_1  | npm ERR! A complete log of this run can be found in:
> onfinished_1  | npm ERR!     /root/.npm/_logs/2021-05-15T08_44_11_660Z-debug.log
> myexpressapp_onfinished_1 exited with code 1
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by karolz-ms** [comment]
I cannot reproduce this issue using latest VS Code Docker extension bits and latest Express app generator (4.16.1), sorry. The application is running fine and can be opened in the browser as expected.

One remark regarding repro steps: in step 1 you say "Choose a package.json file in the node_modules directory". There should be no packages.json file in node_modules directory, and even if there is, that is wrong file to choose. You should always use packages.json file from the root of the repository, not from node_modules directory.
