### ISSUE TITLE
No running container shows in container view after deploying image to ACI

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2941]
**OS:** Windows
**Build Version:** 20210513.4

**Repro Steps:**
1. Right click one image of registries view -> Deploy Image to Azure Container Instances... -> Create a new ACI.
2. Check whether there is a running container in container view or not.

**Expect:**
There is a running container in container view.

**Actual:**
No running container shows in container view.
![image](https://user-images.githubusercontent.com/45614674/118258167-20277f00-b4e2-11eb-9c39-f22405f34988.png)

**More Info:**
There is a running container if checking all containers using command, see details from above screen.

**Comment by karolz-ms** [comment]
May be related to https://github.com/microsoft/vscode-docker/issues/2933

**Comment by karolz-ms** [comment]
I can confirm that the bug is reproducible as described

**Comment by karolz-ms** [comment]
Seems an external (Docker node SDK) issue.

**Comment by byaruhaf** [comment]
Having the same issue

<img width="1787" alt="Screenshot 2021-06-29 at 05 00 09" src="https://user-images.githubusercontent.com/4116539/123725561-ee525800-d896-11eb-820e-9260e3f9e1af.png">

**Comment by bwateratmsft** [comment]
I'm still able to reproduce.

**Comment by bwateratmsft** [comment]
Marking blocked external for now: https://github.com/docker/node-sdk/issues/67

**Comment by bwateratmsft** [comment]
The upstream issue (https://github.com/docker/node-sdk/issues/67) has been fixed in Docker Desktop 4.2.0.
