### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by dewens12** [microsoft/vscode-docker#2948]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "ewens" --password-stdin' exited with code 1
Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied

Version: 1.12.1
OS: linux
OS Release: 4.18.0-293.el8.x86_64
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4668801
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Socket.<anonymous> child_process.js:439:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by karolz-ms** [comment]
@dewens12 are you able to pull the image using docker command line? Have you followed the steps to enable Docker CLI for non-root access?
