### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by shuoshuren1996** [microsoft/vscode-docker#2950]
When I attach the to running container, I received a hint "Docker version 17.12.0 or later required". 
However,  when I tried to install, it told me "The Docker Desktop installation is started. Complete the installation and then start Docker Desktop" and  the terminal showed that "The terminal process failed to launch: Starting directory (cwd) "/Users/admin" does not exist."
How to solve this problem?

**Comment by karolz-ms** [comment]
@shuoshuren1996 what is your OS? Does re-starting the machine and restarting Docker Desktop installation help?

**Comment by shuoshuren1996** [comment]
> @shuoshuren1996 what is your OS? Does re-starting the machine and restarting Docker Desktop installation help?
Macos. I used vscode to connect SSH server and the docker was running on the server. I have tried restart the machine and VSCode but it doesn't work.

**Comment by shuoshuren1996** [comment]
> OK, thanks. Let me make sure I understood correctly:
> 
> 1. You used Remote-SSH extension to open VS Code session to a remote server.
> 
> _What is the server OS and version of Docker running there?_
> _Did you install [VS Code Docker extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker) in this remote session?_
> 
> 1. Then you did "Attach VS Code to container" gesture (and NOT "Attach Shell" gesture), is that correct?
> 
> _What are you trying to achieve by invoking "Attach VS Code to container"?_

TXS
1. SERVER: Debian 9 linux 4.14; I have installed the extension.
2. Correct
I can only use vim to edit files in docker container, so I prefer to attach vscode to container

**Comment by karolz-ms** [comment]
The "Attach VS Code to container" gesture is owned by a sister team. I would suggest copying the information from this issue, include the version of Docker running on the server (is it 17.12.0 or newer?), and opening a new issue at https://github.com/Microsoft/vscode-remote-release

Sorry for the hassle; but  I can not transfer the issue automatically 😔
