### ISSUE TITLE
Docker Start Page Photos not rendered in Codespaces

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2952]
![image](https://user-images.githubusercontent.com/20650058/118681790-b5fa2d00-b7b4-11eb-8f8b-8113b4fb83b3.png)

I'm not sure why, but I'm getting just squares when the Docker Start Page is fired.

**Comment by karolz-ms** [comment]
No more tears, @ucheNkadiCode! ☺️

**Comment by ucheNkadiCode** [comment]
@karolz-ms, well there are still tears, but now they're tears of joy 😭
