### ISSUE TITLE
There is an error under the repository of Azure registry after deleting the image

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#2968]
**OS:** All
**Build Version:** 1.13.0

**Repro Steps:**
1. Make sure connected Azure registry.
2. Right click a image -> Push -> Azure -> Select a registry (e.g. nicoledocker) -> Enter default value.
3. Navigate to Registry view -> Expand the Azure -> Expand "nicoledocker" registry ->Expand the repository -> image.
4. Right click the image -> Delete Image.
5. Check whether there is an error under the repository of Azure registry or not.

**Expect:**
There is no error under the repository of Azure registry after deleting the image.

**Actual:**
There is an error under the repository of Azure registry after deleting the image.
![image](https://user-images.githubusercontent.com/57662131/119456597-6942c300-bd6d-11eb-8374-cf2cb538d02a.png)

**More Info:**
1. The image is deleted successfully.
![image](https://user-images.githubusercontent.com/57662131/119457019-ce96b400-bd6d-11eb-9989-2ab3184d749f.png)
2. This issue can be fixed by refreshing the Registry view.

**Comment by karolz-ms** [comment]
Bumping up the priority. I see this every time I delete an image from a registry and it makes us look sloppy.
