### ISSUE TITLE
Python app using non-root user is not working with Azure App Service with custom location

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#2973]
Related to #2972 but opening a separate issue just for Python.

The default scaffolded Dockerfile for Python is starting the application using a non-root user when the port is > 1024.
When this container image is deployed to a custom location, the application is not working. But at the same time if port 80 is used and the application is started using root user, it works.

**Comment by karolz-ms** [comment]
https://github.com/microsoft/vscode-docker/pull/3046 should fix this one too
