### ISSUE TITLE
"View logs" container function try to open Powershell from a linux machine

### ISSUE THREAD

**Issue by thomascaillier** [microsoft/vscode-docker#2987]
Issue Type: <b>Bug</b>

Open VS Code from a Windows machine.
Use the Microsoft Remote - SSH extension to open a VS Code running on a linux machine.
Once connected on a Linux machine, install the Docker extension.
Run a Docker container.
From the Docker extension, right click on this container and click on "View Logs".
Here is the failure : "The terminal process failed to launch: Path to shell executable "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" does not exist."

Extension version: 1.13.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 3.10.0-1062.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.14GB free)|
|Process Argv|--crash-reporter-id 28dab68f-2e7f-4a6f-a188-3907a6f79fdb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sidltestauto|
|OS|Linux x64 3.10.0-1062.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz (4 x 2400)|
|Memory (System)|15.51GB (10.01GB free)|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30312182
vscod805:30301674

```

</details>

**Comment by karolz-ms** [comment]
Thank you, @thomascaillier 

Could be related to https://github.com/microsoft/vscode-docker/issues/2945

**Comment by karolz-ms** [comment]
After some investigation I am quite sure this is indeed the same issue as https://github.com/microsoft/vscode-docker/issues/2945
