### ISSUE TITLE
Docker login

### ISSUE THREAD

**Issue by dewens12** [microsoft/vscode-docker#2988]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "ewens" --password-stdin' exited with code 1
Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied

Version: 1.13.0
OS: linux
OS Release: 4.18.0-305.3.1.el8_4.x86_64
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4956333
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:467:12
maybeClose child_process.js:1048:16
Socket.<anonymous> child_process.js:439:11
Socket.emit events.js:315:20
Socket.EventEmitter.emit domain.js:467:12
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by karolz-ms** [comment]
@dewens12 have you [enabled non-root management access to Docker](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)?
