### ISSUE TITLE
Fail to open the web page after deploying image (Express App) to Azure App Service with custom location

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2995]
**OS:** Windows 10
**Build Version:** 20210609.2

**Repro Steps:**
1. Right click Dockerfile for Express App-> Build Image.
2. Right click this image in image view -> Push -> Azure -> Select a registry to push.
3. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service with a custom location.
4. When done, click "Open Site" button in the notification.
5. Check whether the web page can be opened successfully.

**Expect:**
Succeed to open the web page.

**Actual:**
Fail to open the web page with an error “HTTP ERROR 404”.
![image](https://user-images.githubusercontent.com/45614674/121665228-e5ae0380-cada-11eb-890c-8aaa684bf616.png)

**More Info:**
This issue does not reproduce on the previous released build.

**Comment by ravipal** [comment]
@v-ruizh are you using port 80 for this app? If not we have another bug to track this issue.

I just tried to deploy an express app that listening on port 80 and it works. Also note that the old custom environment is busted and throws exception during deployment, so use the new location (arc2-rg)
