### ISSUE TITLE
not able to deploy app

### ISSUE THREAD

**Issue by kundan1974** [microsoft/vscode-docker#3000]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.13.0
OS: darwin
OS Release: 20.4.0
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1394608
extension.bundle.js:2:1382442
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
Duplicate of #2347
