### ISSUE TITLE
[Feature Request] Auto start/stop containers when opening/closing vscode

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode-docker#3005]
My workspace defines various `docker-compose.yml` files - e.g. to start a database, or some other service which I need while coding. So when I open the workspace, I first have to start those containers.

Please consider a feature which auto-starts specific containers when the workspace is opened, and auto-stops/removes them when the workspace is closed.

That would greatly simplify development.

---
The compose files could be specified in a `project/.vscode/.docker` config file, e.g.:
````json
{
  "autoUp": [
    "src/foo/docker-compose.yml"
    "src/bar/docker-compose.yml"
  ],
  "autoDown": [
    "src/foo/docker-compose.yml"
  ],
  "autoRemove": [
    "src/bar/docker-compose.yml"
  ]
}
````

(That would be better than specifying it in the `project/.vscode/settings.json` as that would be checked into source control, whereas the `project/.vscode/.docker` config file is a per-developer preference - e.g. some devs must start the database, whereas others may start redis or whatever.)

**Comment by karolz-ms** [comment]
@lonix1 what you can do today is use `runOn: folderOpen` run option to run a VS Code task when a folder is open: https://code.visualstudio.com/docs/editor/tasks#_run-behavior
Unfortunately there does not seem to be an equivalent mechanism to run a task on folder close, but you can run one manually when you are done working with a workspace. For myself I created a keyboard shortcut for `Tasks: Run Task` command that makes this even simpler:

```json
{
    "key": "alt+t",
    "command": "workbench.action.tasks.runTask"
}
```

The automatically-run task can be anything, but in your scenario it makes sense to use a Docker Compose task provided by the extension: https://code.visualstudio.com/docs/containers/reference#_docker-compose-task

Let us know if that helps!
