### ISSUE TITLE
Navigate to the webpage which opened previously by debugging after clicking "Open in Browser" for a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3006]
**OS:** Mac
**Build Version:** 20210615.1

**Repro Steps:**

1. Open a Node.js project in VS Code -> Add Docker files support including docker-compose files.
2. Debug -> Succeed to open a webpage in the browser.
3. Navigate the "CONTAINERS" node -> Right click the running container -> Select "Open in Browser".
4. Check whether open a new webpage in the browser.

**Expect:**
Open a new webpage in the browser.

**Actual:**
Navigate to the webpage which opened previously by debugging.

**More Info:**
1. This issue also reproduces for Python/.NET Core project.
2. This issue only reproduces on Mac.

**Comment by karolz-ms** [comment]
It is sort-of an external issue, or more precisely, Safari behavior. With Microsoft Edge as default browser on my Mac a new tab is open every time, as on other platforms.
