### ISSUE TITLE
Error: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 127

### ISSUE THREAD

**Issue by modivis-routethis** [microsoft/vscode-docker#3010]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 127
Error Message: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 127
Error: /bin/sh: docker-compose: command not found

Version: 1.13.0
OS: darwin
OS Release: 20.4.0
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4956333
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:467:12
maybeClose child_process.js:1048:16
Socket.<anonymous> child_process.js:439:11
Socket.emit events.js:315:20
Socket.EventEmitter.emit domain.js:467:12
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by karolz-ms** [comment]
@modivis-routethis is `docker-compose` installed and working when you try to use it from command line? Can you add repro steps?
