### ISSUE TITLE
[Remote Codespaces] The running container is not removed automatically after stopping it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3011]
**Environment:** GitHub Codespaces (Remote) 
**Build Version:** 20210615.1

**Repro Steps:**
1. Run `docker pull registry`.
2. The "registry:latest" image shows automatically in "IMAGES" view -> Right click the image -> Run.
3. The running "registry:latest" container shows in "CONTAINERS" view -> Right click the container -> Stop.
4. Check whether the running container is removed automatically.

**Expect:**
The running container is removed automatically.

**Actual:**
The running container stopped but it is not removed automatically.
![stop](https://user-images.githubusercontent.com/57662131/122523363-848daf00-d049-11eb-99a1-0857b2a4d764.gif)

**More Info:**
1. This issue doesn't reproduce for Windows/Mac/Linux OS.
2. This issue doesn't reproduce for Local Codespaces.

**Comment by karolz-ms** [comment]
Cannot reproduce (assuming "remote codespace" means accessing Codespace via web UI)

I noticed from the video that `docker run` command issued in step 2 does not have `--rm` flag. This flag is included by default and causes Docker to remove the container automatically when it is stopped. I suspect you might have customized the run command to omit the `--rm` flag and that is what is causing the observed behavior.
