### ISSUE TITLE
[Remote Codespaces] Nothing copied from the notification after clicking "Copy&Open" button

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3012]
**Environment:** GitHub Codespaces (Remote) 
**Build Version:** 20210615.1

**Repro Steps:**
1. Create a Express App -> Open in VS Code -> Add Docker files to it.
2. Right click Dockerfile file -> Build Image.
3. Navigate to "IMAGES" view -> Right click "myexpressapp:latest" image -> Push it to DockerHub.
4. Navigate to " REGISTRYS" view -> Expand DockerHub.
5. Right click "myexpressapp:latest" registry -> Deploy it to Azure App Service.
6. Click "Copy&Open" button when popping up a notification -> Navigate to the webpage -> Paste it.
![image](https://user-images.githubusercontent.com/57662131/122538663-5ca64780-d059-11eb-8d17-869f66f7fc6f.png)
7. Check whether the URL copied from the notification. 

**Expect:**
The URL copied from the notification. 

**Actual:**
Nothing copied from the notification. 

**More Info:**
1. This issue doesn't reproduce for Windows/Mac/Linux OS.
2. This issue doesn't reproduce for Local Codespaces.

**Comment by karolz-ms** [comment]
Trying to figure out what kind of (write) access to clipboard is possible when a Codespace is accessed from a browser...

**Comment by karolz-ms** [comment]
Edge/Chrome should not have any issues, but Safari does--Safari does not support browser clipboard API at all.

That said, step 5 does not work for me: the `Deploy image to Azure App Service` command is not available when accessing a Codespace via a browser. Following up with @ejizba  and @wwlorey to see if this is a known issue...

**Comment by karolz-ms** [comment]
Blocked by https://github.com/microsoft/vscode-docker/issues/3025

**Comment by karolz-ms** [comment]
I have confirmed that the scenario works with Microsoft Edge. It should also work with Google Chrome.

The problem is, Safari browser does not support clipboard API. I spoke to VS Code core developers and they confirmed it is a known issue that limits many Codespaces scenarios. This is yet another example. Nothing we can do until Safari adds clipboard API support.
