### ISSUE TITLE
[Local Codespaces] Open a webpage in browser after clicking "Preview in Editor" button in notification

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3013]
**Environment:** Local Codespaces
**Build Version:** 20210615.1

**Repro Steps:**

1. Run `docker pull registry`.
2. The "registry:latest" image shows automatically in "IMAGES" view -> Right click the image -> Run.
3. Click "Preview in Editor" button when popping a notification like below.
   ![image](https://user-images.githubusercontent.com/62053665/122533758-7d1fd300-d054-11eb-9cc5-7556bd3d28ac.png)
4. Check whether preview a webpage in editor.

**Expect:**
Preview a webpage in editor.

**Actual:**
Open a webpage in browser.
![run](https://user-images.githubusercontent.com/62053665/122534888-907f6e00-d055-11eb-8114-2a49d9958e8c.gif)

**More Info:**
There is no "Preview in Editor" button on **Remote Codespaces** environment.
![image](https://user-images.githubusercontent.com/62053665/122534325-fddecf00-d054-11eb-9dfe-0045441aa185.png)

**Comment by karolz-ms** [comment]
We do not pop up this notification and I am not even 100% sure what "preview in editor" is supposed to do. 

Resolving as external, since I do not have rights to transfer the issue to https://github.com/microsoft/vscode automatically--please re-open there--thank you!
