### ISSUE TITLE
[Suggestion] Download and install the latest Docker Desktop version if installing it via VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3014]
**OS:** Win 10
**Build Version:** 20210615.1

**Repro Steps:**
1. Make sure Docker Desktop is not installed on the machine.
2. Open the Docker view, a notification will be shown.
3. Click "Install" button to download and install Docker Desktop.
4. Start Docker Desktop and check its version.

**Actual:**
The Docker Desktop version is **3.3.1** which is a older version, we need to download and install the update(**3.4.0**) manually.
![image](https://user-images.githubusercontent.com/45614674/122544960-e22cf600-d05f-11eb-8c6f-bdfd2ba71e25.png)

**Suggestion:**
Download and install the latest Docker Desktop version if installing it via VS Code.

**Comment by karolz-ms** [comment]
This might be an external issue, we have a conversation started with @nebuk89 to determine if we are using wrong  URLs, or something got stale on the Docker side. These are the URLs that we use:

Windows: https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe?source=vscode
Mac: https://download.docker.com/mac/stable/Docker.dmg?source=vscode
Linux: https://get.docker.com?source=vscode

**Comment by karolz-ms** [comment]
This was a bug on the Docker (web) side. It should be fixed now
