### ISSUE TITLE
The results are inconsistent when connecting a GitLab registry that between entering a space and 123 for GitLab personal access token

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3016]
**OS:** All
**Build Version:** 20210615.1

**Repro Steps:**

1. Navigate to "REGISTRIES" node -> Click "Connect Registry" icon -> Select "GitLab" -> Enter a username, e.g. "test" -> Enter a space when asking for GitLab personal access token -> Expand the GitLab -> Check the result.
2. Click "Connect Registry" icon -> Select "GitLab" -> Enter a username, e.g. "test new" -> Enter `123` when asking for GitLab personal access token -> Expand the GitLab -> Check the result.
3. Check whether the results of step 1 and step 2 are consistent.

 
**Expect:**
The results of step 1 and step 2 are consistent.

**Actual:**
The results of step 1 and step 2 are inconsistent.
![image](https://user-images.githubusercontent.com/62053665/122550488-4bb00300-d066-11eb-84a4-d930f98c466c.png)

**Comment by karolz-ms** [comment]
The GitLab registry support is not great at the moment. We want to improve it comprehensively as part of [third party registry support workstream](https://github.com/microsoft/vscode-docker/issues/869).

I am going to close this issue for now; we can revisit if it is still a problem when #869 is done.
