### ISSUE TITLE
It will add a Linux image in Dockerfile when adding Docker files (Windows OS selected) for a .NET project 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3018]
**OS:** Win 10
**Build Version:** 20210615.1

**Repro Steps:**
1. Switch the Docker Desktop to windows container.
2. Create and open a .NET Core MVC project in VS Code.
3. Add Docker files to this project with **Windows** OS selected.
4. Check the image name in Dockerfile.

**Expect:**
The image name is "xxx/aspnet:5.0".
![image](https://user-images.githubusercontent.com/45614674/122562440-a69d2680-d075-11eb-8700-b693b4f9cc4b.png)

**Actual:**
The image name is "xxx/aspnet:5.0-focal" which is a Linux image.
![image](https://user-images.githubusercontent.com/45614674/122562428-a2710900-d075-11eb-889f-2a2bee7d44de.png)

**More Info:**
1. Fail to debug the project with the default added image in windows container. 
2. It seems a regression from this PR https://github.com/microsoft/vscode-docker/pull/2996.

**Comment by karolz-ms** [comment]
@v-ruizh correct, we switched to Ubuntu-based images because the default image does not contain binaries (`ps`) necessary for debugger attach (process picker) to work. 

We should discuss what to do here in 1.15 timeframe
