### ISSUE TITLE
There is no web page opening when debugging a .NET 6.0 MVC project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3019]
**OS:** Win 10
**Build Version:** 20210615.1
**.NET SDK:** **6.0.100-preview.5.21302.13**

**Repro Steps:**
1. Create and open a .NET 6.0 MVC project in VS Code.
2. Add Docker files to this project.
3. Debug this project with "Docker .NET Core Launch" configuration.
4. Check whether there is a web page opening.

**Expect:**
There is a web page opening when debugging this .NET project.
![image](https://user-images.githubusercontent.com/45614674/122570382-48287600-d07e-11eb-9786-eae044cd5e7b.png)

**Actual:**
There is no web page opening when debugging this .NET 6.0 project.

**More Info:**
1. Right click the docker-compose.yml and execute "compose up" action for it -> Execute "Open in Browser" action for the running container in container view -> The web page can be opened successfully.
2. This issue does not reproduce for .NET 5.0 MVC project.

**Comment by bwateratmsft** [comment]
Found the root cause. The "Now listening..." output string is different now; in the past it was emitted on a line all by itself but now has more stuff. We need to change the match regex.
