### ISSUE TITLE
Docker exception pushing via VSCode in AzureContainerRegistry

### ISSUE THREAD

**Issue by FrancescoDiMaggio** [microsoft/vscode-docker#3022]
Does this occur consistently? 
Repro steps:

1. Build image locally using Dockerfile
2. Push Image using Docker extension via VSCode in AzureContainerRegistry

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login "https://touchdomainweb.azurecr.io" -...' exited with code 1
Error: Error response from daemon: Get https://touchdomainweb.azurecr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.57.0
Language: it

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4956333
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:467:12
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
I cannot reproduce. @FrancescoDiMaggio could you please try with latest version of VS Code and Docker extension (1.57.1 and 1.14, respectively)? What version of Docker Desktop software are you using? Does pushing the image from command line (using `docker` CLI) work?
