### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by bhrpro** [microsoft/vscode-docker#3023]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "bhrpro" --password-stdin' exited with code 1
Error: WARNING: Error loading config file: /home/---/.docker/config.json: open /home/---/.docker/config.json: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.14.0
OS: linux
OS Release: 5.4.0-74-generic
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@bhrpro did you follow instructions to enable [non-root access to Docker](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) ?
