### ISSUE TITLE
docker daemon is not running.

### ISSUE THREAD

**Issue by djibal** [microsoft/vscode-docker#3027]
Operation System(Microsoft Windows)![Version 10.0.19043.1081]

docker run -d -p 80:80 
>Error occurred in: commandLine

Error reproduction in:

> Docker daemon is not running an error occurred from in:
"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: (The system cannot find the file specified).

(docker: error during connect:
> This error may indicate that the docker daemon is not running).

Docker version ! > [version 
20.10.6, build 370c289]

**Comment by karolz-ms** [comment]
@djibal Have you installed [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/install/) Did it install successfully?

**Comment by djibal** [comment]
> @karolz-ms  I did install Docker desktop but still getting error from command prompt.

**Comment by karolz-ms** [comment]
OK that means something wrong has happened during Docker Desktop installation. I would suggest trying to clean the Docker installation by rebooting, uninstalling Docker Desktop, rebooting, re-downloading the Docker installation package, and reinstalling it.  Then try some Docker commands from command line.

If Docker command line still does not work, please open an issue at https://github.com/docker/for-win

If the command line works, but VS Code Docker extension gives you trouble, please open a new issue in this repo. Hope this helps!
