### ISSUE TITLE
Publish to the Cloud / Azure App Service Broken Link

### ISSUE THREAD

**Issue by dogutumerdem** [microsoft/vscode-docker#3030]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.14.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerHubAccountTreeItem.<anonymous> extension.bundle.js:2:5029307
fulfilled extension.bundle.js:2:5023140
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
@dogutumerdem thanks for reporting the issue. Can you please add repro steps, or tell us what is the link that results in 404 error?
