### ISSUE TITLE
s

### ISSUE THREAD

**Issue by fawadali1** [microsoft/vscode-docker#3031]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.contexts.inspect
Error type: 1
Error Message: Process 'docker context inspect default' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.14.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@fawadali1 did you install Docker Desktop for Windows? Does Docker work from command line (e.g. if you do `docker context inspect` from command line)?
