### ISSUE TITLE
push fail

### ISSUE THREAD

**Issue by gomes2191** [microsoft/vscode-docker#3032]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login --username "gomes2191" --password-std...' exited with code 1
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.14.0
OS: linux
OS Release: 5.8.0-59-generic
Product: Visual Studio Code
Product Version: 1.57.1
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@gomes2191 what kind of registry are you using? Are you sure it is up and running? If you try to log in to the registry using Docker CLI, does it work?

**Comment by gomes2191** [comment]
I closed the application and logged in again and it started working again.
