### ISSUE TITLE
Extension tries to resolve remote hostname with DNS instead of using ~/.ssh/config

### ISSUE THREAD

**Issue by SirFerdek** [microsoft/vscode-docker#3038]
- VSCode Version: 1.58.0-insider
- Local OS Version: Windows 10 Enterprise (Windows_NT x64 10.0.18363)
- Remote OS Version (doesn't really matter): Linux RHEL 7.9
- Extension version: v1.14.0

I am trying to follow the configuration guide on how to [reopen local workspace with Remote Containers extension](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) and I stumbled upon this bug.

### TL;DR: 

**It seems that the extension is trying to literally resolve configured hostname of remote Docker host instead of leaving it off to SSH to take care of. DNS resolution fails because this host's domain suffix is not in DNS Search Path configured on my system**

### Longer description:

I have ssh configured on my Windows host in this way:

`~/.ssh/config`

```
Host *
    User remoteUser

Host remoteHost
    Hostname %h.internal.network.net

```

Windows' ssh-agent is running and Docker Desktop is installed. In this way, from PowerShell terminal, I can execute the following commands to work with remote Docker host:

```
PS> $Env:DOCKER_HOST = "ssh://remoteHost"
PS> docker ps -a
CONTAINER ID   IMAGE [...]
```

It basically correctly connects to remote host and executes Docker commands there.

We have matching Workspace setting in Docker Extension for this feature:

`.vscode/settings.json`

```
{
    "docker.host": "ssh://remoteHost"
}
```

Unortunately, this setting fails with "Error: Request timed out" printed in sidebar and following output in Docker Extension log:

```
The Docker extension will try to connect to 'ssh://remoteHost', via context 'default'.
```

And nothing else is printed there. Trying to debug this, I took a look at other possible log sources and found this line repeated many many times in `Log (Window)`:

```
[2021-07-02 16:07:32.481] [renderer1] [error] getaddrinfo ENOTFOUND remoteHost: Error: getaddrinfo ENOTFOUND remoteHost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

When I changed the `docker.host` to `remoteHost.internal.network.net` the extension started to work correctly.

**Comment by karolz-ms** [comment]
Yes, I am sorry, this is a know limitation of the Docker extension https://code.visualstudio.com/docs/containers/ssh#_tips
Because of some implementation details, we do not handle host aliases in SSH config at the moment.

We are still counting on [Docker Node SDK](https://github.com/docker/node-sdk) to support local Docker contexts eventually, including full support for remote Docker backends, which would make this problem go away, but that has not happened yet.

**Comment by SirFerdek** [comment]
Thank you for quick answer and sorry for not reading the manual carefully enough, I must have missed this.

Have a nice evening. :)
