### ISSUE TITLE
docker multi-stages builds with wsl2 

### ISSUE THREAD

**Issue by NDzuki** [microsoft/vscode-docker#3039]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: 

Version: 1.14.0
OS: linux
OS Release: 5.10.16.3-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.57.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@NDzuki if you issue the same command `docker context ls --format="{{json .}}"` from terminal, does it work?
