### ISSUE TITLE
Ability to customize Docker Commands through settings.json with the same/similar schema to VS code tasks

### ISSUE THREAD

**Issue by alexmerm** [microsoft/vscode-docker#3042]
I love the easy customization that you can do with the Docker-Extension provided tasks, but I use the commands a lot more often. While we can customize them by overwriting the actual text of the command, it would be nice to be able to use the schema that the Tasks interface provides. 
For example, in the tasks configuration, you can specify multiple docker-compose to operate on, which if implemented in the commands could mean only one line for Docker-compose up and down instead of having to overwrite both commands. (Specifically I am referencing this task-schema https://code.visualstudio.com/docs/containers/reference#_docker-compose-task)

**Comment by karolz-ms** [comment]
@alexmerm interesting idea. Could you give us an example for what would you like to be able to put in the settings file, with regards to command customization? E.g. how would you like to simplify the Docker Compose up/down command customization?

**Comment by alexmerm** [comment]
For the current project I'm working on I was thinking just about being able to se the environment file and the compose files used but I think an ideal schema would be something like this. I think the biggest advantage over the tasks implementation here is having the "files" set globally(for the workspace) so docker-compose brings up and down the correct configurations
```
    "docker.compose" :
    {
        "files": "docker-compose.yml docker-compose-dev.yml",
        "envFile" : "mac.env",
        "up" : {
            "detached" : true,
            "services" : ["service1"],
            "build" : true
        },
        "down" :{
            "removeImages" : false,
            "removeVolumes" : true
        }
    } 
```

**Comment by karolz-ms** [comment]
Hmm, so the configuration above, as far as I understand, corresponds to the following task, correct? (focusing on the `compose up` part, and forgetting `compose down` for the moment)

```json
    {
      "label": "Compose up",
      "type": "docker-compose",
      "dockerCompose": {
        "up": {
          "detached": true,
          "build": true,
          "services": ["service1"],
          "customOptions": "--env-file=mac.env"
        },
        "files": [
          "${workspaceFolder}/docker-compose.yml",
          "${workspaceFolder}/docker-compose-dev.yml"
        ]
      }
    }
```

What makes commands more attractive to you than tasks for the purpose of launching or shutting down Compose workloads such as one above?
