### ISSUE TITLE
Deploy VSCode to Azure

### ISSUE THREAD

**Issue by nkarsiadev** [microsoft/vscode-docker#3047]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAci
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 1.14.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
AzureRegistryTreeItem.<anonymous> extension.bundle.js:2:5029307
fulfilled extension.bundle.js:2:5023140
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
@nkarsiadev could you add repro steps? Thx!
