### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by elcrapula** [microsoft/vscode-docker#3048]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 1
Error Message: Process 'docker-compose -f "." config --services' exited with code 1
Error: .PermissionError: [Errno 13] Permission denied: '.\\.'

Version: 1.14.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
Hmm, the set of file arguments passed to the command does not look valid. What did you do that led to this error @elcrapula ?
