### ISSUE TITLE
I can not push the docker image into docker hub

### ISSUE THREAD

**Issue by achintya-coder** [microsoft/vscode-docker#3049]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Pro---ss 'docker login --username "achintyaa" --password-std...' exited with code 1
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request can---led while waiting for connection (Client.Timeout ex---eded while awaiting headers)

Version: 1.14.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.58.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@achintya-coder are you sure you typed in the username, password, and repository name correctly? Are you able to log in to Docker Hub and push an image from command line?
