### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by mucena** [microsoft/vscode-docker#3052]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.52.0 but received version 1.50.0

Version: 1.14.0
OS: darwin
OS Release: 20.5.0
Product: Theia Blueprint
Product Version: 1.50.0
Language: en-US

<details>
<summary>Call Stack</summary>

```
LanguageClient.checkVersion extension.bundle.js:2:5355493
new LanguageClient extension.bundle.js:2:5355184
extension.bundle.js:2:4339129
extension.bundle.js:2:4335060
u extension.bundle.js:2:4334746
extension.bundle.js:2:4338568
Object.<anonymous> extension.bundle.js:2:4992498
```

</details>

**Comment by rcjsuen** [comment]
> Error Message: The language client requires VS Code version ^1.52.0 but received version 1.50.0

@mucena Looks like you need a newer version of VS Code...

> Product: Theia Blueprint

...but it looks like you're using some product based on Eclipse Theia though so I'm not sure what your upgrade path would look like

**Comment by bwateratmsft** [comment]
I'm going to close this as external, we have no control over what engine Theia uses or what version of the Docker extension they push to the Open VSX marketplace.

**Comment by mucena** [comment]
tks
