### ISSUE TITLE
Dont charging more extensions

### ISSUE THREAD

**Issue by JoseKabo** [microsoft/vscode-docker#3053]
Issue Type: <b>Bug</b>

stopping extensions

Extension version: 1.14.0
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics     (8 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.93GB (7.51GB free)|
|Process Argv|--crash-reporter-id 2b2fdf0a-1fdd-4275-aee8-773e8d38d82f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by bwateratmsft** [comment]
@JoseKabo is there a bug happening here? Can you add more info?

**Comment by JoseKabo** [comment]
> @JoseKabo is there a bug happening here? Can you add more info?

Sure.
I'm running test extensions and was turn on this extension, my intellisense, extensions and file context menu it's not charging. So the next one test, without this extension, all working on perfectly.
I don't have idea. This wrong is very stranger because, I was turn on this extension but then a long time started failed all my visual studio code.

**Comment by bwateratmsft** [comment]
Can you share some screenshots of what wasn't working?
