### ISSUE TITLE
Mac and Windows activation time is higher in 1.14.0

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3054]
(Title)

Both Mac and WIndows activation time spiked significantly in 1.14.0. Doesn't seem to have occurred in Linux.

In the image, yellow line is Windows activation, purple is Mac.

![image](https://user-images.githubusercontent.com/36966225/125300291-e0b9bb00-e2f7-11eb-82ad-a96036b520a3.png)

**Comment by bwateratmsft** [comment]
This regression is also visible in the Kensho dashboards.

**Comment by bwateratmsft** [comment]
I have a new theory. Looking at the Kensho dashboard, it doesn't really look like the perf spike happened on the 21st (when 1.14.0 was released). It looks like it happened on the 23rd (when Docker Desktop 3.5.0 was released).

Additionally, the fact that it's affecting Mac and Windows but not Linux inclines me to believe this is a perf regression in Docker Desktop.

**Comment by bwateratmsft** [comment]
Aha yep, it _is_ Docker Desktop 3.5.0, but not a regression. There's a new default context added called "desktop-linux" that's always present.

**Comment by bwateratmsft** [comment]
I ran some tests comparing the time it takes to fetch context from the gRPC daemon vs. the CLI. The daemon takes in the neighborhood of 175-200 ms to return, whereas the CLI takes about 400 ms each. This is a clear improvement but still isn't anywhere near as good as not needing to do either...

**Comment by karolz-ms** [comment]
@bwateratmsft that is true. On the other hand it cuts the activation time in half. I'd say go for it for now, while engaging Docker and searching for a better solution.

**Comment by bwateratmsft** [comment]
Do we want to drop support for older versions than work for this, or fall back on the CLI?

**Comment by karolz-ms** [comment]
As discussed offline, we will probably have to fall back to CLI, since for Linux it is not a given that the SDK support will be installed.

**Comment by bwateratmsft** [comment]
A fix for this has been released in Docker extension version 1.16.0.
