### ISSUE TITLE
run fail

### ISSUE THREAD

**Issue by hiephn** [microsoft/vscode-docker#3056]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.compose.up.subset
Error type: 1
Error Message: Process 'docker-compose -f "docker-compose.yml" config --se...' exited with code 1
Error: yaml.parser.ParserError: while parsing a block mapping
  in ".\docker-compose.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in ".\docker-compose.yml", line 116, column 2

Version: 1.14.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.58.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4580805
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
@hiephn can you check the syntax in your compose document?

**Comment by hiephn** [comment]
I have checked the syntax and fixed it successfully, thanks

**Comment by hiephn** [comment]
"host" network_mode is incompatible with port_bindings

@bwateratmsft ,Can you help me explain this error?
