### ISSUE TITLE
Problems with indentation and syntax error and formatter

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode-docker#3057]
Problems:

1. Indentation was wrong on moving/copy text

1.1 Reproduce: Use Cmd/Alt + Up/Down arrow (Based on user hotkey settings) to change the current line of text or copy and paste to the other line.

1.1.1 Original text:
```
    depends_on:
      - db
    restart: always
```

1.1.2 Put the cursor on line `restart: always`, then Press `Alt` + `Up Arrow` (x2)
Actual behavior:
```
      restart: always
    depends_on:
      - db
```

Expected behaviour:
```
    restart: always
    depends_on:
      - db
```

1.1.3 Put the cursor on line `restart: always`, then Press `Alt` + `Down Arrow` (x2)
Actual behavior:
```
      depends_on:
        - db
        restart: always
```

Expected behaviour:
```
    depends_on:
      - db
    restart: always
```

2. Relates to the problem 1: The indentation was wrong but nothing was highlighted on error lines.
3. I tried to format the document but it didn't worked as expected.

**Comment by karolz-ms** [comment]
@ansidev the VS Code Docker extension is not contributing to YAML indentation, even for Docker Compose files. 

Are you using any extensions designed for YAML formatting such as YAML language support by Red Hat, or Prettier extension? Can you reproduce the issue with Docker extension uninstalled? With no extensions at all?

**Comment by ansidev** [comment]
@karolz-ms The formatter or at least language file displayed on status bar is `Compose` (from your extension). If I choose YAML from `redhat.vscode-yaml` and repeat the reproduce steps, everything is as expected behaviours (problems 1 & 2).

**Comment by karolz-ms** [comment]
OK, makes sense @ansidev 

The Compose language indentation behavior is provided by VS Code. What is missing is the `autoIndent` setting that is the default for vanilla YAML: https://github.com/microsoft/vscode/blob/main/extensions/yaml/package.json#L61

As a workaround you can add the following to your settings:

```yaml
"[dockercompose]": {
    "editor.autoIndent": "advanced"
}
```

**Comment by karolz-ms** [comment]
@bwateratmsft I figured we can just send a related PR to VS Code, not even bother with opening an issue. LMK if you want me to do that.

**Comment by ansidev** [comment]
> OK, makes sense @ansidev
> 
> The Compose language indentation behavior is provided by VS Code. What is missing is the `autoIndent` setting that is the default for vanilla YAML: https://github.com/microsoft/vscode/blob/main/extensions/yaml/package.json#L61
> 
> As a workaround you can add the following to your settings:
> 
> ```yaml
> "[dockercompose]": {
>     "editor.autoIndent": "advanced"
> }
> ```

It worked!

**Comment by bwateratmsft** [comment]
> @bwateratmsft I figured we can just send a related PR to VS Code, not even bother with opening an issue. LMK if you want me to do that.

Agreed, I think that's the way to go.
