### ISSUE TITLE
No copied digest shows after executing "Copy Image Digest" for an image of azure registry

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3059]
**OS:** All
**Build Version:** 20210709.2

**Repro Steps:**

1. Create an Azure registry -> Push an image to the azure registry -> Right click the pushed image -> Select "Copy Image Digest" -> Paste the copied digest.
2. Check whether the copied digest shows well.

**Expect:**
The copied digest shows well.

**Actual:**
No copied digest shows.

**Comment by karolz-ms** [comment]
Cannot reproduce, at least on Windows 10... 🤔

**Comment by karolz-ms** [comment]
Wait, did not use the latest bits... Reopening
