### ISSUE TITLE
Format of container names in Docker Explorer

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode-docker#306]
This may just be me but is it possible to have a configuration item that we can determine the visual format of the container names?

![image](https://user-images.githubusercontent.com/11204251/42835603-c78389a8-89be-11e8-9e58-e216849d445b.png)

Instead of showing `{image}({container})` I would actually prefer to see `{container}({image})`.

**Comment by jeff-cook** [comment]
This would be an easier format for me. My I suggest having it in the config file for the format.

Thank you for your work on this extension. I just started using it and find it very helpful.

**Comment by Codelica** [comment]
This would definitely be helpful. We use a lot of private images where the names get veeeeery long.  Would much rather have the container name to start. 👍

**Comment by ReeganExE** [comment]
It would very helpful if it has a format option just like `window.title` of VSCode https://code.visualstudio.com/docs/editor/variables-reference#_common-questions.

**Comment by EricJizbaMSFT** [comment]
Hey all - just merged #989 to support custom settings for displaying containers. If you've got the time, we'd appreciate your feedback! You can install the latest build from master with these instructions: https://aka.ms/azCodeInsiders
