### ISSUE TITLE
_vscode-docker.compose.restart

### ISSUE THREAD

**Issue by gchawla007** [microsoft/vscode-docker#3061]
Does this occur consistently? 
Repro steps:

1.
2.
_vscode-docker.compose.restart
Error type: ENOENT
Error Message: spawn cmd.exe ENOENT

Version: 1.14.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.58.1
Language: en

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit child_process.js:269:19
onErrorNT child_process.js:465:16
processTicksAndRejections task_queues.js:80:21
```

</details>

**Comment by karolz-ms** [comment]
@gchawla007 can you reproduce this issue by running the Compose restart from VS Code terminal window? Standalone command prompt window?
