### ISSUE TITLE
docker stats

### ISSUE THREAD

**Issue by robross0606** [microsoft/vscode-docker#3063]
Issue Type: <b>Feature Request</b>

Would be amazing if the extension could show docker stats data for containers. A table of stat data would be good. Graphs of resource utilization would be amazing.

Extension version: 1.14.0
VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by karolz-ms** [comment]
Love the idea, thanks @robross0606 !!

**Comment by bwateratmsft** [comment]
It's not the same but related; the tooltips for containers show quite a bit of information, and the work for making tooltips customizable is partly done (#2677).

**Comment by bwateratmsft** [comment]
This functionality is now released in Docker extension version 1.18.0.
