### ISSUE TITLE
The state of the outdated base image "alpine:latest" is not "Out of date"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3066]
**OS:** All
**Build Version:** 20210714.2

**Repro Steps:**

1. Make sure enable setting "Docker > Images: Check for outdated images".
2. Open Docker view, if the image "alpine:latest" is present, remove it: `docker rmi alpine:latest`.
3. Pull any image, and tag it as "alpine:latest": `docker pull hello-world:latest && docker tag hello-world:latest alpine:latest`.
4. Restart VS Code, then check the state of the outdated base image "alpine:latest" after 1 min.

**Expect:**
The state of the outdated base image "alpine:latest" is "Out of date".
![image](https://user-images.githubusercontent.com/62053665/125755144-7da13f1b-ae9b-4ae8-b915-828869766c8f.png)

**Actual:**
The state of the outdated base image "alpine:latest" is not "Out of date".
![image](https://user-images.githubusercontent.com/62053665/125755883-15bddee9-36e0-49cc-8292-7162ee8417b6.png)

**More Info:**
This issue doesn't reproduce on the previous release build.

**Comment by karolz-ms** [comment]
Same underlying issue as https://github.com/microsoft/vscode-docker/issues/3059, just different code path
