### ISSUE TITLE
The volume in command palette is not selected by clicking up-key and down-key in the keyboard

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3067]
**OS:** Ubuntu 18.04
**Build Version:** 202107014.2

**Repro Steps:**

1. Create several volumes by following command.
`docker volume create <name>`
2. Navigate to "VOLUMES" view -> Click one volume.
3. F1 -> Select "Docker Volumes: Inspect" by the keyboard (Make sure the mouse is not used) -> List all volumes in command palette.
4. Click the up-key and down-key to select volume.
5. Check whether the volume in command palette is selected or not.

**Expect:**
The volume in command palette is selected.

**Actual:**
The volume in command palette is not selected rather than the volume in "VOLUMES" view is selected.
![actual1](https://user-images.githubusercontent.com/57662131/125750285-508cda6f-bbdc-4a1c-9ad6-32aba5d947ce.gif)

**Comment by karolz-ms** [comment]
I do not believe this is specific to Docker extension--e.g. you can reproduce the same behavior (i.e. loss of selection) with Source Control | Commits view for example. 

Resolving as external
