### ISSUE TITLE
The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'

### ISSUE THREAD

**Issue by NogueiraJr** [microsoft/vscode-docker#3068]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.push
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.ContainerRegistry'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 1.14.0
OS: darwin
OS Release: 17.7.0
Product: Visual Studio Code
Product Version: 1.58.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1384923
extension.bundle.js:2:1372397
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
@NogueiraJr please follow the link in the error message ( https://aka.ms/rps-not-found ) to enable the use of Azure Container Registry with your subscription. Hope this helps!
