### ISSUE TITLE
Invalid reference format of FROM derictive

### ISSUE THREAD

**Issue by mcdoker18** [Microsoft/vscode-docker#307]
Hi!
I use the following docker image link:
```docker
FROM artifactory.company.com:18020/python:3.6.5
```
It is a valid url but plugin throws the exception "Invalid reference format".

**Comment by StephenWeatherford** [comment]
@mcdoker18 Thanks for reporting this issue.  The fix (#280) will be available in the next release.

**Comment by StephenWeatherford** [comment]
@zeddicus76 Just wanted to let you know that we have published a new version of the Docker extension that should contain this fix.  Happy coding!
