### ISSUE TITLE
Djfimfhd 

### ISSUE THREAD

**Issue by abdallh121aa** [microsoft/vscode-docker#3071]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: EACCES
Error Message: EACCES: permission denied, open '/opt/local/sbin/.dockerignore'

Version: 1.14.0
OS: darwin
OS Release: 20.5.0
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

**Comment by karolz-ms** [comment]
@abdallh121aa if necessary, please reopen the issue using meaningful title and add repro steps-thx!
