### ISSUE TITLE
dry run

### ISSUE THREAD

**Issue by salmanmoosa642** [microsoft/vscode-docker#3072]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.runFileAsTask
Error type: Error
Error Message: To run a task from a .yaml file you must have yaml file in your VS Code workspace.

Version: 1.14.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:4574756
fulfilled extension.bundle.js:2:4570625
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by karolz-ms** [comment]
@salmanmoosa642 can you add repro steps?
