### ISSUE TITLE
 permission denied

### ISSUE THREAD

**Issue by niltonmalves** [microsoft/vscode-docker#3084]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "xxxxxx" --password-s...' exited with code 1
Error: WARNING: Error loading config file: /home/---/.docker/config.json: open /home/---/.docker/config.json: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.15.0
OS: linux
OS Release: 5.4.0-80-generic
Product: Visual Studio Code
Product Version: 1.57.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4582672
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
Hey @niltonmalves, have you [enabled rootless Docker](https://docs.docker.com/engine/security/rootless/) (more secure) or [enabled Docker CLI for the non-root user account](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)?

**Comment by niltonmalves** [comment]
running vscode as root worked.
on terminal:
`sudo su`
`code --user-data-dir`
