### ISSUE TITLE
Possible to support new heredoc syntax?

### ISSUE THREAD

**Issue by max-sixty** [microsoft/vscode-docker#3087]
Thanks for the excellent extension!

Currently the [experimental heredoc syntax](https://github.com/moby/buildkit/blob/b0c769b97eb8ea29e3ce1a8c0a8d230b88256c9a/frontend/dockerfile/docs/syntax.md#here-documents) raises errors:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5635139/126700662-436d3dee-d649-4859-845f-28b52f223a33.png">

It would be great if this were supported!

**Comment by rcjsuen** [comment]
@max-sixty Thank you for reporting this. I have opened https://github.com/rcjsuen/dockerfile-utils/issues/97 to track this.

**Comment by bwateratmsft** [comment]
I'll close this as external for now; @rcjsuen will have to implement it and we typically pick up new versions of the language server right away.
