### ISSUE TITLE
Error: Process 'docker login --username "hanani" --password-stdin' exited with code 127

### ISSUE THREAD

**Issue by hananiii** [microsoft/vscode-docker#3100]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 127
Error Message: Process 'docker login --username "hanani" --password-stdin' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.15.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4582672
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Socket.<anonymous> child_process.js:439:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by bwateratmsft** [comment]
@hananiii do you have Docker installed?
