### ISSUE TITLE
vs code docker push not working

### ISSUE THREAD

**Issue by suhairliyakath** [microsoft/vscode-docker#3101]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.push
Error type: REQUEST_SEND_ERROR
Error Message: request to https://management.azure.com/subscriptions/---/providers/Microsoft.ContainerRegistry/registries?api-version=2019-12-01-preview failed, reason: getaddrinfo ENOTFOUND management.azure.com

Version: 1.15.0
OS: linux
OS Release: 5.4.0-73-generic
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1384923
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:1366149
step extension.bundle.js:2:4588290
Object.throw extension.bundle.js:2:4588395
rejected extension.bundle.js:2:4587120
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by bwateratmsft** [comment]
@suhairliyakath it looks like your DNS server wasn't able to find `management.azure.com`. This is a network issue; you'll need to work out what's going on there.
