### ISSUE TITLE
docker error 1

### ISSUE THREAD

**Issue by suppleseipel** [microsoft/vscode-docker#3104]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.azure.selectSubscriptions
Error type: Error
Error Message: command 'azure-account.selectSubscriptions' not found

Version: 1.15.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
g._tryExecuteCommand workbench.desktop.main.js:1678:3360
vscode-file:/workbench.desktop.main.js:1678:3241
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by bwateratmsft** [comment]
@suppleseipel do you have the [Azure Account](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) extension installed?
