### ISSUE TITLE
Unable to create dockerfile

### ISSUE THREAD

**Issue by john0630** [microsoft/vscode-docker#3105]
Does this occur consistently? 
Repro steps:

1. Create new dockerfile in the folder
2. Setup the dockerfile using the "Docker - Get Started" guide.
3. Select NodeJs > Package.json > Port:3000
4. Press Enter

Action: vscode-docker.configure
Error type: SyntaxError
Error Message: c:\Gits\koha\source\backend\package.json: Unexpected token } in JSON at position 1272

Version: 1.15.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object._readFile extension.bundle.js:2:3240214
```

</details>

**Comment by bwateratmsft** [comment]
@john0630 it looks like there's a syntax error in your package.json. Try opening it directly in the editor, and see if you can find and correct it.
