### ISSUE TITLE
Syntax highlighting for backslash in RUN strings

### ISSUE THREAD

**Issue by TimothyDJewell** [microsoft/vscode-docker#3107]
Not sure whether this should go here or in [rcjsuen/dockerfile-language-service](https://github.com/rcjsuen/dockerfile-language-service).

While working on a Docker file for a windows container image, I noticed that the editor was using incorrect syntax highlighting when it came to backslashes.  It looks like the assumption from the syntax highlighter is that strings within the "RUN" command are using backslash as an escape character, but this is not the case for most shells I have used.  The result is particularly problematic when the string is a directory path, so it ends in `\`, which the syntax highlighting interprets as a multi-line quote, resulting in subsequent commands not being recognized.

An example of this is:

```
RUN	Remove-Item 'C:\SomePath\item.txt'; \
	Do-Something 'C:\SomePath\To\Item\';
RUN Copy-Item 'C:\SomePath\Foo' 'C:\Another\Path';
```

Here's what that looks like:
![image](https://user-images.githubusercontent.com/6676646/127754016-ec6775d4-f148-40ca-a705-6e6ba4b7b0e0.png)

In particular, note that the second "RUN" command is being colored as if it were part of a string rather than another run command.

**Comment by TimothyDJewell** [comment]
From the [Dockerfile reference for escape](https://docs.docker.com/engine/reference/builder/#escape):
> Note that regardless of whether the escape parser directive is included in a Dockerfile, escaping is not performed in a RUN command, except at the end of a line.

**Comment by rcjsuen** [comment]
@TimothyDJewell Thank you for your bug report. What version of the extension do you have installed? I am unable to reproduce this. Please see below.

![image](https://user-images.githubusercontent.com/15629116/127754787-62f9d7c1-c300-4765-99c6-fe0221f9a7a7.png)

**Comment by rcjsuen** [comment]
Ah, I do see a bug on line 3 with the semicolon highlighted as a string. Will take a look at that.

**Comment by TimothyDJewell** [comment]
I have v1.15.0.  I looked at it again, and it seems to match what you saw.  The view without the extension was matching what I was seeing.  I guess the syntax highlighting from the extension wasn't getting applied.  Thanks for taking a look, but I think this is mainly user error.  The semi-colon being highlighted differently might be a tiny bug, but not something I'm worried about.
