### ISSUE TITLE
Missing support for --gpus option in tasks

### ISSUE THREAD

**Issue by floscha** [microsoft/vscode-docker#3110]
With WSL 2 supporting NVIDIA Docker for a while now, I was eager to try it out for debugging containers running CUDA code using the VS Code Docker plugin. However, the task used for debugging (defined in the *tasks.json* file) does not allow the [required `--gpus all` option](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#gpu-enumeration) to run the code on my PC's GPU.

From my (limited) understanding of the plugin's code, it would be sufficient to simply add something like ` gpus?: string;` to the [DockerRunOptions](https://github.com/microsoft/vscode-docker/blob/8004c9b0d358e3077633085d0f0c241d08402e7f/src/tasks/DockerRunTaskDefinitionBase.ts#L27). Can anyone, more familiar with the plugin, confirm this? If so, I might just draft a pull request myself.

**Comment by bwateratmsft** [comment]
`--gpus` would definitely not be a frequently used option, so I would recommend trying the [`customOptions` option](https://code.visualstudio.com/docs/containers/reference#_dockerrun-object-properties) you can pass to `docker run`; otherwise just a custom task.

**Comment by floscha** [comment]
Hi @bwateratmsft. Thanks a ton for the immediate response!

While I find *customOptions* less intuitive than simple *gpus*, `"customOptions": "--gpus all"` does in fact do the trick. Given that `--gpus` might be more of a niche option and my problem solved, I believe this issue can be closed.

**Comment by bwateratmsft** [comment]
Glad it's working!
