### ISSUE TITLE
docker error can not save update

### ISSUE THREAD

**Issue by giakinh0823** [microsoft/vscode-docker#3120]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.containers.openFile
Error type: Error
Error Message: Could NOT open editor for "docker://f2d0b5af0624c6e9ef80e8211806b6a48e3239077c19ab5ed53c9122f7a3e13e/cralThread/cralThread/getData.py?fileType%3Dfile%26containerOS%3Dlinux%26path%3D%252FcralThread%252FcralThread%252FgetData.py" because another editor opened in the meantime.

Version: 1.15.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
y.showTextDocument extensionHostProcess.js:86:60532
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by bwateratmsft** [comment]
@giakinh0823 can you add repro steps?
