### ISSUE TITLE
Insider

### ISSUE THREAD

**Issue by Scott254** [microsoft/vscode-docker#3123]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

I need help to enable virtualization in BIOS in Windows 11.  Docker will not start.

Extension version: 1.15.0
VS Code version: Code - Insiders 1.60.0-insider (1ee61f368ee0570feeb220605578a8768d99e762, 2021-08-09T06:11:00.971Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.91GB (7.23GB free)|
|Process Argv|--crash-reporter-id 51b1558f-63be-4587-ba1e-faec673ae267|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   112	 16784	code-insiders main
    0	   150	  2060	   gpu-process
    0	    38	  3100	   utility
    0	   155	  5004	   window (Welcome - workspace1 (Workspace) - Visual Studio Code - Insiders)
    0	    12	  8380	     watcherService 
    0	    10	 18928	       console-window-host (Windows internal process)
    0	   118	 22940	     extensionHost
    0	    92	 17660	   shared-process
    0	    77	 18280	     ptyHost
    0	     7	 16632	       console-window-host (Windows internal process)
    0	    77	 18544	       C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe
    0	    25	 18480	   crashpad-handler
    0	    82	 23580	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - workspace1 (Workspace) - Visual Studio Code - Insiders)
|    Folder (hello-world): 1 files
|      File types: code-workspace(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30349639
dockerwalkthru:30348713
bridge0723:30346310

```

</details>

**Comment by bwateratmsft** [comment]
The process for enabling virtualization in BIOS will depend on your motherboard. I'd look for documentation from the motherboard manufacturer.

**Comment by Scott254** [comment]
Thank you Brandon, now that you say that it makes sense.

**Comment by PavelSosin-320** [comment]
@bwateratmsft The process of upgrading Win 10 to Win 11 changes certain BIOS parameters. As a Win insider, I experience it frequently. What is the hell is going here! Check BIOS after every reboot if something stopped working!

**Comment by Scott254** [comment]
Thanks for responding, new to computers to be honest, spent last 3 days
researching several problems.  I've narrowed this last (hopefully) down to
the BIOS.  Still have no clue where to find it or what to do with it when I
do.

**Comment by bwateratmsft** [comment]
You'd access the BIOS during startup, usually with <kbd>F2</kbd>, <kbd>F10</kbd>, <kbd>F12</kbd>, or <kbd>DEL</kbd>. On my ASUS motherboard it's <kbd>F2</kbd> or <kbd>DEL</kbd>, usually I just repeatedly press both during startup until I get to the BIOS screen.

Once you're in there it's gonna vary depending on manufacturer and BIOS version.
