### ISSUE TITLE
Configure tini in nodejs dockerfile template

### ISSUE THREAD

**Issue by mbelsky** [microsoft/vscode-docker#3124]
Hey,

As I found in [Best Practices doc](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals) Node.js was not designed to run as PID 1. There is an option for `docker run` to enable [tini](https://github.com/krallin/tini) however as I know k8s does not provides an argument like that. 

So what is your opinion about [adding some lines](https://github.com/krallin/tini#using-tini) in the node.js dockerfile template to setup tini? The docker file will be a bit longer but it helps the plugin users follow best practices.

I will be glad to help with this patch if you found this idea useful.

**Comment by mbelsky** [comment]
I'm not a unix expert, so I'm not sure how the user change affects the PID. So I've made a simple demo with different docker files and run it with `docker build -t test-node-user . && docker run --rm -it test-node-user`:

- Dockerfile v1 image prints 1 as the PID 
- Dockerfile v2 image prints 7 as the PID

It looks like changing the user doesn't help to start the node process as non PID 1.

<details><summary>Files source</summary>

index.js:

```
console.log(process.pid)

```

Dockerfile v1:

```
FROM node:14-alpine

ENV NODE_ENV=production
USER node
WORKDIR /usr/src/app
COPY index.js .
EXPOSE 3000

CMD ["node", "index.js"]

```

Dockerfile v2:

```
FROM node:14-alpine

ENV TINI_VERSION=v0.19.0
RUN apk add --no-cache tini

ENV NODE_ENV=production
USER node
WORKDIR /usr/src/app
COPY index.js .
EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "index.js"]
```
</details>

**Comment by bwateratmsft** [comment]
Oh, I misread the original issue--my brain was thinking UID, not PID. That said, if Node doesn't work correctly when it is PID 1--e.g. with not responding to `SIGINT`--that sounds like a Node bug to me; is there a reason it needs to be that way?

**Comment by mbelsky** [comment]
I found an interesting note about the pid 1 in docker [docs](https://docs.docker.com/engine/reference/run/#foreground):

> A process running as PID 1 inside a container is treated specially by Linux: it ignores any signal with the default action. As a result, the process will not terminate on SIGINT or SIGTERM unless it is coded to do so.

So I guess `Node.js was not designed to run as PID 1` means:
- Node.js does not have a default handler for SIGINT/SIGTERM signals 
- Node.js expects an app describes how to gracefully shutdown

And it looks like using tini as entrypoint could just hide the necessity of adding signal handlers in an application.

Thanks for the help!

**Comment by bwateratmsft** [comment]
Good to know, thanks for finding that!

**Comment by PavelSosin-320** [comment]
@mbelsky Absolutely correct! This is related to CG management: But [Docker 20.10](https://medium.com/nttlabs/docker-20-10-59cc4bd59d37) may have a solution for this issue. The current WSL2 Kernel 5.10.43.3-microsoft-standard-WSL2 #1 SMP Wed Jun 16 is slightly problematic.
