### ISSUE TITLE
Docker connect issue

### ISSUE THREAD

**Issue by pndeshpande86** [microsoft/vscode-docker#3125]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login --username "deshpr8" --password-stdin' exited with code 1
Error: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/auth: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Version: 1.15.0
OS: win32
OS Release: 6.3.9600
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4582672
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
@pndeshpande86 is Docker running?
