### ISSUE TITLE
Report Issue button should go away

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3127]
I looked at our signal:noise ratio on the Report Issue button and it's clear to me we should just get rid of it altogether like several of the Azure extensions have. In the past year, there were about 5 high-quality issues filed from this path, compared to about 140 low-quality ones. I think that the existing experience built-in to VSCode for reporting extension issues is enough; people who want to file high-quality issues will do so regardless of how it needs to get done.

**Comment by karolz-ms** [comment]
Sadly, I agree
