### ISSUE TITLE
Deployments to Azure Arc App Service from Docker Hub do not work

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3129]
**OS:** All
**Build Version:** 20210809.1

**Repro Steps:**
1. Right click Dockerfile for Express App-> Build Image.
2. Right click this image in image view -> Push -> Docker Hub -> Select a namespace to push.
3. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service with a custom location with port 80 or 3000.
4. When done, click "Open Site" button in the notification.
5. Check whether the web page can be opened successfully.

**Expect:**
Succeed to open the web page.

**Actual:**
Fail to open the web page with the “upstream request timeout” message.
![image](https://user-images.githubusercontent.com/45614674/129011464-52008148-5167-4b2f-b672-685d68034faf.png)

**More Info:**
1. This issue does not reproduce for Azure Registry with port 3000.
2. This issue also reproduces for Azure Registry with port 80.
3. This issue does not reproduce when deploying image to Azure App Service with common locations.

**Comment by bwateratmsft** [comment]
@karolz-ms I wonder if this is a limitation of Arc? I've noticed that regular App Service seems to automagically find the port in the container, maybe Arc is missing that?

**Comment by karolz-ms** [comment]
Hmm. https://github.com/microsoft/vscode-docker/pull/3046 was supposed to fix this, but it is possible that that commit only ensured that the app deploys successfully, and not necessarily that the site open button actually works.

@bwateratmsft where does the data for "Open Site" button come from? Is this controlled by our code?

**Comment by bwateratmsft** [comment]
It is in our code, here: https://github.com/microsoft/vscode-docker/blob/main/src/commands/registries/azure/deployImageToAzure.ts#L74-L87

As far as I can tell, regular AppSvc has never been bothered by having a mix of ports on the images deployed--a request to 443 always gets routed to the application's HTTP port, whatever it is, and AppSvc handles SSL termination.

Is the issue here that Arc AppSvc can't deal with SSL termination? It seems like the ports thing would not be an issue but I can totally see SSL being an issue.

**Comment by bwateratmsft** [comment]
I've figured out at least part of the problem; the `WEBSITES_PORT` setting is not being set for anything deployed from Docker Hub. Most likely deployment from Docker Hub never worked.

That said, I forcibly set that setting, and the website still doesn't work--I'm not able to figure out why though. The logging functions are useless and/or I can't figure out how to get them enabled.
