### ISSUE TITLE
The running container time doesn't refresh automatically when executing "Compose Up" for the same compose file again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3130]
**OS:** All
**Build Version:** 20210809.1
**Regression:** Not a regression

**Repro Steps:**

1. Open a project in VS Code -> Right click the docker-compose.yml file -> Execute "Compose Up".
2. Navigate the "CONTAINERS" node -> There ia an running container.
3. Right click the docker-compose.yml file -> Execute "Compose Up" again.
4. Check whether the running container time refreshes automatically.

**Expect:**
The running container time refreshes automatically.

**Actual:**
The running container time doesn't refresh automatically.
![image](https://user-images.githubusercontent.com/62053665/129006709-57ea6b96-1fa3-454f-86ee-d13e0e1b9c4f.png)

**More Info:**
1. This issue doesn't reproduce when executing "Compose Up" for the docker-compose.debug.yml file in the step 3.
2. This issue also reproduces when executing "Compose Up" for the docker-compose.debug.yml file again.
3. This issue also reproduces when executing "Compose Start" for the compose group.

**The details of log:**
![image](https://user-images.githubusercontent.com/62053665/129007594-2454ba3a-c258-42f0-b32b-f9c4264cc937.png)

**Comment by bwateratmsft** [comment]
This is actually a behavior from Docker itself. If nothing changes--e.g. same image, compose doc, etc.--it will not actually restart the container. I found that by modifying something simple in the compose document (e.g. the port), and trying again, this time it refreshes the container timer.

**Comment by v-mengwe** [comment]
Thanks for your sharing, this issue also reproduces when executing "Compose Start" for the compose group, is it also the same principle?

**Steps:**

1. Navigate the "CONTAINERS" node -> Right click the compose group -> Select "Compose Start".
2. Check the running container time.

**Comment by karolz-ms** [comment]
@v-mengwe correct, if the container is already started, and nothing about its configuration changes, "Compose Start" will be a no-op.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
