### ISSUE TITLE
Pushing the first image is interrupted if meanwhile start pushing the second image 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3131]
**OS:** All
**Build Version:** 20210809.1
**Regression:** Not a regression

**Repro Steps:**

1. Navigate to the "IMAGES" node -> Push the first image to an Azure registry. (**Only one task is opened in the terminal**)
2. Push the second image to an Azure registry during pushing the first image.
3. Check whether two images are pushed to the Azure registries successfully.

**Expect:**
Both images are pushed to Azure registries successfully.

**Actual:**
The second image is pushed successfully but the first image is stopped to push.
![image](https://user-images.githubusercontent.com/62053665/129149794-e067dc00-1e00-489b-8eee-c754f2fbfdc3.png)

More Info:

**Comment by karolz-ms** [comment]
@v-mengwe once the push starts, it is totally under Docker CLI control. 

Does the first push eventually succeed? 

Can you reproduce this behavior outside of VS Code (just using command line window)?

**Comment by bwateratmsft** [comment]
I had somewhat similar behavior, but both pushes worked. Mine came up in different terminal windows. Only one would actually be pushing at a time; in my case it fully pushed the first image before starting on the second one--all the layers stayed in the "Waiting" phase. It seems like it was slower overall than pushing one at a time but that may be my imagination. It did take a fairly long time before much progress was made on the second one.

**Comment by v-mengwe** [comment]
The first push is failed eventually and this issue only reproduces when only one task is opened in the terminal.
Both images are pushed to Azure registries successfully when outside of VS Code(just using command line window).

**Comment by bwateratmsft** [comment]
I wonder why these both showed up in the same terminal window. @alexr00 do you know what might be happening here? Is it possible both of these got the same task ID or something like that?

**Comment by alexr00** [comment]
This is https://github.com/microsoft/vscode/issues/130277

Fix is in main, we'll probably have a recovery release for stable next week.

**Comment by bwateratmsft** [comment]
Awesome, thanks Alex!
