### ISSUE TITLE
Docker view keeps loading without any notification if there is no Docker Desktop installed

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3132]
**OS:** Win 10
**Build Version:** 20210809.1
**Regression:** Previous Release

**Repro Steps:**
1. Make sure there is **no Docker Desktop** on the machine.
2. Install the Docker extension in VS Code.
3. Open the Docker view.
4. Check whether a notification pops up to remind user to install Docker Desktop.

**Expect:**
A notification pops up to remind user to install Docker Desktop.
![expect](https://user-images.githubusercontent.com/45614674/129155959-cbdc3f17-3c03-413f-aa07-92dd5d129b13.gif)

**Actual:**
Docker view keeps loading without any notification.
![testactual](https://user-images.githubusercontent.com/45614674/129155973-7b40de25-d7ab-483e-8a14-3171382c01c0.gif)

**More Info:**
1. This notification pops up after expanding the Networks/Volumes/Contexts view.
2. This issue does not reproduce on the previous released Docker extension 1.15.0.

**Comment by karolz-ms** [comment]
Side-effect of https://github.com/microsoft/vscode-docker/pull/3109 ?

**Comment by bwateratmsft** [comment]
I'm able to reproduce. I think what is happening is the containers and images views start their first refresh call which awaits on `ContextLoadingClient`--which will not forward the call until it observes the `onContextChanged` event from the context manager. However, the event is [only fired if no exception is thrown](https://github.com/microsoft/vscode-docker/blob/main/src/docker/ContextManager.ts#L158).

@karolz-ms I think maybe we should have two separate events in `DockerContextManager`, leave `onContextChanged` as it is now, but add one for `onLoadingFinished` specifically for `ContextLoadingClient`. This one would fire regardless of success/failure of context loading, i.e. by being in the `finally`. What do you think?

**Comment by karolz-ms** [comment]
@bwateratmsft yes, that makes sense to me.

**Comment by bwateratmsft** [comment]
Discussed offline and we'll fix this in 1.17.0.

**Comment by bwateratmsft** [comment]
The fix for this has been released in Docker extension 1.17.0.
