### ISSUE TITLE
[Suggestion] Change the minimum VS Code version that the Docker extension supports

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3133]
**OS:** Windows 10
**Build Version:** 20210809.1

**Repro Steps:**
1. Figure out the minimum VS Code version that the Docker extension supports, the version is "1.56.0".
2. Install VS Code 1.56.2.
3. Navigate to "Extension view" and search Docker extension.
4. Try to open the installation page of Docker extension.
5. Check whether open the Docker extension installation page successfully.

**Actual:**
Fail to open the installation page with an error.
![image](https://user-images.githubusercontent.com/45614674/129165407-8efd3480-4239-4a9d-9dd2-995aaad10df8.png)

**Suggestion:**
Change the minimum VS Code version that the Docker extension supports.

**More Info:**
Can't open the installation page of any extensions.

**Comment by bwateratmsft** [comment]
Looks like this is coming from somewhere else, maybe the Python extension or something with VSCode's built-in Notebooks: https://stackoverflow.com/questions/67587398/vs-code-error-this-configurationservice-getvalue-filter-is-not-a-f
