### ISSUE TITLE
Fail to open the webpage in the browser after clicking "Open in Browser" for the running container which composed up the docker-compose.debug.yml file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3135]
**OS:** All
**Build Version:** 20210809.1

**Repro Steps:**

1. open a Python project in VS Code -> Add Dockerfile support including docker-compose files.
2. Right click the **docker-compose.debug.yml** file -> Select "Compose Up".
3. Navigate to the "CONTAINERS" node -> Right click the running container -> Select "Open in Browser".
4. Check whether succeed to open the webpage in the browser.

**Expect:**
Succeed to open the webpage in the browser.

**Actual:**
Fail to open the webpage in the browser.
Windows:
![image](https://user-images.githubusercontent.com/62053665/129182255-291fdb3a-1146-41ca-a3bb-723dc92b1239.png)
Mac:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62053665/129178085-27c0f730-3b56-41b5-ba9f-cc4384857bf8.png)

**More Info:**

1. This issue also reproduces for the latest release build.
2. This issue **doesn't reproduce** for the the running container which composed up the **docker-compose.yml** file

**Comment by bwateratmsft** [comment]
This is by-design. For Python apps, with the `docker-compose.debug.yml` file, we pass an argument to `debugpy` instructing it to start but wait until a debug client attaches. Once a client attaches, the website begins working.

Here's an example of an attach config in `launch.json` for this scenario:
```json
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        },
```
