### ISSUE TITLE
Unable to use docker context connected with SSH and GSSAPIAuthentication=yes

### ISSUE THREAD

**Issue by chriscasola** [microsoft/vscode-docker#3136]
Issue Type: <b>Bug</b>

The host I am connecting to requires GSSAPIAuthentication / kerberos to be enabled when creating the ssh connection.

I can do this fine with docker CLI:

```bash
# connect via SSH works fine
ssh -o GSSAPIAuthentication=yes casola@somehost.com

# connect with docker command line works fine
docker context create remote-dev --docker "host=ssh://casola@somehost.com"
docker context use remote-dev
docker ps
```

But vscode is unable to connect after doing "Docker Contexts: Use". I get the error "Failed to connect. Is Docker running?".

In the vscode dev console I get this:

```
 ERR All configured authentication methods failed: Error: All configured authentication methods failed
    at doNextAuth (/Users/ccasola/.vscode/extensions/ms-azuretools.vscode-docker-1.15.0/dist/extension.bundle.js:2:3963153)
    at tryNextAuth (/Users/ccasola/.vscode/extensions/ms-azuretools.vscode-docker-1.15.0/dist/extension.bundle.js:2:3964392)
    at /Users/ccasola/.vscode/extensions/ms-azuretools.vscode-docker-1.15.0/dist/extension.bundle.js:2:3964043
    at Socket.onclose (/Users/ccasola/.vscode/extensions/ms-azuretools.vscode-docker-1.15.0/dist/extension.bundle.js:2:3948526)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
```

Is there a way for me to get this working? Sorry if I overlooked part of the setup for this.

Extension version: 1.15.0
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 823e7799-33ba-4d5f-a806-4488746b727e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
Looks like it is indeed a limitation of the [`ssh2`](https://www.npmjs.com/package/ssh2) package used by [`Dockerode`](https://www.npmjs.com/package/dockerode): https://github.com/mscdex/ssh2/issues/333

Nothing we can do about it 😞
