### ISSUE TITLE
Docker view in the VS Code local instance shows "Failed to connect. Is Docker installed?" after using remote context

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3137]
**OS:** Windows 10
**Build Version:** 20210809.1

**Repro Steps:**
1. Create an Ubuntu 18.04 LTS machine with SSH access--as a remote machine.
2. Install Docker in this Linux machine.
3. In local machine, install Remote-SSH extension in VS Code local instance.
4. Connect to the remote Ubuntu machine via SSH in VS Code.
5. Switch to the VS Code local instance use 'docker context' command to create a context for connecting to the remote machine:
docker context create --docker "host=ssh://username@machineIP" test
6. Switch Docker context to "test".
7. Check the Docker view in the VS Code local instance and check the image and container from Terminal.
docker ps
docker images

**Expect:**
Docker view in the VS Code local instance shows Docker assets on the remote machine.

**Actual:**
Docker view in the VS Code local instance shows "Failed to connect. Is Docker installed?" after using remote context.
![image](https://user-images.githubusercontent.com/45614674/129320761-c6392918-7d95-4486-85f6-eb60b812c8a0.png)

**Comment by bwateratmsft** [comment]
@v-ruizh did you set up SSH key auth and an SSH agent? https://code.visualstudio.com/docs/containers/ssh

**Comment by v-ruizh** [comment]
@bwateratmsft I have set up SSH key auth and an SSH agent on my machines. 

This issue does not reproduce after uninstalling and reinstalling one of my Ubuntu VM. But it still reproduces on my other machines. I'm not sure if this is an environment issue. I will close this issue first and keep tracking on it in our testing.

**Comment by bwateratmsft** [comment]
Thanks! Sounds good.
