### ISSUE TITLE
[Suggestion] It would be better to add a button "Open Extension" or a hyperlink in the notification to prompt the installation of C# extension

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3138]
**OS:** All
**Build Version:** 20210809.1
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the C# extension is not installed in VS Code.
2. Open a .NET Core project in VS Code -> F1 -> Docker: Add Docker Files to Workspace.
3. Check the notification.

**Actual:**
There is no button or hyperlink in the notification.
![image](https://user-images.githubusercontent.com/62053665/129314350-9ab0fda4-22db-4288-8df1-4cb4c6b34fbb.png)

**Suggestion:**
It would be better to add a button "Open Extension" or a hyperlink in the notification, like bellow:
![image](https://user-images.githubusercontent.com/62053665/129315552-1cb46c52-7f4b-4cb1-b79e-457eeeb4a1ed.png)
![image](https://user-images.githubusercontent.com/62053665/129315701-6eae4aa1-d4ae-44ab-99a2-9feac6ce5778.png)

**Comment by bwateratmsft** [comment]
Good idea. This should be pretty simple to add.
