### ISSUE TITLE
The images' order is changed when refreshing the "REGISTRIES" view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3139]
**OS:** All
**Build Version:** 20210809.1
**Regression:** Not a Regression

**Repro Steps:**
1. Push an image to the Azure registry multiple times with different tags, e.g. "hello-world".
4. Navigate to "REGISTRIES" view -> Expand "Azure" -> Subscription -> Registry -> Hello-world.
5. Refresh the "REGISTRIES" view.
6. Check whether the images' order is not changed or not.

**Expect:**
The images' order is not changed.

**Actual:**
The images' order is changed.
![actual1](https://user-images.githubusercontent.com/57662131/129323621-579b07be-57db-4d2c-9aea-a760a19b9715.gif)

**More Info:**
This issue doesn't reproduce for Docker Hub.

**Comment by bwateratmsft** [comment]
This is strange. I wonder if the API is returning the images in a somewhat random order?

**Comment by bwateratmsft** [comment]
I found what's happening. The API is returning them consistently in alphabetical order, but we create them with a subtle async call:

https://github.com/microsoft/vscode-docker/blob/main/src/tree/registries/dockerV2/DockerV2RepositoryTreeItem.ts#L46-L49

The order of that call returning will determine the order of the tags. That code hasn't been changed in two _years_ so I'm sure this behavior is not new at all.

**Comment by bwateratmsft** [comment]
I don't believe this can still occur.
