### ISSUE TITLE
SSH tunnel setup doesn't work in PowerShell

### ISSUE THREAD

**Issue by yurymik** [microsoft/vscode-docker#3142]
In ["Connect to remote Docker over SSH/Set up SSH Tunneling"](https://code.visualstudio.com/docs/containers/ssh#_set-up-ssh-tunneling) it is advised to run `sc config ssh-agent start=auto`, but it only works in old `cmd` terminal. PowerShell will complain:

```
> sc config ssh-agent start=auto
Set-Content : A positional parameter cannot be found that accepts argument 'start=auto'.
At line:1 char:1
```

Please update the documentation with correct steps:

```
Set-Service ssh-agent -StartupType "Automatic"
Start-Service ssh-agent
```

**Comment by bwateratmsft** [comment]
Thanks! I'll get this fixed.
