### ISSUE TITLE
errors in docker

### ISSUE THREAD

**Issue by panda15963** [microsoft/vscode-docker#3143]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Process 'docker login -----name "seok7521" --password-stdi...' exited with code 1
Error: error during connect: Post "http://docker/v1.24/auth": command [ssh -l --- -- remote_server_ip docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh: Could not resolve hostname remote_server_ip: \276\313\267\301\301\370 \310\243\275\272\306\256\260\241 \276\370\275\300\264\317\264\331. 

Version: 1.15.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.0
Language: ko

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4582672
ChildProcess.emit events.js:315:20
ChildProcess.EventEmitter.emit domain.js:467:12
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
@panda15963 can you add repro steps?
