### ISSUE TITLE
Installation of Extension fails on remote host w/o internet connection

### ISSUE THREAD

**Issue by jrwagz** [microsoft/vscode-docker#3149]
My workflow is such that I'm running VSCode in windows, and connecting over SSH to a linux system that doesn't have an internet connection, but my local windows machine does have such a connection.  Whenever I try and installed the VSCode Docker extension onto the remote system, it fails with the following error messages:

```
[2021-08-16 09:07:29.586] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-16 09:08:38.520] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-16 09:08:38.524] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-16 09:08:38.526] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
```

Perhaps you could provide a .vsix version of the extension that has all of it's dependencies bundled, like how the C++ extension handles this?  They call it their ["offline" vsix](https://github.com/microsoft/vscode-cpptools/releases)

**Comment by bwateratmsft** [comment]
The VSIX is always available from the Releases page: https://github.com/microsoft/vscode-docker/releases/latest

I'd recommend filing this as a general feedback to VSCode though, it seems like it would be generally useful in these scenarios.

**Comment by jrwagz** [comment]
@bwateratmsft , thanks for the reply.  The problem is that, even when you download the VSIX directly from the releases page of this repo, like you suggest, the plugin won't install properly, unless the remote system you are connecting to has an active internet connection.  So, like if you look at the offline VSIX for C++, the actually bundle their dependencies directly into the VSIX for that case, and that VSIX is like 24MB, instead of the usual 5MB VSIX (for C++).

Perhaps this is a general VSCode problem, but it's confusing as a user to know which extensions will install in this setup and which won't.  For example, the [GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) installs correctly in this configuration, but the Docker extension doesn't.  If you are suggesting a more broad fix from VSCode to handle any extensions with this dependency problem, where should I raise that ticket?

**Comment by bwateratmsft** [comment]
Hm, what error message do you see? I would not have expected an install failure. I know there's some things that would require internet still (like downloading vsdbg for debugging .NET apps), but the VSIX should have everything needed for most operation.

**Comment by jrwagz** [comment]
Here is the error message I get (which appears to be the exact same no matter if I install from VSIX or from the marketplace)

```
[2021-08-17 09:24:50.082] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-17 09:27:01.371] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-17 09:27:01.375] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-17 09:27:01.376] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
```

I should mention the following background info:

This remote server already has version `1.15.0` of the extension installed, and I'm trying to upgrade it to `1.16.0`.

"How did you get `1.15.0` installed in the first place?" Great question.

When first getting going in vscode, I had played around with running vscode directly on that remote linux machine (until I realized how amazing the remote-ssh extension was), and I was able to install the vsix for docker `1.15.0` from the command line on that linux machine (which has no internet connection), but I wasn't ever able to get it to install on other linux servers when in the remote-ssh setup.  So, as a hack, I simply copied the folder for this extension from remote server to remote server, by copying the files under ~/.vscode-server/extensions/ from server to server.

Now, with the `1.16.0` update, I circled around and want to try and install it through my remote-ssh setup, without the hassle of running vscode on the remote machine via command line, to install the extension, and then copy the expanded files from machine to machine.

**Comment by bwateratmsft** [comment]
Interesting...the Docker extension has only two dependencies, `vscode.docker` and `vscode.yaml`, both of which are built-in to VSCode. I'd expect them to be present in a remote session but maybe it's more stripped down than that?

**Comment by jrwagz** [comment]
So, great question, and my extension development experience is about zero, so maybe don't have enough info, BUT I do know that the GitLens extension installs in this setup without error, and their `package.json` at the root [DOES NOT have any definition of `extensionDependencies`](https://github.com/eamodio/vscode-gitlens/blob/main/package.json) whereas I can see where you are [setting that for this extension](https://github.com/microsoft/vscode-docker/blob/main/package.json#L2881-L2884).

The part that I don't have any context on, is what those dependencies are referring to exactly.  I'm happy to poke around on the remote server and show you what is/isn't present there if you can help me understand where it would be looking for `vscode.docker` and `vscode.yaml`.

**Comment by bwateratmsft** [comment]
Basically, VSCode has its core stuff, plus a large number of mini "extensions" that ship with it. `vscode.docker` and `vscode.yaml` both are just language "extensions" that provide the grammar and syntax highlighting for Dockerfiles and YAML files that is present even without the Docker extension.

I'll try to find a contact from VSCode to ask about whether those extensions should be expected to be present by default in a remote server, and if not, why not.

**Comment by bwateratmsft** [comment]
@sandy081 is it expected for built-in extensions like `vscode.docker` and `vscode.yaml` to be present by default in remote sessions?

**Comment by sandy081** [comment]
Yes they shall be available already. There is a bug in recent release that offline installations are broken - https://github.com/microsoft/vscode/issues/130962. Will be fixing it soon.

Another tip for remote set up users if the remote box does not have network connection or some network issues connecting to Marketplace, they can set the setting `remote.downloadExtensionsLocally` to true so that VS Code downloads the VSIXs on the client side and install them on the remote box.

**Comment by jrwagz** [comment]
> Another tip for remote set up users if the remote box does not have network connection or some network issues connecting to Marketplace, they can set the setting `remote.downloadExtensionsLocally` to true so that VS Code downloads the VSIXs on the client side and install them on the remote box.

Great tip! I'll test out this setting with my setup as it is and see if this resolves this issue for me.

**Comment by bwateratmsft** [comment]
That setting is pretty much exactly what I would have hoped VSCode would have, so I'll consider this done! @jrwagz please let us know if that setting works (or doesn't!)

**Comment by jrwagz** [comment]
@bwateratmsft , using `remote.downloadExtensionsLocally` as `true` DID NOT resolve my problem.

I still get the following error:

```
[2021-08-20 11:35:21.246] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-20 11:37:31.899] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-20 11:37:31.903] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-20 11:37:31.904] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
```

This same error still occurs if installing from the Marketplace, or from the downloaded VSIX.

To double check connectivity to 13.107.42.18 I visited it in a browser over HTTPS from both my local machine, and the remote machine.

My local machine gets a response:
```
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0EuofYQAAAABdPqdHvqkhSpcCTSfwAbL9V1NURURHRTEwMjAARWRnZQ==
```

Whereas the remote machine just times out (as expected)
![image](https://user-images.githubusercontent.com/498172/130273541-bf250d64-0551-4f64-8da6-4ebfd989b809.png)


So, I suspect that you may still need to remove these items from `extensionDependencies`, or maybe there is still a bug I'm running into that is causing this? I read the descriptions of the issues mentioned by @sandy081 , but those errors all seem a bit different, and also refer to inter-dependencies, which isn't the case here as far as I'm aware.  Meaning, I don't suspect that `vscode.docker` depends on this extension, and only this extension depends on it.

**Comment by bwateratmsft** [comment]
@sandy081 Any ideas? If these built-in extensions are indeed pre-installed on remote sessions (even offline ones) it seems like it shouldn't be trying again to install them from the internet.

**Comment by sandy081** [comment]
As mentioned in my earlier comment there is a bug in current stable that installing from VSIX is failing if there are connection issues - https://github.com/microsoft/vscode/issues/130962. I fixed it in insiders and the fix will be available in next stable release. Please try the insiders to see if it works. Sorry about this.

**Comment by jrwagz** [comment]
I can confirm that the extension installs in my setup/environment with the version of vscode insiders that was downloadable today:

![image](https://user-images.githubusercontent.com/498172/130704515-21653943-3e54-4f28-b530-7fb8291a9e13.png)

Which means it should then come out in the 1.60 release.

Thanks guys!
