### ISSUE TITLE
error building docker env

### ISSUE THREAD

**Issue by ivanpedro** [microsoft/vscode-docker#3154]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: Unable to write into the launch configuration file. Please open it to correct errors/warnings in it and try again.

Version: 1.16.0
OS: linux
OS Release: 5.4.72-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
E.toConfigurationEditingError workbench.desktop.main.js:1981:18781
E.updateConfiguration workbench.desktop.main.js:1981:15911
E.doWriteConfiguration workbench.desktop.main.js:1981:15544
```

</details>

**Comment by bwateratmsft** [comment]
Can you add repro steps? Can you check if `.vscode/launch.json` in your workspace is valid JSON?
