### ISSUE TITLE
Fail to execute "Compose Up" action for docker-compose.yml file with Docker Desktop setting "Compose V2" enabled

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3158]
**OS:** Win 10
**Build Version:** 20210816.22

**Repro Steps:**
1. Open Docker Desktop settings -> Experimental Features -> Enable "Use Docker **Compose V2** release candidate".
2. Switch Docker Desktop to **Windows Container**.
3. Open one .NET MVC project in VS Code and add Docker support for it.
4. Right click the docker-compose.yml file and execute "Compose Up" action.
5. Check whether succeed to execute "Compose Up" action or not.

**Expect:**
Succeed to execute "Compose Up" action for docker-compose.yml file.

**Actual:**
Fail to execute "Compose Up" action for docker-compose.yml file with an error "not implemented".
![image](https://user-images.githubusercontent.com/45614674/130210985-0f5c7545-ed06-47ec-aabd-29df4b3046a0.png)

**More Info:**
1. This issue does not reproduce for Linux Container.
2. This issue does not reproduce if disabling Docker Desktop setting "Use Docker **Compose V2** release candidate".

**Comment by bwateratmsft** [comment]
Unfortunately Windows containers are not supported by Compose V2 at this time. We are working with Docker Inc. on that. We're tracking this issue in DevOps so I'll close this one. I'll send you the DevOps link offline.
