### ISSUE TITLE
There is no complete log when executing "Compose Start" action with Docker Desktop setting "Compose V2" enabled

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3160]
**OS:** Win 10
**Build Version:** 20210816.22

**Repro Steps:**
1. Open Docker Desktop settings -> Experimental Features -> Enable "Use Docker **Compose V2** release candidate".
2. Switch Docker Desktop to Linux Container.
3. Open one .NET MVC project in VS Code and add Docker support for it.
4. Right click the docker-compose.yml file and execute "Compose Up" action.
5. Right click the container group in container view and execute "Compose Start" action.
6. Check whether there is a complete log or not.

**Expect:**
There is a complete log when executing "Compose Start" action.
![image](https://user-images.githubusercontent.com/45614674/130215061-e2e31619-734d-4f88-bded-a48b6a3ff266.png)

**Actual:**
There is no complete log when executing "Compose Start" action.
![image](https://user-images.githubusercontent.com/45614674/130215138-e0394666-689f-41ca-a6bc-e64f5856be99.png)

**More Info:**
1. This issue does not reproduce if executing the "Compose Start" action for a stopped container.
2. This issue does not reproduce if disabling Docker Desktop setting "Use Docker Compose V2 release candidate".

**Comment by bwateratmsft** [comment]
This output is controlled by the compose CLI; I'm guessing they made this change on purpose.
