### ISSUE TITLE
MacOS: Remote Docker Containers won't start after 3.6.0 update

### ISSUE THREAD

**Issue by notslow** [microsoft/vscode-docker#3161]
I finally restarted my Mac to get the latest updates.  Docker Desktop is now at v3.6.0 (67351).  I tried restarting my local dev containers (both Debian) and both are erroring out with different errors.

Error 1: "Docker Version 17.12.0 or later required" 
Error 2: "The 'docker' command was not found. Make sure Docker is installed."

>` ➜ $ which docker`
> `/usr/local/bin/docker`

>` ➜ $ docker -v`
> `Docker version 20.10.8, build 3967b7d`

VSCode Version:
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

Docker Version:
v3.6.0(67351)
Engine: 20.10.8

Thanks!

**Comment by bwateratmsft** [comment]
Probably yet more of Docker and the `PATH` not getting along, so duping to #2894.

@notslow try setting the VSCode setting `docker.dockerPath` to `/usr/local/bin/docker` or wherever Docker is located.

**Comment by notslow** [comment]
> Probably yet more of Docker and the `PATH` not getting along on OSX, so duping to #2894.
> 
> @notslow try setting the VSCode setting `docker.dockerPath` to `/usr/local/bin/docker` or wherever Docker is located.

Yep, thanks! That did the trick.
