### ISSUE TITLE
Debugger is not started when debugging containerized Python app in remote environment

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode-docker#3167]
Using the Python general template, no debugger is attached. This issue is similar to #2641.

tasks.json:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "docker-build",
			"label": "docker-build",
			"platform": "python",
			"dockerBuild": {
				"tag": "chatbotpy:latest",
				"dockerfile": "${workspaceFolder}/Dockerfile",
				"context": "${workspaceFolder}",
				"pull": true
			}
		},
		{
			"type": "docker-run",
			"label": "docker-run: debug",
			"dependsOn": [
				"docker-build"
			],
			"python": {
				"file": "bot.py"
			}
		}
	]
}
```

launch.json

```
{
  "configurations": [
    {
      "name": "Docker: Python - General",
      "type": "docker",
      "request": "launch",
      "preLaunchTask": "docker-run: debug",
      "python": {
        "pathMappings": [
          {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
          }
        ],
        "projectType": "general"
      }
    }
  ]
}
```

**Comment by bwateratmsft** [comment]
Is there any error information written to the Debug Console, the "Python Debug Console" terminal window, or to the Output window for anything Python-related?

**Comment by Thomas1664** [comment]
> Is there any error information written to the Debug Console, the "Python Debug Console" terminal window, or to the Output window for anything Python-related?

I only get the following error in a message box: "Timed out waiting for launcher to connect". All logs contain no errors and the container is running.

**Comment by bwateratmsft** [comment]
Does anything change if you add `debugAdapterHost` to the launch profile, as in this comment? https://github.com/microsoft/vscode-docker/issues/2641#issuecomment-762900993

**Comment by Thomas1664** [comment]
> Does anything change if you add `debugAdapterHost` to the launch profile, as in this comment? [#2641 (comment)](https://github.com/microsoft/vscode-docker/issues/2641#issuecomment-762900993)

No

**Comment by bwateratmsft** [comment]
One more thing to check--does the container created by the `docker-run` task stay up? If it's crashing for some reason and immediately going down and/or disappearing, that would explain the timeout.

**Comment by Thomas1664** [comment]
> One more thing to check--does the container created by the `docker-run` task stay up? If it's crashing for some reason and immediately going down and/or disappearing, that would explain the timeout.

The container stays up.

**Comment by bwateratmsft** [comment]
There's some info on debugging the debugging (yep) for Python here: https://github.com/microsoft/vscode-docker/issues/2716#issuecomment-812187762

Can you check that out? We need to work out what's going wrong with the handoff to the Python extension / `debugpy`.

**Comment by Thomas1664** [comment]
There are no log files at the host machine.
These are the logs from within the container:

```
I+00000.145: Linux-5.10.52-v7l+-armv7l-with-glibc2.4 armv7l
             CPython 3.8.11 (32-bit)
             debugpy 1.4.1

I+00000.173: debugpy.launcher startup environment:
             
             System paths:
                 sys.prefix: /usr/local
                 sys.base_prefix: /usr/local
                 sys.real_prefix: <missing>
                 site.getsitepackages(): /usr/local/lib/python3.8/site-packages
                 site.getusersitepackages(): /home/appuser/.local/lib/python3.8/site-packages
                 sys.path (site-packages): /usr/local/lib/python3.8/site-packages
                 sysconfig.get_path('stdlib'): /usr/local/lib/python3.8
                 sysconfig.get_path('platstdlib'): /usr/local/lib/python3.8
                 sysconfig.get_path('purelib'): /usr/local/lib/python3.8/site-packages
                 sysconfig.get_path('platlib'): /usr/local/lib/python3.8/site-packages
                 sysconfig.get_path('include'): /usr/local/include/python3.8
                 sysconfig.get_path('scripts'): /usr/local/bin
                 sysconfig.get_path('data'): /usr/local
                 os.__file__: /usr/local/lib/python3.8/os.py
                 threading.__file__: /usr/local/lib/python3.8/threading.py

I+00000.173: sys.argv before parsing: ['/debugpy/launcher', '172.17.0.1:36115', '--', 'bot.py']

I+00000.173: sys.argv after patching: ['/debugpy/launcher', 'bot.py']

I+00000.179: Connecting to adapter at 172.17.0.1:36115

I+00133.471: Not logging to "<stderr>" anymore.


```

**Comment by bwateratmsft** [comment]
Is there anything in those other logs in `~/.vscode/extensions/ms-python.python-xxxx.x.xxxx`?

**Comment by Thomas1664** [comment]
> Is there anything in those other logs in `~/.vscode/extensions/ms-python.python-xxxx.x.xxxx`?

There are no log files

**Comment by bwateratmsft** [comment]
@int19h any ideas what's going on here?
