### ISSUE TITLE
Formatter doesn't respect organizational indentation

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-docker#3175]
Hi,

When I specify long, complicated commands like `apt-get` installing dozens of packages, then I want to use a certain indentation style, so that the command line arguments indent one level deeper than the other command line arguments. This adds visual clarity, so that the engineer can maintain the Dockerfile more easily. Unfortunately, the VSCode Docker plugin does not respect custom `RUN` indentation and crudely dedents everything to a bare four spaces.

This happens, for example, when enabling the VSCode global format on save option.

As a workaround, I am configuring my VSCode preferences with:

```json
    "[dockerfile]": {
        "editor.formatOnSave": false
    },
```

I assume the problem arises from the Docker plugin, but there is a possibility of it coming from the EditorConfig plugin. Not sure which at the moment.

**Comment by rcjsuen** [comment]
@mcandre You could toggling the `docker.languageserver.formatter.ignoreMultilineInstructions` setting introduced in #2976 to see if that helps.

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
