### ISSUE TITLE
Process 'docker context ls --format="{{json .}}"' exited with code 1

### ISSUE THREAD

**Issue by LeonardoRepetto** [microsoft/vscode-docker#3176]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.build
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.16.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4591337
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
@LeonardoRepetto can you add repro steps? Do you have Docker installed?

**Comment by LeonardoRepetto** [comment]
Now it was solved, it was not running docker desktop
