### ISSUE TITLE
Fail to debug Express app with an error "Configured debug type 'node2' is not supported" in VS Code Insider

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3177]
**OS:** Win 10
**Build Version:** 20210828.1
**VS Code Insider:** 1.60.0-insider

**Repro Steps:**
1. Open an Express app in VS Code Insiders.
2. Add Docker related files to it.
3. Debug this project.
4. Check whether succeed to debug this Express app or not.

**Expect:**
Succeed to debug this Express app without any error.

**Actual:**
Fail to debug this Express app with an error "Configured debug type 'node1' is not supported".
![image](https://user-images.githubusercontent.com/45614674/131628302-c2270e65-e2a2-48ac-8df7-d8b5d03a0bf5.png)
Click "Install node2 Extension" button, no extensions found.
![image](https://user-images.githubusercontent.com/45614674/131628371-331232d9-41b5-4ae3-bf5a-e0221ff2f60f.png)

**More Info:**
This issue does not reproduce in the latest VS Code 1.59.1.

**Comment by bwateratmsft** [comment]
Looks like the old Node debug launch is gone; we'll need to fix this.

**Comment by bwateratmsft** [comment]
Since VSCode 1.60.0 is releasing soon we may also need to backport a fix to Docker extension 1.16.0.

**Comment by bwateratmsft** [comment]
Looks like `node2` was removed as part of https://github.com/microsoft/vscode-js-debug/issues/1065.

**Comment by bwateratmsft** [comment]
The fix for this is now available in Docker extension version 1.16.1.
