### ISSUE TITLE
There is an error after clicking the "Restart" button to debug the Express app again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3183]
**OS:** All
**Build Version:** 20210901.1
**VS Code Insider:** 1.60.0-insider
**Regression:** Previous release

**Repro Steps:**

1. Open an Express app in VS Code Insiders.
2. Add Docker related files to it.
3. Debug this project -> Click "Restart" button to restart debugging.
4. Check whether succeed to debug this Express app again or not.

**Expect:**
Succeed to debug this Express app again without any error.

**Actual:**
There is an error when debugging again.
![image](https://user-images.githubusercontent.com/62053665/131775908-4ce94545-454d-43b3-a46b-bf9270972d9f.png)

**More Info:**
1. Succeed to debug this Express app again with the error after clicking "Debug Anyway".
2. There is no error in the "PROBLEMS" after clicking "Show Errors".

**Comment by bwateratmsft** [comment]
Looks like this is external. The node attach configuration does not fire a debug stop event because it's not actually fully detaching.
