### ISSUE TITLE
Fail to build the image in azure with an error when executing "Build Image in Azure..." to the Express app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3184]
**OS:** All
**Build Version:** 20210901.1
**Regression:** Not a regression

**Repro Steps:**

1. Open an Express app in VS Code Insiders.
2. Add Docker related files to it.
3. Right click the Dockerfile -> Click "Build Image in Azure..." -> Tag image as default value -> Select a subscription -> Select a registry -> Select "Linux".
4. Check whether succeed to build the image in azure or not.

**Expect:**
Succeed to build the image in azure without any error.

**Actual:**
Fail to build the image in azure with an error.
Windows/Mac:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/62053665/131823669-bd14cfe6-8ec8-47d3-a9a3-c603f5caf21c.png)
Linux:
![image](https://user-images.githubusercontent.com/62053665/131824539-3d8f150e-9b67-4201-b042-9bd62aa79544.png)

**Comment by bwateratmsft** [comment]
I wasn't able to reproduce the issue on Windows; deployment was successful. One thing to double check @v-mengwe, is the `package.json` file next to the `Dockerfile` or is one or the other in a subfolder?

**Comment by v-ruizh** [comment]
@bwateratmsft Maybe this is an unstable issue. I tried this scenario several times on Windows/Mac/Linux, sometimes it can be built successfully. But most of the times it can be reproduced. The same error on Linux if the package.json file next to Dockerfile. Not sure the root cause. Could you try it more times?

**Comment by bwateratmsft** [comment]
Is the casing of the Linux file name exactly `package.json` or is it `Package.json` or something like that? Linux has a case-sensitive file system unlike Mac and Windows.

**Comment by v-mengwe** [comment]
Yes, this error is indeed caused by the `package.json` file in a subfolder on the Linux.
> One thing to double check for the Linux issue @v-mengwe, is the package.json file next to the Dockerfile or is one or the other in a subfolder?
![image](https://user-images.githubusercontent.com/62053665/132440842-67f3e003-5a6e-4447-b48d-4bbdf31501f8.png)

But, the same error as Windows/Mac occurs on Linux if the package.json file next to Dockerfile, and the Linux file name is `package.json`.

**Comment by bwateratmsft** [comment]
@v-mengwe can you share the project you are using?

**Comment by bwateratmsft** [comment]
@v-mengwe I think it has to do with the source location you are using on the file share. Something strange is going on with the files--I am not able to copy them locally; Windows complains that the destination location doesn't support encryption, asks me if I want to copy them anyway, and then doesn't actually copy them.

Can you see if it repros when you create a fresh express app on your local machine? More on how to create them here: https://expressjs.com/en/starter/generator.html

**Comment by v-mengwe** [comment]
Sorry for not being able to copy them, it's weird. You can create an Express App project with following commands:
```
npm install -g express-generator
express myApp
cd myApp
npm install
set DEBUG=myapp:* & npm start
```
Open the myApp folder in VS Code -> Add Docker related files to it -> Execute "Build Image in Azure..." to the dockefile file.
This issue reproduces when creating a fresh express app on local machine.
![image](https://user-images.githubusercontent.com/62053665/135195863-ccaafe38-c31e-4b53-a22c-0143d2da00a2.png)

**Comment by bwateratmsft** [comment]
Ok. I'll see if I can reproduce this issue. Maybe the failure to copy package.json is because of the strange file share.

**Comment by bwateratmsft** [comment]
I'm still not able to reproduce. But it looks like it might be some external issue:
https://github.com/Azure/azure-cli/issues/11455
https://github.com/Azure/azure-acr-plugin/issues/43
