### ISSUE TITLE
Docker-Extension

### ISSUE THREAD

**Issue by omkar120** [microsoft/vscode-docker#3186]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullImage
Error type: 1
Error Message: Process 'docker login --username "---" --password-stdi...' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.16.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4591337
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by karolz-ms** [comment]
@omkar120 is Docker installed on your machine? Can you successfully run any Docker command from the command line?
