### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SadeQ232** [microsoft/vscode-docker#3194]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.logInToDockerCli
Error type: 1
Error Message: Process 'docker login --username "---" --password-stdi...' exited with code 1
Error: Error response from daemon: Get "<redacted:url> net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Version: 1.16.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.60.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4594464
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Process.ChildProcess._handle.onexit child_process.js:288:5
```

</details>

**Comment by bwateratmsft** [comment]
This looks like a networking issue to me.
