### ISSUE TITLE
The term '-Command' is not recognized

### ISSUE THREAD

**Issue by pflannery** [microsoft/vscode-docker#3198]
My terminal profile on vscode v1.60.0 is set to use "Git Bash" on my Windows 10 pc.

Since installing the latest version of vscode-docker v1.16.1 I get the following error when trying "View Logs" for a container

```
> Executing task: docker logs --tail 1000 -f 473d01a1bc1601223fef027bfd2ad6ffe3d923ef78099049e6cdb79c4f11f379 <

-Command : The term '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -Command docker logs --tail 1000 -f 473d01a1bc1607755fef027bfd2ad6ffe ...
+ ~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (-Command:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

If I copy and paste the command `docker logs --tail 1000 -f 473d01a1bc1601223fef027bfd2ad6ffe3d923ef78099049e6cdb79c4f11f379` and run that in the vscode git bash terminal it works. I see the container logs as expected
 
I've also tried changing the contribution settings for logs to use `docker logs --tail 1000 -f ${containerId}`
but that gives the same error. 
I've also tried `com.docker.cli logs --tail 1000 -f ${containerId}`
and that also shows the same error

Seems that this extension isn't picking up my default terminal type.

**Comment by bwateratmsft** [comment]
This might be a bug in VSCode. @alexr00 any ideas? We're creating a shell task and executing it (https://github.com/microsoft/vscode-docker/blob/main/src/utils/executeAsTask.ts#L20-L68) but it looks like it's trying to use PowerShell.

**Comment by pflannery** [comment]
@bwateratmsft just got vscode v1.60.1 and its now fixed for me. Thanks for your help.
