### ISSUE TITLE
Error with Gitlab registry

### ISSUE THREAD

**Issue by J3m5** [microsoft/vscode-docker#3199]
After entering username and access token, I get this message: 
> Error: Cannot read property 'fullId' of undefined

My access token has the readRegistry and writeRegistry permission levels.

**Comment by bwateratmsft** [comment]
It looks like the minimum permission required is either `read_api` or `api`. Without this permission we are unable to enumerate the `api/v4/projects` endpoint.

I'm going to fix the issue with this unhelpful "fullId" error message though.

**Comment by J3m5** [comment]
Indeed, it works with the read_api scope.
Sorry for the unhelpful error message but I can't find more information about this error.

**Comment by bwateratmsft** [comment]
Not your fault at all! That's a bug in our code. With the fix I have in #3242 it will show the 403 Forbidden error which will help guide users to the issue. Additionally, I added some helper text to indicate the scopes needed when connecting the registry.

**Comment by J3m5** [comment]
Good idea, thanks for the help and the fix!

**Comment by bwateratmsft** [comment]
This fix is now released in Docker extension version 1.18.0. The "403 Forbidden" error will be shown directly to help indicate that the token has insufficient permissions.
