### ISSUE TITLE
remove all images is flakey

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#32]
multiple confirm prompts
last image is not removed

**Comment by lostintangent** [comment]
@chrisdias I don't see the multiple prompts (on macOS Sierra), but I definitely can repro the issue with the last image not being removed.

**Comment by PrashanthCorp** [comment]
This currently does not work due to the wrong string match in [this line](https://github.com/Microsoft/vscode-docker/blob/7c95b8dcc042b6cc7f4595684414b365d3146c02/commands/remove-image.ts#L19). 
Let me see if this still repros
