### ISSUE TITLE
How to use the docker extension when I am non-root user?

### ISSUE THREAD

**Issue by drxmy** [microsoft/vscode-docker#3205]
In vscode, I can run docker commends in terminal as a non-root user. But I can't see any images or container listed in the docker extension. It has this 'fail to connect. is docker running?' message.

Thank you for your time!
![WechatIMG161](https://user-images.githubusercontent.com/39789137/133030769-887c4feb-0abf-46f7-b556-1d4405d53c11.jpeg)

**Comment by bwateratmsft** [comment]
Can you give more info about your setup? What flavor of Linux, how did you set up Docker, etc.?

**Comment by drxmy** [comment]
> Can you give more info about your setup? What flavor of Linux, how did you set up Docker, etc.?

I am not sure why. But today it all work out. Maybe I need to restart my computer not just vscode. Sorry for wasting your time. And thank you for replying!

**Comment by bwateratmsft** [comment]
No worries! Glad it's working now!
