### ISSUE TITLE
Shows restart option for a stopped container 

### ISSUE THREAD

**Issue by aakashthakkar** [Microsoft/vscode-docker#321]
![restart container](https://user-images.githubusercontent.com/5239823/42960790-7f55d7ae-8b52-11e8-9269-0b82957b73ba.png)
For a stopped/existing container, it should show an option to start the container instead of restarting it.

**Comment by StephenWeatherford** [comment]
@aakashthakkar As noted in #322, we do not believe this warrants a fix at this moment, but we do appreciate the time you spent reporting it and supplying a potential fix.  If you feel strongly, you can re-open to discuss further.
