### ISSUE TITLE
Fail to build image of the "Dockerfile" file for the .NET 6.0 MVC project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3212]
**OS:** All
**Build Version:** 20210913.1
**.NET Version:** 6.0.100
**Regression:** Previous build 20210909.3

**Repro Steps:**

1. Create and open a .NET 6.0 MVC project in VS Code.
2. Add Docker files to this project -> Right click the "Dockerfile" file -> Select "Build Image...".
3. Check whether succeed to build image of the "Dockerfile" file.

**Expect:**
Succeed to build image of the "Dockerfile" file.

**Actual:**
Fail to build image of the "Dockerfile" file.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/62053665/133417318-e3638d58-a98c-464b-8295-91bf3388348e.png)

**Comment by bwateratmsft** [comment]
Probably due to a mismatch between the container's version of .NET 6 and the host machine's...this seems to always happen during .NET preview periods.

**Comment by v-mengwe** [comment]
This issue doesn't reproduce after updating the version of .NET 6 from `6.0.100-preview.7.21379.14` to `6.0.100-rc.1.21458.32`.

**Comment by bwateratmsft** [comment]
Thanks! That makes sense. The SDK image now contains `6.0.100-rc.1.21458.32`.

```
PS D:\vscode-docker> docker run -it mcr.microsoft.com/dotnet/sdk:6.0-focal
root@6031ff74bde5:/# dotnet --list-sdks
6.0.100-rc.1.21458.32 [/usr/share/dotnet/sdk]
```

I'll close this for now but if you see this come back please reopen it. Thanks!
