### ISSUE TITLE
Fail to deploy image to Azure Container Instances

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3215]
**OS:** Win10
**Build Version:** 20210916.1

**Repro Steps:**

1. Right click one image of registries view -> Deploy Image to Azure Container Instances... -> Create a new ACI.
2. Check whther succeed to deploy image to Azure Container Instances.

**Expect:**
Succeed to deploy image to Azure Container Instances without any error.

**Actual:**
Fail to deploy image to Azure Container Instances with an error.
![image](https://user-images.githubusercontent.com/62053665/133765228-0cbc3c17-18c8-440f-a9d1-5e8cc8c511ed.png)

**Comment by karolz-ms** [comment]
I cannot reproduce the problem:

```shell
> Executing task: docker --context acictx3 run -d -p 31117:31117 cr210728a.azurecr.io/hwflask:0.3 <

[+] Running 2/2
 - Group stupefied-borg  Created                                                                                                                                                                 2.1s
 - stupefied-borg        Created                                                                                                                                                                60.9s
stupefied-borg

C:\code\helloworldflask>docker ps
CONTAINER ID        IMAGE                              COMMAND             STATUS              PORTS
stupefied-borg      cr210728a.azurecr.io/hwflask:0.3                       Running             40.64.68.179:31117->31117/tcp

C:\code\helloworldflask>curl http://40.64.68.179:31117

    <!doctype html>
    <html>
      <head>
        <title>Amazing Flask app</title>
      </head>
      <body>
        <h3>Hello, World!</h3>
      </body>
    </html>

C:\code\helloworldflask>
```

To be fair, the repro steps do not indicate whether a new, or existing resource group and ACI context are used. I used a new resource group and a new ACI context.
