### ISSUE TITLE
The 'services' is in the list after typing version "1" and CTRL+SPACE in the "docker-compose.yml" file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3216]
**OS:** Win10/Mac
**Build Version:** 20210916.1
**VS Code Version:** 1.60.0
**Regression:** Previous Release

**Repro Steps:**

1. Open a project in VS Code -> Add Docker files to this project -> Open the "docker-compose.yml" file.
2. Change the version to "1" -> On the next line, type CTRL+SPACE. 
3. Check whether the 'services' is not in the list.

**Expect:**
The 'services' is not in the list.

**Actual:**
The 'services' is in the list.
1. The "docker-compose.yml" file has no other contents:
    ![image](https://user-images.githubusercontent.com/62053665/133764658-daaaecdc-2b83-474b-a482-5dcea7c55c53.png)
2. The "docker-compose.yml" file has other contents:
    ![image](https://user-images.githubusercontent.com/62053665/133764798-d9970eea-20c7-4049-8578-ff9941273104.png)

**More Info:**
1. The 'net' in the list changes to 'NET'.
    ![image](https://user-images.githubusercontent.com/62053665/133762423-8e514e22-c4da-41a2-a1f1-7af5003b8e0c.png)
2. The 'NET' is in the list if changing the version to "2".
    ![image](https://user-images.githubusercontent.com/62053665/133763201-682a899a-4984-4d2e-b7ed-d7072ab7d917.png)

**Comment by bwateratmsft** [comment]
This is expected at this time. We're working on the compose language service and opted to release it partially-completed. It will not explicitly support compose v1.
