### ISSUE TITLE
Brand new to the tech world.

### ISSUE THREAD

**Issue by BigDawg27** [microsoft/vscode-docker#3217]
Does this occur consistently? 
Repro steps:

1. No, just happened recently.
2. While working on a class with linkedin, I may have configured something the wrong way or I might've missed a step. I have a HP Chromebook x360 and I've just recently installed python 3.7.9 as well as a VScode app. Everything installed fine and worked well yesterday. This afternoon after installing recommended extension,Vim emulation. shortly afterwards I opened an exercise in the visual studio and had trouble trying to add to the assignment and opening Docker files so I then installed the Git Extension pack as recommended only to still remain stuck. Again I am new to the tech field so I hope that I explained things were you can understand my problem. Other than that I have no further issues, thank you for your time.
[Ex_Files_Programming_Foundations_Fundamentals.zip](https://github.com/microsoft/vscode-docker/files/7187857/Ex_Files_Programming_Foundations_Fundamentals.zip)
[Ex_Files_Programming_Foundations_Fundamentals.zip](https://github.com/microsoft/vscode-docker/files/7187864/Ex_Files_Programming_Foundations_Fundamentals.zip)
    

Action: vscode-docker.configure
Error type: EACCES
Error Message: EACCES: permission denied, open '/mnt/chromeos/archive/Ex_Files_Programming_Foundations_Fundamentals.zip/Ex_Files_Programming_Foundations_Fundamentals/Exercise Files/requirements.txt'

Version: 1.16.1
OS: linux
OS Release: 5.4.131-16046-g83914013f376
Product: Visual Studio Code
Product Version: 1.60.1
Language: en

**Comment by karolz-ms** [comment]
@BigDawg27 I assume you are going through some programming exercises involving Docker. Just a guess, but make sure you "unzip" (copy) the exercise files into a separate folder, and only then open the folder in VS Code. In other words, do not try to open the exercise directly from within the zip file. Let us know if that helps!

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
