### ISSUE TITLE
[Remote Codespaces] Fail to debug in the Remote Codespace environment

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3219]
**OS:** Remote Codespaces
**Build Version:** 20210916.1

**Repro Steps:**

1. Create a .NET Core MVC/Console project and open it in VS Code.
2. Add Docker files to workspace.
3. Change debug configuration to "Docker .NET Core Launch" -> F5.
4. Check whether succeed to debug.

**Expect:**
Succeed to debug in the Remote Codespace environment.

Actual:
Fail to debug in the Remote Codespace environment.
![debug4](https://user-images.githubusercontent.com/62053665/133882792-76538f5f-99ab-4a38-9bcb-3f48c4c498c3.gif)

**More Info:**
This issue also reproduces for other projects.
![debug2](https://user-images.githubusercontent.com/62053665/133882495-e427840d-b775-43b0-9bea-d32e9352cef8.gif)
![debug3](https://user-images.githubusercontent.com/62053665/133882692-00621c1e-4ede-46f7-9d9b-4c390d0d2f55.gif)
_Sometimes like this:_
![debug](https://user-images.githubusercontent.com/62053665/133882825-c8b62c9a-bf25-48ba-91e1-66f8246e0936.gif)

**Comment by bwateratmsft** [comment]
Seems like this might be a VSCode bug, it shouldn't be offering to debug the Dockerfile.

**Comment by bwateratmsft** [comment]
I've found this only reproduces in the browser-based Codespaces. Still investigating why it's offering to debug a Dockerfile.

**Comment by bwateratmsft** [comment]
I can confirm this is definitely external--it happens even with non-Docker-related debugging scenarios--but I can't work out what is _supposed_ to be happening.

**Comment by bwateratmsft** [comment]
Hey @connor4312, @alexr00 recommended I ask you about this one. It seems like VSCode half thinks it's in a cloud-hosted codespace (it is), and half thinks it's not.

**Comment by connor4312** [comment]
I'm not sure what the issue here is, or what you mean by "half thinks it's in a cloud-hosted codespace / half thinks it's not."

**Comment by connor4312** [comment]
Oh, you're probably hitting https://github.com/microsoft/vscode/issues/133178

**Comment by bwateratmsft** [comment]
Thanks! I'll see if this repros on Insiders, if not then I agree it must be microsoft/vscode#133178.

**Comment by bwateratmsft** [comment]
Yep, it's working as expected in Insiders. Thank you!
