### ISSUE TITLE
unable to sign in to docker hub

### ISSUE THREAD

**Issue by zheroed** [microsoft/vscode-docker#3226]
Does this occur consistently? Yes
Repro steps: 

1.Click on Connect Registry in the docker explorer panel
2.Enter docker ID and password

expected to be connected to Docker Hub 

actual:  Error: The name org.freedesktop.secrets was not provided by any .service files
Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freede---ktop<redacted:id>ecret--- wa--- not provided by any .---ervice file---

Version: 1.16.1
OS: linux
OS Release: 5.13.15-1-MANJARO
Product: VSCodium
Product Version: 1.60.2
Language: en

**Comment by bwateratmsft** [comment]
Duplicate of #2925. You'll need to install `gnome-keyring`.
