### ISSUE TITLE
Dockerfile linting does not recognize a registry with a port

### ISSUE THREAD

**Issue by zeddicus76** [Microsoft/vscode-docker#323]
With the following FROM line in a Dockerfile:
```
FROM my.registry:7744/myproject/python-base:3.6.5
```
I get this error with the `3.6.5` underlined
"[dockerfile-utils] "message": "invalid reference format"

If I remove the port from my registry, the linting error goes away.

**Comment by StephenWeatherford** [comment]
@zeddicus76 Thanks for taking the time to report this. I'm happy to say this has been fixed, and will be available with the next update (see #https://github.com/Microsoft/vscode-docker/issues/288).

**Comment by StephenWeatherford** [comment]
@zeddicus76 Just wanted to let you know that we have published a new version of the Docker extension that should contain this fix.  Happy coding!
