### ISSUE TITLE
There is a duplicate terminal log when running "Compose Down task" with "Compose V2" enabled

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3233]
**OS:** Win 10
**Build Version:** 20210922.5
**Regression:** Not a Regression

**Repro Steps:**
1. Open Docker Desktop settings -> Experimental Features -> Enable "Use Docker Compose V2 release candidate".
2. Create and open a .NET MVC project in VS Code Insiders.
3. Add Docker files to this project.
4. Add a compose up task and down task in .vscode/tasks.json file with the following code.
```
{
            "type": "docker-compose",
            "label": "My Docker Compose Up task",
            "dockerCompose": {
                "up": {
                    "detached": true,
                    "build": true,
                    "scale": {
                        "mvc": 1
                    },
                    "services": [
                        "mvc"
                    ]
                },
                "files": [
                    "${workspaceFolder}/docker-compose.yml",
                    "${workspaceFolder}/docker-compose.debug.yml"
                ]
            }
        },
        {
            "type": "docker-compose",
            "label": "My Docker Compose Down task",
            "dockerCompose": {
                "down": {
                    "removeVolumes": false,
                    "removeImages": "local"
                },
                "files": [
                    "${workspaceFolder}/docker-compose.yml",
                    "${workspaceFolder}/docker-compose.debug.yml"
                ]
            }
    }
```
5. F1 -> Tasks: Run Task -> Select "My Docker Compose Up task" to run.
6. F1 -> Tasks: Run Task -> Select "My Docker Compose Down task" to run.
7. Check whether there is a duplicate terminal log during stopping the container.

**Expect:**
There is no duplicate terminal log.

**Actual:**
There is a duplicate terminal log during stopping the container.
![image](https://user-images.githubusercontent.com/45614674/134636835-3b7bced0-334d-486a-8d39-b50a24c22d7e.png)

**More Info:**
This issue does not reproduce with "Use Docker Compose V2 release candidate" disabled.
![image](https://user-images.githubusercontent.com/45614674/134637247-0e707211-e0b6-44ed-a61b-976e3e6745ad.png)

**Comment by bwateratmsft** [comment]
This is an artifact of the way compose is emitting to terminal in combination with the way VSCode handles the terminal. Not something under our control unfortunately.
