### ISSUE TITLE
Unable to connect to docker when using DOCKER_HOST

### ISSUE THREAD

**Issue by mrd030485** [microsoft/vscode-docker#3234]
Does this occur consistently? Yes
Repro steps:
1. Add DOCKER_HOST=tcp://1.2.3.4:2376
2. Add DOCKER_TLS_VERIFY=1
3. View Docker tab in vs code
4. Error: Socket is closed

Note:  With the environment variables set running docker in the terminal works both in and outside of vscode.  There are no errors in the logs or errors accessible beyond the socket is closed message.

Version: 1.17.0
OS: linux
OS Release: 5.11.0-16-generic
Product: Visual Studio Code
Product Version: 1.60.2
Language: en

**Comment by bwateratmsft** [comment]
I think this is #2058 right @karolz-ms?

**Comment by karolz-ms** [comment]
@bwateratmsft  yeah, that would be my guess as well

**Comment by bwateratmsft** [comment]
I'll resolve as dupe then. @mrd030485, you can probably use the `docker.dockerodeOptions` setting to set up certificates to work correctly.

**Comment by mrd030485** [comment]
@bwateratmsft I have looked and could not find any documentation on what is expected in the `docker.dockerodeOptions` 
I did look at the dockerode project and tried to figure it out but it it give me a `Cannot read property 'request' of undefined` error.  Are there any docs you can point me to for configuration?

**Comment by bwateratmsft** [comment]
Does it give any more information like a call stack for that error?
