### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by mondiniit** [microsoft/vscode-docker#3240]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
ChildProcess.EventEmitter.emit domain.js:475:20
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:223:5
Socket.EventEmitter.emit domain.js:475:20
Pipe.<anonymous> net.js:664:12
```

</details>

**Comment by bwateratmsft** [comment]
This is an old version of the Docker extension. Please update to the latest (1.17.0).
