### ISSUE TITLE
Docker login Client.Timeout using CLI

### ISSUE THREAD

**Issue by NoneelPrasad** [microsoft/vscode-docker#3251]
Does this occur consistently? Yes
Repro steps:
-Able to login on Docker Hub.
-Able to access registry through Docker extenstion in VSCode

-Unable to login using the CLI -> Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

1.docker login -u <username>
2.tried with both password and security token
3.Connected to home internet 

Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by bwateratmsft** [comment]
Is this error coming from the CLI itself or the extension?

**Comment by NoneelPrasad** [comment]
Yes from the CLI.
I can pull and run images from the hub however cannot push images due to the error mentioned.

**Comment by NoneelPrasad** [comment]
Closing this issue.
Just changed my ISP and worked.
