### ISSUE TITLE
Support Docker rootless mode on linux

### ISSUE THREAD

**Issue by VeraSimon** [microsoft/vscode-docker#3257]
While the vscode-docker extension supports running as a non-root user on Linux as [documented here](https://code.visualstudio.com/docs/containers/overview#_installation), Docker's documentation on [setting that up](https://docs.docker.com/engine/install/linux-postinstall/) is very explicit about the security implications of doing so. In the same piece of documentation, they link to how to [set up Docker to run in rootless mode](https://docs.docker.com/engine/security/rootless/), but the vscode-docker extension doesn't see the running daemon due to the socket not being located at /var/run/docker.sock, but under a directory in /run/user associated with the users ID. Adding support for rootless mode would allow a setup path that doesn't needlessly reduce the security of the user's system in order to run the vscode-docker extension.

**Comment by VeraSimon** [comment]
Found workaround by setting docker.host to the unix socket path in settings.json

**Comment by bwateratmsft** [comment]
I agree, I think we should update the README [section](https://github.com/microsoft/vscode-docker#installation) and maybe the docs as well where rootless is mentioned to include setting up either a Docker context, `DOCKER_HOST` environment variable, or `docker.host` extension setting to the correct socket path.
