### ISSUE TITLE
Add an `Update` context menu entry to change running containers configuration

### ISSUE THREAD

**Issue by Delapouite** [microsoft/vscode-docker#3261]
Hello

## Current situation

When right clicking on a running container in the dedicated panel, a few actions are available. To name a few: `View logs`, `Attach Shell`, `Restart`…

By choosing `Inspect`, a read-only editor opens, displaying the current configuration of the container as a JSON which is great.
But sometimes, you need to adjust one of the value and there's no easy way to do it.

Here's a concrete example. In the morning, when I start my work-day, I start the docker daemon on my dev station. Some of my containers are also started automatically at the same time. It's because they have the following config value:

``` json
"RestartPolicy": {
    "Name": "always",
    "MaximumRetryCount": 0
},
```

For some of them, I'd like to disable this restart behavior and turn this policy to `no`.

I understand that it would be quite adventurous at first, to remove the read-only flag on the editor displaying the result of the inspect command, in order to let each subsequent "change" → "save" sequence automatically update the associated container.

## Proposal

So maybe a first step in this direction, would be to add a `Update` action in the right-click menu of a container.

This action would then trigger the display of the palette command asking which option should be updated, as documented on the official doc page : https://docs.docker.com/engine/reference/commandline/update/

So it my example, I would be free to choose the `restart` entry in the palette. After validating this choice by pressing the return key, the palette changes, and now offers the different possibilities for this `restart` option: `no`, `always`, `unless-stopped` and `on-failure`. Then I if select the `no` value, the `docker update --restart=no foo` is applied under the hood.

Thanks!

**Comment by ucheNkadiCode** [comment]
Hey @Delapouite! For the purposes of our extension, containers are immutable by design. As @bwateratmsft mentioned, the docker update command is limited and since this command is still accesssible from terminal, we will not do this feature at this time. 

We would recommend using a [Custom Task](https://code.visualstudio.com/docs/editor/tasks) if this is a command you run often.

Thank you for your feedback!
