### ISSUE TITLE
Make a CLI-only `DockerApiClient`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3263]
We need an implementation of [`DockerApiClient`](https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerApiClient.ts) that uses CLI only. This will work better with a wider range of scenarios than the CLI + HTTP daemon through Dockerode + gRPC daemon. Plus it mostly removes the need to look up the Docker context during activation...

Potentially resolves:
- #2058
- #3295, #3590, #3605
- #3241, #1590, #3306, #3367, #3411
- #2941, #2933, #3578
- #2391
- #3475
- #3596
- _Maybe_ #2442

Related to #2977, #3281

**Comment by bwateratmsft** [comment]
I've noticed that `com.docker.cli` tends to be drastically faster than `docker`.

**Comment by bwateratmsft** [comment]
Work is ongoing for this, it will need to be moved to the 1.21.0 milestone.

**Comment by ucheNkadiCode** [comment]
We are continuing to work on a path forward for supporting other Container runtimes. This will be moved to the 1.22 milestone.

**Comment by bwateratmsft** [comment]
I know a lot of folks are interested so I wanted to give an update. Work on this is proceeding in earnest right now (as in, we're past most of the planning and really writing code!). We have rather ambitious plans so it will take some time.

**Comment by benatshippabo** [comment]
> I know a lot of folks are interested so I wanted to give an update. Work on this is proceeding in earnest right now (as in, we're past most of the planning and really writing code!). We have rather ambitious plans so it will take some time.

Thanks for the update @bwateratmsft! I'm so glad this is underway

**Comment by bwateratmsft** [comment]
Thanks for your thoughts, we appreciate the input! I'll try to address some of your questions here:

> Do want to start a branch for this? would you accept contributions/ideas?

The key work on the container runtimes library is still in a private repository but we should be opening it up soon; certainly some time before release. I'll update on this issue once it is opened. We love contributions!

> so can multiple extensions be installed and the first one to run, or do they all run

The architecture we're envisioning is that the Docker extension would permit other extensions to register a container runtime provider conforming to a specific interface. It would also register a Docker provider conforming to that interface with itself. Thus, the Docker extension would always be present; marked as a dependency of the other extensions. In addition, the Docker extension would need some kind of experience for choosing which provider should be active; I'm thinking of doing something like what Python has for selecting the interpreter path--that is, an item in the status bar, and when you click it, it allows you to select which provider to use. Separately from all this work in the Docker extension, we (Microsoft) would probably work on these "sidecar" extension(s) for Podman and Nerdctl.





As you noted, there are significant advantages to using the HTTP API, instead of the CLI. It's more compatible and much faster. However, we've found a common class of issues (most of them linked in the original comment) that basically boil down to "I have the CLI working, why doesn't the explorer view work?" We are taking a risk using the CLI, but we're hoping that we can avoid the worst of it by continuing to be agile with releases of the extensions. Based on data we've seen, users update VSCode extensions _very_ quickly--usually immediately upon startup, often before the extension activates. Since auto-updating is the default, this isn't terribly surprising. Our hope is that if we encounter a break in the CLI, we can get a fix out to users very quickly.

For what it's worth, the Remote - Containers extension went through similar challenges and also ended up going CLI-only.

**Comment by bwateratmsft** [comment]
Thanks for your thoughts, we appreciate the input! I'll try to address some of your questions here:

> Do want to start a branch for this? would you accept contributions/ideas?

The key work on the container runtimes library is still in a private repository but we should be opening it up soon; certainly some time before release. I'll update on this issue once it is opened. We love contributions!

> so can multiple extensions be installed and the first one to run, or do they all run

We think that, fundamentally, all of the runtimes deal with the same objects and offer the same operations on those objects. There are exceptions of course (e.g. Podman doesn't have contexts, as far as I'm aware), so we'll need a reasonable user experience in those cases, but I think that's manageable. Consequently, we can create a common interface to abstract away the specific runtime.

The architecture we're envisioning is that the Docker extension would permit other extensions to register a container runtime provider conforming to that common interface (and it would also register a Docker provider with itself). Thus, the Docker extension would always be present; marked as a dependency of the other extensions. In addition, the Docker extension would need some kind of experience for choosing which provider should be active; I'm thinking of doing something like what Python has for selecting the interpreter path--that is, an item in the status bar, and when you click it, it allows you to select which provider to use. There also needs to be graceful handling for when these extensions are uninstalled without the setting being updated. Separately from all this work in the Docker extension, we (Microsoft) would probably work on these "sidecar" extension(s) for Podman and Nerdctl.

> when you say 'cli' do you mean literally a shellExecute?

Yes, mostly. There are some operations that we perform behind-the-scenes in a non-visible shell. There are also others that we very deliberately execute in the VSCode terminal as a task, so that users can see both the command itself and the output (for example, building images). Naturally, we'll need to make both of these work regardless of the runtime in use.

As you noted, there are significant advantages to using the HTTP API, instead of the CLI. It's more compatible and much faster. However, we've found a common class of issues (many of them linked in the original comment) that basically boil down to "I have the CLI working, why doesn't the explorer view work?" We are taking a risk using the CLI, but we're hoping that we can avoid the worst of it by continuing to be agile with releases of the extensions. Based on data we've seen, users update VSCode extensions _very_ quickly--usually immediately upon startup, often before the extension activates. Since auto-updating is the default, this isn't terribly surprising. Our hope is that if we encounter a break in the CLI, we can get a fix out to users very quickly.

For what it's worth, the Remote - Containers extension went through similar challenges and also ended up going CLI-only.

**Comment by wenbingzhang** [comment]
This is how I set up support for podman

settings.json
```
    "docker.host": "tcp://192.168.64.3:2979",
    "docker.dockerPath": "podman",
```

podman-remote
```
# user=root
/usr/bin/podman system service --time=0 tcp:0.0.0.0:2979
```

<img width="603" alt="image" src="https://user-images.githubusercontent.com/13162606/176151505-c7db3da5-0e24-43de-91d6-6279d1ccdd8a.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/13162606/176151618-b4e73674-78b2-451c-aefc-83a5852e69d4.png">

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.

**Comment by gliptak** [comment]
`1.23.0` still shows

![image](https://user-images.githubusercontent.com/50109/204365042-3faf11ed-ab2d-4b62-9c44-59d16e6dd849.png)

with

```
    "docker.dockerPath": "/usr/bin/podman",
```

was above to be corrected in this update?

Name: Docker
Id: ms-azuretools.vscode-docker
Description: Makes it easy to create, manage, and debug containerized applications.
Version: 1.23.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker

**Comment by bwateratmsft** [comment]
Podman isn't intended to work yet, still working on that in #3241 / #1590.

**Comment by gliptak** [comment]
#1590
