### ISSUE TITLE
Fail to debug Express app with an error "Couldn't find a debug adapter descriptor for debug type 'pwa-node' (extension might have failed to activate)" in VS Code Insider

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3264]
**OS:** Win 10/Mac
**Build Version:** 20211013.1
**VS Code Insider:** 1.62.0-insider

**Repro Steps:**
1. Open an Express app in VS Code Insiders.
2. Add Docker related files to it.
3. Debug this project.
4. Check whether succeed to debug this Express app or not.

**Expect:**
Succeed to debug this Express app without any error.

**Actual:**
Fail to debug this Express app with an error "Couldn't find a debug adapter descriptor for debug type 'pwa-node' (extension might have failed to activate)".
![image](https://user-images.githubusercontent.com/45614674/137274878-fbad12b6-2a16-40b6-a9b8-4b75442ec054.png)

**More Info:**
This issue does not reproduce in VS Code 1.61.0.

**Comment by bwateratmsft** [comment]
It's not really a good workaround for customers but it should unblock testing; if you force the activation of the Javascript Debugger extension by launching this launch config, it should start working for the rest of the session:

```json
{
    "configurations": [
        {
            "name": "Javascript Debugger Activator",
            "type": "pwa-node",
            "request": "attach"
        }
    ]
}
```

**Comment by bwateratmsft** [comment]
Verified this is now fixed in the latest VSCode Insiders.
