### ISSUE TITLE
The error message is inconsistent in the different contexts when executing "Attach Shell" -> "Remove..." to a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3265]
**OS:** Win 10
**Build Version:** 20211013.1

**Repro Steps:**

1. Use the default context -> Right click a running container under the "CONTAINERS" node -> Select "Attach Shell" -> Select "Remove...".
![image](https://user-images.githubusercontent.com/62053665/137295914-47c83269-52c3-4f0e-b9a7-5c22da0302db.png)
2. Check the error message in the terminal.
3. Use the non-default context -> Right click a running container under the "CONTAINERS" node -> Select "Attach Shell" -> Select "Remove...".
![image](https://user-images.githubusercontent.com/62053665/137296021-950d783f-7450-4b18-abfe-9fe73491916b.png)
4. Check the error message in the terminal.
5. Check whether the error message is consistent in the different contexts.

**Expect:**
The error message is consistent in the different contexts.

**Actual:**
The error message is inconsistent in the different contexts.
![image](https://user-images.githubusercontent.com/62053665/137295615-1a4883cf-ec52-4682-a079-4b1568cdecf3.png)

**Comment by bwateratmsft** [comment]
These error messages come from the Docker CLI so we cannot change them.
