### ISSUE TITLE
When debugging JS inside a Docker container, sourcemaps are resolved against CWD instead of `localRoot`.

### ISSUE THREAD

**Issue by jwalton** [microsoft/vscode-docker#3277]
I have a Typescript project which generates sourcemaps in /dev/myproject.  In the container, there's a `/usr/src/app/dist` folder that's full of ".js" and ".js.map" files.  The sourcemaps all have relative references to the source:

```json
"sources":["../src/app.ts"]
```

In VSCode, I create a task to launch the container:

<details>
<summary>"docker-run: int" task</summary>

```json
    {
      "type": "docker-run",
      "label": "docker-run: int",
      "dependsOn": ["docker-build"],
      "options": { "cwd": "${workspaceFolder}" },
      "dockerRun": {
        "env": {
          "DEBUG": "*",
          "NODE_ENV": "development"
        },
        "volumes": [
          {
            "localPath": "${env:HOME}/.aws/credentials",
            "containerPath": "/home/node/.aws/credentials"
          }
        ],
        "command": "node --inspect-brk=0.0.0.0:9229 ./dist/transcoder_server.js int debug temp_folder=/tmp"
      },
      "node": {
        "enableDebugging": true
      }
    }
 ```

</details>
 
 And then I have a launch configuration:
 
 <details>
<summary>"Docker - Int" launch config</summary>

 ```json
     {
      "type": "docker",
      "name": "Docker - Int",
      "request": "launch",
      "preLaunchTask": "docker-run: int",
      "platform": "node",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/usr/src/app",
    },
 ```

</details> 
 
Now, if I close all running copies of vscode, and do:

```sh
$ cd ~/dev/myproject
$ code .
```

Then try to start a debugging session, my sourcemaps all resolve correctly!  If I close all running copies of vscode and do:

```sh
$ cd ~
$ mkdir test
$ cd test
$ code .
$ cd ~/dev/myproject
$ code .
```
 
Here I started vscode in ~/test, so it's `cwd` is ~/test, and then I opened a second window in ~/dev/myproject.  When I try to debug in that second window, I get:

```
Could not load source '/Users/jwalton/src/app.ts': Unable to retrieve source content.
```

vscode seems to be trying to resolve the sourcemap against `cwd` instead of against the `localRoot` defined in the task or the `options.cwd` defined in the tasks.json.

**Comment by bwateratmsft** [comment]
This might be a Mac thing, in Windows the `cwd` seems to always be `"C:\Users\userName\AppData\Local\Programs\Microsoft VS Code"`.

@philliphoff do you know where the code for resolving the source maps would be? Our [code](https://github.com/microsoft/vscode-docker/blob/main/src/debugging/node/NodeDebugHelper.ts#L95-L98) substitutes in `'${workspaceFolder}'` if it is `undefined` (which is not the case here) so I'm guessing that VSCode itself is doing something wrong here?

**Comment by bwateratmsft** [comment]
@jwalton can you try debugging locally (no Docker) and see if the same issue occurs? This seems to me like a JS debug issue, not anything to do with the Docker extension.
