### ISSUE TITLE
Switch to PowerShell WMI provider

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#3282]
On Windows containers , the extension uses WMI to acquire file metadata, via the `wmic` utility.  This utility has been deprecated in Windows 11, in favor of using PowerShell WMI command-lets instead (e.g. `Get-WmiObject`).  At some point, Windows 11 container images will no longer ship with `wmic`; we need to move to the PowerShell equivalent.  (Windows 10 images should ship with both utilities.)

**Comment by bwateratmsft** [comment]
Putting here something we discussed offline; if we're using PowerShell anyway maybe we can use `Get-ChildItem` and get WMI out of the equation.
