### ISSUE TITLE
Add a way to filter or distinguish dangling volumes

### ISSUE THREAD

**Issue by Delapouite** [microsoft/vscode-docker#3283]
Hi

In the left sidebar, the `images` panel has a button to show/hide dandling images.
Unfortunately there's no such things for `volumes` yet.

This kind of information about which volumes are bound with containers is available in the output of `docker system df --verbose`. 

Example of output of the command above :

```
VOLUME NAME  LINKS  SIZE
foo           1     34.24MB
bar           0     377.9MB
qux           0     516MB
```

Possibility to resurface the size of each volume in the VSCode sidebar would also be great.

Thanks

**Comment by ucheNkadiCode** [comment]
In this case, I'd propose that the button would be to Show All Volumes/ Show Only Dangling Volumes.

**Comment by bwateratmsft** [comment]
@Delapouite one feature that exists today, and may be helpful if you have relatively few volumes, is the tooltips if you hover over a volume with the mouse pointer:
![image](https://user-images.githubusercontent.com/36966225/142030933-f375f447-74e7-46ac-b0c7-2b457a95e110.png)
![image](https://user-images.githubusercontent.com/36966225/142030786-b3819dcd-ea0b-42c9-ab24-314e30365b87.png)

This contains a list of containers that are associated.

**Comment by dbreshears** [comment]
This information can be obtained from the tooltip, closing since we don't have plans to provide this elsewhere
