### ISSUE TITLE
Change Functionality of Show Dangling Images to Show Only Dangling/Show All Images

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#3290]
When I click Show dangling images - right now it toggles between either showing both used containers and unused (dangling) containers OR used containers. 

I propose that the show dangling containers button should show ONLY the images that are unsused even if it's an empty list, then clicking the button once more should show ONLY the used containers. This would help a user know exactly what would get pruned. 

This would include conditional text based on what the user had selected

**Comment by bwateratmsft** [comment]
I looked into this further and it would require changing the interface' meaning: https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerApiClient.ts#L37

It's  _probably_ safe to do so but I'm not real excited about that. Though perhaps it would be more practical once #3263 is done.

**Comment by ucheNkadiCode** [comment]
> I looked into this further and it would require changing the interface' meaning: https://github.com/microsoft/vscode-docker/blob/main/src/docker/DockerApiClient.ts#L37
> 
> It's _probably_ safe to do so but I'm not real excited about that. Though perhaps it would be more practical once #3263 is done. A slightly-updated interface could have a trinary where it's `'NonDanglingOnly' | 'DanglingOnly' | 'All'`.

That's definitely an option, we could also do "isDangling: boolean" which would make it more of a toggle. How would that be represented in the extension? Would it be a dropdown menu pretty much? 

I like the trinary idea through since we want there to be a way for the user to see all of their images, all the dangling images (which totally could be empty if all images are being used), or just the NON-dangling aka currently used images (which could be empty as well )

**Comment by bwateratmsft** [comment]
I don't think a trinary in the extension UX is necessary, just in the interface.

Honestly I'm a little skeptical of showing dangling images in general...they are all tagged "<none>:<none>" which is not helpful. All the clearly-identifying information (namely the tag) has been stripped; this is Docker's design. But, we have the feature now, so a takeback isn't a good idea.

**Comment by bwateratmsft** [comment]
Per discussion we'll won't-fix this, the changes in #3336 are good enough for now.
