### ISSUE TITLE
Explore possible use cases for VSCode's new Terminal Profiles feature

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3297]
VSCode added a cool new [Terminal Profiles](https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles) feature, we should think about if there are any use cases for that in the Docker extension.

As an example, the [Azure Account](https://github.com/microsoft/vscode-azure-account) extension is adding profiles for Azure Cloud Shell (both bash and PowerShell).
![image](https://user-images.githubusercontent.com/36966225/140328076-65898c76-ab47-428a-97a0-176a5a96afde.png)

**Comment by bwateratmsft** [comment]
I can't think of anything to do here. The only thing that comes to mind is a way to attach a shell to containers, but the way the terminal provider's registrations work, we would have to register a provider for _each_ container; it would be hacky at best and is far from the intended use case of terminal providers.

If Docker had an interactive CLI that would be an obvious candidate but that isn't the case.

**Comment by ucheNkadiCode** [comment]
@bwateratmsft Okay I trust your judgment, let's hold off on this for now
