### ISSUE TITLE
Is there a way to create an ACI context which will run windows containers?

### ISSUE THREAD

**Issue by TravisEz13** [microsoft/vscode-docker#3299]

**Comment by bwateratmsft** [comment]
It looks like maybe you don't need to do anything with the context, just use a Windows base image: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-overview#linux-and-windows-containers

**Comment by TravisEz13** [comment]
This is what I get when I try from the command line after creating the ACI:
```
❯ docker --context tplunkacicontext run mcr.microsoft.com/powershell:nanoserver
[+] Running 0/1
 ⠿ Group busy-napier  Error                                                                                                                                                    3.6s
containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ImageOsTypeNotMatchContainerGroup" Message="The container image 'mcr.microsoft.com/powershell:nanoserver' doesn't support specified OS 'Linux' for container group 'busy-napier'."
```

**Comment by karolz-ms** [comment]
This problem is probably outside of VS Code extension scope. I would suggest opening an issue against https://github.com/docker/compose-cli

**Comment by TravisEz13** [comment]
Existing issue:  https://github.com/docker/compose-cli/issues/657
