### ISSUE TITLE
upload files into docker

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-docker#3302]
Is there a way to upload files into docker?

i can access docker file system . view/edit/download file . but i cant upload file. 

Is there any easy way to do it?

**Comment by bwateratmsft** [comment]
There isn't anything provided by the extension, but you can copy files in using the command line:

`docker cp myFile.txt <containerNameOrId>:/destination/path`

e.g.

`docker cp myFile.txt 2db0:/home`

@philliphoff is there a good way you can think of to copy files in, from a UX perspective? The tree view might not avail us here...
