### ISSUE TITLE
Install Another Version hangs

### ISSUE THREAD

**Issue by spg** [microsoft/vscode-docker#3303]
When I click on Install Another Version, the version list is empty and keeps loading forever
Extension version: v1.17.0
VS Code Version: 1.62.0

![Screen Shot 2021-11-08 at 6 39 40 AM](https://user-images.githubusercontent.com/892367/140735759-4ebca814-5526-4977-8bf9-6a7baa06d919.png)
![Screen Shot 2021-11-08 at 6 40 27 AM](https://user-images.githubusercontent.com/892367/140735835-6393b7ec-fb5f-4e56-aa81-30c4e40989ec.png)

**Comment by bwateratmsft** [comment]
This functionality is provided by VSCode, not the Docker extension. Please file an issue there: https://github.com/microsoft/vscode/issues

**Comment by spg** [comment]
Well it works properly for every other extension (e.g. ESLint, GitLens, Prettier, etc)
That's why I was thinking there might be a problem with the registry where you host the extension versions

**Comment by bwateratmsft** [comment]
All are hosted by the VSCode extension marketplace; we don't have anything special going on with the Docker extension in particular for that.
