### ISSUE TITLE
allow preLaunchTask and postDebugTask when using docker attach

### ISSUE THREAD

**Issue by sw34** [microsoft/vscode-docker#3304]
Currently according to the documentation https://code.visualstudio.com/docs/containers/docker-compose#_debug if debugging docker containers that are started with docker compose, you must run docker compose up in terminal/command pallet/right click compose file, then you can run the debugger to attach to the container.  Once done you need to run docker compose down to stop the containers.

What I would like to have is a preLaunchTask that will run docker compose up, and a postDebugTask that will run docker compose dowm.

**Comment by chrmarti** [comment]
This sounds like it would belong to the Docker extension (not Remote-Containers). Moving there.

**Comment by bwateratmsft** [comment]
I think this might already work, but I need to test it out to be sure.

**Comment by bwateratmsft** [comment]
What type of app do you have @sw34? Node, Python, .NET?

**Comment by sw34** [comment]
.Net 5 (actually now 6) web api

**Comment by bwateratmsft** [comment]
Ok, here's what I got working with a .NET 6 MVC app:

In `.vscode/launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Docker .NET Core Attach (Preview)",
            "type": "docker",
            "request": "attach",
            "platform": "netCore",
            "sourceFileMap": {
                "/src": "${workspaceFolder}"
            },
            "netCore": {
                "debuggerPath": "/remote_debugger/vsdbg" // This is the path to vsdbg in the container
            },
            "containerName": "net6-net6-1", // `net6` is the name of my app, you can replace with your app name--whatever gets started by compose up
            "preLaunchTask": "Compose Up",
            "postDebugTask": "Compose Down"
        },
    ]
}
```

In `.vscode/tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compose Up",
            "type": "docker-compose",
            "dockerCompose": {
                "up": {
                    "detached": true,
                    "build": true
                },
                "files": [
                    "${workspaceFolder}/docker-compose.debug.yml" // Running the debug one is important, it overloads the `ASPNETCORE_ENVIRONMENT` environment variable and maps in the debugger from ~/.vsdbg.
                     // You can add more compose files using the usual layering mechanics, but put docker-compose.debug.yml last.
                ]
            }
        },
        {
            "label": "Compose Down",
            "type": "docker-compose",
            "dockerCompose": {
                "down": {
                    "removeVolumes": false
                },
                "files": [
                    "${workspaceFolder}/docker-compose.debug.yml"
                ]
            }
        },
    ]
}
```

One prerequisite ahead of time (there's a good chance you've already met it), to make sure `vsdbg` gets downloaded. If you have the "Docker .NET Core Launch" debug configuration, you can run it, and it will download the debugger if it doesn't already have it. Even if it doesn't succeed in actually debugging, that's fine; the debugger download at the beginning is the only important part.

Can you try this approach and see if it works?
