### ISSUE TITLE
App cannot read mounted NuGet packages from /root/.nuget/packages when using generated Dockerfile

### ISSUE THREAD

**Issue by dwoldo** [microsoft/vscode-docker#3305]
I am attempting to debug a .NET Container Linux container from my Windows 10 machine. The Dockerfile was generated by this extension when running `Docker: Add Docker Files to Workspace`. 

Upon running debug using the generated launch item `Docker .NET Core Launch`, this extension runs the container for debugging, but the NuGet packages folder is mounted to `/root/.nuget/packages` inside the container. This is a problem because the Dockerfile generated by this extension runs the app as `appuser` rather than `root` (which is best practice). Therefore, the app can neither resolve or access the mounted NuGet packages folder at `/root/.nuget/packages`. This results in an inability for the app to access the mounted .nuget/packages and any `staticwebassets`.

Steps to Reproduce (repro repo: https://github.com/dwoldo/repro-root-vscode-debug)
1. dotnet new console
2. code \<console app folder\>
3. Open command pallet (Windows: CTRL + SHIFT + P), select `Docker: Add Docker Files to Workspace...`
4. Choose `.NET: Core Console App` for "Select Application Platform" prompt
5. Choose `Linux` for "Select Operating System" prompt
6. Choose `No` for "Include optional Docker compose files?" prompt.
7. Open the generated Dockerfile and observe line 6 and 7, running as `appuser`
   ![image](https://user-images.githubusercontent.com/10914645/140760173-f976cb61-d5f7-4fb2-8b3f-e9f67d6c0d1f.png)
7. From "Run and Debug" start debugging `Docker: .NET Core Launch`
8. From "docker-run: debug" terminal display, observe the volume mount `-v "C:\Users\<Username>\.nuget\packages:/root/.nuget/packages:ro"`:

   ```docker run -dt -P --name "reprorootvscodedebug-dev" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" --label "com.microsoft.created-by=visual-studio-code" -v "C:\repos\throwaway\repro-root-vscode-debug:/app:rw" -v "c:\repos\throwaway\repro-root-vscode-debug:/src:rw" -v "C:\Users\<Username>\.vsdbg:/remote_debugger:ro" -v "C:\Users\<Username>\.nuget\packages:/root/.nuget/packages:ro" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro" "reprorootvscodedebug:dev"```

Work Around:
1. Remove Line 6 and 7 from Dockerfile (not recommended).

Possible Fix:
1. Replace all hard-coded paths for `/root/.nuget` in https://github.com/microsoft/vscode-docker/blob/4e7ba64d90204cc9b18ef068cda6b64ccc282fa5/src/tasks/netcore/NetCoreTaskHelper.ts with the dynamic user read-in from Dockerfile seen here: https://github.com/microsoft/vscode-docker/blob/4e7ba64d90204cc9b18ef068cda6b64ccc282fa5/src/tasks/netcore/NetCoreTaskHelper.ts#L262

**Comment by karolz-ms** [comment]
@dwoldo thank you for a comprehensive bug report, much appreciated. We'll take a look

**Comment by bwateratmsft** [comment]
@karolz-ms We could mount to both locations (`/root/.nuget/packages` and `/home/appuser/.nuget/packages`), which I think should whether running as root or the default-scaffolded `appuser`. What do you think?

**Comment by karolz-ms** [comment]
@bwateratmsft we could do that. Alternatively, we could consider adding a setting to the docker-run task that indicates where the user folder is. This will work regardless what the container user name is. Do we scaffold `docker-buld` and `docker-run` tasks as part of "Add Docker files to workspace"?

@dwoldo you should be able to use [dockerRun.volumes setting](https://code.visualstudio.com/docs/containers/reference#_net-core-dockerrun) to map the Nuget and Nuget fallback folders to the correct location in the container, and still run the container as normal user. Could you try and see if that works for you as a workaround?

**Comment by dwoldo** [comment]
> @dwoldo you should be able to use [dockerRun.volumes setting](https://code.visualstudio.com/docs/containers/reference#_net-core-dockerrun) to map the Nuget and Nuget fallback folders to the correct location in the container, and still run the container as normal user. Could you try and see if that works for you as a workaround?

It does work as you described. I failed to highlight as a work around on my initial message.

**Comment by bwateratmsft** [comment]
> @bwateratmsft we could do that. Alternatively, we could consider adding a setting to the docker-run task that indicates where the user folder is. This will work regardless what the container user name is. Do we scaffold `docker-buld` and `docker-run` tasks as part of "Add Docker files to workspace"?

Yes, we do scaffold these. We could add such a user parameter but then again, the end user could also just add the volumes manually (as in the workaround); this would work today without any changes. I don't feel strongly but there's something to be said for not adding new properties when existing ones can work. (If that's the approach we go with, I'd still dual map `/home/appuser` so that not everyone must add this long list of volumes--just those with custom usernames)

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.19.0.
