### ISSUE TITLE
Cannot see docker images after docker uninstall/install

### ISSUE THREAD

**Issue by phalouvas** [microsoft/vscode-docker#3308]
The electricity went down. After starting again my Windows 10, docker could not start. Then I uninstall/installed it again.
After that VS Code cannot view the images of wsl2. I tried all sort of things, like uninstalling/installing docker extension and even VS code it self. From wsl ubuntu terminal the docker commands works fine.

Does this occur consistently? Yes
Repro steps:

1. Force Shut down PC windows 10. e.g. with power button
2. uninstall/install docker

Action: vscode-docker.networks.create
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: invalid character '\x00' looking for beginning of value

Version: 1.17.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.62.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:3941280
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1048:16
Socket.<anonymous> child_process.js:439:11
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by bwateratmsft** [comment]
There was a bug in Docker Desktop on upgrade that filled up the context file with invalid characters, and unfortunately uninstall does not fix it. You'll need to delete everything in `%USERPROFILE%\.docker\contexts`, then it should work: https://github.com/microsoft/vscode-docker/issues/3249#issuecomment-937772119

**Comment by phalouvas** [comment]
thanks, problem solved
