### ISSUE TITLE
Process 'docker context ls --format="{{json .}}"' exited with code 1

### ISSUE THREAD

**Issue by conduongtong** [microsoft/vscode-docker#3316]
![1](https://user-images.githubusercontent.com/43648013/141716278-a2921b28-331f-4230-a49f-dcd902a8ae58.png)
Sr for my bad english.
I got error as title, i've tried reinstall docker, vscode, extension, none of this works.
I've been using docker normally 2-3 months and stuck with this error. Please help me.
Command line and docker still works. only cannot see through vscode.
When i run docker context ls --format="{{json .}} in cmd and got this:
Error: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: invalid character '\x00' looking for beginning of value

**Comment by bwateratmsft** [comment]
Same as #3249. Docker had a bug that corrupted the contexts file, try deleting `%USERPROFILE%\.docker\contexts` (Windows) or `~/.docker/contexts` (Mac and Linux), as in https://github.com/microsoft/vscode-docker/issues/3249#issuecomment-937772119.
