### ISSUE TITLE
Allow use of environment/debug variables in `dockerServerReadyAction`

### ISSUE THREAD

**Issue by eladavron** [microsoft/vscode-docker#3320]
Hi
I have the following use case:
I have a web server started inside a docker container which can not be accessed with `localhost` or an IP address, but instead - due to the way our SSO system works, must be accessed using the host's name FQDN: (e.g. `https://my-computer.contoso.com`).

While it's possible to just hard-code my host's url into `launch.json`, I want it to be versatile enough so that when other developers use it it'll automatically launch the correct url.
I was hoping this syntax would work:
```json
"dockerServerReadyAction": {
    "uriFormat": "https://${HOSTNAME}.contoso.com",
}
```
But instead it just launches `https://%24%7Bhostname%7D.contoso.com/`.

So I thought I'd get clever with the replacement - add the hostname as an environment variable to the docker container (which CAN be done dynamically), and print it when the server starts.

So the debug would print something like this:
```
Debug URL: https://my-computer.contoso.com
````
and then I'd use something like this:

```json
"dockerServerReadyAction": {
    "uriFormat": "%s",
    "pattern": "Debug URL: (.+)"
}
```
But then it complains that I don't have a capture group for port number.
I tried that too, and it just ignored the whole string.

Please allow using simpler URI Formats - using environment variables, or even simpler replacements would be great.
If that's already possible, or if you have a better idea how to achieve my use case, I'd appreciate feedback.
Thanks!

**Comment by bwateratmsft** [comment]
Might be automatically fixed if #2289 is implemented.

**Comment by bwateratmsft** [comment]
Good news, you can actually do this now! In your scenario, just use `${env:HOSTNAME}` instead of `${HOSTNAME}`. Our variable substitution logic works on most things in https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables.

**Comment by eladavron** [comment]
Worked great, thank you!
