### ISSUE TITLE
Can't sign in to Docker Enterprise Trusted Registry 2.7.8

### ISSUE THREAD

**Issue by CharlesNadolskiNtrs** [microsoft/vscode-docker#3325]
### Steps to reproduce

Open the command palette using `F1` or `CTRL+SHIFT+P`, and select "Docker Registries: Connect Registry".
Next, select "Generic Docker Registry" as a provider.
Enter our internal Docker Enterprise Trusted Registry as the URL, and enter our corporate credentials.
Click on the Docker whale icon and expand Registries.
Our internal Docker Enterprise Trusted Registry URL shows up.
Expand our URL, you'll see the error "Error: Request with GET/HEAD method cannot have body".

### VS Code Environment

From Help -> About:

Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

### Docker Extension Information

Name: Docker
Id: ms-azuretools.vscode-docker
Description: Makes it easy to create, manage, and debug containerized applications.
Version: 1.18.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker

### Docker Enterprise Trusted Registry Environment

Version: 2.7.8
URL format: https://docker-dtr-{env}.{domain}.com/
CLI Compatability: The Registry CLI requires a Docker client using Engine - Enterprise 19.03 or higher.
API: swagger doc at `/api/v0/docs.json` starts with:
```json
{
 "swagger": "2.0",
 "info": {
  "title": "Docker Trusted Registry",
  "version": "2.7.8"
 },
}
```

### Other tools

Docker for Windows not yet installed, just using remote registries for now.

**Comment by bwateratmsft** [comment]
This is a known limitation at this time, tracked on #869. I'll add this issue to that list.
