### ISSUE TITLE
Fail to list containers after switching context

### ISSUE THREAD

**Issue by jacekplocharczyk** [microsoft/vscode-docker#3330]
Hey,

I'm trying to connect to docker running on my PC in the local network from Mac.
I'm able to change context (using vscode extension) and print all running containers running `docker ps` in CLI but they aren't showing up in the vscode extension containers section:
![image](https://user-images.githubusercontent.com/41325597/142760000-3531318b-95cf-4960-8d4a-a8790b2f21df.png)

Docker extension: `v1.18.0`
VS Code: 
```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (4 days ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

Am I doing something wrong?

**Comment by karolz-ms** [comment]
How exactly is the Docker context defined? Does it involve SSH?

**Comment by jacekplocharczyk** [comment]
Yes, it's over ssh.

I have Ubuntu 18.10 on PC with docker daemon running.

I'm authenticating using private key which path is defined in `~/.ssh/config`. Password login is forbidden.

I've created context using: `docker context create home-desktop --docker "host=ssh://[user]@[host]"`

So I'm able to login to PC using just `ssh user@host` with host defined in `config`.

Also, I found workaround by first attaching to SSH target (PC) and there installing docker add-on and attaching to the running container but it doesn't use docker context.

**Comment by karolz-ms** [comment]
Makes sense, thanks for the clarification.

Remoting to the machine with Docker daemon running is generally recommended if remote Docker daemon needs to be used: https://code.visualstudio.com/docs/containers/choosing-dev-environment#_remote-machine
May I ask why you choose this setup? I.e. why use remote Docker daemon, as opposed to installing Docker Desktop on your Mac?

The extension can be made to work with remote Docker daemon directly, but there are limitations: https://code.visualstudio.com/docs/containers/ssh

Let us know please if this helps

**Comment by jacekplocharczyk** [comment]
I'm playing with deep learning and on PC I have GPU so I'm able to use CUDA from container.

Interesting thing is that I was able to connect to the container running on GCP VM with GPU using docker context (but it didn't work flawless - some vs window reload was necessary)

Thanks for help - knowing that attaching to ssh target and connecting to local docker is a way to go is the solution to me :smile:
