### ISSUE TITLE
Error: proces "docker context ls --format="{{json.}} exited with code 1

### ISSUE THREAD

**Issue by draiyz** [microsoft/vscode-docker#3331]
what does this mean?

**Comment by bwateratmsft** [comment]
I'd guess this is probably #3249. Try deleting the `~/.docker` folder as in https://github.com/microsoft/vscode-docker/issues/3249#issuecomment-937772119.

**Comment by draiyz** [comment]
> I'd guess this is probably #3249. Try deleting the `~/.docker` folder as in [#3249 (comment)](https://github.com/microsoft/vscode-docker/issues/3249#issuecomment-937772119).

hey thanks for the reply. the context file was corrupted. I had to delete it content and set the context to default.
it works perfectly now
