### ISSUE TITLE
Docker Registry: Lets Encrypt certificate has expired

### ISSUE THREAD

**Issue by martinrotzinger** [microsoft/vscode-docker#3332]
Does this occur consistently? Yes.
Repro steps:

1. Run Visual Studio Code 1.62.3 or Visual Studio Code Insiders 1.63-0-insider
2. Use Docker extension   1.18.0 
3. connect to a docker registry using https and domain using lets encrypt certificate

Action: AzureTreeDataProvider.getChildren
Error type: CERT_HAS_EXPIRED
Error Message: request to redacted:url failed, reason: certificate has expired

Version: 1.18.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code - Insiders
Product Version: 1.63.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:5413178
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:469:9
TLSSocket.emit events.js:315:20
emitErrorNT destroy.js:106:8
emitErrorCloseNT destroy.js:74:3
processTicksAndRejections task_queues.js:80:21
```

</details>

**Comment by bwateratmsft** [comment]
This is an external issue: https://github.com/microsoft/vscode/issues/136787. There is a workaround suggested in [this comment](https://github.com/microsoft/vscode/issues/136787#issuecomment-969065291) that may help.
