### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by arinzejustin** [microsoft/vscode-docker#3334]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.18.0`
- OS Version: `Windows_NT x64 10.0.10240`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\<name>\AppData\Local\Temp\ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@arinzejustin can you add the cpuprofile file?

**Comment by bwateratmsft** [comment]
Ok. So it's unlikely but still possible that VSCode is tracking the CPU usage of those child processes and associating it back to the extension that spawned it.

Also I see this in the process explorer, so it's _definitely_ a separate process:
![image](https://user-images.githubusercontent.com/36966225/145590896-352519d5-bba7-460c-9f92-ecbbd75e451c.png)
