### ISSUE TITLE
In building/pushing an image, make it easier to choose a registry

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#334]
Triage decided feature:
- [x] After first push, when registry is specified, ask to save setting (workspace or global)
- [x] Fuse `defaultRegistry` and `defaultRegistryPath` settings into one setting. Note: If a user already has both set, we should either warn the user about it, or change the setting ourselves. 
- [x] Select the prefix in the edit box so that user can easily type over it
- [x] Add menu item to set registry as default
- [x] If they try to push an image with no prefix (username/whatever), we ask if they wanted to provide a prefix - need to figure out wording/etc
- [x] While building an image, we use a flag that lets us know whether or not to prefix registry.
- [x] Discover-ability of the above flag: If the flag is not set, we haven't asked before, and a default registry is set .
- [x] Add prefix for Tag, and for Build if flag set.  Don't apply to push (push might send user to Tag)

**Comment by StephenWeatherford** [comment]
See https://github.com/Microsoft/vscode-docker/issues/253

**Comment by StephenWeatherford** [comment]
1) After first push, ask to save setting (workspace or global)
2) Add menu item to set registry as default 
3) If they try to push an image with no prefix (username/whatever), we ask if they wanted to provide a prefix - need to figure out wording/etc

**Comment by PrashanthCorp** [comment]
> - [ ] After first push, ask to save setting (workspace or global)

By first, do we mean: 
a) first ever push in the extension
b) first push of an image (discern this by ID perhaps?)

@fiveisprime

**Comment by fiveisprime** [comment]
Originally, I was thinking first push to each endpoint, though now I'm thinking first ever push. Just something to indicate that the functionality exists.

**Comment by PrashanthCorp** [comment]
Closing via above PR's
