### ISSUE TITLE
The task is not the name of the running container when executing "View Logs" for a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3340]
**OS:** All
**Build Version:** 20211130.10
**Regression:** Not a Regression

**Repro Steps:**

1. Right click a running container -> Select "Attach Shell" -> Check the task.
2. Right click the same one -> Select "View Logs".
3. Check whether the task is the name of the running container.

**Expect:**
The task is the name of the running containerL.

**Actual:**
The task is the name of the image.
![image](https://user-images.githubusercontent.com/62053665/144185680-4ab6c8a4-14ed-4cb1-9e5f-439aba0e2a35.png)

**Comment by bwateratmsft** [comment]
Good idea. This is a very easy change so I'll just go ahead and get it into 1.19.
