### ISSUE TITLE
An extra command `ipc no event received : <nil>` displays in the TERMINAL window after executing docker login

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3341]
**OS:** Windows
**Build Version:** 20211130.10

**Repro Steps:**

1. Navigate to TERMINAL window -> Type `docker login <registry-name>.azurecr.io` -> Enter.
2. Check whether only display `Username:` in the TERMINAL window.

**Expect:**
Only display `Username:` in the TERMINAL window.

**Actual:**
An extra command `ipc no event received : <nil>` displays in the TERMINAL window.
![image](https://user-images.githubusercontent.com/57662131/144209815-2d008f92-da1e-4db3-9bee-86eeb7366038.png)

**More Info:**
1. This issue also reproduces when executing compose up.
![image](https://user-images.githubusercontent.com/57662131/144211210-f2b6a010-729c-44ed-ac5d-c4b92c4d3820.png)
2. This issue doesn't reproduce with Docker 4.2.0.
3. This issue doesn't reproduce on Mac.

**Comment by bwateratmsft** [comment]
This comes from the CLI and is out of our control. @karolz-ms also mentioned it would be removed in the final build.
