### ISSUE TITLE
Consider adding debug instructions to readme

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#335]
e.g. https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript

**Comment by StephenWeatherford** [comment]
#268

**Comment by StephenWeatherford** [comment]
https://github.com/Microsoft/vscode-docker/issues/56?

**Comment by bwateratmsft** [comment]
Going to dupe this one over to #1113
