### ISSUE TITLE
Cannot get images from registry | Extension call the wrong endpoint

### ISSUE THREAD

**Issue by PouletteMC** [microsoft/vscode-docker#3356]
Does this occur consistently? Yes or No -->
Repro steps:

1. Create a Docker Registry using the official image
2. Try to connect to it
3. The extension goes to `https://registry.domain.com/v2` instead of `https://registry.domain.com/v2/_catalog` so it can't see the files

Action: AzureTreeDataProvider.getChildren
Error type: CERT_HAS_EXPIRED
Error Message: request to redacted:url failed, reason: certificate has expired

Version: 1.18.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.63.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:5413178
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:469:9
TLSSocket.emit events.js:315:20
emitErrorNT destroy.js:106:8
emitErrorCloseNT destroy.js:74:3
processTicksAndRejections task_queues.js:80:21
```

</details>

**Comment by bwateratmsft** [comment]
This is an external issue: https://github.com/microsoft/vscode/issues/136787. There is a workaround suggested in [this comment](https://github.com/microsoft/vscode/issues/136787#issuecomment-969065291) that may help.
