### ISSUE TITLE
Server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by chrishdx** [microsoft/vscode-docker#3358]
Hi there,
when I am connected to the Docker host via an unencrypted TCP connection I get the containers, networks etc. listed and can also start and stop them. However, as soon as I try to interact with the containers, I get the following error message:

error during connect: Get https://192.168.21.222:2375/v1.24/containers/52f60b035f1b8fcb3d19c42cd7fe002f5e9dd28c78fe626eb3e6a1c5e40d1be5/json: http: server gave HTTP response to HTTPS client
The terminal process "bash '-c', 'docker logs --tail 1000 -f 52f60b035f1b8fcb3d19c42cd7fe002f5e9dd28c78fe626eb3e6a1c5e40d1be5'" failed to launch (exit code: 1).

The Version from  ms-azuretools.vscode-docker is 1.18.0

**Comment by bwateratmsft** [comment]
What value do you have for environment variable `DOCKER_HOST` or VSCode setting `docker.host`? Or are you using contexts? It seems like Dockerode is content but the CLI might be having issues with the connection.
