### ISSUE TITLE
first install docker

### ISSUE THREAD

**Issue by soulake2012** [microsoft/vscode-docker#3361]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.installDocker
Error type: 3
Error Message: Process '"C:\Users\User01\AppData\Local\Temp\docker_1640338...' exited with code 3
Error: 

Version: 1.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:477087
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@soulake2012 are you able to install Docker manually? There are a wide variety of reasons why install might fail automatically.
