### ISSUE TITLE
`python:slim` image not working for FastAPI

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3363]
We recently [changed](https://github.com/microsoft/vscode-docker/pull/3294) to using just `python:slim` for the base image, which equates (currently) to `python:3.10-slim-bullseye`. Previously, we used `python:3.8-slim-buster`. However, I noticed that my FastAPI app failed to build; it appears `gcc` is needed as part of the pip install, and is missing on 3.9+ Python images.

**Comment by bwateratmsft** [comment]
Correction...`gcc` isn't present in 3.8 images either, but apparently isn't needed during pip install on 3.8.

**Comment by bwateratmsft** [comment]
I don't know enough about how Python packages work to solve this in a better way than just switching to `python:3.8-slim`. Python 3.8 will be supported for almost three more years so...let's just do that.

**Comment by karolz-ms** [comment]
Is Python 3.9 an option?

**Comment by bwateratmsft** [comment]
I tried 3.9, 3.10, and 3.11; all had the same or variations of the same issue.
