### ISSUE TITLE
Simple Python script remote debugging in Docker container leads to 'Invalid message: "debugLauncherPath" must be str'

### ISSUE THREAD

**Issue by tcladet** [microsoft/vscode-docker#3365]
I am trying to trigger a remote debugging session (on local VM) in a Python container on a really simple Hello World example:

### Configuration

- Host OS: **Windows 10**
- Guest OS: **CentOS 7.9** (local Vagrant box)
- VS Code: **1.63.2**

_Extensions_
- Remote - SSH: **0.70.0**
- Docker: **1.18.0**
- Python: **2021.12.1559732655**

### Scenario

I am following the official documentation here: [https://code.visualstudio.com/docs/containers/quickstart-python](https://code.visualstudio.com/docs/containers/quickstart-python). So I ran `Add: Docker files...` VS Code command and followed the prompt...

My python script (`hello.py`)

```python
print('Hello World!')
```

The `Dockerfile` generated:

```Dockerfile
# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY . /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python", "hello.py"]
```

The `tasks.json` generated:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "docker-build",
            "label": "docker-build",
            "platform": "python",
            "dockerBuild": {
                "tag": "backend:latest",
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build"
            ],
            "python": {
                "file": "hello.py"
            }
        }
    ]
}
```

The `launch.json` generated:

```json
{
    "configurations": [
        {
            "name": "Docker: Python - General",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}",
                        "remoteRoot": "/app"
                    }
                ],
                "projectType": "general",
            },
        }
    ]
}
```

Everything is working well when I try to launch the debugging session: the image is built correctly (I am able to run it manually) but when the container is launched through `docker-run: debug` task, it leads to the following popup with: `Invalid message: "debugLauncherPath" must be str`.

![image](https://user-images.githubusercontent.com/6628041/148156207-590ab3be-5548-4aad-a6af-48fef1ebb6ad.png)

Command line (my image is called `backend`):

```
> Executing task: docker-run: debug <

> docker run -dt -P --name "backend-dev" --label "com.microsoft.created-by=visual-studio-code" -v "/home/vagrant/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy:/debugpy:ro" --entrypoint "python3" "backend:latest" <
```

The entrypoint seems quite small and only contains the call to Python 3. The container launched is blocked in an "interactive mode" as the container logs shows the Python 3 prompt and wait for commands.

I saw the issue #2455 and at a moment this message is mentionned:
- I tried the different `Path`s options but it doesn't work (or maybe I didn't use them in the right way).
- I ensured that my files are in `LF` mode.

Any thoughts ?

**Comment by bwateratmsft** [comment]
Could be related to the remote setup, I'll have to give it a try to be sure. Last I tried, Python debugging was working in Codespaces setups which isn't too different from remote SSH.

That entrypoint of just `python3` is intentional for debugging; rather than launching the app, we launch the container with a do-nothing task to keep it alive. Then, we hand off control to the Python extension; it will launch the debugger, which will in turn launch the app within the container. This makes it possible to debug startup code, whereas attaching after the container launched would miss that.

@tcladet does a "Python Debug Console" appear in the Terminal window? e.g.
![image](https://user-images.githubusercontent.com/36966225/148271298-d23bf44e-b669-47af-b78d-66dd070f12d4.png)

**Comment by tcladet** [comment]
No Python Debug Console instance appears...

![image](https://user-images.githubusercontent.com/6628041/148274489-93b0b570-1d28-40e9-900d-4be13242e494.png)

But there is a plot twist. It works just now !? I literally took these three screenshots (the one above and the two below) in the space of a minute !? With just a `F5` trigger that separate these two events !?

![image](https://user-images.githubusercontent.com/6628041/148274868-4bf8fb81-ae5c-4b76-a7ea-e2d40750cdaf.png)

![image](https://user-images.githubusercontent.com/6628041/148274948-5d69ac8b-a5dc-4fda-a965-19b65af553d9.png)

I am quite confused to be honest... I didn't change anything expect the fact that I was writing this message...
Is there any kind of different starts depending on the file opened or the active panel while triggering the Debug session ?

Anyway, everything seems OK.

**Comment by bwateratmsft** [comment]
Huh, that's strange. Oh well, it works now! Please let us know if the issue returns.
