### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by TheVPN** [microsoft/vscode-docker#3369]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
ChildProcess.EventEmitter.emit domain.js:475:20
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@TheVPN can you add repro steps? Do you have Docker installed?
