### ISSUE TITLE
React app not running on a docker container

### ISSUE THREAD

**Issue by igboBoydev** [microsoft/vscode-docker#3370]
Does this occur consistently? 
Repro steps:

1. Yes 
2. I created a docker container for my react-app but when I trying accessing it from that port on the browser it's not working.

Version: 1.18.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

**Comment by bwateratmsft** [comment]
@igboBoydev can you add more information about your scenario? There are a wide variety of reasons why the app may be inaccessible.

**Comment by karolz-ms** [comment]
@igboBoydev e.g. could you share your Dockerfile? When you run the container, did you publish any ports? etc.
