### ISSUE TITLE
I have mingled menus with version control panel 

### ISSUE THREAD

**Issue by shrewdact** [microsoft/vscode-docker#3374]
<img width="314" alt="Screen Shot 2022-01-11 at 10 42 56" src="https://user-images.githubusercontent.com/6049800/148866900-d78fc4c5-0a71-45d1-bcc0-45c34bd4a7ab.png">

**Comment by bwateratmsft** [comment]
@shrewdact you should be able to fix this issue by running the command "View: Reset View Locations" from the command palette (<kbd>F1</kbd> or <kbd>Ctrl/Cmd</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>). Let us know if that does not work.
