### ISSUE TITLE
Multi-line LABEL directives highlight as errors

### ISSUE THREAD

**Issue by adambkaplan** [Microsoft/vscode-docker#338]
Extension Version: 0.1.0
VSCode Version: 1.25.1 (1.25.1)
OS: MacOS 10.13.6 (17G65) "High Sierra"

If a LABEL directive includes multiple key/value names listed on multiple lines, the Dockerfile linter reports "Syntax error - can't find = in \"      \". Must be of the form: name=value".

**Dockerfile**
```
FROM my-image
USER 1001
LABEL "io.k8s.display-name"="my-image-app" \
      "io.openshift.s2i.build.image"="my-image" \
      "io.openshift.s2i.build.source-location"="test/test-app"
...
```

**Reported Error**
```
{
	"resource": "/path/to/my/Dockerfile",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "33",
	"severity": 8,
	"message": "Syntax error - can't find = in \"      \". Must be of the form: name=value",
	"source": "dockerfile-utils",
	"startLineNumber": 10,
	"startColumn": 49,
	"endLineNumber": 11,
	"endColumn": 7
}
```

**Comment by rcjsuen** [comment]
Hi, @adambkaplan. Thank you very much for your bug report and I apologize for the long delay in responding.

I have confirmed what you have found and it is indeed a bug in the Dockerfile validation code. I have opened rcjsuen/dockerfile-utils#50 to track this. Please do not hesitate to let me know if you find other false positives being flagged.

**Comment by StephenWeatherford** [comment]
Related to #150?

**Comment by rcjsuen** [comment]
@StephenWeatherford No, they’re not the same issue.

I’ve fixed this particular issue and will try to spin a new release before the new release of this extension.

**Comment by StephenWeatherford** [comment]
Great, thanks!

**Comment by StephenWeatherford** [comment]
@adambkaplan I'm going to go ahead and close for now, it should be fixed.   Feel free to re-open if not.  Thanks.
