### ISSUE TITLE
Browser freezes when connecting with Python App

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#3383]
From Chris Harris: 

In the build, run, and debug the container: https://code.visualstudio.com/docs/containers/quickstart-python#_build-run-and-debug-the-container.

- When my browser opened, it was stuck on trying to connect to localhost/[random port] for 5+ minutes until I hit refresh.
- I wasn’t sure what was going on with my app/container, and I was confused that the browser opened on [random port] instead of port 8000 as the tutorial had mentioned previously. I had just enough docker knowledge to understand that application ports in the container were mapped to random, high-level ports on the machine, but everything looked good in both VS Code and Docker Desktop so I was really confused as to why the app wouldn’t open.
- I believe what happened is the browser window opened just a bit ahead of the container spinning up and starting the Django app, and so there was nothing responding on the port when the browser opened.

**Comment by bwateratmsft** [comment]
Same as #2191. We have never been able to get a repro reliable enough to debug what's going on.

**Comment by bwateratmsft** [comment]
Consider a doc update describing why a seemingly-random port is opened.

**Comment by ucheNkadiCode** [comment]
Hey @luabud, we have an inclination that this issue is happening after we hand off to the application to the python debugger. Have you heard feedback about this?

**Comment by luabud** [comment]
Not that I know of! @karthiknadig -- do you have an idea of what could be happening?

**Comment by ucheNkadiCode** [comment]
Adding @charris-msft for any additional feedback

**Comment by karthiknadig** [comment]
If we can get a consistent repro we can dig into this. /cc @int19h

**Comment by bwateratmsft** [comment]
I'll close this for now, it seems unlikely we'll be able to obtain a consistent repro. I've personally only seen this issue once or twice ever.
