### ISSUE TITLE
"Failed to connect. Is Docker installed?" on Mac

### ISSUE THREAD

**Issue by AOEChamp** [microsoft/vscode-docker#3384]
macOS 11.3.1
docker 20.10.12, build e91ed5707e
vscode 1.63.2
docker extension v1.18.0

After newly installing the extension, when opening the docker panel I get "Failed to connect. Is Docker installed?" as an error. Docker is already installed and clicking the "Install docker" button at the bottom of the panel correctly detects that docker is installed. The default shell for vscode is set to bash and "docker -v" shows the correct version.

**Comment by bwateratmsft** [comment]
If I had to guess I'd say it's the `PATH` issue again... #2578

Does the issue persist after restarting VSCode and/or restarting the whole machine?

**Comment by AOEChamp** [comment]
Yes, issue persists after restarts. Btw I'm not using Docker Desktop due to licensing. Using minikube instead as described here: https://dhwaneetbhatt.com/blog/run-docker-without-docker-desktop-on-macos . Not sure if that matters

**Comment by AOEChamp** [comment]
Solved: I had to add `eval $(minikube -p minikube docker-env)` to my `.bashrc` and restart vscode for it to pick up the correct host settings for docker daemon.
