### ISSUE TITLE
Docker on WSL2 Ubuntu fails to connect to the Internet

### ISSUE THREAD

**Issue by Zaffer** [microsoft/vscode-docker#3385]
At completely random moments, docker fails to connect to the internet when building the image.
I will build an image, all good. Then build the image again or after doing some development and will never work again.
Only solution I have is to completely uninstall and reinstall Linux, and start a new dev environment from scratch taking hours everytime.
This is started happening last month and now happens about once a week.
I have tried every suggestion on the internet to fix it and nothing helps.
A colleague of mine started having the same issue and now also has to reinstall his whole system everytime.

Please help!

Does this occur consistently? No
Repro steps:

1. $ docker compose up --build
2. ---> WARNING: ... Failed to establish a new connection

Version: 1.18.0
OS: linux
OS Release: 5.10.16.3-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

**Comment by bwateratmsft** [comment]
This sounds like it would be an issue in either Docker or WSL, but definitely not the Docker extension for VSCode.

Does the connectivity issues affect everything in the WSL instance, or just Docker in particular? If it's just Docker I'd start by filing an issue in one of their repos.
