### ISSUE TITLE
The log changes in the terminal when more than 2 tasks are opened and command window narrows

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3386]
**OS:** All
**Build Version:** 20220112.2
**Regression:** Not a regression

**Repro Steps:**

1. Open a project and add Docker files for this project in VS Code.
2. Right click docker-compose.debug.yml -> Compose Up.
3. Right click the container group in containers view -> Compose Stop -> Check the log in the terminal.
4. Make sure there are more than 2 tasks open and the command window narrows, like below:
    ![image](https://user-images.githubusercontent.com/62053665/149464137-9792ac9e-6708-4bc7-b047-6af97c548d50.png)
5. Right click the container group in containers view again -> Compose Stop.
6. Check whether the log is consistent with the log in the step 3.

**Expect:**
The log is consistent with the log in the step 3.

**Actual:**
The log is inconsistent with the log in the step 3.
1. The log in the step 3:
    ![image](https://user-images.githubusercontent.com/62053665/149464672-4a0bd0f2-5b70-4215-b7a4-d1ae507755a9.png)
2. The log in the step 5:
    ![image](https://user-images.githubusercontent.com/62053665/149464715-35d3e1d3-ee74-426e-b503-d8eb13a2ef3e.png)

**Comment by bwateratmsft** [comment]
This is between the Docker CLI and VSCode's terminal handling, so it is out of our control.
