### ISSUE TITLE
[GitHub Codespaces] Pop up an error after deleting more than two images at the same time

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3388]
**OS:** GitHub Codespaces (Remote&Local)
**Build Version:** 20220112.2
**Regression:** Not a regression

**Repro Steps:**
1. Run `docker run hello-world` in Terminal.
2. Expand the "hello-world" node in the IMAGES view -> Right click the "latest" -> Tag... -> Type a name as "hello-world:latest02"  -> Enter.
3. F1 -> Docker Images: Remove... -> Click "hello-world" -> Select all images -> OK.
4. Check whether doesn't pop up any error.

**Expect:**
Don't pop up any error.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/57662131/149731149-6d1b4c2d-dfac-4dd1-bdb8-6b359d0a5112.png)

**More Info:**
1. This issue doesn't reproduce after deleting one image.
2. This issue doesn't reproduce on Windows, Mac and Linux OSs.

**Comment by bwateratmsft** [comment]
It would have to be an external issue so I'll close it, but I'm still curious. @Chuxel, we do removal by referencing the image name; on other platforms this causes the removal of the tag only, if there are multiple tags for the same image. The image is only removed alongside the last tag to be removed. Is this different in Codespaces for whatever reason?
