### ISSUE TITLE
Pop up an extra dialog when F5ing a Go project with a `Dockerfile` file opened in the editor

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3389]
**OS:** All
**Build Version:** 20220112.2
**Regression:** Not a regression

**Repro Steps:**
1. Create a new folder and open it in VS Code, e.g. 'dockergo'. 
2. Execute the following command:
    ```
    go mod init microsoft.com/dockergo
    ```
3. Add main.go file in the same directory, with the following content:
    ```
    package main
    
    import (
	    "fmt"
	    "net/http"
    )
    
    func main() {
	    http.HandleFunc("/", serveRoot)
    
	    err := http.ListenAndServe(":3000", http.DefaultServeMux)
	    if err != nil {
		    fmt.Println(err.Error())
	    }
    }
    
    func serveRoot(w http.ResponseWriter, r *http.Request) {
	    fmt.Fprintln(w, "Hello, world!")
    }
    ```
4. F1 -> Docker: Add Docker Files to Workspace -> Go -> Port 3000 -> Yes.
5. The `Dockerfile` file opened in the editor -> F5.
6. Check whether to start debugging directly.

**Expect:**
Start debugging directly.

**Actual:**
Pop up an extra dialog.
![image](https://user-images.githubusercontent.com/62053665/149769278-38086e65-36ad-4d4b-97de-77b1b5a57e20.png)
![go](https://user-images.githubusercontent.com/62053665/149769711-ae519ee5-9ad5-45db-b3ab-d7125020f740.gif)

**More Info:**
This issue doesn't reproduce for other projects.

**Comment by bwateratmsft** [comment]
Go + Docker debugging is not supported at this time so this is by-design. VSCode has generic handling for when <kbd>F5</kbd> is pressed on any file; debuggers can be registered by extensions to provide dynamic debug configurations for given languages.
