### ISSUE TITLE
Docker SVG icon has extra pixel

### ISSUE THREAD

**Issue by MattHardcastle** [Microsoft/vscode-docker#339]
The Docker Whale icon in the Visual Studio Code sidebar has what I believe is an errant dot.

![docker-icon](https://user-images.githubusercontent.com/10106755/43362825-a935c086-92a8-11e8-82d5-b0f7861b83bc.png)

**Comment by chrisdias** [comment]
This is from the official docker images which can be downloaded from https://www.docker.com/brand-guidelines. They have this mark, my guess is that it is a very small copyright symbol.

**Comment by MattHardcastle** [comment]
@chrisdias Would you be open to a pull request removing the dot? It looks like a stuck pixel on my display and is a bit distracting.

**Comment by chrisdias** [comment]
We're following their guidelines so I don't think we can. 

![image](https://user-images.githubusercontent.com/1487073/43429301-8a6e986a-9417-11e8-98f5-8fa7b81f5ffc.png)
