### ISSUE TITLE
can I see container's internal ip address in quick info?

### ISSUE THREAD

**Issue by yilmazdurmaz** [microsoft/vscode-docker#3390]
This issue is a feature request, if possible.

It is a nice feature we can see a quick info of a container when we mouse over them. However, I want to see the internal IP of the container in it if it is running to use that info in other containers.

I can do a multi-step `docker exec container-name ifconfig` execution for the purpose but would be quicker if it is in this quick info.

thanks

**Comment by bwateratmsft** [comment]
Related to #2677

**Comment by bwateratmsft** [comment]
We'll dupe this one to #2677. Our thinking is that not everyone would want to see the IP address so it probably shouldn't be default, but if the tooltips were customizable (which is what #2677 is about), then this scenario could be covered.

**Comment by bwateratmsft** [comment]
It's worth adding, you can also view the container IP address by right clicking the container and doing Inspect. The IP address is in `NetworkSettings` -> `IPAddress`.
