### ISSUE TITLE
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node'

### ISSUE THREAD

**Issue by left-code** [microsoft/vscode-docker#3392]
Higher version than **v1.17.0** it's not possible to debug/compile on Windows OS

Error:

`
WARNING in ./node_modules/ssh2/lib/protocol/crypto.js 30:12-60
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node' in 'C:\Code\GitHub\vscode-docker\node_modules\ssh2\lib\protocol'
 @ ./node_modules/ssh2/lib/server.js 27:29-60
 @ ./node_modules/ssh2/lib/index.js 33:10-32
 @ ./node_modules/docker-modem/lib/ssh.js 1:13-35
 @ ./node_modules/docker-modem/lib/modem.js 6:8-24
 @ ./node_modules/dockerode/lib/docker.js 2:10-33
 @ ./src/docker/DockerodeApiClient/DockerodeUtils.ts 17:18-38
 @ ./src/docker/DockerodeApiClient/DockerodeApiClient.ts 28:25-52
 @ ./src/docker/ContextManager.ts 119:73-123
 @ ./src/extension.ts 27:25-59
`

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.65.0 compiled with 1 warning in 28095 ms

Task `webpack --watch` never complete successfully and **Extension Development Host** never get opened. 

Windows version: Windows 11 Enterprise, 21H2
Node version: v16.13.1
npm version: 8.1.2

**Comment by bwateratmsft** [comment]
The fix is in the main branch now so I'm marking it as "fix released", since it's a debugging scenario and doesn't need an actual product release.
