### ISSUE TITLE
Improve the text in the containers window for the Docker tutorial link

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3396]
Currently looks like this:
![image](https://user-images.githubusercontent.com/36966225/150371306-7a763917-042b-47b7-863c-c607a83723c8.png)

**Comment by bwateratmsft** [comment]
To me, the most obvious criticism is that it's not obvious to me that it's a link. We do not have control of the color or presentation (i.e. underline), unfortunately, which IMO leaves icon and text to be our only choice.

Here's an example with the standard hyperlink icon, and `...` removed:
![image](https://user-images.githubusercontent.com/36966225/150373769-fe53d406-a9e1-4917-9d8e-cd20b2a18546.png)

**Comment by j-martens** [comment]
Suggestion: 
Instead of 
"Get started with Docker containers"
"Tutorial: Get started with Docker"

**Comment by ghogen** [comment]
Yes, with the "..." it would be expected to open up a dialog box, since that is a common UI convention.  Having "Tutorial" in the text and having the icon for an external hyperlink would be helpful.

**Comment by bwateratmsft** [comment]
Here's how @j-martens and @ghogen's suggestions look:
![image](https://user-images.githubusercontent.com/36966225/150540705-21cbd243-df19-443a-b115-fb76036c7a4b.png)

**Comment by j-martens** [comment]
@bwateratmsft - did this go live yet? Thanks!

**Comment by j-martens** [comment]
@bwateratmsft - is it live? I'm looking forward to seeing the impact. thanks.
