### ISSUE TITLE
Improve Add Dockerfiles to Django projects

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#3410]
Scenario:

User selects add dockerfiles to workspace
Select Application Platform -> no change
Python: Django -> no change
Choose the app's entry point (e.g. manage.py, app.py) 

My suggestion is to add a dialog so the user can (optionally) select where their wsgi.py file is in their application. We should try to look for wsgi file in the root folder as well as the [workspace name]\[workspace_folder of same name]\wsgi.py > ...(e.g. wsgi.py, asgi.py) and pop those to the top, but then also allow them to type it in 

Port: 8000 -> no change

If they choose manage.py, need to attempt to locate the wsgi.py, but if they choose wsgi.py or asgi.py then use the path exactly

**Comment by bwateratmsft** [comment]
We still need them to pick `manage.py`. That can't change, it is necessary for debugging to work properly. I'll alter the logic so that if the WSGI/ASGI module cannot be found automatically, we'll prompt.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.20.0.
