### ISSUE TITLE
The image name changes to "mvc1" after building image for a .NET Core MVC project with name "mvc-1"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3416]
**OS:** Win10/Mac
**Build Version:** 20220208.5
**Regression:** Not a regression

**Repro Steps:**

1. Open a .NET Core MVC project with name "mvc-1" -> Add Docker files for this project in VS Code.
2. Right click the Dockerfile file -> Build image.
3. Check whether the image name is "mvc-1" under the "IMAGES" node.

**Expect:**
The image name is "mvc-1" under the "IMAGES" node.

**Actual:**
The image name is "mvc1" under the "IMAGES" node.
![image](https://user-images.githubusercontent.com/62053665/153172670-fc699209-4a8a-4e70-8f09-443f2ab34a5b.png)
![image](https://user-images.githubusercontent.com/62053665/153174818-257aca3e-e118-43e5-8de9-642c53a31fe2.png)
Details of TERMINAL:
[build image.txt](https://github.com/microsoft/vscode-docker/files/8031558/build.image.txt)

**More Info:**
This issue also reproduces for the **django_project/flask_project** project, the image name changes to **djangoproject/flaskproject** under the "IMAGES" node when building image for the Dockerfile file.

**Comment by bwateratmsft** [comment]
This is by-design. We keep only letters and numbers for the image name to maximize the chance of it being valid.

**Comment by v-mengwe** [comment]
As above, we keep only letters and numbers for the image name to maximize the chance of it being valid. Is the hyphen in the image **hello-world** by design?

**Comment by v-mengwe** [comment]
Got it, thanks for your guidance!
