### ISSUE TITLE
Logs. Bug/Feature request. Shell is killed when a container restarts

### ISSUE THREAD

**Issue by o-alexandrov** [microsoft/vscode-docker#3420]
## How it currently works

When attaching to listen to container's logs, VS Code opens a shell in a built-in terminal.
If a container is restarted, the shell won't get any new logs. A user would have to start to listen to container's logs again.

## How it should work

It should work as in [Docker Desktop](https://www.docker.com/products/docker-desktop).
In Docker Desktop, if you start to listen to container's logs and restart the container, the existing shell continues to receive new logs.

**Comment by bwateratmsft** [comment]
It may be worth putting in a feature request to the Docker CLI repo to support an additional flag with the Docker Logs command, that would instruct it to keep the logs stream open when the container is stopped.

**Comment by o-alexandrov** [comment]
Okay, thank you for taking a look.
Created an issue in `docker/cli` as you proposed.
- https://github.com/docker/cli/issues/3426
