### ISSUE TITLE
Pop up a dialog contained two same ports when opening a .NET running container in browser

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3431]
**OS:** Ubuntu 18.04
**Build Version:** 20220214.1
**Regression:** Previous Release

**Repro Steps:**

1. Open the .NET Core project and add Docker files for this project in VS Code.
2. F5 with "Docker .NET Core Launch" configuration.
3. Right click the running container in the CONTAINERS view -> Open in Browser.
4. Check whether opens a web page directly.

**Expect:**
Open a web page directly.

**Actual:**
Pop up a dialog contained two same ports.
![image](https://user-images.githubusercontent.com/57662131/154413327-bb63ea63-8698-4623-b024-b27536a36f4a.png)

**More Info:**
1. No responding after selecting the second port on Ubuntu. 
2. This issue also reproduce on Codespaces. 
3. This issue doesn't reproduce on Windows and Mac(M1).

**Comment by bwateratmsft** [comment]
We should condense the port list in a `Set` to remove duplicates.

**Comment by v-xinda** [comment]
@bwateratmsft the result of executing "Inspect" command in the [result.txt](https://github.com/microsoft/vscode-docker/files/8094534/result.txt) file.

**Comment by bwateratmsft** [comment]
Thanks! I figured out what's happening here. The container has its internal port published both to "0.0.0.0" (IPv4) and "::" (IPv6) on the host machine. The public port is the same. We should dedupe these down into one; later on we will open to "localhost" if the public IP is either "0.0.0.0" or "::".
