### ISSUE TITLE
How can an extension icon be seen in the activity bar only when an extension is executed in vscode?

### ISSUE THREAD

**Issue by jiminu** [microsoft/vscode-docker#3441]
hello. I'm using this extension well.

I use a docker in vscode, but Sometimes I don't use it.

so, i want extension icon to be hidden when not in use and visible when using it.

cmake works in that way.

Do you have any plans to add these functions?

thanks.

![example](https://user-images.githubusercontent.com/88309919/154834704-71c2d5df-ff4a-4f99-a90e-b328cc02ef37.PNG)

**Comment by jiminu** [comment]
1. I think it is right icon to be seen on the tab when the extension is activated.
2. I use windows10. In order to use docker, the docker desktop must be executed first. I usually executed (docker) run, start, stop, etc. command. sometimes use a dockerfile.

thanks.

**Comment by jiminu** [comment]
> A couple of clarifying questions,
> 
> 1. Do you want the tab to stay visible as long as the extension is activated, or only show when you are on the Docker view?
> 2. What do you normally do to activate the Docker extension--run commands, open a Dockerfile, open the view, etc.?

1. I think it is right icon to be seen on the tab when the extension is activated.
2. I use windows10. In order to use docker, the docker desktop must be executed first. I usually executed (docker) run, start, stop, etc. command. sometimes use a dockerfile.

thanks.

**Comment by bwateratmsft** [comment]
Thanks! It looks like they're using `when` clause contexts. I'd want to implement this as a setting so as not to disrupt folks who expect the tab to always be visible.

**Comment by bwateratmsft** [comment]
It's not perfect, but as a "workaround", you can right click and hide the Docker tab:
![image](https://user-images.githubusercontent.com/36966225/155546482-993da96c-bb9f-4828-9bfd-716a9e89ad75.png)

When you want to access it, run the command "View: Show Docker". You can also set a keybinding for that command for quick access. The downside to this workaround is that the tab will disappear as soon as you navigate away, requiring that command to be run each time.

**Comment by jiminu** [comment]
> Thanks! It looks like they're using `when` clause contexts. I'd want to implement this as a setting so as not to disrupt folks who expect the tab to always be visible.

I hope it will be implemented someday. I'll waiting. Thanks!

**Comment by bwateratmsft** [comment]
Closing as not planned.
