### ISSUE TITLE
dockerCompose task down options is missing profiles

### ISSUE THREAD

**Issue by fpw23** [microsoft/vscode-docker#3443]
Looks like the up options supports profiles but not the down options?

https://github.com/microsoft/vscode-docker/blob/79ed0e8bc526e502c37ed72c59ab6a600f0955c7/src/tasks/DockerComposeTaskProvider.ts#L92

**Comment by bwateratmsft** [comment]
Is the idea to do a partial shutdown?

**Comment by casectrl-fw** [comment]
yes, I was trying to create tasks in tasks.json that could run a single dock-compose file in two different ways, one for backend devs and one for frontend devs.  I ended up just using two different compose files.
