### ISSUE TITLE
DockerExtention

### ISSUE THREAD

**Issue by foleajibola** [microsoft/vscode-docker#3446]
Does this occur consistently? 
Repro steps:

1.500
2.HTTP code 500

Action: vscode-docker.containers.prune
Error type: 500
Error Message: (HTTP code 500) server error - i/o timeout
 

Version: 1.20.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2342237extension.bundle.js:2:2342237
getCause extension.bundle.js:2:2342199
Modem.buildPayload extension.bundle.js:2:2342209
IncomingMessage.<anonymous> extension.bundle.js:2:2341618
IncomingMessage.emit events.js:327:22
IncomingMessage.EventEmitter.emit domain.js:467:12
endReadableNT readable.js:1327:12
processTicksAndRejections task_queues.js:80:21
```

</details>

**Comment by foleajibola** [comment]
The docker extention is not respond.

**Comment by bwateratmsft** [comment]
This error is coming from your Docker daemon, not from the extension. Can you try restarting?
