### ISSUE TITLE
connect registries error

### ISSUE THREAD

**Issue by montery8** [microsoft/vscode-docker#3449]
Does this occur consistently? yes
Repro steps:

1.connect registries to private harbor
2.after authentication ok

Action: AzureTreeDataProvider.getChildren
Error type: TypeError
Error Message: Request with GET/HEAD method cannot have body

Version: 1.20.0
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
new Request extension.bundle.js:2:5384059
extension.bundle.js:2:4131453
extension.bundle.js:2:4131039
R extension.bundle.js:2:4130725
httpRequest extension.bundle.js:2:4131339
BasicOAuthProvider.<anonymous> extension.bundle.js:2:4061134
rejected extension.bundle.js:2:4060324
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by bwateratmsft** [comment]
Duping this to #869. Certain third-party registries aren't supported at this time.
