### ISSUE TITLE
Unable to determine compose project info for container group

### ISSUE THREAD

**Issue by princekukreja** [microsoft/vscode-docker#3453]
I'm not able to compose up/down the container using the docker extension in VS code.

![Screenshot from 2022-03-03 14-54-18](https://user-images.githubusercontent.com/96442608/156535809-9ed1d6ff-e9c0-445e-a571-5a3eb5bdc1a2.png)

**Comment by bwateratmsft** [comment]
@princekukreja can you right-click a container in the Compose group and do Inspect, and share the inspect result?

**Comment by princekukreja** [comment]
> @princekukreja can you right-click a container in the Compose group and do Inspect, and share the inspect result?

@bwateratmsft Here you go!

`{
    "Id": "c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313",
    "Created": "2022-03-03T13:08:13.923569917Z",
    "Path": "npm",
    "Args": [
        "run",
        "dev"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 60981,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2022-03-03T13:08:17.547230341Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "sha256:af3b6a02c4c8ac6e865c3def8fb05c14c28ce12a5aa981d1d47d0dc0f7a0b306",
    "ResolvConfPath": "/var/lib/docker/containers/c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313/hostname",
    "HostsPath": "/var/lib/docker/containers/c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313/hosts",
    "LogPath": "/var/lib/docker/containers/c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313/c6fedd5f60128822bc3ec726c2027d3fb0b74d8f27214ed932588eb59cd51313-json.log",
    "Name": "/orbitfour_portal_app",
    "RestartCount": 0,
    "Driver": "overlay2",
    "Platform": "linux",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "docker-default",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/home/spark/Documents/spark/OrbitFour:/home/node/app:rw"
        ],
        "ContainerIDFile": "",
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "NetworkMode": "orbitfour_default",
        "PortBindings": {
            "3000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "3000"
                }
            ]
        },
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "AutoRemove": false,
        "VolumeDriver": "",
        "VolumesFrom": [],
        "CapAdd": null,
        "CapDrop": null,
        "CgroupnsMode": "private",
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "GroupAdd": null,
        "IpcMode": "shareable",
        "Cgroup": "",
        "Links": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "SecurityOpt": null,
        "UTSMode": "",
        "UsernsMode": "",
        "ShmSize": 67108864,
        "Runtime": "runc",
        "ConsoleSize": [
            0,
            0
        ],
        "Isolation": "",
        "CpuShares": 0,
        "Memory": 0,
        "NanoCpus": 0,
        "CgroupParent": "",
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "BlkioDeviceReadBps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteIOps": null,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "Devices": null,
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "OomKillDisable": null,
        "PidsLimit": null,
        "Ulimits": null,
        "CpuCount": 0,
        "CpuPercent": 0,
        "IOMaximumIOps": 0,
        "IOMaximumBandwidth": 0,
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ]
    },
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/1d3d164a37e08f360099e84049c7f1cef50febf44a7beb7df136fa40594f5673-init/diff:/var/lib/docker/overlay2/78456f10b43e6cad5ffcb2af715e00ee695ccfd2051f7d76b6479f196d601ba9/diff:/var/lib/docker/overlay2/28f7e772fdbe8c603fe46bf44cb1851910e8a9d1f3cc9be364741f5ec10fea71/diff:/var/lib/docker/overlay2/524e246fb18c92941fd801589b475a92aa4d3d6933fd0afc04413209ad4bafbb/diff:/var/lib/docker/overlay2/69fcba565639c7bf40a844832ed84d255242251216cadbdaae07fb0162f62463/diff:/var/lib/docker/overlay2/448df3cab2db68eebe6d266156a5715d0f413e40df9648a3e4f8a9f1be56f593/diff:/var/lib/docker/overlay2/ef8688c9e021eb205896db5012eb558047731cca51d34c973dea93c0aeca1bed/diff:/var/lib/docker/overlay2/269ca3eccc30a2dccbd354bb6acb1591b0d5ee42ea7e6bc943175b251196b51a/diff:/var/lib/docker/overlay2/0deab3376bfeffcc01cf69583201d463ac449f404c9c3f616b2a1f4a84a04782/diff:/var/lib/docker/overlay2/24ce4415327c254d8df6424b1e7b4439b592749b342cfb12a11278ebef03e104/diff",
            "MergedDir": "/var/lib/docker/overlay2/1d3d164a37e08f360099e84049c7f1cef50febf44a7beb7df136fa40594f5673/merged",
            "UpperDir": "/var/lib/docker/overlay2/1d3d164a37e08f360099e84049c7f1cef50febf44a7beb7df136fa40594f5673/diff",
            "WorkDir": "/var/lib/docker/overlay2/1d3d164a37e08f360099e84049c7f1cef50febf44a7beb7df136fa40594f5673/work"
        },
        "Name": "overlay2"
    },
    "Mounts": [
        {
            "Type": "bind",
            "Source": "/home/spark/Documents/spark/OrbitFour",
            "Destination": "/home/node/app",
            "Mode": "rw",
            "RW": true,
            "Propagation": "rprivate"
        },
        {
            "Type": "volume",
            "Name": "af6a7b943c4ee683b69366ddfda861eeee26240ec244da2869212beb87255764",
            "Source": "/var/lib/docker/volumes/af6a7b943c4ee683b69366ddfda861eeee26240ec244da2869212beb87255764/_data",
            "Destination": "/home/node/app/.nuxt",
            "Driver": "local",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "volume",
            "Name": "dce0cb6691c552d804a27bd438579ab3a7e8df95ac540bfa548f99c3b4aa98c5",
            "Source": "/var/lib/docker/volumes/dce0cb6691c552d804a27bd438579ab3a7e8df95ac540bfa548f99c3b4aa98c5/_data",
            "Destination": "/home/node/app/node_modules",
            "Driver": "local",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        }
    ],
    "Config": {
        "Hostname": "c6fedd5f6012",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3000/tcp": {}
        },
        "Tty": false,
        "OpenStdin": true,
        "StdinOnce": false,
        "Env": [
            "NODE_ENV=development",
            "HOST=0.0.0.0",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=14.19.0",
            "YARN_VERSION=1.22.17"
        ],
        "Cmd": null,
        "Image": "orbitfour_app",
        "Volumes": {
            "/home/node/app": {},
            "/home/node/app/.nuxt": {},
            "/home/node/app/node_modules": {}
        },
        "WorkingDir": "/home/node/app",
        "Entrypoint": [
            "npm",
            "run",
            "dev"
        ],
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "474589c70e39b4d95a2c6f8e70218938e18c2fda3104ced134bd803d0876a860",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "orbitfour",
            "com.docker.compose.service": "app",
            "com.docker.compose.version": "1.24.0"
        }
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "acdb1419b053f544bbeb1917219f733abd388aaf99890abb45d4941a6b64aca0",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3000"
                },
                {
                    "HostIp": "::",
                    "HostPort": "3000"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/acdb1419b053",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": {
            "orbitfour_default": {
                "IPAMConfig": null,
                "Links": null,
                "Aliases": [
                    "app",
                    "c6fedd5f6012"
                ],
                "NetworkID": "0722bd23395853c7c9bebc48aae4b19f2bf3c901895557cab8cb2c7cbde73acc",
                "EndpointID": "d111fa5aff6853aa0bb42d591c4e2668e8f21c9965a18a03b767d06ae7c1365d",
                "Gateway": "172.21.0.1",
                "IPAddress": "172.21.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:15:00:03",
                "DriverOpts": null
            }
        }
    },
    "CreatedTime": 1646312893923
}`

**Comment by bwateratmsft** [comment]
What version of Docker (`docker -v` in the terminal) and Docker Compose (`docker-compose -v`) do you have installed? The container is missing all of the labels necessary to make this command work.

**Comment by princekukreja** [comment]
@bwateratmsft 
Docker version 20.10.7
docker-compose version 1.24.0
![Screenshot from 2022-03-03 20-03-08](https://user-images.githubusercontent.com/96442608/156585526-ddfbbb96-68ba-44da-901f-ec7b9fa75393.png)

**Comment by bwateratmsft** [comment]
It seems like these containers were created with a pre-1.3 version of Compose, which is very old (about 2015).

Even though your compose version is much newer than that, I'd try [updating it](https://docs.docker.com/compose/install/) and relaunching the compose apps entirely.

**Comment by hexpunk** [comment]
I've got the same issue.  I'm able to compose up from the palette menu, but I can't interact with any of the container groups.  I receive the same error as @princekukreja.

```
Docker version 20.10.13, build a224086
docker-compose version 1.21.0, build unknown
```

<details>
<summary>
Results of running inspect on one of the containers in the group
</summary>
<pre>
<code>
{
  "Id": "908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48",
  "Created": "2022-03-19T01:25:00.743385043Z",
  "Path": "/usr/bin/supervisord",
  "Args": [],
  "State": {
    "Status": "running",
    "Running": true,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "Dead": false,
    "Pid": 2649,
    "ExitCode": 0,
    "Error": "",
    "StartedAt": "2022-03-19T01:25:18.111940187Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
  },
  "Image": "sha256:b3704474dd11c347a9b0fff1096f7131554f85ab6c3f13ca41e5b58b317dd67d",
  "ResolvConfPath": "/var/lib/docker/containers/908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48/resolv.conf",
  "HostnamePath": "/var/lib/docker/containers/908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48/hostname",
  "HostsPath": "/var/lib/docker/containers/908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48/hosts",
  "LogPath": "/var/lib/docker/containers/908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48/908c0933c45a1afcaba8bcd2a01c2413bb88b9b238a9b8d0008419e87e9d0f48-json.log",
  "Name": "/samba",
  "RestartCount": 0,
  "Driver": "overlay2",
  "Platform": "linux",
  "MountLabel": "",
  "ProcessLabel": "",
  "AppArmorProfile": "",
  "ExecIDs": null,
  "HostConfig": {
    "Binds": [
      "/media/1234-5678:/samba/public:rw"
    ],
    "ContainerIDFile": "",
    "LogConfig": {
      "Type": "json-file",
      "Config": {}
    },
    "NetworkMode": "host",
    "PortBindings": {},
    "RestartPolicy": {
      "Name": "unless-stopped",
      "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": [],
    "CapAdd": null,
    "CapDrop": null,
    "CgroupnsMode": "host",
    "Dns": null,
    "DnsOptions": null,
    "DnsSearch": null,
    "ExtraHosts": null,
    "GroupAdd": null,
    "IpcMode": "shareable",
    "Cgroup": "",
    "Links": null,
    "OomScoreAdj": 0,
    "PidMode": "",
    "Privileged": false,
    "PublishAllPorts": false,
    "ReadonlyRootfs": false,
    "SecurityOpt": null,
    "UTSMode": "",
    "UsernsMode": "",
    "ShmSize": 67108864,
    "Runtime": "runc",
    "ConsoleSize": [
      0,
      0
    ],
    "Isolation": "",
    "CpuShares": 0,
    "Memory": 0,
    "NanoCpus": 0,
    "CgroupParent": "",
    "BlkioWeight": 0,
    "BlkioWeightDevice": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteIOps": null,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "Devices": null,
    "DeviceCgroupRules": null,
    "DeviceRequests": null,
    "KernelMemory": 0,
    "KernelMemoryTCP": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": null,
    "OomKillDisable": null,
    "PidsLimit": null,
    "Ulimits": null,
    "CpuCount": 0,
    "CpuPercent": 0,
    "IOMaximumIOps": 0,
    "IOMaximumBandwidth": 0,
    "MaskedPaths": [
      "/proc/asound",
      "/proc/acpi",
      "/proc/kcore",
      "/proc/keys",
      "/proc/latency_stats",
      "/proc/timer_list",
      "/proc/timer_stats",
      "/proc/sched_debug",
      "/proc/scsi",
      "/sys/firmware"
    ],
    "ReadonlyPaths": [
      "/proc/bus",
      "/proc/fs",
      "/proc/irq",
      "/proc/sys",
      "/proc/sysrq-trigger"
    ]
  },
  "GraphDriver": {
    "Data": {
      "LowerDir": "/var/lib/docker/overlay2/ff33ea2a7026fc70c15cc7d652e01afb28ef246580565aec6bd34fc2322f3800-init/diff:/var/lib/docker/overlay2/9312799870e6704f5b8691753df66e023144071c6f31fb2d4396def38c991319/diff:/var/lib/docker/overlay2/3dcf30683dc4cbefe1c255c9a6982cf87e9998b2ef07ac0ac0ab3a317266d3b1/diff:/var/lib/docker/overlay2/a1c2e9a84b9d0ba5107f97cda20380f2f8eb298c72b2be412a4ddb1437c457a7/diff:/var/lib/docker/overlay2/27fad1f679ae1b6af28e9206ab602f4a8d8341314d4dd3750039c3fbc18fcbff/diff:/var/lib/docker/overlay2/ac6fd1aa40edcf64f3cdeda86eafdab974794f4d849bfeeea03449b8e60d96a6/diff",
      "MergedDir": "/var/lib/docker/overlay2/ff33ea2a7026fc70c15cc7d652e01afb28ef246580565aec6bd34fc2322f3800/merged",
      "UpperDir": "/var/lib/docker/overlay2/ff33ea2a7026fc70c15cc7d652e01afb28ef246580565aec6bd34fc2322f3800/diff",
      "WorkDir": "/var/lib/docker/overlay2/ff33ea2a7026fc70c15cc7d652e01afb28ef246580565aec6bd34fc2322f3800/work"
    },
    "Name": "overlay2"
  },
  "Mounts": [
    {
      "Type": "bind",
      "Source": "/media/1234-5678",
      "Destination": "/samba/public",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    }
  ],
  "Config": {
    "Hostname": "hexpunk-device",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
      "137/udp": {},
      "138/udp": {},
      "139/tcp": {},
      "445/tcp": {}
    },
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": null,
    "Image": "samba_samba",
    "Volumes": {
      "/samba/public": {}
    },
    "WorkingDir": "",
    "Entrypoint": [
      "/usr/bin/supervisord"
    ],
    "OnBuild": null,
    "Labels": {
      "com.docker.compose.config-hash": "37a8c898f64d59cef0cc1b73d54f2951251ed0db9413dbbcdc35673d4328d817",
      "com.docker.compose.container-number": "1",
      "com.docker.compose.oneoff": "False",
      "com.docker.compose.project": "samba",
      "com.docker.compose.service": "samba",
      "com.docker.compose.version": "1.21.0"
    }
  },
  "NetworkSettings": {
    "Bridge": "",
    "SandboxID": "9f6083cb85df1838ab9483933c2cba7decd9bde2260717ff7b84929cb70049c0",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {},
    "SandboxKey": "/var/run/docker/netns/default",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
      "host": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": null,
        "NetworkID": "4921927faa867d3e482861acf0d368dd2e77995c914bec3ba24c07df4d5c1e79",
        "EndpointID": "be8b48482e4f13b8a266cb7aea9012b7e04e9ac884b6759a506f402db59f2027",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "",
        "DriverOpts": null
      }
    }
  },
  "CreatedTime": 1647653100743
}
</code>
</pre>
</details>

**Comment by bwateratmsft** [comment]
Can you share more info about your setup? How Docker and compose were installed, etc.? Without the necessary labels on the containers, it is not possible for the extension to manage the Compose projects, so there's nothing that can be done--but I'd like to know what is leading to this scenario.

**Comment by hexpunk** [comment]
The remote machine I'm connecting to is a Raspberry Pi 4B running Raspbian GNU/Linux 10.11.  Docker and docker-compose were installed via this debian repository:
```
deb [arch=armhf] https://download.docker.com/linux/debian buster stable
```
