### ISSUE TITLE
Ctrl+PageUp / Ctrl+PageDown doesnt work sometimes on a docker shell

### ISSUE THREAD

**Issue by javs** [microsoft/vscode-docker#3457]
1. Open a non-docker shell (e.g. bash).
2. Open a docker shell (e.g. attach shell to a container).
3. Focus the non-docker shell.
4. Press Ctrl+PageDown, focus moves to docker shell, cursor correctly focuses command line.
5. Press Ctrl+PageUp.

Expected: focus to move back to non-docker shell.
Actual: tabs file in editor area changes focus instead.

Notes:
* This works consistently for shell types other than docker shells.
* If instead of the keyboard shortcut one uses the command pallete (e.g. "Terminal: Focus Previous Terminal Group"), cycling works correctly.
* Maybe related to the "when" clause of the key mapping, set by default as `terminalFocus && terminalHasBeenCreated && !terminalEditorFocus || terminalFocus && terminalProcessSupported && !terminalEditorFocus`

**Comment by bwateratmsft** [comment]
Most of the Docker CLI commands are executed as tasks, that may be related.

**Comment by bwateratmsft** [comment]
I am not able to repro this on Windows or in WSL, with VSCode 1.65.0. What version of VSCode do you have @javs?

**Comment by javs** [comment]
I think I was in 1.64.x. I updated today to 1.65.1 and I can't reproduce any more, so I think it's good.
