### ISSUE TITLE
[Windows 10 + WSL2] Extension versions >= 1.4.0 are broken

### ISSUE THREAD

**Issue by theAkito** [microsoft/vscode-docker#3458]
I'm getting `Failed to connect. Is Docker running?` for all sections of the extension's page, when using **ANY** version that is higher than `1.3.1` (`1.4.0` is the next installable one). I have installed all the versions, starting from the newest one, i.e. `1.20.0` down to `0.9.0`. All versions up to and including `1.3.1` work. Then, at `1.4.0` it stops working.

Obviously, Docker is working as it should, etc. or else the earlier versions wouldn't work either.

I found several issues, looking like the following ones.

https://github.com/microsoft/vscode-docker/issues/2933
https://github.com/microsoft/vscode-docker/issues/2058

Perhaps, this might be related to the support of contexts. I do not use that feature, at all. My Docker installation on WSL 2 is pretty generic and provided the official Docker Desktop way.

**Comment by bwateratmsft** [comment]
Are you using a Remote - WSL connection? Or running on the Windows host?

What version of Docker Desktop do you have?

**Comment by theAkito** [comment]
@bwateratmsft 

Thank you for responding so quickly! 🙂 

> Are you using a Remote - WSL connection?

I am using the default way of VS Code to connect to WSL2, which seems like it's the `Remote-WSL` way, so, yes.

Docker Desktop Version: 4.5.1 (74721)

Engine: 20.10.12

Compose: v2.2.3

Credential Helper: 0.6.4

Kubernetes: v1.22.5

Snyk: v1.827.0

**Comment by bwateratmsft** [comment]
Thanks! One more question; which WSL distro are you connecting to? On my machine I have Ubuntu (Default), `docker-desktop-data`, and `docker-desktop`. If I connect to the Ubuntu one things work as expected. I think you're not meant to connect to the `docker-desktop` ones; i.e. they're thought of as "hidden".

**Comment by theAkito** [comment]
@bwateratmsft 

```powershell
Windows Subsystem for Linux Distributions:
Debian (Default)
docker-desktop
Alpine
docker-desktop-data
```

I connect to and always use Debian for everything. Neither did I ever connect to `docker-desktop` nor to `docker-desktop-data`. I also never used the Alpine one through VS Code.

I just set up that Debian as the WSL target a long time ago and then didn't change it since then. It's all working on `Debian`. I also have a lot of other extensions installed on this `Debian` and they all work, as they should.

**Comment by bwateratmsft** [comment]
That makes sense, thanks! In the Debian instance, if you open a terminal and do `docker context ls --format="{{json .}}"` does it give results or an error? What's the output of `docker -v` (also from within the WSL terminal)?

I'm wondering if what is happening is that the Docker CLI in the Debian "VM" is old. I'm not sure if Docker Desktop will update the executable within the WSL instance or if the user is expected to do that themselves with `apt` / similar. If it's old it might error on that `docker context` command. Our logic is _supposed_ to tolerate that but there might be something going wrong; we don't typically test with old CLIs.

**Comment by theAkito** [comment]
```bash
docker context ls --format="{{json .}}"
```

Indeed, that was the issue.

@bwateratmsft Thank you for the help! 🙂

To future readers who would encounter this issue:

1. Enter your WSL2 and enter the following commands.
```bash
cd
mv .docker .docker-broken
```

2. Go back to VS Code.
3. File -> Exit
4. Re-Open VS Code.
5. This extension should work, again.

**Comment by bwateratmsft** [comment]
Ah, I wonder if this is the same as #3249--there was an upgrade of Docker Desktop that corrupted a config file in the `%userprofile%\.docker` folder. That was on the Windows side, but it's possible the same/similar thing happened on the WSL side.
