### ISSUE TITLE
Refreshing Explorer doesn't collapse the expanded nodes

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#346]
Repro Steps:
1. Navigate to Docker Explorer -> expand some nodes.
2. Click 'Refresh' icon.

Expect:
The expanded nodes are collapsed after refreshing.

Actual:
The expanded nodes aren't collapsed after refreshing.

**Comment by estebanreyl** [comment]
I think that's expected behavior as it allows for saving state. Refreshing, from my understanding only checks for new items that may have appeared (say a new item was added (repository, container registry, image, etc)). I am not sure however if this is considered standard behavior ?

**Comment by StephenWeatherford** [comment]
Correct, by design.  Collapsing the nodes would be frustrating to users.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
