### ISSUE TITLE
Docker plugin cannot detect Docker is installed when it actually is

### ISSUE THREAD

**Issue by mpconte** [microsoft/vscode-docker#3466]
VS Code Version: 1.65.2
OS Version: Windows 10 Enterprise (version 20H2)

Steps to Reproduce:

1) Installer Docker plugin
2) Install Docker Desktop (version 4.6.0)
3) Select Docker tab, it indicates "Failed to connect. Is Docker installed?"

**Comment by mpconte** [comment]
@bwateratmsft Yes, I've also tried reinstalling VS Code and Docker Desktop

**Comment by bwateratmsft** [comment]
The way we detect if docker is installed is by trying `docker -v`; if it returns a 0 error code Docker is considered installed. What happens if you run that command in a terminal?

**Comment by mpconte** [comment]
unable to resolve docker endpoint: ..path to certificate file..

I've found a solution from the following [link](https://stackoverflow.com/questions/49679818/docker-could-not-read-ca-certificate)

I deleted the DOCKER environment variables and not it works

**Comment by bwateratmsft** [comment]
Ah, I see. I'll keep this in mind if users hit this in the future. Based on that StackOverflow post it looks like if Docker Toolbox was previously installed, and later Docker Desktop for Windows is installed instead, this can happen.
