### ISSUE TITLE
There is no custom location in the location list when asking to select a location for deploying image to app service

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3467]
**OS:** All
**Build Version:** 20220315.3

**Repro Steps:**
1. Right click an image in the registry view -> Deploy Image to Azure App Service -> Select a subscription -> Enter a web app name -> Select a resource group.
2. Check whether there is a custom location in the location list when asking to select a location.

**Expect:**
There is a custom location in the location list when asking to select a location.

**Actual:**
There is no custom location in the location list when asking to select a location.
<img width="610" alt="Screen Shot 2022-03-17 at 09 54 44" src="https://user-images.githubusercontent.com/62053665/158750007-72613908-c487-44fa-9807-b4e5a23f7f9c.png">

**Comment by bwateratmsft** [comment]
Potentially related to #3444 and/or https://github.com/microsoft/vscode-azuretools/pull/1087

**Comment by bwateratmsft** [comment]
I am no longer able to reproduce this issue.
