### ISSUE TITLE
Don't communicate with docker until necessary

### ISSUE THREAD

**Issue by guilhem** [microsoft/vscode-docker#3475]
Currently, docker plugin communicate with docker at each run, even if not necessary.
When using socket activation, it spawns docker daemon + all networks, and it has impact on battery consumption.

Postponing docker communication will prevent it.

Another way can be to separate `Dockerfile` linting plugin from Docker management, itself.
User being able to disable Docker communication without losing linting.

**Comment by bwateratmsft** [comment]
This would probably be solved by #3263. Right now our initial communications with Docker are to get the context so we can set up Dockerode; if the CLI alone was used then none of that would be needed.

**Comment by guilhem** [comment]
thanks @bwateratmsft, I subscribed.

**Comment by bwateratmsft** [comment]
Fixed by #3263

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.
