### ISSUE TITLE
Add .venv to default .dockerignore

### ISSUE THREAD

**Issue by matneh** [microsoft/vscode-docker#3476]
Situation:
When working through the Flask tutorial in https://code.visualstudio.com/docs/python/tutorial-flask it recommends following this tutorial https://code.visualstudio.com/docs/containers/quickstart-python to discover how to containerize a python application.

In the Flask tutorial, it suggests creating a virtual environment inside the `.venv` directory, but in the default `.dockerignore` file there is an ignore for `.env`.

I suggest that either the docker plugin add `.venv` as one of its defaults in `.dockerignore`, OR change the Flask tutorial to recommend building a virtual environment in the `.env` directory.

**Comment by bwateratmsft** [comment]
This is a good idea. Should be quick to add to the .dockerignore template.
