### ISSUE TITLE
Duplicated IntelliSense with YAML extension

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode-docker#3480]
When both this extension and the [YAML Support extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) are enabled, the IntelliSense suggestions for docker compose files are duplicated like this:

![image](https://user-images.githubusercontent.com/22894169/161321472-9f53b817-ff5d-4351-a1d9-6787c85e2b69.png)

**Comment by bwateratmsft** [comment]
I've noticed this too 😕

I'm not sure of the best approach other than to use the `docker.enableDockerComposeLanguageService` setting to disable the language server provided by the Docker extension. They YAML extension may offer a way to selectively disable itself for files of the language type "Compose" (id: `dockercompose`), but I have not checked.

**Comment by bwateratmsft** [comment]
We could add auto-detection so if we see YAML is also installed, maybe prompt if they want to disable the Docker language server.

**Comment by ucheNkadiCode** [comment]
@bwateratmsft do we feel as though the Docker extension provides more value for Yaml **within** the Compose file though?

If so would there be a way to instead suppress the YAML support extension just for this specific file type?

**Comment by bwateratmsft** [comment]
We could ask the YAML extension to support that, but it would require them to make changes. VSCode might also have a way to choose one language server or another for a given language, but I'm not sure.

**Comment by ucheNkadiCode** [comment]
Added over here https://github.com/redhat-developer/yaml-language-server/issues/715

**Comment by Igorgro** [comment]
@bwateratmsft I have an idea of how this can be solved. You can add a new separate Docker compose "language" which will be associated with this extension and corresponding language server and which won't be conflicting with YAML. This is what was done for example in Ansible extension: they also have separate "Ansible" language and language server

**Comment by bwateratmsft** [comment]
@Igorgro this was already done; there is a separate `dockercompose` language definition built in to VSCode. The YAML extension is explicitly targeting that language as well as `yaml`.

**Comment by bwateratmsft** [comment]
This is largely mitigated at this point; we did some deconfliction work with the YAML extension so that only some of the advanced completions show up if the YAML extension is present.
