### ISSUE TITLE
Failed to connect. Is Docker installed and running?

### ISSUE THREAD

**Issue by tigeran2020** [microsoft/vscode-docker#3483]
I am using docker to develop on remote linux host, and I am using docker context to connect to the remote host.
But I got error `Failed to connect. Is Docker installed and running?` when I open the docker panel on vscode:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/65532159/162154525-bddcca64-3f47-4d54-be39-8887ce6f19f5.png">

 And the  Docker CLI works :

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/65532159/162155165-06e9dd92-3964-4dc1-9b40-4c8d1e5f3587.png">

**Comment by bwateratmsft** [comment]
This error usually occurs in SSH contexts when an ssh-agent has not been set up. Even though the Docker CLI does not require one, the `ssh2` package used by `dockerode` does. There's more info on setting it up here: https://code.visualstudio.com/docs/containers/ssh#_set-up-ssh-tunneling

Once you have one going, does it work?

**Comment by tigeran2020** [comment]
> 

After I had restarted the remote linux, it worked.
I will try your way next time.

**Comment by bwateratmsft** [comment]
Glad to hear it's working now!

**Comment by Igorgro** [comment]
@bwateratmsft Hi! I have the same issue, but I have ssh-agent running. It seems like vscode cannot detect it and shows the warning and cannot connect to remote context. I've everything according to instruction yu linked but it still doesn't works.

**Comment by karolz-ms** [comment]
@Igorgro please confirm you _understood and followed the first tip in the instructions_ (the one about using only globally-resolvable DNS machine name or IP address in Docker endpoint definition) and that the remote Docker context is usable from command line (you can execute command such as `run`, `images` etc against that context).

If that is all true, maybe you can share the definition of your remote Docker context?

**Comment by Igorgro** [comment]
Yes, I can run any docker commands from command line, but not from vscode. I'm creating the context with the following command: `docker context create myserver --docker "host=ssh://igormahov@192.168.1.2:22"`

**Comment by karolz-ms** [comment]
Igorgro thanks. Sorry, I have no other ideas why the Docker extension does not work; looks like you did everything right. 😞
