### ISSUE TITLE
Registries: Unable to scroll down beyond 1st page of Images

### ISSUE THREAD

**Issue by flavour** [microsoft/vscode-docker#3489]
Our Docker registry has a lot of images on...when I open the registry then the 1st page appears fine, however there is no way that I can find to scroll down beyond this first page...so currently nothing beyond 'f'
Removing the Containers/Images/Volumes/Networks/Help from view doesn't help...I see no extra images & no option to scroll
Am running Extension 1.21.0 on VS Code 1.66.1 (was also happening for 1.66.0) on Ubuntu 20.04
Happy to provide any other details/do debugging if you guide me
Thanks!

**Comment by bwateratmsft** [comment]
@flavour are you able to provide some screenshots? It's fine to censor image names if needed.

**Comment by flavour** [comment]
I made a little mistake...I can scroll a bit...so the 1st screenshot is the initial screen, and the second is after scrolling to the bottom of where I can scroll...but I know that there are many more images underneath 'f'
![Docker_Registry_1](https://user-images.githubusercontent.com/389592/163005238-47a706c5-085c-4a94-8842-e1d0a2904c27.png)
![Docker_Registry_2](https://user-images.githubusercontent.com/389592/163005240-a9772a56-5d9b-4874-b75a-7a73158550f2.png)

**Comment by bwateratmsft** [comment]
Gotcha. I didn't count but it looks like you're hitting the default page size of 100. There's supposed to be a `Load more...` item at the end of the list, and clicking it loads the next page. I'll take a look and see if I can figure out what's going on.

**Comment by bwateratmsft** [comment]
Is the registry based on the official [Registry](https://hub.docker.com/_/registry) image, or is it another implementation?

**Comment by flavour** [comment]
It's the official one

**Comment by bwateratmsft** [comment]
I'm not able to reproduce the issue with the `registry:2` image. To debug I just set the maximum page size to 5; and I'm able to see the `Load More...` button at the bottom of the list, and it works as expected. I'm wondering if it works differently when the registry is configured as a mirror; I'll try that.

**Comment by bwateratmsft** [comment]
@flavour I set my registry up as a mirror and was still able to see the `Load More...` button. I even changed around some window heights and positions, but I'm always able to see it.

Can you scroll to the bottom of that repository listing and see if the option is there?

**Comment by flavour** [comment]
Thanks...not the option is definitely not there...funny thing is that I am pretty sure that I have seen it in the past...probably a couple of revisions of code ago.
I tried playing with my zoom & full screen, but no joy...with zoom far out then I can see all the images that are loaded...and empty space below it...plenty of space for the 'Load more' but it's not visible.
I tried disconnecting/reconnecting the registry, but no joy.

**Comment by bwateratmsft** [comment]
That's strange. The only thing I can think of that would cause this is that the `link` header being missing or malformed in the response. That `link` header is basically used to get the _next_ page of items.

The only way I can think of to investigate this is to either provide you a private build that logs the header to the output window, or if you're familiar with Postman or similar products, you could make the request to the registry and look at the headers. Do you have a preference?

**Comment by flavour** [comment]
I had a try with Postman, but it doesn't work easily...our registry has a custom SSL cert...I found where to put that into Postman, but it still doesn't log the requests at all & the images completely fail to load, so it is definitely trying to use the proxy.

**Comment by flavour** [comment]
Thanks, I installed this fine...confirmed that this shows as v1.22.5-alpha in extensions
Absolutely nothing appears in OUTPUT when I browse the registry, which I guess confirms your suspicion?
Weird that I am sure that I have seen this in the past & the registry software hasn't been upgraded since.
