### ISSUE TITLE
The repository keeps deleting status and doesn't disappear from registry view directly after deleting its images

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3490]
**OS:** All & Codespaces
**Build Version:** 20220411.2
**Regression:** Previous release

**Repro Steps:**
1. Make sure connected Azure registry.
2. Right click a image -> Push -> Azure -> Select a registry (e.g. nicole1) -> Enter default value.
3. Navigate to Registry view -> Expand the Azure -> Expand "nicole1" registry -> Expand the repository -> image.
4. Right click the image -> Delete Image.
5. Check whether the repository is also deleted and disappears from registry view directly.

**Expect:**
The repository is also deleted and disappears from registry view directly.

**Actual:**
The repository keeps deleting status and doesn't disappear from registry view directly.
![actual](https://user-images.githubusercontent.com/57662131/162936046-36622b32-4274-46d3-a016-72f40ab61094.gif)

**More Info:**
This issue can be fixed by restarting VS Code.

**Comment by bwateratmsft** [comment]
OK to release 1.22.0 with this. We'll investigate.

**Comment by bwateratmsft** [comment]
Relates to #544

**Comment by dbreshears** [comment]
Closing as low priority, assuming this still reproduces.
