### ISSUE TITLE
Can't select the Docker Hub registry provider after executing the command "Docker Registries: Copy Full Tag" from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3491]
**OS:** All
**Build Version:** 20220411.2
**Regression:** Not a Regression

**Repro Steps:**

1. Make sure connected Azure registry and Docker Hub registry.
2. F1 -> Docker Registries: Copy Full Tag.
3. Check whether can select the Docker Hub registry provider.

**Expect:**
Can select the Docker Hub registry provider.
![image](https://user-images.githubusercontent.com/62053665/162940836-dc72e1df-f785-439e-802a-8f0aae6d62c5.png)

**Actual:**
Can't select the Docker Hub registry provider.
![dockers](https://user-images.githubusercontent.com/62053665/162941919-50b80160-1d6a-4a60-9f0a-4811bd21646f.gif)

**More Info:**
1. The command "Copy Full Tag" in the context menu of the Azure registry and Docker Hub registry.
    ![image](https://user-images.githubusercontent.com/62053665/162942791-6db7ddee-7ac6-40e2-8ee0-951b1ae738b7.png)
2. Can select the Generic Docker Registry provider after executing the command "Docker Registries: Copy Full Tag" from command palette.
    ![image](https://user-images.githubusercontent.com/62053665/162944006-9546967c-5bc8-4ac3-8748-cbe6c3950984.png)

**Comment by bwateratmsft** [comment]
Might be a similar issue to what I fixed with #3487. I'll take a look.
