### ISSUE TITLE
No longer works with latest Docker Desktop

### ISSUE THREAD

**Issue by elucidsoft** [microsoft/vscode-docker#3499]
This no longer works under WSL with the latest version of Docker Desktop 4.7.0 (77141).  I get an error saying "Error: Process 'docker context ls --format --format={{.json.}} exited with code 1" in the VSCode Explorer window for both Containers and Images.  

Detailed Error: ``Error: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: invalid character '\x00' looking for beginning of value``

- VSCode
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.2259

Yes, Docker Desktop is running. Yes Docker Desktop is working, I can view the logs from the command line and from Docker Desktop of my containers just fine. All my containers are running fine with no issues. Yes I have restarted WSL, and rebooted the machine. Yes I have uninstalled and re-installed the extension. No I do not have another Docker extension installed. Yes I have confirmed I can view logs in WSL by running the command from the command prompt.  This just started this morning, it's been working fine for me for nearly a year.  

![image](https://user-images.githubusercontent.com/217424/163843399-87f95ee8-8dd9-4b72-843f-39b0a93a042e.png)

**Comment by elucidsoft** [comment]
Perhaps related? https://github.com/docker/for-linux/issues/140

**Comment by elucidsoft** [comment]
FYI, the solution to this is to Reset Factory Settings on Docker Desktop which clears out the offending log with the bad character in it that causes this entire mess.  It's a hack, but it works.

**Comment by bwateratmsft** [comment]
Same as #3249. Unfortunately this is outside of our control, but doesn't seem to happen often. I'll keep in mind that the Factory Reset works; previously the only way I knew of was to delete the local settings files which would _probably_ not be supported by Docker.
