### ISSUE TITLE
Support "context-based" completion for compose files

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-docker#35]
Currently, the completion support for compose files simply displays a list of all possible properties, regardless of the cursor's position in the file. For example, bringing up the completion list at the top-level of a v2 file should only display `services`, `volumes` and `networks`, since those are the only allowable properties. 

Adding this support would not only provide the user with a more "guided" authoring experience (why should someone need to remember which properties they can use at a specific position?), but it would allow us to display customized documentation for properties that exist in multiple contexts (e.g. the `driver` property could indicate a custom logging driver, network driver, volume driver, etc.).

**Comment by PrashanthCorp** [comment]
Closing due to lack of user feedback.
