### ISSUE TITLE
wx

### ISSUE THREAD

**Issue by KY-0426** [microsoft/vscode-docker#3503]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: open C:\Users\Administrator\.docker\contexts\meta\fe9c6bd7a66301f49ca9b6a70b217107cd1284598bfc254700c989b916da791e\meta.json: The system cannot find the file specified.

Version: 1.8.1
OS: win32
OS Release: 10.0.22000
Product: WeChat Web Devtools
Product Version: 1.52.0
Language: zh-CN

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:98044
ChildProcess.emit events.js:315:20
maybeClose child_process.js:1026:16
Process.ChildProcess._handle.onexit child_process.js:286:5
```

</details>

**Comment by bwateratmsft** [comment]
This error is coming from the Docker CLI; it looks like the file is corrupted or disappeared unexpectedly. This is outside of our control.
