### ISSUE TITLE
Automatically auth to registry when pushing, not just when pulling

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#351]
We should be able to do this programmatically. Need to investigate whether this can be done via AAD or Service principal (with admin disabled).

**Comment by estebanreyl** [comment]
Do you mean automatically do az acr login --name regname? . If this is for the cli, the only issue is that we wouldnt know for certain that people have the CLI installed, I am also wondering if this would be for when doing existing push and pull. We could check if people are pushing to ACR and then run a containerized cli including az acr login and do the push for them. Alternatively my team is working on doing push for ACR removing the CLI from the middle and using the built in API. To answer your question the authentication to do this underneath follows the same docker login syntax and can use a null GUID and a refreshtoken bith obtained from the apis.  Service principals are also an option but wouldnt be necessary in the scheme we are using

**Comment by fiveisprime** [comment]
I don't want to depend on the CLI and we should be able to do this via the JS SDK. I envision provisioning an RBAC SP on the users' behalf and configuring the environment to auth with the registry using the SP.

I'm still uncertain if this is possible though.
