### ISSUE TITLE
Fail to execute docker login with an error on Linux

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3513]
**OS:** Ubuntu20.04
**Docker Extension Build Version:** 20220506.1

**Repro Steps:**
1. Create a new azure registry.
2. Navigate to terminal window -> Run the following command `docker login <registry-name>.azurecr.io` -> Enter username 
-> Enter password -> Press Enter.
3. Check whether succeeds to execute docker login.

**Expect:**
Succeed to execute docker login.

**Actual:**
Fail to execute docker login with an error.
![image](https://user-images.githubusercontent.com/57662131/167392001-2d3b4d13-fb50-45f0-b25d-0871fe3fa0cb.png)

**More Info:**
1. This issue doesn't reproduce when installing docker with docker engine.
2. Show "Password encryption aborted." after executing "pass init <registry-name>".
![image](https://user-images.githubusercontent.com/57662131/167395564-d71c305e-7e27-4a05-ab36-831f407c1794.png)

**Comment by bwateratmsft** [comment]
I was not able to reproduce on Ubuntu 22.04.

**Comment by v-xinda** [comment]
@bwateratmsft I will verify this issue on the next Docker extension test pass.

**Comment by v-xinda** [comment]
Verified on Ubuntu 21.10 with the latest build 20220601.3 and the new Docker Desktop 4.9.0. This issue doesn't reproduces for now, so close it.

**Comment by karolz-ms** [comment]
@v-xinda thanks. Just for future reference, I would recommend using Ubuntu 22.04 a.k.a. Jammy as the primary Linux flavor for future testing. It is the latest LTS release https://ubuntu.com/about/release-cycle

**Comment by v-xinda** [comment]
@karolz-ms  Got it. we will use Ubuntu 22.04 a.k.a. Jammy as the primary Linux flavor for future testing.
