### ISSUE TITLE
Fail to debug the project if debugging a .NET 7 MVC project with "7.0-jammy" image

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3518]
**OS:** Win 10
**Docker Extension Build Version:** 20220510.1
**.NET Version:** 7.0.100-preview.3.22179.4

**Repro Steps:**
1. Create and open a .NET 7.0 MVC project in VS Code.
2. Add Docker files to this project (Linux Container).
3. Open the Dockerfile and change the image to "**7.0-jammy**".
4. Debug this project with the configuration "Docker .NET Core Launch".
5. Check whether succeeds to debug the project with a web page opening.

**Expect:**
Succeed to debug the project with a web page opening.

**Actual:**
Fail to debug the project.
![image](https://user-images.githubusercontent.com/45614674/167673958-e711d0fa-6ab7-4623-b27f-23519ddf5cbc.png)

**More Info:**
This issue does not reproduce for image "7.0/7.0-alpine".

**Comment by bwateratmsft** [comment]
@mthalman have you seen anything about `libssl` on the `7.0-jammy` containers?

**Comment by bwateratmsft** [comment]
Tested it out; both `7.0` (Debian) and `7.0-alpine` (Alpine) work as expected. Seems only Jammy is affected. .NET 6.0 seems to also be equally affected.

The pipe command being used looks like this:
```bash
docker exec -i container-name /remote_debugger/vsdbg
```

**Comment by mthalman** [comment]
Ah, I bet it is vsdbg that has the dependency then?

**Comment by bwateratmsft** [comment]
That would not surprise me. I'll sync with some vsdbg folks.

**Comment by bwateratmsft** [comment]
Working with the vsdbg folks, they have a fixed version and I tested it successfully, with .NET 6.0 Alpine/Debian/Ubuntu Focal/Ubuntu Jammy, and .NET 7.0 Alpine/Debian/Ubuntu Jammy. Once this has been released I'll close this issue.

**Comment by bwateratmsft** [comment]
vsdbg has updated its links; this should now be fixed. @v-ruizh can you try it out during the next Docker test pass, and reopen this issue if it still exists?

Thanks!
