### ISSUE TITLE
Support for deploying to Azure Container Apps

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3535]
We should add support for deployment to Azure Container Apps. Potentially work with the ACA extension or with shared libraries.

We should also consider having this replace the deployment to ACI.

Depends on https://github.com/microsoft/vscode-azurecontainerapps/issues/209.

**Comment by bwateratmsft** [comment]
A couple of possible options:

1. The ACA extension puts a command in our context menu. A disadvantage of this is that if the ACA extension is not installed, discoverability isn't there.
2. The Docker extension puts a small wrapper command in our context menu. It will install ACA if needed and proceed with calling the "real" command in ACA.
3. The Docker extension implements its own deployment with some level of code sharing.

Of these I prefer 1 or 2.

**Comment by philliphoff** [comment]
I like #1 the best, by far, and #3 the least, by far.  I see #1 as a convenience for a user that already knows and cares enough about ACA to have first installed that extension. I don't quite buy (2) or (3) as an effective means for ACA discovery.

**Comment by mudanzasIPROM** [comment]
mmmmmmmmmmm

**Comment by bwateratmsft** [comment]
> A question remaining to be answered: do we want to show the command only if ACA extension is already installed?

After further discussion we've decided we'll show it even without ACA, and provide an experience for getting it installed.

**Comment by bwateratmsft** [comment]
Associated docs PR: https://github.com/microsoft/vscode-docs/pull/6028
