### ISSUE TITLE
Consider deprecating `docker.host`, `docker.context`, etc. settings

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3539]
We're thinking about deprecating these settings, in favor of using VSCode's standard `terminal.env.<os>` option. I think that we would want to have a migration experience to help users get over to the new settings, as well as some documentation to describe how to set those.

VSCode will apply those environment variables automatically to all terminal windows, but we would need to pick up and apply the appropriate setting for any shell tasks that we execute behind-the-scenes.

**Comment by bwateratmsft** [comment]
@Tyriar had an alternative idea I think I like better. Instead of using `terminal.integrated.env.<os>`, define our own setting that accepts any key/value pairs, e.g.:
```json
"containers.envVariables": {
    "DOCKER_HOST": "..."
}
```
We can apply this setting to `ExtensionContext.environmentVariableCollection`, as well as any shells we create in the background.

**Comment by chrmarti** [comment]
I assume that could contain env variables for several CLIs? (E.g., Docker and Podman.)

**Comment by bwateratmsft** [comment]
Yes, I think we would make it accept any environment variables, so that we don't have to chase many runtimes' particular environment variables.

**Comment by bwateratmsft** [comment]
Associated docs PR: https://github.com/microsoft/vscode-docs/pull/5488

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.
