### ISSUE TITLE
Find all occurrances stopped working but "find declaration"/"find definition" still work

### ISSUE THREAD

**Issue by nccaruso** [microsoft/vscode-docker#3543]
Issue Type: <b>Bug</b>

I am not sure how to reproduce -- I disabled some extensions (not sure which) and re-enabled them, restoring the system to what should have been the original state, but now "find all references" says "no references" to query, even though the same queries worked before the initial disable.    And "goto definition/declaration" both still work.  Tried uninstalling and re-installing all extensions and the lookup still fails.  

Extension version: 1.22.0
VS Code version: Code - Insiders 1.68.0-insider (2260d7cca34384a2838c728850afdd38113ddb47, 2022-06-04T00:27:36.630Z)
OS version: Linux x64 5.13.0-44-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|15.35GB (2.75GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5adb8f96-574e-4a6c-a93f-c40902f48c5f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container drone_automation:_home_ncaruso_dev_drone_automation (drone_automation-_home_ncaruso_dev_drone_automation)|
|OS|Linux x64 5.13.0-44-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 2900)|
|Memory (System)|15.35GB (2.75GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by bwateratmsft** [comment]
@nccaruso did you mean to file this in the [microsoft/vscode](https://github.com/microsoft/vscode) repo?

**Comment by nccaruso** [comment]
well, I'm not sure.  I am using the remote explorer.

**Comment by bwateratmsft** [comment]
Which programming language is this occurring for?

**Comment by bwateratmsft** [comment]
Ok, can you open this issue in the [repo](https://github.com/Microsoft/vscode-cpptools) for the C++ extension? Most likely the issue is there, but it's definitely not in the Docker extension.

**Comment by nccaruso** [comment]
Sure, sorry, I used a "file a bug report" button somewhere in the app and I
guess I was not careful.  Thanks for your help!
