### ISSUE TITLE
Use ext.ui.showQuickPick everywhere

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-docker#355]
This could bring uniformity - like appropriate values for ignoreFocusOut, etc.

**Comment by estebanreyl** [comment]
My team has a working one of these. Will soon PR

**Comment by StephenWeatherford** [comment]
vscode.window.showQuickPick 
=> 
ext.ui.showQuickPick

Note that ext.ui.showQuickPick throws UserCancelledError if cancelled rather than returning undefined.  This is already being used in a few places (necessary for test automation).
