### ISSUE TITLE
Failed to connect. Is Docker installed and running? Error: connect ENOENT /var/run/docker.sock

### ISSUE THREAD

**Issue by dnsahoo** [microsoft/vscode-docker#3552]
Issue Type: <b>Bug</b>

I have installed: Docker and Remote-Container... plugins
and I have Dockerfile, and press (Ctrl + Shift + P) --> select: Remote-Container: Open folder in Container....

Able to run file inside container successfully But while kept breakpoint in Python file, its shows following error:

Failed to connect. Is Docker installed and running? Error: connect ENOENT /var/run/docker.sock

Extension version: 1.22.0
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.63GB free)|
|Process Argv|--crash-reporter-id 55a0213b-1592-4403-919d-a7a2cd9e9d4c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (2 x 1896)|
|Memory (System)|1.94GB (0.26GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549
841h4636:30513947

```

</details>

**Comment by bwateratmsft** [comment]
The explorer view will not work from within the container as the Docker extension cannot reach the container host. The easiest solution would be to keep a separate VSCode window open for that purpose.
