### ISSUE TITLE
Cannot add dockerfile to workspace using the extension

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-docker#3553]
Dev Env: WSL2, Windows 11
![image](https://user-images.githubusercontent.com/3619378/175426687-23227b21-19c5-469a-895f-49f67a46d6b9.png)
Docker Desktop for Windows, v 20.10.13
VS Code: 1.68.1
Docker Extension: v1.22.0
C#: v1.25.0

These extensions are all activated in VS Code.

Steps to reproduce:
1. Command Palette -> Docker: Add Dockerfiles to workspace -> .NET: ASP.NET Core -> Linux -> Port:empty
2. Error message
![image](https://user-images.githubusercontent.com/3619378/175427113-2bbd9927-3308-4c84-953e-aae57ede4dc9.png)

**Comment by bwateratmsft** [comment]
Hm, this might actually be coming from the C# extension. I'll take a look.

**Comment by bwateratmsft** [comment]
Yep, looks like this has to be coming from C#. I'll reopen the issue there. We don't have anywhere in source where we're reading a property called `isWindows`, but C# does.
