### ISSUE TITLE
A warning dialog pops up when executing "Open in Browser" action for a running container under a new ACI context

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3554]
**OS:** Win 10
**Build Version:** 20220616.6

**Repro Steps:**
1. Create an Express App and add Dockerfiles to it.
2. Build image for the Dockerfile.
3. Push the Express image to Azure Container registry.
4. Navigate to Express image in registry view -> Right click it and select "Deploy image to Azure Container Instances..." -> Create an ACI context to deploy.
5. Right click the running container (under the new ACI context) and select "Open in Browser".
6. Check whether succeeds to open the Express web page or not.

**Expect:**
Succeed to open the Express web page.
![image](https://user-images.githubusercontent.com/45614674/175486646-4e5ef117-dff1-47be-9fa5-955617222988.png)

**Actual:**
Pop up a warning dialog "No valid ports are available".
![image](https://user-images.githubusercontent.com/45614674/175486632-ca7f078b-aac8-4ba2-9739-ba20eaccb485.png)

**More Info:**
1. This issue also reproduces for Docker Hub registry.
2. Succeed to open the Express web page after switching to the default context and then using back to the new ACI context.

**Comment by bwateratmsft** [comment]
Nevermind, this time I was able to reproduce. The issue appears to be that after the container has started, for at least a few seconds the gRPC daemon returns no IP address for the assigned port. Switching context and returning definitely takes enough time to obtain that port. This could just be a fundamental limitation of the ACI integration...

**Comment by dbreshears** [comment]
Doesn't reproduce 100% of the time.   This is a temporary issue and should resolve in less than 10 seconds.
