### ISSUE TITLE
The extension corrupts the URL to the docker registry, making it impossible to connect.

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [microsoft/vscode-docker#3562]
My registry has a URL without the ending `/v2/` and it works fine and matches `v2`. However, this extension adds `/v2/` to the URL on its own, so I can't connect to my registry. Is it possible to fix this bug? I suppose registry owners may well enter the full URL to their registry and specify the ending `/v2` themselves.

**Comment by bwateratmsft** [comment]
We'll have to investigate. Technically if your registry does not have the `/v2/` endpoint, it is _not_ Registry V2 compliant: https://docs.docker.com/registry/spec/api/#api-version-check

We can't require users to add `/v2/` to the URL; for most users the URL is just a hostname (and if needed, a port).

**Comment by bwateratmsft** [comment]
We've discussed internally and we're going to close this as by-design, however, I did also want to link #869 and #2033. The registry you are using is certainly not the only _mostly_ V2-compliant registry--GitHub Container Registry, Docker Hub, and others are close but not entirely V2-compliant. I have also added a link to this issue in #869.
