### ISSUE TITLE
An error "Timed out waiting for launcher to connect" occurs when debugging a python project on Linux

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3568]
**OS:** Ubuntu22.04
**Build Version:** 20220628.2

**Repro Steps:**
1. Open a python project in VSCode.
2. Add docker files to it -> F5.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/177949118-17aac0b0-c20f-4806-8f86-7117409c765c.png)

**Comment by bwateratmsft** [comment]
This might be related or same as #3514. @v-xinda, was this using Docker Desktop on Linux, or the regular Docker CE?

**Comment by v-xinda** [comment]
@bwateratmsft  Using the Docker Desktop 4.10.1 on Linux when debugging the python project.

**Comment by bwateratmsft** [comment]
Ok, I'm guessing it's probably the same as #3514. Just to check, can you try the workaround in [this comment](https://github.com/microsoft/vscode-docker/issues/3514#issuecomment-1124090485) and see if it works? Thanks!
