### ISSUE TITLE
Couldn't start client Dockerfile Language Server

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-docker#357]
Seems to happen only but always in Insiders when running via F5.

**Comment by StephenWeatherford** [comment]
Thanks, Ramya!

**Comment by StephenWeatherford** [comment]
@PrashanthCorp could you please fix this?  Thanks.

**Comment by PrashanthCorp** [comment]
Have a fix. 

Ran it once, it worked! 

Thanks, @ramya-rao-a
