### ISSUE TITLE
Error on macOS zsh:1: command not found: docker

### ISSUE THREAD

**Issue by alfredoalarcon** [microsoft/vscode-docker#3570]
## OS Information
- **OS**: macOS Monterey (12.4)
- **Extension version**: 1.22.0

## Repro steps
- Open any `docker-compose.yml` on vscode
- Left click on `compose up `
- Get the following error: `zsh:1: command not found: docker`

If I manually run the suggested code 
`docker compose -f "development/docker-compose.yml" up -d --build`
It works perfectly.

I think it is a problem of the path of the console opened by vscode docker extension but I do not understand why it does not recognize docker ?

Thanks for your help

<img width="733" alt="Screenshot 2022-07-09 at 08 49 58" src="https://user-images.githubusercontent.com/24211511/178095091-bc6d9d6c-9d6d-47db-ae6b-5c81c1d5431a.png">

**Comment by bwateratmsft** [comment]
This is due to an annoying issue (see #2578) on Mac where the `PATH` environment variable is not properly populated. You can fix this with the following two VSCode settings:

```json
{
    "docker.dockerPath": "/usr/local/bin/docker",
    "docker.composeCommand": "/usr/local/bin/docker compose"
}
```
