### ISSUE TITLE
container not opening in ubtuntu 

### ISSUE THREAD

**Issue by alec-p-hong** [microsoft/vscode-docker#3575]
Hello, I am very new in coding inside a container environment in Visual studio code. When I try to reopen the repository using the docker file, it errors out. Here is the error log attachment. 

[remoteContainers-2022-07-13T21-27-55.496Z.log](https://github.com/microsoft/vscode-docker/files/9106584/remoteContainers-2022-07-13T21-27-55.496Z.log)

1. I am using the latest version of Docker Desktop 
2. I am using vscode's Docker extension 
3. I am using Ubuntu 22.04 LTS
4. If you want to replicate the environment, the repo is open source. Here is the link to the repository: [https://github.com/alec-p-hong/cactus](url)

I am kind of new to coding in visual studio code in a large repository like this. Can someone help me?

**Comment by karolz-ms** [comment]
@alec-p-hong from the logs you attached it looks like the development container for Hyperledger Cactus quit shortly after starting, and so VS Code was not able to inject itself into it. I would first try to contact the Cactus developers at https://github.com/hyperledger/cactus/issues to see if they have any troubleshooting suggestions.

If you start suspecting it might be VS Code problem, open an issue in https://github.com/Microsoft/vscode-remote-release repo. That repo is for issues related to **developing inside a container**, including "Open folder in container" feature in VS Code. This repo is for the Docker extension, which is about working directly with containers, container images, and container registries. 

Hope this helps!
