### ISSUE TITLE
The new created ACR disappears after refreshing the Azure registries view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3577]
**OS:** Win 10
**Build Version:** 20220713.1

**Repro Steps:**
1. Navigate to Azure registries view -> Create an Azure container registry.
2. Refresh the Azure registries view.
3. Check whether the new created ACR still exists or not.

**Expect:**
The new created ACR still exists.

**Actual:**
The new created ACR disappears.
![test](https://user-images.githubusercontent.com/45614674/179711016-fc6a366b-db3f-4baf-ab55-5eb560638710.gif)

**More Info:**
The new created ACR shows again after refreshing the registries view half hour later.

**Comment by dbreshears** [comment]
Closing due to lower priority.
