### ISSUE TITLE
No running container shows in container view after deploying image to ACI

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3578]
**OS:** Windows 10
**Build Version:** 20220713.1

**Repro Steps:**
1. Right click one image of registries view -> Deploy Image to Azure Container Instances... -> Create a new ACI.
2. Check whether there is a running container in container view or not.

**Expect:**
There is a running container in container view.

**Actual:**
No running container shows in container view.
![image](https://user-images.githubusercontent.com/45614674/179719979-0949a5a8-592f-446f-9929-0283ef7e1238.png)

**More Info:**
Wait 20-30 mins, use other ACT context and switch back to the new ACI context, the running container shows well.
![image](https://user-images.githubusercontent.com/45614674/179720057-9d82e015-9426-486d-ae59-cc16b5d45be2.png)

**Comment by bwateratmsft** [comment]
Closing since we're doing ACA instead with #3535.
