### ISSUE TITLE
Add failures in registry listing to telemetry

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-docker#358]
e.g. this:

        if (loggedIntoAzure) {
            const subs: SubscriptionModels.Subscription[] = this.getFilteredSubscriptions();

            const subPool = new AsyncPool(MAX_CONCURRENT_SUBSCRIPTON_REQUESTS);
            let subsAndRegistries: { 'subscription': SubscriptionModels.Subscription, 'registries': ContainerModels.RegistryListResult }[] = [];
            //Acquire each subscription's data simultaneously
            // tslint:disable-next-line:prefer-for-of // Grandfathered in
            for (let i = 0; i < subs.length; i++) {
                subPool.addTask(async () => {
                    const client = new ContainerRegistryManagement(this.getCredentialByTenantId(subs[i].tenantId), subs[i].subscriptionId);
                    let regs: ContainerModels.Registry[];
                    try {
                        regs = await client.registries.list();
                        subsAndRegistries.push({
                            'subscription': subs[i],
                            'registries': regs
                        });
                    } catch (error) {
                        vscode.window.showErrorMessage(error); <<<<<<<<<<

**Comment by StephenWeatherford** [comment]
Another possibility would be to add error nodes.

**Comment by estebanreyl** [comment]
Ill add these to the telemetry right now. Additionally, I quite like the errorNode idea, you mentioned an azuretreedataprovider in #360 , should we wait until that is added before we add error nodes? I can try adding them in later PR's with the current model as well.

**Comment by StephenWeatherford** [comment]
It'll be easier if we wait, but thanks anyway.  I'd like to handle this in a shared aware across all our extensions if possible.
