### ISSUE TITLE
The executing task is incorrect in terminal window if executing run image command after executing build image command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3580]
**OS:** Windows 10
**Build Version:** 20220713.1

**Repro Steps:**
1. Open an Express app in VS Code and add Docker files to it.
2. Right click the Dockerfile -> Build image.
3. Navigate to the Image view -> Right click the express image and select "Run".
4. Check whether the executing task is correct in terminal window.

**Expect:**
The executing task is correct in terminal window.
![image](https://user-images.githubusercontent.com/45614674/179939815-b5950d0c-2e86-4866-bcee-5928f0edfca5.png)

**Actual:**
The executing task is incorrect in terminal window.
![image](https://user-images.githubusercontent.com/45614674/179939471-7c84e2b8-c9be-4c7f-8d2b-fe23ef9c35ce.png)

**More Info:**
The executing task is right if only executing run image command.

**Comment by bwateratmsft** [comment]
This was done on the PR build for #3555, so could be related to that.

**Comment by bwateratmsft** [comment]
@v-ruizh was this on VSCode Insiders or the main release?

**Comment by v-ruizh** [comment]
@bwateratmsft Verified on the latest main Docker extension build 20220720.11, this issue also **reproduces** in **VS Code Insiders**. It does not reproduce in VS Code.

**Comment by bwateratmsft** [comment]
I am able to reproduce. This is only happening in Insiders and there haven't been changes in Docker in that area lately, so I suspect this must be a VSCode bug. I'll create an issue.

**Comment by bwateratmsft** [comment]
Verified this is fixed on the latest Insiders build.
