### ISSUE TITLE
Cannot change subscription of Azure Registry

### ISSUE THREAD

**Issue by ChrisSidebotham** [microsoft/vscode-docker#3592]
Does this occur consistently?  Yes
Repro steps:

1. Sign into Azure via Docker Registries and select subscription
2. Disconnect Azure Registry 
3. Reconnect Azure Account and subscription selection does not come up

There is no way to disconnect the subscription from the Azure Account meaning I cannot use multiple registries

Version: 1.22.1
OS: win32
OS Release: 10.0.22622
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by bwateratmsft** [comment]
It sounds like you may have subscription filters in place? Can you try doing the command "Azure: Select subscriptions"?

**Comment by ChrisSidebotham** [comment]
Hi Brandon, Thanks - Solved
