### ISSUE TITLE
The remote debugging auto-disconnects immediately on Mac

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3593]
**OS:** M1(Pro)
**Build Version:** 20220726.5

**Repro Steps:**
1. Open a python project in VS Code -> Add docker files to it.
2. Right click **.debug.yml** file -> Compose Up.
3. Open the **launch.json** file -> Add a new "Python Remote Attach" configuration.
4. Navigate to "Run and Debug" view -> Select "Python: Remote Attach" -> F5.
5. Check whether succeeds to remote debug the python project.

**Expect:**
Succeed to remote debug the python project.

**Actual:**
The remote debugging auto-disconnects immediately.

**More Info:**
This issue doesn't reproduce on Windows and Linux.

**Comment by bwateratmsft** [comment]
I was able to test on my Intel Mac, and the issue did not reproduce. I'll see if I can test on M1.

**Comment by philliphoff** [comment]
I was able to make [this Flask-based tutorial](https://github.com/microsoft/python-sample-vscode-flask-tutorial/tree/tutorial) work on my M1 Mac, as well as another FastApi-based sample (with a base image quirk that had a different symptom but was ultimately successful).

@v-xinda If you still repro this issue, it'd be good to attach the Python project source as there's so many different flavors, it makes reproduction difficult.

**Comment by v-xinda** [comment]
@philliphoff  @bwateratmsft   Python project source as below:
[flask_project.zip](https://github.com/microsoft/vscode-docker/files/9204737/flask_project.zip)

**Comment by philliphoff** [comment]
@v-xinda I was able to successfully attach and debug using that sample project on my M1 Mac.  What port were you choosing for running the app/container?  If `5000` (which tends to be the default for Flask), you could end up colliding with an Apple service running on the machine (AirPlay, which uses the same port).

**Comment by v-xinda** [comment]
@philliphoff   The default port is `5002`, but this issue also reproduces if I change the port to `3000` when **remote debugging** the `flask_project` project.

**Comment by bwateratmsft** [comment]
We'll close this for now and see if any customers reproduce it.
