### ISSUE TITLE
Is Docker installed

### ISSUE THREAD

**Issue by Mr-Quinn** [microsoft/vscode-docker#3610]
Does this occur consistently? 
Repro steps:

1. yes
2. starting VSCodium and the Docker extension asks do I want install Docker?

Version: 1.22.1
OS: linux
OS Release: 5.19.0-76051900-generic
Product: VSCodium
Product Version: 1.71.0
Language: en

**Comment by bwateratmsft** [comment]
What do you see if you run `docker -v` in the terminal?

**Comment by Mr-Quinn** [comment]
Docker version 20.10.17, build 100c701 in system terminal.
In VSC it says:
 sh-5.1$ docker -v 
sh: docker: command not found
sh-5.1$

**Comment by bwateratmsft** [comment]
That explains why it cannot detect Docker being installed. I'm guessing that wherever it's installed, it's not on the `PATH` environment variable. Can you try to determine where the Docker executable is, and make sure it's on the `PATH` used by VSCode?

**Comment by Mr-Quinn** [comment]
sh-5.1$ $PATH
sh: /app/bin:/usr/bin:/home/quinn/.var/app/com.vscodium.codium/data/node/bin:/home/quinn/.var/app/com.vscodium.codium/data/cargo/bin:/home/quinn/.var/app/com.vscodium.codium/data/python/bin:/home/quinn/.var/app/com.vscodium.codium/data/gem/ruby/3.1.0/bin: No such file or directory
sh-5.1$

**Comment by bwateratmsft** [comment]
On the system terminal, where `docker -v` works, what do you see for `which docker`? The typical location is `/usr/bin/docker`; `/usr/bin` is indeed on your `PATH`.

**Comment by Mr-Quinn** [comment]
$ which docker
/usr/bin/docker

**Comment by Mr-Quinn** [comment]
docker desktop woks fine...

**Comment by bwateratmsft** [comment]
Do you have any terminal-related settings in place in VSCodium? Something is fundamentally different between system terminals and those in VSCodium. Could be environment, permissions, or other things.

**Comment by Mr-Quinn** [comment]
in .zshrc

[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"

**Comment by Mr-Quinn** [comment]
I just did this but docker has never connected to VSC

**Comment by Mr-Quinn** [comment]
ZSH plugins=(
git
gh
sudo
vscode
docker
ssh-agent
z
colorize
command-not-found
zsh-syntax-highlighting
zsh-autocomplete
common-aliases
)

**Comment by bwateratmsft** [comment]
Is Codium using `sh` as the shell while `zsh` is the one that is set up on the system?

**Comment by Mr-Quinn** [comment]
> Is Codium using `sh` as the shell while `zsh` is the one that is set up on the system terminals that are working?

Apparently it is... How would one change  this?

Thanks for the follow-up.

**Comment by bwateratmsft** [comment]
For the integrated terminal you can run the command "Terminal: Select Default Profile". This will not help with the "Is Docker installed?" prompt though, because the Docker extension is using NodeJS' [`child_process`](https://nodejs.org/api/child_process.html) module, which always uses `/bin/sh` on Unix unless a specific alternative is specified. It looks like `docker` is a plugin on ZSH but I'm not really familiar with how they work. Wherever the `docker` executable is actually installed, would need to be present on the `PATH` environment variable used by `/bin/sh`.

**Comment by Mr-Quinn** [comment]
Good Morning,

Actually Docker is installed on this laptop, [image.png]

The docker plugin is for Oh-My-ZSH and only enables command line functions.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by bwateratmsft** [comment]
I'm not sure why `sh` can't find it, then. The environment variable appears to be set correctly and a full install of Docker would put `docker` in `/usr/bin`. Does the issue persist after restarting VSCode, or a full machine reboot?

**Comment by Mr-Quinn** [comment]
Hello and thank you for all your help... I fixed all issues by completely removing the program from the system, then reinstalling it, again! Now all works as expected, console shows zsh and docker with all containers.
![Screenshot from 2022-09-08 13-22-12](https://user-images.githubusercontent.com/17627616/189219589-de6eaade-5c19-4672-87d5-4abc296c9eda.png)

**Comment by bwateratmsft** [comment]
Great! I'm glad it's working now!

**Comment by Mr-Quinn** [comment]
Yes, it is a constant debacle trying to make it work. I get by using tilix terminal as I am unable to use the integrated terminal to see tilex or zsh integration.

Integration failed is all the info I get... No details.

Michael

Sent from Proton Mail mobile

-------- Original Message --------
