### ISSUE TITLE
Failed to connect. Is Docker running?

### ISSUE THREAD

**Issue by prkaaviya** [microsoft/vscode-docker#3611]
Docker is running with a Minikube container. This is the output of `docker ps` on terminal.
<img width="1895" alt="image" src="https://user-images.githubusercontent.com/65661406/188787466-7e4c6c0a-7d11-4968-9d99-e403d9163f1f.png">
I want to attach to this container `minikube` in VSCode but looks like the extension is not able to load the container. When I do `docker -v`, `docker ps` from terminal inside VSCode, it seems to work as well. 

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/65661406/188787092-d629c204-d5b9-4b69-83e5-c06b733c22b4.png">

But the extension is not able to recognise the running container? Apparently, requests are timing out.

Things I have tried but to no avail:
- Reinstalling Docker extension.
- Reinstalling VSCode

**Docker version** 
20.10.14, build a224086OS
**OS** 
macOS Monterey version 12.4
**VSCode**
Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by prkaaviya** [comment]
I changed to previous versions for extensions Docker -  v1.22.0 and Remote Containers - v0.241.3.

Ran a container with base ubuntu image and it still fails to be recognised by both the extensions.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/65661406/188792651-64d0a552-db4f-45f9-98db-0f77d9eec021.png">
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/65661406/188792862-08c5cd9e-6f20-4a52-8742-ece3dcdf9513.png">

**Comment by bwateratmsft** [comment]
This setup isn't currently supported, but will become supported once we've finished #3263. I'll resolve this as a dupe.
