### ISSUE TITLE
Docker extension provides no visible progress/activity indicator when using `Build Image in Azure...`

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode-docker#3614]
# Issue
I've run through the "Build Image in Azure..." process a number of times and I have never noticed any kind of progress or activity indicator other than the logs in the OUTPUT window.

Unless you are intimately familiar with the normal steps, it makes it quite difficult to determine whether the build is done or there is more work to do and you need to be patient.

# Expected behavior
I expect the OUTPUT window, a notification message, or something to visually indicate that the build is in process and I need to wait.

# Video Repros
https://microsoft.sharepoint.com/:f:/t/JEM/EklDiahGaQtDigc5E2SlrYAB3YU7H2NvdoiyIo1AkQUZ-A?e=eCGRIh

**Comment by bwateratmsft** [comment]
I'll investigate. I thought it was supposed to automatically open the Output window and show the logs, but it's been a while since I've tested this.

**Comment by charris-msft** [comment]
Hey @bwateratmsft  - 
It is automatically opening the Output window, but for someone who hasn't used it much, it's not clear when it's doing work and when it's complete.

**Comment by bwateratmsft** [comment]
Is a toast notification upon job completion more in-line with what you'd expect?

**Comment by charris-msft** [comment]
Commonly, extensions will have a toast notification indicating that an operation is in progress, and then the notification will change when it is done to indicate completion, often with a button to take you to the next relevant place. 

Example of a pretty nice experience:
App Service shows creation progress indication for each step, plus a completion message in the AZURE: ACTIVITY LOG
And a toast notification upon completion that contains a button for the next logical step - in this case `Deploy`
<img width="268" alt="image" src="https://user-images.githubusercontent.com/74415662/191057055-4fb08e16-a53a-4320-97b0-02f597b111d6.png">

Then when clicking the deploy button, there is a toast notification link to view the progress:
![image](https://user-images.githubusercontent.com/74415662/191059372-395c6a56-07fe-4832-aa46-44e3ec9c1cea.png)

When you click the link above you see the progress in the App Service log:
![image](https://user-images.githubusercontent.com/74415662/191059506-bfe38716-28e0-4cba-83d7-57efd4890649.png)

When deployment is finished you get another notification with 3 buttons for the next logical steps - `Browse Website`, `Stream Logs`, `Upload Settings`.

**Comment by bwateratmsft** [comment]
I think that's reasonable and IMO better than just log streaming.

**Comment by dbreshears** [comment]
Nice to have, but closing lower priority
