### ISSUE TITLE
Running kubernetes commands is causing below error

### ISSUE THREAD

**Issue by naman4662** [microsoft/vscode-docker#3619]
Does this occur consistently? 
Repro steps:
Run below command 
1. `kubectl create -f flaskpod.yaml --save-config`

It throws below error although kubectl and all are installed

```
Error: must specify one of -f and -k

error: unknown command "–f flaskpod.yaml"
```
it is not recognizing first parameter although kubectl command is working fine
Version: 1.22.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

**Comment by bwateratmsft** [comment]
@naman4662 did you mean to file this on the [Kubernetes extension](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools)?

**Comment by naman4662** [comment]
No , like in terminals, Gitbash and Powershell are giving this error only cmd terminal is working. @bwateratmsft

**Comment by bwateratmsft** [comment]
In that case did you mean to file it in the [VSCode repo](https://github.com/microsoft/vscode)? This repo is for the Docker extension.
