### ISSUE TITLE
Container/Image explorer user settings do not override workspace settings

### ISSUE THREAD

**Issue by obambrough** [microsoft/vscode-docker#3628]
Docker extension version: v1.22.1
VS Code version: 1.71.2
OS: Mac OS 12.5.1

_Steps to reproduce:_

1. Configure the default Container/Image explorer settings (e.g. docker.images.label) for the workspace.
1. Configure different Container/Image explorer settings for the user

_Expected behaviour:_

User settings should override the workspace settings

_Actual behaviour:_

The opposite, Workspace settings override User settings.

**Comment by bwateratmsft** [comment]
Workspace settings are meant to override user settings, not the other way around. This is a feature of VSCode itself and not specific to the Docker extension. You can read more here: https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence

**Comment by obambrough** [comment]
Wow, I really got that wrong. I don't know how I managed to not realize the settings order of precedence using VS Code after using it for years.
