### ISSUE TITLE
Attach with "docker attach", not "docker exec -it"

### ISSUE THREAD

**Issue by jeanfbrito** [microsoft/vscode-docker#363]
To use binding.pry on Ruby on Rails, I need to access the same console that is already running.
Then, could be added a way to use the command `docker attach containerid` instead of the `docker exec -it` that opens another instance of the shell?
A setting to use it would solve my problem.
![image](https://user-images.githubusercontent.com/1177482/43851299-a774b228-9b10-11e8-968b-38e01cc4fa21.png)

**Comment by PrashanthCorp** [comment]
We open a new instance of the shell for most operations. 
For example, [here](https://github.com/Microsoft/vscode-docker/blob/8aabff1c07d49031361611d8ab7884a33c437e4d/commands/build-image.ts#L108). 

If that is what you want to change, we can log it under another issue.

**Comment by PrashanthCorp** [comment]
We open a new instance of the shell for most operations. 
For example, [here](https://github.com/Microsoft/vscode-docker/blob/8aabff1c07d49031361611d8ab7884a33c437e4d/commands/build-image.ts#L108). 

If that is what you want to change, we can log it under another issue.

**Comment by jeanfbrito** [comment]
No. This can remain this way.
What I need to change is the command executed. Where it is docker exec -it.
I would like to be docker attach.
Opening a new terminal is essential, but I need to attach using another
command.
Maybe a way to adjust the command executed on attach would be a great
solution.
This is a viable feature?

Em qui, 9 de ago de 2018 18:44, Prashanth <notifications@github.com>
escreveu:

**Comment by StephenWeatherford** [comment]
Would it be useful to have a separate  menu item for both, or do you only want one or the other?

**Comment by jeanfbrito** [comment]
For me, Just one is ok.
But there could be the two options.
Something like "container attach" and "container execute interactive".
Then would keep what you call today an attach that is executing something
with an interactive tty AND would have the real attach that just open the
terminal on main tty.

Em qui, 9 de ago de 2018 23:28, Stephen Weatherford (MSFT) <
notifications@github.com> escreveu:

**Comment by StephenWeatherford** [comment]
Decision: provide both, something along these lines:
  Attach via New Shell
  Attach to Running Process

**Comment by bwateratmsft** [comment]
This will be possible as a user setting with #1596. Nevertheless we should investigate changing the default.

**Comment by bwateratmsft** [comment]
Thinking about this; changing the default is probably not a good idea. `docker attach` will attach to the original shell, whereas `docker exec` will create a new one. Arguably it should have always been `docker attach`, but a significant behavioral change could confuse people.

Given that the attach command can be [customized](https://code.visualstudio.com/docs/containers/reference#_command-customization), I'll close this. Command customization is the right option for those who want to use `docker attach`.

**Comment by karolz-ms** [comment]
There is a big difference between "injecting a shell into a running container" vs "attaching to stdin/stdout/stderr of the container's PID 1 process". I think we made the right choice exposing the former. If a lot of users ask for the latter, it should be a separate command.
