### ISSUE TITLE
An exception occurs when debugging a .NET MVC project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3638]
**OS:** Win 10
**Build Version:** 20221010.1

**Repro Steps:**
1. Create a .NET MVC project with "dotnet new mvc" command and open it in VS Code.
2. Add Docker files which include docker compose files to this project.
3. Debug this project with configuration "Docker .NET Core Launch".
4. Check whether succeeds to debug this project or not.

**Expect:**
Succeed to debug this .NET MVC project without any error.

**Actual:**
An exception occurs when debugging the .NET MVC project.
![image](https://user-images.githubusercontent.com/45614674/195035627-e8d7e4e7-9d33-4626-9bd1-0973b0703928.png)

**More Info:**
This issue reproduces with both .NET 6 and .NET 7 rc1.

**Comment by dbreshears** [comment]
@v-ruizh .   Does this reproduce in .NET 7 rc2?

**Comment by v-ruizh** [comment]
Yes, this issue also reproduces in .NET 7 rc2.

**Comment by bwateratmsft** [comment]
I am able to reproduce.

**Comment by bwateratmsft** [comment]
A fix for this issue has been released in Docker extension version 1.22.2.
