### ISSUE TITLE
Fail to build image for Dockerfile with the default image "7.0-focal"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3647]
**OS:** All
**Build Version:** 20221014.1
**.NET Version:** 7.0.100-rc.2.22477.23

**Repro Steps:**
1. Create and open a .NET 7.0 MVC project in VS Code.
2. Add Docker files to this project (Linux Container) -> Right click the "Dockerfile" file -> Select "Build Image...".
3. Check whether succeeds to build image of the "Dockerfile" file.

**Expect:**
Succeed to build image of the "Dockerfile" file.

**Actual:**
Fail to build image of the "Dockerfile" file.
![image](https://user-images.githubusercontent.com/57662131/196079446-ef0870fd-bca0-4b83-a706-2a1d9534bee6.png)

**More Info:**
1. This issue only reproduces with the default Docker image "7.0-focal".
2. This issue does not reproduce with other images "7.0" and "7.0-alpine".
3. This issue does not reproduce for a .NET 6.0 project.

**Comment by bwateratmsft** [comment]
Same as #3512. @dbreshears, do you want to include this in the 1.22.2 servicing update? It's a straightforward, low-risk fix. The workaround the user can do is to take `-focal` off when using .NET 7 previews.

**Comment by dbreshears** [comment]
@bwateratmsft , yes let's fix this in 1.22.2

**Comment by bwateratmsft** [comment]
For posterity, the fix is to stop doing `-focal` with the image name scaffolding. From here on it will just be `:6.0`, `:7.0`, etc.

**Comment by bwateratmsft** [comment]
A fix for this issue has been released in Docker extension version 1.22.2.
