### ISSUE TITLE
Installation of Extension is extremely slow on remote host w/o internet connection

### ISSUE THREAD

**Issue by DDCCCC** [microsoft/vscode-docker#3659]
**when the remote box does not have network connection**, I set the setting **remote.downloadExtensionsLocally** to **true** so that VS Code downloads the VSIXs on the client side and install them on the remote box.
However, **the process of installing the plugin is extremely slow**. The installation of the python plugin takes about 10 minutes, and the installation of the jupyter plugin also takes 4 minutes. I tried to install these two plugins on another remote host with internet connection for about 9s and 4s respectively.

**Comment by DDCCCC** [comment]
https://github.com/microsoft/vscode-docker/issues/3149 Through this answer, I know that remote.downloadExtensionsLocally needs to be configured as true when there is no network connection remotely

**Comment by DDCCCC** [comment]
As shown in the figure, installation of extension is extremely slow on remote host w/o internet connection. **Check the log** (_Ctrl+Shift+p -> show logs -> Remote Server_) and find that each plugin takes about 2 minutes from this step (**_"[remoteagent] [info] Installing the extension without checking dependencies and pack ms-python.vscode-pylance."_**) to the next step. See that the previous information plugin has been downloaded and uploaded locally, **so what operation does not print out in the log take about 2 minutes? Is there any way to shorten the change time?**
![python](https://user-images.githubusercontent.com/23070233/196589025-3213b5be-340f-4cf2-9a3a-e28ca2edbdbd.png)
![jupyter](https://user-images.githubusercontent.com/23070233/196588959-20f4a3f1-5d24-4ada-9a94-6a0bbc717069.png)

**Comment by bwateratmsft** [comment]
@DDCCCC did you mean to file this in the [VSCode repo](https://github.com/microsoft/vscode)?
