### ISSUE TITLE
docker-compose up not used .env file

### ISSUE THREAD

**Issue by gschnellOnera** [microsoft/vscode-docker#3661]
When docker-compose.yml is not in root directory, clic right and docker-compose up, no use the .env file in this directory

**Comment by bwateratmsft** [comment]
Hm, this is an interesting question. Currently, we always use the workspace folder root as the current working directory. IIRC that's where `docker compose` looks for env files--the CWD.

Changing to use the folder containing the compose file would be a breaking change for some users, so we definitely shouldn't do it without careful consideration.

In the meantime, you can use [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) to ensure that the ENV file gets picked up in this workspace.
