### ISSUE TITLE
docker-compose up, multiple containers without debugger.

### ISSUE THREAD

**Issue by iledesmanerd** [microsoft/vscode-docker#3663]
The issue is that when we want to run multiple containers with docker-compose we have a notification pop upd with dialog: 
![Captura de Pantalla 2022-10-21 a la(s) 11 43 29](https://user-images.githubusercontent.com/111795221/197246882-7520f3fb-4856-4c92-8944-f1417d16ae25.png)
But the issue is that no dialog is show again for the others containers. So the compound only runs one container. I try to wait on each compound attachment but this is not doing the difference.

Now if I do one by one we are going to have this debugger on every container because it was installed on the previous. And the compound works without dialog now that every debugger is installed. But I want to install the debugger on every container at ones.

**Comment by bwateratmsft** [comment]
Your best bet is going to be to volume map the debugger into each container you want to attach to. The default-generated `docker-compose.debug.yml` file shows an example of this.

**Comment by iledesmanerd** [comment]
Thanks @bwateratmsft for the quick response. I did all my files manually cause I couldn't run a project on VS so I'm in charge of making this workin on VSCode. I did all the files manually so I cna train myself but this debug.yml file you are pointing is new to me. Will you suggest an exemple please?.

Agin thank you

**Comment by iledesmanerd** [comment]
@bwateratmsft I did what you suggest I add the container on the volumes on my docker-compose and it is working now! thanks

**Comment by bwateratmsft** [comment]
Awesome! Glad it's working now, thanks @iledesmanerd!
