### ISSUE TITLE
Fail to open the web page after deploying image (Express App) to Azure App Service

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3667]
**OS:** Windows 10
**Build Version:** 20221021.9

**Repro Steps:**
1. Right click Dockerfile for Express App-> Build Image.
2. Right click this image in image view -> Push -> Azure -> Select a registry to push.
3. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service.
4. When done, click "Open Site" button in the notification.
5. Check whether the web page can be opened successfully.

**Expect:**
Succeed to open the web page.
![image](https://user-images.githubusercontent.com/45614674/197771769-f864d105-a345-480a-b412-96643877d2f4.png)

**Actual:**
Fail to open the web page with "504.0 GatewayTimeout".
![image](https://user-images.githubusercontent.com/45614674/197771739-a9573a07-0f47-45c0-962a-f485b25ac4f7.png)

**More Info:**
Refreshing the web page can fix this issue.

**Comment by bwateratmsft** [comment]
Potentially just startup delay, since refreshing fixed it. I'll investigate and see if I can reproduce.

**Comment by bwateratmsft** [comment]
I'm able to reproduce but I don't think there's anything we can do about it. It seems to be some delay in Azure starting the website, which is out of our control.
