### ISSUE TITLE
WORKDIR paths should be absolute

### ISSUE THREAD

**Issue by hvignolo87** [microsoft/vscode-docker#3670]
Similar to [this issue](https://github.com/microsoft/vscode-docker/issues/1492) (#1492)

I'm working with version 1.22.2 of the ms-azuretools.vscode-docker extension.

The linter is failing when using a relative path with [WORKDIR instruction](https://docs.docker.com/engine/reference/builder/#workdir). See the image below:

![vscode-docker-bug](https://user-images.githubusercontent.com/205441/197897551-8256df1b-572d-4a34-a5cd-a99a3091e2a8.png)

I'm working in Ubuntu 22.04 on WSL2. More information about my system is below:

Output of `lsb_release -a` command:

```text
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
The output of the `uname -a` command:

```text
Kernel name: Linux 
Kernel release: 5.15.68.1-microsoft-standard-WSL2 
Kernel version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
Machine: x86_64 
Processor: x86_64 
Hardware platform: x86_64 
OS: GNU/Linux
```
The output of the `docker version` command:

```text
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by bwateratmsft** [comment]
This is not a failure, it is a legitimate warning based on Docker Inc's [best practices for the `WORKDIR` statement](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#workdir). You can disable this warning if you wish, by changing the setting `docker.languageserver.diagnostics.instructionWorkdirRelative` to `ignore`:

![image](https://user-images.githubusercontent.com/36966225/198040923-798432e5-11b8-4e70-b3c6-595e1b3ea493.png)

**Comment by hvignolo87** [comment]
Thanks a lot @bwateratmsft! I completely forgot that part of the best-practices document.
Sorry for opening an issue with this little thing 😅
