### ISSUE TITLE
Change the minimum VS Code version that the Docker extension supports

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#3671]
**OS:** Win10
**Build Version:** 20221021.9

**Repro Steps:**

1. Figure out the oldest vs code version that the extension supports, the version is 1.66.0 as below.
![image](https://user-images.githubusercontent.com/107091828/197989859-c72d1695-ceef-4c3e-9333-efa1707b78a0.png)
2. Install VS Code 1.66.2 from https://code.visualstudio.com/updates.
3. Install the Docker extension from VSIX.
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/197989677-21ff87f9-13b5-4c10-88fd-bd5c05463616.png)

**Comment by bwateratmsft** [comment]
Good catch, thanks @v-chenzha!
