### ISSUE TITLE
Use `docker events` to avoid making so many CLI calls

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3674]
When idling on the Docker explorer view, there's a small but noticeable increase in CPU usage, presumably due to all the CLI calls from polling. The `docker events` feature enables us to avoid making unnecessary polling calls. Probably the simplest approach (and what the container tools window in VS does) is to use it just as an event notification, but not actually use the data from the events. This would eliminate the need to poll on a schedule while still keeping the implementation of the current views essentially unchanged.

**Comment by Abuchtela** [comment]
merge

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.
