### ISSUE TITLE
Fail to execute "My Docker Compose Down task" command

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3682]
**OS:** All
**Build Version:** 20221027.4
**Regression:** Previous release

**Repro Steps:**
1. Open a project (such as project "mvc") and add docker files to it in VS Code.
2. Add the following contents in the .vscode/tasks.json (**Update the "services" and "scale" parameters to match services in your docker-compose.yml file**).
```
{
            "type": "docker-compose",
            "label": "My Docker Compose Up task",
            "dockerCompose": {
                "up": {
                    "detached": true,
                    "build": true,
                    "scale": {
                        "mvc": 1
                    },
                    "services": [
                        "mvc"
                    ]
                },
                "files": [
                    "${workspaceFolder}/docker-compose.yml",
                    "${workspaceFolder}/docker-compose.debug.yml"
                ]
            }
        },
        {
            "type": "docker-compose",
            "label": "My Docker Compose Down task",
            "dockerCompose": {
                "down": {
                    "removeVolumes": false,
                    "removeImages": "local"
                },
                "files": [
                    "${workspaceFolder}/docker-compose.yml",
                    "${workspaceFolder}/docker-compose.debug.yml"
                ]
            }
        }
```
3. Execute "Tasks: Run Task" from command palette -> Click "My Docker Compose Up task".
4. Execute "Tasks: Run Task" again from command palette -> Click "My Docker Compose Down task".
5. Check whether succeeds to execute "My Docker Compose Down task" command.

**Expect:**
Succeed to execute "My Docker Compose Down task" command.

**Actual:**
Fail to execute "My Docker Compose Down task" command.
![image](https://user-images.githubusercontent.com/57662131/199197463-5a826c7f-a784-49db-9f54-04bc4e2c17f6.png)

**More Info:**
 This issue also reproduces in Local/Remote Codespaces environment.

**Comment by bwateratmsft** [comment]
Due to https://github.com/microsoft/vscode-docker-extensibility/issues/126
