### ISSUE TITLE
Connect to GitHub

### ISSUE THREAD

**Issue by waltiam** [microsoft/vscode-docker#3686]
Type: <b>Feature Request</b>

There is no clear way to connect to GHCR - there was a ticket /  feature request open on this  ( #2735 ) but it was closed over a year ago as fixed.  

Am i missing some magic sauce that is needed to make this work?

Extension version: 1.22.2
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-52-generic

**Comment by bwateratmsft** [comment]
#2735 wasn't really about GitHub Container Registry, rather generic registries. GHCR support is tracked in #869; I will dupe this issue to that and add a +1 to GHCR.
