### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by anon4K** [microsoft/vscode-docker#3688]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:332:326003
module.exports.resolveDebugConfiguration.s.callWithTelemetryAndErrorHandling extension.bundle.js:332:325823
Object.<anonymous> extension.bundle.js:1:479348
module.exports.n extension.bundle.js:1:477440
module.exports.n extension.bundle.js:1:477217
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:479267
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:332:325754
_.<anonymous> extensionHostProcess.js:618:886
o extensionHostProcess.js:13:454
```

</details>

**Comment by bwateratmsft** [comment]
@anon4K you are using a very old version of VSCode and the Docker extension. I'd recommend updating them both to the latest and trying your scenario.
