### ISSUE TITLE
Current docker context name in status bar

### ISSUE THREAD

**Issue by khssnv** [microsoft/vscode-docker#3690]
Hello. This is a feature request.

Is it possible to add an optional field with Docker context name to the Status bar?

It is convenient to inspect and update compose stacks and swarm clusters by switching Docker context. But user should keep in mind which context is active currently to not mess it up.

Now the current context is shown in "contexts" section of the Docker Explorer tab Side bar only.
![image](https://user-images.githubusercontent.com/833019/200756153-1d80b916-f12a-4c01-80bc-beda032c5890.png)

But it would be helpful to have an option to add a current context name in the status bar as well. Status bar looks like a suitable place for the context name because it is already possible to add remote machine name, current VCS branch name or DB connection name to the status bar with other plugins.
![image](https://user-images.githubusercontent.com/833019/200757780-64ffc70a-7f7c-4b4a-912e-85bb5b665efb.png)

**Comment by bwateratmsft** [comment]
I like this idea. In fact I might like it better than the existing Contexts tree view. :smile:

**Comment by alexyaang** [comment]
@khssnv  This has now been released in Docker extension version 1.26.0. You can enable the status bar item by: 

1. Going to VSCode Settings -> Docker Settings
2. Navigate to the setting `Docker › Contexts: Show in Status Bar` 
3. Check the checkbox and close the setting page
4. You should see the current Docker context in the left corner of your status bar 

> <img width="199" alt="image" src="https://github.com/microsoft/vscode-docker/assets/59073590/f9a3481d-3b7e-44d5-8ac7-57336ff34582">

You can switch context by clicking on the status bar. 

> <img width="671" alt="image" src="https://github.com/microsoft/vscode-docker/assets/59073590/c2f57656-878a-4269-b555-6a11bf669dbf">
