### ISSUE TITLE
Images tree reports "(Out of date)" but pull says "up to date"

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-docker#3696]
Type: <b>Bug</b>

Similar to #2730.

![image](https://user-images.githubusercontent.com/6726799/201642944-6a560a37-dbd8-493a-a835-9c8b4ec475ba.png)

I am using the tree filter above but first had to use the gearwheel to set the label as "FullTag". But the problem also exists when Docker Explorer configuration for Images view is reverted to its default.

Extension version: 1.22.2
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Connection to 'codespaces+gjsjohnmurray-microsoft-vscode-jupyter-gw5xwxgrjg2pwv9' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.52GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/JohnM/Documents/GitHub/intersystems-community/vscode-iris-jupyter-server --enable-proposed-api intersystems-community.vscode-objectscript|
|Screen Reader|no|
|VM|0%|

Connection to 'codespaces+gjsjohnmurray-microsoft-vscode-jupyter-gw5xwxgrjg2pwv9' could not be established
</details>

**Comment by bwateratmsft** [comment]
@gjsjohnmurray can you right click each of those images and do "Inspect", and paste the JSON output?

**Comment by bwateratmsft** [comment]
Actually, nevermind. I'm able to reproduce right now for the same image. I need to sync with some MCR folks; it is behaving differently from Docker Hub in certain significant ways.

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.
