### ISSUE TITLE
Compose - Don't prompt if only one yml file in CWD

### ISSUE THREAD

**Issue by Sub-Xaero** [microsoft/vscode-docker#370]
Possibly the same feature request as #223, but relating to workspaces which contain a single compose file.

If your project contains only a single `docker-compose.yml` file, could the extension please default to just running compose against that file, instead of prompting for which file you want to run. 

This is by far my favourite VSCode extension, but it's very annoying that every time I have to run a compose command via the command palette, that I have to endure 2 levels of prompting before the command runs. This would be a nice quality of life improvement for many small projects.

**Comment by bwateratmsft** [comment]
Hey @Sub-Xaero, the fix is now available in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).

**Comment by Sub-Xaero** [comment]
@bwateratmsft Amazing! Thank you! This is such a quality of life fix.
