### ISSUE TITLE
The volume disappears more than 20 seconds after click "Prune..." button

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3704]
**OS:** All
**Build Version:** 20221116.1
**Regression:** Previous release 1.22.2

**Repro steps:**
1. Run `docker volume create vol1`.
2. Navigate to "Volumes" view -> Click "Prune..." button.
3. Check whether the volume disappears within 5 seconds.

**Expect:**
The volume disappears within 5 seconds.

**Actual:**
The volume disappears more than 20 seconds.

**Comment by bwateratmsft** [comment]
Turns out "prune" isn't even listed in the [docs](https://docs.docker.com/engine/reference/commandline/events/), so that's nice.

**Comment by bwateratmsft** [comment]
After further investigation, it turns out that pruning containers, images, and networks all result in `destroy` / `delete` events being fired in addition to the prune event. Only volumes lack these `destroy` events. Simplest fix is to just add `prune` to the volume events being listened to.
