### ISSUE TITLE
The created time doesn't show next to the volume after selecting "CreatedTime"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3705]
**OS:** All
**Build Version:** 20221116.1
**Regression:** Previous release 1.22.2

**Repro steps:**
1. Run `docker volume create my7`.
2. Navigate to "Volumes" view -> Click "Configure Explorer..." button -> Description -> Select "CreatedTime".
3. Check whether the created time shows next to the volume.

**Expect:**
The created time shows next to the volume.
![image](https://user-images.githubusercontent.com/57662131/202644995-93910b3d-3f4d-4312-804a-9849cb3b34bd.png)

**Actual:**
The created time doesn't show next to the volume.
![image](https://user-images.githubusercontent.com/57662131/202646135-d2499cd4-3172-4d39-88c7-95d3a08a0dde.png)

**More Info:**
This issue doesn't reproduce after selecting "VolumeName".

**Comment by bwateratmsft** [comment]
Looks like the Docker CLI does not return the created time, so there's nothing we can do about that. We should remove 'time' as an option in the Volumes label/sort/etc.

**Comment by bwateratmsft** [comment]
I created https://github.com/docker/cli/issues/3871 as an upstream issue. I'd really prefer to have `CreatedAt` be a property that exists on the volumes, it's awkward to remove it from the tree view options.

**Comment by dbreshears** [comment]
Closing this since external and blocked
