### ISSUE TITLE
Fail to add docker files to the .NET projects

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#3709]
**OS:** Win10
**Build Version:** 20221116.1

**Repro steps:**

1. Create a .NET MVC project with `dotnet new mvc` command and open it in VS Code.
2. F1 -> Select "Add Docker Files to Workspaces..." -> Select ".NET: ASP.NET Core" -> Select "Linux" -> Enter.
3. Check whether the next step is "Include optional Docker Compose files?".

**Expect:**
The next step is "Include optional Docker Compose files?".

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/203023143-1f82f12d-6f1a-4568-b974-32a3ec3aff33.png)

**More Info:**
1. The issue also reproduces when adding docker files to a .NET Core console project.
2. This issue does not reproduce on Linux and Mac.

**Comment by karolz-ms** [comment]
I cannot reproduce the issue. 😑 At least not on my Win 11 machine. I do not have access to a Win 10 machine at the moment, but I would be surprised if the OS version made a difference. 

The process that is launched between the OS/port selection and the "Include optional Compose files?" question is `dotnet build`, with a custom target.  The code is here:  https://github.com/microsoft/vscode-docker/blob/main/src/utils/netCoreUtils.ts#L17

@v-chenzha 
1. Can you verify that you can `dotnet build` the project from command line, after step 1?
2. Can you try to repro the issue on a different machine and/or Win 11 machine?

**Comment by v-chenzha** [comment]
@karolz-ms 
1. Succeed to build the project on windows 10. This issue doesn't exist after executing `dotnet build` command.
2. This issue only reproduces on windows 10, it doesn't reproduce on Windows 11.
3. This issue is unstable; it is easy to reproduce on new windows 10 machines.

**Comment by karolz-ms** [comment]
@v-chenzha I tried on a freshly set up Windows 10 machine with .NET SDK version 7.0.100 installed, extension build 20221116.8, and I cannot reproduce the issue. What version of .NET are you using (provide output of `dotnet --version` please).

**Comment by v-chenzha** [comment]
@karolz-ms 
Today I create two new windows 10 machines, we can reproduce this issue on one machine, but can't reproduce it on the other one. This is an unstable issue.

This is my dotnet version:
![image](https://user-images.githubusercontent.com/107091828/203485562-a3c84bc7-e8c7-4056-b30a-81ce60eda4c9.png)

**Comment by karolz-ms** [comment]
@v-chenzha thank you for sharing the repro machine with me.

I figured out what was going on. The repro VM has only 8 GB of RAM and was almost out of disk space. The machine is so overstressed that `dotnet build` command regularly times out (cannot complete within allocated 10 seconds).
