### ISSUE TITLE
Volumes in Docker Explorer

### ISSUE THREAD

**Issue by Sub-Xaero** [microsoft/vscode-docker#373]
The Docker explorer is a wonderful tool, but it is missing the ability to be able view and administrate the Docker Volumes that are present on the system.

**Comment by StephenWeatherford** [comment]
Was wondering if anyone would ask for that... :-)

**Comment by Sub-Xaero** [comment]
Haha, sorry, hope I haven't given you a horrendous task.

**Comment by StephenWeatherford** [comment]
Programming is fun!  :-)

We will have to prioritize it against other features, of course.

**Comment by Sub-Xaero** [comment]
Of course :)
