### ISSUE TITLE
Erorr: Template parsing error: template:1:194: executing " at <.State>: can't evaluate feld State in type *formatter.containerContextd

### ISSUE THREAD

**Issue by wodrow** [microsoft/vscode-docker#3733]
![image](https://user-images.githubusercontent.com/7815635/204744921-92ddc5e4-e3ea-4840-9b82-3c75b40944a5.png)

how to slove it?

```html
Failed to connect. Is Docker installed and running?
Erorr: Template parsing error: template:1:194: executing " at <.State>: can't evaluate feld State in type *formatter.containerContextd
```

**Comment by cocolato** [comment]
Same problem in version v1.23.0,  demoted to v1.22.2 fixed.

**Comment by wodrow** [comment]
![image](https://user-images.githubusercontent.com/7815635/204755996-1e74000e-75e9-4b24-99a9-1f1274aaec35.png)
I use v1.73.1
should me must rollback to v1.22.2?

**Comment by cocolato** [comment]
> ![image](https://user-images.githubusercontent.com/7815635/204755996-1e74000e-75e9-4b24-99a9-1f1274aaec35.png) I use v1.73.1 should me must rollback to v1.22.2?

I mean docker extention version.

**Comment by wodrow** [comment]
![image](https://user-images.githubusercontent.com/7815635/204756565-aad242cb-ad40-42be-9452-d90e48189115.png)
this is my docker version

**Comment by cocolato** [comment]
> I mean docker extention version.

Check your vscode docker extension version.

**Comment by cocolato** [comment]
> Check your vscode docker extension version.

Check your vscode docker extension version.

**Comment by cocolato** [comment]
> ![image](https://user-images.githubusercontent.com/7815635/204756565-aad242cb-ad40-42be-9452-d90e48189115.png) this is my docker version

Check your vscode docker extension version.

**Comment by wodrow** [comment]
good solution
i have sloved id by rollback vscode docker extension to version 1.22.2
thanks

**Comment by ShiquanYu** [comment]
Same problem, is there any way to solve this problem except rollback vsc version?

**Comment by giahung24** [comment]
Since there is already an issue for this problem #3724 , I suggest you to follow there

**Comment by bwateratmsft** [comment]
As @giahung24 notes this is a duplicate of #3724. These are older versions of Docker Engine / Docker Desktop, and updating them would fix the issue. We are working on a fix to make the code more resilient to the lack of this `State` field on container JSON, but it's going to require a fair bit of work, since we have to change the output format considerably. It would be easier if Go wasn't so frustrating about templating...
