### ISSUE TITLE
Python Version bump to Python 3.10

### ISSUE THREAD

**Issue by kjaymiller** [microsoft/vscode-docker#3736]
Python 3.11 is out and the default object passed is Python 3.8. While I'm not sure if 3.11 is the right move. Bumping the python version from 3.8 to 3.10 seems reasonable.

**Comment by bwateratmsft** [comment]
Yeah, I think a bump to 3.10 (or maybe even 3.11) is totally reasonable. Both branches are in "bugfix" [support status](https://devguide.python.org/versions/) and in-support for several more years.

**Comment by bwateratmsft** [comment]
While we're in the area, we may as well bump the versions of Django / FastAPI / Flask / etc. in the `requirements.txt.template` file.

**Comment by danegsta** [comment]
We've just shipped version 1.24.0 of the extension with the relevant change for this.
