### ISSUE TITLE
Add placeholder to the prompted textbox when logging in docker hub

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#374]
Repro Steps:
1. Make sure doesn't log into docker hub.
2. Expand 'Docker Hub' node under 'Registries'.
3. Check the propmpted textbox of usernasme and password.

Expect:
Display a placeholder like 'Please login in docker hub with your username and password'.

Actual:
No placeholder displays.
![placeholdewr](https://user-images.githubusercontent.com/34729022/44135354-453e71f0-a058-11e8-8807-12ebabc26108.png)

**Comment by StephenWeatherford** [comment]
We don't want a placeholder, but we do want a better prompt.
