### ISSUE TITLE
The "--rm" doesn't appear in the log when building a Dockerfile

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#3741]
**OS:** All
**Build Version:** 20221129.11

**Repro steps:**
1. Open a project in VS Code -> Add docker files to it.
2. Open the setting.json --> Add the setting of "docker.commands.build" with the default value.
3. Execute "Build Image...".
4. Check whether the "--rm" appears in the log.

**Expect:**
The "--rm" appears in the log.
![image](https://user-images.githubusercontent.com/57662131/205022339-7a437f88-af7a-43f5-81ef-cb76cf7b34bc.png)

**Actual:**
The "--rm" doesn't appear in the log.
![image](https://user-images.githubusercontent.com/57662131/205023364-1ea87f40-2096-4fb4-a6fa-eb90955c893f.png)

**Comment by bwateratmsft** [comment]
Is there a `docker-build` task in `.vscode/tasks.json`? If so, we intentionally do that task instead of the command in `docker.commands.build` when right-clicking -> build on the Dockerfile.

**Comment by v-xinda** [comment]
@bwateratmsft There is a `docker-build `task in `.vscode/tasks.json` file, as below:
```
                   {
			"type": "docker-build",
			"label": "docker-build",
			"platform": "node",
			"dockerBuild": {
				"dockerfile": "${workspaceFolder}/Dockerfile",
				"context": "${workspaceFolder}",
				"pull": true
			}
                  }
```
 So this is by design that the log in the Terminal window is inconsistent with the defualt value of the `docker.command.build` when right-clicking -> build on the Dockerfile.

**Comment by bwateratmsft** [comment]
Yes. If you comment out or remove that `docker-build` task, it should use the setting in place for `docker.command.build`.

**Comment by v-xinda** [comment]
@bwateratmsft Thanks, I Got it, so close it.
