### ISSUE TITLE
not work in remote machine docker

### ISSUE THREAD

**Issue by lazyZhou1997** [microsoft/vscode-docker#3742]
I run vscode in remote machine's docker. This extension not works since 1.23.0(include 1.23.1).
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/22818425/205363043-50c44858-cc2b-4ab8-82e7-720530deb3dd.png">

It works well in 1.22.2.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/22818425/205363471-ac67f8c1-be06-473a-8b16-25ec08e05eb3.png">

**Comment by bwateratmsft** [comment]
Looking at that error message, this is likely the same as #3724.
