### ISSUE TITLE
connot list any container info

### ISSUE THREAD

**Issue by bigdaronlee163** [microsoft/vscode-docker#3746]
Type: <b>Bug</b>

connot list any container info

Extension version: 1.23.1
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 4.15.0-142-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.35GB (21.23GB free)|
|Process Argv|--unity-launch --crash-reporter-id e5e45115-0783-4857-9b3b-d52cdcf487c6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by bigdaronlee163** [comment]
Rolling back to the extension version v1.21.9 solves the issue for me.

**Comment by bwateratmsft** [comment]
@bigdaronlee163 Was there an error shown in the container window? If so what was it?

**Comment by alanyu9857** [comment]
Same problem here it happen since v1.23

**Comment by withSunday** [comment]
![Uploading temp_1.png…]()

**Comment by bwateratmsft** [comment]
@withSunday your issue is the same as #3724

**Comment by davidarchanjo** [comment]
Hi guys,
Just to let ya know. I faced the same issue with version `1.23.1` as reported, i.e. not listing of running containers, images, network etc. As a workaround, I rollback to version `1.22.2` and everything came back to work. I'm running on a Ubuntu 20.04.5 LTS x86_64 kernel 5.14.0-1054-oem

**Comment by eyosias-k-negash** [comment]
> Hi guys, Just to let ya know. I faced the same issue with version `1.23.1` as reported, i.e. not listing of running containers, images, network etc. As a workaround, I rollback to version `1.22.2` and everything came back to work.
> 
> OS: Ubuntu 20.04.5 LTS x86_64 5.14.0-1054-oem Docker: 20.10.17, build 100c70180f

Issue Persists. The same workaround works out.
```
docker:
Version:           20.10.22
...
OS/Arch:           linux/amd64
```
![image](https://user-images.githubusercontent.com/24894119/209572241-f6aa73c2-c822-41d3-8d03-01e62fffaa60.png)

**Comment by bigdaronlee163** [comment]
> @bigdaronlee163 Was there an error shown in the container window? If so what was it?
same as 
![image](https://user-images.githubusercontent.com/49524138/210030611-7d2440ce-e48a-459b-82f0-5addf3bad97c.png)

**Comment by eyosias-k-negash** [comment]
No. it kept loading. It rarely finished loading but soon as a refresh is
triggered for some reason it loads for a while all over again.

**Comment by bwateratmsft** [comment]
@bigdaronlee163 it looks like your issue is the same as #3724, so I'll duplicate this to that.

@eyosias-k-negash it sounds like your issue is the same as #3779.
