### ISSUE TITLE
The Docker extension can't resolve the private registry image

### ISSUE THREAD

**Issue by evanjack2002** [microsoft/vscode-docker#3749]
Type: <b>Bug</b>

Hi Sir,

The Docker extension can't resolve the private registry image. 
ex.  myhub:5000/helloworld:1.0.0
It will appear "Failed to connect. Is Docker installed?" in the IMAGES.

Please help me, thanks.

Extension version: 1.23.1
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19041
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-56-generic
Remote OS version: Linux x64 5.15.0-56-generic
Remote OS version: Linux x64 5.4.0-131-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.53GB free)|
|Process Argv|--crash-reporter-id ddc9bde8-040c-4d05-80c3-684035728821|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: u18|
|OS|Linux x64 5.15.0-56-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (56 x 2100)|
|Memory (System)|62.79GB (46.12GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: u18|
|OS|Linux x64 5.15.0-56-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (56 x 2100)|
|Memory (System)|62.79GB (46.12GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: u20-1|
|OS|Linux x64 5.4.0-131-generic|
|CPUs|Intel Xeon Processor (Cascadelake) (24 x 2100)|
|Memory (System)|31.36GB (29.95GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
cc2-nonfim-prod:30622702

```

</details>

**Comment by bwateratmsft** [comment]
Likely the same as #3739 so I will dupe this to that.
