### ISSUE TITLE
The logged docker hub isn't auto removed after clicking 'Docker Hub Logout' 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#375]
Repro Steps:
1. Expand 'Docker Hub' under 'Registries' -> Enter your username and password into the prompted textbox.
2. After logging in successfully, right click 'Docker Hub' then click 'Docker Hub Logout'.
3. Check whether the logged docker hub is removed or not.

Expect:
The logged docker hub is auto removed.

Actual:
The logged docker hub isn't auto removed.

**Comment by StephenWeatherford** [comment]
#429
