### ISSUE TITLE
The "copy debugger" notification still pops up when running 'Docker .Net Core Attach (Preview)' configuration again

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3758]
**OS:** All
**Build Version:** 20221206.1
**Regression:** Previous Release

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code -->
 F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
3. Right click the docker-compose.yml --> Select "Compose Up".
4. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
5. Run the above configuration, select the running container from step4 and click **yes** in the below notification to copy the debugger on the container.
![image](https://user-images.githubusercontent.com/45614674/206410147-45d07d84-d3b5-4c56-b037-48e7a91ae803.png)
6. Stop debugging.
7. Debug again and select the running container.
8. Check there shouldn't be any "copy debugger" notification.

**Expect:**
There shouldn't be any "copy debugger" notification.

**Actual:**
The "copy debugger" notification pops up again.
![image](https://user-images.githubusercontent.com/45614674/206411127-884858a4-40a5-443a-a3e5-c2128fd3f08f.png)

**More Info:**
This issue does not reproduce on the previous released Docker extension 1.23.1.

**Comment by bwateratmsft** [comment]
Need to make sure that the changes to shell quoting / running without a shell / etc. didn't cause this.

**Comment by bwateratmsft** [comment]
This is occurring because of Docker's reparsing of arguments. The latter half of the `docker exec` script is being ripped off, causing a syntax error that leads the extension to believe the debugger is never installed.

**Comment by bwateratmsft** [comment]
Because Docker is reparsing the arguments, it's tearing apart all the scripts we give to `docker exec`. Either we need to always run those through a shell, or we need to do some hard quoting similar to what we did for the JSON format arg.
