### ISSUE TITLE
$ sudo systemctl disable --now docker.service docker.socket

### ISSUE THREAD

**Issue by Ryoyip** [microsoft/vscode-docker#3762]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.23.1
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.74.0
Language: zh-tw

**Comment by bwateratmsft** [comment]
@Ryoyip can you share repro steps or describe what's going wrong?
