### ISSUE TITLE
[GitHub Codespaces] No web page opens when debugging Python (Flask) project

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#3768]
**OS:** Remote Codespaces
**Build Version:** 20221212.12

**Repro Steps:**

1. Open a python project (Flask) and add docker files to it in VS Code.
2. Debug this project with configuration "Docker: Python - Flask".
3. Check whether debug successfully and open a web page.

**Expect:**
Debug python (Flask) project successfully with the web page opens.

**Actual:**
It keeps debugging state without any web page opens.

**More Info:**
This issue does not reproduce in Local Codespaces environment.

**Comment by bwateratmsft** [comment]
I was able to debug a flask app successfully, but I had to apply two workarounds--

1. Work around #3823 by selecting the pre-release Python extension version (this shouldn't be necessary for much longer)
2. The browser notified me about a blocked popup--it was blocking the tab opened to browse to the web app. This is not something we can do anything to change.
