### ISSUE TITLE
Error: Invalid container JSON

### ISSUE THREAD

**Issue by nvablaest** [microsoft/vscode-docker#3773]
Does this occur consistently? Yes

Docker PS shows that service and containers are running but VS code extension fails to connect: Error: Invalid container JSON

Version: 1.23.2
OS: linux
OS Release: 5.4.0-135-generic
Product: Visual Studio Code
Product Version: 1.74.0
![Screenshot 2022-12-14 091920](https://user-images.githubusercontent.com/70451571/207542875-2db460c8-e943-439c-b187-2270a7cc6aa0.png)

Language: en

**Comment by chopinx** [comment]
I have the same problem, have you found the solution?

**Comment by chopinx** [comment]
I rollback to v1.20.0, and it works. I guess this problem occurs in the latest version.

**Comment by nadar** [comment]
Same

**Comment by bwateratmsft** [comment]
Dupe of #3724

**Comment by Andry30** [comment]
I rollback to v1.22.2 and it works

**Comment by cilence** [comment]
I rollback to v1.22.2 and it works

**Comment by jvoinot** [comment]
I have the same problem with the latest version v1.23.3.
I rollback to v1.22.2 and it works.

**Comment by JustinGrote** [comment]
Same problem for me, in my case I was using podman. Was there a breaking change in JSON format?

**Comment by bwateratmsft** [comment]
Podman's JSON objects are in a slightly different format. We're working on a solution for it, #3241.
