### ISSUE TITLE
There are redundant logs when executing "Compose Up" action in Django project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3778]
**OS:** Ubuntu 22.04
**Build Version:** 20221214.2

**Repro Steps:**
1. Open a **Django** project in VS Code.
2. Add Docker files including compose files to this project.
3. Right click "docker-compose.yml" file and execute "Compose Up" action.
4. Check the logs in Terminal window.

**Expect:**
There are no redundant logs in Terminal window.

**Actual:**
There are redundant logs in Terminal window.
![image](https://user-images.githubusercontent.com/45614674/208092776-9d632853-a9f5-4f09-85ad-7c98d1f2453f.png)

**More Info:**
1. This issue does not reproduce for Flask project.
2. This issue does not reproduce on Windows.

**Comment by bwateratmsft** [comment]
Probably some oddity about `Pseudoterminal` that is out of our control...in any case, would not block 1.23.3.

**Comment by dbreshears** [comment]
Won't fix for now

**Comment by bwateratmsft** [comment]
Since this is running in a regular terminal, it would be from Docker Compose' output. It might be that the terminal window is too narrow.
