### ISSUE TITLE
unauthorized: aad access token with sp failed client id must be guid Azure push

### ISSUE THREAD

**Issue by jkesterabns** [microsoft/vscode-docker#3780]
Pushing containers to my azure container registry no longer works. It had worked without issue for months, and now all of a sudden I get: unauthorized: "aad access token with sp failed client id must be guid" when I try to push my image. My Azure registry shows up in code along with all of my images.

**Comment by danegsta** [comment]
@jkesterabns that error should indicate a permission issue either with your Service Principal or ACR instance. Have you rotated a Service Principal credential (or do you have a Service Principal credential set to expire) that you were using to login to ACR via Docker? If so, you may need to update your Service Principal secret, your Docker login credentials, or both.

**Comment by jkesterabns** [comment]
Where do I set my docker login credentials? Usually it just asks me to log in via web pop up when I attempt to push. I haven't changed any thing in azure. I have been looking through the access control area in the containerRegistry in azure, but i have nothing configured there.

**Comment by jkesterabns** [comment]
I just ran az acr login --name myregistry which said it succeeded, then tried a push and it worked.... not sure what was going on there, but looks like it took care of itself.

**Comment by danegsta** [comment]
If you try to push from the command line `docker image push <acrimage>` does that succeed? Additionally, can you try running the `>Docker Registries: Log In to Docker CLI` command from the command pallet to force authentication to the ACR registry and see if you get the same error?

I'd also recommend disconnecting and reconnecting your Azure Registry node from the registries pane, as well as logging out and logging back into Azure via the command pallet (`Azure: Sign Out` followed by `Azure: Sign In`).

**Comment by danegsta** [comment]
Just saw you'd already resolved, so disregard my follow up message. I'm assuming a bad token got cached for you for some reason and wasn't being repopulated. Glad you were able to get things working again.

**Comment by danegsta** [comment]
Closing this out since you were able to get unblocked.
