### ISSUE TITLE
Failed to connect. Is docker running?

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode-docker#3784]
Does this occur consistently?  Yes
Repro steps:

1. `docker ps` executes successfully however the image fails to show up on the left bar as seen below. 
2. I am connected to a remove machine via ssh. 

Action: vscode-docker.containers.prune
Error type: 1
![Screenshot 2022-12-21 at 16 48 18](https://user-images.githubusercontent.com/60148725/208959521-1a4e35e7-c446-4904-914c-909725079673.png)

Error Message: Got permission denied while trying to connect to the Docker daemon socket at redacted:url Post "redacted:url dial unix /var/run/docker.sock: connect: permission denied

Version: 1.23.3
OS: linux
OS Release: 5.15.0-52-generic
Product: Visual Studio Code
Product Version: 1.74.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:3895677
```

</details>

**Comment by danegsta** [comment]
@zohimchandani Can you confirm if `docker ps` works when run from a VS Code terminal instance?

**Comment by danegsta** [comment]
Also, to make sure of the specific environment you're running in, are you using the VS Code SSH Remote Development extension or are you manually setting up an SSH tunnel to a Docker engine socket on a remote machine?

**Comment by zohimchandani** [comment]
I am ssh'ing into a remote unix machine from my Mac via VS code. 

I have got the docker extension installed and enabled on my ssh. 

```
zchandani@ipp5-03762:/$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
```

`docker ps` was working yesterday and I did see the `hello` output however its been hit and miss to get it to work.

**Comment by danegsta** [comment]
If you run `sudo docker ps` from a VS Code terminal after connecting to the remote machine, does that work?

**Comment by zohimchandani** [comment]
```

zchandani@ipp44:/mnt/abcd/qgans$ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS       PORTS                               NAMES
8627efc5525f   docker/getting-started   "/docker-entrypoint.…"   12 days ago   Up 12 days   0.0.0.0:80->80/tcp, :::80->80/tcp   magical_bouman

```

**Comment by zohimchandani** [comment]
Below is a couple more snippets which may help diagnose the issue: 

```
zchandani@ipp44:/mnt/abcd/qgans$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

```

```
zchandani@ipp44:/mnt/abcd/qgans$ sudo docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4

```
```
zchandani@ipp44:/mnt/abcd/qgans$ docker run -it ubuntu bash
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```


![Screenshot 2023-01-03 at 12 05 33](https://user-images.githubusercontent.com/60148725/210354047-de2e2914-e3aa-41f9-ba04-7ac21f5008bc.png)

**Comment by zohimchandani** [comment]
`killall node` solved the issue. Thanks.
