### ISSUE TITLE
Images are not being listed - invalid filter 'dangling'

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode-docker#3787]
Installed the lates build from [Dec 22](https://github.com/microsoft/vscode-docker/commit/8e591b8634583af0a0a3dc1f60015cb8bdab6d83) and receive this error when Docker extension tries to load the images panel:

```console
Failed to connect. Is Docker running?
    Error: Error response from daemon: invalid filter 'dangling'
```

![image](https://user-images.githubusercontent.com/11204251/209453212-a333aa16-a3ba-44c0-bb19-a9a6e7689977.png)

From the terminal in VS Code Insiders docker commands show images and containers:

![image](https://user-images.githubusercontent.com/11204251/209453274-dd32ac70-e931-4451-b5f0-cc1c1777b25f.png)

**Comment by danegsta** [comment]
@wsmelton can you run the command `docker version` from your terminal and share the results? I'm suspicious based on the error that you're on version 18.09 of Docker or earlier as the "dangling" filter option was added in 19.03.

As a short term workaround, you may also try clicking the "eye" icon on the images tree view pane (it will have hover text "show dangling images") as that will turn off the dangling images filter.

![image](https://user-images.githubusercontent.com/50252651/209862181-48ddf25f-0c06-4fa8-a223-2433f2c9a2bc.png)

**Comment by wsmelton** [comment]
Confirm togging the eye does indeed list the images:
![image](https://user-images.githubusercontent.com/11204251/209862923-bd4dd083-d380-4d79-9510-beeb293931e6.png)

Here is the `docker version` output:

```console
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          22.06.0-beta.0-902-g2708be0db4.m
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.18.4
  Git commit:       2708be0db4
  Built:            Wed Nov 23 09:33:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by danegsta** [comment]
That's actually not at all what I expected from the version output... looks like your Docker engine version is on the beta release of 22.06 instead of the current 20.10. Can you try running `docker image ls --filter dangling=false` from the command line and see what output you get?

**Comment by danegsta** [comment]
I found a [similar error](https://github.com/docker/cli/issues/3825) reported in the Docker CLI github issues. Have you enabled the experimental [containerd image management feature](https://www.docker.com/blog/extending-docker-integration-with-containerd/)?

**Comment by wsmelton** [comment]
Yes, I have the containderd beta feature enabled on the desktop config
![image](https://user-images.githubusercontent.com/11204251/209886042-0b4778ed-0d39-41dc-b23e-c8f81c47deb1.png)

The command `docker image ls --filter dangling=false` errors with `invalid filter 'dangling'`

**Comment by minpeter** [comment]
The same symptoms occurred to me.  
I enabled the containerd image store (Beta) and the symptom occurred after that.  
![image](https://user-images.githubusercontent.com/62207008/210222637-bc965c56-c529-412a-b15c-f1f670095369.png)
Toggling the single eye icon seems to work just fine as mentioned above.  
![image](https://user-images.githubusercontent.com/62207008/210222859-f412f2f6-4313-4171-a4cb-c4bdd3bbfcbf.png)

Thanks @danegsta @wsmelton

I used a translator. hope you understand.

**Comment by danegsta** [comment]
I opened an issue on the Docker Desktop for Windows repo for this behavior as it appears to be a bug in the containerd image store beta: https://github.com/docker/for-win/issues/13152

**Comment by bwateratmsft** [comment]
Here's the further-upstream issue: https://github.com/moby/moby/issues/43846

**Comment by bwateratmsft** [comment]
I'm going to move this tracking issue to the 1.25.0 milestone. No action should be required by us either way, so whenever it is fixed in Docker (and updated on the user's machine) it should immediately start working.

**Comment by bwateratmsft** [comment]
The upstream issue has been fixed (though not yet released); no additional work is required on our end. I'll close this issue.
