### ISSUE TITLE
Failed to connect under flatpak VSCode

### ISSUE THREAD

**Issue by mbnoimi** [microsoft/vscode-docker#3788]
I'm unable to use docker from VSCode (flatpak version)!
- vscode-docker: v1.23.3
- VSCode (Linux Mint 21.1 Xfce)
```
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:35:03.979Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic
Sandboxed: No
```
- `flatpak info --show-permissions com.visualstudio.code`
```ini
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=all;
features=devel;
filesystems=xdg-config/gtk-3.0;/home/laptop/.themes;xdg-config/kdeglobals:ro;/run/docker.sock;host;/usr/share/themes;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.AppMenu.Registrar.*=talk
org.freedesktop.secrets=talk

[System Bus Policy]
org.freedesktop.login1=talk

[Environment]
GTK_THEME=Mint-Y-Dark-Aqua
LD_LIBRARY_PATH=/app/lib
NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
ZYPAK_SPAWN_LATEST_ON_REEXEC=0
QT_STYLE_OVERRIDE=Adwaita-dark
```
![image](https://user-images.githubusercontent.com/284547/209578334-466c1ea5-6c4d-4647-8eb8-7ebdba08183d.png)

**Comment by mbnoimi** [comment]
```bash
$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4
$ docker-compose --version
docker-compose version 1.29.2, build unknown
```

**Comment by danegsta** [comment]
@mbnoimi Can you try running `docker -v` from a VS Code terminal pane and sharing the results?

**Comment by mbnoimi** [comment]
> @mbnoimi Can you try running `docker -v` from a VS Code terminal pane and sharing the results?

```
$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu4
```

**Comment by danegsta** [comment]
Hmm, that's the exact command that we run to determine if Docker is installed; from this, I'm assuming there's a boundary issue between the flatpak sandbox and the host machine where Docker is installed/running on one side, but our spawn command is running on the other. Do you know if the flatpak-spawn terminal from your screenshot is running with `flatpak-spawn --host`?

**Comment by mbnoimi** [comment]
> `flatpak-spawn --host`

```
flatpak-spawn: command not found
```
![image](https://user-images.githubusercontent.com/284547/210126039-d2ea74fd-484b-439a-812f-574ef6682440.png)

**Comment by mbnoimi** [comment]
`~/.var/app/com.visualstudio.code/config/Code/User/settings.json`

```json
{
  "window.zoomLevel": 2,
  "telemetry.telemetryLevel": "off",
  "intelephense.telemetry.enabled": false,
  "code-runner.enableAppInsights": false,
  "workbench.startupEditor": "none",
  "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "/usr/bin/env",
      "args": [
        "--",
        "flatpak-spawn",
        "--host",
        "--env=TERM=xterm-256color",
        "bash"
      ]
    }
  },
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "workbench.iconTheme": "material-icon-theme",
  "cSpell.userWords": [
    "Autoload",
    "autoloader",
    "fakerphp",
    "guzzlehttp",
    "heroicons",
    "inertiajs",
    "laravel",
    "mbnoimi",
    "nunomaduro",
    "pestphp",
    "phpunit",
    "spatie",
    "Vite"
  ],
  "[json]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
  "redhat.telemetry.enabled": false,
  "[dockercompose]": {
    "editor.defaultFormatter": "ms-azuretools.vscode-docker"
  },
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[php]": {
    "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
  },
  "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
  "php-cs-fixer.lastDownload": 1672076150671,
  "git.confirmSync": false,
  "update.showReleaseNotes": false,
  "update.mode": "none",
  "[shellscript]": {
    "editor.defaultFormatter": "shakram02.bash-beautify"
  },
  "editor.multiCursorModifier": "ctrlCmd",
  "python.formatting.provider": "yapf",
  "php.suggest.basic": false,
  "php.validate.enable": false,
  "emmet.excludeLanguages": [
    "markdown",
    "php"
  ],
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.linkedEditing": true,
  "rapidapi.terminalLink.enabled": false,
  "gopls": {},
  "go.goroot": "/home/admino/.go",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "gitlens.views.branches.branches.layout": "list",
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": [
    "source.fixAll.eslint"
  ],
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "vue"
  ],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "typescript.tsdk": "node_modules/typescript/lib",
  "[dotenv]": {
    "editor.defaultFormatter": "foxundermoon.shell-format"
  }
}
````

**Comment by danegsta** [comment]
Okay, based on that config, it looks like the VSCode terminal is running commands with `flatpak-spawn --host`, which should be running them outside the sandbox.

I haven't been able to find a flatpak docker extension that would allow access to the system docker executable from within the VSCode flatpak sandbox; if one does exist, that would likely be the proper way to enable support for running Docker commands inside the flatpak instance. Without an extension, I believe this flathub issue has several potential workarounds for working with Docker inside the VSCode flatpak: https://github.com/flathub/com.visualstudio.code/issues/55

Specifically, from the suggestions in that issue, creating a shell script in the VSCode flatpak to effectively proxy calls to the Docker CLI and run them on the host is the most likely option to get you unblocked. Save the following shell script in the flatpak as an executable file named "docker" and add it to the flatpak's PATH:
`
#!/bin/sh
flatpak-spawn --host docker "$@"
`

That *should* basically intercept our calls to the Docker CLI and run them on the host.

**Comment by mbnoimi** [comment]
> in add it to the flatpak's PATH

I couldn't understand what you mean!

Any way, I put `docker.sh` in `~/.var/app/com.visualstudio.code/data/vscode/extensions/ms-azuretools.vscode-docker-1.23.3` as you can see below:
```bash
$ ls -lh
total 608K
-rw-r--r-- 1 admino admino  64K Dec 20 08:45 CHANGELOG.md
drwxr-xr-x 5 admino admino 4.0K Dec 20 08:45 dist
-rwxrwxr-x 1 admino admino   46 Jan  4 08:40 docker.sh
-rw-r--r-- 1 admino admino 1.2K Dec 20 08:45 LICENSE.md
-rw-r--r-- 1 admino admino 1.3K Dec 20 08:45 main.js
-rw-r--r-- 1 admino admino 307K Dec 20 08:45 NOTICE.html
-rw-r--r-- 1 admino admino  90K Dec 20 08:45 package.json
-rw-r--r-- 1 admino admino  36K Dec 20 08:45 package.nls.json
-rw-r--r-- 1 admino admino 8.4K Dec 20 08:45 README.md
drwxr-xr-x 8 admino admino 4.0K Dec 20 08:45 resources
-rw-r--r-- 1 admino admino 2.8K Dec 20 08:45 SECURITY.md
```
And modified  `/home/admino/.var/app/com.visualstudio.code/config/Code/User/settings.json` as following. Now I no longer able to launch the terminal inside vscode and the extension still unable to detect docker!


```json
{
  "window.zoomLevel": 2,
  "telemetry.telemetryLevel": "off",
  "intelephense.telemetry.enabled": false,
  "code-runner.enableAppInsights": false,
  "workbench.startupEditor": "none",
  "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "/home/admino/.var/app/com.visualstudio.code/data/vscode/extensions/ms-azuretools.vscode-docker-1.23.3/docker.sh",
    }
  },
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "workbench.iconTheme": "material-icon-theme",
  "cSpell.userWords": [
    "Autoload",
    "autoloader",
    "fakerphp",
    "guzzlehttp",
    "heroicons",
    "inertiajs",
    "laravel",
    "mbnoimi",
    "nunomaduro",
    "pestphp",
    "phpunit",
    "spatie",
    "Vite"
  ],
  "[json]": {
    "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
  },
  "redhat.telemetry.enabled": false,
  "[dockercompose]": {
    "editor.defaultFormatter": "ms-azuretools.vscode-docker"
  },
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[php]": {
    "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
  },
  "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
  "php-cs-fixer.lastDownload": 1672076150671,
  "git.confirmSync": false,
  "update.showReleaseNotes": false,
  "update.mode": "none",
  "[shellscript]": {
    "editor.defaultFormatter": "shakram02.bash-beautify"
  },
  "editor.multiCursorModifier": "ctrlCmd",
  "python.formatting.provider": "yapf",
  "php.suggest.basic": false,
  "php.validate.enable": false,
  "emmet.excludeLanguages": [
    "markdown",
    "php"
  ],
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.linkedEditing": true,
  "rapidapi.terminalLink.enabled": false,
  "gopls": {},
  "go.goroot": "/home/admino/.go",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "gitlens.views.branches.branches.layout": "list",
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": [
    "source.fixAll.eslint"
  ],
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "vue"
  ],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "typescript.tsdk": "node_modules/typescript/lib",
  "[dotenv]": {
    "editor.defaultFormatter": "foxundermoon.shell-format"
  }
}
```

**Comment by danegsta** [comment]
Flatpak acts as a sandbox for the application that is running, so your VSCode has no access to any applications/services that aren't installed into the flatpak directly. Docker is installed on your system, but not inside the VSCode flatpak. This means that the VSCode Docker extension can't access the Docker CLI. When you run the commands from the terminal in VSCode, it's actually using a special command `flatpak-spawn --host ...` to run the terminal on the host outside the flatpak sandbox, which is why you can run Docker commands from the terminal, but the Docker extension in VSCode can't run any Docker commands itself.

You need to either make the system Docker CLI available within the VSCode flatpak via a flatpak extension (which is a way to make system resources available inside a flatpak) or you need to somehow provide a proxy for the Docker CLI via a shell script that will invoke docker via flatpak-spawn --host, which is the approach I was mentioning in the previous comment.

**Comment by mbnoimi** [comment]
@danegsta Thanks for the explanation. But what's the practical steps I've to follow for fixing this issue?
I sent to you the permissions for vscode. Do I've to give it a new permission?

For now I use [Whaler](https://flathub.org/apps/details/com.github.sdv43.whaler) as a replacement to this extension as I couldn't find any solution since a while!
BTW, [Whaler](https://flathub.org/apps/details/com.github.sdv43.whaler) is a flatpak app and works very well.

**Comment by mbnoimi** [comment]
I copied the permissions of [Whaler](https://flathub.org/apps/details/com.github.sdv43.whaler) to vscode but it didn't fix this issue!

`flatpak info --show-permissions com.visualstudio.code`
```ini
[Context]
shared=ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
filesystems=!/home/admino/.themes;xdg-run/docker.sock;/run/docker.sock;xdg-run/podman/podman.sock;xdg-config/gtk-3.0;/run/podman/podman.sock;!host;xdg-config/kdeglobals:ro;/usr/share/themes;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.AppMenu.Registrar.*=talk
org.freedesktop.secrets=talk

[Environment]
LD_LIBRARY_PATH=/app/lib
NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
ZYPAK_SPAWN_LATEST_ON_REEXEC=0

```

**Comment by danegsta** [comment]
To be clear, this isn't necessarily a permissions issue. The Docker extension for VSCode needs to be able to invoke the Docker CLI, which doesn't seem to be installed in the VSCode flatpak. Flatpaks specifically sandbox the running application from accessing executables outside the flatpak and there are certain system paths that you cannot allow access to in a flatpak for security reasons. You have Docker installed on your system outside of the VSCode flatpak, but the Docker extension in VSCode doesn't have access to it due to the sandbox.

You can try running `which docker` from a terminal to see where the Docker CLI is installed, but if it's installed in one of the folders listed in the flatpak docs as not being allowed to grant access to inside a flatpak (https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access), you won't be able to grant the VSCode flatpak direct access to it.

You need to either expose the file path to the Docker CLI executable into the VSCode flatpak (which will only work if the Docker CLI is installed outside of the forbidden system paths) OR expose the path to a shell script you create that you name "docker" that can use `flatpak-spawn --host` to invoke the system Docker CLI outside of the flatpak (see my above comment for the contents of this shell script).

**Comment by mbnoimi** [comment]
Thank you for the huge two theoretical comments. You didn't help me to fix anything!
You just talk like a bot!

I sent to you many logs but you still send comments explain, explain and explain then did nothing.
All the info mentioned in your comment  are already know. For god sake do you installed vscode flatpak version?! It seems you didn't because you still talllllllk.

[Whaler](https://flathub.org/apps/details/com.github.sdv43.whaler) works fine to me. It's a flatpak app. It has less permissions than vscode it can access `/run/docker.sock` without any problem.

Please keep commenting and explaining to me how to use flatpak. I uninstalled this stupid extension for good.
