### ISSUE TITLE
Allow configuring the python interpreter used in the container

### ISSUE THREAD

**Issue by dhirschfeld** [microsoft/vscode-docker#3789]
AFAICS the value of the Python interpreter used in the container is *hardcoded* to `python3`?
https://github.com/microsoft/vscode-docker/blob/8e591b8634583af0a0a3dc1f60015cb8bdab6d83/src/debugging/python/PythonDebugHelper.ts#L120-L122

The `exec` command looks like:
```
docker exec -d seautnsquetz-dev python3 /debugpy/launcher 172.17.0.1:37973 -- -m uvicorn quetz.main:app --host 0.0.0.0 --port 8000
```

My Python containers use `conda` environments and the correct interpreter to use is `python`, ***not*** `python3`.

What that means is that the command bypasses the `python` in the `conda` environment and falls through to the system `python` which has none of the dependencies installed so results in the error:

![image](https://user-images.githubusercontent.com/881019/209803999-dd2c4936-f245-42f9-95dc-f55fd34a75f6.png)

**Comment by dhirschfeld** [comment]
Since I'm using `conda` environments, the command should actually be:
```yaml
python: ["conda", "run", "-n", "quetz", "--no-capture-output", "--live-stream", "python"]
```

**Comment by dbreshears** [comment]
Closing stale issue
