### ISSUE TITLE
Pull image from Generic Docker Registry : bad path

### ISSUE THREAD

**Issue by gri38** [microsoft/vscode-docker#3790]
Hello.

First congratulation for your **awesome** extension.

### My versions
I'm using vscode on Windows:
```Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
```

Your extension version I use is `1.23.3`

### My problem
When I configure a registry like that:
- As provider I select "Generic Docker Registry"
- As url: "https://artifactory.mysociety.net/artifactory/api/docker/docker-dev/"
- I input my user and artifactory API key
=> The images are correctly listed under the registry.

```diff
- But image pull fails because a bad path
```
- I expand an image with this path: path/to/the/image => images are listed as expected
- If I right-click on latest tag for this image and select "Pull image" => it fails with the following message:
```
 *  Executing task: docker image pull artifactory.mysociety.net/path/to/the/image:latest 

Error response from daemon: unknown: Not Found

 *  The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker image pull artifactory.mysociety.net/path/to/the/image:latest" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```
The path should be (in my case at least): artifactory.mysociety.net/**docker-dev**/path/to/the/image:latest

I'm available if you need more info.
Thanks for your support, and once again for your sooooooo usefull extension.

**Comment by bwateratmsft** [comment]
Sorry it took so long to get to this, we've been super busy.

Looking at the documentation, it seems like Artifactory may not quite be complying with the [Registry V2 spec](https://docs.docker.com/registry/spec/api/). The repository listing result returns images with names like `path/to/the/image`, and also returns tag lists for those images, but (I think) it _should_ be returning images with names like `docker-dev/path/to/the/image`.

Currently, we treat the hostname (plus port) as the base image path; if the URL provided was `https://artifactory.mysociety.net/artifactory/api/docker/docker-dev/`, there's not a deterministic way to know that the `artifactory/api/docker` part should _not_ be considered part of the base image path but `docker-dev` _should_. However, if Artifactory includes `docker-dev` as part of the repository name in the list repository results, everything should just work.

@gri38 It looks like Artifactory calls this `docker-dev` part of the image the ["repository key"](https://www.jfrog.com/confluence/display/JFROG/Docker+Registry#DockerRegistry-LocalDockerRepositories). I have no familiarity with Artifactory, so there may be some way to configure it to include that in the repository list results.

**Comment by gri38** [comment]
Hello.
No problem, thanks a lot for your answer, your investigation, and your suggestion.
I'll try (not be, but let's simplify ;-)) to setup artifactory so it answers correctly, and let you know (it may take also a while).

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
