### ISSUE TITLE
Cannot add Docker File to a webapi ASP.NET project in vscode

### ISSUE THREAD

**Issue by tarekahf** [microsoft/vscode-docker#3791]
I followed the steps below:

1. Create new dotnet project using 

`dotnet new webapi -o HelloASPNetCore --use-program-main -f net6.0`

2. Opened the project above using vscode.
3. The project was run successfully.
4. Installed Docker Extension.
5. Press ctrl-shift-p tp add docket file and selected ASP.NET Core, Linux, and the default port.
6. I see the following error:

```
Error: Unable to determine project information for target 'GetProjectProperties' on project 'c:\Projects\HelloASPNetCore\HelloASPNetCore.csproj' Process exited due to signal SIGTERM
```

And, the docker file is not created.

Also note that I was able to run the getting started docker container. In addition, I was able to use docker successfully by running webapi projects from Visual Studio 2022, and I can see all the docker containers and images from VS Code Docker Extension.

Please help to resolve this issue.

Using:
- Azure VM Windows Server 2022
- VSCode Version: 1.74.2 (system setup)
- Docker Extension: v1.23.3

**Comment by danegsta** [comment]
This is likely a timeout on the dotnet build command we run to determine various project properties we need to scaffold the correct Dockerfile. Can you share the machine size of the Azure VM you're using (CPU cores, available memory, etc.)?

**Comment by tarekahf** [comment]
I actually increased the size of the machine from D2s_v3 to D4s_v3 and it is working now. I am not sure if the change in the machine size has solved this problem. Maybe you need to mention this in the requirements to make this extension work.

Thank you for the help.

**Comment by danegsta** [comment]
Glad upgrading the machine got you unblocked. Upgrading the machine size is likely what fixed the issue for you as the error you were seeing is related to a command we run timing out. It may be a CPU/RAM performance limitation on the D2s_v3 machine or possibly a disk performance issue on that machine size. I'll take a look at our performance on a D2s_v3 machine to try and find the particular bottleneck see if there are any tweaks we can make to better support lower resource Azure VMs.

**Comment by tarekahf** [comment]
I had to upgrade as the docker build commands used to take 10 to 15 minutes to finish building a simple container. It dropped to a few minutes after the upgrade.

Tgank you so much. Please add this to the prerequisites of the extension.

**Comment by bwateratmsft** [comment]
I'll close this as external. Our timeout for the `dotnet` processes we're starting is 20 seconds which is far longer than it would typically require. On extremely slow machines it could still timeout; it sounds like that was happening here, but it is not practical to try to enumerate all possible minimum system requirements.

**Comment by tarekahf** [comment]
I suggest at least the error message should indicate it's a timeout or add the error message to a troubleshooting section and possibly solution to get a better machine.
