### ISSUE TITLE
way to disable WORKDIR paths should be absolute

### ISSUE THREAD

**Issue by walksanatora** [microsoft/vscode-docker#3799]
there is no where where that is true so give us the option to disabler linter warnings
i could understand the UPPERCASE for the commands but this is annoying

**Comment by bwateratmsft** [comment]
You can disable linter warnings on an individual basis with extension settings. The setting ID for the WORKDIR linter warning is `docker.languageserver.diagnostics.instructionWorkdirRelative`.

![image](https://user-images.githubusercontent.com/36966225/212938674-a4af0172-cb56-4212-a08f-9b868efff1fb.png)
