### ISSUE TITLE
Document relationship (or lack thereof) between compose tasks and commands customisation

### ISSUE THREAD

**Issue by motohedgehog** [microsoft/vscode-docker#3801]
Hey, I did my best to read the docs/code and experiment with different options, but either I am missing something very obvious or there's a genuine bug in command customisation logic.

# Problem
Suppose I have a very bare-bones project:
```shell
❯ ls -aT
.
├── .vscode
│  ├── settings.json
│  └── tasks.json
└── docker-compose.yml
```

The compose file is extremely simple (it uses the [official Docker hello-world image](https://hub.docker.com/_/hello-world)):
```yaml
name: compose-bug

services:
  hello:
    image: hello-world
```

I also have a single task for starting the service:
```yaml
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "up",
            "type": "docker-compose",
            "dockerCompose": {
                "up": {},
                "files": [
                    "${workspaceFolder}/docker-compose.yml"
                ]
            }
        }
    ]
}
```

Suppose I'd like to override the `compose up` command so that it prints the timestamps. My `settings.json` file is as follows:
```yaml
{
    "docker.commands.composeUp": "${composeCommand} ${configurationFile} up --timestamps ${detached} ${build}"
}
```

## Expectation
Running the `up` task invokes `docker compose up` command with `--timestamps` argument

## Reality
Running the `up` task executes `docker compose up` in default configuration.
```shell
Executing task: up 

> docker compose --file “${MY_WORKSPACE_ROOT}/docker-compose.yml” up <
```

Am I missing something obvious here?

**Comment by bwateratmsft** [comment]
The tasks feature and command customization aren't directly related. Command customization is meant to change what command gets run if you right click the compose file and do compose up, or run it from the command palette (and several other things like building a Dockerfile when there isn't a `docker-build` task for it, running images, attaching the shell, etc.). Task customization is only done through the parameters of the task. Timestamps are not an "official" option, but you can use the `customOptions` field to add that argument, like this:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "up",
            "type": "docker-compose",
            "dockerCompose": {
                "up": {
                    "customOptions": "--timestamps"
                },
                "files": [
                    "${workspaceFolder}/docker-compose.yml"
                ]
            }
        }
    ]
}
```

I think there's room to improve the documentation here; the overlap between `docker-build` / `docker-run` / `docker-compose` tasks and the customizable commands for the same actions can be more clearly delineated.

**Comment by motohedgehog** [comment]
Thank you @bwateratmsft , that's very insightful!

One interesting thing that I've noticed is that compose tasks will still respect the `docker.composeCommand` setting, but not `docker.commands.compose*` ones. I personally feel that it would be valuable to have the tasks respect all of those settings or perhaps to provide a similar mechanism within task for overriding the commands.

My high-level issue (I know, I know, [XY problem](https://xyproblem.info) 🙂) is to find the most clean way of setting up a `compose up` task  where the `docker-compose.yml` has a secret reference that can be resolved by [1Password CLI.](https://developer.1password.com/docs/cli/secret-references)

I could set up something based on your explanation -- namely, I prefixed the default `compose up` command template with `MY_ENV_VARIABLE=op://Secret/reference/here op run --`. It still feels a bit hacky, but I guess it's up to me to figure out if there's a better option.

**Comment by bwateratmsft** [comment]
I tested the `docker.composeCommand` thing and it worked as expected. What value do you have set for `docker.commands.composeUp`? We only use the `docker.composeCommand` setting to replace the `${composeCommand}` token in the string; if you directly put `docker-compose` (or `docker compose`) in we will not change it. For example, the default value for `docker.commands.composeUp` is `${composeCommand} ${configurationFile} up ${detached} ${build}`.

**Comment by motohedgehog** [comment]
Sorry if I misled you -- what I meant is
* If `docker.composeCommand` is set in `settings.json` and there's a `"type": "compose-up"` task defined in `tasks.json`, then the task will pick up the compose command setting
* If only `docker.commands.composeUp` is set in `settings.json` and there's `"type": "compose-up"` task defined in `tasks.json` (my original question), then it will *not* pick up the compose command setting

The `docker.commands.compose*` settings indeed respect `docker.composeCommand` as long as the `${composeCommand}` token is present.

I think it aligns with everything you're saying and actually highlights the documentation improvement point 🙂

Regarding tasks dependencies, I was considering that option but ideally I'd like to avoid generating intermediate files to simplify housekeeping.

**Comment by bwateratmsft** [comment]
Ah, now I understand what you mean. Thanks!

**Comment by bwateratmsft** [comment]
Closed by https://github.com/microsoft/vscode-docs/pull/6201.
