### ISSUE TITLE
Enable debugging support for .NET native container builds

### ISSUE THREAD

**Issue by baronfel** [microsoft/vscode-docker#3808]
Starting with .NET 7, the .NET SDK enables [containerizing .NET applications without a Dockerfile](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/) via a simple `dotnet publish` command. Subsequent releases of this capability have focused on integrating the package into more project types - the 7.0.200 release of the SDK in February will include the package for Web SDK projects (those that use ASP.NET Core), and we plan to extend this to all .NET project types in the spring release of 7.0.300.

It would be amazing if we could integrate this package into the tooling for this extension, letting developers continue the easy containerization experience all the way up to publishing their app to the cloud provider even inside their IDE.

Conceretely, it would be great if the onboarding experience for .NET debugging support didn't require the use of scaffolded Dockerfiles, and could generate `publish` commands instead of `docker build` commands for the prerequisite build tasks.

**Comment by bwateratmsft** [comment]
I tested build and debug with one of these, and was successful with a small number of changes. In terms of performance it felt about the same--the initial image build is slower (in both cases), but subsequent builds are very fast.

**Comment by alexyaang** [comment]
Unlinking the PR since we're switching directions after discussing with Brandon. Instead of adding a flag onto the existing `docker-build`, we're going with an ambient task and building a brand new task handler to handle this task. This makes more sense in the long run and gives us more flexibility.
