### ISSUE TITLE
Extension not displaying any panels 

### ISSUE THREAD

**Issue by leegodden** [microsoft/vscode-docker#3810]
When clicking the Docker icon in sidebar all I can see are the containers, no images, volumes etc
<img width="456" alt="extension-view" src="https://user-images.githubusercontent.com/3835338/214566598-255b66c9-905d-4579-b1cf-8f439fa91cea.png">

**Comment by bwateratmsft** [comment]
@leegodden can you try right-clicking where it says "Docker: Containers" at the top, and verify if the other views are enabled?
![image](https://user-images.githubusercontent.com/36966225/214593774-5c9667ef-c17f-42b2-91b7-d80b5bc2d519.png)

If this doesn't work, try running the command "View: Reset View Locations". This will move all views back to their original view containers.

**Comment by leegodden** [comment]
Good call, now working, thanks

**Comment by bwateratmsft** [comment]
Great! Glad it's working now.
