### ISSUE TITLE
Add "Pull" menu option for repositories and tags in a container registry

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#382]

**Comment by estebanreyl** [comment]
We have one for pull at least for the tags that we can PR soon, is there such a thing as a local repository?

**Comment by StephenWeatherford** [comment]
Not sure what you mean.

**Comment by estebanreyl** [comment]
Wait, I see how it works, sorry I wasn't quite certain how you'd pull a repository.
