### ISSUE TITLE
Docker is very unstable on Macos Ventura x86_64

### ISSUE THREAD

**Issue by 524c** [microsoft/vscode-docker#3820]
Several things no longer work in Docker on MacOs Ventura, x86_64.

Docker login in a local registry;
VScode extension;
Docker Desktop takes a long, long time to open and consumes tons of resources. No chance to use local. Only with a powerful machine or use a remote solution. For local work it is not feasible.

Does this occur consistently? 
Repro steps:
Only try, if you can, install and use de Docker and Vscode extension on a MacOS ventura, intel proc :)

With latest Docker installed:
<img width="1552" alt="Screenshot 2023-02-01 at 18 02 10" src="https://user-images.githubusercontent.com/527641/216162678-3186d524-81f2-4b68-aa4a-909d3b0ab710.png">
<img width="995" alt="Screenshot 2023-02-01 at 18 04 26" src="https://user-images.githubusercontent.com/527641/216162995-8a3b451c-68f2-4b03-bf3b-5fc2025ae8bf.png">

Version: 1.23.3
OS: darwin
OS Release: 22.1.0
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

**Comment by bwateratmsft** [comment]
@524c it sounds like this is a Docker Desktop issue, not specifically the Docker extension for VSCode, correct?

**Comment by 524c** [comment]
Hey @bwateratmsft

Sorry. You're right. It's a Docker Desktop issue.
The Vscode tricked me into reporting an issue and I didn't realize it went to the Vscode repository.

Tks!

**Comment by bwateratmsft** [comment]
No problem! https://github.com/docker/for-mac is probably the right repo, otherwise they can transfer as needed.

**Comment by 524c** [comment]
tks!
