### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by melwinkle** [microsoft/vscode-docker#3822]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.9.0
OS: darwin
OS Release: 22.2.0
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:95302
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:223:5
Pipe.<anonymous> net.js:664:12
```

</details>

**Comment by bwateratmsft** [comment]
@melwinkle do you have Docker installed?

**Comment by bwateratmsft** [comment]
This is also a really old version of both VSCode and the Docker extension, I recommend updating both and trying again.
