### ISSUE TITLE
Make activity bar icon match VS Code style guide

### ISSUE THREAD

**Issue by azat-io** [microsoft/vscode-docker#3824]
There is official VS Code icon library - codincons:
https://microsoft.github.io/vscode-codicons/dist/codicon.html

The current icon stands out from the rest:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/5698350/216731002-09d17dd7-8fac-40c7-a602-02d7e1f90112.png">

It would be nice to make outline activity bar icon for Docker extension

**Comment by bwateratmsft** [comment]
We'd have to check what icons are available; we can only use ones that are Docker Inc.-approved. Something from https://www.docker.com/company/newsroom/media-resources/ or equivalent.

**Comment by azat-io** [comment]
Sounds sad. 😞 

Official logos don't fit well and strongly differ from other icons. I thought about something like that:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5698350/217060873-1199095d-5795-4596-a531-ebe0a7ff80a3.png">

**Comment by bwateratmsft** [comment]
Aesthetically speaking I do like the look of what you've suggested. But I can't find any approved wireframe-style logos, so we might be out of luck.

**Comment by bwateratmsft** [comment]
I guess I'll close this issue. I can't find anything wireframe-styled that's approved. Sorry 😞
