### ISSUE TITLE
The vscode docker extension is not working correctly.

### ISSUE THREAD

**Issue by PabloMuYAnYO** [microsoft/vscode-docker#3827]
The vscode docker extension does not work correctly for me.

An error popup tells me this:

Cannot activate extension "Docker" because it depends on an unknown extension "vscode.docker".

Any solution?
<img width="923" alt="Captura de pantalla 2023-02-09 103935" src="https://user-images.githubusercontent.com/99806891/217775369-c58704dc-0c7a-476a-a76b-79fd6955b29e.png">

**Comment by PabloMuYAnYO** [comment]
Hello, I hope this helps.
<img width="280" alt="Captura de pantalla 2023-02-10 095658" src="https://user-images.githubusercontent.com/99806891/218047808-e718f679-69d3-43a3-8fc4-1364a0b8562e.png">

Thanks, let me know if you need something specific, because I'm not sure.

**Comment by bwateratmsft** [comment]
Can you run the command "Extensions: Show Built-in Extensions", and in the "Programming Languages" section, see if "Docker Language Basics" and "YAML Language Basics" are present and enabled?
![image](https://user-images.githubusercontent.com/36966225/218136356-7f689b9f-547f-4913-be6f-8abff72075be.png)
![image](https://user-images.githubusercontent.com/36966225/218136424-cc903039-82b5-48c7-8c28-b56aa6e04cc6.png)

**Comment by PabloMuYAnYO** [comment]
Hello, I am very sorry for the delay, is this what you mean?
![image](https://user-images.githubusercontent.com/99806891/218676253-ae2ab185-163e-4cff-91c1-26d1244c2f17.png)

**Comment by bwateratmsft** [comment]
Yes, this looks right. I'm going to open an issue in the VSCode repo, it seems that the `vscode.docker` and `vscode.yaml` extensions are indeed present, so there shouldn't be an error saying they're unknown.

**Comment by bwateratmsft** [comment]
I created https://github.com/microsoft/vscode/issues/174348 to track this. I'll resolve this issue as external.

**Comment by PabloMuYAnYO** [comment]
👌
