### ISSUE TITLE
Container tooltip's port should not hardcode `localhost`

### ISSUE THREAD

**Issue by KillahB33** [microsoft/vscode-docker#3829]
Clicking on the docker port should either be the same IP I am connected to, or let me set it in the settings.

**Comment by bwateratmsft** [comment]
@KillahB33 can you elaborate on where you're seeing the port and clicking on it?

**Comment by KillahB33** [comment]
Yes, when I hover over the container in the dropdown menu it shows the image, ports, volumes and networks.
The ports are links but when you click on it, it goes to localhost:<port> I assume because it's not aware I am also using the remote ssh conector.
Apologies for the wait, just saw the email this morning for your response.

**Comment by KillahB33** [comment]
Was not aware that was on option, very cool. Yes it's working, but it appears VSCode is working as some form of reverse proxy, so the address in the bar is still localhost but it's actually rendering the page.

**Comment by bwateratmsft** [comment]
Hm, I wonder if VSCode is opening the links in a different manner? I've always been impressed at how well VSCode handles acting like a reverse proxy in remote scenarios.

**Comment by KillahB33** [comment]
Yeah it's pretty neat. I just recently moved to use VSCode more for my remote stuff and it has been really great

**Comment by dbreshears** [comment]
Closing lower priority since open in browser works and remote only
