### ISSUE TITLE
Conncet via tcp not possible

### ISSUE THREAD

**Issue by josersleal** [microsoft/vscode-docker#3833]
Connecting to a remote machine docker engine is not possible via tcp.
the setting docker.host is no longer available. (somebody forgot to write a test?)

**Comment by bwateratmsft** [comment]
@josersleal the setting has been migrated to `docker.environment`. You can do something like this:

```json
`"docker.environment": {
    "DOCKER_HOST": "tcp://foo@bar.baz"
}
```

Nevertheless, the extension should have prompted when it first activated to migrate the settings for you. Did that toast not appear?
