### ISSUE TITLE
Support filter on docker volume prune

### ISSUE THREAD

**Issue by Mehayes411** [microsoft/vscode-docker#3839]
Type: <b>Feature Request</b>

Docker 23 changed the way docker volume prune selects volumes to remove. Add support for the --filter options to address these changes

Extension version: 1.23.3
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.15.90-54.138.amzn2.x86_64
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1058-aws

**Comment by bwateratmsft** [comment]
I'm going to mark this as a bug, since it's something that worked previously but was broken (by the external change). Looks like this is it: https://github.com/moby/moby/pull/44259

We'll need to make sure that the `--filter` argument works on older versions of Docker...

**Comment by bwateratmsft** [comment]
We may just change our behavior to match the CLI's behavior, i.e., only prune anonymous volumes instead of all volumes now. We need to see if older versions of the Docker CLI (or Docker CE) choke on the `--filter` argument.

**Comment by alexyaang** [comment]
I'm going to do a second investigation on this today and see what we can do.

**Comment by dbreshears** [comment]
Agreed. Closing this.
