### ISSUE TITLE
Troubleshooting docs still mentionning deprecated `docker.host` option

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [microsoft/vscode-docker#3847]
I'm trying to make the extension work with rootless podman. In the [troubleshooting docs](https://github.com/microsoft/vscode-docker/wiki/Troubleshooting), it was made mention of the ` docker.host` parameter, which is deprecated and removed in the latest version of the extension from what I understood of #3539. 

I found a solution to my problem using [this comment](https://github.com/microsoft/vscode-docker/issues/3766#issuecomment-1347005283) (i.e. revert back to v1.22.2 and use the `docker.host` option).

It would be nice to update the troubleshooting docs in order not to make reference to the ` docker.host` option anymore and to give a better explanation on how to use another container runtime than docker (maybe linking to the related issue (#3241) or to the solution given above).

**Comment by bwateratmsft** [comment]
We'll need to update the troubleshooting docs. Podman will not work with Docker extension version 1.23 or 1.24, due to differences in the JSON output that our parser isn't handling; we're tracking that in #3241.

**Comment by bwateratmsft** [comment]
I have updated the troubleshooting doc. It looks like the [product docs](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-vs-code-settings-or-local-environment-variables) are already up-to-date.
