### ISSUE TITLE
some phrases seems not translated on wsl from windows 10, also icon is not visible

### ISSUE THREAD

**Issue by matteo-bombelli** [microsoft/vscode-docker#3853]
issue:

![image](https://user-images.githubusercontent.com/15176885/223608515-40882b4f-f8f6-491d-ad61-65f7fb27daad.png)

some phrases seems not translated on wsl from windows 10, also icon is not visible. if local or remote linux not on wsl it works correctly, 

vscode version

![image](https://user-images.githubusercontent.com/15176885/223606575-ddba997b-8d2a-4a4f-ac69-2e3baf7c621c.png)

vscode-docker version: v1.24.0

**Comment by bwateratmsft** [comment]
Looks the same as what [this user hit](https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1397057523) in #3783, so I'll resolve this as a dupe. There's some strange [issue](https://github.com/microsoft/vscode/issues/171834) in VSCode that appears only occasionally. It may resolve itself if you reinstall the Docker extension or reinstall VSCode: https://github.com/microsoft/vscode-docker/issues/3783#issuecomment-1413580724
