### ISSUE TITLE
Express application based on generated Dockerfile doesn't work on Web App for Containers.

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode-docker#3855]
The following logs are written when running a simple Express application container with the default Dockerfile generated by this extension.
![image](https://user-images.githubusercontent.com/4566555/224009779-f96f6a69-f7c4-47dc-baf8-463f5bd8d03c.png)
This is caused by that the version of npm in `node:lts-alpine` is 9.5.0.

The logs matches the Docker User Namespace remapping issues.
https://azureossd.github.io/2022/06/30/Docker-User-Namespace-remapping-issues/index.html

This issue is resolved by changing the owner of files in `node_modules` or upgrading to npm@9.5.1 or later (i.e. changing the following line to `RUN npm install --production --silent && chown -R node:root node_modules && mv node_modules ../` or `RUN npm install -g npm && npm install --production --silent && mv node_modules ../`).
https://github.com/microsoft/vscode-docker/blob/ad130138a88a722316c935ab357ee39d4bd84797/resources/templates/node/Dockerfile.template#L5

**Comment by dbreshears** [comment]
Unable to reproduce this with the existing extension and existing version of npm in the image. Going to close for now.

**Comment by bwateratmsft** [comment]
If users are hitting this, they should be able to apply the workaround suggested by @horihiro to update NPM within the image.
