### ISSUE TITLE
[Suggestion] It would be better to change the button from "Install" to "View Extension" in the prompt dialog

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3861]
**OS:** Windows 10
**Build Version:** 20230309.12
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure there is no "Azure Container Apps" extension installed.
2. Right click one image in registry view -> Select “Deploy Image to Azure Container Apps...” -> A dialog pops up.

**Actual:**
The button is "Install" in the dialog. Click the "Install" button, the "Azure Container Apps Extension" page is opened but the extension is not installed.
![image](https://user-images.githubusercontent.com/45614674/224954575-bfe9b301-4dd0-42c8-b647-79268a118dfe.png)

**Suggestion:**
It would be better to change the button from "Install" to "View Extension".

**Comment by bwateratmsft** [comment]
Agreed. I think we have a utility method in utils now to install an extension *and* open the extension page; if so we should use that instead.

**Comment by v-ruizh** [comment]
This issue is fixed on Docker extension 20230405.3.
