### ISSUE TITLE
Fail to open the web page after deploying image (Express App) to Azure App Service

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3862]
**OS:** Windows 10
**Build Version:** 20230309.12

**Repro Steps:**
1. Right click Dockerfile for Express App-> Build Image.
2. Right click this image in image view -> Push -> Azure -> Select a registry to push.
3. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service.
4. When done, click "Open Site" button in the notification.
5. Check whether the web page can be opened successfully.

**Expect:**
Succeed to open the web page.
![image](https://user-images.githubusercontent.com/45614674/224956532-b87fb8b6-9841-486b-9076-0b71869d32ae.png)

**Actual:**
Fail to open the web page with "Application Error".
![image](https://user-images.githubusercontent.com/45614674/224956605-7734f9ed-f59d-43de-818d-1d9ea85a7927.png)

**More Info:**
This issue does not reproduce after deploying MVC or Python Flask image.

**Comment by alexyaang** [comment]
I was not able to reproduce this after trying the steps a few times. In my experience, it took an average of 2-3 minutes for the website to load after deploying. Are you sure you waited long enough for the website to load?

**Comment by v-ruizh** [comment]
Verified on the latest Docker extension 20230405.3, this issue still reproduces. The npm version is 9.5.0 on my machine.

1. Update the **npm version to 9.6.4** for my machine using this command "npm install -g npm@latest", then create a new Express App and follow the steps, this issue still **reproduces**.
2. According to the bug [3855](https://github.com/microsoft/vscode-docker/issues/3855), change the line to "RUN npm install -g npm && npm install --production --silent && mv node_modules ../" in Express project Dockerfile. This issue **does not reproduce** after following the steps.

**Comment by bwateratmsft** [comment]
Sounds like this might be the same thing as #3855, but we have not been able to reproduce that.
