### ISSUE TITLE
There is an extra notification "Do you want to install the recommended extensions for Dockerfile?" after reopening VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3863]
**OS:** Windows 10
**Build Version:** 20230309.12
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure there is Docker extension installed.
2. Open a Go project in VS Code.
3. Add docker files to this project and open Dockerfile.
4. Close and reopen VS Code.
5. Check whether there is no extra notification "Do you want to install the recommended extensions for Dockerfile?".

**Expect:**
There is no notification "Do you want to install the recommended extensions for Dockerfile?".

**Actual:**
There is an extra notification "Do you want to install the recommended extensions for Dockerfile?". 
![image](https://user-images.githubusercontent.com/45614674/225193301-eb696eea-38c4-46a2-941f-d23cb5e1b41c.png)
Click "Show Recommendations" button, it navigates to Docker extension page.
![image](https://user-images.githubusercontent.com/45614674/225193444-a5dcf5d9-cac9-4ea5-b388-6c9927ddf5bb.png)

**More Info:**
1. This issue also reproduces on the previous released Docker extension v1.24.0.
2. This issue does not reproduce for MVC/Express/Flask projects with Dockerfile opening.

**Comment by bwateratmsft** [comment]
These notifications come from VSCode, I'll transfer this issue there.

**Comment by bwateratmsft** [comment]
I opened https://github.com/microsoft/vscode/issues/177249 for this.
