### ISSUE TITLE
Open in Browser assumes https

### ISSUE THREAD

**Issue by richlander** [microsoft/vscode-docker#3868]
I was using this sample: https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/tutorials/scalable-razor-apps/start

I built and launched the container image from VS Code and then tried "View in Browser". It launched as https, with no port.

That doesn't make sense (IMO) for two reasons:

- The mapped TLS port is `443` not `80`.
- There are no certs in the image (volume mounted or otherwise) so a TLS connection isn't possible.

Seems like raw http should be the default. If I remove the `s` in `https`, then the site loads fine.

The steps I followed seem to match https://code.visualstudio.com/docs/containers/quickstart-aspnet-core

**Comment by richlander** [comment]
It's possible this is a browserism. Once I removed `EXPOSE 443`, the problem went away. I'm going to call that good.

**Comment by bwateratmsft** [comment]
Yeah, our logic for it is here: https://github.com/microsoft/vscode-docker/blob/main/src/commands/containers/browseContainer.ts#L72

It's very much a heuristic; if 443 or 5001 are open (regardless of whether the app is actually listening--which is not something we can tell from the outside without just opening the page), we prefer those and assume they are HTTPS. Then there is a list of HTTP ports we'll auto-select, and if no open ports match either list we'll ask the user.
