### ISSUE TITLE
Build image ... should add `--pull`

### ISSUE THREAD

**Issue by richlander** [microsoft/vscode-docker#3869]
`docker build --pull` is almost always the right choice. Images get stale quickly. The extension doesn't seem to be using that.

**Comment by danegsta** [comment]
Do you have a `docker-build` task in a tasks.json file for your project? If so, it may be missing the `pull` option (or have `pull` set to false). Our default task configuration enables passing the --pull flag in during build. See the docker-build task reference here: https://code.visualstudio.com/docs/containers/reference#_build-task-reference

**Comment by richlander** [comment]
I was using the context menu on the `Dockerfile`.

**Comment by bwateratmsft** [comment]
I think adding `--pull` to our [default Docker build command](https://github.com/microsoft/vscode-docker/blob/f85bcf60d1e20b7af9a8445d2001595a1e17518e/package.json#L1489) is definitely reasonable.

**Comment by richlander** [comment]
I do not. I just used the doc above.

I was using this sample: https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/tutorials/scalable-razor-apps/start

**Comment by richlander** [comment]
Odd. I don't know what happened before. I just tested this again. It works as expected.

```bash
 *  Executing task: docker build --pull --rm -f "Dockerfile" -t start:latest "." 
 ```

Sorry for the false report. Looks great!
