### ISSUE TITLE
=> ERROR [internal] load metadata for docker.io/library/busybox:latest 

### ISSUE THREAD

**Issue by visweswar5555955** [microsoft/vscode-docker#3872]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.24.0
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

**Comment by visweswar5555955** [comment]
yes its occuring even if i m entering correct id and pw of docker hub

**Comment by bwateratmsft** [comment]
@visweswar5555955 where does this error show up?
