### ISSUE TITLE
Docker extension does not find docker installed: Failed to connect. Is Docker installed?

### ISSUE THREAD

**Issue by horacioj** [microsoft/vscode-docker#3880]
Same as https://github.com/microsoft/vscode-docker/issues/3739, still happens running the latest 1.24.0 version.
Downgrading to 1.22.2 still works.

I have Docker Desktop (latest) v4.17.1, running in WLS mode on Windows 10 Home.

When running the docker vsc extension v1.24.0, the single entry in the Docker output was:

`[error] Failed to set up event listener: spawn docker EACCES`

Running v1.22.2 (showing containers and images without issues), in the output I see only this:

`The Docker extension will try to connect to 'npipe:////./pipe/docker_engine', via context 'default'.`

**Comment by bwateratmsft** [comment]
@horacioj what happens if you try to run Docker commands in the terminal in VSCode?

**Comment by horacioj** [comment]
@bwateratmsft, the command is opened not in the vsc console, but in a "popup"  windows that is started and closed. I cannot see what is in there. It is closed too fast.

Notice Docker is fine, and the extension v1.22.2 works fine.

**Comment by horacioj** [comment]
This is the vsc console:

![01](https://user-images.githubusercontent.com/984821/227994343-9ef5d375-1265-44ed-8865-9ee80b70af27.jpg)

When I hit enter after typing e.g. `docker ps` is this popup windows that appears and disappears very quickly.
![02](https://user-images.githubusercontent.com/984821/227994351-c5e955ce-3ddd-43da-a302-91f5a4e2c10a.jpg)

**Comment by bwateratmsft** [comment]
Huh, that's unusual. Is the behavior any different if you execute from _outside_ the VSCode terminal? e.g. from `cmd.exe`.

**Comment by bwateratmsft** [comment]
Do you have any value for the `docker.environment` VSCode setting?

**Comment by horacioj** [comment]
Nope (it is the same for"User" and "Workspace").

![04](https://user-images.githubusercontent.com/984821/228001797-38b9434b-7676-4402-b5ff-1747dd04f828.jpg)

**Comment by madlene** [comment]
I'm having the same issue. Are you on a Mac?

**Comment by bwateratmsft** [comment]
It seems likely that _something_ is different about the environment in VSCode vs. outside of it. Can you install 1.24 and follow the steps in [this comment](https://github.com/microsoft/vscode-docker/issues/3811#issuecomment-1409056748) and see if there's anything that stands out? The comment mentions using the nightly build but at this point the changes are in the 1.24 release.

Especially look for any `DOCKER_*` environment variables or the `PATH` environment variable.

@madlene a faily common issue we see on Mac is [items missing from the `PATH` environment variable](https://github.com/microsoft/vscode/issues/118460). Usually it can be fixed by setting the VSCode setting `docker.dockerPath` to `/usr/local/bin/docker`.

**Comment by horacioj** [comment]
Thank you for following up. Log sent to: danegsta at microsoft.com

Note: C:\Program Files\Docker\Docker\resources\bin is in the PATH.
The error is "[error] Failed to set up event listener: spawn docker EACCES" (first line in the log)

I'll now roll back to v1.22.2 again :)

**Comment by bwateratmsft** [comment]
Is VSCode being run as a different user?

**Comment by horacioj** [comment]
Both VSCode and Terminal are using my user account, with elevated permissions (run as admin).

**Comment by bwateratmsft** [comment]
That might be what's going wrong. I'm not sure, but I think that processes launched by VSCode will not be elevated--even when VSCode itself is. @isidorn do you know if on Windows, VSCode de-elevates itself, or the extension host process, or processes started by the extension host?

**Comment by horacioj** [comment]
Notice v1.22.2 works fine, on the exact same machine, user, etc.

**Comment by bwateratmsft** [comment]
That makes sense. The extension was substantially changed starting in 1.23 to no longer use Docker's HTTP endpoint, but to use the CLI instead. This saved us from a multitude of issues where the CLI was working but the explorer was not.

**Comment by mglatz** [comment]
same issue, can't even docker ps in terminal. Temporary fix is export DOCKER_HOST=unix:///var/run/docker.sock so that terminal commands work, but docker extension still does not see docker.

**Comment by yue0707** [comment]
I just set up a Hyper-V VM and install VSCode then use Tunnels to a Linux VM with proper docker installed. 

If you run other variants like Podman, vs will not pick it up. Some older versions I notice will do this too or anything not directly obtained from docker itself. However this will work w/o issue if you use Ubuntu and Docker official w/o any issues and no setup to Code. WSL doesn't work for this, not without messing with some networking/routing commands. Just easier to throw it on HyperV (for me). 

Some advantages I noticed too if you're sharing the system drive is with Hyper-V you'll be able to set your v-disk's IOPS to put a leash on what it can consume in bandwidth and dynamic memory works pretty flawlessly with docker. Out of 15 containers, we're sitting at 6GB total in-use.

**Comment by horacioj** [comment]
@stuartMulin, not available in Win 10 Home

**Comment by horacioj** [comment]
I've uninstalled the extension ¯\_(ツ)_/¯

**Comment by stuartMulin** [comment]
yes
________________________________

**Comment by stuartMulin** [comment]
That solution is what worked for me
________________________________
