### ISSUE TITLE
Investigate `docker init`

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#3882]
Docker Desktop is adding an `init` command that will do some scaffolding. We should look into how that works alongside VSCode and also see if it makes sense to eventually use it instead of our scaffolding logic.

https://github.com/docker/docs/pull/16982/files#diff-35670dabaa87c713655968d6149904b1fc6bcc3c757f36e19077ca91d9d4ffca
https://github.com/docker/roadmap/issues/453

**Comment by dbreshears** [comment]
Looks like there is only support for golang at this point.  No work in the Docker extension so moving to future

**Comment by dbreshears** [comment]
Closing lower priority
