### ISSUE TITLE
v0.1.0 not working with vscode 1.20.1

### ISSUE THREAD

**Issue by CodeJjang** [Microsoft/vscode-docker#389]
Hi,

I use vscode 1.20.1 on Ubuntu 16.04 due to some other extensions constraints. It is a version from May 2018.

After successfully installing this extension (v0.1.0) and reloading vscode, I get no errors, however the extension doesn't work. 

I don't see the icon in the left menu, no auto completion, etc. Seems like it silently fails somewhere.

When I view the extension in the enabled extensions section, it has a Reload button which never disappears even after several reloads. 

How can I further investigate and help with fixing the problem?

**Comment by rcjsuen** [comment]
@CodeJjang I don't think the 0.1.0 release runs on VS Code 1.20.1. You're going to need 1.23.x or higher it seems.

https://github.com/Microsoft/vscode-docker/blob/d61e273c6b6182549c5652022c29061e3de227c8/package.json#L634-L636

**Comment by CodeJjang** [comment]
0.27.0 doesn't work either :/  Despite its dependency on vscode ^1.0.0

**Comment by rcjsuen** [comment]
@CodeJjang There is no 0.27.0 release. Did you mean 0.0.27? That one is no different, it also depends on 1.23.x or higher.

https://github.com/Microsoft/vscode-docker/blob/d91c7c035fd41190c87cfb578d2b4afb610b4ffe/package.json#L607-L609

**Comment by rcjsuen** [comment]
Maybe you can try 0.0.24. That one seems to depend on 1.17.0 and up.

https://github.com/Microsoft/vscode-docker/blob/4a79464dc191e4fcc78e8902ae24af0d3ea1433b/package.json#L597-L599

**Comment by CodeJjang** [comment]
0.0.24 works :)
But the explorer doesn't show, despite the auto correction so work and also the config is "docker.showExplorer" is true

**Comment by StephenWeatherford** [comment]
Are you looking in the new view?  It no longer shows in the file explorer view.

![image](https://user-images.githubusercontent.com/6913354/44610336-98890780-a7b0-11e8-93e0-d1a65c88661d.png)
