### ISSUE TITLE
Add quay.io as registry option

### ISSUE THREAD

**Issue by fahlke** [microsoft/vscode-docker#390]
Hi!

I'm using [quay.io][quay-search] as my main registry and it is really missing in the extension. I'd really like to see this registry added in the near future.

[quay-search]: https://quay.io/search

**Comment by LeonardAukea** [comment]
This would be very nice to have!

**Comment by shaneholloman** [comment]
**Yes please** we use it here to serve all our client images

**Comment by StephenWeatherford** [comment]
Added to https://github.com/microsoft/vscode-docker/issues/869
