### ISSUE TITLE
Is Empty PORT EXPOSE By Design

### ISSUE THREAD

**Issue by gangachris** [Microsoft/vscode-docker#391]
I was generating a Dockerfile with the `> Dockerfile` command, and decided to leave the `PORT` section as an empty string, as I'm generating a base image that doesn't require exposing. This is what is generated 
<img width="457" alt="screen shot 2018-08-22 at 14 37 00" src="https://user-images.githubusercontent.com/3910877/44461281-e0752680-a618-11e8-8e3b-4a5f7a849fdc.png">

I know it's as easy as just deleting the last line, but I'm wondering if this is by design, or if someone doesn't specify a port, EXPOSE should not be generated.

**Comment by StephenWeatherford** [comment]
Ideally we will not add the EXPOSE if port is empty.

**Comment by StephenWeatherford** [comment]
Need to deal with compose files, too.

**Comment by PrashanthCorp** [comment]
Moving forward we won't be generating dockerfiles with empty expose statements. It shouldn't be an issue moving forward.
