### ISSUE TITLE
Fail to execute "Build Image..." command in windows container

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3915]
**OS:** Win 10
**Build Version:** 20230421.3
**Regression:** Previous Release 

**Repro Steps:**
1. Switch Docker Desktop to windows containers.
2. Open a .NET 8 MVC project in VS Code and add Docker Files to this project with Windows OS.
3. Right click the Dockerfile in this project and execute "Build Image..." command.
4. Check whether succeeds to execute "Build Image..." command or not.

**Expect:**
Succeed to execute "Build Image..." command.

**Actual:**
Fail to execute "Build Image..." command with an error.
![image](https://user-images.githubusercontent.com/45614674/234217241-c24fb275-9504-471e-902a-e1e93e9ab71a.png)

**More Info:**
1. The docker-build task shows as below, there is an incorrect platform definition in task.json. Remove the platform line, succeed to execute "Build Image..." command.
![image](https://user-images.githubusercontent.com/45614674/234217780-ddcc496b-d3a5-41be-92f7-726e2c683ec2.png)
2. Succeed to debug this project.
3. This issue also **reproduces** on the previous released **1.25.0**.
4. This issue does **not reproduce** on the previous released **1.24.0**.

**Comment by alexyaang** [comment]
Looks like it has something to do with the platform flag support here https://github.com/microsoft/vscode-docker/pull/3874

**Comment by alexyaang** [comment]
After discussing with @danegsta, it seems like the best **temporary solution** is to remove this line so the platform is not hard coded.  https://github.com/microsoft/vscode-docker/blob/4dcf9c68c1b40fec5b27f5ea4a244332e436f5b7/src/tasks/netcore/NetCoreTaskHelper.ts#L77 

However, in the next iteration, we should set the platform flag based on the local architecture of the computer (for release only) and the OS of the container chosen during wizard steps

**Comment by bwateratmsft** [comment]
We should get this fixed ASAP since it will affect scaffolding.
