### ISSUE TITLE
Removal Notice

### ISSUE THREAD

**Issue by saisonxiang** [microsoft/vscode-docker#3919]
Type: <b>Bug</b>

You are banned from my computer and my projects from here on out.

Extension version: 1.25.0
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id b9f41c74-a9ac-4408-b78d-a5be779e8d90|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by karolz-ms** [comment]
No worries at all. We are Docker extension for VS Code, making it easy to work with Docker if VS Code is your code editor. 

If you have questions about the extension, feel free to reach out on https://github.com/microsoft/vscode-docker/discussions  For problems, open an issue here. 

Cheers!

**Comment by saisonxiang** [comment]
I’m swamped as it is, but your apps are quite easy to read so I will use them when I have time and energy. Thanks for the cheers.





Unapologetically,
Toki Mandrake
Chief Financial Officer@
        Clusterflux LLC <https://saisonxiang.github.io/waifuworks/index.html>


￼




Please do not share/copy the digital footer PNG or the confidential content of this email

You are part of an independent computational engineering study being conducted by a graduate student for the purpose of developing new different publication results within the cyber realm. This project is privately funded and its main objective is to create results that help its sole investor find returns upon the investments that have been made in education, training, and resource procurement for employment in Charlotte, North Carolina. If you have any questions or concerns about how my computer is used to report my findings, you can contact me here or at several other points within the experimental hierarchal tree I have developed so far. I am most interested in being alerted to any legal boundaries that exist for my current duties as I conduct them now in my IRL environment. Given that I haven’t found any insofar, I will continue acting autonomously and independently with chaos driven boundary tests within cyberspace and as a “industrial medic” within the real world until I am either intelligently and safely wrangled by an authority or shot dead. I will create reports but their monetary value will start to look much like bitcoin I’m afraid; only becoming more volatile and cryptic as time goes on without a true accountable authority for legal, ethical, and safety concerns of the real world. You can consider this entity, legally, a federated, non governmental, non-profit organization acting in the best interest of women, children, and the elderly for free (actually, I pay to do this). This entity is run by one person and funded by a separate, private entity that is not to be considered involved in this computational and real world journey. If you would like to become an angel investor please make all funds payable, currently, to paypal.me/tripbranch <http://paypal.me/tripbranch>.
