### ISSUE TITLE
There is no validation for an existing web app name when executing "Deploy Image to Azure App Service..." command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#3920]
**OS:** Win 10
**Build Version:** 20230425.3
**Regression:** Previous Release

**Repro Steps:**
1. Navigate to "Registries" view -> Expand one ACR -> Right click one image and select "Deploy Image to Azure App Service..." -> Enter a web app name that already exists.
2. Check whether there is a validation "Hostname already exists" for an existing web app name.

**Expect:**
There is a validation "Hostname already exists" for an existing web app name.
![image](https://user-images.githubusercontent.com/45614674/234800644-a7e62978-36a7-4a5d-b5e7-704a815ef789.png)

**Actual:**
There is no validation for an existing web app name.
![image](https://user-images.githubusercontent.com/45614674/234800730-030e5a2c-2244-4f67-9ea0-0d0b944e458a.png)

**More Info:**
1. The validation appears after clicking "Enter".
2. This issue does not reproduce on the previous release version 1.25.0.

**Comment by bwateratmsft** [comment]
This may be due to some changes made recently in the way slow validation tasks are executed.

**Comment by bwateratmsft** [comment]
Yes, looks like that's it. @v-ruizh in some of the Azure extensions and in the Docker extension, we have changed slow validation tasks to only run when you try to hit <kbd>Enter</kbd>, and not as you are typing. Here's what I saw after trying to push <kbd>Enter</kbd>:

![image](https://user-images.githubusercontent.com/36966225/236210102-4b68ca18-7413-4d3f-bab5-894729f82e4e.png)
