### ISSUE TITLE
i have an error in vscode could not start java lang server

### ISSUE THREAD

**Issue by gauravpatil9021** [microsoft/vscode-docker#3926]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: TypeError
Error Message: Cannot read property '0' of undefined

Version: 1.1.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:226:318181extension.bundle.js:226:318181
Object.<anonymous> extension.bundle.js:1:494457
extension.bundle.js:1:492288extension.bundle.js:1:492288
s extension.bundle.js:1:491974
Object.callWithTelemetryAndErrorHandling extension.bundle.js:1:494365
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:226:318045
extensionHostProcess.js:712:440extensionHostProcess.js:712:440
```

</details>

**Comment by karolz-ms** [comment]
@gauravpatil9021 seems like you are using a very old version of VS Code. Please upgrade and try again. 

Feel free to open another issue if the problem still persists, but please add more information about when the error occurred--the automatically generated call stack alone is not very helpful.
