### ISSUE TITLE
Add & Honor Configuration Field For .NET Dockerfile Image builds

### ISSUE THREAD

**Issue by alexyaang** [microsoft/vscode-docker#3927]
We need to honor the .NET Configuration during Dockerfile Image build.

Since we have already added the `ARG` in https://github.com/microsoft/vscode-docker/pull/3924 to fix .NET Debugging with Docker Compose. We can add a `configuration` field to `netCore` to allow the user to override the `-c` flag to `Debug` or what they desire. 

## New Scenario
1. Create a new .NET app with `dotnet new mvc`
2. Scaffold the project with `Add Docker files`
3. Add `"configuration":"Debug"` under netCore in `docker-build: release`
4. Build image by running command `tasks -> docker-build: release`

## Expected Result:
The image should build in debug mode

## Notes
The `configuration` field is also used to determine build mode in .NET SDK builds and will be automatically scaffolded during .NET SDK build.

**Comment by bwateratmsft** [comment]
We have a "enableDebugging" field, we _could_ do Configuration=Debug for that, and release otherwise. Or something along those lines.

**Comment by dbreshears** [comment]
Can close this now that direction changed

**Comment by bwateratmsft** [comment]
Closing as dupe to #3808
