### ISSUE TITLE
Cannot get the popup container description to stay on screen so that I can copy info from it

### ISSUE THREAD

**Issue by huornlmj** [microsoft/vscode-docker#3933]
When I mouse hover over a container and I see the popup description of the mounts, volumes, ports, networks etc, it disappears when I try to copy the content from the box.  Some times it stays, sometimes it doesn't.  Please allow users to copy content from these popup boxes.

**Comment by bwateratmsft** [comment]
Unfortunately this is a limitation of VSCode's tree hover implementation, not something we can directly address. Can you file an issue on the https://github.com/microsoft/vscode/issues repository? If the hover could be made just a little bit sticky--a few hundred milliseconds where it would stay even though your mouse left the tree item--that could help. Or if the hover could be "pinned" or similar.
