### ISSUE TITLE
Task not found if same definition already exists

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-docker#3937]
I'm checking a new pre-release version (`0.38.2023051002`) of [Test Runner for Java](https://github.com/microsoft/vscode-java-test) extension that includes support for [postDebugTask](https://github.com/microsoft/vscode-java-test/issues/1557) property.

Trying to run a [docker-compose](https://code.visualstudio.com/docs/containers/reference#_compose-task-reference) type task after a test run I found that the specified task can't be found if the task definition (except for the **label**) is the same for other existing task (more detail [here](https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541920533)).

Should it be possible that an "optimization" (or something) is been done for **docker-compose** task definitions that prevents duplicates?

**Comment by bwateratmsft** [comment]
There are some oddities around VSCode's task system with respect to identifying different tasks. I'll ping some of the VSCode folks I know that work on this...

**Comment by bwateratmsft** [comment]
@meganrogge do you know what might be going on here? It seems like there's probably an ID conflict where the task label isn't being considered as part of the task ID.

**Comment by rubensa** [comment]
Hi @meganrogge 

Just checked with VSCode Insiders latest version (1.79.0-insiders from code-insider-x64-1683697471.tar.gz) and I got the same error message:

`Could not find the task 'Teardown test-local'.`

if the task definitions for "_Teardown test-local_" and "_Teardown test-snowflake_" (as specified [here](https://github.com/microsoft/vscode-java-test/issues/1557#issuecomment-1541429757)) are the same but works if I change, for example, the `down` tag in one of them.

**Comment by rubensa** [comment]
As a side note, just realized that looks like the last one defined is the only one available (found).  Any previous definition that matches the same configuration are removed.

**Comment by meganrogge** [comment]
thanks for the info. i'm pretty sure this has been identified in prior versions and is working as designed. Is there a reason you cannot have a unique definition?

**Comment by bwateratmsft** [comment]
I can't transfer this issue to the VSCode repository but it sounds like it's external. I'll close the issue but it will stay unlocked so the discussion can continue as needed.

**Comment by rubensa** [comment]
@bwateratmsft Then, where should I report this issue? :confused:

**Comment by bwateratmsft** [comment]
https://github.com/microsoft/vscode/issues would be the best place to report it.
