### ISSUE TITLE
Google container registry?

### ISSUE THREAD

**Issue by chadbr** [microsoft/vscode-docker#394]
Any chance to add support for Google Container Registry?

---

![Image of runforit](https://media.giphy.com/media/NzrVgcbz3pXlS/giphy.gif)

**Comment by rcjsuen** [comment]
See #18 and other referenced issues.

**Comment by StephenWeatherford** [comment]
Although I hate closing your fitting GIF :-), this is being tracked in https://github.com/microsoft/vscode-docker/issues/869.
