### ISSUE TITLE
Cannot debug pytest tests in docker

### ISSUE THREAD

**Issue by ilaner** [microsoft/vscode-docker#3946]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: 1.78.2
OS Version: Darwin x64 22.4.0
I'm trying to debug pytest tests inside Docker. I understand it's not supported by the Python VSCode extension yet, but I followed this guide to setup this.

My tasks.json file:
```
{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "docker-run",
        "label": "docker-run: test",
        "python":{ 
          "module": "pytest",
          "args": ["."],
        },
        "platform": "python",
        "dockerRun": {
            "image": "<my-image-tag>",
            "volumes": [
                {
                    "localPath": "${workspaceFolder}",
                    "containerPath": "/app"
                    
                },
            ],

          }

      }
    ]
  }
```
My launch.json file:
```
{
  "version": "2.0.0",
  "configurations": [
    {
      "name": "Docker: Debug tests in docker",
      "type": "docker",
      "request": "launch",
      "preLaunchTask": "docker-run: test",
      "python": {
        "pathMappings": [
          {
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
          }
        ],
        "projectType": "general",
        "justMyCode": false,

      }
    }
  ]
}
```
If I hit Debug and Run, all the tests are running, but it doesn't stop on VSCode breakpoints. I tried using the -k argument for specific test, but it still doesn't work. However, I'm able to debug the pytest internal module, but not my code. In addition, I can debug properly regular python files as expected.
Steps to Reproduce:

1. Set the tasks.json and launch.json to .vscode directory.
2. Set breakpoints on the test
3. The test fail/pass, but without entering the breakpoint

**Comment by bwateratmsft** [comment]
Generally when the debugger attaches but breakpoints aren't hit, there's something wrong with source maps. But this sure looks like it should work; in both tasks.json and launch.json, `/app` in the container is mapped to `${workspaceFolder}` on the host.

Is there any info given in the Python Debug output window?

**Comment by ilaner** [comment]
Not really, this is the log from the python output window:
```
2023-05-19 17:59:53.703 [info] Send text to terminal:  /usr/bin/env /Users/<user>/dev/demisto/content/Packs/GenericSQL/Integrations/GenericSQL/venv/bin/python /Users/ierukhimovic/.vscode/extensions/ms-azuretools.vscode-docker-1.25.1/resources/python/launcher.py 49159 -- -m pytest --override-ini junit_family=xunit1 -vv --log-cli-level=INFO -s --rootdir /app/Packs/GenericSQL/Integrations/GenericSQL /app/Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py docker genericsql-dev 
```

Note that if debug a file in the same case (and not the `pytest` module), the debugger works great. In addition, I managed to stop on a breakpoint of the `pytest` module, and was abale to debug until the actual tests were executed in the code.

**Comment by bwateratmsft** [comment]
Can you show the output of the `docker-run` task that is run before the app is launched? I wonder if the debugger is not being mapped in.

**Comment by ilaner** [comment]
This is the output of the docker-run task:
```
> docker container run --detach --tty --name 'genericsql-dev' --publish-all --mount 'type=bind,source=/Users/<user>/dev/demisto/content,destination=/app' --mount 'type=bind,source=/Users/<user>/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy,destination=/debugpy,readonly' --label 'com.microsoft.created-by=visual-studio-code' --entrypoint 'python3' devtestdemisto/genericsql:1.1.0.56304-f1a8a03f0d4031309fa67e5b6b566d13 <

a1a0f5d505657484e653e7e72fd506c671fe0304a4b0e3d28915fd87a5dd2819
```
I believe the debugger is attached and I'm able to debug the pytest module:
<img width="1045" alt="image" src="https://github.com/microsoft/vscode-docker/assets/88267954/ca5ac7f9-c94a-4c2f-9edf-3523d34a8cfa">

I believe the bug is specific to `pytest` (and maybe more modules that use the same logic).

**Comment by bwateratmsft** [comment]
That breakpoint hit is definitely a good sign! Does pytest run the tests in a separate process?

**Comment by ilaner** [comment]
I don't know the pytest implementation, but it sounds reasonable the tests are executed in a different process

**Comment by bwateratmsft** [comment]
I just found this StackOverflow thread that looked interesting: https://stackoverflow.com/questions/69912836/pytest-breakpoints-in-tests-are-being-skipped-when-debugging-with-vscode

There were several answers that all looked like they may help.

**Comment by ilaner** [comment]
I don't understand, how can I change the docker run configuration accordingly?

**Comment by bwateratmsft** [comment]
I'm not sure honestly, I don't know enough about Pytest. You could try creating a discussion in the Pytest repo? https://github.com/pytest-dev/pytest/discussions

**Comment by ilaner** [comment]
I opened a [discussion](https://github.com/pytest-dev/pytest/discussions/11023) in their community, but I really appreciate the team will take a look on this as well. I think it's important to debug files and modules properly.

**Comment by ilaner** [comment]
@bwateratmsft I think the issue is somewhere in the Docker extension.
I tried the following configuration:
```
    {
      "name": "Python: test",
      "type": "python",
      "request": "launch",
      "module": "pytest",
      "args": [
        "-s",
        "--no-cov",
        "."],
      "console": "integratedTerminal",
      "justMyCode": false
    },
```
This configuration is the same as I did in the `docker-run` task, with the same arguments. However, this configuration works and I'm able to debug the actual tests (as well as the `pytest` module).

**Comment by ilaner** [comment]
I upgraded the pytest version in the image and now it works as expected.

**Comment by bwateratmsft** [comment]
Awesome! Glad to hear it's working now.
