### ISSUE TITLE
"Invalid image inspect json" error while running an image

### ISSUE THREAD

**Issue by adandev1125** [microsoft/vscode-docker#3947]
![Screenshot from 2023-05-19 21-36-38](https://github.com/microsoft/vscode-docker/assets/131336201/e6a5bf9a-744b-4b87-92b6-7af4b9e0b472)

I have a problem with VSCode Docker extension.
Building with this extension has no problem and successfully build images.
Command "docker run" runs the image successfully and "docker inspect" also shows an inspect json.
But when I tried to run an image with this extension, it showed error: "Invalid image inspect json". (I attached my screenshot)
I'm working on Ubuntu 22.04 and Docker 24.0.0.
Please help me to use this extension.
Look forward to your help.

**Comment by bwateratmsft** [comment]
@adandev1125 can you share the full contents of the image inspect JSON? You can redact any parts that you need to, we're mostly interested in seeing the structure and what fields are present.

**Comment by adandev1125** [comment]
This is the inspect json.

[
    {
        "Id": "sha256:85ddebfd793e22c89076c71366ea7223ffa0275d9a8d83248b6191b4a6f89695",
        "RepoTags": [
            "gomvc:latest"
        ],
        "RepoDigests": null,
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-05-19T21:35:04.181215369+03:00",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "/go-mvc"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 17809328,
        "VirtualSize": 17809328,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ut3u8hne9czq0ygo2oynza1ol/diff:/var/lib/docker/overlay2/7ig5trvby30g313jryrvj0rpb/diff:/var/lib/docker/overlay2/jdi34o1b92g0j568htfn5aryt/diff:/var/lib/docker/overlay2/x4ac5ozcdrrgog3urujq7ltof/diff:/var/lib/docker/overlay2/62f9r4z5zttajxpabpq7veot6/diff:/var/lib/docker/overlay2/4dc0afaf9bba575b2fb2a5fd0c3d37e646e311be5f4899679b3bd5b747daaa27/diff",
                "MergedDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/merged",
                "UpperDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/diff",
                "WorkDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:bb01bd7e32b58b6694c8c3622c230171f1cec24001a82068a8d30d338f420d6c",
                "sha256:1898c2ea40f5a60e198aaffedf5f83bb7bd655d94b747ce3258e168dab6c3441",
                "sha256:abce1419c43a7312e5f02c9dd3930c9328532623d39a445ffa7c7b8365dd1239",
                "sha256:b4202a0c6016cdf588bcd1476b861f7452e6097d8ae4250570c807d57c49de27",
                "sha256:867f91b62f53c5638189cf02d1378573600503614a8bf6a798cdcf7dfe6dcea1",
                "sha256:b49cb00ef9a2f7726aeaf455ca8e6cd6b5bd9787896295ca1a46667bff86a313",
                "sha256:6e6dd0007a63e89ef08b87e1c409f2e44ee5e099efc5d2d9250ff7ba3502a3da"
            ]
        },
        "Metadata": {
            "LastTagTime": "2023-05-19T22:05:42.461115321+03:00"
        }
    }
]

**Comment by adandev1125** [comment]
`[
    {
        "Id": "sha256:85ddebfd793e22c89076c71366ea7223ffa0275d9a8d83248b6191b4a6f89695",
        "RepoTags": [
            "gomvc:latest"
        ],
        "RepoDigests": null,
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-05-19T21:35:04.181215369+03:00",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "/go-mvc"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 17809328,
        "VirtualSize": 17809328,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ut3u8hne9czq0ygo2oynza1ol/diff:/var/lib/docker/overlay2/7ig5trvby30g313jryrvj0rpb/diff:/var/lib/docker/overlay2/jdi34o1b92g0j568htfn5aryt/diff:/var/lib/docker/overlay2/x4ac5ozcdrrgog3urujq7ltof/diff:/var/lib/docker/overlay2/62f9r4z5zttajxpabpq7veot6/diff:/var/lib/docker/overlay2/4dc0afaf9bba575b2fb2a5fd0c3d37e646e311be5f4899679b3bd5b747daaa27/diff",
                "MergedDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/merged",
                "UpperDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/diff",
                "WorkDir": "/var/lib/docker/overlay2/kyvk1eu4d8fnm0zc7ydb2kvtz/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:bb01bd7e32b58b6694c8c3622c230171f1cec24001a82068a8d30d338f420d6c",
                "sha256:1898c2ea40f5a60e198aaffedf5f83bb7bd655d94b747ce3258e168dab6c3441",
                "sha256:abce1419c43a7312e5f02c9dd3930c9328532623d39a445ffa7c7b8365dd1239",
                "sha256:b4202a0c6016cdf588bcd1476b861f7452e6097d8ae4250570c807d57c49de27",
                "sha256:867f91b62f53c5638189cf02d1378573600503614a8bf6a798cdcf7dfe6dcea1",
                "sha256:b49cb00ef9a2f7726aeaf455ca8e6cd6b5bd9787896295ca1a46667bff86a313",
                "sha256:6e6dd0007a63e89ef08b87e1c409f2e44ee5e099efc5d2d9250ff7ba3502a3da"
            ]
        },
        "Metadata": {
            "LastTagTime": "2023-05-19T22:05:42.461115321+03:00"
        }
    }
]`

**Comment by bwateratmsft** [comment]
It looks like the image has `null` for the `RepoDigests` field. How was it built?

**Comment by adandev1125** [comment]
I built it with Docker Extension -> "Build Image" for Dockerfile.

**Comment by bwateratmsft** [comment]
Can you share your Dockerfile?
