### ISSUE TITLE
Please stop nagging to install this extension

### ISSUE THREAD

**Issue by HankB** [microsoft/vscode-docker#3951]
It's annoying. I have Docker installed so I can run Docker images I pull form the hub. I do not edit Docker files on this host.

The popup is a minor annoyance but if every extension author popped up a nag to install their package for every facility I have on this host, it would be a major problem.

If I ever open a Dockerfile feel free to pop up a reminder. Otherwise, Just. Please. Stop.

**Comment by bwateratmsft** [comment]
Extension recommendations are done by VSCode itself, not by the extension. There should be a way to suppress the recommendation for any particular extension or all recommendations. If that's not working, can you file an issue at https://github.com/microsoft/vscode/issues ?
