### ISSUE TITLE
docker compose V2 ?

### ISSUE THREAD

**Issue by rpa275** [microsoft/vscode-docker#3958]
Will the extension support the V2 of docker compose, which removes the hyphen from docker-compose ?  Believe they are phasing it out of their releases at the end of June 2023.

**Comment by bwateratmsft** [comment]
Yes, it supports Compose V2 and has for quite some time. It should also be backward-compatible to V1, automatically detecting what is present. We use the command `docker compose version` to [check if V2 compose is available](https://github.com/microsoft/vscode-docker/blob/81c873db5967a8edbac6e18b18ffd80a90163aeb/src/runtimes/clients/AutoConfigurableDockerComposeClient.ts#L61).

Are you still seeing `docker-compose` commands used somewhere?

**Comment by rpa275** [comment]
Yes, when I am in VSCode, right click on the docker-compose.yml file and compose, the command in the terminal shows 
 *  Executing task: docker-compose -f "docker-compose.yml" up -d --build 

WARNING: Compose V1 is no longer supported and will be removed from Docker Desktop in an upcoming release. See https://docs.docker.com/go/compose-v1-eol/
Creating network "cat_ld-network" with driver "bridge" 
 
 similar when running compose down after right clicking the running container

**Comment by bwateratmsft** [comment]
Can you check that `docker.composeCommand` setting and also run `docker compose version` in a terminal and share the output?

**Comment by rpa275** [comment]
docker compose version                                                                                                                                           ✔ 
Docker Compose version v2.18.1


looks like the docker extensions settings.json showed docker-compose in there (image attached).  Believe I just need to take the hyphen out myself to fix?

![image](https://github.com/microsoft/vscode-docker/assets/71098918/efd10fa6-23ba-4ff2-9f12-11ed062bf036)

**Comment by rpa275** [comment]
that worked!  Thanks!
