### ISSUE TITLE
issue to connect vs code to docker and it  is not finding docker is running

### ISSUE THREAD

**Issue by salonikareer** [microsoft/vscode-docker#3959]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.25.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

**Comment by salonikareer** [comment]
PS C:\Users\saloni\New folder\django> docker version
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

**Comment by bwateratmsft** [comment]
@salonikareer is Docker running? Are you using Docker Desktop or a different setup?

**Comment by joewidd** [comment]
I'm having the same issue on MacOs ventura 13.4. I rolled the extension back to 1.22.0 as suggested on an older bug thread  and it fixed it for me.

**Comment by bowdenk7** [comment]
Rolling back to 1.22.0 fixed for me as well

**Comment by alexyaang** [comment]
@joewidd @bowdenk7 Thanks for bringing this to our attention. Are you able to run Docker commands from within the VS Code terminal? For example, what do you get after running `docker ps`?

**Comment by joewidd** [comment]
> @joewidd @bowdenk7 Thanks for bringing this to our attention. Are you able to run Docker commands from within the VS Code terminal? For example, what do you get after running `docker ps`?

Yes, I'm able to run docker commands in the vs code terminal. It was just the extension not being about to connect to docker.

**Comment by bwateratmsft** [comment]
It's not uncommon for Mac to exhibit problems like this because of `PATH` issues (i.e. https://github.com/microsoft/vscode/issues/118460). @joewidd @bowdenk7 if you set the VSCode setting `docker.dockerPath`, to the path emitted by `which docker` (usually `/usr/local/bin/docker` on Mac with Docker Desktop), do things work?

**Comment by joewidd** [comment]
> It's not uncommon for Mac to exhibit problems like this because of `PATH` issues (i.e. [microsoft/vscode#118460](https://github.com/microsoft/vscode/issues/118460)). @joewidd @bowdenk7 if you set the VSCode setting `docker.dockerPath`, to the path emitted by `which docker` (usually `/usr/local/bin/docker` on Mac with Docker Desktop), do things work?

I'll give this a shot today and let you know if that's the solution.

**Comment by UnixMonky** [comment]
This resolved the issue for me.  After updating the VSCode setting it was only about 5-10 seconds before the panels populated.

**Comment by fckfizz** [comment]
well I sorted the little glitch, don't know exactly how. Something to do with deleting VS docker extension and using docker explorer and add file sharing pathway in resources ? Gobbledegook to me but you lot might make sense of it. Cheers anyways

**Comment by joewidd** [comment]
> It's not uncommon for Mac to exhibit problems like this because of `PATH` issues (i.e. [microsoft/vscode#118460](https://github.com/microsoft/vscode/issues/118460)). @joewidd @bowdenk7 if you set the VSCode setting `docker.dockerPath`, to the path emitted by `which docker` (usually `/usr/local/bin/docker` on Mac with Docker Desktop), do things work?

Sorry for the late response but this fixed my extension! Thank you!

**Comment by bwateratmsft** [comment]
@salonikareer any updates?

**Comment by Olumuyiwa** [comment]
Thanks @bwateratmsft. It worked

**Comment by Olumuyiwa** [comment]
![image](https://github.com/microsoft/vscode-docker/assets/3593622/3e563374-fe28-4c56-ad77-43360d8af732)

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
