### ISSUE TITLE
Fuse defaultRegistry and defaultRegistryPath settings into one setting.

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#396]
Note: If a user already has both set, we should either warn the user about it, or change the setting ourselves.

**Comment by StephenWeatherford** [comment]
@chrisdias Chris, just making sure we aren't making a mistake by combining these two.  Having them separate is confusing, and they're just being joined together anyway.  Is there any reason to keep them separate?  The new design is, e.g.:
   "defaultRegistryPath": "sweatherford/hello-world"
Thx.

**Comment by chrisdias** [comment]
Looking back, I think it will be ok to fuse these two together.
