### ISSUE TITLE
VSCode fails to connect to my Docker setup on Mac OS Ventura 13.4

### ISSUE THREAD

**Issue by Olumuyiwa** [microsoft/vscode-docker#3968]
Do you know if this happens regularly? Yes

Steps taken 
Step A: I downloaded and installed the latest M1-compatible Docker installation and it was successful. I started my containers successfully but my VS Code "Failed to connect"

Step B: I tried re-installing from VSCode twice but it seems VSCode uses the .dmg installation file for Mac with Intel chips so it failed during installation since the machine I have is an M1 device.

I have restarted my machine and retried step A, but there is no difference.

Version: 1.25.1
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

**Comment by bwateratmsft** [comment]
@Olumuyiwa if you follow the workaround in [this comment](https://github.com/microsoft/vscode-docker/issues/3959#issuecomment-1584484417) does that fix your issue?

**Comment by bwateratmsft** [comment]
Closing per https://github.com/microsoft/vscode-docker/issues/3959#issuecomment-1587686281
