### ISSUE TITLE
Determine Type of .NET App from build file

### ISSUE THREAD

**Issue by alexyaang** [microsoft/vscode-docker#3972]
When scaffolding docker files, we prompt the user with the following, including ".NET: ASP.NET Core" and ".NET: Console". However, we could determine the type of .NET file by looking at the `.csproj` file. In other words, we can consolidate the two into one called ".NET" option and use code logic to determine whether it's a web app. After this, we can also do something similar with Python to prompt users with less options to avoid confusion. 

<img width="637" alt="Screenshot 2023-06-14 at 1 40 38 PM" src="https://github.com/microsoft/vscode-docker/assets/59073590/b775ced1-5b22-4906-b52f-6f826eca09e6">

**Comment by dbreshears** [comment]
Won't fix as lower priority.
