### ISSUE TITLE
docker installed but report command not found

### ISSUE THREAD

**Issue by realhuyi** [microsoft/vscode-docker#3975]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.8.1
OS: darwin
OS Release: 20.6.0
Product: WeChat Web Devtools
Product Version: 1.52.0
Language: zh-CN

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:98044
```

</details>

**Comment by bwateratmsft** [comment]
@realhuyi can you try the workaround in https://github.com/microsoft/vscode-docker/issues/3959#issuecomment-1584484417 and see if that works?

**Comment by realhuyi** [comment]
yes,it works, when I start IDE by command line from terminal window

**Comment by bwateratmsft** [comment]
Sounds like it's the same issue as https://github.com/microsoft/vscode-docker/issues/3959#issuecomment-1584484417 then. I'll resolve this as a duplicate.
