### ISSUE TITLE
Docker Extension Icon Not Showing On Activity Bar

### ISSUE THREAD

**Issue by MinamiHasaki** [microsoft/vscode-docker#3978]
OS: Windows 10 Enterprise 19045.3086
Browser: Google Chrome 114.0.5735.134
Remote OS: Ubuntu 22.04.2 LTS
VS Code: 1.79.2
Remote - Tunnels Extension: v1.2.1
Docker Extension: 1.25.1

I'm using VS Code remotely.  I'm using the Visual Studio Code Remote - Tunnels to connect to an Linux machine running the tunnel service via VS Code CLI.

I've installed the Docker extension and the icon isn't showing up in the activity bar even though I can click it and use the extension.

![image](https://github.com/microsoft/vscode-docker/assets/20251864/c14b6b1a-e55a-4969-b61c-37833c22cf72)

**Comment by bwateratmsft** [comment]
@MinamiHasaki this must be a VSCode issue. Can you open one there? https://github.com/microsoft/vscode/issues

**Comment by MinamiHasaki** [comment]
Sure sure. Thanks.
