### ISSUE TITLE
Docker Desktop already installed.But following are thrown when open vscode-docker

### ISSUE THREAD

**Issue by Yeenyeong** [microsoft/vscode-docker#3980]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 127
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 127
Error: /bin/sh: docker: command not found

Version: 1.8.1
OS: darwin
OS Release: 21.6.0
Product: WeChat Web Devtools
Product Version: 1.52.0
Language: zh-CN

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:98044
```

</details>

**Comment by bwateratmsft** [comment]
Also, this is a pretty old version of the Docker extension, I'd recommend updating.
