### ISSUE TITLE
vs code not prperly worked

### ISSUE THREAD

**Issue by SASWAJIT** [microsoft/vscode-docker#3989]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.25.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

**Comment by SASWAJIT** [comment]
in vs code after writting somethhing of a word the functionality of the word not wroked

**Comment by alexyaang** [comment]
@SASWAJIT this sounds like a VSCode issue. Can you open one there? https://github.com/microsoft/vscode/issues
