### ISSUE TITLE
Recognize docker compose symlinks

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode-docker#399]
In this environment I have done:

```bash
ln -s devel.yaml docker-compose.yml
```

![captura de pantalla de 2018-08-23 10-55-50](https://user-images.githubusercontent.com/973709/44519006-b0369200-a6c3-11e8-9314-b24f2352d431.png)

`docker-compose` recognizes that correctly automatically, but when I trigger any docker compose command with this extension, it says: _Couldn't find any docker-compose files in your workspace._

If `docker-compose.yml` is a real file, however, it recognizes it.

Please allow us using symlinks! Thanks! :blush:

**Comment by StephenWeatherford** [comment]
Might be a vscode issue with workspace.findFiles.

**Comment by bwateratmsft** [comment]
Tested it out, this no longer seems to be an issue on Windows or Mac, on VSCode 1.45 with Docker 1.2.0.
