### ISSUE TITLE
Feature: Buildx bake HCL schema

### ISSUE THREAD

**Issue by mckelveygreg** [microsoft/vscode-docker#3994]
Not sure if this is the right spot for a feature request, but I just started working with the new bake file syntax and noticed there doesn't seem to be any support for syntax highlighting inside of a `.hcl` file?

[Hashicorp has a general extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL) for `.hcl` files, but it would be nice of course to have all of the docker fields available!

Would love to at least kick off the discussion!

**Comment by danegsta** [comment]
@mckelveygreg from past experience, trying to have two competing syntax highlighting implementations for a specific language gets messy quickly; I'd suggest opening up an issue on the existing [hcl extension](hashicorp/vscode-hcl) or [syntax implementations](hashicorp/syntax) to request support for the bake file specific usage of hcl since that would provide the most straightforward path to proper syntax highlighting.

**Comment by mckelveygreg** [comment]
I took a look at those repos, and I think I original talked about the wrong thing, a syntax highlighting implantation, which Hashicorp's [vscode-hcl](https://github.com/hashicorp/vscode-hcl/) already provides. 

They say they will highlight anything, but to get any intellisense, [that is up to the language provider to make a schema available.](https://github.com/hashicorp/vscode-hcl/issues/240) 

Could this extension instead provide a docker bake [hcl schema](https://github.com/hashicorp/hcl-lang#what-is-schema)?

**Comment by ruffsl** [comment]
> I'd suggest opening up an issue on the existing [hcl extension](https://github.com/microsoft/vscode-docker/issues/hashicorp/vscode-hcl) or [syntax implementations](https://github.com/microsoft/vscode-docker/issues/hashicorp/syntax) to request support for the bake file specific usage of hcl since that would provide the most straightforward path to proper syntax highlighting.

@danegsta, as @mckelveygreg noted, it looks like the onus for docker domain specific support isn't on `vscode-hcl`:

- https://github.com/hashicorp/vscode-hcl/issues/240#issuecomment-1534277260

> Could this extension instead provide a docker bake [hcl schema](https://github.com/hashicorp/hcl-lang#what-is-schema)?

@mckelveygreg, is there an official schema for bake files yet? I couldn't find an static schema file detentions in the buildx repo:

- https://github.com/search?q=repo%3Adocker%2Fbuildx+HCL+-language%3AHCL+schema&type=code

**Comment by bwateratmsft** [comment]
Sounds like we'd need to build a language service for this scenario which is a huge undertaking. For now we'll won't-fix unless we get more feedback that this is necessary.
