### ISSUE TITLE
Displaying remote image manifest similarly to inspecting local images

### ISSUE THREAD

**Issue by michalpokusa** [microsoft/vscode-docker#3996]
Issue Type: **Feature Request**

Issue is about adding an additional option to RMB context menu when clicking a specific tag of image on remote repository.

For example, under "Copy Image Digest" might be option called "Manifest", there could also be command for that - "Docker Registries: Manifest".

![image](https://github.com/microsoft/vscode-docker/assets/72110769/cac4b665-a81e-4c94-b55e-1fbdd659d43a)
_(Current context menu)_

The idea is, that for now it is impossible to _inspect_ a image without pulling it first. This command would allow getting more information about remote images without doing that.

After running the command the manifest would open similarly as the result of running "Inspect" on local image:

![image](https://github.com/microsoft/vscode-docker/assets/72110769/a0682a63-e68b-4b82-896a-a362eae5afda)
_(Visualisation how this could look like)_

When it comes to implementing it, self-hosted repositories allow it simply by doing a specific GET request to API v2, i do not know how it works in Azure, GitLab and Docker HUb, but I believe they also allow is one way or another.

**Comment by bwateratmsft** [comment]
IIRC we are actually doing the manifest fetch in the background for something--can't recall exactly what--but it shouldn't be too hard to add a command to do the same.

**Comment by michalpokusa** [comment]
> The manifest information is different from image inspect but IMO still interesting.

Yes, of course. Nevertheless the manifest itselt can be usefull. I only compared it to Inspect in order to visualize the behaviour.

**Comment by bwateratmsft** [comment]
This has been released in Docker extension version 1.28.0.
