### ISSUE TITLE
Dockerfile language detection is too generic

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-docker#40]
If you open a file that starts with `dockerfile`, regardless what it's extension is (e.g. `dockerfilewhatever.foo`), it will be detected as a Dockerfile, which I'm not sure makes sense. Having this VS Code extension simply detect `Dockerfile` or `dockerfile` (with the former being the standard) seems reasonable and should cover most use cases, without introducing any false positives.

**Comment by PeterJausovec** [comment]
See issue #15. Support for files named ```Dockerfile*``` was added on purpose, because there were cases of multiple dockerfiles in the same folder.

**Comment by lostintangent** [comment]
Ah Ok. I'll close this issue then. Thanks!
