### ISSUE TITLE
Support mapping arbitrary port/protocols as declared in image metadata for .NET SDK Containers

### ISSUE THREAD

**Issue by baronfel** [microsoft/vscode-docker#4001]
Image configuration metadata has an `ExposedPorts` property that contains key/value pairs of the form:

```json
"ExposedPorts": {
 "<PORT>[/<PROTOCOL>]": {}
}
```

where `<PORT>` is a number and the optional `<PROTOCOL>` is one of `tcp` or `udp` (`tcp` if not specified). It would be great if this tooling could inspect those values and automatically map available ports from the host to these declared ports for ease of access for the .NET SDK-built containers, too!

**Comment by alexyaang** [comment]
This is for the .NET SDK build & run specifically. Ports are hard coded as (8080 and 80) currently. This would allow us to honor the user's ports config.

**Comment by dbreshears** [comment]
Should these default ports be exposed via the SDK?

**Comment by alexyaang** [comment]
This issue is being tracked in the SDK container build repo https://github.com/dotnet/sdk-container-builds/issues/478

**Comment by alexyaang** [comment]
Just validated that this has been added in .NET 8 RC1
