### ISSUE TITLE
Show reclaimed space after pruning

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode-docker#4002]
The extension used to report how much space was freed, which was nice as a little check to know whether the action did anything. Somewhere along the lines the notification stopped saying how much space was reclaimed, and it would be nice to have that back so I don't have to go to the command line to see it.

**Comment by bwateratmsft** [comment]
This was something we lost with the move to CLI only in 1.23.0, but I think it should be possible to parse the CLI's plaintext output and give the results.
