### ISSUE TITLE
An error occurs when debugging a MVC project in Windows container

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4005]
**OS:** Win 10
**Build Version:** 20230712.5
**Regression:** Not a regression

**Repro Steps:**

1. Switch Docker Desktop to Windows containers.
2. Create and open a .NET 8.0 MVC project in VS Code, make sure it doesn't have 'launch.json' file.
3. F5 -> Select 'Docker: Debug in Container' -> Select 'Use .NET SDK'.
3. Check whether succeeds to debug.

**Expect:**
Succeed to debug.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/11356c22-a869-4a44-ae8b-c59d39836598)

**More Info:**
This issue also reproduces when debugging Multi Project.

**Comment by alexyaang** [comment]
This did not reproduce for me on an single .csproj .NET 7 web app or a multi proj .NET 7 solution. What error output are you seeing in the terminal or debug console?

**Comment by v-chenzha** [comment]
@alexyaang  The details of the terminal and .csproj file get from below:
![image](https://github.com/microsoft/vscode-docker/assets/107091828/18a28d33-7610-4c51-822d-b5f295336643)

![image](https://github.com/microsoft/vscode-docker/assets/107091828/ed4a2d33-d9e5-4ddb-a980-2e1cb1e2ef99)

**Comment by alexyaang** [comment]
I see. From the error message, it seems like `win-x64` is not supported. I'm going to dig deeper into the RunIds and see what we can do for windows containers targeting x64 architecture.

**Comment by danegsta** [comment]
@alexyaang that's expected behavior for .NET 8 (see https://github.com/dotnet/dotnet-docker/discussions/4549). There's a [work item](https://github.com/dotnet/sdk-container-builds/issues/413) on the SDK team to generate proper default Windows base images for .NET 8.

**Comment by alexyaang** [comment]
@danegsta  Gotcha, that makes sense!

**Comment by dbreshears** [comment]
Tracking bug in .NET containers SDK was won't fixed.    Going to close this
