### ISSUE TITLE
An error occurs when debugging a NET 8.0 console project without any scaffolding

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4007]
**OS:** Mac&Windows
**Docker Extension Build Version:** 20230712.5
**.NET Version:** 8.0.100-preview.5.23303.2

**Repro Steps:**
1. Create a .NET 8.0 console project by command `dotnet new console --name consoleapp` -> Open it in VS Code.
2. Make sure the project doesn't have `Launch.json` file.
3. Make sure the `TargetFramework` property inside the `.csproj` file is equal to `net8.0`.
4. F5 -> Select "Docker: Debug in Container" -> Select "Use .NET SDK".
5. Check whether succeeds to debug.

**Expect:**
Succeed to debug.

**Actual:**
An error occurs.
<img width="449" alt="Screenshot 2023-07-13 at 14 44 06" src="https://github.com/microsoft/vscode-docker/assets/57662131/9dd0d5cb-3d2d-4b7f-b4ba-cea27b4a1971">

**More Info:**
This issue also reproduces for the .NET 7.0 mvc project and only install .NET 7 on the machine.

**Comment by alexyaang** [comment]
This is actually expected for a console app created from the command `dotnet new console --name consoleapp`. You'll have to make a few additions to the .csproj file to make it work with SDK Container build. 

What does your .csproj look like?

**Comment by v-xinda** [comment]
@alexyaang  The details of the .csproj file get from below:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

**Comment by alexyaang** [comment]
Yeah that makes sense. Try replacing the first line with `<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">` and it should work! You should see something like this:

![image](https://github.com/microsoft/vscode-docker/assets/59073590/0a978755-91ab-4d3d-b429-1f286df18de1)

**Comment by v-xinda** [comment]
@alexyaang  For the .NET 8.0 console project, this issue is fixed after changing the "Project Sdk" in the .csproj file. The updated .csproj file as below:
```
<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

**But the .NET 7.0 mvc/console project, this issue also reproduces after changing the "Project Sdk" in the .csproj file.**

**Comment by alexyaang** [comment]
Gotcha, this is expected behavior from the .NET SDK.

**Comment by v-xinda** [comment]
@alexyaang  The details after executing `dotnet --info`:
```
C:\Users\AzureTest>dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.412 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by alexyaang** [comment]
@v-xinda I overlooked your comments earlier. Only put `<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">` if it's a console app. Leave the first line the same if it's a MVC app (e.g. `<Project Sdk="Microsoft.NET.Sdk.Web">`)

**Comment by v-xinda** [comment]
@alexyaang  OK, I got it.

**Comment by dbreshears** [comment]
Closing this an not reproducible
