### ISSUE TITLE
Unable to connect to jfrog.io-based Artifactory Cloud registry using Docker extension

### ISSUE THREAD

**Issue by NWinocur** [microsoft/vscode-docker#4011]
Does this occur consistently? Yes
Repro steps:

1. In Docker "Registries" view on left sidebar, Click "Connect Registry"
2. Among selections appearing in command area at top center, click "Generic Docker Registry"
3. For URL, enter Artifactory Cloud url e.g. https://myemployer.prodenvironment.jfrog.io"
4. For username, enter my username, firstname.lastname@companyacronym.com"
5. For password, enter the authentication token provided by Artifactory's "generate token & create instructions" button in its "set me up" UI.
6. This populates the (previously-empty) "Connected registries" in the left sidebar with a new entry.  Click the arrows to expand that down & see the new entry for the just-added registry.
7. Similarly, click the arrow of that new entry (which shows the recently-entered URL, without its https:// prefix) to try to expand it down.
8. Here's the point at which we start seeing an unexpected behavior: VSCode shows `Error: Cannot read properties of undefined (reading 'repositories')` directly below just-expanded line for the just-added registry.  I'd expect to instead be shown something indicative of having connected to the registry without error.  (Or at least a more-informative error message about why it failed, so I could try internet searching for ways to troubleshoot it.)

Interestingly, command+shift+p > "Docker Registries: Log In to Docker CLI" and "Docker Registries: Log Out of Docker CLI" appear to log in/out of the same Artifactory instance without obvious error, which gives me some level of confidence that the registry is reachable.

Action: AzureTreeDataProvider.getChildren
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'repositories')

Version: 1.26.0
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

<details>
<summary>Call Stack</summary>

```
GenericDockerV2RegistryTreeItem.<anonymous> extension.bundle.js:2:4311126
fulfilled extension.bundle.js:2:4310204
```

</details>

**Comment by bwateratmsft** [comment]
I've added this to the list in #869.
