### ISSUE TITLE
FROM ${TARGETARCH} wrongly detected as "base name should not be blank"

### ISSUE THREAD

**Issue by timon-schelling** [microsoft/vscode-docker#4012]
Dockers build in automatic platform args in the global scope should be recognized and should not be annotated as missing.
https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

Example:
```dockerfile
FROM alpine:latest as amd64
COPY /appbin/x86_64-unknown-linux-gnu/bin /app
RUN chmod +x /app

FROM alpine:latest as arm
COPY /appbin/armv7-unknown-linux-gnueabihf/bin /app
RUN chmod +x /app

FROM ${TARGETARCH} as build
FROM scratch
COPY --from=build /app /app
ENTRYPOINT ["/app"]
```
![image](https://github.com/microsoft/vscode-docker/assets/36821505/cf539a96-8f8e-4b46-8d96-430d8718c2ef)

**Comment by bwateratmsft** [comment]
@rcjsuen can you take a look?

**Comment by rcjsuen** [comment]
@timon-schelling Interesting. I guess you are using the `AS` to set something "equal to" `${TARGETPLATFORM}` so that `FROM ${TARGETPLATFORM}` works. Is this correct?

**Comment by timon-schelling** [comment]
@rcjsuen, No ${TARGETPLATFORM} is provided by docker.

See https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

Docker predefines a set of ARG variables with information on the platform of the node performing the build (build platform) and on the platform of the resulting image (target platform). The target platform can be specified with the --platform flag on docker build.

The following ARG variables are set automatically:

- TARGETPLATFORM - platform of the build result. Eg linux/amd64, linux/arm/v7, windows/amd64.
- TARGETOS - OS component of TARGETPLATFORM
- TARGETARCH - architecture component of TARGETPLATFORM
- TARGETVARIANT - variant component of TARGETPLATFORM
- BUILDPLATFORM - platform of the node performing the build.
- BUILDOS - OS component of BUILDPLATFORM
- BUILDARCH - architecture component of BUILDPLATFORM
- BUILDVARIANT - variant component of BUILDPLATFORM

**Comment by rcjsuen** [comment]
> @rcjsuen, No ${TARGETPLATFORM} is provided by docker.

@timon-schelling Right. But to clarify, you can't just use that variable to build, right?

```Dockerfile
FROM ${TARGETARCH} as build
```
```
$ cat Dockerfile
FROM ${TARGETARCH} as build
$ docker build --no-cache .
[+] Building 0.7s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 36B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/amd64:latest                                                                                                        0.6s
 => [auth] library/amd64:pull token for registry-1.docker.io                                                                                                                 0.0s
------
 > [internal] load metadata for docker.io/library/amd64:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by timon-schelling** [comment]
Looks like a buildx thing. I don't know how to go forward than. When using buildx the hint is wrong but otherwise...

**Comment by timon-schelling** [comment]
> > @rcjsuen, No ${TARGETPLATFORM} is provided by docker.
> 
> @timon-schelling Right. But to clarify, you can't just use that variable to build, right?
> 
> ```Dockerfile
> FROM ${TARGETARCH} as build
> ```
> ```
> $ cat Dockerfile
> FROM ${TARGETARCH} as build
> $ docker build --no-cache .
> [+] Building 0.7s (4/4) FINISHED
>  => [internal] load build definition from Dockerfile                                                                                                                         0.0s
>  => => transferring dockerfile: 36B                                                                                                                                          0.0s
>  => [internal] load .dockerignore                                                                                                                                            0.0s
>  => => transferring context: 2B                                                                                                                                              0.0s
>  => ERROR [internal] load metadata for docker.io/library/amd64:latest                                                                                                        0.6s
>  => [auth] library/amd64:pull token for registry-1.docker.io                                                                                                                 0.0s
> ------
>  > [internal] load metadata for docker.io/library/amd64:latest:
> ------
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
> ```

Yes, I define stages for all platforms Like this:
```
FROM ... as amd64
...

FROM ... as arm
...

FROM ${TARGETARCH}
...
```

**Comment by rcjsuen** [comment]
Since the architecture cannot be deduced with certainty I think I may have to just loosen the rules to allow "undefined" variables to be set to a `FROM`. The `FROM` instruction is arguably the most important instruction of a Dockerfile and any errors in `FROM` are fatal. I think dropping this validation should not be a deal breaker given that if a variable was truly undefined the build would fail instantaneously and it should be clear to the user what correction action should be taken.

**Comment by rcjsuen** [comment]
Opened https://github.com/rcjsuen/dockerfile-utils/issues/119 to track this. Thanks for reporting this, @timon-schelling.
