### ISSUE TITLE
401 Unauthorized when loading more images from registry

### ISSUE THREAD

**Issue by pfroelke** [microsoft/vscode-docker#4020]
When trying to load more images from a generic v2 docker registry, the authorization context seems to get forgotten.
Logging in and the initial load of first 100 images works fine :)

**Repro Steps:**
1. Login to external docker registry with username and password
2. Click on the registry in the `Registries` view to expand
3. Scroll down and click on `Load More...`

**Expect:**
Loading another 100 images

**Actual:**
401 Request status
![Screenshot 2023-08-02 182022](https://github.com/microsoft/vscode-docker/assets/50522783/af4ac37a-bf52-4915-9fe4-f9918f2ddddf)

**Comment by bwateratmsft** [comment]
This might just get automatically fixed when we do #869.

**Comment by bwateratmsft** [comment]
I'm going to optimistically dupe this one to #869, IMO if the issue still occurs in completely brand-new code then it deserves a new bug to be filed.
