### ISSUE TITLE
command 'csharp.listProcess' already exists on vscode

### ISSUE THREAD

**Issue by daisymanson** [microsoft/vscode-docker#4028]
when I create a docker file thought ctrl+shift+p and choose .NET:ASP.NET Core->Linux->port  press Enter
then it's show me command 'csharp.listProcess' already exists on vscode can't create a dockerfile

**Comment by alexyaang** [comment]
@daisymanson. Thanks for logging the issue. I was not able to reproduce this with a .NET 8 MVC app on my M1 Mac. 

Could you provide more information such as your OS, VSCode version, the Docker extension version, and your .NET version?

**Comment by bwateratmsft** [comment]
Do you have the C# Dev Kit extension installed @daisymanson?

**Comment by daisymanson** [comment]
@alexyaang 
.NetCore 6.0
vscode is the latest version
OS win10 , use wsl2 ubuntu20.04 
docker extension version 1.26.0

@bwateratmsft 
I'm installed c# extension below to:

Name: C#
Id: ms-dotnettools.csharp
Description: Base language support for C#
Version: 2.0.328
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

**Comment by daisymanson** [comment]
it's works
I found another c# extions in my wsl2 then I removed it, reinstall .NET Install Tool for Extension Authors
dockerfile can create

thanks, guys.
