### ISSUE TITLE
Logs Displayed in Terminal Close when Container Restarts

### ISSUE THREAD

**Issue by NischayaSharma** [microsoft/vscode-docker#4032]
The Logs it is displaying closes whenever I restart the Docker Container.
Meanwhile the Official Docker Desktop doesn't do that which is making it difficult to switch to this extension from the Docker Desktop.

Can we make this configurable if we want the Logs to continue displaying or not, or we can keep it on in case of restarting the containers and kill it in case we stop the containers...

This will greatly improve the User Experience.

https://github.com/microsoft/vscode-docker/assets/45327263/42cedc37-f8aa-4fd3-87ad-72ed4df74587

**Comment by bwateratmsft** [comment]
Let's investigate but I'm not sure there's anything we can do.

**Comment by dbreshears** [comment]
Closing as lower priority and not sure there is anything we can do here.
