### ISSUE TITLE
[Ubuntu] Permission denied while trying to connect to the Docker daemon

### ISSUE THREAD

**Issue by ildarin22** [microsoft/vscode-docker#4035]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: 1
Error Message: permission denied while trying to connect to the Docker daemon socket at redacted:url Post "redacted:url dial unix /var/run/docker.sock: connect: permission denied

Version: 1.26.0
OS: linux
OS Release: 5.15.0-78-generic
Product: Visual Studio Code
Product Version: 1.81.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:4113969
```

</details>

**Comment by bwateratmsft** [comment]
Did you add your user to the correct user group? https://docs.docker.com/engine/install/linux-postinstall/

**Comment by ildarin22** [comment]
> Did you add your user to the correct user group? https://docs.docker.com/engine/install/linux-postinstall/

Thank you!
