### ISSUE TITLE
Unable to restart app when debugging with Docker: Debug in Container

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-docker#4036]
Here are the steps to reproduce this issue:

1. Check for .NET SDK version

    ```sh
    C:\>dotnet --version
    7.0.400
    ```

1. Create new project

    ```sh
    dotnet new web -n MyContainerizedApp
    ``` 

3. Enter `MyContainerizedApp` folder

    ```sh
    cd MyContainerizedApp
    ```

4. Open with VSCode

    ```sh
    code .
    ```

5. Hit `F5` and choose `Docker: Debug in Container` to debug

    ![image](https://github.com/microsoft/vscode-docker/assets/88981/bbb86436-137a-41e9-b141-8d4676959d83)

6. Choose `Use .NET SDK`

    ![image](https://github.com/microsoft/vscode-docker/assets/88981/fa71d67a-02ab-450f-9e1d-cff1e4a0ad8c)

7. Hit `Restart` button from the VSCode

    ![image](https://github.com/microsoft/vscode-docker/assets/88981/35fbc2cb-bf94-469e-92ec-d5ff71431abe)

8. Error happened

    ![image](https://github.com/microsoft/vscode-docker/assets/88981/f56e8f25-3daf-40f8-9fa5-2986077528e5)

**Comment by alexyaang** [comment]
Hi @doggy8088, does this error only occur when you click Restart? In other words, does it initially work but when you click reload/restart, the error pops up?

**Comment by doggy8088** [comment]
Hi @alexyaang , the container is actually started by passing `--rm` arguments to it. So when I hit **Restart**, the container will be destroyed and unable to run `docker exec` again. That's why "Restart" not works.

If I hit **Stop**, then hit **F5** to start debugging again. It works fine for sure. It because the container will be created again.

**Comment by bwateratmsft** [comment]
I'm not sure the Restart feature has ever worked for .NET debugging in containers, including before the SDK container build was a thing. We should investigate. It may not be possible to support.
