### ISSUE TITLE
Feature Request: Add ability to migrate and clone images across different containers registries

### ISSUE THREAD

**Issue by Hyperclaw79** [microsoft/vscode-docker#4037]
Now that we have the ability to list images from multiple container registries, it would be beneficial to have an option in the dropdown menu or a command to migrate or clone images from one registry to the other.

_Originally posted by @Hyperclaw79 in https://github.com/microsoft/vscode-docker/issues/869#issuecomment-1686276587_

**Comment by dbreshears** [comment]
Closing as lower priority
