### ISSUE TITLE
Feature Request : containerd for pulling and storing images Support

### ISSUE THREAD

**Issue by ytooyama** [microsoft/vscode-docker#4047]
If you currently use this feature on Docker Desktop, this extension will not work.
I think "containerd image storing" also needs to be supported.

https://docs.docker.com/desktop/containerd/

**Comment by bwateratmsft** [comment]
Maybe related to https://github.com/microsoft/vscode-docker/issues/3787

**Comment by ytooyama** [comment]
Thank you.
My environment is here:

- macOS Monterey 12.6.8 + Docker Desktop 4.22.1
- Docker v1.26.0 Extension

**Comment by bwateratmsft** [comment]
@ytooyama does this still reproduce on Docker Desktop 4.23.0? The images view seems to be working normally for me with containerd image storage enabled.

**Comment by ytooyama** [comment]
Thanks! Docker Extension is operating normally.

Environment:

- Docker Desktop 4.23.0
- Docker Extension v1.26.1
