### ISSUE TITLE
Feature Request: OS-specific docker.composeCommand setting

### ISSUE THREAD

**Issue by appetite-j** [microsoft/vscode-docker#4049]
Feature Request:

We wrap `docker compose` with a script: `dc.sh` for Linux/MacOS, `dc.ps` for Windows. For example, on Linux and MacOS we run `./dc.sh up -d` to start our containers. We'd like to use the `docker.composeCommand` setting in our project's `settings.json`, but it would need to be different for Linux/MacOS and Windows.

I would suggest adding 3 settings which could override `docker.composeCommand`:
* `docker.composeCommand.linux`
* `docker.composeCommand.osx`
* `docker.composeCommand.windows`

**Comment by dbreshears** [comment]
Closing lower priority
