### ISSUE TITLE
`ADD --checksum` in `Dockerfile` is not recognized

### ISSUE THREAD

**Issue by datorr2** [microsoft/vscode-docker#4051]
### Issue

When editing a `Dockerfile`, using the `--checksum` option with `ADD` directive results in the following error:

![image](https://github.com/microsoft/vscode-docker/assets/28566413/ebe767ee-3117-4ccd-9c17-11db54f84429)

The `--checksum` flag was added in Dockerfile v1.6.0 on 2023-06-13.

https://docs.docker.com/build/dockerfile/release-notes/#160

### Applicability

This issue affects `ms-azuretools.vscode-docker` up to v1.26.0 (2023-08-30)

**Comment by bwateratmsft** [comment]
@rcjsuen can you look at this? Thanks!

**Comment by rcjsuen** [comment]
Thank you for reporting this issue, @datorr2. I have verified that this can be enabled with `#syntax=docker/dockerfile:1` and have opened https://github.com/rcjsuen/dockerfile-utils/issues/116 to track this.
