### ISSUE TITLE
Dockerfile schema missing support for HEALTHCHECK --start-interval switch

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode-docker#4054]
The [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) allows a `--start-interval` switch, which is unrecognised:
> Unknown flag: start-interval dockerfile-utils

vscode 1.80.2
extension 1.26.0
docker 24.0.5

**Comment by bwateratmsft** [comment]
@rcjsuen can you look at this? Thanks!

**Comment by rcjsuen** [comment]
Interestingly enough, this feature is actually not live yet (https://github.com/docker/cli/issues/4486). However, it can be enabled with `#syntax=docker/dockerfile:1` and I have confirmed that to be the case.

I have opened https://github.com/rcjsuen/dockerfile-utils/issues/115 to track this. Thank you for reporting this issue, @lonix1.
