### ISSUE TITLE
Bug: Link to Docker Hub gets confused when image is hash-pinned

### ISSUE THREAD

**Issue by pnacht** [microsoft/vscode-docker#4056]
When I write a `FROM` command, a Docker Hub link is automatically created pointing to the image.

![FROM cirrusci/windowsservercore:2019](https://github.com/microsoft/vscode-docker/assets/15221358/48f3f10d-d03c-4415-8792-c41c34c57921)

Clicking on the underlined section in the image above, for example, takes me to https://hub.docker.com/r/cirrusci/windowsservercore/.

However, if I decide to hash-pin the image, the parser seems to get confused:

![Screenshot 2023-09-04 at 13 56 21](https://github.com/microsoft/vscode-docker/assets/15221358/3799fa42-9a44-4f23-ad17-c749e99dba83)

We can see the underlined section has moved, and the link now takes me to https://hub.docker.com/_/windowsservercore:2019/, which 404's.

Hash-pinning without the tag works correctly, as before:

![Screenshot 2023-09-04 at 13 56 03](https://github.com/microsoft/vscode-docker/assets/15221358/91e52da0-63d4-4060-b931-429b42cec6e3)

**Comment by bwateratmsft** [comment]
@rcjsuen can you look at this? Thanks!

**Comment by pnacht** [comment]
Not really, but I'm fairly certain it's precisely what you think it is.

Docker allows using both a tag and a digest, but that effectively turns the tag into a "comment". 

When docker actually goes to fetch the image, it'll only care about the digest. [It won't even validate that the tag exists](https://www.mikenewswanger.com/posts/2020/docker-image-digests/#lets-see-it-in-action). But having the tag there makes it easier for humans to understand what exactly is being fetched, and it gives automated tools such as dependabot a better idea of what to track.

**Comment by rcjsuen** [comment]
> Docker allows using both a tag and a digest, but that effectively turns the tag into a "comment".
```Dockerfile
FROM [--platform=<platform>] <image> [AS <name>]
FROM [--platform=<platform>] <image>[:<tag>] [AS <name>]
FROM [--platform=<platform>] <image>[@<digest>] [AS <name>]
```
The documentation mentions the three forms above. I wonder why it does not mention this "fourth" form which is the format in your file.
```Dockerfile
FROM [--platform=<platform>] <image>[:<tag>][@<digest>] [AS <name>]
```
As it is right now your example does not conform to any of the three forms but perhaps that is just an oversight that was missed in the documentation.

**Comment by rcjsuen** [comment]
The parser will have to be updated to handle this. I have opened https://github.com/rcjsuen/dockerfile-ast/issues/112 to track this.

**Comment by pnacht** [comment]
> As it is right now your example does not conform to any of the three forms but perhaps that is just an oversight that was missed in the documentation.

Good point! I've opened https://github.com/docker/docs/issues/18157 to track this.
