### ISSUE TITLE
Tag image: Select the prefix in the edit box so that user can easily type over it

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#406]

**Comment by PrashanthCorp** [comment]
Should the highlight include the slash? 
@fiveisprime  @StephenWeatherford 

I'm almost done with the fix.

**Comment by PrashanthCorp** [comment]
I don't have an answer to your question, unfortunately. 

My thought process was that not highlighting '/' would mean once the user starts overwriting, the path and imageName are still separated, allowing easy word-edits (Ctrl+arrow/delete/backspace). Not having it would be a major pain point personally.

**Comment by StephenWeatherford** [comment]
agreed
