### ISSUE TITLE
The registries are not listed in alphabetical order

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4082]
**OS:** Win 10
**Build Version:** 20230922.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect all registries (Azure/Docker Hub/GitHub/Generic Registry V2) in REGISTRIES view.
2. Check whether the registries are listed in alphabetical order or not.

**Expect:**
The registries are listed in alphabetical order.

**Actual:**
The registries are not listed in alphabetical order.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/2a3f7cf6-84e7-4961-8a29-af58ade442af)

**More Info:**
This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by alexyaang** [comment]
I feel indifferent about this but it should be an easy fix if we decide to do this. What are your thoughts? @bwateratmsft

**Comment by bwateratmsft** [comment]
Easy fix, let's do it.

**Comment by bwateratmsft** [comment]
I'd suggest doing it in URTDP.getChildren so that everything is alphabetized

**Comment by alexyaang** [comment]
yeah sounds good
