### ISSUE TITLE
There is no tooltip for the registry list when pushing image to registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4083]
**OS:** Win 10
**Build Version:** 20230922.1
**Regression:** Previous Release

**Repro Steps:**
1. Navigate to Image view -> Right click one image and select "Push..." action.
2. Check whether there is a tooltip for the registry list.

**Expect:**
There is a tooltip for the registry list, such as the below one.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/73e34bef-20e6-4d93-998a-8ae88bb6728f)

**Actual:**
There is no tooltip for the registry list.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/85bc0bea-2c8d-4e8c-b936-e0b2ad957ba5)

**More Info:**
1. This issue also reproduces for the next steps.
2. This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by alexyaang** [comment]
I feel indifferent about this one as well, @bwateratmsft any preferences?

**Comment by bwateratmsft** [comment]
We should add the tooltip, I don't think it's much work.

**Comment by alexyaang** [comment]
Sounds good

**Comment by v-ruizh** [comment]
This issue also reproduces for the steps after selecting the registry provider, such as "select subscription" option, "select registry" option, "select namespace" and so on.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/9ab79922-934d-4165-a537-6b724abc1068)

**Comment by alexyaang** [comment]
I don't feel strongly about this either way. Having the prompt would be nice. @bwateratmsft what do you think?

**Comment by dbreshears** [comment]
Can revisit if we get compelling feedback,  but seems fairly low priority since it is self explanatory
