### ISSUE TITLE
There is no "Select Subscriptions..." button in Azure registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4085]
**OS:** Win 10
**Build Version:** 20230922.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect Azure registry.
2. Check whether there is a "Select Subscriptions..." button in Azure registry or not.

**Expect:**
There is a "Select Subscriptions..." button in Azure registry.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/401839aa-12ca-4938-bba3-3db962d0dd1d)

**Actual:**
There is no "Select Subscriptions..." button in Azure registry.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/c02d13bf-26ad-4d59-be44-62800ba99cb5)

**More Info:**
This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by alexyaang** [comment]
This is expected behavior as well due to the revamp of the registries view. You can filter from the Azure extension and we will honor that.

**Comment by bwateratmsft** [comment]
It's worth noting, the Azure Resources extension does not have to be installed for the Docker extension to work, but if it is installed and a subscription filter is used, it will be honored.
