### ISSUE TITLE
There is no "+ Create new registry..." in "Select registry" option

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4086]
**OS:** Win 10
**Build Version:** 20230922.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect Azure registry.
2. Navigate to Image view -> Right click one image and select "Push..." action -> Select "Azure" -> Select a subscription.
3. Check whether there is a "+ Create new registry..." in "Select registry" option.

**Expect:**
There is a "+ Create new registry..." in "Select registry" option.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/07a69073-52b5-4be9-aa39-c45c88073632)

**Actual:**
There is no "+ Create new registry..." in "Select registry" option.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/8c0bb467-8780-436d-a15e-85a24b6119af)

**More Info:**
This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by bwateratmsft** [comment]
@alexweininger where did we land on create picks?

**Comment by bwateratmsft** [comment]
I think Push is a special command that uniquely deserves to have the ACR create pick. I'm wondering if it wouldn't be best to just refactor the whole Push command to be an `AzureWizard`, and forego using the URTDP to pick the registry, instead going to the backing data.
