### ISSUE TITLE
[Suggestion] It would be better to add a prompt "No matching resources found" when no registry can be connected

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4087]
**OS:** Win 10
**Build Version:** 20230922.1

**Repro Steps:**
1. Connect all registries (Azure/Docker Hub/GitHub/Generic Registry V2) in REGISTRIES view.
2. Click "Connect Registry..." button again.
3. Check whether there is a prompt "No matching resources found" or not.

**Actual:**
There is no prompt, it keeps in "Select a registry provider to use" step.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/46f8cbd4-316c-42e2-84be-6e96ef3f0685)

**Suggestion:**
It would be better to add a prompt "No matching resources found" when no registry can be connected.

**Comment by alexyaang** [comment]
I like the suggestion. We can add something like this when there's 0 things present. @bwateratmsft, how do you feel?

**Comment by bwateratmsft** [comment]
Agreed, should be easy to add an error or something like that.
