### ISSUE TITLE
Can't set up compose file name

### ISSUE THREAD

**Issue by acyment** [microsoft/vscode-docker#4090]
Hi there! I use [Django cookiecutter](https://github.com/cookiecutter/cookiecutter-django), which creates a dev compose file named local.yml. If I right-click on it I do not see the command "Compose up". I tried setting COMPOSE_PROJECT_NAME=local.yml in an .env file in the root folder of the project to no avail. Please add the possibility to configure the extension so that a custom Compose project file name can be used.

Thanks!

**Comment by bwateratmsft** [comment]
This can be accomplished using the `files.associations` setting.

```json
    "files.associations": {
        "local.yml": "dockercompose"
    }
```
