### ISSUE TITLE
There is no validation for the existing URL when connecting to generic Docker registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4091]
**OS:** All
**Build Version:** 20230923.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect "Generic Registry V2" registry with URL "http://localhost:5100".
2. Right click "Generic Registry V2" registry -> Select "Connect to Generic Docker Registry..." -> Enter the above URL again.
3. Check whether there is a validation for the existing URL.

**Expect:**
There is a validation for the existing URL.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/5780217b-9a5b-4b26-b7d3-e18b85400487)

**Actual:**
There is no validation for the existing URL.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/41ee0b9c-c3ae-4f25-8b40-9bdcaf3df71c)

**More Info:**
1. The existing RUL can be connected again without any error, 2 same registries show in the "Registries" view.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/c15351bd-2c79-4ec5-8285-d0e294b2ac37)
3. This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by bwateratmsft** [comment]
Let's see if it's complicated to add this. If it's just a few lines then I'm cool with adding it but if it's complex then I think we can won't-fix.

**Comment by alexyaang** [comment]
Yeah sounds good!
