### ISSUE TITLE
There is no "Learn more" button in the notification when deleting image from one generic Docker registry

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4092]
**OS:** All
**Build Version:** 20230923.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect "Generic Registry V2" registry with URL "http://localhost:5100".
2. Push one image to the above registry.
3. Expand the above registry -> Right click the image and execute "Delete Image..." action.
4. Check whether there is a "Learn more" button in the notification.

**Expect:**
There is a "Learn more" button in the notification, like it in the current released extension v1.26.1. 
![image](https://github.com/microsoft/vscode-docker/assets/45614674/6a33bc85-8af5-45cf-a5ad-2ae5f5e7a780)

**Actual:**
There is no "Learn more" button in the notification.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/9a95284f-5075-4800-afc2-9edd48e44782)

**More Info:**
This notification is different from the one in the current released extension v1.26.1.

**Comment by alexyaang** [comment]
I'll need to investigate into this one.

**Comment by alexyaang** [comment]
So it seems like `parseError()` is not working properly. I think the current message is still informative, maybe not as informative as the old message. To make this work, we'll need to implement a custom error parser. @bwateratmsft do you think it's worth the time?
