### ISSUE TITLE
There is no action "Connect Registry..." in REGISTRIES view when no registry connected in REGISTRIES view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4094]
**OS:** All
**Build Version:** 20230923.1
**Regression:** Previous Release

**Repro Steps:**
1. Disconnect all registries (Azure/Docker Hub/GitHub/Generic Registry V2) in REGISTRIES view.
2. Check whether there is an action "Connect Registry..." in REGISTRIES view.

**Expect:**
There is an action "Connect Registry..." in REGISTRIES view.
<img width="356" alt="Screenshot 2023-09-25 at 10 11 48" src="https://github.com/microsoft/vscode-docker/assets/57662131/63489f5d-64ee-4d62-bb9b-04201f77c9cf">

**Actual:**
There is no action "Connect Registry..." in REGISTRIES view.
<img width="466" alt="Screenshot 2023-09-25 at 10 06 50" src="https://github.com/microsoft/vscode-docker/assets/57662131/a6a3c236-4d4e-4619-a678-dbb204d0d874">

**Comment by alexyaang** [comment]
@bwateratmsft  We should add this back.

**Comment by bwateratmsft** [comment]
Agreed, I think this is a good feature. Shouldn't be too difficult to add something for this to `URTDP.getChildren()`
