### ISSUE TITLE
Extension fails searching for container to attach before executing preLaunchTask

### ISSUE THREAD

**Issue by thefat32** [microsoft/vscode-docker#4096]
I have a preLaunchTask that starts the container but debug fails because extension is searching for container to attach before executing preLaunchTask. 

`launch.json`

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Docker NET Core Attach",
      "type": "docker",
      "request": "attach",
      "platform": "netCore",
      "preLaunchTask": "start:container",
      "sourceFileMap": {
        "/src": "${workspaceFolder}/src"
      },
      "processName": "dotnet"
    }
  ]
}
```

![image](https://github.com/microsoft/vscode-docker/assets/10998637/0a961d72-277e-4434-970e-027f6fc70965)

**Comment by bwateratmsft** [comment]
Unfortunately this is by-design from VSCode's perspective. Debug configurations are evaluated, and _then_ the pre-launch tasks execute. That makes it impossible to use a pre-launch task to start a container ahead of "Docker .NET Core Attach". I'd really like to fix this but there's nothing we can do. 😞
