### ISSUE TITLE
There is no connected registry in REGISTRIES view after executing "Docker Registries: Connect to Generic Docker Registry..." command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4097]
**OS:** All
**Build Version:** 20230926.1
**Regression:** Previous Release

**Repro Steps:**

1. Disconnect Generic Registry V2 registry in REGISTRIES view.
2. F1 -> Docker Registries: Connect to Generic Docker Registry... ->Enter registry url -> Enter registry username -> Enter registry password.
3. Check whether there is a connected registry in REGISTRIES view.

**Expect:**
There is a connected registry in REGISTRIES view.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/29d4e351-b707-4580-a805-8d1a13bae765)

**Actual:**
There is no connected registry in REGISTRIES view.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/e0ad3c2a-e0d1-41ab-b46c-4b8fbc4f8d2a)

**Comment by bwateratmsft** [comment]
Maybe a missed refresh?
