### ISSUE TITLE
An error occurs when executing "Docker Registries: Copy Image Digest" command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4098]
**OS:** All
**Build Version:** 20230926.1
**Regression:** Previous Release

**Repro Steps:**

1. Disconnect all registries (Azure/Docker Hub/GitHub/Generic Registry V2) in REGISTRIES view.
2. F1 -> Docker Registries: Copy Image Digest -> Select "Connect Registry...".
3. Check whether the next step is "Select the provider for your registry".

**Expect:**
The next step is "Select the provider for your registry".
![image](https://github.com/microsoft/vscode-docker/assets/107091828/7f18539f-3cd0-4273-8bbc-12b7c6d1256d)

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/965449e8-a30a-4713-a6c3-413caa7cea4a)

**More Info:**
This issue also reproduces when executing "Docker Registries: Copy Full Tag/Delete Image/Deploy Image to Azure App Service.../Deploy Image to Azure Container Apps.../Pull Repository/Pull Image/Log Out of Docker CLI/Log In to Docker CLI" command from command palette.

**Comment by alexyaang** [comment]
That would make sense since these commands need at least one registry to be connected to work. I think we can either 1. throw a better error, or 2.  run the connect registry command.

**Comment by bwateratmsft** [comment]
Let's throw a better error here.
