### ISSUE TITLE
There is no prompt "No matching resources found" when executing "Docker Registries: Disconnect" command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4099]
**OS:** All
**Build Version:** 20230926.1
**Regression:** Previous Release

**Repro Steps:**

1. Disconnect all registries (Azure/Docker Hub/GitHub/Generic Registry V2) in REGISTRIES view.
2. F1 -> Docker Registries: Disconnect.
3. Check whether there is a prompt "No matching resources found" or not.

**Expect:**
There is a prompt "No matching resources found".
![image](https://github.com/microsoft/vscode-docker/assets/107091828/fc7be4d8-4c6d-49fb-a694-e0fb4926d23a)

**Actual:**
There is "Connect Registry..." command.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/2d20b12d-02de-4953-b4cc-58f62811474c)

**Comment by alexyaang** [comment]
I actually like the current behavior more. @bwateratmsft what do you think?

**Comment by bwateratmsft** [comment]
It doesn't really make sense to offer a "Connect registry" option when you're in the process of disconnecting

**Comment by alexyaang** [comment]
![image](https://github.com/microsoft/vscode-docker/assets/59073590/b6cdb339-b58f-4dde-b833-ee8c30fffad5)

Would this be okay when you run `Docker Registries: Disconnect.` when no registries are connected?

**Comment by bwateratmsft** [comment]
I think it's fine--not perfect but not a big deal.
