### ISSUE TITLE
Cannot run untagged image

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-docker#4100]
Type: <b>Bug</b>

Build an image (using docker build) but don't give it a tag. It will show up in the images panel under `<none>` (you may need to select "show dangling images"). Try to run it interactivly. The extension tries to run it by name instead of by id, which results in the error

```
/bin/bash: -c: line 0: syntax error near unexpected token `newline'
/bin/bash: -c: line 0: `docker run --rm -it  <none>'
```

The solution would be to run it by id. This should probably be done not just for untagged images, but for all images

Extension version: 1.26.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.4.0-162-generic
Remote OS version: Linux x64 5.4.0-162-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (9.27GB free)|
|Process Argv|--crash-reporter-id 026754aa-b996-4f12-9e27-4c515ec2b2cc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.4.0-162-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (6 x 2495)|
|Memory (System)|7.74GB (5.48GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.4.0-162-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (6 x 2495)|
|Memory (System)|7.74GB (5.48GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by bwateratmsft** [comment]
A fix has been released for this in Docker extension version 1.28.0.
