### ISSUE TITLE
No error occurs when connecting "Docker Hub" registry with empty username

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4103]
**OS:** All
**Build Version:** 20230926.1
**Regression:** Previous Release

**Repro Steps:**
1. Connect "Docker Hub" registry with empty username.
2. Check whether there is an error "Username cannot be empty" or not.

**Expect:**
There is an error "Username cannot be empty".
![image](https://github.com/microsoft/vscode-docker/assets/107091828/12ba9ebd-0065-4117-9c20-fd5cff9f433c)

**Actual:**
No error occurs.

**More Info:**
1. There is an error in "Docker Hub" registry which connected with empty username and password.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/3df63359-1e48-47ae-9055-7cfee0296bb9)

2. This issue does not reproduce on the current released Docker extension v1.26.1.

**Comment by alexyaang** [comment]
Is it worth adding validation here? @bwateratmsft 

If so, we should do it for GitHub and Docker Hub

**Comment by bwateratmsft** [comment]
Yeah, I think we should add it for Docker Hub and GitHub. And GitLab when it's that time.
