### ISSUE TITLE
Deadlock When Debugging ASP.NET Core

### ISSUE THREAD

**Issue by perspectivism** [microsoft/vscode-docker#4105]
- VSCode Version: 1.82.2
- Local OS Version: Windows 10 Pro 22H2
- Remote OS Version: mcr.microsoft.com/dotnet/aspnet:7.0
- Remote Extension/Connection Type: Containers/WSL

Steps to Reproduce:

1. Follow the tutorial for "ASP.NET Core in a container" (on a Windows machine with WSL2 as the Docker backend): https://code.visualstudio.com/docs/containers/quickstart-aspnet-core
2. Attempt to debug the container
3. Notice that the debugger deadlocks and the application is never started

**Comment by perspectivism** [comment]
I figured out what's happening. Specifically, when the VSCode project is located within a directory containing non-ASCII characters, it results in a debugger deadlock. Here are the updated steps to reproduce:
1. Create a folder using Unicode characters, ex~ ```mkdir C:\Users\Ažb\src```
2. Follow the tutorial for "ASP.NET Core in a container" using the folder created in step 1 (on a Windows machine with WSL2 as the Docker backend): https://code.visualstudio.com/docs/containers/quickstart-aspnet-core
3. Attempt to debug the container
4. Notice that the debugger deadlocks and the application is never started

**Comment by bwateratmsft** [comment]
This sounds like it's an issue with the C# debugger. Can you file an issue in [their repo](https://github.com/dotnet/vscode-csharp/issues)?

**Comment by perspectivism** [comment]
Looking into this further, they'd likely classify it as an external issue. I found a [related bug](https://github.com/microsoft/vscode-cpptools/issues/1998) within the vscode-cpptools repository. The workaround suggested there is:

1. Press Win+R and type "intl.cpl" in the Run dialog.
2. Navigate to the Administrative tab.
3. Locate and select the "Change system locale" button.
4. Enable the option labeled "Beta: Use Unicode UTF-8 for worldwide language support."
5. Proceed to reboot your system.

Alternatively, another workaround involves moving the project to a path that does not use Unicode characters.
