### ISSUE TITLE
Feature Request: Add filter/search menu for in the Docker explorer view 

### ISSUE THREAD

**Issue by medchedli** [microsoft/vscode-docker#4107]
Motivation

The VS Code Docker extension is a great tool for managing Docker assets, but it can be difficult to find the image or container you're looking for when you have a large number of images. This is especially true if you're working on a project with multiple Dockerfiles.

Description

I propose adding a search or filter button to the VS Code Docker extension. This would allow users to quickly and easily find the image or container they're looking for by name, tag, or other criteria. One simple approach would be to add a search bar to the Docker Explorer view. Users could then enter the name, tag (running or stopped container) or other criteria they're looking for, and the Docker Explorer view would filter the list of images or containers accordingly.

**Comment by bwateratmsft** [comment]
This is already possible by using <kbd>Ctrl</kbd>+<kbd>F</kbd>

**Comment by bwateratmsft** [comment]
Reopening based on https://github.com/microsoft/vscode-docker/issues/4340

**Comment by danegsta** [comment]
It looks like the hotkey was changed at some point; `ctrl`+`alt`+`f` is the current default Windows hotkey for searching in a pane (I'm assuming `cmd`+`alt`+`f` on Mac).
