### ISSUE TITLE
(intermediate value).slice is not a function error

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#411]
Received the error when trying to log into DockerHub.

![image](https://user-images.githubusercontent.com/1487073/44683207-7b477980-a9fa-11e8-9a19-c5da635ad420.png)

in the console:

![image](https://user-images.githubusercontent.com/1487073/44683231-88646880-a9fa-11e8-8dbe-479aa22c3cda.png)

**Comment by chrisdias** [comment]
master, sorry i should have mentioned that.

**Comment by StephenWeatherford** [comment]
I can't repro this.  Can you sync up, make sure to do "npm install" and try again?  Thanks.

**Comment by chrisdias** [comment]
this issue is blocking me from trying again: https://github.com/Microsoft/vscode/issues/57292

**Comment by chrisdias** [comment]
i can no longer reproduce it :(
