### ISSUE TITLE
[Suggestion] It would be better to add an action "Re-enter credentials" after connecting "Generic Registry V2" registry with empty name and password

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4117]
**OS:** All
**Build Version:** 20231012.1
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Click "Docker Registries: Connect Registry..." -> Click "Generic Registry V2" registry -> Type "http://localhost:5100/" -> Type empty for the name and password.
2. Navigate to the "Registries" view -> Expand "Generic Registry V2" registry -> Expand "http://localhost:5100/" -> Right click the error massage.
3. Check whether there is an action "Re-enter credentials".

**Actual:**
There is no action "Re-enter credentials".
<img width="533" alt="Screenshot 2023-10-12 at 17 27 16" src="https://github.com/microsoft/vscode-docker/assets/57662131/55796ef5-2e42-4b59-98ad-31cdf9f947bd">

**Suggestion:**
It would be better to add an action "Re-enter credentials" after connecting "Generic Registry V2" registry with empty name and password. Like below:
<img width="537" alt="Screenshot 2023-10-12 at 17 27 03" src="https://github.com/microsoft/vscode-docker/assets/57662131/80a469eb-c272-4100-9d37-4f49412459e8">

**More Info:**
1. This issue also reproduces for the DockerHub registry.
2. This issue doesn't reproduce for the GitHub registry.

**Comment by alexyaang** [comment]
This seems to be an easy fix, we'll need to change this to `username === undefined || username === null`. @bwateratmsft would you be okay with this?

https://github.com/microsoft/vscode-docker-extensibility/blob/ab6a5b21ec58079079ff1ff52c60761a02fe0cc6/packages/vscode-docker-registries/src/auth/BasicAuthProvider.ts#L17

**Comment by bwateratmsft** [comment]
This is so we can intentionally allow an empty username correct?

**Comment by alexyaang** [comment]
@bwateratmsft  yes

**Comment by bwateratmsft** [comment]
I think your proposal makes sense
