### ISSUE TITLE
Fail to debug a Flask python project with an error

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4119]
**OS:** All
**Build Version:** 20231013.1
**Regression:** Previous Release

**Repro Steps:**

1. Open a Flask python project [flask_project.zip](https://github.com/microsoft/vscode-docker/files/12892137/flask_project.zip) in VS Code.
2. F1 -> Docker: Add Docker Files to Workspace -> Python: Flask -> Include docker compose files.
3. F5.
4. Check whether succeeds to debug the Flask python project.

**Expect:**
Succeed to debug the Flask python project without any error.

**Actual:**
Fail to debug Python flask project with an error.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/66051db7-e4f1-4345-a83d-daed967196df)

**More Info:**
Succeed to debug Django and General python projects.

**Comment by alexyaang** [comment]
I was able to reproduce this error and after some research I found this stakc overflow thread here https://stackoverflow.com/a/77214086/21528633. I added `Werkzeug==2.2.2` to `requirements.txt` as the answer mentioned and everything worked just fine. 

It's an issue with flask and not our tooling.

**Comment by bwateratmsft** [comment]
@alexyaang we may need to update the requirements.txt template for Flask to include `Werkzeug`.

**Comment by alexyaang** [comment]
After talking offline with Brandon, we decide to update the [requirements.txt template for Flask](https://github.com/microsoft/vscode-docker/blob/444eedb47d654a50d758c0bdb1787222b6d037aa/resources/templates/python/requirements.txt.template#L9-L11) to have flask==3.0.0.
