### ISSUE TITLE
[GitHub Codespaces] Fail to push an image to Docker Hub

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4120]
**OS:** GitHub Codespaces (Remote&Local)
**Build Version:** 20231013.1
**Regression:** Previous Release

**Repro Steps:**

1. Connect Docker Hub registry.
2. Navigate to "Images" view -> Right click an image -> Push... -> Select "Docker Hub" -> Select namespace -> Tag image.
3. Check whether succeeds to push an image to Docker Hub.

**Expect:**
Succeed to push an image to Docker Hub.

**Actual:**
Fail to push an image to Docker Hub.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/022c1522-a30b-45ea-a7ca-3384c7af2ad7)

**More Info:**

1. There is a different error when pushing an image in VS Code(non-Codespaces Environment). The error message as below:
![image](https://github.com/microsoft/vscode-docker/assets/107091828/dcf4fdda-c994-4960-b572-b1de98f3c3d2)
2. This issue doesn't reproduce when pushing an image to Azure/Generic Registry V2/GitHub registry.

**Comment by alexyaang** [comment]
The error message seems to indicate your access token does not have enough scope. Change it to `Read & Write` and it should work. 

@bwateratmsft should we add a note in the DockerHub secret step to tell user to use `Read & Write`? I think it's pretty self explanatory but... never hurts to be too clear?

**Comment by bwateratmsft** [comment]
Yeah, I think that's a good idea. Users who choose just a read token can expect that push will fail.

**Comment by v-chenzha** [comment]
Verified this issue on the build 20231107.2, it still reproduces for now. So, reopen it. The error message as below:
![image](https://github.com/microsoft/vscode-docker/assets/107091828/ec11b43c-1c4d-493b-93d8-b48cf70176fa)

**Comment by bwateratmsft** [comment]
This might be an issue with Docker Hub...

**Comment by bwateratmsft** [comment]
I think I know roughly what is happening. When the Codespace is created, it is being created already logged in to Docker Hub with a public token allowing it to pull from public repos. When we log in, we are logging in to `https://docker.io/` which is treated differently from `https://index.docker.io/v1/` but only in Codespaces--signing in to just `https://docker.io/` on my desktop works.

We could probably fix this by changing [this line](https://github.com/microsoft/vscode-docker-extensibility/blob/5a05e1ebc18b846dca71566599bb4daa78eff3d7/packages/vscode-docker-registries/src/auth/DockerHubAuthProvider.ts#L57) to return an empty string.
