### ISSUE TITLE
submission cancelled

### ISSUE THREAD

**Issue by annavanna599** [microsoft/vscode-docker#4127]
Does this occur consistently?  Yes
Repro steps:

1. compiling and running the program
2. executing submit50 cs50/problems/2023/x/recover
3. receiving the following error message: Connecting.....
Authenticating...
Verifying.......
Preparing.....
Files that will be submitted:
./recover.c
Files that won't be submitted:
Sorry, something's wrong, please try again. If the problem persists, please visit our status page https://cs50.statuspage.io for more information.
Submission cancelled.

Version: 1.27.0
OS: linux
OS Release: 6.2.0-1014-azure
Product: Visual Studio Code
Product Version: 1.83.1
Language: de

**Comment by bwateratmsft** [comment]
This doesn't look like an error in the Docker extension or the Docker CLI. Can you clarify what you were doing and what happened?

**Comment by annavanna599** [comment]
I completed pset4 recover. When I compile and run it it works perfectly, and according to check50 everything is correct. (Lmk if you want me to provide my code but I don't think that's where the problem is.) When I try to submit50 I always get the same error message as above, even after refreshing and updating multiple times.
![Screenshot 2023-10-18 153246](https://github.com/microsoft/vscode-docker/assets/117865140/48f5ad21-f76e-4843-8cce-1258a0252236)
I didn't do anything differently than usual, the only thing that's weird are these files in the recover directory that I've never seen before. I can neither open nor delete them since they don't exist but I have no idea if that's of any relevance.
![Screenshot 2023-10-18 152848](https://github.com/microsoft/vscode-docker/assets/117865140/a72d4462-3895-4219-b975-e4a1edc0feda)
Yesterday I also had to create a new key for EdX when trying to submit for the first time after which it was supposed to work normally, so I don't think that has anything to do with it.

**Comment by bwateratmsft** [comment]
Sounds like this is for a school project?

**Comment by annavanna599** [comment]
It's Harvard's CS50 introduction to computer science. Do you have any idea what might be the problem?

**Comment by bwateratmsft** [comment]
Not a clue :smile:

This page is for issues with the Docker extension for VSCode. I'd suggest asking your TA or professor, or try submitting from another machine.

**Comment by annavanna599** [comment]
Okay, thanks nontheless!

**Comment by alexweininger** [comment]
You might be able to submit an issue over on the https://github.com/cs50/submit50 repository. The submit50 tool also has documentation here: https://cs50.readthedocs.io/submit50/
