### ISSUE TITLE
An error occurs after clicking "Restart" button during "Ctrl+F5" a MVC project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4129]
**OS:** Win 10
**Build Version:** 20231019.1
**Regression:** Not a Regression

**Repro Steps:**
1. Open a .NET MVC project in VS Code Insiders.
2. Add Docker related files to it.
3. “**Ctrl+F5**” the above project with the configuration "Docker .NET Launch" -> Click "Restart" button to restart debugging.
4. Check whether succeeds to restart debugging this MVC project without any error.

**Expect:**
Succeed to restart debugging this MVC project without any error.

**Actual:**
An error occurs when restarting debugging this MVC project.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/25acbc81-2ab8-47c5-b6ca-f0dfbb222a82)

**More Info:**
1. This issue does not reproduce after clicking "Restart" button during F5ing.
2. This issue also reproduces for Python project with the below error.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/e33688d3-39da-44db-a36c-06981aa485b6)

**Comment by bwateratmsft** [comment]
Restart most likely will not work but we should definitely have better error messages.

**Comment by bwateratmsft** [comment]
Both of the issues are external. We could block doing <kbd>Ctrl</kbd>+<kbd>F5</kbd> debugging, but I feel like that's a heavy-handed way of solving the issue. Instead I think the best solution is just "don't do that".
