### ISSUE TITLE
Fail to open the web page after deploying image (Windows Container) to Azure App Service

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4130]
**OS:** Win 10
**Build Version:** 20231019.1
**Regression:** Not a Regression

**Repro Steps:**
1. Switch Docker Desktop to "Windows Container".
2. Open a .NET MVC project in VS Code Insiders.
3. Add Docker related files to it.
4. Build image for Dockerfile.
5. Push the above image to ACR.
6. Right click the image in registry view -> Deploy Image to Azure App Service -> Create a new app service.
7. When done, click "Open Site" button in the notification.
8. Check whether the web page can be opened successfully.

**Expect:**
Succeed to open the web page.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/0d20d920-bc37-480f-8b9b-da11aaa231ab)

**Actual:**
Fail to open the web page with "Application Error".
![image](https://github.com/microsoft/vscode-docker/assets/45614674/db87749a-c95b-408e-9ed0-a7b341807f21)

**More Info:**
This issue does not reproduce on "Linux Container".

**Comment by bwateratmsft** [comment]
Windows containers are a supported configuration for App Service so this might be worth a look.

**Comment by bwateratmsft** [comment]
I am able to reproduce.

**Comment by bwateratmsft** [comment]
It looks like we've never supported deploying Windows containers to App Service. I see a couple places in the deployment code that hardcode Linux:
https://github.com/microsoft/vscode-docker/blob/e882270bd9a1ec7515d039bf4dc31239b7ec34ae/src/commands/registries/azure/deployImageToAzure.ts#L42
https://github.com/microsoft/vscode-docker/blob/e882270bd9a1ec7515d039bf4dc31239b7ec34ae/src/commands/registries/azure/DockerSiteCreateStep.ts#L116-L121

Pushing a Windows image to ACR is supported and does work, but deployment to App Service through the extension fails. You have to use portal to deploy the Windows image.
