### ISSUE TITLE
Problems in Lecture 0 - CS50’s Introduction to Databases with SQL

### ISSUE THREAD

**Issue by long1611** [microsoft/vscode-docker#4136]
Dear Sir/madam

I have the following problem

When I practice step by step as instructed in the lecturer with the command "SELECT"
SELECT * FROM "longlist";
Parse error: no such table: longlist

I have tried many times but the same problem exist.

help me how to fix it.

Thank.

Does this occur consistently? 
Repro steps:

1.
2.

Version: 1.27.0
OS: linux
OS Release: 6.2.0-1014-azure
Product: Visual Studio Code
Product Version: 1.83.1
Language: vi-VN

**Comment by bwateratmsft** [comment]
Please check with your lecturer. This GitHub repository is for issues with the Docker extension for VSCode, we can't help with CS50 homework.
