### ISSUE TITLE
The web page is not found with "404" error after clicking "Learn more" button in the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4139]
**OS:** Win 10
**Build Version:** 20231025.2
**Regression:** Not a Regression

**Repro Steps:**

1. Connect "Generic Registry V2" registry with URL "http://localhost:5100/".
2. Push one image to the above registry.
3. Expand the above registry -> Right click the image and execute "Delete Image..." action -> The below notification pops up.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/5212bfcb-ba38-4698-8166-c632e0d1bc72)
5. Click "Learn more" button in the above notification.
6. Check whether the right web page is opened or not.

**Expect:**
The right web page is opened.

**Actual:**
The web page is not found with "404" error.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/4ca32d91-f829-44b1-ae37-2c8ef2403c47)

**More Info:**
This issue also reproduces on the current released Docker extension v1.27.0.

**Comment by bwateratmsft** [comment]
The new link is live: https://aka.ms/AA7jsql
