### ISSUE TITLE
Cannot connect private registries anymore

### ISSUE THREAD

**Issue by LordMilutin** [microsoft/vscode-docker#4140]
I don't know what you did but private registries are no longer visible for connection...
There is no way anymore to connect them. Please bring back this functionality as this was my only way to manage the registry with a nice UI...

_Originally posted by @LordMilutin in https://github.com/microsoft/vscode-docker/issues/869#issuecomment-1780569342_

**Comment by bwateratmsft** [comment]
Do you mean generic V2 registries or some other private registry?

**Comment by LordMilutin** [comment]
Yeah, I am referring to V2 registries from the official registry image on DockerHub. 
https://hub.docker.com/_/registry

**Comment by bwateratmsft** [comment]
We refactored the registry provider system to make it extensible, but V2 registries were and still are supported. The settings should have been migrated. Can you share a screenshot of your Registries view in the Docker explorer page?

**Comment by LordMilutin** [comment]
Here you go. There is no option to specify a private docker registry nor enter username and pass.

![image](https://github.com/microsoft/vscode-docker/assets/76582100/28373f66-b24d-4cf0-af22-e2e4cbff77d2)

![image](https://github.com/microsoft/vscode-docker/assets/76582100/8fcb7d55-d0d0-4297-9bee-dcefb6040791)

**Comment by bwateratmsft** [comment]
Can you do "Connect to Generic Docker Registry..." in either the command palette or the context menu? Does anything happen?

**Comment by LordMilutin** [comment]
> Can you do "Connect to Generic Docker Registry..." in either the command palette or the context menu? Does anything happen?
> 
> Note, this is a different command from "Connect Registry"

Nothing at all happens...

**Comment by bwateratmsft** [comment]
Huh. Somehow you're in a strange state of data inconsistency where you're connected to the V2 registry _provider_ but not to any individual V2 registries. This is definitely a bug.

I'm afraid there isn't any good workaround for this. There's a _bad_ one--clearing out your entire memento storage by deleting or renaming `%appdata%\Code\User\globalStorage\state.vscdb`--but this will basically be like reinstalling VSCode from scratch. Your user settings will be preserved but all your accumulated temporary storage will be wiped out.

**Comment by LordMilutin** [comment]
Thank you Brandon! 
I am on Linux, but I will go ahead and reinstall it anyway.

**Comment by bwateratmsft** [comment]
A fix has been released for this in Docker extension version 1.28.0.
