### ISSUE TITLE
An error occurs after expanding the Azure registry 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4141]
**OS:** All
**Build Version:** 1.27.0

**Repro Steps:**
1. Connect Azure registry -> Expand it.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
<img width="451" alt="Screenshot 2023-10-26 at 10 13 25" src="https://github.com/microsoft/vscode-docker/assets/57662131/0a5eb4cd-f8cd-4175-90e6-f168143ba1d2">

**Comment by bwateratmsft** [comment]
I have seen this too but I did not notice any negative effects. @TylerLeonhardt is this a known issue?

**Comment by bwateratmsft** [comment]
It looks like this might be due to https://github.com/microsoft/vscode-azuretools/issues/1607 which just requires an update of the azureauth package.

**Comment by v-xinda** [comment]
This issue still reproduces for now with the build 20231107.2.

**Comment by bwateratmsft** [comment]
I haven't seen this since the update. @v-xinda, can you email me the output from the Output window, "Microsoft Authentication" tab when the error occurs? Please email it as it may contain PII.

![image](https://github.com/microsoft/vscode-docker/assets/36966225/f0963af9-c963-44ed-a2ca-41c7f78095aa)

**Comment by bwateratmsft** [comment]
I suspect this issue may still occur even after it's been fixed in the Docker extension, but if you don't encounter it to begin with, you never will. Essentially, the authentication provider is getting stuck with a bad session and it seems unable to actually log out of it, so the error keeps coming up, but the Docker extension is no longer requesting bad sessions.

**Comment by bwateratmsft** [comment]
In short, it won't be an issue for external users if my suspicion is right.

**Comment by bwateratmsft** [comment]
Based on offline conversation I think my hunch is right; the bad data left over from before the fix caused the issue to reoccur once, but never again. External customers should not run into this.
