### ISSUE TITLE
After updating VSCode to the October 2023 release, the Docker extension is no longer working in Remote SSH connections

### ISSUE THREAD

**Issue by rnorthcott** [microsoft/vscode-docker#4148]
Type: <b>Bug</b>

I was using the Docker extension ok earlier on a remote host which was connected via the Remote SSH extension.  I then updated VSCode to version 1.84.0 as prompted then subsequently updated the Remote SSH extension to v0.107.0.  Since then the Docker  extension has stopped working on the remote host (after reinstalling it).  It doesn't think docker is running which it is.

Extension version: 1.27.0
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.2.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.93GB free)|
|Process Argv|--crash-reporter-id 4f3198e0-bc75-42e7-880a-06373bfe2ff8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: indigo-compute-02|
|OS|Linux x64 6.2.0-26-generic|
|CPUs|AMD EPYC 7702P 64-Core Processor (128 x 1996)|
|Memory (System)|125.36GB (108.88GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by bwateratmsft** [comment]
What is the error message you are seeing @rnorthcott?

**Comment by rnorthcott** [comment]
It seems that docker ps is not working in a terminal session either anymore unless I use sudo docker ps.
My user profile is however part of the docker group on the host and it works in a Terminal session via SSH.

![2023-11-02 15_14_20-Extension_ Docker - docker  SSH_ indigo-compute-03  - Visual Studio Code](https://github.com/microsoft/vscode-docker/assets/78229855/3268a344-423b-4166-9550-41817ac79633)

**Comment by bwateratmsft** [comment]
Do you have something in place for the VSCode setting `docker.environment`, or the `DOCKER_HOST` environment variable, or anything in `docker context`?

**Comment by rnorthcott** [comment]
Yes I did:
"docker.environment": {
        "DOCKER_HOST": "ssh://openwrt@indigo-compute-01"
    },
 Removing that fixed the problem - thanks very much
