### ISSUE TITLE
An error occurs after opening the TestSolution project in VS Code

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#4157]
**OS:** Win10/Linux
**Build Version:** 20231107.2

**Repro Steps:**

1. Clone this test project [https://github.com/alexyaang/TestSolution](url) and open it in VS Code.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/9d809cb9-dad2-4bc0-a4e9-fd22071aa905)

**More Info:**
1. Succeed to debug the project.
2. This issue doesn't reproduce on Mac.

**Comment by bwateratmsft** [comment]
This is coming from the C# extension. I have opened an issue in their repo: https://github.com/dotnet/vscode-csharp/issues/6644
