### ISSUE TITLE
[GitHub Codespaces] An error occurs after connecting "Generic Registry V2" registry with the empty name and password

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4159]
**OS:** GitHub Codespaces
**Build Version:** 20231107.2

**Repro Steps:**
1. F1 -> Click "Docker Registries: Connect Registry..." -> Click "Generic Registry V2" registry -> Type "http://localhost:5100/" -> Type empty for the name and password.
2. Navigate to the "Registries" view -> Expand "Generic Registry V2" registry -> Expand "http://localhost:5100/".
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-docker/assets/57662131/fb96c587-9ed4-4cd3-9ff0-f8d122010b7a)

**More Info:**
This issue doesn't reproduce on the Windows, Linux and Mac OSs.

**Comment by bwateratmsft** [comment]
Not a blocking issue since empty username and password is an edge case.

**Comment by dbreshears** [comment]
Closing since this is an edge case that we don't plan to fix
