### ISSUE TITLE
There is an extra "Disconnect" action in the context menu of the "Generic Registry V2" registry

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4160]
**OS:** All
**Build Version:** 20231107.2
**Regression:** Previous release (1.27.0)

**Repro Steps:**
1. F1 -> Click "Docker Registries: Connect Registry..." -> Click "Generic Registry V2" registry -> Type "http://localhost:5100/" -> Type a name and password.
2. Navigate to the "Registries" view -> Right click "Generic Registry V2" registry.
3. Check whether there is no "Disconnect" action in the context menu.

**Expect:**
There is no "Disconnect" action in the context menu.

**Actual:**
There is an extra "Disconnect" action in the context menu.
![image](https://github.com/microsoft/vscode-docker/assets/57662131/1099c1dd-dafb-45eb-bc13-5ec9ccafe489)

**More Info:**

1. There is no "Disconnect" command for the "Generic Registry V2" registry in the command palette.
2. There is an error prompt when connecting "Generic Registry V2" registry using the "http://localhost:5100/" again, if disconnect "Generic Registry V2" registry using "Disconnect" action from the context menu.
   ![image](https://github.com/microsoft/vscode-docker/assets/57662131/81be158c-73a6-45a6-b4c4-6cf6ae16442b)

**Comment by bwateratmsft** [comment]
This was added intentionally to fix #4140.

**Comment by v-xinda** [comment]
@bwateratmsft  It is not convenient, we need to connect "Generic Registry V2" registry using another URI, if I disconnect "Generic Registry V2" registry (Connect with "http://localhost:5100/" URI) from its context menu.

**Comment by bwateratmsft** [comment]
Hm, I'm not getting the "Already connected" warning. I need to look into this.
