### ISSUE TITLE
The subscriptions disappear in the Registries view after selecting several subscriptions from Azure view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4161]
**OS:** GitHub Codespaces (Remote)
**Build Version:** 20231107.2

**Repro Steps:**
1. Connect "Azure" registry -> Expand it -> All subscriptions display.
2. Install the Azure Resource extension -> Navigate to Azure view -> Select several subscriptions (Not all).
3. Navigate to Docker view -> Refresh the Registries view.
4. Check whether the subscriptions still display.

**Expect:**
The subscriptions still display.

**Actual:**
The subscriptions disappear.

**More Info:**
This issue doesn't reproduce on the Local Codespaces environment.

**Comment by bwateratmsft** [comment]
This is by-design. The subscription filters set by the Azure Resources extension will be respected by the Docker extension. We need to document this behavior though, I will include it in the documentation for #4147.
