### ISSUE TITLE
Cannot log out of Azure container registry

### ISSUE THREAD

**Issue by RokitSalad** [microsoft/vscode-docker#4163]
Does this occur consistently? Yes
Repro steps:

1. Add an Azure registry.
2. Remove the Azure registry by clicking 'Disconnect' on the context menu
3. Trigger command: Azure: Log Out
4. Try to add a registry from a different Azure account
5. You aren't given the opportunity to log into a different account, the original Azure registry is re-added to the panel.

Version: 1.27.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

**Comment by bwateratmsft** [comment]
This is by-design. To log out and log in to a different Azure account, you must use the Accounts menu:
![image](https://github.com/microsoft/vscode-docker/assets/36966225/60bd2cd7-42e9-40c6-a76f-93bade8667d4)
