### ISSUE TITLE
Docker connect permission

### ISSUE THREAD

**Issue by Uv-Katalist** [microsoft/vscode-docker#4170]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.containers.prune
Error type: 1
Error Message: Got permission denied while trying to connect to the Docker daemon socket at redacted:url Post "redacted:url dial unix /var/run/docker.sock: connect: permission denied

Version: 1.28.0
OS: linux
OS Release: 5.15.0-88-generic
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:2:2915801
```

</details>

**Comment by bwateratmsft** [comment]
Have you followed the post-install steps for Linux in the README? https://github.com/microsoft/vscode-docker#installation
