### ISSUE TITLE
Docker Resource Saver causes poor UX in .NET SDK Publishing

### ISSUE THREAD

**Issue by baronfel** [microsoft/vscode-docker#4171]
On Docker for Windows, if the Resource Saver feature kicks in then .NET SDK Container Publish + Debugging doesn't trigger successfully. What happens is that the user can select the "Debug in container" => "Use .NET SDK" flow, but after that the UI just....stays in a 'pending' state forever. There's no log activity in the Docker Output channel, and overall the user has no indication of what the problem is. Once you kick the Resource Saver feature by using the Docker CLI in some way, then the Docker extension comes back to life.

**Comment by bwateratmsft** [comment]
I ended up disabling the resource saver.

**Comment by bwateratmsft** [comment]
@baronfel is the SDK build what is hanging indefinitely or something else?

**Comment by baronfel** [comment]
From what I can see the SDK build isn't even being triggered (the Task output pane that I would usually see is never even created). I suspect there's some Docker interaction/probing happening in the VSCode Docker tooling before launching the SDK build, but I'm not certain.

**Comment by bwateratmsft** [comment]
I was not able to reproduce this when I tried. Does it reproduce consistently for you?
