### ISSUE TITLE
cannot remove registry with failed connection

### ISSUE THREAD

**Issue by ggrrll** [microsoft/vscode-docker#4182]
Hi, 

I am trying to remove registries (generic v2) for which the connection failed --  with error: `could not load user name` , but it does not work (they are still there)
it seems like a bug :bug: 

(in particular, I am trying to connect to https://registry.gitlab.com/ )

thanks 

-- maybe related to https://github.com/microsoft/vscode-docker/issues/1155

**Comment by bwateratmsft** [comment]
Are you unable to right click and remove the registry?

By the way, GitLab is not supported in Docker extension version 1.27 and up. We're working with GitLab Inc on them taking over support, #4132

**Comment by ggrrll** [comment]
> By the way, GitLab is not supported in Docker extension version 1.27 and up.  

this means that even these suggestions are not supposed to work , right?
https://stackoverflow.com/a/77579533/5533078

**Comment by bwateratmsft** [comment]
That's correct. GitLab uses a bespoke API for their registry that is not v2 compliant.

**Comment by bwateratmsft** [comment]
This has been released in Docker extension version 1.29.0.
