### ISSUE TITLE
[Feature Request] Keep recently used docker compose in a separate category

### ISSUE THREAD

**Issue by pramit-live** [microsoft/vscode-docker#4195]
When we do `compose down` (in the CONTAINERS section), the whole context is removed and not shown in the panel. It would be very useful if the context goes to a separate section (let's say RECENT), where it will be easier to do `compose up`.

**Comment by bwateratmsft** [comment]
I like this idea but unfortunately it would be incredibly difficult to implement in our current UI framework.

**Comment by learngitatfuture** [comment]
While in development, I need it to make them down many a time. 
Is it possible to create another category called RECENT? I know there will be eight categories then in the panel and might overwhelm new users. 
Or, inside CONTAINERS, a foldable placeholder for "Recent Compose"

**Comment by bwateratmsft** [comment]
Based on the difficulty of the work and the relatively low amount of feedback, we're going to won't-fix this.
