### ISSUE TITLE
Docker is installed

### ISSUE THREAD

**Issue by Rubber-hose-cryptanalysis** [microsoft/vscode-docker#4205]
Type: <b>Bug</b>

Docker is installed but VS Code says that Docker is not installed.
It is installed in desktop and the extension of VS Code.

Extension version: 1.28.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (51.21GB free)|
|Process Argv|--crash-reporter-id 559e7b3c-ac4b-46d1-a7ae-e9517665bfa2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sagemath/sagemath (kind_brown)|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3599)|
|Memory (System)|31.18GB (29.32GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by bwateratmsft** [comment]
It looks like you're using Remote WSL, is Docker installed in that WSL instance?
