### ISSUE TITLE
[FEATURE]: add architecture display in images view

### ISSUE THREAD

**Issue by fredleger** [microsoft/vscode-docker#4207]
Would be nice to add architecture filter available in labels config for images views (and possibly group by)

![image](https://github.com/microsoft/vscode-docker/assets/2778741/d6a366de-34e9-41b8-ba0b-81e94163deb2)

**Comment by bwateratmsft** [comment]
Unfortunately it looks like this wouldn't be possible without doing `docker inspect` on every image, because `docker image ls --format "{{ json . }}"` doesn't include architecture information. `docker inspect` on every image would be prohibitively slow so I guess we can't really do this 😞

**Comment by fredleger** [comment]
ohhhh make totally sense. Wasn't aware of that
thank you for clarification
