### ISSUE TITLE
Fail to debug the .NET Core project with "Docker .NET Attach (Preview)" configuration

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4208]
**OS:** Win 10
**Build Version:** 20240117.1
**.NET Core SDK:** 8.0.101

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
3. Right click the docker-compose.debug.yml --> Select "Compose Up".
4. Open launch.json and click "Add Configration…" -> Choose "Docker .NET Attach (Preview)".
5. Debug this project with "Docker .NET Attach (Preview)" configuration, select the running container and click "yes" to copy the debugger to the container.
6. Check whether succeeds to debug this project or not.

**Expect:**
Succeed to debug this project.

**Actual:**
Fail to debug this project with an error.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/ab3797d5-933d-42e2-b94a-c63497d11977)

**More Info:**
The container is stopped automatically during debugging.

**Comment by bwateratmsft** [comment]
Exit code 137 indicates something was terminated because of memory usage. Is your system out of available memory?

**Comment by v-ruizh** [comment]
I created a new VM, this issue does not reproduce on the new VM.
