### ISSUE TITLE
[Suggestion]Be more friendly to display a confirmation dialog when deleting Azure Registry

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#421]
Repro Steps:
1. In DOCKER EXPLORER, drill down from 'Registries' -> 'Azure'.
2. Right click one azure registry ->Select 'Delete Azure Registry'.
3. Check the result.

Actual:
Need to type Yes/No to confirm deletion.

Suggestion:
Be more friendly to display a confirmation dialog when deleting Azure Registry.
![add-buttons](https://user-images.githubusercontent.com/34729092/44710856-9c60a680-aa9c-11e8-83fe-2cab3b45e61c.PNG)

**Comment by estebanreyl** [comment]
This is intended, the reasoning behind it is that registries are high priority items whose deletion can cause a lot of consequences. Additionally it is unlikely, that being the item with the largest scope, that delete registry will be a very common operation so it seems reasonable to go the extra step to make sure users don't accidentally delete them. Images on the other hand are usually less trouble if accidentally deleted and users are more likely to delete many of them. I hope this seems like a reasonable explanation for the feature. Any suggestions as to how else to guarantee this safety while being more user friendly would be greatly appreciated.

**Comment by v-dantch** [comment]
@estebanreyl ,thanks a lot for your update. There is another one question need to confirm with you, could you help to take a look?
Display placeholder 'Yes' after deleting the default value 'No'. Is it expected?
![confirm](https://user-images.githubusercontent.com/34729092/44760839-27d74780-ab30-11e8-9914-0ec5214103f1.PNG)

**Comment by estebanreyl** [comment]
@v-dantch Happy to clarify. As for the latest question, yes, this is expected. The default value "No" is an asumed response meant to further protect users feom making a mistake, the user may chose to delete it if they intend to proceed with deletion. The "Yes" that appears is a guideline that helps users see what they can expect to write should they choose to proceed with the operation, its not a value on its own. Btw thanks for trying out the new features :) .

**Comment by v-dantch** [comment]
@estebanreyl  Oh, so thoughtful. And thanks a lot for your confirmation.

**Comment by StephenWeatherford** [comment]
@estebanreyl I suggested in the PR that you change the placeholder from 'Yes' to 'Enter "Yes"' to reduce confusion.  Could you please make that change?  Thanks.

@v-dantch Please let us know if this change makes it clearer, or if you still think things are confusing.  Thanks!

**Comment by estebanreyl** [comment]
@StephenWeatherford  Oh I must have completely missed it, Ill update accordingly an open a tiny PR with the fix.

**Comment by v-dantch** [comment]
@StephenWeatherford Verified on the latest Docker build from master branch. It is clearer to display 'Enter "Yes" '.

Thank you both for working on this suggestion.
