### ISSUE TITLE
Fail to debug multi project without any scaffolding

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4211]
**OS:** Win 10
**Build Version:** 20240117.1
**.NET Version:** 8.0.101

**Repro Steps:**
1. Clone this test project [TestSolution](https://github.com/alexyaang/TestSolution).
2. Open the project in VS Code Insiders.
3. Ensure that it does not contain the .vscode folder. If there is, make sure it doesn't have a "launch.json".
4. F5 -> Choose "Docker: Debug in Container" from "Select debugger" list -> Choose "Use .NET SDK" from "How would you like to build your container image?" option -> Select "TestWebApp/TestWebApp.csproj" project file.
5. Check whether succeeds to debug the project or not.

**Expect:**
Succeed to debug the project.

**Actual:**
Fail to debug the project with an error.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/07ddc8f0-f7e1-4b1a-90e0-d33e7bfe19c9)

**Comment by bwateratmsft** [comment]
I am able to reproduce

**Comment by bwateratmsft** [comment]
This seems to only reproduce for .NET 7 projects

**Comment by dbreshears** [comment]
Agreed, let's close this as won't fix for now since it doesn't reproduce in .NET 8
