### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mdhvg** [microsoft/vscode-docker#4212]
Does this occur consistently? Yes
Repro steps:
1. Run any docker container.
2. Open the docker tab from Side Bar
![image](https://github.com/microsoft/vscode-docker/assets/57744109/68978926-c8d3-4b42-90cd-0d19ea6bc4b0)
3. Right click on any running container.
4. Select either ```View Logs``` or ```Attach Shell```
![image](https://github.com/microsoft/vscode-docker/assets/57744109/cd1cc832-79d5-49a0-9bcb-b12ddb0070cc)

Error:
![image](https://github.com/microsoft/vscode-docker/assets/57744109/5e404ccb-2c41-45ba-adbb-c917473e1ae2)

Since I have installed docker in the default install location, ```C:\Program Files\Docker\Docker\resources\bin\docker.exe``` the space in **Program Files** is causing the issue.

The error also occurs when trying to run some npm build commands from the JS debugger

Version: 1.28.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.85.2
Language: en

**Comment by bwateratmsft** [comment]
Do you have a value set for the VSCode setting `docker.dockerPath`?

**Comment by mdhvg** [comment]
> Do you have a value set for the VSCode setting `docker.dockerPath`?

I tried setting it to the same value as in the **PATH** environment variable, but that caused 
![image](https://github.com/microsoft/vscode-docker/assets/57744109/7c91fda0-6028-4342-a6e3-64a95b3f80d7)

**Comment by bwateratmsft** [comment]
Try resetting the setting to have no value, does the issue still reproduce?

**Comment by mdhvg** [comment]
> Try resetting the setting to have no value, does the issue still reproduce?

VS code is able to find docker but, the original issue still reproduces.

**Comment by bwateratmsft** [comment]
It looks like you're using `cmd` as your shell, does it still happen if you use PowerShell as your shell instead? The relevant setting is `terminal.integrated.defaultProfile.windows` I believe. This may work as a workaround.

`cmd` is supported so this should be working, there might be a bug in VSCode because it's supposed to be handling the shell quoting for us in the case of task execution which is what's happening here.

**Comment by mdhvg** [comment]
> It looks like you're using `cmd` as your shell, does it still happen if you use PowerShell as your shell instead? The relevant setting is `terminal.integrated.defaultProfile.windows` I believe. This may work as a workaround.
> 
> `cmd` is supported so this should be working, there might be a bug in VSCode because it's supposed to be handling the shell quoting for us in the case of task execution which is what's happening here.

Whoa! It worked with PowerShell as default shell.

**Comment by bwateratmsft** [comment]
I'm not able to reproduce in VSCode 1.86.1, can you check if this still repros for you in the latest VSCode?
