### ISSUE TITLE
Open in Browser using 0.0.0.0 not the remote context

### ISSUE THREAD

**Issue by MartinCanto** [microsoft/vscode-docker#4214]
Bottom Line Up Front (BLUF): Is there a way to configure the ‘Open in Browser’ option to direct to a specific IP address or hostname, instead of defaulting to 0.0.0.0?

I have a setup where a Visual Studio Code (VSCode) server is running within my Docker swarm, alongside a Docker-in-Docker (dind) container. Both are interconnected via a Docker network. I’ve configured the Docker context within the VSCode server, enabling me to execute Docker commands and spawn new containers within the dind container from the VSCode server without any issues.

Additionally, I’ve installed the Docker extension in my VSCode server environment. When I initiate a container and select the ‘Open in Browser’ option from the Docker extension for VSCode, it launches a new browser window. However, it returns an error: “connect ECONNREFUSED 0.0.0.0:8080”.

My question is: How can I configure the system so that when I select ‘Open in Browser’ for a container, it establishes a connection to the dind container over the Docker network, rather than attempting to connect using 0.0.0.0:8080?

For reference, I can successfully curl the dind container from the terminal inside VSCode using the command: curl http://dind:8080.

**Comment by bwateratmsft** [comment]
IIRC we use the results from container inspect to determine the IP to connect to. Can you do `docker inspect <containerID>` and paste the full output?

**Comment by MartinCanto** [comment]
Sure here is the output of the docker inspect on the container.

**Comment by MartinCanto** [comment]
Based on your input, it appears that the appropriate course of action maybe to execute the following command:

docker run -p <DNSName|HostIP>:<HostPort>:<ContainerPort> <ImageName>

I will test this when I get back in the office.

**Comment by bwateratmsft** [comment]
What address do you get if you do `nslookup dind`?

**Comment by MartinCanto** [comment]
nslookup dind
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   dind
Address: 10.0.7.17

**Comment by bwateratmsft** [comment]
It may not be possible to make the Open in Browser command open the right URL, since neither the hostname (dind) nor the IP address (10.0.7.17) appear in the `docker inspect` result. However, it still shouldn't be opening `0.0.0.0`, it's supposed to open `localhost` in that case...

**Comment by MartinCanto** [comment]
Thank you for looking into it. I was hoping for some way to just pass the info into it maybe through an env variable or maybe add a label to the container itself that would show up. 
I appreciate your thorough review.

**Comment by bwateratmsft** [comment]
Long-delayed update--looking at the code, I can't figure out how it's even possible that 0.0.0.0 is being selected as the browsed IP address. We rewrite the port mapping in such a case so that localhost is used instead:

https://github.com/microsoft/vscode-docker/blob/a45a3dfc8e582f563292a707bbe56f616f7fedeb/src/commands/containers/browseContainer.ts#L40-L47

I don't know what to do with this other than to resolve not-repro.
