### ISSUE TITLE
[Engg] Unreachable code in customRegistries.test.ts

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#422]
`tsc -p ./` give me an error here: 
https://github.com/Microsoft/vscode-docker/blob/faa94deb54a9368f2f7bf3647c938b15ad5d913e/test/customRegistries.test.ts#L50

**Comment by StephenWeatherford** [comment]
Use "npm run build" - that uses the version of typescript installed with the project, which is 2.9.2.  "tsc -p ./" uses the typescript installed globally on your machine.  For me it was lower and gives the error you mention.  Might be a good idea to uninstall it globally so you don't forget: "npm -g remove typescript"
