### ISSUE TITLE
VSCode extension error: "Failed to connect. Is Docker installed?"

### ISSUE THREAD

**Issue by bruno-assuno** [microsoft/vscode-docker#4227]
Hello everybody!

I recently installed zorin 17 and needed to reinstall docker and also its extension in VSCode, but this appears in the extension, as if I didn't have docker installed on my PC. Does anyone know how to fix this please?

Version: 1.28.0
Docker Desktop Version: 4.27.1
OS: linux
OS Release: 6.5.0-15-generic
Product: Visual Studio Code
Product Version: 1.85.2
Language: pt-br

![Captura de tela de 2024-02-05 16-07-52](https://github.com/microsoft/vscode-docker/assets/54970379/5412fdd0-1458-4b9b-9396-ef59a4ed870c)

**Comment by bwateratmsft** [comment]
May be the same issue that is addressed in #3843. Is Docker and/or VSCode installed via a Snap package?
