### ISSUE TITLE
There is no option "Python Debugger" after clicking "Add Configuration..." in the launch.json file

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4232]
**OS:** All
**Build Version:** 20240206.2

**Repro Steps:**
1. Open a python project [myapp.zip](https://github.com/microsoft/vscode-docker/files/13975357/myapp.zip) in VS Code.
2. F1 -> Docker: Add Docker Files to Workspace -> Python: General -> Include docker compose files.
3. Right click the .debug.yaml file -> Compose Up
4. Open the launch.json file -> Click "Add Configuration...".
5. Check whether there is an option "Python Debugger".

**Expect:**
There is an option "Python Debugger".
![image](https://github.com/microsoft/vscode-docker/assets/57662131/5e2c80a9-978f-4795-a812-3379d8a6f945)

**Actual:**
There is no option "Python Debugger".
![actual](https://github.com/microsoft/vscode-docker/assets/57662131/402c28f1-89c9-4ef2-b180-e2379d2146f3)

**More Info:**
This issue doesn't reproduce on the GitHub Codespaces environment.

**Comment by bwateratmsft** [comment]
I wonder if this got moved to the Python Debugger extension.

**Comment by bwateratmsft** [comment]
It looks like it's gone from both the Python and Python Debugger extensions. I opened https://github.com/microsoft/vscode-python-debugger/issues/203 to track this.
