### ISSUE TITLE
Multi stage build dockerfile with requirements-stage line showing false error  

### ISSUE THREAD

**Issue by Avin-Mathew** [microsoft/vscode-docker#4240]
I am using a dockerfile with multi-stage build, I am getting what I believe is a false warning for the line 

```
# Stage 1: Build the requirements
FROM python:3.10 as requirements-stage
....................................................................
rest of the logic
....................................................................
# Stage 2: Build the final image
FROM python:3.10
```
in this the first line **"FROM python:3.10 as requirements-stage"** shows the error

 **[dockerfile-validator] Invalid parameters for command.: "FROM python:3.10 as requirements-stage"
	https://docs.docker.com/engine/reference/builder/**

**Comment by danegsta** [comment]
Make sure you’re uppercasing any keywords in the Dockerfile: `FROM python:3.10 AS requirements-stage`. Capitalizing AS should hopefully fix the error.

**Comment by Avin-Techv** [comment]
no it does not, still the same.

**Comment by Avin-Mathew** [comment]
@danegsta no it does't, still the same.

**Comment by danegsta** [comment]
Can you make sure you don’t have any extra Dockerfile linter extensions installed? That error looks like it may be coming from a different extension, `dockerfile-validator`.

**Comment by Avin-Techv** [comment]
sorry my mistake, yes you are right. thank you.

**Comment by Avin-Mathew** [comment]
yes you were right it was from the extension dockerfile-validator, thanks for the replies.
