### ISSUE TITLE
Docker extension doesn't show files in VS. 

### ISSUE THREAD

**Issue by martinezooo** [microsoft/vscode-docker#4243]
Hello! 

I'm a user of an M1 MacBook Pro:
```
uname -a
Darwin MacBook-Pro-Test.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

I've resolved almost all issues related to using Podman through Visual Studio Code on macOS. I based on this artictle: https://medium.com/@guillem.riera/use-podman-with-visual-studio-code-docker-extension-f4c00e78c5bf
I tried also tips from here: https://github.com/containers/podman/issues/17313

However, I'm unable to list files of my container. When I click to show files, nothing happens:
![image](https://github.com/microsoft/vscode-docker/assets/102879293/6d9234b9-8b15-4886-9b5e-e85d36ef3ce6)

Here's my settings.json:

`{
  "docker.commands.composeDown": [
    {
      "label": "Compose Down",
      "template": "${composeCommand} ${configurationFile} down"
    }
  ],
  "docker.environment": {
    "DOCKER_HOST": "unix:///Users/marcin.bortkiewicz/.local/share/containers/podman/machine/qemu/podman.sock"
  },
  "docker.dockerPath": "/opt/homebrew/bin/podman",
  "dev.containers.defaultFeatures": {},
  "editor.accessibilitySupport": "off",
  "docker.host": "unix:///Users/marcin.bortkiewicz/.local/share/containers/podman/machine/qemu/podman.sock",
  "dev.containers.executeInWSL": true,
  "dev.containers.dockerPath": "podman",
  "dev.containers.mountWaylandSocket": false,
  "docker.commands.logs": "${config:docker.dockerPath} logs --tail 1000 -f ${containerId}"
}
`

Could you help please? 

Kind regards.

**Comment by bwateratmsft** [comment]
Podman is not fully compatible with the Docker extension, you can follow #3241 for more information.
