### ISSUE TITLE
Connecting to generic v2 registry is failing

### ISSUE THREAD

**Issue by pWoLiAn** [microsoft/vscode-docker#4245]
using latest extension version.
When connecting to registry, get the message "fetch failed"
![image](https://github.com/microsoft/vscode-docker/assets/49567139/06a75aca-ac92-4410-aab7-450ddae3705d)
im able to pull using CLI
![image](https://github.com/microsoft/vscode-docker/assets/49567139/944330cd-3731-4b6e-9887-6ea08effcc83)
EDIT:
the extension works properly with the previous version(1.28). issue is seen only with the latest version(1.29)

vscode details:
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

running on ubuntu 20.4 with remote SSH

**Comment by bwateratmsft** [comment]
Try removing the `/v2` from your registry URL, the extension adds that automatically as needed.

**Comment by pWoLiAn** [comment]
still failing with the same error

**Comment by bwateratmsft** [comment]
Can you tell me more about your registry provider? It may not be supported by the generic V2 registry connection.

**Comment by pWoLiAn** [comment]
yes i am

**Comment by bwateratmsft** [comment]
Are you able to test without the proxy in place? It would be helpful to know for sure if the issue is something to do with the proxy.

**Comment by pWoLiAn** [comment]
i cannot access the registry without the proxy but i can try using a different proxy

**Comment by westy** [comment]
I'm getting the same issue. It was working with a previous version of the extension, and now it's not.
I suspect it might be something to do with the cert on the private registry (hosted on a local linux server) being self-signed?

The certificate is installed as a trusted CA on the machine, and I can browse to it fine in a web browser.

Is there any logging for the extension that I can look at perhaps?

Cheers

**Comment by bwateratmsft** [comment]
That's very helpful to know. @pWoLiAn does your registry also use a self-signed certificate?

**Comment by pWoLiAn** [comment]
yes

**Comment by fengjianxincoke** [comment]
I had the same problem with my mac,
vs code version: 1.88.1
docker plugin version: 1.29.0
I can't connect to docker hub registried
![Uploading WechatIMG149.jpg…]()

**Comment by TorchDSP** [comment]
Our current workaround is to use version 1.28.0.  Otherwise getting the fetch failed message

**Comment by tonimore** [comment]
I confirm that 1.28.0 working fine and 1.29.1 doesn't

**Comment by danegsta** [comment]
1.29.2 that was just pushed to the marketplace yesterday contains [fixes to the `Accept` header](https://github.com/microsoft/vscode-docker-extensibility/pull/225) used by the extension when connecting to V2 registries. I can't guarantee it will solve all the connection issues being reported, but it's worth testing to see if you're unblocked with the latest release.

**Comment by westy** [comment]
> 1.29.2 that was just pushed to the marketplace yesterday contains [fixes to the `Accept` header](https://github.com/microsoft/vscode-docker-extensibility/pull/225) used by the extension when connecting to V2 registries. I can't guarantee it will solve all the connection issues being reported, but it's worth testing to see if you're unblocked with the latest release.

Hi,

Good to hear updates are being made. Unfortunately this does not solve the self-certificate issue for it, so have had to revert to 1.28.0
Hopefully a future update can sort it.

Cheers

**Comment by RuthAlk** [comment]
> 1.29.2 that was just pushed to the marketplace yesterday contains [fixes to the `Accept` header](https://github.com/microsoft/vscode-docker-extensibility/pull/225) used by the extension when connecting to V2 registries. I can't guarantee it will solve all the connection issues being reported, but it's worth testing to see if you're unblocked with the latest release.

Thanks for the update, but as mentioned above as well, it does not fix the issue with connecting to a docker with self-signed certificate.  Reverted to 1.28

**Comment by bwateratmsft** [comment]
So, it's not a good security practice, but you might be able to work around it by setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` in VSCode. Node.js has a static list of trusted root certificates; the system certificate store is ignored unfortunately.

A better solution would be to get "real" certificates for the registries, but of course that likely will cost money.

**Comment by danegsta** [comment]
It looks like node also supports trusting a specific certificate by setting the `NODE_EXTRA_CA_CERTS` environment variable (i.e. `NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem`). This should hopefully allow you to trust the specific certificate without disabling the certificate trust feature entirely.

**Comment by pWoLiAn** [comment]
@danegsta @bwateratmsft Can i set this ENV variable(NODE_EXTRA_CA_CERTS) as part of ~/.bashrc? Will the extension be able to pick it up from there?

**Comment by bwateratmsft** [comment]
I'm not familiar enough with Unix to know for sure, you'd have to try it out.

**Comment by egoward** [comment]
I hit this with my private registry and found a setting in VSCode -
   HTTP / Experimental / System Certificates V2 
"Controls whether experimental loading of CA certificates from the OS should be enabled..."

I think that basically fixes the odd default behaviour where it trusts a bundle of certs that ship with NodeJS
