### ISSUE TITLE
Unable to debug with Docker when project name is all capital letters (regression in Docker extension v1.29.0)

### ISSUE THREAD

**Issue by joeyadams-bec** [microsoft/vscode-docker#4247]
On Ubuntu 22.04, I cannot debug an ASP.NET Core app under Docker if the project name is all capital letters.  But if I downgrade to Docker extension version v1.28.0, it works.

Steps:

1. Install the VS Code extensions listed below.
2. Run `dotnet new webapi -o FOO.BAR`
3. Open the folder in VS Code (trust if prompted).
4. Ctrl+Shift+P and pick "Docker: Add Docker Files to Workspace..."
5. Pick .NET: ASP.NET Core
6. Pick Linux
7. Leave default port (in my case, 5125)
8. Error appears in corner saying: Unable to determine project information for target 'GetProjectProperties' on project ...

In the terminal this appears as:

    2024-02-24 13:31:27.842 [info] Error: Unable to determine project information for target 'GetProjectProperties' on project '/home/joey/test/webapi-docker-4/FOO.BAR/FOO.BAR.csproj' Process exited with code 1

If I delete the FOO.BAR directory and repeat the steps above with Foo.Bar instead of FOO.BAR, it works.  Also, if I complete the scaffold with Foo.Bar and then rename the project to FOO.BAR, debugging fails to launch with the same error.

Environment:
* Ubuntu 22.04.4 LTS
* Visual Studio Code 1.86.2 (commit 903b1e9d89d)
    - Also seen in Code Insiders 1.87.0 (commit c11a2dd4d52)

Installed VS Code Extensions:
* .NET Install Tool v2.0.1
* C# v2.18.16
* Docker **v1.29.0** (problem goes away with version v1.28.0)

Similar issue (same error message): https://github.com/microsoft/vscode-docker/issues/3791

**Comment by baronfel** [comment]
Nothing immediately comes to mind - an https://aka.ms/binlog would help a lot to understand what's happening here. Casing + Ubuntu immedately makes me thing there's some sensitivity issue in the build pipeline somewhere, which a binlog would show.

**Comment by bwateratmsft** [comment]
@baronfel It looks like the error is coming from the SDK:
```
PS D:\Sandbox\FOO.BAR> dotnet build /r:false /t:GetProjectProperties /p:CustomAfterMicrosoftCommonTargets="d:\vscode-docker\resources\netCore\GetProjectProperties.targets" /p:CustomAfterMicrosoftCommonCrossTargetingTargets="d:\vscode-docker\resources\netCore\GetProjectProperties.targets" /p:InfoOutputPath="C:\Users\bwater\AppData\Local\Temp\585b710b-d675-4313-ad1c-ca3baeafe9f11708969717400-0.tmp"  "d:\Sandbox\FOO.BAR\FOO.BAR.csproj"
MSBuild version 17.9.4+90725d08d for .NET
C:\Program Files\dotnet\sdk\8.0.200\Containers\build\Microsoft.NET.Build.Containers.targets(112,5): error CONTAINER2005: The inferred image name 'FOO.BAR' c
ontains entirely invalid characters. The valid characters for an image name are alphanumeric characters, -, /, or _, and the image name must start with an a
lphanumeric character. [d:\Sandbox\FOO.BAR\FOO.BAR.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\8.0.200\Containers\build\Microsoft.NET.Build.Containers.targets(112,5): error CONTAINER2005: The inferred image name 'FOO.BAR' c
ontains entirely invalid characters. The valid characters for an image name are alphanumeric characters, -, /, or _, and the image name must start with an a
lphanumeric character. [d:\Sandbox\FOO.BAR\FOO.BAR.csproj]
    0 Warning(s)
    1 Error(s)
```

Is there an MSBuild property that can be set as the image name?

**Comment by bwateratmsft** [comment]
@baronfel nevermind, found it.

@joeyadams-bec I was able to work around the issue by adding a property to the CSPROJ file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ContainerRepository>foo.bar</ContainerRepository> <!-- Add this line -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

</Project>
```

**Comment by bwateratmsft** [comment]
Property is documented [here](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-8-0#set-the-container-image-name); it mentions this scenario:
> If that name is invalid as a container image name, you can override it by specifying a `ContainerRepository` as shown in the following project file...

**Comment by dbreshears** [comment]
Based on above information, going to close this as appears it is an issue in the .NET SDK?
