### ISSUE TITLE
Docker extension failed to show containers and images

### ISSUE THREAD

**Issue by qiyueliuhuo23** [microsoft/vscode-docker#4248]
I connected to a remote machine with remote ssh extension. There is docker and docker extension installed on the remote machine. It's supposed to show CONTAINERS and IMAGES by the docker extension, so I could attcher some container to the VSC, but it failed. How to fix this?  I can still attach to containers I used to open with "Open Recent" option in "File".

Here is the picture of Docker Extension.  It's just refreshing all the time
  
![image](https://github.com/microsoft/vscode-docker/assets/45259966/391cdb7d-7562-49a4-92fd-e150d0579f5b)

**Comment by qiyueliuhuo23** [comment]
Docker Extensin Version: 1.29.0
OS: linux
OS Release: 5.15.0-92-generic
Product: Visual Studio Code
Product Version: 1.86.2
Language: en

**Comment by bwateratmsft** [comment]
What happens if you run commands like `docker images` or `docker ps -a` in a command line?
