### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by raphael2025** [microsoft/vscode-docker#4249]
Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-context.initialize
Error type: 1
Error Message: Process 'docker context ls --format="{{json .}}"' exited with code 1
Error: 'docker' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Version: 1.8.1
OS: win32
OS Release: 10.0.19045
Product: WeChat Web Devtools
Product Version: 1.52.0
Language: zh-CN

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:98044
```

</details>

**Comment by bwateratmsft** [comment]
You have a very old version of the Docker extension (version 1.8.1). Can you try updating to the latest (1.29.0)?
