### ISSUE TITLE
Fetch failed error when using a proxy server

### ISSUE THREAD

**Issue by smargoli2** [microsoft/vscode-docker#4255]
I have a proxy server installed on my PC and I am getting 'fetch failed' when I try to push a container to an azure container registry. I can do it using the cli, but I would like to know if there is a way to make the UI work with my current setup.
Can you provide the url that the service is calling so I can add it to the proxy ignore list?

**Comment by bwateratmsft** [comment]
Does the issue only happen when pushing the image, or when browsing the existing images on the ACR? We use the CLI to push so I would expect that to be working, but use `fetch` for browsing images.

**Comment by smargoli2** [comment]
I checked now, I see that I can't browse the existing images either. Same error.

**Comment by bwateratmsft** [comment]
@smargoli2 did it work in version 1.28.0 of the Docker extension and break in version 1.29.0?

**Comment by smargoli2** [comment]
I don't know, I installed this proxy yesterday. It also has its own certificates...

**Comment by bwateratmsft** [comment]
In VSCode's settings, look for "Http: Proxy Strict SSL". Does disabling that have any effect?

![image](https://github.com/microsoft/vscode-docker/assets/36966225/c6dd9a86-d104-4ac3-af38-f13f45092ed5)

**Comment by smargoli2** [comment]
That's already unchecked

**Comment by smargoli2** [comment]
Can you tell me what url Docker is using? I can add it to a whitelist
