### ISSUE TITLE
There is no suggestions of docker image or any syntax when I am writing a docker compose file

### ISSUE THREAD

**Issue by yankeexe** [microsoft/vscode-docker#426]

**Comment by StephenWeatherford** [comment]
What's the name of your docker compose file?

**Comment by yankeexe** [comment]
@StephenWeatherford it is docker-compose.yml

**Comment by Abhinav1217** [comment]
I too can not get intellisense or help when writing docker-compose.yml file. Only option is using ctrl+space. I saw #128 which is closed, It said this is tracked by #243 which is also closed. This is only open issue regarding this.

**Comment by EricJizbaMSFT** [comment]
#243 is still open - closing as a duplicate of that. It also has a workaround listed here: https://github.com/microsoft/vscode-docker/issues/243#issuecomment-489879233
