### ISSUE TITLE
Unable to see Azure Registry or use Build Image in Azure with recent versions

### ISSUE THREAD

**Issue by IcyCooldrink** [microsoft/vscode-docker#4269]
Just recently picked up a project that has been on the backburner for quite a while.  When trying to right click my Dockerfile and 'Build Image in Azure...', I'm unable to complete the process.

- Build Image in Azure
- Prompt for image tag (autofill from previous run)
- Select registry provider (can only choose Azure)
- No matching resources found.
- Go to the Docker pane and confirm that I see 'Azure' under Registries
- Cannot expand this list.

I rolled back several versions to 1.26.1 and expected functionality is restored.

- Go to the Docker pane and confirm I see 'Azure' under Registries
- Expanding shows me my subscription, then my Azure registry
- Build Image in Azure
- Prompt for image tag (autofill from previous run)
- 'Select registry' prompt allows me to select my registry
- 'Select image base OS' lets me select OS (Linux)
- Build commences.

There may have been a change in process or some other requirement, but I'd like to understand what has changed and how to resolve using the current verison.

**Comment by bwateratmsft** [comment]
Do you have the Microsoft Account built-in extension enabled? We changed from using Azure Account to using the builtin authentication in IIRC 1.27.0. This is probably related to that.

![image](https://github.com/microsoft/vscode-docker/assets/36966225/fd7943f5-c17f-45c0-8ab8-423967cbd0fd)

**Comment by IcyCooldrink** [comment]
I was unaware of that one.  I can see it in the list, and it's not disabled.  I assume that means enabled.

From there ... well ... I'm not sure what to do with it TBH.  Where can I see if I'm authenticated, etc?

**Comment by bwateratmsft** [comment]
I think I might know what's going on. Can you try installing the Azure Resources extension if you don't already have it, and run the command "Azure: Sign in to Directory..."? If my hunch is correct it'll list the tenant containing the Azure subscription you are trying to use. Once you've signed in to that tenant, it should begin showing up in the Azure Container Registry listing *and* when building the image in Azure.

**Comment by IcyCooldrink** [comment]
I had Azure Resources extension installed, and funnily enough I did blunder my way into 'Azure: Sign In', but not 'Azure: Sign in to Directory'.  

The first one didn't work, and in a weird twist, I've just today left Azure Container Registry for GitLab, so I can no longer test this.  I'll try to grab some time tomorrow to quickly set it up again to test, given I raised the issue.

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
