### ISSUE TITLE
VS Code crashes when attempting to remove a container

### ISSUE THREAD

**Issue by OzzyTheGiant** [microsoft/vscode-docker#4282]
Every time I ether righ-click > remove a container from the Docker panel or use the command in the command palatte to attempt to remove a container, VS Code crashes completely and I have to restart it. This has been happening at least since upgraded VS Code to the latest release; I recall I was able to remove containers just a few months ago.

OS: Ubuntu 22.04.4
VS Code version: 1.88.0
Docker: 20.10.17 build 100c701

**Comment by bwateratmsft** [comment]
VSCode crashing would not be the extension's fault. Can you please file this here? https://github.com/microsoft/vscode/issues
