### ISSUE TITLE
Linting error using docker/dockerfile:1.7-labs and COPY --exclude

### ISSUE THREAD

**Issue by joaomorenorf** [microsoft/vscode-docker#4284]
I'm using `docker/dockerfile:1.7-labs` syntax to be able to use `COPY --exclude`, but the linter doesn't recognize it.

![image](https://github.com/microsoft/vscode-docker/assets/19269649/4badad01-c34d-466e-9a4f-26920952bc61)

![image](https://github.com/microsoft/vscode-docker/assets/19269649/1dd67059-9092-4507-b013-c57c0a53bc31)

I tried to restart the IDE, but didn't worked.

I'm using:
Visual Studio Code 1.88.0
Docker extension v1.29.0
Docker Desktop 4.28.0

**Comment by bwateratmsft** [comment]
@rcjsuen is this labs syntax stuff something we even want to support?

**Comment by joaomorenorf** [comment]
It's in the official documentation:
https://docs.docker.com/reference/dockerfile/#copy---exclude

**Comment by joaomorenorf** [comment]
Is there a way of adding a custom rule to ignore this error?

**Comment by rcjsuen** [comment]
> @rcjsuen is this labs syntax stuff something we even want to support?

I added support for this last month (https://github.com/rcjsuen/dockerfile-utils/issues/124) but I need to make a new release of the language server to include the update.

> Is there a way of adding a custom rule to ignore this error?

You can try putting `# dockerfile-utils: ignore` before the error and it should ignore it.

**Comment by rcjsuen** [comment]
I've published a new 0.12.0 to npm that should fix this issue.
