### ISSUE TITLE
Add proper HEALTHCHECK colorization/intellisense

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode-docker#43]
[This PR](https://github.com/Microsoft/vscode/pull/16476) introduces basic colorization of the `HEALTHCECK` command in `Dockerfiles`, however, it doesn't support colorization of the healtcheck sub-commands (`NONE` and `CMD`) or any of the options (`--interval`, `--timeout`, `--retry`). 

<img width="483" alt="screen shot 2016-12-04 at 10 16 58 pm" src="https://cloud.githubusercontent.com/assets/116461/20875415/6cbc8030-ba6f-11e6-8b4a-c5f90ba39151.png">

Additionally, the `Dockerfile` language service should provide auto-completion support for the `HEALTHCHECK` command, in order to make it easier to author.

The newly added linting support already fully supports validating the various permutations of the `HEALTHCHECK` command, and we have a snippet as well, so we just need to finish the colorization/auto-complete.

**Comment by bwateratmsft** [comment]
@rcjsuen Is this part of the language server? Or would it go in VSCode itself?

**Comment by rcjsuen** [comment]
@bwateratmsft Oof, this is an oldie I see, haha.

1. The language server provides code completion already for like `HEALTHCHECK --i`. If that's not working, please let me know.
1. The language server also does some validation here so something like `HEALTHCHECK --intersval=30s CMD [ "/bin/sh" ]` with the misspelling of `--interval` will flag an error. Again, if this is not working let me know and I'll take a look see.
1. The language server does not do syntax highlighting. This is blocking on microsoft/language-server-protocol#513 if you want to wait for the language server to support this or it's something you will need to figure out with the `tmLanguage` file. This is all part of a wider issue such as #75 and #292.

**Comment by bwateratmsft** [comment]
@rcjsuen Yep, we're trying to go through old issues, hence many have been resurrected :)

**Comment by bwateratmsft** [comment]
Since this is in VSCode itself, I'm closing this issue as external, and opened https://github.com/microsoft/vscode/issues/82984
