### ISSUE TITLE
docker : 找不到驱动器。名为“.D”的驱动器不存在。

### ISSUE THREAD

**Issue by Djttt** [microsoft/vscode-docker#4301]
Type: <b>Bug</b>

 终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker exec -it 94c4361b6e77a92a487a275d749c748855a427ef67d8e0159525b5396658dc2d sh”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。 

 *  正在执行任务: docker logs --tail 1000 -f 94c4361b6e77a92a487a275d749c748855a427ef67d8e0159525b5396658dc2d 

docker : 找不到驱动器。名为“.D”的驱动器不存在。
所在位置 行:1 字符: 1
+ docker logs --tail 1000 -f 94c4361b6e77a92a487a275d749c748855a427ef67 ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (.D:String) [], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound

Extension version: 1.29.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.79GB free)|
|Process Argv|--crash-reporter-id ea15a93b-cfa4-477c-9f28-e54b549b429e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
dsvsc021:30996838
0ee40948:31013168
pythonprc:31039816
dwnewjupyter:31039675

```

</details>

**Comment by bwateratmsft** [comment]
Does this same error occur if you run `docker logs` or `docker exec -it` in the VSCode terminal?
