### ISSUE TITLE
remote ssh docker : error cannot statx

### ISSUE THREAD

**Issue by gxcuit** [microsoft/vscode-docker#4302]
Hi, I'm using remote-ssh to connect the docker .

through the docker pannel, I cannot access the file in the container. However, attach  vs code works fine.
![image](https://github.com/microsoft/vscode-docker/assets/18736196/7b4b2a23-7840-4710-89a2-b3599022ec26)

![image](https://github.com/microsoft/vscode-docker/assets/18736196/e42289d2-bafb-42bf-bc61-5125f7e1da8f)

**Comment by bwateratmsft** [comment]
Can you post the full error message?

**Comment by gxcuit** [comment]
> Can you post the full error message?

Hi, Is there any way that I can get the log?

Almost all of the files are not available.  Files under a folder are not available,

**Comment by bwateratmsft** [comment]
Does anything show up under /etc or /var? The folders that are visible when you attach VSCode are very different from what is available when you use the file browser in the Docker container view.

**Comment by gxcuit** [comment]
> Does anything show up under /etc or /var? The folders that are visible when you attach VSCode are very different from what is available when you use the file browser in the Docker container view.

When I attach vs code, everything works fine. However when I use file browser, only file under the folder is available(i.e. I can access /etc/a.txt BUT CANNOT /etc/folder/*)

**Comment by bwateratmsft** [comment]
We use the `stat` command to list files and folders. It might be a permissions issue, i.e., the default Docker user in the container does not have permission to execute the `stat` command. Does this happen for all containers? e.g. can you run a generic `alpine:latest` container and see if it's happening in that container too?

**Comment by bwateratmsft** [comment]
Ok, I'll close this issue for now. Let me know if it starts happening on other containers. Thanks!
