### ISSUE TITLE
Fail to push images to private registry(127.0.0.1:5200) with an error 'no basic auth credential'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#431]
Repro Steps:
1. Connect to a private registry using the below settings.
			URL: https://127.0.0.1:5200
			Username: testuser
			Password: testpassword
2. After connecting to the private registry successfully, attempt to tab any existing images by adding 'localhost:5200' to the front of it.
3. Push the newly-tagged image

Expect:
The image shows up in the tree view for the private registry.

Actual:
An error occurs on the command line as below.
![credentials](https://user-images.githubusercontent.com/34729022/44908041-93284180-ad09-11e8-8fa4-7c32908b3b7c.png)

**Comment by StephenWeatherford** [comment]
Sorry, there was a step missing:

![image](https://user-images.githubusercontent.com/6913354/44940610-9e00c780-ad45-11e8-92c1-473b1c8b57ab.png)

**Comment by v-xuanzh** [comment]
Hi @StephenWeatherford ,this same error 'no basic auth credentials' still occurs after adding the new step "docker login 127.0.0.1:5200 -u testuser -p testpassword". Could you help to take look at it?

**Comment by StephenWeatherford** [comment]
What happens if you
```
docker login 127.0.0.1:5200
```
and enter the user and password manually?

**Comment by StephenWeatherford** [comment]
Actually I think this step is wrong:
		j. Tag any existing image by adding 'localhost:5200/' to the front of it

Try tagging with 127.0.0.1:5200 instead

**Comment by v-xuanzh** [comment]
Hi @StephenWeatherford ,Thanks for your sharing about this issue.
1. 'What happens if you follow the new step **docker login 127.0.0.1:5200'**?
A: We can log in successfully without entering the username and password maunally.
2. And now we can push any existing images to the private registry by tagging with '127.0.0.1:5200'.
