### ISSUE TITLE
Fail to debug the .NET MVC project with an error on Windows ARM platform

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#4312]
**OS:** Win 11 ARM
**Build Version:** 1.29.1
**Regression:** Not a Regression

**Repro Steps:**
1. Open a .NET MVC project in VS Code.
2. Add Docker related files to it.
3. Debug the above project with the configuration "Docker .NET Launch".
4. Check whether succeeds to debug the MVC project without any error.

**Expect:**
Succeed to debug the MVC project without any error.

**Actual:**
Fail to debug the MVC project with an error.
![image](https://github.com/microsoft/vscode-docker/assets/45614674/32ab0715-365f-43bb-9969-8d3e3a2e7d22)
![image](https://github.com/microsoft/vscode-docker/assets/45614674/0093dd26-f9dd-4dab-bb0c-01450e36364f)

**More Info:**
1. This issue does not reproduce on Windows Intel platform.
2. This issue also reproduces for a .NET Console project.

**Comment by bwateratmsft** [comment]
I think I know what's going on. Currently it looks like we only install the `linux-arm64` debugger if on an M1 Mac:
https://github.com/microsoft/vscode-docker/blob/9f8639508224478d867776d7f3fb3df655f5f837/src/debugging/netcore/NetCoreDebugHelper.ts#L240-L255
