### ISSUE TITLE
VS-code docker extention tells me docker is not installed .... 

### ISSUE THREAD

**Issue by olterman** [microsoft/vscode-docker#4317]
Docker is installed and working as per the installation instructions linked in the extension turorial (have instalkled and unisnstalled both docker and vs-code ultiple times ... I have added user to the docker group, I have changed permission on the docker socket and put in the docker absolute path in settings .... I am so tired of this ... been troubleshooting the last 4 hours and no dice ... pls help 

I am on debian trixie, running  code 1.90.0,  Docker version 26.1.4, build 5650f9b

**Comment by bwateratmsft** [comment]
Can you share a screenshot of the error you're seeing?

**Comment by olterman** [comment]
Sure, here it is !

![Screenshot_07-Jun_06-51-23_15791](https://github.com/microsoft/vscode-docker/assets/40863714/3394ca1a-8b98-46aa-b818-673a54c452b6)
![Screenshot_07-Jun_06-51-45_4274](https://github.com/microsoft/vscode-docker/assets/40863714/954310b5-da87-49f1-87bc-a2020075d369)

**Comment by ehsash** [comment]
Same here with Linux 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux and flatpak version of vscode. Since last update, no more connexion to docker from vscode. The bug occurs with or without terminal integration in the settings. The docker command and services are accessible from the terminal in vscode, but the extension doesn't detect it. It breaks also the use of any dev-container.

**Comment by ehsash** [comment]
Issue solved using the APT version from Microsoft website instead of flatpak version. With Microsoft version, which is not sandboxed as is the flatpak version, the issue of the docker service not being found by the docker vscode extension is not occuring.

**Comment by olterman** [comment]
I am not running flatpak (I was at first in which I got the docker extention to work by adding the path to the mounted host system but there where other problems with the flatpak version which made me switch to the deb version from official repos.

**Comment by ehsash** [comment]
@olterman so you have the issue with the deb version from Microsoft VSCode website?

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
