### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by lungani-delihlazo** [microsoft/vscode-docker#4321]
getting the following error when I want  to regitr :Error response from daemon: login attempt to https://registry.digi.is/v2/ failed with status: 426 Upgrade Required

**Comment by danegsta** [comment]
That 426 error code is a standard HTTP error code indicating that a server doesn't support the HTTP protocol used to connect to it. This could be connecting to a server that only supports `https` over `http` (or the opposite), but is going to be down to the specific server you're attempting to connect to.

You'll need to double check the registry URL you have configured in VSCode and determine if it's using the correct protocol for the server.
