### ISSUE TITLE
Error: "Failed to connect. Is Docker Installed?" 

### ISSUE THREAD

**Issue by JYL480** [microsoft/vscode-docker#4326]
I have installed Docker Desktop locally on windows. However the Docker extension will display this error message Error: "Failed to connect. Is Docker Installed?". Any idea how to fix this?

**Comment by JonChanGit** [comment]
I also encountered this problem。I'm using docker on WSL2

**Comment by JonChanGit** [comment]
![image](https://github.com/microsoft/vscode-docker/assets/20020550/05407b43-77c3-47fc-bfb0-e81f76999b31)


> I also encountered this problem。I'm using docker on WSL2

**Comment by mikobits** [comment]
<img width="409" alt="image" src="https://github.com/user-attachments/assets/79005418-e0de-4f67-a0a1-fee5144da5da">

yes exact same problem here.
