### ISSUE TITLE
add setting for a default --platform parameter on docker command line

### ISSUE THREAD

**Issue by giallu** [microsoft/vscode-docker#4338]
I work in OSX but my target platform is based on linux/amd64 so all of my images does not include the  linux/arm64 variant.
For this reason I need to add "--platform=linux/amd64" to all docker commands, which is supported in settings.json but ONLY for 'docker.commands.{build,run,runInteractive}

as a result, I get this when using other commands like "pull"

```
Executing task: docker image pull ghcr.io/moldiscovery/centos7:latest 

latest: Pulling from moldiscovery/centos7
no matching manifest for linux/arm64/v8 in the manifest list entries
```

So I think "pull" should also support customizing it's command or, even better, having a global setting that applies to all commands  so I can add "--platform=linux/amd64" there

**Comment by bwateratmsft** [comment]
According to https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos you can set an environment variable that would do it: `DOCKER_DEFAULT_PLATFORM`. The best way to set it would be the `docker.environment` VSCode setting--this is for Docker-specific environment variables and gets applied to every Docker CLI command we run.
