### ISSUE TITLE
Feature Request: Add filter/search menu for in the Docker explorer view #4107

### ISSUE THREAD

**Issue by tmiquel** [microsoft/vscode-docker#4340]
Reopening https://github.com/microsoft/vscode-docker/issues/4107 because this feature is no longer available.

Cmd (or Ctrl) + F doesn't work anymore, as it would open a search snippet in another parts of the VSCode UI (typically in files)

Docker: v1.29.1
vscode version: 1.91.1 (Universal)
OS: Darwin arm64 22.4.0

**Comment by bwateratmsft** [comment]
I'll reopen #4107 and dupe this to that.
