### ISSUE TITLE
Docker Extension with Podman in v1.29.1 not working ? 

### ISSUE THREAD

**Issue by Mer0winger** [microsoft/vscode-docker#4341]
I use docker extension version v1.29.1 and tried to start a Podman  container via docker.host as defined like this 
and the command in the debug window was working well. 
But in VS Code under CONTAINERS i got the errors 

Failed to connect. Is Docker running ? 
Error: Unexpected end of JSON input . 

any help pls possible ? 

thanks br 

SETTING => 

{
    "docker.host": "unix:///run/podman/podman.sock",
    "docker.dockerPath": "podman",
    "docker.commands.runInteractive": "${containerCommand} run --rm -it ${exposedPorts} ${tag}",
    "docker.environment": {
        "DOCKER_HOST": "unix:///run/podman/podman.sock"
    },
    "docker.commands.attach": "${containerCommand} exec -it ${containerId} ${shellCommand}",
    "snowflake.connectionsConfigFile": "/home/<myusername>/.snowflake/connections.toml"
}

DEBUG => 

2024-07-17 20:29:09.587 [debug] podman container ls --all --no-trunc --format {{json .}} --size=false
2024-07-17 20:29:09.596 [debug] podman image ls --filter dangling=false --no-trunc --format {{json .}}
2024-07-17 20:29:09.616 [debug] [
  {
    "AutoRemove": false,
    "Command": [
      "start-notebook.py"
    ],
    "CreatedAt": "2 weeks ago",
    "Exited": true,
    "ExitedAt": 1719601350,
    "ExitCode": 137,
    "Id": "3cb3e4f8b292b0c851993cdf15c48415f7eaf4f9d9ac848527cf56a1dff3f0c3",
    "Image": "docker.io/jupyter/base-notebook:latest",
    "ImageID": "07bb7d6acc265e404ebd132b4784081803892c6f7b67d76324ddac74e07c83f4",
    "IsInfra": false,
    "Labels": {
      "maintainer": "Jupyter Project \u003cjupyter@googlegroups.com\u003e",
      "org.opencontainers.image.ref.name": "ubuntu",
      "org.opencontainers.image.version": "22.04"
    },
    "Mounts": [],
    "Names": [
      "eloquent_pascal"
    ],
    "Namespaces": {
      
    },
    "Networks": [
      "podman"
    ],
    "Pid": 0,
    "Pod": "",
    "PodName": "",
    "Ports": [
      {
        "host_ip": "",
        "container_port": 8888,
        "host_port": 8888,
        "range": 1,
        "protocol": "tcp"
      }
    ],
    "Size": null,
    "StartedAt": 1719600629,
    "State": "exited",
    "Status": "Exited (137) 2 weeks ago",
    "Created": 1719600625
  },
  {
    "AutoRemove": false,
    "Command": [
      "start-notebook.py"
    ],
    "CreatedAt": "3 hours ago",
    "Exited": true,
    "ExitedAt": 1721230416,
    "ExitCode": 0,
    "Id": "bc26edb03bd76561aaf70566ae738bb126efa54fbb69bd1485eb1baa405322c5",
    "Image": "docker.io/jupyter/base-notebook:latest",
    "ImageID": "07bb7d6acc265e404ebd132b4784081803892c6f7b67d76324ddac74e07c83f4",
    "IsInfra": false,
    "Labels": {
      "maintainer": "Jupyter Project \u003cjupyter@googlegroups.com\u003e",
      "org.opencontainers.image.ref.name": "ubuntu",
      "org.opencontainers.image.version": "22.04"
    },
    "Mounts": [],
    "Names": [
      "gallant_wiles"
    ],
    "Namespaces": {
      
    },
    "Networks": [
      "podman"
    ],
    "Pid": 0,
    "Pod": "",
    "PodName": "",
    "Ports": [
      {
        "host_ip": "",
        "container_port": 8888,
        "host_port": 8888,
        "range": 1,
        "protocol": "tcp"
      }
    ],
    "Size": null,
    "StartedAt": 1721229072,
    "State": "exited",
    "Status": "Exited (0) 3 hours ago",
    "Created": 1721229066
  },
  {
    "AutoRemove": false,
    "Command": [
      "start-notebook.py"
    ],
    "CreatedAt": "3 hours ago",
    "Exited": false,
    "ExitedAt": -62135596800,
    "ExitCode": 0,
    "Id": "4e1b2e17e3c1cb37410780ba31276caaca0f2258a035be92ee37c07bf8b5406c",
    "Image": "docker.io/jupyter/base-notebook:latest",
    "ImageID": "07bb7d6acc265e404ebd132b4784081803892c6f7b67d76324ddac74e07c83f4",
    "IsInfra": false,
    "Labels": {
      "maintainer": "Jupyter Project \u003cjupyter@googlegroups.com\u003e",
      "org.opencontainers.image.ref.name": "ubuntu",
      "org.opencontainers.image.version": "22.04"
    },
    "Mounts": [],
    "Names": [
      "beautiful_easley"
    ],
    "Namespaces": {
      
    },
    "Networks": [
      "podman"
    ],
    "Pid": 0,
    "Pod": "",
    "PodName": "",
    "Ports": [
      {
        "host_ip": "",
        "container_port": 8888,
        "host_port": 8888,
        "range": 1,
        "protocol": "tcp"
      }
    ],
    "Size": null,
    "StartedAt": -62135596800,
    "State": "created",
    "Status": "Created",
    "Created": 1721229071
  }
]

2024-07-17 20:29:09.746 [debug] [
    {
        "Id": "e0c9858e10ed8be697dc2809db78c57357ffc82de88c69a3dee5d148354679ef",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/library/nginx@sha256:4e02e85a6f060a8406978fa53aafd2d828d0cedf5259275d191bab9afc33249e",
            "docker.io/library/nginx@sha256:9c367186df9a6b18c6735357b8eb7f407347e84aea09beb184961cb83543d46e"
        ],
        "Size": 191815842,
        "SharedSize": 0,
        "VirtualSize": 191815842,
        "Labels": {
            "maintainer": "NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e"
        },
        "Containers": 0,
        "Names": [
            "docker.io/library/nginx:latest"
        ],
        "Digest": "sha256:9c367186df9a6b18c6735357b8eb7f407347e84aea09beb184961cb83543d46e",
        "History": [
            "docker.io/library/nginx:latest"
        ],
        "Created": 1718935955,
        "CreatedAt": "2024-06-21T02:12:35Z"
    },
    {
        "Id": "940b05c860978f2138bf053db516b4b1b797d8c6f2f3b1e37f5008a30d16612d",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/apache/airflow@sha256:7f9ac2c33cb0615a70dd5351637fd90527f0b2b26bb6053cf9a903de09c92fb6",
            "docker.io/apache/airflow@sha256:8d6e541066a0f3c66180407b240659fdc6c6f8ce3909a808b99d194f38cf75fb"
        ],
        "Size": 1483063777,
        "SharedSize": 0,
        "VirtualSize": 1483063777,
        "Labels": {
            "org.apache.airflow.component": "airflow",
            "org.apache.airflow.distro": "debian",
            "org.apache.airflow.image": "airflow",
            "org.apache.airflow.main-image.build-id": "",
            "org.apache.airflow.main-image.commit-sha": "f56f13442613912725d307aafc537cc76277c2d1",
            "org.apache.airflow.module": "airflow",
            "org.apache.airflow.uid": "50000",
            "org.apache.airflow.version": "2.9.2",
            "org.opencontainers.image.authors": "dev@airflow.apache.org",
            "org.opencontainers.image.created": "",
            "org.opencontainers.image.description": "Reference, production-ready Apache Airflow image",
            "org.opencontainers.image.documentation": "https://airflow.apache.org/docs/docker-stack/index.html",
            "org.opencontainers.image.licenses": "Apache-2.0",
            "org.opencontainers.image.ref.name": "airflow",
            "org.opencontainers.image.revision": "f56f13442613912725d307aafc537cc76277c2d1",
            "org.opencontainers.image.source": "https://github.com/apache/airflow",
            "org.opencontainers.image.title": "Production Airflow Image",
            "org.opencontainers.image.url": "https://airflow.apache.org",
            "org.opencontainers.image.vendor": "Apache Software Foundation",
            "org.opencontainers.image.version": "2.9.2"
        },
        "Containers": 0,
        "Names": [
            "docker.io/apache/airflow:latest"
        ],
        "Digest": "sha256:7f9ac2c33cb0615a70dd5351637fd90527f0b2b26bb6053cf9a903de09c92fb6",
        "History": [
            "docker.io/apache/airflow:latest"
        ],
        "Created": 1718008654,
        "CreatedAt": "2024-06-10T08:37:34Z"
    },
    {
        "Id": "ab363ab21d7b44b4b0c4032655dca5e812153e81966e758fcdb08cef9d0159e2",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/library/python@sha256:d3d5f8afa67f736ff75f50ffde0abfaec42d27780155fb19e95f0bbc697eec61",
            "docker.io/library/python@sha256:f6d04873f0a67146854270e5f6513ed5e0165557c1b10689f1a20e9e65c8fe8e"
        ],
        "Size": 1041527339,
        "SharedSize": 0,
        "VirtualSize": 1041527339,
        "Labels": null,
        "Containers": 0,
        "Names": [
            "docker.io/library/python:latest"
        ],
        "Digest": "sha256:f6d04873f0a67146854270e5f6513ed5e0165557c1b10689f1a20e9e65c8fe8e",
        "History": [
            "docker.io/library/python:latest"
        ],
        "Created": 1717732404,
        "CreatedAt": "2024-06-07T03:53:24Z"
    },
    {
        "Id": "eb179b9f4315d7fdb8a337cc84b2edec5c7ac3ffa0746fb59e3113998de7099b",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/library/rabbitmq@sha256:727ea4e8dcd75480d9fa2ecae36d04badf1e54ee86380b32b8445a3d616c4a3c",
            "docker.io/library/rabbitmq@sha256:a9d813e3c19aceec72f54817708f3d32a0313901ea8eeb96ee4acc6634766414"
        ],
        "Size": 227339839,
        "SharedSize": 0,
        "VirtualSize": 227339839,
        "Labels": {
            "org.opencontainers.image.ref.name": "ubuntu",
            "org.opencontainers.image.version": "22.04"
        },
        "Containers": 0,
        "Names": [
            "docker.io/library/rabbitmq:latest"
        ],
        "Digest": "sha256:727ea4e8dcd75480d9fa2ecae36d04badf1e54ee86380b32b8445a3d616c4a3c",
        "History": [
            "docker.io/library/rabbitmq:latest"
        ],
        "Created": 1717522883,
        "CreatedAt": "2024-06-04T17:41:23Z"
    },
    {
        "Id": "f869b27253235e6c8f3764e9b02d6e2abe7b6d18e1768e8671f722d934ed0c87",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/apache/nifi@sha256:39b947dfc2d996e79ecfc419f700d0d69a53ccb94d8ec4cd5e22ea38b85b0185",
            "docker.io/apache/nifi@sha256:9181ca2855715c8df6a26641f64a07cc7ae09cccffd8c714828f601fcaf6da5c"
        ],
        "Size": 1764422413,
        "SharedSize": 0,
        "VirtualSize": 1764422413,
        "Labels": {
            "maintainer": "Apache NiFi \u003cdev@nifi.apache.org\u003e",
            "org.opencontainers.image.ref.name": "ubuntu",
            "org.opencontainers.image.version": "22.04",
            "site": "https://nifi.apache.org"
        },
        "Containers": 0,
        "Names": [
            "docker.io/apache/nifi:latest"
        ],
        "Digest": "sha256:9181ca2855715c8df6a26641f64a07cc7ae09cccffd8c714828f601fcaf6da5c",
        "History": [
            "docker.io/apache/nifi:latest"
        ],
        "Created": 1715050345,
        "CreatedAt": "2024-05-07T02:52:25Z"
    },
    {
        "Id": "07bb7d6acc265e404ebd132b4784081803892c6f7b67d76324ddac74e07c83f4",
        "ParentId": "",
        "RepoTags": null,
        "RepoDigests": [
            "docker.io/jupyter/base-notebook@sha256:0ec801994602a53d3917d0f07ccf4474a1ddf5ae419483b24681a3c42abc4ce5",
            "docker.io/jupyter/base-notebook@sha256:8c903974902b0e9d45d9823c2234411de0614c5c98c4bb782b3d4f55b3e435e6"
        ],
        "Size": 1094833386,
        "SharedSize": 0,
        "VirtualSize": 1094833386,
        "Labels": {
            "maintainer": "Jupyter Project \u003cjupyter@googlegroups.com\u003e",
            "org.opencontainers.image.ref.name": "ubuntu",
            "org.opencontainers.image.version": "22.04"
        },
        "Containers": 3,
        "Names": [
            "docker.io/jupyter/base-notebook:latest"
        ],
        "Digest": "sha256:8c903974902b0e9d45d9823c2234411de0614c5c98c4bb782b3d4f55b3e435e6",
        "History": [
            "docker.io/jupyter/base-notebook:latest"
        ],
        "Created": 1697766616,
        "CreatedAt": "2023-10-20T01:50:16Z"
    }
]

**Comment by danegsta** [comment]
We're tracking the work required to support Podman in #3241. I'm going to mark this as a duplicate, but please consider upvoting #3241 if you haven't already.
