### ISSUE TITLE
cannot open folders of docker-container

### ISSUE THREAD

**Issue by rr-appadaptive** [microsoft/vscode-docker#4347]
Does this occur consistently? Yes
Repro steps:
1. Goto "Files" in a docker-container 
2. Try to open a folder. E.g. "/usr"

Action: AzureTreeDataProvider.getChildren
Error type: Unknown
Error Message: stat: cannot statx '/---/.*': No such file or directory

Version: 1.29.1
OS: ubuntu 
OS Release: 24.04 LTS
Product: Visual Studio Code
Product Version: 1.91.1
Language: de
Docker-Version: 27.0.3

<details>

```
P.e extensionHostProcess.js:155:7236
Object.readDirectory extensionHostProcess.js:155:4091
```

</details>

**Comment by dbreshears** [comment]
Possibly related to https://github.com/microsoft/vscode-docker-extensibility/issues/231

**Comment by danegsta** [comment]
This should be resolved with the updated `@microsoft/vscode-container-client` package that was just merged

**Comment by danegsta** [comment]
Release 1.29.2 was just published to the marketplace with a fix for this issue.
