### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/vscode-docker#4349]
https://github.com/microsoft/vscode-docker/issues/4296 has been addressed but this extension needs to be published with the changes in order to work.

**Comment by bwateratmsft** [comment]
We're currently doing a test pass to prepare for release.

**Comment by rcjsuen** [comment]
Are you planning to merge #4343 for this upcoming release or the one after that?

**Comment by bwateratmsft** [comment]
> Are you planning to merge [#4343](https://github.com/microsoft/vscode-docker/pull/4343) for this upcoming release or the one after that?

We'll get it for the current release. Thanks @rcjsuen!
