### ISSUE TITLE
Cant see a list of my containers and images 

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode-docker#4359]
I ssh into a machine which has docker installed. 

Docker works properly as shown below: 

```
zchandani@gorby:~$ docker ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED          STATUS          PORTS                                       NAMES
a20516b36995   be777eecadcf                                         "bash -l"                48 minutes ago   Up 48 minutes                                               cudaq40_zohim
```

However the list of images and containers does not show up when I open the docker extension like it used to approximately a month ago. 

![Screenshot 2024-08-05 at 11 02 28](https://github.com/user-attachments/assets/054475d2-378c-46b8-8aca-50c054f29d6b)

Any ideas what could be going wrong here? I need to attach vscode to my container so any terminal commands to do that would also help. 

Thanks

**Comment by bwateratmsft** [comment]
What version of Docker do you have installed? What happens if you run `docker container ls` instead of `docker ps`?

**Comment by zohimchandani** [comment]
```
zchandani@gorby:~$ docker container ls
CONTAINER ID   IMAGE                                                COMMAND                  CREATED        STATUS       PORTS                                       NAMES

a20516b36995   be777eecadcf                                         "bash -l"                6 hours ago    Up 6 hours                                               cudaq40_zohim

```

**Comment by zohimchandani** [comment]
The output of `docker container ls` and `docker ps` is both the same. It prints out all the active containers. 

I usually look at the active containers on the panel on the left and attach vscode to them but that seems to have broken.

**Comment by bwateratmsft** [comment]
The full command that we run is as follows, can you try it?
```bash
docker container ls --all --no-trunc --format "{{json .}}" --size=false
```

**Comment by zohimchandani** [comment]
```
zchandani@gorby:~$ docker container ls --all --no-trunc --format "{{json .}}" --size=false
"docker container ls" accepts no arguments.
See 'docker container ls --help'.

Usage:  docker container ls [OPTIONS]

List containers
```

**Comment by bwateratmsft** [comment]
@danegsta any ideas? Maybe an old Docker version?

**Comment by zohimchandani** [comment]
I updated vscode to version 1.92.0 which I believe is the latest. 

The error I am getting now is: 

```
Error running command vscode-docker.containers.refresh: command 'vscode-docker.containers.refresh' not found. This is likely caused by the extension that contributes vscode-docker.containers.refresh.
```

![Screenshot 2024-08-06 at 10 53 51](https://github.com/user-attachments/assets/c986935b-233e-432e-b9ad-917cd86c68a9)

**Comment by zohimchandani** [comment]
I have access to 2 machines which I ssh into. Both have the same version of docker: 

```
zchandani@gorby:~$ docker --version
Docker version 24.0.7, build afdd53b
```

One works fine but the other one does not. How can we figure out what the difference between the 2 is?

Moreover, can you tell me if a command line command exists to attach vscode to a running container please?

Thanks.

**Comment by bwateratmsft** [comment]
For this new error I have a couple questions:
> Error running command vscode-docker.containers.refresh: command 'vscode-docker.containers.refresh' not found. This is likely caused by the extension that contributes vscode-docker.containers.refresh.

1. What version of the Docker extension do you have installed?
2. If you go to the Output window and open the Extension Host log, do you see anything suspicious? Errors, warnings, etc. about activating the Docker extension?

**Comment by ZethWang** [comment]
I have the same problem,latest version vscode
I installed v1.28.0,v 1.29.1  Docker extension. Both didn't work
and the Extension log didn't show info. about Docker

**Comment by zohimchandani** [comment]
For me, `apt dist-upgrade` seems to have fixed it.

**Comment by bwateratmsft** [comment]
Glad to hear it! I'll close this for now then.
