### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by R-G78** [microsoft/vscode-docker#4368]
Does this occur consistently? yes
Repro steps:
when I right click on a file im not able to access the context menu.

1.
2.

Version: 1.29.2
OS: darwin
OS Release: 23.6.0
Product: Visual Studio Code
Product Version: 1.92.2
Language: en

**Comment by bwateratmsft** [comment]
Can you share a screenshot of where you're right-clicking?

**Comment by R-G78** [comment]
My pointer cant be seen but its on top of the word Dockerfile

**Comment by bwateratmsft** [comment]
It looks like the screenshot didn't come through, can you try again?

**Comment by R-G78** [comment]
I'll try again.

**Comment by danegsta** [comment]
@R-G78 you're likely going to have to upload the screenshot directly on GitHub, I don't believe attachments are included when replying to comments via email.

**Comment by R-G78** [comment]
Ok. Thank you for your patient and swift response. I will do that right away

**Comment by R-G78** [comment]
![Image 19-08-2024 at 19 58 (1)](https://github.com/user-attachments/assets/52e436ef-1308-4d68-8ec6-b16cdd6b3068)

**Comment by danegsta** [comment]
@R-G78 I just tested on my Mac with the latest VSCode and extension release and wasn't able to reproduce. It looks like you have one or more extensions installed that are adding functionality to your Explorer view (you've expanded info views for individual files and what looks like a line number badge next to the individual files); are you able to right click on other file types besides Dockerfiles and get a context menu still?

**Comment by R-G78** [comment]
No. It’s all the same. I can’t access the context menu for any of the files

**Comment by bwateratmsft** [comment]
This is the Source Control view. The Docker extension doesn't do anything with it. You should check what other extensions you have installed and possibly try reinstalling VSCode.

**Comment by danegsta** [comment]
You could try disabling all of your extensions and seeing if your context menu starts working, then turning them back on one at a time until it stops working; that way you'll know exactly what extension is breaking things. If it still doesn't work after disabling all extensions, then a full reinstall is definitely your best bet.

**Comment by R-G78** [comment]
I’ve done so. Still the same result
