### ISSUE TITLE
Fail to debug a Console project

### ISSUE THREAD

**Issue by v-meilei** [microsoft/vscode-docker#4369]
**OS:** Mac M1/Linux
**Build Version:** v1.29.2
**Docker Desktop App Version:** 4.34

**Repro Steps:**

1. Create and open a .NET 9.0/8.0 Console project in VS Code, make sure it doesn't have 'launch.json' file.
2. F5 -> Select 'Docker: Debug in Container' -> Select 'Use .NET SDK'.
3. Check whether succeeds to debug.

**Expect:**
Succeed to debug.

**Actual:**
An error occurs.
![image](https://github.com/user-attachments/assets/09680dd5-731e-4243-aec8-35117e7ca867)

**More Info:**
This issue doesn't reproduce when debugging .Net 9.0/8.0 MVC Project.

**Comment by bwateratmsft** [comment]
I am able to reproduce.

**Comment by bwateratmsft** [comment]
It looks like maybe the property `EnableSdkContainerSupport` is required to be set to `true`, confirming with Chet.

**Comment by bwateratmsft** [comment]
Ok, confirmed. For all console apps, you need to add `<EnableSdkContainerSupport>true</EnableSdkContainerSupport>` to a property group in the CSPROJ file. I have updated the test case instructions to note that.
