### ISSUE TITLE
add filters for container properties

### ISSUE THREAD

**Issue by Diluka** [microsoft/vscode-docker#4375]
the filter can be stored in configs to hide some containers that you don't need to care about.

For example, hiding stopped containers allows for a better view of running docker swarm containers. As we all know, docker service keeps several historical containers, which greatly interferes with the viewing list.

properties:
- status
- image name
- container name
- create date
- label
- ...

**Comment by bwateratmsft** [comment]
As a workaround, you can group by the status/state and collapse the group of stopped containers.

For now we're won't-fixing based on the low volume of feedback and the high cost to implement.
