### ISSUE TITLE
error in  "docker compose" commands  in docker container panel 

### ISSUE THREAD

**Issue by MSoltaniN** [microsoft/vscode-docker#4377]
i have problem when run  "docker compose" commands in vs code installed in windows and i remote to the docker engine located in the linux server .

this is because of diffrence between file system separator in linux '/' vs windows '\'

when i click on  docker compose start >>>

this is error:
 *  The terminal process failed to launch: Starting directory (cwd) "\path-to-docker-compose-yaml-files" does not exist.

**Comment by bwateratmsft** [comment]
Compose down/etc. commands have to be run on the same machine as they were started on. Compose stamps the compose file and running directory as labels on the containers, and the paths are absolute paths.
