### ISSUE TITLE
server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by Rahulagowda004** [microsoft/vscode-docker#4379]
Does this occur consistently? 
Repro steps:

1.TODO: yes
2.Im not able to push the image to the hub even after using all the possible solutions

Version: 1.29.2
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.93.0
Language: en

**Comment by bwateratmsft** [comment]
Which provider are you using? Docker Hub, GitHub, etc.?

**Comment by Rahulagowda004** [comment]
Dockerhub

**Comment by bwateratmsft** [comment]
I assume you are using a PAT (personal access token) for authentication to Docker Hub? Does your PAT have read and write scopes?

**Comment by bwateratmsft** [comment]
You can view your generated tokens, and generate new ones, here: https://app.docker.com/settings/personal-access-tokens

**Comment by bwateratmsft** [comment]
That error is coming from the Docker CLI. Does your PAT have high enough privileges?

**Comment by Rahulagowda004** [comment]
Yes It has access to read, write and delete

**Comment by bwateratmsft** [comment]
I'd suggest raising this with [Docker Hub's support](https://hub.docker.com/support/contact). Does this happen only when pushing existing images, or does it happen every time?

**Comment by Rahulagowda004** [comment]
Ok thank u
