### ISSUE TITLE
when docker image start postgrep，it shows error

### ISSUE THREAD

**Issue by yjyszzr** [microsoft/vscode-docker#4381]
(HTTP code 500) server error - Cannot restart container 41155443ba25472f08bc7358a731b5b1b1a3108dec998ec25f4479544ea97f08: error while creating mount source path '/host_mnt/private/var/db/timezone/tz/2024a.1.0/zoneinfo/Asia/Shanghai': mkdir /host_mnt/private/var/db/timezone/tz/2024a.1.0: permission denied

**Comment by bwateratmsft** [comment]
This sounds like an issue with permissions. In any case, it sounds external to the Docker extension. Please ensure you have permissions to access the host path you're trying to mount.
