### ISSUE TITLE
Docker extension repeatedly uninstalls itself, then won't connect when installed

### ISSUE THREAD

**Issue by mark-turner** [microsoft/vscode-docker#4389]
I have repeatedly installed Docker extension version 1.29.2 in VS Code Version 1.93.1 on macOS Sonoma 14.6.1 on M1 hardware. It works for a short while (less than an hour), then at some point disappears from the VS Code sidebar and the following message reappears:

"Do you want to install the recommended 'Docker' extension from Microsoft for the Docker language?" 

After agreeing to reinstall, I get the message "Docker is not installed. Would you like to learn more about installing Docker?" even though Docker is installed and running the whole while this is going on.

The issue sounds similar to https://github.com/microsoft/vscode-docker/issues/4317 and https://github.com/microsoft/vscode-docker/issues/4227 which were both closed without resolution.

I have tried manually setting the docker executable path [as described here](https://stackoverflow.com/questions/69530014/failed-to-connect-is-docker-running-vs-code), but it makes no difference.

When the extension is reinstalled an running, I get this message, even though Docker Desktop is running and the container is running:

![Screenshot 2024-09-24 at 16 33 34](https://github.com/user-attachments/assets/da1a6406-f361-477a-ae70-aa5255c25c6a)

![Screenshot 2024-09-24 at 16 35 04](https://github.com/user-attachments/assets/db852687-76ae-4c39-860f-88feed5c0be8)

This is a new issue, as I have been running Docker and the Docker Extension without problems until recently.

**Comment by bwateratmsft** [comment]
The extension uninstalling itself is definitely a VSCode issue--that absolutely should not be happening. I'll file a VSCode issue for that one.

For the other issue--not detecting that Docker is installed even though it is--is there anything in the Output tab -> "Docker" output log?

**Comment by bwateratmsft** [comment]
Created https://github.com/microsoft/vscode/issues/229566 for the self-uninstall issue.

**Comment by bwateratmsft** [comment]
Is this using a remote connection like [SSH remoting](https://code.visualstudio.com/docs/remote/ssh)?

**Comment by bwateratmsft** [comment]
If you open a terminal in VSCode on the host machine (not the terminal attached to the container), and execute a Docker command like `docker -v`, what do you see?

**Comment by bwateratmsft** [comment]
This is probably the endless Mac `PATH` environment variable issue then. Can you try the following to see if the `PATH` contains what it's supposed to?

1. In the terminal, run `which docker` and share the path that it says Docker is located at.
2. In VSCode, go to the Output tab, and then to Docker's output log.
3. Click the little gear icon next to the dropdown, and change Docker's output log level to Trace.![Image](https://github.com/user-attachments/assets/ef7ff2ca-ede9-4436-b060-6d26179389a0)

4. This should output a bunch of information and environment variables, etc. Please redact whatever you need to but share what you can from that output.

**Comment by danegsta** [comment]
That particular setting only controls the behavior for the Dev Containers extension; can you try updating the `docker.dockerPath` setting as well and see if that works?

**Comment by SusanWhiteUTK** [comment]
I am following this thread as I have the same issue. I have updated the docker.dockerPath everywhere it was showing as an option in vscode. My setup is an M1 ultra on Sonoma 14.6.1. Open to any additional suggestions please.

**Comment by danegsta** [comment]
@mark-turner when you connect VSCode to a Dev Container (whether its running locally or on another machine), your IDE and extensions are running in the context of the container itself rather than the host machine, so any Docker commands we're running are executing inside the Dev Container.

* If you want to access the Docker environment on your host machine, you'll need to enable the docker-outside-of-docker feature for your Dev Container.
* If you expect to run an isolated Docker environment within your Dev Container (without access to the host-machine) you'll need to enable the docker-in-docker feature.

You can see [this guide](https://code.visualstudio.com/remote/advancedcontainers/use-docker-kubernetes) for specific details and guidance on the different Docker support modes in Dev Container.

**Comment by SusanWhiteUTK** [comment]
@danegsta - Wow, thank you for that. I confess I'm learning how to operate in docker, and adding vscode to this mix and also mac complicates things. I'll give a run, see how it goes, and report back.

**Comment by danegsta** [comment]
Accessing Docker from within a container is definitely not the most straightforward thing; the DevContainer features make it a bit more manageable. One other option that might work is to force the Docker extension to run in “local” mode in your DevContainer workspace. See [this section](https://code.visualstudio.com/docs/devcontainers/containers#_advanced-forcing-an-extension-to-run-locally-or-remotely) of the docs for an example of how to force the Docker extension into local mode in your workspace.

**Comment by bwateratmsft** [comment]
Doing a docker-in-docker setup like this is possible but it's really painful.
