### ISSUE TITLE
Remember collapsed containers, networks and volumes between sessions

### ISSUE THREAD

**Issue by tomkr4l** [microsoft/vscode-docker#4392]
In docker sidebar collapsing containers, networks and volumes is not remembered between vscode window reloads. When you have only few containers, It's quite ok, but when you work with a lot contaniers, you want to collapse the ones you work with less.

Steps to reproduce:

1. Go to Docker containers and collapse some of the containers.
2. Reload window or close and reopen VsCode
3. Collapsed containers are no longer collapsed.

Images: 
 - docker1 collapsed containers before window reload
 - docker2 containers view after window reload

![docker1](https://github.com/user-attachments/assets/de4c789c-391e-4ed2-98b5-b8e9b79eb0fc)
![docker2](https://github.com/user-attachments/assets/32c8a570-d6e5-446f-8871-43e1b604a7ec)

**Comment by bwateratmsft** [comment]
Kinda related to #4375

**Comment by dbreshears** [comment]
Thanks for the suggestion but we are unable to prioritize this.
