### ISSUE TITLE
[Feature] - Add global prune all button

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-docker#4397]
At the moment if cleaning of containers, volumes, networks... is required action for the user, he will need to go through each and every component and click prune. I was wondeirng would it be more ocnviniet to provide one global button/action prune all which will do all subsequent actions, as in most cases the users will prune everything.

**Comment by bwateratmsft** [comment]
There is a command for this but the button isn't shown anywhere in the UI, because there's nowhere in the UI that really makes sense for it. The command is "Docker: Prune System..."

**Comment by mamilic** [comment]
Would it make sense to put it in the "header" of the Docker Component, something like Search, Run And Debug, Extensions have?

![Image](https://github.com/user-attachments/assets/9a9595b7-5d13-4199-9601-9a76d3de7725)
![Image](https://github.com/user-attachments/assets/cb61f140-5495-4d6b-a848-b52afa2edf10)
![Image](https://github.com/user-attachments/assets/14d43b44-5a89-4689-bc7e-d85f5ac6ce65)

**Comment by bwateratmsft** [comment]
I don't think there's actually an extensibility point in VSCode for making things appear there for extension-contributed views. `view/title` appears at the top of each view, I don't know of a contribution point for view _containers_.

**Comment by mamilic** [comment]
I was able to find some extension that implemented that, https://github.com/jlandersen/vscode-kafka. Thouhg not sure wheter that is feasable. Hope it will be helpfull.

![Image](https://github.com/user-attachments/assets/8c08bf8f-8bd2-4305-85cc-94ab6fe14cfe)

**Comment by bwateratmsft** [comment]
For Kafka, VSCode is "collapsing" the view somewhat since there is only one view in the view container. If you deselect all but one of the Docker views you get the same behavior.
