### ISSUE TITLE
Add auto-completion for de-facto label names

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-docker#44]
There are various efforts to standardize on the names of well-known labels, in order to support be interop/toolability. We should investigate whether it would make sense to add auto-completion for one or more of the following:

* [Label Schema](http://label-schema.org/rc1/)
* [Project Atomic](https://github.com/projectatomic/ContainerApplicationGenericLabels)
* Other?

**Comment by PrashanthCorp** [comment]
Closing due to lack of user feedback
