### ISSUE TITLE
All images show on the prompting list after tagging/pushing one specific image

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#441]
Repro Steps:
1. Make sure there are several images under 'Images' node.
2. Right click one image then select 'Push'/'Tag Image'.
3. Check the prompting list.

Expect:
1. No prompting pops up when selecting 'Push' for one tagged image.
2. Display the prompting 'Tag image as ...' when selecting 'Tag Image'.

Actual:
All the images show on the prompting list when selecting 'Push'/'Tag Image'.
![list](https://user-images.githubusercontent.com/34729022/45018374-7d709000-b019-11e8-8482-d2abdf0b6430.png)

**Comment by StephenWeatherford** [comment]
Fixed via #439
