### ISSUE TITLE
Failed to connect. Is docker Installed?

### ISSUE THREAD

**Issue by k3nd3r9** [microsoft/vscode-docker#4410]
Type: <b>Bug</b>

Visual Code fails to realize docker is installed.

I follow the post install instructions:
https://docs.docker.com/engine/install/linux-postinstall/

I can "docker run hello-world" without sudo from terminal.

If I open code with sudo, it is able to run the extension fine.

If I open code normally, it is unable to find the extension, but I can open the terminal and run "docker info" and it reports normally. docker can see images from terminal.

I have added my user to the "docker group"

Seems like a permissions issue.

Ubuntu version 24.04.1 LTS

Extension version: 1.29.3
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600KF (16 x 4500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|31.18GB (28.03GB free)|
|Process Argv|--crash-reporter-id ec332379-b5d7-42fc-bc62-ed95471c8cdc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by bwateratmsft** [comment]
This could be a case where a full system restart is required for permissions to fully propagate. Can you try that if you haven't already?

**Comment by k3nd3r9** [comment]
Yes, I tried this already.

**Comment by bwateratmsft** [comment]
When you open VSCode normally (non-sudo), do you launch it from the terminal or somewhere else?

**Comment by bwateratmsft** [comment]
This might be a snap issue. Can you try the workarounds in [here](https://github.com/microsoft/vscode-docker/issues/3843) and see if that works?

**Comment by nanachan3835** [comment]
You can remove CODE config in ~/.config and then relogin  VSCODe (non-sudo),  after that you can see docker extension icon appear in taskbar. Remember sync this setting to your account. This work for me, you can try it. Hope you can fix this problem soon.

**Comment by niloykashyap** [comment]
Encountering the exact same issue. Followed all the steps mentioned 
1. Added user to the group 'docker' 
2. Confirmed changes after logging out and logging back in.
3. Able to use all docker commands without using sudo when using the terminal.
4. Issue persists only  with VSCode not being able to detect the containers and images when VSCode is run as a non-root user.

**Comment by bwateratmsft** [comment]
@k3nd3r9 any updates?
