### ISSUE TITLE
404 Not Found when getting the list of tags

### ISSUE THREAD

**Issue by pbernery** [microsoft/vscode-docker#4419]
I've just installed the Docker extension and did the setup for connecting to the GitHub Registry.
I have the list of packages, but when trying to get the list of tags, the extension displays a 404 error.

I created a Personal Access Token with repo + write:packages as requested.
Did I miss something?

![Image](https://github.com/user-attachments/assets/25ed2bea-07a0-4eb6-a357-eddba2a70554)

**Comment by bwateratmsft** [comment]
Does this show for all images or just the one?

**Comment by pbernery** [comment]
It shows for all of them.

**Comment by bwateratmsft** [comment]
Does your organization require multi-factor authentication? I'm wondering if the PAT is not enough when MFA is required.

**Comment by pbernery** [comment]
My organisation does not, my personal account is setup for MFA though, and can also use a passkey (if this can have any influence).

However, I can list the account + packages of the organization, so it looks like it is working partially.
And FYI, I did create a classic token, not a fine-grained one (those have no access on packages yet).

**Comment by pbernery** [comment]
Some internal tests of the API showed that lowercasing the URL would work.

My GitHub project is called Platform, and the Docker Extension generates a call to `ghcr.io/v2/<MyOrg>/Platform/<package>/tags/list`.
Calling `ghcr.io/v2/<myorg>/platform/<package>/tags/list` seems to work.

**Comment by bwateratmsft** [comment]
That's a great find! We'll have to look at casting the URLs to request to lowercase.
