### ISSUE TITLE
enhancement - provide command outcome/result as status update

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-docker#4421]
As of now the command outputs are opened in the terminal and when that happens the focus is changed tot he cmmand terminal output, which puts away user from the workflow. The status popup which vscode provides would be much more suitable for command updates such as
- command successfull
- command failed

**Comment by bwateratmsft** [comment]
We're pretty deliberate about when we show the commands--in certain cases it's the only possibility (e.g. attach shell, logs), but in others we really want the command to be prominently visible (docker build, docker run). Which command(s) are you using where this is problematic?

**Comment by mamilic** [comment]
Hi @bwateratmsft , 

Thank you for the quick response! I understand the reasoning behind showing terminal/output for certain commands like attach shell or logs, where visibility is critical. However, for commands like compose up, compose down, and compose restart, the automatic opening of the terminal/output disrupts the workflow.

In my use case, 99% of the time, I don’t need to view the logs for these commands unless there’s an error or failure. It would be great if these commands could utilize a less intrusive status popup (e.g., "Command successful" or "Command failed") for most scenarios and only open the terminal/output if the command fails or if explicit logs are needed.

This way, users can stay focused without interruptions while still having access to detailed logs when necessary. Would this approach be feasible?

**Comment by bwateratmsft** [comment]
We could make this a setting but I wouldn't want to change the default behavior as many users count on easily-discoverable command logs.

**Comment by bwateratmsft** [comment]
Thanks for bringing this up! We talked about it internally and decided we'd like to keep the current behavior.
