### ISSUE TITLE
the container could not be rebuilt

### ISSUE THREAD

**Issue by KCDaemon** [microsoft/vscode-docker#4424]
Does this occur consistently? yes
Repro steps:

1.rebuild the container
2.rebuilding codespace always leads to a stop

Version: 1.29.3
OS: linux
OS Release: 6.5.0-1025-azure
Product: Visual Studio Code
Product Version: 1.95.3
Language: zh-tw

**Comment by bwateratmsft** [comment]
@KCDaemon what error are you seeing?
