### ISSUE TITLE
Docker push: Cancelling at the quick pick gives a user-facing error: 

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#443]
Repro steps:
Command Palette -> Docker push -> Hit escape (do not pick an image)

Action: vscode-docker.image.push
Error type: TypeError
Error Message: Cannot read property 'includes' of undefined

Version: 0.1.1-alpha
OS: win32

**Comment by StephenWeatherford** [comment]
Dupe of #440
