### ISSUE TITLE
Docker Extension: Can not connect to docker engine when used on SSH remote machine

### ISSUE THREAD

**Issue by qkhanhpro** [microsoft/vscode-docker#4434]
I am using VSCode remotely on Ubuntu remote machine using SSH 

Host MyHost
    HostName 18.x.x.x
    User ubuntu
    IdentityFile C:\Users\dqkpr\keys...

On the host there is docker running. 
`docker info `
shows
```
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.7.0
    Path:     /home/ubuntu/.docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-1103-aws
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 974.2MiB
 Name: ip-172-26-3-161
 ID: H742:C3FI:2PRJ:QJJV:LFUS:ZAF2:H34X:TZ2U:QPLP:G62O:HFMJ:MJLL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

However the extension seems unable to connect to docker 
![image](https://github.com/microsoft/vscode-docker/assets/10443536/d7919d6e-3ec8-4799-bc88-ad4904c23dd2)

If I close the VSCode windows and connect again, docker commands in my terminal hang indefinetely until I do `unset $DOCKER_HOST`

I use this configuration to connect to multiple different Ubuntu remote host and only 1 machine face this issue

**Comment by bwateratmsft** [comment]
@qkhanhpro do you have a value for the setting `docker.environment`, either in user or workspace settings? We set environment variables that come from that setting.

**Comment by Savagery504** [comment]
I don't know

**Comment by qkhanhpro** [comment]
> [@qkhanhpro](https://github.com/qkhanhpro) do you have a value for the setting `docker.environment`, either in user or workspace settings? We set environment variables that come from that setting.

Hi @bwateratmsft Thank you, you are right ! 
In the remote host the setting docker.environment is indeed set to ssh://54... 
Removing that setting fixed the issue
