### ISSUE TITLE
vscode-docker on Windows 10: Wrong build path for subfolder

### ISSUE THREAD

**Issue by Szauka** [Microsoft/vscode-docker#455]
* VSCode Version: 1.26.1 (stable)
* VSCode-docker Version: 0.1.0
* OS Version: Windows 10 Build 16299.551

Steps to Reproduce:

1. Install Docker for Windows
1. Install VSCode
1. Add Docker extension
1. Create an empty Folder (eg Test) with two subfolders (eg client and server) and open it in VSCode
1. Generate a Dockerfile on each of the subfolders (client & server)
1. Run Docker: Build from the command palette

![image](https://user-images.githubusercontent.com/33459309/45082345-0d353d80-b0f1-11e8-80ae-2165503e4ed9.png)

The Build fails then with docker build --rm -f client\Dockerfile -t test client
unable to prepare context: unable to evaluate symlinks in Dockerfile path: 
GetFileAttributesEx **D:\projects\test\clientDockerfile**: The system cannot find the file specified.

Works when build manually with correct parameters.

**Comment by PrashanthCorp** [comment]
Thanks for using the extension! 
We have made changes to the build-image UX, ready for release in 0.2.0. Currently, this is how it looks in my repro: 
![image](https://user-images.githubusercontent.com/30420973/45120626-8b0a4080-b113-11e8-91df-3e83d20f9b56.png)
This seems fixed for 0.2.0, which we plan to release soon. If this does not solve your problem, feel free to let us know. 

However, investigating this has shown us a couple other issues - thanks for reporting this! :)

**Comment by PrashanthCorp** [comment]
Yes. It looks fixed right now. Shall I close this?

**Comment by Szauka** [comment]
Is there a time frame for the 0.2.0 release?

**Comment by StephenWeatherford** [comment]
Probably tomorrow.

**Comment by StephenWeatherford** [comment]
@Szauka We just released 0.2.0.  Please let us know if this does not fix your issue.
