### ISSUE TITLE
No 'Dockerfile' shows on Command Palette list after selecting the suggested command 'Build Image' 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#456]
Repro Steps:
1. Open Command Palette, type 'build image'. 
2. Click the suggested command 'Build Image' on Command Palette list.

Expect:
Show up the 'Dockerfile' on Command Palette list.

Actual:
Show up the tagged prompt directly without selecting 'Dockerfile' on Command Palette list.
![prompt](https://user-images.githubusercontent.com/34729022/45086214-31454e80-b0f2-11e8-8937-f8500f6a5b38.png)

**Comment by StephenWeatherford** [comment]
If there's only a single Dockerfile we don't bother asking.  Thanks.
