### ISSUE TITLE
add context menus for common commands

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#46]
Dockerfile -> Docker Build, Run

Compose files -> compose up, compose down

**Comment by lostintangent** [comment]
#47 addresses the Docker Build scenario. Let me know what you think!

**Comment by chrisdias** [comment]
for compose, best i can do is have context menus if the file name is `docker-compose.yml` or `docker-compose.debug.yml`. VS Code doesn't support wildcards in the `resourceFilename` when clause.

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode/issues/26044
