### ISSUE TITLE
[build] Suggested name only suggests parent folder, not the full relative path

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-docker#460]
A nested Dockerfile, eg. `bin/xyz/Dockerfile` would show 'xyz:latest' not `bin/xyz:latest`. 

Culprit: the basename call here
https://github.com/Microsoft/vscode-docker/blob/d1bc4a1d4709014d885d7a02664525c2c1934564/commands/build-image.ts#L104

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Why would you want an image named bin/xyz:latest?  That would indicate a dockerid of "bin"

**Comment by PrashanthCorp** [comment]
My bad. I misunderstood this. Closing.
