### ISSUE TITLE
Fail to pop up the information message after restarting the Docker extension

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#461]
Repro Steps:
1. Go to the user setting -> Set the defaultRegistryPath to TestV2.
2. Uninstall the docker extension->reload->Install the Docker extension again -> reload.
3. Check whether pop up an information message or not after restarting the VS Code.

Expect:
Pop up an information message.
![expect](https://user-images.githubusercontent.com/34729092/45153394-52c23b00-b1c3-11e8-9076-77b8d4195b72.png)

Actual:
Fail to pop up the information message.

**Comment by StephenWeatherford** [comment]
Won't fix. This functionality isn't important after this last release since they will have already updated.
