### ISSUE TITLE
Duplicate command registration

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-docker#467]
Issue Type: <b>Bug</b>

See  the following in my log:

> extensionService.ts:920 [PeterJausovec.vscode-docker]: Command `vscode-docker.delete-ACR-Image` appears multiple times in the `commands` section.

Extension version: 0.2.0
VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:12:30.432Z)
OS version: Darwin x64 16.7.0

**Comment by StephenWeatherford** [comment]
Thanks.
