### ISSUE TITLE
GitLab Registry (on premise) with 2FA enabled (Personal Access Token) returns 401 Unauthorized

### ISSUE THREAD

**Issue by ghost-of-turek** [Microsoft/vscode-docker#468]
I use the GitLab instance hosted on premise by the company I work for. I use 2FA authentication, so the only way to login is to use a Personal Access Token, which I input in place of a password.

When trying to connect to GitLab Docker Registry with the extension, I get the `401 Unauthorized` response:

>Error: 401 - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

The same access token works fine when I connect to the same registry using `docker login docker-registry.company.com`.

**Comment by StephenWeatherford** [comment]
We don't yet support GitLab, just private registries.  This is tracked by #162.  Thanks for trying it out, though.

**Comment by ghost-of-turek** [comment]
Thanks, I was sure that GitLab Registry behaves just like a regular Docker Registry, especially that `docker login` can connect to it without a hitch.
