### ISSUE TITLE
Log in to docker when pushing images to Docker Hub

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#469]
Repro Steps:
1. Make sure log into Docker Hub successfully under Registry.
2. Tag any images as the username of Docker Hub.
3. Attempt to push the tagged image.

Expect:
The image can be pushed to Docker Hub successfully.

Actaul:
Fail to push the image to Docker Hub.
![denied](https://user-images.githubusercontent.com/34729022/45349488-ed928f00-b5a0-11e8-8b65-b4eee67ff87c.png)

**Comment by StephenWeatherford** [comment]
dupe of #351
