### ISSUE TITLE
add trailing slash automatically for private docker repositories

### ISSUE THREAD

**Issue by n0mer** [Microsoft/vscode-docker#471]
hello, i'm running self-hosted hexus for private docker registry.

This extensions tries REPO_URL/v2 for API endpoint, but Nexus by default returns http/404 for "/v2" url.

Work-around is to add this

```
rewrite ^(\/v2)$ $1/ permanent;
```

in nginx.

But, is there any chance that this extension will probe REPO_URL/v2/ (with trailing slash) as well?

**Comment by StephenWeatherford** [comment]
Looks like v2/ is actually the correct call (https://docs.docker.com/registry/spec/api/#api-version-check).

**Comment by StephenWeatherford** [comment]
@n0mer Would you be willing to try a private build with a fix?  It's here: https://azcode.blob.core.windows.net/vscode-docker/saw/v2slash/667/vscode-docker-0.2.0.vsix.  Choose 'Install from VSIX" from the command palette.  Thanks!

**Comment by StephenWeatherford** [comment]
@n0mer We just released a new version of the extension with this fix.  Please try it out and let us know if you're still having problems.

**Comment by SurrealTiggi** [comment]
@StephenWeatherford was having the same issue and looks like it's working perfectly now, thanks!

**Comment by StephenWeatherford** [comment]
Great to hear, thanks for letting us know!
