### ISSUE TITLE
Typo in extensions store description

### ISSUE THREAD

**Issue by carbureted** [Microsoft/vscode-docker#48]
"The Docker extension it easy to build and deploy containerized applications from Visual Studio Code." should probably be "The Docker extension **makes** it easy to build and deploy containerized applications from Visual Studio Code."

**Comment by lostintangent** [comment]
@carbureted Thanks for letting us know! We recently fixed this in the `README` in this repo, but that change hasn't been published to the marketplace yet. We'll be publishing an update soon with some new improvements, and will include this typo fix as well.

**Comment by chrisdias** [comment]
this is fixed in master so closing.
