### ISSUE TITLE
'Run Interactive'/'Run' doesn't work for "hello-world:latest" image

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-docker#482]
**Repro Steps**:
1. Run 'docker run hello-world' command -> Make sure the 'hello-world: latest' displays under Images node.  
2. Right click 'hello-world: latest' -> Execute 'Run Interactive'.
3. Check the result.

**Expect**:
 'Run Interactive'/'Run' works well for "hello-world:latest"

**Actual**:
 'Run Interactive'/'Run' doesn't work for "hello-world:latest".

**More Info:**
1. This issue doesn't reproduce on the previous release docker extension 0.2.0.
2. 'Run Interactive'/'Run' works well for "registry" image.

**Comment by StephenWeatherford** [comment]
Please let us know what result you actually see rather than simply saying "it doesn't work."

This is what I'm seeing, which looks correct:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\Repos\vscode-docker> docker run --rm -it hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

PS C:\Repos\vscode-docker>
```

**Comment by StephenWeatherford** [comment]
Okay, I see it now in master.  Thanks.

**Comment by v-haiz** [comment]
@StephenWeatherford Ok. And I will give a direct result with screenshot the next time if it makes sense for you.(●'◡'●)

**Comment by StephenWeatherford** [comment]
Thanks.  In this case, saying something like "nothing happens" or "it doesn't do anything" is much better than "it doesn't work", which could mean anything.  Nice catch, by the way.

**Comment by v-haiz** [comment]
Ok, thanks for your sharing.
