### ISSUE TITLE
No prompting displays when there is no available repository to delete after executing 'Docker: Delete Azure Repository'

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-docker#487]
**Repro Steps**:
1. F1 ->  Type and select 'Docker: Delete Azure Repository' -> Select a registry which have no repository to use -> make sure the placeholder prompts to select the repository you want to delete.
2. Check the result.

**Expect**:
Prompt the customers that there is no available repository to delete.

**Actual**:
Keep showing 'Select the repository you want to delete ' and there is no any prompting.
![actual1](https://user-images.githubusercontent.com/37653604/45678734-9c494900-bb26-11e8-93d5-bf0280afd2b2.PNG)

**Comment by StephenWeatherford** [comment]
Good bug, but won't fix for now.
