### ISSUE TITLE
Docker Catalog Error with HTTP-404

### ISSUE THREAD

**Issue by ya5hw4nth** [Microsoft/vscode-docker#488]
The same works with /v2/_catalog

&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.connectCustomRegistry
Error type: StatusCodeError
Error Message: 404 - "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /v2 was not found on this server.</p>\n</body></html>\n"

Version: 0.2.0
OS: win32

**Comment by StephenWeatherford** [comment]
This is likely a dup of #471 

Would you be willing to try a private build with a fix? You can download it here: https://azcode.blob.core.windows.net/vscode-docker/saw/v2slash/667/vscode-docker-0.2.0.vsix. Choose 'Install from VSIX" from the command palette. Thanks!

**Comment by StephenWeatherford** [comment]
@ya5hw4nth We just released a new version of the extension with this fix.  Please let us know if it doesn't work for you.

**Comment by ya5hw4nth** [comment]
it works perfectly now!

**Comment by StephenWeatherford** [comment]
Great to hear, thanks for letting us know!
