### ISSUE TITLE
Add a 1.8 supported Docker launch snippet

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-docker#49]
VS Code 1.8 support to add launch configurations: https://code.visualstudio.com/updates#_debugging

The Docker extension should provide a launch configuration snippet. For an example see: https://github.com/Microsoft/vscode-mock-debug/blob/master/package.json#L71

//CC @chrisdias @lostintangent

**Comment by lostintangent** [comment]
Oh nice! I was actually curious how the list of available configurations to add was populated, so thanks for the pointer :)  This will definitely be a nice addition.

**Comment by chrisdias** [comment]
should be easy enough, we already contribute a debug configuration.

**Comment by chrisdias** [comment]
i think this is fixed.
