### ISSUE TITLE
Only display the image's tag when trying to run 'Delete Azure Image' command

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#491]
Repro Steps:
1. Open Command Palette -> Type 'Delete Azure Image' -> Select one regisrty to use -> Select one repository of the image you want to delete.
2. Check popped prompting list.

Expect:
Display the format like [Image_name]:tag.

Actual:
Only display the image's tag.
![tag](https://user-images.githubusercontent.com/34729022/45743777-5d7dc680-bbec-11e8-9504-65a644cac75b.png)

**Comment by StephenWeatherford** [comment]
Not a regression

**Comment by StephenWeatherford** [comment]
Triage: just add the name of the repository to the prompt
