### ISSUE TITLE
Private registry, self-signed certificate does not work: "can not verify first certificate"

### ISSUE THREAD

**Issue by SebastianSchuette** [Microsoft/vscode-docker#497]
The feature "connect to private registry" does not work for a private registry with a self-signed certificate. You get an error "can not verify first certificate".

IMHO, having self signed certificates is very common for private registries.

**Comment by StephenWeatherford** [comment]
Is this server on localhost?  Thx.

**Comment by SebastianSchuette** [comment]
Hi,

I am using the python debugger running on my Windows machine. It is started from Visual Studio code. So yes, all running locally.

Regards,

Sebastian

Von: Stephen Weatherford (MSFT) <notifications@github.com>
Gesendet: Dienstag, 25. September 2018 22:10
An: Microsoft/vscode-docker <vscode-docker@noreply.github.com>
Cc: Sebastian Schuette <sebastian.schuette@bayer.com>; Author <author@noreply.github.com>
Betreff: Re: [Microsoft/vscode-docker] Private registry, self-signed certificate does not work: "can not verify first certificate" (#497)


Is this server on localhost? Thx.

**Comment by aarongilliland** [comment]
I would like to see this addressed as well. I am not using a localhost. I am using a registry with a self-signed certificate and I am able to reach it through the browser but I get the same Error:self signed certificate message why trying to add the registry. 
+1

**Comment by StephenWeatherford** [comment]
Thanks, we're hoping to look into this soon. vscode doesn't currently have built-in proxy support for extensions. You can try setting "http.proxyStrictSSL" to false in settings and see if that fixes it for the moment, but that does carry security risks.

**Comment by StephenWeatherford** [comment]
Tracking this in #483

**Comment by StephenWeatherford** [comment]
@aarongilliland @SebastianSchuette Could you please try the new functionality for [trustede certificates and certificate stores](https://github.com/microsoft/vscode-docker#self-signed-and-corporate-certificates) and see if that works instead of setting http.proxyStrictSSL to false? Thanks.
