### ISSUE TITLE
Add Docker files to workspace fails on platform ruby (Unknown error)

### ISSUE THREAD

**Issue by J-Vaughan** [Microsoft/vscode-docker#498]
# `Docker: Add Docker files to workspace` fails on platform ruby (Unknown error)

## Repro steps:

1. Install Docker tools and docker extension on vscode 1.28.0-insider (user setup), that is both the extension in the extension pane and the extended support on the Welcome page.

2. Open an empty folder (no git, nothing). Mine was called cardiovascular.

3. From the command palette (CTRL-SHFT-p) run `Docker: Add Docker files to workspace`, when asked for platform select `ruby`, port 3000 (default)

4. > Unknown error occurred.

No files created in workspace.

## Info

Action: vscode-docker.configure
Error type: object
Error Message: Unknown Error

Version: 0.2.0
OS: win32

**Comment by StephenWeatherford** [comment]
Weird, I haven't been able to repro this, either in the currently released version or the new one.  We'll be releasing a new version very soon, so you could try it again then.  Does this happen every time?

**Comment by J-Vaughan** [comment]
It happens every time, but it just occurred to me that I haven't actually
tested whether or not my Docker install works. Let me get back to you on
that.

**Comment by StephenWeatherford** [comment]
This appears to be an issue with vscode 1.28.0-insider.  I don't see it on released vscode.

**Comment by J-Vaughan** [comment]
I think you're right. You can close this. Thanks!

**Comment by StephenWeatherford** [comment]
Reported here: https://github.com/Microsoft/vscode/issues/59138

**Comment by StephenWeatherford** [comment]
Thanks for reporting this before it came out of insiders!
