### ISSUE TITLE
Docker files added to workspace of ASP.NET Core 2.1 project are incorrect

### ISSUE THREAD

**Issue by philliphoff** [Microsoft/vscode-docker#499]
When adding Docker files to the workspace of an ASP.NET Core 2.1 project, the Dockerfile uses the 2.0 base images (e.g. `microsoft/aspnetcore:2.0 `), rather than the new .NET Core 2.1 base images (e.g. `microsoft/dotnet:2.1-aspnetcore-runtime`).

The scaffolding command should either prompt the user to select the version of .NET Core or (better) extract the target framework from the project file.

**Comment by StephenWeatherford** [comment]
Thanks for filing.  See https://github.com/Microsoft/vscode-docker/issues/465.

Would love to have you beta test this.  We're probably releasing tomorrow: https://azcode.blob.core.windows.net/vscode-docker/master/754/vscode-docker-0.3.0.vsix

**Comment by philliphoff** [comment]
I discovered this was fixed as soon as I merged my branch with `master` (which, of course, was immediately after I filed the issue).  I'll try out the changes.

**Comment by spboyer** [comment]
Tested and confirmed in https://github.com/Microsoft/vscode-docker/releases/tag/v0.3.1

**Comment by StephenWeatherford** [comment]
@spboyer @philliphoff Great, thanks!
