### ISSUE TITLE
Error while generating Dockerfile for 'other'

### ISSUE THREAD

**Issue by humb1t** [Microsoft/vscode-docker#504]
Repro steps:

1.  Press 'F1' and  search for Docker: Add Docker files to Workspace
1.  Select 'Other' Application platform
1.  Enter port (8000 in my case)

Action: vscode-docker.configure
Error type: ERR_ASSERTION
Error Message: Could not find dockerfile generator functions for "Other"

Version: 0.3.0
OS: win32

**Comment by StephenWeatherford** [comment]
Resolved by #509
