### ISSUE TITLE
notification overload

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#515]
when i "add dockerfiles to the workspace", i get a prompt that tells me files were added to my workspace.  This seems unnecessary:

* the command i executed indicated that i wanted to add files to my workspace
* i can see that new files were added because they show up in my explorer
* i can see that files were added because i am using source code control

For the past few years i don't remember anyone complaining that this was an issue, but now i have to click again to dismiss the notification.

**Comment by StephenWeatherford** [comment]
P1 just for Chris.
