### ISSUE TITLE
Add support for debugging .NET containers

### ISSUE THREAD

**Issue by Andrew-MSFT** [Microsoft/vscode-docker#516]
cc @fiveisprime 

https://github.com/OmniSharp/omnisharp-vscode/issues/1369

**Comment by fiveisprime** [comment]
This was a customer request at Ignite. He said he uses debugging in containers for node via the generated debug compose config and wants that to work for .NET as well.

Thanks Andrew!

**Comment by robrich** [comment]
And since it's open-source, if you agree (and with a little direction), I don't mind PRing it into place.

**Comment by StephenWeatherford** [comment]
@philliphoff Your PR will handle this, right?

**Comment by StephenWeatherford** [comment]
#500

**Comment by philliphoff** [comment]
> Your PR will handle this, right?

My [PR](https://github.com/Microsoft/vscode-docker/pull/500) adds debugging for individual .NET Core web apps/services using their generated Dockerfiles.  It *does not* allow any multi-service debugging via Docker Compose.  (An earlier comment mentioned "compose config", and I'm not sure if they actually meant Docker Compose (YAML) configuration or just the Dockerfile.)

**Comment by StephenWeatherford** [comment]
Should already be supported.
