### ISSUE TITLE
Fail to 'Attach Shell' for 'registry' with error

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#518]
Repro Steps:
1. Run 'docker run registry'.
2. Navigate to 'Containers' node -> Right click the 'registry' container ->Select 'Attach Shell'.
3. Check the result.

Expect:
Succeed to execute 'Attach Shell' fro container 'registry'.

Actual:
Fail to Fail to 'Attach Shell' for 'registry' with error.
![compare](https://user-images.githubusercontent.com/34729092/46255317-0d73ef00-c48b-11e8-9908-9d0138424050.PNG)

**Comment by StephenWeatherford** [comment]
#480
