### ISSUE TITLE
[Suggestion] Keep the same form for the notifications after creating and deleting a registry successfully

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#519]
Repro Steps:
1. Right clicking on the ‘Azure’ node in the Docker Explorer -> Click ‘Create Azure Registry’.
2. Check the notification popping up after creating an azure registry successfully .
3. Right clicking on the registry created in Step2  -> Click ‘Delete Azure Registry’ and delete it.
4. Check the notification popping up after deleting the azure registry successfully .

Actual:
Notifications popping up after successfully creating or deleting a registry with different forms.
![capture1](https://user-images.githubusercontent.com/41351993/46255082-7d34aa80-c488-11e8-9b53-8bf4892fd001.PNG)

Suggestion:
Notifications popping up after successfully creating or deleting a registry with the same form .

**Comment by StephenWeatherford** [comment]
Sorry, won't fix.
