### ISSUE TITLE
IntelliSense and file association for docker-stack.yml

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-docker#520]
It is not uncommon to name docker-compose.yml something different, like docker-stack.yml, for swarm mode/stack files. I tried to add the following configuration to get IntelliSense but that did not work, as it thought it was a normal Dockerfile:

```json
"files.associations": {"docker-*.yml":"dockerfile"}
```

Is there a way to assign other docker "stack" files to the extension to get IntelliSense?

**Comment by Larswa** [comment]
Yes please! As I am starting to implement docker swarm, it is a little annpying having to name all my stack configs docker-compose to get intellisense.

**Comment by EricJizbaMSFT** [comment]
@thernstig @Larswa I believe you want to specify the file type as "yaml" and not "dockerfile" as mentioned [here](https://github.com/microsoft/vscode-docker/issues/192#issuecomment-353517815):
```
"files.associations": {
    "docker-*": "yaml"
}
```

**Comment by thernstig** [comment]
@EricJizbaMSFT that does unfortunately not give IntelliSense to work for Docker. There is no difference in naming it yaml or yml, both will give yaml syntax highlighting. What we are after is for also IntelliSense to work.

**Comment by EricJizbaMSFT** [comment]
@thernstig We've got a number of issues related to non-standard naming of these files, so I'm just trying to consolidate and make sure everyone is aware of all possible workarounds. Good to know exactly where the current workarounds falls short - thanks!

**Comment by bwateratmsft** [comment]
I think this depends on #37.

**Comment by bwateratmsft** [comment]
Duping to #2539
