### ISSUE TITLE
Connection to Private Registry (Docker Trusted Registry) fails

### ISSUE THREAD

**Issue by sujaypillai** [Microsoft/vscode-docker#524]
We have a DTR instance running behind our firewall and on trying to connect to this from Docker Explorer -> Registries it gives me the below error.

Repro steps:
1. Open the Docker: Explorer
2. Navigate to Registries -> Private Registries
3. Right click -> Connect to a private registry
4. Enter the registry URL -https://myhub.registry.com
5. Enter the username - myuser
6. Enter the password - my password

VSCode fails to establish the connection to my private registry.

Action: vscode-docker.connectCustomRegistry
Error type: RequestError
Error Message: Error: unable to get local issuer certificate

Version: 0.3.1
OS: darwin

**Comment by sujaypillai** [comment]
From within the integrated terminal it allows me to login to the same DTR instance.

**Comment by StephenWeatherford** [comment]
Should be fixed by #627
