### ISSUE TITLE
sqlserver

### ISSUE THREAD

**Issue by 211003514** [Microsoft/vscode-docker#532]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.configure
Error type: Error
Error Message: Docker files can only be generated if VS Code is opened on a folder.

Version: 0.3.1
OS: darwin

**Comment by StephenWeatherford** [comment]
@211003514 Please follow the error message - you need to actually open your project or solution folder inside VS before using 'Add Docker Files to Workspace' so that we can find related files needed to figure out the current context.  Thanks.

**Comment by StephenWeatherford** [comment]
I've improved the error message a bit.  Thanks for reporting, let us know if you're still having issues.
