### ISSUE TITLE
Extension slow startup time

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode-docker#535]
When starting VS Code after the upgrade to 1.28.0, VS Code gives you status about the Extension Host and slow extensions. The Extension Host becomes a bit unresponsive, and opening it shows that the Docker extension is slow. Over 10 seconds. This gives the error seen here:

https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive

Here is a screenshot of some random extensions:
![capture](https://user-images.githubusercontent.com/30827238/46737134-07f08300-cc9b-11e8-9616-066c58322f4c.PNG)

**Comment by StephenWeatherford** [comment]
We're aware of some recent sporadic performance issues that we are looking into. Thanks for reporting this.

**Comment by StephenWeatherford** [comment]
Note: this is improved a bit in 0.4.0 (delayed activating Azure Account extension), releasing soon.  Expect much bigger improvements in 0.5.0...

**Comment by StephenWeatherford** [comment]
@thernstig This was fixed in v0.5.0.
