### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Rihards12** [Microsoft/vscode-docker#536]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.configure
Error type: Error
Error Message: No .csproj file could be found.

Version: 0.3.1
OS: win32

**Comment by StephenWeatherford** [comment]
@Rihards12  .NET Core is C#-based and requires a .csproj file in the workspace. Here's a tutorial that works through a simple example: https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial#windowscmd

If that doesn't solve your problem, please let us know.  Thanks!
