### ISSUE TITLE
Can't connect to Nexus container registry

### ISSUE THREAD

**Issue by GyuhyeokYi** [Microsoft/vscode-docker#537]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.connectCustomRegistry
Error type: 404
Error Message: 404 - "\n<!DOCTYPE html>\n<html>\n<head>\n  <title>404 - Nexus Repository Manager</title>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n\n\n  \n  <link rel=\"icon\" type=\"image/png\" href=\"http://localhost:8081/favicon-32x32.png?3.13.0-01\" sizes=\"32x32\">\n  <link rel=\"mask-icon\" href=\"http://localhost:8081/safari-pinned-tab.svg?3.13.0-01\" color=\"#5bbad5\">\n  <link rel=\"icon\" type=\"image/png\" href=\"http://localhost:8081/favicon-16x16.png?3.13.0-01\" sizes=\"16x16\">\n  <link rel=\"shortcut icon\" href=\"http://localhost:8081/favicon.ico?3.13.0-01\">\n  <meta name=\"msapplication-TileImage\" content=\"http://localhost:8081/mstile-144x144.png?3.13.0-01\">\n  <meta name=\"msapplication-TileColor\" content=\"#00a300\">\n\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"http://localhost:8081/static/css/nexus-content.css?3.13.0-01\"/>\n</head>\n<body>\n<div class=\"nexus-header\">\n  <a href=\"http://localhost:8081\">\n    <div class=\"product-logo\">\n      <img src=\"http://localhost:8081/static/images/nexus.png?3.13.0-01\"/>\n    </div>\n    <div class=\"product-id\">\n      <div class=\"product-id__line-1\">\n        <span class=\"product-name\">Nexus Repository Manager</span>\n      </div>\n      <div class=\"product-id__line-2\">\n        <span class=\"product-spec\">OSS 3.13.0-01</span>\n      </div>\n    </div>\n  </a>\n</div>\n\n<div class=\"nexus-body\">\n  <div class=\"content-header\">\n    <img src=\"http://localhost:8081/static/rapture/resources/icons/x32/exclamation.png?3.13.0-01\"/>\n    <span class=\"title\">Error 404</span>\n    <span class=\"description\">Not Found</span>\n  </div>\n  <div class=\"content-body\">\n    <div class=\"content-section\">\n      Not Found\n    </div>\n      </div>\n</div>\n</body>\n</html>\n\n"

Version: 0.3.1
OS: darwin

**Comment by StephenWeatherford** [comment]
We're working on third-party support.  However, a 404 sounds suspicious.  What does the URL look like that you gave to vscode (you can replace user/project names with <username>, <projectname> etc if you'd like)?  Thanks.  If you do a "curl <server-url>/v2/" you should see something other than 404 (probably a 401).

**Comment by StephenWeatherford** [comment]
Need to see if we support this when done with third-party registry work.
