### ISSUE TITLE
Intellisense makes no sense

### ISSUE THREAD

**Issue by Bazmundi** [Microsoft/vscode-docker#538]
- visual code studio 1.27.2
- debian 9 stretch amd64
- docker 0.3.1 plug-in
- docker-compose 0.3.0 plug-in
- docker-compose.yml file in editor
- no intellisense suggestions for things like image:drupal etc (going by examples in udemy lecture 54 of  docker-mastery.
- change file extension to xx.yaml, still no intellisense running
- docker whale icon in top left hand corner suggests file is associated with docker

**Comment by StephenWeatherford** [comment]
@Bazmundi We don't currently have specific Intellisense for compose files like we do for Dockerfile (beyond the syntax help that vscode already provides). This is a feature we are considering, so thank for filing.  What features would you most like to see auto completion for?

**Comment by Bazmundi** [comment]
I am only going by videos of user who provides course on udemy. In that
video he is demonstrating code completion on docker-compose file. I might
need ask him what plugin he was using. Not yours obviously. Sorry. My
mistake.

**Comment by rcjsuen** [comment]
There is a [`dockerComposeCompletionItemProvider.ts`](https://github.com/Microsoft/vscode-docker/blob/46bba4d233691cf07637895da21e41b3eb71cebc/dockerCompose/dockerComposeCompletionItemProvider.ts) file but I'm not really sure how much it's supposed to provide.

See #128 and its many duplicates.

**Comment by Bazmundi** [comment]
Yep, thanks.  I will report back once the lecturer from Udemy has clarified
the extension they are using.

**Comment by StephenWeatherford** [comment]
@Bazmundi Actually I need to apologize.  I took the extension over fairly recently and was told there was no IntelliSense for docker compose files, but that was not correct, it does, including image completion, plus completion of schema for two levels, depending on which version is specified in the file.

So the question is, what exactly are you seeing?  Here's an example of it working on docker-compose.yml:
![compose](https://user-images.githubusercontent.com/6913354/46912055-4d25e680-cf21-11e8-9164-899e038d3d5c.gif)
One thing to note: if you type CTRL+SPACE without typing part of the image first, you'll only get a set of "popular" images. Typing only 'd' first doesn't seem to work - this appears to be a docker hub issue (same if you type 'd' in the searchbox there). Typing 'dr' causes it to actually search the hub.

If you type CTRL+SPACE first and then continue typing, it will still only show the popular list. That looks like a possible vscode issue.

Are you seeing any of this?  Thx.

**Comment by Bazmundi** [comment]
DOH! New user blues.  The missing magic was CTRL-SPACE.

**Comment by StephenWeatherford** [comment]
@Bazmundi Glad to hear it's working for you now! And sorry for the confusion. :-) Please do let us know if you find things we should improve.

**Comment by StephenWeatherford** [comment]
The issue of requiring CTRL+SPACE in compose files but not Dockerfiles is being tracked in #243
