### ISSUE TITLE
Add completion support for Docker Compose v3.0 files

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode-docker#54]
Docker Compose v1.10 introduces a new v3 file format, so we'll need to add support for it as it approaches GA.

**Comment by lostintangent** [comment]
Docker Compose 1.10 was released last week, so I'll get to this item later this week.

**Comment by bkbonner** [comment]
From what i can tell, this is primarily secrets support?

**Comment by jamesmoey** [comment]
Hi @lostintangent how is this issue coming along? would love to help.

**Comment by PrashanthCorp** [comment]
@jamesmoey Do you still run into this issue? We'd like some context on this before prioritizing this.

**Comment by bwateratmsft** [comment]
@lostintangent Can you add some more context on this (admittedly old) issue?
