### ISSUE TITLE
Log in to Docker Hub automatically when pushing or pulling

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#540]

**Comment by EricJizbaMSFT** [comment]
Pulling was handled here: https://github.com/microsoft/vscode-docker/pull/966
Pushing is being tracked here: https://github.com/microsoft/vscode-docker/issues/351

**Comment by v-dantch** [comment]
Add the screenshot for it:
![image](https://user-images.githubusercontent.com/34729092/59491657-c95e3880-8eb9-11e9-8fa0-770c03c65575.png)
