### ISSUE TITLE
[Suggestion]Validate against existing web apps when deploying image to Azure App Service

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#543]
Platform/OS Version: Win 10
Node.js: 8.9.3
Extension: https://azcode.blob.core.windows.net/vscode-docker/master/830/vscode-docker-0.3.2-alpha.vsix

Repro Steps:
1. Drill down from Registries -> Private Registries.
2. Expand one private registry -> Right click one image ->Select 'Deploy Image to Azure App Service'.
3. Select one subscription if there are 2 at least ->Select one resource group -> Select one App Service Plan -> Enter a name for the new web app according to the notification.

Actual:
Don't validate against existing web apps.

Suggestion:
Validate against existing web apps when typing the new web app name. In this case, we don't need to start from 1st step if the web app name is existing.

**Comment by StephenWeatherford** [comment]
When we move to using the new code, the experience will be better and this code will be obsolete.

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
