### ISSUE TITLE
docker commend not available on VS code

### ISSUE THREAD

**Issue by cvpeceee** [Microsoft/vscode-docker#562]
(env) PS C:\Users\Source\Repos\flask-webapp-quickstart> docker login zerotoazure1.azurecr.io

Error : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.

Action: vscode-docker.container.open-shell
Error type: Error
Error Message: Unable to connect to Docker, is the Docker daemon running?

Version: 0.3.1
OS: win32

**Comment by StephenWeatherford** [comment]
@cvpeceee You need to have docker installed and on the system PATH for these commands to work.

**Comment by StephenWeatherford** [comment]
Let us know if that does not resolve your problem, thanks.
