### ISSUE TITLE
Respect docker-compose.override.yml by default

### ISSUE THREAD

**Issue by johnmcdowall** [microsoft/vscode-docker#569]
This may be related to #379 and #261. 

The default canonical behavior of the `docker-compose` command line tool is that if you have a `docker-compose.override.yml` file, when running `docker-compose up` it will look at your `docker-compose.yml` and then `docker-compose.override.yml` file as well, automatically. Nothing more needs to be specified via switches, it just works. 

What this extension currently does is to specify the `-f` flag bye default for whatever selected compose file is being targeted, breaking the automatic inclusion of `docker-compose.override.yml` and producing an unexpected experience. 

I feel this is a separate issue from people using `docker-compose.whatever.yml` files, as those would have to be specified in order with the `-f` flag to `docker-compose` anyway. 

I'd propose that the default behavior of this extension's `docker-compose up` command should be to look for the presence of a `docker-compose.override.yml` file, and if it's present append a `-f docker-compose.override.yml` to the command arguments.

I suggest this because it seems more straightforward to implement this than dealing with VSCode's current inability to determine what the order between a larger collection of `docker-compose.whatever.yml` files should be - in the case above we know that the order is always `-f docker-compose.yml -f docker-compose.override.yml`.

Implementing that behavior will bring this extension into line with how the `docker-compose` command line tool works, reducing unexpected and confusing behaviour, and allows breaking off the bigger task hinted at in #379 and #261 of handling general collections of `.yml` files or making `-f` be optional to a later date.

**Comment by ravipal** [comment]
Fixed by #1603

**Comment by bwateratmsft** [comment]
Hey @johnmcdowall , this is now available in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
