### ISSUE TITLE
Show ports the container is exposing

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-docker#571]
It would be great to see a way to hide/show the ports exposed by a container. this would help when you have port conflicts and cant figure out who has them occupied.

**Comment by StephenWeatherford** [comment]
You thinking of this going in the label?

**Comment by StephenWeatherford** [comment]
Re-open, would be useful.

**Comment by johnpapa** [comment]
Yes the label would be great.

The reason this came up was because I often have containers running on ports, and it helps identify if there’s a conflict before one happens.

**Comment by EricJizbaMSFT** [comment]
Just merged #989 to support custom settings for displaying containers (including ports). @johnpapa if you've got the time, we'd appreciate your feedback! You can install the latest build from master with these instructions: https://aka.ms/azCodeInsiders

**Comment by johnpapa** [comment]
Thanks. I just grabbed 0.6.3.alpha from the vsix tried it and I do not see the label showing the port. Where should i be looking?

![image](https://user-images.githubusercontent.com/1202528/59640699-e3538180-912c-11e9-8d6a-e10698b1d2ec.png)

**Comment by EricJizbaMSFT** [comment]
The port won't be there by default, but you can add it in your own settings. You should see a "settings" icon like this on the containers view:
![Screen Shot 2019-06-13 at 4 16 51 PM](https://user-images.githubusercontent.com/11282622/59473418-3b217e00-8df7-11e9-86c6-32120644de87.png)

Which will let you use the port for either the grouping, label, or description

**Comment by johnpapa** [comment]
OK - I see this now.

I'll play around with it.

Early feedback - it is not obvious once I make changes how i can reset it to the defaults. This would be useful as some of the options I chose were clearly not what I wanted (as I explore). so it woul d be nice to go back to the original state - and I dont know if users will know what that is.

Maybe a `reset to original settings` ?

**Comment by EricJizbaMSFT** [comment]
> some of the options I chose were clearly not what I wanted (as I explore)

😂 ...yeah you can definitely do some interesting things with this... 😂

Good feedback! These are all backed by normal VS Code settings, so the easiest way to reset defaults (at least right now) is just delete them from your settings.json.

**Comment by johnpapa** [comment]
True - but I've learned through creating Peacock that people get dont seem to know that's what extensions are doing. So having a menu option that clearly resets it all to defaults is helpful. Obviously I am biased in my experienced though :)

I like what I see - I'll keep tinkering.
