### ISSUE TITLE
Cannot connect to external host

### ISSUE THREAD

**Issue by jrseliga** [Microsoft/vscode-docker#572]
I've setup `docker-machine` on an Ubuntu laptop and have created a new machine on an external Ubuntu host using the generic driver.

`docker-machine ls` now displays:
```
NAME          ACTIVE   DRIVER    STATE     URL                       SWARM   DOCKER        ERRORS
server           *               generic   Running   tcp://192.168.1.2:2376           v18.06.1-ce 
```
I've set `docker.host` to `192.168.1.2:2376` in Code on the laptop however I receive the error:
> Unable to connect to Docker, is the Docker daemon running?

**Comment by StephenWeatherford** [comment]
@jrseliga Have you seen these instructions for Linux?  https://github.com/Microsoft/vscode-docker#im-on-linux-and-get-the-error-unable-to-connect-to-docker-is-the-docker-daemon-running

**Comment by jrseliga** [comment]
Hey @StephenWeatherford, I used those to attempt to set this up

**Comment by StephenWeatherford** [comment]
Does running "docker" work from the system terminal?  If you start a terminal in vscode and run "docker", does it work?

**Comment by StephenWeatherford** [comment]
Closing due to lack of response. Feel free to re-open with new information, thanks.
