### ISSUE TITLE
 Unable to connect to Docker

### ISSUE THREAD

**Issue by RituRajSingh878** [Microsoft/vscode-docker#576]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.start.interactive
Error type: ENOENT
Error Message: Unable to connect to Docker, is the Docker daemon running?
Output from Docker: connect ENOENT //./pipe/docker_engine

Version: 0.3.1
OS: win32

**Comment by StephenWeatherford** [comment]
@RituRajSingh878 The error message pretty much says it all.  Is Docker running?  Can you successfully run docker commands on the command line (e.g. "docker images")?  Thx.

**Comment by RituRajSingh878** [comment]
No , that's the problem docker command says " it is not recognized as an internal or external command, operable program or batch file."

**Comment by StephenWeatherford** [comment]
You've followed the install instructions? https://docs.docker.com/docker-for-windows/install/

**Comment by RituRajSingh878** [comment]
I am doing this into vs studio code .
And install docker as an extension  for some project .
And i tried  many times to reinstall it but it doesn't work.

**Comment by StephenWeatherford** [comment]
I'm trying to verify that you actually have Docker for Windows installed.  It doesn't come packaged with the extension, you need to install it separately.   Thanks.

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.  Feel free to re-open with more info.
