### ISSUE TITLE
[Suggestion]Prompt to add required assets in need again after selecting 'Not Now'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#584]
**Platform/OS Version**: Win10/ Ubuntu 16.04 / MacOS High Sierra
**Node.js** : 8.9.3
**Extension Version**: [0.3.2--alpha](https://azcode.blob.core.windows.net/vscode-docker/master/895/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps**:
1. Make sure that Docker , .NET Core SDK (>=2.0) and C# extension are installed -> Make sure in 'Linux containers'.
2. Create a new .NET Core ASP.NET application by 'dotnet new web --name test' -> Open this application folder in VS Code.
3. Wait for and respond 'Not Now' when prompting to add required assets to build and debug.
4. Run 'Docker: Add Docker files to workspace' -> Add .NET Core launch task -> Debug.
5. Check the result.

**Actual:**
Pop up an error dialog 'Could not find the task 'build''.
![image](https://user-images.githubusercontent.com/34729092/47412686-faf58880-d79e-11e8-9bf1-f040ef6fd2b4.png)

**Suggestion:**
Prompt to add required assets in need again after selecting 'Not Now'.

**Comment by StephenWeatherford** [comment]
This behavior comes from the C# extension, not us. If you want to file an issue against them, you can do so here: https://github.com/OmniSharp/omnisharp-vscode/issues.  Thx.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
