### ISSUE TITLE
[Suggestion]Add a notification after succeeding to add the required assets

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#585]
**Platform/OS Version**: Win10/ Ubuntu 16.04 / MacOS High Sierra
**Node.js** : 8.9.3
**Extension Version**: [0.3.2--alpha](https://azcode.blob.core.windows.net/vscode-docker/master/895/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps**:
1. Make sure that Docker , .NET Core SDK (>=2.0) and C# extension are installed.
2. Make sure in 'Linux containers'.
3. Create a new .NET Core ASP.NET application by 'dotnet new web --name test'.
4. Open this application folder in VS Code.
5. Wait for and respond 'yes' when prompting to add required assets to build and debug.
![image](https://user-images.githubusercontent.com/34729092/47411625-f1b6ec80-d79b-11e8-8580-733dda3045fe.png)

**Actual:**
There is no any notification after succeeding to add the required assets.

**Suggestion:**
Add a notification after succeeding to add the required assets.

**Comment by StephenWeatherford** [comment]
This behavior comes from the C# extension, not us. If you want to file an issue against them, you can do so here: https://github.com/OmniSharp/omnisharp-vscode/issues.  Thx.
