### ISSUE TITLE
Display a confused error message when creating a new application with an existing application name

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#586]
**Platform/OS Version**: Win10/ Ubuntu 16.04 / MacOS High Sierra
**Node.js** : 8.9.3
**Extension Version**: [0.3.2--alpha](https://azcode.blob.core.windows.net/vscode-docker/master/895/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps**:
1. Make sure that Docker , .NET Core SDK (>=2.0) and C# extension are installed.
2. Make sure in 'Linux containers'.
3. Create a new .NET Core ASP.NET application by 'dotnet new web --name test'.
4. Create a another application named 'test/TEST'.
5. Check the error message.

**Expect:**
Display a clear error message.

**Actual:**
Display a confused error message.
![image](https://user-images.githubusercontent.com/34729092/47413098-faa9bd00-d79f-11e8-9ed5-e6a44452f053.png)

**Comment by StephenWeatherford** [comment]
This behavior comes from the dotnet CLI extension, not us.  Thx.
