### ISSUE TITLE
[Suggestion]Convert the location of 'Yes' and 'Don't Ask Again' when adding the required assets

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#587]
**Platform/OS Version**: Win10/ Ubuntu 16.04 / MacOS High Sierra
**Node.js** : 8.9.3
**Extension Version**: [0.3.2--alpha](https://azcode.blob.core.windows.net/vscode-docker/master/895/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps**:
1. Make sure that Docker , .NET Core SDK (>=2.0) and C# extension are installed.
2. Make sure in 'Linux containers'.
3. Create a new .NET Core ASP.NET application by 'dotnet new web --name test'.
4. Open this application folder in VS Code.
5. Pop up a dialog to prompt to add the required assets.

**Actual:**
Display 'Don't Ask Again' -> 'Not Now' -> 'Yes'.

**Suggestion:**
Convert the location of 'Yes' and 'Don't Ask Again'. For 'Yes' is more commonly used for customer.
![image](https://user-images.githubusercontent.com/34729092/47416544-89223c80-d7a8-11e8-8baf-cbe851347248.png)

**Comment by StephenWeatherford** [comment]
This behavior comes from the C# extension, not us.  If you want to file an issue against them, you can do so here: https://github.com/OmniSharp/omnisharp-vscode/issues
