### ISSUE TITLE
(HTTP code 409) conflict - conflict: unable to delete 4a689991aa24 (cannot be forced) - image has dependent child images

### ISSUE THREAD

**Issue by ValeraMax** [Microsoft/vscode-docker#588]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.image.push
Error type: Error
Error Message: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

Version: 0.3.1
OS: win32

**Comment by StephenWeatherford** [comment]
@ValeraMax I'm confused...  The title has nothing to do with the actual error in the repro steps.

**Comment by StephenWeatherford** [comment]
Closing due to lack for response. Feel free to reopen with more info.
