### ISSUE TITLE
Dockerfile should go in same folder as project

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#592]

**Comment by PrashanthCorp** [comment]
I might not be understanding this correctly. 
Do you have more info of cases when it does not place the dockerfile in the workspace folder?

**Comment by StephenWeatherford** [comment]
If you have multiple projects in the workspace, Dockerfiles should go in same folder as the project file.

**Comment by bwateratmsft** [comment]
I'm marking this one for milestone 0.10.0 since it may be essentially necessary for compose to work.

**Comment by dbreshears** [comment]
.Net Core is fixed in 0.10.0.  Separate item will be created for Node.js in 0.11.0
