### ISSUE TITLE
No notification displays after succeeding to add docker files to wokespace with Go language

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#594]
**Platform/ OS Version**: Win10
**Node.js:** 8.9.3
**Extension Version:** [0.3.2-alpha](https://azcode.blob.core.windows.net/vscode-docker/master/915/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps:**
1. Download an [application](https://github.com/cloudfoundry-community/simple-go-web-app/archive/master.zip) -> Extract it and open it in VS Code.
2. Run 'Docker: Add Docker Files to Workspace' -> Select 'Go' -> Keep '3000' as the port -> Build Image of Dockerfile.
3. Check the result.

**Expect:**
Display notifications after succeeding to add docker files to wokespace.
![image](https://user-images.githubusercontent.com/34729092/47555271-f9ae9200-d93d-11e8-9891-9da0c50b01df.png)

**Actual:**
No notification displays after succeeding to add docker files to wokespace.

**Comment by StephenWeatherford** [comment]
Yes, that was removed due to #515, thanks.
