### ISSUE TITLE
Fail to auto switch to 'Docker' Extension after running 'Docker: Refresh Explorer'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#595]
**Platform/ OS Version**: Win10
**Node.js:** 8.9.3
**Extension Version:** [0.3.2-alpha](https://azcode.blob.core.windows.net/vscode-docker/master/915/vscode-docker-0.3.2-alpha.vsix)

**Repro Steps:**
1. Navigate to File 'Explorer'.
2. F1 -> Type and select 'Docker: Refresh Explorer'.
3. Check the result.

**Expect:**
Auto switch to 'Docker' Explorer and refresh the Docker Explorer.

**Actual:**
Fail to auto switch to 'Docker' Explorer .

**More Info:**
Running 'File: Refresh Explorer' auto switches from Docker Explorer to File Explorer.

**Comment by StephenWeatherford** [comment]
This is vscode's behavior. It won't be common to do this.
