### ISSUE TITLE
Docker wont fine deamon'

### ISSUE THREAD

**Issue by NicholasBlackburn1** [Microsoft/vscode-docker#599]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.image.inspect
Error type: EACCES
Error Message: Unable to connect to Docker, is the Docker daemon running?
Output from Docker: connect EACCES /var/run/docker.sock

Version: 0.3.1
OS: linux

**Comment by StephenWeatherford** [comment]
@NicholasBlackburn1 Did you follow these steps?  https://github.com/Microsoft/vscode-docker#running-commands-on-linux

**Comment by StephenWeatherford** [comment]
Closing due to lack of response. If you need any more help, please reopen.
