### ISSUE TITLE
11

### ISSUE THREAD

**Issue by 237833645** [Microsoft/vscode-docker#601]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.start.interactive
Error type: ENOENT
Error Message: Unable to connect to Docker, is the Docker daemon running?
Output from Docker: connect ENOENT /var/run/docker.sock

Version: 0.3.1
OS: darwin

**Comment by StephenWeatherford** [comment]
The extension relies on docker being installed and accessible.  Is it installed, and can you run "docker" from a Terminal?  We are improving this error message in the next release.  Thanks.

**Comment by StephenWeatherford** [comment]
Closing due to lack of response. Feel free to reopen with more info.
