### ISSUE TITLE
Doesnt Support Self Signed Certs

### ISSUE THREAD

**Issue by pbuckley4192** [Microsoft/vscode-docker#602]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.connectCustomRegistry
Error type: RequestError
Error Message: Error: self signed certificate

Version: 0.3.1
OS: linux

**Comment by StephenWeatherford** [comment]
#497, this is high on our list.  Please note the work-around there as well, although note it does carry security risks.  Thanks for using the extension!

**Comment by StephenWeatherford** [comment]
This was released a while ago.
