### ISSUE TITLE
Capability to sort/group images/containers in UI by more than just age

### ISSUE THREAD

**Issue by cmeyertons** [Microsoft/vscode-docker#603]
It's sometimes hard to get a good understanding of what needs to be pruned, etc. on your machine by just looking at the Docker explorer UI as things can get quite jumbled with the age based sorting.

I (and maybe others too) would get a lot of value out of seeing an alphabetically sorted list (or at least alphabetical for the image name with tag still being age based).

This could be a user setting we flip on potentially.

An even better UI would be to have tags nested inside of image so there is a logical grouping.

**Comment by StephenWeatherford** [comment]
@cmeyertons I share your frustration with this, so we appreciate your comments on what you would prefer instead.

**Comment by StephenWeatherford** [comment]
From #565:
Currently in the images pane, it's only ordered by date and every image + tag combination get its own line item. In a typical use case, you don't really care to see all of the old tags.
It would be nice to have a tree view + see just the last built image of each image name and expanding that tree view shows all the tags for that image.

**Comment by StephenWeatherford** [comment]
@cmeyertons What about images with hostname/port?  I.e. would you want myimage:v1, myreg.azurecr.io/myimage:v1 and myusername/myimage:v1 to all be stored under a single name?

**Comment by cmeyertons** [comment]
Definitely think tree view is the best direction to go.

My first impression is that `myimage:v1` and `myreg.azurecr.io/myimage:v1` would be better as separate top level nodes in the tree because it gives a natural order that is aligned with how docker has the image name constructed (registry -> image -> tag).

I think an important thing to call out again is that tags are still ordered by age, as alphabetical order is not really significant.

so ideally for me it would look like:

```
image1
- latest
- tag2
- tag1
myReg.azurecr.io/image1
- latest
- tag1
```
