### ISSUE TITLE
Simplify generated launch.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docker#612]
Hey,

VSCode dev here. This milestone I am looking into simplifing generated `launch.json` for various extensions https://github.com/Microsoft/vscode/issues/62851

The `launch.json` that docker generates is the following:
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Docker: Attach to Node",
			"type": "node",
			"request": "attach",
			"port": 9229,
			"address": "localhost",
			"localRoot": "${workspaceFolder}",
			"remoteRoot": "/usr/src/app",
			"protocol": "inspector"
		}
	]
}
```

Here are my suggestions on how to simplify this:
- [ ] Remove the protocol field, by default it is auto which should work fine
- [ ] Remove the `address` and `localRoot`. Also contribute a [`DebugConifgurationProvider`](https://github.com/Microsoft/vscode/blob/e839e4560c19ce53c717d6f3078fd01e35c737a2/src/vs/vscode.d.ts#L8190) which will just resovle every launch configuration by appending the localRoot and address if they are not already present
- [ ] Change the default for localRoot to be `${workspaceFolder}`, not `null` as it is now (auto complete it in json)

By removing these unnecesry fields we will make it look simpler for the user, making him see only what is important to him.
Also what is the field that the user has to configure here the most? I would think it is the port and the remoteRoot. Would you profit from some quick pick which would ask the user which port he is using? Similar to your create a `dockerfile` experience?

All of this should be pretty straightforward. Please let me know if you need help.

**Comment by weinand** [comment]
@isidorn setting "localRoot" to the default value "${workspaceFolder}" should be done in node-debug. For "address" node-debug already uses the default "localhost".  
So there should be no need for vscode-docker to implement a DebugConfigurationProvider.

**Comment by StephenWeatherford** [comment]
Adding @philliphoff as he owns the .NET Core debugging part of the code.
