### ISSUE TITLE
Private registry: Fail to verify first certificate on non-self-signed certificate.

### ISSUE THREAD

**Issue by grhm** [Microsoft/vscode-docker#613]
Repro steps:
###### Create private registry
Create a private registry, with SSL enabled using a certificate issued by an internal/private CA (e.g using [mkcert](https://github.com/FiloSottile/mkcert))
Registry works for pushing/pulling images (certificate is trusted)

###### Exercise issue
In VSCode, right click on Registries\Private Registries in docker explorer.
Choose "Connect to a Private Registry … (Preview)
Enter "https://localhost:5443/"   
Press enter to ignore username

Action: vscode-docker.connectCustomRegistry
Error type: RequestError
Error Message: Error: unable to verify the first certificate

Version: 0.3.1
OS: win32

**Comment by grhm** [comment]
Actually, this looks like it's the same issue as #483.
So closing this as a duplicate.

**Comment by StephenWeatherford** [comment]
Do you have your certificate in the Windows certificate store?  Thx.

**Comment by grhm** [comment]
Yes. Certificate is in the windows cert store.

**Comment by StephenWeatherford** [comment]
This was released a while ago.
