### ISSUE TITLE
Extension: Docker missing docker-compose exec

### ISSUE THREAD

**Issue by mictadlo** [Microsoft/vscode-docker#614]
Hi,
It appears that the Docker extension is missing `docker-compose exec/run` so it is not possible to do  `docker-compose run node npm install cors`.

Could you please add `docker-compose exec`?

Thank you in advance,

Michal

**Comment by StephenWeatherford** [comment]
@mictadlo Thanks for using the extension. The extension does not install docker at all, it is expected that you install it separately from the extension.  Or am I misunderstanding you?  Thx.

**Comment by mictadlo** [comment]
I understand that docker has to be installed separately. Within in your extension you have

```
>Docker:Com
Docker: Compose Restart
Docker: Compose UP
Docker: Compose Down
```
but there is missing Exec and Run.

Do you think it will be possible to add to your extension Exec and Run?

Thank you in advance,

Michal

**Comment by StephenWeatherford** [comment]
We'll look into this, thanks.

**Comment by PrashanthCorp** [comment]
@mictadlo , we'd like to hear what your usual experience is when running docker compose exec/run.
