### ISSUE TITLE
Use different icons to highlight unhealthy containers

### ISSUE THREAD

**Issue by grhm** [Microsoft/vscode-docker#615]
On my dev box I have a number of containers running, and they all have green icons in the Docker side bar.  However, there is little indication if any of them are in an unhealthy state - i.e. the docker  HEALTHCHECK command is failing.

Currently the healthy/unhealthy status is embedded at the far right of the string shown for a container (i.e. the container string is something like "my.private.registry:5000/project/imagnename:latest (myContainerName) (Up N hours (unhealthy))

In order to see the health, the side bar need to be very wide.  I'd like have a yellow icon for containers that are running but failing their healthchecks.  Thus you could see at a glance that the container needed some attention, and without having the sidebar occupy too much of the screen.

**Comment by StephenWeatherford** [comment]
Fixed via #609
