### ISSUE TITLE
Maintainer is deprecated

### ISSUE THREAD

**Issue by matheusrocha89** [Microsoft/vscode-docker#62]
The lint alert when the `MAINTAINER` is not defined but the docker docs said that is deprecaded and should use the `LABEL` instead.

More info: https://docs.docker.com/engine/reference/builder/#/maintainer-deprecated

**Comment by matheusrocha89** [comment]
I saw that you are using `dockerfile_lint` project to make the lint verification. And they already removed this mandatory rule. https://github.com/projectatomic/dockerfile_lint/pull/65/files Maybe you should just bump a new version with an updated version of the dockerfile_lint dependency

**Comment by lostintangent** [comment]
Thanks for the reminder! We actually made this change in the dockerfile_lint project because of the deprecation in Docker 1.13, but we haven't released an update of this extension to the marketplace. We'll get a new release out ASAP!

**Comment by chrisdias** [comment]
working on this here https://github.com/Microsoft/vscode-docker/pull/63

**Comment by lostintangent** [comment]
Closed via #63. We'll get this update published to the marketplace ASAP.
