### ISSUE TITLE
Error connecting to unknown registry

### ISSUE THREAD

**Issue by yangshun2005** [Microsoft/vscode-docker#626]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.3.1
OS: darwin

**Comment by StephenWeatherford** [comment]
What registry are you trying to connect to?

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.  We are working on improving our compatibility with third-party container registries.  Feel free to re-open with more info.  Thx.
