### ISSUE TITLE
Unhandled error if you cancel saving Azure log

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-docker#639]
1) On ACR node -> View Azure Logs
2) Open a build and click on the copy log icon
<img width="122" alt="image" src="https://user-images.githubusercontent.com/6913354/48783480-5418e500-ec95-11e8-9cc4-52503eb77d95.png">
3) Cancel the save dialog

!) Error 'TypeError': Cannot read property 'fsPath' of undefined

TWO PROBLEMS:
1) The error doesn't have the "Report An Issue" button - should wrap the call in CallWithTelemtryAndErrorHandling
2) the error itself

**Comment by rosanch** [comment]
Fixed by #705
