### ISSUE TITLE
Incorrect icon for open log in View Azure Logs, and where's the copy button?

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#641]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/6913354/48784238-1cab3800-ec97-11e8-8a63-b777be0b9a30.png">
The open button (last on right) has a copy icon.  

Also, the code references a copy button (and uses clipboardy), but there is no such button:
  const digestClickables = panel.querySelectorAll('.copy');

**Comment by rosanch** [comment]
I don't see that we have a save icon. I'll try to find the designer that worked with the interns to see if she can provide one.
About that line. That is to copy the digest, not the logs. and you can see the copy icon next to the digest.
