### ISSUE TITLE
Fail to debug a .NET Core ASP.NET application with an error dialog

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#643]
**OS:** Win10
**Node.js:** V8.12.0
**Build Definition:** [20181120.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=711&view=logs)

**Prerequisites:**
1. Install Docker.
2. Install .NET Core SDK(2.0 or later).
3. Install C# extension.
4. Switch to Linux Container.

**Repro Steps:**
1. Create a new .NET Core ASP.NET application by  'dotnet new web --name test'.
2. Open this application folder in VS Code.
3. Wait for and respond 'yes' when prompted to add required assets to build and debug.
4. Add Docker files to workspace.
5. Add .NET Core debug launch task.
6. Debug the application.

**Expect:**
Succeed to debug the application without errors.

**Actual:**
Fail to debug the application with an error dialog.
![error](https://user-images.githubusercontent.com/34729092/48814641-7cc4db80-ed76-11e8-828d-3877d92aa79f.png)

[Launch.txt](https://github.com/Microsoft/vscode-docker/files/2602345/Launch.txt)

**More Info:**
This issue also reproduces for .NET Core Console applications.

**Comment by philliphoff** [comment]
@v-dantch Can you provide a bit more context about the issue, such as the exact versions of Windows, Docker for Windows, .NET Core SDK/runtime, and any contents of the Docker output window and the debug output window?  I'm not seeing any issues with `0.4.0` on Mac or on Windows (build `1809` with Docker `2.0.0.0-win78 (28905)`).

**Comment by philliphoff** [comment]
@v-dantch No worries.  Even if it doesn't reproduce on other machines, it would still be useful to know why it didn't work on that particular machine, so that we might be able to identify a prerequisite or other error check that we could add to the extension to provide a better user experience.  If you have any more information about that machine, let me know.  Otherwise, I'll close this issue.

**Comment by v-dantch** [comment]
Hi @philliphoff yes, we are continuing to investigate this issue, even though we fail to reproduce it now And we will re-open this bug when we can reproduce it constantly.
