### ISSUE TITLE
Wrong DOCKER_HOST config when using docker.host configuration

### ISSUE THREAD

**Issue by ntcong** [microsoft/vscode-docker#649]
vscode-docker tell me to set docker.host in the format \<ip\>:\<port\>. When using Docker build image command, it'll set DOCKER_HOST = docker.host config.

DOCKER_HOST config should be tcp://\<ip\>:\<port\>. Using \<ip\>:\<port\> will result in an error:
`parse <ip>:<port>: first path segment in URL cannot contain colon`

**Comment by ntcong** [comment]
changing https://github.com/Microsoft/vscode-docker/blob/4d7b773fabd8c210ff7392bcc1daffc66b862004/commands/utils/TerminalProvider.ts#L20 from `DOCKER_HOST: value` to `DOCKER_HOST: "tcp://" + value` works. But i'm not sure we should use the correct DOCKER_HOST format (tcp://host:port) for docker.host configuration, or add `tcp://` to the DOCKER_HOST environment

**Comment by DefineFC** [comment]
same here, thanks for the workaround!

**Comment by PrashanthCorp** [comment]
Hey @ntcong, you are correct. Looking at how the host prefix is used by the upstream library (docker-modem), there seem to be multiple allowed protocols. I don't think it's appropriate for us to make assumptions about wanting a tcp connection. We'll look into making this more visible.

**Comment by zxfishhack** [comment]
setting docker.host to tcp://host:port does not work for me.

source from docker-modem 
```javascript
    var parsed = url.parse(self.host);
    address = url.format({
      'protocol': parsed.protocol || self.protocol,
      'hostname': parsed.hostname || self.host,
      'port': self.port
    });
    address = url.resolve(address, options.path);
```
when host is `tcp://192.168.1.1`, options.path is `/containers`, self.port is 8080, the final address will be 'tcp:/containers'.

[DockerClient::refreshEndpoint](https://github.com/Microsoft/vscode-docker/blob/master/commands/utils/docker-endpoint.ts#L27), the errorMessage defind is 'The docker.host configuration setting must be entered as <host>:<port>, e.g. dockerhost:2375'

IMO, `vscode-docker` accept <host>:<port> only and export DOCKER_HOST=tcp://<host>:<port> to terminal is better.
