### ISSUE TITLE
Webpack: Find proper solution for azure-arm-resource dynamic module load issue in webpack.config.js

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#651]
from webpack.config.js:

>  // CONSIDER: Figure out how to make this work properly. The consequences of ignoring this error are that 
> // the Azure SDKs (e.g. azure-arm-resource) don't get their info stamped into the user agent info for their calls.

**Comment by BigMorty** [comment]
@StephenWeatherford can you provide more info on this and whether it is still something that needs attention.

**Comment by StephenWeatherford** [comment]
Yes, it still applies, I believe the consequences I state are correct.  But it affects all our extensions, as well as others (it's a fundamental problem with webpack), so I'm not positive of whether anyone cares enough to fix.

**Comment by bwateratmsft** [comment]
We'll be getting rid of this package anyway with #844.
