### ISSUE TITLE
Pop up an error after cancelling one operation 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#657]
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. F1 ->Type and select 'Docker: Delete Azure Image' -> Press 'Esc' to cancel the operation.
2. Check the result.

**Suggestion:**
Display the log in 'Output' window or display the notification at bottom-right.

**Actual:**
Display an error.
![image](https://user-images.githubusercontent.com/34729092/49147479-c2b60c80-f33f-11e8-9dda-342fcf652060.png)

**Comment by StephenWeatherford** [comment]
@rosanch I think you already fixed this?

**Comment by rosanch** [comment]
> @rosanch I think you already fixed this?

Yes. This is no longer an issue.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.

**Comment by StephenWeatherford** [comment]
This is already fixed in master, but not in the hotfix.
