### ISSUE TITLE
[Suggestion]Add steps to pull a new image when asking to choose one image

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#659]
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. Right click 'Images' node -> Select 'Push'.
2. Check the reulst.

**Suggestion:**
Add steps to pull a new image when asking to choose one image. In this case, we have no need to back to the TERMINAL to pull the desired image.
![image](https://user-images.githubusercontent.com/34729092/49148411-4e309d00-f342-11e8-964f-9e3efc49c023.png)

**Expect:**
Only display the existing images.

**Comment by StephenWeatherford** [comment]
We don't feel this one will help in the most common scenarios.  Thanks, though.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
