### ISSUE TITLE
Miss the icon for 'Tasks' node

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#660]
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. Create a build task(please refer to below link:
![image](https://user-images.githubusercontent.com/34729092/49149042-03178980-f344-11e8-8bb4-79a3bb4f5daa.png)
2. Check the 'Tasks' node.

**Expect:**
The icon of 'Tasks' node displays well.

**Actual:**
Miss the icon for 'Tasks' node
![image](https://user-images.githubusercontent.com/34729092/49148954-c0ee4800-f343-11e8-9c95-0c938142ee1f.png)

**Comment by StephenWeatherford** [comment]
Good catch, thanks.
