### ISSUE TITLE
There are no tooltips when hovering on the icons in the Logs window

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#661]
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. Create a build task(please refer to below link:
![image](https://user-images.githubusercontent.com/34729092/49149042-03178980-f344-11e8-8bb4-79a3bb4f5daa.png)
2. Run a task.
3. View Azure logs.
4. Navigate to the Logs window -> Expand one -> Hover on the icons.
5. Check the result.

**Expect:**
Display the tooltips when hovering on the icons.

**Actual:**
There are no tooltips when hovering on the icons.
![image](https://user-images.githubusercontent.com/34729092/49149617-85ed1400-f345-11e8-87a1-e35ca0033631.png)

**Comment by StephenWeatherford** [comment]
Might as well start looking at accessibility as well.  For example, http://accessibility.athena-ict.com/aria/examples/tooltip.shtml.  And also make sure the icons have alt text.

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT Cheater!  :-)
