### ISSUE TITLE
Nothing happens after saving the logs locally for digests

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#663]
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. Create a build task(please refer to below link:
![image](https://user-images.githubusercontent.com/34729092/49149042-03178980-f344-11e8-8bb4-79a3bb4f5daa.png)
2. Run a task.
3. View Azure logs.
4. In Logs window, click the 'Save as' icon next to digest.

**Expect:**
Succeed to save the digest locally.

**Actual:**
Nothing happens.
![image](https://user-images.githubusercontent.com/34729092/49150038-a5d10780-f346-11e8-8f7a-da034403792f.png)

**Comment by rosanch** [comment]
This copies the digest. It is not meant to save it.

**Comment by rosanch** [comment]
I'm closing this issue.
The icon next to the digest is to copy it. You can try pasting it somewhere else to ensure it is working properly

**Comment by v-dantch** [comment]
Hi @rosanch Thanks for your update. I can succeed to copy the digest and paste it somewhere successfully. 
One suggestion: could we add a tooltip for it? Due to it is same as the 'Save As' icon like below.
![image](https://user-images.githubusercontent.com/34729092/49774059-6fc05a00-fd2e-11e8-8d97-c5153485056c.png)
