### ISSUE TITLE
Não é possível definir a propriedade 'suppressErrorDisplay'

### ISSUE THREAD

**Issue by steniafelix** [Microsoft/vscode-docker#664]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.system.prune
Error type: TypeError
Error Message: Cannot set property 'suppressErrorDisplay' of undefined

Version: 0.4.0
OS: linux

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  This is tracked in #652 and will be fixed in the next release.
Please see #652 for the message the extension was trying to report.
