### ISSUE TITLE
e

### ISSUE THREAD

**Issue by hellboy33** [Microsoft/vscode-docker#668]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.system.prune
Error type: TypeError
Error Message: Cannot set property 'suppressErrorDisplay' of undefined

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment]
Thanks for reporting. The fix for this will appear in the next release, out soon.  In the meantime, make sure that Docker is running.

**Comment by hellboy33** [comment]
> <Please be sure to remove any private information before submitting.>
> 
> Repro steps:
> <Enter steps to reproduce issue>
> 
> Action: vscode-docker.system.prune
> Error type: TypeError
> Error Message: Cannot set property 'suppressErrorDisplay' of undefined
> 
> Version: 0.4.0
> OS: win32

**Comment by StephenWeatherford** [comment]
https://github.com/Microsoft/vscode-docker/issues/652
