### ISSUE TITLE
Docker Refresh Command Palette Prompts for Username and Password of Unknown Site

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-docker#672]
From https://github.com/Microsoft/vscode/issues/64254

> Clicking 'Refresh' on the Docker Extension user interface opens the command palette. The command palette prompts for a username and password.
> 
> The command palette does not clarify that the credentials being required are for Docker. This is particularly confusing if the container images are placed on Azure Container Registry.
> 
> My suggestion would be to have the prompt ask the user for their 'Docker username' and 'Docker password'. This reduces confusion.

kind of related to #360

**Comment by StephenWeatherford** [comment]
This is what I currently see:
![image](https://user-images.githubusercontent.com/6913354/49555490-ebe11a80-f8b4-11e8-8b2a-b7e7e94daa4f.png)

> The command palette does not clarify that the credentials being required are for Docker. This is particularly confusing if the container images are placed on Azure Container Registry.

I'm not seeing anywhere where we simply ask for username and password without being more explicit.

**Comment by StephenWeatherford** [comment]
@raahmed Do you have any more info on how to reproduce this?  Are you on the latest version of the Docker extension?  Thanks!

**Comment by raahmed** [comment]
This was on VSCode 1.22.1 using an older version of the extension. Unfortunately, I upgraded VSCode and don't have visibility into the old extension number.

**Comment by StephenWeatherford** [comment]
Based on the comment, it appears it no longer repros.  Feel free to re-open if that's not correct. Thx.
