### ISSUE TITLE
docker extension can not be read on vscode

### ISSUE THREAD

**Issue by zhorahmatt** [Microsoft/vscode-docker#674]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.configure
Error type: undefined
Error Message: Unknown Error

Version: 0.4.0
OS: linux

**Comment by StephenWeatherford** [comment]
For instance, what kind of project were you trying to add dockerfiles to?  What settings did you select?  Thx.

**Comment by StephenWeatherford** [comment]
Closing due to lack of input.  Feel free to re-open with more information. Thx.
