### ISSUE TITLE
An error occurs after canceling the operation of saving the platform info

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#676]
**OS**: Windows 10
**Node.js**: V10.13.0
**Build Definition**: [20181204.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1226)

**Repro Steps:**
1. Create a build task(please refer to below link:
![image](https://user-images.githubusercontent.com/34729092/49149042-03178980-f344-11e8-8bb4-79a3bb4f5daa.png)
2. Invoke Run Build Task command.
3. Right click one task -> Select 'View Azure Logs'.
4. Expand one image node on the opened Logs window, -> Click the 'Save as' button next to the 'Log' tab.
5. Close the 'Save as' dialog directly ->Check the result.

**Expect:**
There is no error.

**Actual**:
An error occurs on the bottom.
![error](https://user-images.githubusercontent.com/34729022/49504755-53976580-f8b5-11e8-902d-d611eff2f1a4.png)

**Comment by StephenWeatherford** [comment]
Thanks, dup: https://github.com/Microsoft/vscode-docker/issues/639
