### ISSUE TITLE
Run in docker container throw an exception debugging Core CLR

### ISSUE THREAD

**Issue by tachev** [Microsoft/vscode-docker#681]
Repro steps:
1. Opened a .NET project. Converted it to .NET Core
2. Click Command+F5
3. Selected the docker preview option
4: Got the exception

Action: debugCoreClr
Error type: 1
Error Message: Command failed: docker build --rm -f "/IdentityServer/IdentityProvider/Dockerfile" --label "com.microsoft.created-by=visual-studio-code" -t "identityprovider.web:dev" --target "base" "/IdentityServer/IdentityProvider"
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /IdentityServer/IdentityProvider/Dockerfile: no such file or directory

Version: 0.4.0
OS: darwin

**Comment by StephenWeatherford** [comment]
FYI @philliphoff

**Comment by tachev** [comment]
I didn't have a Dockerfile before that. I expected this function will create one for me.
________________________________

**Comment by StephenWeatherford** [comment]
Phil - If you want to go that route, some of the commands will ask about adding a dockerfile:
https://github.com/Microsoft/vscode-docker/blob/a29573dcb36a738727419d11d1a8ea094794ac7e/commands/build-image.ts#L67
