### ISSUE TITLE
Command to set default ACR configuration

### ISSUE THREAD

**Issue by rosanch** [microsoft/vscode-docker#682]
This command should allow the user to set defaults values for subscription & and registry to improve user experience and make commands such as "run ACR task file" and "ACR Task: build image" faster.

**Comment by StephenWeatherford** [comment]
One thing that will help, when we move to the common tree code, it will remember the last used option and default to it on each question.

**Comment by rosanch** [comment]
it remembers it right now. It's just that is a pain to have to choose them every time. So, we could add a default config, so the user doesn't have to choose a subscription, registry, etc... every single time they run commands like run ACR task file.

**Comment by StephenWeatherford** [comment]
@rosanch Could you prioritize this one, too?  Thanks.

**Comment by bwateratmsft** [comment]
Closing as we've removed support for ACR tasks.
