### ISSUE TITLE
How to encode OLE Data when I read the data with OLEDB connection in C#

### ISSUE THREAD

**Issue by Rango941001** [Microsoft/vscode-docker#684]
I want to know how to encode the oleDB data to another charset when I read the *.dbf file on the connection. I checked many methods.

like this:

OleDbConnection dbConn = new OleDbConnection(@"Provider=vfpoledb.1;Data Source=" + dbf_file_path + ";CharacterSet=" + encode.BodyName + "; Collating Sequence=general;");

As you can see, there "CharacterSet=UTF8", but there is nothing Somebody helps me!

OleDbConnection dbConn = new OleDbConnection(@"Provider=vfpoledb.1;Data Source=" + dbf_file_path + ";CharacterSet=" + encode.BodyName + "; Collating Sequence=general;");

**Comment by StephenWeatherford** [comment]
@Rango941001 This is a place for posting bug reports for the vs code Docker extension. You need to find a support forum for OLEDB for your question - nothing to do with this.  Perhaps try stackoverflow.com?

**Comment by Rango941001** [comment]
I did it.
I tested all kinds of method to solve this issue.
But I can't encode other dbf files on my app.
there is no way to solve this, I think.
