### ISSUE TITLE
Allow more customization of docker run command

### ISSUE THREAD

**Issue by ismael-soriano** [Microsoft/vscode-docker#691]
## SUMMARY
Actual `dockerRun` configuration does not allow to use custom ports nor volumes and other elements to be added under the execution of the docker run command.

## Elements to be modified
* Add ports element to manage the bindings.
* Add volumes element to manage volume mapping.
* Add externalHosts element to manage connectivity to not known hostnames.

You can take a preview of all this changes on the following PR #690

**Comment by pereiren** [comment]
Hi @philliphoff, please take a look at this issue/PR. 

I am a @ismael-soriano teammate, and we decided to modify a little bit the extension code to allow us a more customizable use of this great feature for VS Code!

**Comment by StephenWeatherford** [comment]
Fixed by #690
