### ISSUE TITLE
Specify network for docker run

### ISSUE THREAD

**Issue by farzadmf** [Microsoft/vscode-docker#692]
Hi,

I was wondering if it's possible to specify the network option when using the `Docker: Launch .NET Core (Preview)` launch configuration. As I see from the docs, supported customization options are
- `containerName`
- `env`
- `envFiles`
- `labels`

So, I was wondering if there's somehow an option to specify the network for the running container.

**Comment by StephenWeatherford** [comment]
@philliphoff

**Comment by StephenWeatherford** [comment]
@philliphoff What do you think should be the priority of this feature request?  Thx.

**Comment by farzadmf** [comment]
Another use case that comes to my mind (maybe I'm wrong) is that you have multiple services being defined using `docker-compose`, and you just want to run one of them from vscode. Then, you can configure the other ones to use a specific network, and then configure vscode to use the same network.

**Comment by philliphoff** [comment]
Resolved by #748.

@farzadmf Let me know if that change wouldn't meet your needs.

**Comment by farzadmf** [comment]
Thank you @philliphoff , I'll give it a try :)

**Comment by farzadmf** [comment]
Hi @philliphoff , I was so excited to see that we have a new release to `0.5.2` yesterday (Jan 31, 2019), but apparently (according to the GitHub `Releases` tab), it only contains a single commit.

Also, there was another merged PR (#690) which also go me excited. So, when are these features coming out? I'm so anxious to try them.

**Comment by StephenWeatherford** [comment]
@farzadmf Yesterday was a hotfix for a bug that would have appeared in the next vscode release.  We'll have another release in about 2 weeks.  In the meantime, you can try out the current alpha with Phil's fixes if you'd like - go to https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2713, click on Artifacts to download the VSIX, and use Command Palette->Install from VSIX...
