### ISSUE TITLE
Build image fails for python if requirements.txt doesn't exist

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-docker#693]
See PR #647

**Comment by StephenWeatherford** [comment]
@brettcannon, @lloydchang I would rather show (or document) best practice first, and have it be convenient second. Does it make sense to only supply the requirements.txt file to install if it exists? Or is it better to supply it always and document that users should create it? Or something else? Thanks!

**Comment by brettcannon** [comment]
Since this is Docker who knows what the person did at a different layer 😉 . So if you don't have a `requirements.txt` file then skipping the running of `python3 -m pip` is fine as I would assume/hope you got your dependencies into the image in some other way.

**Comment by StephenWeatherford** [comment]
Probably should make no changes.  need to follow up.

**Comment by StephenWeatherford** [comment]
@brettcannon, @lloydchang Sounds like the best policy is to leave things as they are and let the user modify if they need to.  Closing for now, but feel free to re-open if you have a different suggestion.  Thx.
