### ISSUE TITLE
[Suggestion]Add a button to select subscriptions when there is no applied subscription

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#695]
**OS:** All
**Node.js:** V10.14.1
**Extension Build:** [20181209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1407)

**Repro Steps:**
1. Make sure there is no applied subscription.
2. F1 -> Type and select 'Docker: Create Azure Registry'.
3. Check the result.

**Suggestion:**
Add a button to select subscriptions on the error dialog.

**Actual:**
![image](https://user-images.githubusercontent.com/34729092/49783434-bd4fbd80-fd54-11e8-9cd7-34a3e035483c.png)

**Comment by StephenWeatherford** [comment]
And it also happens to be wrong - you also get this message if you're not signed in to Azure.

**Comment by v-dantch** [comment]
Yes, this issue also reproduces when I am not signed in to Azure. So it will be better to prompt the customer to select subscriptions on the error dialog if one is available.

**Comment by StephenWeatherford** [comment]
We should at least have a button to sign in if not signed in.

**Comment by StephenWeatherford** [comment]
It's also possible to not have any subscriptions selected.

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-docker/issues/512
