### ISSUE TITLE
Missing 'Pull Image from Azure' in the context menu

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#696]
**OS:** All
**Node.js:** V10.14.1
**Extension Build:** [20181209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1407)

**Repro Steps:**
1. Drill down from 'Registries' -> 'Azure' ->Select one registry -> Select one repository ->Right click one image.
2. Check the context menu.

**Expect:**
Display 'Pull Image from Azure'.

**Actual:**
Miss 'Pull Image from Azure'.
![image](https://user-images.githubusercontent.com/34729092/49784089-17ea1900-fd57-11e8-89e5-ff6ac23924b5.png)

**More Info:**
Display 'Docker: Pull Repository from Azure' in the 'Command Palette'. It doesn't display in the previous release 0.4.0.
![image](https://user-images.githubusercontent.com/34729092/49784143-41a34000-fd57-11e8-847b-a77465dd3545.png)

**Comment by StephenWeatherford** [comment]
@rosanch Can you get this fixed today?  Thanks!
