### ISSUE TITLE
Fail to push image to the defaulted registry under 'Docker Hub' node without signing in Docker Desktop

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#697]
**OS:** Windows
**Node.js:** V10.14.1
**Extension Build:** [20181209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1407)

**Repro Steps:**
1. Make sure you have not signed in Docker Desktop and sign in with Docker ID in VS Code.
2. Drill down from 'Registries' -> 'Docker Hub' ->Right click one registry and select 'Set as Default Registry Path'.
3. Push one image to this registries and check the result.

**Expect:**
Succeed to push image.

**Actual**:
Fail to push image with error 'Server misbehaving'.
![image](https://user-images.githubusercontent.com/34729092/49784650-09046600-fd59-11e8-98f4-26abf921fb61.png)

**More Info:**
This issue doesn't reproduce after signing in Docker Desktop.
![image](https://user-images.githubusercontent.com/34729092/49784731-3ea94f00-fd59-11e8-8a54-d58bcbbb4e7d.png)

**Comment by v-dantch** [comment]
Hi @StephenWeatherford , sorry for the unmatched screenshot. 
About 'Sign in with Docker ID in VS Code', yes,  it means I typed in docker login in a vscode terminal. To make sure I have logged in to Docker Hub with my Docker ID.
Please get more info from below.
**Actual:**
Pop up 'denied: requested access to the resource is denied.'

**More Info:**
Succeed to push image with signing in the Docker Desktop.
![image](https://user-images.githubusercontent.com/34729092/49842321-0572ec80-fdf6-11e8-9875-a91ab7b6ca18.png)

**Comment by StephenWeatherford** [comment]
You have to be signed in to Docker to push to docker hub.

**Comment by v-dantch** [comment]
Got it 👍
