### ISSUE TITLE
Regression: Open in Portal and copying to clipboard do not work on Linux

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#699]
**OS:** Linux
**Node.js:** V10.14.1
**Extension Build:** [20181209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1407)

**Repro Steps:**
1. Drill down from 'Registries' -> 'Azure' -> Right click one registry and select 'Browse in the Azure Portal'.
2. Check the result.

**Expect:**
Succeed to browse the Azure registry in portal.

**Actual:**
Fail to browse the azure registry in portal.

**Comment by StephenWeatherford** [comment]
Works fine on windows, does nothing on Linux.

**Comment by StephenWeatherford** [comment]
Eric might know what's required.

**Comment by StephenWeatherford** [comment]
Two issues:
1) opn needs to be excluded from webpack
2) fallback exe in node_modules/opn/ doesn't have execute bit set (https://github.com/webpack-contrib/copy-webpack-plugin/issues/35)

**Comment by PrashanthCorp** [comment]
@v-dantch can you verify if the bug still repros?

**Comment by v-dantch** [comment]
Hi @PrashanthCorp we verified this issue onLinux with the latest Docker Extension build [20190226.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3583). And this issue is fixed.
