### ISSUE TITLE
Recognize docker-compose.yaml files

### ISSUE THREAD

**Issue by rhencke** [Microsoft/vscode-docker#70]
Currently, completion support is provided for docker-compose.yml files, but not for docker-compose.yaml files.

According to the docker-compose documentation, both are valid:

> [Tip: You can use either a .yml or .yaml extension for this file. They both work.](https://docs.docker.com/compose/compose-file/#service-configuration-reference)

**Comment by lostintangent** [comment]
@rhencke Thanks for reporting this! You're definitely right about this, so we can correct this limitation in the extension. VSCode's out-of-the-box YAML support [respect's both extensions](https://github.com/Microsoft/vscode/blob/master/extensions/yaml/package.json#L13), so we should as well. I'll send out a PR to fix this.
