### ISSUE TITLE
Fail to debug a new .NET Core ASP.NET Application

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#700]
**OS:** Linux
**Node.js:** V10.14.1
**Extension Build**: 20181209.1

**Repro Steps:**
1. Make sure 'Docker/.NET Core SDK(2.0 or later)/C# extension' installed.
2. Ensure the current user is a member of the 'docker' group.
3. Create a new .NET Core ASP.NET application using command 'dotnet new web --name test'.
4. Open application folder in vscode -> Wait for and respond ‘yes’ when prompted to add required assets to build and debug.
5. Add Docker files to workspace -> Add .NET Core debug launch task -> Debug application.

**Expect:**
Show the building of the image and running of the container in output window.

**Actual:**
Error messages show in docker output window during debugging.
![image](https://user-images.githubusercontent.com/41351993/49797603-ec792580-fd7a-11e8-8fd2-2a0a94ca2580.png)

**More Info:**
This issue also reproduces when debugging a new .NET Core Console Application.

**Comment by philliphoff** [comment]
This appears to be an issue with the `getvsdbg.sh` script itself (excerpt below):

```bash
    # For the rest of this script we can assume the working directory is the install path

    if [ -z $__RuntimeID ]; then
        get_dotnet_runtime_id
    elif [ "$__ExactVsDbgVersionUsed" == "false" ]; then
        # Remap the old distro-specific runtime ids unless the caller specified an exact build number.
        # We don't do this in the exact build number case so that old builds can be used.
        remap_runtime_id
    fi
```
The Ubuntu shell doesn't appear to like the `==` in the comparison, which causes the runtime ID to not be mapped properly, which causes the script to attempt to download the incorrect (or nonexistent) debugger version.  If you use `=` instead, the script succeeds.

I'm trying to find the owner for that script in order to file an issue.

**Comment by philliphoff** [comment]
So, found the owners and the issue has already been fixed, but just not yet released.  When that happens (hopefully soon), VS Code should pick up the updated script, at worst, 24 hours after the last debugging attempt.  (The script is cached for up to a day.)

**Comment by StephenWeatherford** [comment]
@philliphoff So this is fixed in the SDK?  Can it be closed?

**Comment by philliphoff** [comment]
@StephenWeatherford No, it looks like the updated `getvsdbg.sh` script hasn't yet been published.

**Comment by philliphoff** [comment]
The updated script was published today and I've verified that it unblocks the "debugging on Linux host" scenario.
