### ISSUE TITLE
[ACR Tasks] Feature: Allow specifying values

### ISSUE THREAD

**Issue by ehotinger** [microsoft/vscode-docker#703]
This includes two points:
1.  In order to run a task file, you need to be able to specify a Values file 
2. As well as `--set` variables

This provides rendering capabilities for things like `build -t {{.Values.someTag}}` where you could have a `Values.yaml` file containing `someTag: foo`, or alternatively you could specify `--set someTag=foo`

**Comment by StephenWeatherford** [comment]
@rosanch What do you think?

**Comment by rosanch** [comment]
I think it can be done. We upload the whole directory anyway. I'm just not sure how does the set functionality works. So I'm having trouble thinking how will it work with the schedule run API. But I'd take a deeper look into it after I finished with #682

**Comment by StephenWeatherford** [comment]
@rosanch Assigning P2 to 7.0 as investigate.  I'd say whether you think this makes sense and its priority are up to you guys.

**Comment by StephenWeatherford** [comment]
We don't know the feature or requirements as well, so we'll want at least a recommendation from you on features.  Thanks!
