### ISSUE TITLE
Connect to a Private Registry on windows 

### ISSUE THREAD

**Issue by dog-cat** [Microsoft/vscode-docker#708]
Action: vscode-docker.connectCustomRegistry
Error type: RequestError
Error Message: SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment]
Currently on vacation.

What kind of registry are you trying to connect to?

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.  Please feel free to re-open with additional info.  Thanks.
