### ISSUE TITLE
Show error messages after installing and reloading docker extension

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#713]
**OS**: Windows
**Node.js**: V10.13.0
**Extension Build**: [20181216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1605)

**Repro Steps:**
1. Open VS Code ->Make sure have **Docker for windows** installed.
2. Install docker extension -> Reload.

**Expect:**
No error messages show in **OUTPUT**.

**Actual:**
Show error messages in **OUTPUT**.
![image](https://user-images.githubusercontent.com/41351993/50081681-08247600-022a-11e9-83e1-06a9aa9aa8d1.png)

**Comment by StephenWeatherford** [comment]
We haven't been able to repro this.  Can you try uninstalling, removing the c:\users\<users>\.vscode\peterjausovec.vscode-docker-0.5.0 folder, reinstalling, and then try again?  Thx.

If you still repro, what version of vscode are you using?  And 32-bit or 64-bit?  Thx.

**Comment by v-xianya** [comment]
Thanks for your updates.
Verified with build 20181618.1. This issue also reproduces. 
1. Uninstall the docker extension and remove c:\users<users>.vscode\peterjausovec.vscode-docker-0.5.0 folder.
2. Reinstall docker extension and reload -> Open DOCKER:EXPLORER.
3. The error message shows in **OUTPUT**.

**More Info:**
The version of vscode is 1.31.0-insider , 64-bit.

**Comment by v-xianya** [comment]
Verified with build 20181218.1. This issue doesn't reproduce.

**Comment by StephenWeatherford** [comment]
Okay, thanks.

**Comment by v-xianya** [comment]
Verified with build 20190101.1. This issue reproduces.
Repro Step:
1. Open VS Code -> Make sure have Docker for windows installed.
2. Removing the c:\users<users>.vscode\peterjausovec.vscode-docker-0.5.0 folder -> Restart VS Code.
3. Install docker extension -> Reload -> Turn to DOCKER:EXPLORER.

Actual show errors in OUTPUT window.
![image](https://user-images.githubusercontent.com/41351993/50586377-2211ba00-0eb4-11e9-9081-2a3243e87512.png)

**Comment by StephenWeatherford** [comment]
Ah, this is #733, which only repros on vscode Insiders 1.31.x.  Thanks for reporting.  Might be a good idea to indicate the version of vscode when filing bugs in the future (might or might not have helped to narrow this down, but it's something we should consider in the future if we're having trouble reproing).

Thanks!
