### ISSUE TITLE
[Suggestion] Add 'Inspect Container' in container context menu

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-docker#714]
**OS**: Windows
**Node.js**: V10.13.0
**Extension Build**: [20181216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1605&view=results)

**Repro Steps**:
1. Open VS Code -> Open Docker extension.
2. Expand 'Containers' node and make sure there is a running container -> Right click the running container and check the context menu.

**Suggestion**
Show **Inspect Container** on container context menu.

**Actual:**
No **Inspect Container** shows on container context menu.

**Comment by ssotomayor** [comment]
Suprised this is missing as it's quite usual to want to know which volume is used by a container.
