### ISSUE TITLE
Fail to create azure registry for MoonCake accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-docker#716]
**OS:** Windows
**Node.js**: V10.14.1
**Extension Build**: [20181218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1624)

**Repro Steps**:
1. Open docker extension -> Sign in using MoonCake account.
2. Expand **Registries** node -> Right Click **Azure** -> Select "Create Azure Registry".

**Expect:**
Succeed to create azure registry.

**Actual:**
Fail to create azure registry and pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/50198905-ca8a2f00-0388-11e9-9c54-6b5483e0f332.png)

**More Info:**
1. This issue doesn't reproduce for azure account.
2. This issue also reproduces for Azure Germany account.

**Comment by EricJizbaMSFT** [comment]
This was likely fixed in https://github.com/microsoft/vscode-docker/pull/966. @v-xianya if you could verify on latest build from master that would be great

**Comment by v-dantch** [comment]
Verified on the latest build [20190611.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6724). Fixed, so close this bug.
