### ISSUE TITLE
Operation cancelled error canceling "container remove" when used on Containers node

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-docker#718]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.remove
Error type: Error
Error Message: Operation cancelled.

Version: 0.5.0
OS: win32

**Comment by v-dantch** [comment]
Add more info;
This issue also reproduces after canceling 'Tag Image'.

**Comment by StephenWeatherford** [comment]
This has something to do with minification - error.constructor.name in parseError() comes back as "object" instead of "UserCancelledError".

**Comment by StephenWeatherford** [comment]
name of the class is getting changed by minimize:

class i extends Error{constructor(){isuper(n.localize("userCancelledError","Operation cancelled."))}}
