### ISSUE TITLE
Intellisense is not available when file is named docker-compose.yaml

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode-docker#72]
If you name the file docker-compose.yaml, and hit ctrl-space, it says "No suggestions."

If you rename the file to docker-compose.yml, you get context-support.

From the docs for Docker (https://docs.docker.com/compose/compose-file/#service-configuration-reference).  

> Tip: You can use either a .yml or .yaml extension for this file. They both work.

**Comment by bkbonner** [comment]
I see that is does specify both file extensions:

https://github.com/Microsoft/vscode-docker/blob/master/dockerExtension.ts#L27

I'm running:  Version 1.10.2 (1.10.2)   on OSX 10.11.6

**Comment by lostintangent** [comment]
@bkbonner We actually just had this issue filed via #70, so you aren't the only one hitting it! :) As you mentioned, we resolved the bug, but we haven't deployed the update to the marketplace yet. We'll try to get that out ASAP.

**Comment by chrisdias** [comment]
i hope to push an update today

**Comment by chrisdias** [comment]
0.0.13 is published

**Comment by bkbonner** [comment]
Thank you.   I actually looked through the open items.   I must have been tired when I looked.   Sorry for the duplicate.

**Comment by chrisdias** [comment]
@bkbonner no worries!
