### ISSUE TITLE
vscode-docker.acr.pullImage

### ISSUE THREAD

**Issue by leandroclf** [Microsoft/vscode-docker#726]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.acr.pullImage
Error type: TypeError
Error Message: Path must be a string. Received undefined

Version: 0.4.0
OS: linux

**Comment by StephenWeatherford** [comment]
Can you describe what you were doing when the error occurred?  Does it happen every time?  Thx.

**Comment by rosanch** [comment]
I remember there was a similar error in December that got fixed. So please also check that the extension is updated to be sure this is still an existing issue
