### ISSUE TITLE
Error remove container unsused 

### ISSUE THREAD

**Issue by l-jhon** [Microsoft/vscode-docker#727]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.system.prune
Error type: TypeError
Error Message: Cannot set property 'suppressErrorDisplay' of undefined

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment]
THis should have been fixed in 0.5.1 released a couple weeks ago.
