### ISSUE TITLE
Allow restart container (Compose Up and Compose Down) with one command

### ISSUE THREAD

**Issue by akalcik** [Microsoft/vscode-docker#73]
Often when you develop something new, you make lot of changes to __config.yml_. It will be helpful when I could quick restart container with one command. It will be also cool when the __config.yml_ could be monitored and restart  container automatically on change.

**Comment by StephenWeatherford** [comment]
@akalcik Just to let you know, we shipped a new version of the extension today that contains "Docker compose restart".

**Comment by PrashanthCorp** [comment]
PR shipped, closing this
