### ISSUE TITLE
1

### ISSUE THREAD

**Issue by hongkunyue** [Microsoft/vscode-docker#734]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  This is tracked by #729.  The next version of the extension will require vscode 1.26 before the extension can be installed.  Is there any reason you can't update to 1.26 or later from 1.25?  Thanks!
