### ISSUE TITLE
Cannot read property 'useCertificateStore' of undefined

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#735]
Seeing this in telemetry from multiple users.  Only way I know to repro is
```
"docker.importCertificates": null
```
which shows an error but still gets passed through to our code.  Maybe there's some other way as well.

**Comment by StephenWeatherford** [comment]
Still getting this in the 0.5.2 telemetry

![image](https://user-images.githubusercontent.com/6913354/53278456-36a54e00-36be-11e9-806d-0c68ff492277.png)

**Comment by bwateratmsft** [comment]
This property is no longer used so this should be fixed.
