### ISSUE TITLE
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.0

### ISSUE THREAD

**Issue by farbodsalimi** [Microsoft/vscode-docker#738]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.0

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
Already tracked in #729, thanks!  Can you please upgrade to vscode 1.26?  We'll fix this soon to enforce this requirement.

**Comment by farbodsalimi** [comment]
Sure, Thanks!

**Comment by StephenWeatherford** [comment]
This was fixed in 0.5.1, released a couple of weeks ago.
