### ISSUE TITLE
Error show logs if there are no running containers

### ISSUE THREAD

**Issue by mohamedgb00714** [Microsoft/vscode-docker#739]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.show-logs
Error type: Error
Error Message: There are no Docker containers that apply to this command.

Version: 0.5.1
OS: win32

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT Eric is correct that is seems like we shouldn't be filtering out stopped containers for showing logs.

**Comment by StephenWeatherford** [comment]
We now look for any containers, not just running ones.
