### ISSUE TITLE
Unable to infer the application project file

### ISSUE THREAD

**Issue by yyahoo11** [Microsoft/vscode-docker#740]
&lt;Please be sure to remove any private information before submitting.&gt;
l
Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the `appFolder` or `appProject` property in the Docker debug configuration.

Version: 0.5.1
OS: win32

**Comment by yyahoo11** [comment]
j

**Comment by philliphoff** [comment]
@yyahoo11 That error indicates that the extension did not find the application's project (`.csproj`) file in the expected location (i.e. the typical location relative to the root of the workspace opened in VS Code).  It's entirely possible (and ok) if the file is in another location better suited to the application and workspace.  In that case, however, you must set the `appFolder` or `appProject` to that location.

**Comment by StephenWeatherford** [comment]
@philliphoff Suggestions from @EricJizbaMSFT:

1. Include the second level of the folder structure when inferring the app project. I think having the csproj at the second level is pretty common for C# projects.
1. Add a button to open the launch.json file
1. Add a button to browse for a *.csproj file
1. Improve the wording of the message or add a “Learn More” link (Some new users might not know the difference between the different docker launch configs or even where to find their launch.json file)

**Comment by winiciuscota** [comment]
I'm having this same issue when setting appFolder or appProjects I get these errors:

ENOENT: no such file or directory, scandir <appFolder>
or 
ENOENT: no such file or directory, unlink '/tmp/temp_1552347286443_8568_2.tmp'

I'm setting relative paths, Have anyone got it to work?

if the csproj is on the root it simply works and the debug starts over docker

**Comment by philliphoff** [comment]
@winiciuscota When you say you're using relative paths, is that including the `${workspaceFolder}` variable or is it strictly relative?

**Comment by winiciuscota** [comment]
Using ${workspaceFolder} fixed the issue.

Thanks @philliphoff

**Comment by winiciuscota** [comment]
I know it is not related to this issue, but I couldn't find it in the docs.

Is there any way to run the image within the context of a docker-compose file? I tried creating a docker-compose.yml and a docker-compose.debug.yml on the project path but the extension simply ignores it.
is there a way to not launch a new browser? There is no launchBrowser in the configuration.

**Comment by yyahoo11** [comment]
Ok

**Comment by philliphoff** [comment]
@winiciuscota There's currently no switch to disable launch of the browser; it's on the list, though (#764).

**Comment by philliphoff** [comment]
@winiciuscota There's no support for Docker Compose today, though you're not the first to ask.  I've created #840 to track that request, but I honestly don't know if/when it would happen.
