### ISSUE TITLE
Is Windows Subsystem for Linux WSL and Docker Toolbox supported?

### ISSUE THREAD

**Issue by felipe1982** [Microsoft/vscode-docker#741]
I am trying to use this Docker extension for VSCode in Windows 10 **HOME** and running docker toolbox. I can `docker info` on the bash shell provided by docker toolbox, and I have provided docker extension for vscode with the `DOCKER_HOST` as `tcp://192.168.99.199:2376` but it says "docker isn't running"

Is there more that I should do?

* latest vscode
* windows 10 Home
* latest docker toolbox

**Comment by StephenWeatherford** [comment]
Could you be more specific about when it says this?  Thx.

**Comment by StephenWeatherford** [comment]
I don't really understand the scenario here. Are you using WSL inside vscode? I understand vscode support is not very good at that. Can you better describe what you are trying to do?  Thx.

**Comment by StephenWeatherford** [comment]
Does this work if you're not using WSL?

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.

**Comment by JamesPGriffith** [comment]
This may help: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
