### ISSUE TITLE
Dockerfile syntax highlighting for escaped quotes is not quite right

### ISSUE THREAD

**Issue by dlech** [microsoft/vscode-docker#75]
Given the following dockerfile snippet...

```
# setup a new user
COPY compiler.sudoers /etc/sudoers.d/compiler
RUN chmod 0440 /etc/sudoers.d/compiler && \
    adduser --disabled-password --gecos \"\" compiler && \
    usermod -a -G sudo compiler
USER compiler
WORKDIR /home/compiler
CMD ["/bin/bash"] ["--login"]
```

The escaped quotes after `gecos` appear to throw off the syntax highlighting.

![selection_014](https://cloud.githubusercontent.com/assets/963645/24261832/46b8213a-0fc6-11e7-8d30-7eacab9c946a.png)

**Comment by natemcmaster** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/2696087/24632392/cfc1893e-1878-11e7-994f-5002ae1f0dc0.png)

**Comment by craigguest** [comment]
Also seems to be an issue when using backslashes within quoted paths:

![image](https://user-images.githubusercontent.com/3973190/31915867-129bda92-b848-11e7-9922-e63a681ba219.png)

**Comment by dcormier** [comment]
Another example of the problem:

```Dockerfile
# escape=`

FROM repo:label

RUN command `
	-arg1=\"val1\" `
	-arg2=\"val2\" `
	-arg3=\"val3\"

RUN echo "and now all the syntax highlighting is backwards"
```

Which shows up as:
![image](https://user-images.githubusercontent.com/216265/42092679-b5882cc2-7b77-11e8-91ae-f10c16657247.png)

**Comment by rcjsuen** [comment]
I wonder if this issue should really belong in [Microsoft/vscode](https://github.com/Microsoft/vscode/) or [moby/moby](https://github.com/moby/moby/) instead. The syntax highlighting is provided by the [`docker.tmLanguage.json` file](https://github.com/Microsoft/vscode/blob/master/extensions/docker/syntaxes/docker.tmLanguage.json) which lives in Microsoft/vscode (which is a converted version of the file in moby/moby).

**Comment by Leon99** [comment]
@PrashanthCorp so any chances to get this fixed here or we need to log an issue in https://github.com/Microsoft/vscode?
Also, just an observation - this problem doesn't happen in VS (just wondering if there is any potential for syntax rules reuse).

**Comment by rcjsuen** [comment]
@Leon99 Could you please provide an example of your Dockerfile that has proper syntax highlighting in Visual Studio Code but doesn't when the `vscode-docker` extension is installed?

**Comment by Leon99** [comment]
@rcjsuen I can't, I never said that was the case. It worked fine in VS2019, not in VSCode.

**Comment by rcjsuen** [comment]
> @rcjsuen I can't, I never said that was the case. It worked fine in VS2019, not in VSCode.

You're right, I misread your comment. You were talking about Visual Studio 2019 and not Visual Studio Code. My mistake and sorry for the confusion.

Could you share a screenshot of how something looks in VS2019 and VSCode for comparison? Thanks!

**Comment by bwateratmsft** [comment]
Since syntax highlighting is provided by VSCode with the tmLanguage file, I've created https://github.com/microsoft/vscode/issues/82988 and will close this one as external to that one.
