### ISSUE TITLE
Keep loading more than 10 minutes after clearing the invalid filter value 

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#751]
**OS:** Windows
**Node.js**: V10.14.1
**Extension Build**: [20190120.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2300)
Repro Steps:
1. Create a build task 'taskhelloworld' according to https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task.
2. Right click the created task ->'Run Task' ->Make sure there generated a repository named 'helloworld' with images tagged as 'cj*'.
3. Right click the task 'taskhelloworld' -> 'View Task Log' ->Input an invalid value on any of the text box of the filter like '\' -> Press 'Enter'(_It will pop up an error dialog--'Cannot read property 'os' of undefined_').
4. Clear the invalid value -> Press 'Enter' directly -> Check the result.

**Expect:**
Show all the images tagged as 'cj*' of the task '**taskhelloworld**'.

**Actual**:
1. Show all the images tagged as 'cj*' of the **registry**.
2. Keep loading more than 10 minutes.
![image](https://user-images.githubusercontent.com/34729022/51462576-ecb60900-1d9b-11e9-8f06-eecf603a38ed.png)

**Comment by rosanch** [comment]
The filter does not support any type of expressions. I will file this as a feature request.

**Comment by rosanch** [comment]
Sorry, I see what you mean. The loading appears to take a while for some unhandled filter request scenarios.

Also, I created a new issue (#757) for the enhancement request.

**Comment by EricJizbaMSFT** [comment]
Closing this as "wont-fix" since filters aren't supported in the [new tree and tasks view](https://github.com/microsoft/vscode-docker/pull/966)

**Comment by v-dantch** [comment]
Add the screenshot for it:
![image](https://user-images.githubusercontent.com/34729092/59490898-61f3b900-8eb8-11e9-868f-fb2974ba922d.png)
