### ISSUE TITLE
Add PHP support for 'Add Docker Files to Workspace'

### ISSUE THREAD

**Issue by Abhinav1217** [microsoft/vscode-docker#752]
Currently when we select "Docker: Add Docker Files to Workspace", We get 8 options, and an almost useless `other`.  Being a PHP developer, I would like it to have a `Php` option as well. 

Is there is a way to add templates, those who need can add docker files for there needs like `php-apache`, `php-nginx`, `lamp-stack` etc. Which would show when we select that option.

**Comment by StephenWeatherford** [comment]
We are glad to accept community PRs to add support for additional languages (see for instance https://github.com/Microsoft/vscode-docker/pull/644).  I do request that we have a responsive contact we can go to when related issues or PRs are entered by others, and if possible a project we can use for testing.

There isn't currently a way to add templates, although it's an interesting idea. I'm not sure it would get a lot of usage, though?

**Comment by Abhinav1217** [comment]
> We are glad to accept community PRs to add support for additional languages (see for instance #644).

I can submit a well commented docker-compose for a basic LAMP stack as PR. User can use the comments to adjust settings as per their need, ( like replacing mysql with pgsql or apache with nginx )

> I do request that we have a responsive contact we can go to when related issues or PRs are entered by others, and if possible a project we can use for testing.

I do check github everyday, does that count? As for project, A simple website with link to `phpinfo()` and `Db connection Test` with should be enough to get going. 

Personally, I am really just using updated and adjusted versions of https://github.com/sprintcube/docker-compose-lamp and https://github.com/atillay/docker-lemp as project starter.  Both of them have homepage out of box, and a beginner friendly configuration. 

> There isn't currently a way to add templates, although it's an interesting idea. I'm not sure it would get a lot of usage, though?

How about updating the "Other" to ask a little more than port. Or an import option. Something like `"Other"=> 'Link to raw dockerhub/github file'`

How about an extension with features similar to [cookiecutter](https://github.com/audreyr/cookiecutter), i.e. layout a basic project starter boilerplate as per an individuals preference.

**Comment by Surendrajat** [comment]
I have opened a PR #1449 for basic PHP support with Apache. The server will listen at `localhost:3000` by default. To test this create a `hello.php` file with the simplest code 
```php
<?php echo "hello from server"; ?>
```
and do a `docker-compose up`. You should be able to see output at `http://localhost:3000`.

**Comment by bwateratmsft** [comment]
Duping to #3346 (umbrella issue)
