### ISSUE TITLE
jupyter

### ISSUE THREAD

**Issue by killer88dk** [Microsoft/vscode-docker#753]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the `appFolder` or `appProject` property in the Docker debug configuration.

Version: 0.5.1
OS: win32

**Comment by philliphoff** [comment]
@killer88dk That error indicates that the extension did not find the application's project (.csproj) file in the expected location (i.e. the typical location relative to the root of the workspace opened in VS Code). It's entirely possible (and ok) if the file is in another location better suited to the application and workspace. In that case, however, you must set the appFolder or appProject to that location.
