### ISSUE TITLE
Docker command not working in vscode

### ISSUE THREAD

**Issue by beebeaaron** [Microsoft/vscode-docker#754]
Installed Docker, signed in

Installed the docker extension in vscode
Images are listed, however attempting to run them through either right click, or in the vscode terminal I get the error
'docker' is not recognized as an internal or external command, operable program or batch file.

the same command works normally in regular windows command prompt.
I have reinstalled the extension using F1, Developer Tools: Reinstall

**Comment by StephenWeatherford** [comment]
@beebeaaron Per the prerequisites in the README.md (https://github.com/microsoft/vscode-docker#prerequisites), you need to have docker installed on the machine for much of our functionality, as we use it directly.  The command you're getting seems to imply that either you don't have docker installed, or it is not in the system PATH.  Can you run docker from a standard command line?

**Comment by StephenWeatherford** [comment]
> 'docker' is not recognized as an internal or external command, operable program or batch file.

Sorry, just noticed you already answered that question of mine.  Then it seems to imply that docker is not in the PATH, or perhaps vscode needs to be restarted in order to pick up changes to the path?

**Comment by beebeaaron** [comment]
Well, it took a full reboot of the computer, but after that it worked.  Which is odd, since docker was installed before vscode and vscode has been updated and restarted several times after the docker install.

Oh well, it is working now, thanks for the help!

**Comment by StephenWeatherford** [comment]
Yeah, that is weird, but glad it's working for you now.  And thanks for using the extension.
