### ISSUE TITLE
Error docker visual studio 

### ISSUE THREAD

**Issue by ivanslemos** [Microsoft/vscode-docker#755]
1. 

&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.image.push
Error type: Error
Error Message: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

Version: 0.5.1
OS: win32

**Comment by StephenWeatherford** [comment]
@ivanslemos We do require that you open a workspace or folder before using much of the Docker extension functionality.  Please let me know if that is a problem or major inconvenience for you.  Thanks.

**Comment by ivanslemos** [comment]
Hi !!

Thanks for your help.. I go try again !!

;)

Em qui, 24 de jan de 2019 às 19:50, Stephen Weatherford (MSFT) <
notifications@github.com> escreveu:
