### ISSUE TITLE
The language client requires VS Code version ^1.26 but received version 1.25.1

### ISSUE THREAD

**Issue by Roman-Boiko-AT** [Microsoft/vscode-docker#756]
Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: @The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: win32

**Comment by StephenWeatherford** [comment]
@Roman-Boiko-AT Thanks for reporting.  We fixed this a couple of weeks ago with 0.5.1 (meaning that you shouldn't be able to upgrade to 0.5.1 if you don't have vscode 1.26). Unfortunately, you can still upgrade to 0.5.0 without issues.

You'll need to either upgrade to vscode 1.26 or install an earlier release of the extension. Please let me know if upgrading won't be accepting to you.  Thanks!
