### ISSUE TITLE
dockerSypete

### ISSUE THREAD

**Issue by SangYoonH** [Microsoft/vscode-docker#758]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.5.1
OS: win32

**Comment by StephenWeatherford** [comment]
@SangYoonH Without a workspace opened, we don't know where to place the docker files, and we don't know how to inspect the project to determine appropriate settings.  Please use File -> Open Folder... or Workspace and try again.  Thx.
