### ISSUE TITLE
Better quick-pick descriptions for .NET Core variants (ASP.NET, Console)

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-docker#766]
Users may not be clear on the differences between the `.NET Core Console` and `ASP.NET Core` variants of the Dockerfiles generated by the `Add Dockerfiles to workspace` task.  In particular, ASP.NET Core applications *are* technically console applications (that just happen to bind to a well-known port and serve HTTP traffic).  (Some users may still associate ASP.NET strictly with Windows and IIS despite ASP.NET Core being cross-platform.)

It may be helpful to improve the documentation around this task by highlighting the differences between each variant and when one is might be better suited than another.

**Comment by StephenWeatherford** [comment]
What do you think about adding a description to the quick pick items? They show up in the dropdown in a smaller font next to the item name. It could be added to IPlatformGeneratorInfo.

**Comment by bwateratmsft** [comment]
I like Stephen's suggestion. The "description" text shows up in a nice less-emphasized coloring (grey by default), and IMO is the perfect spot for some short descriptive text.
