### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by rajukmnr** [Microsoft/vscode-docker#768]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.configure
Error type: Error
Error Message: To generate Docker files you must first open a folder or workspace in VS Code.

Version: 0.5.1
OS: win32

**Comment by rajukmnr** [comment]
test

**Comment by StephenWeatherford** [comment]
@rajukmnr Just like the error says, please open a folder or workspace in vscode before using this command. We've gotten a couple of issues reported from this error lately.  Is the error confusing?  I'd appreciate feedback on how this would be less confusing to the user.  Thanks!
