### ISSUE TITLE
Display 'Delete' button when untagging one image

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#772]
**OS:** Win10/ Mac/ Linux
**Node.js:** V 10.14.0
**Build Version:** [20190130.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2570)

**Repro Steps:**
1. F1 -> Type and select 'Untag Azure Image'.
2. Select one registry -> Select one repository including one image at least.
3. Select one image -> Pop up a confirming dialog.

**Expect:**
Display 'Yes' button which means that the customers agree to untag the image.

**Actual:**
Display 'Delete'. It is a bit confused.
![image](https://user-images.githubusercontent.com/34729092/52033289-4e335180-24d9-11e9-861a-29e64b7cdc94.png)

**Comment by StephenWeatherford** [comment]
@rosanch This is fixed, right?

**Comment by rosanch** [comment]
correct
