### ISSUE TITLE
[Unstable] Do actions pop up an error 'Entry not found in cache' after shelving VS Code for hours

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#773]
**OS:** Win10/ Mac/ Linux
**Node.js:** V 10.14.0
**Build Version:** [20190130.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2570)

**Repro Steps:**
1. Open VS Code and shelve it for hours.
2. Do an action like 'F1'.

**Expect:**
All actions work well.

**Actual:**
Pop up an error 'Entry not found in cache'.
![image](https://user-images.githubusercontent.com/34729092/52033717-d0704580-24da-11e9-861d-029665192ec9.png).

**More Info:**
1. It works well after reloading VS Code or sign in again.
2. It is an unstable issue.

**Comment by StephenWeatherford** [comment]
This is a known issue in the old code we're using for our treeview.  We have plans to update this at some point: #445.  Thx.
