### ISSUE TITLE
[Suggestion]Update 'Docker' to 'Docker Desktop' in error notification

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#776]
**OS:** Win10/ Mac/ Linux
**Node.js:** V 10.14.0
**Build Version:** [20190130.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2570)

**Repro Steps:**
1. Make sure 'Docker Desktop' is not running like it is starting.
2. Navigate to 'Docker Explorer' --> Expand 'Images/Containers' node.
3. Pop up an error notification.

**Actual:**
Display 'Unable to connect to Docker....'.

**Suggestion:**
Update 'Docker' to 'Docker Desktop'.
![image](https://user-images.githubusercontent.com/34729092/52034340-129a8680-24dd-11e9-825a-5bb0a5483ac1.png)

**Comment by StephenWeatherford** [comment]
There are different options for installing Docker.  Docker for Windows (apparently now Docker Desktop) is only one of them.
