### ISSUE TITLE
No Intellisense shows after pressing "CTRL+SPACE" in docker-compose.yml on Mac

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-docker#777]
**OS:** Mac
**Node.js:**  V8.11.3
**Build Version:** [20190130.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2570&view=results)

**Repro Steps:**
1. Open VSCode  -> Open a file named docker-compose.yml.
2. Type **version: '1'** into the docker-compose.yml then type "CTRL+SPACE" on the next line.
3. Check for intellisense.

**Expect:**
Intellisense shows well after pressing "CTRL+SPACE" in docker-compose.yml.

**Actual：**
No Intellisense shows after pressing "CTRL+SPACE" in docker-compose.yml.

**More Info**
This issue doesn't reproduce on Windows/Linux.

**Comment by vishwavijayverma** [comment]
same happing with me also. I am unable to get a suggestion in docker-compose.ymal.I need to press key control+space, this is really annoying.

**Comment by philliphoff** [comment]
@v-xianya Are you continuing to see this?  Using `version: '2'`, I get immediate Intellisense as I type.

**Comment by v-dantch** [comment]
Hi @philliphoff , thanks for your work and we verified this issue on Mac with the latest build [20190921.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10325), fixed. So we will close this bug for now.
