### ISSUE TITLE
Dockerfile-development has no syntax coloring

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docker#78]
Testing MERN starter kit https://github.com/Microsoft/vscode/issues/22277

I expect Dockerfile-development to by syntax highlighted like Dockefile. It is not. 

![image](https://cloud.githubusercontent.com/assets/2449568/24820200/b6703f80-1b9c-11e7-8f39-02d94d7140f0.png)

**Comment by lostintangent** [comment]
Resolved in master, and we'll publish an update this week.
