### ISSUE TITLE
Support for ${workspaceFolder} in dockerRun/Volumes localPath and containerPath

### ISSUE THREAD

**Issue by xstof** [Microsoft/vscode-docker#785]
**Issue**: Currently, there seems to be no support for ${workspaceFolder} when configuring volume mappings in localPath or containerPath.  The error is 

`docker: Error response from daemon: create ${workspaceFolder}/.devcerts: "${workspaceFolder}/.devcerts" includes invalid characters for a local volume name`

**Example**:
~~~~json
"dockerRun": {
                "volumes": [
                    {
                        "localPath": "${workspaceFolder}/.devcerts",
                        "containerPath": "/.devcerts",
                        "permissions": "rw"
                    }
                ]
            }
~~~~

**Use case**: when mapping a drive into an ASP.NET Core container containing certificates for development in order to enable SSL.  These certs could be stored in the local workspace and mapped this way, without having to hardcode the full path.  (The full path might vary depending on who checks out the source.)

**Plugin version**: plugin was built from master at commit `a45a9a6601cf7b17cc3f2cc2ad16db339ba13a49`

**Comment by philliphoff** [comment]
@xstof Is there a specific use case for using `${workspaceFolder}` in the `containerPath` property *in addition to* `localPath`?  I would think that the container file system should be fairly independent of the user's workspace.

**Comment by xstof** [comment]
That makes perfect sense to me; I don't quite see the use case for that either.
