### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by sathishcaffeine** [Microsoft/vscode-docker#786]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@sathishcaffeine Thanks for taking the time to report this.  This dependency has already been fixed.  You need to either update vscode to at least 1.26.0 or downgrade the extension (hopefully the former).  Thanks!
