### ISSUE TITLE
The language client requires VS Code version ^1.26 but received version 1.25.1

### ISSUE THREAD

**Issue by prabhay759** [Microsoft/vscode-docker#787]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: win32

**Comment by StephenWeatherford** [comment]
@prabhay759 Thanks for reporting. 0.5.1 correctly requires vscode 1.26 to be installed, and 0.5.0 has been unpublished. Please upgrade vscode to 1.26 (or fall back to a 0.4.x version of the extension).
