### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by szarych** [Microsoft/vscode-docker#788]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.0-insider

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@szarych Thanks for taking the time to report this.  This was fixed in 0.5.1, in that the 0.5.1 version correctly requires vscode 1.26 before installing. So, could you please upgrade to vscode 1.26?  Thanks!
