### ISSUE TITLE
Prune all in category with right click menu

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode-docker#789]
Right now there's a whole system prune, which prunes even volumes. Although it's useful under some circumstances, sometimes you just want to prune containers or images.

It would be great if this extension allowed to right-click into "Images" or "Containers" and select "Prune" there, pruning only that kind of resource.

**Comment by StephenWeatherford** [comment]
Great idea, thanks!

https://docs.docker.com/engine/reference/commandline/image_prune/
