### ISSUE TITLE
Operation cancelled.

### ISSUE THREAD

**Issue by Dragonesis** [Microsoft/vscode-docker#790]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.image.build
Error type: Error
Error Message: Operation cancelled.

Version: 0.5.2
OS: darwin

**Comment by StephenWeatherford** [comment]
Thanks for taking the time to report.  This is fixed in the next release.
