### ISSUE TITLE
Parse error on private registry

### ISSUE THREAD

**Issue by khaosdoctor** [Microsoft/vscode-docker#792]
Getting a parse error when trying to log into any private repository:

## Repro steps:

1. Open docker explorer
2. Add a new private registry

```
Action: vscode-docker.connectCustomRegistry
Error type: HPE_INVALID_CONSTANT
Error Message: Parse Error
```

Version: 0.5.2
OS: darwin

**Comment by StephenWeatherford** [comment]
Sorry for the delay in responding. Can you tell us more about your private registry? It sounds like it's giving us back a response that Node doesn't understand (see https://stackoverflow.com/questions/34769824/what-does-this-error-mean-hpe-invalid-constant).

The main private registries we've tested are those built with the Docker 'registry:v2' image.

**Comment by khaosdoctor** [comment]
It's a normal registry, it's a v2 image. The odd part is that it used to work before the last VSCode update, all my colleagues can still access the registry, but I just can't.

**Comment by StephenWeatherford** [comment]
What version of vscode?  And is it insiders?

**Comment by jiaoyilun** [comment]
i have the save error.   
my version is stable

**Comment by khaosdoctor** [comment]
Version stable, no insider

**Comment by StephenWeatherford** [comment]
Not coming up with much more here - everything I search for suggests the server is returning invalid data.  Some things to try:
1) Disable all other extensions
2) Reinstall older vscode version, see if it really is related to that (are your coworkers using a different version?)  Are they also on Macs?
3) Are you using a proxy server?  Could it be returning invalid data?

**Comment by khaosdoctor** [comment]
Ok I ran some tests:

1. Disabled all extensions except for `vscode-docker` and the error continues
2. Yesterday one of my coworkers just updated his version to 1.32 (I think that is the latest one), which was the same as mine, and he also lost his private registry config. So he just went up there and logged like nothing happened. So I really do not believe this is something to do with versions
3. Nope, tried it at home, at an university, at a coworking and at the office. Same results for all

Is there a way I can get more debug info without having to build the extension?

**Comment by StephenWeatherford** [comment]
Very strange. Command Palette -> Developer: Toggle Developer Tools will open up a debugger that you can check for output and errors in with the console.

**Comment by khaosdoctor** [comment]
I got it opened here and I got this message:

![image](https://user-images.githubusercontent.com/3200560/54087868-639c6680-4336-11e9-8e97-ba7e326921da.png)

But not much intel though...

**Comment by jiaoyilun** [comment]
> I got it opened here and I got this message:
> 
> ![image](https://user-images.githubusercontent.com/3200560/54087868-639c6680-4336-11e9-8e97-ba7e326921da.png)
> 
> But not much intel though...

same error

**Comment by StephenWeatherford** [comment]
Running out of ideas.  Can you successfully do a "docker login" and push/pull with this private registry?

**Comment by khaosdoctor** [comment]
Yep!

![image](https://user-images.githubusercontent.com/3200560/54313151-7c677f00-45b7-11e9-9c33-fcaf7097990d.png)

And I can successfully pull too:

![image](https://user-images.githubusercontent.com/3200560/54313249-aa4cc380-45b7-11e9-9778-0470034608bd.png)

Is there any way we can get network messages? Like log them or something?

**Comment by khaosdoctor** [comment]
Ok so now things got really weird. After the latest update from VSCode, something happened and suddenly everything started working again... I just cloned the extension so I could test it locally but it seems that something in the VSCode version did the trick. 

However I'm also on a different network than before, which can also be the cause of the solution, as soon as I return I'll test it again with the dev mode enabled and debug it properly.

**Comment by PrashanthCorp** [comment]
Looks like the problem could have been solved. If you don't find a repro soon, we shall automatically close it.

**Comment by khaosdoctor** [comment]
Well, apparently this has been magically solved... I'll get in touch again if something happens.

Thanks for the help!
