### ISSUE TITLE
Allow configuration of docker-compose down --rmi

### ISSUE THREAD

**Issue by felipelazzari** [microsoft/vscode-docker#794]
Currently we can not configure the option to perform a docker-compose down --rmi local
I find it very useful to be able to clean up the images built by the docker-compose up.

**Comment by PrashanthCorp** [comment]
Adding this to #623.

**Comment by StephenWeatherford** [comment]
We should make all the commands customizable.

**Comment by Sach97** [comment]
In my experience I find this command more reliable `docker-compose down -v --rmi all --remove-orphans`

**Comment by bwateratmsft** [comment]
This sort of fits under the #1596 umbrella.
