### ISSUE TITLE
Syntax highlting of comments after commands

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode-docker#796]
Adding a line like this does not color the comment green.

RUN npm install # Make this green please

Would be nice if it did.

**Comment by rcjsuen** [comment]
@thernstig It doesn't highlight it because Docker does not interpret what you wrote as a comment.

See moby/moby#37841.

**Comment by thernstig** [comment]
@rcjsuen you are absolutely correct and I should have found this myself with better research. As it did not fail the build process I thought it worked with such comments. Closing this. Hopefully the issue will stop someone else from reporting this in the future.

**Comment by StephenWeatherford** [comment]
@thernstig Either way, thanks for taking the time to report, and yeah, hopefully it will help others.
