### ISSUE TITLE
[.NET Core Debugging] Debug with dotnet watch

### ISSUE THREAD

**Issue by Patrik-Berglund** [microsoft/vscode-docker#797]
Hi,

Is it possible to use dotnet watch together with the debugger?

If so, how should the launch.json and Dockerfile be setup?

BR
Patrik berglund

**Comment by Patrik-Berglund** [comment]
Current Dockerfile with watch,

```
FROM microsoft/dotnet:2.2-sdk 
WORKDIR /app
ENTRYPOINT dotnet watch run --project TestApp.Api/TestApp.Api.csproj --urls=http://+:5000

```

**Comment by philliphoff** [comment]
@Patrik-Berglund That's an interesting idea, but honestly I don't know if it is feasible; it would require some investigation. Usually rebuilding the binaries requires stopping/restarting the debugger, which may not give you the experience you're looking for.  There are some exceptions, such as `.cshtml` files which are watched and re-built by ASP.NET MVC itself.  (It appears that isn't happening in the case of debugging in Docker with VS Code, which is something that I'll need to look into separately.)

**Comment by Patrik-Berglund** [comment]
Hi, 

Ok, 

We went with using the file watcher and then manually attaching the debugger when needed.

**Comment by bwateratmsft** [comment]
Something like this could be done with the Remote - Containers extension.
