### ISSUE TITLE
Incomplete image listing for private registry (support Load More)

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#799]
Reported by a customer:

> I've added a private registry, and the menu shows the first 50x or so images available but the extension doesnt request the whole list, or does not show a way to request the next page of results as there are several hundred images

I'm not sure if this is a function of the registry returning paginated data or just that the extension is only showing the first _n_ images.

**Comment by StephenWeatherford** [comment]
Need to move to shared tree code first.
