### ISSUE TITLE
Docker extension error: Cannot read property 'registerDebugConfigurationProvider'

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/vscode-docker#801]
Repro steps:
Pretty simple to repro, just download the Docker .VSIX file ( [https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker) ) and load it up into ADS.

Please let me know if there's any more information I can provide?
( Probably fastest to just ping me on twitter: [@SQLvariant](https://twitter.com/SQLvariant) )

Action: docker.activate
Error type: TypeError
Error Message: Cannot read property 'registerDebugConfigurationProvider' of undefined

Version: 0.5.2
OS: win32

**Comment by philliphoff** [comment]
@SQLvariant What version of VS Code are you using?

**Comment by SQLvariant** [comment]
@philliphoff I'm running:
Version 1.4.5
Commit 887f4e8985023602e599cf86bdb44df48bb28569
Date 2019-02-12T06:20:08.633Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by SQLvariant** [comment]
Doh!  Just realized I added this to VS-Code, not ADS.
<Head-Desk!>

**Comment by SQLvariant** [comment]
I went ahead and opened an issue for this on the Azure Data Studio repo: https://github.com/Microsoft/azuredatastudio/issues/4162

You can probably close this item now.
