### ISSUE TITLE
certificate signature failure

### ISSUE THREAD

**Issue by andjimrio** [microsoft/vscode-docker#802]
I was trying enter my Private Registry in the Docker Extension but failed. However, in the cli of docker, it worked without problem.

Repro steps:
Enter the same parameters of docker login and in the PowerShell works. But, in the Private Registries fails with this error:

Action: vscode-docker.connectCustomRegistry
Error type: CERT_SIGNATURE_FAILURE
Error Message: certificate signature failure

Version: 0.5.2
OS: win32

**Comment by bwateratmsft** [comment]
@andjimrio I know it's been a long time 😖 Registries have been pretty much entirely rewritten since this was filed, do you know if this issue is still occurring?
