### ISSUE TITLE
Internal error: Unexpected value found in context "type of registry node": undefined

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#806]
![image](https://user-images.githubusercontent.com/6913354/53278503-93a10400-36be-11e9-9247-938128161188.png)

**Comment by StephenWeatherford** [comment]
Can't figure out how to repro, adding more info to the error message.

**Comment by EricJizbaMSFT** [comment]
Closing this since "registry node" was changed in https://github.com/microsoft/vscode-docker/pull/966 and this error shouldn't be possible.
