### ISSUE TITLE
Docker: Attach Shell always connects as root

### ISSUE THREAD

**Issue by bhaidar** [Microsoft/vscode-docker#807]
Hi,
Is there a way not to connect as root when attaching a shell?
For instance, when I connect to the container and try to connect to Postgres I get an error:

````
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
````

So if I can connect with a normal user then I can connect to Postgres internally.

Thanks
Bilal

**Comment by StephenWeatherford** [comment]
It was my understanding that docker exec ran unprivileged (see https://github.com/moby/moby/pull/26836/files) by default. What if you added the -u param?
```Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container

Options:
  -d, --detach               Detached mode: run command in the background
      --detach-keys string   Override the key sequence for detaching a
                             container
  -e, --env list             Set environment variables
  -i, --interactive          Keep STDIN open even if not attached
      --privileged           Give extended privileges to the command
  -t, --tty                  Allocate a pseudo-TTY
  -u, --user string          Username or UID (format:
                             <name|uid>[:<group|gid>])
  -w, --workdir string       Working directory inside the container
```

When you find a command you like, you can modify the docker.attachShellCommand.linuxContainer setting to change what command we use for attach to shell.

**Comment by bhaidar** [comment]
@StephenWeatherford Thanks for the info! 

I am always running VS Code As Admin, do you think that's the reason?

I ran now VS Code without As Admin, I attached a shell, still, the username logged in is using root@... but I was able to connect to psql.

**Comment by StephenWeatherford** [comment]
Good to hear.  In general we don't recommend running vscode as admin unless there's a specific requirement for it. I would assume terminals created in this case would also have admin privileges, but vscode controls that, not us.

It sounds like the issue is resolved, then?
