### ISSUE TITLE
error report (auto gen)

### ISSUE THREAD

**Issue by firblaze** [Microsoft/vscode-docker#808]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.0

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@firblaze Thanks for taking the time to report this.  This dependency issue has been fixed and version 0.5.0 of the extension has been unpublished. You'll need to either upgrade to vscode 1.26 or install a previous version of the extension (hopefully the former).  Thanks for using the extension!
