### ISSUE TITLE
Colorblind Settings/Indicators for Container Status

### ISSUE THREAD

**Issue by RyanTaite** [Microsoft/vscode-docker#811]
I'm partially colorblind with both Deuteranopia and Protanopia. I am unable to tell the difference between a stopped (red) or started (green) container in VS Code: 
<img width="30" alt="screen shot 2019-02-27 at 1 53 23 pm" src="https://user-images.githubusercontent.com/5490996/53522588-f10acb80-3a97-11e9-8630-55d8ea9281fc.png">

Please either add some icons to it or change the colors to something more drastic such as Blue for started and Red for stopped

Using extension:
Name: Docker
Id: peterjausovec.vscode-docker
Description: Adds syntax highlighting, commands, hover tips, and linting for Dockerfile and docker-compose files.
Version: 0.5.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker

**Comment by StephenWeatherford** [comment]
@RyanTaite Thanks for reporting. We always try to make sure that important information is not conveyed by graphics or color alone. In this case, the state of the container is contained in the label itself:
![image](https://user-images.githubusercontent.com/6913354/53601006-ef0c3f80-3b5f-11e9-9258-66e0fe749369.png)
Does that not help?  Thanks.

**Comment by RyanTaite** [comment]
Sure, but not at a glance like the icons do for everyone else. I have to expand the side panel until it's literally half my screen to read all of my current environments statues because of how long their names are.

I figure there could be something similar to how Skype and Microsoft Teams handles their presence icons, shown in some photos here: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-new-in-Microsoft-Teams-April-update/ba-p/179801

**Comment by StephenWeatherford** [comment]
That's helpful info, thanks, will look into it.

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/54163871-ae41df80-4417-11e9-8f22-4791d1a8dfbc.png)

**Comment by RyanTaite** [comment]
That looks great to me! I would really appreciate that!

**Comment by StephenWeatherford** [comment]
Will be released soon, thanks for letting us know!
