### ISSUE TITLE
Why do I get error?

### ISSUE THREAD

**Issue by secuof** [Microsoft/vscode-docker#812]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.remove
Error type: Error
Error Message: Operation cancelled.

Version: 0.5.2
OS: darwin

**Comment by StephenWeatherford** [comment]
@secuof Thanks for reporting. This issue has been fixed and will be released in a new version of the extension very soon.
