### ISSUE TITLE
[Suggestion]Could we deploy an image to an existing azure app service?

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#813]
**OS:** All
**Build Version:** [20190228.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3669)
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one image under registry --> Select 'Deploy Image to Azure App Service'.
2. Check the result.

**Actual:**
Prompt to create a new web app.
![image](https://user-images.githubusercontent.com/34729092/53627149-8bfcc600-3bbc-11e9-812d-8ee338dda7e7.png)

**Suggestion:**
Could we deploy an image to an existing azure app service?

**Comment by bwateratmsft** [comment]
Marking this as a dupe of #1535
