### ISSUE TITLE
Unable to infer the application project file. Set either the `appFolder` or `appProject` property in the Docker debug configuration.

### ISSUE THREAD

**Issue by liuhll** [Microsoft/vscode-docker#815]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the `appFolder` or `appProject` property in the Docker debug configuration.

Version: 0.5.2
OS: win32

**Comment by philliphoff** [comment]
@liuhll Can you provide any additional context, such as where your project file is located relative to the root folder opened in VS Code?  This error generally means that the project file couldn't automatically be found amongst a couple of default locations, so you will need to specify either the folder or full path (`appFolder` or `appProject` respectively) in the debug configuration.  Thanks!
