### ISSUE TITLE
No workspace folder is associated with debugging

### ISSUE THREAD

**Issue by alejagapatrick** [Microsoft/vscode-docker#821]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.5.2
OS: win32

**Comment by philliphoff** [comment]
@alejagapatrick Can you provide more context, such as the folder structure opened in VS Code and the location of the .NET project file in relation to that root folder opened with VS Code?
