### ISSUE TITLE
vscode

### ISSUE THREAD

**Issue by hongkunyue** [Microsoft/vscode-docker#827]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: darwin

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  This was fixed in https://github.com/Microsoft/vscode-docker/issues/787.  You'll need to update vscode to at least 1.26 or use a previous version of the extension.  Thanks.
