### ISSUE TITLE
An error occurs when executing 'Run Interactive' for an image

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#828]
**OS:** ALL
**Node.js:** V10.13.0
**Regression From**: Previous release 0.5.2
**Build Version:** [20190309.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3904&view=results)

**Repro Steps:**
1. Run '**docker pull hello-world**' command.
2. Expand 'Images' and make sure the image "hello-world:latest" exists.
3. Right click it and select 'Run interactive' then check the result on 'TERMINAL'

**Expect**:
No error occurs.

**Actual**:
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/54111410-bc472e80-441e-11e9-8c33-46ab913826e2.png)

**More Info:**
1. This issue also reproduce when executing 'Run' for an Image.
2. Show an error  '**bash: syntax error near unexpected token'('**' on 'TERMINAL' when executing 'Run Interactive/Run' for an image on Mac/Linux.

**Comment by StephenWeatherford** [comment]
Having trouble reproing this.  Note that the "unable to find image" error can be ignored.  So please do a "docker login" from the terminal and try again.

On Mac, I don't see any errors, either.  Can you show the full terminal command and output that you're seeing?  Thx.

**Comment by v-xianya** [comment]
@StephenWeatherford Thanks for your updates.

**On windows:**
![image](https://user-images.githubusercontent.com/41351993/54191538-16b0bf80-44f1-11e9-906d-5488767bef1c.png)

**On Mac/Linux:**(Show the same error on TERMINAL and nothing shows in OUTPUT)

1. **TERMINAL:**
![image](https://user-images.githubusercontent.com/41351993/54191706-6e4f2b00-44f1-11e9-9a66-c9f363d33b4e.png)

2. **OPUPUT:**
![image](https://user-images.githubusercontent.com/41351993/54191846-ad7d7c00-44f1-11e9-8cd8-11a630cebbb6.png)

**Comment by StephenWeatherford** [comment]
Must have tested without the grouping support.  I see this now, good catch!

**Comment by StephenWeatherford** [comment]
(It's not just Mac/Linux.)
