### ISSUE TITLE
Display " :( Application Error " in browser after deploying one image 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-docker#830]
**OS**: All
**Build Version:** [20190309.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3904)
**Regression**: Not a Regression

**Repro Steps**:
1. Right click one image under 'Registries' -->Select 'Deploy Image to Azure App Service'.
2. New an Azure App Service according to the prompting.
3. Open the link in browse from 'Output' window after deploying completely.

**Expect:**
Succeed to browse the website.

**Actual:**
Display "Application Error".
![image](https://user-images.githubusercontent.com/34729092/54114625-0d680b80-43a8-11e9-85cc-3e0fc34d4c3a.png)

**Comment by StephenWeatherford** [comment]
Can't repro.  What image did you deploy?  It needs to be something designed to be deployed, such as the express app in the testcases.  Just random images may or may not work.  Thx.

**Comment by v-dantch** [comment]
Hi Stephen, I tried to deploy the express app on the latest build [20190312.5,](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3975) this issue does not repro. 
And we will continue to investigate the root cause.

**Comment by PrashanthCorp** [comment]
Closing for now. Feel free to reopen if it reproduces.
