### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by mosesfabiyi** [Microsoft/vscode-docker#831]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.acr.runTaskFile
Error type: Error
Error Message: Operation cancelled.

Version: 0.5.2
OS: win32

**Comment by StephenWeatherford** [comment]
@mosesfabiyi The fact that an error has been shown when you cancel an operation has been fixed and will be released soon.  Thanks for taking the time to report.  Let us know if you are having any other issues, thanks.
