### ISSUE TITLE
Change the action 'Pull Tag from Azure' to 'Pull Image from Azure' on context menu

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#837]
**OS**: All
**Build Version**: [20190312.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3975)
**Regression From**: Not a regression

**Steps to reproduce:**
1. Expand one ACR node -> Right click one image then check the context menu.

**Expect:**
There shows 'Pull **Image** from Azure'.

**Actual**:
There shows 'Pull **Tag** from Azure'.
![image](https://user-images.githubusercontent.com/34729022/54186876-9abf6480-4469-11e9-9a52-ecbde17c1d73.png)

**More info:**
The placeholder shows '**Select the image ....**' when running the action from Command Palette.
![image](https://user-images.githubusercontent.com/34729022/54186838-8a0eee80-4469-11e9-9bad-e00998bca4fc.png)

**Comment by StephenWeatherford** [comment]
@rosanch  What do you think? I'm inclined to agree.

**Comment by rosanch** [comment]
Well a tag is a specific type of image. However for naming, it'll be better to add @SteveLasker to the issue.

**Comment by rosanch** [comment]
I do agree however that both should show the same name. It's either image or tag.

**Comment by StephenWeatherford** [comment]
I don't think I've seen an image itself referred to as a tag, but the naming conventions are very confusing, so I'd love to hear what Steve says.
