### ISSUE TITLE
 No icon shows in front of one image when selecting 'No Grouping'

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#838]
**OS:** All
**Node.js:** V10.13.0
**Build Version:** [2019312.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3975)

**Repro Steps:**
1. Make sure there are images under 'Images' node.
2. Right click 'Images' and select 'No Grouping' then check whether icon shows in front of the image.

**Expect:**
The icon of images shows well.
![image](https://user-images.githubusercontent.com/41351993/54189341-8cfef300-44ec-11e9-9798-a4c7c12b5b4b.png)

**Actual:**
No icon shows.
![image](https://user-images.githubusercontent.com/41351993/54189358-9b4d0f00-44ec-11e9-9b71-895f13ab9e89.png)

**Comment by StephenWeatherford** [comment]
@fiveisprime We talked about this, and I believe you were fine with it.  I'm now only using the icon for group nodes.  So I guess we need an images icon?

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/54233335-fb7e8980-44c9-11e9-9825-0af8ce1bd79b.png)
![image](https://user-images.githubusercontent.com/6913354/54233321-f3264e80-44c9-11e9-9549-d078414e1937.png)
![image](https://user-images.githubusercontent.com/6913354/54233632-8bbcce80-44ca-11e9-9a2d-585749f53c56.png)
![image](https://user-images.githubusercontent.com/6913354/54233483-439dac00-44ca-11e9-808b-e92ac1946435.png)

**Comment by v-xianya** [comment]
Verified on build [20190316.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4119&view=results). This issue also reproduces, so re-open it.

**Comment by StephenWeatherford** [comment]
We changed the design, the new behavior is correct, thanks.
