### ISSUE TITLE
Unable to restart one container which initial state is stopped

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#839]
**OS**: All
**Build Version**: [20190312.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3975)
**Regression From**: Not a regression

**Steps to reproduce:**
1. Run the command: **_docker run hello-world._**
2. Make sure there shows a stopped container 'hello-world' on Containers node.
3. Right click the container then select 'Restart Container' -> Refresh.

**Expect:**
The container can be restarted successfully.

**Actual**:
The container still shows as stopped.

**More info:**
This issue doesn't reproduce for images which initial state is started.

**Comment by StephenWeatherford** [comment]
hello-world just writes to the output and then immediately exits, so you will never see it in a running state.
