### ISSUE TITLE
Capitalize the first letter of each word when selecting how to group the images node

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-docker#845]
**OS:** All
**Extension Version:** [2019.313.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3998)
**Regression From:** Not a regression

**Steps to reproduce:**
1. Click the icon 'Group Images By...' -> Check the command list.

**Expect:**
Capitalize the first letter of each word for the shown commands.
![image](https://user-images.githubusercontent.com/34729022/54269826-4dabc300-453b-11e9-8f67-6b55260e73fd.png)

**Actual:**
Not the first letter of every words is capitalized.
![image](https://user-images.githubusercontent.com/34729022/54269786-3cfb4d00-453b-11e9-92e3-4027d43e6a17.png)

**Comment by StephenWeatherford** [comment]
This is definitely confusing, and I had to look it up to be sure, but I believe these should be sentence casing (only first word capitalized).  See https://vsuiguide.azurewebsites.net/topics/02%20Fonts%20and%20Formatting/02.02%20Text%20style.html, 
![image](https://user-images.githubusercontent.com/6913354/54305300-3f35c980-4584-11e9-9069-f802e842894b.png)
The ones in the command palette are all commands and are thus title casing (all/most words capitalized).

Thx.
