### ISSUE TITLE
Different Icons for container that is starting and container that is healthy

### ISSUE THREAD

**Issue by duxbuse** [microsoft/vscode-docker#856]
Currently both containers that are starting and containers that are healthy have the same green icon. I would appreciate if there was a starting icon that then turned into a green healthy icon, so I can visually see when the state changes. Even if this is only for images with healthchecks.

**Comment by StephenWeatherford** [comment]
Which version of the extension do you have?  We've made some recent icon changes.  Thx.

**Comment by duxbuse** [comment]
Yes the latest version with the new icons there is still no distinction
between starting and healthy

**Comment by aharpervc** [comment]
"Health" isn't an option for description, group, or sort which would largely address this. Additionally, this would be helpful when starting containers with long names, where the health check is stuffed off to the right where it's not easily visible:

Not visible here:

![image](https://user-images.githubusercontent.com/441085/91071009-9fe48500-e605-11ea-8857-80ba5a1c75e0.png)

Is it here? Not yet....

![image](https://user-images.githubusercontent.com/441085/91071093-c0acda80-e605-11ea-8471-4ed347fddeb4.png)


Oh _there_ you are

![image](https://user-images.githubusercontent.com/441085/91071196-e508b700-e605-11ea-8777-21df62780dba.png)

I don't have a 200" monitor so putting the health check the right side (in a panel that doesn't even horizontally scroll) isn't great design...

**Comment by kjorand** [comment]
Maybe inspiration for a PR : 
#609

Well for some reason it won't link ...

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.29.4.
