### ISSUE TITLE
VS Code Docker Extension  Not Working Windows7

### ISSUE THREAD

**Issue by tusharbudhe0302** [microsoft/vscode-docker#857]
Repro steps:

1.
2.

Action: vscode-docker.dockerHubLogin
Error type: 407
Error Message: \r\n \r\n 
\r\n \r\n > \r\n \r\n \r\n \r\n Access Denied (authentication_failed)\r\n 
\r\n 
\r\n \r\n \r\n \r\n \r\n Your credentials could not be authenticated: \"Credentials are missing.\". You will not be permitted access until your credentials can be verified.\r\n \r\n \r\n \r\n \r\n This is typically caused by an incorrect username and/or password, but could also be caused by network problems.\r\n \r\n \r\n \r\n \r\n 
\r\n For assistance, contact your network support team.\r\n \r\n \r\n \r\n 
\r\n \r\n

Version: 0.6.1
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
new i (dist/extension.bundle.js:157:636651)
$.callback (dist/extension.bundle.js:157:635500)
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:157:634554)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:187:5468)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:187:18281)
$.emit (events.js:182:13)
IncomingMessage.<anonymous> (dist/extension.bundle.js:187:17123)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tic

**Comment by StephenWeatherford** [comment]
@tusharbudhe0302 Could you make sure you can log in to dockerhub.com and docker command-line?  And then try again?  Thx.

**Comment by tusharbudhe0302** [comment]
This issue only comes when you use Docker in a VPN. I come out of the VPN and connect to direct network It works.
