### ISSUE TITLE
Can't login to DockerHub account

### ISSUE THREAD

**Issue by alidursen** [Microsoft/vscode-docker#858]
Repro steps:
1. Docker asked me to logout/login once i created a 2nd Docker account
2. I logged in through CLI but  it didn't work
3. I disabled/enabled extension on Code, at which point it asked me to login again
4. Entered my credentials to where it asked, it failed.

Action: vscode-docker.dockerHubLogin
Error type: Error
Error Message: Couldn't create item: The secret was transferred or encrypted in an invalid way.

Version: 0.6.1
OS: linux
VS Code Version: 1.31.1

**Comment by alidursen** [comment]
failed to realize i ought to logout by right-clicking the menu, as opposed to from terminal. problem seems to be solved now.

**Comment by StephenWeatherford** [comment]
Weird, but thanks.
