### ISSUE TITLE
No Attach Shell

### ISSUE THREAD

**Issue by vladknp** [microsoft/vscode-docker#859]
Repro steps:

1.
2.

Action: vscode-docker.container.open-shell
Error type: Error
Error Message: There are no Docker containers that apply to this command.

Version: 0.6.1
OS: win32
VS Code Version: 1.33.0-insider

<details>
<summary>Call Stack</summary>

```
l (dist/extension.bundle.js:1:421683)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
The extension didn't think there were any running containers that could be attached to.  Was this not the case?  Thx.
