### ISSUE TITLE
Apostrophe in MAINTAINER causes all following text to be parsed as string

### ISSUE THREAD

**Issue by Strum355** [Microsoft/vscode-docker#860]
![image](https://user-images.githubusercontent.com/18282288/54683368-5dae3e80-4b09-11e9-8e8f-83f43e21b5d7.png)

**Comment by StephenWeatherford** [comment]
This is a bug in moby/moby (the Dockerfile colorization is owned by VS Code, and they get the file from moby).  I've entered a bug here: https://github.com/moby/moby/issues/38927

If it's fixed there, we can ask vscode to import the fix.

**Comment by Strum355** [comment]
Great, thanks!

**Comment by StephenWeatherford** [comment]
I had noticed this as well, but they specifically pointed out that MAINTAINER is superseded by LABEL:  https://github.com/moby/moby/issues/38927#issuecomment-475842660

LABEL maintainer="Mark O'Malley"

Does this resolve the issue for you?

**Comment by Strum355** [comment]
Ideally it would be fixed as we have a lot of dockerfiles in various repos using `MAINTAINER`. This isnt a big issue however so if youd like to close this then thats fine. If a fix is created in the moby repo then itd be great to see it end up here too :)

**Comment by StephenWeatherford** [comment]
Okay, given the status I'm going to close it for now. Thanks!
