### ISSUE TITLE
[Docker: Build Image] not detecting all "Dockerfile" files.

### ISSUE THREAD

**Issue by Szauka** [Microsoft/vscode-docker#861]
Vs Code: 
    Version: 1.32.3 (user setup)
    Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
    Date: 2019-03-14T23:43:35.476Z
    Electron: 3.1.6
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Windows_NT x64 10.0.16299

![image](https://user-images.githubusercontent.com/33459309/54689045-afa99100-4b16-11e9-996d-9036b6713b44.png)

**Comment by dluc** [comment]
looks like the extension supports "*.Dockerfile" but not "Dockerfile.*". The latter is a popular way of naming docker files when more than one is present in a folder.

**Comment by Szauka** [comment]
@dluc thanks for pointing it out.

**Comment by EricJizbaMSFT** [comment]
FYI - we're tracking support for `Dockerfile.*` here: https://github.com/microsoft/vscode-docker/issues/192
