### ISSUE TITLE
 OAuth support Error When coonect to private registry

### ISSUE THREAD

**Issue by Lywangwenbin** [Microsoft/vscode-docker#864]
Repro steps:

1.
2.

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.6.0
OS: darwin
VS Code Version: 1.32.1

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.connectCustomRegistry (dist/extension.bundle.js:157:513558)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
How is your private registry set up?

**Comment by StephenWeatherford** [comment]
#869

**Comment by louzadod** [comment]
Hi.
I'm using private Docker Registry (https://docs.docker.com/registry/deploying/) and having the same issue.
Authentication is Basic.
Registry certificate is emitted  by Let's Encrypt.

Message from vscode Output Docker
```
Error: read ECONNRESET
```
