### ISSUE TITLE
 UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by aglwallac** [Microsoft/vscode-docker#867]
Repro steps:

1. connect to private registy
2. Entered: https://myregistry.mysubdomain.mydomain.com
3. Enter username: "ENTER" for anonymous
4. Pop-up appears in lower right:
      " unable to get local issuer certificate 
      Source: Docker (Extension)
     "

Action: vscode-docker.connectCustomRegistry
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.6.1
OS: darwin
VS Code Version: 1.33.0-insider

<details>
<summary>Call Stack</summary>

```
new n (dist/extension.bundle.js:157:636422)
$.callback (dist/extension.bundle.js:157:635108)
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:157:634554)
module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:187:5468)
$.emit (events.js:182:13)
$.module.exports.$.onRequestError (dist/extension.bundle.js:187:14523)
ClientRequest.emit (events.js:187:15)
TLSSocket.socketErrorListener (_http_client.js:382:9)
TLSSocket.emit (events.js:182:13)
emitErrorNT (internal/streams/destroy.js:82:8)
emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by PrashanthCorp** [comment]
Can you try adding  `"docker.importCertificates": true` in your `settings.json`?  Let us know if that helps.
