### ISSUE TITLE
Improve error message when docker has not been found- ENOENT //./pipe/docker_engine

### ISSUE THREAD

**Issue by benmed00** [microsoft/vscode-docker#868]
Repro steps:

==> Steps to reproduce the issue

1.CTRL+Shift+P in VScode 
2.typing "azur"
3.choose : "Doker: Azure CLI"

Action: vscode-docker.container.start.azurecli
Error type: ENOENT
Error Message: connect ENOENT //./pipe/docker_engine

Version: 0.6.1
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
PipeConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

</details>

**Comment by PrashanthCorp** [comment]
I could repro the error. It turned out that I had closed/killed the docker process (Docker desktop on windows). Once I spun it up again, it seems to work. 

Hope that helps!

**Comment by PrashanthCorp** [comment]
TODO: Improve the error message.

**Comment by kreiswelt** [comment]
I also got this kind of error by clicking the Docker icon from side menu 

Error message:
Unable to connect to Docker. Please make sure you have installed Docker and that it is running. Details: connect ENOENT //./pipe/docker_engine

Version: 0.6.4
OS: Windows 7 Pro
VSCode: 1.35.1


```
stack:"Error: connect ENOENT //./pipe/docker_engine\n\tat PipeConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)"
```
