### ISSUE TITLE
Default Node.js Dockerfile fails to build if there are no dependencies in package.json

### ISSUE THREAD

**Issue by exocode** [microsoft/vscode-docker#871]
In order to jumpstart development, it would be good to provide an example which works out of the box.

To recreate this issue:

```
npx create-react-app demo-app
cd demo-app
code .
```
Scaffold the `Dockerfile`, `docker-compose.yml` and `.dockerignore` via `Docker: Add docker Files to Workspace`-function provided by this plugin. _(shift + cmd + p)_ 

Run `docker-compose up --build`.

```
Building demo-app
Step 1/8 : FROM node:10.13-alpine
 ---> 93f2dcbcddfe
Step 2/8 : ENV NODE_ENV production
 ---> Using cache
 ---> 5b75b5a890c9
Step 3/8 : WORKDIR /usr/src/app
 ---> Using cache
 ---> b5ff035ce18b
Step 4/8 : COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
 ---> Using cache
 ---> bd52b25d166b
Step 5/8 : RUN npm install --production --silent && mv node_modules ../
 ---> Using cache
 ---> a445b737058b
Step 6/8 : COPY . .
 ---> Using cache
 ---> b93fe1c55766
Step 7/8 : EXPOSE 3000
 ---> Using cache
 ---> a9e939ba46df
Step 8/8 : CMD npm start
 ---> Using cache
 ---> 18dc7960d7c3
Successfully built 18dc7960d7c3
Successfully tagged demo-app:latest
Recreating demo-app_demo-app_1 ... done
Attaching to demo-app_demo-app_1
demo-app_1  |
demo-app_1  | > demo-app@0.1.0 start /usr/src/app
demo-app_1  | > react-scripts start
demo-app_1  |
demo-app_1  | sh: react-scripts: not found
demo-app_1  | npm ERR! file sh
demo-app_1  | npm ERR! code ELIFECYCLE
demo-app_1  | npm ERR! errno ENOENT
demo-app_1  | npm ERR! syscall spawn
demo-app_1  | npm ERR! demo-app@0.1.0 start: `react-scripts start`
demo-app_1  | npm ERR! spawn ENOENT
demo-app_1  | npm ERR!
demo-app_1  | npm ERR! Failed at the demo-app@0.1.0 start script.
demo-app_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
demo-app_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
demo-app_1  |
demo-app_1  | npm ERR! A complete log of this run can be found in:
demo-app_1  | npm ERR!     /root/.npm/_logs/2019-03-28T20_42_28_845Z-debug.log
demo-app_demo-app_1 exited with code 1
```

This results from the `node_modules` entry within the `.dockerignore` file.

So my suggestion is to remove that. I don't know how else I can solve this problem.

Any thoughts on that?

**Comment by philliphoff** [comment]
@exocode I'd love to know more about what you were intending to do with this application within Docker (e.g. development, testing, deployment, etc.)

This is a case where the `Dockerfile` optimization `mv node_modules ../` actually causes the application to fail, as `npm` expects `react-scripts` to exist in `/usr/app/node_modules/.bin` but the `node_modules` folder has actually been moved to the parent directory.  The solution is to either remove the optimization or to update the Docker run command to point to the modified `react-scripts` path.

This is the second application (framework) I've come across that dislikes that optimization.  Given that, it would seem to raise the question of whether we should scaffold that optimization in the first place.  However, in the case of the other application that failed; Node.js applications *should* support the `node_modules` folder(s) being in the current application folder or any parent folder (by the import resolution rules of Node.js).  In that case, it was a long-known issue but one that did not appear to have any support for fixing.  Unless there's a strong call from the community for making that application (framework) work "out of the box" relative to other frameworks, there isn't a strong argument for removing the optimization (given the ease of the workarounds).

In this specific case, while it's certainly possible to run the application via the `react-scripts` from within a Docker container, I'd ask about the reason for doing so.  `react-scripts` is intended for "inner loop development and testing" of the application, setting up auto-reload and other development-time processes that don't really make sense (to me) to be running within a container that's divorced from the source itself.  Docker-izing such an application would generally involve creating a production build of the application (e.g. `yarn build`), then taking the output and inserting it into a Docker image that serves that, now static, content.  Given that, I don't think there's a strong argument here for removing that optimization either (given the ease of the workarounds).

If the ultimate intent is to try to develop a React application while minimizing the prerequisites on the local machine, this would be a good application of [VS Code's dev containers](https://code.visualstudio.com/docs/remote/containers).  In that scenario, all development occurs within the context of the Docker container, which has access to the source itself, so you can do "inner loop" development and test as if you were on your local machine.  Please note, however, that ultimately deploying a Docker-ized application would still require a `Dockerfile` that builds the application and inserts it into some static web server image.
