### ISSUE TITLE
Login in a docker Hub error

### ISSUE THREAD

**Issue by flegli** [microsoft/vscode-docker#873]
Repro steps:

1.
2.

Action: vscode-docker.dockerHubLogin
Error type: Error
Error Message: The user name or passphrase you entered is not correct.

Version: 0.6.1
OS: darwin
VS Code Version: 1.32.3

**Comment by eugenejeonme** [comment]
I try to the username, input email address. Been success.

**Comment by EricJizbaMSFT** [comment]
@flegli can you add repro steps to this issue? It seems like you just entered the wrong username or password
