### ISSUE TITLE
Error - command 'vscode-docker.configure' not found 

### ISSUE THREAD

**Issue by danielBrule** [Microsoft/vscode-docker#875]
Hello, 

I have the following for any of the docker command I try to execute: "Error - command 'vscode-docker.configure' not found"

I have followed the recommended steps on https://github.com/Microsoft/vscode-docker/issues/226 but still have the issue. 

OS: 
Windows server 2016 data center 

Version 
VSCode: 1.29.1 
Electron 2.0.12
Chrome: 61.0.3163.100
V8: 6.1.534.41
Node.js: 8.9.3
Architecture: x64

Docker: version 18.09.2, build 6247962

Thanks

**Comment by StephenWeatherford** [comment]
Weird.  Can you try going to %USERPROFILE%\{.vscode,.vscode-insiders}\extensions and delete the peterjausovec.vscode-docker-* folder(s), then restart vscode and try installing again?

**Comment by danielBrule** [comment]
I reinstalled vs code, deleted the file, and reinstall the extension. 

It works 

Thanks for your help

**Comment by StephenWeatherford** [comment]
Glad it's working, thanks for letting us know!
