### ISSUE TITLE
Please Add the Docker Extension to Azure Data Studio Marketplace

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/vscode-docker#877]
Issue Type: <b>Feature Request</b>

Please Add the Docker Extension to Azure Data Studio Marketplace.  I have been using this Docker extension in Azure Data Studio for over a month now and it works quite well.  I would love for it to be available to everyone in the Azure Data Studio Marketplace.  

Many data professionals are much more familiar with SSMS than they are VS Code, so they aren't aware they can just download the VS Code extension and manually add it to their Azure Data Studio themselves.

Here is the relevant information on how to [publish your extension](https://docs.microsoft.com/en-us/sql/azure-data-studio/extension-authoring?view=sql-server-2017#publish-an-extension) to the Azure Data Studio Marketplace.

Azure Data Studio version: azuredatastudio 1.6.0-insider (414c73665548145ab59b640c1b324639d191b9e6, 2019-04-02T07:31:32.984Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by StephenWeatherford** [comment]
Thanks for the tip, will definitely look into this!

**Comment by eugman** [comment]
This would be really convenient.

**Comment by yankyhoffman** [comment]
I use Azure Data Studio as my DB management tool on Ubuntu Linux and I have MS SQL Server and Posgres databases installed as docker containers and would really love to be able to start/stop/etc them from Azure Data Studio just like I can from VSCode.
(I find it a bit amuzing that the name from the extension has `azuretools` in it (`ms-azuretools.vscode-docker`) yet I can't get it to work in Azure Data Studio

**Comment by bwateratmsft** [comment]
This is not planned at this time. We'll reconsider if we get some more feedback.
