### ISSUE TITLE
harbor login

### ISSUE THREAD

**Issue by linkingtd** [Microsoft/vscode-docker#878]
Repro steps:

1.
2.

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.6.1
OS: darwin
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.connectCustomRegistry (dist/extension.bundle.js:157:513712)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
Moved to #869
