### ISSUE TITLE
Extension does not load in Azure Data Studio and older versions of VS Code

### ISSUE THREAD

**Issue by henrov** [Microsoft/vscode-docker#881]
The extension it is unusable.
It shows the docker logo in the side bar but clicking it gives a warning in the main window

_There is no data provider registered that can provide view data._

When clicking refresh it gives me an error:

_command 'vscode-docker.explorer.refresh' not found_

This is on the latest Windows 10 Pro (stable release). 
Azure Data Studio was downloaded and installed on 4-4-2019.
Extension was downloaded the same day.
Only Powershell extension is installed (from marketplace).

Azure Data Studio has been running for 20 hours as well as the extension as well as the docker-container.

**Comment by Annecao1** [comment]
I have the same experience.

**Comment by StephenWeatherford** [comment]
C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:48235/47b50c81-c4da-4163-b0ae-5265ad9a64b2
For help see https://nodejs.org/en/docs/inspector

C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension 'PeterJausovec.vscode-docker' failed: Invalid regular expression flags.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
log @ workbench.main.js:30511
ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:220059
(anonymous) @ workbench.main.js:219876
ZoneDelegate.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
ZoneDelegate.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
data.args.(anonymous function) @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Activating extension 'PeterJausovec.vscode-docker' failed: Invalid regular expression flags.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
ExtensionService._logMessageInConsole @ workbench.main.js:367080
ExtensionService._logOrShowMessage @ workbench.main.js:367095
MainThreadExtensionService.$localShowMessage @ workbench.main.js:367161
RPCProtocol._doInvokeHandler @ workbench.main.js:228327
RPCProtocol._invokeHandler @ workbench.main.js:228312
RPCProtocol._receiveRequest @ workbench.main.js:228244
RPCProtocol._receiveOneMessage @ workbench.main.js:228174
(anonymous) @ workbench.main.js:228053
Emitter.fire @ workbench.main.js:21573
acceptChunk @ workbench.main.js:33886
Protocol.Protocol.firstDataChunk._socketDataListener @ workbench.main.js:33912
ZoneDelegate.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension `PeterJausovec.vscode-docker` failed:  Invalid regular expression flags
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
log @ workbench.main.js:30511
ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:220059
(anonymous) @ workbench.main.js:219876
ZoneDelegate.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
ZoneDelegate.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
data.args.(anonymous function) @ C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
C:\Users\stephwe\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Here is the error stack:  C:\Users\stephwe\.azuredatastudio\extensions\peterjausovec.vscode-docker-0.6.2-alpha\dist\extension.bundle.js:441253
    const atMatch = result.match(/^\s*at\s.*/ms);
                                 ^

**Comment by StephenWeatherford** [comment]
#886

**Comment by PrashanthCorp** [comment]
There's a fix in place. It will land in the next release.

**Comment by StephenWeatherford** [comment]
It's not fixed yet...

**Comment by StephenWeatherford** [comment]
You wanna see why the PR is failing?
