### ISSUE TITLE
 Please log out of Docker Hub and then log in again.

### ISSUE THREAD

**Issue by denilen** [microsoft/vscode-docker#882]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.1
OS: darwin
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser (dist/extension.bundle.js:1:643184)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
@denilen I assume that logging out and back in worked, correct?  I'm assuming the login expired, and we don't currently support handling that directly.  Does it happen often?

**Comment by denilen** [comment]
Hello!
This happens every time I try to open registries in the docker plugin: explorer

**Comment by rafidwiriz** [comment]
> @denilen I assume that logging out and back in worked, correct? I'm assuming the login expired, and we don't currently support handling that directly. Does it happen often?

Hello, I have the same problem with @denilen, and I can tell you that `docker logout` and `docker login` had no effect at all.

**Comment by smirzo** [comment]
Right clicking on the Docker Hub folder path in the explorer reveals an option to "Log Out of Docker Hub". After clicking on that, an option to "Log In to Docker Hub" should appear under the same path.

_These commands are also available under the Command Palette (⇧⌘P), where typing `> docker hub` should show these options._

As @rafidwiriz points out, it is not immediately obvious from the error message how one should proceed to log out, and I would assume that for most people the first reaction is to do `docker logout`.
