### ISSUE TITLE
Order images by NAME

### ISSUE THREAD

**Issue by PureKrome** [microsoft/vscode-docker#883]
Currently, you can only GROUP images by 3 options.

Would be nice to add an ORDERING ability, also. 

For example, Order by A->Z, no grouping.

Currently, the names are not ordered by A->Z and sometimes (when you have lots of images) it's hard to find a specific image.

cheers!

**Comment by StephenWeatherford** [comment]
Good to know, thanks!  Do you like the current most-recent ordering when not grouping, or do you want to be able to set order that would apply to all grouping varieties?  Thx.

**Comment by PureKrome** [comment]
> Do you like the current most-recent ordering

nope - because until you just said that, then ... I didn't realise _how_ it was ordered. It was pretty .. messy/random ordering, to me.

> or do you want to be able to set order that would apply to all grouping varieties

🤔 hmm ...I definitely would like to be able to set the ordering to A->Z etc .. but "apply to all grouping varieties" .. hmm ... I would think so ..  yep. I think so, please.

---

Now here's a Sloth, for no particular reason but to make you smile (and sloths are awesome, like VS Code)

![](https://media.giphy.com/media/Qff97WxBLl2Bq/giphy.gif)

**Comment by EricJizbaMSFT** [comment]
Just merged #989 to support custom settings for images (including sort by label). @PureKrome if you've got the time, we'd appreciate your feedback! You can install the latest build from master with these instructions: https://aka.ms/azCodeInsiders

**Comment by PureKrome** [comment]
Loving it!

![image](https://user-images.githubusercontent.com/899878/59731136-57ef0300-9288-11e9-8ddc-90c050ea3516.png)

Thanks kindly for this!

I'm assuming that when this extensions goes from `alpha` to normal-public-release, VSCode will pick this up and update?

**Comment by EricJizbaMSFT** [comment]
> I'm assuming that when this extensions goes from alpha to normal-public-release, VSCode will pick this up and update?

@PureKrome fyi - we just released the official 0.7.0 update. It _should_ update automatically - but might be worth checking and uninstalling the old "alpha" if it's still there.

**Comment by PureKrome** [comment]
Noticed that I had:
- 0.6.3-alpha
- 0.6.4

both installed, so I
- uninstalled 0.6.3-alpha
- updated to 0.7.0

✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ 
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ 
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ 

Thank you again for the effort and ❤️ the new UI - very kewl!

cheers!!
