### ISSUE TITLE
dockerHubUtils handling errors: Cannot read map of undefined

### ISSUE THREAD

**Issue by jiawo** [microsoft/vscode-docker#885]
Repro steps:

1.
2.

Action: getChildren
Error type: TypeError
Error Message: Cannot read property 'map' of undefined

Version: 0.6.1
OS: win32
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>

```
RegistryRootNode.getDockerHubOrgs (dist/extension.bundle.js:262:1706387)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
dockerHubUtils isn't properly handling errors

**Comment by StephenWeatherford** [comment]
for version 0.6.2:
RegistryRootNode.getDockerHubOrgs extension.bundle.js:262:1712712
process._tickCallback next_tick.js:68:7
