### ISSUE TITLE
Unable to login to docker Hub

### ISSUE THREAD

**Issue by ChilliFog** [microsoft/vscode-docker#888]
Repro steps:

1.
2.

Action: vscode-docker.dockerHubLogin
Error type: EPROTO
Error Message: write EPROTO 4570453440:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../../vendor/node/deps/openssl/openssl/ssl/record/ssl3_record.c:252:

Version: 0.6.1
OS: darwin
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>

```
new n (dist/extension.bundle.js:157:636422)
$.callback (dist/extension.bundle.js:157:635108)
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:157:634554)
module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:187:5468)
$.emit (events.js:182:13)
$.module.exports.$.onRequestError (dist/extension.bundle.js:187:14523)
ClientRequest.emit (events.js:182:13)
onerror (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/agent-base/index.js:100:9)
callbackError (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/agent-base/index.js:122:5)
```

</details>

**Comment by StephenWeatherford** [comment]
I've never seen that one before. Do you get this every time?  Can you log in at the command line?  Thx.
