### ISSUE TITLE
nable to infer the application project file

### ISSUE THREAD

**Issue by dclinh** [microsoft/vscode-docker#889]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.1
OS: win32
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>a

```
DockerDebugConfigurationProvider.inferAppProject (dist/extension.bundle.js:263:45223)
```

</details>

**Comment by philliphoff** [comment]
@dclinh Can you provide any context for your issue?  Where is your project file in relation to the root folder opened in VS Code? The extension attempts to infer the location based on a the typical arrangement, but if not found, you simply have to add the `appFolder` or `appProject` properties to the debug configuration.
