### ISSUE TITLE
Display "manifest unknown" when running "Docker: Delete Azure Image" 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#891]
**OS:** Windows/Mac
**Build Version**: [20190410.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4881)

**Repro Steps:**
1. Create a new Azure Registry.
2. Push one image to this new registry.
3. Run "Docker: Delete Azure Image" in Command Palette from the new azure registry.
4. Check the result.

**Expect:**
Succeed to delete the image.

**Actual:**
Pop up an error "manifest unknown".
![image](https://user-images.githubusercontent.com/34729092/56024080-2542f000-5cc4-11e9-927c-857df89548c1.png)

**Comment by bwateratmsft** [comment]
@v-dantch Is this issue still occurring?

**Comment by v-dantch** [comment]
Hi @bwateratmsft , verified this issue on the latest build [20191008.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10961), and this issue does not reproduce. So we close it for now.
![image](https://user-images.githubusercontent.com/34729092/66473670-50b36580-eac2-11e9-80c0-84d8b846506b.png)
