### ISSUE TITLE
Pop up a warning after executing "Run Interactive" of "registry" image 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#892]
**OS**: Windows/Mac
**Build Version**: [20190410.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4881)

**Repro Steps**:
1. Run "docker pull registry" in terminal.
2. Right click this image and select "Run Interactive".
3. Check the result.

**Expect:**
No any warning list in "Terminal" window.

**Actual:**
Pop up a warning.
![image](https://user-images.githubusercontent.com/34729092/56025123-56bcbb00-5cc6-11e9-97e6-4fb7ee8d39d2.png)

**Comment by bwateratmsft** [comment]
@v-dantch Is this still an issue?

**Comment by v-dantch** [comment]
Hi @bwateratmsft , verified this issue on Win 10 & Mac with the latest build [20191008.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10961) and this issue also reproduces. 
![image](https://user-images.githubusercontent.com/34729092/66468685-29a46600-eab9-11e9-9675-a260ad1fdcd1.png)

**Comment by bwateratmsft** [comment]
Given that running the registry locally would only be a test scenario, and that it's only a warning, I'll resolve this as won't-fix.
