### ISSUE TITLE
not create Dockerfile

### ISSUE THREAD

**Issue by f0l1v31r4** [microsoft/vscode-docker#893]
Repro steps:

1.
2.

Action: vscode-docker.configure
Error type: Error
Error Message: command failed with error code 2: error parsing glob '!/"**/*.pyc": true': invalid use of **; must be one path component

Version: 0.6.1
OS: linux
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Object.t.deserializeSearchError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3951:333)
Promise.all.then.t (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4521:246)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
@f0l1v31r4 Thanks for reporting.  Could you please provide more info so we can try to reproduce?  Were you creating a Dockerfile for a Python project?  Does it always happen?  Can you try on another python project?  Thx.
