### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by albertofilho82** [Microsoft/vscode-docker#895]
Hi all...

Any command I try or even refresh explorer, I get the error "Command [...] not found" .

Docker up and running.
Other docker extensions working fine.

I've tried everything. Uninstall, reinstall, restart, close, reopen, reload.... 

Error:
<img width="553" alt="Captura de Tela 2019-04-13 às 16 46 34" src="https://user-images.githubusercontent.com/37080912/56084615-ba043580-5e0b-11e9-8406-8a1a96771c35.png">

Inspector:
<img width="1268" alt="Captura de Tela 2019-04-13 às 16 47 32" src="https://user-images.githubusercontent.com/37080912/56084621-ea4bd400-5e0b-11e9-89f1-5049844e9a4d.png">

VSCode 1.27.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true

Thanks!

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  We're working on the fix for this in #881.  In the meantime, could you consider updating to a more recent version of VS Code?  The bug only repros on older versions.  Thanks!
