### ISSUE TITLE
issue to synchronise  vs browser with debuger

### ISSUE THREAD

**Issue by jobran41** [microsoft/vscode-docker#896]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.1
OS: darwin
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject (dist/extension.bundle.js:263:45223)
```

</details>

**Comment by philliphoff** [comment]
@jobran41 Can you provide any context for your issue? Where is your project file in relation to the root folder opened in VS Code? The extension attempts to infer the location based on a the typical arrangement, but if not found, you simply have to add the `appFolder` or `appProject` properties to the debug configuration.
