### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by windNight** [microsoft/vscode-docker#898]
Repro steps:

1.
2.

Action: getChildren
Error type: ECONNRESET
Error Message: Client network socket disconnected before secure TLS connection was established

Version: 0.6.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
new n (dist/extension.bundle.js:157:636422)
$.callback (dist/extension.bundle.js:157:635108)
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:157:634554)
module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:187:5468)
$.emit (events.js:182:13)
$.module.exports.$.onRequestError (dist/extension.bundle.js:187:14523)
ClientRequest.emit (events.js:187:15)
TLSSocket.socketErrorListener (_http_client.js:382:9)
TLSSocket.emit (events.js:182:13)
emitErrorNT (internal/streams/destroy.js:82:8)
emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by EricJizbaMSFT** [comment]
@windNight please add repro steps to this issue

Also, https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders
