### ISSUE TITLE
Switch off request package

### ISSUE THREAD

**Issue by peterj** [microsoft/vscode-docker#9]
In order to work with proxies we should be using 'request' library in dockerHubApi

**Comment by BigMorty** [comment]
@peterj - Do you have additional info on this? Is there still something for us to do?

**Comment by peterj** [comment]
Oh wow, you pulled this issue out formaldehyde :) 

Since this was 4 years ago, I am just guessing, but what you could try is to check if the Docker hub search functionality works when you're running behind a proxy server.

**Comment by BigMorty** [comment]
Thanks Peter!

**Comment by bwateratmsft** [comment]
Related to #1648. Also, the request package is deprecated now, so we should look for a replacement.

**Comment by bwateratmsft** [comment]
Related to #1804.

**Comment by bwateratmsft** [comment]
Essentially blocked on #844

**Comment by bwateratmsft** [comment]
Gonna have to do this now to deal with changes upstream in `vscode-azureextensionui`.
