### ISSUE TITLE
Syntax highlighting ENV and ARG references

### ISSUE THREAD

**Issue by pn-santos** [Microsoft/vscode-docker#90]
It would be nice (if possible) to highlight the text associated with a Dockerfile's ENV and ARG references in a different color.

**Comment by rcjsuen** [comment]
Interestingly enough, if you select the `dockerfile` language on the [Monaco Editor website](https://microsoft.github.io/monaco-editor/index.html), the `ENV` variables are indeed getting highlighted. So the [Monaco Dockerfile grammar definition](https://github.com/Microsoft/monaco-languages/blob/e162b4ba29044167bc7181c42b3270fa8a467424/src/dockerfile.ts) is arguably a little bit better than the [TextMate Dockerfile grammar definition](https://github.com/Microsoft/vscode/blob/7e539de2f4a8872909a748cfe59f0dd1ea1ce0fc/extensions/docker/syntaxes/docker.tmLanguage.json).

**Comment by StephenWeatherford** [comment]
Closing for now due to lack of interest. If anybody thinks this would be very important to them, please let us know!  Thanks.

**Comment by rcjsuen** [comment]
If semantic highlighting gets added to the LSP I may be able to help with this. See Microsoft/language-server-protocol#513.
