### ISSUE TITLE
OAUth is NOT supported, only basic authentication

### ISSUE THREAD

**Issue by gauravlakhani** [Microsoft/vscode-docker#901]
Repro steps:

1. We are trying to connect to private DTR using AD username and password
2. DTR is configured on https using a certificate from CA.
3. Downloaded the cert and installed to trusted root CA, restarted VS code but getting this OAuth is not currently supported. Can you please provide a fix to this?

Action: vscode-docker.connectCustomRegistry
Error type: Error
Error Message: OAuth support has not yet been implemented in this preview feature.  This registry does not appear to support basic authentication.

Version: 0.6.1
OS: win32
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.connectCustomRegistry (dist/extension.bundle.js:157:513712)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by StephenWeatherford** [comment]
Thanks for the info. This is tracked by #869, you should upvote that one.
