### ISSUE TITLE
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.

### ISSUE THREAD

**Issue by ggprod** [microsoft/vscode-docker#905]
This extension is causing an error to occur when starting up the latest VS Code on Mac

The error: VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.

This disappears when the extension is removed and reappears when the extension is added.  This is with v0.6.1 of the extension and v1.33.1 of VS Code

**Comment by StephenWeatherford** [comment]
@ggprod Very weird. We're certainly not doing anything to vscode.  Have you tried uninstalling/reinstalling vscode?  Perhaps the error message is actually correct about vscode being messed up, but only shows during functionality used by the Docker extension.

@mjbvz since you dealt with https://github.com/Microsoft/vscode/issues/21689

**Comment by ggprod** [comment]
@StephenWeatherford It is several extensions (the Docker, several extensions by RedHat, Prettier - Code Formatter)

**Comment by ggprod** [comment]
seems like it may also be related to these issues:
https://github.com/Microsoft/vscode/issues/56329
https://github.com/VitalyKondratiev/vscode-sshextension/issues/9

**Comment by ggprod** [comment]
I logged this issue in the vscode github issues as well and another user that encountered it found a fix
see: https://github.com/Microsoft/vscode/issues/72721

**Comment by PrashanthCorp** [comment]
Looks like it's fixed.

**Comment by OmriSama** [comment]
Literally never saw this issue until today. I'm getting this on the latest Insider version on Windows using Remote SSH. Not sure where the issue is... but it's not totally gone

**Comment by EricJizbaMSFT** [comment]
@OmriSama this was a bug in VS Code, not this extension. I suggest taking a look at t https://github.com/microsoft/vscode/issues/72721 and https://github.com/microsoft/vscode/issues/71752. You can follow up with VS Code if you're still seeing the error
