### ISSUE TITLE
Cannot login to docker in vscode - command  line is fine  

### ISSUE THREAD

**Issue by jpr999** [microsoft/vscode-docker#910]
Repro steps:

1.run vscode  
2. sign in to docker hub via the extension - it always fails 
3. The command line is fine

Action: vscode-docker.dockerHubLogin
Error type: i
Error Message: {"detail":"Incorrect authentication credentials."}

Version: 0.6.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
new i (dist/extension.bundle.js:157:636651)
$.callback (dist/extension.bundle.js:157:635500)
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] (dist/extension.bundle.js:157:634554)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:187:5468)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:187:18281)
$.emit (events.js:182:13)
IncomingMessage.<anonymous> (dist/extension.bundle.js:187:17123)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by PrashanthCorp** [comment]
It looks like the username or password is wrong. Can you check again, using the same username and password you'd use to log in via the web browser?
