### ISSUE TITLE
docker-compose may not see .env file

### ISSUE THREAD

**Issue by carldunham** [microsoft/vscode-docker#913]
If I have a docker-compose.yml below the root of the workspace/folder, it is found nicely by Docker: Compose Up, but the .env file in the same sub-folder is not recognized. It would be nice if it was, probably by running in the same sub-directory.

By the way, https://github.com/docker/compose/issues/6170 would give a nice way to pair docker-compose definition and environment, but it has been deemed unnecessary for some reason.

Edit: https://github.com/docker/compose/pull/6535 has been merged to add that flag, so it should be available in some future version.

**Comment by bwateratmsft** [comment]
With [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) it's possible to fully customize the Compose Up/Down commands; I think that is the right solution to address this.
