### ISSUE TITLE
Cannot access Docker Hub

### ISSUE THREAD

**Issue by xinxiao** [microsoft/vscode-docker#916]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.1
OS: darwin
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser (dist/extension.bundle.js:1:643184)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by PrashanthCorp** [comment]
Please provide repro steps

**Comment by xinxiao** [comment]
This error appears every time I try to click the 

> Registry > Docker Hub

 button

**Comment by StephenWeatherford** [comment]
Have you tried logging out and logged back in as it requests?
![image](https://user-images.githubusercontent.com/6913354/58349785-100bc600-7e19-11e9-98c0-ee74d1b47ee3.png)

**Comment by StephenWeatherford** [comment]
#935
