### ISSUE TITLE
browse to containers step gives 401 error

### ISSUE THREAD

**Issue by wbsnipes** [microsoft/vscode-docker#919]
Repro steps:

1.In Docker explorer, after you have successfully pushed a container to an ACR following this guide: https://code.visualstudio.com/docs/python/tutorial-deploy-containers
2. Click on the ACR that you have pushed the container to Get the 401 error. 
3. Verified via Azure portal that the container was in the registry (by deploying as an app service)

Action: getChildren
Error type: 401
Error Message: 401 - undefined

Version: 0.6.2
OS: linux
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:157:643505
$.callback extension.bundle.js:157:642354
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:187:18281
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:187:17123
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by PrashanthCorp** [comment]
Can you verify that you were signed in to Azure when you saw this error? Can you verify what your access privileges to that ACR registry are? 

A 401 error is usually sent when there's unauthorized access.

**Comment by wbsnipes** [comment]
I was able to successfully complete the steps after installing the Azure CLI and logging into Azure.  I'll go ahead and close the issue now.  Thanks for your help!
