### ISSUE TITLE
Support Dockerfile with arbitrary names for Docker build

### ISSUE THREAD

**Issue by SajayAntony** [Microsoft/vscode-docker#92]
Currently docker build command cannot use a Dockerfile that does not have `Dockerfile` as the name even if the user specifies it fully. 

![image](https://user-images.githubusercontent.com/1821104/26946567-9f2767da-4c44-11e7-9bfa-4a788e78d161.png)

**Comment by lostintangent** [comment]
@SajayAntony Ah yeah that's a good catch. Thanks for reporting this! We can definitely update the build command to detect arbitrary suffixes on Dockerfiles (which we already do in other places).

**Comment by chrisdias** [comment]
hmmm... what version do you have?  this works for me.

![image](https://user-images.githubusercontent.com/1487073/26947332-34ec7d9e-4c47-11e7-9ba2-06be9574d150.png)

We made a fix for this a while back https://github.com/Microsoft/vscode-docker/commit/f7c8ecfb43e9a83b647004a401fc1e331e5048b3

**Comment by SajayAntony** [comment]
Ahh .. it was an extension update issue. 
Thanks for checking - 

![image](https://user-images.githubusercontent.com/1821104/26947707-81582402-4c48-11e7-8d07-f52d7920ecab.png)

**Comment by SajayAntony** [comment]
@chrisdias
Is there any for the docker build command against the same file to remember the last tag that it built with so that the users don't have to types in the tag every time if its different?

**Comment by chrisdias** [comment]
no, can you open a new issue for this, describing exactly the behavior you would like to see?

**Comment by SajayAntony** [comment]
Ok i've opened #93
