### ISSUE TITLE
Connect to remote docker daemon when using "Remote - SSH" extension

### ISSUE THREAD

**Issue by pd93** [microsoft/vscode-docker#924]
**The `Remote - SSH` extension**

This week, [the Remote Development pack was released to Insiders](https://code.visualstudio.com/blogs/2019/05/02/remote-development). This allows you to open up a VSCode window as if it were running on the remote host. I have been using the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension to connect to a server and it works beautifully.

**Expected `vscode-docker` behaviour**

When I install the `vscode-docker` extension, it should be installed to the **remote** VSCode installation.  
When opening a remote (SSH) vscode session, `vscode-docker` should list images/containers from the docker daemon on the **remote** host.

**Actual `vscode-docker` behaviour**

The extension is installed **locally** and lists my **local** containers/images.

**Summary**

It would be fantastic if these two extensions could work together so that I can view my remote docker container/images while I'm developing remotely over SSH and my local ones when working locally.

I don't think this effects the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) and [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extensions as developers tend to use the local Docker daemon in these environment anyway (either via opening TCP port 2375 or by using some form of DinD).

Potentially related to #216 & #646.

**Comment by PabloSzx** [comment]
This feature would be amazing, and the most strange behavior is that this extension is the only extension (at least that i could found) that installing on ssh is disabled, it only allows to install locally.

**Comment by aruiz14** [comment]
My expectations were also that it would use the docker socket in the remote, but it didn't work like that.

I managed to make it work with this workaround:
 - In your `~/.ssh/config`, you can add to the section of the host you are connecting to the line (the actual port used is irrelevant, you can use a different one as long as it's not in use):

```
LocalForward 22375 /var/run/docker.sock
```

 - Then, while connected to the remote host, go to `Settings`, select the tab for the remote host and change the `Docker Host` config to `localhost:22375`.

You may need to reconnect to the host or restart VSCode for this to take effect.

**Comment by pd93** [comment]
Done some further reading on this.

Firstly, this is [addressed in the README](https://github.com/microsoft/vscode-docker#workaround-for-vs-code-remote-development) which I hadn't noticed when I opened the issue. However, all it says about SSH is:

> In SSH, the setup for docker is dependent on the machine environment.

I've also found the [document about remote development for extension authors](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). It looks like adding:
```json
"extensionKind": "workspace",
```
in the `package.json` file will force the extension to be recognised as a workspace extension. However, I can't confirm if this works or not because I can't get the extension to build over Remote SSH :')

**Comment by pd93** [comment]
@PabloSzx's workaround fixes the problem for me on "Remote - SSH" sessions, but unfortunately it also breaks "Remote - WSL". (probably a separate issue). A slight improvement on this would be to force the docker extension to be installed on SSH sessions only:

```json
    "remote.SSH.defaultExtensions": [
        "peterjausovec.vscode-docker"
    ]
```

Unfortunately, this does mean my previous suggestion of setting `"extensionKind"` in the `package.json` might break the extension when running via "Remote - WSL" and "Remote - Container"?

**Comment by SuperSandro2000** [comment]
@pd93 it wouldn't matter if it does not work in remote wsl or docker cause you can't run docker on wsl or in a container. It only needs to function for remote ssh and then forward the data to the client vscode

**Comment by EricJizbaMSFT** [comment]
@pd93 and others thanks for your comments on this! We've discussed this in the past and it's not a simple thing to pick the default behavior for the docker extension in VS Code remote scenarios. I'm going to close this issue in favor of https://github.com/microsoft/vscode-docker/issues/954 because this felt specific to SSH and I wanted a new issue that summarized our past discussions, your comments, the current workaround, etc. for all three scenarios (SSH, WSL, and Dev Containers). Feel free to add your opinion to the new issue!
