### ISSUE TITLE
Enable Docker build to keep history of the image:tag that the user has specified for a Dockerfile

### ISSUE THREAD

**Issue by sajayantony** [Microsoft/vscode-docker#93]
Users currently have to retype the tag specified during build if the tag is not of the form `{folder}:latest`. 
Enabling a history of the tags currently built for a file would enable the user to simply rebuild the docker file without having to retype this over again .. 

For e.g. If the user runs docker build with a image:tag as shown below the expectation is that the extension remembers this 😀 
![image](https://user-images.githubusercontent.com/1821104/26948115-147c62b0-4c4a-11e7-85ff-d4d27164b6d7.png)

As part of the dev inner loop it would nice if rebuild can keep history of tag instead of the default -> Also might be worth considering deriving the tag from the file extension. 

![image](https://user-images.githubusercontent.com/1821104/26948171-485ab56e-4c4a-11e7-9367-e6ccd1b5d730.png)

**Comment by lostintangent** [comment]
I like this suggestion!

**Comment by jgainfort** [comment]
Another suggestion that is similar to this is to add **--rm** to the build command to remove intermediate and none images after a successful build. Reason is current docker build command using the same tag name pushes the previous tag to have a tag of <none>.

**Comment by chrisdias** [comment]
@jgainfort i created https://github.com/Microsoft/vscode-docker/issues/111

PRs much appreciate everywhere!

**Comment by StephenWeatherford** [comment]
@sajayantony We currently show the last-used tag as the default value when you go to build.  I assume this takes care of this issue, right?

**Comment by sajayantony** [comment]
Yep it retains the tag information.
