### ISSUE TITLE
Error when trying to view Docker Hub or Private Registries sections

### ISSUE THREAD

**Issue by xandermar** [microsoft/vscode-docker#930]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @xandermar,

Sorry that you're having issues.  Based on the error message, it seems like it's an issue with Docker Hub.  Have you tried logging out and then logging back in?
