### ISSUE TITLE
TODO: Enter steps to reproduce issue

### ISSUE THREAD

**Issue by stev02** [microsoft/vscode-docker#931]
### 

> `*<!--**` IMPORTANT: Please be sure to remove any private information before submitting. -->

Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.6.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:263:42448
Object.module.exports.resolveDebugConfiguration.i.callWithTelemetryAndErrorHandling extension.bundle.js:263:42268
Object.<anonymous> extension.bundle.js:1:394554
module.exports.n extension.bundle.js:1:392892
new module.exports.t.exports extension.js:1:120797
module.exports.n extension.bundle.js:1:392669
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394471
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:263:42199
v.<anonymous> extensionHostProcess.js:502:886
s extensionHostProcess.js:11:9
i extension.js:1:101648
extension.js:1:101992
```

</details>

**Comment by philliphoff** [comment]
@stev02 Can you provide a little more context?  For example, it would help to know what your project structure looks like in order to determine where we should be looking to infer project data?

**Comment by stev02** [comment]
ok thank you Mr Phillip hoff for all you said i'm a beginner programmer
and i want to get better

Le mar. 21 mai 2019 à 18:16, Phillip Hoff <notifications@github.com> a
écrit :

**Comment by stev02** [comment]
Hi microsoft/vscode-docker,

Please join me on WowApp to connect, share and get rewarded!
Check out my personal page to create your free account:
https://www.wowapp.com/w/stev02/Stev-hack-Tekou

Contact me if you have any questions!

Meet you on WowApp,
Stev hack

WowApp is available on iOS, Android, Windows and Mac. Learn more on
www.wowapp.com

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!
