### ISSUE TITLE
vscode-docker

### ISSUE THREAD

**Issue by Lade007** [microsoft/vscode-docker#932]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.32.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644889
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment]
Can you add some repro steps? we'd like to get an idea of the scenario you're trying out.

**Comment by StephenWeatherford** [comment]
#935
