### ISSUE TITLE
Missing null check?

### ISSUE THREAD

**Issue by pushqrdx** [microsoft/vscode-docker#933]
Repro steps:

1. Opened Registeries > Docker Hub
2.Kept loading and ended up with this.

Action: getChildren
Error type: TypeError
Error Message: Cannot read property 'map' of undefined

Version: 0.6.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistryRootNode.getDockerHubOrgs extension.bundle.js:262:1712712
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by StephenWeatherford** [comment]
@pushqrdx Thanks for reporting!  Being tracked in #885

**Comment by pushqrdx** [comment]
thanks, i am gonna close this one then
