### ISSUE TITLE
winlet.UWP

### ISSUE THREAD

**Issue by Infraton11** [microsoft/vscode-docker#934]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:263:45299
```

</details>

**Comment by Infraton11** [comment]
inlude_result

**Comment by StephenWeatherford** [comment]
Could you describe your workspace/project workout so we can better understand how to make this work for more customers?  Thx.
