### ISSUE TITLE
We should better handle expired credentials for Docker Hub

### ISSUE THREAD

**Issue by Dhwanil20** [microsoft/vscode-docker#935]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.34.20-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by StephenWeatherford** [comment]
@Dhwanil20 Thanks for reporting. It would be nice if we handled this better.  Can you verify that logging out (via right-clicking on the Docker Hub node) and logging back in does work?  Thx.

**Comment by Dhwanil20** [comment]
@StephenWeatherford Hello, it's Click On Docker Hub After Getting Error And Also Today i have not start docker and i have open Vs Code after same Error Occur Please check That's

**Comment by StephenWeatherford** [comment]
We're saving credentials that have expired, did you try this?

> Can you verify that logging out (via right-clicking on the Docker Hub node) and logging back in does work? Thx.
![image](https://user-images.githubusercontent.com/6913354/58203261-8f20c300-7c8e-11e9-8dee-fe0f9064605a.png)
