### ISSUE TITLE
Update 'Sign in to Azure...' to 'Sign In to Azure...'

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#936]
**OS**: Windows
**Extension Version**: [20190513.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5945)

**Steps to reproduce:**
1. Make sure you haven't signed in.
2. Drill down from 'Registry' -> 'Azure'.
3. Check the shown message link under 'Azure' node.

**Expect Experience:**
There shows 'Sign **in** to Azure...'

**Actual Experience:**
There shows 'Sign **In** to Azure...'.
![image](https://user-images.githubusercontent.com/34729022/57665574-39268e00-75b1-11e9-94d4-d02087875e90.png)

**Comment by StephenWeatherford** [comment]
Suggestion is correct, see https://vsuiguide.azurewebsites.net/topics/02%20Fonts%20and%20Formatting/02.02%20Text%20style.html for title casing:
Prepositions that are part of a verb phrase — like Closing Out All Windows or Shutting Down the System
