### ISSUE TITLE
Fail to debug a new .NET Core ASP.NET application

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#938]
**OS**: Windows
**Extension Version:** [20190513.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5945)

**Steps to reproduce:**
1. Make sure the Docker Desktop, .NET Core SDK(2.0 or later), c# extension are installed.
2. Switch to Linux Container.
3. Create a new .NET Core ASP.NET application by  'dotnet new web --name test'.
4. Open this application folder in VS Code.
5. Add Docker files to workspace.
6. Add .NET Core debug launch task.
7. Debug this application.

**Expect Experience:**

Succeed to debug this application without any errors.

**Actual Experience:**

Fail to debug this application with the below error.
![image](https://user-images.githubusercontent.com/34729022/57687070-9ccfac00-75ef-11e9-815f-cc54a10c46a5.png)

**Comment by bwateratmsft** [comment]
External issue with the 1806 Docker CLI.
