### ISSUE TITLE
support "exclude" setting when searching for Dockerfiles to build

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#94]
for example, don't look in `node_modules`.

could look at using the `.dockerignore` file, but have to figure out which entries are folders vs. files, because the default `.dockeringore` file lists `Dockerfile`... which we want.

**Comment by dewdad** [comment]
For instance the docker compose command shows me all the history (local history extension) archived versions for my docker-compose.yml even though its excluded in the settings.

**Comment by StephenWeatherford** [comment]
We've added the ability to show the most recently used Dockerfile first in the dropdown so you just have to press ENTER to select it again.  Given that there also probably won't be a large number of Dockerfiles in the workspace, it seems like this feature isn't very important.  Thanks!
