### ISSUE TITLE
Feature request: Display column with abbreviated sha256 id for containers and images

### ISSUE THREAD

**Issue by marvingreenberg** [microsoft/vscode-docker#940]
Minor feature.  It would be nice if there were an easy way to see/get the id's associated with images and containers.  When doing commands in other windows, comparing the results or running commands, the id's are always evident.   The image IDs can be found by looking via "Inspect Image" and the container IDs can be found by looking at the commands used to, e.g., attach a shell.  But, my personal preference is to just be able to see the IDs, since various other commands I'm running using will be displaying them.  I also prefer using IDs to the generated container names since it is much easier to type 'ae28' than 'elongated_elastomeer' or whatever.

Modest proposal:  A setting

    docker.showContainerIdentifier: [ "hash", "name", "none"]
    docker.showImageIdentifier: ["hash", "none"]

BTW, fantastic, indispensable extension.

As a simpler alternative, just add a right-click action to "Copy id" to get the hash for images and containers.

**Comment by PrashanthCorp** [comment]
Hey @marvingreenberg , thanks for the feedback! 
The copy id is a great idea, we'll try that approach.

**Comment by EricJizbaMSFT** [comment]
Just merged #989 to support custom settings for images (including image id). @marvingreenberg if you've got the time, we'd appreciate your feedback! You can install the latest build from master with these instructions: https://aka.ms/azCodeInsiders
