### ISSUE TITLE
There are no docker images. Try Docker Build first.

### ISSUE THREAD

**Issue by EliBaron** [microsoft/vscode-docker#941]
Repro steps:

1.
2.

Action: vscode-docker.container.start
Error type: Error
Error Message: There are no docker images. Try Docker Build first.

Version: 0.6.2
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.34.20-insider
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.quickPickImage extension.bundle.js:1:421717
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@EliBaron please add repro steps and your desired behavior
