### ISSUE TITLE
Unknown or unsupported transport disabled

### ISSUE THREAD

**Issue by rmagruder** [microsoft/vscode-docker#945]
Repro steps

1.Click on the Docker Extension icon on the left side of VS Code on Linux in a Chromebook.

Action: getChildren
Error type: Error
Error Message: Unknown or unsupported transport 'disabled' for address 'disabled:'

Version: 0.6.2
OS: linux
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

**Comment by StephenWeatherford** [comment]
@rmagruder A quick search seems to imply that you need to install gnome-keyring for use by keytar:

https://github.com/vladimiry/ElectronMail/issues/57
https://github.com/atom/node-keytar/issues/132#issuecomment-428976389

There is an open [feature request ](https://github.com/microsoft/vscode-docker/issues/722) to not require gnome-keyring (but that would mean not storing credentials between sessions).
