### ISSUE TITLE
Docker Hub error on open

### ISSUE THREAD

**Issue by ilinojkovic** [microsoft/vscode-docker#947]
Repro steps:
1. Go to Docker tab -> Registries -> Docker Hub
2. When Docker Hub is clicker the error is prompted

Action: getChildren
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.6.2
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.35.0-insider
Language: en

**Comment by PrashanthCorp** [comment]
What distro are you running on? 

This error looks like there's a problem accessing the keyvault equivalent for your distro/Desktop Environment

**Comment by ilinojkovic** [comment]
Thanks for the response @PrashanthCorp. I'm using Manjaro KDE.

**Comment by PrashanthCorp** [comment]
Are you using kde wallet?

**Comment by ilinojkovic** [comment]
No

**Comment by PrashanthCorp** [comment]
What password manager ()like gnome keyring, kde wallet, etc.) do you use?

**Comment by ilinojkovic** [comment]
So there's KDE Wallet installed by default on my machine, but I don't use it, nor have I opened it once.

**Comment by bwateratmsft** [comment]
Duping this one over to #1296
