### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by DEVfancybear** [microsoft/vscode-docker#949]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: No workspace folder is associated with debugging.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.resolveDockerDebugConfiguration extension.bundle.js:263:42448
Object.module.exports.resolveDebugConfiguration.i.callWithTelemetryAndErrorHandling extension.bundle.js:263:42268
Object.<anonymous> extension.bundle.js:1:394554
module.exports.n extension.bundle.js:1:392892
module.exports.n extension.bundle.js:1:392669
Object.module.exports.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:394471
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:263:42199
v.<anonymous> extensionHostProcess.js:604:161
s extensionHostProcess.js:13:221
```

</details>

**Comment by philliphoff** [comment]
@DEVfancybear Can you provide a little more context?  For example, it would help to know what your project structure looks like in order to determine where we should be looking to infer project data?
