### ISSUE TITLE
Docker Off And I have Open Visual Studio Code. It's Occur Error

### ISSUE THREAD

**Issue by Dhwanil20** [microsoft/vscode-docker#951]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.35.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment]
Can you please add some repro steps?

**Comment by StephenWeatherford** [comment]
#935
