### ISSUE TITLE
Unable to Deploy the docker image to Azure App Service

### ISSUE THREAD

**Issue by bilgrami** [microsoft/vscode-docker#955]
Repro steps:

1.
2.

Action: vscode-docker.createWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457extension.js:229:171457
extension.js:229:43512extension.js:229:43512
extension.js:229:41505extension.js:229:41505
extension.js:229:41127extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
