### ISSUE TITLE
Extension: Docker not working 

### ISSUE THREAD

**Issue by Agos88** [microsoft/vscode-docker#956]
Repro steps:

1. Log In to Docker Hub using VS Code extension
2. Insert Docker ID
3. Insert Docker Password

Action: vscode-docker.dockerHubLogin
Error type: EPROTO
Error Message: write EPROTO 52156:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:d:\_vsts\3\s\vendor\node\deps\openssl\openssl\ssl\record\ssl3_record.c:252:

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:157:643276
$.callback extension.bundle.js:157:641962
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.module.exports.$.onRequestError extension.bundle.js:187:14523
ClientRequest.emit events.js:182:13
TLSSocket.socketErrorListener _http_client.js:382:9
TLSSocket.emit events.js:182:13
onwriteError _stream_writable.js:431:12
onwrite _stream_writable.js:456:5
_destroy destroy.js:40:7
TLSSocket.Socket._destroy net.js:603:3
TLSSocket.destroy destroy.js:32:8
WriteWrap.afterWrite [as oncomplete] net.js:835:10
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Agos88 does this consistently happen for you? Does your machine have any unique setup? Like are you behind a corporate proxy?

https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders
