### ISSUE TITLE
Connect to private repository Ubuntu 18.04

### ISSUE THREAD

**Issue by ixomaxip** [microsoft/vscode-docker#957]
Repro steps:

1. In docker explorer: select  Private Registries -> Connect to a private registry...

2. Enter a url like this http://host.name.org:5000
![image](https://user-images.githubusercontent.com/38070796/58249328-02eaca80-7d78-11e9-87f1-f06d3b6af008.png)

3. Enter a user name and password that is used to connect by docker login
![image](https://user-images.githubusercontent.com/38070796/58249246-c4551000-7d77-11e9-9c44-fe1015e33a2e.png)

Action: vscode-docker.connectCustomRegistry
Error type: HPE_INVALID_CONSTANT
Error Message: Parse Error

Version: 0.6.2
OS: linux
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:157:643276
$.callback extension.bundle.js:157:641962
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.module.exports.$.onRequestError extension.bundle.js:187:14523
ClientRequest.emit events.js:187:15
Socket.socketOnData _http_client.js:438:9
Socket.emit events.js:182:13
addChunk _stream_readable.js:279:12
readableAddChunk _stream_readable.js:264:11
Socket.Readable.push _stream_readable.js:219:10
TCP.onread net.js:636:20
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ixomaxip what kind of registry were you trying to connect to? We're tracking OAuth support here: https://github.com/microsoft/vscode-docker/issues/869

Also - https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders

**Comment by ixomaxip** [comment]
Just ordinary registry https://docs.docker.com/registry/
Without certificates

**Comment by EricJizbaMSFT** [comment]
@ixomaxip there are a lot of different types of registries. Was it Docker Hub, Azure, quay.io, ECR, GCR, etc.? Or a local registry?

Did you add "https://" or "http://" to the beginning of the url?
