### ISSUE TITLE
VS code won't recognise docker login to allow listing of private regs

### ISSUE THREAD

**Issue by dataismus** [microsoft/vscode-docker#958]
Repro steps:

1.
2.

Action: getChildren
Error type: Error
Error Message: Docker: Please log out of Docker Hub and then log in again.

Version: 0.6.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.getUser extension.bundle.js:1:644951
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment]
@dataismus please add repro steps for this issue
