### ISSUE TITLE
Excessive Docker polling

### ISSUE THREAD

**Issue by jeff-h** [microsoft/vscode-docker#959]
Issue Type: <b>Performance Issue</b>

VS Code version: Code - Insiders 1.35.0-insider (955afd60a5e4177d1fdf1c3a4a02dc4e0ca7d781, 2019-05-22T18:03:07.494Z)
OS version: Darwin x64 18.6.0
- Remote Extension/Connection Type:Docker

Running macOS, with Docker for Mac CE 18.06.

When clicking around inside the Docker sidebar, VSCode appears to start polling Docker for the data it is displaying — I noticed in Console.app that (I think) this is polling `/containers/json` and `images/json`.

Unfortunately each of these is polled once per second, for each kind of information, for every window you might have used the Docker sidebar in, resulting in multiple polls per second if you view enough data in the Docker sidebar. 

Even worse, the polling continues even when you exit the Docker sidebar. In my case this often results in Docker using 50% CPU even with no containers running.

Is this unique to my setup perhaps? Happy to provide further info if I can.

**Comment by EricJizbaMSFT** [comment]
@jeff-h as a workaround you can adjust the VS Code setting `docker.explorerRefreshInterval`, which defaults to 1 second.

I'll leave this issue open, though, because it feels like we might be able to stop polling if the Docker sidebar isn't open.

**Comment by jeff-h** [comment]
I'll give that a try, thanks! However, stopping the polling when the sidebar isn't open would be much better.
