### ISSUE TITLE
Provide a VSIX file for download.

### ISSUE THREAD

**Issue by BaadDaad** [Microsoft/vscode-docker#96]
Would it be possible to provide the latest version as a VSIX file for download and installation on a machine that doesn't have access to the VSCode Marketplace?

Thanks.

**Comment by chrisdias** [comment]
Sure. In the meantime, you can clone, build, and install the extension locally:

``` bash
npm install -g vsce
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install
vsce package
code --install-extension vscode-docker-0.0.14.vsix   # make sure version is correct
```

**Comment by BaadDaad** [comment]
Thanks.
