### ISSUE TITLE
Directory paths formatted incorrectly on WSL

### ISSUE THREAD

**Issue by eli-kaplan** [microsoft/vscode-docker#960]
Running latest version of VS Code Insiders, and using WSL as a "remote" environment. When running docker-compose through the plugin (i.e. by pressing `Ctrl + Shift + P` then selecting `Docker: Compose Up` (or `Down`), the plugin tries to change directory to the absolute path to the working directory before running `docker-compose`,  as such:

`cd "\mnt\c\Repos\....\....."`
`docker-compose -f "docker-compose.yml" up -d --build`

The path itself is correct, but on WSL, paths must use forward slashes, not backslashes. The `cd` command thus fails with `No such file or directory`. When the project working directory is the same as the location of the `docker-compose.yml` file, the `Compose Up` / `Compose Down` commands still run fine, but I suspect if the file were to be located outside of the project working directory, the commands would fail.

**Comment by EricJizbaMSFT** [comment]
@eliplan312 by default the Docker extension is currently running as a UI extension, which means it's running in the local environment. We're debating the best default behavior (see https://github.com/microsoft/vscode-docker/issues/954), but you could try switching to a Workspace extension (which means it'll run in the remote environment, aka WSL) by adding this to your settings:

```
"remote.extensionKind": {
    "peterjausovec.vscode-docker": "workspace"
}
```

That will probably have other effects, which you may or may not like. Would love to hear your preference on running as a UI vs. Workspace extension

**Comment by bwateratmsft** [comment]
Hey @eli-kaplan , now that the Docker extension behaves as a workspace extension by default, is this issue still occurring?
