### ISSUE TITLE
docker hub login

### ISSUE THREAD

**Issue by zaier75** [microsoft/vscode-docker#961]
Repro steps:

1.
2.

Action: vscode-docker.dockerHubLogin
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.32.1
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:157:643276
$.callback extension.bundle.js:157:641962
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.module.exports.$.onRequestError extension.bundle.js:187:14523
ClientRequest.emit events.js:187:15
TLSSocket.socketErrorListener _http_client.js:382:9
TLSSocket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@zaier75 can you add repro steps to this issue? Also try updating VS Code as they improved extension support for proxies in this release: https://code.visualstudio.com/updates/v1_33#_network-proxy-support-for-extensions
