### ISSUE TITLE
Setting "docker.host" description is misleading

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-docker#962]
Testing https://github.com/microsoft/vscode-remote-release/issues/474

The `docker.host` setting has the following description:

> Full host address to connect to (with protocol). Equivalent to setting the DOCKER_HOST environment variable

This is misleading, as reported by @benad in https://github.com/microsoft/vscode-docker/issues/580#issuecomment-494921010.

It just doesn't work:

![image](https://user-images.githubusercontent.com/22350/58546355-73c13500-8205-11e9-9c44-54bb012e7698.png)

It works once I remove the `tcp://` prefix.

---

Either fix the description or, better yet, handle the prefix correctly.

**Comment by wizcas** [comment]
I doesn't works for me even if I removed the `tcp://` prefix

**Comment by EricJizbaMSFT** [comment]
@joaomoreno @wizcas this should now work with or without "tcp://". Feel free to try the latest build from master with these instructions: https://aka.ms/azCodeInsiders
