### ISSUE TITLE
Can't connect to Docker after opening a folder/workspace (Docker Toolbox)

### ISSUE THREAD

**Issue by wizcas** [microsoft/vscode-docker#964]
> Environment: 
> Windows 10 Pro 1809 17763.503
> Docker Toolbox with Docker 18.09.3

The extension on my machine works fine on a clean startup, i.e. in an empty workspace. It looks as below:

![image](https://user-images.githubusercontent.com/2867434/58848425-250a1400-86b9-11e9-9056-b3af6f4ee8b1.png)

But **once I open a folder or a workspace and the window reloaded**, the connection won't establish anymore with error:

![image](https://user-images.githubusercontent.com/2867434/58848459-4ec33b00-86b9-11e9-8067-0c38131a2f46.png)

I have the `DOCKER_HOST` environment variable in my system setting as `tcp://192.168.99.100:2376`, and I tried to set `docker.host` to both `tcp://192.168.99.100:2376` and `192.168.99.100:2376` (which was mentioned in another issue saying removing the protocol makes the extension works). None of them works.

Another weird thing is that, the `start.sh` script provided by Docker Toolbox can't work in VSCode terminal after loading folder/workspace as well, which works fine on startup. It shows an error that 'Docker Machine is not installed, which seems being caused by `DOCKER_TOOLBOX_INSTALL_PATH` not correctly read.

Is there any log or more information I can provide to figure out how this problem happens?

**Comment by wizcas** [comment]
Here're more experiments which might lead to easier problem locating:

The extension cannot connect to docker **after VS Code reloaded**. So there is nothing to do with if there's a folder/workspace loaded, as long as VS Code doesn't reload after startup.

I tried to run `code /foo/bar/work` in terminal and the docker extension works super good with my the folder open. Then I selected `Files->Open a folder->some other folder`, VS Code reloads, and docker connection is down again as expected.

**Comment by EricJizbaMSFT** [comment]
@wizcas there's a lot of discussion in VS Code about how and when process environment variables should be inherited. I'm guessing VS Code is properly inheriting DOCKER_HOST (or some other env var) when you open it the first time, but not after reloading the window. Here's one example issue: https://github.com/microsoft/vscode/issues/15452 Suffice it to say I'm not entirely caught up on all of their design choices/reasoning in this area and you're welcome to poke around in their repo.

In terms of the "docker.host" setting - that is something we can control directly from this extension. We're aware there's issues here and we want to improve this. Take a look at this for an example: https://github.com/microsoft/vscode-docker/issues/216 (or any issue labeled with "DOCKER_HOST"). I don't have an easy workaround for you at the moment, but we're looking into it

**Comment by wizcas** [comment]
@EricJizbaMSFT Thank you for you reply. Good to know the problems are spotted. Hopefully there will be a fix in not far future :)
