### ISSUE TITLE
Docker Extension in VS Code can not get the list of pushed image from Azure Registry?

### ISSUE THREAD

**Issue by Dezleung** [microsoft/vscode-docker#971]
Repro steps:

1. Create Azure Registry Group - OK
2. Add Azure Container Registry to the Group - OK
3. Push a image to the Azure Registry from VS Code - OK
4. The pushed image can not be shown under the Azure Registry within the VS Code.
Error from the VS docker Extension: 401 - Undefined Source: Docker (Extension)

Action: getChildren
Error type: 401
Error Message: 401 - undefined

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:157:643505
$.callback extension.bundle.js:157:642354
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:187:18281
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:187:17123
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Dezleung does this consistently repro? Or does this error go away if you refresh a little while later?

https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders

**Comment by Dezleung** [comment]
@EricJizbaMSFT  Thanks Eric for the response.

It is consistent. I can push a docker image thru to ACR, but it can not be viewed in the tree. 
[Tried] the latest build #975 (nice GUI make over). Problem persists with Error: 401 - undefined.

But I can view it using Azure CLI or via the Portal

NOTES: Wired that I tried using Azure concierge subscription with a Registry Group (created automatically by Tutorial).  This Registry works fine and pushed images are shown in the tree.

**Comment by EricJizbaMSFT** [comment]
> Wired that I tried using Azure concierge subscription with a Registry Group (created automatically by Tutorial). This Registry works fine and pushed images are shown in the tree.

@Dezleung So you're saying one subscription worked for you, but not another? I'm not familiar with "Azure concierge subscription". Is that a specific type of subscription?

**Comment by Dezleung** [comment]
@EricJizbaMSFT It is a sandbox subscription for  hand on courses from Azure Learning site. [https://docs.microsoft.com/en-us/learn/modules/run-docker-with-azure-container-instances/](url)

This sandbox subscription is visible by the Azure App Service Plugin in VSCode. Once selected, Dockor Extension Plug can see it too.

**Comment by EricJizbaMSFT** [comment]
@Dezleung perhaps you have more strict permissions on the "VS entreprise MPN subscription"? Aka not permissions to list the catalog?

As a workaround, you could try attaching the registry in the "Private Registries" section using the login url (with `https://` prepended) and the admin username/password
