### ISSUE TITLE
An error occurs while signing in 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#981]
**OS**: All
**Build Version**:  [20190609.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6682)

**Repro Step:**
1. Make sure you have install Azure Account extension and there is no other azure extensions.
2. F1 --> Type and select "Azure : Sign In".

**Expect:**
Succeed to sign in without any error.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/59262743-6dee3980-8c72-11e9-9c9d-e1259ac7af1b.png)
![image](https://user-images.githubusercontent.com/34729092/59262755-70509380-8c72-11e9-804f-ac661d021fd4.png)
Then succeed to sign in with Device Code, 
But it is a bit un-friendly to pop up an error.

**Comment by EricJizbaMSFT** [comment]
Closing as external. If this consistently repros for you, you're welcome to file an issue on the Azure Account extension here: https://github.com/Microsoft/vscode-azure-account/issues, but this might even be external for that, too
