### ISSUE TITLE
[Suggestion] Remove the action "Delete Image" for Private Registry

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#982]
**OS**: All
**Build Version**:  [20190609.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6682)

**Repro Steps:**
1. Set up a private local registry by "docker run -d --rm --name noAuthRegistry -p 5100:5000 registry".
2. Connect it with http://localhost:5100 URL and empty username.
3. Pull an image at least to it.
4. Select "Delete Image..."  from the image context menu.
5. Select "Delete" when prompting.

**Expect:**
Succeed to delete the image.

**Actual:**
Pop up an error "The operation is unsupported.".
![image](https://user-images.githubusercontent.com/34729092/59263472-b2c6a000-8c73-11e9-8f54-ce9c9194f8f6.png)

**Suggestion:**
Remove the action "Delete Image".

**Comment by EricJizbaMSFT** [comment]
@v-dantch that error is specific to a _local_ registry, not a _private_ registry. In other words, that error is coming directly from `http://localhost:5100`.

For example, you could try connecting an Azure registry as a private registry like this:
1. In the portal, go to a registry -> Access Keys
1. Make sure "admin user" is enabled
1. Connect a private registry
1. Use the login server (like `emjacr2.azurecr.io`) with `https://` as a prefix
1. Use the username and password from the portal

Try to delete image. It should work.

**Comment by v-dantch** [comment]
Hi Eric, got it.  Thanks for your share.
And this issue does not repro when connecting an Azure registry as a private registry.

**Comment by EricJizbaMSFT** [comment]
Closing as external since the error came from the local registry
