### ISSUE TITLE
Docker-compose is not recognized as an internal/external command but works from normal command prompt

### ISSUE THREAD

**Issue by mattwC137** [microsoft/vscode-docker#987]
Docker-compose works fine from a regular command prompt but the compose commands do not work from either F1 or context menu of a .yml file.  

At a regular command prompt -version returns 1.23.2, build 1110ad01.

I've tried the recommendations in #270.  There are no errors in the console and a hard reinstall via Developer: reinstall extension does not change the condition.  I've also tried previous versions with no luck.

**Comment by mattwC137** [comment]
More information regarding this:  The commands were working fine a few days ago.  I have since tried reinstalling Docker and reinstalling the extensions with no luck.  I am able to run this docker commands from a regular terminal fine and the containers show running in the extension just fine.  

I am still unable to use any docker commands from VS code.

**Comment by EricJizbaMSFT** [comment]
@mattwC137 a few questions:
1. Can you be more explicit when you say "commands do not work"? Are you getting the same exact error as #270 like "docker is not recognized as an internal or external command"?
1. What OS are you on?
1. What is your [default terminal](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration)?

**Comment by mattwC137** [comment]
1. Yes, "xxxxx is not recognized as an internal or external command" is the error message for any Docker extension commands (ie. build, compose up, down, reset, etc.) Although, as I mentioned in the second post, if I run the commands from a regular cmd prompt, they work and the containers show that they're running from within VS Code so my guess is that the extension is loaded and functioning properly.  
2. Windows 10 Pro
3. Default shell is cmd prompt.  Although whenever I issue a command such as Compose Up, it will create a Docker Compose 'shell' which is basically just the cmd prompt with the current Python environment I have setup for my open folder (Flask application).  

From a regular command prompt if I type PATH, I see the entire system PATH that is configured on m machine.  If I type, PATH from the integrated terminal (cmd prompt created from VS Code Docker Compose command), the PATH is (null).  I am not sure how this worked before or what exactly broke it but at one point I did have Docker installed under another account on my machine.

**Comment by EricJizbaMSFT** [comment]
Maybe the Python environment is messing with your PATH? Try opening a workspace in VS Code without a python environment and see if PATH in the terminal still outputs as (null)

As a workaround you might want to try leveraging the setting `terminal.integrated.env.windows`

**Comment by mattwC137** [comment]
Thank you!!

For some reason, this setting was configured in the settings.json and the PATH was empty.  I'm not sure how it was added there or by what extension but by removing the setting with the empty PATH it (obviously) started working again!

"terminal.integrated.env.windows": {
	    "PATH": "",
    }

**Comment by EricJizbaMSFT** [comment]
Awesome - glad it works now!
