### ISSUE TITLE
investigate dockerfile language server

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#99]
investigate using https://github.com/rcjsuen/dockerfile-language-server-nodejs as the language server for the extension.

happy for a PR too!

**Comment by rcjsuen** [comment]
Thank you for your interest in my language server, @chrisdias. I have opened #100 for you and anyone else who is interested in the server to (hopefully) easily test it out.

While I feel that the server is already capable of a nice handful of things, there are still many more features and/or tiny things that could be done to enrich the editing experience of a Dockerfile.

I look forward to hearing the vscode-docker community's feedback. Thank you! :)
