### ISSUE TITLE
Error when opening yaml

### ISSUE THREAD

**Issue by aneel-sigsci** [microsoft/vscode-docker#994]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: docker.languageclient.activate
Error type: Error
Error Message: The language client requires VS Code version ^1.26 but received version 1.25.1

Version: 0.5.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@aneel-sigsci can you try updating VS Code to at least version 1.26?

**Comment by aneel-sigsci** [comment]
Looks like there are no new updates. I'm on Version 1.25.1 (1.25.1)

**Comment by EricJizbaMSFT** [comment]
@aneel-sigsci the current VS Code version is 1.35.1: https://code.visualstudio.com/updates/v1_35

(1.25.1 is actually a year old at this point https://code.visualstudio.com/updates/v1_25)


You could try googling your update problem or worst-case uninstall and re-install VS Code

**Comment by aneel-sigsci** [comment]
Oh my bad, thank you for that. I updated to 1.35.1. Thanks!
