### ISSUE TITLE
primer archivo

### ISSUE THREAD

**Issue by JOSELMARRUFOM1** [microsoft/vscode-docker#995]
Repro steps:

1.
2.

Action: vscode-docker.dockerHubLogin
Error type: i
Error Message: {"detail":"Incorrect authentication credentials."}

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
new i extension.bundle.js:157:643505
$.callback extension.bundle.js:157:642354
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:187:18281
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:187:17123
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@JOSELMARRUFOM1 please add repro steps to this issue

As an aside, https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders
