### ISSUE TITLE
docker error vs code

### ISSUE THREAD

**Issue by stosc** [microsoft/vscode-docker#996]
Repro steps:

1.
2.

Action: vscode-docker.connectCustomRegistry
Error type: ECONNRESET
Error Message: socket hang up

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:157:643276
$.callback extension.bundle.js:157:641962
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:157:641408
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:187:5468
$.emit events.js:182:13
$.module.exports.$.onRequestError extension.bundle.js:187:14523
ClientRequest.emit events.js:187:15
Socket.socketOnEnd _http_client.js:416:9
Socket.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@stosc please add repro steps to this issue

As an aside, https://github.com/microsoft/vscode-docker/pull/966 might've improved this experience - you're welcome to follow these instructions to try the latest build from master: https://aka.ms/azCodeInsiders

**Comment by mdemoret-nv** [comment]
Just ran into this issue myself when trying to add a private repository. Hardly any information is given in the window about the error. My repro steps:

1. Right click on "Private Repositories"
1. Select "Connect to a Private Repository (Preview)"
1. Enter URL for the registry
   1. `<Entered URL for our private Gitlab regsistry>`
2. Enter username
   1. `<Entered Username>`
1. Enter password
   1. `<Entered Password>`

Immediately the error is show that says nothing more than `Error: socket hang up`

I have check that my login information works with `docker login` and that I am able to pull images. Looked around for more information in the logs but couldnt find anything. 

I will give the Preview a chance and see if that helps. Looks like a significant improvement over the current extension. Let me know if you have any more questions

**Comment by mdemoret-nv** [comment]
FYI, this still does not work in the Preview build. Instead I am getting a different error: `Error: getaddrinfo ENOTFOUND <Address of Registry>`

Is there any reason why a Gitlab docker registry wouldnt work? Also are registries that use a specific port supported? (i.e. `docker login subdomain.domain.com:5000`)

**Comment by EricJizbaMSFT** [comment]
Yeah you should be able to add a port. We only support basic auth registires right now. Does gitlab support basic auth or just OAuth? We're tracking the OAuth work here: https://github.com/microsoft/vscode-docker/issues/869

**Comment by mdemoret-nv** [comment]
Not 100% sure what authentication method its using. Is there a way to test/confirm?

It looks like Basic auth to me (simple username/password combo) instead of OAuth. In the past I have used `$oauthtoken` as the username when logging in with OAuth. Thats not the case in this situation.

**Comment by EricJizbaMSFT** [comment]
Just to make sure - when you enter the address in VS Code you need to include the protocol like **https://**subdomain.domain.com:5000. Were you doing that?

> Not 100% sure what authentication method its using. Is there a way to test/confirm?

I'm not familiar enough with gitlab to answer this. It's on the list to verify when we do #869

**Comment by mdemoret-nv** [comment]
Yes, I included the protocol. VS Code actually enforces this before you can press Enter.

I saw #869 earlier and am keeping track of the updates. I know I always hate this question but: Any idea on the timetable for that issue to be completed? 

Just looking for super rough estimate here (days, weeks, months, or years) to decide if I should wait or look at replicating the functionality on my own.

Thanks for the help.

**Comment by arjeeone** [comment]
I'm getting this exact error with  http://cloud.canister.io:5000  using basic authentication. Docker Login from the command line passing username and password works fine.

**Comment by EricJizbaMSFT** [comment]
@mdemoret-nv I have some good new and some mildly bad news for you.

The good news: I've just submitted two PRs to improve this area:
1. https://github.com/microsoft/vscode-docker/pull/1097: Generalize registry support to make it as easy as possible for the community to contribute more providers
1. https://github.com/microsoft/vscode-docker/pull/1098: Add GitLab support (mainly chosen as a test subject for my above work)

The mildly bad news is that I don't have any plans to add support for _self-hosted_ GitLab any time soon. We would love if you could help contribute! Honestly it might be a simple change based on my above PRs, but I just don't have the time to created a self-hosted instance, test it, etc.
